### ISSUE TITLE
jinja2 variable_start_string cannot be set

### ISSUE THREAD

**Issue by droe** [ansible/ansible#10031]
##### Issue Type:

Bug Report
##### Ansible Version:

At least >= 1.7, including latest `devel` branch
##### Environment:

N/A
##### Summary:

Ansible cannot template config files that need to preserve `{{` syntax (e.g. exim config), and there seems to be no workaround preserving the ability to template such files. Earlier versions had the ability to specify `variable_start_string` in the template, but that was removed without providing any alternative (cf. unresolved but closed #9491, #8347, #8101, #8040).

It would be great to leave at least one of the issue tickets pertaining to this problem open until an actual fix is committed, so people who are burnt by the inability of ansible templating such files have a ticket to see the current state.
##### Steps To Reproduce:

Take e.g. your typical production exim main configuration file containing copious amounts of `{{` and `}}` and try to deploy it using the template module. Add `#jinja2: variable_start_string: "[%", variable_end_string: "%]"` at the start of the templated exim config.
##### Expected Results:

Ansible should use `[%` for variable expansion and leave the `{{` exim syntax alone, while preserving the ability to use jinja2 features in the template.
##### Actual Results:

```
fatal: [example.net] => {'msg': "AnsibleError: file: .../templates/configure.j2, line number: 683, error: expected token 'end of print statement', got '{'", 'failed': True}
```

**Comment by sbocahu** [comment]
+1 !

**Comment by AlekSi** [comment]
+1

**Comment by bcoca** [comment]
works in current devel

**Comment by bcoca** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by bjne** [comment]
You could atleast point to a commit if you think this is solved. Unprofessional to just close
the issue!
