### ISSUE TITLE
"with_dict" attempts to eval a variable even if "when" return false

### ISSUE THREAD

**Issue by evgeny-goldin** [ansible/ansible#10047]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Ubuntu 14.04.1 LTS
##### Summary:

If task's "when" returns false - "with_dict" still evals the variable specified, failing if it's undefined.
##### Steps To Reproduce:

Save the following playbook as `"1.yaml"`:

```

---
- name:  test
  hosts: localhost
  tasks:
    - debug:     msg="{{ item.key }}:{{ item.value }}"
      with_dict: something
      when:      something is defined
```

and run it:

`ansible-playbook 1.yaml -c local`
##### Expected Results:

I expect the task to be skipped as "something" variable is not defined.
##### Actual Results:

Running task fails with `"with_dict expects a dict"`:

```
$ ansible-playbook 1.yaml -c local

PLAY [test] *******************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="{{ item.key }}:{{ item.value }}"] ***************************
fatal: [localhost] => with_dict expects a dict

FATAL: all hosts have already failed -- aborting
```

Modifying it to have a default value works, the task is skipped:

```

---
- name:  test
  hosts: localhost
  tasks:
    - debug:     msg="{{ item.key }}:{{ item.value }}"
      with_dict: something | default({})
      when:      something is defined
```

**Comment by evgeny-goldin** [comment]
Could it be iteration is eval-ed before "when"?

**Comment by sivel** [comment]
You are correct in you assessment. The iteration is run before the "when" statement for times when you want to evaluate an item in the loop.  Your use of "default" is correct

**Comment by evgeny-goldin** [comment]
So "when" in this case is not for the whole task but for internal loops. Not a bug (again)?

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- "when" is a conditional for each execution of a task, with_ creates a loop and the conditional is per iteration. Otherwise it would not be possible to make tasks conditionals on each item. As you already state in the ticket, adding a |default clause you get the result you wanted.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by jmenga** [comment]
One way to overcome this would be to wrap such tasks in a block with the "outer" block when conditional providing the ability to skip the task that includes the "inner" with_ loop.  

This however is not the current behaviour.
