### ISSUE TITLE
Fact caching slows down Ansible execution almost 5 times

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#10050]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
##### Environment:

Centos 6
##### Summary:

With fact caching enabled Ansible runs a few times slower than without it.
##### Steps To Reproduce:

I enabled fact caching via Redis adding the following lines in `ansible.cfg`:

```
fact_caching = redis
fact_caching_timeout = 86400
```

and installed Redis support for Python using pip. This works without a problem, but the problem is that whole Ansible started executing a few times slower than before.

With fact caching DISABLED:

```
$ time ansible-playbook -i hosts site.yml -t postgres -l pg-01 -C
...
real    0m15.762s
user    0m11.118s
sys     0m1.553s
```

With fact caching ENABLED:

```
$ time ansible-playbook -i hosts site.yml -t postgres -l pg-01 -C
...
real    1m8.195s
user    1m1.394s
sys     0m2.594s
```

The most interesting thing is that even tasks that are being skipped run extremely slow. Basically whole Ansible slows down.
##### Expected Results:

It should execute faster with fact caching, since it doesn't need to fetch facts from the host.
##### Actual Results:

It runs almost 5 times slower than without fact caching.

**Comment by bcoca** [comment]
what do you have gathering set to in ansible.cfg?

## 

Brian Coca

**Comment by kustodian** [comment]
`gathering = smart`

**Comment by jimi-c** [comment]
Hi @kustodian, we're going back through old issues and I found this.

Overall, I believe this is to be expected. Instead of fetching facts from memory, with the redis fact caching enabled you're now going over the network (even if the machine is local) which is an order of magnitude slower. Even if facts are not being gathered, the Ansible engine still has to go out and query the fact cache for variables to see if there are any there, and this is done per-task because some tasks can update those facts.

So, because of the above, we're going to go ahead and close this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
