### ISSUE TITLE
replace module does not obey follow=yes

### ISSUE THREAD

**Issue by bsd04** [ansible/ansible#10059]
Issue Type: Bug Report

Ansible Version:
ansible-1.8.2-1.el7.noarch, from epel repo.
ansible 1.8.2
  configured module search path = None

Environment:
OL7 3.8.13-55.1.2.el7uek.x86_64

Summary:
Replace module does not obey follow=yes.
Following snippet replaces /etc/sysconfig/grub symlink pointing to /etc/default/grub.

Steps To Reproduce:
    - name: Remove rhgb quiet
      replace: dest=/etc/sysconfig/grub regexp=' rhgb quiet' follow=yes

Expected Results:
Leave /etc/sysconfig/grub symlink in place and modify /etc/default/grub it points to.

Actual Results:
/etc/sysconfig/grub symlink is replaced by correctly modified /etc/default/grub file. The original /etc/default/grub file is left in place unmodified.

**Comment by abadger** [comment]
Thanks @sysadmin75!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
