### ISSUE TITLE
Asynchronous Actions and Polling does not honor remote_tmp

### ISSUE THREAD

**Issue by MartinNowack** [ansible/ansible#10054]
Issue Type:  “Bug Report”

Ansible Version: 1.8.2

Environment:

Running/Managing from Linux Ubuntu 14.04 

Summary:

Asynchronous Actions and Polling should save intermediate files as well in the directory provided by remote_tmp. But files get saved in $HOME/.ansible_async

Steps To Reproduce:
1. Execute async job

Expected Results:
Files should be in the directory provided by remote_tmp

Actual Results:
Intermediate files are in  $HOME/.ansible_async

**Comment by jimi-c** [comment]
Hi @MartinNowack, just going through old issues and found this. As of 2.1 at least (and I believe 2.0), async uses the same random temp directory all other modules use, so I'll go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by IOOOTAlan** [comment]
Seems like I'm having the same issue on Ansible-2.3.0.
I also opened a discussion as suggested by @jimi-c [here](https://groups.google.com/d/msg/ansible-project/OFNrnuXdxgI/nlUhqzuOBwAJ).

**Comment by jimi-c** [comment]
@IOOOTAlan if you have a reproducible example, please feel free to open an issue.

Thanks (and sorry for the late follow-up)!

**Comment by IOOOTAlan** [comment]
@jimi-c Done, I've created issue #28318.
Thanks!

**Comment by jimi-c** [comment]
Thanks!
