### ISSUE TITLE
Support SSH two factor authentication

### ISSUE THREAD

**Issue by Amoki** [ansible/ansible#10065]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8.2
##### Environment:

Ubuntu Server 14.04
##### Summary:

Be able to deploy on servers that use SSH with two factor authentication.

Tuto to enable two factor authentication with public key + Google Authenticator on the server : 
[http://www.justgohome.co.uk/blog/2013/07/better-two-factor-ssh-authentication-on-ubuntu.html](http://www.justgohome.co.uk/blog/2013/07/better-two-factor-ssh-authentication-on-ubuntu.html)
##### Expected Results:

ansible-playbook should ask the code of the two-factor-authentication as it does with the -k parameter for password authentication.
##### Actual Results:

ansible-playbook is stuck at ssh initialisation when the server asks the code.

**Comment by bauruine** [comment]
Hi
I've done some work on this https://github.com/ansible/ansible/pull/9480 Unfortunately it needs a patched sshpass (sshpass only looks for the Password: prompt and not for Verification Code:) I'm not a good programmer and failed to implement the sshpass functionality directly in python and therefore it won't get merged.

**Comment by jmMeessen** [comment]
I would also be interested in such feature. +1

**Comment by sankalp-mobolt** [comment]
Interest +1 :)

**Comment by sankalp-khare** [comment]
I'd welcome it too. +1

**Comment by Neamar** [comment]
+1 too :)

**Comment by Ehekatl** [comment]
+1

**Comment by pujan14** [comment]
+1

**Comment by oenpelli** [comment]
I don't see how this could work even if sshpass was modified. sshpass is effectively a wrapper around ssh which enters the password when requested and checks whether it is valid. But for something like google authenticator the magic number will change over time so you will not be able to preload it with a password. You would think this would apply to any 2FA scheme.

**Comment by amenonsen** [comment]
@oenpelli what #9480 does is to add an `--ask-otpcode` command-line option to ask for the OTP (analogous to `--ask-pass`), use `sshpass` to authenticate with it, and set `ControlPersist=10m`, which is basically crossing your fingers and hoping that the playbook won't take longer than that to finish so that you won't need a new OTP.

**Comment by xbeta** [comment]
+1

**Comment by espoal** [comment]
plus one

**Comment by sergakaibis** [comment]
+1

**Comment by alfonsodev** [comment]
Other option could be add support for git init and then pull with token, as described here  
https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

**Comment by ProgressiveAstronaut** [comment]
+1

**Comment by falc0nheart** [comment]
+1

**Comment by cjsheets** [comment]
+1

**Comment by vadimg** [comment]
+1

**Comment by awurster** [comment]
+1

**Comment by karattopp** [comment]
+1

**Comment by ceesvanegmond** [comment]
+1

**Comment by zacharya** [comment]
+1

**Comment by laapsaap** [comment]
+1

**Comment by artkrz** [comment]
+1

**Comment by ghost** [comment]
+1

optional:  2fa support with duo security. (https://www.duosecurity.com/)

**Comment by marcus-ahle** [comment]
+1

**Comment by memelet** [comment]
+1 for sure.

**Comment by ghost** [comment]
+1

**Comment by kiiwii** [comment]
+1

**Comment by psivesely** [comment]
+1

**Comment by antonysohal** [comment]
+1

**Comment by bhardin** [comment]
+1

**Comment by mxxcon** [comment]
Guys, please don't reply with `+1` but instead click on :+1: under the original message. That allows better sorting of issues based on votes.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. There is obviously quite a lot of interest in this feature, so we would appreciate it if someone would submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by brammittendorff-dd** [comment]
+1

**Comment by cake99** [comment]
+1

**Comment by anmolnagpal** [comment]
+1
