### ISSUE TITLE
create a set_global module

### ISSUE THREAD

**Issue by purduemike** [ansible/ansible#10063]
Can someone create a module for set_global?  It would work the same way as set_fact, except the variable is not pinned to a host.  The main purpose is to access the variable between playbooks.  The other option here is to make registered variables accessible between playbooks.

**Comment by bandesz** [comment]
+1

**Comment by srgvg** [comment]
+1

Small workaround for now: `set_fact` actually works almost globally, in the context of the play hosts, when combined with `run_once: true` (at least in v1)

So, if you can have a play targetting `hosts: all` and a `set_fact` with `run_once` set, the effect is global.

**Comment by janmejay** [comment]
+1

**Comment by alexschedrov** [comment]
+1

**Comment by ThomasSteinbach** [comment]
+1

**Comment by hkratz** [comment]
+1

**Comment by akostadinov** [comment]
@srvg , the `run_once` actually quiet makes sense to me (and works with 1.9.x). In fact why should anybody need anything more? You define the play to run on all hosts that need it but then have in tasks `run_once` when desired. Any use cases not covered by it? Thanks a lot for your helpful comment!

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
