### ISSUE TITLE
Error when using readlink filter: no filter named 'readlink'

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#10062]
##### Issue Type:

Documentation Report
##### Ansible Version:

```
ansible-playbook 1.8.2
  configured module search path = None
```
##### Summary:

The [Other Useful Filters](http://docs.ansible.com/playbooks_variables.html#other-useful-filters) section of the [Variables](http://docs.ansible.com/playbooks_variables.html) document page references a filter named `readlink`, but it doesn't seem to exist.
##### Steps To Reproduce:

Playbook that reproduces the issue

```
- hosts: localhost
  vars:
  - myfile: /tmp
  tasks:
  - debug: msg={{ myfile | readlink }}
```
##### Expected Results:

Expected output like this:

```
ok: [localhost] => {
    "msg": "/private/tmp"
}
```
##### Actual Results:

```
ERROR: template error while templating string: no filter named 'readlink'
```

Note that there is a filter in lib/ansible/runner/filter_plugins/core.py called [realpath](https://github.com/ansible/ansible/blob/cce87acfedaeca097bf6e84ea8618b226bd2d98d/lib/ansible/runner/filter_plugins/core.py#L324), so maybe it should be realpath instead of readlink?

**Comment by abadger** [comment]
Thanks for the bug report.  You appear to be correct that we want realpath, not readlink.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
