### ISSUE TITLE
`defaults/main.yml` overriding variables `include_vars:` in roles

### ISSUE THREAD

**Issue by bcomnes** [ansible/ansible#10077]
In `defaults/main.yml`:

``` yml

---
foo: bar
```

In `vars/Darwin.yml`:

``` yml

---
foo: baz
```

In `tasks/main.yml`:

``` yml
- name: include env specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
- debug: var=foo
```

Assume this is run on a Darwin machine we get 

``` yml
foo: bar
```

where I would expect to get `baz`.

The work around is to ditch the `defaults` folder and instead load it with a defaults file with   `with_first_found:`

Maybe I am doing something backwards here, but the `defaults` folder seem to take higher precedence over including variables selectively included in the task.

**Comment by philipwigg** [comment]
Hi,

I think I am experiencing this same issue whereby the default variables of a role are taking precedence over the ```include_vars``` in my playbook.

I have created a test case at https://github.com/postdata/ansible-variables-issue

I am fairly new to Ansible so it could well be me misunderstanding something.

Is it possible for someone to take a look at https://github.com/postdata/ansible-variables-issue and tell me if I'm doing something wrong or if it is indeed a bug?

**Comment by anthonysr** [comment]
I am unable to reproduce this issue in a test VM, switching Darwin for Ubuntu (with the vars file named Ubuntu.yml instead). It correctly prints the conditionally included value 'baz'. (ansible v1.9.1)

With respect to Phillip's comment, tasks in playbooks are executed after roles, not in the order you list sections in a playbook (which is rather annoying). Use a pre_tasks: https://docs.ansible.com/playbooks_roles.html

"Note, you are still allowed to list tasks, vars_files, and handlers “loose” in playbooks without using     roles, but roles are a good organizational feature and are highly recommended. If there are loose things in the playbook, **the roles are evaluated first**."

**Comment by bcomnes** [comment]
Ack, didn't list the ansible version this occurred on, my bad.  I think it was around 1.8.  I will try again on 1.9.1

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv test.yml 
1 plays in test.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [test : test : include env specific vars] **********************************
{'item': u'/root/testing/10077/roles/test/vars/Darwin.yml', 'ansible_facts': {u'foo': u'baz'}}
ok: [localhost] => {"msg": "All items completed", "changed": false, "results": [{"item": "/root/testing/10077/roles/test/vars/Darwin.yml", "ansible_facts": {"foo": "baz"}}]}
TASK [test : test : debug var=foo] **********************************************
ok: [localhost] => {
    "foo": "baz", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcomnes** [comment]
Woop!  Cool.
