### ISSUE TITLE
jinja: stuck in endless loop, 100% CPU usage

### ISSUE THREAD

**Issue by christophgysin** [ansible/ansible#10073]
My ansible configuration causes ansible to lock up, using 100%CPU.

I managed to reduce to problem to the following:

```
$ echo localhost > ansible.hosts
$ cat > test.yml << EOF

---
- hosts: localhost
  vars:
    test:
      foo: "{{ lookup('file', 'files-test/baz') }}"
      bar: "{{ lookup('file', 'files-test/baz2') }}"
EOF
$ mkdir files-test
$ echo foobar > files-test/baz
$ ansible-playbook -i ansible.hosts test.yml
^C
^C
^Z
[1]+  Stopped                 ansible-playbook -i ansible.hosts test.yml -v
$ kill %1
$ 
[1]+  Terminated              ansible-playbook -i ansible.hosts test.yml -v
```

It seems that the string 'files-test/baz' is parsed by jinja, which tries to resolve "test" as a variable, ending in an endless loop. If I rename the variable or the directory, it works as expected.

So while there is a simple workaround, this seems like a bug and took me a while to isolate. I'm not sure though if the problem is in jinja itself or in the way ansible is using it.

**Comment by janLo** [comment]
This issue is not limited to the file lookup. Its within [ansible.utils.listify_lookup_plugin_terms](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L1450) which gives the string to the template engine to get terms defined as

```
    with_items: some_list
```

This evaluates the term as template expression. If one of the expression parts is the key for the current yaml dict part it evaluate the lookup endless recursive.

V2 seems not to have this function. I've not tested if the bug is present there.

**Comment by janLo** [comment]
A simple but ugly hack is to double-quote the terms given to 

```
---
- hosts: localhost
  vars:
    test:
      foo: "{{ lookup('file', '\"files-test/baz\"') }}"
      bar: "{{ lookup('file', '\"files-test/baz2\"') }}"
```

A better solution is to do the template evaluation of the lookup term only when its called within a with_files context. This information can be provided with the `inject` variabe.

**Comment by janLo** [comment]
This PR fixes the Issue for me.

**Comment by janLo** [comment]
Its simple to reproduce the issue without having a endless recursion. Given the playbook:

```
- hosts: localhost
  vars:                                      
    foo: peng                                
    bar: "{{ lookup( 'file', 'foo' ) }}"
```

The upstream ansible 1.9 looks:

```
% ansible-playbook -i testhosts -v bugtest.yml
 [WARNING]: non fatal error while trying to template play variables: Failed to
template {{ lookup( 'file', 'foo' ) }}: could not locate file in lookup: peng


PLAY [localhost] ************************************************************** 

PLAY RECAP ******************************************************************** 

```

With the patch its:

```
% ansible-playbook -i testhosts -v bugtest.yml
 [WARNING]: non fatal error while trying to template play variables: Failed to
template {{ lookup( 'file', 'foo' ) }}: could not locate file in lookup: foo


PLAY [localhost] ************************************************************** 

PLAY RECAP ******************************************************************** 

```

The first complains that a file "peng" is missing, the second - as expected - that "foo" is missing.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# mkdir 10073
# cd 10073
# vi test.yml
# mkdir files-test
# echo foobar > files-test/baz
# ansible-playbook -vv test.yml 
1 plays in test.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
