### ISSUE TITLE
apt_key module - issue with url cert

### ISSUE THREAD

**Issue by tborealis** [ansible/ansible#10091]
Issue Type:

Bug Report

Ansible Version:

ansible 1.8.2

Environment:

Host: Fedora 21
Client: Debian 7.8

Summary:

`apt_key` module not using certificate available in `/etc/ssl/certs`

Steps To Reproduce:

``` yaml
- name: Add Duo packaging key
  apt_key: url=https://www.duosecurity.com/APT-GPG-KEY-DUO state=present
```

Expected Results:

Key downloaded and installed

Actual Results:

```
Failed to validate the SSL certificate for www.duosecurity.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
```

Additional Notes:

`wget` can download the file without issue. The root certificate is present in `/etc/ssl/certs` and Qualys SSL Labs shows no chain issues (https://www.ssllabs.com/ssltest/analyze.html?d=www.duosecurity.com&s=54.230.34.152). I have also tried downloading both the root certificate and the intermediate and putting them in `/etc/ansible` but this doesn't have any effect. I'm raising this issue here as the `get_url` code is in this repo. Let me know if you want any additional debug.

**Comment by apollocatlin** [comment]
I too am seeing this exact same issue with apt_key as mentioned above. Appears to be related to the cert concat issue seen in the apt_repository that seemed to be resolved in ansible 1.8.

I too am having no chain issues. Etc. Same errors. Just different website.

running ansible-playbook on localhost on Ubuntu hosts.

**Comment by drewblas** [comment]
I also have this same issue.  Mine is with "https://www.threatstack.com/APT-GPG-KEY-THREATSTACK"

I've found a few similarities:
- `get_url` also fails with these URLs, it's not just `apt_key`
- Both are CDN'ed by Cloudfront
- Both require SNI in order to function.  I suspect this is why it's not working.

Is it possible to get all commands (`get_url`, `apt_key`, etc) that use the python URL donwloader to work with SNI properly?

**Comment by phobologic** [comment]
Running into this issue as well while trying to get the GPG key at https://get.docker.io/gpg with the apt_key module.

**Comment by shaikhfaisal** [comment]
I had the same issue with ansible v1.8.2 when trying to download the key over ssl from https://www.postgresql.org/media/keys/ACCC4CF8.asc using the apt_key module.

Upgrading ansible to v1.8.4 fixed this issue for me.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). 

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by monokal** [comment]
How are you guys working around this in the meantime? Grabbing the key and having apt_key add it from local disk?

**Comment by phobologic** [comment]
Crazily enough this just started hitting me again.  I just made this change:

```
- name: get_docker repository key
  command: /usr/bin/curl https://get.docker.com/gpg | /usr/bin/apt-key add -
```

**Comment by monokal** [comment]
Thanks @phobologic. Yeah, same here. I think perhaps a change was made on Docker's end to the repo as apt_key was working fine for me a couple of days ago. I'm using command with a 'creates' to prevent duplicate runs for now. Not ideal but hopefully one Ansible 2.0 resolves.

**Comment by phobologic** [comment]
Yeah - actually, were you hitting get.docker.io or get.docker.com?  I just realized I was using get.docker.io, and it looks like it was re-directing.  Not sure if that was part of the problem.

That said, I'm still working with the curl/apt-key system now, this is my latest:

```
- name: get_docker repository key
  shell: /usr/bin/curl https://get.docker.com/gpg | /usr/bin/apt-key --keyring /etc/apt/trusted.gpg.d/docker.gpg add - creates=/etc/apt/trusted.gpg.d/docker.gpg
```

**Comment by monokal** [comment]
Thanks @phobologic. I'm using ".com". Below is my current work-around, using the shell module as suggested by the docs (because of the use of pipe).

``` yaml
- name: add_docker_apt_key
  shell: "/usr/bin/curl https://get.docker.com/gpg | /usr/bin/apt-key add -"
  args:
    creates: /root/.ansible_add_docker_apt_key_lock
  register: add_docker_apt_key

- name: add_docker_apt_key_lock
  when: add_docker_apt_key|success
  copy:
    content: ""
    dest:    /root/.ansible_add_docker_apt_key_lock
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
```
