### ISSUE TITLE
set()s from jinja are treated as strings

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#10098]
##### Issue Type:

Bug Reports
##### Ansible Version:

1.8.2
##### Environment:

NA
##### Summary:

Jinja expressions that output a set() aren't converted to lists, just left as strings. This looks related to https://github.com/ansible/ansible/issues/9622. builtin set filters like difference() don't really output sets most of the time, so this happens mostly with custom filters.

Looking around is seems like the result of the template isn't safe_eval()ed for sets, only dicts and lists.
##### Steps To Reproduce:

playbook:

```
---   
- hosts: localhost
  vars: 
# I'm using strings as lists to make difference() return a set instead of a list.
    l1: asd
    l2: sd
  tasks:
    - debug: msg="{{l1|difference(l2)}}"
    - debug: var=item                
      with_items: l1|difference(l2)
```
##### Expected Results:

```
TASK: [debug msg="{{l1|difference(l2)}}"] ************************************* 
ok: [localhost] => {
    "msg": "set(['a'])"
}

TASK: [debug var=item] ******************************************************** 
ok: [localhost] => (item=a) => {
    "item": "a",
    "var": {
        "item": "a"
    }
}
```
##### Actual Results:

```
TASK: [debug msg="{{l1|difference(l2)}}"] ************************************* 
ok: [localhost] => {
    "msg": "set(['a'])"
}

TASK: [debug var=item] ******************************************************** 
fatal: [localhost] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting

```

**Comment by jimi-c** [comment]
With the following version of your playbook, this works as expected:

<pre>
---   
- hosts: localhost
  gather_facts: no
  vars: 
    l1:
    - a
    - s
    - d
    - f
    l2:
    - s
    - d
  tasks:
    - debug: msg="{{l1|difference(l2)}}"
    - debug: msg="item is {{item}}"
      with_items: "{{l1|difference(l2)}}"
</pre>

The main two differences here are:
1) the vars are actual lists - this is important because the type is preserved.
2) the with_items value is clearly a variable, which helps the internal engine do the correct thing (otherwise it is interpreted as a single string item).

So, not quite sure if this is still a problem, as the engine is doing what I'd expect it to do, and trying to figure that out from the original example above is not quite that easy.

**Comment by hkariti** [comment]
I intentionally used strings and not lists, because the built in `difference` filter doesn't return a set when comparing lists. Looking at `filter_plugins/mathstuff.py` it seems that `difference` uses sets only when the two args are `Hashable`, which lists are not. In that case, it implements difference finding using lists.

Another way of forcing the use of a set is to create a custom filter that returns a set. In either case (difference on strings or custom filter), Ansible doesn't convert the returned value to a set or list internally and keeps it as a string.

**Comment by jimi-c** [comment]
@hkariti I believe this patch would address it:

<pre>
diff --git a/lib/ansible/template/__init__.py b/lib/ansible/template/__init__.py
index 8ce243f..23fc3f4 100644
--- a/lib/ansible/template/__init__.py
+++ b/lib/ansible/template/__init__.py
@@ -171,7 +171,7 @@ class Templar:
                     result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
 
                     # if this looks like a dictionary or list, convert it to such using the safe_eval method
-                    if (result.startswith("{") and not result.startswith(self.environment.variable_start_string)) or result.startswith("[") or result in ("True", "False"):
+                    if (result.startswith("{") and not result.startswith(self.environment.variable_start_string)) or result.startswith("[") or result.startswith("set(") or result in ("True", "False"):
                         eval_results = safe_eval(result, locals=self._available_variables, include_exceptions=True)
                         if eval_results[1] is None:
                             result = eval_results[0]
</pre>

**Comment by hkariti** [comment]
@jimi-c : thanks for looking into this. I tried the patch, and now an error isn't thrown, but I think `save_eval` doesn't really know what to do with sets.

Playbook:

```
vars:
  s1: "asdf"
  s2: "a"
tasks:
  - debug: msg="item is {{item}}"
    with_items: "{{s1|difference(s2)"
```

output:

```
TASK [debug msg=item is {{item}}] ***********************************************
{'msg': u"item is set([u's', u'd', u'f'])", 'verbose_always': True, 'item': u"set([u's', u'd', u'f'])"}
ok: [localhost]
```

Putting the difference into its own var yields the same result.

**Comment by jimi-c** [comment]
Hi @hkariti, looking back at old issues, and this appears to have been resolved in 2.0:

<pre>
# ansible-playbook --version
ansible-playbook 2.0.2.0 (stable-2.0 0df4bfe063) last updated 2016/04/18 12:04:17 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 38a38bbd03) last updated 2016/06/18 06:21:26 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 40acb516fd) last updated 2016/06/18 06:21:27 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
# ansible-playbook -vv 10098.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: 10098.yml ************************************************************
1 plays in 10098.yml
PLAY [localhost] ***************************************************************
TASK [debug] *******************************************************************
task path: /root/testing/10098.yml:9
ok: [localhost] => {
    "msg": "set([u'a', u'f'])"
}
TASK [debug] *******************************************************************
task path: /root/testing/10098.yml:10
ok: [localhost] => (item=set([u'a', u'f'])) => {
    "item": "set([u'a', u'f'])", 
    "msg": "item is set([u'a', u'f'])"
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcoca** [comment]
@hkariti  you are using filters for lists on strings, which 'kindofworks' because of python but this is not intended to handles strings, you have 2 options (depending on what you actually want).

To use it on the strings as elements, define them in a list:

```
vars:
    l1: 
         - asd
    l2: 
         - sd
```

The other option if you want to operate on the strings as lists:

```
   with_items: "{{(l1|difference(l2))|list}}"
```

**Comment by hkariti** [comment]
@bcoca I used strings in this example because it was a simple way to reproduce the bug. I actually don't remember my original use case (I worked around it 1.5 years ago...), but it was either `difference` returning a string and surprising me, or me creating a filter plugin and using a set because it made more sense than a list. Either way, Ansible treating sets as a string is very unexpected.

Also, having to manually convert the type from a built-in ansible filter plugin (difference) to a list because this filter returns a type that Ansible itself can't handle is.. kinda broken. The use of set in difference is by design too. From `difference`'s implementation:

```
    if isinstance(a,collections.Hashable) and isinstance(b,collections.Hashable):
        c = set(a) - set(b)
```
