### ISSUE TITLE
Subversion password shows in failure message

### ISSUE THREAD

**Issue by justintaft** [ansible/ansible#10101]
When using password="This is a test" and a checkout fails, following error message is shown

failed: [webserver -> localhost] => {"cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache --username testuser --password *******\* is a test' info /tmp/checkout/", "failed": true, "rc": 1}
stderr: svn: E155007: '/tmp/checkout' is not a working copy

**Comment by abadger** [comment]
Note -- the password obscuring we do is for convenience but cannot catch every password :-(  If you want to make sure passwords are not shown you need to use no_log for the task: http://docs.ansible.com/faq.html#how-do-i-keep-secret-data-in-my-playbook

That said, I'm going to take a look at the code and see if we can do better in this case but I won't know until I've had a chance to dive in.

**Comment by abadger** [comment]
Some notes for here:  The PR I just merged should fix this particular problem.  However, we discussed some of the implementation and decided that some of the places where passwords could show up (in particular, the stdout and stderr from commands that fail in a task) will not be hidden automatically.  So it's definitely recommended to use no_log on tasks that specify passwords in case the command itself prints out the password that was attempted for some reason. (or in case of bugs like this ;-)

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
