### ISSUE TITLE
Remote with_fileglob? IE: with_remote_fileglob

### ISSUE THREAD

**Issue by bcomnes** [ansible/ansible#10115]
So I just wrapped my head around `with_fileglob:` and now understand that it runs against the host running the play only.  In order to get a remote fileglob array, I will have to run shell commands on the remote host and loop against those results. 

My question is, will a `with_remote_fileglob:` ever get added or accepted as a PR?  Does something like this already exist?

**Comment by bcoca** [comment]
lookups, which is what all with_\* are, get executed on the master. To do
what you want that lookup would have to handle ssh (or other) connections
and that is a complexity we really do not want to add there.

It is simple enought to :

```
- shell: ls /path/*
  register: path_files

- othertask: path=/path/{{item}}
  with_items: path_files.stdout_lines
```

**Comment by bcomnes** [comment]
That is what I have been doing for now.

Would be be hard to write a lookups plugin that globs against the remote server and generates the path array that way contained to enable a simplified `with_remote_fileglob` interface?

**Comment by bcoca** [comment]
@bcomnes, no, tasks are used for remote machines, lookups are for local information to help those tasks. 

In the end, using a task or implementing with_remote_anything, the underlying actions would be exactly  the same, the difference is that lookups would need to become tasks to deal with connection, inventory, host health, errors, return values, etc and on top it would require strict grouping with the tasks you associate it with for the host.

Since we don't want to create a hidden/implied  way to execute tasks here I'm going to close this ticket.

**Comment by bcomnes** [comment]
Thanks for the info.  That seems fair.
