### ISSUE TITLE
 no test named 'equalto'

### ISSUE THREAD

**Issue by coderplay** [ansible/ansible#10123]
Here is the ansible code

```
- name: for debugging
  debug: msg="{% if 'a' is equalto('a') %} true {% else %} false {% endif %}"
#  debug: msg="{{ ansible_mounts|map(attribute='mount')|reject('equalto', '/') | list "
  tags:
    debug
```

the result showed

```
... template error while templating string: no test named 'equalto'

FATAL: all hosts have already failed -- aborting
```

OS: ubuntu 14.04
python:2.7
script how I installed ansible 

``` bash
$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible
$ sudo apt-get update
$ sudo apt-get install ansible
```

ansible version 

``` bash
$ ansible --version
ansible 1.8.2
  configured module search path = None
```

**Comment by sivel** [comment]
The `equalto` test is provided by Jinja 2.8, which is currently tagged as Dev and not yet released. The current stable jinja2 release is 2.7.

This is not an Ansible bug.

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- As @sivel posted above, this is not an Ansible issue

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by vhosakot** [comment]
`pip install --upgrade Jinja2` resolved this error for me.

**Comment by rmetzler** [comment]
I'm still on Ubuntu 14.04 and had the very same problem. My workaround was to use the Dockerfile and build an image, run it, and copy my ssh-key inside the container.

Inside I used
```
chown -R root:root /root/.ssh
eval `ssh-agent -s`
ssh-add
```
to add my SSH-Key to the agent and then I was able to setup my cluster.
