### ISSUE TITLE
UTF-8 chars in task name makes --step barf

### ISSUE THREAD

**Issue by gilou** [ansible/ansible#10126]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9 devel (fef435cc2a)
##### Environment:

Ubuntu 14.10
To clarify: env has those defined:
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR
##### Summary:

If you use an utf8 chars (say an accent) in a task name and use --step to run the playbook, it crashes when it tries to display it.
##### Steps To Reproduce:

Set-up a name for a task that includes an accent, and run the playbook with step.
test.yml

```
- hosts: vm
  gather_facts: no
  tasks:
    - name: Ansible déteste l'UTF-8
      debug: msg="Hey"
```

Command:
`ansible-playbook test.yml --step`
##### Expected Results:

Perform task: Ansible déteste l'UTF-8 (y/n/c):  y
...
`ok: [vm] => {
    "msg": "Hey"
}`
##### Actual Results:

```
 ___________
< PLAY [vm] >
 -----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


Traceback (most recent call last):
  File "/home/Technique/Code/ansible/bin/ansible-playbook", line 346, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/Technique/Code/ansible/bin/ansible-playbook", line 286, in main
    pb.run()
  File "/home/Technique/Code/ansible/lib/ansible/playbook/__init__.py", line 347, in run
    if not self._run_play(play):
  File "/home/Technique/Code/ansible/lib/ansible/playbook/__init__.py", line 740, in _run_play
    if not self._run_task(play, task, False):
  File "/home/Technique/Code/ansible/lib/ansible/playbook/__init__.py", line 474, in _run_task
    self.callbacks.on_task_start(template(play.basedir, name, task.module_vars, lookup_fatal=False, filter_fatal=False), is_handler)
  File "/home/Technique/Code/ansible/lib/ansible/callbacks.py", line 632, in on_task_start
    msg = ('Perform task: %s (y/n/c): ' % name).encode(sys.stdout.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)
```

**Comment by abadger** [comment]
tested, this works in the v2 tree.

**Comment by abadger** [comment]
Actually, on second look, --step isn't implemented on the v2 tree yet.  So we'll have to re-check once it's more complete.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by gilou** [comment]
works! thanks ;)
