### ISSUE TITLE
It would be nice to have ssh_path in ansible.cfg

### ISSUE THREAD

**Issue by dago** [ansible/ansible#10139]
I have a configuration where the system ssh in my path does not contain all the Control\* directives and OpenSSH is installed at a different location not in my path. It would be very convenient if I could configure something like

```
ssh_path = /opt/csw/bin/ssh
```

in `ansible.cfg`. As downstream packager this would also allow me to ship an example `ansible.cfg` together with the package and an OpenSSH dependency to get users a smooth start.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
