### ISSUE TITLE
Backup retention 

### ISSUE THREAD

**Issue by cmodijk** [ansible/ansible#10149]
We use the backup option of the template module to keep older versions of config files to possibly go back if necessary but the backup option keeps backup files and does not remove older versions of the files. Currently we implement a new method after every time we backup to cleanup older version but it would be cool to be able to specify the retention period or the retention count.

```
 - name:          Install config
   template:      src=./vsftpd.conf
                  dest=/etc/vsftpd/vsftpd.conf
                  backup=yes
   notify:        Restart vsftpd

 - name:          Cleanup old files
   shell:         find /etc/vsftpd/ -iname "vsftpd.conf.*@*~" -type f -mtime +7 -delete
   changed_when:  false
```

**Comment by lewiseason** [comment]
+1

I'm currently doing something very similar to keep the `n` most recent backups: (n=2)

``` shell
---
- name: bash_profile for root
  template: src=bash_profile dest=/root/.bash_profile owner=root group=root mode="600" backup=yes
  register: bash_profile

- name: clean bash_profile backups
  shell: find /root -maxdepth 1 -iname '.bash_profile.*@*~' -type f | sort | head -n-2 | xargs rm
  when: bash_profile.changed
```

**Comment by cmodijk** [comment]
Could someone point me in the right direction (file/code used by template) and some guides how i could run the unittests?

**Comment by Schroeffu** [comment]
+1

Same here, during runs already 50+ backup files generated here... Would love to see a retention=X feature.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by jimi-c** [comment]
Really, the backup system needs a major overhaul, I'll make a note of it to put it on the agenda for 2.3.

**Comment by inferiorhumanorgans** [comment]
So what's the status of this? Abandoned?

**Comment by urusha** [comment]
About workaround: in some cases `sort` doesn't work fine, so I use backup's modification time instead of name.  And `xargs -r` (GNU only) to skip empty lists. And `xargs -d '\n'`, `xargs -0` to allow spaces in names. And `tail -n+3` means keep 2 (3-1) last backups.
`shell: find /some/directory -maxdepth 1 -name "orig_filename.*@*~" -type f -print0 | xargs -0r ls -1t | tail -n+3 | xargs -rd '\n' rm`
