### ISSUE TITLE
Unable to read registered output of docker inspect --format=...

### ISSUE THREAD

**Issue by seschwar** [ansible/ansible#10156]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = /usr/share/ansible
```
##### Environment:

Debian unstable
##### Summary:

Trying to use the registed output of `docker inspect --format=... ...` results in a fatal error.

Interestingly enough this works with Ansible 1.7.2 but not with 1.8.2.  Also works when just using the output of `docker inspect ...` without the `--format` option.
##### Steps To Reproduce:

Use the following `playbook.yml`:

```
- hosts: localhost
  connection: local
  tasks:
    ## I know this task returns the information we inpect below
    ## in ansible_facts.docker_containers[0].  But to uncover
    ## the bug `docker inspect --format=...` will be used.
    - name: start test container
      docker:
        image: busybox
        name: sleep
        command: sleep 10
        volumes:
          - /srv
        state: running
    - name: read image hash of container
      command: docker inspect sleep
      register: inspect
    - name: read image hash of container
      command: docker inspect --format='{{ "{{" }}index . "Image"{{ "}}" }}' sleep
      register: image
    - name: read name of container
      command: docker inspect --format='{{ "{{" }}.Name{{ "}}" }}' sleep
      register: name
    - name: read directory of container volume
      command: docker inspect --format='{{ "{{" }}index .Volumes "/srv"{{ "}}" }}' sleep
      register: volume
    ## We can't us with_items on the variable names since the
    ## encountered FATALs will end the loop prematurely.
    - debug:
        var: "{{ i }}.stdout"
    - name: clean up test container
      docker:
        image: busybox
        name: sleep
        state: absent
```

Execute it on a host which has Docker installed and running:

```
for i in inspect image name volume; do
    ansible-playbook -e i=$i playbook.yml
done
```
##### Expected Results:
- `inspect.stdout` should contain the complete JSON output
- `image.stdout` should be the hash of the official `busybox` Docker image
- `name.stdout` should be `/sleep`
- `volume.stdout` should be something like `/var/lib/docker/vfs/dir/92fd93ceedababafb4d61615749e093dd170cae4f2f1ec092fc11159b6b0b7c5`
##### Actual Results:
- `inspect.stdout` correctly contains the complete JSON output with
- the debug task for `image.stdout` fails with: `fatal: [localhost] => template error while templating string: expected name or number`
- the debug task for `name.stdout` fails with: `fatal: [localhost] => template error while templating string: unexpected '.'`
- the debug task for `volume.stdout` fails with: `fatal: [localhost] => template error while templating string: expected token 'end of print statement', got 'string'`

**Comment by gimoh** [comment]
Just in case this helps anyone, a workaround for now is to use \ to escape:

```
- command: /usr/bin/docker inspect -f \{\{.NetworkSettings.IPAddress\}\} CONTAINER
  register: CONTAINER_ip
```

Thanks to [this post](https://www.mail-archive.com/ansible-project@googlegroups.com/msg07940.html)

**Comment by d-a-n** [comment]
I had to double escape the curly braces to get it working with ansible 1.9.1:

```
- command: docker inspect -f \\{\\{.NetworkSettings.IPAddress\\}\\} CONTAINER
  register: CONTAINER_ip
```

**Comment by syabro** [comment]
Same here. 1.9.2.

``` yaml
    - name: Get postgres IP
      command: docker inspect --format '{% raw %}{{ .NetworkSettings.IPAddress }}{% endraw %}' postgres
      register: postgres_ip_result
    - debug:
        var: "postgres_ip_result.stdout"
```

raises 

```
TASK: [Get postgres IP] *******************************************************
changed: [xxx.com]

TASK: [debug ] ****************************************************************
fatal: [xxx.com] => Failed to template {{postgres_ip_result.stdout}}: Failed to template docker inspect --format '{{ .NetworkSettings.IPAddress }}' postgres: template error while templating string: unexpected '.'
```

Escaping

``` yaml
    - name: Get postgres IP
      command: docker inspect --format '\{\{ .NetworkSettings.IPAddress \}\}' postgres
      register: postgres_ip_result
    - debug:
        var: "postgres_ip_result.stdout"
```

produces `\\{\\{ .NetworkSettings.IPAddress \\}\\}` instead of actual value

```
TASK: [Get postgres IP] *******************************************************
changed: [xxx.com]

TASK: [debug ] ****************************************************************
ok: [xxx.com] => {
    "var": {
        "postgres_ip_result.stdout": "\\{\\{ .NetworkSettings.IPAddress \\}\\}"
    }
}
```

Even tried double-escaping mentioned above

``` yaml
    - name: Get postgres IP
      command: docker inspect --format '\\{\\{ .NetworkSettings.IPAddress \\}\\}' postgres
      register: postgres_ip_result
    - debug:
        var: "postgres_ip_result.stdout"
```

produces `\\\\{\\\\{ .NetworkSettings.IPAddress \\\\}\\\\}` instead of actual value

```
TASK: [Get postgres IP] *******************************************************
changed: [xxx.com]

TASK: [debug ] ****************************************************************
ok: [xxx.com] => {
    "var": {
        "postgres_ip_result.stdout": "\\\\{\\\\{ .NetworkSettings.IPAddress \\\\}\\\\}"
    }
}
```

PS Downgraded back to 1.7.2

**Comment by zstarer** [comment]
same issue here, might work on something to make this easier today

**Comment by conrado** [comment]
for those of you trying to call `docker inspect` by hand, skip that and use either the **docker_containers** variable, which you magically get by running docker module and has the inspect info, or get the info from docker_facts module http://patg.net/ansible,docker/2014/07/10/ansible-docker-facts/

However, bug is still valid, there's no way to escape the double curly braces...

**Comment by metasim** [comment]
@conrado Do you know if ansible has to actually launch the container in the same session for the `docker_containers` variable to be created? I'm trying to get the IP of already running containers.

**Comment by conrado** [comment]
yes, I believe the docker_containers requires you to use the docker module at least once. I would recommend you try the docker_facts module instead.

**Comment by metasim** [comment]
I tried it but got an error I couldn't decode. Probably user error (I'm new to ansible). My workaround was to put the command in a separate script and use the `script:` action.

```
TASK: [Get facts about containers] ******************************************** 
failed: [foobar.com -> 127.0.0.1] => {"failed": true, "parsed": false}
BECOME-SUCCESS-tqntgkvuvygjbhhkwdixwebjtaktjrwv
Traceback (most recent call last):
  File "/Users/sfitch/.ansible/tmp/ansible-tmp-1432655835.16-255992250020353/docker_facts", line 1842, in <module>
    main()
  File "/Users/sfitch/.ansible/tmp/ansible-tmp-1432655835.16-255992250020353/docker_facts", line 237, in main
    manager.docker_facts(module)
  File "/Users/sfitch/.ansible/tmp/ansible-tmp-1432655835.16-255992250020353/docker_facts", line 192, in docker_facts
    containers = self.client.containers(all=True)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 440, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 106, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by ianbytchek** [comment]
Any news on this? I keep hitting dead ends all day marrying ansible with docker. Isn't that the hottest thing out there right now? Would be great to see more traction in that area.

**Comment by iby** [comment]
I just came across [the following](http://adeslade.co.uk/post/docker-inspect-inside-an-ansible-task-with-a-go-template), it works. The question is why? Can this be explained in the docs so everyone can make use of it? I assume the fact that this happening to docker is a tragic coincidence, so should be useful in general?

``` yml
- command: docker inspect -f \{\{' index .NetworkSettings.Ports "8080/tcp" 0 "HostPort" '\}\} jenkins
```

Basically the idea is to keep the escaped braces (`\{\{` and `\}\}`) out of any quotes, this must be some bash-related thing – my best guess.

**Comment by zstarer** [comment]
I wrote a python script to return the data I needed. @ianbytchek would you be interested in using it?

**Comment by zstarer** [comment]
oh, wow. that's a crazy workaround.

**Comment by iby** [comment]
@zstarer thanks man. No, I really prefer to keep things plain and simple without any scripts or crazy hacks. Appreciate the hand of help though. PS: updated the earlier comment with further findings.

**Comment by zstarer** [comment]
yep, understandable.. it quickly turned into a multi step process involving sysargs, an api call into /containers/$container_id/json, patience, etc.

**Comment by asans** [comment]
I took the non-cross-platform-compatible out and just used this to obtain the ip:

```
shell: 'docker inspect vpm-ui |grep IPAddress | cut -d \" -f 4'
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 10156.yml 
1 plays in 10156.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [start test container] *****************************************************
changed: [localhost] => {"changed": true, ...
TASK [read image hash of container] *********************************************
changed: [localhost] => {"changed": true, ...
TASK [read image hash of container] *********************************************
changed: [localhost] => {"changed": true, "end": "2015-07-04 00:16:25.530540", "stdout": "a9eb172552348a9a49180694790b33a1097f546456d041b6e82e4d7716ddb721", "cmd": ["docker", "inspect", "--format={{index . \"Image\"}}", "sleep"], "start": "2015-07-04 00:16:25.515320", "delta": "0:00:00.015220", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "docker inspect --format='{{index . \"Image\"}}' sleep"}}, "stdout_lines": ["a9eb172552348a9a49180694790b33a1097f546456d041b6e82e4d7716ddb721"], "warnings": []}
TASK [read name of container] ***************************************************
changed: [localhost] => {"changed": true, "end": "2015-07-04 00:16:25.730257", "stdout": "/sleep", "cmd": ["docker", "inspect", "--format={{.Name}}", "sleep"], "start": "2015-07-04 00:16:25.715526", "delta": "0:00:00.014731", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "docker inspect --format='{{.Name}}' sleep"}}, "stdout_lines": ["/sleep"], "warnings": []}
TASK [read directory of container volume] ***************************************
changed: [localhost] => {"changed": true, "end": "2015-07-04 00:16:25.934447", "stdout": "/var/lib/docker/vfs/dir/21dea598bd2b0c3fd787b057cec1dea209c2a44ff35e4f0de23edcfb2a0d9ce8", "cmd": ["docker", "inspect", "--format={{index .Volumes \"/srv\"}}", "sleep"], "start": "2015-07-04 00:16:25.919853", "delta": "0:00:00.014594", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "docker inspect --format='{{index .Volumes \"/srv\"}}' sleep"}}, "stdout_lines": ["/var/lib/docker/vfs/dir/21dea598bd2b0c3fd787b057cec1dea209c2a44ff35e4f0de23edcfb2a0d9ce8"], "warnings": []}
TASK [clean up test container] **************************************************
changed: [localhost] => {"changed": true, ...
PLAY RECAP **********************************************************************
localhost                  : ok=7    changed=6    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by michaljrk** [comment]
Hello @jimi-c , actually is still not working with ansible 2.0.0.2 , same result as before:

**playbook:**

```
- name: Verify {{ server_name }} container state
  command: docker inspect -f \{\{ .State.Status \}\} {{ server_name }}
  register: server_state
  tags:
    - app deploy

```

**Result**:

> FAILED! => {"changed": true, "cmd": ["docker", "inspect", "-f", "{{", ".State.Status", "}}", "cw-server-apns"], "delta": "0:00:00.043873", "end": "2016-05-02 17:41:39.381017", "failed": true, "rc": 1, "start": "2016-05-02 17:41:39.337144", "stderr": "Template parsing error: template: :1: unexpected unclosed action in command", "stdout": "", "stdout_lines": [], "warnings": []}
