### ISSUE TITLE
vault_password initialized to False instead of None by Playbook.__init__()

### ISSUE THREAD

**Issue by the-gigi** [ansible/ansible#10155]
The default value of vault_password should be None because in utils.**init**.py the expectation is that if you didn't specify a vault password it will be None

```
if vault.is_encrypted(data):
    # if the file is encrypted and no password was specified,
    # the decrypt call would throw an error, but we check first
    # since the decrypt function doesn't know the file name
    if vault_password is None:
        raise errors.AnsibleError("A vault password must be specified to decrypt %s" % path)
    data = vault.decrypt(data)
    show_content = False
```

But, the Playbook's .**init**() method initializes it to False, which causes the above check for None to be skipped and then the vault will try to decrypt with a None vault passowrd, which of course fails.

```
class PlayBook(object):
    def __init__(self,
        playbook         = None,
        ...
       vault_password   = False,
       force_handlers   = False,
    ):
```

**Comment by abadger** [comment]
Do you have a reproducer that triggers the behaviour?  I'd like to trace the code a bit more to see if the code should be changed to expect None in both places or to expect False in both places.

**Comment by the-gigi** [comment]
I have a complicated system where I generate inventory files, vars file and playbooks and then use the PlayBook class and the Runner to run the whole thing. The code that actually runs the playbook looks like:

```
    stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats,
                                                  verbose=utils.VERBOSITY)

    book = PlayBook(playbook,
                    inventory=self.inventory,
                    remote_user=self.user,
                    private_key_file=self.private_key_file,
                    # vault_password=self.vault_password,
                    stats=stats,
                    callbacks=playbook_cb,
                    runner_callbacks=runner_cb)
    result = book.run()
```

If you pass an actual vault password everything is fine (commented out in code above). If you don't then you end up with vault_password=False.

Probably the correct thing is to check for C.p (if there is ansible.cfg file) and use C.p.get('defaults', 'vault_password_file')

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0).The code where the vault_password is initialized in devel now sets it to `None` by default.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
