### ISSUE TITLE
Ansible EC2 external inventory script only finds jump-hosts not the internal servers.

### ISSUE THREAD

**Issue by snackycracky** [ansible/ansible#10179]
The 'Ansible EC2 external inventory script' does not detect internal hosts which are hidden behind a jumphost. 
The script is described here: http://docs.ansible.com/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script
it only finds the jump-hosts for each environment but not the internal servers with the command `./ec2.py --list`.

**Comment by Osterjour** [comment]
It works without a problem for me. I'm running the script inside the VPC itself and configured it to report back internal IPs and not the external ones. Maybe you need to configure the script accordingly (hosts behind a jump host don't have a external IP i.e.)?

**Comment by jonathanhle** [comment]
@snackycracky, if you're leaving ec2.ini at it's defaults, when you run ec2.py it'll look for "public_dns_name" across your EC2 instances either inside a VPC ("vpc_destination_variable") or outside of one ("destination_variable").  

I bet you're only giving your internal hosts behind the "jump server" private IPs within a VPC, so you'd need to change vpc_destination_variable to private_dns_name or private_ip_address.

Btw, you can setup multiple ec2.ini config files, if you need it to run differently depending on inventory needs, by just changing the ini config export var before a run, e.g.:
export EC2_INI_PATH=/etc/ansible/ec2_custom_something.ini
export EC2_INI_PATH=/etc/ansible/ec2_custom_something_else.ini

See: http://docs.pythonboto.org/en/latest/ref/ec2.html#module-boto.ec2.instance

@Osterjour - thanks for the info.  Super helpful!
![screenshot from 2015-03-13 11 31 04](https://cloud.githubusercontent.com/assets/3851599/6644835/7f0ffc00-c974-11e4-9373-7c24d12435cc.png)

**Comment by snackycracky** [comment]
sounds promising, will check it out asap :+1:

**Comment by mattfirtion** [comment]
I also reduced the cache_max_age for testing which was helpful.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi! Sorry for the late follow-up, but it appears the question here has been answered. As such, we're going to close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by thapakazi** [comment]
thanks :bowing_man: @jonathanhle && @mattfirtion
