### ISSUE TITLE
`unarchive` option `creates` check does not work correctly when using non equals sign syntax

### ISSUE THREAD

**Issue by follower** [ansible/ansible#10181]
##### Issue Type:

Bug Report
##### Ansible Version:

  ansible 1.8.2
      configured module search path = None
##### Environment:

Mac OS X 10.8 managing Debian 3.2
##### Summary:

The `creates` option of the `unarchive` action is supposed to check if the archive has already been unarchived on the destination--this can be used to prevent a large archive file from being copied, for example. This check does not work correctly if the "complex syntax" a.k.a non-inline (a.k.a. non-"equals sign") syntax is used.

When the non-"equals sign" syntax is used the check always results in the archive being copied even if the archive has been successfully extracted before. If the "equals sign" syntax is used then the check is performed correctly and the file is not copied unnecessarily.

This issue was reported to the mailing list later in the thread ["unarchive module: creates does not work"](https://groups.google.com/forum/#!msg/ansible-project/jwYFl8zw8Qw/5n1CqMML7A0J) but no issue was created in GitHub AFAICT.
##### Steps To Reproduce:

```
- name: Install files
  unarchive:
    src: files/my_large_archive.zip
    dest: /opt/my_dest/
    creates: /opt/my_dest/my_directory
    copy: yes
  sudo: yes
```
##### Expected Results:

After the playbook was successfully run once, the large archive file should not be copied to the destination again as the `/opt/my_dest/my_directory` directory from inside the archive now exists.
##### Actual Results:

The large archive file is always copied

The only way to avoid this is to use the inline/"equals sign" syntax, like so:

```
- name: Install files                                 
  unarchive: src=files/my_large_archive.zip dest=/opt/my_dest/ creates=/opt/my_dest/my_directory copy=yes                  
  sudo: yes
```

(As a side note I see #9538 includes the comment "Removing the 'creates:' line makes the issue go away, as does changing it to 'equals notation'" which makes me wonder if it's related?)

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv test.yml
1 plays in test.yml
PLAY: ***************************************************************************
TASK [unarchive dest=/tmp/10181 src=test.tar.gz copy=True creates=/tmp/10181/test] ***
changed: [localhost] => {"src": "/root/.ansible/tmp/ansible-tmp-1435984279.4-123321438720751/source", "group": "root", "uid": 0, "dest": "/tmp/10181", "changed": true, "extract_results": {"cmd": "/bin/gtar -xzf \"/root/.ansible/tmp/ansible-tmp-1435984279.4-123321438720751/source\"", "out": "", "err": "", "rc": 0}, "owner": "root", "state": "directory", "handler": "TgzArchive", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "mode": "0755", "invocation": {"module_name": "unarchive", "module_args": {"creates": "/tmp/10181/test", "src": "/root/.ansible/tmp/ansible-tmp-1435984279.4-123321438720751/source", "copy": true, "original_basename": "test.tar.gz", "dest": "/tmp/10181"}}, "gid": 0, "check_results": {"cmd": "/bin/gtar -C \"/tmp/10181\" --diff -zf \"/root/.ansible/tmp/ansible-tmp-1435984279.4-123321438720751/source\"", "out": "", "unarchived": false, "err": "/bin/gtar: test: Warning: Cannot stat: No such file or directory\n/bin/gtar: test/b: Warning: Cannot stat: No such file or directory\n/bin/gtar: test/a: Warning: Cannot stat: No such file or directory\n/bin/gtar: test/c: Warning: Cannot stat: No such file or directory\n", "rc": 1}, "size": 60}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
# ansible-playbook -vv test.yml
1 plays in test.yml
PLAY: ***************************************************************************
TASK [unarchive dest=/tmp/10181 src=test.tar.gz copy=True creates=/tmp/10181/test] ***
skipping: [localhost] => {"msg": "skipped, since /tmp/10181/test exists", "skipped": true, "changed": false}
PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
