### ISSUE TITLE
Filtering by vpc not applied to RDS instances in EC2 inventory script (ec2.py)

### ISSUE THREAD

**Issue by gmalouf** [ansible/ansible#10193]
To produce the issue, one needs an EC2 account with two or more vpcs setup and an RDS instance running in one of them.  Now use an instance filter in the ec2.ini file as follows to filter for all resources in the vpc group NOT containing the RDS instance.

instance_filters = vpc-id=vpc-myid

Besides getting all the resources in that vpc group, you will get meta-data and other information for any RDS instances in the other vpc group as well.

I'm unsure whether this is a bug in the ec2.py script or whether the vpc filtering feature is simply not supported by boto.

**Comment by cchurch** [comment]
It doesn't appear to be supported by the [API](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html), so the filtering for RDS would have to be implemented in the inventory script.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
