### ISSUE TITLE
debug requires a connection with a client when using winrm

### ISSUE THREAD

**Issue by t-v** [ansible/ansible#10197]
When I try to use a debug task in my role, I noticed that when I run it on a future linux machine (ssh connection) there is no problem. But when the machine is going to be a windows machine, so requiring winrm, this task hangs.

(ansible-1.8.2)exh345 ~/werner- rhevm ✔✖  > ansible testnixpxe -m debug -a "msg=testjen" -i platform/dev/inventory/ -vvvv
<testnixpxe> ESTABLISH CONNECTION FOR USER: exh345
testnixpxe | success >> {
    "msg": "testjen"
}

(ansible-1.8.2)exh345 ~/werner- rhevm ✔✖  > ansible testwinpxe -m debug -a "msg=testjen" -i platform/dev/inventory/ -vvvv
<testwinpxe> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO testwinpxe
<testwinpxe> WINRM CONNECT: transport=plaintext endpoint=https://testwinpxe:5986/wsman
<testwinpxe> WINRM CONNECTION ERROR: 500 WinRMTransport. [Errno 113] No route to host
<testwinpxe> WINRM CONNECT: transport=plaintext endpoint=http://testwinpxe:5986/wsman
<testwinpxe> WINRM CONNECTION ERROR: 500 WinRMTransport. [Errno 113] No route to host
testwinpxe | FAILED => 500 WinRMTransport. [Errno 113] No route to host

Sidenote, both of these machines don't exist yet. I just added them to the host file, so ansible knows them already. Because I create these machines with ansible (as a role on the to be created machine, but with delegates) and the moment that finishes, I want to continue with their required roles after the machine creation is completed.
## (ansible-1.8.2)exh345 ~/werner- rhevm ✔✖  > cat createvm.yml 
- hosts: all
  gather_facts: no
  vars_prompt:
  - name: passwd
    prompt: RHEVM Password
    private: yes
    pre_tasks:
  - fail: msg="You should limit the hosts you're running on."
    when: play_hosts == groups.all
    run_once: yes
    roles:
  - createvm
  - webserver

and I run this with:
(ansible-1.8.1)exh345 ~/werner- rhevm ✔✖  > ansible-playbook createvm.yml -l testwinpxe -i platform/dev/inventory/ 

which works perfect for a linux machine, so it creates the vm and runs the rest of the required roles.
But on the windows machine, it doesn't because of the required connection with the windows to output a debug msg.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible -m debug -c winrm -i badhost, all
badhost | SUCCESS => {
    "msg": "here we are", 
    "verbose_always": true, 
    "changed": false
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
