### ISSUE TITLE
Add md5sum/sha1sum option to get_url module, sha256sum is too slow

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#10216]
##### Issue Type:

Feature Idea
##### Ansible Version:

```
$ ansible --version
ansible 1.8.2
  configured module search path = None
```
##### Environment:

```
$ uname -a
Darwin 0x6D67 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```
##### Summary:

My playbooks spend a considerable amount of time calculating sha256 hashes. Would be great to have a `md5sum` option to speed up things while still playing the CRC check role.

**Comment by abadger** [comment]
hmm... I'm not opposed to faster hashes.  However, md5 isn't available on machines that are running in fips compliance mode.  I could see two possibilities:
- use sha1 as the faster alternative instead of md5.
- make a param that takes a string specifying a hash algorithm.  The user is responsible for selecting a hash that is available on the managed machines. something like the new hash filter: https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/filter_plugins/core.py#L282

The latter is probably the better option but is more work.

**Comment by sboulkour** [comment]
Hi,

I'd be interested by the sha1 algo, as it seems quite often used.
For instance, Elasticsearch and Kibana tarballs are shipped with sha1 hash : https://www.elastic.co/downloads/kibana

**Comment by mgcrea** [comment]
`sha1` would be great.

**Comment by muffl0n** [comment]
I already made a PR that supports all algorithms that hashlib is capable of: ansible/ansible-modules-core#141. Unfortunately it has not been merged yet.

**Comment by mgcrea** [comment]
Landed in https://github.com/ansible/ansible-modules-core/commit/4f0cf6d2ca0b46d289f631496af373fac02adf1c. Thanks!
