### ISSUE TITLE
Suggest renaming copy=no on unarchive to something else

### ISSUE THREAD

**Issue by JGailor** [ansible/ansible#10218]
After using Ansible for over a year, I still regularly get bitten by this.  I know there has been a few other issues with less than friendly people, but I wanted to open a civil discussion to create a path towards renaming this into something much more explicit.

Core problem:  I keep getting bitten by unarchive doing {local archive} -> {remote host}, instead of {remote archive} -> {remote host}.  copy=no sort of solves this problem but really requires you to carefully parse the documentation.  Based on some Googling other people regularly have this problem as well.

Question:  Is there better naming for this to make it explicit for people who want to unarchive files they download to machines, or should remote be the default?  "remote=yes" might also be a better naming convention than "copy=no"

**Comment by bcoca** [comment]
in other modules we use remote_src, it would be easy to replace copy (but
keep as alias for backwards compatibility).

**Comment by JGailor** [comment]
Sounds like a reasonable path forward to me

+1

**Comment by dagwieers** [comment]
We cannot use an alias if we revert the meaning and swap "yes" and "no". We could rename **copy: no** to **transfer: no**, but replace **copy: no** with **remote_src: yes** is not doable using aliases, but requires mutual exclusive options, glue-logic and documentation updates.

I don't mind implementing this as part of ansible/ansible-modules-core#3307 if we have consensus.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
