### ISSUE TITLE
Role variables containing other variables are not changed when the inner variables are set by extra-vars

### ISSUE THREAD

**Issue by benofbrown** [ansible/ansible#10251]
If I set a variable in a role which refers to another variable, then override the second variable with `--extra-vars` the original variable is unchanged.

Here's an example:

```
cat <<'EOF' > playbook

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  roles:
    - x

EOF

mkdir -p roles/x/{vars,tasks}

cat <<'EOF' > roles/x/vars/main.yml

---
var: 1
var2: "This is {{var}}"
EOF

cat <<'EOF' > roles/x/tasks/main.yml

---
- debug: var=var
- debug: var=var2
EOF

ansible-playbook playbook -e var=2
```

Expected output:

```
PLAY [127.0.0.1] ************************************************************** 

TASK: [x | debug var=var] ***************************************************** 
ok: [127.0.0.1] => {
    "var": "2"
}

TASK: [x | debug var=var2] **************************************************** 
ok: [127.0.0.1] => {
    "var2": "This is 2"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

Actual output:

```
PLAY [127.0.0.1] ************************************************************** 

TASK: [x | debug var=var] ***************************************************** 
ok: [127.0.0.1] => {
    "var": "2"
}

TASK: [x | debug var=var2] **************************************************** 
ok: [127.0.0.1] => {
    "var2": "This is 1"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

I am running ansible 1.8.2 from EPEL (ansible-1.8.2-3.el6.noarch).

**Comment by benofbrown** [comment]
Forgot to mention, if I move `roles/x/vars/main.yml` to `roles/x/defaults/main.yml` it works as expected. If this is a difference between using vars and defaults then it could do with being highlighted in the documentation.

**Comment by seuf** [comment]
Hi !
Same problem here since ansible-1.8.0
Tested with ansible  1.8.0, 1.8.2, 1.8.4 and 1.9.0.1 : same problem.
It works on ansible 1.7.2.

**Comment by kottenator** [comment]
This bug affects me too - v1.9.0.1
I understand that it's a bit "tricky" case, but still it's very popular case.

**Comment by jimi-c** [comment]
Just tested this on the v2 code base, and it does work as expected there:

<pre>
# ansible-playbook --version
ansible-playbook 2.0 (stable-1.9 99af3a8dc1) last updated 2015/04/23 10:32:08 (GMT -500)
  lib/ansible/modules/core: (stable-1.9 d0b95a4b9e) last updated 2015/04/23 10:26:32 (GMT -500)
  lib/ansible/modules/extras: (stable-1.9 c11f901389) last updated 2015/04/23 10:27:32 (GMT -500)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/17 10:11:45 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/04/23 10:18:34 (GMT -500)
  configured module search path = /usr/share/ansible
# ansible-playbook playbook -e var=2
PLAY [<no name specified>] ******************************************************
TASK [x : debug var=var] ********************************************************
ok: [127.0.0.1] => {
    "var": "2", 
    "changed": false
}
TASK [x : debug var=var2] *******************************************************
ok: [127.0.0.1] => {
    "changed": false, 
    "var2": "This is 2"
}
</pre>

Based on that, we'll go ahead and close this as we will be making that switch in the near future for the devel branch.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
@benofbrown to answer your question, yes there is a big difference in defaults and vars. Defaults are purposely held to the lowest level of variable precedence for situations like this, so I'd recommend continuing to use that instead of vars/ until v2 goes mainstream.

Thanks!
