### ISSUE TITLE
ansible-vault edit does not properly retain file permissions

### ISSUE THREAD

**Issue by flibby-jibbit** [ansible/ansible#10253]
Issue Type:

Bug Report

Ansible Version:

$ ansible --version
ansible 1.9 (devel 2da35a55a5) last updated 2015/02/16 10:38:29 (GMT -500)
  lib/ansible/modules/core: (detached HEAD aa6c73f11b) last updated 2015/02/16 10:38:34 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 2ffd7235e5) last updated 2015/02/16 10:38:34 (GMT -500)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/12 16:14:10 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 312d59061c) last updated 2015/02/12 16:14:15 (GMT -500)
  configured module search path = None

Environment:

OS is Mac OS X 10.10.2. The user account is managed in an Active Directory domain. Not managing any remote hosts.

Summary:

`ansible-vault edit` does not retain the permissions of the file.

Steps To Reproduce:

``` bash
$ vim some-file
$ ls -l
total 4.0K
-rw-r--r-- 1 pkoebbe staff 14 Feb 16 10:39 some-file

$ ansible-vault encrypt some-file
Vault password:
Confirm Vault password:
Encryption successful

$ ls -l
total 4.0K
-rw-r--r-- 1 pkoebbe staff 355 Feb 16 10:39 some-file

$ ansible-vault edit some-file
Vault password:
```

Expected Results:

``` bash
$ ls -l
total 4.0K
-rw-r--r-- 1 pkoebbe staff 355 Feb 16 10:39 some-file
```

Actual Results:

``` bash
$ ls -l
total 4.0K
-rw------- 1 pkoebbe FLOAK\Domain Users 355 Feb 16 10:39 some-file
```

**Comment by abadger** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- The usage of vault files is more like a secure opaque data store rather than encrypting a file.  In that model ansible is doing the right thing to make the file permissions more secure.
  
  Typically when we hear about someone wanting to save the file permissions of a vault file the desired outcome is to be able to save some passwords securely in valut then use those passwords in a configuration file that is placed on the target system.  The better way to achieve that in ansible is to store just the secure settings in variables defined in the vault file.  Then use the template module to construct the actual file using the variables from vault.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by flibby-jibbit** [comment]
Thanks for the response. Some thoughts:
- I might be persuaded to agree that going from 644 to 600 is acceptable, but it really should be configurable. I'm not sure ansible-vault should be telling me how to configure the permissions on my files.
- Even if changing the perms is right, why would the group be changed?
- Assuming changing the perms is correct, why didn't the `encrypt` command do it? If you notice, `encrypt` left the perms and group alone, but `edit` changed them.
