### ISSUE TITLE
bundle install --binstubs can't be set as async task [ruby]

### ISSUE THREAD

**Issue by quasipedia** [ansible/ansible#10252]
I have the following ansible include file:

``` yaml
- name: Install Omnibus gem
  gem: name=omnibus state=latest
  async: 1800
  poll: 3

- name: Installation the bundle necessary for running Omnibus
  command: bundle install --binstubs
  args:
    chdir: omnibus-fluentd
  async: 1800
  poll: 3
```

My problem is that **this run _exclusively_ if I remove the last two lines** (`async: 1800` and `poll:3`).  If I try to run it as-is, I get:

``` none
failed: [virgin7] => {"ansible_job_id": "421445526623.18514", "changed": true, "cmd": ["bundle", "install", "--binstubs"], "delta": "0:00:00.145549", "end": "2015-02-13 14:05:49.047085", "finished": 1, "rc": 10, "start": "2015-02-13 14:05:48.901536", "warnings": []}
stdout: Bundler::GemfileNotFound
<job 421445526623.18514> FAILED on virgin7
```

Have I stumbled on a bug, or is this the expected behaviour? In which case: why is so?

**Comment by jimi-c** [comment]
Hi @quasipedia, looking at older issues and was wondering if you're still seeing this occur on the most recent devel branch? There was quite a bit of reworking done to the async subsystem in the v2 rewrite.

**Comment by quasipedia** [comment]
@jimi-c - Sorry, I'm unable to test this again, as we eventually change our system entirely.

**Comment by jimi-c** [comment]
Ok, I'm going to go ahead and close this then, as we have not had any other reports of this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
