### ISSUE TITLE
SSH connection fails when ControlPath has spaces & dashes

### ISSUE THREAD

**Issue by robzienert** [ansible/ansible#10283]
When running Ansible from a slave job in Jenkins that has spaces & dashes in it, Ansible fails to correctly escape the job name while trying to connect to a remote host.

```
<10.10.78.154> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=<https://jenkins.xxx.com/job/Video%20-%20video-conn%20-%2002%20-%20Deploy/ws/$HOME/.ansible/cp/ansible-ssh-%h-%p-%r',> '-o', 'Port=22', '-o', 'IdentityFile=/xxx/xxx/xxx.pem', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=ubuntu', '-o', 'ConnectTimeout=10', '10.10.78.154', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1424294657.65-265327126865726 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1424294657.65-265327126865726 && echo $HOME/.ansible/tmp/ansible-tmp-1424294657.65-265327126865726'"]
previous known host file not found
fatal: [10.10.78.154] => SSH encountered an unknown error. The output was:
command-line line 0: garbage at end of line; "-".
```

I've confirmed this works as intended while running via command line, on the same box.

**Comment by robzienert** [comment]
Furthermore, and this may be an issue with Jenkins, the ControlPath doesn't appear to be correct since it's using a URL (this is using the Jenkins Java Web Start slave.jar; so communication is occurring over HTTPS right now).

Changing the Jenkins job to have no spaces still fails to work, but with: 

```
debug1: read_passphrase: can't open /dev/tty: No such device or address
Host key verification failed.
```

No passphrase is required for this key and I've already connected using this key before.

**Comment by jimi-c** [comment]
HI @robzienert, looking back through old issues, and taking a look at this I don't believe the problem is the spaces and/or dashes, but instead it looks like there are less-than and greater-than signs from the Jenkins https path:

<pre>
'ControlPath=<https://jenkins.xxx.com/job/Video%20-%20video-conn%20-%2002%20-%20Deploy/ws/$HOME/.ansible/cp/ansible-ssh-%h-%p-%r',> '-o',
</pre>

Looking at this, I would say your second comment is correct and Ansible is not at fault here. If you're still seeing this as a problem, I would look at your Jenkins configuration to see if you can resolve the issue there. As a result of this, I'm going to go ahead and close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
