### ISSUE TITLE
Ansible playbook fails when passed string containing a quote.

### ISSUE THREAD

**Issue by facetoe** [ansible/ansible#10287]
When I pass ansible-playbook a string containing quotes it fails with:

```
error parsing argument string .... try quoting the entire line
```

The string in question is contained in a dict that is passed directy to a custom module from my dynamic inventory. When printed from the shell it appears to be formatted correctly:

```
"attendence_body": "testing quote's" 
```

System info:

```
$ ansible --version
ansible 1.8.2
  configured module search path = /usr/share/ansible

$ uname -a
Linux facetoe 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 14.04.1 LTS
Release:  14.04
Codename: trusty
```

**Comment by bcoca** [comment]
for it to be proper json, quotes should be escaped:

```
"attendence_body": "testing quote\'s"
```

**Comment by facetoe** [comment]
@bcoca The playbook fails after it has consumed the json from the dynamic inventory. It fails when passed a dict:

```
sms_settings_dict="{{item['sms_settings']}}"
```

`sms_settings` is a dict here.

**Comment by bcoca** [comment]
can you provide the exact error and a minimal playbook that reproduces the issue?

**Comment by facetoe** [comment]
@bcoca Sure not a problem. 

test_inventory.py

```
    #!/usr/bin/env python
    import sys
    import json

    hosts = {'test_hosts': {
        'hosts': ['test_server'],
        'vars': {'test_quotes': {'quotes': "test quote's"},
                 'test_no_quotes': {'no_quotes': "Hello world"}
        }
    }
    }

    if sys.argv[1] == '--list':
        print(json.dumps(hosts, indent=2))
```

playbook.yml:

```
---
- hosts: test_server
  remote_user: root
  gather_facts: no

  tasks:
  - name: test no quotes
    ping: data="{{test_no_quotes}}"

  - name:
    ping: data="{{test_quotes}}"
```

Error:

```
    ansible-playbook playbook.yml -i test_inventory.py -v

    PLAY [test_server] ************************************************************ 

    TASK: [test no quotes] ******************************************************** 
    ok: [test_server] => {"changed": false, "ping": "{'no_quotes': 'Hello world'}"}

    TASK: [ping data="{{test_quotes}}"] ******************************************* 
    fatal: [test_server] => error parsing argument string 'data="{'quotes': "test quote's"}"', try quoting the entire line.

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/home/facetoe/playbook.retry

    test_server                : ok=1    changed=0    unreachable=1    failed=0   
```

Hope this helps.

**Comment by bcoca** [comment]
this is invalid json:

```
'vars': {'test_quotes': {'quotes': "test quote's"},
```

it should look like:

```
'vars': {'test_quotes': {'quotes': "test quote\'s"},
```

still, the error persists

**Comment by facetoe** [comment]
Yes I should have added that test case to the playbook. I've tried escaping the quotes with no luck.

**Comment by bcoca** [comment]
test in current devel, another related fix seems to have fixed it for me

**Comment by facetoe** [comment]
Unfortunately I'm still getting the error:

```
facetoe ~/IdeaProjects/python_stuff/ansible $
⇒ ansible-playbook --version
ansible-playbook 1.9 (devel a5ac9aafad) last updated 2015/03/02 10:11:38 (GMT +800)
  lib/ansible/modules/core: (detached HEAD 0c53b9033c) last updated 2015/03/02 10:11:54 (GMT +800)
  lib/ansible/modules/extras: (detached HEAD bb886a595d) last updated 2015/03/02 10:11:54 (GMT +800)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/19 21:02:41 (GMT +800)
  v2/ansible/modules/extras: (detached HEAD 650d740a3a) last updated 2015/03/02 10:11:54 (GMT +800)
  configured module search path = None
facetoe ~/IdeaProjects/python_stuff/ansible $
⇒ ansible --version
ansible 1.9 (devel a5ac9aafad) last updated 2015/03/02 10:11:38 (GMT +800)
  lib/ansible/modules/core: (detached HEAD 0c53b9033c) last updated 2015/03/02 10:11:54 (GMT +800)
  lib/ansible/modules/extras: (detached HEAD bb886a595d) last updated 2015/03/02 10:11:54 (GMT +800)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/19 21:02:41 (GMT +800)
  v2/ansible/modules/extras: (detached HEAD 650d740a3a) last updated 2015/03/02 10:11:54 (GMT +800)
  configured module search path = None
facetoe ~/IdeaProjects/python_stuff/ansible $
⇒ ansible-playbook playbook.yml -i test_inventory.py 

PLAY [test_server] ************************************************************ 

TASK: [test no quotes] ******************************************************** 
ok: [test_server]

TASK: [ping data="s{{test_quotes}}"] ****************************************** 
fatal: [test_server] => error parsing argument string 'data="s{u'quotes': u"test quote's"}"', try quoting the entire line.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/facetoe/playbook.retry

test_server                : ok=1    changed=0    unreachable=1    failed=0   
```

**Comment by facetoe** [comment]
Any update on this bug? It's causing us a lot of problems at the moment...

**Comment by tr3pan** [comment]
I had a problem with json script and single quotes. [Wikipedia](https://en.wikipedia.org/wiki/JSON#Data_portability_issues) again saved me. It says that you can use Unicode escapes. So i escaped my single quote `'` with `\u0027` it the json file and it worked.

And if you want to automate the stuff: 
`body='{{ lookup('template',my.json.j2)|replace("\'","\\u0027") }}'`
or
`body='{{ lookup('file',my.json)|replace("\'","\\u0027") }}'`
or 
whatever you think about.

**Comment by bcoca** [comment]
I cannot reproduce, unless its a different unicode quote and not the ascii/lower utf-8 quote

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv -i inventory.py playbook.yml -c local
1 plays in playbook.yml
PLAY: ***************************************************************************
TASK [test no quotes] ***********************************************************
ok: [test_server] => {"invocation": {"module_name": "ping", "module_args": {"data": {"no_quotes": "Hello world"}}}, "changed": false, "ping": {"no_quotes": "Hello world"}}
TASK [ping data={u'quotes': u"test quote's"}] ***********************************
ok: [test_server] => {"invocation": {"module_name": "ping", "module_args": {"data": {"quotes": "test quote's"}}}, "changed": false, "ping": {"quotes": "test quote's"}}
PLAY RECAP **********************************************************************
test_server                : ok=2    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
