### ISSUE TITLE
UTF-8 variables in inventory resulting in UnicodeDecodeError

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#10302]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
1.8.4
1.9 (devel)
2.0 (devel)
##### Environment:

Debian, Arch, CentOS:

$ echo $LANG
en_US.UTF-8
##### Summary:

UTF-8 variables in inventory resulting in UnicodeDecodeErrorused when used in template:

```
fatal: [localhost -> 127.0.0.1] => {'msg': "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)", 'failed': True}
```

Note: But same value in group_vars works!
##### Steps To Reproduce:

Demo repo: https://github.com/resmo/ansible-uft8-template-bug

```
$ cat inventory 
localhost   var_from_inventory="ä"
```

Run:

```
$ ansible-playbook test.yml -i inventory 
```
##### Actual Results:

```
ansible-playbook test.yml -i inventory 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [var_from_group_vars] *************************************************** 
ok: [localhost]

TASK: [var_from_inventory] **************************************************** 
fatal: [localhost] => {'msg': "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)", 'failed': True}
fatal: [localhost] => {'msg': "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/resmo/test.retry

localhost                  : ok=2    changed=0    unreachable=1    failed=0 
```

**Comment by abadger** [comment]
@resmo, did you test that #10426 fixed this in either devel or the stable-1.9 branch?

**Comment by resmo** [comment]
I can confirm this is fixed in devel. :+1:

**Comment by abadger** [comment]
Excellent.  It's pushed to the stable1.9 branch so it should be present in 1.9rc2 

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
