### ISSUE TITLE
UTF-8 characters in a vars_prompt variable resulting in a UnicodeDecodeError

### ISSUE THREAD

**Issue by xagaba** [ansible/ansible#10319]
If I use a vars_prompt variable that contains UTF-8 characters ('ñ')
- hosts: localhost
  vars_prompt:
  - name: "p_password"
    prompt: "Enter Password"
    private: yes
    tasks:
    - name: Change password
      lineinfile: dest=~/testpasswd line="password={{ p_password }}" state=present create=yes

I get 

fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/**init**.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 995, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 119, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/lib/pymodules/python2.7/ansible/utils/template.py", line 365, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

The same UTF-8 string ('ñ') in a vars: variable works fine.
- hosts: localhost
  vars:
    p_password: ñ
  tasks:
  - name: Change password
    lineinfile: dest=~/testpasswd line="password={{ p_password }}" state=present create=yes

**Comment by abadger** [comment]
Thanks for reporting!  That commit should fix things for you.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
