### ISSUE TITLE
jinja2 to_json filter fails for module

### ISSUE THREAD

**Issue by aikomastboom** [ansible/ansible#10321]
Hi,

`set_fact: volume_ids_json="{{ volume_ids | to_json }}"`

where volume_ids = ['abc','def','ghi']

fails with: 

`ERROR: an unexpected type error occurred. Error was Undefined is not JSON serializable`

I traced `Undefined` to the value of `a` in to_json

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/filter_plugins/core.py#L55 
- ansible (1.8.2)
- Jinja2 (2.7.3)
- Python 2.7.6
- Ubuntu 14.04

Do not ask me why.. but adding `str(a)` inside the function triggers `a` to be useful again.

```
def to_json(a, *args, **kw):
    ''' Convert the value to JSON '''
    str(a) # make sure a is an object dumps can work with.
    return json.dumps(a, *args, **kw)
```

**Comment by abadger** [comment]
Works in v2... In v1 it looks like the volume_ids variable isn't being passed along 

playbook/**init**.py::_run_task.py

``` python
        if task.role_name:
            name = '%s | %s' % (task.role_name, task.name)
        else:
            name = task.name

        self.callbacks.on_task_start(template(play.basedir, name, task.module_vars, lookup_fatal=False,              filter_fatal=False), is_handler)
```

With a playbook task like this:

``` python
      - debug: msg="{{volume_ids|to_json}}"
```

However, if I set the name in the playbook like this:

``` python
- name: test
  debug: msg="{{volume_ids|to_json}}"
```

then this works.

**Comment by aikomastboom** [comment]
Indeed, I can confirm.. adding

```
- name: "a name"
```

to the action, resolves this too

**Comment by abadger** [comment]
Okay, The above commit should fix the traceback for you.  There is a little more to the problem than just the traceback, the name fields of tasks seem to not be getting all the variables they need in order to be templated.  Since v2 drastically changes how variables are passed around inside of ansible we'll try to fix that portion of the problem in v2-only, not in v1.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
