### ISSUE TITLE
supervisorctl module falsely returns "ok" when called with insufficient permissions

### ISSUE THREAD

**Issue by sanear** [ansible/ansible#10336]
A task like the one below

```
- supervisorctl: name=myService state=restarted
```

Will result in an "ok" if called without sudo (assuming the supervisor daemon is run under root), though the service is not restarted.

**Comment by infinityandbian** [comment]
I'm seeing that regardless of whether or not sudo is true, `supervisorctl` module is not successfully updating and restarting. I haven't dug too deep into what's occurring here, but my quick fix is to manually reread, update and restart through `command` module.

**Comment by sbl** [comment]
> I haven't dug too deep into what's occurring here, but my quick fix is to manually reread, update and restart through command module.

I can just add that this is how we have to handle this as well. 

Also:
- updates to the file referenced in the `config` parameter aren't reflected (just gives an "ok")
- manually stopping a service and starting it also wasn't picked up

**Comment by bcoca** [comment]
so this is in wrong repo, also this PR https://github.com/ansible/ansible-modules-core/pull/1519 possibly fixes this by now correctly reporting on the return code

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
