### ISSUE TITLE
Regression issue when Parsing Arguments

### ISSUE THREAD

**Issue by coryrwagner** [ansible/ansible#10332]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
  configured module search path = /usr/share/ansible
##### Environment:

SLES 11 SP3
##### Summary:

This parsing error appeared after upgrading from ansible 1.8.2 to ansible 1.8.4. Removing the single quote within the prompt string resolves the issue.
##### Steps To Reproduce:

```
- name: remind user to update the ansible inventory file
  pause: prompt="IMPORTANT - add or update {{ name }} in Ansible's inventory file (/etc/ansible/hosts). {{   continue_msg }}"
```
##### Expected Results:

```
TASK: [remind user to update the ansible inventory file] **********************
[hostname]
IMPORTANT - add or update  in Ansible's inventory file (/etc/ansible/hosts) and Zenoss. Press Enter to continue:
```
##### Actual Results:

```
TASK: [remind user to update the ansible inventory file] **********************
fatal: [hostname] => Traceback (most recent call last):
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/runner/__init__.py", line 1027, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/runner/action_plugins/pause.py", line 91, in run
    (self.pause_type, self.duration_unit, self.seconds, self.prompt))
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/callbacks.py", line 181, in vv
    return verbose(msg, host=host, caplevel=1)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/callbacks.py", line 190, in verbose
    msg = utils.sanitize_output(msg)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/utils/__init__.py", line 1002, in sanitize_output
    parts = parse_kv(str)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/utils/__init__.py", line 793, in parse_kv
    vargs = split_args(args)
  File "/usr/local/lib64/python2.6/site-packages/ansible-1.8.4-py2.6.egg/ansible/module_utils/splitter.py", line 185, in split_args
    raise Exception("error while splitting arguments, either an unbalanced jinja2 block or quotes")
Exception: error while splitting arguments, either an unbalanced jinja2 block or quotes
```

**Comment by mattkaar** [comment]
I mentioned this to @defionscode as last night's Ansible DC meetup.

We're seeing the same issue with splitting arguments in 1.8.4 and devel. After testing intermediate versions, we isolated the problem to these two commits:

0af7e212a (release1.8.3 + release1.8.4)
4902c063 (devel)

Both introduce changes to jinja2 parsing returning the same error as above. Testing against their respective parent commits gives no error.

**Comment by abadger** [comment]
Thanks for reporting!  I found the issue in the log sanitization code to be a place where I assumed we were receiving key-value pairs but it was actually log messages with only a pseudo-regular format.  Enough free-form text was sneaking in to cause this issue.

The fix above essentially reverts the parsing of the message string to look for key-value paris to the old behaviour while keeping the new code's logic for obfuscating values that appear to contain passwords.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
