### ISSUE TITLE
ansible.cfg inline comments not working

### ISSUE THREAD

**Issue by carolinux** [ansible/ansible#10354]
Hello,
I had to change my remote_tmp directory because I was getting permission errors.
I changed it and the resulting line was:

 remote_tmp     = /tmp/ #$HOME/.ansible/tmp

I didn't know that commenting this out inline doesn't work (and there are other bash-type comments in the file, but as it happens, a cfg file doesn't exactly have bash syntax). Only when I deleted the part after the # did my new path work properly. My suggestion would be to add a warning about it. I can do a Pull Request for it if the maintainers think it's a good idea. 

Thanks!

**Comment by jimi-c** [comment]
Hi @carolinux, can you please give an example of a commented out line which doesn't work for you? We have many examples of lines commented out by default in the ansible.cfg we ship by default, so I'm not understanding how this is failing for you.

**Comment by carolinux** [comment]
This is exactly the commented line that didnt work for me 

```
remote_tmp = /tmp/ #$HOME/.ansible/tmp
```

Ansible thought that remote_tmp is the string " /tmp/ #$HOME/.ansible/tmp"

**Comment by jimi-c** [comment]
@carolinux per the ConfigParser docs (which we use for ansible.cfg files):

<pre>
Comments may appear on their own in an otherwise empty line, or may be entered in 
lines holding values or section names. In the latter case, they need to be preceded by 
a whitespace character to be recognized as a comment. (For backwards compatibility, 
only ; starts an inline comment, while # does not.)
</pre>

https://docs.python.org/2/library/configparser.html

So just change your `#` to a `;` and your inline comment should work.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by carolinux** [comment]
What I have been saying is that this particular ConfigParser  quirk is easy to miss for people using ansible, because the cfg file has a syntax that looks like, but isn't, actually, bash.

**Comment by tima** [comment]
ConfigParser is based on INI file syntax, not bash. Can't have it both ways.
