### ISSUE TITLE
String to vars not working anymore in Ansible v1.8.4

### ISSUE THREAD

**Issue by khuongdp** [ansible/ansible#10359]
Hi

In v1.7.2 it was possible to do this in a template:

```
​{{ vars['prefix_' + item.env + '_postfix' ] | get_something }}
```

But it's not working anymore in v.1.8.x.

The usecase:

myvars.yml (third party code):

```
prefix_main_postfix: some_value
```

master.yml:

```
  vars_files:
    - ~/myvars.yml
```

task:

```
- template: src=mytemplate.j2 ...
    with_items:
      - { env: 'main' }
      - { env: 'staging' }
```

mytemplate.j2:

```
​{{ vars['prefix_' + item.env + '_postfix' ] | get_something }}
```

error:

```
fatal: [127.0.0.1 -> 127.0.0.1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'prefix_main_postfix'", 'failed': True}
```

**Comment by itsmemattchung** [comment]
@khuongdp , I'm unable to reproduce. @bcoca , are you able to reproduce this issue?

(ansible1.8.4)Matts-MacBook-Pro-2:ansible_sandbox mattchung$ ansible --version
ansible 1.8.4

tasks/main.yml

```
- template: src=mytemplate.j2 dest=/tmp/{{ item.env }}
  with_items:
    - { env: 'main' }
```

templates/mytemplate.j2

```
{{ vars['prefix_' + item.env + '_postfix' ] | replace("prefix", "suffix") }}
```

```
(ansible1.8.4)Matts-MacBook-Pro-2:ansible_sandbox mattchung$ ansible-playbook 10359.yml -i hosts -u vagrant --private .vagrant/machines/default/virtualbox/private_key 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [stringtovars | template src=mytemplate.j2 dest=/tmp/{{ item.env }}] **** 
ok: [localhost] => (item={'env': 'main'})

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

(ansible1.8.4)Matts-MacBook-Pro-2:ansible_sandbox mattchung$ 
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat 10359.yml
- hosts: localhost
  gather_facts: no
  vars:
     testing: "bar"
     foo_bar: "hi"
  tasks:
  - debug: msg="{{vars['foo_' + testing] | replace('hi', 'hello')}}"
# ansible-playbook -vv 10359.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in test_vars.yml
PLAY: ***************************************************************************
TASK [debug msg=hello] **********************************************************
ok: [localhost] => {
    "msg": "hello", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
