### ISSUE TITLE
Broken checksumming with tcsh as login shell

### ISSUE THREAD

**Issue by lonerr** [ansible/ansible#10353]
It looks like commit 8150b14d8d4a1d49a80ff9b4ace660ba4d03141e broke dry-run execution for template module, as backslash escaping is unsupported feature in csh/tcsh shell family.

**Comment by pixie79** [comment]
This is also broken when using Pypy as the remove python - tested with 1.8.4 works fine if you downgrade to 1.8.2

**Comment by abadger** [comment]
@pixie79 Please open a separate ticket for your problem.  It's different than the csh one.  Also note that I was unable to reproduce the pypy issue here.  So we'll need a lot more information about how you have things setup.  Where is pypy located (You said in the user's home dir on IRC).  Is that path on the user's PATH?  Are you using ansible_python_interpreter?  and anything else you can think of for us to reproduce.

**Comment by abadger** [comment]
@lonerr can you give more information about what behaviour you're seeing and how to reproduce it?  I see that --check is reporting that the file will be changed when it won't be but I'm not sure if that's the sole problem you're seeing or not.

**Comment by lonerr** [comment]
@abadger, yes I see the same behaviour. Running ansible-playbook with '--check --diff' options shows the changes (yellow coloured output) without the actual diff lines.

**Comment by abadger** [comment]
Okay, I think this commit will fix the issue you're seeing.  If it doesn't, please open a new ticket or ping me on IRC.  Thanks!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by lonerr** [comment]
The problem disappeared now, thank you!
