### ISSUE TITLE
Failed to checksum remote file

### ISSUE THREAD

**Issue by Du-St** [ansible/ansible#10363]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
##### Environment:

CentOS7 on both.
##### Summary:

The error occured during processing template with the "\" (backslash) in the name of the file.
##### Steps To Reproduce:

I am trying to re-create systemd.mount file. Some characters (i.e. "-") in the filename must be escaped, which means replace them by sequence "\x2d". For the first time everything works as expected (file on the destination was succesfully created), but during the next run checksum failed.
##### Expected Results:

Repetitive runs w/o error.
##### Actual Results:

failed: [x.x.x.x] => (item=./etc/systemd/system/opt-my\x2dmountpoint.mount) => {"failed": true, "item": "./etc/systemd/system/opt-my\x2dmountpoint.mount"}
msg: failed to checksum remote file. Checksum error code: 0

**Comment by abadger** [comment]
Okay, in my testing, that commit fixes this issue.  Please open a new issue or ping me on IRC if it's still broken.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by jasdeepsingh** [comment]
- We are experiencing this same issue with ansible 1.8.4 and CentOS7. We will attempt an upgrade or downgrade and see if that will fix this issue for us.

Just leaving this note here in case someone also experiences this issue.

**Comment by majidaldo** [comment]
latest v2
CoreOS (latest python interpreter installed)

**Comment by madhurranjan** [comment]
@majidaldo  I am facing the same issue with coreos when I set ansible_python_interpreter as a var.
ansible_python_interpreter: "PATH=/home/core/bin:$PATH python" . What is your setting that is causing this issue ?  The checksum error is 4. (Checksum error code: 4)

**Comment by bcoca** [comment]
@madhurranjan dont do that, just set it to /home/core/bin/python if that is where the interpreter is, trying to inherit path there might get you unexpected results

**Comment by majidaldo** [comment]
@madhurranjan yea error code 4. i've tried your setting and more directly, /path/to/python with two different pythons. both don't work. however, template works and i'm just using that to copy files. (template does not work if ansible_python_interpreter is wrong)

my problem is copying files.

**Comment by madhurranjan** [comment]
@bcoca  Thanks. That worked.
