### ISSUE TITLE
Provide list of current Linux capabilities

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#10360]
##### Issue Type:

Feature idea
##### Ansible Version:

Current development
##### Environment:

Linux environments, Docker, LXC, OpenVZ, virtual machines, containers.
##### Summary:

Ansible should provide a list of currently present Linux capabilities(7). This can be especially useful in a restricted environment, for example a Docker/LXC container, to check if certain actions are allowed before executing them. Examples:
- missing `CAP_SYS_TIME` means that we cannot change system clock, so installing `ntpd` is not needed;
- missing `CAP_NET_ADMIN` means that we cannot manage network interfaces or firewall, so tasks/roles related to these can be confidently skipped;
##### Steps To Reproduce:

Current capabilities can be easily checked with:

```
sudo /sbin/capsh --print
```

command, available from `libcap2-bin` package (on Debian-based systems). Here's a Bash script that parses the output of that command and returns JSON-formatted list of capabilities. A separate variable indicates if capabilities are enabled or not (full `root` access).

```
#!/bin/bash
output="{"
# Get current capabilities
line=$(capsh --print | grep -E '^Current:\s+=')
line=${line##* }

# '=ep' shows up on systems that don't have capabilities enabled
# and indicates root, unrestricted privileges
if [ "${line}" = "=ep" ]; then
    output="${output}\"enabled\": \"false\","
else
    output="${output}\"enabled\": \"true\","
fi

IFS=, caps=${line}
output="${output} \"list\": ["
first=1
for cap in ${caps} ; do
    [ -z "${first}" ] && output="${output}, "
    first=
    output="${output}\"${cap}\""
done
output="${output}]"
output="${output}}"IFS=

echo ${output}
```
##### Expected Results:

In Ansible facts, if `libcap2-bin` package is present on remote host, there should be a separate variable `ansible_system_capabilities_enforced`, which indicates that capabilities are enabled or disabled, and a list of current capabilities in a separate list, `ansible_system_capabilities`.
##### Actual Results:

Currently there's no such functionality present.

**Comment by mscherer** [comment]
So here is a quick fix, but I didn't test yet on any containers systems. I wonder if we shouldn't also list the capacity presents as well, on top of the one we are cosntrained. 

One another problem is that capsh do not seems to have a string value for each caps on system I tried ( ie, sometime, it would return "35" instead of cap_syslog. 

I wonder also if we should make the caps be uppercase or not.

And there is also the issue of portability, and the issue of a potential translation breaking parsing. ( ie, I suspect I should add a LC_ALL=C just to be sure ). 

Also, as we should do the work on v2 rather than v1, I put the code there only. it is quite easy to port to v1 if needed.

As i didn't test with a constrained system, I cannot be sure that the patch work fine there, so I would rather not have been merged now and as is.
