### ISSUE TITLE
synchronize module using wrong hosts from inventory

### ISSUE THREAD

**Issue by FlorentCoppint** [ansible/ansible#10368]
### Issue Type:

Bug Report
### Ansible Version:

1.8.4
### Environment:

Ansible on Ubuntu 14.10 managing Debian Wheezy hosts
### Summary:

The synchronize modules uses a "127.0.0.1" host from a group on which it does have to run on.
### Steps To Reproduce:

Inventory file:
[apidbdeploy]
192.168.0.1 number=1
[api]
#192.168.0.2 number=2
#192.168.0.3 number=3

[api-hosts:children]
apidbdeploy
api
[memcache-api]
127.0.0.1

Handler on "api-hosts".

Task:

```
- name: Deploy files

  synchronize: src={{ path }}/{{ item.src }} dest=/var/www/easyrsa/{{ item.dest }}
  with_items:
  - { src: var-file, dest: vars }
  - { src: pki-dir/, dest: pki/ }
```

Synchronize task will use "127.0.0.1" from "memcache-api" as destination host...
If I change 127.0.0.1 from memcache-api with my host (192.168.0.1), it works well...
### Expected Results:

```
TASK: [Deploy files] ********************************************************** 
`<127.0.0.1> 
<127.0.0.1> 
<127.0.0.1> u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/florent/.ansible/tmp/ansible-tmp-1425297435.34-258998633999383/synchronize; rm -rf /home/florent/.ansible/tmp/ansible-tmp-1425297435.34-258998633999383/ >/dev/null 2>&1']
changed: [192.168.0.1 -> 127.0.0.1] => (item={'dest': 'vars', 'src': 'var-file'}) => {"changed": true, "cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/florent/XXX/XXX-XXX/XXX-ansible/files/var-file\" \"root@192.168.0.1:/var/www/easyrsa/vars\"", "item": {"dest": "vars", "src": "var-file"}, "msg": "<f+++++++++ var-file\n", "rc": 0, "stdout_lines": ["<f+++++++++ var-file"]}
```

...
...`
### Actual Results:

```
TASK: [Deploy files] ********************************************************** 
`<127.0.0.1> 
<127.0.0.1> ConnectTimeout=10 PasswordAuthentication=no KbdInteractiveAuthentication=no User=root ControlPath=/home/florent/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto ControlPersist=60s
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ECDSA key fingerprint is c0:58:57:81:c5:06:fc:0a:b8:e7:33:16:16:4b:44:cf.
Are you sure you want to continue connecting (yes/no)? `
```

**Comment by abadger** [comment]
A lot has changed in the code of synchronize between 1.8.4 and 2.0.1 (the next release which is currently in the stable-2.0 branch).  This issue may have been fixed.  you can take a look at the test cases that I've been using to see if your usage falls under one of those: https://gist.github.com/abadger/0fc9e36a295979210698#file-sync-yml

or you can checkout the devel or stable-2.0 branch and check for yourself whether the issue has been resolved: http://docs.ansible.com/ansible/intro_installation.html#running-from-source

If it turns out that the issue has not been resolved, we'll need more information than presently provided.  A minimal playbook that reproduces the error is the best.  Barring that, the `hosts:` line of your play is what I'm missing to know how to attempt to reproduce your issue.

If we don't hear back regarding this issue we'll assume that the code in 2.0.x has resolved this.  Thanks!

**Comment by tima** [comment]
Submitter timeout. Recommend closure.
