### ISSUE TITLE
default vars aren't evaluated when used within include statement in a dependency role

### ISSUE THREAD

**Issue by DominikTo** [ansible/ansible#10375]
When requiring a dependency that uses a var (e.g. `path`) that has been defined in `./defaults/main.yml` (within the dependency) in an include statement, the var is not evaluated and instead the following error is returned. `debug: msg="{{ path }}"` evaluates the var correctly, so this seems to only affect includes.

```
ERROR: file could not read: /Users/foo/test/roles/dependency/tasks/{{ path }}/before.yml
```

**/roles/dependency/defaults/main.yml**

```

---
path: foo
```

**roles/dependency/tasks/main.yml**

```

---
- include: "{{ path }}/test.yml"
```

**roles/root/meta/main.yml**

```

---
dependencies:
  - { role: dependency }
```

When `path` is passed while requiring the dependency as follows, the var is correctly evaluated, so this seems to fail only when the default from `/roles/dependency/defaults/main.yml` should be used.

**roles/root/meta/main.yml**

```

---
dependencies:
  - { role: dependency, path: "foo" }
```

(Tested with: ansible 1.8.4 and discovered while testing #10374)

**Comment by varsy** [comment]
Indeed, I have the same issue:

```
ERROR: file could not read: /data/.../tasks/{{ component }}/app-undeploy.yml
```

Related code:

```
    - include: "tasks/{{ component }}/app-undeploy.yml"
```

Ansible version:

```
[root@a943da5497af data]# ansible-playbook --version
ansible-playbook 1.9 (devel ee469c2ab1) last updated 2015/01/15 03:18:53 (GMT +000)
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [dependency : dependency : include] ****************************************
included: foo/test.yml for localhost
TASK [dependency : dependency : debug msg=here i am in the include] *************
ok: [localhost] => {
    "msg": "here i am in the include", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
