### ISSUE TITLE
Strange behavior with accelerate mode  

### ISSUE THREAD

**Issue by sogft** [ansible/ansible#10407]
Hi,
we are facing a problem using accelerate mode on a PlayBook .
I particular we run the playbook from a Jenkins slave (single client) to two remote server. 
At the first run , all is work fine, the daemon is started and task executed. Also the following execution is ok. The problem coming when I run the PB after more of 2-3 hours, in this case the daemon on the remote server are still present and the PB logs are : 

TASK: [skel | Create folder] **********************************\* 
attempting connection to 172.31.10.10 via the accelerated port 5099
172.31.10.10: sending request for validate_user
172.31.10.10: waiting for validate_user response
172.31.10.10: in recv_data(), waiting for the header
172.31.10.10: received nothing, bailing out
Falling back to ssh to startup accelerated mode
attempting to start up the accelerate daemon...

Is seems that is not validate the user .  If I kill the daemon all is work fine again .

Please, can you help us with this problem ?

Thanks,
Marco.

**Comment by sogft** [comment]
I add some info found in remote /var/log/messages : 

In this case we start with a clean situation, no daemon present : 

Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: Invoked with timeout=300 ipv6=False debug=4 password=NOT_LOGGING_PASSWORD minutes=3 port=5099 multi_key=False 
Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: exiting pid 29716
Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: daemon pid 29717, writing /home/prod/.accelerate.pid
Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: daemonizing successful
Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: pid file written
Mar  9 11:19:45 md1-ss002-wik01 ansible-accelerate: serving!
.......
Mar  9 11:20:15 md1-ss002-wik01 ansible-accelerate: daemon idle for 30 seconds (timeout=180)
.......
Mar  9 11:20:45 md1-ss002-wik01 ansible-accelerate: daemon idle for 60 seconds (timeout=180)
.......
Mar  9 11:21:15 md1-ss002-wik01 ansible-accelerate: daemon idle for 90 seconds (timeout=180)
.......
Mar  9 11:21:45 md1-ss002-wik01 ansible-accelerate: daemon idle for 120 seconds (timeout=180)
......
Mar  9 11:22:15 md1-ss002-wik01 ansible-accelerate: daemon idle for 150 seconds (timeout=180)
.....
Mar  9 11:22:45 md1-ss002-wik01 ansible-accelerate: server has been idle longer than the timeout, shutting down

If I run now [root@md1-ss002-wik01 ~]# ps -auwx | grep python

```
 prod     29717  0.0  1.0 296096 11004 ?        Sl   11:19   0:00 /usr/bin/python    /home/prod/.ansible/tmp/ansible-tmp-1425896385.1-120528273122498/accelerate
 root     29926  0.0  0.0 103232   832 pts/1    S+   11:29   0:00 grep python
```

It seems that the problem is that the daemon not shutdown correctly. 

Any suggestions ?

**Comment by bsodmike** [comment]
Hey, I'm seeing the same issue above as well as this,

```
May  3 03:44:26 vagrant-ubuntu-vivid-64 ansible-accelerate: Invoked with timeout=300 ipv6=False debug=0 password=NOT_LOGGING_PASSWORD minutes=30 port=5099 multi_key=False
May  3 03:44:26 vagrant-ubuntu-vivid-64 ansible-accelerate: daemon pid 28189, writing /home/deploy/.accelerate.pid
May  3 03:44:26 vagrant-ubuntu-vivid-64 ansible-accelerate: daemonizing successful
May  3 03:44:27 vagrant-ubuntu-vivid-64 ansible-accelerate: exception caught, exiting accelerated mode: max # of attempts to serve reached#012Traceback (most recent call last):#012  File "/home/deploy/.ansible/tmp/ansible-tmp-1430624652.51-43688463438774/accelerate", line 2221, in daemonize#012Exception: max # of attempts to serve reached
```

First run is fine, after a while when I come back to re-strapping my changes (Vagrant), it seems to either timeout or reach this 'max # of attempts' state.

**Comment by bsodmike** [comment]
@sogft seems there's a timeout on it, why? At the moment I'm testing in Vagrant, so it's ok for me to cycle the VM; but in production, i'd want fireball to always be available.

**Comment by jimi-c** [comment]
Hi all, the issue here I believe is the fact that we time out keys after a shorter period of time than you are starting the daemon up. By default, the daemon will timeout after 30 minutes and keys are considered invalid if they are older than 2 hours (for safety reasons). So to work around this, simply set your accelerated mode daemon life for less than 2 hours and you shouldn't see any problems. If the daemon times out due to inactivity, it is restarted quickly and securely, with very little speed penalty overall.

Because of the above, we will be closing this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
One further note regarding accelerated mode: in my testing, SSH with ControlPersist combined with pipelining mode are just as fast as accelerated mode, FWIW.
