### ISSUE TITLE
Explicit package_dir in setup.py considered harmful

### ISSUE THREAD

**Issue by jhermann** [ansible/ansible#10437]
Consider this [command sequence to install the release candidate](https://github.com/jhermann/jhermann.github.io/wiki/Ansible#installing-a-pre-release-version).
When I don't do the `setup.py` fix, I get the import error (see below), else I don't.
Any reason you have the version with the explicit package name?

``` sh
$ ansible --version
Traceback (most recent call last):
  File "…/.venv/ansible/bin/ansible", line 7, in <module>
    execfile(__file__)
  File "…/bin/ansible", line 36, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
$ sed -i~ -r -e "s~'ansible': 'lib/ansible'~'': 'lib'~" setup.py
$ python setup.py develop -U
…
$ ansible --version
ansible 1.9.0 (detached HEAD bce4bb2ce2) last updated 2015/03/11 23:41:25 (GMT +200)
…
```

Also, a `test-requirements.txt` for `pip` would be helpful. If you agree, I can do a PR for both.

**Comment by abadger** [comment]
Change to setup.py Looks good.  I'll merge a PR for that.

test-requirements.txt I think would be good but let me CC: @jlaska to make sure that won't step on anything that he's planning.

**Comment by jhermann** [comment]
BTW, https://travis-ci.org/jhermann/ansible/builds/54041180

**Comment by abadger** [comment]
Reopening since there's still the question of test-requirements.txt for feedback from jlaska

**Comment by abadger** [comment]
Re: Travis:  Nice!

**Comment by jlaska** [comment]
@jhermann @abadger no complaints here, thanks for the fix!

**Comment by jhermann** [comment]
Hi… which still leaves the open question whether I should do another PR for the changes from 2cdc46d to tip @ https://github.com/jhermann/ansible/commits/devel.

This basically makes `hacking/env-setup` jobless (or it could be rewritten to use "normal" Python tooling, namely virtualenv + pip), and allows easy Travis integration.

**Comment by abadger** [comment]
@jhermann: @jlaska is working on a somewhat different approach for travis integration.  So for that, probably should hold off, see what he has when we merge it, and then see if there's any pieces that we should merge from what you have.

I will merge your test-requirements.txt now if you want to submit it though :-)

**Comment by jlaska** [comment]
@jhermann @abadger thanks!  Yeah, `test-requirements.txt` is a good thing and will help reduce duplication.  Thanks for that addition!  The `.travis.yml` should be running tests through `tox` on all supported python versions.  I have a working local copy, but also needed to make a few test adjustments ... and review.  I plan to post that for review soon-ish.

UPDATE: `tox` and `travis` support added in #10455

**Comment by abadger** [comment]
test-requirements.txt PR merged as well.  Thanks!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
