### ISSUE TITLE
ConfigureRemotingForAnsible.ps1 $CertValidityDays not hooked up

### ISSUE THREAD

**Issue by sonjz** [ansible/ansible#10439]
Small bug, but affecting people (like me) that are downloading this raw via within our playbooks:
https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

The ps1 param `$CertValidityDays` is collected, but never passed to `New-SelfSignedCertificate ... -ValidDays $CertValidityDays` on line 140 & 145, which keeps the value at the defaulted 365 days.

In my case, I never want to replace the cert for the life of the box.

**Comment by dagwieers** [comment]
@sonjz Thanks for reporting this. I just found this issue and promptly fixed it.

In case you didn't know, you can make edits to files directly from GitHub (so prior Git experience is not needed). That way you can contribute changes directly from the GitHub web interface, and often it's faster than writing an issue because you offer a PR that can be merged with a click.
