### ISSUE TITLE
replace error with strings inadvertently containing regexp group reference

### ISSUE THREAD

**Issue by horrorhead** [ansible/ansible#10444]
Issue Type:
Bug Report

Ansible Version:

$ ansible --version
ansible 1.8.2
  configured module search path = /usr/share/ansible

Environment:

```
$ cat /etc/redhat-release
CentOS release 6.6 (Final)
```

Summary:

When trying to replace a value in a file replace thinks I use a group reference which is not present. However I actually have a string that contains the text \8 which is escaped to \8 and therefore perceived by replace as a group reference. I understand why this happends and maybe it's just me doing things the wrong way but I just can't see what I should do differently.

Steps To Reproduce:

playbook: https://gist.github.com/horrorhead/691035576a0c79a42c33#file-reproduce_replace_error-yml
text file: https://gist.github.com/horrorhead/07f18c290500c1269452#file-replace-txt

Expected Results:

I had expected this to replace the line:
value=sometext
with:
value: sometext\8somemoretext

Actual Results:

The play fails with the following error:

```
Traceback (most recent call last):
  File "/home/SESYSansible/.ansible/tmp/ansible-tmp-1421996455.89-233197455275473/replace", line 1729, in <module>
    main()
  File "/home/SESYSansible/.ansible/tmp/ansible-tmp-1421996455.89-233197455275473/replace", line 143, in main
    result = re.subn(mre, params['replace'], contents, 0)
  File "/usr/lib64/python2.6/re.py", line 162, in subn
    return _compile(pattern, 0).subn(repl, string, count)
  File "/usr/lib64/python2.6/re.py", line 278, in filter
    return sre_parse.expand_template(template, match)
  File "/usr/lib64/python2.6/sre_parse.py", line 795, in expand_template
    raise error, "invalid group reference"
sre_constants.error: invalid group reference
```

**Comment by jimi-c** [comment]
Hi @horrorhead, the solution here is to use an extra set of backslashes in order to pass that escape through to the regex subn call. In your example:

<pre>
    - name: Set replacement string
      set_fact:
        replace_with: "sometext\\\\8somemoretext"
</pre>

^ This allows the playbook to run without errors, and the text is replaced as expected.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
