### ISSUE TITLE
Services not starting properly on CentOS6

### ISSUE THREAD

**Issue by wkielas** [ansible/ansible#10441]
Hello,

I'm writing a simple playbook helping with provisioning a node with Cloudera Manager on Centos6. I have the following directive in it:

```
- name: start cloudera scm db
  service: name=cloudera-scm-server-db state=started
```

However, it does not work as expected: the service doesn't get started. Every time I run Ansible, I get the following:

```
ok: [cdhmanager] => {"changed": false, "name": "cloudera-scm-server-db", "state": "started"}
```

After some digging, I found out that the service returns the following when I check it's status:

```
[root@ip-172-31-1-29 ~]# service cloudera-scm-server-db status
pg_ctl: no server running
[root@ip-172-31-1-29 ~]# echo $?
1
```

After some digging I got to https://github.com/ansible/ansible-modules-core/blob/devel/system/service.py#L573, which seems to explain why the service isn't getting started. I have the following questions:
- Why is the textual output parsed before the return code? It seems like a very unreliable way to check if a service is running, as the example above shows. Pretty much every service I've run into adheres to the LSB.
- In the LSB section, why is return code 69 checked? It does not appear in the specification linked in the comment.
- How do I get around it? Should I simply run `service cloudera-scm-server-db start` instead of using the service module, or is there a more elegant way?

**Comment by autotune** [comment]
Hey,

Just to make things a bit easier this can also be replicated without installing any additional third party services or repos in CentOS 6.5 by modifying the last line below:

[brian ~]$ grep -in "no server running" /etc/init.d/functions -B5
451-    if [ -f /var/lock/subsys/${lock_file} ]; then
452-        echo $"${base} dead but subsys locked"
453-        return 2
454-    fi
455-    # echo $"${base} is stopped"
456:    echo $"${base} no server running"

and trying to start something like httpd with the service module. You can actually specify a pattern like the following to match another output that would be shown with the process name in ps and get the service up and running again as a temporary workaround:

```
- name: ensure apache is running
  service: name=httpd state=started pattern="httpd"
```

This is all documented below:
http://docs.ansible.com/service_module.html

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
