### ISSUE TITLE
ansible ignores extra words in interpolated task

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#10451]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.4
##### Environment:

OSX
##### Summary:

Using extra vars on the command line causes values to be truncated if they contain spaces
##### Steps To Reproduce:

Run 
`ansible-playbook irc.yml -c local -e 'new_name="tom hanks"'` 

or 

`ansible-playbook -i host irc.yml -c local -e @var` 
where var simply contains `new_name: tom hanks`

where irc.yml is

```
- name: Demo extra vars
  hosts: localhost
  tasks:
     - debug: var={{new_name}}
```
##### Expected Results:

An error
##### Actual Results:

```
PLAY [Demo extra vars] ********************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug var={{new_name}}] ************************************************
ok: [localhost] => {
    "tom": "tom"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
The problem is that you need to quote your `{{ }}` such as:

```
- debug: var="{{new_name}}"
```

Without the quotes, the second word is a bare word not associated with `var`, the quotes prevent that issue.

**Comment by juliedavila** [comment]
Ah yep. Though I would still think it should error out versus truncating
and proceeding.

**Comment by bcoca** [comment]
var does not need {{ }} it is trying to resolve the var 'tom' in this case:

```
ansible -m debug -a "var=new_name" -e 'new_name="tom hanks"' localhost
localhost | success >> {
    "var": {
        "new_name": "tom hanks"
    }
}
```

**Comment by akuznecov** [comment]
Reproduced on 1.9

```
  vars:
    projects_root: "/home/xxxx/project"

  tasks:

    - name: "Clone repository"
      git: repo={{repo}}
           version={{branch}}
           dest={{projects_root}}/{{name}}
```

``

`» ansible-playbook -i hosts provision.yml -e 'repo=git@yyy.zzz.com:foo branch=master path=sites/all/modules/custom name="FirstWord SecondWord"'`

> TASK: [Clone repository] *****************************************************\* 
> failed: [example.com] => {"failed": true}
> msg: this module requires key=value arguments (['repo=git@yyy.zzz.com:foo', 'version=master', 'dest=/home/xxxx/project/FirstWord', 'SecondWord'])

**Comment by akuznecov** [comment]
wrapping `dest` value with quote marks solves my issue

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv -c local -e 'new_name="tom hanks"' 10451.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 10451.yml
PLAY: Demo extra vars ***********************************************************
TASK [debug var=new_name] *******************************************************
ok: [localhost] => {
    "new_name": "tom hanks", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
