### ISSUE TITLE
git clone with --connection=local creates bare repo, not normal checkout

### ISSUE THREAD

**Issue by jhartman86** [ansible/ansible#10456]
Using 1.8.4 in a vagrant machine, using the git module and trying to clone a repo, its creating a bare repo instead of checking out the source. Unable to make it checkout the repo normally unless --connection=local flag is removed. Anyone experiencing the same thing?

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
