### ISSUE TITLE
Password expiration notice causes host to fail, but task completes

### ISSUE THREAD

**Issue by swimlappy** [ansible/ansible#10494]
Hello,

We had a playbook fail this morning due to a Sudo password expiration notification.

"Your password will expire in 9 days"

Our Linux servers all use Samba joined to Active Directory to authenticate users.  The particular user who ran the playbook says that the actual tasks completed successfully, but the host failed, which caused the playbook to fail at the end of the task.

Has anyone ever encountered this before?.

Thanks,
Jay

**Comment by swimlappy** [comment]
Hello, this is still an issue for us, using Ansible 2.0.  Task and host failure when password expiration notice is displayed from Sudo.

Jay

**Comment by jctanner** [comment]
# Can You Help Us Out?

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket. We hope you understand as this is really valuable to us!.

Solving this is simple: open a new ticket and fill out the template.

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!
