### ISSUE TITLE
service status fails

### ISSUE THREAD

**Issue by elenigen** [ansible/ansible#10501]
Issue Type:
Bug Report

Ansible version:
1.8.4

Environment:
Centos 6

Summary
If we want only to check the status of a service, the module service will force us to actually force either a start or a stop while we only want the get the state.

Steps To Reproduce:

```
  - command: service service-processor status
    register: serviceStatusResult

  - fail: msg="Service is not running, *** STDOUT *** ->'{{ serviceStatusResult.stdout }}', *** STDERR *** ->'{{ serviceStatusResult.stderr }}'"
    when: "'is running' not in serviceStatusResult.stdout"
```

Expected Results:
I feel the command should not fail and just return the current status.

Actual Results:
Here the command will fail the script if the returned status is not "service-processor is running.":
failed: [hostname] => {"changed": true, "cmd": ["service", "service-processor", "status"], "delta": ...

**Comment by elenigen** [comment]
I realized we can just add a flag ignore_errors:
- command: service service-processor status
  register: serviceStatusResult
  ignore_errors: True

It would be nice to have the status option in the ansible module service to avoid this hack.

**Comment by alfredocambera** [comment]
This feature would be pretty useful.

**Comment by jimi-c** [comment]
The other option is to use `failed_when: false` on that task to ensure it never fails. You could even combine the two tasks you have above using register and failed_when to check for the string in the stdout.

As this is more of a use question than a bug, we will close this now (and sorry for the late follow-up). If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
