### ISSUE TITLE
'vars' and 'defaults' are not documented anywhere

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10506]
In addition to `hostvars` Ansible appears to have another "magical" data structures: `vars` and `defaults` (maybe also others, of which I have no idea). These are not documented anywhere, which is a pity.

**Comment by caphrim007** [comment]
Hi @nfubh.

When they are referred to as data structures, it is usually in the context of the top-level plays. For example, the "Variables Defined in a Playbook" section here
http://docs.ansible.com/playbooks_variables.html#variables-defined-in-a-playbook

Aside from that when using terms such as vars and defaults, we're typically referring to directories inside of a role. For example, refer to the directory layout seen here
http://docs.ansible.com/playbooks_roles.html#roles

Inside of those directories is a single main.yaml that is included by ansible automatically if it exists; mentioned here
http://docs.ansible.com/playbooks_roles.html#role-default-variables

The syntax of the file is plain yaml.
http://docs.ansible.com/YAMLSyntax.html

Because these two locations serve two different purposes, those purposes are spelled out more completely under the Roles section I mentioned above. Specifically there is a bulleted list there that, among other things, mentions

```
- If roles/x/vars/main.yml exists, variables listed therein will be added to the play
```

Also, there is a concept of precedence that you may encounter with variables as you move forward. It is documented more here

http://docs.ansible.com/playbooks_variables.html
Specifically the section "Variable Precedence: Where Should I Put A Variable?" near the bottom of the page

Hope that helps!

**Comment by ghost** [comment]
Hi Tim,

Thanks for the clarification! However what I meant was that Ansible has these two special dicts, `vars` and `defaults`, which you can actually view e.g. with:
- debug: var=defaults
- debug: var=vars

In my case I was looking for a way to use an indirect reference to a certain variable. Normally you would use something like `hostvars[inventory_hostname][variable_name]` for that. However it didn't work, because this particular variable was only defined in a role defaults, and therefore I could only refer to it as `defaults[variable_name]`. Anyway, this let me understand that indirect reference was not the way to go and it is best to avoid using them in general.

In fact I would be happy to see consistent and maybe even strict scoping and precedence rules in Ansible along with some flexible ways of working with complex data structures, like merging dicts, etc. So far I had to dig through the sources a bit to understand all this variable magic better.

**Comment by bcoca** [comment]
So we expose hostvars as a way to access variables, other constructs are internal and should not be used as they can change at any time, hence the lack of documentation.
