### ISSUE TITLE
Do not throw error on --skip-tags when tag(s) are not found

### ISSUE THREAD

**Issue by tonglil** [ansible/ansible#10510]
Since we want to skip these tags and they don't exist anyways, I don't think an error should be thrown since the result is the same as what the user wants.

We have a repository of roles that we use to deploy and sometimes we skip cloning a certain role because we don't need it (and thus its tags won't exist), even though the command still asks to skip that tag.

**Comment by caphrim007** [comment]
This is defined in the playbook/__init__py script's run() method.

It looks like this is a current feature of the system per the comment above the block that checks this.

```
    # if the playbook is invoked with --tags or --skip-tags that don't
    # exist at all in the playbooks then we need to raise an error so that
    # the user can correct the arguments.
```

I'm not entirely sure what the consequences of removing the exception would be aside from the behavior you mentioned; that if we're skipping it anyways then why fail.

One case I can think of, would be if you had some tasks with some tags

```
- name: this is task 1
  debug: msg="task "
  tags:
      - tag1

- name: this is a super critical task that can break everything if run
  debug: msg="task 2"
  tags:
      - tag2

- name: this is task 3
  debug: msg="task 3"
  tags:
      - tag3
```

And you specified

```
--skip-tags tga2
```

(note the misspelling).

You could get yourself in a situation where your task ran, unbeknownst to you, and caused something to break. With the existing functionality, your playbook would never have run to begin with because of the misspelling.

Granted, it might be an edge case example, but CYA mode may be the intent to begin with. There are definitely cases where badness has been activated in the past http://dougseven.com/2014/04/17/knightmare-a-devops-cautionary-tale/

**Comment by tonglil** [comment]
Thanks for the detailed explaination @caphrim007. Hope about an option to forcibly ignore tags then? Automation would be much simplified with this flag!

Anyways, if you accidentally type `--skip-tags tag3` instead of `tag2`, it would also be a same spelling mistake causing the same issue, and even harder to pick up because you can't tell it's a misspelling!

**Comment by bcoca** [comment]
This is currently the case (has been for most of 2.x)  but it is considered a bug. I'm closing this issue as we want to support clear errors for the user when the input is incorrect.
