### ISSUE TITLE
1.9-rc2 BUG: playbook local or configured library/ dir does not allow to overrule a standard module anymore

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#10520]
##### Issue Type:

BUG
##### Ansible Version:

1.9.0-0.2.rc2ppa

```
$ ansible --version
ansible 1.9.0
  configured module search path = 
```
##### Environment:

Ubuntu
##### Summary:

Previously a local library/ folder (relative to tha playbook dir, or configured in ansible.cfg) was searched before the ansible packaged supplied module locations.

This allowed to use a modified/patched version a standard module.
##### Steps To Reproduce:

I had imported an old version from a pull request for Zabbix.

```
$ ls -l plays/library/zabbix_group 
-rw-rw-r-- 1 serge serge 6689 Sep 24 12:44 plays/library/zabbix_group
```
##### Expected Results:

The play just uses that older version of the module.
##### Actual Results:

```
failed: [host] => {"failed": true}
msg: unsupported parameter for module: host_groups
```

which is a parameter (name) that changed in the final version of that module that was merged in 1.9.

**Comment by sivel** [comment]
Just curious, does adding a `.py` extension resolve the problem?

I am using a modified module with the stable-1.9 branch without issue right now, but it does have an extension.

**Comment by srgvg** [comment]
You are correct Matt, renaming them with he `.py` extension solves this.
I see all packaged modules have the `.py` extension now, I must have missed that update.

This fix is good enough for me, but I'll leave it the core maintainers to decide if this is something to solve for backwards compatibility's sake.

**Comment by bcoca** [comment]
path should matter before extension, I thought i had made this so a while back, double checking.

**Comment by bcoca** [comment]
so this might be related to the plugin load cache optimization, though I cannot really reproduce your issue with a simple playbook (i use copy first to ensure cache is loaded):

```
- hosts: localhost
  gather_facts: false
  tasks:
    - copy: src=testfile dest=/tmp/testfile
- hosts: localhost
  gather_facts: false
  tasks:
    - ping:
    - snmp_facts: host=nyx version=v2
```

i have an invalid snmp_facts which gives me an error when executed, I always get this instead of the official one.

**Comment by hoppers99** [comment]
I believe I may be having a related issue; to help reproduction/testing I'll add my scenario here. 

Upgrade from 1.8.2 to 1.9.1 (mac osx using brew) broke precedence on modules for me. I have a modified version of vsphere_guest.py in the library directory of a role which includes changes from the core one.

We've also confirmed this on a Debian Wheezy box with ansible 1.9.1 installed by pip.

In 1.8.2, my modified one was picked up fine from within the role library directory. In 1.9.1, ansible-playbook is trying to use the core library one, so failing due to not having my customization. The only way I was able to make it use mine correctly (without changing the names) was to delete the core copy.

This seems in conflict with the documentation at https://docs.ansible.com/playbooks_roles.html#embedding-modules-in-roles, so hopefully I'm not just missing something obvious.

**Comment by hostmaster** [comment]
I've run into the same issue. '.py' extention solves the problem

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ll library/
total 4
-rw-r--r--. 1 root root 73 Jul  5 02:09 ping
# cat library/ping 
#!/usr/bin/python
print('{"msg": "ok, this is my custom ping module"}')
# cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - ping:
# ansible-playbook -vv test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [ping] *********************************************************************
ok: [localhost] => {"msg": "ok, this is my custom ping module", "invocation": {"module_name": "ping", "module_args": {}}, "changed": false}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
