### ISSUE TITLE
Slow performance issue

### ISSUE THREAD

**Issue by leap72** [ansible/ansible#10523]
Issue Type:

Bug Report

Ansible Version:

ansible 1.7.2

Environment:

Ubuntu 14.04

Summary:
I am using the many roles inside the playbook. There are some tasks not all which take longer as inthe example below eg. 3 minutes just to make sure Nginx service is running or 6 minutes to create some folders. I don't understand why this take really long just to verify a service. 

Steps To Reproduce:

Here's my tasks:

First task

```
- name: Ensure service is running
  service: name=nginx state=started enabled=yes
```

Second task

```
- name: Create project folder(s)
  file: dest=/home/{{ project_id }}/{{ item }}
        state=directory
        owner={{ project_user }}
        group=www-data
        mode=0750
  with_items:
    - backup
    - conf
    - log
    - cgi-bin
    - cgi-bin/php5-default
    - ci-phing
    - ci-phing/config
```

Expected Results:
several seconds for no-change runs. ~40 seconds for creating all folders. 

Actual Results:

First task

```
09:43:44 TASK: [nginx | Add configuration] ********************************************* 
09:43:44 ok: [monitoring]
09:43:44 TASK: [nginx | Ensure service is running] ************************************* 
09:43:44 ok: [monitoring]
09:46:11 TASK: [nginx | Create SSL folder] ********************************************* 
09:46:11 ok: [monitoring]
```

Second task

```
09:53:51 TASK: [Create project folder(s)] ********************************************** 
09:53:51 ok: [app] => (item=backup)
09:53:51 ok: [app] => (item=conf)
09:53:51 ok: [app] => (item=log)
09:53:51 ok: [app] => (item=cgi-bin)
09:53:51 ok: [app] => (item=cgi-bin/php5-default)
09:53:51 ok: [app] => (item=ci-phing)
09:53:51 ok: [app] => (item=ci-phing/config)
09:59:14 TASK: [Create php-fcgi-wrapper] *********************************************** 
09:59:14 ok: [app]
```

**Comment by jimi-c** [comment]
Hi @leap72, have you tried this against a new version of Ansible or the devel branch? There was some work around that time to help prevent some variables from being templated inappropriately (ie. custom facts containing `{{lookup()}}` syntax), and that work has been tweaked since then to provide better performance.

If we don't hear from you in a few days, we'll assume this issue has been resolved and close it.

Thanks!

**Comment by jimi-c** [comment]
Noted that there there has been no follow-up in quite a while, so going to go ahead and close this, as it has been reported against a much older version of Ansible.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
