### ISSUE TITLE
Ansible 1.9.0-1 is breaking

### ISSUE THREAD

**Issue by johnrengelman** [ansible/ansible#10537]
This is likely some user error on my part, but I encountered it and it was incredibly frustrating.
We're using packer.io to create AMIs. We have a base image that has Ansible 1.8.4-1 installed to do provisioning. However during the provisioning process, we were having Ansible run a `apt-get upgrade`. A couple hours ago, this started upgrading Ansible to 1.9.0-1 (since the package was released) and then subsequent tasks would fail with this error:

```
   user-entity-service: File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 590, in _executor
    user-entity-service: msg = str(ae)
    user-entity-service: File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 792, in _executor_internal
    user-entity-service: raise errors.AnsibleError("lookup plugins (with_*) cannot be used with async tasks")
    user-entity-service: File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1027, in _executor_internal_inner
    user-entity-service: File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/copy.py", line 237, in run
    user-entity-service: if self.runner.become and self.runner.become_user != 'root' and not raw:
    user-entity-service: AttributeError: 'Runner' object has no attribute 'become'
```

**Comment by bcoca** [comment]
you caught us mid-release, could you try again now?

also need to look into why mid-release triggered a bad install?? it seems you are using 1/2 one code base and 1/2 the other

**Comment by johnrengelman** [comment]
Well, it revealed an error in our process, but this was the task that was running:

```
---
- name: Update cache and install all updates
  apt: upgrade=dist update_cache=yes
```

This is what `apt-get` was reporting at the time:

```
# apt-get upgrade --dry-run
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  ansible
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Inst ansible [1.8.4-1ppa~trusty] (1.9.0-1ppa~trusty ansible:14.04/trusty [all])
Conf ansible (1.9.0-1ppa~trusty ansible:14.04/trusty [all])
```

**Comment by johnrengelman** [comment]
And here are the commands we used to install Ansible on the base image (Ubuntu Trusty):

```
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible=1.8.4-1ppa~trusty
```

**Comment by srgvg** [comment]
It seems there were 3 releases quick one after another:
- 29809bb 14 hours ago James Cammarata Version bump for 1.9.0.1-1  _(tag: v1.9.0.1-1_, ansible/stable-1.9)
- 717ffe2 16 hours ago James Cammarata Version bump for 1.9.0-2  (tag:\* v1.9.0-2*)
- a0c7381 16 hours ago Brian Coca updated ref to extras
- d76f8de 18 hours ago James Cammarata Submodule updates for 1.9  (tag:\* v1.9.0-1*)
- b268970 18 hours ago James Cammarata Updating submodule pointers for 1.9
- 03c6492 18 hours ago James Cammarata cleaning up CHANGELOG with incorrect entries
- 4ca9fc7 18 hours ago James Cammarata Version bump for 1.9.0 final release

The current latest is  1.9.0.1-1ppa
I assume that is the good one.

**Comment by bcoca** [comment]
yes, we had some issues with pypy and were forced to play with version numbers

**Comment by johnrengelman** [comment]
Ok. I'll assume this is closed then as an intermittent failure. Just wanted to document it somehow in case anyone else hit the same problem.

Thanks!

**Comment by abadger** [comment]
A possible explanation for how upgrading an ansible release and then doing other tasks in the playbook could do bad things:

Ansible is a python application.  Python will load each file of byte code as needed (when it encounters an import statement that needs it).  it's possible that an ansible playbook will load some byte code to run a task that upgrades ansible locally.  Then, when it encounters the next task and it goes to load more byte code files, it gets the byte code from the upgraded package.  that could lead to errors if the upgraded package needs to call or pass around variables that the old package version didn't know about.

I don't think this would be something that caused an error frequently as most of the time an ansible task would load most of the same byte code files as subsequent tasks (with the result that on the controller, the old ansible code would be running until the last play was run).  However, become was a change that touched many different areas of the code and it is definitely possible that after upgrading there were a few byte code files that had to be loaded that knew about become while the old code did not.  As long as things went back to normal once the package update had finished and you started a new ansible-playbook run I think this is  somewhat expected.  To prevent it in the future you'd want to make sure that updating ansible is the last task that any playbook would perform so that there is less chance of the byte code getting out of sync.
