### ISSUE TITLE
v2 is returning success when a module raises an uncaught exception

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#10549]
If you modify v2/ansible/modules/core/system/ping.py like this:

``` patch
diff --git a/system/ping.py b/system/ping.py
index b098d00..2fefc9b 100644
--- a/system/ping.py
+++ b/system/ping.py
@@ -40,6 +40,7 @@ ansible webservers -m ping
 import exceptions

 def main():
+    raise Exception('You should see me!')
     module = AnsibleModule(
         argument_spec = dict(
             data=dict(required=False, default=None),
```

and then run v2's ansible you'd expect an error.  Instead you get a success message:

```
$ ansible localhost -c local -m ping -a 'you=wouldexpectanerror'
localhost | SUCCESS => {
    "invocation": {
        "module_name": "ping", 
        "module_args": {
            "you": "wouldexpectanerror"
        }
    }, 
    "changed": false
}
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
