### ISSUE TITLE
allow_duplicates does not work with transitive dependencies

### ISSUE THREAD

**Issue by ddidier** [ansible/ansible#10562]
##### Summary:

When 2 roles using the same transitive dependency (more than 1 level deep) are applied to a single host, the transitive dependency is applied only once.
##### Steps To Reproduce:

I have 4 roles:
1. `postgresql_third_party` : from Ansible Galaxy, install and configure an instance of PostgreSQL
2. `roles/postgresql_commons/meta/main.yml` : commons settings for my projects
   
   ```
   # allow_duplicates: yes
   dependencies:
     - postgresql_third_party
   ```
3. `roles/postgresql_db1/meta/main.yml`: creates a database named DB1
   
   ```
   # allow_duplicates: yes
   dependencies:
     - { role: postgresql_commons, db_name: DB1 }
   ```
4. `roles/postgresql_db2/meta/main.yml`: creates a database named DB2
   
   ```
   # allow_duplicates: yes
   dependencies:
     - { role: postgresql_commons, db_name: DB2 }
   ```

Enabling or disabling `allow_duplicate` does not change anything when executing the playbook:

```
- name : Install multiple DB on a single instance of PostgreSQL
  hosts: db
  sudo: true
  roles:
    - postgresql_db1
    - postgresql_db2
```
##### Expected Results:

I would expect that the third party role is executed twice, once for DB1 and the other for DB2. The end result would be the creation of the 2 databases.
##### Actual Results:

The role is applied only once. Only the first database is created.

**Comment by danmux** [comment]
I have a similar issue. In my case the dependancy is run twice but it assumes all the variables of the first role - so appears to not do anything whereas it actually repeats the dependant task. the net result is the same.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat roles/dep/tasks/main.yml 
---
# tasks file for dep
- debug: msg="in the dep role, test_param = {{ test_param }}"
# cat roles/role_a/tasks/main.yml 
---
# tasks file for role_a
- debug: msg="this is a task in role_a"
# cat roles/role_a/meta/main.yml 
dependencies:
- { role: dep, test_param: "foo" }
# cat roles/role_b/tasks/main.yml 
---
# tasks file for role_b
- debug: msg="this is a task in role_b"
# cat roles/role_b/meta/main.yml 
dependencies:
- { role: dep, test_param: "bar" }
# cat test.yml
- hosts: localhost
  gather_facts: no
  roles:
  - { role: role_a, tags: role_a }
  - { role: role_b, tags: role_b }
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [dep : dep : debug msg=in the dep role, test_param = foo] ******************
ok: [localhost] => {
    "msg": "in the dep role, test_param = foo", 
    "changed": false
}
TASK [role_a : role_a : debug msg=this is a task in role_a] *********************
ok: [localhost] => {
    "msg": "this is a task in role_a", 
    "changed": false
}
TASK [dep : dep : debug msg=in the dep role, test_param = bar] ******************
ok: [localhost] => {
    "msg": "in the dep role, test_param = bar", 
    "changed": false
}
TASK [role_b : role_b : debug msg=this is a task in role_b] *********************
ok: [localhost] => {
    "msg": "this is a task in role_b", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
# ansible-playbook -vv test.yml --tags=role_a
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [dep : dep : debug msg=in the dep role, test_param = foo] ******************
ok: [localhost] => {
    "msg": "in the dep role, test_param = foo", 
    "changed": false
}
TASK [role_a : role_a : debug msg=this is a task in role_a] *********************
ok: [localhost] => {
    "msg": "this is a task in role_a", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
# ansible-playbook -vv test.yml --tags=role_b
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [dep : dep : debug msg=in the dep role, test_param = bar] ******************
ok: [localhost] => {
    "msg": "in the dep role, test_param = bar", 
    "changed": false
}
TASK [role_b : role_b : debug msg=this is a task in role_b] *********************
ok: [localhost] => {
    "msg": "this is a task in role_b", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

I even included a test showing tag usage, to verify the dependent role was only called once.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
