### ISSUE TITLE
support for asynchronous roles and playbooks

### ISSUE THREAD

**Issue by dkoppstein** [ansible/ansible#10588]
### Issue Type:

Feature Idea
### Ansible Version:

1.9.0.1
### Environment:

N/A
### Summary:

It would be nice to be able to submit an entire role or playbook as an asynchronous task. It is often difficult to run a complex playbook without ssh flaking out. Decorating every task with async is a poor option, and many tasks can't even use async (see #5841). 

Packer does this naively when it's making an image: it uploads the ansible configuration to the remote, then executes with a remote copy of ansible (which you have to install yourself). Despite being a little cludgy, this gets the desired behavior of "fire once, then forget" for a whole ansible playbook which to the best of my knowledge cannot be done using native ansible modules. I feel like it shouldn't be that hard to implement this behavior in ansible itself, perhaps in a more clever manner than simply copying the files over.

**Comment by dkoppstein** [comment]
Nevermind, I found pipeline=True in the docs =)

**Comment by jimi-c** [comment]
Hi @dkoppstein thanks for the interest, and based on your above comment it looks like you're not as interested in seeing this be a feature anymore. For what it's worth, async has been greatly improved in the 2.0 (current devel) branch, and now has nearly no limitation on which kind of tasks it can run. Beyond that, I don't think we'd be interested in this feature, as it would be quite complex to implement based on how Ansible works internally, and has very limited use/benefit for most users.

Thanks for the idea though, and if you have anything further you'd like to discuss please head over to the Ansible development mailing list:
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
