### ISSUE TITLE
delegate_to not setting host variable 

### ISSUE THREAD

**Issue by ogavrisevs** [ansible/ansible#10608]
**_Issue Type:**_

Bug Report

**_Ansible Version:**_

1.8.1

**_Environment:**_

local : MacOsX, 10.10.2
remote: centos 6

**_Summary:**_

Im trying to identify cases when playbook host dos not exists and playbook tasks are skipped.

**_Steps To Reproduce:**_

Run playbook above and replace "192.168.0.1" with actual host you can reach.  

**_Expected Results:**_

Im expecting to set variable on localhost and change value if playbook are executed.

**_Actual Results:**_

Im getting task fail as "play_skiped" keeps = true despite "192.168.0.1" can be reach and task executed.

code: 

``` ansible

---

- hosts: localhost
  pre_tasks:
    - set_fact:
        play_skiped: true

- hosts: "192.168.0.1"
  pre_tasks:
    - set_fact:
        play_skiped: false
      delegate_to: localhost
    - debug:
        msg: "job to run"

- hosts: localhost
  pre_tasks:
    - fail: "host not found, task skiped"
      when: play_skiped
```

**Comment by bcoca** [comment]
cc @abadger

**Comment by bcoca** [comment]
see if #10701 fixes this

**Comment by raags** [comment]
If i'm not mistaken, set_fact does not work with delegate_to, so this is another issue than what it is linked to.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example:

<pre>
# ansible-playbook -vv test.yml -i inv 
Using /etc/ansible/ansible.cfg as config file
3 plays in test.yml
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [set_fact play_skiped=True] ************************************************
ok: [localhost] => {"ansible_facts": {"play_skiped": true}, "changed": false}
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [foobar]
TASK [set_fact play_skiped=False] ***********************************************
ok: [foobar] => {"ansible_facts": {"play_skiped": false}, "changed": false}
TASK [debug msg=job to run] *****************************************************
ok: [foobar] => {
    "changed": false, 
    "msg": "job to run"
}
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [fail msg=host not found, task skiped] *************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
PLAY RECAP **********************************************************************
foobar                     : ok=3    changed=0    unreachable=0    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
