### ISSUE TITLE
cpanm not changed in anync mode

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#10611]
```
    - name: install cpanm
      apt: name=cpanminus state=present
      when: ansible_os_family == 'Debian'

    - name: install Net::Server::SS::PreFork – could take up to 10 minutes
      cpanm: name=Net::Server::SS::PreFork #long
      poll: 0
      async: 1800
      register: cpanm_async

    - name: 'spanm - check Net::Server::SS::PreFork installation status'
      async_status: jid={{ cpanm_async.ansible_job_id }}
      register: cpanm_async_result
      until: cpanm_async_result.finished
      notify: reload app
      retries: "{{ '%d'|format(1800/5) }}"

    - fail: msg="Net::Server::SS::PreFork installation timeout"
      when: not cpanm_async_result.finished
```

`cpanm_async_result` never gets changed, neither does `cpanm_async`.

ansible 1.9.0.1, mac os.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 10611.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 10611.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [ubuntu1404]
TASK [install cpanm] ************************************************************
ok: [ubuntu1404] => {"invocation": {"module_name": "apt", "module_args": {"state": "present", "name": "cpanminus"}}, "cache_updated": false, "changed": false, "cache_update_time": 0}
TASK [install Net::Server::SS::PreFork – could take up to 10 minutes] ***********
ok: [ubuntu1404] => {"started": 1, "results_file": "/root/.ansible_async/300125330969.11904", "ansible_job_id": "300125330969.11904", "changed": false}
TASK [spanm - check Net::Server::SS::PreFork installation status] ***************
FAILED - RETRYING: TASK: spanm - check Net::Server::SS::PreFork installation status (359 retries left). Result was: {u'ansible_job_id': u'300125330969.11904', u'started': 1, u'changed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/300125330969.11904', 'invocation': {'module_name': u'async_status', 'module_args': {u'jid': u'300125330969.11904'}}}
FAILED - RETRYING: TASK: spanm - check Net::Server::SS::PreFork installation status (358 retries left). Result was: {u'ansible_job_id': u'300125330969.11904', u'started': 1, u'changed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/300125330969.11904', 'invocation': {'module_name': u'async_status', 'module_args': {u'jid': u'300125330969.11904'}}}
...
FAILED - RETRYING: TASK: spanm - check Net::Server::SS::PreFork installation status (1 retries left). Result was: {u'ansible_job_id': u'995810864084.4320', u'started': 1, u'changed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/995810864084.4320', 'invocation': {'module_name': u'async_status', 'module_args': {u'jid': u'995810864084.4320'}}}
ok: [ubuntu1404] => {"ansible_job_id": "995810864084.4320", "started": 1, "changed": false, "finished": 0, "results_file": "/root/.ansible_async/995810864084.4320", "invocation": {"module_name": "async_status", "module_args": {"jid": "995810864084.4320"}}}
TASK [fail msg=Net::Server::SS::PreFork installation timeout] *******************
fatal: [ubuntu1404]: FAILED! => {"msg": "Net::Server::SS::PreFork installation timeout", "failed": true, "changed": false}
PLAY RECAP **********************************************************************
ubuntu1404                 : ok=4    changed=1    unreachable=0    failed=1   
</pre>

Now, you can see that the task did fail due to the async task not completing in time, however overall it worked as expected.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
