### ISSUE TITLE
Unicode bug when using multibytes variables

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10621]
ansible 1.9.0.1

I’m having an issue with the following Jinja2 template:

<pre>
# playbook.yml

---
- hosts: yun
  remote_user: jefurry
  vars:
   author: 小马哥
  tasks:
   - name: 测试
     shell: 'echo "hello"'
   - debug: msg={{ author }}
</pre>

it works fine. but when i using multibytes variables in template, I’m getting the following error:

<pre>
# playbook.yml

---
- hosts: yun
  remote_user: jefurry
  vars:
   author: 小马哥
  tasks:
   - name: 测试
     local_action: shell echo {{ author }} > t.txt
</pre>

error details:

<pre>
PLAY [yun] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [aliyun]

TASK: [测试] **************************************************************** 
failed: [aliyun -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/jefurry/.ansible/tmp/ansible-tmp-1428235901.38-125429082829696/command", line 2073, in <module>
    main()
  File "/Users/jefurry/.ansible/tmp/ansible-tmp-1428235901.38-125429082829696/command", line 209, in main
    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell)
  File "/Users/jefurry/.ansible/tmp/ansible-tmp-1428235901.38-125429082829696/command", line 1691, in run_command
    to_clean_args = shlex.split(args.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/jefurry/playbook.retry

aliyun                     : ok=1    changed=0    unreachable=0    failed=1   
</pre>

If I remove the non-ascii character (小马哥), it works fine.
thanks!

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 10621.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 10621.yml
PLAY: ***************************************************************************
TASK [测试] ***********************************************************************
changed: [localhost] => {"changed": true, "end": "2015-07-05 15:24:11.428406", "stdout": "", "cmd": "echo 小马哥 > /tmp/10621.txt", "start": "2015-07-05 15:24:11.425324", "delta": "0:00:00.003082", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo 小马哥 > /tmp/10621.txt", "_uses_shell": true}}, "stdout_lines": [], "warnings": []}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
# cat /tmp/10621.txt 
小马哥
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ghost** [comment]
ok, good job!
