### ISSUE TITLE
ansible / ansible-playbook group_vars behave differently?

### ISSUE THREAD

**Issue by jtktam** [ansible/ansible#10648]
In my first attempt at using ansible and ansible-playbook, I have the group variables inside the inventory file and both picks up the variables fine.

...\hosts\testlab

```
[coreos]
10.0.0.1
10.0.0.2
10.0.0.3

[coreos:vars]
ansible_ssh_user=core
ansible_python_interpreter="/home/core/bin/python"
```

After reading the best practices and wanting to add more hosts, I went and seperated out the group vars into the group_vars directory

...\hosts\testlab

```
[coreos]
10.0.0.1
10.0.0.2
10.0.0.3
```

...\group_vars\coreos

```
ansible_ssh_user: core
ansible_python_interpreter: /home/core/bin/python
```

ansible-playbook picks up the group variables correctly and it functions as expected

ansible does not seem to read the ...\group_vars\coreos at all.  Only after adding the [core:vars] back into the inventory file does it work again.  

I wanted to abstract the group variables from the inventory file since my inventory file is being dynamically built and i would like to centralize the common variables in group_vars directory.

**Comment by sivel** [comment]
`group_vars` can live in 2 locations:
1. Alongside your inventory
2. Alongside your playbook

When executing the `ansible` command, there is no playbook, so I do not believe the `group_vars` would load if `group_vars` is not located with the inventory file.

I am having difficulty understanding your paths, since you reference `...` in multiple locations, additionally without knowing what command you are running I cannot be certain;  However, it appears as though your `group_vars` need to be moved into the `hosts` directory.

**Comment by bcoca** [comment]
Ah, yes, I assumed these where inventory group_vars, which I've tested and
work for both, play group_vars will ONLY work for ansible-playbook as
ansible (ad-hoc) does not have a reference play from which to base the
location of group_vars.

## 

Brian Coca

**Comment by jtktam** [comment]
Thanks for the quick replies.

the two hints given by @sivel and @bcoca helped me solved this.

my group_vars and host_vars was at the playbook directory, hence why it works with ansible-playbook

i made a group_vars and host_vars directory in my inventory file location and it works now!

thanks
