### ISSUE TITLE
allow sudo: True/False to be set via extra vars 

### ISSUE THREAD

**Issue by avadhanula** [ansible/ansible#10667]
Re-opening #2526 as it was  closed as duplicate. It is still reproducible in 1.9.01

**Comment by jctanner** [comment]
Hi!

We believe recent versions of ansible should resolve this question or problem for you.

This example properly sets the become value in ansible 2.1 ..

```
ansible-playbook -vvvv -i inventory -e "ansible_become=yes" site.yml
```

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
