### ISSUE TITLE
sudo_exe should be an inventory variable an not a global one

### ISSUE THREAD

**Issue by davidvd** [ansible/ansible#10669]
Hi,

We have a very large and heterogeneous environment with a lot of Solaris 10, 11 and 2-3 kinds of linux distribution. The problem is that the sudo path is not the same everywhere. If I set sudo_exe to /usr/local/bin/sudo in ansible.cfg, I can have the solaris 10 working. If I set it to /usr/bin/sudo, I get the solaris 11, and I have to remove this setting to have the linux ones to work. I tried to add /usr/local/bin and /usr/bin to the default path but ansible seems to ignore this, by design I think. Is there another solution to my problem, other than requesting this feature?

Sorry if I don't respect the standards on issues, it's the first time I open one on github... 

Thank you for the great tool!

David

**Comment by davidvd** [comment]
This is from Issue #9986 : https://groups.google.com/forum/#!topic/ansible-project/ZEnYyvLcqL0

**Comment by jimi-c** [comment]
@davidvd this has been completed on the devel branch. You can now set `ansible_become_exe` (or `ansible_sudo_exe`/`ansible_su_exe`) as an inventory variable.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
