### ISSUE TITLE
Ansible load error

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10671]
I was working with provisioning **vagrant box** using **Ansible** and every time I reload the vagrant with provisioning, Ansible used to run fine. I changed some provisioning script like some commands and since then I get this error. Its not about the command, as I have already tested reverting back the changes, but somehow I get this error below:-

I assume its Ansible failing to load?

My Ansible version is:

``` shell
ansible --version
ansible 1.9.0.1
  configured module search path = None
```

``` shell
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/rajib/.vagrant.d/insecure_private_key --user=vagrant --connection=ssh --limit='vaasa' --inventory-file=/home/rajib/vagrant_vbox/tiera/vaasa/.vagrant/provisioners/ansible/inventory -vvv provisioning/playbook.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 263, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 188, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 661, in _load_tasks
    loaded = self._load_tasks(data, mv, role_params, default_vars, included_become_vars, list(included_additional_conditions), original_file=include_filename, role_name=new_role)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 642, in _load_tasks
    (k,v) = t.split("=", 1)
ValueError: need more than 1 value to unpack
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by ghost** [comment]
The issue was with `include module` 

I listed the include like

``` ruby
tasks:
  include:
    - this.yml
    - that.yml
```

Now sure why this threw the Ansible load error, but when I changed the include statement to

``` ruby
tasks:
  - include: this.yml
  - include: that.yml
```

it loads perfectly.

However if there's something wrong with YAML file then it might be great to inform users about the certain wrong thing instead of fail to load.

The perfect error information example I got from Ansible is in include module with_items statement like

``` ruby
tasks:
  - include: {{ item }}
    with_items:
      - this.yml
      - that.yml
```

Ansible says nicely 

> include with_items is deprecated.

**Comment by jimi-c** [comment]
The first syntax would be if include would take multiple file names (which it doesn't), while the second works as expected. The third will be in v2, so we're going to go ahead and close this issue for now, as it does work in v2 currently.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
