### ISSUE TITLE
Outcome of calculated variable different in play vs role/vars

### ISSUE THREAD

**Issue by discordianfish** [ansible/ansible#10674]
I'm trying to calculate the min quorum for elasticsearch and set it as variable. If I do this all in one play it works as expected:

```
- hosts: tag_role_infra
  vars:
    es_nodes: "{{ groups['tag_role_infra']|intersect(groups['tag_aws_cloudformation_stack_name_'+ec2_tag_aws_cloudformation_stack_name|replace('-','_')]) }}"
    es_min_masters: "{{ ((es_nodes|count / 2) + 1) | int }}"
  tasks:
    - debug: var=es_nodes
    - debug: var=es_min_masters
```

This outputs 3 nodes and a es_min_master of 2.
Now I wanted to move this into a role. I get the same 3 node output but a es_min_master of "71". I suspect a difference in execution of play vs role but really have no clue how this happens. Here is a gist of a simple role + play + full output which should make it easy to reproduce: https://gist.github.com/discordianfish/88d0d8f21442c34a2e4e

**Comment by discordianfish** [comment]
Oh maybe a few words about the rather complex es_nodes expression: I have multiple stacks and in each stack there are 3 instances tagged as 'infra', so this expression basically finds all nodes tagged 'infra' which are in the same stack as the current node.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
TASK [test : test : debug var=es_min_masters] ***********************************
ok: [host1] => {
    "changed": false, 
    "es_min_masters": "2"
}
ok: [host2] => {
    "changed": false, 
    "es_min_masters": "2"
}
ok: [host3] => {
    "changed": false, 
    "es_min_masters": "2"
}
ok: [host4] => {
    "changed": false, 
    "es_min_masters": "2"
}
ok: [host5] => {
    "changed": false, 
    "es_min_masters": "2"
}
PLAY RECAP **********************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
host2                      : ok=2    changed=0    unreachable=0    failed=0   
host3                      : ok=2    changed=0    unreachable=0    failed=0   
host4                      : ok=2    changed=0    unreachable=0    failed=0   
host5                      : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
I believe this shows your example a bit more concisely, using --limit as you show:

<pre>
# ansible-playbook -vvv -i inv test.yml -e ec2_tag_aws_cloudformation_stack_name=foo --limit=host1:3
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [test : test : debug var=es_nodes] *****************************************
ok: [host1] => {
    "changed": false, 
    "es_nodes": [
        "host1", 
        "host2", 
        "host3"
    ]
}
TASK [test : test : debug var=es_min_masters] ***********************************
ok: [host1] => {
    "changed": false, 
    "es_min_masters": "2"
}
PLAY RECAP **********************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
</pre>
