### ISSUE TITLE
running powershell script on windows remote host 

### ISSUE THREAD

**Issue by neilrogers** [ansible/ansible#10726]
getting this error. Seems the #!powershell shebang is not installed? I have upgraded powershell, installed the winrm pip also ran the configure ps script on the windows host

failed: [127.0.0.1] => {"changed": true, "rc": 126}
stderr: /bin/sh: /root/.ansible/tmp/ansible-tmp-1429094323.5-255856345700713/windows.ps1: powershell: bad interpreter: No such file or directory

using ansible 1.9.0.1

**Comment by cchurch** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

It seems like Ansible is connecting to localhost instead of the Windows host as you intended.  If you could provide the command line options you're using to run Ansible and a sample of your inventory file, it may help us to better understand what's going wrong.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
