### ISSUE TITLE
ansible stop at the step of sudo

### ISSUE THREAD

**Issue by ansible-lee** [ansible/ansible#10724]
1.In playbook write "sudo: yes" and "sudo_user: root" line,
2.If exec the playbook with "-K" paramater,then linux pop the input dialog line,ask the sudo password.
3.if input password error,then the ansible will stop at the sudo task step, no return error. till express "CTRL + C" to terminate it.The ansible look as dead or locked at somewhere.

This problem met some times, no better solution.

**Comment by ansible-lee** [comment]
The exec cmd is "ansible-playbook site.yml -i hosts -K"

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 10724.yml -k -K
Using /etc/ansible/ansible.cfg as config file
SSH password: 
SUDO password[defaults to SSH password]: 
1 plays in 10724.yml
PLAY: ***************************************************************************
TASK [command] ******************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001801", "end": "2015-07-12 00:38:52.435211", "rc": 0, "start": "2015-07-12 00:38:52.433410", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"]}
TASK [command] ******************************************************************
fatal: [awxlocal]: FAILED! => {
    "failed": true, 
    "msg": "ERROR! Incorrect sudo password"
}
PLAY RECAP **********************************************************************
awxlocal                   : ok=1    changed=1    unreachable=0    failed=1   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
