### ISSUE TITLE
calling the same playbook multiple times in the parent playbook seems to only respect the variables in the last call

### ISSUE THREAD

**Issue by fawaf** [ansible/ansible#10739]
in the parent playbook, i have this:

```
...do some stuff...
- include: "{{ playbook_dir }}/common/foo.yml prepare_tool=true"
...do some other stuff...
- include: "{{ playbook_dir }}/common/foo.yml phase=all prepare_tool=false"
...do some more stuff...
```

in foo.yml, i have this:

```
  - debug: var=prepare_tool
  - debug: var=phase
```

the output that i expect to get is:

```
prepare_tool: "True"
prepare_tool: "false"
phase: "all"
```

but the actual output that i get is:

```
prepare_tool: "True"
phase: "all"
prepare_tool: "false"
phase: "all"
```

i would expect that because there is no "phase" in the first invocation of the playbook, that variable should not be set. is this expected behavior?

**Comment by nickhammond** [comment]
Is phase being defaulted or set somewhere else? Here's what I'm seeing, still somewhat confusing that when phase isn't set you see `"phase" : "phase"`.

playbook.yml

```
---

- hosts: all
  tasks:
    - include: foo.yml prepare_tool=true
    - include: foo.yml phase=all prepare_tool=false
```

foo.yml

```
---

- debug: var=prepare_tool
- debug: var=phase
```

output

```
➜  ansible_10739  ansible-playbook -i localhost playbook.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug var=prepare_tool] ************************************************
ok: [localhost] => {
    "var": {
        "prepare_tool": "true"
    }
}

TASK: [debug var=phase] *******************************************************
ok: [localhost] => {
    "var": {
        "phase": "phase"
    }
}

TASK: [debug var=prepare_tool] ************************************************
ok: [localhost] => {
    "var": {
        "prepare_tool": "false"
    }
}

TASK: [debug var=phase] *******************************************************
ok: [localhost] => {
    "var": {
        "phase": "all"
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0

```

**Comment by fawaf** [comment]
nope, "phase" is not being defaulted anywhere.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [include prepare_tool=true] ************************************************
included: /root/testing/10739/common/foo.yml for localhost
TASK [debug var=prepare_tool] ***************************************************
ok: [localhost] => {
    "changed": false, 
    "prepare_tool": "true"
}
TASK [debug var=not specified] **************************************************
ok: [localhost] => {
    "changed": false, 
    "{{phase|default('not specified')}}": "not specified"
}
TASK [include phase=all prepare_tool=false] *************************************
included: /root/testing/10739/common/foo.yml for localhost
TASK [debug var=prepare_tool] ***************************************************
ok: [localhost] => {
    "changed": false, 
    "prepare_tool": "false"
}
TASK [debug var=all] ************************************************************
ok: [localhost] => {
    "changed": false, 
    "{{phase|default('not specified')}}": "all"
}
PLAY RECAP **********************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
