### ISSUE TITLE
Unable to get stdout of the 'cat'ing of a file that contains (and starts with) special characters

### ISSUE THREAD

**Issue by inghama** [ansible/ansible#10731]
Unfortunately, the problem described in https://github.com/ansible/ansible/issues/7299 
has RETURNED (as of ansible version 1.8.4 ?):

FAILS:
    ansible HOSTXYZ -m shell -a 'cat /var/log/boot.log' -K --sudo
    sudo password: 
    HOSTXYZ | success | rc=0 >>

```
<NO OUTPUT HERE, WHERE THERE SHOULD BE (DUE TO SPECIAL CHARACTERS AT THE BEGINNING OF THAT FILE?)>
```

WORKS PROPERLY:

```
ansible HOSTXYZ -m shell -a 'cat /etc/motd' -K --sudo
sudo password: 
HOSTXYZ | success | rc=0 >>

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
You are about to access a Duke University computer network that is intended for
authorized users only. You should have no expectation of privacy in your use of
this network. Use of this network constitutes consent to monitoring, retrieval,
and disclosure of any information stored within the network for any purpose
including criminal prosecution.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

CURRENT VERSION:
    ansible --version
    ansible 1.8.4

Andy

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible -m shell -a 'cat /var/log/boot.log' --ask-become-pass --become -u testing awxlocal
SUDO password: 
awxlocal | SUCCESS => {
    "changed": true, 
    "cmd": "cat /var/log/boot.log", 
    "delta": "0:00:00.003765", 
    "end": "2015-07-12 02:41:45.031854", 
    "rc": 0, 
    "start": "2015-07-12 02:41:45.028089", 
    "stderr": "", 
    "stdout": "\u001b%G\t\tWelcome to \u001b[0;36mCentOS\u001b[0;39m \r\nStarting udev: \u001b%G\u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]\r\r\n...\r\r\n\u001b[00;32mTomcat is running with pid: 1942\u001b[00m", 
    "stdout_lines": [
        "\u001b%G\t\tWelcome to \u001b[0;36mCentOS\u001b[0;39m ", 
        "Starting udev: \u001b%G\u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]", 
        "", 
        ...
        "\u001b[00;32mTomcat is running with pid: 1942\u001b[00m"
    ]
}
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
