### ISSUE TITLE
Inventory group vars incorrectly returned, example:

### ISSUE THREAD

**Issue by victorgp** [ansible/ansible#10755]
I found an incorrect behavior with the inventory file and group vars, see this example:

Inventory file:

``` yaml
[groupA]
host1.domain.com

[groupA:vars]
myvar=valueA

[groupB]
host1.domain.com

[groupB:vars]
myvar=valueB
```

Playbook:

``` yaml
- name: Example
  hosts: groupA
  tasks:
    - command: "echo {{myvar}}"
```

Output:

```
$ ansible-playbook -v -i hosts pb.yaml 

PLAY [Example] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [host1.domain.com]

TASK: [command echo {{myvar}}] ************************************************ 
changed: [host1.domain.com] => {"changed": true, "cmd": ["echo", "valueB"], "delta": "0:00:00.002181", "end": "2015-04-16 14:40:56.129921", "rc": 0, "start": "2015-04-16 14:40:56.127740", "stderr": "", "stdout": "valueB", "warnings": []}

PLAY RECAP ******************************************************************** 
host1.domain.com           : ok=2    changed=1    unreachable=0    failed=0
```

In the Playbook i'm selecting "groupA" as hosts, but Ansible is printing "valueB" for "myvar" variable, and it should be printing "valueA".

That is because in "_executor_internal" method in "runner/__init__.py", the variables are got from the host instead of the group, in this line:

``` python
temp_vars = self.inventory.get_variables(host, vault_password=self.vault_pass)
```

This inventory file a dummy example that doesn't make much sense, but if you want to have a more complex scenario, this becomes a big issue, like for example something like this:

``` yaml
[serviceA1]
host1.domain.com
host2.domain.com
host3.domain.com

[serviceA2]
host4.domain.com
host5.domain.com
host6.domain.com

[serviceA:children]
serviceA1
serviceA2

[serviceA:vars]
process=myprocessA

[serviceB]
host5.domain.com
host6.domain.com

[serviceB:vars]
process=myprocessB
```

**Comment by srgvg** [comment]
This is a feature and not a bug, and has been asked several times yet here and on the list. You are trying to use a way to define things that just isn't the way ansible dpes things.

Ansible only uses variables on the host level. The inventory only returns variables after they are calculated/inherited down top that host level.

When you target a play to a particular group, that gets calculated down to a list of hosts. Whether you call groupA or groupB here, it results in the same host. And that hosts only has one [articular value for `myvar`, which happens to be `groupB` because thats the last one bing parsed.

To quote the docs: 

>  Remember: Child groups override parent groups, and hosts always override their groups.

PS Given this question get's asked a lot, it might be helpfull add a note on this (http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular,  variable resolution is not related to host selection, as explained in the post above.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
