### ISSUE TITLE
Expire password for user

### ISSUE THREAD

**Issue by DustinTrap** [ansible/ansible#10791]
When creating a new user account a password can be set. A desirable behavior is to have the user login with the password once and the be forced to set a new password immediately. 

A shell command could be used in this form: "password -e username" but passing with_items is clunky. I recommend the user module be enhanced to include a 'expire_password' option with two flags, yes and no. See example below.

```

---
- hosts: user_add
  remote_user: username
  sudo: yes
  tasks:
  - name: Add new user
    user:
     name="{{ item }}"
     password=XXXXXXXXXXX
     state=present
     expire_password=yes
    with_items:
     - user1
     - user2...
```

Thanks!

**Comment by bcoca** [comment]
on my list i had more of a 'password_expires=<epoch>' feature

**Comment by tonyyarusso** [comment]
Perhaps it could accept both a date code for times in the future and a keyword of "now"?

**Comment by DustinTrap** [comment]
@bcoca Newb here... where's the list?

@tonyyarusso Yes, date codes would be nice. Is this what you mean? expire_password=<now or 12\31\2015>

**Comment by tonyyarusso** [comment]
I suspect Brian means the wishlist in his head ;)

Regardless of whether the parameter is named expire_password or password_expires, I think we're talking about behavior similar to the "expires" one:

"An expiry time for the user in epoch, it will be ignored on platforms that do not support this. Currently supported on Linux and FreeBSD. (added in Ansible 1.9)"

In practice it looks like this:
expires: 16435.0 # 31 December 2014, expiry locks both password and SSH key access

But then possibly also accepting a non-float keyword that gets translated to the current day (or maybe previous day to make sure it's really immediate).

(On a related note, it really ought to be smart enough to take an integer and convert to a float...I had trouble with that with the other parameter.)

**Comment by tonyyarusso** [comment]
Oh, also, this should be under ansible-modules-core for the user module, rather than the main project.  Is there a way to move an issue, or would it need to be refiled?

**Comment by bcoca** [comment]
answering at random:
- yes, full wishlist is in my head, but i believe this is in several places written down
- we are also looking at date/time filters to deal with the minutia of now/tomorrow/dec 1st 4043
- sadly github has no way of moving issues

**Comment by DustinTrap** [comment]
Well, I'm in favor of a basic implementation for the time being. Just having a expire-now feature would accomplish the most common task. There's other methods of setting a date for a password to expire that could be leveraged instead of putting the code in Ansible. For example chage on most *nix should provide the needed functions.

I'm a bit of a github newb, so help me out here. Should I recreate the issue under ansible-modules-core or can it just live here? Thanks!

**Comment by esacteksab** [comment]
Came here looking for this. Would be valuable for managing users.

**Comment by selivan** [comment]
Vote up for this feature. Ansible lacks functionality of `chage -m|-M` to set minimum number of days between password change and maximum number of days while password is valid. If anybody need quick-and-dirty workaround with shell commands: https://github.com/selivan/ansible-set-user-password-expire (just for Linux, BSD have different management utils).

**Comment by SaaldjorMike** [comment]
:+1:

**Comment by kerrc** [comment]
Vote up for this Also

password_expires=yes/no functionality in this module would be ideal.
This is exactly what i am missing from creating my current playbook - rather then running a command such as passwd -x -1 {{ user }} 

How do we know if this will be looked at?

**Comment by Doooooo0o** [comment]
```
- name: Create
  user: name={{ item }} generate_ssh_key=yes password="yourpassword" update_password=on_create
  register: changes
  with_items: "{{ users }}"


- name: Expire
  command: chage -d 0 {{ item.item }}
  with_items: "{{ changes.results }}"
  when: "{{ item.changed == true }}"
```

**Comment by lqueryvg** [comment]
I've written a chage Ansible module in Python, available here:

https://github.com/lqueryvg/ansible-role-chage

It provides proper & efficient read & write access to the Linux /etc/shadow file via Python spwd & chage commands (respectively), by which I mean it can change multiple shadow attributes for a user in one I/O (via spwd) and bundles multiple attribute changes into one invocation of chage with proper change detection.

I personally think it would be better for chage features (i.e. modification of /etc/shadow file) to be kept separate from the user module, since it is very Linux specific and could cause the user module to become overloaded.

I'd be happy to package this up as a pull request for ansible-modules-extras if there was a reasonable chance of it being accepted.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by lnovara** [comment]
Since Ansible modules are now merged with the main repository, can this issue be reopened? I think that there is still interest in having this feature implemented.

**Comment by finaroux** [comment]
Same here, we should probably open a new ticket as this issue is now closed and will not be reviewed

**Comment by termlen0** [comment]
Curious if this is being tracked through an open issue/feature request.

**Comment by relrod** [comment]
:+1: for re-opening.
