### ISSUE TITLE
win_copy/template action plugins remain in repo

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#10804]
**Issue Type:**

Bug Report

**Ansible Version:**

1.9.0.1

**Environment:**

All

**Summary:**

The win_copy/win_file/win_template modules were added during earlier development and then reverted. However, win_copy.py and win_template.py remain in the actions_plugins dir.

If they're going to eventually be used, we can keep them - if the new version of the modules isn't going to use them, they should probably be removed.

**Steps To Reproduce:**

Look in the actions plugin directory.

**Comment by wenottingham** [comment]
cc @jhawkesworth

**Comment by jhawkesworth** [comment]
I haven't forgotten about this.  I had email exchange with @bcoca when this was merged and if I recall correctly the plan was to refactor the action plugin code so that there was more common logic available to action plugins.

Its possible I am the only person making use of these but I use these every day of the week as I have local versions of win_copy / win_file / win_template from the unmerged https://github.com/ansible/ansible-modules-core/pull/384 

so I think this is really a refactoring which needs doing but is not necessarily a functional bug.

**Comment by bcoca** [comment]
The refactoring was meant to centralize duplicate code in module_utils,
like we do for many other modules.

## 

Brian Coca

**Comment by ibratoev** [comment]
You are not the only person using that ;) Please, leave the action plugins in until the modules are finally merged.

**Comment by bcoca** [comment]
So I'm going to close this ticket as we don't want to remove the action plugins, we should just add back the win_copy/template modules

**Comment by jhawkesworth** [comment]
If possible please - the modules would allow the remainder of the winrm integration tests to pass.
I can resubmit the modules to modules-extras if that would be preferable.
