### ISSUE TITLE
cmdline extra-vars does not affect to vars inside include

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#10817]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible-playbook 1.9.0.1
  configured module search path = None
```
##### Environment:

Linux - Ubuntu 
##### Summary:

While 
- vars from inventory
- include with vars,

run with extra-vars, the vars in included is not affected.
##### Steps To Reproduce:

Inventory

```
localhost branch=inventory
```

include_test.yml

``` yml
- hosts: localhost
  connection: local
  tasks:
    - include: included.yml msg="from include {{ branch }}"
    - debug: msg="from root {{ branch }}"
```

included.yml

``` yml
- debug: msg="{{ msg }}"
```

run

```
ansible-playbook -i inventory/include_test slack_test_root.yml -e "branch=cmdline"
```
##### Expected Results:

```
TASK: [debug msg="from include {{ branch }}"] ********************************* 
ok: [localhost] => {
    "msg": "from include cmdline"
}

TASK: [debug msg="from root {{ branch }}"] ************************************ 
ok: [localhost] => {
    "msg": "from root cmdline"
}
```
##### Actual Results:

```
TASK: [debug msg="from include {{ branch }}"] ********************************* 
ok: [localhost] => {
    "msg": "from include inventory"
}

TASK: [debug msg="from root {{ branch }}"] ************************************ 
ok: [localhost] => {
    "msg": "from root cmdline"
}
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -i inv -vv test.yml -e branch=cmdline
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [include msg=from include cmdline] *****************************************
included: included.yml for localhost
TASK [debug msg=from include cmdline] *******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "from include cmdline"
}
TASK [debug msg=from root cmdline] **********************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "from root cmdline"
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by shirou** [comment]
confirmed. Thank you very much!
