### ISSUE TITLE
Galaxy role_path in config file is relative to cwd, it should not IMHO

### ISSUE THREAD

**Issue by lyrixx** [ansible/ansible#10811]
Hi, I don't want to install all my deps into `/etc/ansible` because I think it's better to not share all dependencies between several ansible project.

Instead I want to install my vendor like that:

``` bash
ansible-galaxy install -r requirements.yml --force --roles-path=vendor/
```

So I want to configure my ansible.cfg like that

``` ini
[defaults]
roles_path = vendor/
```

Because I want a portable installation, I don't want to use absolute path.

Now, I'm using vagrant to test my playbook, and I put my vagrantfile inside another directory.
So I configured vagrant + ansible to use a specific ansible.cfg because ansible looks at `cwd` like that:

``` ruby
ENV['ANSIBLE_CONFIG'] = "../../../ansible/ansible.cfg"

Vagrant.configure("2") do |config|
    config.vm.box = "sl_base"

    config.vm.network "private_network", ip: "192.168.50.20"
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../../ansible/sl_elasticsearch.yml"
        # ansible.verbose = "vvvv"
        # ansible.extra_vars = { }
        ansible.skip_tags = [ 'sl_base' ]
    end
end
```

But that's not work as expected. Indeed I have to use this kind of configuration to make it work

``` diff
[defaults]
- roles_path =  vendor/
+ roles_path = ../../../ansible/vendor/
```

And for me it does not make sense to make the `role_paths` relative to my `cwd` ... because as said in other issue, ansible can be fired from anywhere...

**Comment by bcoca** [comment]
agreed, it should be relative either to the config or to the play being executed

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
