### ISSUE TITLE
file lookups behave differently in a role's main var file vs. in auxiliary var files

### ISSUE THREAD

**Issue by tomconnors** [ansible/ansible#10823]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.0.1
##### Environment:

Running from OSX 10.9.5
Targeting Ubuntu 14.04
##### Summary:

Using a file lookup in a role's main var file succeeds and an identical lookup in an auxiliary var file fails.

More specifically, I have a role with two files in the "vars" directory: `main.yml` and `dev.yml`. In the role's `tasks/main.yml`, the first task is to conditionally include the `dev.yml` var file using `include_vars`. The `dev.yml` file contains a lookup intended to read a file in the role's `files` directory:

```
key: "{{ lookup('file', 'ssh/phony_key.pub') }}"
```

The `main.yml` file has a lookup that reads successfully from the same `files` directory. Once the var defined using a lookup in `dev.yml` is referenced, the playbook fails because the lookup plugin was unable to find the file. 
##### Steps To Reproduce:

Create a role with a `dev.yml` var file. In `dev.yml` use a lookup for a file in the role's `files` directory. Include the var file using `include_vars` in the role's `tasks/main.yml`. The lookup will not succeed.
##### Expected Results:

I expected lookups to function identically in all sibling var files.
##### Actual Results:

Lookups succeed in `main.yml` and fail in other files in the `vars` directory.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [test : test : include_vars] ***********************************************
ok: [localhost] => {"ansible_facts": {"lookup_from_include": "{{lookup('file', 'keys/key1.pub')}}"}, "changed": false}
TASK [test : test : debug var=lookup_from_vars] *********************************
ok: [localhost] => {
    "changed": false, 
    "lookup_from_vars": "This is the first public key file"
}
TASK [test : test : debug var=lookup_from_include] ******************************
ok: [localhost] => {
    "changed": false, 
    "lookup_from_include": "This is the first public key file"
}
PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
