### ISSUE TITLE
s3 exceptions being raised by Boto on 1.9.0.1 and master

### ISSUE THREAD

**Issue by apenney** [ansible/ansible#10831]
Given:

```
- name: Copy results to S3
  s3: bucket=nroute-loadtest-results object=/{{ansible_date_time['date']}}-{{run_id}}.txt src=/tmp/results/{{run_id}}.txt mode=put region=eu-east-1
```

From master:

TASK: [Copy results to S3] ****************************************************
failed: [52.4.166.46] => {"failed": true, "parsed": false}
BECOME-SUCCESS-fwurcphsnjcinrjjpobxnjlqcvnazkld
Traceback (most recent call last):
  File "/home/apenney/.ansible/tmp/ansible-tmp-1429884459.29-240245887052132/s3", line 156, in <module>
    def create_bucket(module, s3, bucket, location=Location.DEFAULT):
NameError: name 'Location' is not defined

I tried this with the latest boto (2.38.0) as well as 2.35.2 just in case it was a recent regression.  I have tried leaving the region in/out of the task with no difference.

**Comment by apenney** [comment]
Embarrassingly the problem here is that boto was only on my ansible running box, not the node that was going to PUT the file.  Iwould normally close this from shame but it would be nice if we raised or did a test up front to make sure boto is available.  I am sort of surprised it got as far as it did with no boto. :)

**Comment by bcoca** [comment]
There is a check, the script tries to import boto and returns 'boto required for this module' when it is not the case. Since this is referenced in the function's definition the Exception happens before the runtime check is able to run though, this is still a bug and should be fixed.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
