### ISSUE TITLE
Don’t notify handlers from failing tasks

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#10845]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0
##### Environment:

Running from: Ubuntu 12.04, managing Ubuntu 14.04
##### Summary:

--force-handlers can be used to run already notified handlers even if a later task fails. At the moment, however, a handler is ran even if the only task that notifies it failed. This seems superfluous, there’s no need to restart a service if writing its configuration failed.
##### Steps To Reproduce:

```
[
    {
        "hosts":          "all",
        "gather_facts":   false,
        "force_handlers": true,

        "tasks": [
            {
                "name":   "notify",
                "action": "command /bin/false",
                "notify": "handle"
            }
        ],

        "handlers": [
            {
                "name":   "handle",
                "action": "debug"
            }
        ]
    }
]
```
##### Expected Results:

`handle` should not run.
##### Actual Results:

`handle` runs.

**Comment by bcoca** [comment]
I'm not sure I understand what you are saying, can you fill in the tempalte https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md?

**Comment by jooadam** [comment]
@bcoca I have filled in the template, though I’m not sure how that helps better understanding in this case. Can you point out where is my description unclear?

**Comment by sivel** [comment]
I'm pretty sure that `force_handlers` is doing it's job.  You told it to force running of handlers.  So even though the task failed, ansible is doing what you told it to do.  

From https://docs.ansible.com/playbooks_error_handling.html#handlers-and-failure

> When handlers are forced, they will run when notified even if a task fails on that host

**Comment by bcoca** [comment]
So what seems to be the point of contention is the "previously notified" part, if there is only one task and IT fails, it should not have notified the handlers in the first place, it should notify only on changed=true (which command ALWAYS does).

**Comment by jooadam** [comment]
> Handlers: Running Operations On Change

The whole point of a handler is that it is ran only if something has changed.

@bcoca Exactly.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Currently, notifications are only sent if the task is successful and if it returns `changed=true`. So even with `--force-handlers` enabled, you should not see a notification if the triggering task failed.

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
