### ISSUE TITLE
Missing variables in the special variable "vars"

### ISSUE THREAD

**Issue by lucaagostini** [ansible/ansible#10859]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
##### Environment:

I am running Ansible in Ubuntu 14.04.1 LTS with a playbook with local connection.
##### Summary:

With Ansible 1.7.2 if I include a var file with `vars_files` directive, variables in these files are also in the special `vars` variable.
Starting from Ansible 1.8 (but also in 1.9.1) in the special variable `vars` disappeared variables included with `vars_files` directive. 
##### Steps To Reproduce:

my_vars.yml

```

---

var_key: var_value
var_value: RESPONSE
```

play.yml

```

---

- name: Test
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - my_vars.yml
  tasks:
    - debug: var=vars[var_key]
    - debug: var=vars
```

Command:

``` bash
$ ansible-playbook -i "127.0.0.1," play.yml
```
##### Expected Results:

In Ansible 1.7.2  the output of `vars[var_key]` is `RESPONSE` because I can get the value of `var_value` using the variable `var_key` as key in the `vars` dictionary.

```
PLAY [Test] *******************************************************************

TASK: [debug var=vars[var_key]] ***********************************************
ok: [localhost] => {
    "vars[var_key]": "RESPONSE"
}

TASK: [debug var=vars] ********************************************************
ok: [localhost] => {
    "vars": {
        "always_run": false,
        "changed_when": null,
        "delegate_to": null,
        "failed_when": null,
        "ignore_errors": false,
        "play_hosts": [],
        "playbook_dir": "/home/ago/ansible-bug-vars",
        "register": null,
        "role_names": [],
        "var_key": "var_value",
        "var_value": "RESPONSE"
    }
}
```
##### Actual Results:

In Ansible 1.9.1 (but also starting from Ansible 1.8) `var_key` and `var_value` variable aren't in the `vars` variable and I canno't access to the value of `var_value` variable using the value of `var_key` variable as key in `vars`.

```
PLAY [Test] *******************************************************************

TASK: [debug var=vars[var_key]] ***********************************************
ok: [localhost] => {
    "var": {
        "vars[var_key]": "{{vars[var_key]}}"
    }
}

TASK: [debug var=vars] ********************************************************
ok: [localhost] => {
    "var": {
        "vars": {
            "always_run": false,
            "ansible_version": {
                "full": "1.9.1",
                "major": 1,
                "minor": 9,
                "revision": 1,
                "string": "1.9.1\n  configured module search path = None"
            },
            "changed_when": null,
            "delegate_to": null,
            "failed_when": null,
            "ignore_errors": false,
            "play_hosts": [
                "localhost"
            ],
            "playbook_dir": "/home/ago/ansible-bug-vars",
            "register": null,
            "role_names": []
        }
    }
}
```

**Comment by bcoca** [comment]
just to note that the vars variable was not meant to be exposed for use in the playbooks

**Comment by rektide** [comment]
this also effects `vars:` here's an example i wrote up while freaking out: https://gist.github.com/rektide/c83208ccf4ab84638546 

the take-away is that these playbook vars moved from vars -> hostvars, but they exist in a super weird and funky state inside the hostvars: they exist as toplevel properties of hostvars, rather than being under inventory_hostname. and when you go to access these vars, `Exception: host not found: HI`

**Comment by rektide** [comment]
Places in the wild this capability is mentioned:
https://github.com/ansible/ansible/issues/10859
https://github.com/lorin/ansible-quickref#play-parameters

I've also recently written the ML,
https://groups.google.com/forum/#!topic/ansible-project/K5s6rFM4sSw

I don't see why we would be able to indirectly reference vars (`hostvars[ansible_hostname]`) but not facts (`vars`). I have a lot of ALICE_URL, BOB_URL stuff defined in facts, and I need to be able to lookup against Alice or Bob somehow, and right now that capability has become broken. Arguing that it "was not meant to be exposed" doesn't make sense- it was very explicitly injected into the play's context, and it was documented by third parties and mentioned in conversation with mdehann, and it is a basic capability that gives parity with hostvars/vars.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv -i "127.0.0.1," test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: Test **********************************************************************
TASK [debug var=vars[var_key]] **************************************************
ok: [localhost] => {
    "changed": false, 
    "vars[var_key]": "RESPONSE"
}
TASK [debug var=vars] ***********************************************************
ok: [localhost] => {
    "changed": false, 
    "vars": {
        "ansible_connection": "local", 
        "ansible_play_hosts": [], 
        "ansible_python_interpreter": "/bin/python", 
        "ansible_ssh_host": "127.0.0.1", 
        "ansible_ssh_port": null, 
        "ansible_version": {
            "full": "2.0.0", 
            "major": 2, 
            "minor": 0, 
            "revision": 0, 
            "string": "2.0.0"
        }, 
        "group_names": [
            "ungrouped"
        ], 
        "groups": {
            "all": [
                "localhost", 
                "127.0.0.1"
            ], 
            "ungrouped": [
                "localhost"
            ]
        }, 
        "hostvars": {}, 
        "inventory_dir": null, 
        "inventory_hostname": "localhost", 
        "inventory_hostname_short": "localhost", 
        "omit": "__omit_place_holder__b744c254e5c0e97d44a2f67d4aa0fabc369bc8d3", 
        "play_hosts": [], 
        "playbook_dir": "/root/testing/10859", 
        "var_key": "var_value", 
        "var_value": "RESPONSE"
    }
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
