### ISSUE TITLE
ansible_managed VCS information

### ISSUE THREAD

**Issue by jmdh** [ansible/ansible#10887]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.2

(but I've checked that the feature isn't in master)
##### Environment:

N/A
##### Summary:

The `ansible_managed` macro is a very helpful way of tagging a file as being managed by ansible, but  including it will cause quite a lot of deployment churn with multiple users, since it's dependent on the user running it and the path, as well as the mtime of the file (which may not be the time the file actually changed).

It would be great to have the following strings available to that macro from `git log -1 $file`:

Author
Date
Hash/shorthash
Short commit message

as well as the current branch name. Thoughts on exactly how this should work welcomed!

**Comment by bcoca** [comment]
This would need to be configurable as not everyone uses git (I don't understand why, but its true!).

Changes to source template is only 1/2 of the issue, the generated file can also change depending on vars, this is a lot harder to locate the commit/author/file that caused it. An auto git bisect with error being file change can help ... but ... rabbit hole ...

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Our reasons for this are:

Since we aren't always templating from files in a VCS, I'm not sure this a feature we would want to implement. The best option would probably be a way to manipulate/configure the ansible_managed data via config, but even then it would be simpler to just set a fact with the relevant information and include that fact in a comment inside the template. 

However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

https://groups.google.com/forum/#!forum/ansible-devel
In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
