### ISSUE TITLE
"delegated for" host sudo setting is being used instead of delegated_to host's settings

### ISSUE THREAD

**Issue by Lx** [ansible/ansible#10906]
##### Issue Type:

bug report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.1
```
##### Environment:

```
$ lsb_release -d
Description:    Linux Mint 17.1 Rebecca
```
##### Summary:

Setting `ansible_sudo` for a remote host to `true` forces `local_action` tasks to use `sudo` even if the task says `sudo: false`.
##### Steps To Reproduce:

Create a playbook for a host whose `ansible_sudo` value is `true`, add this task and run the playbook:

``` yaml
- name: wait for reboot to complete
  sudo: false
  local_action: wait_for host={{ inventory_hostname }} state=started
```
##### Expected Results:

The `local_action` task completes successfully.
##### Actual Results:

```
TASK: [playbook | wait for reboot to complete] **************************** 
failed: [XXX -> 127.0.0.1] => {"failed": true, "parsed": false}
[sudo via ansible, key=XXX] password: 
```

indicating that `sudo: false` is not honoured for the `local_action`.  If I set the remote host's `ansible_sudo` value to `false`, the `local_action` works as expected.

**Comment by bcoca** [comment]
in this case the ansible_sudo of the delegated host (localhost) should be the decider.

**Comment by Lx** [comment]
Without an explicit `sudo` paramter to the `local_action`, I fully agree.

I explicitly state `sudo: false` in my task above; intuitively, I would expect that to take precedence over `localhost`'s `ansible_sudo` value.  In any event, I haven't defined `ansible_sudo` for `localhost` so I would expect it to default to false:

```
$ ansible -i inventory -m debug -a 'msg={{ ansible_sudo }}' 'localhost;127.0.0.1'
127.0.0.1 | FAILED => One or more undefined variables: 'ansible_sudo' is undefined
localhost | FAILED => One or more undefined variables: 'ansible_sudo' is undefined
```

**Comment by bcoca** [comment]
inventory connection settings trump all others except connection settings set at extra vars level, this is not that level so the host specific vars will trump the task more general case.

**Comment by DmitrySandalov** [comment]
I tried with `sudo: no` as well, but the tasks still use `sudo` (observed with `synchronize` module).
- Suggested workaround: remove `ansible_sudo=true` from inventory; add `sudo: yes` everywhere :)
- Another one: create additional playbook for `sudo: false` tasks

**Comment by skozin** [comment]
Got bitten by this too.

Intuitively, `sudo` setting specified for an individual task/play should take precedence over `ansible_sudo`, because it is more specific. Just like `vars` for includes/plays take precedence over all vars specified elsewhere.

**Comment by bcoca** [comment]
we consider host connection variables more specific than the rest, the privilege escalation vars have been considered 'connection variables' also (hosta allows root login, hostb requires sudo to root, hostc requires su to root). I can see how this can be considered th e other way, but this is how ansible is currently meant to work.  

This issue is still a bug as the delegated_for host variable is being used for the delegated_to host. not because the host setting overrides the task setting.

**Comment by skozin** [comment]
I understand, just wanted to say that, in my opinion, this is far from intuitive, and can bite people who are just starting to use Ansible (like me).

**Comment by thkala** [comment]
Incidentally, this also seems to happen when the "parent" task is performed on a node that uses `su` for privilege escalation. Both `local_action` and `delegate_to: localhost` insist on trying to use `su`, even when there is an explicit localhost entry in the inventory with a local connection specified, and ansible_{become,su,sudo} explicitly set to false.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vvv 10906.yml -K
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
1 plays in 10906.yml
PLAY: ***************************************************************************
TASK [command] ******************************************************************
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: testing
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=testing -o ConnectTimeout=10 192.168.122.100 mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000 && echo $HOME/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: testing
<192.168.122.100> PUT /tmp/tmpvN2IJg TO /home/testing/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000/command
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: testing
<192.168.122.100> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=testing -o ConnectTimeout=10 192.168.122.100 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ghtpukmjbzydjnpukyutsrjpxxxcwprf] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ghtpukmjbzydjnpukyutsrjpxxxcwprf; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/testing/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000/command; rm -rf /home/testing/.ansible/tmp/ansible-tmp-1436800684.54-70411516558000/ >/dev/null 2>&1'"'"''
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002924", "end": "2015-07-13 11:18:05.906132", "rc": 0, "start": "2015-07-13 11:18:05.903208", "stderr": "", "stdout": "root", "stdout_lines": ["root"]}
TASK [wait for reboot to complete] **********************************************
ESTABLISH LOCAL CONNECTION FOR USER: testing
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187 && echo $HOME/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187
127.0.0.1 PUT /tmp/tmpvIseKv TO /root/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187/wait_for
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187/wait_for; rm -rf /root/.ansible/tmp/ansible-tmp-1436800686.03-47237416327187/ >/dev/null 2>&1
ok: [awxlocal] => {"changed": false, "elapsed": 0, "path": null, "port": 80, "search_regex": null, "state": "started"}
PLAY RECAP **********************************************************************
awxlocal                   : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
For the record, this was my test playbook, using the new `become` syntax:

<pre>
# cat 10906.yml 
- hosts: awxlocal
  gather_facts: no
  remote_user: testing
  become: yes
  become_user: root
  tasks:
  - command: whoami
  - name: wait for reboot to complete
    become: false
    local_action: wait_for port=80
</pre>

**Comment by Hubbitus** [comment]
Master branch today (7124504ccfd837d6a8e4124d619fb605ae92e0b0)

Playbook (cat test-dev/bug10906.yml):

```
- hosts: 127.0.0.2
  gather_facts: no
  remote_user: testing
  become: yes
  become_user: root
  tasks:
    - name: DEBUG id *local_action*
      become: false
      shell: id
      delegate_to: localhost

    - name: DEBUG id *delegate_to*
      become: false
      local_action: shell id
```

Result:

```
$ ansible-playbook -vvv test-dev/bug10906.yml 
Using /home/pasha/Projects/Ansible.cfg/ansible.cfg as config file
1 plays in test-dev/bug10906.yml

PLAY ****************************************************************************

TASK [DEBUG id *local_action*] **************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437476189.26-193494002042629" && echo "$HOME/.ansible/tmp/ansible-tmp-1437476189.26-193494002042629"
127.0.0.1 PUT /tmp/tmp7XuXET TO /home/pasha/.ansible/tmp/ansible-tmp-1437476189.26-193494002042629/command
127.0.0.1 EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=nwewcqupathewxmwxvbumcwatfmrkivb] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-nwewcqupathewxmwxvbumcwatfmrkivb; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /home/pasha/.ansible/tmp/ansible-tmp-1437476189.26-193494002042629/command; rm -rf "/home/pasha/.ansible/tmp/ansible-tmp-1437476189.26-193494002042629/" >/dev/null 2>&1'"'"''
changed: [127.0.0.2] => {"changed": true, "cmd": "id", "delta": "0:00:00.002410", "end": "2015-07-21 13:56:29.334445", "rc": 0, "start": "2015-07-21 13:56:29.332035", "stderr": "", "stdout": "uid=0(root) gid=0(root) groups=0(root)", "stdout_lines": ["uid=0(root) gid=0(root) groups=0(root)"], "warnings": []}

TASK [DEBUG id *delegate_to*] ***************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437476189.56-71718806229233" && echo "$HOME/.ansible/tmp/ansible-tmp-1437476189.56-71718806229233"
127.0.0.1 PUT /tmp/tmpEM0pwz TO /home/pasha/.ansible/tmp/ansible-tmp-1437476189.56-71718806229233/command
127.0.0.1 EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jdpibcggjxfzdqahnrgvibsxogkusbqd] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jdpibcggjxfzdqahnrgvibsxogkusbqd; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /home/pasha/.ansible/tmp/ansible-tmp-1437476189.56-71718806229233/command; rm -rf "/home/pasha/.ansible/tmp/ansible-tmp-1437476189.56-71718806229233/" >/dev/null 2>&1'"'"''
changed: [127.0.0.2] => {"changed": true, "cmd": "id", "delta": "0:00:00.002483", "end": "2015-07-21 13:56:29.636293", "rc": 0, "start": "2015-07-21 13:56:29.633810", "stderr": "", "stdout": "uid=0(root) gid=0(root) groups=0(root)", "stdout_lines": ["uid=0(root) gid=0(root) groups=0(root)"], "warnings": []}

PLAY RECAP **********************************************************************
127.0.0.2                  : ok=2    changed=2    unreachable=0    failed=0
```

Host defined:

```
$ grep 127 inventory/hosts 
127.0.0.2 ansible_become=yes ansible_become_method=sudo ansible_ssh_user=root
```

Even if I add localhost in hosts file, or even more:

```
localhost ansible_become=false
```

still

```
shell: id
delegate_to: localhost
```

will tell me what I root.

**Comment by jimi-c** [comment]
@Hubbitus I'm unclear if you're saying there's a problem? If so, that output is what I'd expect, if you're running the ansible-playbook command as root.

**Comment by Hubbitus** [comment]
@jimi-c, no! Ansible-playbook run from regular user (pasha).

**Comment by Hubbitus** [comment]
@jimi-c, excuse me, do you plan address it?

**Comment by HanXHX** [comment]
Hi, I confirm this bug on Ansible 1.9.2

Play:

```
- hosts: aws-ami
  tasks:
    - name: LOCAL_ACTION whoami
      become: no
      sudo: no
      local_action: command whoami 
```

Inventory:

```
aws-ami ansible_ssh_host=myhost.tld ansible_ssh_user=admin ansible_sudo=yes
```

Output:

```
TASK: [LOCAL_ACTION WAIT_FOR | Waiting for server to come back] *************** 
failed: [aws-ami -> 127.0.0.1] => {"failed": true, "parsed": false}
[sudo via ansible, key=lcrntibvkeqhdkhvbgoznqqzvxamdmpl] password: 


FATAL: all hosts have already failed -- aborting

```

**Comment by HanXHX** [comment]
Quick & dirty way to bypass this problem: add yourself in sudoers without password.

```
echo "$(whoami) ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
```

**Comment by Hubbitus** [comment]
And what it does? It is not always need to be root!

**Comment by jimi-c** [comment]
@Hubbitus sorry, I meant to re-open this after your previous comment above.

**Comment by jimi-c** [comment]
@Hubbitus / @Lx in 1f5584aa5b9d1142e67fed209bbeea1ca99fc307, I am no longer seeing this issue. Running the example from @Hubbitus, on my system (running as my user, not root), I get the following output:

<pre>
TASK [DEBUG id *local_action*] *************************************************
changed: [127.0.0.2] => {"changed": true, "cmd": "id", "delta": "0:00:00.003914", "end": "2015-09-18 15:45:09.341409", "rc": 0, "start": "2015-09-18 15:45:09.337495", "stderr": "", "stdout": "uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", "stdout_lines": ["uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023"], "warnings": []}
TASK [DEBUG id *delegate_to*] **************************************************
changed: [127.0.0.2] => {"changed": true, "cmd": "id", "delta": "0:00:00.003696", "end": "2015-09-18 15:45:09.454587", "rc": 0, "start": "2015-09-18 15:45:09.450891", "stderr": "", "stdout": "uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", "stdout_lines": ["uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023"], "warnings": []}
</pre>

If one or both of you could also confirm, I'll go ahead and close this.

**Comment by jimi-c** [comment]
As there hasn't been a follow-up in a few days since I verified this, I'm going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by caylorme** [comment]
I'm getting this error on 1.9.3 and on the latest devel a89412ecb13e4207a25aaf2ea6bd2c932463720f for 2.0

```
$ ansible --version
ansible 2.0.0 (devel a89412ecb1) last updated 2015/09/29 17:07:17 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a4ac171a07) last updated 2015/09/29 17:07:22 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 3c8c716801) last updated 2015/09/29 17:07:26 (GMT -400)
  config file =
  configured module search path = None
```

Task

```
- name: Create a local file
  local_action: template src=template.j2 dest=file.txt
  become: false
```

Error

```
fatal: [testhost.localdomain]: FAILED! => {"changed": false, "failed": true, "msg": "sudo: a password is required\n", "parsed": false}
```

**Comment by jimi-c** [comment]
@caylorme could you please open a new issue for this? Thanks!

**Comment by caylorme** [comment]
@jimi-c , why? It is the exact same issue, unresolved in the latest releases and development versions.

**Comment by jimi-c** [comment]
@caylorme because I'm not sure if it is the same issue or not, and my testing showed it working so it could be broken somewhere else than was addressed above.

**Comment by Hubbitus** [comment]
Sorry for long silence.

I could confirm in Ansible 4cd810a it work for me as expected (reproduce playbook return me id of regular user under what I have run it). Thank you very much @jimi-c.
