### ISSUE TITLE
Having task nested tasks in role leads for incorrect template path search

### ISSUE THREAD

**Issue by holms** [ansible/ansible#10907]
### Issue type:

bug report
### Ansible Version:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```
### Environment:

OSX Yosemite: 10.10.2 (14C1514)
Ansible Installed from Pip
### Summary:

I'm not sure if this is an issue, or I'm wrong in using ansible.

I assume that having subdirectory in `roles/myrole/tasks` is a normal behaivior. It's just organizing your stuff around. In this situation templates are being searched in _not expected_ location.
### Steps To Reproduce:

For example if you have this kind of task in your role: `roles/myrole/tasks/rhel/repository.yml`
Which has `template` action in it:

```
- name: RHEL | Add yum repository for MariaDB for CENTOS
  template: src=rhel/centos.j2
                  dest=/etc/yum.repos.d/mariadb.repo
                  owner=root
                  group=root
                  mode=0644
  when: ansible_distribution == 'CentOS'
```
### Expected Results:

I expect that `rhel/centos.j2` templated should be searched in `role/myrole/templates/rhel/centos.j2`
### Actual Results:

Instead it's searching in different locations:

```
TASK: [galera | RHEL | Add yum repository for MariaDB for CENTOS] *************
fatal: [xxx.182.232] => input file not found at /Users/holms/Dev/playbooks/galera/roles/galera/tasks/templates/rhel/centos.j2 or /Users/holms/Dev/playbooks/repo/galera/rhel/centos.j2
```

Here's my template dir:

```
Romans-MacBook-Air:rhel holms$ ls -lah
total 16
drwxr-xr-x@ 4 holms  staff   136B May  3 16:07 .
drwxr-xr-x@ 8 holms  staff   272B May  1 18:51 ..
-rw-r--r--@ 1 holms  staff   301B May  1 17:34 centos.j2
-rw-r--r--@ 1 holms  staff   283B May  1 17:37 redhat.j2
Romans-MacBook-Air:rhel holms$ pwd
/Users/holms/Dev/playbooks/repo/galera/roles/galera/templates/rhel

```

**Comment by pragmatist-nz** [comment]
+1 just came across the same situation, when calling template out of a included subtask

main.yml

```
- include: centos/postinstall.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
```

centos/postinstall.yml:

```
- template:
    src: systemd.consul-agent.j2
    dest: '{{ consul_config_dir }}/consul-agent.service'
    owner: root
    group: root
    mode: 644
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat roles/test/templates/test_sub/test.j2
This was the file from {{inventory_hostname}}
# cat roles/test/tasks/main.yml
---
- include: test_sub/foo.yml
# cat roles/test/tasks/test_sub/foo.yml
- template: src=test_sub/test.j2 dest=/tmp/10907.txt
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [test : test : include] ****************************************************
included: test_sub/foo.yml for localhost
TASK [test : test : template dest=/tmp/10907.txt src=test_sub/test.j2] **********
changed: [localhost] => {"changed": true, "checksum": "25c3125bece852548e558d7014811983e890a495", "dest": "/tmp/10907.txt", "diff": {"after": "This was the file from localhost\n", "before": ""}, "gid": 0, "group": "root", "md5sum": "1951b51a8d757a8af07b5e869466ac4b", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 33, "src": "/root/.ansible/tmp/ansible-tmp-1436800921.01-46497971329799/source", "state": "file", "uid": 0}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
# cat /tmp/10907.txt 
This was the file from localhost
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
