### ISSUE TITLE
Ansible does not expand variables from other var files

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#10919]
##### Ansible Version:

$ ansible --version
ansible 2.0.0 (devel c488ea019f) last updated 2015/05/05 13:59:20 (GMT +200)
  lib/ansible/modules/core: (detached HEAD c4f6e63117) last updated 2015/05/05 16:22:56 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 28b0f3ce13) last updated 2015/05/05 16:22:56 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/05/05 16:22:57 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/05/05 16:22:57 (GMT +200)
  configured module search path = None
##### Summary: ansible does not expand variables from var files in var files directives anymore.

It looks like a bug related to issue #9621
##### Steps To Reproduce:

```
mkdir './playbooks'
mkdir './vars'
cat > './hosts' <<EOF
example
EOF
cat > './playbooks/example.yml' <<EOF

---
- hosts: example
  vars_files:
    - "{{ lookup('env', 'ANSIBLE_PUBLIC_BASEDIR') }}/vars/global.yml"
    # works
    #- "{{ lookup('env', 'ANSIBLE_PUBLIC_BASEDIR') }}/vars/{{ ansible_distribution }}.yml"
    # does not work
    - "{{ mybasedir }}/vars/{{ ansible_distribution }}.yml"
  tasks:
    - action: shell echo "{{ dist_tag }}"
EOF
cat > './vars/CentOS.yml' <<EOF

---
dist_release: ${ansible_distribution_version[0]}
dist_tag: el${dist_release}
EOF
cat > './vars/global.yml' <<EOF
mybasedir: "{{ lookup('env','ANSIBLE_PUBLIC_BASEDIR') }}"
EOF
ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook -i hosts playbooks/example.yml
```
##### Expected Results:

```
$ ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook -i hosts playbooks/example.yml

PLAY [example] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [example]
example: importing /tmp/ansible/vars/CentOS.yml

TASK: [shell echo "{{ dist_tag }}"] ******************************************* 
changed: [example]

PLAY RECAP ******************************************************************** 
example                    : ok=2    changed=1    unreachable=0    failed=0   
```
##### Actual Results:

```
$ ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook -i hosts playbooks/example.yml

PLAY [example] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [example]

TASK: [shell echo "{{ dist_tag }}"] ******************************************* 
fatal: [example] => One or more undefined variables: 'dist_tag' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/till/example.retry

example                    : ok=1    changed=0    unreachable=1    failed=0   
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook -vv -i hosts playbooks/example.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in playbooks/example.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [example]
TASK [debug msg=the dist_tag variable is el] ************************************
ok: [example] => {
    "changed": false, 
    "msg": "the dist_tag variable is el"
}
PLAY RECAP **********************************************************************
example                    : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
