### ISSUE TITLE
lookup failing to find file

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#10929]
**Issue Type:**

Bug report

**Ansible Version:**

ansible 1.9.0.1 and ansible 1.9.1

**Environment:**

Mac OSX 10.10.3
Ubuntu 15.04

**Summary:**

Error 1:

```
TASK: [bootstrap | add rsa public key to the remote host] *********************
fatal: [192.168.4.5] => could not locate file in lookup: cloudserver.pub

FATAL: all hosts have already failed -- aborting
```

Error 2:

```
TASK: [bootstrap | add rsa public key to the remote host] *********************
fatal: [192.168.4.5] => could not locate file in lookup: /home/hyper/.ssh/cloudserver.pub

FATAL: all hosts have already failed -- aborting
```

**Steps To Reproduce:**

run `vagrant provision` (with ansible provisioner)

with plays below:

```
- name: add rsa public key to the remote host
  authorized_key: user={{ user }}
                  key="{{ lookup('file', 'cloudserver.pub') }}"
```

```
- name: add rsa public key to the remote host
  authorized_key: user={{ user }}
                  key="{{ lookup('file', '/home/hyper/.ssh/cloudserver.pub') }}"
```

**Expected Results:**

Simply work.

**Actual Results:**

Error above.

**Comment by mightydok** [comment]
@hyperfocus1337 can you:
ls -la /home/hyper/.ssh/cloudserver.pub in vagrant box

Also can you provide full Vagrantfile file playbook, maybe on pastebin.

**Comment by bcoca** [comment]
you are trying to lookup a remote file?

**Comment by mightydok** [comment]
@bcoca i think @hyperfocus1337 use vagrant box, so its local file.

**Comment by bcoca** [comment]
@mightydok depends on which box is running ansible, it can be done both ways, that is why i ask for a disambiguation

**Comment by jimi-c** [comment]
Per the above, I believe this is confusion regarding where the lookup plugins operate, which is always on the server where Ansible is being run, not the endpoint nodes where the module code is executed. As a result, these files would should be located on the managing node. If you need the contents of the remote file, you can use the slurp or fetch modules instead.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
