### ISSUE TITLE
host variables do not override role/vars values

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#10922]
##### Issue Type:

“Bug Report”
##### Ansible Version:

```
ansible 2.0.0 (devel a0def30c34) last updated 2015/04/15 11:32:13 (GMT -700)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/15 11:32:18 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/15 11:32:18 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/05 16:10:19 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/15 11:32:18 (GMT -700)
  configured module search path = None
```
##### Environment:

Ubuntu 14.04.2 LTS
##### Summary:

Variables in host_vars/file.yml should take precedence over variables in roles/rolename/vars/main.yml. In my tests, the role variables appear to take precedence.
##### Steps To Reproduce:

Add the same variable to host_vars/hostname.yml and roles/rolename/vars/main.yml. Create a playbook for that host and role. Add a debug task to the playbook that outputs the test variable. 
##### Expected Results:

debug should output the value stored in host_vars/hostname.yml.
##### Actual Results:

debug ouputs the value stored in roles/rolename/vars/main.yml.
##### Comments:

The Ansible docs say:

> Avoid defining the variable “x” in 47 places and then ask the question “which x gets used”. Why? Because that’s not Ansible’s Zen philosophy of doing things.
> There is only one Empire State Building. One Mona Lisa, etc. Figure out where to define a variable, and don’t make it complicated.

As nice as it would be to only define a variable in one place, it's just not feasible. I'd end up with a playbook per host, or a role per host, or some other unmanageable mess. In order to keep sane, I have to be able to define general defaults for everything, then be able to override them on a group or host based level when needed.

The best way I've found to do that is a common role that I can share between Ansible projects. (Sadly group_vars/all won't work unless I start copying the same values in to multiple locations. Which kinda defeats the whole point of configuration management...) Unfortunately, that causes issues between the common role defaults/main.yml values and rolename/defaults/main.yml values. Both are at the same level, so it's impossible to tell which will get applied. Thus, I need to put my common values in common/vars. Which, when I need to override that value on a specific host, causes the above issue...

Anyway, that's why I need host_vars/host to take precedence over rolename/var/blah.

**Comment by HitScan** [comment]
This is the list from the documentation page you linked to:
- extra vars (-e in the command line) always win
- then comes connection variables defined in inventory (ansible_ssh_user, etc)
- then comes "most everything else" (command line switches, vars in play, included vars, **role vars**, etc)
- then comes the rest of the variables defined in inventory
- then comes facts discovered about a system
- then "**role defaults**", which are the most "defaulty" and lose in priority to everything.

What it sounds like you need are the "role defaults" which are kept in ROLE/defaults/main.yml instead of ROLE/vars/main.yml This give you the ability to put role vars at 2 different points on the precedence list. I'm not sure the distinction between role variables and role defaults is very well spelled out, I didn't notice the difference until I came across the example role dir structure and saw "defaults/"

**Comment by jerrac** [comment]
Thanks for the reply, but I've tried that already. From my first post:

> Unfortunately, that causes issues between the common role defaults/main.yml values and rolename/defaults/main.yml values. Both are at the same level, so it's impossible to tell which will get applied.

I'm not sure it's actually impossible to tell which will get applied, but I do know that in my testing, the wrong value was applied when I wasn't specifying it in the host/group_vars file.

**Comment by HitScan** [comment]
I see, I misread what you were intending to do with your common role. I'm not certain roles are the best way to do what you're trying to achieve, but someone with more Ansible experience than I have may be able to help out.

**Comment by jerrac** [comment]
I'd rather have the common role defaults in the all group, but, due to how my servers are set up, I would end up have to edit multiple all group vars every time I changed something. The common role helps me avoid that.

I've thought about making the group_vars/all directory a git submodle, or symlinking it. But I'm not sure it wouldn't have annoying side effects. Haven't fully thought it through yet.

Ideally, I'd have something I could put in my playbooks that would say "This directory contains vars at a level just above the all group." var_files doesn't do that, does it? It sticks the vars at the same level as vars defined in the actual playbook, right?

Or maybe a project level defaults file/dir...

**Comment by bcoca** [comment]
group_vars/all at play level overrides group_vars/all at inventory level

On Fri, May 8, 2015 at 12:56 PM, David Reagan notifications@github.com
wrote:

> I'd rather have the common role defaults in the all group, but, due to how
> my servers are set up, I would end up have to edit multiple all group vars
> every time I changed something. The common role helps me avoid that.
> 
> I've thought about making the group_vars/all directory a git submodle, or
> symlinking it. But I'm not sure it wouldn't have annoying side effects.
> Haven't fully thought it through yet.
> 
> Ideally, I'd have something I could put in my playbooks that would say
> "This directory contains vars at a level just above the all group."
> var_files doesn't do that, does it? It sticks the vars at the same level as
> vars defined in the actual playbook, right?
> 
> Or maybe a project level defaults file/dir...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/10922#issuecomment-100298126.

## 

Brian Coca

**Comment by bocharsky-bw** [comment]
My workaround to override play vars with variables defined in inventory file

`ansible/hosts.ini`:

``` ini
[localhost]
localhost    ansible_connection=local    host_project_path=/var/www/html/project
```

`ansible/deploy.yml`:

``` yaml
- name: ansible application deploy
  hosts: all
  vars:
    project_path: "{{ host_project_path|default('/var/www/html') }}"
```

So `project_path` with default value `/var/www/html` could be overridden with `host_project_path` (with `/var/www/html/project` value) defined in inventory file if last exists.

Maybe it will help someone

**Comment by jerrac** [comment]
So, I'm pretty sure my solution is going to be a git submodule. But I'm still very curious why variable precedence isn't better defined. 

Something like this:
- command line
- connection/inventory
- playbook vars list/hash
- playbook vars_file include
- host_vars
- group_vars
- all group
- role vars files
- role defaults

Ansible code does have to figure all that out. So why is it so fuzzy?

**Comment by jimi-c** [comment]
@jerrac part of the original thinking was, we didn't want users to have to think about it. I believe that has not worked out well, so we will be clarifying that doc based on the new devel class VariableManager, which has very clear rules about how and what order variables from all sources are merged into the final global view of variables.

Defaults were things that were supposed to be over-ridden, so generally that's where you'd want your variables. In your case, it sounds like you're having collisions in names, which is generally just related to poor variable naming. I'd suggest sticking with that, as it provides the most flexibility.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
