### ISSUE TITLE
Replace python2-style octal numbers

### ISSUE THREAD

**Issue by cjdrake** [ansible/ansible#10925]
The source code has several instances of number literals in the form `0700`. Python3 raises a `SyntaxError` for these. For forward compatibility, we will need to change `0700` to `0o700`.

See the [What's New in Python3](https://docs.python.org/3.0/whatsnew/3.0.html#integers) document for reference.

**Comment by abadger** [comment]
First an explanation of our python3 roadmap:
- We're working on python3 compatibility in the v2_final branch (will be merged back to devel soon).
- The plan is for python2.6+ and python3.x+ compatibility where "x" is  the current latest version of python3.  We're not planning on officially supporting python3 yet but we will take pull requests to fix things that are incompatible.
- This compatibility and willingnes to take pull requests is for the pieces of ansible that run on the "controller".  Where you invoke ansible, ansible-playbook, etc.
- For the modules and supporting code that runs on the "managed" machines we have not yet worked out what to do.  The modules have to be compatible with python2.4 which makes py2+py3 compatibility harder.
- Of note is that the module_utils directory in ansible/ansible is used by the modules and thus must be python2.4 compatible.

Okay, with that background... I just ran `2to3 -f numliterals lib/ansible` on the v2_final branch.  There appears to be several places in module_utils that use octal literals and several modules.  Those cannot be fixed until a plan for python2.4 compatibility is arrived at.

`ansible/plugins/connections/paramiko_ssh.py` also uses octal with the old-style literal.  I'll fix that now.

**Comment by abadger** [comment]
Fixed in: https://github.com/ansible/ansible/commit/7733dc7bb51dd1632babfbdf90e6c305cc5764a7

If you'd like to help figure out the python2.4 and python3 compatibility problems, feel free to start a conversation on the mailing list.  There have been various threads there but we have not yet touched the question of python2.4 compatibility.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by cjdrake** [comment]
Thanks for the info, @abadger.
