### ISSUE TITLE
failed to create temporary content file: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by gaecom** [ansible/ansible#10938]
In uri.py file，it always report  error msg when i run ansible-playbook to download a file from internet,the error message is  "failed to create temporary content file: 'ascii' codec can't encode character u'\x89' in position 0: ordinal not in range(128)". 

it seems that the code cant catch UnicodeEncodeError.

 As i change the code **_unicode(content.decode('raw_unicode_escape'))**_  to  **_str(content, encoding='utf-8', errors = 'ignore')**_ in uri.py,the error  disappeared and can be catched.

``` python
        try:
            return r, unicode(content.decode('raw_unicode_escape')), dest
        except:
            return r, content, dest
```

**Comment by abadger** [comment]
If I recall the code correctly, this line is causing the error but the error is actually being thrown elsewhere.  That's why it appears that the error isn't being caught... that other place doesn't have a try: except.

Both the present code and your proposed code have problems.  The present code is turning a byte str into unicode twice, it doesn't account for the need to have a byte str when writing the file, and raw_unicode_escape implicitly uses latin-1 encoding which is often wrong.  Your code is turning a byte str into a byte str and it doesn't account for the fact that json serialization may require a unicode string to work.

I'm looking at some solutions but I've been hampered by not knowing if the escape portion of the raw_unicode_escape codec is important there.  I'm leaning towards it not being important but want to test some more before committing to that.

**Comment by abadger** [comment]
I think ansible/ansible-modules-core#1331 will fix this issue. Please give it a try. I'm closing this issue in favor of the PR since the issue needs to be tracked on the ansible-modules-core repository anyway.

**Comment by anthonygreen** [comment]
Still getting this issue with the uri module ansible 1.9.2

**Comment by abadger** [comment]
@anthonygreen Looks like it was pushed to the devel branch but since I never heard back from anyone having tested it it wasn't pushed to the stable-1.9 branch (There's a lot of related tickets that could potentially regress from touching this code... I was hoping at least some of those people would respond that the changes didn't cause their issues to crop up again).  I'll ask around and see if other committers are comfortable promoting this to the stable branch.

**Comment by abadger** [comment]
Pushed to stable-1.9:

https://github.com/ansible/ansible-modules-core/commit/6906760d46b8afb884c5340415a17df315afd1b2
