### ISSUE TITLE
[PATCH] Unhelpful stack trace if inventory fails

### ISSUE THREAD

**Issue by porridge** [ansible/ansible#10955]
TL;DR: add ", no_exceptions=True" to the utils.parse_json() call here:
https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/script.py#L61

If one uses an inventory script, and its output fails to parse as JSON for whatever reason, the user is presented with unhelpful trace such as the following. It looks like inventory/script.py _parse is already prepared to produce a much nicer error message (including the stderr of the script), but fails to invoke parse_json() in a way that would allow it to detect errors.

```
 Traceback (most recent call last):
   File "/usr/bin/ansible-playbook", line 324, in <module>
     sys.exit(main(sys.argv[1:]))
   File "/usr/bin/ansible-playbook", line 160, in main
     inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
   File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 118, in __init__
     self.parser = InventoryScript(filename=host_list)
   File "/usr/lib/pymodules/python2.7/ansible/inventory/script.py", line 49, in __init__
     self.groups = self._parse(stderr)
   File "/usr/lib/pymodules/python2.7/ansible/inventory/script.py", line 57, in _parse
     self.raw  = utils.parse_json(self.data)
   File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 551, in parse_json
     results = json.loads(data)
   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
     return _default_decoder.decode(s)
   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
     raise ValueError("No JSON object could be decoded")
 ValueError: No JSON object could be decoded
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible -m ping -i inv.sh all
 [ERROR]: ERROR! failed to parse executable inventory script results from
/root/testing/10955/inv.sh: data needs to be formatted as a json dict
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
