### ISSUE TITLE
Have available modules in a variable

### ISSUE THREAD

**Issue by kodfodrasz** [ansible/ansible#10952]
Currently available modules is not available in a variable for use in a conditional.

**Comment by bcoca** [comment]
This would require pre-loading all the modules, which we currently do not do, it would also clash with play/role loadable modules.

**Comment by jimi-c** [comment]
As this has been open for quite a while with no traction, we're going to go ahead and close it now. If you'd like to restart the conversation on the devel mailing list please feel free to do so:

   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
