### ISSUE TITLE
BUG: can't create GCE instances  (GCE module; affects > 1.8.4)

### ISSUE THREAD

**Issue by kevinschumacher** [ansible/ansible#10998]
#### Issue Type

BUG
#### Ansible Version

ansible 1.9.1 configured module search path = None

Note: this works in 1.8.4
#### Ansible Configuration

clean, defaults as installed by pip
#### Environment

running from Mac OS X 10.10; apache libcloud 0.17
#### Summary

Using the GCE module, I am no longer able to create GCE instances. This is a regression, as this same playbook works under 1.8.4
##### Playbook

(as `test-gcp.yml`)

```

---
    - name: deploy GCE instances
      hosts: gcp
      connection: local
      gather_facts: no
      vars:
        #needed for libcloud:
        project_id: project-id
        service_account_email: service-account-email@developer.gserviceaccount.com
        pem_file: /path/to/pem/test.pem

        #instance configuration:
        zone: us-central1-a
        machine_type: g1-small
        image: debian-7
        network_name: default

      tasks:
        - name: launch instances
          gce:
            service_account_email: "{{ service_account_email }}"
            pem_file: "{{ pem_file }}"
            project_id: "{{ project_id }}"

            name: "{{ inventory_hostname }}"
            zone: "{{ zone }}"
            machine_type: "{{ machine_type }}"
            image: "{{ image }}"
            network: "{{ network_name }}"  
          register: gce_result
```
##### Inventory

(as `demo-inventory`)

```
[gce]
server1
```
##### Environment setup

```
$ virtualenv test-cant-create-gce --no-site-packages 
$ source test-cant-create-gce/bin/activate 
$ pip install apache-libcloud==0.17 ansible==1.9.1
$ gcloud auth login
```

Running `gcloud auth login` should set up your private key in the right place (`~/.ssh/google_compute_engine`)
##### Command:

(in a shell script)

```
export SSL_CERT_FILE=$(pwd)/cacert.pem
export ANSIBLE_HOST_KEY_CHECKING=False

if [[ ! -f "$SSL_CERT_FILE" ]]; then
      curl -O http://curl.haxx.se/ca/cacert.pem
fi

ansible-playbook -i ./demo-inventory --private-key=~/.ssh/google_compute_engine  test-gcp.yml
```
#### Expected Results

Instance to be created in GCE; successful run of playbook
#### Actual Results

```

PLAY [deploy GCE instances] *************************************************** 

TASK: [launch instances] ****************************************************** 
failed: [server1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/kschumache007/.ansible/tmp/ansible-tmp-1431465807.35-127872674163139/gce", line 2204, in <module>
    main()
  File "/Users/kschumache007/.ansible/tmp/ansible-tmp-1431465807.35-127872674163139/gce", line 497, in main
    module, gce, inames)
  File "/Users/kschumache007/.ansible/tmp/ansible-tmp-1431465807.35-127872674163139/gce", line 356, in create_instances
    external_ip=external_ip, ex_disk_auto_delete=disk_auto_delete)
TypeError: create_node() got an unexpected keyword argument 'ex_can_ip_forward'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/kschumache007/gcp-test.retry

server1                    : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules in ansible are now moved two separate repos. We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:

https://github.com/ansible/ansible-modules-extras
If this is about an existing module:

Find the module at http://docs.ansible.com/list_of_all_modules.html
Open the documentation page for that module
If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
Otherwise, submit your module to https://github.com/ansible/ansible-modules-core
Additionally, should you need more help with this, you can ask questions on:

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
Thanks!

**Comment by kevinschumacher** [comment]
Created issue in ansible-modules-core:
https://github.com/ansible/ansible-modules-core/issues/1319

Thanks
