### ISSUE TITLE
Conditional imports does'nt work

### ISSUE THREAD

**Issue by maethor** [ansible/ansible#10990]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
##### Ansible Configuration:

```
[defaults]

sudo_user=root
ask_sudo_pass=true
forks=50
pipelining=True
fact_caching=redis
fact_caching_timeout=86400
```
##### Environment:

I'm using Debian Stretch on my laptop, Debian 7/8 and CentOS 7 on my servers.
##### Summary:

Conditional imports (http://docs.ansible.com/playbooks_conditionals.html#conditional-imports) doesn't work as expected.
##### Steps To Reproduce:

I have this playbook:

```

---
- hosts: all:!services
  vars_files:
    - [ "vars/{{ ansible_os_family }}.yml", vars/default_os.yml ]
  tasks:
    - debug: var=sudo_group
```

vars/RedHat.yml contains:

```

---
sudo_group: wheel
```

vars/default_os.yml contains:

```

---
sudo_group: sudo
```
##### Expected Results:

This is what I get when I only put `- [ "vars/{{ ansible_os_family }}.yml"]` in `vars_files`

```
PLAY [all:!services] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test-centos01.sysnove.net]
test-centos01.sysnove.net: importing vars/RedHat.yml

TASK: [debug var=sudo_group] ************************************************** 
ok: [test-centos01.sysnove.net] => {
    "var": {
        "sudo_group": "wheel"
    }
}

PLAY RECAP ******************************************************************** 
test-centos01.sysnove.net  : ok=2    changed=0    unreachable=0    failed=0 
```
##### Actual Results:

This is what I get with `- [ "vars/{{ ansible_os_family }}.yml", vars/default_os.yml]`.

```
PLAY [all:!services] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test-centos01.sysnove.net]

TASK: [debug var=sudo_group] ************************************************** 
ok: [test-centos01.sysnove.net] => {
    "var": {
        "sudo_group": "sudo"
    }
}

PLAY RECAP ******************************************************************** 
test-centos01.sysnove.net  : ok=2    changed=0    unreachable=0    failed=0 
```

Thanks.

**Comment by abadger** [comment]
I haven't used this feature much myself but I see in the documentation you linked to that you need to have either facter or ohai installed in order for that to work.  Which one do you have installed?

**Comment by maethor** [comment]
I have facter and ruby(gem)-json installed. But I can't see how this could be relevant. The `ansible_os_family` variable is not computed by facter, but by ansible itself.

**Comment by jimi-c** [comment]
Hi @maethor, there are two problems here. First off, you have the vars_files entered as a "list of lists" - it only needs to be a list, so you can use the following syntax:

<pre>
- hosts: all:!services
  vars_files:
    - vars/default_os.yml
    - "vars/{{ ansible_os_family }}.yml"
  tasks:
    - debug: var=sudo_group
</pre>

or

<pre>
- hosts: all:!services
  vars_files: [ vars/default_os.yml, "vars/{{ ansible_os_family }}.yml"]
  tasks:
    - debug: var=sudo_group
</pre>

Second, and most critical to your problem - the order of the vars_files is important, as they are processed in order. This means if two files contain the same variable name, whichever is listed last will "win". To fix your problem, you really should be using `include_vars` with the `with_first_found` option, or simply list the more specific one last.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
@maethor my apologies, I didn't realize this was a feature. I've corrected it in devel as of now, so this should work as expected.

<pre>
# cat test.yml 
- hosts: all:!services
  vars_files:
    - [ "vars/{{ ansible_os_family }}.yml", vars/default_os.yml ]
  tasks:
    - debug: var=sudo_group
# ansible-playbook -vv test.yml -i localhost, -c local
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [debug var=sudo_group] *****************************************************
ok: [localhost] => {
    "changed": false, 
    "sudo_group": "wheel"
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

**Comment by maethor** [comment]
Thank you @jimi-c
