### ISSUE TITLE
Git clone with submodules error

### ISSUE THREAD

**Issue by fbrbovic** [ansible/ansible#10993]
Issue Type:

Bug Report.

Ansible Version:

Ansible 1.9.1

Ansible Configuration:

No Changes

Environment:

Centos 7 with tower installed 

Summary:

When cloning a repo which has submodules, I am getting an error 
`msg: Unable to determine hashes of submodules`

And I see that main parent repo is cloned but not the submodules. 

I have this for the command

```
- name: Clone project files 
  git: repo={{ repo }} dest={{ dest_path }}/release/{{ version }} version={{ version }} depth=1 accept_hostkey=yes key_file=/home/deploy/.ssh/id_rsa_github
```

Can someone tell me is that error coming from git  or from ansible.  When I do  a clone form the server directly, It all clones properly without an error.

**Comment by abadger** [comment]
We have integration tests checking whether submodules work with ansible's git module so this is likely a problem with git or the specific parameters being used here.  Could be a cornercase that ansible does not handle, though.  Probably best to ask about this on the mailing list.  Hopefully someone there will be able to figure out what you could change to make this work or else we can narrow it down to something reproducible that points to a bug in ansible.

If it is a bug in ansible, we should open the new bug on the ansible-modules-core repo, https://github.com/ansible/ansible-modules-core , since that's where the git submodule lives ;-)

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jawngee** [comment]
I just wanted to note that it is likely to do with the _url_ for your submodule using _http_ and not _ssh_.

I just ran into this issue, changed the submodule's source url's to ssh from http and everything went without error afterwards.
