### ISSUE TITLE
Allow adding paths to module path

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#11000]
##### Ansible Version: 1.9.1

or any other newer version probably
##### Summary:

 I would like to extend the default module path, to add an extra module to ansible, but this is not possble in a cross-distro compatible way, since it is only possible to overwrite the module path not to append or prepend dirs to it.
##### Steps To Reproduce:

```
export ANSIBLE_LIBRARY $PWD/library:
```
##### Expected Results:

This should prepend `$PWD/library` to the library path
##### Actual Results:

The library path become `$PWD/library`, the default modules are not found anymore.

**Comment by bcoca** [comment]
you can drop the module in a library/ dir relative to your plays or inside a loaded role

**Comment by jimi-c** [comment]
The module path is listed as a `pathlist` type in constants.py, so it should work fine to create a standard path list on any distro:
<pre>
DEFAULT_MODULE_PATH       = get_config(p, DEFAULTS, 'library',          'ANSIBLE_LIBRARY',          None, value_type='pathlist')
</pre>
And as @bcoca pointed out above ./library is already picked up (not sure if that was just a basic example or what but it shouldn't be a problem to do others using a path list as above).

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
