### ISSUE TITLE
Copy content from variable to file

### ISSUE THREAD

**Issue by flmmartins** [ansible/ansible#11012]
Hello All,

I need to put a vaulted file in a file inside my server. 
As this is not yet supported by ansible, I have looked many solutions for these like using lookups (https://github.com/ansible/ansible/pull/8110 - it didn't work), using template files (http://stackoverflow.com/questions/22773294/how-to-upload-encrypted-file-using-ansible-vault - generate new lines in the file) and with copy module as described in previous link.
With the copy module using the long sintax (link above) was the way I found to pass a vaulted variable b but I need my destination to use a path provided by another variable like this:

(Declared in a vars)
app_path: /opt

``` bash
 - copy:
      content: "{{ mycert }}"
      dest: {{app_path}}/config/public.pem
```

Infortunately I was not able to use {{app_path}} with destination WITH THE LONG SINTAX. I tried the following:

``` bash
 - copy:
      content: "{{ mycert }}"
      dest: "{{app_path}}"/config/public.pem
```

And

``` bash
 - copy:
      content: "{{ mycert }}"
      dest: "{{app_path}}/config/public.pem"
```

None of  those worked. Does someone knows why is that? I am running Ansible 1.7.2

**Comment by bcoca** [comment]
First i would advise using the template module instead, copy's content was not meant to support anything but trivial values. 
- the first example will not work because YAML will see the initial '{' and expect a dictionary
- the 2nd will not work because when you start a YAML value with a quote, the whole value must be contained in that quote pair.
- the 3rd 'should work' at least for dest

We need more info for debuggin as 'does not work' can mean many things, please provide specific errors

**Comment by bcoca** [comment]
since there has been no responses to the info request, i'm marking this ticket for closure.

**Comment by smrutikanta** [comment]
I want to write my xml format var into a file
How can I do it?
