### ISSUE TITLE
RPM installation fails when /etc/ansible/hosts is a directory

### ISSUE THREAD

**Issue by knh1** [ansible/ansible#11033]
Issue Type: Bug Report

Ansible Version: ansible 1.8.3 (attempting upgrade to 1.9.1)

Ansible Configuration: /etc/ansible/hosts is a directory with two flat files and two sub-directories (group_vars and host_vars)

Environment: SLES 11 SP3

Summary: Installing the RPM from repo http://download.opensuse.org/repositories/systemsmanagement/SLE_11_SP3/ fails when /etc/ansible/hosts is a directory.

Steps To Reproduce:
1. Rename, move, or delete existing /etc/ansible/hosts file.
2. Create /etc/ansible/hosts as a directory
3. Attempt installation of latest RPM version

Expected Results: Ignore cpio error when /etc/ansible/hosts is a directory or install default hosts template into /etc/ansible/hosts if it exists as a directory.

Actual Results: RPM installation fails with the error "error: unpacking of archive failed on file /etc/ansible/hosts: cpio: rename failed - Is a directory".

Workaround Steps:
1. Rename /etc/ansible/hosts directory to /etc/ansible/hosts.bak
2. Install updated RPM package
3. Remove /etc/ansible/hosts file installed by RPM package
4. Rename /etc/ansible/hosts.bak directory to /etc/ansible/hosts

**Comment by abadger** [comment]
Unfortunately, this is a problem with the rpm packaging that you're getting from OpenSuse.  So you'll have to file a bug report with them about the problem.

https://en.opensuse.org/openSUSE:Submitting_bug_reports

# Should This Be Filed Elsewhere?

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this:
- The rpm that you are attempting to upgrade with is being created by the OpenSuSE project.  Unfortunately we don't control how that rpm is packaged so we aren't able to correct any problems with it.  In this case, it is a problem with packaging (the rpm won't install cleanly) rather than a code bug inside of ansible so opensuse will need to fix the problem.

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by knh1** [comment]
That makes sense.  Thanks for providing the link to submit the bug report to OpenSUSE.
