### ISSUE TITLE
Feature request: report time each task took to complete

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#11038]
It would be great to see how much time task takes on each host. Especially if you leave ansible working and find it done or failed in tens of minutes or even hours.

**Comment by jhawkesworth** [comment]
There are a couple of callback plugins around that will report task
timings, might give you what you need. I think there's one called something
like profile_tasks.py that reports longest running tasks. Can't find where
I got it from right now but I think it was on github somewhere.

**Comment by bcoca** [comment]
https://github.com/jlafon/ansible-profile/blob/master/callback_plugins/profile_tasks.py

**Comment by hryamzik** [comment]
Thanks! I'll give it a try. I still think it would be great to have this info by default.

**Comment by senorsmile** [comment]
This has been added in v2.0 as an available callback plugin (ported from jlafon's original work).  I agree that having this as a default would be great!

**Comment by rharrison10** [comment]
I haven't found the feature for 2.x in the docs. Could you help me with a link. Wonderful improvement I'd love to use it, especially in testing!

**Comment by senorsmile** [comment]
@rharrison10 see the most recent ansible.cfg at: 
https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg

and the list of available callbacks built in here: 
https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/callback

In short, make sure you uncomment the following
#callback_whitelist = timer, mail

and then add 'profile_tasks' to the list

For example, this my my callback_whitelist
callback_whitelist = timer, profile_tasks

**Comment by jimi-c** [comment]
Per the above discussion, I'm going to close this now. The perf callback is not the default, as not everyone would want that, however in 2.0+ it's very easy to enable it.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
