### ISSUE TITLE
Single * pattern not working

### ISSUE THREAD

**Issue by elouanKeryell-Even** [ansible/ansible#11039]
##### Issue Type:

Bug Report
##### Ansible Version:

`$ ansible --version`
`ansible 1.9.1`
`configured module search path = None`
##### Ansible Configuration:

I think I changed nothing to the base configuration.
##### Environment:

Centos 7
##### Summary:

In the [docs](docs.ansible.com/intro_patterns.html) it says it is possible to use a single \* pattern to target every host, but it doesn't seem to work for me.
##### Steps To Reproduce:

`$ ansible * -m ping`
##### Expected Results:

Same result as `$ ansible all -m ping`, which is working fine for me.
##### Actual Results:

`Usage: ansible <host-pattern> [options]`

**Comment by elouanKeryell-Even** [comment]
I think the doc page I was reading was oriented towards playbooks, not command line, which explains the problem.

**Comment by abadger** [comment]
@ekeryelleven Can you try this:

`ansible '*' -m ping`

I use the star frequently in this manner.  You have to quote or escape the *, though, otherwise the shell will interpret it before ansible gets a chance to see it and substitute the filenames in the current directory in its place.  if you need further help on this, probably should take it to the mailing list as I don't believe there's any code that needs to be modified here.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by elouanKeryell-Even** [comment]
Works like a charm, thanks a lot for the piece of information, and sorry for the disturbance!
