### ISSUE TITLE
Ubuntu ppa: ansible does not even run

### ISSUE THREAD

**Issue by COLABORATI** [ansible/ansible#11054]
wow. ansible does not even run: 

```
xxx@xxx ~/Code/devops/> ansible
Traceback (most recent call last):
  File "/usr/bin/ansible", line 36, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```

**Comment by abadger** [comment]
I'm not able to reproduce this:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
badger@ubuntu14:~$ ansible
Usage: ansible <host-pattern> [options]

Options:
[...]
$ dpkg -p ansible
Package: ansible
Priority: optional
Section: admin
Installed-Size: 4189
Maintainer: Michael DeHaan <michael.dehaan@gmail.com>
Architecture: all
Version: 1.9.1-1ppa~trusty
[...]
```

Probably the quickest way for you to get up and running is to post more details to the mailing list so that the many people present there can try to figure out what's going wrong in your environment.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by COLABORATI** [comment]
Ah, ok, I was lazy, sorry. "Environment" triggered me to remember that I am using pyenv - I had to set the pyenv shell environment to 'system'. To avoid lazy people like me asking such things, I would like to suggest to add this as a note  to the installation manual:

If you are using [pyenv](https://github.com/yyuu/pyenv), please do not forget to set the used environment to 'system' like this:

```
pyenv shell system
```

Have a nice weekend!
