### ISSUE TITLE
about function '_execute_module' code wrong?

### ISSUE THREAD

**Issue by ozhiwei** [ansible/ansible#11065]
look code.

lib/ansible/runner/**init**.py:1280

```
basefile = 'ansible-tmp-%s-%s' % (time.time(), random.randint(0, 2**48))
```

lib/ansible/runner/**init**.py:535

```
if "tmp" in tmp and not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files and delete_remote_tmp:
```

the `"tmp" in tmp` expression is always True

**Comment by bcoca** [comment]
i'm not sure if this is a bug or a code question. IIRC the tmp variable is by default set to ~/.ansible/tmp and configurable by the user, I believe this check just makes sure that this or the optional /tmp is being used and avoids deleting files if for some reason the user is pointing at a non temporary directory.

**Comment by jimi-c** [comment]
@uhe1231 this is not an issue, but more of a question. If you are still curious in regards to this code, please redirect it to the ansible-devel mailing list.
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
