### ISSUE TITLE
synchronize always say "changed"

### ISSUE THREAD

**Issue by urajio** [ansible/ansible#11066]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
  configured module search path = None
##### Ansible Configuration:

[defaults]
inventory       = ~/inventory
##### Environment:

Running at: Mac OS X 10.10.3
Managing: Debian 7.8
##### Summary:

synchronize works, but always set state "changed" as result.
##### Steps To Reproduce:

file "inventory":

```
[office-servers]
server1 ansible_ssh_host=192.168.1.1

[office-servers:vars]
ansible_ssh_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa_office
```

file "office-servers.yml':

```
- hosts: office-servers
  remote_user: root
  gather_facts: no
  roles:
    - firehol
```

file "roles/firehol/tasks/main.yml":

```
- name: Sync common files
  synchronize: archive=no recursive=yes times=yes perms=yes checksum=yes src=common/etc/firehol/ dest=/etc/firehol
```
##### Expected Results:

```
First run return "changed", following runs - "ok"
```
##### Actual Results:

```
ansible-playbook office-servers.yml 

PLAY [office-servers] ********************************************************* 

TASK: [firehol | Sync common files] ******************************************* 
changed: [server1 -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
server1                  : ok=1    changed=1    unreachable=0    failed=0  
```

**Comment by henryon** [comment]
can you rerun the code with -vvv ,then you can get more detail about this task

**Comment by urajio** [comment]
I found the problem - I have two tasks synchronize to same directory, so './' always changes.

**Comment by nh2** [comment]
Note: This can also happen when you use `archive: no` and don't enable `times: yes` (equivalent to e.g. `rsync -r`) - it will update the modification times each time the task is run, and so it'll show up as `changed`.

You can see that in the `-vvv` output, it'll look like `<<CHANGED>><f..T...... yourfilename` (where I think that `T` stands for the timestamp being updated).

**Comment by frank-carnovale** [comment]
Thanks so much for comment about times: yes.    Was really struggling with that.  Deserves a mention in the reference documentation.

**Comment by thalesmello** [comment]
I spent quite a while understanding the issue I was having with `synchronize`, trying to figure out the stdout debug info, so I hope this commend can save people time in the future.

The first thing you want to do it to effectively debug the output of synchronize module.

```
# In your task:
    - name: Copy Foo files
      register: files
      synchronize:
        src: ./foo/
        dest: ~/foo/
        rsync_opts: ["-i"] # this is to itemize the changes and make it easier to debug
    - debug: var=files.stdout_lines
```

That was outputting to me something like:

```
TASK [debug] ***********************************************************************************
ok: [foo_instance] => {
    "files.stdout_lines": [
        ".d..t....... ./"
    ]
}
```

If you go to the rsync man page, you get something like:

```
       -i, --itemize-changes
              Requests a simple itemized list of the changes  that  are  being
              made to each file, including attribute changes.  This is exactly
              the same as specifying --out-format='%i %n%L'.
```

Further ahead:

```
              The "%i" escape has a cryptic output that is  11  letters  long.
              The  general  format is like the string YXcstpogfaxn, where Y is
              replaced by the type of update being done, X is replaced by  the
              file-type,  and  the other letters represent attributes that may
              be output if they are being modified.
```

So the `.d..t.......` is the `%i` in the stdout and corresponds to the changes made to the file. `d` indicates it's a folder, and `t` indicates the time was updated, and apparently it was caused by any sort of process you might be integrating with ansible. The second part of the output was `./`, indicating it was the root folder of the synchronization.

Based on @nh2 and @frank-carnovale, the solution was to use `times: no` in my synchronize task.

Hopefully this comment might make it easier for people facing this issue in the future. Remember to look at the `rsync` documentation if you find a slightly different issue than this.
