### ISSUE TITLE
ansible-playbook --limit doesnt filter correctly when playbooks has the same host ip.

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#11071]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.9.1
##### Ansible Configuration:

default
##### Environment:

Debian 8 64bit
##### Summary:

If I have two different plays configured on the same remote host ansible-playbook --limit doesnt filter correctly. It wants to run both plays on the host.
##### Steps To Reproduce:

hosts.yml

```
[web]
18.18.10.16
18.18.10.17

[crontab]
18.18.10.16
```

deploy.yml

```

---
 - hosts: web
   serial: 1
   roles:
     - web

 - hosts: crontab
   serial: 1
   roles:
     - crontab
```

```
ansible-playbook -i hosts.yml -l crontab deploy.yml --list-hosts

playbook: deploy.yml

  play #1 (web): host count=1
    18.18.10.16

  play #2 (crontab): host count=1
    18.18.10.16
```
##### Expected Results:

It should only run the playbook that matches "crontab" not both playbooks which is on the common ip.
##### Actual Results:

Even if I say with --limit to only play the hosts tagged "crontab" it wants to run my other playbook which is also configured for the same ip.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

So the limit applies a filter ON TOP of the existing hosts: lines, in this case is the equivalent of the following:
- hosts: web:&crontab
  ...
- hosts: crontab:&crontab

and resolve the hosts remaining in the list, since you have a host common to the web and crontab groups, it will execute the first play. You might want to look into tags instead if you just wan't to execute one play and not the other.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
