### ISSUE TITLE
path arguments are not being templated correctly

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#11085]
I have the following playbook:

``` ---
- hosts: "{{ target }}"
  name: 'sync repos'  
  gather_facts: no
  tasks:
    - debug: var="{{ ansible_ssh_user }}"    
    - synchronize: times=yes compress=no archive=no delete=yes dest="/home/{{ ansible_ssh_user }}/hgdata/sfdc-ops1" recursive=yes src="/home/{{ local_user }}/hgdata/sfdc-ops/"     
```

The output when running this is as follows:

```
*PLAY [sync repos] ************************************************************* 

TASK: [debug var="{{ ansible_ssh_user }}"] ************************************ 
ok: [httpd] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [db] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [api] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [kibana] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [es] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [logstash] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}
ok: [ldap] => {
    "var": {
        "ubuntu": "ubuntu"
    }
}

TASK: [synchronize times=yes compress=no archive=no delete=yes dest="/home/{{ local_user }}/hgdata/sfdc-ops1" recursive=yes src="/home/{{ ansible_ssh_user }}/hgdata/sfdc-ops/"] *** 
failed: [ldap -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh -i files/keys/sv-test.pem -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/seb/hgdata/sfdc-ops/\" \"ubuntu@test.com:/home/seb/hgdata/sfdc-ops1\"", "failed": true, "rc": 11}
msg: rsync: mkdir "/home/seb/hgdata/sfdc-ops1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]

failed: [api -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh -i files/keys/sv-test.pem -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/seb/hgdata/sfdc-ops/\" \"ubuntu@test.com:/home/seb/hgdata/sfdc-ops1\"", "failed": true, "rc": 11}
msg: rsync: mkdir "/home/seb/hgdata/sfdc-ops1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]

failed: [httpd -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh -i files/keys/sv-test.pem -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/seb/hgdata/sfdc-ops/\" \"ubuntu@test.com:/home/seb/hgdata/sfdc-ops1\"", "failed": true, "rc": 11}
msg: rsync: mkdir "/home/seb/hgdata/sfdc-ops1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]

failed: [es -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh -i files/keys/sv-test.pem -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/seb/hgdata/sfdc-ops/\" \"ubuntu@test.com:/home/seb/hgdata/sfdc-ops1\"", "failed": true, "rc": 11}
msg: rsync: mkdir "/home/seb/hgdata/sfdc-ops1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]

failed: [kibana -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh -i files/keys/sv-test.pem -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/seb/hgdata/sfdc-ops/\" \"ubuntu@test.com:/home/seb/hgdata/sfdc-ops1\"", "failed": true, "rc": 11}
msg: rsync: mkdir "/home/seb/hgdata/sfdc-ops1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]

^C32
ERROR: interrupted
```

The issue is that in the dest path the ansible_ssh_user variable is not replaced correctly, instead of "ubuntu@test.com:/home/seb/hgdata/sfdc-ops1" it should be ubuntu@test.com:/home/ubuntu/hgdata/sfdc-ops1

Sebi Calbaza

**Comment by sebi-hgdata** [comment]
One more thing, if I remove the debug task,  the "ubuntu@..." will be incorrectly set to "seb@..." which is my local user

**Comment by bcoca** [comment]
A few things:

For the syncronize module you should open tickets in the ansible-modules-core repo, but in this case it does not seem to be a syncronize issue as modules are not in charge of templating, ansible itself is.

Also, the proper use of debug is :
`- debug: var=ansible_ssh_user`
or 
``- debug: msg={{ansible_ssh_user}}` 
otherwise you are 'double templating' which can lead to more confusion.

As for locating the issue,  where do you set ansible_ssh_user? local_user?

**Comment by sebi-hgdata** [comment]
Hey,
  ansible_ssh_user is set in the inventory file and  local_user is set in the all group vars file.
Ansible version  :
  seb@sebi:~$ ansible --version
ansible 1.9.1
  configured module search path = None

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vvv test.yml -e ansible_ssh_user=testing
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: sync repos ****************************************************************
TASK [debug var=testing] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ ansible_ssh_user }}": "testing"
}
TASK [synchronize src=/root/testing/11085/src/ recursive=yes dest=/tmp/testing/11085/ delete=yes compress=no archive=no times=yes] ***
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436929722.13-249601400189553 && echo $HOME/.ansible/tmp/ansible-tmp-1436929722.13-249601400189553
127.0.0.1 PUT /tmp/tmpIbBluR TO /root/.ansible/tmp/ansible-tmp-1436929722.13-249601400189553/synchronize
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1436929722.13-249601400189553/synchronize; rm -rf /root/.ansible/tmp/ansible-tmp-1436929722.13-249601400189553/ >/dev/null 2>&1
changed: [localhost] => {"changed": true, "cmd": "rsync --delay-updates -F --delete-after --recursive --times --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/root/testing/11085/src/\" \"/tmp/testing/11085/\"", "invocation": {"module_args": {"archive": "no", "compress": "no", "delete": "yes", "dest": "/tmp/testing/11085/", "recursive": "yes", "src": "/root/testing/11085/src/", "times": "yes"}, "module_name": "synchronize"}, "msg": ".d..t...... ./\n>f+++++++++ a\n>f+++++++++ b\n>f+++++++++ c\n", "rc": 0, "stdout_lines": [".d..t...... ./", ">f+++++++++ a", ">f+++++++++ b", ">f+++++++++ c"]}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
