### ISSUE TITLE
The file module won't delete directories with recursive=yes

### ISSUE THREAD

**Issue by ryanschulze** [ansible/ansible#11087]
**Ansible Version:**

tested with 

ansible 1.9.1
  configured module search path = None

ansible 2.0.0 (devel ac14ad1419) last updated 2015/05/29 10:14:02 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 74e69d1fd1) last updated 2015/04/14 22:57:06 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 4048de9c1e) last updated 2015/04/14 22:57:16 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/14 22:57:33 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 21fce8ac73) last updated 2015/04/14 22:58:02 (GMT +200)
  configured module search path = None

**Ansible Configuration:**

Default ansible configuration from https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg

**Environment:**

Host running Ansible: Ubuntu 15.04
Destinations: Ubuntu 12.04.5 LTS, Ubuntu 14.04.2 LTS

**Summary:**

When trying to delete a directory with the file module, ansible fails if recursive=yes is set

**Steps To Reproduce:**

```
- name: Delete a directory
  hosts: all
  remote_user: root
  tasks:
    - stat: path=/var/tmp/deleteme
      register: somepath

    - debug: var=somepath

    - file: path=/var/tmp/deleteme recurse=yes state=absent
      when: somepath.stat.isdir is defined and somepath.stat.isdir == true
```

**Expected Results:**

The file module should recursively delete directories.

**Actual Results:**

```
failed: [192.168.10.10] => {"failed": true, "gid": 0, "group": "root", "mode": "0700", "owner": "root", "path": "/var/tmp/deleteme", "playbook": "test.yml", "role": null, "size": 6, "state": "directory", "task": "file path=/var/tmp/deleteme recurse=yes state=absent", "uid": 0}
msg: recurse option requires state to be 'directory'
```

The module complains that it can only recursively delete if the state of the path is a directory, even though in the output it says "state": "directory".

**Comment by sysadmin75** [comment]
I don't think this is a bug. 

I added some debug statements in the code and ran the playbook dopefish listed.
[root@apache-server ~]# python /root/.ansible/tmp/ansible-tmp-1433036309.41-108432167483321/file 
DEBUG prev_state: directory
DEBUG state: absent
DEBUG recurse: True
{"group": "root", "uid": 0, "failed": true, "owner": "root", "state": "directory", "gid": 0, "mode": "0755", "msg": "recurse option requires state to be 'directory'", "path": "/var/tmp/deleteme", "size": 4096}

So the state the error message refers to is the state of the file/directory on the remote server, not the state of the file module. Because the state of the file module is obviously set to absent.
The docs specifically states for the recurse option, "recursively set the specified file attributes (applies only to state=directory) (added in Ansible 1.1)", which refers to the state of the file module.

To test this, I removed recurse=yes from the task and the directory and subdirectories were deleted.

**Comment by ryanschulze** [comment]
Ah I see, the usage of the term 'state' is a bit ambiguous in the error message since it isn't clear it is referring to the file module and not to the file/directory in the remote server.

The playbook in question is a pretty old and seldom used, so I don't know when the behavior of the file module was changed causing runs to fail now. But as sysadmin75 pointed out, state=absent is always recursive and the recursive= option only applies to state=directory, so I was just using the module wrong. I'll close the issue since it isn't a bug.
