### ISSUE TITLE
Unicode issues with Ansible 1.8 and up

### ISSUE THREAD

**Issue by silvax** [ansible/ansible#11091]
Im running some Ansible playbooks on ec2 instances created by OpsWorks. Part of the automation reads the ec2 tags from the instance. here is the code for that

```
      - name: gather ec2 facts
        action: ec2_facts

      - name: get environment tag
        action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
        register: allTags
```

Using that information I then do a group by using one of the tags. The main reason to do this is to leverage group_vars and do automation that configures settings differently for environments. In this case the tag name is environment. Code below

```
- group_by: key={{ allTags.tags.environment }}
```

All this worked perfectly in Ansible 1.7. But after 1.8 the playbook fails with the following error. Is intersting to note that the automation works fine with instances that are not spun up by OpsWorks. OpsWorks does add some special tags to the instance. My suspicion is that some of those tags have special characters that are causing some sort of unicode issue. 

```
TASK: [group_by key={{ allTags.tags.environment }}] *************************** 
fatal: [localhost] => template error while templating string: unexpected char u'\x99' at 2600
```

I've tried using quotes in the group_by like this but with the same result

```
- group_by: key="{{ allTags.tags.environment }}"
```

I also tried using a different way of referencing the dictionary value like this

```
- group_by: key={{ allTags['tags']['environment'] }}
```

But had the same results

I tried the recommendation on this thread https://groups.google.com/forum/#!msg/ansible-project/mLgdORSFspo/PXfO76QNfMMJ but still the same issue. 

From what I've read there are some changes in Jinja that cause this behaviour but I have not been able to figure out the issue. Anyone has seen this issue or has some recommendations? Thanks in advance

**Comment by resmo** [comment]
could you test  Ansible v1.9.x? There was a fix to a similar looking issue related to inventory.

**Comment by silvax** [comment]
Hi Rene

I tested with 1.9 with the same result . Thanks

**Comment by jimi-c** [comment]
Hi, this situation appears to be resolved in the devel branch (which will be ansible 2.0). Here is the output using the following playbook and inventory:

<pre>
# cat test.yml 
- hosts: all
  gather_facts: no
  tasks:
  - group_by: key=Ümlaut
- hosts: Ümlaut
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
# cat inv 
host1 Ümlaut=foo ansible_connection=local
host2 Ümlaut=foo ansible_connection=local
host3 Ümlaut=foo ansible_connection=local
host4 Ümlaut=foo ansible_connection=local
host5 Ümlaut=foo ansible_connection=local
# ansible-playbook -vvv test.yml -i inv 
Using /etc/ansible/ansible.cfg as config file
2 plays in test.yml
PLAY: ***************************************************************************
TASK [group_by key=Ümlaut] ******************************************************
changed: [host1] => {"add_group": "Ümlaut", "changed": true}
PLAY: ***************************************************************************
TASK [debug var=inventory_hostname] *********************************************
ok: [host2] => {
    "changed": false, 
    "inventory_hostname": "host2"
}
ok: [host3] => {
    "changed": false, 
    "inventory_hostname": "host3"
}
ok: [host1] => {
    "changed": false, 
    "inventory_hostname": "host1"
}
ok: [host4] => {
    "changed": false, 
    "inventory_hostname": "host4"
}
ok: [host5] => {
    "changed": false, 
    "inventory_hostname": "host5"
}
PLAY RECAP **********************************************************************
host1                      : ok=2    changed=1    unreachable=0    failed=0   
host2                      : ok=1    changed=0    unreachable=0    failed=0   
host3                      : ok=1    changed=0    unreachable=0    failed=0   
host4                      : ok=1    changed=0    unreachable=0    failed=0   
host5                      : ok=1    changed=0    unreachable=0    failed=0   
</pre>

As you can see from the above, the group_by works on the unicode string without errors.

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
