### ISSUE TITLE
pip module hangs when installing from git repos

### ISSUE THREAD

**Issue by andrewyoung1991** [ansible/ansible#11101]
Attempting to install from a requirements.pip file works for all packages registered with PYPI, but if there is a git packege (i.e. `git+http://github.com/Supervisor/supervisor.git@20e47d8b09c0a7700078c99054ad47ca7fd74ae0`), ansible will hang indefinitely.

**Comment by geekofalltrades** [comment]
Probably related to #8625. I'm suffering from this issue right now, too.

**Comment by fuhrysteve** [comment]
You should be able to do something like this in your playbook to specify what pip's default behavior should be when it comes across this:

```
pip: requirements=requirements.txt extra_args='--exists-action=w'
```

See:
http://pip.readthedocs.org/en/stable/reference/pip/#exists-action-option

Unclear to me whether ansible should have some sort of default behavior for this..

**Comment by geekofalltrades** [comment]
I don't see how that addresses this issue. I think the issue we're suffering is that pip is trying to download from a git remote, and is being stopped by an HTTPS or SSH password prompt.

**Comment by miohtama** [comment]
@geekofalltrades Please see https://github.com/ansible/ansible-modules-core/issues/2697

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
