### ISSUE TITLE
with_items accepts a single string which could be a source of trouble

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#11144]
##### Issue Type:

Bug Report, maybe (depending on assessment)
##### Ansible Version:

$ ansible --version
ansible 1.9.1
  configured module search path = None
##### Ansible Configuration:

Default configuration
##### Environment:

Control Machine: Ubuntu 14.04
Target Machines: Ubuntu 14.04
##### Summary:

We use `with_items` extensively to loop over collection variables like this:

```
- debug: 
    msg: 'do stuff with {{ item }}'
  with_items: collection_variable
```

When `collection_variable` is undefined, we'd expect Ansible to throw an error. Instead, the name of the variable is taken literally and is passed as the only item of a one-element-colletion to the task.

This way, a misspelled variable name could lead to all kinds of unwanted side effects.
##### Steps To Reproduce:

Run the following Playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    existing_list:
      - foo
      - bar
      - baz
  tasks:
    # this does stuff to items foo, bar & baz
    - debug:
        msg: 'do stuff with {{ item }}'
      with_items: existing_list

    # this should fail IMO
    # (instead of doing stuff to an item called "nonexistent_list")
    - debug:
        msg: 'do stuff with {{ item }}'
      with_items: nonexistent_list
```
##### Expected Results:

An error in the vein of

```
fatal: [127.0.0.1] => One or more undefined variables: 'nonexistent_list' is undefined
```
##### Actual Results:

```
ok: [127.0.0.1] => (item=nonexistent_list) => {
    "item": "nonexistent_list", 
    "msg": "do stuff with nonexistent_list"
}
```

**Comment by bcoca** [comment]
Sadly this is a 'feature', which as you noted makes a undefined variable indistinguishable from a bare string, which is also allowed in this context. 

We are thinking deprecating it and making this a warning, always requiring explicit templating "{{existing_list}}" in this field. Eventually remove this feature and then accurately report on errors, we have tried making this a hard error in the past but it broke too many playbooks.

**Comment by b6d** [comment]
Thanks for the quick reply! We'll make sure to use explicit templating then.

(Might this be something to change in the [docs](http://docs.ansible.com/playbooks_loops.html#standard-loops) - `with_items: "{{ somelist }}"` instead of `with_items: somelist`?)

**Comment by b6d** [comment]
To answer my own question: Maybe not - `with_items: "{{ somelist }}"` seems to behave differently than `with_items: somelist` (see #11149).

**Comment by jimi-c** [comment]
As of recent (2.2+) versions, Ansible no longer allows bare variables to be use with `with_*` loops in this manner, so I will close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
