### ISSUE TITLE
failed handlers are run multiple times

### ISSUE THREAD

**Issue by ahanwadi** [ansible/ansible#11158]
Easy to reproduce issue where any handler that has error is retried thrice. Is this by design?
Why is this behavior different from normal tasks?

```
root@c036654f83e5:/tmp# cat /tmp/test.yml 
- name: Test Plugins
  hosts: localhost
  sudo: False
  gather_facts: no
  tasks:
    - name: test notify
      command: echo hi
      notify: my handlers

    - name: test notify one
      command: echo "hi 1"
      notify: my handlers

    - meta: flush_handlers

  handlers:
     - name: my handlers
       shell: echo handler && exit 1
       notify: my handlers one

     - name: my handlers one
       command: echo "handler one"
```

```
ansible-playbook -i localhost, /tmp/test.yml  -c local 

PLAY [Test Plugins] *********************************************************** 

TASK: [test notify] *********************************************************** 
changed: [localhost]

TASK: [test notify one] ******************************************************* 
changed: [localhost]

NOTIFIED: [my handlers] ******************************************************* 
failed: [localhost] => {"changed": true, "cmd": "echo handler && exit 1", "delta": "0:00:00.030650", "end": "2015-06-04 02:36:38.193469", "rc": 1, "start": "2015-06-04 02:36:38.162819", "warnings": []}
stdout: handler

FATAL: all hosts have already failed -- aborting

NOTIFIED: [my handlers] ******************************************************* 
failed: [localhost] => {"changed": true, "cmd": "echo handler && exit 1", "delta": "0:00:00.030621", "end": "2015-06-04 02:36:38.270058", "rc": 1, "start": "2015-06-04 02:36:38.239437", "warnings": []}
stdout: handler

FATAL: all hosts have already failed -- aborting

NOTIFIED: [my handlers] ******************************************************* 
failed: [localhost] => {"changed": true, "cmd": "echo handler && exit 1", "delta": "0:00:00.030636", "end": "2015-06-04 02:36:38.346093", "rc": 1, "start": "2015-06-04 02:36:38.315457", "warnings": []}
stdout: handler

FATAL: all hosts have already failed -- aborting

NOTIFIED: [my handlers] ******************************************************* 
failed: [localhost] => {"changed": true, "cmd": "echo handler && exit 1", "delta": "0:00:00.030820", "end": "2015-06-04 02:36:38.422671", "rc": 1, "start": "2015-06-04 02:36:38.391851", "warnings": []}
stdout: handler

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/test.retry

localhost                  : ok=2    changed=2    unreachable=0    failed=4   
```

**Comment by bennojoy** [comment]
@ahanwadi  in which version of ansible are you seeing this behaviour ?

**Comment by ahanwadi** [comment]
root@c036654f83e5:/tmp#   ansible --version
ansible 1.9.0.1
  configured module search path = None

**Comment by ahanwadi** [comment]
Any idea as to why this is happening? I can help fix this if pointed in the right direction.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vvv 11158.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 11158.yml
PLAY: Test Plugins **************************************************************
TASK [test notify] **************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436979421.02-14056187307296 && echo $HOME/.ansible/tmp/ansible-tmp-1436979421.02-14056187307296
127.0.0.1 PUT /tmp/tmpaacLbL TO /root/.ansible/tmp/ansible-tmp-1436979421.02-14056187307296/command
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1436979421.02-14056187307296/command; rm -rf /root/.ansible/tmp/ansible-tmp-1436979421.02-14056187307296/ >/dev/null 2>&1
changed: [localhost] => {"changed": true, "cmd": ["echo", "hi"], "delta": "0:00:01.003802", "end": "2015-07-15 12:57:02.081990", "rc": 0, "start": "2015-07-15 12:57:01.078188", "stderr": "", "stdout": "hi", "stdout_lines": ["hi"], "warnings": []}
TASK [test notify one] **********************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436979422.22-277756917340231 && echo $HOME/.ansible/tmp/ansible-tmp-1436979422.22-277756917340231
127.0.0.1 PUT /tmp/tmpEjHkgB TO /root/.ansible/tmp/ansible-tmp-1436979422.22-277756917340231/command
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1436979422.22-277756917340231/command; rm -rf /root/.ansible/tmp/ansible-tmp-1436979422.22-277756917340231/ >/dev/null 2>&1
changed: [localhost] => {"changed": true, "cmd": ["echo", "hi 1"], "delta": "0:00:00.002689", "end": "2015-07-15 12:57:02.285568", "rc": 0, "start": "2015-07-15 12:57:02.282879", "stderr": "", "stdout": "hi 1", "stdout_lines": ["hi 1"], "warnings": []}
RUNNING HANDLER [my handlers] ***************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436979422.42-21317573740560 && echo $HOME/.ansible/tmp/ansible-tmp-1436979422.42-21317573740560
127.0.0.1 PUT /tmp/tmp_yeMYh TO /root/.ansible/tmp/ansible-tmp-1436979422.42-21317573740560/command
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1436979422.42-21317573740560/command; rm -rf /root/.ansible/tmp/ansible-tmp-1436979422.42-21317573740560/ >/dev/null 2>&1
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": "echo handler && exit 1", 
    "delta": "0:00:00.003214", 
    "end": "2015-07-15 12:57:02.483732", 
    "rc": 1, 
    "start": "2015-07-15 12:57:02.480518", 
    "stderr": "", 
    "stdout": "handler", 
    "stdout_lines": [
        "handler"
    ], 
    "warnings": []
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=1   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
