### ISSUE TITLE
hostvars lookup fallback logic not working as expected

### ISSUE THREAD

**Issue by nathanielks** [ansible/ansible#11176]
I'd like to look up a value in `hostvars` if it exists, otherwise fallback to just returning the key I'm using to do the lookup. If the host doesn't exist, ansible yells and says `host not found: whatever_the_key_is` which makes sense to a degree, but I would think using a Jinja pipe would catch that as a failure and just use the default value?

Example:

``` yaml
- debug: var="{{ hostvars[ item.1 ].ansible_eth0.ipv4.address | default(item.1) }}"
  with_subelements:
    - mysql_users_expanded
    - hosts
```

Here's how `mysql_users_expanded` looks:

``` json
{
   "mysql_users_expanded":[
      {
         "hosts":[
            "app-1"
         ],
         "user":{
            "database":"some_db",
            "group":"app",
            "password":"boogers",
            "user":"db_builder"
         }
      },
      {
         "hosts":[
            "12.34.56.78"
         ],
         "user":{
            "database":"some_db",
            "hosts":[
               "12.34.56.78"
            ],
            "password":"boogers",
            "user":"boogers"
         }
      }
   ]
}
```

Note: I've tried condensing this to just the problem I'm encountering. If you'd like more context, check out the [server fault question](http://serverfault.com/questions/696405/using-ansible-to-provisioning-users-modify-facts-expand-hostvars).

**Comment by sivel** [comment]
The default filter only works one level at a time, it cannot work on deep reference if a parent further up is not defined.

**Comment by nathanielks** [comment]
Aha, I see, I see... any recommendations on catching that earlier? A hack that comes to mind is I can generate a json file locally using templating and then load that as a fact and loop over that. But that does feel hacky. Perhaps there's a more official-y way of doing this?

**Comment by nathanielks** [comment]
I'm trying to test my file solution but it seems like `default`'s behavior isn't as expected, @sivel. The method I'm using to test:

```
- debug: msg="{{ hostvars['12.34.56.78'] | default(false) }}" 
```

Still spits out the error that host is not defined.

Edit: using ansible 1.9.0.1 for reference. Can't use 1.9.1 because of [this](https://github.com/ansible/ansible/issues/10675)

**Comment by bcoca** [comment]
hostvars is 'special' and has some validation on the host existing that you don't find in a normal dictionary

**Comment by nathanielks** [comment]
Gotcha @bcoca :+1:. Fwiw, the file method worked for accomplishing want I wanted to accomplish. Thanks for building an awesome tool!!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
