### ISSUE TITLE
Use of failed_when in v2 always results in fatal

### ISSUE THREAD

**Issue by shawnferry** [ansible/ansible#11172]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel f3f3fb7c49) last updated 2015/06/04 14:05:18 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/04 13:35:34 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/05/31 18:53:16 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/02 18:10:20 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/02 18:10:33 (GMT -400)
  configured module search path = None
##### Summary:

Any use of failed_when in v2 results in failure. Including command exit with rc 0
Behavior in v1 is as expected 
##### Steps To Reproduce:

https://gist.github.com/shawnferry/b1ffad1508927cc58047
##### Expected Results:

failed_when: false should never fail a task
##### Actual Results:

Any use of failed_when task execution

**Comment by sivel** [comment]
I've just submitted a PR (#11174) that addresses this issue.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
