### ISSUE TITLE
Write up architecture for (core) developers

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1117]
Plugins are documented ok already, but this is more about the core.

This need not be on the web documetation, but something like a developers.md in the hacking directory is a good idea.

Explain what files are important, differences in things, etc, maybe some basic ASCII diagrams.

**Comment by jpmens** [comment]
I'd be interested in a short guide as to which bits of Ansible get executed where (ie. on master or on nodes). I haven't spent enough time trying to understand that ...

**Comment by timlnx** [comment]
Funny you should mention that. I made a fancy graph when I was trying to figure out how to incorporate the BYPASS_HOST_LOOP stuff. The pic on my phone turned out OK, here's a link. I can get a higher quality pic at lunch. If you're interested I could even be persuaded to go graphviz on this.

https://www.dropbox.com/s/h0vqjd3m1rmc4km/20121003_105145.jpg

**Comment by mpdehaan** [comment]
Cool.   

Generally graphviz can make it hard for some things to draw out, but it might work because the number of nodes is pretty small.   Worth a shot.  Would make it easy to redraw.  It is my experience that manually drawn diagrams tend to grow unmaintained and are fiddly to play with.

**Comment by jpmens** [comment]
@tbielawa Graphviz would be cool!

**Comment by mpdehaan** [comment]
Let's do this as part of the docs project so "make docs" also calls dot.

I'll volunteer to write the Sphinx page.

**Comment by mpdehaan** [comment]
this changes a bit too much I think, and some refactoring is queued up for 0.9 that will keep changing this.   Don't think it's immediately needed.
