### ISSUE TITLE
"module requires key=value arguments" error in command/shell on v1.9.1-1 but not v2.0.0

### ISSUE THREAD

**Issue by aldanor** [ansible/ansible#11199]
Hi, not sure if this belongs here on in ansible-modules-core, but here goes.

I'm getting a strange error on a `v1.9.1-1` which doesn't seem to occur on git HEAD (v2.0.0) -- command and shell modules would fail in the following manner: 

```
$ ansible all -a ls
myhost | FAILED | rc=0 >>
this module requires key=value arguments (['ls'])
```

(it also happens in playbooks and not just in ad-hoc)

On the latest v2.0.0 it seems to work perfectly fine.

Thanks.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by memelet** [comment]
for 1.9.2-1

I cannot run any ad hoc -using -a, I get the "this module requires key=value arguments" error. Is this closed because we just have to wait for 2.0 to get this back?

**Comment by aldanor** [comment]
Also interested in why this was closed.

**Comment by bcoca** [comment]
closed as this is not a bug, user needs submodule updates, command module is incompatible across 1.9 to 2.0 boundaries.

**Comment by memelet** [comment]
I am running against the released version (1.9.2-1), not source. What would it mean for me to need to submodule updates?

**Comment by ghost** [comment]
This is now the top rated google search for this error. What is the fix? Also using 1.9.2 from pypi.

**Comment by lightblu** [comment]
Just run "git submodule update" which brings your submodules in sync with the main repo, which is required when incompatibilities arise. Had a hard time finding that, while it is most likely out of scope of ansible itself, it would be so nice if ansible could detect this case and tell the user about, on the other hand ignorants like us should just use a released archive.
(Oh, if this is in pypi maybe pypi bundled the wrong versions, I assumed you had a specific ansible version checked out from github like me.)

**Comment by adfernandes** [comment]
So, @bcoca, I understand that in some ways that "this is not a bug, user need submodule updates".

However, the currently released version of ansible is v1.9.2-1. I have packaged this release for MacPorts. MacPorts makes sure that all dependent python packages are at their latest versions.

And the final result is that ansible does not work.

For casual or "hack at home" projects, the idea that "just update your submodules" is a bugfix is fine.

However, as a software engineer for my company exploring unprovisioning software, you've just told me that I should avoid ansible at all costs because if we find and document a bug, it will be ignored with a response that feels like "just run git pull lol".

Software that is released should work, or inform the user that there are version mismatches. I understand that you may not want to support old versions (who does?) but dying with a cryptic error message and a "just git update" is _not_ acceptable for enterprise-grade software.

**Comment by amenonsen** [comment]
@adfernandes I don't actually see where anyone has found and documented a bug here. This ticket is seriously short on useful details.

The error quoted happens when you try to use the v2 `command.py` module with a v1 ansible. I can reproduce it by downloading 1.9.2 from PyPi (https://pypi.python.org/pypi/ansible/1.9.2) and copying `command.py` from my v2 source tree over the equivalent v1 module. But if I **don't** overwrite the v1 module (and not doing so is surely the sensible thing to do), ad-hoc commands work just fine.

> However, the currently released version of ansible is v1.9.2-1. I have packaged this release for MacPorts. MacPorts makes sure that all dependent python packages are at their latest versions.
> 
> And the final result is that ansible does not work.

Here, you seem to be suggesting that if you install Ansible from MacPorts, you get too-new versions of the core modules ("at their latest versions"). Now I don't use MacOS and am not familiar with MacPorts, but if I look at 
https://trac.macports.org/browser/trunk/dports/sysutils/ansible/Portfile (which is for 1.9.1; I can't find whatever you did for 1.9.2-1, sorry), it just appears to use whatever is on PyPi (which contains the correct version of the modules, as I verified above), and its dependencies are httplib2, jinja2, paramiko, and yaml. I can find nothing to suggest that the Ansible core modules are packaged separately (and by definition they aren't supposed to be packaged separately).

There's a `./packaging/macports/sysutils/ansible/Portfile` file in the Ansible source. Of course, I'm not in a position to test it, but it looks like if you use it, you should end up with devel ansible and devel modules.

So how **exactly** are you (or anyone) ending up with v1 ansible and v2 modules? That's the part that needs to be documented for the report to be taken seriously. So far it's more like "it doesn't work lol".

P.S. Looking at the original post here, I would guess that @aldanor had a git clone of ansible.git, and checked out an earlier release without updating the submodules (that _would_ result in v1 ansible running against v2 submodules), and `git submodule update` is _exactly_ the right fix for that. But I have to guess based on the fact that the report mentioned that it worked with HEAD, since there are no other details or any steps to reproduce the problem.

**Comment by adfernandes** [comment]
You have a fair point, @amenonsen.

But the point stands. Github has a tarball release of this repo, and people use it.

It's nice that the `./packaging/macports/sysutils/ansible/Portfile` exits, and it appears that it was used as the basis of the current `Portfile`.

Unfortunately that `Portfile` is currently broken. It requires telling the `git clone` to be `--recursive`. (I have a patch awaiting MacPorts review to fix this.)

So I apologize if I offended, but I was one of those many people who googled for an hour to try to figure out what was going on before I hit this (closed) bug report, and then spent even more time figuring out how to fix it. (How do I update the submodules if I never cloned the git repo?)

My suggestion would be that rather than provide releases, ansible should say "install by cloning the repo, including all submodules" and leave it at that.

**Comment by ghost** [comment]
"The error quoted happens when you try to use the v2 command.py module with a v1 ansible. I can reproduce it by downloading 1.9.2 from PyPi (https://pypi.python.org/pypi/ansible/1.9.2) and copying command.py from my v2 source tree over the equivalent v1 module."

I installed 1.9.2 from PyPi. I DIDN'T COPY ANY SHIT FROM V2 I DONT HAVE V2 AND HAVE NEVER CLONED THE GIT REPO TO START WITH. But I still get the error, in a "user" task no less.

WTF?

**Comment by ghost** [comment]
I got this error from downloading from PyPi, not github. So any responses regarding "just run git submodule" is pointless.

**Comment by amenonsen** [comment]
Lots of outrage, but still no useful details.

I just installed Ansible 1.9.2 on a machine that had no earlier traces of Ansible on it:

```
magpie:~ $ virtualenv /home/ams/ansible
New python executable in /home/ams/ansible/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.
magpie:~ $ cd ansible
magpie:~/ansible $ source bin/activate
(ansible)magpie:~/ansible $ pip install ansible >log 2>&1
(ansible)magpie:~/ansible $ echo $?
0
(ansible)magpie:~/ansible $ which ansible
/home/ams/ansible/bin/ansible
(ansible)magpie:~/ansible $ ansible --version
ansible 1.9.2
  configured module search path = None
(ansible)magpie:~/ansible $ ansible -i'127.0.0.1, ' localhost -m command -a "echo foo bar"
localhost | success | rc=0 >>
foo bar
```

So all I can say is "it works for me".

Update: just for completeness, it also works when I'm connected with ssh without (implied) `-c local`:

```
(ansible)magpie:~ $ ansible -i'127.0.0.1, ' all -c ssh -a ls
127.0.0.1 | success | rc=0 >>
ansible
```

**Comment by adfernandes** [comment]
For anyone who finds this thread via google, the MacPorts ticket is [#48545 ](https://trac.macports.org/ticket/48545) and I have a [pending patch](https://trac.macports.org/attachment/ticket/48545/Portfile.patch) that should fix it. ~~I'll add the patch to this repo's via pull request in a few minutes.~~

Actually, I just looked at the diff between ansible's Portfile and the current Macports one; they've diverged  too much for a quick patch. :disappointed: 

The major changes, if anyone wants to do it, are
- adding the submodule `post-fetch` phase, and
- changing the `reinplace` path fixer-upper

But test, test, test. As always, the official MacPorts version is preferred (usually just because it's been tested heavily).

**Comment by ryandesign** [comment]
> My suggestion would be that rather than provide releases, ansible should say "install by cloning the repo, including all submodules" and leave it at that.

No, the developers of ansible should provide downloadable tarballs that are complete and contain everything needed to install, without the use of the `git` program. The github service provides a function whereby developers can attach manually-created tarballs to each tag; the developers should make use of this facility.

**Comment by adfernandes** [comment]
Again, for anyone coming to this page via google, the MacPorts version is **now working** and corresponds to the `v1.9.2-1` tag. It does this by pulling the git tag and all submodules.

**Comment by bcoca** [comment]
@ryandesign, the github tarballs/zips are not controlled by the developers, its auto generated from repo and cannot be modified (they used to be). But what you want is available at http://releases.ansible.com/ansible/.

**Comment by ryandesign** [comment]
@bcoca, you're right that github does offer automatically-generated tarballs from any git tag or commit hash. But what I was referring to was that github also separately offers the facility for developers to upload developer-created files that get attached to git tags, and become visible in the project's "releases" tab.

https://github.com/blog/1547-release-your-software

Thanks for letting me know about the location of your prepared release tarballs. Assuming they contain everything needed to build ansible, we should use those in MacPorts in the future.

**Comment by volodalexey** [comment]
I had the same problem, but I downloaded and compiled ansible from git.
Solution by @amenonsen helped me.

Previously I made so:
// clone git repo

``` bash
git clone git://github.com/ansible/ansible.git --recursive
```

// see list of tags

``` bash
git tag
```

// checkout specific tag

``` bash
git checkout tags/v1.9.2-1
```

// compile ansible

``` bash
source ./hacking/env-setup
sudo make install
```

And after this I had the same error

But now after checkout specific tag I saw:

``` bash
git status
```

``` bash
HEAD detached at v1.9.2-1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   lib/ansible/modules/core (new commits)
    modified:   lib/ansible/modules/extras (new commits)
```

It means that submodules need to be updated too.
// update submodules

``` bash
git submodule update
```

// status now

``` bash
git status
```

``` bash
HEAD detached at v1.9.2-1
nothing to commit, working directory clean
```

And I compiled after this, now it works!

**Comment by sepsyk** [comment]
I have followed the instructions from the official Ansible website to install the latest Ansible version (1.9.4) for OS X and I still get the same bug! It is December now, first bug report was in June. 

Instead of making excuses if this is a bug or not this should have been fixed a long time ago in my opinion.

**Comment by mpictor** [comment]
I encountered the error in the title after making some changes to my module for testability. Perhaps this problem would be obvious to a python guru, but it wasn't to me.

To fix it, I removed a conditional import that I _thought_ had been working
```python
 if __name__ == '__main__':
    import ansible.module_utils.basic
```
and added this (order probably doesn't matter, but I put it before other imports):
```python
from ansible.module_utils.basic import *
```
