### ISSUE TITLE
Included task file in role always report a changed state.

### ISSUE THREAD

**Issue by ArkaGPL** [ansible/ansible#11197]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 2.0.0 
##### Environment:

Localhost : Debian Jessie 8.0 3.16.0-4-amd64
##### Summary:

Included task file in a role is shown as 'included' during the run of the playbook but is always marked as 'changed'.
##### Steps To Reproduce:

Create a dummy role :

```
├── dummy
│   ├── tasks
│   │   ├── main.yml
│   │   └── tasklist.yml
```

Inside main.yml include 'tasklist.yml'

```

---

- name: include a list of tasks
  include: tasklist.yml
```

And inside tasklist.yml :

```

---

- name: ensure myfile exists
  copy: content='this is my file' dest=/tmp/myfile
```

Put this role inside a playbook and run it twice. The first time there will be 2 changed tasks, one for the include task and one for the copy task. And then the second time the include will be marked as 'changed'.

You can try to include as much taskfile as you want it will increase the number of changed tasks.
##### Expected Results:

Included task file are marked as 'included' and should not report a changed state since they will be included each time the playbook run.

```
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [dummy : include a list of tasks] ******************************************
included: tasklist.yml for localhost

TASK [dummy : ensure myfile exists] *********************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [dummy : include a list of tasks] ******************************************
included: tasklist.yml for localhost

TASK [dummy : ensure myfile exists] *********************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

Even if you add 'changed_when: False' to the include task the result is the same.

**Comment by kustodian** [comment]
I can also confirm this bug.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
