### ISSUE TITLE
`allow_duplicates` does not allow a role and its dependencies to be run multiple times

### ISSUE THREAD

**Issue by dellis23** [ansible/ansible#11205]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

N/A
##### Environment:

Mac OSX 10.9.5
##### Summary:

Roles that are included multiple times cannot have their dependencies included multiple times.  The documentation states that `allow_duplicates` accomplish something like this so long as the dependency is included multiple times from the _same_ role, but it does not seem to work for the aforementioned case.
##### Steps To Reproduce:

Here's a simple set of playbooks / roles that should illustrate the problem.

```
###  ./hypervisor-1.yml

---
- hosts:
    - host1
  roles:
    - role: vm
      name: red
    - role: vm
      name: blue

###  ./hypervisor-2.yml

---
- hosts:
    - host2
  roles:
    - role: vm
      name: green
    - role: vm
      name: yellow
    - role: vm
      name: purple

###  ./inventory
[hosts]
host1
host2

###  ./roles/disk/tasks/main.yml
- debug: msg="Setting up disk for {{ path }}"

###  ./roles/vm/meta/main.yml

---
allow_duplicates: yes
dependencies:
  - role: disk
    path: "/path/to/{{ name }}"

###  ./roles/vm/tasks/main.yml
- debug: msg="Installing VM {{ name }}"
```
##### Expected Results:

Running the first playbook, `hypervisor-1.yml`, should give output that shows a disk is set up for both `red` and `blue`, as well as the installation of the VM for both.
##### Actual Results:

```
PLAY [host1] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [host1]

TASK: [disk | debug msg="Setting up disk for /path/to/red"] ******************* 
ok: [host1] => {
    "msg": "Setting up disk for /path/to/red"
}

TASK: [vm | debug msg="Installing VM red"] ************************************ 
ok: [host1] => {
    "msg": "Installing VM red"
}

TASK: [vm | debug msg="Installing VM blue"] *********************************** 
ok: [host1] => {
    "msg": "Installing VM blue"
}

PLAY RECAP ******************************************************************** 
host1                      : ok=4    changed=0    unreachable=0    failed=0 
```

Note the disk is only set up for `red` and is skipped for `blue`.

**Comment by macster84** [comment]
Hi,

I encountered the same issue when I was provisioning some of my server machines. Trying to find a solution I've stumbled upon `allow_duplicates` too. However, as you've already mentioned, `allow_duplicates` should not apply here. The _vm_ role is not referencing the _disk_ role as a dependency twice. Instead the _vm_ role is just referenced twice from the playbook. 
That is a totally different use case.

The only workaround I can think of is to use `include`s instead of role dependencies but this effectively eliminates the whole role concept...

**Comment by dellis23** [comment]
@LuedDev Yeah, I thought "oh, include should be fine", until I realized it breaks all of the variables defined in the roles as well as the tasks that include templates and files.  So it's not much of a workaround unfortunately.

**Comment by joshuajcoronado** [comment]
+1

**Comment by jimi-c** [comment]
@dellis23 about to push a fix up for this, but I do notice one mistake in your example above: you need to specify `allow_duplicates` in the `disk` role, not the vm role. Since you are specifying unique parameters to the vm role each invocation will be unique and thus falls outside of the duplicate detection check.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dellis23** [comment]
Thank you @jimi-c !  Looking forward to trying it out.
