### ISSUE TITLE
Allow "-" as well as ":" to delimit host ranges in an inventory file?

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1124]

**Comment by mpdehaan** [comment]
it's ":" and they do.   Maybe make "-" work as well.

**Comment by mpdehaan** [comment]
The range parsing code is too primative to support this without rewriting it.

Leaving it as ":" for now.

**Comment by dhozac** [comment]
I have a branch where using - works.

However, the whole reason I did that was because I would like for inventory host ranges to be usable in patterns as well (so you can address nodes the same way you specify them in inventory), but enumeration has already claimed the [x-y] syntax there, and [x:y] won't work because : is the pattern separator. Any suggestions on how to get around that?

**Comment by mpdehaan** [comment]
Right, I think that's the other reason that was done.

I think we just let it go.

(You can still use group names in patterns, and pattern slicing uses "-" I'm pretty sure, which is not the same ":" you use in inventory, right?)

**Comment by mpdehaan** [comment]
(updated previous comment)
