### ISSUE TITLE
UTF-8 characters silently break Jinja2 templates

### ISSUE THREAD

**Issue by pako-pl** [ansible/ansible#11247]
I have a simple Jinja2 template, that I upload to a remote server using Ansible:

```
- name: Generate configuration file
  template: src=test.j2 dest=/test/test.conf
```

The test.j2 template contains:

```
{# private IP address #}
{{ private_ip }} 
```

Everything works fine if the template does not contain any UTF-8 characters. The {{ private_ip }} variable is substituted for the correct value. But when I add a word UTF-8 characters to the template file:

```
{# private IP address - Wrocław #}
{{ private_ip }} 
```

the template will be copied to the remote server unchanged. Ansible won't complain about this even in verbose mode - it will just happily upload the template without any changes like it was a binary file.

I'm using Python 2.7.9 on Debian Jessie 64 bit with default locale set to en_US.UTF-8 with a fresh checkout of Ansible 2.0.0 straight from Github.

I reverted to Ansible 1.9.2 - it doesn't have this problem.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
