### ISSUE TITLE
Unable to pass in a list of roles to playbook as a JSON list via --extra-vars

### ISSUE THREAD

**Issue by simon-lam** [ansible/ansible#11241]
**Issue Type**: Bug Report
**Ansible Version**: 1.9.1
**Ansible Configuration:** My installation is clean, with no customizations and done through `pip`.
**Environment:** Mac OSX 10.10.3

**Summary:**

I am trying to dynamically set the included roles in a playbook using the --extra-vars variable and the feature's built in JSON support.

A minimal playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  roles: 
    - "{{ some_roles }}"
```

The command I'm trying to run:

```
ansible-playbook test.yml --extra-vars '{ "some_roles": [ "role_1"] }'
```

**Steps To Reproduce:**
1. Copy my minimal playbook
2. Run the command listed above
3. Observe the stacktrace

**Expected Results:**

My playbook should run and I should be able to specify an arbitrary number of roles through the --extra-vars parameter.

**Actual Results:**

Ansible chokes and spits out:

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 103, in __init__
    ds = self._load_roles(self.roles, ds)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 440, in _load_roles
    roles = self._build_role_dependencies(roles, [], {})
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 251, in _build_role_dependencies
    role_path,role_vars = self._get_role_path(role)
  File "/Library/Python/2.7/site-packages/ansible/playbook/play.py", line 221, in _get_role_path
    role_name = utils.role_spec_parse(orig_path)["name"]
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 391, in role_spec_parse
    role_spec = role_spec.strip()
AttributeError: 'list' object has no attribute 'strip'
```

It seems there is a problem when passing in a collection of size 1, the existing workaround is to add dummy entries to the list, e.g.

```
ansible-playbook test.yml --extra-vars '{ "some_roles": [ "role_1", "dummy"] }'
```

**Comment by bcoca** [comment]
This is not a feature, roles need to be statically defined in the file. Still keeping this open as a bug as you should get a error message saying so and not a traceback.

**Comment by jimi-c** [comment]
In devel this does currently print a nicer error message:

<pre>
# ansible-playbook -vv 11241.yml 
Using /etc/ansible/ansible.cfg as config file
 [ERROR]: ERROR! the role '{{foo}}' was not found
</pre>

So closing this now, since as stated above this is not something we have ever supported.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
