### ISSUE TITLE
include parameters not overriding values from vars_files

### ISSUE THREAD

**Issue by mrdrmmn** [ansible/ansible#11258]
This is in references to https://groups.google.com/forum/#!topic/ansible-project/si_SXvRXGAo

The short version is that in ansible 1.9.1, parameters passed to includes are always overridden by values in vars_files.

For ansible v2/devel, the behavior varies.  For simple test cases, the behaviors is the same as ansible 1.9.1.  Hoever, it more complex cases, the behavior can apper to be correct.  The seems to be related to parameters being past to one include can end up bleeding over.  It seems most likely that this bleed over is related to variable references being used rather than copies, but that is just an educated guess.

For a more detailed breakdown of the varied behaviore in ansible v2/devel, please see https://github.com/therevmj/ansible-oddities/blob/master/play.yml

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat test.yml
- hosts: localhost
  gather_facts: no
  vars_files:
    - param_file.yml
  tasks:
  - debug: var=varname
  - include: foo.yml
    vars:
      varname: from_params
# cat foo.yml
- debug: msg="included var is {{varname}}"
# cat param_file.yml
varname: from_vars_files
# ansible-playbook -vv test_include_precedence2.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test_include_precedence2.yml
PLAY: ***************************************************************************
TASK [debug var=varname] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "varname": "from_vars_files"
}
TASK [include] ******************************************************************
included: foo.yml for localhost
TASK [debug msg=included var is from_params] ************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "included var is from_params"
}
PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
I do see you have some other v2 examples, if you have any working samples in a gist (full copies of the files) which produce odd output, please go ahead and open a new issue for those.

Thanks!
