### ISSUE TITLE
command warnings are no longer displayed in v2

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#11255]
The COMMAND_WARNINGS option still exists, warn=no works correctly, the command module still returns a warnings key/value pair, but nothing actually displays the warning.

It used to be in callbacks.py on_ok, but doesn't seem to have migrated to runner_on_ok in v2.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
