### ISSUE TITLE
WinRM fails in v2 mode on current devel branch

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11278]
v2 does not work in the current devel branch:
azureuser@thansible:~$ ansible all -m win_ping -vvv
thhighperf4 | FAILED! => {'failed': True, 'exception': 'Traceback (most recent call last):\n  File "/home/azureuser/ansible/ansible/lib/ansible/executor/process/worker.py", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File "/home/azureuser/ansible/ansible/lib/ansible/executor/task_executor.py", line 111, in run\n    res = self._execute()\n  File "/home/azureuser/ansible/ansible/lib/ansible/executor/task_executor.py", line 218, in _execute\n    self._handler = self._get_action_handler(connection=self._connection, templar=templar)\n  File "/home/azureuser/ansible/ansible/lib/ansible/executor/task_executor.py", line 425, in _get_action_handler\n    shared_loader_obj=self._shared_loader_obj,\n  File "/home/azureuser/ansible/ansible/lib/ansible/plugins/__init__.py", line 284, in get\n    obj = getattr(self._module_cache[path], self.class_name)(_args, *_kwargs)\n  File "/home/azureuser/ansible/ansible/lib/ansible/plugins/action/__init__.py", line 64, in **init**\n    self._shell = shell_loader.get(shell_type)\n  File "/home/azureuser/ansible/ansible/lib/ansible/plugins/__init__.py", line 274, in get\n    path = self.find_plugin(name)\n  File "/home/azureuser/ansible/ansible/lib/ansible/plugins/**init**.py", line 246, in find_plugin\n    if not name.startswith(\'_\'):\nAttributeError: \'ShellModule\' object has no attribute \'startswith\'\n', 'stdout': ''}

sourcing the v1 env-setup file and re-running the command works.

**Comment by bcoca** [comment]
We have not updated this connection plugin to work with v2, keeping this as a reminder that this is still on our TODO list.

**Comment by elventear** [comment]
@trondhindenes how do you source the v1 env-setup?

**Comment by jhawkesworth** [comment]
From memory it's just a question of running

source v1/hacking/env_setup

**Comment by trondhindenes** [comment]
correct.

**Comment by elventear** [comment]
Is there somewhere where I can read on the changes between v1 and v2?

**Comment by jhawkesworth** [comment]
James Cammarata's Ansible V2 and beyond slides probably a good place to
start - linked from here:
http://www.ansible.com/blog/ansiblefest-presentations

**Comment by jimi-c** [comment]
The winrm connection plugin was working in v2 as of this commit:

<pre>
commit 3aede800c575989b7c7f2b18e2818b5b4fdf4fd2
Author: James Cammarata <jimi@sngx.net>
Date:   Mon Apr 27 00:28:25 2015 -0500
    Fixing winrm connection for v2
</pre>

but apparently something we changed along the way broke things. I'll bisect this now and figure out what's going wrong internally.

**Comment by jimi-c** [comment]
I believe I have this mostly sorted out, however this issue https://github.com/ansible/ansible/issues/10294 appears to be causing problems as well. The problem there appears to be related to low-level python ssl functions rejecting self-signed certs, and not necessarily anything Ansible is doing incorrectly. We're looking into ways beyond those brute-force methods show in that issue to address that problem as well.

**Comment by jhawkesworth** [comment]
Thanks for this, this is good news.
I think #10294 occurs when using python 2.7.9 on the ansible controller so
fixing without tackling the self-signed certs issue would be useful for
some.

A more elegant way of dealing with the self-signed certs issue would be
very welcome though.   I think if we have to have a more involved process
to use self-signed certs, then provided its documented (and any bits of it
are automated where possible) then we should live with it rather than
disabling the security checks.  The approach taken in #10132 seems
reasonable (provided its documented).

**Comment by jimi-c** [comment]
@jhawkesworth the fixes I had were pushed last night, if you can verify. Beyond that, the problem I have with #10132 is that it modifies low-level methods in the ssl library which will have impact on any other code doing https stuff (ie. modules using code from urls.py). So I'm still looking at another way to fix that, similar to what we do for fetch_url in urls.py.

**Comment by jhawkesworth** [comment]
Thanks.  Have pulled latest dev and will try when I get home.

**Comment by trondhindenes** [comment]
It works, but there's something very wrong with the json output (specifically errors look way different in v2 than in v1 right now):

v2: thhighperf4 | FAILED! => {u'msg': u'mising required argument: name', u'failed': True, u'changed': False, u'invocation': {u'module_name': u'win_feature', u'module_args': {}}}

v1: 
thhighperf4 | FAILED >> {
    "changed": false,
    "failed": true,
    "msg": "mising required argument: name"
}

I don't know if that's related to winrm or a known bug in general?

**Comment by jimi-c** [comment]
It's not that different - there's a little more information there now is all.

**Comment by trondhindenes** [comment]
...and less formatting. I wouldn't mind a bit more pretty-printed json. But, I don't know if that's a winrm related thing or a global one. Happy to close this if the latter.

**Comment by jimi-c** [comment]
Just a callback issue - seems like failures were always pretty printed? Not sure, but otherwise if you're good we can close this issue. Thanks!

**Comment by jhawkesworth** [comment]
Glad to see this working for myself.

I did find an unrelated difference between v1 and v2 - v2 doesn't seem to
pick up vars defined in my inventory inside a [windows:vars] group.

So I had

[windows]
testhost ansible_ssh_host=testhost ansible_ssh_user=User
ansible_ssh_pass=*****

[windows: vars]
ansible_connection=winrm
ansible_ssh_port=5986

# but had to change it to the following otherwise v2 ansible attempted to

connect on port 22 (ssh port)
[windows]
testhost ansible_ssh_host=testhost ansible_ssh_user=User
ansible_ssh_pass=****\* ansible_connection=winrm
ansible_ssh_port=5986

Not really a big issue as I wouldn't set up inventory this way in anything
other than a test environment.
Having looked through the tracker it looks like maybe there's work or
documentation to be done in this area - not investigated but could be
related to https://github.com/ansible/ansible/issues/11325.

Clearly a separate issue though. Great to be able to start working with v2
though.

Many thanks

Jon

**Comment by trondhindenes** [comment]
@jhawkesworth Others ( https://github.com/ansible/ansible-modules-extras/pull/398#issuecomment-117742527 ) are having the same issue with the winrm port not getting picked up. "Someone" should probl post that bug.

**Comment by jimi-c** [comment]
@trondhindenes agreed, if there's not an issue for that yet definitely create one. It's a simple fix, just don't want to lose it.
