### ISSUE TITLE
Facts Caching not working

### ISSUE THREAD

**Issue by OnlyLoveOleg** [ansible/ansible#11318]
Just did a clean clone and facts caching with redis stopped working.

Details:

```
Ubuntu14.04 LTS (ansible and remote)
redis-3.0.1
```

Install:

```
cd /opt
git clone git://github.com/ansible/ansible.git --recursive
```

ansible.cfg

```
...
gathering = smart
fact_caching = redis
```

Version:

```
ansible 2.0.0 (devel b41b08ba7d) last updated 2015/06/18 18:05:35 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/18 18:05:46 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/18 18:05:56 (GMT +100)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/18 18:06:06 (GMT +100)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/18 18:06:16 (GMT +100)
```

Before the clone was using the following version with working fatcs:

```
ansible 2.0.0 (devel a8d52e3e94) last updated 2015/05/22 03:37:08 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 150b71f11a) last updated 2015/05/22 03:37:19 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 5187c7fcd7) last updated 2015/05/22 03:37:28 (GMT +100)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/05/22 03:37:38 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/05/22 03:37:48 (GMT +100)
```

In Redis-Cli prior the most recent clone was noticing the following using the MONITOR CMD:

```
1434646747.998848 [0 127.0.0.1:35517] "ZREMRANGEBYSCORE" "ansible_cache_keys" "0" "1434560347.998691"
1434646747.999143 [0 127.0.0.1:35517] "ZRANK" "ansible_cache_keys" "<HOST>"
1434646747.999465 [0 127.0.0.1:35517] "GET" "ansible_facts<HOST>"
1434646748.000622 [0 127.0.0.1:35517] "SETEX" "ansible_facts<HOST>" "86400" "<The Fatcs>"
1434646748.002593 [0 127.0.0.1:35517] "ZADD" "ansible_cache_keys" "1434646748.00208" "<HOST>"
```

Using the current clone the following transactions from Redis (No SETEX or ZADD):

```
1434647623.914616 [0 127.0.0.1:35528] "ZREMRANGEBYSCORE" "ansible_cache_keys" "0" "1434561223.914521"
1434647623.914947 [0 127.0.0.1:35528] "ZRANK" "ansible_cache_keys" "<HOST>"
1434647623.915266 [0 127.0.0.1:35528] "GET" "ansible_facts<HOST>"
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
1437158491.254951 [0 127.0.0.1:42894] "ZREMRANGEBYSCORE" "ansible_cache_keys" "0" "1437072091.254823"
1437158491.255157 [0 127.0.0.1:42894] "ZRANK" "ansible_cache_keys" "localhost"
1437158491.255691 [0 127.0.0.1:42894] "SETEX" "ansible_factslocalhost" "86400" ...
1437158491.257398 [0 127.0.0.1:42894] "ZADD" "ansible_cache_keys" "1437158491.257323" "localhost"
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
