### ISSUE TITLE
host_vars file doesn't parsed, when run playbook with -l

### ISSUE THREAD

**Issue by dh-harald** [ansible/ansible#11313]
Hi,

Here's my test case:

```
group_vars/all:
  variable_all: true
group_vars/group1
  variable_group1: true
group_vars/group2
  variable_group2: true
host_vars/server1
  variable_server1: true
host_vars/server2
  variable_server2: true

inventory/hosts
[group1]
server1
[group2]
server2

site.yml
- name: test role
  hosts: group1

  tasks:
    - debug: var=hostvars["server2"]
      delegate_to: 127.0.0.1


$ ansible-playbook -i inventory site.yml
TASK: [debug var=hostvars["server2"]] ***************************************** 
ok: [server1 -> 127.0.0.1] => {
    "var": {
        "hostvars[\"server2\"]": {
            "group_names": [
                "group2"
            ],
            "variable_all": true,
            "variable_group2": true,
            "variable_server2": true
        }
    }
}

$ ansible-playbook -i inventory site.yml -l group1
TASK: [debug var=hostvars["server2"]] ***************************************** 
ok: [server1 -> 127.0.0.1] => {
    "var": {
        "hostvars[\"server2\"]": {
            "group_names": [
                "group2"
            ],
            "variable_all": true,
            "variable_group2": true
        }
    }
}
```

I'm using ansible 1.8.2 on CentOS6 & ansible 1.9.1 on CentOS7 & arch linux

**Comment by dh-harald** [comment]
It's not the variable file parsing, because a host variable from dynamic inventory is also missing...

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv -i hosts test.yml -l group1
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: test role *****************************************************************
TASK [setup] ********************************************************************
ok: [server1]
TASK [debug var=hostvars["server2"]] ********************************************
ok: [server1] => {
    "changed": false, 
    "hostvars[\"server2\"]": {
        "ansible_connection": "local", 
        "ansible_play_hosts": [
            "server1"
        ], 
        "ansible_ssh_host": "server2", 
        "ansible_ssh_port": null, 
        "ansible_version": {
            "full": "2.0.0", 
            "major": 2, 
            "minor": 0, 
            "revision": 0, 
            "string": "2.0.0"
        }, 
        "group_names": [
            "group2"
        ], 
        "groups": {
            "all": [
                "server1", 
                "server2"
            ], 
            "group1": [
                "server1"
            ], 
            "group2": [
                "server2"
            ], 
            "ungrouped": []
        }, 
        "hostvars": {}, 
        "inventory_dir": "/root/testing/11313", 
        "inventory_hostname": "server2", 
        "inventory_hostname_short": "server2", 
        "omit": "__omit_place_holder__2261971b89388b4ee1c090cce9065885d922e9a7", 
        "play_hosts": [
            "server1"
        ], 
        "playbook_dir": "/root/testing/11313", 
        "variable_all": true, 
        "variable_group2": true, 
        "variable_server2": true, 
        "vars": {
            "ansible_connection": "local", 
            "ansible_play_hosts": [
                "server1"
            ], 
            "ansible_ssh_host": "server2", 
            "ansible_ssh_port": null, 
            "ansible_version": {
                "full": "2.0.0", 
                "major": 2, 
                "minor": 0, 
                "revision": 0, 
                "string": "2.0.0"
            }, 
            "group_names": [
                "group2"
            ], 
            "groups": {
                "all": [
                    "server1", 
                    "server2"
                ], 
                "group1": [
                    "server1"
                ], 
                "group2": [
                    "server2"
                ], 
                "ungrouped": []
            }, 
            "hostvars": {}, 
            "inventory_dir": "/root/testing/11313", 
            "inventory_hostname": "server2", 
            "inventory_hostname_short": "server2", 
            "omit": "__omit_place_holder__2261971b89388b4ee1c090cce9065885d922e9a7", 
            "play_hosts": [
                "server1"
            ], 
            "playbook_dir": "/root/testing/11313", 
            "variable_all": true, 
            "variable_group2": true, 
            "variable_server2": true
        }
    }
}
PLAY RECAP **********************************************************************
server1                    : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
