### ISSUE TITLE
roles_path regression in v2

### ISSUE THREAD

**Issue by arturhoo** [ansible/ansible#11328]
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 2.0.0 (devel ff251a0dcc) last updated 2015/06/22 10:51:04 (GMT -200)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/22 10:51:09 (GMT -200)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/22 10:51:14 (GMT -200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 10:51:19 (GMT -200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 10:51:26 (GMT -200)
  configured module search path = None
```

**Ansible Configuration:**

I haven't changed or added any configuration settings to Ansible.

**Environment:**

OSX 10.10.3
Python 2.7.10

**Summary:**

There is a regression on `v2` regarding how `roles_path` is constructed with subdirectories:
- `./ansible.cfg` 
- `./subfolder/playbook.yml`
- `./subfolder/child/roles/`

**Steps to Reproduce:**

I set up an example repository to illustrate this bug: https://github.com/arturhoo/ansible-bug-2

**Expected Results:**

```
$ ansible-playbook -i 'localhost,' --connection=local subfolder/playbook.yml

PLAY [all] ********************************************************************



GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [one | create one.txt file] *********************************************
changed: [localhost]

TASK: [child/roles/two | create two.txt file] *********************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

**Actual Results:**

```
$ ansible-playbook -i 'localhost,' --connection=local subfolder/playbook.yml
ERROR! the role 'child/roles/two' was not found
```

**Notes:**

The expected result is the one we get on `1.9.1`. A workaround on `v2` (maybe the wanted way all along) is to use only the role name in the playbook.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
