### ISSUE TITLE
group_vars/all.yml no longer loaded in v2

### ISSUE THREAD

**Issue by shawnferry** [ansible/ansible#11325]
##### Issue Type:

Bug
##### Ansible Version:

ansible --version
ansible 2.0.0 (devel fc82bccf6c) last updated 2015/06/19 11:15:17 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/19 11:16:15 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1604382538) last updated 2015/06/19 11:16:30 (GMT -400)
  v1/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/19 11:16:31 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 1604382538) last updated 2015/06/19 11:16:33 (GMT -400)
  configured module search path = None
##### Summary:

Without manually including all.yml my roles fail because my high level vars aren't available.
##### Steps To Reproduce:

Do anything that requires group_vars/all.yml to be loaded

https://gist.github.com/shawnferry/8a0a0c2f144753f2ebde
##### Expected Results:

all.yml variables will be available
##### Actual Results:

all.yml variables appears to be ignored

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [debug var=present] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ test_var_all|default('this should be defined') }}": "present"
}
TASK [include_vars] *************************************************************
ok: [localhost] => {"changed": false, "msg": "All items completed", "results": [{"ansible_facts": {"test_var_all": "present"}, "item": "group_vars/all.yml"}]}
TASK [debug var=present] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "{{ test_var_all|default('this should be defined') }}": "present"
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
