### ISSUE TITLE
ssh port in inventory no longer working

### ISSUE THREAD

**Issue by cswingle** [ansible/ansible#11330]
I just switched from the pip version of ansible to the source version (`devel` branch) from this repository.  I have an inventory file like this:

```
[web]
192.168.14.18:2222 hostname=trusty
```

ansible doesn't appear to be using the ssh port:

```
$ ansible all -m ping -vvvv
...
debug1: connect to address 192.168.14.18 port 22: Connection refused
```

When I add `-o Port=2222` to `ssh_args` in `ansible.cfg`:

```
$ ansible all -m ping
192.168.14.18 | SUCCESS => {
    "invocation": {
        "module_name": "ping",
        "module_args": {}
    },
    "changed": false,
    "ping": "pong"
}
```

Is there a new way to specify the ssh port that's not in the docs?

Thanks.

**Comment by bennojoy** [comment]
@cswingle  that can be a bug,  meanwhile can you try setting ansible_ssh_port=2222 in inventory.

**Comment by cswingle** [comment]
@bennojoy, `ansible_ssh_port=2222` doesn't help in inventory or config.  It's still trying to use port 22.

For what it's worth:

```
$ ansible --version
ansible 2.0.0 (devel b34b606fcf) last updated 2015/06/21 08:01:22 (GMT -800)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/20 17:37:30 (GMT -800)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/20 17:37:31 (GMT -800)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/20 17:37:31 (GMT -800)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/20 16:59:44 (GMT -800)
  configured module search path = None
```

Platform OS X Yosemite, 10.10.2

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
