### ISSUE TITLE
start-at-task not working in version 2.0

### ISSUE THREAD

**Issue by koss822** [ansible/ansible#11338]
# Basic info

works correctly at ansible 1.8
# Role: roles/aws/tasks/main.yml

``` ---
- name: Check CloudWatch installation
  stat: path=/usr/local/aws-scripts-mon
  register: cloudwatch
```
# Command

`ansible-playbook site.yml --start-at-task="aws | Check CloudWatch installation" --extra-vars "target=enigma14"`
# Console output

```
PLAY: Enigma LAMP ***************************************************************

TASK [setup] ********************************************************************
ok: [enigma14]

TASK [base : base : Core server packages] ***************************************
^C
```
# version

`ansible 2.0.0 (devel ff251a0dcc) last updated 2015/06/22 10:38:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD d6ed6113a7) last updated 2015/06/22 09:38:14 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 57813a2e74) last updated 2015/06/22 09:38:14 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 09:38:14 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 09:38:14 (GMT +200)
  configured module search path = None`

**Comment by bcoca** [comment]
This is on the "to implement list".

**Comment by jimi-c** [comment]
This has been corrected, and should be working now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
