### ISSUE TITLE
Extraneous syslog output from ansible-file

### ISSUE THREAD

**Issue by jmeickle** [ansible/ansible#11359]
When I do a fairly standard ansible-playbook run, the remote server ends up getting syslog output with a lot of Ansible modules (expected). However, it also produces output like this interspersed with the Ansible commands:

```
Jun 23 15:42:52 nrg-buildmaster ansible-service: Invoked with name=logstash-forwarder pattern=None enabled=True state=started sleep=None arguments= runlevel=default 
Jun 23 15:42:53 nrg-buildmaster afile = open("'/etc/sysconfig/logstash-forwarder'", "rb")
Jun 23 15:42:53 nrg-buildmaster buf = afile.read(BLOCKSIZE)
Jun 23 15:42:53 nrg-buildmaster while len(buf) > 0:
Jun 23 15:42:53 nrg-buildmaster     hasher.update(buf)
Jun 23 15:42:53 nrg-buildmaster     buf = afile.read(BLOCKSIZE)
Jun 23 15:42:53 nrg-buildmaster afile.close()
Jun 23 15:42:53 nrg-buildmaster print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
Jun 23 15:42:53 nrg-buildmaster afile = open("'/etc/sysconfig/logstash-forwarder'", "rb")
Jun 23 15:42:53 nrg-buildmaster buf = afile.read(BLOCKSIZE)
Jun 23 15:42:53 nrg-buildmaster while len(buf) > 0:
Jun 23 15:42:53 nrg-buildmaster     hasher.update(buf)
Jun 23 15:42:53 nrg-buildmaster     buf = afile.read(BLOCKSIZE)
Jun 23 15:42:53 nrg-buildmaster afile.close()
Jun 23 15:42:53 nrg-buildmaster print(hasher.hexdigest())' 2>/dev/null)
Jun 23 15:42:53 nrg-buildmaster ansible-file: Invoked with directory_mode=None force=False remote_src=None path=/etc/sysconfig/logstash-forwarder owner=None follow=False group=None state=None content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/etc/sysconfig/logstash-forwarder selevel=None original_basename=logstash-forwarder.rpm regexp=None validate=None src=logstash-forwarder.rpm seuser=None recurse=False delimiter=None mode=0655 backup=None
```

I believe it's ansible-file that's causing this, but it's not clear why it's ending up in syslog...

**Comment by bcoca** [comment]
that does not look like the log information ansible normally emits, I suspect this is some other software that is producing these logs

**Comment by jmeickle** [comment]
I only partially manage this machine, so I don't know all of the configuration here, but I'm only using stock Ansible modules. Perhaps something to do with how the file module is running the command, like at the SSH/shell level?

**Comment by bcoca** [comment]
it runs it like you would run a command normally over ssh:

`ssh hostname "command"` or `echo "command" |ssh hostname` if using pipelining

**Comment by jimi-c** [comment]
@Eronarn any follow-up on this? As @bcoca mentioned, we're pretty sure this isn't something Ansible is doing, as we don't have any logging levels that would show such verbose output.

**Comment by jimi-c** [comment]
Actually, now that I've looked a bit closer, this is simply the logged output from the python-based checksum code (used to get SHA checksums in a platform independent manner). As such, this is completely normal, and you may see it from time to time.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
