### ISSUE TITLE
Group/host and command line vars not loaded/registered

### ISSUE THREAD

**Issue by brenix** [ansible/ansible#11352]
For the last couple of weeks using v2, it seems variables loaded from either group_vars, host_vars, or the command line do not seem to be loaded. If using group_vars/host_vars combined with `- debug: var=hostvars[inventory_hostname]`, it appears to return an empty dict. However, variables seem to work if specified in a playbook. Reverting to the stable-1.9 branch or sourcing v1 seem to resolve the issue.

Additionally, the condensed output option (`-o`) does not seem to be working in v2 as well (see examples below).
#### version

```
» ansible --version
ansible 2.0.0 (devel 94d9fc0ef9) last updated 2015/06/22 23:49:50 (GMT -700)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/22 23:58:42 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/22 23:58:42 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 23:58:43 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 23:47:45 (GMT -700)
  configured module search path = None
```
#### example - sourcing v2 (not working)

```
» source ./hacking/env-setup -q
» ansible localhost -i "localhost," -m debug -a "var=example" -e "example=foo" -o
localhost | SUCCESS => {
    "verbose_always": true,
    "changed": false,
    "example": "example"
}
```
#### example - sourcing v1 (working)

```
» source ./v1/hacking/env-setup -q
» ansible localhost -i "localhost," -m debug -a "var=example" -e "example=foo" -o
localhost | success >> {"var": {"example": "foo"}}
```

**Comment by brenix** [comment]
Possibly related to #11325

**Comment by sebi-hgdata** [comment]
I'm seeing this issue also

**Comment by yasserg** [comment]
+1

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
