### ISSUE TITLE
Include paths do not work the same in v2 as in v1

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#11353]
I have a couple of task files that  include each other and are not at the same level as the playbook. 

It seems that in v2 codebase the include path needs to be specified relative to the palybook's directory... specifying the path relative of the task's file directory does not work any more.

$ ansible --version
ansible 2.0.0 (devel 952166f48e) last updated 2015/06/23 11:45:41 (GMT +300)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/23 11:45:45 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/23 11:45:49 (GMT +300)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/23 11:45:53 (GMT +300)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/23 11:45:56 (GMT +300)
  configured module search path = None

Sebi

**Comment by sej7278** [comment]
i also found in 1.7.2 you could call a template from a task using a relative path from the top-level playbook.yml directory, now it seems you need to add the templates directory to the path.

so in 1.7.2 this worked:

`template: src=10-disable-ipv6.conf.j2 dest=/etc/sysctl.d/10-disable-ipv6.conf`

but in 2.0.0 (1.9.2 built from git) you need:

`template: src=templates/10-disable-ipv6.conf.j2 dest=/etc/sysctl.d/10-disable-ipv6.conf`

**Comment by jimi-c** [comment]
@sebi-hgdata can you share a gist of an example that reproduces this? Thanks!

**Comment by bcoca** [comment]
can you check again against latest devel, the path searching has been updated

**Comment by sebi-hgdata** [comment]
Checked and it does not work. 
I've created a new repo that can be used to debug it: https://github.com/sebi-hgdata/ansible_test.  

If you run 'ansible-playbook -v build_admin_ui.yml -i inventories/local/hosts --extra-vars "admin_ui_version=1234"', the first issue will be a varaible resolution error for 'sudo_user' varaiable that is defined in group_vars/all (probably related to https://github.com/ansible/ansible/issues/11352) and the second issue will be this one ( tasks/docker/build.yml    file includes other files using a path relative to itself).

**Comment by jimi-c** [comment]
@sebi-hgdata I have a patch here https://gist.github.com/jimi-c/ae720565d20cae6273d8 which resolves the two issues you mention above, however now I hit a new error:

<pre>
TASK [build images] *************************************************************
fatal: [admin_ui]: FAILED! => {
    "failed": true, 
    "msg": "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'list object' has no attribute 'path'"
}
</pre>

Since this playbook is very complex, I can't tell if this is simply a result of me missing something in your setup or some other error, so I'll let you test the above patch.

**Comment by sebi-hgdata** [comment]
@jimi-c just tested it and got the same error... it seems all  includes work now...but there might be an issue with variable resolution in  with_items. 
In build.yml task file   I've added 2 debug tasks and it seems that in 1.9.2 item[0] resolves to a dictionary, but in latest devel it is a list with a dictionary element.

**Comment by jimi-c** [comment]
I believe I've tracked this down:

<pre>
>>> v={'a dump of the variables'}
>>> v['images']
u'{{ base_images }}'
>>> v['base_images']
[{u'path': u'{{ docker_apps_base }}/origin', u'name': u'origin'}]
>>> v['docker_apps_base']
u'{{docker_apps}}/base'
>>> v['docker_apps']
u'{{docker_images_base}}/apps'
>>> v['docker_images_base']
u'{{ ansible_base }}/docker'
>>> v['ansible_base']
u'/home/{{ ansible_ssh_user }}/hgdata/sfdc-ops'
>>> v['ansible_ssh_user']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'ansible_ssh_user'
</pre>

So, because this is a lookup plugin, the error is not being triggered properly and failing on the template error. If I add `-e ansible_ssh_user=foo` to the command line options, it does not throw that error (but it does trigger an error in docker_image...).

**Comment by jimi-c** [comment]
@sebi-hgdata I've fixed the main two issues here, which is not catching the template error in the lookup plugin expansion of values, as well as the original issue for the ticket. However, the above still fails because the ansible_ssh_user value is not being set somewhere, which may occur after the loop items are set? In that case, we may need to temporarily inject that data to the variables before they're used, but I'm still tracking that one down.

But because the original issue is now fixed, I went ahead and closed this one.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
@sebi-hgdata the variable issue has now been resolved as well in c2435fab7edf39ef5f36d924bee33cb37dd0795d.

Thanks!

**Comment by sebi-hgdata** [comment]
Looks good :+1:
