### ISSUE TITLE
template error while templating string: Encountered unknown tag 'S'

### ISSUE THREAD

**Issue by jhagg** [ansible/ansible#11366]
This strange bug bit me when I tried Ansible 1.8.4, latest released version(?).

I've reduced it to a playbook, an template file and the inventory file.

The content in the template file doesn't matter, it is enough
with a completely empty file.

Hostname doesn't matter, either **localhost** or other names triggers the bug.
I've tried 127.0.0.1 and other variants of hostnames, with or without domain.

I also tried deleting my environment completely using **env -i ash**, trying
a minimal shell that has few veriables.

These are the current files:

**hosts**

```
[host_list]
localhost
```

**site.yaml**

```

---
- hosts:
  - host_list
  tasks:
  - action: template dest=/tmp/app_keys.txt src=mupp.j2
```

**mupp.j2**

```
[empty file, 0 byte]
```

The error shows when I run Ansible like this:

```
ansible-playbook -i hosts site.yaml

PLAY [host_list] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [template dest=/tmp/mupp.txt src=mupp.j2] ******************************* 
fatal: [localhost] => template error while templating string: Encountered unknown tag 'S'.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jh/site.yaml.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   

```

Now, the interesting thing happens when I change **action:** to **local_action:**.
Everything works, I get a zero byte sized file in /tmp as expected.
Once again, content doesn't matter. Using -c local doesn't help either.

```
ansible-playbook -i hosts site.yaml         

PLAY [host_list] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [template dest=/tmp/mupp.txt src=mupp.j2] ******************************* 
ok: [localhost -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
FYI, latest released as of today is 1.9.2, you might want to try this with that version and current devel to see if the issue persists.

**Comment by jhagg** [comment]
I've tried 1.9.2, still the same error

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -i inv test.yml -vv
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [template dest=/tmp/app_keys.txt src=mupp.j2] ******************************
changed: [localhost] => {"changed": true, "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "dest": "/tmp/app_keys.txt", "diff": {"after": "", "before": ""}, "gid": 0, "group": "root", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 0, "src": "/root/.ansible/tmp/ansible-tmp-1437452775.11-138392636689739/source", "state": "file", "uid": 0}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
# cat /tmp/app_keys.txt 
# 
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
