### ISSUE TITLE
authorized_keys fails on glusterFS

### ISSUE THREAD

**Issue by dthvt** [ansible/ansible#11373]
Ansible 1.9.1 on CentOS 6.6 (fully patched as of 6/24/2015).

A user home directory is hosted on a GlusterFS file system.  When using the authorized_keys module to install their key, I receive the following error:

```
failed: [hostxxxx] => (item=userxxxxx) => {"cur_context": ["system_u", "object_r", "fusefs_t", "s0"], "failed": true, "gid": 0, "group": "root", "input_was": ["unconfined_u", "object_r", "user_home_t", "s0"], "item": "userxxxxx", "mode": "0600", "new_context": ["unconfined_u", "object_r", "user_home_t", "s0"], "owner": "root", "path": "/home/chroot/userxxxx/.ssh/authorized_keys", "secontext": "system_u:object_r:fusefs_t:s0", "size": 0, "state": "file", "uid": 0}
msg: invalid selinux context
```

I would guess this is similar to #5632 in root cause.

I worked around the issue by using a copy module command instead, but would prefer authorized_keys be fixed so things are more self-documenting in the playbook.

**Comment by bcoca** [comment]
weird that the copy module works as both use the same shared function to actually copy the file into place (which is selinux aware). In any case this seems to be an issue common with non posix file systems, try adding gluserfs to the special_context_filesystems setting in ansible.cfg.

**Comment by jimi-c** [comment]
Per the above comment, this issue should be resolved by adding `glusterfs` to the ansible.cfg settings under the list `special_context_filesystems`. This will prevent ansible from attempting to manage SELinux permissions on that FS type.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
