### ISSUE TITLE
Relative Path broken in V2

### ISSUE THREAD

**Issue by jfpucheu** [ansible/ansible#11375]
The relative path are not good in v2 (working in V1):

main.yml :

``` ---
   # Update NTP config:  
   - include: system/ntp-update.yml

   # Mongodb install :  
    - include: products/mongoDB_deploy.yml
```

 ntp-update.yml  :           

```
tasks:
   - name: Transfer ntp.conf /etc/
     copy: src=system-files/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
```

execution :

```
TASK [Transfer ntp.conf /etc/] **************************************************
fatal: [audvnws01]: FAILED! => {"msg": "could not find src=/Users/Jeff/deploiement/playbooks/infra/products/system-files/ntp.conf", "failed": true, "changed": false}
```

the src path should be ('system' instead of 'products'):
 src=/Users/Jeff/deploiement/playbooks/infra/system/system-files/ntp.conf"

**Comment by jfpucheu** [comment]
the pb come from the variable {{ playbook_dir }} witch have th value of the last playbook executed

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 11375/main.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 11375/main.yml
PLAY ****************************************************************************
TASK [debug msg=here i am in foo] ***********************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "here i am in foo"
}
TASK [copy dest=/tmp/11375.txt src=system-files/test.txt group=root mode=0644 owner=root] ***
changed: [localhost] => {"changed": true, "checksum": "4a0f171a35948dd42ec39bccbfa9c500da7a2725", "dest": "/tmp/11375.txt", "gid": 0, "group": "root", "md5sum": "1aecba0400320165459d0c6836fce2f6", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 22, "src": "/root/.ansible/tmp/ansible-tmp-1437453698.63-213530200868712/source", "state": "file", "uid": 0}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
For the record, this was the small setup I used to test this:

<pre>
# ll
total 8
-rw-r--r--. 1 root root   26 Jul 21 00:36 main.yml
drwxr-xr-x. 3 root root 4096 Jul 21 00:38 system
# cat main.yml 
- include: system/foo.yml
# ll system/
total 8
-rw-r--r--. 1 root root  169 Jul 21 00:37 foo.yml
drwxr-xr-x. 2 root root 4096 Jul 21 00:38 system-files
# ll system/system-files/
total 4
-rw-r--r--. 1 root root 22 Jul 21 00:38 test.txt
# cat system/foo.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: msg="here i am in foo"
  - copy: src=system-files/test.txt dest=/tmp/11375.txt owner=root group=root mode=0644
# cat system/system-files/test.txt 
this is the test file
</pre>
