### ISSUE TITLE
Bad var in included playbook produces misleading error

### ISSUE THREAD

**Issue by usernamenumber** [ansible/ansible#11387]
I found [this post from 2014](http://grokbase.com/t/gg/ansible-project/1473nhq6te/include-error-message-misleading) when I encountered the same problem (`file could not read: /path/to/playbook` error that makes it look like the playbook doesn't exist, when in fact it does, but there is a problem with an undefined variable within). 

In the responses it was suggested that a github issue should be created but I can't find one, so here is a github issue.

**Comment by bcoca** [comment]
have you tried this in current devel? we revamped the parser to be much better about this kind of error.

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by usernamenumber** [comment]
Sorry, haven't had a chance to do this with devel. I'll make a TODO for myself, but as I do not normally run devel I'm not sure when I'll have a chance.

**Comment by jimi-c** [comment]
This does fail with a clearer message on devel, however one thing that must be taken into consideration is that includes are now dynamic, meaning they no longer function as a pre-processor statement. To get your playbook working (to show the error at least) I had to modify it as follows:

<pre>
# cat 11387.yml 
- hosts: localhost
  gather_facts: no
  vars:
    TOP_BAD: ".."
  tasks:
  - name: check TOP
    debug: msg="notifying handlers"
    changed_when: true
    notify: include test
  handlers:
    - name: include test
      include: "{{TOP}}/handlers/apache_graceful.yml"
</pre>

This when run, shows the following output:

<pre>
RUNNING HANDLER [include test] **************************************************
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'TOP' is undefined"
}
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
