### ISSUE TITLE
Feature Request: include playbooks from python packages

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ansible/ansible#11399]
currently its only possible to include playbooks from filenames

for better reuse in different projects (and wanting to avoid the trouble around)
i propose extending the include mechanism to also resolve for python packages

```
- incude: webserver.yml
  from_package: foo.common.ansible
```

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We don't want this to seem confrontational, but unfortunately we're not sure if we want this feature in the program. This issue has remained open for quite a while, and it has failed to garner any interest nor have any community members picked it up to work on it. However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
