### ISSUE TITLE
self.aliases is 'NoneType' object; AttributeError no attribute 'get'

### ISSUE THREAD

**Issue by puhrez** [ansible/ansible#11403]
**Issue Type:** Bug Report (maybe)

**Ansible Version**: ansible 1.9.2 installed via pip via virtualenv

**Ansible Configuration**: Nothing special

**Environment:**
Mac OS X 10.10.1

**Steps to reproduce**:
`ansible-playbook -i hosts REDACTED.yml --extra-vars "emr_cluster_id=REDACTED cluster_name=REDACTED" -vvvv --ask-vault-pass`

**Task:**

```
- name: Get cluster nodes
  shell: aws ec2 describe-instances --filters Name=instance-state-name,Values=running Name=tag:Name,Values={{ cluster_name }}-server Name=tag:aws:elasticmapreduce:instance-group-role,Values={{ item }} --output json
  with_items:
    - MASTER
    - CORE
  register: cluster_instances
  changed_when: False
```

**Expected Results**
Not an error... I.e. I expected the playbook to continue using the registered variable in subsequent tasks

**Actual Results**:

```
<localhost> REMOTE_MODULE command aws emr describe-instances --filters Name=instance-state-name,Values=running Name=tag:Name,Values=REDACTED Name=tag:aws:elasticmapreduce:instance-group-role,Values=MASTER --output json #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667 && echo $HOME/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667']
<localhost> PUT /var/folders/44/rg86bv9578v197smmykx6jvm0000gn/T/tmpTXBsYp TO /Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /Users/micperez/envs/impala-venv/bin/python2.7 /Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command']
failed: [localhost] => (item=MASTER) => {"changed": false, "failed": true, "item": "MASTER", "parsed": false}
Traceback (most recent call last):
  File "/Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command", line 1734, in <module>
    main()
  File "/Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command", line 32, in main
    module = CommandModule(argument_spec=dict())
  File "/Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command", line 465, in __init__
    self._log_invocation()
  File "/Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command", line 1182, in _log_invocation
    canon  = self.aliases.get(param, param)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Summary <--> Findings thus far**.
Inspecting /Users/micperez/.ansible/tmp/ansible-tmp-1435328568.23-84034094653667/command shows that the `CommandModule` class overwrites its inherited method `_handle_aliases` to just `pass`. When its then used in the constructor of the parent class, `AnsibleModule`, the result `None` is assigned to `self.aliases`, thus when its used in `_log_invocation`, there is no attribute `get`.

**Comment by shaddi** [comment]
I ran into this same issue and found out I had a old version of `commands` in my modules path (`/usr/share/ansible`) that was returning `None` in its `_handle_aliases` method instead of an empty dict. Removing the file there fixed the issue.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- Version mismatch between modules and ansible.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
