### ISSUE TITLE
Feature request - ability to only use one group in group_vars, even if host is in multiple groups

### ISSUE THREAD

**Issue by jagibson** [ansible/ansible#11406]
If a host is in multiple groups, by design Ansible's behavior is that, "variables will come from all of the groups they are a member of."  This is great most of the time, but there are certain instances where it is desirable to turn this feature off.  For some provisioning/cloud modules it's actually a detriment.

For example, if I want to run the route53 module to manage domain records, I'm very likely to run it on localhost as there is not specific server I'm managing.  However, if I try to use group_vars to define each separate route53 domain in its own group, Ansible will only use the first set of vars it finds since the host for each group (localhost) is the same.

If I could somehow tell Ansible, "hey, only use the group that matches your '-hosts: " line," it would be a neat thing.  I know I can use include_vars or vars_files instead, but it seems a little less elegant when running at the playbook level.  Also, there isn't a good 'standard' place to put vars that aren't host or group vars at the playbook level (referencing http://docs.ansible.com/playbooks_best_practices.html).  Besides, creating 'vars' directory at the playbook level seems... excessive... when group_vars is such a good fit otherwise.

Anyway, thanks for your time and consideration.

**Comment by dankeder** [comment]
I run into the same issue when I tried to specify the list of collectd plugins to install onto servers using group_vars. Then I realized that it's a bit more tricky than just taking the group that matches the "hosts" key in the playbook - the value in hosts may be more complex than just the group name, e.g. one can have something like `all:!webservers` there. It isn't clear what would happen in that case.

As for a good place for playbook-level vars - there isn't a "standard" place to put those vars to (or at least none that I know of). I usually put these vars into a yaml file and include it in the playbook manually. I store these files in the `profiles/` subdirectory in the top of my project. Generally, these files contain configuration specific for the deployment type - e.g. `profiles/dev`, `profiles/production`. I specify the profile I want by passing the `--extra-vars` to ansible-playbook when running the playbook. I don't know if there's a better way to do it, but I've been using this for a long time and it works quite well.

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We don't want this to seem confrontational, but unfortunately we're not sure if we want this feature in the program. This issue has remained open for quite a while, and it has failed to garner any interest nor have any community members picked it up to work on it. However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by pavetok** [comment]
+1

**Comment by jagibson** [comment]
Bummer that this was closed.  There doesn't seem to be a good way to manage non-host resources.
