### ISSUE TITLE
v2 callback plugin issues

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#11412]
There seem to be a number of callback methods not called anywhere in the code.  Specifically, in v1 `playbook_on_start` was called, in v2, neither `playbook_on_start` nor `v2_playbook_on_start` seem to be called from anywhere.  I also noted a `v2_playbook_on_setup` method, which doesn't appear to be called from anywhere.

Also, in v1, the `playbook` instance was made available to the callback.  Currently I do not see that the callback plugin has access to the playbook instance.

I have several callback plugins which perform deeper inspection into the playbook run and use data from:
- loaded variables/host_vars
- playbook
- play
- inventory
- provided tags
- provided limit
- connection information

Without deeper insight into the playbook run, we lose a lot of information that we previously had access to.

**Comment by bcoca** [comment]
discussed this today with core team, since a lot of this depended on the chaining of references in the old API we don't think we can enable it the same way, we are going to try to supply read only data structures for playbook, play and task that have most of the information you list above.

Also some of the v1 callbacks were not called on purpose, due to the lack of the old objects, we will try to mock what they need to work as much as possible in the new framework

**Comment by bcoca** [comment]
So these you can get by looking at sys.args, no need to add them explicitly.
provided tags
provided limit

**Comment by jimi-c** [comment]
Based on the above, and per team discussions, we're going to go ahead and close this now. In the future, we can revisit any callback points that aren't being hit in later releases.

Thanks!

**Comment by KimNorgaard** [comment]
We often run playbooks programmatically in which case sys.args is not really useful.
I wrote a callback-module designet for auditlogging whatever ansibles does (https://github.com/neticdk/ansible-auditlog-callback). This no longer works with v2 because I don't have access to enough context. This potentially stops us from using ansible with certain customers because they require detailed audit logs of everything that goes on.

You don't need to chain the reference of the playbook. You just need to parse it as an argument to v2_playbook_on_start and call that callback from a place in the code where the playbook data is available. Also, DataLoader should probably keep a record of the filename that was loaded.
