### ISSUE TITLE
playbook host/group vars are not loaded, inventory ones do work

### ISSUE THREAD

**Issue by ubergeek42** [ansible/ansible#11423]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel d612838116) last updated 2015/06/29 12:54:46 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 50912c9092) last updated 2015/06/29 12:54:50 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD dec7d95d51) last updated 2015/06/29 12:54:50 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/16 13:51:36 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/16 13:51:46 (GMT -400)
  configured module search path = None
```
##### Ansible Configuration:

N/A
##### Environment:

N/A (but I'm running Ubuntu 14.04)
##### Summary:

`host_vars` and `group_vars` are not loaded from the path adjacent to playbooks. They are only loaded from where the inventory file is. This breaks things like vagrant+ansible since it creates a dynamic inventory file(usually in .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory) that is not next to my main ansible structure.
##### Steps To Reproduce:

play.yml

``` yaml
- hosts: all
  tasks:
    - debug: msg={{somevar}}
```

inventory/test_inventory

```
testhost ansible_ssh_host=127.0.0.1
```

host_vars/testhost

``` yaml
somevar: this is some variable
```

Invoke ansible as follows: `ansible-playbook -i inventory/test_inventory play.yml`
##### Expected Results:

```
TASK [debug msg=this is my hostvar] *********************************************
ok: [testhost] => {
    "msg": "this is my hostvar", 
    "changed": false
}
```
##### Actual Results:

```
TASK [debug msg={{somevar}}] ****************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'somevar' is undefined", "failed": true}
```

If I move my inventory file to be in the same directory as `host_vars` and `play.yml` then ansible runs correctly.

**Comment by bcoca** [comment]
confirmed, i reproduced the issue in current devel

**Comment by luisico** [comment]
Having the same issue. As a workaround I symlink vagrant's inventory to a file in the right directory:

```
ln -s .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory development
```

and then set `ansible.inventory_path = "development"` in `Vagrantfile`.

**Comment by jimi-c** [comment]
@ubergeek42 this was fixed yesterday, so updating your checkout should resolve your issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by luisico** [comment]
Thanks, works for me know.

**Comment by ghost** [comment]
Please reopen. It doesn't seem to work here. The hostvars of other machines in vagrant are not correctly filled in. Only the group_vars and host_vars of the current machine are applied. See also #24483
