### ISSUE TITLE
Running from source docs are missing a dependency

### ISSUE THREAD

**Issue by jinnko** [ansible/ansible#11438]
The [docs](http://docs.ansible.com/intro_installation.html#running-from-source) are missing a reference to the `six` module as a dependency.

```
- $ sudo pip install paramiko PyYAML Jinja2 httplib2
+ $ sudo pip install paramiko PyYAML Jinja2 httplib2 six
```

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (ed07a90289991152392b7baa8287afb6521e30b5) should resolve this question or problem for you.

This will be included in the next docs push.

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
