### ISSUE TITLE
with_pipe doesn't grok line breaks

### ISSUE THREAD

**Issue by jan-grant** [ansible/ansible#11454]
```
- hosts: localhost
  vars:
    dir: /tmp/bar
  tasks:
    - file:
        dest: "{{ dir }}"
        state: absent
    - file:
        dest: "{{ dir }}/{{item}}"
        state: directory
      with_items:
        - a
        - b
        - c
    - debug:
        var: item
      with_pipe: find {{ dir }} -maxdepth 1 -mindepth 1 -type d
```

A single `item` is returned, which contains all the output of find (with embedded newlines).

**Comment by jan-grant** [comment]
A more stable test that doesn't rely on the filesystem:

```
- hosts: localhost
  tasks:
    - debug:
        var: item
      with_pipe: printf 'a\nb\nc'
```

**Comment by jimi-c** [comment]
Hi @jan-grant, you can use with_lines or use `lookup('pipe', ...).split('\n')` to get the lines. The with_pipe lookup will always return the raw output of the command only.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
