### ISSUE TITLE
Winrm with V2: Connection variables are not picked up correctly

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11462]
Several users are having issues with Ansible not picking up all "connection variables" when these are placed in separate blocks, such as using [windows:vars]: 
https://github.com/ansible/ansible/issues/11278#issuecomment-117780566
https://github.com/ansible/ansible-modules-extras/pull/398#issuecomment-117756012

This leads to Ansible attempting to perform Winrm connection on port 22, for example. 

(If anyone is able to shed more light on when it fails, please be my guest)

**Comment by trondhindenes** [comment]
Any updates on this? I still need to use the v1 code until this has been resolved.

**Comment by bcoca** [comment]
several fixes went in as this also affected ssh, have you checked against current devel head?

**Comment by trondhindenes** [comment]
At least I'm getting a new error:
azureuser@thansible:~$ ansible -m win_ping all
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: debug() got an unexpected keyword argument 'host'
thansiblewin01.ansib.le | FAILED! => {
    "failed": true,
    "stdout": ""
}

**Comment by bcoca** [comment]
whmm, that might be unrelated issue with winrm plugin others are working on

**Comment by cchurch** [comment]
@trondhindenes: I think that was broken via https://github.com/ansible/ansible/commit/851ed45bbf76b74083a0f7e409811418d45ca217

See if https://github.com/ansible/ansible/pull/11719 works for you.

**Comment by trondhindenes** [comment]
Thanks, I'll test it right away

**Comment by trondhindenes** [comment]
Fantastic work, Chris! This solves all the problems I've been having on V2 using winrm :-)

**Comment by cchurch** [comment]
@trondhindenes can you confirm this works for you using devel since #11719 has been merged?

**Comment by jimi-c** [comment]
@trondhindenes since you previously indicated the above patches resolved the issue for you, we're going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
