### ISSUE TITLE
Ansible accelerate mode can not working

### ISSUE THREAD

**Issue by shencan** [ansible/ansible#11465]
## Issue Type:

Bug Report
## Ansible Version:

`ansible 1.9.1`
## Environment:

`Centos 6.6` and all machines has installed `python-keyczar` package.
## Summary:

Ansible accelerate mode can not working in playbook
## Steps To Reproduce:

site.yaml

<pre>

---
 - hosts: all
   accelerate: true
   tasks:
     - name: test
       shell: hostname
</pre>

Expected Results:

<pre>
[root@vm10-160-112-18 ~]# ansible-playbook  site.yaml -l  172.17.0.10 -vvvv

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
Thursday 02 July 2015  15:31:18 +0800 (0:00:00.015)       0:00:00.015 *********
attempting connection to 172.17.0.10 via the accelerated port 5099
172.17.0.10: sending request for validate_user
172.17.0.10: waiting for validate_user response
172.17.0.10: in recv_data(), waiting for the header
172.17.0.10: got the header, unpacking
172.17.0.10: data received so far (expecting 121): 0
172.17.0.10: received 121 bytes
172.17.0.10: received all of the data, returning
172.17.0.10: received the validate_user response: {u'msg': u'unhandled error in the handle() function', u'failed': True, u'rc': 1}
<172.17.0.10> REMOTE_MODULE setup
EXEC COMMAND mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435822278.43-61461131657903 && echo $HOME/.ansible/tmp/ansible-tmp-1435822278.43-61461131657903
172.17.0.10: in recv_data(), waiting for the header
172.17.0.10: received nothing, bailing out
fatal: [172.17.0.10] => Failed to get a response from 172.17.0.10

TASK: [test] ******************************************************************
Thursday 02 July 2015  15:31:18 +0800 (0:00:00.032)       0:00:00.048 *********
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
Thursday 02 July 2015  15:31:18 +0800 (0:00:00.004)       0:00:00.053 *********
===============================================================================
test -------------------------------------------------------------------- 0.01s

           to retry, use: --limit @/root/site.yaml.retry

172.17.0.10                : ok=0    changed=0    unreachable=1    failed=0
</pre>

**Comment by msaffar** [comment]
Have the same error on RedHat 6.5 and Aix 7.1

**Comment by thudry** [comment]
Same on OSX

**Comment by jimi-c** [comment]
Hi @shencan, this was fixed in 051d04c8d7a01ccc0fa64c2d64395ad9b677d9a7, and will be included in the 1.9.3 release.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
