### ISSUE TITLE
AttributeError: 'TaskQueueManager' object has no attribute '_callback_plugins'

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#11463]
Since 927072546b4ffb12d6642643d44551de945b390f, `TaskQueueManager._callback_plugins` is defined in [`TaskQueueManager.run()`](https://github.com/ansible/ansible/blob/71f72b655ee04c2de5e759c6ccd8cb9386ab491c/lib/ansible/executor/task_queue_manager.py#L208). But it is possible to use  [`TaskQueueManager._callback_plugins`](https://github.com/ansible/ansible/blob/71f72b655ee04c2de5e759c6ccd8cb9386ab491c/lib/ansible/executor/task_queue_manager.py#L287) without calling [`TaskQueueManager.run()'](https://github.com/ansible/ansible/blob/71f72b655ee04c2de5e759c6ccd8cb9386ab491c/lib/ansible/executor/playbook_executor.py#L128).

The error:

```
$ ansible-playbook -l host1 test.yml # test.yml contains : "- hosts: host2"
Traceback (most recent call last):
  File "ansible/ansible.git/bin/ansible-playbook", line 66, in <module>
    sys.exit(cli.run())
  File "ansible/ansible.git/lib/ansible/cli/playbook.py", line 161, in run
    results = pbex.run()
  File "ansible/ansible.git/lib/ansible/executor/playbook_executor.py", line 128, in run
    self._tqm.send_callback('v2_playbook_on_play_start', new_play)
  File "ansible/ansible.git/lib/ansible/executor/task_queue_manager.py", line 288, in send_callback
    for callback_plugin in self._callback_plugins:
AttributeError: 'TaskQueueManager' object has no attribute '_callback_plugins'
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
