### ISSUE TITLE
Ansible fails to report error when task name contains non-ascii characters

### ISSUE THREAD

**Issue by quantum-omega** [ansible/ansible#11472]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

No changes.
##### Environment:

Fedora 22
`Linux  4.0.4-303.fc22.x86_64 #1 SMP Thu May 28 12:37:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
##### Summary:

When, using ansible-playbook, there is an error in a playbook and the error is because of a task that has a non-ascii character in it's name, an exception is printed out instead of the actual error.
##### Steps To Reproduce:

Create a `site.yml` playbook with the following content, encoded as UTF-8:

```

---
- hosts: localhost
  tasks:
    - name: Caractères accentués
```

Run the file like thus:
`ansible-playbook -i inventory_containing_a_localhost_group site.yml`
##### Expected Results:

The following error message appears on screen:

```
ERROR: 'action' or 'local_action' attribute missing in task "Caractères accentués"
```
##### Actual Results:

The following stack trace appears:

```
Traceback (most recent call last):
  File "/home/user/ansible/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/user/ansible/bin/ansible-playbook", line 313, in main
    display("ERROR: %s" % e, color='red')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 60: ordinal not in range(128)
```
##### Suggestions for fix:

Changing the line 313 in ansible-playbook from
`display("ERROR: %s" % e, color='red')`
to
`display(u"ERROR: %s" % e, color='red')`
will make the string interpolation work even when the string representation of the exception `e` would be a unicode string (Python type `unicode`) and display the right message with accents and other non-ascii characters.

This quick fix might have repercussions on the portability of the code between Python versions.

**Comment by abadger** [comment]
This is working in devel.  Looking into a fix for the stable-1.9 branch now.

**Comment by abadger** [comment]
Looks like the display function in the stable-1.9 branch can handle either unicode or byte str.  So your idea to use a unicode string there shouldn't break anything.  I'll push that up in just a moment.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
