### ISSUE TITLE
copy module in v2 does not honour dest argument

### ISSUE THREAD

**Issue by kodfodrasz** [ansible/ansible#11470]
using ansible changeset 08ad05c83bcd7b3dfc63a732f24e87bc41fb2f7d with the copy module for a directory I have observed that the dest argument is not honoured, but the files are copied to the root of the remote filesystem.

Steps which I used to verify the problem:

```
$ ansible -i droplets frontend -m copy -a "src=../demoWebapp/Frontend/public_html/ dest=/srv/www/metrika/"
$ ls ../demoWebapp/Frontend/public_html/
css  index.html  js
$ ansible -i droplets frontend -m copy -a "src=../demoWebapp/Frontend/public_html/ dest=/srv/www/metrika/"
$ ssh root@frontend01 "ls /srv/www/metrika/"
registry.json
$ ssh root@frontend01 "ls /"
bin
boot
css
dev
etc
home
index.html
js
lib
lib64
lost+found
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
$
```

the js, css and index.html entries can be seen in their unexpected locations.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
