### ISSUE TITLE
with_dict + default filter behavior is slightly different in v2

### ISSUE THREAD

**Issue by hfinucane** [ansible/ansible#11530]
This works in v1

```

---
- hosts: all
  gather_facts: no
  tasks:
  - debug: msg={{item.key}}
    with_dict: foo|default({})
```

While in v2 it produces the following error:

```
fatal: [localhost]: FAILED! => {"msg": "ERROR! with_dict expects a dict", "failed": true}
```

Guarding it with a when conditional doesn't help either:

```

---
- hosts: all
  gather_facts: no
  tasks:
  - debug: msg={{item.key}}
    with_dict: foo|default({})
    when: foo is defined
```

Although I think `when` has always evaluated after `with_*`.

This has to do with the filter somehow, because this works just fine:

```

---

- hosts: all
  gather_facts: no
  tasks:
  - debug: msg={{item.key}}
    with_dict: {}
```

**Comment by michaeljs1990** [comment]
I am running version 1.9.2 and I also encountered this exact same error. to clarify guarding with a when does not work in v1.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
