### ISSUE TITLE
with_sequence skipping when count = 1

### ISSUE THREAD

**Issue by phleemac** [ansible/ansible#11546]
The following should print item = 1, however, it's skipping.  Ansible 1.9.2 Linux.

<pre>

---
- name: Re-producing with_sequence bug
  hosts: localhost
  gather_facts: no

  tasks:
  - debug: var=item
    with_sequence: start=1 count=1
</pre>

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
Using /etc/ansible/ansible.cfg as config file
1 plays in 11546.yml
PLAY: Re-producing with_sequence bug ********************************************
TASK [debug var=item] ***********************************************************
{'verbose_always': True, u'item': '1'}
ok: [localhost] => {"msg": "All items completed", "changed": false, "results": [{"verbose_always": true, "item": "1"}]}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
