### ISSUE TITLE
Variables values containing tildes or accents cause a failure

### ISSUE THREAD

**Issue by rodolfojcj** [ansible/ansible#11541]
Hi!

Given a directory with the following tree-like content for a playbook:

```
dummy-playbook/
|-- main.yml
`-- mypeople.yml
```

And given a directory with the following tree-like content for a role:

```
roles/dummy-role/
|-- tasks
|   |-- main.yml
|   `-- people-provisioning.yml
`-- templates
    `-- templaterole.j2
```

And here the content for each of those files:

_dummy-playbook/main.yml_:

```

---
# Ansible dummy playbook
- hosts: my-dummy-host
  vars_files:
    - mypeople.yml
  roles:
    - dummy-role
```

_dummy-playbook/mypeople.yml_:

```

---
people:
  - internalcode: ABC123
    fullname: "Juan Pérez Peña"
```

_roles/dummy-role/tasks/main.yml_:

```

---
# Dummy role main tasks
- include: people-provisioning.yml
  when: people
```

_roles/dummy-role/tasks/people-provisioning.yml_:

```

---
# Dummy role provisioning tasks
- name: Generate people file
  template: src=templaterole.j2 dest=/tmp/people.txt
  with_items: '{{ people }}'
```

_roles/dummy-role/templates/templaterole.j2_:

```
# {{ ansible_managed }}
{{ item.internalcode }}
{{ item.fullname }}
```

When I run the playbook with the following command:
    ansible-playbook -vvv ~/playbooks/dummy-playbook/main.yml

I get this error:

```
TASK: [dummy-role | Generate people file] ************************************* 
fatal: [my-dummy-host] => Failed to template {% if [{'fullname': u'Juan P\xe9rez Pe\xf1a', 'internalcode': 'ABC123'}] %} True {% else %} False {% endif %}: template error while templating string: expected token ',', got 'string'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
       to retry, use: --limit @/home/osg/main.retry

my-dummy-host            : ok=1    changed=0    unreachable=1    failed=0   
```

I did the following:
- Changed the double quotes around the value "Juan Pérez Peña" to single quotes or to no quotes at all, but it failed too
- Changed the value "Juan Pérez Peña" to something like "Juan Perez" and it worked fine
- Rewrote the playbook to a simpler version with no roles and no _"when" conditions_ and it worked fine
- Reviewed the codification of the file _dummy-playbook/mypeople.yml_ and there's no difference in the failed output between UTF-8 and ISO-8859-15
- Removed the condition _"when: people"_ in the file _roles/dummy-role/tasks/main.yml_ and it worked fine

Then, it seems to me there's some kind of bug in the implementation of the _when condition_.

Could someone please review this case?
Thanks in advance!

**Comment by rodolfojcj** [comment]
Regarding the environment I tested on, it is:
- Workstation with Ansible versions 1.9.1 and 1.9.2 and Python version 2.7.6 on Ubuntu 14.04.1 with Linux kernel version 3.19.0-21
- Target host (named _my-dummy-host_) has CentOS 5 with Python version 2.4.3, Python SimpleJSON version 2.0.9 and Linux kernel version 2.6.18

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
PLAY: ***************************************************************************
TASK [dummy-role : dummy-role : include] ****************************************
included: people-provisioning.yml for localhost
TASK [dummy-role : dummy-role : Generate people file] ***************************
{u'src': u'/root/.ansible/tmp/ansible-tmp-1436513308.73-1937450531713/source', u'changed': True, u'group': u'root', u'uid': 0, 'item': {u'fullname': u'Juan P\xe9rez Pe\xf1a', u'internalcode': u'ABC123'}, u'dest': u'/tmp/people.txt', u'checksum': u'2d27d1f0c54ce49e6b68194219a90d84073853c4', u'md5sum': u'3f2c79f0bfe5f89e096912a1f225bc8f', 'invocation': {'module_name': 'copy', 'module_args': {u'src': '/root/.ansible/tmp/ansible-tmp-1436513308.73-1937450531713/source', 'original_basename': u'templaterole.j2', u'dest': u'/tmp/people.txt', 'follow': True}}, u'state': u'file', u'gid': 0, u'secontext': u'unconfined_u:object_r:user_tmp_t:s0', u'mode': u'0644', u'owner': u'root', 'diff': {'after': u'# Ansible managed: /root/testing/11541/roles/dummy-role/templates/templaterole.j2 modified on 2015-07-10 03:27:44 by 0 on jimi\nABC123\nJuan P\xe9rez Pe\xf1a\n', 'before': ''}, u'size': 152}
changed: [localhost] => {"msg": "All items completed", "changed": true, "results": [{"src": "/root/.ansible/tmp/ansible-tmp-1436513308.73-1937450531713/source", "md5sum": "3f2c79f0bfe5f89e096912a1f225bc8f", "group": "root", "uid": 0, "dest": "/tmp/people.txt", "checksum": "2d27d1f0c54ce49e6b68194219a90d84073853c4", "changed": true, "owner": "root", "item": {"fullname": "Juan Pérez Peña", "internalcode": "ABC123"}, "state": "file", "gid": 0, "secontext": "unconfined_u:object_r:user_tmp_t:s0", "mode": "0644", "invocation": {"module_name": "copy", "module_args": {"dest": "/tmp/people.txt", "src": "/root/.ansible/tmp/ansible-tmp-1436513308.73-1937450531713/source", "original_basename": "templaterole.j2", "follow": true}}, "diff": {"after": "# Ansible managed: /root/testing/11541/roles/dummy-role/templates/templaterole.j2 modified on 2015-07-10 03:27:44 by 0 on jimi\nABC123\nJuan Pérez Peña\n", "before": ""}, "size": 152}]}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
$ cat /tmp/people.txt
# Ansible managed: /root/testing/11541/roles/dummy-role/templates/templaterole.j2 modified on 2015-07-10 03:27:44 by 0 on jimi
ABC123
Juan Pérez Peña
</pre>

Per our normal policy, we close bug reports once the issue has been resolved on the development branch, so we will be closing this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rodolfojcj** [comment]
Thanks for reviewing the situation and answering!

An alternative way that works with Ansible 1.9.2 is to use the _is defined_ operator in the _when_ condition, so the file _roles/dummy-role/tasks/main.yml_ looks like this:

```
---
# Dummy role main tasks
- include: people-provisioning.yml
  when: people is defined
```
