### ISSUE TITLE
--extra-vars={ansible_ssh_user:USER} and delegate_to: do not work together

### ISSUE THREAD

**Issue by eparis** [ansible/ansible#11554]
https://github.com/eparis/anisble_ssh_user_bug

For reproducer. It seems as though --user= works....

```
ansible-playbook --extra-vars='{"ansible_ssh_user":"fedora"}' -i inventory cluster.yml -vvvv

PLAY [groupb] ***************************************************************** 

TASK: [doit | Get the node token values] ************************************** 
<209.132.179.61> ESTABLISH CONNECTION FOR USER: eparis
<209.132.179.61> REMOTE_MODULE slurp src=/etc/resolv.conf
<209.132.179.61> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 209.132.179.61 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436556187.78-125165592577875 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436556187.78-125165592577875 && echo $HOME/.ansible/tmp/ansible-tmp-1436556187.78-125165592577875'
fatal: [b1 -> a1] => SSH Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
    while connecting to 209.132.179.61:22
```

**Comment by bcoca** [comment]
might be related to #11436

**Comment by jimi-c** [comment]
Wondering if this is related to https://github.com/ansible/ansible/issues/10781

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the issue described here has been resolved on the devel branch. Here is the output from running your example above:

<pre>
# USER=testing ./broken.sh 
Using /etc/ansible/ansible.cfg as config file
1 plays in cluster.yml
Loaded callback default of type stdout, v2.0
PLAY ****************************************************************************
TASK [doit : Get the node token values] *****************************************
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-251434451969062" && echo "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-251434451969062"
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-226234613743610" && echo "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-226234613743610"
<192.168.122.100> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-199277077540863" && echo "$HOME/.ansible/tmp/ansible-tmp-1437970935.08-199277077540863"
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> PUT /tmp/tmpptpU57 TO /root/.ansible/tmp/ansible-tmp-1437970935.08-226234613743610/slurp
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> PUT /tmp/tmpDsZo25 TO /root/.ansible/tmp/ansible-tmp-1437970935.08-251434451969062/slurp
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> PUT /tmp/tmpp65H6D TO /root/.ansible/tmp/ansible-tmp-1437970935.08-199277077540863/slurp
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=bpkjuyeucosrpfiakcrphwfkoybheoav] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bpkjuyeucosrpfiakcrphwfkoybheoav; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python ; rm -rf "/root/.ansible/tmp/ansible-tmp-1437970935.08-226234613743610/" >/dev/null 2>&1'"'"''
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=delfognunrvrhmljqqozgnwvegoyxzty] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-delfognunrvrhmljqqozgnwvegoyxzty; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python ; rm -rf "/root/.ansible/tmp/ansible-tmp-1437970935.08-199277077540863/" >/dev/null 2>&1'"'"''
<192.168.122.100> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.100> EXEC ssh -C -vvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 192.168.122.100 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=pyzuczrcvoljtmtfqkhbsevcitxfcpuv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pyzuczrcvoljtmtfqkhbsevcitxfcpuv; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python ; rm -rf "/root/.ansible/tmp/ansible-tmp-1437970935.08-251434451969062/" >/dev/null 2>&1'"'"''
ok: [b1] => {"changed": false, "content": "IyBHZW5lcmF0ZWQgYnkgTmV0d29ya01hbmFnZXIKZG9tYWluIHNuZ3gubmV0CnNlYXJjaCBzbmd4Lm5ldApuYW1lc2VydmVyIDE5Mi4xNjguMTIyLjEK", "encoding": "base64", "source": "/etc/resolv.conf"}
ok: [b2] => {"changed": false, "content": "IyBHZW5lcmF0ZWQgYnkgTmV0d29ya01hbmFnZXIKZG9tYWluIHNuZ3gubmV0CnNlYXJjaCBzbmd4Lm5ldApuYW1lc2VydmVyIDE5Mi4xNjguMTIyLjEK", "encoding": "base64", "source": "/etc/resolv.conf"}
ok: [b3] => {"changed": false, "content": "IyBHZW5lcmF0ZWQgYnkgTmV0d29ya01hbmFnZXIKZG9tYWluIHNuZ3gubmV0CnNlYXJjaCBzbmd4Lm5ldApuYW1lc2VydmVyIDE5Mi4xNjguMTIyLjEK", "encoding": "base64", "source": "/etc/resolv.conf"}
PLAY RECAP **********************************************************************
b1                         : ok=1    changed=0    unreachable=0    failed=0   
b2                         : ok=1    changed=0    unreachable=0    failed=0   
b3                         : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
