### ISSUE TITLE
Copy and include module don't search in roles_path for referenced files

### ISSUE THREAD

**Issue by tahajahangir** [ansible/ansible#11566]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

https://github.com/tahajahangir/ansible-bug-copy-roles-path/blob/master/ansible.cfg
##### Environment:

Ubuntu 14.04
##### Summary:

From https://docs.ansible.com/playbooks_roles.html#roles:
- Any copy tasks can reference files in roles/x/files/ without having to path them relatively or absolutely
- In Ansible 1.4 and later you can configure a roles_path to search for roles. 

But actually, `roles_path` is not searched in copy, include and probably other modules.
##### Steps To Reproduce:

This is complete playbook demonstrating this bug:
https://github.com/tahajahangir/ansible-bug-copy-roles-path
##### Expected Results:

Two files should be copied to `/tmp/test1` and `/tmp/test2`, one from current roles directory, and one from a role in `roles_path`.
##### Actual Results:

Copying from current roles directory succeed, but copying from roles_path fails.

**Comment by jimi-c** [comment]
@tahajahangir there are a few problems with your example. First off, the role directory is expected to be at the role_path configured, so in your example it should be `./common/roles`. Second, the role_path is only searched when the task itself comes from a role, so for your example to be valid the two copy calls in your `incl/test.yml` should actually be in the foo/bar roles themselves.

That being said, after making these corrections I'm not seeing any tasks from the two roles execute, so there may be some issues with the way we process roles, especially if roles are coming from multiple paths. I will continue looking into this issue.

**Comment by jimi-c** [comment]
Nevermind, the problem was simply that you have the files under each role's tasks/ directory misnamed (test.yml instead of main.yml). When they were properly renamed, I get the following output:

<pre>
# ansible-playbook -vv -i hosts playbook.yml
Using /root/testing/11566/ansible-bug-copy-roles-path/ansible.cfg as config file
1 plays in playbook.yml
PLAY ****************************************************************************
TASK [foo : foo : debug msg=success-foo] ****************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "success-foo"
}
TASK [foo : foo : copy dest=/tmp/test2 src=test.txt] ****************************
changed: [localhost] => {"changed": true, "checksum": "7ef81d5ffe03a3462a54031c61b88ea8ccbe74d1", "dest": "/tmp/test2", "gid": 0, "group": "root", "md5sum": "7141be0d289d3cac6b09a15ffd95fde6", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 13, "src": "/root/.ansible/tmp/ansible-tmp-1437563012.34-220513478940021/source", "state": "file", "uid": 0}
TASK [bar : bar : debug msg=success-bar] ****************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "success-bar"
}
TASK [bar : bar : copy dest=/tmp/test1 src=test.txt] ****************************
changed: [localhost] => {"changed": true, "checksum": "f731f558dd47416b304ee12fb641741b2aadb131", "dest": "/tmp/test1", "gid": 0, "group": "root", "md5sum": "36d985a355d611c9d2d60d3f8546b5c2", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 13, "src": "/root/.ansible/tmp/ansible-tmp-1437563012.74-51509495436871/source", "state": "file", "uid": 0}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0   
# cat /tmp/test1
bar/test.txt
# cat /tmp/test2
foo/test.txt
</pre>

So there is no issue here, and the role_path is being searched correctly by role tasks.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
