### ISSUE TITLE
unarchive fails to pick up HTTP source

### ISSUE THREAD

**Issue by hrstoyanov** [ansible/ansible#11562]
-unarchive:  
    src: "http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.zip"
    dest: "/tmp"
    copy: no

This fails with: 
msg: Source 'http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.zip' does not exist

although you can verify with your browser that the link works?

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by Hubbitus** [comment]
Hello, I've has that problem too:

##### Issue Type:

Bug Report

##### Ansible Version:

```
$ ansible --version
ansible 1.9.2
  configured module search path = None
```

##### Ansible Configuration:

I belive nothing changed in config related to that functionality

##### Environment:

Fedora 22

##### Summary:

Task declaration:

```
- name: Download and unpack the compressed Gradle
  unarchive: src=https://services.gradle.org/distributions/gradle-{{gradle_version}}-all.zip dest=/opt/gradle/ copy=no
```

##### Steps To Reproduce:

Run task posted early with actual version:

```
- { role: gradle-user, gradle_version: "2.5" }
```

##### Expected Results:

Distribution of gradle downloaded and unpacked, or correct message about error appeared.

##### Actual Results:

```
TASK: [gradle-user | Download and unpack the compressed Gradle] *************** 
failed: [egais.perf.db.master] => {"failed": true}
msg: Source 'https://services.gradle.org/distributions/gradle-2.5-all.zip' does not exist
```

But that file exists and accessible:

```
$ LANG=en_US.utf-8 wget --spider https://services.gradle.org/distributions/gradle-2.5-all.zip
Spider mode enabled. Check if remote file exists.
--2015-07-14 17:06:32--  https://services.gradle.org/distributions/gradle-2.5-all.zip
Resolving services.gradle.org (services.gradle.org)... 207.223.250.8
Connecting to services.gradle.org (services.gradle.org)|207.223.250.8|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.gradle.org/distributions/gradle-2.5-all.zip [following]
Spider mode enabled. Check if remote file exists.
--2015-07-14 17:06:33--  https://downloads.gradle.org/distributions/gradle-2.5-all.zip
Resolving downloads.gradle.org (downloads.gradle.org)... 54.230.98.230
Connecting to downloads.gradle.org (downloads.gradle.org)|54.230.98.230|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65027659 (62M) [application/zip]
Remote file exists.
```

**Comment by bcoca** [comment]
if you read the docs, this feature was added in 2.0, so it won't work in 1.9

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by Hubbitus** [comment]
Indeed. Sorry. And thank you.

**Comment by bcoca** [comment]
added a comment to the example to make it more prominent, since people seem to miss it in the description.
