### ISSUE TITLE
ansible_connection not working on local_actions and connection to vms via localhost

### ISSUE THREAD

**Issue by pgmillon** [ansible/ansible#11564]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.1
##### Ansible Configuration:

Standard
##### Environment:

Running a virtualenv on Arch.
Managing Ubuntu-based systems.
##### Summary:

When using the following inventory :

```
localhost ansible_connection=local ansible_python_interpreter=/home/pgmillon/.virtualenv/ansible/bin/python

[db]
127.0.0.1:2222
```

I've got the following error when trying to run the playbook

```
FATAL: no hosts matched or all hosts have already failed -- aborting
```

I'm running Arch Linux and Ansible is within a virtualenv so without this line I've got the following error (when something goes wrong) :

```
  File "/home/pgmillon/.ansible/tmp/ansible-tmp-1436717919.69-212014276253269/get_url", line 165
    except Exception, err:
                    ^
SyntaxError: invalid syntax


FATAL: all hosts have already failed -- aborting
```

When I use a hostname configured in my hosts file

```
toto.local  127.0.0.1
```

And modify my inventory accordingly :

```
localhost ansible_connection=local ansible_python_interpreter=/home/pgmillon/.virtualenv/ansible/bin/python

[db]
toto.local:2222
```

Everything goes smoothly.

There must be something messing up with localhost and 127.0.0.1 when connecting via SSH + trying to configure interpreter for local_actions.

Regards,
##### Steps To Reproduce:

Use the following inventory :

```
localhost ansible_connection=local ansible_python_interpreter=/home/pgmillon/.virtualenv/ansible/bin/python

[db]
127.0.0.1:2222
```
##### Expected Results:

Any playbook running smoothly.
##### Actual Results:

```
FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by pgmillon** [comment]
Updated the issue accordingly.

**Comment by bcoca** [comment]
so when using connection=local there is no ssh involved, its just a fork.

from the error it seems ansible is executing python3

**Comment by pgmillon** [comment]
yes, I think the inventory lines that says to connect to 127.0.0.1 creates trouble with the "localhost ansible_connection=local ansible_python_interpreter" line

**Comment by bcoca** [comment]
they both resolve to localhost, but having the port there should short circuit that

**Comment by bcoca** [comment]
closing as this was a data issue
