### ISSUE TITLE
SSL Certificate does not belong to * (Ansible 1.9.2)

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible#11579]
In the latest Ansible version 1.9.2 there seems to a problem with SSL Certificate validation:

```
msg: SSL Certificate does not belong to download.jetbrains.com.  Make sure the url has a certificate that belongs to it or use validate_certs=False (insecure)
```

The failing [build](https://travis-ci.org/Oefenweb/ansible-pycharm/jobs/70803232), all other Ansible versions a working.

Is it possible to the problem is related to the `302 Moved Temporarily` to `cloudfront`? See below:

```
# wget https://download.jetbrains.com/python/pycharm-professional-4.5.3.tar.gz
--2015-07-14 09:40:42--  https://download.jetbrains.com/python/pycharm-professional-4.5.3.tar.gz
Resolving download.jetbrains.com (download.jetbrains.com)... 54.217.236.18
Connecting to download.jetbrains.com (download.jetbrains.com)|54.217.236.18|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://d1opms6zj7jotq.cloudfront.net/python/pycharm-professional-4.5.3.tar.gz [following]
--2015-07-14 09:40:42--  https://d1opms6zj7jotq.cloudfront.net/python/pycharm-professional-4.5.3.tar.gz
Resolving d1opms6zj7jotq.cloudfront.net (d1opms6zj7jotq.cloudfront.net)... 216.137.63.43, 216.137.63.163, 216.137.63.19, ...
Connecting to d1opms6zj7jotq.cloudfront.net (d1opms6zj7jotq.cloudfront.net)|216.137.63.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160688951 (153M) [binary/octet-stream]
Saving to: ‘pycharm-professional-4.5.3.tar.gz’
```

**Comment by abadger** [comment]
I think this is a problem with SNI.  We recently implemented a fix for SNI if the host doing the downloading is using python-2.7.9 or greater: https://github.com/ansible/ansible-modules-core/issues/1716

If the host is using python less than 2.7.9 then you unfortunately cannot use get_url securely as the python module that implements the url fetching and certificate verification did not gain the ability to do SNI until 2.7.9.  Two workarounds exist:  You can tell get_url to download this without verifying the certificate belongs to the server using validate_certs=False.  Since this means the connection is subject to man-in-the-middle attacks I would not recommend this if you're downloading from a site where you don't control the network (as seems to be the case here).  You can also use curl or wget with the command module.  They have had support for SNI for longer than the python standard library functions.

You can tell that SNI is being used here by looking at the difference between these two openssl commands:

```
$ openssl s_client -connect download.jetbrains.com:443| openssl x509 -noout -text 
$ openssl s_client -connect download.jetbrains.com:443 -servername download.jetbrains.com | openssl x509 -noout -text
```

When you run them, you'll find that the first version returns a certificate for www.jetbrains.com which does not match with the host that we requested.

The second uses SNI to inform the server that we're attempting to contact download.jetbrains.com.  the server is then able to send the certificate for download.jetbrains.com.

**Comment by tersmitten** [comment]
Thanks for the explanation @abadger

**Comment by trinitronx** [comment]
It seems that the workaround to add `validate_certs=False` returns another error during my testing:

```
failed: [localhost] => {"dest": "/usr/bin/docker-1.3.3", "failed": true, "response": "Request failed: <urlopen error [Errno 1] _ssl.c:492: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>", "state": "absent", "status_code": -1, "url": "https://get.docker.com/builds/Linux/x86_64/docker-1.3.3"}
       msg: Request failed
```

The other workaround with using the `command` module with `curl` or `wget` seems to work.  On some platforms like Ubuntu `12.04`, `curl` is not installed by default, so must be bootstrapped.  On Ubuntu `12.04`, `wget` doesn't work and returns an SSL connection error.

**Comment by naktinis** [comment]
Yes, same issue as for @trinitronx here. Switching to wget.

**Comment by abadger** [comment]
Could you guys open a new bug for the issue with validate_certs false? I
didn't see it when it was initially posted because this ticket is closed.

Knowing ansible version, python version, and url that has the problem will
help in taking it down.

-Toshio
