### ISSUE TITLE
Including empty task files no longer allowed

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#11582]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel 6971e92f39) last updated 2015/07/14 09:44:27 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 9acf10face) last updated 2015/07/13 11:14:56 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8a89f4afe4) last updated 2015/07/13 11:14:56 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/08 13:25:41 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/08 13:25:47 (GMT +200)
  configured module search path = None
```
##### Ansible Configuration:

None
##### Environment:

N/A
##### Summary:

In Ansible 2, it is no longer legal to include an empty task file. This was allowed with Ansible 1.9, and there are Galaxy playbooks that depend on this. From the looks of it, they include boilerplate task files that could just be deleted, but this is a breaking change nonetheless.
##### Steps To Reproduce:

It's easy to repeat with this `playbook.yml`:

``` yaml

---
-
  hosts: localhost
  connection: local
  tasks:
    - include: included.yml
```

We just provide empty YAML in `included.yml`:

``` yaml

---
```
##### Expected Results:

The playbook should complete without error.
##### Actual Results:

```
ansible-playbook -i /dev/null playbook.yml
...
TASK [include] ******************************************************************
included: included.yml for localhost
ERROR! included task files must contain a list of tasks

The error appears to have been in '/home/sheldonh/git/req/playbook.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - include: included.yml
      ^ here
```

Although this example begs the question "But why would you do that?", this problem exists in roles too, where we might have includes for each supported distro, but where not all distros need anything special done. I'm reporting the issue because I ran into a Galaxy playbook is affected.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
