### ISSUE TITLE
Variable resolution wrong if using hostvars

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#11585]
##### Summary:

When resolving a variable from `another_host` via `hostvars` - if that variable is built up from other variables, those are resolved in the content of the `current_host` instead of `another_host`
##### Steps To Reproduce:

Please see https://github.com/dwt/ansible-reproduction-variable-resolution for a reduction.

Calling that playbook will demonstrate the problem in the output.
##### Expected Results:

Using `hostvars` should not change the way variables are evaluated, as that means you can't really get the variables from another host as he would see them, which makes this feature rather dangerous. Instead it should allow to access variables as if another host would access them.
##### Actual Results:

If a variable is a composition of other variables, accessing it through `hostvars` will resolve those other variables in the context of the current host, thus giving unexpected (and sometimes dangerous) results.

**Comment by rbu** [comment]
Same thing happens in 1.9.2

```
~/ansible-reproduction-variable-resolution $ ansible-playbook -i inventory test.yml  

PLAY [host1] ****************************************************************** 

TASK: [This should show "from host 2"] **************************************** 
ok: [host1] => {
    "msg": "from host 2"
}

TASK: [This should show "from host 2" but doesn't] **************************** 
ok: [host1] => {
    "msg": "from host 1"
}

PLAY RECAP ******************************************************************** 
host1                      : ok=2    changed=0    unreachable=0    failed=0   

~/ansible-reproduction-variable-resolution $ ansible --version
ansible 1.9.2
  configured module search path = None
```

**Comment by conrado** [comment]
if you inspect `hostvars` you will notice variables with template strings in them are only evaluated on the target host.

**Comment by dwt** [comment]
On the chat the user halberom suggested that switching the order of the variable definition around could be the reason / solution to this behavior. I tried that and it doesn't change the outcome.

**Comment by dwt** [comment]
conrado: I'm not sure what you mean? It seems you are describing the bug?

**Comment by conrado** [comment]
Yes, it is what is happening. I also noticed the question this bug report originates from on [stackoverflow](https://stackoverflow.com/questions/31350289/how-can-i-access-templated-variables-for-another-host-in-ansible). IMO `hostvars['host']` variables **must** hold values as evaluated on said host.

I must admit ansible's `hostvars` capabilities are very limited. If you do not include a host in a play, it will not be included in `hostvars`.

Perhaps this is an opportunity for cleaning that missing feature too.

**Comment by bcoca** [comment]
@conrado, that is incorrect, what will happen is that the host will not get facts gathered, but host/group vars will still be loaded. For the facts there is a workaround of using fact cache or a 'pre play with those hosts'.  In 2.0 you can do the following:

```
- setup: 
   delegate_to: "{{item}}"
   with_items: "{{groups['all']}}"
```

which will gather facts for all hosts and now populate those hosts, in v1 they would overwrite the 'current' host. Change group for a smaller target.

**Comment by bcoca** [comment]
@dwt, as for the reported issue, I'm not sure this is a bug, I do see what is happening.

when templating data we use the current host's vars and not the vars of the host we reference through hostvars.

**Comment by dwt** [comment]
Well, I think it is a bug in the following sense. When I access a variable through `hostvars[some_other_host]` I usually get the variable he has defined. In cases where that variable is composed of other variables though, suddenly you get the variable from your own host instead. This is highly surprising and inconsistent with the behavior of other variables.

Some reasons why this is bad:
- If I change a variable to a composed variable, that can break the behavior for another host, which hurts real bad during refactoring.
- If a location is a composition, for example a backup location which gets username and host spliced in, it's impossible to get that for another host without repeating the pattern. That is you have to duplicate the information of how the pattern is assembled at each usage.

I think I can go on and list more use cases if you need them - I think this behavior is highly surprising and inconsistent.

So you should really consider it a bug.

**Comment by bcoca** [comment]
@dwt I'm inclined to agree, even though this behavior seems to have been the same since the beginning. I'm actually surprised that this is the first time this is noticed.

**Comment by dwt** [comment]
:-) Well, somebody always has to be the first!

Thanks!

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example:

<pre>
# ansible-playbook -vv test.yml -i inventory 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [This should show "from host 2"] *******************************************
ok: [host1] => {
    "changed": false, 
    "msg": "from host 2"
}
TASK [This should show "from host 2" but doesn't] *******************************
ok: [host1] => {
    "changed": false, 
    "msg": "from host 2"
}
PLAY RECAP **********************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dwt** [comment]
Thanks!
