### ISSUE TITLE
ERROR: Invalid ini entry

### ISSUE THREAD

**Issue by incognito15** [ansible/ansible#11608]
I first time configurating ansible. I use  ansible-playbook 1.7.2, ubuntu 14.10. I am configured playbook and task, created inventory file.
I started ansible follow command
 ansible-playbook -i /etc/ansible/inventory /etc/ansible/roles/preconf/tasks/test_new.yml -v  --list-hosts --list-tasks
 and receipt error:
 ERROR: Invalid ini entry: This - need more than 1 value to unpack

In what my error? What i do wrong?

**Comment by abadger** [comment]
These kinds of questions are better addressed over IRC or the mailing list rather than bug reports.

That error probably mean that there's something wrong with your inventory file.    If you post the error and inventory file to the mailing list we can probably help you figure out what needs changing.

(Also note, 1.7.2 is getting pretty old.. You may want to update to 1.9.2 so that you don't lag too far behind.  I don't think that's the cause of this error for you, though.)

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
