### ISSUE TITLE
Key Error  dependencies from ansible-galaxy install -r requirements.yml in role_dependencies = role_data['dependencies']

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#11621]
##### Issue Type:

Bug Report
##### Ansible Version:

```
fdavis@haifisch> ansible --version
ansible 1.9.2
  configured module search path = None
```
##### Ansible Configuration:

uncommented the following
retry_files_save_path = ~/.ansible-retry
##### Environment:

Server - archlinux
fdavis@haifisch> uname -a
Linux haifisch 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux

Client - ubuntu 14.04 from the Vagrantbox ubuntu/trusty64
vagrant@vagrant-ubuntu-trusty-64:~$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

Better error handling when 'dependencies' is not in role_data during ansible-galaxy install

```
  File "/usr/bin/ansible-galaxy", line 845, in execute_install
    role_dependencies = role_data['dependencies']
KeyError: 'dependencies'
```
##### Steps To Reproduce:

run ansible-galaxy -r requirements.yml -p roles
against

``` yml
# requirements.yml

---
# upstream galaxy role was good
- src: aalda.gocd

# patched waiting for upstream merge
- src: https://github.com/fdavis/ansible-gocd-agent.git
```
##### Expected Results:

Role should install without errors.

``` bash
fdavis@haifisch> ag install -r requirements.yml -p roles
- downloading role 'gocd', owned by aalda
- downloading role from https://github.com/codingbunch/ansible-gocd/archive/v1.0.0.tar.gz
- extracting aalda.gocd to roles/aalda.gocd
- aalda.gocd was installed successfully
- executing: git clone https://github.com/fdavis/ansible-gocd-agent.git ansible-gocd-agent
- executing: git archive --prefix=ansible-gocd-agent/ --output=/tmp/tmp96RGm_.tar HEAD
- extracting ansible-gocd-agent to roles/ansible-gocd-agent
- ansible-gocd-agent was installed successfully
```
##### Actual Results:

Key Errors during install

``` bash
fdavis@haifisch> ag install -r requirements.yml -p roles
- downloading role 'gocd', owned by aalda
- downloading role from https://github.com/codingbunch/ansible-gocd/archive/v1.0.0.tar.gz
- extracting aalda.gocd to roles/aalda.gocd
- aalda.gocd was installed successfully
- executing: git clone https://github.com/fdavis/ansible-gocd-agent.git ansible-gocd-agent
- executing: git archive --prefix=ansible-gocd-agent/ --output=/tmp/tmp96RGm_.tar HEAD
- extracting ansible-gocd-agent to roles/ansible-gocd-agent
- ansible-gocd-agent was installed successfully
Traceback (most recent call last):
 File "/usr/bin/ansible-galaxy", line 959, in <module>
   main()
  File "/usr/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/bin/ansible-galaxy", line 845, in execute_install
    role_dependencies = role_data['dependencies']
KeyError: 'dependencies'
```

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by mkuzmin** [comment]
Your role list includes a link to git repository, but ubuntu/trusty64 Vagrant box does not have git client installed, here is the error.

**Comment by bcoca** [comment]
can you test with 1.9.4 and/or 2.0?

**Comment by fdavis** [comment]
@bcoca Thanks! Looks to be working in 1.9.4

**Comment by udondan** [comment]
I'm getting this exact error in 1.9.4. It does work though in devel.
