### ISSUE TITLE
Timeout causes Fact Cache Corruption

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#11645]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.9.2 (as distributed by Debian, 1.9.2+dfsg-1)
##### Ansible Configuration:

Any playbook containing conditionals involving facts.
##### Environment:

Debian Linux 8.1 (Jessie)
##### Summary:

After a timeout during a play on a slow host, plays involving conditionals fail on that host.
##### Steps To Reproduce:

(Copied from downstream ticket: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792793)

I faced a timeout on a (slow) host:

```
Daneel | FAILED >> {
    "cmd": "/bin/lsblk -ln --output UUID 
/dev/mapper/Daneel_xtra-backup",
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File 
\"/root/.ansible/tmp/ansible-tmp-1437234237.91-43519604009961/setup\", 
line 1677, in run_command\n    rfd, wfd, efd = select.select(rpipes, [], 
rpipes, 1)\n  File 
\"/root/.ansible/tmp/ansible-tmp-1437234237.91-43519604009961/setup\", 
line 1807, in _handle_timeout\n    raise 
TimeoutError(error_message)\nTimeoutError: Timer expired\n",
    "rc": 257
}
```

Since this, playing playbooks failed on that host when conditionals 
where used.

After some digging it appeared the fact cache for this host (using 
jsonfile) only contained the following line:
{"module_setup": true}

So Ansible must not write in cache if any error occurred during fact 
collection.
##### Expected Results:

Fact cache is either deleted upon failure to refresh on next run, or left intact with old data.
##### Actual Results:

Fact cache contains only module setup indication.

**Comment by jimi-c** [comment]
Hi @hlieberman, this should have been fixed in d977da5b41f34933ca11c69d3af766f8ec283b55, which is in devel, and will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
