### ISSUE TITLE
Issue when python-json is installed (centos5à

### ISSUE THREAD

**Issue by perrioto** [ansible/ansible#11654]
Hello,

I would report a issue en centos5 vhen python-json is also installed.
We have installed on the same server:
- python-json-3.4-3.el5
- python-simplejson-2.0.9-8.el5

and when we try to use ansible we have this error:

```
ansible -m ping dc1-mkt-corp-tools-01.corp.dc1.kelkoo.net
dc1-mkt-corp-tools-01.corp.dc1.kelkoo.net | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1437377547.96-17610895201588/ping\", line 1657, in ?\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1437377547.96-17610895201588/ping\", line 47, in main\n    supports_check_mode = True\n  File \"/root/.ansible/tmp/ansible-tmp-1437377547.96-17610895201588/ping\", line 417, in __init__\n    (self.params, self.args) = self._load_params()\n  File \"/root/.ansible/tmp/ansible-tmp-1437377547.96-17610895201588/ping\", line 1144, in _load_params\n    params2 = json_dict_unicode_to_bytes(json.loads(MODULE_COMPLEX_ARGS))\nAttributeError: 'module' object has no attribute 'loads'\n",
    "parsed": false
}
```

without python-json all works fine.
Is it a issue already knew ?

**Comment by abadger** [comment]
Thanks for bringing that up -- it's a problem caused by the python-json module being written before the python standard library json module was added.  The python-json library has the same module name but a different API.  I'll look at detecting the python-json library and utilizing python-simplejson instead.

**Comment by abadger** [comment]
@perrioto That commit should fix this but I also notice that a great many of ansible's modules explicitly use the json or simplejson library.  Those modules won't work if the python-json module is installed so it's probably easiest to uninstall the python-json library if you can.  These changes should get enough ansible modules working so that you can yum uninstall it.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
