### ISSUE TITLE
Repeated role/task names in playbook output in v2

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11691]
Issue type: Bug report
Ansible version: devel
Ansible configuration: NA
Environment: NA
Summary:

Task names are doubled in v2 playbook output. I tracked it down to this part of `get_name` in `lib/ansible/playbook/task.py`:

```
 97     def get_name(self):
 98        ''' return the name of the task '''
 99 
100        if self._role and self.name:
101            return "%s : %s" % (self._role.get_name(), self.name)
```

By adding delimeters to the return, I determined that somehow `self.name` is getting set to "common: " (`self._role.get_name()` returns just "common" as expected), but I ran out of time to dig further.

Steps to reproduce:

Run a playbook that has "roles: common" with names tasks in roles/common/tasks/*.yml.

Expected results:

```
TASK: [common | Install pip] ************************************************** 
```

Actual results:

```
TASK [common : common : Install pip] ********************************************
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
