### ISSUE TITLE
Complex task arguments (args:) ignored

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#11718]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel 88e1ef8c9b) last updated 2015/07/24 12:55:50 (GMT +200)
  lib/ansible/modules/core: (detached HEAD c9b7043ee2) last updated 2015/07/24 12:56:00 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 14fffa5b53) last updated 2015/07/24 12:56:00 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/17 15:26:48 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/17 15:26:52 (GMT +200)
  config file = 
  configured module search path = None
```
##### Ansible Configuration:

None
##### Environment:

N/A
##### Summary:

Complex task arguments specified with `args:` are ignored.
##### Steps To Reproduce:

Create this `playbook.yml`:

``` yaml

---
-
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    debug_vars:
      msg: Hello, world!
  tasks:
    - debug:
        args: "{{ debug_vars }}"
```
##### Expected Results:

As per Ansible 1.9.2:

```
ok: [localhost] => {
    "msg": "Hello world!"
}
```
##### Actual Results:

```
ERROR! this task 'debug' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/root/testing/11718.yml': line 7, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - debug:
    ^ here

```

**Comment by jimi-c** [comment]
@sheldonh `data` is a param specific to the ping module. The syntax you are looking for above is `args:`, which is currently not working in devel. This has been an internal to-do for v2 for a while,  so I'll keep this open on Github so it's visible to other users.

**Comment by jimi-c** [comment]
Updated problem text and title to reflect the issue.

**Comment by sheldonh** [comment]
It's great to hear that it's a v2 milestone, because this is an extremely powerful feature that I'd never seen until someone wanted it on IRC. :-)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
