### ISSUE TITLE
Docker image is required to be pushed when use docker-py>=1.3

### ISSUE THREAD

**Issue by DXist** [ansible/ansible#11710]
Issue Type:

Bug Report

Ansible Version:

ansible 1.9.2

Ansible Configuration:
## 

Environment:

Ubuntu Utopic
docker-py==1.3.1

Summary:

After I update docker-py to 1.3.1 ansible unsuccessfully tries to find my image in private registry which results following error:

```
failed: [127.0.0.1] => {"changes": ["{\"status\":\"Pulling repository myregistry:5000/myimage\"}\r\n", "{\"errorDetail\":{\"message\":\"Error: image myimage:latest not found\"},\"error\":\"Error: image myimage:latest not found\"}\r\n"], "failed": true, "status": ""}
msg: Unrecognized status from pull.

FATAL: all hosts have already failed -- aborting
```

Steps To Reproduce:
1. prepare simple Dockerfile
2. docker build -t myregistry:5000/myimage .
3. run container using following task and `connection=local` parameter:

```
    docker:
      detach: False
      stdin_open: True
      tty: True
      image: "myregistry:5000/myimage"
      name: "container"
      command: "{{ lookup('env', 'SHELL')}}"
      state: started
```

Expected Results:

Ansible should use an image built and saved locally.

Actual Results:

Ansible tries to pull an image from `myregistry:5000`

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by DXist** [comment]
Thanks! I recommend to include this info to the contribution guidelines.
