### ISSUE TITLE
SSL issue using Hipchat

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible#11724]
Running v1.9.2  and running into an issue with Hipchat's module. It was working prior to me updating all the modules.

```
# ansible --version
ansible 1.9.2 (stable-1.9 f074c6ad35) last updated 2015/07/24 15:57:48 (GMT -400)
    lib/ansible/modules/core: (detached HEAD eda33a45e0) last updated 2015/07/24 16:08:00 (GMT-400)
    lib/ansible/modules/extras: (detached HEAD 8c01513e1e) last updated 2015/07/24 16:08:00 (GMT -400)
    v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/07/24 16:08:03 (GMT-400)
    v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/07/24 16:08:08 (GMT -400)
    configured module search path = None
```

Output of task:

```
TASK: [client_install | announce_hipchat] *************************************
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
File "/home/deployment/.ansible/tmp/ansible-tmp-1437769014.82-134926666743109/hipchat", line 1871, in ?
PROTOCOL = ssl.PROTOCOL_TLSv1
NameError: name 'ssl' is not defined
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
