### ISSUE TITLE
vars_files does not use variables from first file for substituting into the name of the second file in a playbook

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#11742]
Ansible version: 1.9.1 on CentOS 6.6

When using facts from gather_facts, it substitutes properly into the filename:

```
  vars_files:
   - vars/vars.yml
   - "vars/{{ ansible_distribution }}_vars.yml"
```

But trying to substitute a variable defined in the first vars file fails:

```
  vars_files:
   - vars/vars.yml
   - "vars/{{ type }}_vars.yml"
```

```
$ ansible-playbook site.yml -i inventory -u root -k -v

PLAY [Ansible Playbook 005] ************************* 

GATHERING FACTS *************************************************************** 
ok: [192.168.100.11]

TASK: [debug var=type] ********************************************** 
ok: [192.168.100.11] => {
    "var": {
        "type": "tcp"
    }
}

TASK: [copy template to server] *********** 
fatal: [192.168.100.11] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'port' is undefined", 'failed': True}
fatal: [192.168.100.11] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'port' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

I turned on debugging to verify that it knows the variable type evaluates to "tcp". 

The only way I am able to make it work at the moment is by passing the variable when running the playbook:
`$ ansible-playbook site.yml -i inventory -u root -k -v -e "type=tcp"`

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example:

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  vars_files:
  - vars/vars.yml
  - "vars/{{ type }}_vars.yml"
  tasks:
  - debug: var=type
  - debug: var=from_type_vars
# cat vars/vars.yml 
type: foo
# cat vars/foo_vars.yml 
from_type_vars: "this is from the vars file with a variable in the name"
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [debug var=type] ***********************************************************
ok: [localhost] => {
    "changed": false, 
    "type": "foo"
}
TASK [debug var=from_type_vars] *************************************************
ok: [localhost] => {
    "changed": false, 
    "from_type_vars": "this is from the vars file with a variable in the name"
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ghost** [comment]
Thanks for the quick response. I look forward to the next release.

**Comment by sebitoelcheater** [comment]
I have ansible 2.3.1.0 and this isn't working:
`
vars_files:
`
`
    - "{{PROJECT_PATH}}/.drim/credentials.yml"
`
any news?

**Comment by 29x10** [comment]
Any update on this?
