### ISSUE TITLE
On notify does not checked handler exist

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#11766]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0
Master 7d8afad28c46ec04e6a32d5aff65bde2d5ab54c5
##### Ansible Configuration:

Irrelevant
##### Environment:

Fedora 22
##### Summary:

You may notify handler which does not present at all.
##### Steps To Reproduce:

Simple playbook:

```
- hosts: server1.local
  tasks:
    - name: Test shell task which always should fire change
      local_action: shell date
      notify:
        - test handler
```
##### Expected Results:

Error what "test handler" not found.
##### Actual Results:

Playbook run and just silent skip notify:

```
$ ap /home/pasha/Projects/Ansible.cfg/test-dev/TestNonExistentHandler.yml 

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [server1.local]

TASK [Test shell task which always should fire change] **************************
changed: [server1.local]

PLAY RECAP **********************************************************************
server1.local              : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Hi @Hubbitus, this behavior is a change from v1 due to the nature of includes in v2. Since includes are now dynamic, they may bring in additional handlers that are not immediately visible in the list of tasks when the play begins executing, so we are now more lenient in allowing notifications that may not be immediately found.

I'll leave this open for now, but I'm not sure if/how we'll fix this to account for the above.

**Comment by Hubbitus** [comment]
So it may be possible notify handlers defined in other roles? It will be cool to do not dupe them if I have roles dependency.

**Comment by bcoca** [comment]
all defined handlers are 'play level' and can be called by any task, so role handlers are callable from other roles. The caveat is that they must be uniquely named or they just 'overwrite' each other.

**Comment by Hubbitus** [comment]
@bcoca it does not work, I just tried. Please look:

```
$ ap test-dev/TestDepRolesHandler.yml 

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [server1.local]

TASK [testdep : Fire test handler from test role] *******************************
changed: [server1.local]

PLAY RECAP **********************************************************************
server1.local              : ok=2    changed=1    unreachable=0    failed=0 
```

cat test-dev/TestDepRolesHandler.yml:

```
- hosts: server1.local
  roles:
    - testdep
```

cat test-dev/roles/testdep/meta/main.yml 

```
dependencies:
  - test
```

cat test-dev/roles/test/handlers/main.yml

```
- name: Test handler from test role
  shell: echo "FIRE Test handler from test role"
```

**Comment by jimi-c** [comment]
@Hubbitus yes, cross-play does not work as the handler information is contained per-play and reset when the new play starts. I don't think that would be easy to implement at this point either.

**Comment by bcoca** [comment]
@Hubbitus as I mentioned before, they are defined at 'play level', not across plays

**Comment by Hubbitus** [comment]
What is "play level"? I run single play in that example, but with 2 roles.

**Comment by bcoca** [comment]
@Hubbitus that works in my tests

**Comment by Hubbitus** [comment]
hm. And what version of ansible you are use?

**Comment by jimi-c** [comment]
@Hubbitus his example was from devel.

Since this issue has not really progressed and the original reported issue will remain as-is in devel/2.0, I'm going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Hubbitus** [comment]
Could you please provide debug output from your run of provided reproduce? With what message ansible fails there??

**Comment by garyayo** [comment]
I just recently updated ansible from 1.9.4 to 2.0.0.1 and I'm experiencing a very similar issue. My handlers are no longer being notified since upgrading to 2.0.

I.E.

```
## in my .yml file
- name: Copy rc.local over
  template: "src=templates/rc.local dest=/etc/rc.local owner={{ default_user }}"
  notify:
    - start uwsgi

## Output from:
## ansible==1.9.4
TASK: [Copy rc.local over] ****************************************************
changed: [ansible_web] => {"changed": true, "checksum": "defdd9bbea6ce0765a7c91edd2c03fdffc6b06b0", "dest": "/etc/rc.local", "gid": 0, "group": "root", "md5sum": "4444bdb22dc44e4db916a50737bb3fa0", "mode": "0755", "owner": "vagrant", "size": 477, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1452716207.89-202383960636512/source", "state": "file", "uid": 1000}

NOTIFIED: [start uwsgi] *******************************************************
changed: [ansible_web] => {"changed": true, "cmd": "/usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --daemonize /var/log/uwsgi-emperor.log", "delta": "0:00:00.005648", "end": "2016-01-13 20:16:48.196342", "rc": 0, "start": "2016-01-13 20:16:48.190694", "stderr": "", "stdout": "", "warnings": []}

PLAY RECAP ********************************************************************
ansible_web                : ok=21   changed=16   unreachable=0    failed=0


## ansible==2.0.0.1
TASK [Copy rc.local over] ******************************************************
changed: [ansible_web] => {"changed": true, "checksum": "defdd9bbea6ce0765a7c91edd2c03fdffc6b06b0", "dest": "/etc/rc.local", "gid": 0, "group": "root", "md5sum": "4444bdb22dc44e4db916a50737bb3fa0", "mode": "0755", "owner": "vagrant", "size": 477, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1452716532.79-97259342851244/source", "state": "file", "uid": 1000}

PLAY RECAP *********************************************************************
ansible_web                : ok=22   changed=14   unreachable=0    failed=0
```

I can't find anything that explains what's going on?

**Comment by mshytikov** [comment]
+1  have the same. Any ideas how to solve?

**Comment by garyayo** [comment]
Hey @mshytikov, so I was able to figure out what the problem was... If you go to http://www.ansible.com/blog/ansible-2.0-launch and scroll down to see the following under _Dynamic Include Problems_

> Handlers in includes will not be seen when a task attempts to notify them, so handlers should avoid using includes at this time.

So my solution was the remove the handlers from the include file and put them directly inline... ie.

```
---
- hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - include: tasks/uwsgi.yml
  handlers:
    - name: start uwsgi
      shell: /usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --daemonize /var/log/uwsgi-emperor.log
```

Hope that helps a bit..

**Comment by mshytikov** [comment]
@garyayo :+1:  Thanks!

**Comment by schnittchen** [comment]
This problem has nothing to do in particular with dynamic includes. I can have `notify: elmofromsesamestreet` and ansible won't tell me that my configuration does not make sense. A handler that is not found is simply, silently, ignored.

This behaviour is potentially dangerous: Assume I have a task that copes with a security problem by changing some config (e.g. disabling some openssh ciphers). After the config change, I want openssh-server to be restarted. I misspell the handler, without noticing, because ansible lets me.
As a result, my server is unpatched until the next reboot or sshd restart, and what is even worse, I am left in a false belief of security, unless I am paranoid enough to sieve through the output from ansible or log into all my servers and look at how long sshd is running...

IMHO this issue should be reopened or another issue opened in its place.

**Comment by dead10ck** [comment]
Guys, this is pretty critical for the reason @schnittchen mentioned above. @jimi-c you shouldn't just close an issue because no progress is being made. You close issues when it's no longer an issue.

**Comment by dead10ck** [comment]
@abadger @AlanCoding @anoek @bbaassssiiee @bcoca @bennojoy @cchurch @chouseknecht @chrishoffman @chrismeyersfsu @defionscode @erjohnso @ghjm @j2sol @jakemcdermott @jaredevantabor @jbrockett @jimi-c @jlaska @jsdalton @lorin @matburt @michelleperz @nitzmahone @petemounce @phips @privateip @ryansb @samdoran @shanemcd @sivel @skottler @smadam813 @softzilla @srvg @thisdavejohnson @tombamford @tonk @wenottingham @wtcross @wwitzel3 someone please reopen and prioritize this issue

**Comment by tima** [comment]
@tima (I feel left out.)

**Comment by ravigude** [comment]
Hello, any update on this issue ? Though technically @garyayo solution works, its a lot of effort to redo lot of our handlers. We would really like to see this solved

**Comment by jimi-c** [comment]
@schnittchen (and @dead10ck), this does have something to do with dynamic includes. In your example, we could check that the named handler was not present and there are no dynamic includes, however now that we have static includes we can get back around to fixing this properly, so I'll re-open it.

**Comment by vkruoso** [comment]
I see that ignoring non-existent handlers might be a nice feature for some cases. If this is fixed, please consider adding an option to ignore missing handlers.

**Comment by netdevfighter** [comment]
We have also the same problem with this change. Please, adding an option to ignore missing handlers. Thanks

**Comment by bcoca** [comment]
did in  #17902

**Comment by jimi-c** [comment]
As of 2.1, the following is the output of the example playbook above:

<pre>
$ ansible-playbook -vv 11766.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: 11766.yml ************************************************************
1 plays in 11766.yml
PLAY [localhost] ***************************************************************
TASK [Test shell task which always should fire change] *************************
task path: /home/jamesc/testing/11766.yml:4
ERROR! The requested handler 'test handler' was not found in the main handlers list
</pre>

As such, we will close this issue now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
