### ISSUE TITLE
sequence.py skips tasks when count=1

### ISSUE THREAD

**Issue by aelent** [ansible/ansible#11774]
@bcoca,

As @bbasata pointed out in "made sequence more flexible #10565" I just want to make sure this doesn't get lost in a Closed ticket.

```
# sequence1.yml

---
- hosts: all
  tasks:
    - debug: msg="Hello World @ {{ item }}"
      with_sequence: count=1

# ansible-playbook -i 'localhost,' -c local sequence1.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="Hello World @ {{ item }}"] **********************************
skipping: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

```
# sequence2.yml

---
- hosts: all
  tasks:
    - debug: msg="Hello World @ {{ item }}"
      with_sequence: count=2

# ansible-playbook -i 'localhost,' -c local sequence2.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="Hello World @ {{ item }}"] **********************************
ok: [localhost] => (item=1) => {
    "item": "1",
    "msg": "Hello World @ 1"
}
ok: [localhost] => (item=2) => {
    "item": "2",
    "msg": "Hello World @ 2"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example:

<pre>
# ansible-playbook -vv 11774.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 11774.yml
PLAY ****************************************************************************
TASK [debug msg=Hello World @ {{ item }}] ***************************************
ok: [localhost] => (item=1) => {
    "item": "1", 
    "msg": "Hello World @ 1"
}
ok: [localhost] => {"changed": false, "msg": "All items completed"}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcoca** [comment]
this is fixed already:

```
ok: [localhost] => (item=1) => {
    "item": "1",
    "msg": "Hello World @ 1"
}
```
