### ISSUE TITLE
Ansible incorrectly constructing paths when running a playbook in a subdirectory

### ISSUE THREAD

**Issue by lukehoersten** [ansible/ansible#11789]
- **Issue Type:** Bug Report
- **Ansible Version:** 2.0.0
- **Ansible Configuration:** Added an additional roles path: `../../ansible/roles`
- **Environment:** OS X 10.11
##### Summary:

```
$ tree project
project
|-- Vagrantfile
|-- ansible.cfg
|-- ansible
|   |-- group_vars
|           |-- all
|   |-- playbook.yml
```

Running `ansible-playbook ansible/playbook.yml` via Vagrant provisioner fails to locate the `provisioning/group_vars/all`. In pre-2.0.0, the `ansible/group_vars/all` was found and used correctly.

Also, it would be nice to be able to use `ansible/ansible.cfg` instead of `./ansible.cfg` just to consolidate my files. In this case `project` is my top-level project directory.
##### Steps To Reproduce:

```
$ vagrant provision
==> vagrant_build: Running provisioner: ansible...
ERROR! the file_name '/Users/luke/project/ansible/ansible/group_vars/builders' does not exist, or is not readable
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

$ cat .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory 
# Generated by Vagrant

vagrant_build ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/luke/project/.vagrant/machines/vagrant_build/virtualbox/private_key

[builders]
vagrant_build
```

Notice the doubling of the directory `ansible/ansible/group_vars` instead of the correct single `ansible/group_vars`.
##### Relevant Bit of Vagrantfile

``` ruby
  config.vm.define "vagrant_build" do |vagrant_build|
    vagrant_build.vm.hostname = "vagrant-build"
    vagrant_build.vm.provision "ansible" do |ansible|
      ansible.limit = "vagrant_build" # Disable default limit to connect to all the machines
      ansible.playbook = "ansible/playbook.yml"
      ansible.groups = {
        "builders" => ["vagrant_build"]
      }
    end
  end
```

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by lukehoersten** [comment]
Updated. Thanks for the tip.

**Comment by bcoca** [comment]
first this looks like a vagrant issue, second i believe the error is already telling you why:

```
/Users/luke/project/ansible/ansible/group_vars/builders
```

^ there seems to be an extra ansible in your path.

**Comment by lukehoersten** [comment]
That's the error: an extra ansible is getting in the path that I didn't put there. The error started when updating ansible to 2.0. I haven't changed Vagrant.

**Comment by bcoca** [comment]
using ansible directly I have no issues like this

**Comment by lukehoersten** [comment]
I'll submit a Vagrant issue and see what comes of it.

**Comment by lukehoersten** [comment]
Looks like this is not related to Vagrant. I was able to reproduce directly:

```
$ ansible-playbook ansible/playbook.yml -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory 
ERROR! the file_name '/Users/luke/project/ansible/ansible/group_vars/builders' does not exist, or is not readable
```

Note the inventory file is quoted in previous comments.

**Comment by abadger** [comment]
Yeah, here's a shorter (non-vagrant) way to reproduce:

```
$ find .                                                                        (17:00:57)
.
./ansible
./ansible/group_vars
./ansible/group_vars/all
./ansible/site.yml
./inven
$ cat inven                                                                     (17:01:34)
localhost
$ cat ansible/group_vars/all                                                    (17:01:47)
test_var: "make a test"
$ cat ansible/site.yml                                                          (17:02:12)
---
- hosts: all
  tasks:
      - debug: var=test_var
$ ansible-playbook ansible/site.yml -i inven                                    (17:02:30)

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [debug var=test_var] *******************************************************
ok: [localhost] => {
    "changed": false, 
    "test_var": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

(Note: I'd already started working on this in #11806 so that's why the variable isn't defined instead of an error being thrown.  If you do this with a fresh checkout, you'll get the reported error from running ansible-playbook)

If there's no variables defined in group_vars/all then the error isn't thrown.  Not sure why that is.

So far I've tracked this to DataLoader._basedir being the directory path up to the .yml file. (which seems proper) and vars/__init__.py:_load_inventory_file() getting a filename that seems to be the dirname(YAML_FILE_GIVEN_ON_CLI).  The latter seems to be the issue to me.

**Comment by lukehoersten** [comment]
Excellent work! Let me know if you want me to test anything.

**Comment by lukehoersten** [comment]
Confirmed this is fixed.

Also, this fixed another issue I was having where `group_vars` of groups of groups (`group:children`) wasn't properly applying it's vars to it's children groups. Just in case this comes up.

**Comment by walterdolce** [comment]
Sorry to bring this back to life again. But if possible I'd like to get clarification from you core maintainers that everything is looking good and that it's just me doing it wrong.


I have the following setup:
```
# Dir structure
group_vars/
    all.yml
roles/
    test/
        tasks/
            main.yml
Vagrantfile
development-playbook.yml
```

The content of the files above is as follows:
```
# group_vars/all.yml
---
main:
  timezone: 'Europe/Zurich'


# roles/test/tasks/main.yml
---
- debug:
    msg: "Timezone is: {{ main.timezone }}"


# Vagrantfile

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./", "/vagrant",
    :nfs => true

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
     vb.name = "test-vm"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./development-playbook.yml"
    ansible.raw_arguments = " -vvvv"
  end
end


# development-playbook.yml
---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - test
```


When I launch Vagrant and it starts to provision, then I get:
```
TASK [test : debug] ************************************************************
task path: /vagrant/roles/test/tasks/main.yml:2
fatal: [default]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'timezone'\n\nThe error appears to have been in '/vagrant/roles/test/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- debug:\n  ^ here\n"
}
	to retry, use: --limit @/vagrant/development-playbook.retry
```

Am I correct in thinking the group_vars are not being imported/seen/included ?

The ansible version from within the VM is:
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

Please note the Vagrant provisioner used here is `ansible_local` , *not* `ansible`. 
That runs from within the VM.

Thank you all.

**Comment by walterdolce** [comment]
I just figured it out. I think this is Ansible not supporting that kind of structure(s)...

If I change my `group_vars/all.yml` to just:
```
main_timezone: "Europe/Zurich"
```
And I reference the var in `roles/test/tasks/main.yml` accordingly:
```
---
- debug:
    msg: "Timezone is: {{ main_timezone }}"
```

Then it works.

@bcoca / @LukeHoersten is it expected from Ansible?

I would have expected that the variable structures are supported in the same way no matter where they are defined (in `vars`, or `group_vars`, etc).

**Comment by bonuscheese** [comment]
I'm experiencing the same thing as @walterdolce with nested vars not being picked up from `group_vars/all.yml `

**Comment by meersjo** [comment]
Similar, but interestingly it worked fine with a vagrant host; but when I copy/pasted the role definition to an actual plabook it stopped working.

Given that they're a related set of settings (proxy variables) it's very convenient to have them together in a list.
