### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11794]
remote: Counting objects: 156, done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 156 (delta 72), reused 43 (delta 43), pack-reused 24
Receiving objects: 100% (156/156), 145.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (72/72), completed with 36 local objects.
From github.com:ansible/ansible
   29347ac..527ae36  devel      -> origin/devel
   2714080..6dfa93b  stable-1.9 -> origin/stable-1.9
- [new branch]      synchronize-fix -> origin/synchronize-fix
  First, rewinding head to replay your work on top of it...
  Fast-forwarded devel to 527ae360b041c3777f9b2d0f82fe6463028c7b5b.

$ ansible --version
Traceback (most recent call last):
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/bin/ansible", line 40, in <module>
    from ansible.utils.display import Display
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/utils/display.py", line 32, in <module>
    from ansible import constants as C
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/constants.py", line 103, in <module>
    p, CONFIG_FILE = load_config_file()
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/constants.py", line 81, in load_config_file
    if os.path.isdir(path0):
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by amenonsen** [comment]
Fixed in #11795

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
