### ISSUE TITLE
global retry setting

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible#11797]
I try to deploy distributed application to the number of amazon instances.
Some times something happens with amazon network and deploy process fails.
It will be very helpful to have global retry settings, so every command retries in cace of broken connection before failure.

**Comment by halberom** [comment]
By default a '<playbook name>.retry' file is created if hosts fail.  It should be relatively trivial to wrap your playbook execution and check for the creation of such a file, and then re-run using it.

**Comment by awasilyev** [comment]
I know, but this is a quiet different path.
In case of one job on one node failed - all other nodes will proceed with next steps, and retry will be attempted only when deploy finished. But I am talking about something like
- action: shell /usr/bin/foo
  register: result
  until: result.stdout.find("all systems go") != -1
  retries: 5
  delay: 10

but for all steps, configured globally. if step fail - we will try to rerun it for 5-10 times with 5 seconds delay for example. Both parameters should configures globally in ansible.cfg or as parameters to the role

**Comment by jimi-c** [comment]
The global retry settings feature has already been implemented, and can be controlled via the ansible.cfg options `retry_files_enabled` and `retry_files_save_path`. We do have an outstanding issue to get this documented however: https://github.com/ansible/ansible/issues/11491.

For your other comment, you should look at using other options on the play to control how things proceed, such as max_fail_pct and serial batches, to prevent a full deployment in the event of a subset of failures.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
