### ISSUE TITLE
AnsibleModule() class argument_spec parsing broken

### ISSUE THREAD

**Issue by pcktdmp** [ansible/ansible#11820]
##### Issue Type:

Bug report
##### Ansible Version:

2.0.0 0.0.pre
##### Ansible Configuration:

Vanilla git clone
##### Environment:

Reproducible on CentOS 6/7
##### Summary:

In the most recent version of Ansible I have found that evaluation of module parameters is broken with 'test-module'
AnsibleModule() will always return an emtpy module.params['name'](for example)
##### Steps To Reproduce:

```
./test-module -m module.py -a "name=test state=present" 
```

With version v1.9.2-0.1.rc1 this does work.
##### Expected Results:

Being able to use module arguments in ./test-module
##### Actual Results:

Returns that name is empty but is required (which is it but is being set)

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by abadger** [comment]
It looks like hacking/test-module hasn't been ported to v2 (or has been incompletely ported to v2).  I think I can whip up something that addresses this particular problem but I'm not sure if there's other bugs related to using test-module with v2 that I don't see.

**Comment by abadger** [comment]
I think that commit will fix this for you.  With it applied I now see this:

```
$ hacking/test-module -m lib/ansible/modules/core/packaging/os/yum.py -a 'name=python-q state=present'
* including generated source, if any, saving to: /home/badger/.ansible_module_generated
* this may offset any line numbers in tracebacks/debuggers!
***********************************
RAW OUTPUT
{"msg": "", "changed": false, "results": ["python-q-2.5-2.fc21.noarch providing python-q is already installed"], "rc": 0}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "python-q-2.5-2.fc21.noarch providing python-q is already installed"
    ]
}
```

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by pcktdmp** [comment]
Thanks for the ad-hoc fix! :+1:
