### ISSUE TITLE
"script" module behaves unexpectedly

### ISSUE THREAD

**Issue by adeck** [ansible/ansible#11829]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2

(I used the default version of ansible in the debian jessie repositories. And will continue to do so, because installing software outside the package manager is a recipe for getting behind on security bugfixen.)
##### Ansible Configuration:

This is the only thing in my `ansible.cfg`:

```
[defaults]
ansible_managed = "This file is managed by Ansible. Do not edit manually."
```
##### Environment:

Really doesn't matter, but as stated above, Debian 8 (Jessie).
##### Summary:

Have the [`script`](http://docs.ansible.com/ansible/script_module.html) module accept `args` the same way the [`shell`](http://docs.ansible.com/ansible/shell_module.html) module does. At the moment, it does the worst possible thing; it doesn't fail, it just silently ignores `args`.
##### Steps To Reproduce:

The script runs every time, regardless of whether or not the file already exists.

```
- name: create CA cert
  script: mk-ca.sh
  args:
    creates: /etc/easy-rsa-openvpn/keys/ca.crt
```

And this works as expected:

```
- name: create CA cert
   script: mk-ca.sh creates=/etc/easy-rsa-openvpn/keys/ca.crt
```

Which violates the principle of least surprise; either the first one should simply fail with an error, or the first one should behave identically to the second one.
##### Expected Results:

I expected

```
args:
  created: <filename>
```

to work the same way in [script](http://docs.ansible.com/ansible/script_module.html) as it does in [shell](http://docs.ansible.com/ansible/shell_module.html)
##### Actual Results:

It's really all covered above.

**Comment by amenonsen** [comment]
Quick testing note: this works  as expected in `devel`, but `stable-1.9` still displays the always-run behaviour with `args:`. But it skips correctly if you use `command` instead of `script`.

**Comment by jimi-c** [comment]
Hi, as this situation is no longer present, we will close this issue now. Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by danielcompton** [comment]
I had this issue in Ansible 1.9.4, but not in 2.0.0-0.8.rc3_1 (from Homebrew).
