### ISSUE TITLE
Wording of hg module documentation misleading

### ISSUE THREAD

**Issue by assarbad** [ansible/ansible#11824]
##### Issue Type:
- Documentation Report
##### Ansible Version:
- `ansible 2.0.0`
##### Ansible Configuration:

Not relevant for the ticket.
##### Environment:

Ubuntu 14.04, fully updated.
##### Summary:

The current documentation for the `hg` module in its synopsis states:

> Manages Mercurial (hg) repositories. Supports SSH, HTTP/S and local address.

I was led to use this module because I saw the following warning in my registered result:

```
"warnings": ["Consider using hg module rather than running hg"]
```

This seems to suggest that I should be able to **push** to a remote repository. However, the documentation only mentions cloning, not pushing or pulling.
##### Steps To Reproduce:

Using the following playbook

```

---
- name: Update repos
  hosts: lxchost
  sudo: True
  connection: local
  gather_facts: False
  tasks:
    - name: Push
      hg: repo="/root/repo" dest="ssh://{{item}}/repo"
      with_items: "{{groups['enabled']}}"
```

and existing repositories on the hosts in group `enabled`, run the playbook.
##### Expected Results:

I expected it to push the changes. After all the warning pointed me to the `hg` module as a response to my attempt to push to the hosts using the `command` module.
##### Actual Results:

```
TASK: [Push] *******************************************
failed: [lxchost] => (item=machine1) => {"failed": true, "item": "machine1", "playbook": "playbooks/push.yml", "role": null, "task": "Push"}
msg: abort: repository .dotfiles already exists!
abort: could not create remote repo!

failed: [lxchost] => (item=machine2) => {"failed": true, "item": "machine2", "playbook": "playbooks/push.yml", "role": null, "task": "Push"}
msg: abort: repository .dotfiles already exists!
abort: could not create remote repo!
```

Ansible fails, telling me that the remote repo exists. Right, so how do I push changes rather than clone a fresh copy?

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by assarbad** [comment]
Thanks, I opened it as [#1851](https://github.com/ansible/ansible-modules-core/issues/1851) in `ansible-modules-core`.
