### ISSUE TITLE
Synchronize module doesn't read host_vars/locahost

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#11836]
The problem started with this error on my system:
https://gist.github.com/Tahvok/a04a5344b919b33e7ada

After some debugging with @abadger we came to the conclusion that I need to set `ansible_python_interpreter` to python2 as I have python3 on my local machine as the default, but this problem came up:

Synchronize module doesn't read host_vars/locahost as in this example:

$ cat sync_test.yml

``` yaml

---
- hosts: antest
  tasks:
  - synchronize:
      src: /tmp/some_file
      dest: /tmp/
```

$ cat host_vars/localhost 

``` yaml

---
ansible_python_interpreter: /usr/bin/python2
```

Error:

```
ansible-playbook sync_test.yml 

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [antest]

TASK [synchronize dest=/tmp/ src=/tmp/some_file] ********************************
fatal: [antest]: FAILED! => {"changed": false, "failed": true, "msg": "  File \"/home/albert/.ansible/tmp/ansible-tmp-1438532538.89-25095218155511/synchronize\", line 910\n    except OSError, e:\n                  ^\nSyntaxError: invalid syntax\n", "parsed": false}                                                                   

PLAY RECAP **********************************************************************
antest                     : ok=1    changed=0    unreachable=0    failed=1
```

A working example with a symlinked /usr/bin/python -> /usr/bin/python2:
https://gist.github.com/Tahvok/2717ff16009f80d835f0

**Comment by abadger** [comment]
Two potential solutions here.

(A) In this section of the synchronize code:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/synchronize.py#L129

we need to get ansible_python_interpreter out of the hostvars and put it into the toplevel task_vars.

(B) Or in this section of the modules_common code:
https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/module_common.py#L181

we need to look for ansible_python_interpreter in the hostvars. 

Since the module_common code doesn't know about what host we're connecting to I think (A) is where we should fix this, at least for now.

There's a second problem with localhost and 127.0.0.1 not being properly combined.  It seems that if both 127.0.0.1 and localhost are specified in inventory then the two entries are combined.  If only one is, then the "implicit localhost" feature is creating the other entry and the two entries are unmerged.

**Comment by abadger** [comment]
Potential implementation of (A) https://gist.github.com/abadger/ac89bb94f2bd04606c7c  Going to look into the localhost/127.0.0.1 problem later today/tomorrow to see if I can wrap that up into this same commit.

**Comment by abadger** [comment]
Alright @Tahvok this should fix things now.  Ping me again on IRC if you need help going from the symlink stuff that we had working for you last week to using ansible_python_interpreter with this fix applied.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
