### ISSUE TITLE
free strategy doesn't execute more than one play in playbook

### ISSUE THREAD

**Issue by vbichov** [ansible/ansible#11839]
- **Version:**

$ ansible --version
ansible 2.0.0 (devel a586c74967) last updated 2015/07/23 02:37:33 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 222927256d) last updated 2015/07/23 00:37:20 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 167cad99fa) last updated 2015/07/23 00:37:55 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/23 00:38:37 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/23 00:39:11 (GMT -700)
  config file = 
  configured module search path = None
- **How to reproduce:**

``` yaml

---
- hosts: localhost
  strategy: free
  tasks:
    - debug: msg="message 1"


- hosts: localhost
  strategy: free
  tasks:
    - debug: msg="message 2"

```

Results in:

```
bichov@ubuntu:/playground/pss-client$ ansible-playbook reproducer.yaml -i inventory

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [debug msg=message 1] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "message 1"
}

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

_note there is no message 2_
- **Expected behaviour**

Similar to the following:

``` yaml

---
- hosts: localhost
  strategy: linear
  tasks:
    - debug: msg="message 1"


- hosts: localhost
  strategy: linear
  tasks:
    - debug: msg="message 2"

```

Which gives:

```
PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [debug msg=message 1] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "message 1"
}

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [debug msg=message 2] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "message 2"
}

PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
