### ISSUE TITLE
"No module named apt"

### ISSUE THREAD

**Issue by skorokithakis** [ansible/ansible#11841]
I'm running ansible 1.9.2, and whenever I try to run a local-only playbook, it will fail when `sudo`ing with "no module named apt". Here:

``` .yaml
- name: A playbook.
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add Virtualbox PPA.
    apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian {{ hostvars[inventory_hostname]["ansible_distribution_release"] }} contrib' state=present
    register: ppa
    sudo: yes
```

```
TASK: [Add Virtualbox PPA.] *************************************************** 
failed: [127.0.0.1] => {"failed": true, "parsed": false}
BECOME-SUCCESS-njkogljwfxlehmsowszihlswijugnutk
Traceback (most recent call last):
  File "/home/stavros/.ansible/tmp/ansible-tmp-1438627945.63-31357676881100/apt_repository", line 2749, in <module>
    main()
  File "/home/stavros/.ansible/tmp/ansible-tmp-1438627945.63-31357676881100/apt_repository", line 400, in main
    install_python_apt(module)
  File "/home/stavros/.ansible/tmp/ansible-tmp-1438627945.63-31357676881100/apt_repository", line 112, in install_python_apt
    import apt
ImportError: No module named apt
```

**Comment by skorokithakis** [comment]
Apparently, this works fine if I run the script from outside my virtualenv (using the system's env), but not inside the virtualenv.

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- This seems to be an installation issue, you are using ansible on one python and have the apt module installed in another.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by leifhanack** [comment]
_off-topic_ @skorokithakis did you solved your virtualenv setup problem? It seems I have the same problem with python

**Comment by skorokithakis** [comment]
@leifhanack I just used the system's venv, IIRC.

**Comment by lowks** [comment]
+1 I have the same problem when using a virtualenv.
