### ISSUE TITLE
win_iis_website ignores required "name" parameter

### ISSUE THREAD

**Issue by rriggs** [ansible/ansible#11842]
I am querying an IIS server with two web sites.  No matter what "name" parameter I pass, I get back both web sites, both app pools for the two web sites, etc.  I don't have to pass a valid name or I can pass a valid name for either site.  I always get back both.

I am running IIS7 on Windows 2008R2 with PowerShell 4.0

I seem to be hitting this defect:
http://stackoverflow.com/questions/4170530/powershell-get-website-name-parameter-is-ignored

That link lists some workarounds.  These seem to work for me in PowerShell.

**Comment by cchurch** [comment]
This issue should be filed in the [ansible-modules-extra](https://github.com/ansible/ansible-modules-extras) repo instead of this one.

However, I've found this bug already and submitted https://github.com/ansible/ansible-modules-extras/pull/797, which should take care of this issue once merged.  Please try my changes there and give it a :+1: if that fixes your problem.
