### ISSUE TITLE
set_facts fails silently when given a variable that starts with a number

### ISSUE THREAD

**Issue by scofflan** [ansible/ansible#11851]
Tested on Ansible 1.6.3

```

---
# test set_facts

- name: test
  hosts: 127.0.0.1
  tasks: 
  - name: Set facts
    set_fact:
        var1: foo
        2var: bar
  - debug: var=var1
  - debug: var=2var
```

ansible-playbook test.yaml 

```
 _____________ 
< PLAY [test] >
 ------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 _________________ 
< TASK: Set facts >
 ----------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [127.0.0.1]
 ______________________ 
< TASK: debug var=var1 >
 ---------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [127.0.0.1] => {
    "var1": "foo"
}
 ______________________ 
< TASK: debug var=2var >
 ---------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [127.0.0.1] => {
    "2var": "{{ 2var }}"
}
 ____________ 
< PLAY RECAP >
 ------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0  
```

set_fact siliently fails as 2var is set but then is unavailable for use.

**Comment by jimi-c** [comment]
Hrm, interesting, `- set_fact: 2-var='foo'` also works. Looking into this.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
