### ISSUE TITLE
When not working from include

### ISSUE THREAD

**Issue by chrisdail** [ansible/ansible#11852]
I'm using the latest ansible from the master branch to ensure my playbooks are combatible with 2.0 when it arrives. The when attribute of include does not seem to work anymore.

This is the error I'm getting:

```
ERROR! 'when' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/opt/emc/caspian/bedrock/playbooks/foo.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: bar.yml
  ^ here
```

Here is a test showing the issue. Test run by running 'ansible-playbook foo.yml'

foo.yml:

```
- include: bar.yml
  when: bar_enabled | bool
```

bar.yml:

```
- name: bar
  hosts: all
  tasks:
  - debug: "msg=Bar"
```

This same test works with 1.9.2

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
