### ISSUE TITLE
Loop on lookup_plugin from role rejected

### ISSUE THREAD

**Issue by quinot** [ansible/ansible#11858]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel faf4c3bb6c) last updated 2015/08/05 11:31:42 (GMT +200)
##### Ansible Configuration:

Default
##### Environment:

Debian 8.1 Jessie
##### Summary:

A playbook cannot directly use a loop base on a lookup plugin provided by a role.
##### Steps To Reproduce:

Consider a role providing a lookup plugin:

```
$ mkdir -p roles/lookup_myitems/lookup_plugins
$ cp $ANSIBLE_ROOT/lib/ansible/plugins/lookup/items.py roles/lookup_myitems/lookup_plugins/myitems.py
```

A playbook that attempts to use a `with_myitems` loop in a task is then rejected:

```
$ cat test_role_lookup.yml 

---
- hosts: localhost
  roles:
    - lookup_myitems
  tasks:
    - name: enumerate stuff
      debug: msg="item {{item}}"
      with_myitems:
        - foo
        - bar
```

It seems to me that while loading a play, roles need to be _loaded_ before we can _preprocess_ tasks. Or alternatively the setup of plugin directories should be part of prerpocessing roles, not loading them.
##### Expected Results:

Success (display of the two debug messages "item foo" and "item bar").
##### Actual Results:

```
$ ansible-playbook test_role_lookup.yml
ERROR! 'with_myitems' is not a valid attribute for a Task
```

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by quinot** [comment]
Ticket description updated following template.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by quinot** [comment]
Thanks @jimi-c, I confirm that your latest commits appears to resolve the problem!
