### ISSUE TITLE
Directive "become" (sudo) not working unless using ANSIBLE_KEEP_REMOTE_FILES=1, Oracle Linux 6.6

### ISSUE THREAD

**Issue by dawud** [ansible/ansible#11859]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```
##### Ansible Configuration:

Sanitized `diff` follows:
    --- ansible/examples/ansible.cfg  2015-07-03 18:24:28.138641679 +0100
    +++ my/ansible.cfg  2015-05-14 21:14:03.000000000 +0100

```
-inventory      = /etc/ansible/hosts
-#library        = /usr/share/my_modules/
+hostfile       = /etc/ansible/hosts
+library        = /usr/share/ansible
-transport      = smart
+transport      = ssh
+fact_caching   = memory
-gathering = implicit
+gathering = smart
-#deprecation_warnings = True
+deprecation_warnings = True
-fact_caching = memory
+http_user_agent = ansible-agent
-#pty=False
+pty=False
 #ssh_args = -o ControlMaster=auto -o ControlPersist=60s
+ssh_args = -o ControlMaster=auto
-#control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
+control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
-#pipelining = False
+pipelining = False
-#scp_if_ssh = True
+scp_if_ssh = True
```
##### Environment:

Oracle Linux 6.6
##### Summary:

This issue seems to be similar to [#11611](https://github.com/ansible/ansible/issues/11611), but that one was reported as fixed by the OP.
This is happening on an ansible installation built from the git repo.
Running `ansible` with `--become` does not work unless `ANSIBLE_KEEP_REMOTE_FILES=1` is used.
##### Steps To Reproduce:
1. Install `ansible` from the git repository
2. Try to run an ad-hoc task that requires becoming a different user
##### Expected Results:

`ansible` does not require the `ANSIBLE_KEEP_REMOTE_FILES=1` environmental variable set.

```
$ ansible -vvv host.example.com -a 'uptime' -b --become-user someuser --ask-become-pass
Using /etc/ansible/ansible.cfg as config file
SUDO password:
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com mkdir -p "/tmp/ansible-tmp-1438770811.21-268931387794476" && chmod a+rx "/tmp/ansible-tmp-1438770811.21-268931387794476" && echo "/tmp/ansible-tmp-1438770811.21-268931387794476"
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> PUT /tmp/tmpwYsPWI TO /tmp/ansible-tmp-1438770811.21-268931387794476/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com chmod a+r /tmp/ansible-tmp-1438770811.21-268931387794476/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=durhytuchutihmjtwzxoafmfwshdrdyn] password: " -u someuser /bin/sh -c '"'"'echo BECOME-SUCCESS-durhytuchutihmjtwzxoafmfwshdrdyn; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1438770811.21-268931387794476/command'"'"''
host.example.com | SUCCESS | rc=0 >>
 10:33:32 up 109 days, 20:12,  2 users,  load average: 0.01, 0.01, 0.00
```
##### Actual Results:

Two runs, with `-vvv`, with and without the environmental variable set:

```
$ ansible -vvv host.example.com -a 'uptime' -b --become-user someuser --ask-become-pass
Using /etc/ansible/ansible.cfg as config file
SUDO password:
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com mkdir -p "/tmp/ansible-tmp-1438770797.51-185748965806726" && chmod a+rx "/tmp/ansible-tmp-1438770797.51-185748965806726" && echo "/tmp/ansible-tmp-1438770797.51-185748965806726"
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> PUT /tmp/tmp_vRyjd TO /tmp/ansible-tmp-1438770797.51-185748965806726/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com chmod a+r /tmp/ansible-tmp-1438770797.51-185748965806726/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=adxaihuxqpizkhqbveobukxvznmrytwo] password: " -u someuser /bin/sh -c '"'"'echo BECOME-SUCCESS-adxaihuxqpizkhqbveobukxvznmrytwo; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1438770797.51-185748965806726/command'"'"''
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com rm -rf /tmp/ansible-tmp-1438770797.51-185748965806726/ >/dev/null 2>&1
host.example.com | FAILED | rc=0 >>
ERROR! Connection closed waiting for privilege escalation password prompt:


$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible -vvv host.example.com -a 'uptime' -b --become-user someuser --ask-become-pass
Using /etc/ansible/ansible.cfg as config file
SUDO password:
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com mkdir -p "/tmp/ansible-tmp-1438770811.21-268931387794476" && chmod a+rx "/tmp/ansible-tmp-1438770811.21-268931387794476" && echo "/tmp/ansible-tmp-1438770811.21-268931387794476"
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> PUT /tmp/tmpwYsPWI TO /tmp/ansible-tmp-1438770811.21-268931387794476/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com chmod a+r /tmp/ansible-tmp-1438770811.21-268931387794476/command
<host.example.com> ESTABLISH SSH CONNECTION FOR USER: sysadm
<host.example.com> EXEC ssh -C -tt -q -o ControlMaster=auto -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 host.example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=durhytuchutihmjtwzxoafmfwshdrdyn] password: " -u someuser /bin/sh -c '"'"'echo BECOME-SUCCESS-durhytuchutihmjtwzxoafmfwshdrdyn; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1438770811.21-268931387794476/command'"'"''
host.example.com | SUCCESS | rc=0 >>
 10:33:32 up 109 days, 20:12,  2 users,  load average: 0.01, 0.01, 0.00
```

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- tested against every version of ansible since 1.9.0 and sudo was used in every case without requiring ANISBLE_KEEP_REMOTE_FILES

And we suggest that:
- Retest with a more recent version of ansible.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!
