### ISSUE TITLE
Role dependencies only run once, even with serial enabled

### ISSUE THREAD

**Issue by MichaelDrogalis** [ansible/ansible#11863]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible 2.0.0 (devel 9aa4214417) last updated 2015/07/31 08:03:38 (GMT -700)`
##### Ansible Configuration:

``` text
[defaults]                                                                                                                                                  
filter_plugins = /usr/share/ansible_plugins/filter_plugins:./filter_plugins
roles_path = roles
host_key_checking = False
```
##### Environment:

OS X 10.9
##### Summary:

I have a role A with a dependency on role B. Role B is normally executed implicitly by role A's `meta/` folder specifying role B as a dependency. Role B gets executed _against each host_ before role A. Then, I set role A to be `serial` with a value of 1. I have three hosts in the inventory. Now when I run the playbook, role B only executes against the first host in the inventory, and is skipped on subsequent hosts.
##### Steps To Reproduce:
- Make a playbook with two roles
- Make role A depend on role B
- Set the inventory size to anything greater than 1
- Make role A serial with a value of 1
- Run the playbbook
##### Expected Results:

Role B executes against every host in the inventory when role A has `serial` set to 1.
##### Actual Results:

Role B only executes against the first host in the inventory.

**Comment by MichaelDrogalis** [comment]
Pull request opened at #11878.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
