### ISSUE TITLE
Role dependencies misbehave when running playbook selectively with --tags

### ISSUE THREAD

**Issue by nikut** [ansible/ansible#11871]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2 (detached HEAD f974ff6972) last updated 2015/06/30 09:32:58 (GMT +300)
  lib/ansible/modules/core: (detached HEAD ea913bada2) last updated 2015/06/30 09:33:13 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD f291e9fcc3) last updated 2015/06/30 09:33:14 (GMT +300)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/06/30 09:33:14 (GMT +300)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/06/30 09:33:14 (GMT +300)
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

When multiple roles share a common dependency and the first role with that dependency is skipped due to --tags, the dependency is never run. 
##### Steps To Reproduce:

Playbook:

```

---
- name: Role dependency test
  hosts: localhost
  gather_facts: no
  roles:
    - { role: test-role-2, tags: test-role-2 }
    - { role: test-role-3, tags: test-role-3 }
```

Both test-role-2 and test-role-3 define test-role-1 as a dependency in meta/main.yml:

```
dependencies: 
  - test-role-1
```
##### Expected Results:

test-role-1 should always run, whether running the playbook as-is, with `--tags test-role-2` or with `--tags test-role-3`. 
##### Actual Results:

When running the playbook entirely or with `--tags test-role-2` it works as expected (test-role-1 runs first):

```
> ansible-playbook playbooks/test-role-dependency.yml --tags test-role-2

PLAY [Role dependency test] *************************************************** 

TASK: [test-role-1 | Task in test-role-1 should always run] ******************* 
ok: [localhost] => {
    "msg": "Task in test-role-1"
}

TASK: [test-role-2 | Task in test-role-2 should run when requested] *********** 
ok: [localhost] => {
    "msg": "Task in test-role-2"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

However, with `--tags test-role-3` or `--skip-tags test-role-2` the dependency is ignored (test-role-1 never runs):

```
> ansible-playbook playbooks/test-role-dependency.yml --tags test-role-3

PLAY [Role dependency test] *************************************************** 

TASK: [test-role-3 | Task in test-role-3 should run when requested] *********** 
ok: [localhost] => {
    "msg": "Task in test-role-3"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
Hi @nikut, this has been discussed in other issues, however the problem has been corrected in devel (and will be included in the 2.0 release). Per our normal policy, we close issues when the problem has been resolved in the devel branch, so we will close this as well.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
