### ISSUE TITLE
cannot set run_once via vars

### ISSUE THREAD

**Issue by vlad-belogrudov** [ansible/ansible#11876]
I try to set run_once via vars but tasks still run on all hosts:

play1.yml:

<pre>
- name: check run_once via var set
  hosts: [ndb01, ndb02]
  tasks:
    - include: play2.yml
      vars:
        run_once: True
</pre>

play2.yml:

<pre> 
- name: check run once
  debug: msg="run_once={{ run_once }}"

- name: run once
  debug: msg="running once"
  run_once: "{{ run_once }}"
</pre>

<pre>
$ ansible-playbook -i ./myhosts play1.yml 

PLAY [check run_once via var set] ********************************************* 

GATHERING FACTS *************************************************************** 
ok: [ndb01]
ok: [ndb02]

TASK: [check run once] ******************************************************** 
ok: [ndb01] => {
    "msg": "run_once=True"
}
ok: [ndb02] => {
    "msg": "run_once=True"
}

TASK: [run once] ************************************************************** 
ok: [ndb01] => {
    "msg": "running once"
}
ok: [ndb02] => {
    "msg": "running once"
}

PLAY RECAP ******************************************************************** 
ndb01                      : ok=3    changed=0    unreachable=0    failed=0   
ndb02                      : ok=3    changed=0    unreachable=0    failed=0   
</pre>

**Comment by dvavili** [comment]
I'm running into this issue as well. Is there an alternative way to handle this scenario?

**Comment by bcoca** [comment]
i actually see the opposite, it always runs once .. but also i don't use a var with the same name, which causes many issues.

`run_once: "{{myrun|defaul(False)}}"`

**Comment by dvavili** [comment]
Need a clarification here.. Does setting run_once as include_var automatically ensure that all the tasks in the included file are only run once or does it need to be mentioned explicitly again per task?

**Comment by bcoca** [comment]
it is not a var, its a keyword/directive, not sure about the interaction with include though.

**Comment by dvavili** [comment]
I'm trying to use it with include with the expectation that all tasks from included file are run only once. But, looks like it is not supported yet. Will be good to have such an option though.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
