### ISSUE TITLE
"Streamlined" include syntax no longer works

### ISSUE THREAD

**Issue by bretmartin** [ansible/ansible#11882]
At http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse I find

> If you are running Ansible 1.4 and later, include syntax is streamlined to match roles, and also allows passing list and dictionary parameters:
> 
> ```
> tasks:
>  - { include: wordpress.yml, wp_user: timmy, ssh_keys: [ 'keys/one.txt', 'keys/two.txt' ] }
> ```

I've been using this syntax but I find that it doesn't work anymore after updating to a recent `devel` revision.

main.yml:

```

---

- include: otherfile.yml
  message: hello
```

otherfile.yml:

```

---

- debug: var=message
```

Results with e16b24c01e:

```
ERROR! 'message' is not a valid attribute for a Task

The error appears to have been in '/Users/bam/dev/h3-ansible/roles/test/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: otherfile.yml
  ^ here
```

Results with tag `v1.9.2-1`:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [test | debug var=message] **********************************************
ok: [localhost] => {
    "var": {
        "message": "hello"
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bretmartin** [comment]
Out of curiosity I also tried this in main.yml (which I think is equivalent to the above contents):

```
---

- { include: otherfile.yml, message: hello }
```

with the same results.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bretmartin** [comment]
@jimi-c Thanks! Should the docs be updated to note the deprecation? The current language makes this sound fully supported

**Comment by bcoca** [comment]
doc source has been updated, it is not immediately reflected on the site though.
