### ISSUE TITLE
Variables not set on successive runs when using vars syntax instead of inline

### ISSUE THREAD

**Issue by bretmartin** [ansible/ansible#11893]
The following works:

main.yml

```

---

- include: otherfile.yml description=hello
- include: otherfile.yml description=goodbye
```

otherfile.yml

```

---

- include: otherfile2.yml message='{{ description }}'
```

otherfile2.yml

```

---

- debug: var=message
```

Results (on 8f106c9a58):

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test : include description=hello] ****************************************
included: otherfile.yml for localhost

TASK [test : include message={{ description }}] ********************************
included: otherfile2.yml for localhost

TASK [test : debug var=message] ************************************************
ok: [localhost] => {
    "changed": false,
    "message": "hello"
}

TASK [test : include description=goodbye] **************************************
included: otherfile.yml for localhost

TASK [test : include message={{ description }}] ********************************
included: otherfile2.yml for localhost

TASK [test : debug var=message] ************************************************
ok: [localhost] => {
    "changed": false,
    "message": "goodbye"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0
```

If I change otherfile.yml to the following:

```

---

- include: otherfile2.yml
  vars:
    message: '{{ description }}'
```

the results change to

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test : include description=hello] ****************************************
included: otherfile.yml for localhost

TASK [test : include] **********************************************************
included: otherfile2.yml for localhost

TASK [test : debug var=message] ************************************************
ok: [localhost] => {
    "changed": false,
    "message": "hello"
}

TASK [test : include description=goodbye] **************************************
included: otherfile.yml for localhost

TASK [test : include] **********************************************************
included: otherfile2.yml for localhost

TASK [test : debug var=message] ************************************************
ok: [localhost] => {
    "changed": false,
    "message": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by bretmartin** [comment]
##### Issue Type:
  - Bug Report

##### Ansible Version:
```
ansible 2.0.0 (devel 8f106c9a58) last updated 2015/08/07 10:56:17 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 8412adc4f9) last updated 2015/08/07 08:53:32 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/06 16:37:41 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/06 14:46:13 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/06 14:46:16 (GMT -400)
  config file =
  configured module search path = /Users/bam/dev/ansible-modules-core:/Users/bam/dev/ansible-modules-extras

```

##### Ansible Configuration:
`ansible.cfg
What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by bretmartin** [comment]
##### Issue Type:
- Bug Report

##### Ansible Version:

```
ansible 2.0.0 (devel 8f106c9a58) last updated 2015/08/07 10:56:17 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 8412adc4f9) last updated 2015/08/07 08:53:32 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/06 16:37:41 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/06 14:46:13 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/06 14:46:16 (GMT -400)
  config file =
  configured module search path = /Users/bam/dev/ansible-modules-core:/Users/bam/dev/ansible-modules-extras

```

##### Ansible Configuration:

`ansible.cfg` is stock.

##### Environment:

N/A but I'm running this on OS X

##### Summary:

##### Steps To Reproduce:

##### Expected Results:

##### Actual Results:

Please see above for all of these -- I think I covered them. Thanks!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bretmartin** [comment]
I"ve confirmed this fix -- thank you, @jimi-c.
