### ISSUE TITLE
regex_replace requires 4 backslashes to escape for key=value argument

### ISSUE THREAD

**Issue by plumzl** [ansible/ansible#11891]
##### Issue Type:
- Bug Report
##### Ansible Version:

 2.0.0
##### Ansible Configuration:

```
[defaults]
inventory = inventory
host_key_checking = False

[ssh_connection]
pipelining = True
```
##### Environment:

“N/A”
##### Summary:

I upgraded ansible from 1.9.1 to 2.0.0 recently, and the `regex_replace` backreference escaping stopped working. It now requires 4 backslashes to escape for `key=value` argument instead of 2, which is different from what's described in the documentation below: 

> If “regex_replace” filter is used with variables inside YAML arguments (as opposed to simpler ‘key=value’ arguments), then you need to escape backreferences (e.g. \1) with 4 backslashes (\\) instead of 2 (\).
##### Steps To Reproduce:

```
test.yml

---
- hosts: localhost
  tasks:
  - debug: msg="{{ "test_name" | regex_replace('^(.*)_name$', '\\\\1') }}"
  - debug: msg="{{ "test_name" | regex_replace('^(.*)_name$', '\\1') }}"
```
##### Expected Results:

I expected the output message to be `"test"` for the second case, which would be consistent with v1.9.1
##### Actual Results:

For ansible v2.0.0:

```
$ ansible-playbook test.yml 

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [debug msg={{ "test_name" | regex_replace('^(.*)_name$', '\\1') }}] ********
ok: [localhost] => {
    "changed": false, 
    "msg": "test"
}

TASK [debug msg={{ "test_name" | regex_replace('^(.*)_name$', '\1') }}] *********
ok: [localhost] => {
    "changed": false, 
    "msg": "\u0001"
}

PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

For ansible v1.9.1:

```
$ ansible-playbook test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="\1"] ******************************************************** 
ok: [localhost] => {
    "msg": "\\1"
}

TASK: [debug msg="test"] ****************************************************** 
ok: [localhost] => {
    "msg": "test"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by abadger** [comment]
Are you running the very latest checkout?  We recently changed something that was checking for octal escapes for similar symptoms.  It could be that this was fixed by that fix or it could be another place where octal escaping is occurring in the code that we might be able to get rid of.

**Comment by abadger** [comment]
Here's the commit that I was thinking of: 73aa5686ccf420fe5c5ce80ffed5c9c37b38589c

**Comment by plumzl** [comment]
@abadger: The checkout I'm running is faf4c3b

**Comment by abadger** [comment]
Okay, I've taken a slightly closer look at this.  this might be a somewhat intentional change although it's not 100% desirable.  Here's what's happening differently:

In ansible there's two ways of specifying parameters to modules: key=value pairs and yaml dictionary syntax.  Taking your test case and showing both of them in a playbook, they'd look like this:

```
---
- hosts: localhost
  tasks:
  #  key=value
  - debug: msg="{{ 'test_name' | regex_replace('^(.*)_name$', '\\\\1') }}"
  - debug: msg="{{ 'test_name' | regex_replace('^(.*)_name$', '\\1') }}"
  # yaml dict syntax
  - debug:
      msg: "{{ 'test_name' | regex_replace('^(.*)_name$', '\\\\1') }}"
  - debug:
      msg: "{{ 'test_name' | regex_replace('^(.*)_name$', '\\1') }}"
```

These two are supposed to be equivalent ways of specifying the same behaviour.  Unfortunately, in ansible v1, that's not the case.  There's many corner cases where the key=value parsing results in different values.  If ou run the above playbook under ansible 1.9.x you'll find that the key=value debug statements are emitting one thing and the dict syntax is emitting another.

v2 fixes the disconnect between the two strategies by making everything into dicts much sooner in the parsing process.  If you run the playbook under v2 you'll find that the output matches and that it also matches with the output for the yaml dict syntax in v1. This is a net win, not only because it makes the two ways of specifying parameters the same (as they were always supposed to be) but also because the key=value cornercases were pretty much always wrong or unintuitive.

This might be the one place where the key=value syntax was superior to what was produced by yaml dict usage.  I'm not sure if we can do anything about this one case without also losing all the other benefits.  If we do keep this we definitely need to document it in the CHANGELOG.

CC: @jimi-c Is there anything we can do about this?  or is it a necessary byproduct of unifying key=value and yaml dict syntax?

**Comment by abadger** [comment]
Fix forthcoming.  based on this: https://gist.github.com/abadger/775cb5239705c900e8d3

I'm just testing whether the same fix has an effect on some other open issues.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
