### ISSUE TITLE
task entry environment: is not auto templated (v2)

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#11912]
Using the role @bennojoy 's mysql role (https://github.com/bennojoy/mysql) I noticed the environment: keyword is not being autotemplated (as is the case pre-2.0 and as documented):

```
TASK [bennojoy.mysql : Install the mysql packages in Debian derivatives] *******
fatal: [hydargos]: FAILED! => {"failed": true, "msg": "ERROR! environment must be a dictionary, received env (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}
```

Updating the role with this patch fixes it, but the original behaviour should be patched in ansible of course:

```
diff --git a/tasks/main.yml b/tasks/main.yml
index cb1716b..d1f55a5 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -10,7 +10,7 @@
 - name: Install the mysql packages in Debian derivatives
   apt: name={{ item }} state=installed update_cache=yes
   with_items: mysql_pkgs
-  environment: env
+  environment: '{{env}}'
   when: ansible_os_family == 'Debian'

 - name: Copy the my.cnf file 
```

Verified using ansible 2.0.0 (devel e32d887609) last updated 2015/08/10 17:56:12 (GMT +200)

**Comment by bcoca** [comment]
I believe this is the correct behavior as autotemplating it would create or obscure errors (as currently happens in with_items).

For example:

```
environment:
   PATH: /usr/bin
```

if it were autotemplated PATH or /usr/bin could be interpreted as variables and now come up with 'undefined' error. Or if we ignore all undefined errors then:

```
vars:
   - myenv :. ...
...
environment: myevn 
```

would go undetected.

**Comment by srgvg** [comment]
So that's a needed change in behaviour with 1.9?
At the least, if this needs to change in v2, it should be documented (current docs state it can be autotemplated) and noted as a non backwards compatible change.

**Comment by bcoca** [comment]
i'll document it, but I believe it should be changed for 2.0

**Comment by jimi-c** [comment]
I'm leaning towards @bcoca on this one - I don't like that we allow bare-variable conversions in so many places, and much prefer explicit variables as you're doing above.

For now, we should probably allow this but show a deprecation warning, and remove it in the future.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
