### ISSUE TITLE
cli/galaxy.py: "scm_archive_role is not defined" error

### ISSUE THREAD

**Issue by palmerabollo** [ansible/ansible#11920]
It seems that `scm_archive_role` is not defined in [lib/ansible/cli/galaxy.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/galaxy.py#L369).

This causes the an error with Ansible 2 when you run ansible-galaxy -r requirements.yml and you have a git repository as source such as:

``` yaml
- src: git+git@enterprisegithub.com/user/role.git
  version: develop
```

The exception I get is:

```
Unexpected Exception: global name 'scm_archive_role' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/Users/guido/ansible/bin/ansible-galaxy", line 79, in <module>
    sys.exit(cli.run())
  File "/Users/guido/ansible/lib/ansible/cli/galaxy.py", line 136, in run
    self.execute()
  File "/Users/guido/ansible/lib/ansible/cli/__init__.py", line 97, in execute
    fn()
  File "/Users/guido/ansible/lib/ansible/cli/galaxy.py", line 369, in execute_install
    tmp_file = scm_archive_role(role.scm, role.src, role.version, role.name)
NameError: global name 'scm_archive_role' is not defined
```

The same command with the same requirements.yml file works with ansible 1.x

I might be related to @bcoca's [changes some weeks ago](https://github.com/ansible/ansible/commit/96bcf50a943e31e1fb254ec2811d96c7f2e6a955#diff-0fb1ac8e85c5f8b604a2bcbbe16a50c8), because I'm not using github.com, but a github enterprise instead.

**Comment by palmerabollo** [comment]
Are you guys open to contributions in this regard?

**Comment by MichaelDrogalis** [comment]
Ran into this. Can't resolve any 3rd party roles automatically without a fix here.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
