### ISSUE TITLE
--become-user root not working from Makefile (file not writable)

### ISSUE THREAD

**Issue by klj613** [ansible/ansible#11944]
Issue type: Bug Report

Ansible Version:

```
ansible 1.9.2 (stable-1.9 773a3becf5) last updated 2015/08/06 12:19:59 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 95e1cf2235) last updated 2015/08/06 12:20:05 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 015247a016) last updated 2015/08/06 12:20:05 (GMT +100)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/08/06 12:20:05 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/08/06 12:20:05 (GMT +100)
  configured module search path = None
```

Ansible Configuration: Default/Minimal

Environment: Ubuntu 14.04

Summary:

I am experiencing an issue with --become-user whilst the execution is done from a Makefile.

The two lineinfile ansible commands work whilst manually executing from a terminal. When using a Makefile the ansible command using --become-user doesn't work. However The ansible command using become user and the shell module works.

```
ansible all -i '127.0.0.1,' --connection local --sudo --ask-sudo-pass --module-name lineinfile --args "dest=/etc/hosts line='192.168.34.2 foobar' regexp='^192.168.34.2'"
ansible all -i '127.0.0.1,' --connection local --become-user root --ask-become-pass --module-name lineinfile --args "dest=/etc/hosts line='192.168.34.2 foobar' regexp='^192.168.34.2'"
ansible all -i '127.0.0.1,' --connection local --become-user root --ask-become-pass --module-name shell --args "echo hi"
```

Steps to reproduce:
1. Create a makefile using the example
2. Make ansiblerunner (make sure your terminal doesnt have sudo rights. e.g. if you've sudo'ed recently on your terminal this will work).

Example makefile:

```
.PHONY: ansiblerunner
ansiblerunner:
@ansible all -i '127.0.0.1,' --connection local --become-user root --ask-become-pass --module-name lineinfile --args "dest=/etc/hosts line='192.168.34.2 foobar' regexp='^192.168.34.2'"
```

Expected Result: The file is updated

Actual Result:

```
SUDO password: 
127.0.0.1 | FAILED >> {
    "failed": true, 
    "msg": "The destination directory (/etc) is not writable by the current user."
}
```

**Comment by bcoca** [comment]
you don't seem to add --become to those lines, also --become-user root should not be needed as root is normally the default.

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- You are not calling --become which actually activates privilege escalation (equivalent of the old --sudo) 

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
