### ISSUE TITLE
Different behaviour with include and include_vars

### ISSUE THREAD

**Issue by pujan14** [ansible/ansible#11952]
Ansible version 1.9.2
- include_vars: "{{ filename }}"

works as expected but 
- include: "{{ filename }}"

Gives error "ERROR: file could not read: /tasks/{{ filename }}"

filename is a variable which is set to /tasks/test.yml

**Comment by halberom** [comment]
related to https://github.com/ansible/ansible/issues/5424

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by pujan14** [comment]
##### Issue Type:
- Bug Report
- Feature Idea

##### Ansible Version:

ansible 1.9.2

##### Ansible Configuration:

N/A

##### Environment:

N/A

##### Summary:

There are cases when specific tasks needs to be applied to single hosts (special user requirements) for that it would be easier to create - include: {{ inventory_hostname }}.yml then create include for 20 different hosts with when condition.

PS: This works with include_vars but not with include 

mailing list link: https://groups.google.com/forum/#!topic/ansible-project/xK371Xwom58

##### Steps To Reproduce:

```
---
- include: {{ inventory_hostname }}.yml
```

##### Expected Results:

Includes hostname.yml as task

##### Actual Results:

```
ERROR: Syntax Error while loading YAML script, /home/ps/ansible-local/roles/custom/tasks/main.yml
Note: The error may actually appear before this position: line 5, column 12

  ---
  - include: {{ inventory_hostname }}.yml
           ^
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by bcoca** [comment]
There are really 2 versions of include: , one for tasks and another for plays, the one for tasks DOES work this way in 2.0 (current devel) the one for plays cannot work this way as there are no hosts selected yet.

**Comment by pujan14** [comment]
Ok so then I will have to wait till 2.0 comes out.
