### ISSUE TITLE
with_sequenece is not skipped when run with false conditionals

### ISSUE THREAD

**Issue by davidvasandani** [ansible/ansible#11961]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.0.1
  configured module search path = None
##### Environment:

CentOS release 6.6 (Final)
##### Summary:

When running a playbook and setting a `when:` conditional for a role if he conditional isn't met I expect all task in the role to be skipped. When a role includes a `with_sequence:` that tasks is run regardless.
##### Steps To Reproduce:

The `helios_aws_multi` role should be skipped if env doesn't equal awsstage or awsprod.

```
  roles:
    - { role: helios_aws_single, when: env == 'awsdev' or env == 'awsqa' }
    - { role: helios_aws_multi, when: env == 'awsstage' or env == 'awsprod' }
```

The tasks before and after with_sequence are skipped but the with_sequence task is run. Commenting out the tasks causes the task and all following tasks to skip until the next with_sequenece task.

```
# - name: create identifier sequence for tagging
#   no_log: true
#   debug: msg="{{ item }}"
#   with_sequence: start=0 count="{{ helios_web1b.count }}" format=%02d
#   register: sequence
```
##### Expected Results:

The task should be skipped.
##### Actual Results:

```
TASK: [helios_aws_single | set hostnames] *************************************
<172.20.16.164> REMOTE_MODULE hostname name="awsdev-helios-node00"
ok: [localhost -> 172.20.16.164]

TASK: [helios_aws_multi | helios web1b servers] *******************************
skipping: [localhost]

TASK: [helios_aws_multi | create identifier sequence for tagging] *************
fatal: [localhost] => unknown error parsing with_sequence arguments: u'start=0 count="{{ helios_web1b.count }}" format=%02d'

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
- The when clause gets evaluated AFTER with_ as you can make each iteration condtiional (when: item = 'whati want'). So this is expected behavior. I suggest adding a |default filter to avoid errors in your with_ clauses.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
