### ISSUE TITLE
Error when using <bound method CallbackModule.v2_runner_on_failed of <ansible.plugins.callback.default.CallbackModule object at 0x7f894126df90>>: 'NoneType' object has no attribute 'loop'

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#12014]
I get the following error when testing my playbooks with the latest devel version:
`Error when using <bound method CallbackModule.v2_runner_on_failed of <ansible.plugins.callback.default.CallbackModule object at 0x7f894126df90>>: 'NoneType' object has no attribute 'loop'`
The issue was added in commit e7b2308b6 .

It can be reproduced by cloning https://github.com/sebi-hgdata/ansible_test.git and running "ansible-playbook -v build_admin_ui.yml -i inventories/local/hosts --extra-vars "admin_ui_version=1234""

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by sebi-hgdata** [comment]
@jimi-c  can you have a look?

**Comment by jimi-c** [comment]
@sebi-hgdata I'm not seeing this against the current devel. Can you update and test again?

**Comment by halberom** [comment]
I'm currently seeing the following which seems related

```
[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_skipped of
<ansible.plugins.callback.default.CallbackModule object at 0x10f7fe650>>: global name 'C' is not defined
```

Created a new bug, as this one was logged 9 days ago, diff error too.

**Comment by jimi-c** [comment]
@halberom yours was same place, different issue, fixed for yours now.

**Comment by sebi-hgdata** [comment]
It's fixed.

Thanks
