### ISSUE TITLE
Blank/null hosts pattern defaults to "all"

### ISSUE THREAD

**Issue by tgerla** [ansible/ansible#12011]
Issue Type:

Bug Report
Ansible Version: 1.9.2 and ansible 2.0.0 (devel ab355218a0)

Environment:

N/A

Summary:

A play with blank/empty/null "hosts" value will default to run on all hosts.

Steps To Reproduce:

Have a playbook like this:

```

---
- hosts: ""
  tasks:

  - name: debug
    debug: msg=hello
```

Expected Results:

I would expect to see "skipping: no hosts matched"

Actual Results:

The playbook runs on all hosts in inventory:

```
PLAY [] ***********************************************************************

GATHERING FACTS ***************************************************************
ok: [two]
ok: [one]

TASK: [debug] *****************************************************************
ok: [two] => {
    "msg": "hello"
}
ok: [one] => {
    "msg": "hello"
}

PLAY RECAP ********************************************************************
one                        : ok=2    changed=0    unreachable=0    failed=0
two                        : ok=2    changed=0    unreachable=0    failed=0
```

This could be especially problematic if you parameterize your hosts line and forget to pass in extra vars, or pass in the wrong value.

PS: the "pattern" setting in ansible.cfg seems like it should change this behavior, but doesn't.

**Comment by bobobox** [comment]
Thank you for writing this up. I hope this is treated as a high priority issue, as it has the potential for wreaking serious havoc.

**Comment by caseyclark** [comment]
+1 on this, could potentially cause some serious issues.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
