### ISSUE TITLE
vars name having '-' are not handled as expected

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#12022]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.2
##### Summary:

vars names having a '-' are not handled correctly and ansible does not complain.
##### Steps To Reproduce:

```
- hosts: localhost
  gather_facts: no
  vars:
    test-foo:
      things:
        - one
        - two

  tasks:
    - debug: msg={{ item }}
      with_items: test-foo.things
```
##### Expected Results:

An error message that a variable name contains a unsupported character '-'. 

or

```
PLAY [localhost] ************************************************************** 

TASK: [debug msg={{ item }}] ************************************************** 
ok: [localhost] => (item=one) => {
    "item": "one", 
    "msg": "one"
}
ok: [localhost] => (item=two) => {
    "item": "two", 
    "msg": "two"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0  
```
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

TASK: [debug msg={{ item }}] ************************************************** 
ok: [localhost] => (item=test-foo.things) => {
    "item": "test-foo.things", 
    "msg": "test-foo.things"
}
```

**Comment by resmo** [comment]
ok, the docs are clear about what valid variable names http://docs.ansible.com/ansible/playbooks_variables.html#what-makes-a-valid-variable-name but I still think it would be necessary ansible does complain it.

**Comment by srgvg** [comment]
How could ansible now you meant a (bad syntaxed) variable name instead of a substraction?
also, fyi #3907

**Comment by amenonsen** [comment]
@srvg the place to complain would be after the `vars:` section is defined.

**Comment by srgvg** [comment]
good point @amenonsen

**Comment by jimi-c** [comment]
We had previously done this for `set_fact`, so generalizing it to also work for `vars:`:

<pre>
# ansible-playbook -vv 12022.yml 
Using /etc/ansible/ansible.cfg as config file
ERROR! Invalid variable name in vars specified for Play: test-foo is not a valid variable name
The error appears to have been in '/root/testing/12022.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  vars:
    test-foo:
    ^ here
</pre>

As noted in the commit, we should probably also add this to VariableManager to check vars loaded from files (inventory/vars_files/roles), but this was a quick fix.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
