### ISSUE TITLE
Role main.yml stops after first - include:

### ISSUE THREAD

**Issue by fvant** [ansible/ansible#12039]
roles/Myrole/tasks has 4 files:

```
a.yml
b.yml
c.yml
main.yml
```

and main.yml  - includes a.yml  etc

but only the first include gets executed. No error/warning. When i swap b.yml with a.yml , still only the first one get run.
I can add task above the first include and it gets executed just fine.

Anything (task or include) after the first - include: does nothing.

**Comment by srgvg** [comment]
`and main.yml - includes a.yml etc`

Can you show exactly how you write that?

That said, this is a user question better suited for the user mailing list or on the irc channel.

**Comment by fvant** [comment]
##### Ansible Version:

git status says:

```
On branch devel
Your branch is up-to-date with 'origin/devel'.
commit f150fe2c232a9eb3a3863ed30690397c922de6e1
```

##### Environment:

NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"

##### Summary:

Only the first include is handled. This is in main.yml in a Role.

##### Remark

When we broke up the main.yml in seperate files around 17 juli it worked fine.

```
---

- name: Apply security patches
  command: yum update --security -y
  sudo: yes
  ignore_errors: true

- include: docker.yml

- include: monitoring.yml # setup monitoring and rotatging of logs

- include: debugging.yml # setup debugging tools
```

**Comment by cjstetson** [comment]
I have run into same situation - init runs, deploy doesn't, plus subsequent roles that should execute do not. Code example below

---
- name: init
  include: init.yml
  when: thorough | bool 
- name: deploy
  include: deploy.yml

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by pacahon** [comment]
Have the same bug. In main.yml:

```
- include: apt.yml
- include: pip.yml
- include: stuff.yml
```

In apt.yml (it's just example. I have much more tasks in `apt.yml` and problem not strictly related to `apt_repository` module

```
---
- name: add postgres repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

# - name: add PPAs for latest and greatest software
#   apt_repository:
#     repo: "{{ item }}"
#     update_cache: yes
#   with_items:
#     - 'ppa:nginx/stable'
#     - 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
```

If I uncomment apt_repository module `pip.yml` file will be ignored without any debug info

```
ok: [] => (item=ppa:nginx/stable) => {"changed": false, "item": "ppa:nginx/stable", "repo": "ppa:nginx/stable", "state": "present"}
ok: [] => (item=deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main) => {"changed": false, "item": "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main", "repo": "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main", "state": "present"}

TASK [app : include] ***********************************************************
included: stuff.yml for 
```

Git info

```
$ git branch -v
* devel    635fa07 Several var fixes
```

```
$ git submodule
 4721d6d8b5e251054b01ddaf8bb852e8204c2c9f lib/ansible/modules/core (heads/devel-6-g4721d6d)
 785cd24a02afd23fc98d8ae7713db3327e67af38 lib/ansible/modules/extras (heads/devel)
 f8d8af17cdc72500af8319c96004b86ac702a0a4 v1/ansible/modules/core (remotes/origin/v1_modules)
 495ad450e53feb1cd26218dc68056cc34d1ea9ff v1/ansible/modules/extras (495ad45)
```

**Comment by bcoca** [comment]
probably related to #11995 and #11997

**Comment by jimi-c** [comment]
I believe there may be some confusion here. The original comment from @fvant mentions that the includes occur from a role, however no YAML is provided to show what each file does beyond mentioning that the main.yml includes a.yml - are b.yml and c.yml included in a chain-like manner? Could you please provide a more complete set of files including their contents to help reproduce this issue?

The comment from @cjstetson would appear to be the same as @fvant's, however more details on this setup to help reproduce the issue would also be appreciated.

Second, the example given by @pacahon in https://github.com/ansible/ansible/issues/12039#issuecomment-133508598 appears to show Playbook-level includes rather than Task-level includes, which are very different things. Playbook-level includes still operate essentially as a preprocessor statement, reading in and expanding the Playbooks inline before any execution starts. In 2.0 (devel), Task-level includes are more dynamic and are executed in the course of tasks just as any other task. In 1.9.x and before, task-level includes were also equivalent to a preprocessor statement, so the behavior was roughly equivalent.

**Comment by fvant** [comment]
@jimi-c, I did provide the full main.yml used in the role in comment #3
The contents of docker.yml nor monitoring.yml did not matter.  

But to remove any confusion, I have created a minimal test case that always skips the second include https://github.com/fvant/ansible-role-debug

In my actual project, only the first include is run and the role then stops, in this test case the behaviour is different but also wrong.

**Comment by pacahon** [comment]
@jimi-c My example is provided for includes occurred from a role too. I mean my `main.yml` located in `roles/my_role/tasks/main.yml`

**Comment by cjstetson** [comment]
Apologies for lack of details -

here is version info:
ansible --version
ansible 2.0.0 (devel 144da7e7d1) last updated 2015/08/21 11:57:24 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 4721d6d8b5) last updated 2015/08/25 14:30:51 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 785cd24a02) last updated 2015/08/25 14:31:02 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/20 14:57:48 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/20 14:57:53 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None

Playbook Snippet:

# Configure and deploy the uservice-ip servers.
- hosts: uservice-ip:uservice-ip-a:uservice-ip-b
  roles:
  - { role: uservice-ip, tags: [ 'uservice-ip', 'check-app-dir', 'jwt', 'prana', 'ruby' ] }
  - { role: check-app-dir, tags: "check-app-dir" }
  - { role: jwt, tags: "jwt" }
  - { role: prana, tags: "prana"}
  - { role: ruby, tags: "ruby"}

## roles/prana/tasks/main.yml
- name: init
  include: init.yml
  when: thorough | bool 
- name: deploy
  include: deploy.yml

Note: thorough set to true

Execution:
ansible-playbook -i prodhosts site.yml -l uservice-ip-b  -e "env=prod thorough=true" --ask-vault-pass

results:
   role: uservice-ip - Executes
   role: check-app-dir -Executes
   role: jwt  - Executes
   role: prana - Executes up to - 
          name: init
          include: init.yml
          when: thorough | bool 
Playbook Ends -  role: ruby not executed or evaluated.

Pointing back to  tags/v1.9.2-1 everything executes as expected.

Please let me know if I can provide any other details

**Comment by jimi-c** [comment]
@fvant ahh I see, your example just mentioned a/b/c so I missed that your follow-up had your actual file names in it. I'm working on a patch which in my testing corrects that (along with #11995 and the issue reported by #12039).

**Comment by jimi-c** [comment]
@cjstetson ok, that does look like the same issue reported by @fvant, so my patch should correct your problem as well.

If either of you'd like to give it a test, here is the gist: https://gist.github.com/jimi-c/8fda01b7d92168fbfe62

This is still a rough copy without a ton of testing, but in my limited testing it corrects the issue you're seeing (and several others, as mentioned above, mainly related to when the includes are chained from one to another).

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
