### ISSUE TITLE
Templated variables do not work when accessed through hostvars

### ISSUE THREAD

**Issue by ngaya-ll** [ansible/ansible#12045]
Variables defined in group_vars/host_vars with templates that reference other variables do not return consistent results when accessed through `hostvars`.

**Expected behavior:** `{{ hostvars['hostname']['variable'] }}` evaluated on any host yields the same value as `{{ variable }}` evaluated on host `hostname`.

**Actual behavior:** `{{ hostvars['hostname']['variable'] }}` may yield different results when evaluated on different hosts.

**Example:**
Consider the following ansible project:

```
|--- inventory.ini
|--- playbook.yml
\--- host_vars/
   \--- my_host
```

_inventory.ini_

```
my_host ansible_connection=local
other_host ansible_connection=local
```

_hostvars/my_host_

```

---
my_var: "{{ inventory_hostname }}"
```

_playbook.yml_

```

---
- hosts: all
  tasks:
    - debug: var="hostvars['my_host']['my_var']"
    - debug: var="hostvars['my_host']['inventory_hostname']"
    - assert:
        that: hostvars['my_host']['my_var'] == hostvars['my_host']['inventory_hostname']
```

This playbook should run successfully.  In Ansible 1.9.2, this playbook fails at the `assert` task on `other_host`.  Notice how the first debug statement produces a different result on each host.

```
$ ansible-playbook -i inventory.ini playbook.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [my_host]
ok: [other_host]

TASK: [debug var="hostvars['my_host']['my_var']"] ***************************** 
ok: [my_host] => {
    "var": {
        "hostvars['my_host']['my_var']": "my_host"
    }
}
ok: [other_host] => {
    "var": {
        "hostvars['my_host']['my_var']": "other_host"
    }
}

TASK: [debug var="hostvars['my_host']['inventory_hostname']"] ***************** 
ok: [other_host] => {
    "var": {
        "hostvars['my_host']['inventory_hostname']": "my_host"
    }
}
ok: [my_host] => {
    "var": {
        "hostvars['my_host']['inventory_hostname']": "my_host"
    }
}

TASK: [assert ] *************************************************************** 
ok: [my_host]
failed: [other_host] => {"assertion": "hostvars['my_host']['my_var'] == hostvars['my_host']['inventory_hostname']", "evaluated_to": false, "failed": true}

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/nicholas.gaya/playbook.retry

my_host                    : ok=4    changed=0    unreachable=0    failed=0   
other_host                 : ok=3    changed=0    unreachable=0    failed=1   
```

Related: https://github.com/ansible/ansible/issues/7844

**Comment by bcoca** [comment]
this seems to work fine in current development

**Comment by ngaya-ll** [comment]
@bcoca Yep, worked for me too from the devel branch.  Any idea when that will be released?

**Comment by bcoca** [comment]
beta should be coming out soon, closing this ticket as it is fixed in devel

**Comment by bcoca** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
