### ISSUE TITLE
ec2_security You have specified two resources that belong to different networks.

### ISSUE THREAD

**Issue by rainmanh** [ansible/ansible#12052]
Hi

Executing a piece of code as the follow:

```
ec2_security_billing_ariaproxy_lb:
    - sg_name: billing-lb
      sg_description: Ariaproxy LB for billing service in VPC Staging
      vpc_id: "vpc-xxxxxxxx"
      region_code: "{{ region_code }}"
      sg_rules:
      - proto: tcp
        from_port: 10
        to_port: 10
        group_name: billing-lb
ec2_security_billing_ariaproxy:
    - sg_name: billing-ariaproxy
      sg_description: Ariaproxy for billing service in VPC Staging
      vpc_id: "vpc-xxxxxxxx"
      region_code: "{{ region_code }}"
      sg_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_name: billing-lb

```

I get an output as the following if I got the same "sg_name" anywhere else.
This happens in a condition where VPC IDs are DIFFERENT, so in complete different VPCs should clash does not happen at all.

```
TASK: [aws_region | Region:aws_region Environment:production Name:billing-lb] *** 
failed: [127.0.0.1 -> 127.0.0.1] => (item={'vpc_id': 'vpc-xxxxxxxx', 'sg_rules': [{'to_port': 10, 'from_port': 10, 'proto': 'tcp', 'group_name': 'billing-lb'}], 'region_code': u'us-east-1', 'sg_name': 'billing-lb', 'sg_description': 'Ariaproxy LB for billing service in VPC Staging'}) => {"failed": true, "item": {"region_code": "us-east-1", "sg_description": "Ariaproxy LB for billing service in VPC Staging", "sg_name": "billing-lb", "sg_rules": [{"from_port": 10, "group_name": "billing-lb", "proto": "tcp", "to_port": 10}], "vpc_id": "vpc-xxxxxxxx"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1440199665.67-136090692584177/ec2_group", line 1899, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1440199665.67-136090692584177/ec2_group", line 272, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3192, in authorize_security_group
    params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1223, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>You have specified two resources that belong to different networks.</Message></Error></Errors><RequestID>8970b996-6ebe-4a72-9a7e-4096ff903cae</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

Using the AWS Console you can create he same group_name for different VPCs but it seems c2_security is finding problems there (something I can understand for classic but VPC is a completely different scenario)

Would be possible to do anything about this?

thanks!!

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
