### ISSUE TITLE
Ansible shell command does not display output when output contains ANSI colors (fix not released)

### ISSUE THREAD

**Issue by joel-airspring** [ansible/ansible#12068]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

N/A
##### Environment:

N/A.

But for thoroughness:

local host: OSX 10.8.5
remote/target host: CentOS 6.6
##### Summary:

An issue was fixed over a year ago but has not been released yet.  Perhaps this is intentional, but I thought I'd ask.  This issue has entered a few times:

Here:  #7522
Here:  #7486
Here:  #7487

In the last one (7487), a fix was merged into a branch called "ansible:devel" on April 1st, 2014, but more than a year later, it hasn't been released.

I have tested the fix locally, and it works as expected.  Would it be possible to release the fix?
##### Steps To Reproduce:

See above listed issues.
##### Expected Results:

See above listed issues.
##### Actual Results:

See above listed issues.

**Comment by jimi-c** [comment]
Hi @joel-airspring, I'm not seeing this issue in the current devel branch:

<pre>
# cat 12068.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - shell: 'echo -e "\033[31mHello\e[0m World"'
TASK [command] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": "echo -e \"\\033[31mHello\\e[0m World\"", "delta": "0:00:00.003096", "end": "2015-08-28 14:06:47.546009", "rc": 0, "start": "2015-08-28 14:06:47.542913", "stderr": "", "stdout": "\u001b[31mHello\u001b[0m World", "stdout_lines": ["\u001b[31mHello\u001b[0m World"], "warnings": []}
</pre>

As you can see, the stdout and stdout_lines fields are populated with the output from the echo. I do see this on the stable-1.9 branch, however it is our policy to close issues once they have been resolved in the devel branch.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
