### ISSUE TITLE
yum module fails with_items and an incorrect package name with error "is already installed"

### ISSUE THREAD

**Issue by skyler** [ansible/ansible#12070]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel 16f3f8e244) last updated 2015/08/24 14:22:00 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 85ddb1b902) last updated 2015/08/24 12:23:54 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 7a0bfd91bb) last updated 2015/08/24 12:23:57 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/24 12:24:00 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/24 12:24:02 (GMT -400)
  config file =
  configured module search path = None
```
##### Ansible Configuration:

No changes to default install. I'm running from the git checkout, without any customizations (e.g. settings.cfg).
##### Environment:

Provisioning `CentOS Linux release 7.1.1503 (Core)` 64 bit from Mac OS `10.10.5 (14F27)` using `vagrant provision`, Vagrant version `1.7.2`.
##### Summary:

I'm installing several packages in yum using `with_items` and `state=present`. In my example, `pip` is a bad package name (it doesn't exist; the actual package name is `python-pip`). The `yum` module fails with the error that the package providing "$whatever is already installed" for every package named in `with_items`.
##### Steps To Reproduce:

Here's my playbook (`core/tasks/main.yml` called from `ansible/playbooks.yml`).

```

---
- name: install EPEL
  yum: name=epel-release state=present

- name: install essential packages
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - ntpdate
    - gcc
    - gcc-c++
    - make
    - vim-enhanced
    - git
    - curl
    - wget
    - pip
    - python-setuptools
```

The part of my `Vagrantfile` that runs this playbook.

```
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.sudo = true
    end
```
##### Expected Results:

Installation to fail with an error message like "package `pip` does not exist."
##### Actual Results:

```
vagrant provision
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/skyler/tandem-vagrantbox/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/skyler/tandem-vagrantbox/.vagrant/provisioners/ansible/inventory --sudo ansible/playbook.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [core : install EPEL] *****************************************************
ok: [default]

TASK [core : install essential packages] ***************************************
failed: [default] => (item=ntp,ntpdate,gcc,gcc-c++,make,vim-enhanced,git,curl,wget,pip,python-setuptools) => {"changed": false, "failed": true, "item": "ntp,ntpdate,gcc,gcc-c++,make,vim-enhanced,git,curl,wget,pip,python-setuptools", "msg": "No Package matching 'pip' found available, installed or updated", "rc": 0, "results": ["ntp-4.2.6p5-19.el7.centos.1.x86_64 providing ntp is already installed", "ntpdate-4.2.6p5-19.el7.centos.1.x86_64 providing ntpdate is already installed", "gcc-4.8.3-9.el7.x86_64 providing gcc is already installed", "gcc-c++-4.8.3-9.el7.x86_64 providing gcc-c++ is already installed", "make-1:3.82-21.el7.x86_64 providing make is already installed", "vim-enhanced-2:7.4.160-1.el7.x86_64 providing vim-enhanced is already installed", "git-1.8.3.1-4.el7.x86_64 providing git is already installed", "curl-7.29.0-19.el7.x86_64 providing curl is already installed", "wget-1.14-10.el7_0.1.x86_64 providing wget is already installed"]}

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by skyler** [comment]
Okay, it turns out `pip` is not the correct package name. The correct name is `python-pip`. When I correct the package name in the `with_items` list, the `yum` module works as expected.

It appears that `with_items` cannot differentiate between packages already installed and bad package names.

I updated this issue to reflect this.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
