### ISSUE TITLE
Delegate_to an ip adress not working :

### ISSUE THREAD

**Issue by jfpucheu** [ansible/ansible#12079]
Playbook: 
<code> - lineinfile: dest=/etc/hosts regexp='._{{ inventory_hostname }}._' insertafter="# {{ansible_plateform}} PLATEFORM" line='{{ip}} \t {{inventory_hostname}} \t {{inventory_hostname}}.novalocal' state=present
    delegate_to: 10.222.123.321
    sudo: yes
</code>

Result:

<code> ssh -C -tt -vvv -o ControlPersist=15m -F /Users/Jeff/.ssh/config -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=toto -o ConnectTimeout=10 audvndb01 (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1440494310.89-46378754806660" && echo "$HOME/.ansible/tmp/ansible-tmp-1440494310.89-46378754806660")
</code>

Ansible try to execute the command on the host : audvndb01 instead of 10.222.123.321

**Comment by jimi-c** [comment]
@jfpucheu what version of Ansible are you running in the above example?

**Comment by jfpucheu** [comment]
ansible --version
ansible 2.0.0 (devel efa005c228) last updated 2015/08/25 11:03:26 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 85ddb1b902) last updated 2015/08/24 14:12:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7a0bfd91bb) last updated 2015/08/24 14:12:34 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 09:50:54 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 09:50:57 (GMT +200)
  config file = /Users/Jeff/.ansible.cfg
  configured module search path = None

**Comment by azimut** [comment]
+1
I had to use the hostname that ansible knows about to make it work.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
