### ISSUE TITLE
v2 fails to pick up plugins from ./action_plugins

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12099]
Steps to reproduce:
- Create a module `library/foo.py`
- Create a plugin `action_plugins/foo.py`
- Create a playbook that runs task `foo`
- Run the playbook

Expected behavior:
- Ansible uses the ActionModule defined in `action_plugins/foo.py` (and this is, in fact, what happens with Ansible 1.9.2)

Actual behavior:
- Ansible v2 actually imports `action_plugins/foo.py`(any print statements at the top level are executed), but then
- Ansible v2 uses `ansible.plugins.action.normal.ActionModule` to run `library/foo.py`

**Comment by mgedmin** [comment]
Experiments with printing `self._paths` in `PluginLoader.find_plugin()` show different pathnames at different call sites:

```
['/home/mg/src/deployments/provisioning/action_plugins',
 '/home/mg/.ansible/plugins/action_plugins',
 '/usr/share/ansible_plugins/action_plugins',
 '/home/mg/src/ansible/lib/ansible/plugins/action']
```

when the loader is called from `ansible.plugins.strategies.linear.StrategyModule.run`, but

```
['/home/mg/.ansible/plugins/action_plugins',
 '/usr/share/ansible_plugins/action_plugins',
 '/home/mg/src/ansible/lib/ansible/plugins/action']
```

when the loader is called from `ansible.executor.task_executor.TaskExecutor._get_action_handler`.

**Comment by mgedmin** [comment]
A workaround: add

```
[defaults]
action_plugins = ./action_plugins/
```

to `vagrant.cfg`.

**Comment by jimi-c** [comment]
@mgedmin in your sample, are you using the ActionBase class for the base class of your action plugin?

**Comment by jimi-c** [comment]
Nevermind, this is due to the action_loader not being shared across the forked processes via the SharedPluginLoaderObj class. I'll have this fixed shortly.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
