### ISSUE TITLE
Should not scan for ssh host key for git:// URLs

### ISSUE THREAD

**Issue by mook-as** [ansible/ansible#12096]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2 (also, `devel` source by inspection)
##### Ansible Configuration:

Being run under vagrant.  But nothing here should affect the code involved.
##### Environment:

N/A (Vagrant; Linux (Ubuntu 12.04/14.04) x86_64)
##### Summary:

Please see https://github.com/ansible/ansible/blob/9f9891df2ca87d6adf9b6267846432abd7d3b3f3/lib/ansible/module_utils/known_hosts.py#L72

If given an unencrypted git url, `git://host/repo.git`, ansible should not scan for the ssh host key; the host might not have a ssh server running at all.  It makes sense to scan in case of `ssh://user@host/repo.git` and `git+ssh://user@host/repo.git` though; in both of those cases, the first part of the compound condition matching `ssh` will be hit.

Note that the `git:` protocol is the unencrypted thing that runs on port 9418, which is probably not a good idea to be running on the internet.
##### Steps To Reproduce:

Somewhere in the playbook:

``` yml
- git dest=/some_dir repo=git://host/repo.git
```

Make sure `host` does not in fact run a sshd.
##### Expected Results:

Ansible does not attempt to fetch the ssh host key.
##### Actual Results:

```
failed: [default] => {"failed": true}
msg: failed to add host hostkey:  ...
```
##### Workaround:

Add `ssh_opts="-o StrictHostKeyChecking=no"` to the config.  This gets tricky if git submodules are involved and you do need the hostkey for some repositories but `git://` urls for others.

Thanks for reading :)

**Comment by amenonsen** [comment]
There's a six-month old PR #10204 that fixes this problem for devel. Maybe you could review/test it?

**Comment by abadger** [comment]
@Mook-as Thanks for reporting this!  @amenonsen thanks for pointing out that PR!

Merged the PR here: https://github.com/ansible/ansible/pull/10204

Should fix this issue.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
