### ISSUE TITLE
Add -q/--quiet option for running Ansible from Cron

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1210]
Would this be accepted ?

**Comment by jpmens** [comment]
That certainly would be appreciated here. :)

On the other hand, running `ansible-playbook xx.yml > /dev/null` already works ...

**Comment by dagwieers** [comment]
Not really, fatal errors go to stdout as well. So cron will not send errors out when failed.

**Comment by jpmens** [comment]
Fatal errors to stdout and not stderr is a bug.

**Comment by dagwieers** [comment]
Right, but the general issue here is that if you have a fatal error, you also want the context which at that point has been sent to stdout (already). In the below case, you want to send (at least) the play, the task and the failure to stderr, which is harder to do if you are just piping stdout to /dev/null. Ansible has no knowledge about the fact you are doing that. If you would have -q/--quiet, Ansible could modify its error-output to provide the context because we know it has not been printed before.

Just to indicate that only sending failures to stderr is not going to cut it IMO.

```
PLAY [This will fail on task 2] ********************* 

TASK: [command pwd] ********************* 
changed: [x220] => {"changed": true, "cmd": ["pwd"], "delta": "0:00:00.002359", "end": "2012-10-03 12:28:13.419084", "rc": 0, "start": "2012-10-03 12:28:13.416725", "stderr": "", "stdout": "/root"}
changed: [localhost] => {"changed": true, "cmd": ["pwd"], "delta": "0:00:00.002065", "end": "2012-10-03 12:28:13.418790", "rc": 0, "start": "2012-10-03 12:28:13.416725", "stderr": "", "stdout": "/root"}

TASK: [fail msg="Told you so"] ********************* 
skipping: [x220]
failed: [localhost] => {"failed": true, "msg": "Told you so", "rc": 1}
```

**Comment by dagwieers** [comment]
In fact, now that I think of it, when doing -q/--quiet we probably also want to see the statistics at the end _only if there were errors_ so you can at least see what succeeded despite the failures.

**Comment by jpmens** [comment]
Yes, both things sound sensible to me.

**Comment by mpdehaan** [comment]
Here's what I'll accept.   They must all go together when submitted to
ensure completeness.

(A) Callback errors go to stderr.   (you won't get the task headers in cron
reports but ah well).

(B) We _ALWAYS_ output the summary, but depending on whether there are
failures, it goes to stdout or stderr as appropriate.

(C) There shall not be a quiet yet.  We can talk about this later, but I
want to control option sprawl and it seems like the wrong solution to this
to me.  (B) is better, because if you were parsing things, you're in
terrible shape anyway.

(D) The return code of /usr/bin/ansible/playbook will be 2 (or 3 or or some
unused error code) if there were any failures, otherwise 0.   We need a
different code to distinguish from a syntax error.

And sometime in 0.9 or so (but not now) we'll consider a JSON output mode
or something as well for those that want structured data.

--Michael

**Comment by mpdehaan** [comment]
Since this is an RFE, I'm throwing this in the 0.9 bucket.   I'll accept it earlier if it arrives this week.   We're shooting for a mid October release so codefreeze is a week before that and will be announced closer to the date.

**Comment by mpdehaan** [comment]
Clearly this is looking like November.  Anyway, obviously not a priority issue.  If someone wants to submit a patch, great, if not, moving this to 1.0. 

I will close this if there is no associated pull request in 1.0 given I haven't seen anything yet, so this is up to someone else to make it happen.

**Comment by weirdan** [comment]
There's a trick for crontab: run ansible-playbook as follows:

```
*/15 * * * *    if ! out=`ansible-playbook yourplaybook.yaml`; then echo $out; fi
```

This way you get complete output, but only if ansible exited with a non-zero status.

**Comment by cjw296** [comment]
A little surprised this never happened... Thanks for the workaround @weirdan !

**Comment by jmdh** [comment]
an arguably nicer cron trick is to use `chronic` from [moreutils](https://joeyh.name/code/moreutils/).
