### ISSUE TITLE
vars_plugins not gathered when inventory is string

### ISSUE THREAD

**Issue by jpetrelliswork** [ansible/ansible#12104]
When passing inventory as a hostlist (form: ansible-playbook foo.yml -i 'host1,'), vars_plugins are not assigned correctly and do not get executed.  This worked for me.  It moves the self._vars_pluigins assignment out of the if, elif of parse_inventory. 

```
diff --git a/lib/ansible/inventory/__init__.py b/lib/ansible/inventory/__init__.py
index d25409b..00002aa 100644
--- a/lib/ansible/inventory/__init__.py
+++ b/lib/ansible/inventory/__init__.py
@@ -124,7 +124,7 @@ class Inventory(object):
                 # should never happen, but JIC
                 raise AnsibleError("Unable to parse %s as an inventory source" % host_list)

-            self._vars_plugins = [ x for x in vars_loader.all(self) ]
+        self._vars_plugins = [ x for x in vars_loader.all(self) ]

         # FIXME: shouldn't be required, since the group/host vars file
         #        management will be done in VariableManager
```

I am not sure if there's some other change in behavior that I should be accounting for in my vars_plugin.  I rely on the get_host_vars function being called from my plugin.

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by jpetrelliswork** [comment]
##### Issue Type:

Bug Report

##### Ansible Version:

2.0.0 (devel)

##### Ansible Configuration:

ask_pass=True

##### Environment:

Master/Client - SLES11SP2

##### Summary:

When passing inventory as a hostlist (form: ansible-playbook foo.yml -i 'host1,'), vars_plugins are not assigned correctly and do not get executed.  
I am not sure if there's some other change in behavior that I should be accounting for in my vars_plugin.  I rely on the get_host_vars function being called from my plugin.

##### Steps To Reproduce:

Add a vars plugin.  Execute with -i as a file and it will work.  Execute with -i 'host1,' and it will not.

##### Expected Results:

I would expect vars plugins to always run.

##### Actual Results:

Vars plugins do not run when specifying inventory as -i 'host1,host2, 

Notes:
This worked for me.  It moves the self._vars_pluigins assignment out of the if, elif of parse_inventory. 

```
diff --git a/lib/ansible/inventory/__init__.py b/lib/ansible/inventory/__init__.py
index d25409b..00002aa 100644
--- a/lib/ansible/inventory/__init__.py
+++ b/lib/ansible/inventory/__init__.py
@@ -124,7 +124,7 @@ class Inventory(object):

                 # should never happen, but JIC
                 raise AnsibleError("Unable to parse %s as an inventory source" % host_list)

-            self._vars_plugins = [ x for x in vars_loader.all(self) ]
+        self._vars_plugins = [ x for x in vars_loader.all(self) ]

         # FIXME: shouldn't be required, since the group/host vars file
         #        management will be done in VariableManager
```

**Comment by bcoca** [comment]
can you show a case to reproduce this? I'm not sure what you are expecting with vars_plugins and a list inventory as there is no path from which to load vars.

**Comment by jpetrelliswork** [comment]
Sure.  Where myvar1 should evaluate to string "variable_is_defined" from my vars_plugin.
Also, ANSIBLE_VARS_PLUGINS is set to a custom dir where the plugins live.

```
09:54 petrelli@master:Ansible2>ansible-playbook joe.yml -i 'host1,'
SSH password: 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [host1]

TASK [debug var=myvar1] ************************
ok: [host1] => {
    "changed": false, 
    "myvar": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
host1                 : ok=2    changed=0    unreachable=0    failed=0   
```

However, this works when I change "-i 'host1,'" to "-i inv" where `cat inv` looks like:

> host1

```
09:56 petrelli@master:Ansible2>ansible-playbook joe.yml -i inv
SSH password: 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [host1]

TASK [debug var=myvar1] ************************
ok: [host1] => {
    "changed": false, 
    "myvar1": "variable_is_defined"
}

PLAY RECAP *********************************************************************
host1                 : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
im sorry, but i'm still at a loss on the use case, this seems like a contrived example, vars_plugins are there in the inventory to load from files adjacent to the inventory file/dir ... not sure what you want to happen when there is no 'file to be adjacent to'

**Comment by jpetrelliswork** [comment]
In my use case, ANSIBLE_VARS_PLUGINS is a full path, so being adjacent to the inventory file does not matter.  The issue is that unless I am loading inventory from a file, the function to load vars_plugins does not happen.  

It's easiest to illustrate my issue in this code block in inventory/**init**.py in parse_inventory:

```
if isinstance(host_list, basestring): #This is where I match
    host_list = [ h for h in host_list if h and h.strip() ]
[...]
if host_list is None:
    self.parser = None
elif isinstance(host_list, list): #Match again here.
    # Some stuff...
elif os.path.exists(host_list):
    # Some stuff...
    self._vars_plugins = [ x for x in vars_loader.all(self) ] #This is the function that should be called.  If it isn't called, self._vars_plugins is empty and they do not get executed when they are supposed to.
```

Pre 2.0, the aforementioned function was called just after the if, elif, elif mentioned above. See line 141 here: https://github.com/ansible/ansible/blob/v1.9.2-1/lib/ansible/inventory/__init__.py vs. line 127 here: https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py

**Comment by bcoca** [comment]
that makes sense, pushed fix
