### ISSUE TITLE
ansible.cfg ssh_args -tt does not work

### ISSUE THREAD

**Issue by fuentecilla86** [ansible/ansible#12103]
Hi guys!

I have some problem when I need a "pseudo" tty when I execute "sudo" in a task.

I will give you the context:

ansible.cfg:
[ssh_connection]
ssh_args = -o ControlPersist=15m -o ControlMaster=auto -q
scp_if_ssh = True
pipelining = True
control_path = /tmp/1440572988%%h_%%p_%%r

If I run a playbook that needs sudo with this ansible.cfg, I have this error:
"sudo: sorry, you must have a tty to run sudo"

This happens because I have in the sudoers file of the server (it is necessary): "Defaults    requiretty"

Therefore,  the way to avoid the error is execute ssh with a pseudotty. If I run:
ssh -tt server 'cat /etc/sudoers',  it works perfectly.

But the problem is that If I add this flag to the ansible.cfg it does not work:
ansible.cfg:
[ssh_connection]
ssh_args = -tt -o ControlPersist=15m -o ControlMaster=auto -q
scp_if_ssh = True
pipelining = True
control_path = /tmp/1440572988%%h_%%p_%%r

debug does not show any error and it does not continue with the execution, stay in gathering facts all the time until timeout is reached.

Could anyone help me?

Thanks in advance ;)

**Comment by jimi-c** [comment]
Hi @fuentecilla86, by default, the `-tt` option is added unless you are running in "pipelining" mode (where the module code is sent over stdin instead of uploaded and then executed). You might want to set `pipelining = False`, or remove the `requiretty` option from your sudoers config file.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
