### ISSUE TITLE
win_template - is it possible to template a file from a remote machine to a remote machine?

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12100]
I have been attempting to use win_template to template a jinja formatted file located on a windows node to the same windows node. However it seems it can only be used to template a file from the local machine to a windows node. Is there a fix for this?

**Comment by jhawkesworth** [comment]
Hi @Robby123 

Please could you ask this sort of 'how to use ansible' type question on the ansible-project mailing list - a lot more people will see it there rather than on a github issue.

You can use fetch to retrieve a file from your remote machine before templating it if necessary.  Just remember as you scale up to multiple machines you will need to pick up the correct file for each host you are managing.  Perhaps if you shared a  bit more about what you are trying to achieve others can suggest a more ansibleish way of doing what you need - but as I said before, please ask on the mailing list rather than here.

Many thanks,

Jon

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
