### ISSUE TITLE
populate ansible_sudo_pass from the value of "ansible-playbook -K"

### ISSUE THREAD

**Issue by ediazcomellas** [ansible/ansible#12138]
I've got a playbook to sign up a machine in a service. During the execution, I've got to specify a sudo password to the remote command line:
- name: insert machine in hpsum inventory
  command: hpsum add --nodes "{{ inventory_hostname }}" type=linux user=myloginuser password="{{ ansible_sudo_pass }}" use_sudo=true 
  delegate_to: hpsum_server

This works great as long as I manually set ansible_sudo_pass in the playbook variables, but I would want to use the password entered in the CLI when calling ansible-playbook -K.  

So far, the best aproximation is to use vars_prompt and set ansible_sudo_password with it, but I dislike this solution. I know I can enter that password in the vault, but maintaining the vault is an extra work that I would rather avoid.

Can ansible_sudo_pass be populated by default with the value entered with -K? It would be easy to override if needed. 

BTW: ansible version 1.7.2. If this has been done in updated versions, please just close this issue.
Regards

**Comment by jimi-c** [comment]
Hi @ediazcomellas, this is more of a general use question than an issue.  We reserve Github for bugs and feature requests. Could you please direct it to one of the mailing lists?
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
