### ISSUE TITLE
Multiline strings with leading spaces

### ISSUE THREAD

**Issue by zerkms** [ansible/ansible#12133]
How would one specify the multiline strings that have leading spaces on some lines?

If I define a variable as

```
multiline_str: |
    foo
      bar
        baz
```

And then write it to a file using

```
- name: write multiline string
  copy: content="{{ multiline_str }}" dest="/path/to/file"
```

Then the target file contents is

```
foo
bar
baz
```

What component performs a trim and is it possible to disable such a behaviour?

**Comment by jimi-c** [comment]
Hi @zerkms, using a slightly modified form of your example:

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    multiline_str1: |
      foo
        bar
          baz
    multiline_str2: >
      foo
        bar
          baz
  tasks:
  - copy: content="{{ multiline_str1 }}" dest="/tmp/12133_1.txt"
  - copy: content="{{ multiline_str2 }}" dest="/tmp/12133_2.txt"
</pre>

I get the correct output for both forms of line continuations:

<pre>
# ansible-playbook -vv 12133.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 12133.yml
PLAY ***************************************************************************
TASK [copy content={{ multiline_str1 }} dest=/tmp/12133_1.txt] *****************
changed: [localhost] => {"changed": true, "checksum": "640f6c667739682f05d7b35659412a298a54c6d6", "dest": "/tmp/12133_1.txt", "gid": 0, "group": "root", "md5sum": "25d8f13956606f828b4949eaf4893c9a", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 18, "src": "/root/.ansible/tmp/ansible-tmp-1440781343.31-120951687602534/source", "state": "file", "uid": 0}
TASK [copy content={{ multiline_str2 }} dest=/tmp/12133_2.txt] *****************
changed: [localhost] => {"changed": true, "checksum": "640f6c667739682f05d7b35659412a298a54c6d6", "dest": "/tmp/12133_2.txt", "gid": 0, "group": "root", "md5sum": "25d8f13956606f828b4949eaf4893c9a", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 18, "src": "/root/.ansible/tmp/ansible-tmp-1440781343.44-167289592929193/source", "state": "file", "uid": 0}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
# cat /tmp/12133_1.txt 
foo
  bar
    baz
# cat /tmp/12133_2.txt 
foo
  bar
    baz
</pre>

So it appears that we've corrected this issue in devel, and the fix will be included in the 2.0 final release.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
