### ISSUE TITLE
Devel bug - Error when using <bound method CallbackModule.v2_runner_on_skipped - global name 'C' is not defined

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#12145]
I'm currently seeing the following which seems a bit related to #12014 

```
[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_skipped of
<ansible.plugins.callback.default.CallbackModule object at 0x10f7fe650>>: global name 'C' is not defined
```

ansible version:

```
 $ ansible-playbook --version
ansible-playbook 2.0.0 (devel ec95ad1062) last updated 2015/08/28 20:07:00 (GMT +100)
```

happens on a reasonably slow (20-30sec?) yum install in my case.

```
- name: ensure sss packages are installed
  yum: name={{ item }} state=present
  with_items: "{{ lnbis_stdbase_sss_packages | default([]) }}"
```

```
lnbis_stdbase_sss_packages:
  - sssd
  - oddjob-mkhomedir
```

interestingly, the task before it is also a yum install and that one works fine.

**Comment by halberom** [comment]
I had a look at this briefly, C should exist, as it's imported at the beginning in lib/ansible/plugins/callback/**init**.py

```
from ansible import constants as C
```

so it's probably being imported (certainly works from the python cli).

If I re-run the playbook (with the packages installed), it then works. So I'm (massively) guessing it's a timing issue.  Where the strategy is doing some form of timeout, calling the skip callbackup, and then there's a scope issue.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
