### ISSUE TITLE
Getting SSL issue again

### ISSUE THREAD

**Issue by tolmasky** [ansible/ansible#12161]
msg: Failed to validate the SSL certificate for get.docker.com:443. Use validate_certs=False or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

This is with ansible version 1.9.2. I read on another bug that this is fixed in development branch. Does this mean my only options are to do this insecurely (=False) or run the alpha 2.0 branch?

**Comment by abadger** [comment]
I don not believe that any fixes for that issue have made it into devel that have not made it into 1.9.2.  Could you link the bug and I can verify for you?

Also, what is the playbook that you are using and the version of python on the box that is actually running the task that connects to get.docker.com?

**Comment by tolmasky** [comment]
This is what I have:

 # Config Docker
- name: Add Docker repository key
  sudo: yes
  apt_key: url="https://get.docker.com/gpg" id="A88D21E9"

(We used to have docker.io, but that 301's and also breaks for that reason). I'll report back the python version in a bit.

**Comment by jbaramidze** [comment]
same issue here

**Comment by abadger** [comment]
@tolmasky, I did a little bit of looking into this.  Looks like docker is using SNI to serve get.docker.com.  Unfortunately, SNI isn't supported by python until python-2.7.9.  If the host doing the downloading is using python-2.7.9 or greater then things should be working.  If that host is using python less than 2.7.9 then you unfortunately cannot use get_url securely as the python module that implements the url fetching and certificate verification did not gain the ability to do SNI until 2.7.9. Two workarounds exist: You can tell get_url to download this without verifying the certificate belongs to the server using validate_certs=False. Since this means the connection is subject to man-in-the-middle attacks I would not recommend this as, with that URL, it's likely you're hoping to establish a chain of trust.  If the SSL certificate can't be verified then the chain of trust is broken.  Instead, you can use curl or wget with the command module. They have had support for SNI for longer than the python standard library functions.

@jbaramidze If you're also trying to retrieve files from get.docker.com then the same comments I made above apply to you.  If you're using a different website, you can look at my comments on this ticket: https://github.com/ansible/ansible/issues/11579#issuecomment-121775819 to find out if the website you're connecting to uses SNI.  If so, then the same potential solutions and workarounds apply.  Note that validate_certs=False is a potential workaround if you trust that the machine you're connecting to is authentic.  NOt something I'd recommend for retrieving over the internet but a possibility if you control the remote machine and the network between them.

I'll close this ticket as this seems to be what's going on here but if you are trying to use this with python-2.7.9+ on the machine that's executing the task feel free to ping me on IRC (abadger1999 on irc.freenode.net #ansible channel) the mailing list, or open a new bug report to get the issue looked at.

**Comment by Jared-Prime** [comment]
We're seeing this same issue on Ubuntu 14.04 with Python 2.7.6. If I'm understanding correctly, it seems that the main ubuntu apt repository [does not make 2.7.9 available](http://askubuntu.com/questions/559036/when-will-the-python-2-7-9-upgrades-be-available-from-apt-get-for-14-04lts#560159). For the time being, we're using the `shell` command; but it would be nice if there were a cleaner workaround. Do you think a fix is possible for users of Python 2.7.6?

/cc @DrMavenRebe @ctailor2

**Comment by abadger** [comment]
After having researched this extensively last month, the short answer is no.  But I'm very happy to share what I've discovered to explain my thinking.

Python-2.7.9 is the first version that has builtin support for SNI.  Without that support in the client, websites which make use of SNI to decide which certificate to present to the user are left in the dark as to which certificate to send and thus we get errors because the domain name we contact does not match with the server-side certificate that's presented.

Most python2 clients ignore the problem, leading to insecure connections without warning the user of the potential for Man-in-the-middle attacks.  A few can make the connection securely when operating on python-2.7.9+ and have to fall back to either working insecurely or refusing a connection (ansible falls into this category but allows the user to explicitly make their own choice about whether to work insecurely or connect in another way).

There are one or two third-party client python libraries that can do SNI in python2.  requests is probably the most popular of those.  However, to successfully use SNI on python<2.7.9, requests requires that you install three additional third party python libraries of which one needs to be compiled. (You also have to make sure that the version of requests you are using is new enough... older versions of requests also didn't handle SNI.)  Since ansible needs to be functional on systems that have very little in the way of third party modules (routers and internal, audited systems, for instance) not all of ansible's modules are good candidates to port to using requests with all of these additional dependencies.

I've toyed with the idea of trying to use requests to make calls if available and switching to ansible's fetch_url module if it isn't available.  However, that adds to the complexity of the code and just requests presence isn't enough to guarantee a better experience (you need all of those optional third party libraries as well).  It seems like a bit of work to create and potentially a lot of work to maintain securely.

With all this in mind, I think that the cleanest and most secure solution for people on python < 2.7.9 is going to be the command or shell modules.  People who care less about security can choose not to validate the certificates.  This is the what they are doing with a large amount of other python2 based software running on python<2.7.9 anyway, they just haven't been informed of the security choice that they are making there.

Someone with some coding skills could take a shot at adding optional usage of requests (or pycurl?  I've heard that it can do SNI which makes sense since curl itself can) if we're on python <2.7.9 but it's not a guaranteed sell.  The complexity and maintenance cost has to be weighed against the gains vs using curl and wget as workarounds.

**Comment by offlinehoster** [comment]
While downloading a file from https://downloads.typesafe.com/play get_url is telling me:

```
msg: Failed to validate the SSL certificate for downloads.typesafe.com:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
```

This is a Debian 8 64bit machine and

```
python --version
Python 2.7.9
```

**Comment by antonbormotov** [comment]
I have faced with this issue.
Third-party ppa repositories helped me:

```
---
# Add apt keys
  - name: add key for ppa python repository
    apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
    become: yes
    become_user: root
    become_method: sudo

# Add extra repositories
  - name: Add ppa python repository
    apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes
    become: yes
    become_user: root
    become_method: sudo

# Update python version
  - name: ensure python2.7 tatest  is installed
    apt:
      pkg: python2.7
      state: latest
      install_recommends: no
    become: yes
    become_user: root
    become_method: sudo
```

**Comment by abadger** [comment]
@offlinehoster If you have python-2.7.9 then it is most likely not SNI that's at issue.  Instead ansible isn't able to find a CA certificate that would allow you to verify the certificate that the server presents to you.  It looks like this is the case for downloads.typesafe.com and your host.  If I do this on fedora21 (with python-2.7.8) I get the SNI or certificate error:

```
 ansible localhost -m get_url -a 'url=https://downloads.typesafe.com/ dest=/var/tmp/download'
localhost | FAILED >> {
    "failed": true,
    "msg": "Failed to validate the SSL certificate for downloads.typesafe.com:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"
}
```

When I do the same thing on a fedora 24 host (which has python-2.7.10) it completes successfully:

```
$ ansible localhost -m get_url -a 'url=https://downloads.typesafe.com/ dest=/var/tmp/download'
localhost | success >> {
    "changed": false,
    "dest": "/var/tmp/download",
    "gid": 100068,
    "group": "toshio",
    "mode": "0664",
    "msg": "file already exists",
    "owner": "toshio",
    "secontext": "unconfined_u:object_r:user_tmp_t:s0",
    "size": 119,
    "state": "file",
    "uid": 100068,
    "url": "https://downloads.typesafe.com/"
}
```

I'm going to lock this issue as we're not keeping track of any discussions that might be happening on these closed tickets so further questions like this just sit here without answers.  For people coming to this via google web searches, hopefully the information here and in the other issues I linked to are helpful.  If you need more help, please use the mailing list if you think there might just be something you're not understanding or open a new issue if you think what you're seeing is a bug.  I'll paste the mailing list information below.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
