### ISSUE TITLE
Always load variables/defaults from roles defined in playbook regardless of --tags or a role being 'hit' first.

### ISSUE THREAD

**Issue by darkl0rd** [ansible/ansible#12163]
**Issue Type:** 
- Enhancement Request

**Ansible Version:**
- All

**Ansible Configuration:** 
- N/A

**Environment:**
- N/A

**Summary:**
Roles are unable to access 'defaults' from other roles unless explicitly loaded using include_vars or without having 'hit' the other role first. 

**Use Case:**
A role such as 'nginx' or 'apache' that has it's document_root defined as '/var/www' in defaults. Other roles rely on that value but can't access it by default when using --tags.

**Proposal:**
Have ansible scan all roles defined in the playbook for defaults and variables and load them regardless of '--tags'. First would be 'defaults', overridden by 'vars' and then followed by the current way of loading variables (group_vars, host_vars, playbook vars etc.).

**Steps to Reproduce:**
- Define 2 roles 
- Enclose those in a playbook
- Setup the first role with a default variable
- Limit your playbook to only run the second role
- Have the second role print the 'default' variable from the first role

**Expected Results:**
- The variable to be available

**Actual Results:**
- The contrary.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example:

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  roles:
  - { role: foo, tags: foo }
  - { role: bar, tags: bar }
# cat roles/foo/defaults/main.yml 
foo: "Hi from foo"
# cat roles/bar/tasks/main.yml 
- debug: msg="the foo variable = {{foo}}"
# ansible-playbook -vv test.yml --tags=bar
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [bar : debug msg=the foo variable = {{foo}}] ******************************
ok: [localhost] => {
    "changed": false, 
    "msg": "the foo variable = Hi from foo"
}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
