### ISSUE TITLE
Error while building the RPM

### ISSUE THREAD

**Issue by skynet** [ansible/ansible#12166]
```
RPM build errors:
    File not found by glob: /usr/local/src/ansible/rpm-build/BUILDROOT/ansible-2.0.0-0.git201508310021.6b73cac.devel.amzn1.x86_64/usr/lib/python2.7/dist-packages/ansible*
make: *** [rpm] Error 1
```

Correct location is:

```
/usr/local/src/ansible/rpm-build/BUILDROOT/ansible-2.0.0-0.git201508310021.6b73cac.devel.amzn1.x86_64/usr/lib/python2.7/site-packages/ansible>
```

**Comment by jimi-c** [comment]
@skynet how are you building the RPM?

**Comment by skynet** [comment]
```
$ git clone git://github.com/ansible/ansible.git --recursive
$ cd ./ansible
$ make rpm
```

**Comment by skynet** [comment]
I was able to build on a different system. This error is probably related to python version and libraries.

**Comment by skynet** [comment]
Worked here:

```
$python --version
Python 2.6.6
```

Failed here:

```
$ python --version
Python 2.7.9

```

**Comment by toshywoshy** [comment]
Working with Python 2.7.5
https://rpmrepo1.vantosh.com/yum/el7/x86_64/srpms/ansible-2.0.0-1.el7.src.rpm

**Comment by jimi-c** [comment]
Interesting, I'm on 2.7.10 and it works for me as well.

**Comment by skynet** [comment]
We'll wait for others to report similar issues. Going back to stable, since 2.0 fails in other places too. Thanks.

**Comment by abadger** [comment]
@skynet  It looks like something isn't configured correctly in the python or rpm you're using on that system.  The file glob in the ansible spec file that's throwing that error looks like this:

```
%{python_sitelib}/ansible*
```

The `%{python_sitelib}` is an rpm macro.  rpm itself usually defines it in /usr/lib/rpm/macros:

```
$ grep -ri python_sitelib /usr/lib/rpm
/usr/lib/rpm/macros:%python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())")
$ rpm -qf /usr/lib/rpm/macros
rpm-4.12.0.1-7.fc21.x86_64
```

you can see what rpm would expand the macro to using:

```
$ rpm --eval '%{python_sitelib}'
/usr/lib/python2.7/site-packages
```

From the definition, the macro is calling python to define itself.  If you run:

```
$ rpm --eval '%{__python}'
/usr/bin/python
$ /usr/bin/python -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())"
/usr/lib/python2.7/site-packages
```

It should tell you the same value you had before.

When the ansible spec file runs python it uses `%{__python}` to invoke setup.py just like the rpm macro uses to expand python_sitelib.  This should mean that the same path is being used in both places.  Since it's not, there's probably something misconfigured in either python or rpm on the system.

If you do want to look into this further, the complete output from make rpm might hold some clues as to where the two paths are diverging and therefore where the problem lies.

**Comment by skynet** [comment]
Thanks. I get this:

```
$grep -ri python_sitelib /usr/lib/rpm
/usr/lib/rpm/macros:%python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())")
```

```
$rpm -qf /usr/lib/rpm/macros
rpm-4.11.2-2.64.amzn1.x86_64
```

```
rpm --eval '%{python_sitelib}'
/usr/lib/python2.6/dist-packages
```

```
$ rpm --eval '%{__python}'
/usr/bin/python2.6

$ /usr/bin/python -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())"
/usr/lib/python2.7/dist-packages
```

Looks like I am running with python2.6 in the path.

**Comment by abadger** [comment]
yeah, so rpm is being told by python to look in dist-packages for the python modules.  Can you pastebin or gist the complete output from make rpm for me to look at?

**Comment by skynet** [comment]
Sure, here it is: https://gist.github.com/skynet/13090d69f0100e44a11b

**Comment by abadger** [comment]
Looks like we're not hte only ones having this issue:
- https://github.com/twindb/twindb-agent/issues/9
- https://github.com/rfairburn/amazon-linux-rpms/blob/master/rpmbuild/SPECS/rhnlib.spec#L51

That spec file has a workaround that's really, really hacky but may be general enough to work here.  I'll have to think about what it might break.

Out of curiosity, what does:

```
/usr/bin/python2.6 -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())"
```

Return to you?  Also do you care whether you run ansible on this machine via python2.7 or python2.6?  It looks like Amazon Linux is setup to allow either (and select which one is the default via alternatives). It may be that building rpms works when python2.6 is selected as the default but not reliably when python2.7 is the default (seeing as the output from your rpm commands shows python2.6 when you run rpm -q --eval '%{__python}' )

Our Makefile is trying to use the default python which should be right for most users but it could be that Amazon's setup is so far out of the norm that it makes things worse here.  you could try using alternatives to set the default python to python26, try building the package, and then use alternatives to set the default version back to python2.7?  The fact that it's dist-packages vs site-packages rather than python2.7/dist-packages vs python2.6/dist-packages inclines me to thinking that won't help but since I don't know just how odd Amazon's packaging may be I can't be sure that it won't work either.

**Comment by abadger** [comment]
Okay, slept on it and although I still don't understand quite what amazon linuxis doing to get those variables to mismatch, I do think we can adapt the workaround in that amazon-linux-rpms spec file to do the right thing on amazon linux and not mess up anyone else.  Let me work up a potential fix.

**Comment by abadger** [comment]
Okay, PR opened with potential fix: #12265

**Comment by skynet** [comment]
:+1:

**Comment by abadger** [comment]
Thanks for reporting and testing!  #12265 merged so we should be good here for now.
