### ISSUE TITLE
with_subelements example from documentation doesn't work

### ISSUE THREAD

**Issue by emanation** [ansible/ansible#12176]
Hello
I really get lost. I spent 2 days with playbook trying to use `with_subelements` feature. After all I tried to run example from [Documentation](http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-subelements)

```
tasks:
  - name: Print webcred_result
    debug: var=users
    tags: debugvars

  - name: Setup MySQL users
    debug: var="user={{ item.0.user }}"
    with_subelements:
    - users
    - mysql.hosts
    tags: debugvars
```

I use `debug` module here. but playbook fails on sub loop.
And issue happens only if second list uses nested subkey like `mysql.hosts`

```
TASK: [Print users var] ************************************************** 
ok: [testinghost] => {
    "var": {
        "users": [
            {
                "authorized": [
                    "/tmp/alice/onekey.pub",
                    "/tmp/alice/twokey.pub"
                ],
                "mysql": {
                    "hosts": [
                        "%",
                        "127.0.0.1",
                        "::1",
                        "localhost"
                    ],
                    "password": "mysql-password",
                    "privs": [
                        "*.*:SELECT",
                        "DB1.*:ALL"
                    ]
                },
                "name": "alice"
            },
            {
                "authorized": [
                    "/tmp/bob/id_rsa.pub"
                ],
                "mysql": {
                    "hosts": [
                        "db1"
                    ],
                    "password": "other-mysql-password",
                    "privs": [
                        "*.*:SELECT",
                        "DB2.*:ALL"
                    ]
                },
                "name": "bob"
            }
        ]
    }
}

TASK: [Setup MySQL users] ***************************************************** 
fatal: [testinghost] => could not find 'mysql.hosts' key in iterated item '{'authorized': ['/tmp/alice/onekey.pub', '/tmp/alice/twokey.pub'], 'name': 'alice', 'mysql': {'password': 'mysql-password', 'hosts': ['%', '127.0.0.1', '::1', 'localhost'], 'privs': ['*.*:SELECT', 'DB1.*:ALL']}}'

FATAL: all hosts have already failed -- aborting
```

And you can see at `debug: var=users` and fatal error report that `mysql.hosts` does exist indeed.
I was thinking that it's issue with key declaration but `"{{mysql.hosts}}"` , `mysql[hosts]` or "{{mysql[hosts]}}" do not help.
Sorry if I missed something but I really was too close to commit my mental disorder while was debugging this. 
Ansible is 1.9.2  with Python 2.7.6
Thanks.

**Comment by jimi-c** [comment]
On devel, I'm not seeing this issue (though I did have to make it `item.0.name` instead of `item.0.user` per the example):

<pre>
ok: [localhost] => (item=[{u'authorized': [u'/tmp/alice/onekey.pub', u'/tmp/alice/twokey.pub'], u'name': u'alice', u'mysql': {u'password': u'mysql-password', u'privs': [u'*.*:SELECT', u'DB1.*:ALL']}}, u'%']) => {
    "item": [
        {
            "authorized": [
                "/tmp/alice/onekey.pub", 
                "/tmp/alice/twokey.pub"
            ], 
            "mysql": {
                "password": "mysql-password", 
                "privs": [
                    "*.*:SELECT", 
                    "DB1.*:ALL"
                ]
            }, 
            "name": "alice"
        }, 
        "%"
    ], 
    "user={{ item.0.name }}": "user=alice"
}
ok: [localhost] => (item=[{u'authorized': [u'/tmp/alice/onekey.pub', u'/tmp/alice/twokey.pub'], u'name': u'alice', u'mysql': {u'password': u'mysql-password', u'privs': [u'*.*:SELECT', u'DB1.*:ALL']}}, u'127.0.0.1']) => {
    "item": [
        {
            "authorized": [
                "/tmp/alice/onekey.pub", 
                "/tmp/alice/twokey.pub"
            ], 
            "mysql": {
                "password": "mysql-password", 
                "privs": [
                    "*.*:SELECT", 
                    "DB1.*:ALL"
                ]
            }, 
            "name": "alice"
        }, 
        "127.0.0.1"
    ], 
    "msg": "here we are"
}
ok: [localhost] => (item=[{u'authorized': [u'/tmp/alice/onekey.pub', u'/tmp/alice/twokey.pub'], u'name': u'alice', u'mysql': {u'password': u'mysql-password', u'privs': [u'*.*:SELECT', u'DB1.*:ALL']}}, u'::1']) => {
    "item": [
        {
            "authorized": [
                "/tmp/alice/onekey.pub", 
                "/tmp/alice/twokey.pub"
            ], 
            "mysql": {
                "password": "mysql-password", 
                "privs": [
                    "*.*:SELECT", 
                    "DB1.*:ALL"
                ]
            }, 
            "name": "alice"
        }, 
        "::1"
    ], 
    "msg": "here we are"
}
ok: [localhost] => (item=[{u'authorized': [u'/tmp/alice/onekey.pub', u'/tmp/alice/twokey.pub'], u'name': u'alice', u'mysql': {u'password': u'mysql-password', u'privs': [u'*.*:SELECT', u'DB1.*:ALL']}}, u'localhost']) => {
    "item": [
        {
            "authorized": [
                "/tmp/alice/onekey.pub", 
                "/tmp/alice/twokey.pub"
            ], 
            "mysql": {
                "password": "mysql-password", 
                "privs": [
                    "*.*:SELECT", 
                    "DB1.*:ALL"
                ]
            }, 
            "name": "alice"
        }, 
        "localhost"
    ], 
    "msg": "here we are"
}
ok: [localhost] => (item=[{u'authorized': [u'/tmp/bob/id_rsa.pub'], u'name': u'bob', u'mysql': {u'password': u'other-mysql-password', u'privs': [u'*.*:SELECT', u'DB2.*:ALL']}}, u'db1']) => {
    "item": [
        {
            "authorized": [
                "/tmp/bob/id_rsa.pub"
            ], 
            "mysql": {
                "password": "other-mysql-password", 
                "privs": [
                    "*.*:SELECT", 
                    "DB2.*:ALL"
                ]
            }, 
            "name": "bob"
        }, 
        "db1"
    ], 
    "msg": "here we are"
}
</pre>

So it appears this error may be corrected in devel, if you'd like to test there to verify.

**Comment by haad** [comment]
+1 This happens to me on latest 1.9.3 

$ ansible --version
ansible 1.9.3

**Comment by leocrawford** [comment]
Likewise 1.9.4

**Comment by svalo** [comment]
It's working in ansible 2
`$ ansible --version`
`ansible 2.0.0.2`

**Comment by lieutdan13** [comment]
I'm seeing the same behavior in 1.9.5.

**Comment by julienvey** [comment]
Using a simple playbook, this feature works with ansible 2.0+ but doesn't with ansible 1.9

**Comment by jimi-c** [comment]
# Closing This Ticket

Based on the fact that this is working in 2.0, but not in 1.9.x (which is now only receiving security fixes, we're going to close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
