### ISSUE TITLE
Including task defined within a role fails without relative path

### ISSUE THREAD

**Issue by vboginskey** [ansible/ansible#12171]
##### Summary:

The documentation states:

> Any include tasks can reference files in roles/x/tasks/ without having to path them relatively or absolutely

I don't seem to be able to invoke this behavior.
##### Steps To Reproduce:

```
❯ tree .
.
├── play.yml
└── roles
    └── foo
        └── tasks
            ├── bar.yml
            └── main.yml

❯ cat play.yml

---
- name: Test Ansible include
  hosts: localhost
  connection: local

  roles:
    - role: foo

  tasks:
    - include: bar.yml

❯ cat roles/foo/tasks/main.yml

---

❯ cat roles/foo/tasks/bar.yml

---
- debug: msg=bar
```
##### Expected Results:

The `debug` task runs and prints `bar`.
##### Actual Results:

```
❯ ansible-playbook -vi localhost, -c local play.yml
ERROR: file could not read: [...]/ansible/bar.yml
```

**Comment by jimi-c** [comment]
Hi @vboginskey, before that bullet list you refrence, we note `This designates the following behaviors, for each role 'x':`. This means that the `include` would need to be in the main.yml of the role, and it will attempt to find it in the `role/foo/tasks/` directory first, and then look in the playbook directory. This does not work in reverse, as your example attempts.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
