### ISSUE TITLE
Ansible Vault writes secrets to disk

### ISSUE THREAD

**Issue by anm** [ansible/ansible#12182]
ansible-vault edit saves the decrypted file in /tmp. Unencrypted secrets should never touch disk.

**Comment by amenonsen** [comment]
Don't use `ansible-vault edit` at all. The way to avoid sensitive plaintext ever hitting disk (in devel; it's not possible in 1.9) is to use `echo secrets|ansible-vault encrypt --output some.yml` and `ansible-vault decrypt some.yml --output -`.

**Comment by amenonsen** [comment]
I'd like to clarify my comment above:
1. When I say "don't use ansible-vault edit", I mean in this specific circumstance, where you don't ever want your sensitive data to hit the disk unencrypted. If you don't care about that, then it's not applicable.
2. When I write `echo ...|ansible-vault`, it's just an example to show that ansible-vault can be fed from stdin. But @jimi-c correctly points out that actually doing that may cause the secrets to show up in ps output etc. Please take that into consideration.

**Comment by jimi-c** [comment]
HI @anm, the file is created using https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp, so it's not simply dropping a file in /tmp that anyone can see/read. There are additional ways to mitigate this (file system encryption or piping the data through ansible-vault as @amenonsen mentions, or SELinux enforcing mode to name a few), however this is a limitation of using an editor to modify the file.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
