### ISSUE TITLE
Service reported as started when lacking permissions on Ubuntu

### ISSUE THREAD

**Issue by metajungle** [ansible/ansible#12181]
I'm running a playbook to verify that a service ("tomcat7") is running on a host (Ubuntu 14.04). Ansible responds that the service is running when it is not, and returns an "OK" if the permissions are not there to actually start the service. If I use "sudo: yes", the service is actually started. 

Running the following playbook: 

``` yaml
- hosts: url-expander-services
  tasks:
      - name: ensure tomcat is started 
        service: name=tomcat7 state=started 
        sudo: yes
        register: start
      - name: start output
        debug: var=start
```

returns: 

```
(ansible)ansible $ ansible-playbook -i dev url-expander-tests.yml 

PLAY [url-expander-services] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [10.14.6.36]

TASK: [ensure tomcat is started] ********************************************** 
ok: [10.14.6.36]

TASK: [start output] ********************************************************** 
ok: [10.14.6.36] => {
    "var": {
        "start": {
            "changed": false,
            "invocation": {
                "module_args": "name=tomcat7 state=started",
                "module_name": "service"
            },
            "name": "tomcat7",
            "state": "started"
        }
    }
}

PLAY RECAP ******************************************************************** 
10.14.6.36                 : ok=3    changed=0    unreachable=0    failed=0   
```

when the service is not running. 

If I add "sudo: yes" to the service task in the playbook, the following happens: 

```
(ansible)ansible $ ansible-playbook -i dev url-expander-tests.yml 

PLAY [url-expander-services] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [10.14.6.36]

TASK: [ensure tomcat is started] ********************************************** 
changed: [10.14.6.36]

TASK: [start output] ********************************************************** 
ok: [10.14.6.36] => {
    "var": {
        "start": {
            "changed": true,
            "invocation": {
                "module_args": "name=tomcat7 state=started",
                "module_name": "service"
            },
            "name": "tomcat7",
            "state": "started"
        }
    }
}

PLAY RECAP ******************************************************************** 
10.14.6.36                 : ok=3    changed=1    unreachable=0    failed=0   
```

That is, the state is actually changed. 

I would expect an error thrown in the non-sudo case because the service is not running and the playbook states that the service _should_ be running. 

I'm I right, or am I misunderstanding something? This is using Ansible version 1.9.2.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
