### ISSUE TITLE
Errors when using different hostnames

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12189]
I am using:
Python 2.6.6
CentOS 6.5

Hosts file:
c3puimmsrv1.premierinc.com
c3puhiws2.premierinc.com
c3puhiapp1.premierinc.com
c3dumcoamq1.premierinc.com

I get 2 different errors with the same command:

[vagrant@devops ~]$ ansible -i ./hosts all -m ping -u jegger
c3puimmsrv1.premierinc.com | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
c3puhiws2.premierinc.com | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!"
}
c3puhiapp1.premierinc.com | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "  File \"/home/jegger/.ansible/tmp/ansible-tmp-1441131111.73-207143967228926/ping\", line 213\r\n    return dict((_convert(k), _convert(v)) for k, v in node.items)\r\n                                             ^\r\nSyntaxError: invalid syntax\r\n",
    "parsed": false
}
c3dumcoamq1.premierinc.com | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

**Comment by jimi-c** [comment]
Hi @jegger42, what is the OS on the target systems? In the case of `c3puhiws2.premierinc.com` it looks like it'd be a python 2.4 based system (CentOS/RHEL 5 maybe?), in which case json is not available by default and needs to be installed. In the case of `c3puhiapp1.premierinc.com` I'm unclear what the error is, since we check syntax against python 2.4, so I'm curious if this is running an even older version of python there? Please note that our minimum supported version of python is 2.4.

**Comment by ghost** [comment]
I get it. I didn't realize that it ran python on the destination systems.
Thanks for clarifying.

**Comment by jimi-c** [comment]
Ok, if there's no further issue here I'll go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
