### ISSUE TITLE
Ssh connection: always set remote user if it is present in configuration

### ISSUE THREAD

**Issue by vitaliel** [ansible/ansible#12185]
Maybe we should not check if current user login match, to override ~/.ssh/config host/user option.

For example I have a set of hosts that are configured in ~/.ssh/config to connect with root user. If some server was reinstalled I need to reinstall my ssh key on root user. I have a sudo user that match user name on my laptop. I set it in playbook.yml, but code verifies that is equal with current user and does not set the -o User option, as the result ssh take root user from ~/.ssh/config.

This seems easy to fix, by removing additional check from if statement:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connections/ssh.py#L113

**Comment by jimi-c** [comment]
The problem here is the opposite of your situation, in which the test is not present and users do want the .ssh/config option to be the one used. This is essentially why we have that check there, so unfortunately removing it would impact other users.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
