### ISSUE TITLE
Setting $HOME on *_plugins in ansible.cfg doesn't expand

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12180]
Tested with devel from 01-09-2015 and 1.9.2

Set the following in ansible.cfg:

```
filter_plugins     = $HOME/ansible/plugins/filter_plugins/:/usr/share/ansible_plugins/filter_plugins
```

Or any other path with $HOME. It will **not** work.

I made a strace (thanks to crab from IRC for pointing to check it), and found the following:
https://gist.github.com/Tahvok/99dd7c2e49936bde96d3

However, setting a tilde '~' works as expected.

Other configurations do work with $HOME, such as 'inventory', 'remote_tmp' and 'roles_path'.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
