### ISSUE TITLE
copy content="{{ var }}\n" loses the explict trailing newline

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12199]
**Issue Type**: Bug Report
**Ansible Version**:

```
ansible 2.0.0 (devel e8d7fafc52) last updated 2015/09/02 09:36:18 (GMT +300)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/02 08:52:41 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/02 08:52:41 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```

**Ansible Configuration**: none whatsoever
**Environment**: Ubuntu 15.04
**Summary**:

Files created with the `copy` module using `content` lack trailing newlines despite me explicitly adding one.  This used to work in 1.9.2.

**Steps To Reproduce**:

```
$ cat test.yml

---
- hosts: localhost
  gather_facts: no
  vars:
      var: "hello"
  tasks:
    - copy: content="{{ var }}\n" dest=/tmp/output

$ ansible-playbook test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [copy content={{ var }}
 dest=/tmp/output] ********************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Expected Results**:

```
$ xxd /tmp/output
0000000: 6865 6c6c 6f0a                           hello.
```

**Actual Results**:

```
$ xxd /tmp/output
0000000: 6865 6c6c 6f                             hello
```

**Comment by chrrrles** [comment]
Related to https://github.com/ansible/ansible/issues/12200 perhaps?

**Comment by mgedmin** [comment]
Yes!  `content="hello\n"` ends up with the trailing newline in the file, `content="{{var}}\n"` gets the newline stripped.  I think fixing #12200 will fix this one too.

There are some differences: #12200 affects both 1.9.2 and 2.0.0, while this bug only shows up in 2.0.0.  Curious.

**Comment by abadger** [comment]
@mgedmin Thanks for finding and reporting these issues!  This and #12200 should be fixed by the above change.  There may be some cornercases where we want to _remove_ trailing newlines -- if you notice any of those please let us know and we'll  see if we can work that in.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
