### ISSUE TITLE
Using variables in literal blocks strips trailing newlines

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12200]
**Issue Type**: Bug Report
**Ansible Version**: 1.9.2 (and also v2)
**Ansible Configuration**: none whatsoever
**Environment**: Ubuntu 15.04

**Summary**:
A module argument loses the trailing newline if you use {{ variables }} inside it.

**Steps To Reproduce**:
- Create a `test.yml` with the following contents:

``` yaml

---
- hosts: localhost
  gather_facts: no
  vars:
      var: "hello"
  tasks:
    - copy:
        dest: /tmp/has-trailing-newline
        content: |
            hello
            goodbye
    - copy:
        dest: /tmp/no-trailing-newline
        content: |
            {{ var }}
            goodbye
```
- `ansible-playbook test.yml`

**Expected Results**:

```
$ xxd /tmp/no-trailing-newline; xxd /tmp/has-trailing-newline
0000000: 6865 6c6c 6f0a 676f 6f64 6279 650a       hello.goodbye.
0000000: 6865 6c6c 6f0a 676f 6f64 6279 650a       hello.goodbye.
```

**Actual Results**:

```
$ xxd /tmp/no-trailing-newline; xxd /tmp/has-trailing-newline
0000000: 6865 6c6c 6f0a 676f 6f64 6279 65         hello.goodbye
0000000: 6865 6c6c 6f0a 676f 6f64 6279 650a       hello.goodbye.
```

**Comment by mgedmin** [comment]
[Jinja's behavior with newlines](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control):

> In the default configuration:
> - a single trailing newline is stripped if present

and

> By default, Jinja2 also removes trailing newlines. To keep single trailing newlines, configure Jinja to _keep_trailing_newline_.

If Ansible pipes arguments through the Jinja2 template engine only when it finds variables being used in the argument value, this would explain the behavior.

I think it would make sense to set keep_trailing_newline to True when processing YAML nodes (but keep the default behavior when processing standalone template files).

**Comment by mgedmin** [comment]
> I think it would make sense to set keep_trailing_newline to True when processing YAML nodes (but keep the default behavior when processing standalone template files).

Actually, given #12198, perhaps keep_trailing_newline should be True always?  It looks like Ansible 1.9.2 did not strip the trailing newline from standalone templates.

**Comment by abadger** [comment]
I see why this is happening.  Looking at the best way to fix it.  Instead of using the config var that you've dug up, it appears that the present code counts newlines in the input and the output and then re-adds newlines if they don't match.  Trying to figure out if there's a reason to do it that way or if I should use keep_trailing_newlines by default.

**Comment by abadger** [comment]
Ah -- keep_trailing_newline wasn't present until jinja2-2.7.  I bet that not all Linux distributions have that version.

**Comment by mgedmin** [comment]
Surely people who pip install the latest ansible can pip install a sufficiently-recent jinja2, especially if ansible's setup.py has a versioned requirement?

**Comment by abadger** [comment]
yeah, but this is soon to be released and distros will want to package it.  Not a problem for fixing this bug -- just means that there's a reason to fix this code by adding the newlines back rather than setting the config option.

**Comment by abadger** [comment]
Hmm... this fix I'm trying doesn't seem to fix this particular issue.  I'm thinking we must be passing preserve_trailing_newlines=True to the Templare._do_template() method somewhere in v1 but not in v2.  I'll check whether this fix does fix the newline portion of #12198, though.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by cgwalters** [comment]
If anyone else hits this and is on 1.9.X, I successfully worked around this by squashing everything into one string in the argument form, e.g.:

```
    - copy: dest=/etc/motd content="###\n{{ content }}\n###\n"
```
