### ISSUE TITLE
Fact cache being ignored on 2.0?

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12213]
```
ansible 2.0.0 (devel 843138e7d9) last updated 2015/09/02 18:58:01 (GMT +100)
  lib/ansible/modules/core: (detached HEAD ef1f31c652) last updated 2015/08/31 21:19:36 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 5b39e19387) last updated 2015/08/31 21:19:36 (GMT +100)
  config file = /Users/matt/Development/ansible/ansible.cfg
  configured module search path = None
```

ansible.cfg

```
[default]
gathering = smart
fact_caching = jsonfile
fact_caching_connection = factcache
fact_caching_timeout = 86400
```

In 1.9.2 setup doesn't show up when the cache is used. 
2.0.0 calls setup each time and setup appears slower that in 1.9.2/

**Comment by jimi-c** [comment]
I see the problem. If `gather_facts: smart` is specified in the play, things work as expected, however the setting is not being picked up from the ansible.cfg correctly. I'll work on a patch shortly.

**Comment by jimi-c** [comment]
Well actually, it appears that `smart` in the play may simply make it skip fact gathering as well, so continuing to investigate.

**Comment by jimi-c** [comment]
Scratch what I said above, I thought it could be specified at the play level, but was incorrect. Still looking into why it's not picking that setting up.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by mattwillsher** [comment]
That's fixed if for me. Thanks, @jimi-c
