### ISSUE TITLE
delegate_to works incorrectly with with_items

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#12222]
Here's a sample task:

``` yml
- name: collect facts for hosts in 'hosts_group' group
  action: setup
  delegate_to: "{{ item }}"
  when: hostvars[item]['ansible_eth1'] is not defined
  with_items: groups[hosts_group]
```

The idea is to collect facts for hosts that are not involved in this run directly. And here's the result.

```
TASK: [test | collect facts for hosts] ******************************* 
ok: [db -> app] => (item=app)
skipping: [db -> app] => (item=db)
ok: [db -> srv] => (item=srv)

TASK: [test | put hosts file] **************************************** 
fatal: [db] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}
fatal: [db] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}
```

So facts were not collected!

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

The actual issue is that your when is incorrectly constructed, use this instead:

`when: "'ansible_eth1' not in hostvars[item]"`

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by hryamzik** [comment]
I don't see any issues with `when`, only one host is skipped so it looks good for me. I've taken `when` from you example and got the same result.

```
TASK: [test | collect facts for hosts, broken, github.com/ansible/ansible/issues/12222] *** 
ok: [db -> app] => (item=app)
skipping: [db -> app] => (item=db)
ok: [db -> srv] => (item=srv)

TASK: [test | put hosts file] **************************************** 
fatal: [db] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}
fatal: [db] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute u'ansible_eth1'", 'failed': True}

FATAL: all hosts have already failed -- aborting
```
