### ISSUE TITLE
Literal newlines in YAML vars are being ignored when using Jinja filters in templates

### ISSUE THREAD

**Issue by jesseiqmi** [ansible/ansible#12241]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible-playbook 2.0.0 (devel 7ece767767) last updated 2015/09/03 10:59:37 (GMT -700)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/02 17:49:00 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/02 17:49:00 (GMT -700)
  config file = 
  configured module search path = None
##### Ansible Configuration:

N/A
##### Environment:

OSX Yosemite 10.10.5 to Ubuntu 14.04
##### Summary:

Newlines within YAML var files don't seem to be observed as they should within a template with usage such as `environment={{ app_environment | mandatory | replace('\n', ',') }}`  

The behavior seemed to have changed (i.e. it was working as described) within the last couple of days (4 or so) since I had last pulled to refresh Ansible locally dev.  

The current work around that I have in place is just to flatten the environment variables myself ahead of time, but it makes it more difficult to manage as you start to load in extra env vars.
##### Steps To Reproduce:

Followed the steps provided in http://blog.paulopoiati.com/2015/03/01/how-do-i-configure-environment-variables-in-ansible/ for supervisor configuration with ngnix+unicorn+rails.

Relevant variables

``` yaml
app_environment: |
    RAILS_ENV={{ env }}
    SECRET_KEY_BASE={{ secret_key_base }}
    WEB_CONCURRENCY={{ web_concurrency }}
```

Template

``` ini
[program:unicorn]
user={{ deploy_user_username }}
directory=/home/{{ deploy_user_username }}/apps/{{ app_name }}
command=bundle exec unicorn -c config/unicorn.rb
autostart=true
autorestart=true
environment={{ app_environment | mandatory | replace('\n', ',') }}
```
##### Expected Results:

``` ini
[program:unicorn]
user=deploy
directory=/home/deploy/apps/opsapp
command=bundle exec unicorn -c config/unicorn.rb
autostart=true
autorestart=true
environment=RAILS_ENV=staging,SECRET_KEY_BASE=secret,WEB_CONCURRENCY=2
```
##### Actual Results:

``` ini
[program:unicorn]
user=deploy
directory=/home/deploy/apps/opsapp
command=bundle exec unicorn -c config/unicorn.rb
autostart=true
autorestart=true
environment=RAILS_ENV=staging
SECRET_KEY_BASE=secret
WEB_CONCURRENCY=2
```

**Comment by abadger** [comment]
This is the commit causing this: 7f5080f64ab4a82648cb746990587c1aaff3f61d  which means that this is probably another manifestation of https://github.com/ansible/ansible/issues/12198

**Comment by abadger** [comment]
@jesseiqmi Thanks for finding and reporting this!  There've been a few changes in the past week that whose effect is far reaching.  If you find other things that seem broken or different in a bad way let us know and we'll either fix it or be sure to document why the change is being made and how to port it when moving from v1 to v2.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by arbabnazar** [comment]
@jesseiqmi If you use the `replace` function with the same value and use the variable with the mentioned format inside the blog post then you will get an extra `,` at the end of the line, which I think you don't want. I have solved this problem like this:

modified the variable:

``` yaml
app_environment: |
    RAILS_ENV={{ env }}
    SECRET_KEY_BASE={{ secret_key_base }}
    WEB_CONCURRENCY={{ web_concurrency }}
```

Then modified the `replace` function like this:

``` jinja2
[program:unicorn]
user={{ deploy_user_username }}
directory=/home/{{ deploy_user_username }}/apps/{{ app_name }}
command=bundle exec unicorn -c config/unicorn.rb
autostart=true
autorestart=true
environment={{ app_environment | mandatory | replace(' ', ',') }}
```

Hope that help you or anyone else who is looking for the solution of this problem.
