### ISSUE TITLE
V2 does not load host_vars/*.yml files

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#12245]
##### Issue Type:

Bug Report
##### Ansible Version:

devel 
ansible 2.0.0 (detached HEAD a6de4b86a8) last updated 2015/09/04 09:54:40 (GMT +200)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/04 09:54:04 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/04 09:54:04 (GMT +200)
  config file =
  configured module search path = None
##### Ansible Configuration:

none
##### Environment:

Control host: OSX
Remote host: Debian 7
##### Summary:

Hi, version 2.0 does not load host_vars/*.yml files.
##### Steps To Reproduce:

ansible-playbook -i hosts load_yml.yml

```
==> load_yml.yml <==

---
- hosts: deb7.inter.nos
  tasks:
    - debug: var=foo
    - debug: var=group_foo

==> host_vars/deb7.inter.nos.yml <==

---
foo: bar

==> group_vars/g.yml <==
group_foo: group_bar

==> hosts <==
[g]
deb7.inter.nos
```
##### Expected Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [deb7.inter.nos]

TASK [debug var=foo] ***********************************************************
ok: [deb7.inter.nos] => {
    "changed": false,
    "foo": “bar"
}

TASK [debug var=group_foo] *****************************************************
ok: [deb7.inter.nos] => {
    "changed": false,
    "group_foo": "group_bar"
}

PLAY RECAP *********************************************************************
deb7.inter.nos             : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [deb7.inter.nos]

TASK [debug var=foo] ***********************************************************
ok: [deb7.inter.nos] => {
    "changed": false,
    "foo": "VARIABLE IS NOT DEFINED!"
}

TASK [debug var=group_foo] *****************************************************
ok: [deb7.inter.nos] => {
    "changed": false,
    "group_foo": "group_bar"
}

PLAY RECAP *********************************************************************
deb7.inter.nos             : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
