### ISSUE TITLE
devel logic vs 1.9 - if hosts in play A don't respond, die, do not continue to play B

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#12284]
I've got a playbook like

```

---
- hosts: foo
  gather_facts: yes

- hosts: bar
  gather_facts: yes
  roles:
    - bar
```

testing in Vagrant, I don't always spin up foo.  In 1.9.3, this gives

```
$ time ansible-playbook plays/cfg/resolve.yml -i inv/dev_vagrant

PLAY [foo] ************************************* 

GATHERING FACTS *************************************************************** 
fatal: [foo] => SSH Error: ssh: connect to host 192.168.35.12 port 22: Operation timed out
    while connecting to 192.168.35.12:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

PLAY [bar] ******************************************************* 

GATHERING FACTS *************************************************************** 
ok: [bar]
...
```

vs in devel, where it dies

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [foo]: FAILED! => {"failed": true, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
foo  : ok=0    changed=0    unreachable=0    failed=1   

```

Expected:
that devel does what 1.9 does?  or at least has a flag/option to allow it

Actual:
different behavior

Quesiton:
is this expected?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
