### ISSUE TITLE
ec2_asg termination_policies 'termination_policies is not defined' 

### ISSUE THREAD

**Issue by cgrigor** [ansible/ansible#12289]
Hi,

I've just pulled the latest devel and creating an aws asg group (at least for me) fails when this worked in the past.

The following is a code snippet of the playbook task:

```
- name: Create AutoScaling Group Rundeck
    ec2_asg:
      name: "LP_{{env|upper}}_Rundeck_ASG_1"
      launch_config_name: "LP_{{env|upper}}_LaunchConfig"
      state: present
      health_check_period: 450
      health_check_type: EC2
      min_size: "{{ rundeck.asg.min }}"
      max_size: "{{ rundeck.asg.max }}"
      desired_capacity: "{{ rundeck.asg.desired }}"
      region: "{{ aws.region }}"
      vpc_zone_identifier: "{{ subnets.subnet_ids.0 }}"
      wait_for_instances: yes
    register: rdasg
  - debug: var=rdasg
```

An exception occurred during task execution. The full traceback is:

```
Traceback (most recent call last):
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2744, in <module>
    main()
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2733, in main
    create_changed, asg_properties=create_autoscaling_group(connection, module)
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2345, in create_autoscaling_group
    termination_policies=termination_policies)
NameError: global name 'termination_policies' is not defined

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

The docs section of `ec2_asg.py` says that `termination_policies` default is set to a value of Default, so my guess is that it's not required in my task definition.
`termination_policies` and `default_cool_down` were introduced in the following commit https://github.com/ansible/ansible-modules-core/commit/f7f621839ad2063c707506f7eaf5663f113664a7#diff-689b2e5ce09076c21c9915e50f8a9140

Can anyone else verify if they get the same error? My colleague also reproduced this issue with the same error.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by mikepii** [comment]
@cgrigor did you happen to re-submit the ticket on ansible-modules-core? I'm having the same issue and looking for more info
