### ISSUE TITLE
vars_prompt changes (defaults to "private: yes")

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [ansible/ansible#12297]
While testing our playbooks with 2.0.0-0.2.alpha2, I discovered that unless I include "private: no" in the call, I cannot see any characters I am entering.  I also discovered that the compact form:

vars_prompt:
   variable_name: "Prompt string"

no longer works (it did in 1.9.1) and now requires an explicit "name" parameter.

**Comment by jimi-c** [comment]
@JohnPeacockMessageSystems this appears to have been a bug in the old code, where it was not properly respecting the defaults set unless it was done so explicitly with `private: yes`. As the default of not showing sensitive passwords on the screen is much more sane, we're going to leave it this way.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by JohnPeacockMessageSystems** [comment]
I'll post this to the mailing list as well, but I think this is a bad decision.  You seem to be assuming that most prompts will be for passwords, hence the default of  `private: yes` but I think that is precisely backwards.  I think that most prompts will be normal text and if you want to hide the text you should explicitly add `private: yes` in those case.

This problem would be much less critical if you at least echo'd something to the console (asterisk is the normal convention), instead of just eating every character.

**Comment by jimi-c** [comment]
Fair enough, but to counter your point the convention on Unix/Linux systems is not to echo anything to the screen. And yes, the base assumption regarding the prompt is that it will be used for passwords or other sensitive information which users would not want to store in a file, which is why we decided to fix the bug the way we did.

**Comment by dukas** [comment]
Sorry that I'm posting in closed issue.
But as JohnPeacockMessageSystems we are using vars_prompt as "yes/no" functionality and 
branch/tag/revision for subversion/git. Isnt' password vault for passwords? Probably should be discussed

**Comment by bandjalong** [comment]
This seems silly. To add "private: yes" for a password is easy, to add "private: no" for everything that isn't (which in some cases could be a lot of variables) is a a pain. The statement that the convention on Unix/Linux systems is to not echo anything is weird - the convention for passwords is certainly to obfuscate it with stars, but for anything else, no. The assumption that all variables are passwords is just wrong.

**Comment by datacarl** [comment]
Agree that the case where we do _not_ want to obfuscate the user input is much more common. 

Would it make sense to use a setting in the playbook to alter the default behaviour? Maybe by setting `vars: {ansible_vars_prompt_private_default: no/yes}`. I don't know the design principles of Ansible well enough to determine if that's a good idea or not, but from a UX-perspective it seems fairly simple and easy to understand. Just a thought.
