### ISSUE TITLE
implement meta: close_connection

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#12298]
This would allow forcing logins for when the remote user's group/auth information is updated so it can be immediately reused in play.

For this to happen:
-  task_executor needs to stop closing connections after each task
- winrm connections either need to reuse connections or autoclose after each invocation 
- re enable ssh connection closing for dealing with control master/persist

possibly put this in framework of redoing how we handle connections and connection caching (user/host/port/transport)

**Comment by jhawkesworth** [comment]
Thanks, this sounds useful.  I've not really explored if this is possible currently or not, but something I'd like to be able to do with windows hosts is bring up a windows vm from a template, set the hostname, ip and add it to a domain and then carry on using a domain user rather than a local administrator user.  Probably easy enough to work around with a little scripting but would nice to be able to have it all embodied in a playbook so intentions are clear.

**Comment by ThomasSteinbach** [comment]
fixes ansible/ansible-modules-core#2488

**Comment by bcoca** [comment]
fixed via cc0bb54d2c7d74f8bb155ce602dfb0eecc6da752, but renamed: `meta:refresh_connection`
