### ISSUE TITLE
ansible-pull git options

### ISSUE THREAD

**Issue by montekki** [ansible/ansible#12309]
Ansible Version: 1.9.2
Ansible Configuration: default
Environment: N/A

Summary:

Since 1.9 force=no is the default behaviour for git module and in case of using git from ansible playbooks this options is possible to change. However when running ansible-pull this option is impossible to change which may break the whole checkout on the machine running ansible-pull in case some file in the playbooks repo has a local change or smth else.
Could you add some option to ansible-pull that could be passed to the git module? Or make the git module read it's options from ansible.cfg.

Expected results:
ansible-pull is able to pass force=yes to the git module.

Actual results:
ansible-pull always uses git module with force=no which results in failing to run the playbook in case local modifications to the playbook repo exist.

**Comment by w1r0x** [comment]
In addition to montekki's report

It will be great to add "track_submodules" option to update submodules to latest ones.
With the check if there at least one submodule changed => we should get
`"changed": true`
state. 

May be you should add option to pass args directly to module, because it can be not only git.

**Comment by w1r0x** [comment]
@montekki Why do you have local modifications in your repo? Do you use git submodules? Maybe your problem in tracking submodules too?

**Comment by w1r0x** [comment]
Seems it bug with track_submodules in git module.

Always when you get update on your submodule it goes to detached head state and parent repo get "Local modifications exist" state
When you try to update next time git repo with track_submodules you'll receive that local modifications exists, so we need force=yes
Even with force=yes head and remote sha in parent repo will be the same so git module won't update repo at all and of course submodules

**Comment by w1r0x** [comment]
Will be nice with https://github.com/ansible/ansible-modules-core/issues/1509

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
