### ISSUE TITLE
Differing behavior when using inline vars vs. vars dict with nested includes and with_items:/with_random_choice:

### ISSUE THREAD

**Issue by bretmartin** [ansible/ansible#12314]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel e6c9efec63) last updated 2015/09/10 10:35:26 (GMT -400)
  lib/ansible/modules/core: (h3 0d59980845) last updated 2015/09/06 14:09:15 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6a3cf63351) last updated 2015/09/10 14:40:31 (GMT -400)
  config file = 
  configured module search path = None
```
##### Ansible Configuration:

no `ansible.cfg`, using defaults
##### Environment:

N/A but running on Mac OS X
##### Summary:

I found while writing a role that has an `include` using `with_items:` where the included file uses `with_items:` or `with_random_choice:` that things work as expected when I use inline variables for the include, but not when I use a `vars:` dict.

It seems like when I use the `vars:` dict, the `item` in the "outer" `with_items:` is getting replaced by the `item` from the "inner" one.
##### Steps To Reproduce:

```
==> roles/test/defaults/main.yml <==

---

dictionary:
  thingy_a:
    datapoint: 1
    optional: optional_value
  thingy_b:
    datapoint: 2

==> roles/test/tasks/included.yml <==

---

- debug: msg='{{ key }}'
  with_items: ['1', '2']

==> roles/test/tasks/main.yml <==

---

- include: included.yml key='{{ item }}'
  with_items: dictionary

- include: included.yml
  vars:
    key: '{{ item }}'
  with_items: dictionary
```
##### Expected Results:

I expect the same results from both tasks in `tasks/main.yml`; the first one (with inline variable specification) seems correct to me.
##### Actual Results:

```
ansible-playbook --vault-password-file=~/.ansible_vault_password \
        playbook-test.yml --limit=localhost -vvvv
No config file found; using defaults
1 plays in playbook-test.yml
Loaded callback default of type stdout, v2.0

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: bam
localhost EXEC (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1441910635.77-13736629580480" && echo "$HOME/.ansible/tmp/ansible-tmp-1441910635.77-13736629580480")
localhost PUT /var/folders/n7/wrg1c7615892m2qgyv8r_yg00000gn/T/tmpaQX774 TO /Users/bam/.ansible/tmp/ansible-tmp-1441910635.77-13736629580480/setup
localhost EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/bam/.ansible/tmp/ansible-tmp-1441910635.77-13736629580480/setup; rm -rf "/Users/bam/.ansible/tmp/ansible-tmp-1441910635.77-13736629580480/" > /dev/null 2>&1
ok: [localhost]

TASK [test : include key={{ item }}] *******************************************
included: included.yml for localhost => (item=thingy_a)
included: included.yml for localhost => (item=thingy_b)

TASK [test : debug msg={{ key }}] **********************************************
ok: [localhost] => (item=1) => {
    "item": "1", 
    "msg": "thingy_a"
}
ok: [localhost] => (item=2) => {
    "item": "2", 
    "msg": "thingy_a"
}

TASK [test : debug msg={{ key }}] **********************************************
ok: [localhost] => (item=1) => {
    "item": "1", 
    "msg": "thingy_b"
}
ok: [localhost] => (item=2) => {
    "item": "2", 
    "msg": "thingy_b"
}

TASK [test : include] **********************************************************
included: included.yml for localhost => (item=thingy_a)
included: included.yml for localhost => (item=thingy_b)

TASK [test : debug msg={{ key }}] **********************************************
ok: [localhost] => (item=1) => {
    "item": "1", 
    "msg": "1"
}
ok: [localhost] => (item=2) => {
    "item": "2", 
    "msg": "2"
}

TASK [test : debug msg={{ key }}] **********************************************
ok: [localhost] => (item=1) => {
    "item": "1", 
    "msg": "1"
}
ok: [localhost] => (item=2) => {
    "item": "2", 
    "msg": "2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
I am actually a little torn as to what the correct behavior here should be. The second case actually seems more correct to me, because in the first case the {{item}} is being templated earlier than I would expect. But in the second, it's {{item}} all the way through, which is why it's picking up the values from the second loop.

Really, this is new, undefined behavior because for the first time we're really doing a double loop, but the iterating variable is still item.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
For the record, we decided the second output is actually the correct one, as in the first the values were previously (and to early) templated, so the value of item should be the one from the second (and inner) loop.
