### ISSUE TITLE
include+with_items breaks with multiple included tasks

### ISSUE THREAD

**Issue by copumpkin** [ansible/ansible#12333]
To repro:
1. Get ansible 2.0 alpha 2
2. Uncomment one or both of the commented-out tasks [here](https://github.com/ansible/ansible/blob/devel/samples/include.yml)
3. Run samples/test_include.yml

Result:
The first debug message works fine, but the second comes out as:

```
TASK [debug msg=this is the third debug in the include, and a is still {{a}}] **
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'a' is undefined"}
```

It looks like @jimi-c might be aware of this, commenting out the extra tasks in this giant commit:

https://github.com/ansible/ansible/commit/785c0c0c8ca8d90f3bccc7206f0c267977f77882

I'm assuming this behavior is expected to work as part of the undeprecation of include+with_items, right?

**Comment by copumpkin** [comment]
As a workaround for now, I've found that wrapping the included file in a giant block appeases the Ansible gods.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
