### ISSUE TITLE
add last error to rescue block

### ISSUE THREAD

**Issue by kai11** [ansible/ansible#12341]
Issue Type: Feature Idea

Ansible Version: 2.0.0

Ansible Configuration: not modified

Environment: Ubuntu 14.04

Summary: add last error to rescue block

Steps To Reproduce:
Rescue block described at http://docs.ansible.com/ansible/playbooks_blocks.html have no way to retrieve last error.
I think error notification will be frequent use case for blocks.

Something like this:

```
tasks:
  - block:
      - command: /bin/false
    rescue:
      - debug: var=ansible_last_error
```

Expected Results:
Last error - playbook, task name, failure message.

Actual Results:
No variable defined

**Comment by jimi-c** [comment]
I was just mentioning to someone last night that this might be useful... not sure if we'll get it in by 2.0 but we'll keep this open.

Thanks!

**Comment by dmsimard** [comment]
Love this, +1.

**Comment by sccu** [comment]
+1. I love this, too.

**Comment by dearlordylord** [comment]
+1.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
