### ISSUE TITLE
Multi-play variable inclusion.

### ISSUE THREAD

**Issue by darkl0rd** [ansible/ansible#12351]
Related to #12163.

As pointed out by jimi-c, this now works however in the scenario whereby you have multiple plays in your playbook it doesn't; for example:

playbook.yml.

```
- name: common actions
  hosts: all
  roles:
    - { role: set_variable 
      , tags: set_variable 
      }

- name: specific actions
  hosts: subset_of_all
  roles:
    - { role: echo_variable 
      , tags: echo_variable
      }
```

In this scenario the second play will fail when ran with --tags 'echo_variable'.

**Comment by bcoca** [comment]
it is not supposed to work, roles set vars at play scope, which means that new plays will not get those vars.

**Comment by darkl0rd** [comment]
Previously, pre-ansible 2.0, variables would not be shared between roles when using --tags, this now works. I understand that the current behavior/design did not intend for this to work, however when you look at the scenario provided it makes sense to do so.

For illustration consider the following overly simplified real-life scenario:
- name: specific actions
  hosts: webservers
  - { role: nginx, tags: nginx }
- name: common actions
  hosts: all 
  roles:
  - { role: logstash-forwarder, tags: logstash-forwarder }
  - { role: zabbix-agent, tags: zabbix-agent }

The logstash-forwarder role needs to be applied to all hosts, however on hosts where nginx is installed it will need to include additional paths, for instance '/var/log/nginx/*.log', these paths could be defined in 'group_vars', 'host_vars' etc, in which case it will work when using --tags.
However in the scenario where the variables are defined in the role 'defaults', which isn't unlikely for a variable such as a log directory, using --tags will break it.

**Comment by jimi-c** [comment]
Hi @darkl0rd, this is a common enough scenario even when not done across plays, due to the fact that you're skipping the task that creates the variable. Tasks which may have a dependent action like this should be setup in such a way that they won't be run without the prior task running - ie. the set_fact should either be tagged with the echo_var or the echo/print analog in the second play should default the variable in the event that it is not present. A better way to do this would be with local facts, which would return information (ie. your second example) about software like nginx being installed.

Ii you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
