### ISSUE TITLE
v2 regression: -T timeout doesn't work

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#12372]
With devel, `ansible -T 30` doesn't seem to set `self._play_context.timeout` at all (but setting `ANSIBLE_TIMEOUT` in the environment does). Anyone working on this already?

**Comment by jimi-c** [comment]
@amenonsen nope, go ahead and send a PR for it if you'd like to correct that.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
