### ISSUE TITLE
Environment not taken into account when using async

### ISSUE THREAD

**Issue by AxelDelmas** [ansible/ansible#12381]
I'm trying to set an env var DISPLAY=:99 in order to launch chromium with ansible, but when I use async I get an error message "... Gtk: cannot open display: ", similar to what I get when I connect manually in ssh and forget to do
export DISPLAY=:99
before trying to launch chromium.

If I remove the async action, chromium launches successfully but then the playbook execution hangs there.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
