### ISSUE TITLE
lineinfile syntax error when there is a space after colon(:)

### ISSUE THREAD

**Issue by kojiwell** [ansible/ansible#12380]
`lineinfile` gives a syntax error when there's a space after colon(:) in the line, like `line='item: value'`. If there's no space, it works fine. 

My ansible version is 1.9.3, and here's an example of the error. This task is trying to modify `/etc/sudoers`, and get the error.

```
ERROR: Syntax Error while loading YAML script, /path/to/roles/testrole/tasks/main.yml
Note: The error may actually appear before this position: line 6, column 63

- name: set up sudo for testgroup
  lineinfile: dest=/etc/sudoers line='%testgroup ALL= NOPASSWD: /sbin/shutdown -r now' state=present insertafter=EOF validate='visudo -cf %s'
                                                              ^
This one looks easy to fix.  There seems to be an extra unquoted colon in the line
and this is confusing the parser. It was only expecting to find one free
colon. The solution is just add some quotes around the colon, or quote the
entire line after the first colon.

For instance, if the original line was:

    copy: src=file.txt dest=/path/filename:with_colon.txt

It can be written as:

    copy: src=file.txt dest='/path/filename:with_colon.txt'

Or:

    copy: 'src=file.txt dest=/path/filename:with_colon.txt'
```

Thanks.

**Comment by kojiwell** [comment]
I got an answer at stackoverflow(Please see the following link if you're interested). What I need to do is to escape the colon like this `{{ ":" }}`. It still looks like a workaround to me. Shouldn't this be fixed (or explained on [the official documentation](http://docs.ansible.com/ansible/lineinfile_module.html))?

http://stackoverflow.com/questions/32592246/ansible-lineinfile-syntax-error-when-there-is-a-space-after-colon/32592341#32592341

**Comment by jimi-c** [comment]
Hi @kjtanaka, the other method is to quote the entire line (as the error text suggests), ie: 

<pre>
lineinfile: "dest=/etc/sudoers line='%testgroup ALL= NOPASSWD: /sbin/shutdown -r now' state=present insertafter=EOF validate='visudo -cf %s'"
</pre>

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by kojiwell** [comment]
Thanks @jimi-c, and sorry about my overlooking what the error suggested. I'll stop by one of the lists next time!

**Comment by jimi-c** [comment]
No problem!
