### ISSUE TITLE
confusion with placement of the host_vars directory

### ISSUE THREAD

**Issue by muelli** [ansible/ansible#12396]
I tried for quite a while to find out where to place host_vars. 

Because  the documentation http://docs.ansible.com/ansible/playbooks_variables.html isn't very extensive on where to place host_vars, I  tried to place the host_vars directory next to the group_vars in the directory of my playbook and I expected it to work, simply because I thought it'd be the correct place due to other variables (group_vars) being located there.

That, however, does not seem to work.

Instead, one seems to have to place the host_vars in the director of the inventory.  In my case, Vagrant generates it in a hidden directory (.vagrant/), so I didn't even think about that.

I think that respecting host_vars in all the places where group_vars are accepted improves coherency within Ansible. If it's not desired to put host_vars next to the playbook, Ansible could issue a warning when loading the variables.

**Comment by sivel** [comment]
Per http://docs.ansible.com/ansible/intro_inventory.html :

> Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in either the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.

**Comment by muelli** [comment]
ah. I think I know why it did not work. I made a hosts_vars directory, not host_vars. Sorry for the noise.

**Comment by jimi-c** [comment]
No problem. In the future, questions like this are definitely better directed to the mailing lists, as we reserve Github issues for bugs and PRs:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
