### ISSUE TITLE
Crash (unhandled exception) on playbook for localhost with empty inventory

### ISSUE THREAD

**Issue by quinot** [ansible/ansible#12391]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 2a50957ad8) last updated 2015/09/16 11:56:18 (GMT +200)
##### Ansible Configuration:

N/A
##### Environment:

FreeBSD melamine.cuivre.fr.eu.org 10.1-RELEASE-p5 FreeBSD 10.1-RELEASE-p5 #0: Tue Jan 27 08:55:07 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
##### Summary:

Crash (unhandled exception) on playbook for localhost with empty inventory.
##### Steps To Reproduce:

Consider playbook ping.yml

```

---
- hosts: localhost
  tasks:
  - name: ping
    action: ping
```
##### Expected Results:

$ ansible-playbook ping.yml
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [ping] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
##### Actual Results:

$ ansible-playbook ping.yml
 [WARNING]: provided hosts list is empty, only localhost is available

Unexpected Exception: 'NoneType' object has no attribute 'add_child_group'
to see the full traceback, use -vvv

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
