### ISSUE TITLE
get more than one object from s3 bucket or get entire bucket at once?

### ISSUE THREAD

**Issue by premctl** [ansible/ansible#12408]
As far as I know s3 module of ansible, it can only get an object at once. My question is that what if I want to download/get entire bukcet or more than one object from s3 bucket at once. Is there any hack?

**Comment by jimi-c** [comment]
Hi @premsompura, we generally reserve github issues for bugs and PRs, and ask that questions like yours be directed to one of the mailing lists or IRC:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Our IRC channels are on Freenode:
- ansible
- ansible-devel (reserved for discussion on code and PRs)

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
