### ISSUE TITLE
Bug report: unexpected behavior when use local_action or delegate_to with shell module 

### ISSUE THREAD

**Issue by paco0x** [ansible/ansible#12406]
**Issue Type:**
Bug Report

**Ansible Version:**

```
$ ansible --version
ansible 1.9.3
```

**Summary:**
I want to echo something to a file using local_action and shell module. When I use `echo -e`, ansible will treat `-e` as string to print rather than a command line argument. See below:

```
$ cat t.yaml
- hosts: localhost
  remote_user: root
  gather_facts: False
  tasks:
    - name: test
      local_action: shell echo -e abc
```

```
$ ansible-playbook -vv t.yaml

PLAY [localhost] **************************************************************

TASK: [test] ******************************************************************
<127.0.0.1> REMOTE_MODULE command echo -e abc #USE_SHELL
changed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": "echo -e abc", "delta": "0:00:00.006123", "end": "2015-09-17 11:04:00.381722", "rc": 0, "start": "2015-09-17 11:04:00.375599", "stderr": "", "stdout": "-e abc", "warnings": []}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

The stdout filed shows that ansible echo a string that is `-e abc` which include the command line argument `-e`. I also test it without local_action option in the playbook. Its behavior is normal as I expected.

```
$ cat t.yaml
- hosts: localhost
  remote_user: root
  gather_facts: False
  tasks:
    - name: test
      shell:  echo -e abc
```

```
$ ansible-playbook -vv t.yaml

PLAY [localhost] **************************************************************

TASK: [test] ******************************************************************
<localhost> REMOTE_MODULE command echo -e abc #USE_SHELL
changed: [localhost] => {"changed": true, "cmd": "echo -e abc", "delta": "0:00:00.001969", "end": "2015-09-17 03:06:25.842056", "rc": 0, "start": "2015-09-17 03:06:25.840087", "stderr": "", "stdout": "abc", "warnings": []}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

This time the stdout does not include the `-e` argument. 

Is there something else I need to do when use local_action and shell module to execute command with argument?

**Comment by premctl** [comment]
use this instead

```
tasks:
    - name: test
      local_action: command shell echo -e abc
```

**Comment by paco0x** [comment]
@premsompura Thanks for your suggestion. I need to use shell module because the output should be redirected to some file.

**Comment by abadger** [comment]
I was going to say that using delegate_to instead of localhost should work (and it does) but when I coped your playbook and gave both versions a try I was unable to reproduce this:

```
$ ansible-playbook -vv test.yml -c ssh                               (20:01:40)

PLAY [localhost] ************************************************************** 

TASK: [test] ****************************************************************** 
<127.0.0.1> REMOTE_MODULE command echo -e abc #USE_SHELL
changed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": "echo -e abc", "delta": "0:00:00.002916", "end": "2015-10-09 20:01:40.701335", "rc": 0, "start": "2015-10-09 20:01:40.698419", "stderr": "", "stdout": "abc", "warnings": []}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

$ ansible --version                                                  (20:02:42)
ansible 1.9.3
  configured module search path = None

Perhaps you should stop by either the mailing list or IRC and see if anyone there can help figure out what might be different on your system?  I'll paste the list information below:

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
