### ISSUE TITLE
Ansible 2: 'groups' playbook variable is a list

### ISSUE THREAD

**Issue by jonashaag** [ansible/ansible#12418]
The documentation in this place https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_variables.rst#id47 is out of date since `groups` is now a list of group names, not a dict.

Will there be a way to access the values of that dict in Ansible 2?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
