### ISSUE TITLE
Ansible error message says 'Set accept_hostkey to True' when docs specify 'yes' instead of true

### ISSUE THREAD

**Issue by jeffwidman** [ansible/ansible#12430]
Ansible error message for the git module says 'Set accept_hostkey to True'

But the ansible docs say the accepted values are 'yes' or 'no', with no 'True' option. 

I'm happy to submit a PR fixing this, just not sure whether you want the docs updated or the error message updated. If error message, looks like there's also a test that needs to be updated as well?

**Comment by chrrrles** [comment]
`accept_hostkey` is defined as a YAML boolean, so strings such as "Yes", "true", or even "OFF" are accepted as valid inputs.

**Comment by chrrrles** [comment]
reopened, pending comments

**Comment by jeffwidman** [comment]
Yeah, I'm not saying it doesn't work, just that the text in the error message and the docs should be consistent. It's a trivial thing, but it's also a trivial fix, and I don't mind making a PR... just not sure whether I should correct the docs or the error message

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
