### ISSUE TITLE
Facts variables are not available in vars_files

### ISSUE THREAD

**Issue by mkubenka** [ansible/ansible#12449]
##### Issue Type:

Bug Report
##### Ansible Version:

devel
##### Environment:

Mac OSX 10.10.5
##### Summary:

Facts variables are not available in `vars_files`. It was working on version 1.9.3.
##### Steps To Reproduce:

test.yml

```
- hosts: all
  sudo: true
  gather_facts: yes
  vars_files:
    - vars/credentials/{{ ansible_hostname }}.vault.yml

  tasks:
    - debug: msg="{{ ansible_hostname }}"
```
##### Expected Results:

```
$ ansible-playbook -i hosts test.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [server]
server: importing vars/credentials/server.vault.yml

TASK: [debug msg="{{ ansible_hostname }}"] ************************************
ok: [server] => {
    "msg": "server"
}

PLAY RECAP ********************************************************************
server    : ok=2    changed=0    unreachable=0    failed=0

```
##### Actual Results:

```
$ ansible-playbook -i hosts test.yml

ERROR! 'ansible_hostname' is undefined
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
