### ISSUE TITLE
Roles breaking change: role parameter from later invocation stomps on default value from earlier invocation

### ISSUE THREAD

**Issue by marcind** [ansible/ansible#12460]
I ran into the following issue when upgrading from 1.9 to latest `devel`. Here's a simple repro:

roles\dep\defaults\main.yml

```

---
my_default_var: from defaults
```

roles\dep\tasks\main.yml

```

---
- debug: var=my_default_var
```

playbook.yml

```

---
- hosts: all
  gather_facts: false
  roles:
  - role: dep
  - role: dep
    my_default_var: from invocation
```

This is the output I get running on 1.9

```
PLAY ************************************************************************** 

TASK: [dep | debug var=my_default_var] **************************************** 
ok: [MYHOST] => {
    "var": {
        "my_default_var": "from defaults"
    }
}

TASK: [dep | debug var=my_default_var] **************************************** 
ok: [MYHOST] => {
    "var": {
        "my_default_var": "from invocation"
    }
}
```

And here's what happens when I run on 2.0

```
PLAY ***************************************************************************

TASK [dep : debug var=my_default_var] ******************************************
ok: [MYHOST] => {
    "changed": false,
    "my_default_var": "from invocation"
}

TASK [dep : debug var=my_default_var] ******************************************
ok: [MYHOST] => {
    "changed": false,
    "my_default_var": "from invocation"
}
```

Notice that in 2.0 there appears to be a change to the variable evaluation order whereby a value gets assigned before the logical order of execution should even put it in scope.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
