### ISSUE TITLE
v2: delegate_to is not indicated in the output

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12465]
In ansible v1 any delegation was clearly visible, e.g.:

```
changed: [muskatas -> fridge]
```

whereas ansible v2 shows just

```
changed: [muskatas]
```

I like seeing which hosts are actually affected by the commands, so I'd like the old output back please.

(You can use the steps-to-reproduce from, e.g. #12464 to reproduce this one too.)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
