### ISSUE TITLE
--limit isn't honored at all

### ISSUE THREAD

**Issue by muffl0n** [ansible/ansible#12473]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel c30e464388) last updated 2015/09/22 16:21:32 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 59afecace4) last updated 2015/09/22 16:21:46 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD dee690d7f4) last updated 2015/09/22 16:21:59 (GMT +200)
  config file = 
  configured module search path = None
```
##### Ansible Configuration:

n/a
##### Environment:

n/a
##### Summary:

I have a simple inventory with four hosts (master1, master2, slave1, slave2) in two different groups (app-server, app-slave). When I use a host-pattern to select one group (e.g. app-server) and specify a host with --limit, ansible just selects all hosts. It does not matter if the host is contained in the selected group.
##### Steps To Reproduce:

hosts:

```
[app-server]
master1
master2

[app-slave]
slave1
slave2
```

Run some module with this inventory, use a host-pattern and limit it with a host. E.g: 
`ansible -i hosts -m debug -a "msg=foo" app-slave -l master1`
`ansible -i hosts -m debug -a "msg=foo" app-slave -l slave1`
##### Expected Results:

```
No hosts matched
```
##### Actual Results:

```
$ ansible -i hosts -m debug -a "msg=foo" app-slave -l master1
slave1 | SUCCESS => {
    "changed": false, 
    "msg": "foo"
}
slave2 | SUCCESS => {
    "changed": false, 
    "msg": "foo"
}
```

```
$ ansible -i hosts -m debug -a "msg=foo" app-slave -l slave1
slave1 | SUCCESS => {
    "changed": false, 
    "msg": "foo"
}
slave2 | SUCCESS => {
    "changed": false, 
    "msg": "foo"
}
```

**Comment by jimi-c** [comment]
Looks like this is just an issue with how we're passing CLI params into the `ansible` command. An equivalent playbook does not run into this bug when run with `ansible-playbook`:

<pre>
# cat test.yml 
- hosts: app-slave
  gather_facts: no
  tasks:
  - debug: msg="foo"
# ansible-playbook -vv test.yml -l master1 -i inv
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
skipping: no hosts matched
PLAY RECAP *********************************************************************
# ansible-playbook -vv test.yml -l slave1 -i inv
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [debug msg=foo] ***********************************************************
ok: [slave1] => {
    "changed": false, 
    "msg": "foo"
}
PLAY RECAP *********************************************************************
slave1                     : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by muffl0n** [comment]
Looks great. Thank you! :+1:
