### ISSUE TITLE
conditional import vars_files does not work in 2.0 

### ISSUE THREAD

**Issue by akazakov** [ansible/ansible#12484]
Given this code: 
vars_files:  
    - config/vars.yml  
    - [ "config/zones/{{ zone }}.yml",  config/zones/default.yml ]  
    - [ "config/stages/{{ stage }}.yml", config/stages/default.yml ]  

in 1.9:
PLAY [all] *******************************************************************\* 
localhsot: not importing file: /home/tyoma/projects/plays/config/stages/prod.yml

TASK: [print vars] ***********************************************************\* 
ok: [localhsot] => {
    "var": {
... [omitted] 

in 2.0
ERROR! the file_name '/home/tyoma/projects/plays/config/stages/prod.yml' does not exist, or is not readable

 ansible --version
ansible 2.0.0 (devel c83f51b7f2) last updated 2015/09/23 02:25:16 (GMT +000)
  lib/ansible/modules/core: (detached HEAD e9139ba4fa) last updated 2015/09/23 02:25:44 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 8b83aa4c50) last updated 2015/09/23 02:25:37 (GMT +000)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
