### ISSUE TITLE
--start-at-task evals on all plays (v2 regression)

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#12482]
Issue Type: Bug Report

Ansible Version: 2.0.0 devel (as of d27b73e7b5)

Environment: N/A

Summary: Running a playbook with --start-at-task applies the filter to every play in the playbook, not just the first occurrence of the task as it did in 1.9.

Steps To Reproduce: run playbook at https://gist.github.com/nitzmahone/6c310b32ea4d4346b2a3 with: `ansible-playbook startatfail.yml --start-at-task="start here"`

Expected Results: task "this should run" from the second play runs (as it did in 1.9)

Actual Results: task "this should run" does not run - --start-at-task condition appears to be evaluated again on each play, instead of stopping on the first occurrence as it did in 1.9.

**Comment by palmerabollo** [comment]
Same here. Do you know any workarounds until it is fixed? Thanks.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
