### ISSUE TITLE
Intelligently detect an IP address passed to the `-i` param, and emit a better error message

### ISSUE THREAD

**Issue by nhooey** [ansible/ansible#12507]
Apparently you can specify a list of IP addresses with `ansible-playbook` with the `-i` parameter:

```
-i 1.1.1.1,2.2.2.2
```

Or in the case of a single IP address:

```
-i 1.1.1.1,
```

But you need to include a trailing comma, so Ansible doesn't check for a file called: `1.1.1.1`.

This isn't very user-friendly. Ansible should be smarter and just detect an IP address when the file is found not to exist.

Also, the error message:

```
ERROR: Unable to find an inventory file, specify one with -i ?
```

Should also mention the ability to provide a single IP or a list of IP addresses.

**Comment by jimi-c** [comment]
@nhooey the comma is used there to determine if the inventory is an adhoc list. Generally, we discourage users from doing inventory this way for anything other than troubleshooting, so for now we have no plans on changing this requirement.

If you would like to continue this discussion, feel free to move it to one of the following devel resources:

```
* https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
* #ansible-devel on Freenode IRC
```

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
