### ISSUE TITLE
with_subelements tasks warn with "not all arguments converted during string formatting"

### ISSUE THREAD

**Issue by genofedanzo** [ansible/ansible#12501]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 5d3d9cfe0d9dd3943245c65b92fd91d33e446f2b)
##### Summary:

Initially I was trying to use with_subelements against the authorized_key module but the task throws an error.  I've tested with the debug module and get the same results.
##### Steps To Reproduce:

You can use the example here (quote placement is wrong in the example to begin with but once adjusted you'll get the error I'm seeing): http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-subelements
##### Expected Results:

SSH Keys will be installed for each user that is part of the list.
##### Actual Results:

`[WARNING]: Error when using <bound method CallbackModule.v2_runner_on_ok of <ansible.plugins.callback.default.CallbackModule object at 0x101279210>>: not all arguments converted during string formatting`

The play continues on but I would think that this would be a critical error and it should abort.

**Comment by genofedanzo** [comment]
Looking into this deeper it appears that the tasks runs fine.  I've validated that the keys end up on the remote server.  It's confusing because you don't get the normal output of each key being checked/added but that is probably tied to the WARNING.  Debug messages must also hit this issue.  Since it actually ran fine it shouldn't abort like I originally thought.

**Comment by jimi-c** [comment]
Yes, this just seems to be a bug in the callback. I'll look into it.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
