### ISSUE TITLE
error conflicting actions statements

### ISSUE THREAD

**Issue by jugalporwal** [ansible/ansible#12504]
My playbook appears as follows:

---
- hosts: localhost
  tasks:
  - name: Get the build
    synchronize: mode=pull src=jenkins_server_ip:/home/capsilon/Jenkins/trunk/builds/{{item}}/ dest=/home/builds/{{item}}
    with_items:
    - ['as2-client', 'amc-gateway', 'router']
- hosts: localhost
  tasks:
  - name: Zip and send
    command: /bin/sh "/home/zipfile.sh"
- hosts: windows
  tasks:
  - name: deploy
    win_get_url:
       url: 'http://server_ip/builds/build.zip'
       dest: 'D:\build.zip'
    win_unzip:
       src: D:\build.zip
       dest: D:\

Get the following error:

ERROR! conflicting action statements

The error appears to have been in '/etc/ansible/playbooks/new_logic_zip.yaml': line 16, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Deployment
      ^ here

What is the error here??

**Comment by jimi-c** [comment]
Hi @jugalporwal, your error is here:

<pre>
    - name: deploy
      win_get_url:
         url: 'http://server_ip/builds/build.zip'
         dest: 'D:\build.zip'
      win_unzip:
         src: D:\build.zip
         dest: D:\
</pre>

You cannot have multiple actions listed inside a single task like this. Instead you need to do this:

<pre>
    - name: deploy get url
      win_get_url:
         url: 'http://server_ip/builds/build.zip'
         dest: 'D:\build.zip'
    - name: deploy unzip
      win_unzip:
         src: D:\build.zip
         dest: D:\
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jugalporwal** [comment]
Thanx @jimi-c  that resolved my issue !
