### ISSUE TITLE
"Yes" variable value requires quotes or it would be interpreted as "True"

### ISSUE THREAD

**Issue by MaximF** [ansible/ansible#12519]
CentOS 6.7, ansible 1.9.2

Variable definition in playbook:

```
  vars:
    cassandra_server_monitoring: yes
```

Task to print this variable:

```
- name: print variables
  debug:
    msg="{{item}}"
  with_items:
    - "{{cassandra_server_monitoring}}"
```

Check debug output:

```
ok: [servername] => (item=True) => {
    "item": "True",
    "msg": "True"
}
```

as you see "True" isn't the same as "yes"
### BUT

if I define that variable in the following way:

```
  vars:
    cassandra_server_monitoring: "yes"
```

it will be printed as "yes"

**Comment by jimi-c** [comment]
Hi @MaximF, this is actually a language feature of YAML: http://yaml.org/type/bool.html.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by MaximF** [comment]
Thank you!
