### ISSUE TITLE
Adding different variable types results in UnsafeProxy error

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#12513]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel
##### Ansible Configuration:

Standard config
##### Environment:

Debian / Ubuntu
##### Summary:

Templating different variable types results in UnsafeProxy error
##### Steps To Reproduce:

Example variable:

```
var: '{{ [ "127.0.0.1/32", "::1/128" ] + ansible_all_ipv4_addresses +
           (ansible_all_ipv6_addresses | difference(ansible_all_ipv6_addresses
            | ipaddr("link-local"))) }}'
```

Assume that `ansible_all_ipv6_addresses` is an empty dict (`{}`).
##### Expected Results:

Ansible works without errors.
##### Actual Results:

During Ansible initialization:

```
ERROR! an unexpected type error occurred. Error was can only concatenate list (not "UnsafeProxy(list)") to list
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
