### ISSUE TITLE
Fetch Module: fail_on_missing is not a legal parameter

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#12517]
I am trying to use [fetch](http://docs.ansible.com/ansible/fetch_module.html) module as below on ansible v1.9.2

``` yaml
- fetch: src=/root/{{ ansible_hostname }}.yaml dest=/tmp/{{ ansible_hostname | regex_replace('-', '_') }}.yaml flat=yes
  fail_on_missing: yes
```

It throws below error, which ideally it shouldn't.

``` bash
# ansible-playbook -v vikas027.yml
ERROR: fail_on_missing is not a legal parameter in an Ansible task or handler
#
```

**Comment by jimi-c** [comment]
Hi @vikas027, the `fail_on_missing` parameter should be in the list of arguments to the module, not on the task itself.

<pre>
- fetch: src=/root/{{ ansible_hostname }}.yaml dest=/tmp/{{ ansible_hostname | regex_replace('-', '_') }}.yaml flat=yes fail_on_missing=yes
</pre>

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
