### ISSUE TITLE
Misleading error code with yml syntax error

### ISSUE THREAD

**Issue by skynet** [ansible/ansible#12512]
With ansible 2.0.0

```
ansible --version
ansible 2.0.0 (devel 82b33c381f) last updated 2015/09/24 14:07:42 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e8227dea7a) last updated 2015/09/24 14:07:45 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f2faf70996) last updated 2015/09/24 14:07:48 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

If syntax error in `vars/main.yml` ansible reports file as missing !!!

```
ansible-playbook -vvvv test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
ERROR! vars file vars/main.yml was not found
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
