### ISSUE TITLE
win_iis_webapppool module is need 'attributes',is bug?

### ISSUE THREAD

**Issue by BenMo158** [ansible/ansible#12554]
I was run:
ansible win -m win_iis_webapppool -a "name=newapp state=restarted"

the error:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +     ~~~~~~~~~~~~~~~~~~
win01 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Property 'attributes' cannot be found on this object. Make sure that it exists."
}

Look at the introduction module,"attributes'' 'required' is “no”

**Comment by jhawkesworth** [comment]
Please advise which version of ansible you are using?

If you are using v2 devel it is possible this is related to recent change which adds enforces strict mode on powershell modules.

**Comment by BenMo158** [comment]
My version is 2.0.0-0.2.alpha2
I try " attributes='' ", it's look ok.

**Comment by jimi-c** [comment]
@x7032335 are you saying this bug is resolved?

**Comment by BenMo158** [comment]
Not yet,but I set attributes='',it's ok.
ansible iis01 -m win_iis_webapppool -a "name=tiger attributes=''"
iis01 | SUCCESS => {
    "attributes": {}, 
    "changed": false, 
    "info": {
        "attributes": {
            "CLRConfigFile": "", 
            "applicationPoolSid": "S-1-5-82-2199063738-3115028567-622233357-329056163-822287282", 
            "autoStart": true, 
            "enable32BitAppOnWin64": false, 
            "enableConfigurationOverride": true, 
            "managedPipelineMode": 0, 
            "managedRuntimeLoader": "webengine4.dll", 
            "managedRuntimeVersion": "v4.0", 
            "name": "tiger", 
            "passAnonymousToken": true, 
            "queueLength": 1000, 
            "startMode": 0, 
            "state": 1
        }, 
        "name": "tiger", 
        "state": "Started"
    }
}

**Comment by jimi-c** [comment]
@x7032335 ok, thanks!

**Comment by blakfeld** [comment]
I have a Pull Request that should fix this (or has for me, anyway!) https://github.com/ansible/ansible-modules-extras/pull/1114

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
