### ISSUE TITLE
Bug while making rpm

### ISSUE THREAD

**Issue by 94d90b08-c4ef-416c-bf7b-b6c5b7275e6a** [ansible/ansible#12558]
OS: CentOS 7 and CentOS 6.5
Step: Installation by making rpm file

While installing ansible 2.0.0-0 on step:
# make rpm

I'm face with such error:
error: line 10: Illegal char '/' in: Release: 0.git201509290550.95ede22.heads/v1931.el7.centos
I find, that it is cause of parameter GIT_BRANCH in Makefile.
So, if delete
GIT_BRANCH=...
and .$(GIT_BRANCH) from next string of makefile,
than '#make rpm' work fine.

Also, CentOS Base repo provides too old version of python-six.
So:
# wget https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz#md5=476881ef4012262dfc8adc645ee786c4
# gzip -dc ./six-1.9.0.tar.gz | tar -xf - -C ./
# cd ./six-1.9.0/
# pip install ./

After that, ansible start working.
PS: sorry for my English)

**Comment by jimi-c** [comment]
The other way to get around this is to prepend the make command with `OFFICIAL=yes`, which excludes the git info. This patch should also fix this, if you'd like to test it out:

<pre>
diff --git a/Makefile b/Makefile
index 508be40..fa334bf 100644
--- a/Makefile
+++ b/Makefile
@@ -41,7 +41,7 @@ RELEASE := $(shell cat VERSION | cut -f2 -d' ')
 ifneq ($(shell which git),)
 GIT_DATE := $(shell git log -n 1 --format="%ai")
 GIT_HASH := $(shell git log -n 1 --format="%h")
-GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD | sed 's/[-_.]//g')
+GIT_BRANCH := $(shell git rev-parse --abbrev-ref HEAD | sed 's/[-_.\/]//g')
 GITINFO = .$(GIT_HASH).$(GIT_BRANCH)
 else
 GITINFO = ''
</pre>

**Comment by 94d90b08-c4ef-416c-bf7b-b6c5b7275e6a** [comment]
Thanks for answer.
Specified patch works on CentOS 7.

**Comment by jimi-c** [comment]
# Closing This Ticket

Thanks! I've merged that now, and this will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by phar1no** [comment]
Fixed:
<     #RPMRELEASE = 100.git$(DATE)**$(GITINFO)**
<     RPMRELEASE = 100.git$(DATE)
