### ISSUE TITLE
ansible_ssh_extra_args erroneously passed to scp

### ISSUE THREAD

**Issue by felddy** [ansible/ansible#12576]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel 12a2585e84) last updated 2015/09/28 20:58:02 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 4de4bd0be6) last updated 2015/09/15 16:27:20 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD ea1bd0b078) last updated 2015/09/15 16:27:24 (GMT -400)
  config file = 
  configured module search path = None
```
##### Ansible Configuration:

``` ini
[defaults]
host_key_checking=false

[ssh_connection]
scp_if_ssh=True
pipelining=True
```
##### Environment:
- ssh: `OpenSSH_6.9p1, OpenSSL 1.0.2d 9 Jul 2015`
- from os: `14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64`
- to os:  `4.0.5-gentoo #1 SMP Thu Sep 17 06:41:50 UTC 2015 x86_64 Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz GenuineIntel GNU/Linux`
##### Summary:

`ansible_ssh_extra_args` are erroneously passed to scp which does not accept the same arguments as ssh.
##### Steps To Reproduce:

Add a remote port forward argument to ssh via inventory: 
`ansible_ssh_extra_args=-R8000:localhost:8000`
##### Expected Results:

During a playbook run, ssh connections will open a reverse port forward back to originating host, and scp executions still function correctly.
##### Actual Results:

Any execution to scp will fail as the -R argument is not valid.

``` log
<10.0.28.126> SSH: EXEC scp -vvv -o ControlMaster=auto -o ControlPersist=60s -o
StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o
PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o
PasswordAuthentication=no -o User=root -o ConnectTimeout=10
-R8000:localhost:8000 -o
ControlPath=/Users/username/.ansible/cp/ansible-ssh-%h-%p-%r
/var/folders/hs/3nrn6j0s5xz_sdzdd20hp5w80000gn/T/tmpPTnP6O

[10.0.28.126]:/root/.ansible/tmp/ansible-tmp-1443629368.35-48734248599665/source
 fatal: [test_vm.geekpad.com]: FAILED! => {"failed": true, "msg": "ERROR!
failed to transfer file to
/root/.ansible/tmp/ansible-tmp-1443629368.35-48734248599665/source:\n\nscp:
illegal option -- R\nusage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i
identity_file]\n [-l limit] [-o ssh_option] [-P port] [-S program]\n
[[user@]host1:]file1 ... [[user@]host2:]file2\n"}
```
##### Workaround / patch

In `Connection._build_command(...)` of `lib/ansible/plugins/connection/ssh.py` check to see if the binary parameter is actually ssh before adding arguments specific to ssh:

``` diff
diff --git a/lib/ansible/plugins/connection/ssh.py b/lib/ansible/plugins/connection/ssh.py
index fce2311..b7800dc 100644
--- a/lib/ansible/plugins/connection/ssh.py
+++ b/lib/ansible/plugins/connection/ssh.py
@@ -225,12 +225,13 @@ class Connection(ConnectionBase):
         # this host, or specified as an override on the command line,
         # add them in.

-        if self._play_context.ssh_extra_args:
-            args = self._split_args(self._play_context.ssh_extra_args)
-            self._add_args("command-line added --ssh-extra-args", args)
-        elif self.ssh_extra_args:
-            args = self._split_args(self.ssh_extra_args)
-            self._add_args("inventory added ansible_ssh_extra_args", args)
+        if self._command == 'ssh':
+            if self._play_context.ssh_extra_args:
+                args = self._split_args(self._play_context.ssh_extra_args)
+                self._add_args("command-line added --ssh-extra-args", args)
+            elif self.ssh_extra_args:
+                args = self._split_args(self.ssh_extra_args)
+                self._add_args("inventory added ansible_ssh_extra_args", args)

         # Check if ControlPersist is enabled (either by default, or using
         # ssh_args or ssh_extra_args) and add a ControlPath if one hasn't
```

**Comment by amenonsen** [comment]
There is currently no mechanism to pass certain arguments only to ssh and not to scp; `ansible_ssh_extra_args` is **not** only for ssh, so this isn't a bug (in particular, your proposed patch would eliminate the ability to configure scp to use a jump host). See #6238 and #11681 for an `ssh_specific_args` proposal that never gained much support. It would be easier to implement that functionality given the framework provided by the `ssh_extra_args` PR, though. Maybe you want to try?

**Comment by jimi-c** [comment]
Here's how we're proposing to fix this:
1) Restrict the use of the above option to be only applied when `binary == 'ssh'`
2) Add a new host variable (`ansible_connection_proxy`, or similar) to which users could add things like tunnel settings, and would be applied to all binaries if present.

**Comment by jimi-c** [comment]
@amenonsen any thoughts on the above?

**Comment by amenonsen** [comment]
@jimi-c I don't think much of that solution at all, to be honest. It's an incredibly niche use-case (that's never been supported), and restricting the generic mechanism we have now (`ssh_extra_args` as currently implemented) just to address that seems backwards to me. I'll note, again, that there was a solution available in the form of #6238 from March 2014 and the rebased #11681 from July 2015, and there was precisely zero interest in either of those.

If it's really necessary to support this, I think the reasonable solution is to add the `ssh_only_args` or `ssh_specific_args` (the originally-proposed name) and leave `ssh_extra_args` as it stands. Otherwise people will inevitably end up abusing your proposed `connection_proxy` variable to set non-proxy-related options just because there's no other way to set them for all binaries. I hate that idea.

**Comment by amenonsen** [comment]
After some discussion on IRC and reading the `ssh(1)`, `scp(1)`, and `sftp(1)` manpages side-by-side, here's what I propose instead.
1. We retain the `[ssh_connection] ssh_args` setting in `ansible.cfg` with the current semantics (i.e. added to the start of the command line for ssh, scp, and sftp) for backwards compatiblity with 1.x.
2. We add inventory variables named `ansible_ssh_common_args` (arguments appended to the command line for ssh, scp, and sftp) as well as `ansible_ssh_extra_args`, `ansible_scp_extra_args`, and `ansible_sftp_extra_args`, which are added only to the command lines of the respective binaries.
3. We do NOT add `ssh_args` as an inventory variable, so there's no confusion about which setting overrides the other.
4. We do NOT allow common/extra args to be set in ansible.cfg (they can be set in `group_vars/all` if they are to be set globally).
5. We document and recommend (2) and deprecate (1).

This would be straightforward to implement and document, and it would address both my use case and @felddy's use case without any compromise: I would set `ansible_ssh_common_args='-o ProxyCommand=….'` in `group_vars/something`, whereas @felddy would set `ansible_ssh_extra_args='-R ….'` instead.

**Comment by bcoca** [comment]
agree on 1, I really don't think its an option to break it at this point

I hate 2, it just adds lots of vars, but it might be only way to give everyone customization so I won't oppose it.

i would leave ansible_ssh_args as an override of ansible.cfg's ssh_args which basically means we do not do 3 and 5, just document well the override and how the _extra_args options are appended per binary. 

4, im not sure of, if we go down this road we might as well go all the way and not do 1/2 measures and allow ansible.cfg customization

**Comment by amenonsen** [comment]
The above is now implemented as #12604, and incidentally fixes a pre-existing bug where ssh argument settings in group_vars or host_vars wouldn't be picked up.

**Comment by amenonsen** [comment]
@bcoca I think you've summed up my feelings about (2) precisely.

As for (3) and (4), I haven't implemented them in the PR I submitted, but it would be easy enough to add (especially following @jimi-c's suggestion of moving the setting logic to PlayContext), so if you guys can agree on what needs to be supported, I can write the code.

Personally, though, I think it's best to leave that out, especially since once we do this in PlayContext, we can't log debug messages to tell the user exactly where the setting came from, not even "from the command line" vs. "from the inventory" (which we could do before). And `group_vars/all` is already available to set any of those variables globally, so it's not as though it would add any extra functionality.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
