### ISSUE TITLE
MemoryError failure when using s3 module

### ISSUE THREAD

**Issue by kevinohara80** [ansible/ansible#12581]
I'm seeing intermittent **MemoryError** failures in ansible **1.9.2**. I have a playbook that is using the s3 module and I'm getting the error when I try a `put` to my bucket. 

The issue seems to come and go as I add/remove other tasks from the playbook.

Error:

```
TASK: [l11_web_restore | download backup from s3] *****************************
failed: [default] => {"failed": true, "parsed": false}
BECOME-SUCCESS-zbxyvkkkghdkdgcwbylrupfazjrrenke
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443643529.79-127154845374483/s3", line 2313, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443643529.79-127154845374483/s3", line 371, in main
    md5_local = hashlib.md5(open(dest, 'rb').read()).hexdigest()
MemoryError
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/kevinohara/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.


FATAL: all hosts have already failed -- aborting
```

**Comment by kevinohara80** [comment]
I think I figured out the issue. The file specified in `dest` in the s3 task already exists on the host machine. If I remove that file manually or even rename it before running the s3 task, everything is ok. 

I then tried adding the `overwrite:true` argument but the error keeps happening. 

``` yaml
- name: download backup from s3
    s3:
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
      bucket: "{{ bucket }}"
      object: "{{ restore_object }}"
      dest: "{{ restore_tmp_dir }}/{{ restore_file }}"
      overwrite: true
      mode: get
    tags:
      - unpack
      - s3
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
