### ISSUE TITLE
Concurrency Issue in a multi-node case with NFS drive mounted. 

### ISSUE THREAD

**Issue by pratikdhandharia** [ansible/ansible#12580]
I have a multi-node setup where I am using ansible to perform certain action. There exist a NFS mounted directory which is shared between the nodes. 

I am having unexpected behaviour when the ansible tries to modify the same file from different nodes. 

For example: Node01, Node02, Node03

File resides in: /home/demouser/test.txt  (/home/demouser is nfs mounted and shared across all the nodes.)

My ansible script is something like this: (Ansible Version 1.8.4)
- hosts: all
  tasks:
  - name: executing shell command
    shell: echo "test" >> /home/demouser/demotmp.txt | uniq > /home/demouser/demotmp_unique.txt | cp /tmp/demotmp_unique.txt /home/demouser/test.txt

Occassionally I get a scenario when the updated file is empty. My guess is, this happens as ansible tries to modify the file on all nodes at roughly the same time.

Is there a module which allows locking a file?

**Comment by jimi-c** [comment]
@pratikdhandharia no, there is currently no file locking module, and implementing one would be somewhat tricky I think as each task is a separate connection (even when using ControlPersist) so I don't think the lock would survive the session ending. I'd recommend having each inventory_host append to its own log rather than trying to append to the same file this way.

As this is not really an Ansible issue, I would recommend you move the discussion to one of the mailing lists or IRC:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
- #ansible and #ansible-devel on Freenode IRC

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcoca** [comment]
when doing something like this on a shared resource, use  `run_once: True` on the task to avoid having multiple machines trying to do the same task on the same file and avoid race conditions
