### ISSUE TITLE
Ansible service check ignores exit code for status check

### ISSUE THREAD

**Issue by leonard84** [ansible/ansible#12591]
With 22dbb65b13400db07b537cdfd38926cc03e48dfa the service status detection was changed, this change breaks the status reporting of runit's `sv status`

```
> sudo /etc/init.d/myservice status
run: myservice: (pid 30832) 259s; run: log: (pid 18809) 1973s
> echo $?
0
> sudo /etc/init.d/myservice status
down: myservice: 2s, normally up; run: log: (pid 18809) 1990s
> echo $?
3
```

The problem is that the code now checks for and subsequently ignores non-zero return codes.

```
 elif "run" in cleanout and "not" not in cleanout:
                 self.running = True
```

Since runit reports on the service and its log supervisor together this causes problems.

http://smarden.org/runit/sv.8.html
http://smarden.org/runit/faq.html#lsb

I see two possible fixes, first is to add a check for "down" in the status line before checking for "run", or allow non-zero return codes to override this heuristic.

**Comment by bcoca** [comment]
I wonder if it is just easier to use the daemontools plugin for this

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
