### ISSUE TITLE
But Report: tags=xyz not honered on - include line

### ISSUE THREAD

**Issue by fvant** [ansible/ansible#12605]
Ansible version:
2.0  pull from this morning

Environment:
Ubuntu 14

Summary:
I want to skip an include in certain conditions, so i setup the include like this (per [doc](http://docs.ansible.com/ansible/playbooks_tags.html) )

```
- include: monitoring.yml tags=host
```

When i run  ansible-playbook with --skip-tags=host  the include gets runs nonetheless.
However, if i change it to

```
- include: monitoring.yml
  tags: host
```

it skips the include.

**Comment by bcoca** [comment]
tags= on include are applied to the included tasks, not to the include itself

the second case is actually a bug in 2.0, it should do the same as the first form

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Please note, this does only apply to playbook-level includes (as used in that doc page) and not task-level includes.

Thanks!
