### ISSUE TITLE
Playbook fails while running in check mode

### ISSUE THREAD

**Issue by blelump** [ansible/ansible#12606]
Hi Interstellar travelers. I've got into an issue while playing book in `--check` mode, see below.
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible-playbook --version
ansible-playbook 1.9.3
```
##### Environment:

Ubuntu 14.04
##### Summary:

Running playbook in check mode crashes if tasks chain is:
- add ppa repository
- install whatever package from that repository.

The latter fails, because package was not found in any repo source, whereas it runs just fine without `--check` switch.
##### Steps To Reproduce:

Run `ansible-playbook -i hosts --check --diff  site.yml` with tasks:

```
- name: Add PPA tmux repository
  apt_repository: repo='ppa:pi-rho/dev'
  sudo: yes

- name: install tmux
  apt: pkg=tmux={{ubuntu.v1404.tmux_version}} update_cache=yes
  sudo: yes
```
##### Expected Results:

Ansible runs smoothly in `--check` mode even though given ppa doesn't exist in sources list. 
##### Actual Results:

```
TASK: [common | install tmux] ************************************************* 
failed: [db.example.org] => {"failed": true}
stderr: E: Version '2.0-1~ppa1~t' for 'tmux' was not found

stdout: Reading package lists...
Building dependency tree...
Reading state information...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"  --simulate install 'tmux=2.0-1~ppa1~t'' failed: E: Version '2.0-1~ppa1~t' for 'tmux' was not found


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
@blelump this is a common problem, and there are two ways it is commonly worked around:

1) Add the `always_run: yes` option on the apt repository task, so that it is run even when check mode is enabled. See http://docs.ansible.com/ansible/playbooks_checkmode.html#running-a-task-in-check-mode for more details.

2) Add a task after the apt-repository task to check whether that repo is in fact there (which would be set to `always_run: yes`), and use the registered result from that task as a conditional on the package installation task.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by blelump** [comment]
@jimi-c , thanks for clarification!
