### ISSUE TITLE
Bug report: Missing region parameter not validated in s3_bucket and env variable not used

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12607]
**Issue Type:** Bug Report

**Ansible Version:**

`ansible 2.0.0 (detached HEAD 70677b030b) last updated 2015/10/02 06:34:41 (GMT -400)`

**Environment:** AWS/RHEL 6.7

**Summary:**

Trying to create an S3 bucket with just a name (e.g.)

`- s3_bucket:
    name: "my.test.bucket"`

results in the error

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/xxx/.ansible/tmp/ansible-tmp-1443788720.85-138772044906691/s3_bucket", line 2303, in <module>
    main()
  File "/home/xxx/.ansible/tmp/ansible-tmp-1443788720.85-138772044906691/s3_bucket", line 382, in main
    create_bucket(connection, module)
  File "/home/xxx/.ansible/tmp/ansible-tmp-1443788720.85-138772044906691/s3_bucket", line 149, in create_bucket
    bucket = connection.create_bucket(name, location=region)
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 610, in create_bucket
    location + '</LocationConstraint></CreateBucketConfiguration>'
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This is fixed by explicitly specifying a `region` parameter

Note that the EC2_REGION env variable _is_ set correctly

```
[xxx@ip-xx-xxx-xx-xxx playbooks]$ echo $EC2_REGION
eu-west-1
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
