### ISSUE TITLE
ERROR: Syntax Error while loading YAML script

### ISSUE THREAD

**Issue by cazorla19** [ansible/ansible#12635]
I`m trying to run playbook. What`s inside of this playbook.

```
 ---
 - hosts:group1
   user:user1
   sudo:yes
   gather_facts:yes

tasks:
 - name: ensure update
   apt:update_cache=yes
   apt:upgrade=full
```

How I`m trying to run.

```
 sudo ansible-playbook -i /etc/ansible/hosts test1.yml
```

And what type of error is it.

> ERROR: Syntax Error while loading YAML script, test1.yml
> Note: The error may actually appear before this position: line 7, column 6
> tasks:
>        ^

Maybe someone had similar problem. Please, help me to recognize, where is the trouble lies.

**Comment by jimi-c** [comment]
Hi @cazorla19, you cannot double-stack actions like that. You need to have individual tasks, as follows (you also need a space after the `:` following apt):

<pre>
tasks:
 - name: update cache
   apt: update_cache=yes
 - name: ensure update
   apt: upgrade=full
</pre>

However, in this case you can actually combine these:

<pre>
 - name: ensure update
   apt: upgrade=full update_cache=yes
</pre>

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
