### ISSUE TITLE
Ansible does not override ssh user in .ssh/config

### ISSUE THREAD

**Issue by Fullmetal8ender** [ansible/ansible#12643]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.3
##### Environment:

Linux Mint 17.2 Rafaela
##### Summary:

If in my .ssh/config I set user then ansible allways connect with that username, not specified in ansible.cfg or by -u option
##### Steps To Reproduce:

in .ssh/config set
Host *
User qweqwe
and run ansible -u root  -m ping
##### Expected Results:

Ansible connect as root user
##### Actual Results:

Ansible connect as qweqwe user

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by bcoca** [comment]
are you running ansible as root?

**Comment by Fullmetal8ender** [comment]
No, as non-priviledged user

**Comment by alikins** [comment]
This seems to work now with devel (e70bc06ea102ae3ce364a021f73758e226736d8b)

.ssh/config stanza 
``` 
HOST rhsm_swoop.g.a
    User rhsm
```

inventory file 'hosts'
```
rhsm@swoop ansible_host=rhsm_swoop.g.a
```

output from 'ansible' without a '-u'

```
[fedora-25:ansible (devel % u=)]$ ansible -i hosts -vvv rhsm@swoop   -m shell -a "id" 
Using /home/adrian/ansible/ansible.cfg as config file
META: ran handlers
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<rhsm_swoop.g.a> ESTABLISH SSH CONNECTION FOR USER: None
<rhsm_swoop.g.a> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 rhsm_swoop.g.a '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<rhsm_swoop.g.a> ESTABLISH SSH CONNECTION FOR USER: None
<rhsm_swoop.g.a> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 rhsm_swoop.g.a '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367 `" && echo ansible-tmp-1485800457.64-231583554229367="` echo /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367 `" ) && sleep 0'"'"''
<rhsm_swoop.g.a> PUT /tmp/tmp1lmVJu TO /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367/command.py
<rhsm_swoop.g.a> SSH: EXEC sftp -b - -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 '[rhsm_swoop.g.a]'
<rhsm_swoop.g.a> ESTABLISH SSH CONNECTION FOR USER: None
<rhsm_swoop.g.a> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 rhsm_swoop.g.a '/bin/sh -c '"'"'chmod u+x /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367/ /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367/command.py && sleep 0'"'"''
<rhsm_swoop.g.a> ESTABLISH SSH CONNECTION FOR USER: None
<rhsm_swoop.g.a> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -tt rhsm_swoop.g.a '/bin/sh -c '"'"'/usr/bin/python /home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367/command.py; rm -rf "/home/rhsm/.ansible/tmp/ansible-tmp-1485800457.64-231583554229367/" > /dev/null 2>&1 && sleep 0'"'"''
rhsm@swoop | SUCCESS | rc=0 >>
uid=1001(rhsm) gid=1001(rhsm) groups=1001(rhsm) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

output with '-u root'   (it fails on ssh in this setup but I expect that. But it using 'root' for the ssh user overriding the User set in .ssh/config.

```
Using /home/adrian/ansible/ansible.cfg as config file
META: ran handlers
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<rhsm_swoop.g.a> ESTABLISH SSH CONNECTION FOR USER: root
<rhsm_swoop.g.a> SSH: EXEC ssh -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s -o ControlPath=/home/adrian/.ansible/cp/ansible-ssh-%h-%p-%r -o ConnectTimeout=2s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 rhsm_swoop.g.a '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
rhsm@swoop | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", 
    "unreachable": true
}
```

**Comment by bcoca** [comment]
Ansible just uses ssh in this case, ssh will use an applicable user from your ssh config unless you override it in the command line. 

In some previous versions (1.9 included) if you specified a user -u <user> which matched the 'current user executing Ansible' the user would be 'unset', that was fixed in >2.0 and it now behaves as you would expect (as @alikins   demonstrates above).

**Comment by sudheerdevara** [comment]
[root@server2 ~]# ssh-copy-id server3
root@server3's password:
Now try logging into the machine, with "ssh 'server3'", and check in:

  .ssh/authorized_keys

to make sure we haven't added extra keys that you weren't expecting.

[root@server2 ~]# ansible all -m ping -vvv
Using /etc/ansible/ansible.cfg as config file
META: ran handlers
Using module file /usr/lib/python2.6/site-packages/ansible/modules/system/ping.py
<server3.abc.com> ESTABLISH SSH CONNECTION FOR USER: None
<server3.abc.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c9bad9dfeb server3.abc.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/lib/python2.6/site-packages/ansible/modules/system/ping.py
<server1.abc.com> ESTABLISH SSH CONNECTION FOR USER: None
<server1.abc.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4f4a57605e server1.abc.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Enter passphrase for key '/root/.ssh/id_rsa': Enter passphrase for key '/root/.ssh/id_rsa':
<server1.abc.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
server1.abc.com | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
=========================================
can anyone help me out ......facing the same error

**Comment by sudheerdevara** [comment]
[root@server2 ~]# ssh-copy-id server3
root@server3's password:
Now try logging into the machine, with "ssh 'server3'", and check in:

  .ssh/authorized_keys

to make sure we haven't added extra keys that you weren't expecting.

[root@server2 ~]# ansible all -m ping -vvv
Using /etc/ansible/ansible.cfg as config file
META: ran handlers
Using module file /usr/lib/python2.6/site-packages/ansible/modules/system/ping.py
<server3.abc.com> ESTABLISH SSH CONNECTION FOR USER: None
<server3.abc.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/c9bad9dfeb server3.abc.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Using module file /usr/lib/python2.6/site-packages/ansible/modules/system/ping.py
<server1.abc.com> ESTABLISH SSH CONNECTION FOR USER: None
<server1.abc.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/4f4a57605e server1.abc.com '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
Enter passphrase for key '/root/.ssh/id_rsa': Enter passphrase for key '/root/.ssh/id_rsa':
<server1.abc.com> (255, '', 'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')
server1.abc.com | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
=======================
can any one help me out i ma facing the sam eissue
