### ISSUE TITLE
s3 module: error message unclear if you download multipart s3 objects and dest=/folder

### ISSUE THREAD

**Issue by volker-fr** [ansible/ansible#12646]
If you download a uploaded file with the s3 module the destination needs to be a file. If you set `dest=/folder` and the file is a multipart upload, the error message is misleading.

This task

```
- s3: bucket=mybucket object=/my/desired/key.txt dest=/usr/local/myfolder mode=get
```

will result in a unclear error

```
msg: Files uploaded with multipart of s3 are not supported with checksum, unable to compute checksum.
```

while

```
- s3: bucket=mybucket object=/my/desired/key.txt dest=/usr/local/myfile.txt mode=get
```

works as expected without any errors.

The core issue here is that the s3 object is a multipart upload and ansible can't handle it (see #5442 which has the same error message).

If the s3 object is a "single part" upload the error message you will get when using `dest=/folder` is obvious and will result in a `IOError: [Errno 21] Is a directory: '/folder'` output

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
