### ISSUE TITLE
Add note(s) about support of  ansible_ssh_ variables 

### ISSUE THREAD

**Issue by miabbott** [ansible/ansible#12648]
From the [front page](http://docs.ansible.com/ansible/index.html) of the Ansible doc site:

> This documentation covers the current released version of Ansible (1.9.1) and also some development version features (2.0). For recent features, we note in each section the version of Ansible where the feature was added."

After f56a6e0951af9ae68106a8f9569cc375f53d5b52, all traces of the `ansible_ssh_` variables disappeared with no mention that they are the only supported versions in pre-2.0.  That is, I cannot use `ansible_host` in 1.9.x, but `ansible_ssh_host` works as expected.

There should be a note (or many based on that commit) that users must use `ansible_ssh_` variables if they are using pre-2.0 versions of Ansible.

**Comment by agrrh** [comment]
+1

**Comment by jimi-c** [comment]
Fixed by https://github.com/ansible/ansible/pull/12688, which has been merged in.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
