### ISSUE TITLE
include+with_items don't execute included file

### ISSUE THREAD

**Issue by mbudnick** [ansible/ansible#12654]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0-0.3.beta1
  configured module search path = None
##### Ansible Configuration:

[defaults]
hostfile = /dev/null
gathering = explicit
remote_user = root
##### Environment:

running Ansible from "openSUSE 13.2 (Harlequin) (x86_64)"
managing "openSUSE 13.2 (Harlequin) (x86_64)"
##### Summary:

Include with_itmes shows include for every item but don't execute the included file.
There is no problem when executing with ansible 2.0.0-0.2.alpha2
##### Steps To Reproduce:

```
ansible-playbook -i dev test.yml
```

```

---
# file test.yml
- hosts: localhost
  gather_facts: no
  remote_user: root

  tasks:
  - include: testi.yml foo={{item}}
    with_items:
    - test1
    - test2
```

```

---
# file testi.yml
- debug: msg="hello {{foo}}"
```
##### Expected Results (2.0.0-0.2.alpha2):

```
PLAY ***************************************************************************

TASK [include foo={{item}}] ****************************************************
included: testi.yml for localhost => (item=test1)
included: testi.yml for localhost => (item=test2)

TASK [debug msg=hello {{foo}}] *************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "hello test1"
}

TASK [debug msg=hello {{foo}}] *************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "hello test2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results (2.0.0-0.3.beta1):

```
PLAY ***************************************************************************

TASK [include foo={{item}}] ****************************************************
included: testi.yml for localhost => (item=test1)
included: testi.yml for localhost => (item=test2)

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Bisected to here:

<pre>
commit 4c9f58a1524454e0b8a8ee4e7a4ab6c31cacbd59
Author: Brian Coca <brian.coca+git@gmail.com>
Date:   Fri Oct 2 09:09:40 2015 -0400
    added no_log censoring to item output
    should be last commit that fixes #12214
</pre>

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by mbudnick** [comment]
Problem is resolved for me.
Thanks for the immediate bugfix.
