### ISSUE TITLE
pip module's chdir option does not expand ~/tilde correctly

### ISSUE THREAD

**Issue by ktaragorn** [ansible/ansible#12658]
If i give `chdir=/home/ubuntu/app` it works but giving `chdir=~/app` doesnt seem to work.

After some digging it is because of the code joining this option with the temp directory

```
        this_dir = tempfile.gettempdir()
        if chdir:
            this_dir = os.path.join(this_dir, chdir)
```

From simple testing, this method doesnt work for ~ but it works for absolute paths

```
In [8]: os.path.join("/tmp", "~/bin")
Out[8]: '/tmp/~/bin'

In [9]: os.path.join("/tmp", "/bin")
Out[9]: '/bin'
```

**Comment by ktaragorn** [comment]
This probably can be fixed instead of documenting.. I dont see why anybody would like to `chdir` relative to the temp directory in `pip`.

**Comment by ktaragorn** [comment]
From [stackoverflow](http://stackoverflow.com/a/2057072/1520364) the best way to keep old behavior but fix case of tilde might be to do below

```
In [12]: os.path.join("/tmp", os.path.expanduser("~/bin"))
Out[12]: '/Users/karthikt/bin'
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
