### ISSUE TITLE
s3 module: ListBucket permission required while GetObject permission should be sufficient

### ISSUE THREAD

**Issue by volker-fr** [ansible/ansible#12652]
I have an EC2 instance with an instance profile. This instance profile allows me to download files from an S3 bucket from another AWS account.

The s3 module is not able to download the file from a external bucket as it should. Error message is

```
       msg: Target bucket cannot be found
```

Downloading the file with

```
 aws s3 cp s3://bucket-in-other-aws-account/folder/file /tmp
```

works without any problems.

**Comment by volker-fr** [comment]
The problem here seems to be that the by the instance profile used permissions are really tight and the checks of the s3 module are too comprehensive. First you check if a bucket exists while it would be sufficient to just try to download the provided file+bucket. As I mentioned before, the `aws-cli` can download the files without any problems since the permissions are sufficient enough.

ListBucket is required, while GetObject only would be sufficient.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
