### ISSUE TITLE
Type error concatenating string literal with lookup

### ISSUE THREAD

**Issue by thyming** [ansible/ansible#12650]
Issue Type:  Bug Report

Ansible Version:

ansible 2.0.0 (devel 5ae74f7d38) last updated 2015/10/06 13:09:43 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 13:10:23 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 13:10:24 (GMT -400)

Ansible Configuration:

None

Environment:

N/A

Summary:

Concatenating a string literal followed by another file lookup causes a type error, but not the other way around:
`ERROR! an unexpected type error occurred. Error was coercing to Unicode: need string or buffer, UnsafeProxy(unicode) found`

(I haven't looked into other lookup plugins, but imagine the problem is the same since the code at https://github.com/ansible/ansible/blob/621575681a21448cfd2308809600e6d9554e9b71/lib/ansible/template/__init__.py#L377-L379 looks like it applies for all lookup plugins)

Note that this doesn't happen if the jinja2 join filter is used, so in simple cases that's a reasonable workaround.

Steps To Reproduce:

Inventory: 

```
localhost ansible_connection=local
```

Playbook:

``` ansible
- hosts: localhost
  tasks:
  - debug: var="{{ 'abc' + lookup('file', 'test.txt')  }}"
```

test.txt:

```
asdf
```

Expected Results:

In ansible 1.9.\* at least, this concatenates the text from the files with the intermediate string literal without any problems.

Actual Results:

Type error crashes the playbook run.

**Comment by jimi-c** [comment]
Should be fixed by cd2cb178aeb799efe4aba36f93d48c95f6da3b61, just waiting for a little burn-in due to the major change involved in that commit.

**Comment by thyming** [comment]
Fixed the problem for me, thanks.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
