### ISSUE TITLE
tilde '~' is not expanded correctly in v2

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12667]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 2.0.0 (devel 9e364c2) last updated 2015/10/07 10:29:32 (GMT +300)
lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/07 10:29:43 (GMT +300)
lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/07 10:29:53 (GMT +300)
config file = /home/albert/ansible/ansible.cfg
configured module search path = None
##### Environment:

Arch linux as control machine
Centos as remote machine
##### Summary:

Tilde `~` is not being expanded in `remote_tmp` configuration in ansible.cfg
##### Steps To Reproduce:

Consider our working dir is at /home/name/ansible

Put a custom configuration in ansible.cfg using a tilde:

```
remote_tmp     = ~/.ansible/tmp
```
##### Expected Results:

tmp files dir should be `/home/name/.ansible/tmp`
##### Actual Results:

tmp files dir is `/home/name/ansible/~/.ansible/tmp`, but in the log we would see this:

```
localhost EXEC mkdir -p "~/ansible/tmp/ansible-tmp-1444222355.83-101651715729191" && echo "~/ansible/tmp/ansible-tmp-1444222355.83-101651715729191"
```

So the output is not correct as well

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
