### ISSUE TITLE
ansible_python_interpreter is not being honored in v2

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12666]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 2.0.0 (devel 9e364c2eb5) last updated 2015/10/07 10:29:32 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/07 10:29:43 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/07 10:29:53 (GMT +300)
  config file = /home/albert/ansible/ansible.cfg
  configured module search path = None
##### Environment:

Arch linux as control machine
Centos as remote machine
##### Summary:

Setting ansible_python_interpreter is not beind honored
##### Steps To Reproduce:

If you're using a control machine with python 3 as default, set `ansible_python_interpreter=/usr/bin/python2` on localhost

Run the following playbook with -vvv:

``` yaml

---
- hosts: serbtest
  tasks:
    - shell: "whoami"
      delegate_to: localhost
```
##### Expected Results:

The playbook should run fine
##### Actual Results:

Playbook fails with the following error:

```
fatal: [serbtest -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: b'_raw_params'"}
```

And you can see that it tries to use `/usr/bin/python` as executable, and not `/usr/bin/python2` as we requested:

```
localhost EXEC LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /home/albert/.ansible/tmp/ansible-tmp-1444228422.44-64669274128314/command; rm -rf "/home/albert/.ansible/tmp/ansible-tmp-1444228422.44-64669274128314/" > /dev/null 2>&1
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
