### ISSUE TITLE
Add ability to rate limit data transfer

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12684]
Some of my playbooks require transferring large files to a large number of hosts. I've come across 2 issues related to bandwidth. First, its fairly easy to max out my internet connection. The second is on smaller EC2 instances network performance can become an issue.

I'd like to know if we can get the equivalent of the sftp/scp -l (limit) flag applied both globally (via ansible.cfg or command line option) and as an option for individual tasks (like unarchive).

**Comment by bcoca** [comment]
already provided in 2.0 (devel) via 3ad9b4cba62707777c3a144677e12ccd913c79a8

**Comment by jimi-c** [comment]
Going back looking at older issues, and it appears that this is resolved by the additional ssh argument fields provided in 2.0+

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!. As such, we'll go ahead and close this now.
