### ISSUE TITLE
CallbackBase.runner_on_skipped not called anymore

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#12683]
In `CallbackBase` the v1-method `runner_on_skipped` is expected to be called (an has been called in previous versions) from the v2-method `v2_runner_on_skipped`.

But since commit 4c9f58a15 the v1-method `runner_on_skipped` is not called anymore.

**Comment by bitmensch** [comment]
@bcoca You probably have an idea about this!?

**Comment by bcoca** [comment]
i changed how ti is called, but not that it is called or not

```
-            self.runner_on_skipped(host, item)
+            self.runner_on_skipped(host, self._get_item(getattr(result._result,'results',{})))
```

**Comment by bitmensch** [comment]
I investigated this a little bit more, and wrapped the line

```
self.runner_on_skipped(host, self._get_item(getattr(result._result,'results',{})))
```

in a try-except-block.

Given a play like the following:

```
- hosts: host1:host2
  tasks:
    - name: task1
      ping:
      when: inventory_hostname != 'host2'
```

it raises a `KeyError` exception. `item` key could not be found.

So, it seems this leads to the situation where the v1-method `runner_on_skipped` is not called.

**Comment by bcoca** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
