### ISSUE TITLE
Ansible - change remote_tmp from config file for one task only

### ISSUE THREAD

**Issue by Robby123** [ansible/ansible#12692]

**Comment by jimi-c** [comment]
@Robby123 is this a feature request or a bug?

**Comment by bratzelk** [comment]
@Robby123 @jimi-c What was the outcome of this? Is this possible or is there a known workaround?

Thanks!

**Comment by jimi-c** [comment]
@bratzelk if I understand the issue correctly, I believe there is no workaround - the remote temp directory is set for the entire run and isn't changed per-task.

**Comment by gmanfunky** [comment]
I found myself wanting to do this when running ansible inside of virtualbox with a windows mount. 

I am able to work around some other file copy tasks by setting `remote_tmp` , but when trying to use `local_action: wait_for ...`, ansible is trying to use the `remote_tmp` value, which causes problems due to the way ansible uses python for file copies.

I don't have a workaround yet.

**Comment by nicklinghj** [comment]
I hope there is new feature on the next release include Ansible tower -- remote_tmp can be set for individual host,  group,  job , task also for remote_user
