### ISSUE TITLE
[v2] Ansible does not load dynamic vars_files

### ISSUE THREAD

**Issue by justingood** [ansible/ansible#12711]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0
  config file = 
  configured module search path = None
```
##### Ansible Configuration:

```
[defaults]
hostfile     = ./hosts
```
##### Summary:

Dynamic vars_files are not loaded using Ansible v2.0.0 beta.
##### Steps To Reproduce:

hosts/local:

```
localhost ansible_connection=local
```

test_playbook.yml:

```
- name: test ansible 2.0 beta
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ filename | mandatory }}.yml"
  tasks:
  - name: display variable
    debug: var=var1
```

testvar.yml:

```
var1: "success!"
```
##### Expected Results:

```
# ansible-playbook test_playbook.yml -e filename=testvar

PLAY [test ansible 2.0 beta] ************************************************** 

TASK: [display variable] ****************************************************** 
ok: [localhost] => {
    "var": {
        "var1": "success!"
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
##### Actual Results:

Executing the playbook results in the following:

```
# ansible-playbook test_playbook.yml -e filename=testvar
ERROR! Mandatory variable not defined.
```

If the `mandatory` filter is removed, the values in the file are still not loaded correctly:

```
# ansible-playbook test_playbook.yml -e filename=testvar

PLAY [test ansible 2.0 beta] ***************************************************

TASK [display variable] ********************************************************
ok: [localhost] => {
    "changed": false, 
    "var1": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

This previously worked without problems in **Ansible v1.9.3-1**

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
