### ISSUE TITLE
win_copy: Does not copy a file if it contains a #!powershell shebang line as 1st line

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible#12737]
Hi,

For some reason when I try to upload a text file that starts like this:

``` powershell
#!powershell

...
```

The file is not present afterwards on the remote system. However if I insert some other text on the 1st line of the text file:

``` powershell
foo
#!powershell

...
```

Then it will be copied successfully. This seems like a bug of some sorts.

Target System: win10 / powershell 5.0
Ansible version: 1.9.3

**Comment by cchurch** [comment]
There is a special case when uploading a file where we add a `.ps1` extension if not present, but only if the file starts with `#powershell` (https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/winrm.py#L234).  This was done to ensure modules always have the `.ps1` extension.

I'd expect that your file **is** getting uploaded, but the `.ps1` extension is being added.

**Comment by dreamcat4** [comment]
AFAICT no it isn't. I do `ls` on the target machine and no file of any similar name is being listed there. The folder is empty.

[EDIT] I mean... the file _is_ being uploaded sure. But only to the temp folder with the temp name. Then it's being deleted at the end of the task. The copy to dest isn't happening.

**Comment by nitzmahone** [comment]
Should be fixed by #13381

**Comment by nitzmahone** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by dreamcat4** [comment]
Thanks
