### ISSUE TITLE
What's the current version of http://docs.ansible.com/ansible/ ?

### ISSUE THREAD

**Issue by adoyle-h** [ansible/ansible#12761]
Can you specify the current version on the footer of document site?

**Comment by jimi-c** [comment]
Hi @adoyle-h, the docs track devel currently. In the near future (after 2.0 comes out), we are planning on keeping a stable/devel version of the docs, to limit confusion on new features being added.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
