### ISSUE TITLE
v1.9->2: templated delegate_to with undefined variable fails even if task is skipped on when: undefined

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#12774]
It seems in 2.0 (174ecb843c) a `delegate_to:` gets templated, even when the task would be skipped because the variable used to set the delegate is undefined. This does not happen in 1.9.

Following task snippet reproduces this
(source: https://github.com/bennojoy/mysql/blob/master/tasks/main.yml#L85)

```
139 - name: Get the current master servers replication status                       
140   mysql_replication:                                                            
141     mode:   getmaster                                                           
142   delegate_to: "{{ mysql_repl_master }}"                                        
143   register: repl_stat                                                           
144   when: slave|failed and mysql_repl_role == 'slave' and mysql_repl_master is defined
```

This works fine in 1.9, and used to work in 2.0 (at least until some months/weeks ago).

```
TASK: [mysql | Get the current master servers replication status] ****** 
skipping: [hydargos]
```

Testing with 174ecb843c, this fails:

```
TASK [mysql : Get the current master servers replication status] ********
fatal: [hydargos -> {{ mysql_repl_master }}]: FAILED! => {"failed": true, "msg": "ERROR! 'mysql_repl_master' is undefined"}
```

**Comment by orderedchaosdev** [comment]
I noticed this as well and my work around was a conditional include of a that group of tasks. Just in case you needed to get this up and working.

**Comment by abadger** [comment]
First bad commit: 1f5584aa5b9d1142e67fed209bbeea1ca99fc307

**Comment by abadger** [comment]
If anyone would like to test #12968 that would be great.  It seems to solve this problem in my testing but I'm not sure if it doesn't create other problems.  Wider use and review would be great.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
