### ISSUE TITLE
When using cron_file with cron module new line is not inserted after job entry

### ISSUE THREAD

**Issue by steven-vogogo** [ansible/ansible#12794]
Ansible version: (OSX, 1.9.0.1)
Environment: (source) OSX,amazon-linux (destination) amazon-linux

When using cron module the job entered into the cron.d file is missing a newline at end of file (cron fails to run the job file is there is no new line at the end of file).

Example:

```
- name: cron run nightly
  cron: name="cron nightly" hour=0 minute=0 user=root job="/bin/echo 'nightly cron job has run' | /usr/bin/logger -t cron_nightly" cron_file=nightly
```

Result: /etc/cron.d/nightly

```
#Ansible: cron nightly
0 0 * * * root /bin/echo 'nightly cron job has run' | /usr/bin/logger -t cron_nightly
~ (eof no new line)
```

Workaround:
If I add \n to the job it will work

```
- name: cron run nightly
  cron: name="cron nightly" hour=0 minute=0 user=root job="/bin/echo 'nightly cron job has run' | /usr/bin/logger -t cron_nightly __&& \n__" cron_file=nightly
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
