### ISSUE TITLE
Can't send JSON code using uri module

### ISSUE THREAD

**Issue by sharwariphadnis** [ansible/ansible#12818]
I am trying to send a JSON payload using uri module through body parameter. The variables {{ network-name }} and and {{ IP1 }} are imported from config.yml.

I have defined body in vars. The json code which I am trying to print is getting created properly using (debug: var={{ body | to_json}}). But, the output which I am redirecting to the dest file is showing errors. What could be the reason that the JSON payload is not getting sent at the destination api.

Here's the ansible playbook:

---
- hosts: localhost
  connection: local
  
  vars_files:
  - config.yml
  
  vars:
      body:
        id: 100
        network:
          name: "{{ network-name }}"
          net_list:
            - link_id: 1
            - type: abc
        vlan: "10"
        profile: switch
  
  tasks:
  - debug: var="{{ body | to_json }}"
  - name: Run POST command
    uri:
      url: "https://{{ IP1 }}/url/to/dest/api"
      method: POST
      body: "{{ body | to_json }}"
      user: "abc"
      password: "xyz"
      HEADER_Content-Type: "application/json"
      force_basic_auth: yes
      return_content: yes
      dest: /url/to/dest/file

**Comment by jimi-c** [comment]
Hi @sharwariphadnis, Ansible 2.0 (devel branch) introduces the `body_format: json` option, which fixes this bug. You can grab the module from github and replace your version of it to get this new feature ahead of the 2.0 release if you like.

Per our normal policy, we close issues on Github when they are resolved in the devel branch, so we will be closing this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
