### ISSUE TITLE
os_server: unsupported parameter for module: public_ip - documentation specifies it

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#12812]
Not sure whether it is a bug or a documentation remnant, so excuse a clearer issue.

http://docs.ansible.com/ansible/os_server_module.html lists:
`public_ip - Ensure instance has public ip however the cloud wants to do that`

Running with this option specified yields:
`fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: public_ip"}`

I am not sure whether this is intended to map `_nova_compute.py` to `os_server.py` in a backwards compatibility fashion or whether the documentation simply needs to remove this option.

Ansible version: 
ansible 2.0.0 (devel 89b0c3f6c4) last updated 2015/10/16 11:38:00 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 84b1a1a2b7) last updated 2015/10/16 11:38:20 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8ce3104bc5) last updated 2015/10/16 11:38:24 (GMT +200)

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
