### ISSUE TITLE
win_iis_website: failed when delete ('absent') web site 

### ISSUE THREAD

**Issue by driller23** [ansible/ansible#12811]
Hi All,

On Ansible 2.0 at win_iis_website module there is a bug when running absent web site 

the command:

```
  - name: delete default web site 
    win_iis_website:
      name: "Default Web Site"
      state: absent
    tags: default
```

and the exception i got:

```
An exception occurred during task execution. The full traceback is:
At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1445169915.15-186526999817978\win_iis_website.ps1:405 char:1
+ $result.site = New-Object psobject @{
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [172.26.2.116]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Name' cannot be found on this object. Verify that the property exists."}

PLAY RECAP *********************************************************************
172.26.2.116               : ok=1    changed=0    unreachable=0    failed=1   
```

so i have copied the win_iis_website to my local library and changed several things:
1. add new function:

```
Function Echo-Json($obj, $message = $null)
{
    # If we weren't given 2 args, and the only arg was a string, create a new
    # psobject and use the arg as the failure message
    If ($message -eq $null -and $obj.GetType().Name -eq "String")
    {
        $message = $obj
        $obj = New-Object psobject
    }
    # If the first args is undefined or not an object, make it an object
    ElseIf (-not $obj -or -not $obj.GetType -or $obj.GetType().Name -ne "PSCustomObject")
    {
        $obj = New-Object psobject
    }

    Set-Attr $obj "msg" $message
    echo $obj | ConvertTo-Json -Compress -Depth 99
    Exit 0
}
```

and at the end of the powershell:

```
$site = Get-Website | Where { $_.Name -eq $name }
Try {
  $result.site = New-Object psobject @{
    Name = $site.Name
    ID = $site.ID
    State = $site.State
    PhysicalPath = $site.PhysicalPath
    ApplicationPool = $site.applicationPool
    Bindings = @($site.Bindings.Collection | ForEach-Object { $_.BindingInformation })
  }
}
Catch {
    Echo-Json "Web site: '$name' does not exist"
}
```

PS: i think the function should be part of powershell.ps1 module util

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
