### ISSUE TITLE
Delobj

### ISSUE THREAD

**Issue by luhkevin** [ansible/ansible#12810]
The documentation says that "delobj" is still a valid mode for the s3 module, but I just got this error:

msg: value of mode must be one of: get,put,delete,create,geturl,getstr, got: delobj

I'm on ansible version 1.9.4

**Comment by luhkevin** [comment]
Okay, so tried using the "delete" mode on a dummy-object...it deleted the entire bucket instead.

Is there currently a way to delete objects? This is somewhat urgent if not...

To reproduce, I just had this in a playbook:

`- name: Dummy delete`
`s3:    bucket=dummy-bucket object="/dummy_folder"    mode=delete    aws_access_key="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"    aws_secret_key="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"``

And like I said above, delobj didn't work. I used pretty much the same commands for that:

`- name: Dummy delete`
`s3:    bucket=dummy-bucket object="/dummy_folder"    mode=delobj    aws_access_key="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"    aws_secret_key="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"``

**Comment by mscherer** [comment]
Since this is a module issue, it should be filled against https://github.com/ansible/ansible-module-core rather than this repository. Can you reopen the bug there ?

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
