### ISSUE TITLE
ansible-vault decryptes unrelated files

### ISSUE THREAD

**Issue by pujan14** [ansible/ansible#12824]
ansible-vault decrypts all host and group variables included in an inventory. There are two problems with that.
1) This process is serialized so it takes long time.
2) There is no option to disable this behavior so it would only decrypt files related to hosts/groups used in playbook and not all of them.

**Comment by jimi-c** [comment]
@pujan14 all files are decrypted because there is no way to tell where the source of a variable is otherwise.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by pujan14** [comment]
@jimi-c Is it not possible that you only decrypt variables of hosts and groups that are specified in playbook? If it doesn't make sense to do it always maybe with a option which once enabled would only read host_vars and group_vars of hosts specified.
This is a big issue for me as my inventory is continuously growing this results in continuously increasing start time for ansible. This seriously restricts scalability.

**Comment by jimi-c** [comment]
@pujan14 in which version of Ansible are you seeing this? In devel (2.0), host/group vars files and vars_files are only read if they are needed.

**Comment by pujan14** [comment]
I am using 1.9.4
I haven't moved to 2.0

**Comment by jimi-c** [comment]
Ok, in that case this should already be solved in the latest devel branch.

Thanks!
