### ISSUE TITLE
[v2] template with force=no reports changed in check mode

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#12844]
##### Issue Type:
- Bug Report
##### Ansible Version:
- 1.9.4
- 2.0.0 (devel b46ce47a84) last updated 2015/10/20 20:10:50 (GMT +200)
##### Summary:

In live mode a task with template and force=no would not overwrite an existing file and reports ok, but when running in check_mode it reports changed.
##### Steps To Reproduce:

```
$ cat test.yml 

---
- hosts: localhost
  tasks:
  - template: src=/etc/hosts dest=/etc/hostname force=no
```

```
ansible-playbook test.yml      

PLAY ***************************************************************************

TASK [template dest=/etc/hostname src=/etc/hosts force=no] *********************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

```
$  ansible-playbook test.yml --check

PLAY ***************************************************************************

TASK [template dest=/etc/hostname src=/etc/hosts force=no] *********************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0  
```
##### Expected Results:

reports ok in both cases.
##### Actual Results:

not reports ok in both cases.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
