### ISSUE TITLE
make sdist  xargs: illegal option -- r Error

### ISSUE THREAD

**Issue by saeeda** [ansible/ansible#12845]
After Ansible v2.0.0-0.3.beta1 is checked out. Trying to build ansible-2.0.0.tar.gz fails.

> ansible --version 
> ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/20 16:34:41 (GMT -400)
>   lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/20 16:34:57 (GMT -400)
>   lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/20 16:35:01 (GMT -400)
>   config file = 
>   configured module search path = None
> (venv)[username@hostsystem:~/ansible]$ make sdist 
> Cleaning up distutils stuff
> rm -rf build
> rm -rf dist
> rm -rf lib/ansible.egg-info/
> Cleaning up byte compiled python stuff
> find . -type f -regex "._.py[co]$" -delete
> Cleaning up editor backup files
> find . -type f  ( -name "_~" -or -name "#_" ) |grep -v test/units/inventory_test_data/group_vars/noparse/all.yml~ |xargs -n 1024 -r rm
> xargs: illegal option -- r
> usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
>              [-L number] [-n number [-x]] [-P maxprocs] [-s size]
>              [utility [argument ...]]
> make: *_\* [clean] Error 1

**Comment by abadger** [comment]
Thanks for reporting this!  Looks like -r is a GNU specific extension to xargs.  Hopefully find -path is more portable.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
