### ISSUE TITLE
'invocation' to use from callback plugin is missing in a result.

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#12869]
Issue Type:
  Bug Report or Feature Idea
##### Ansible Version:

  ansible 2.0.0  (09899b7c438bb029bd5715792951d646a302a5de,  latest head)
##### Ansible Configuration:

  Nothing special
##### Environment:

  Mac
##### Summary:

  `'invocation'` is not produced in a callback plugin, `result._result`

  Because, I want to log a module name by using callback plugin. `'invocation'` is always included in a result at v1, but it seems v2 not include it. (I want to run [datadog-callback](https://github.com/DataDog/ansible-datadog-callback) on v2)

  I found @jimi-c said `"I believe invocation was always in the output"` at issue #12787. Could you add invocation into a result?
##### Steps To Reproduce:

  prepare callback module.

```
    def v2_runner_on_failed(self, result, ignore_errors=False):
        print('invocation' in result._result)
```
##### Expected Results:

True
##### Actual Results:

False

**Comment by abadger** [comment]
Working on this now.

**Comment by abadger** [comment]
I think this branch should fix the issue for you now: https://github.com/ansible/ansible/commits/invocation-fix

I've discovered some ways in which this behaving differently depending on which module is being invoked, though, so I'm going to be doing some more work on this before it gets merged to devel.

**Comment by abadger** [comment]
Okay, the above set of commits should fix invocation's presence for all modules!  Test it out and open a new bug if it doesn't work for some reason.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by shirou** [comment]
I confirmed my callback plugin works now. Thank you so much!

**Comment by larsks** [comment]
Commit 2e87c1f breaks the `ansible` command, which now says:

```
$ ansible localhost -m ping
 [WARNING]: Error when using <bound method CallbackModule.v2_runner_on_ok of
</home/lars/src/ansible/lib/ansible/plugins/callback/minimal.CallbackModule object at 0x7fa2ca32df10>>:
'TaskResult' object has no attribute 'copy'
```

And indeed, the `TaskResult` object has no `copy` method.  This does _not_ seem to impact `ansible-playbook`.
