### ISSUE TITLE
Playbooks In Subdirectories

### ISSUE THREAD

**Issue by inadarei** [ansible/ansible#12862]
The recommended directory layout from the documentation (http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout) indicates putting all playbooks at the top level, alongside inventory files. This can get really messy in a large project.

We put all configuration in roles. Playbooks are basically mappings of a set of roles to a set of inventory. I believe that is best-practice to make roles reusable.

In earlier Ansible versions (~ year ago?) it was possible to put playbooks in a subfolder and run them from the top folder (where inventory files are). Somewhere along the line that became impossible, because playbooks in a subfolder cannot see roles and group var files, in such case.

Can we please get support for playbooks in subfolder? Why is that not a recommended best-practice in the documentation?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, there has been no recent change to how playbooks find group/host vars recently. The requirement has been for a long time that they either are adjacent to inventory or adjacent to plays.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by inadarei** [comment]
Thank you, Brian.

Sorry for using the wrong channel of communication. I wasn't sure if this was a bug/side-affect, since it used to work in earlier versions. Will move the discussion to the list.

Cheers

**Comment by ssbarnea** [comment]
This bug should be reopen and lack of documentation is a bug too. Current documentation does not recommend any structure for keeping playbooks and putting all of them in the root does not scale at all. 

We all have lots and lots of playbooks that are used like on-demand scripts and we need to be able to store them somewhere, other then the root directory.

**Comment by inadarei** [comment]
Speaking of documentation, since opening this issue, we have been able to figure-out what is going on, as well as: how to fix it.

Bottomline (and ignoring history of when behavior changed, since it's been a while):
1. By default Ansible seems to be looking for roles folder under /etc/ansible/roles
2. If you want your custom Ansible workspace (e.g. under ~/projects/myawesomestartup) to properly find things in "roles" while your plays are under a subfolder, you need to do the following:
   1. Make sure you have ansibfle.cfg file under your workspace (e.g. ~/projects/myawesomestartup/ansible.cfg)
   2. Under that file in [defaults] section add the following line:
      
      ```
      [defaults]
      roles_path = roles
      ```

**Comment by philfry** [comment]
Unfortunately, that's not sufficient.
You'll also need to specify `library = library` in `[defaults]` when using own modules.

But still ansible won't find `host_vars` and `group_vars` when having the playbooks in a subdir and using the best-practice-structure:

- playbook is in toplevel dir
```
$ strace -e stat -ff ansible-playbook myplaybook.yml
stat("/path/to/ansible/group_vars") <- correct place to look
stat("/path/to/ansible/host_vars") <- correct place to look
stat("/path/to/ansible/inventory/group_vars")
stat("/path/to/ansible/inventory/host_vars")
```
- playbook is in subdir
```
$ strace -e stat -ff ansible-playbook playbooks/myplaybook.yml
stat("/path/to/ansible/playbooks/group_vars"...)
stat("/path/to/ansible/playbooks/host_vars"...)
stat("/path/to/ansible/inventory/group_vars"...)
stat("/path/to/ansible/inventory/host_vars"...)
```

**Comment by flickerfly** [comment]
Has anyone worked out the problems that @philfry pointed out above? Seems like we have part of a solution. It'd be great if I could bring improved organization to playbooks without losing functionality.

**Comment by joequery** [comment]
Our playbooks are becoming so large that invoking specific roles are taking a long time to run just from skipping over all the roles that don't match the specified tags. Being able to create a playbooks subdirectory and split up the playbooks would be much preferrable than littering the root project directory.

**Comment by opoplawski** [comment]
host_vars/group_vars are looked for relative to the playbook directory and the inventory directory.  So you simply need to make sure they are in one of those locations.  You can also make use of symbolic links.

**Comment by joequery** [comment]
I'd prefer to not have to version symlinks.

Edit: I want to clarify that Ansible has absolutely improved quality of life where I work, so I appreciate all the work of the contributors. I just wanted to affirm the opinions of other people in this thread.

**Comment by mrmunch** [comment]
Any update on this?

**Comment by percygrunwald** [comment]
I've decided to drop my two cents in here as well since I have spent the past hour trawling Google for advice about this issue and found nothing that I consider to be an acceptable solution.

In my opinion, Ansible's behavior when moving playbooks into a subdirectory (but still running them from the root directory) is unintuitive and doesn't seem to match how other programs work. I could enumerate all of the things that stop working, but I think it's sufficient to say that the expected behavior for the majority of people would be as follows:

Given that my directory structure is exactly the same as the layout shown in http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout, and I am running my scripts from the Ansible root directory like:

```
cd /path/to/project/ansible
ansible-playbook site.yml
```

If I copy `site.yml` into any subdirectory of the Ansible root folder:

```
mkdir -p playbooks/subdir
cp site.yml playbooks
cp site.yml playbook/subdir
```

Then the following commands should all be **identical**:

```
ansible-playbook site.yml
ansible-playbook playbooks/site.yml
ansible-playbook playbooks/subdir/site.yml
```

In the 2+ years I have been using Ansible, I haven't encountered a situation where the current default behavior would have been beneficial compared to the behavior I outlined above. I feel like most people run their Ansible scripts from the Ansible root directory and mentally treat that as the directory that Ansible should be searching for vars/roles/inventory/etc, _especially_ since the `ansible.cfg` is located there.

It would be really great if there was a setting that would make Ansible behave in the way I have outlined. I would suggest a boolean variable called something like `lock_working_dir` or `lock_base_dir` that would "lock" Ansible to the `pwd` when searching for vars/roles/inventory/etc.

This would be a huge boon for organization. I'm happy to have a go at this if this is something that would get considered for PR.

**Comment by Sephtex** [comment]
I was looking for an easy way to divide the playbooks into categories and bumped against this issue which is exactly what I actually want. I want to make a better overview of the project we have by categorizing all the playbooks into a directory which is meant for the same thing.

Those playbooks might be categorized so you can find a playbook faster by the directory they are located in, eg.:

abstract ansible base structure:
```
ansible.cfg
inventory.sh
roles/.
library/.
templates/.
files/.
group_vars/.
playbooks/local-lxd/ubuntu16.yml
playbooks/local-lxd/ubuntu18.yml
playbooks/farm/setup.yml
playbooks/farm/patch.yml
```

The playbooks in the "playbooks" directory are just failing with the following error:
```
/home/user/ANSIBLE_LOCATION_PATH/ansible/playbooks/local-xld-env/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/ANSIBLE_LOCATION_PATH/ansible/playbooks/local-xld-env
```
It's clear that it searches everywhere except the current directory where ansible-playbook is executed. Actually it should be the first directory to look for those things and all default files/directories instead of configuring roles_path to tell the default directories again etc.

This all works with adding the default value for roles to the ansible.cfg:
```
[defaults]
roles_path = roles
```
And like @philfry also mentioned: you need to specify the location of the library in order to get it working is the same problem.
I suppose for AWX it wouldn't be a problem when you put everything in /etc/ansible directory. But when defining another directory (like you do locally) and executing ansible-playbook from that directory, it gives the unexpected behaviour as you would expect that all files are read from that current directory like it reads the ansible.cfg...

So if it reads the ansible.cfg on that current location, it can read all other required paths/files from that same location right? It actually makes no sense that it reads the configuration file but ignores all the rest. The cool thing I found while getting the above error about the location is that when you have a playbook and a large project you can still put the very specific roles(+/files/templates/..?) next to the playbook if they are only for the specific playbooks:
```
roles/.
library/.
templates/.
files/.
playbooks/local-lxd/ubuntu16.yml
playbooks/local-lxd/ubuntu18.yml
playbooks/local-lxd/roles/...
```

If the current directory where you execute ansible-playbook would be threaded as the base location for everything, you'll be able to structure the ansible directory even better wherever you want your ansible source tree to be. So by adding the current location as one of the source locations where the ansible-playbook binary is executed, then it will open a lot of extra possibilities for everyone with big ansible projects.
So as @pgrunwald mentioned, then the execution of the playbooks wherever they are located should give the same result.

**Comment by BarbzYHOOL** [comment]
this seems so simple that when you find out it bugs (for the 3rd time) you realize that you wasted several precious hours on that for 0 reason :(

please, add this

**Comment by lgg42** [comment]
I also wanted this behavior to be possible since like you said, the root becomes messy in a larger project, I mean, we all don't the get the chance to have a super tidy and well defined infra like (webtier.yml, dbtier.yml, lbtier.yml, backtier.yml, you get me...)
My main concern was group_vars and hosts_vars, so I opted for moving these folders inside inventories/environment/{group_vars,hosts_vars}

That way I can still make use of those variables whilst placing my playbooks inside roorfolder/playbooks.

I still have to try subfoders like playbooks/lb, playbooks/apps, playbooks/os etc..., I ignore yet if this way, my *_vars will work, which I assume they will.

**Comment by pgassmann** [comment]
Why is this issue closed? Can we reopen this issue? @bcoca This is a valid feature request

**Comment by pgassmann** [comment]
https://github.com/ansible/ansible/issues/15061#issuecomment-202144804 is a valid argument against it.

**Comment by gbritton** [comment]
I've also wanted this sort of directory layout.  A project with many "top level" plays can become quickly complex.  This style of layout could be constructed if there were a way to provide a play-relative ansible.cfg (which would in-turn, need a way to expand the dirname of the play).  This seems related to (but not the same as) what was mentioned in ansible/proposals#73

Perhaps though, something that reaches that level of complexity should better be solved with an entrypoint role and arguments, though I haven't figured out a good best practice for a role that wants to invoke other roles in this sort of manner.

**Comment by BarbzYHOOL** [comment]
reopen

**Comment by tb3088** [comment]
Apparently the internal variable `playbook_dir` is [defined](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html?highlight=playbook_dir) so it should be a simple case of treating that as the TLD for all path resolution tasks, augmented with searching $CWD and (optionally?) the location where ansible.cfg was found. This can't possibly be so hard and is how one would expect it to work.

Looks like we just need to address the logic in vars/manager.py/get_vars() and specifically the behavior of role.get_default_vars() and task.get_search_path() so that they look in multiple locations. Conflicts could be resolved not just simply by ordering but by 'ansible_group_priority'.

**Comment by pgassmann** [comment]
FYI, the `roles_path` in ansible.cfg worked as expected when I removed the comment on the same line

Fix: Add comments on separate lines!

WRONG: 
```
[defaults]
roles_path = roles-galaxy:roles # ansible-galaxy install -r requirements.yml
```

WORKING:
```
[defaults]
roles_path = roles-galaxy:roles
#                              ^ no comment here!
```

**Comment by cfasnacht** [comment]
This works as documented:  "However, if the comment is inline with regular values, only the semicolon is allowed to introduce the comment. For instance:"
https://docs.ansible.com/ansible/2.7/reference_appendices/config.html
But in my opinion this is quite a pitfall!

I debugged it a bit more: roles_path=./roles/external:./roles/internal:./roles # this comment only breaks ./roles
this comment only breaks the last path: ./roles
This can be really painful to debug!

**Comment by jpldcarvalho** [comment]
Why is this issue closed? There was any fix?

**Comment by pgassmann** [comment]
@jpldcarvalho You can run playbooks from subdirectories and also have inventories in subdirectories. 

**BUT** the `host_vars` and `group_vars` need to in either `playbook_dir` or `inventory_dir` ! 

OK: vars next to inventory `production.ini`
```
/inventories/production.ini
/inventories/host_vars/
/inventories/group_vars/
/playbooks/site.yml

$ ansible-playbook -i inventories/production.ini playbooks/site.yml
```
OK: vars next to playbook `site.yml`
```
/inventories/production.ini
/playbooks/host_vars/
/playbooks/group_vars/
/playbooks/site.yml

$ ansible-playbook -i inventories/production.ini playbooks/site.yml
```
NOT OK: vars in top-level, inventory and playbooks in subdirectories
```
/inventories/production.ini
/host_vars/
/group_vars/
/playbooks/site.yml

$ ansible-playbook -i inventories/production.ini playbooks/site.yml
```

NOT OK: playbook in another subdirectory
```
/inventories/production.ini
/playbooks/host_vars/
/playbooks/group_vars/
/playbooks/subdirectory/site.yml

$ ansible-playbook -i inventories/subdirectory/production.ini playbooks/site.yml
```

**Comment by jpldcarvalho** [comment]
@pgassmann and there is any way to have global group_vars?
Ex:
```
/inventories/{ENV1}/host_vars/
/inventories/{ENV1}/group_vars/
/inventories/{ENV2}/host_vars/
/inventories/{ENV2}/group_vars/
/inventories/group_vars/
```

**Comment by trompx** [comment]
Would also be really interested to be able to put playbooks in subdirectories. I have a lot of different infras with a bunch of playbooks for each and it does not scale well.
It works if I duplicate the ansible.cfg in each subdirectory but aiming for DRY.

@jpldcarvalho you can create a `/inventories/shared` with `/inventories/shared/group_vars` and run your playbook with multiple inventories. For example `-i /inventories/shared -i/inventories/{ENV1}`. Put the shared one first so specific env vars that are also defined in shared folder are overriden.
