### ISSUE TITLE
[v2] role_names variable doesn't work

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#12863]
It seems that the `role_names` list no longer exists.

With dummy.yml looking like:

```
- hosts: localhost
  connection: local

  roles:
  - dummy1
  - dummy2

  tasks:
  - debug: var="{{role_names}}"
```

```
ansible-galaxy init roles/dummy1
ansible-galaxy init roles/dummy2
ansible-playbook dummy.yml
```

v1

```
[wthames@wthames galaxy]$ ansible-playbook dummy.yml -i localhost,

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var="['dummy1', 'dummy2']"] ************************************** 
ok: [localhost] => {
    "var": {
        "['dummy1', 'dummy2']": "['dummy1', 'dummy2']"
    }
}

PLAY RECAP ******************************************************************** 
```

v2

```
[WARNING]: provided hosts list is empty, only localhost is available

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug vars={{role_names}}] ***********************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'role_names' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
