### ISSUE TITLE
Using yum module to install gnome-desktop-environment on CentOS 7 does not work

### ISSUE THREAD

**Issue by NathanDotTo** [ansible/ansible#12873]
Hi

The details of this issue are here in the Ansible Google group:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/ansible-project/ResIg2C-y_c

Regards

Nathan

**Comment by abadger** [comment]
Note: bugs against the yum module should be filed against the ansible-modules-core repository: https://github.com/ansible/ansible-modules-core/

I've found an answer for you which I don't 100% understand but is apparently how yum works with groups:
   https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Working_with_Package_Groups.html

According to that document, yum splits things into two types of groups, package groups and environment groups.  When using the yum install command (as we are doing so that we can do the package installs as a single transaction) you have to use different syntax for each: @group for a package group and @^group for an environment group.  the gnome-desktop-environment is an example of the latter so you should be using "name=@^gnome-desktop-environment"

I'll add something to the documentation of the yum ansible module about there being these two separate group types and the syntax to use for each.

**Comment by abadger** [comment]
Okay, I wrote up some documentation about the difference between yum's environment groups and package groups in the above referenced commit.

Sorry this is a confusing area of yum that we're making visible.

**Comment by hardion** [comment]
Thanks abadger, this works great!!!
I spend 3 days to scrawl on Internet for that.
