### ISSUE TITLE
FR - handle undefined vars in ternary filter

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#12872]
version:
ansible v1.9.4

description:
The ternary filter fails to be templated if the 'True' param contains an undefined var, even though it should be using the 'False' param.

```
- hosts: localhost
  vars:
    mysql:
      bob:
        version: 5.0.77
    mysql_version: "{{ ('version' in mysql.get(inventory_hostname, {})) | ternary(mysql[inventory_hostname]['version'],'5.5.46') }}"
  tasks:
    - debug: var=mysql_version
```

Expected

```
ok: [localhost] => {
    "var": {
        "mysql_version": "5.5.46"
    }
}
```

actual

```
ok: [localhost] => {
    "var": {
        "mysql_version": "{{ ('version' in mysql.get(inventory_hostname, {})) | ternary(mysql[inventory_hostname]['version'],'5.5.46') }}"
    }
}
```

This works however

```
"{{ mysql[inventory_hostname]['version'] if ('version' in mysql.get(inventory_hostname, {})) else '5.5.46' }}"
```

**Comment by abadger** [comment]
Even worse, it errors out in v2:

```
$ ansible-playbook 12872.yml                           *[devel]  (07:40:25)

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug var=mysql_version] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! 'dict object' has no attribute u'localhost'"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```

**Comment by jimi-c** [comment]
Hi @halberom, the issue here is that you're not conditionally getting the data out of the mysql datastructure the second time. The error being raised in 2.0 is accurate because of this. To work around that, you should use the .get() call for both the inventory_hostname and version value as well:

<pre>
    mysql_version: "{{ ('version' in mysql.get(inventory_hostname, {})) | ternary(mysql.get(inventory_hostname, {}).get('version'),'5.5.46') }}"
</pre>

Beyond that, the use of the `| default` filter here would be more appropriate as that is essentially what you're trying to accomplish.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
