### ISSUE TITLE
Repeat statments don't work, only last one is used

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#12888]
```

---
- hosts: localhost
  tasks:
    - name: test task
      debug: msg=test
      when: False
      when: True
      when: False
```

Test task is skipped in this configuration, but if you comment out the last line, it is launched. Experiments showed, that only last `when` statement is considered by ansible. I see two ways to fix this:
- make multiple `when` statements work with 'AND' logic
- return error if multiple `when` statements are used

**Comment by bcoca** [comment]
the issue is that pyyaml, which we use to read the playbooks, will unique the keys in a dictionary (yaml spec only allows for unique keys as most associative array implementations do). So we don't have an error to capture, we only see the last 'when'.

the other thing is that you can get what you wan't with a single when:

```
when:
  - False
  - True
  - False
```

a list passed to a when is automatically 'AND'ed. or you can use actual AND to join the conditions

**Comment by selivan** [comment]
I'm using multiple statements to make the code more clear. Lists can do this too, thank you :)

I've found this abandoned bug in pyyaml tracker: https://bitbucket.org/xi/pyyaml/issues/9/ignore-duplicate-keys-and-send-warning-or. Not good. Some workarounds are listed in discussion.

Should I close the issue as "bug in upstream library" or leave it open to get fixed with some workaround?

**Comment by bcoca** [comment]
i would like to issue a warning, but this would apply to any/all cases where someone tries to use a duplicate key in a dictionary. But I don't expect many people to do this. 

I'm not sure if we want to keep the ticket open when upstream does not seem to want to change the current state.

**Comment by abadger** [comment]
Okay, that code change should enable a warning message if dict keys are overwritten.  It's a bit larger than expected since I had to also break apart an import loop so that I could use display.warning() in the yaml parsing code.  The dict key overwriting section are just the changes listed for this file: 

https://github.com/ansible/ansible/pull/12930/files#diff-c495d684aecaea8f523caa00ab4ed915R19

Thanks for finding and reporting this!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
