### ISSUE TITLE
local library not being accounted for in ANSIBLE_LIBRARY

### ISSUE THREAD

**Issue by Jmainguy** [ansible/ansible#12891]
Ansible 2.0 latest from source today.

its not reading custom modules from a local library dir by default, like its intended to do.

```
[jmainguy@Jmainguy-Fedora ansible]$ ls
hosts  library
[jmainguy@Jmainguy-Fedora ansible]$ ls library/
puppet2.py
[jmainguy@Jmainguy-Fedora ansible]$ ansible -i hosts all -m puppet2 -a "show_diff=true filter_password=true"
cee-engine01.web.qa.ext.example.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! The module puppet2 was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."
}
[jmainguy@Jmainguy-Fedora ansible]$ rpm -qa ansible
ansible-2.0.0-0.git201510231613.99c6f77.devel.fc22.noarch
[jmainguy@Jmainguy-Fedora ansible]$ ansible -i hosts all -m puppet2 -a "show_diff=true filter_password=true" --module-path library/
cee-engine01.web.qa.ext.example.com | SUCCESS => {
    "changed": true, 
    "rc": 0, 
    "stderr": "", 
    "stdout": "Notice: Enabling EPEL in profiles::collectd\nNotice: /Stage[main]/Profiles::Collectd/Notify[profiles: enabling EPEL]/message: defined 'message' as 'Enabling EPEL in profiles::collectd'\nNotice: Finished catalog run in 28.94 seconds\n", 
    "stdout_lines": [
        "Notice: Enabling EPEL in profiles::collectd", 
        "Notice: /Stage[main]/Profiles::Collectd/Notify[profiles: enabling EPEL]/message: defined 'message' as 'Enabling EPEL in profiles::collectd'", 
        "Notice: Finished catalog run in 28.94 seconds"
    ]
}
```

**Comment by sivel** [comment]
Isn't a local `library` directory only traversed if it is local to a playbook?  Pretty sure it is, in which case since you are using the `ansible` command it wouldn't be used.  I see you mention `ANSIBLE_LIBRARY`, but don't see any output of evidence of that.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
