### ISSUE TITLE
'TaskResult' object has no attribute 'copy' error

### ISSUE THREAD

**Issue by vecrofund** [ansible/ansible#12894]
I install ansible in my debian server and i wanna to check if ansible working by entering: ansible -m ping servers (servers - my list) and i got this:
[WARNING]: Error when using bound method CallbackModule.v2_runner_on_failed of
</usr/local/lib/python2.7/dist-
packages/ansible-2.0.0-py2.7.egg/ansible/plugins/callback/minimal.CallbackModule
object at 0x15a9450>>: 'TaskResult' object has no attribute 'copy'

P.S i try to change my minimal.py to this: https://github.com/ansible/ansible/commit/99c6f77e593a36ac26341d77fddd898665bde3ae , but same error

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (https://github.com/ansible/ansible/commit/99c6f77e593a36ac26341d77fddd898665bde3ae) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
