### ISSUE TITLE
win_copy: Exception when src: is a folder

### ISSUE THREAD

**Issue by dreamcat4** [ansible/ansible#12900]
Hi again,

If `src:` is a folder, it errors out:

``` sh
fatal: [ga-z170x-g3] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1036, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/win_copy.py", line 256, in run
    module_return = self.runner._execute_module(conn, tmp_path, 'win_copy', module_args_tmp, inject=inject, complex_args=complex_args, delete_remote_tmp=delete_remote_tmp)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 508, in _execute_module
    complex_args.update(utils.parse_kv(args))
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 787, in parse_kv
    vargs = split_args(args)
  File "/usr/lib/pymodules/python2.7/ansible/module_utils/splitter.py", line 185, in split_args
    raise Exception("error while splitting arguments, either an unbalanced jinja2 block or quotes")
Exception: error while splitting arguments, either an unbalanced jinja2 block or quotes


FATAL: all hosts have already failed -- aborting
```

That was with python 2.7.9 + ansible 1.9.4.

**Comment by dreamcat4** [comment]
Note: maybe this bug is already fixed since v1.9.4. But I can't test anything directly on master until you guys integrate the fix for the windows SSL cert 500 verification error.

**Comment by dreamcat4** [comment]
OK it seems that the directory copy works, but only if `dest:` ends in a slash. e.g.:

``` yaml
- name: Copy Powershell Modules to remote machine
  win_copy:
    src: powershell-modules
    dest: c:/program files/_Bin/
```

That's a bug IMHO. But if you don't want to fix then please at least document it.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
