### ISSUE TITLE
"until" loops never loop

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#12928]
Using ansible 2.0.0 (57fe0d6aeda17ff93427e02d52c3354adc4f547d), I am seeing surprising behavior from the `until` loop construct.  The behavior I am trying to produce is "loop until a given command returns exit code 0".  I started with this:

```
- command: test -f flagfile
  register: result
  until: result|success
```

But that fails with:

```
TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["test", "-f", "flagfile"], "delta": "0:00:00.001845", "end": "2015-10-27 14:58:16.372686", "rc": 1, "start": "2015-10-27 14:58:16.370841", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
```

I tried adding `ignore_errors`:

```
- command: test -f flagfile
  register: result
  ignore_errors: true
  until: result|success
```

But that simply caused ansible to assume success and move on, rather
than looping:

```
TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["test", "-f", "flagfile"], "delta": "0:00:00.001916", "end": "2015-10-27 15:02:48.349425", "rc": 1, "start": "2015-10-27 15:02:48.347509", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

In a discussion on irc with `sivel`, it turns out that the
default value of retries is `0` rather than `3`.  Adding a `retries:`
value to the original task made it work as expected:

```
- command: test -f flagfile
  register: result
  until: result|success
  retries: 3
```

I see two problems here:
1. The default value for `retries:` is incorrect.
2. I think -- and I realize opinions on this differ -- that setting
   `retries` to `0` should result it in retrying indefinitely, rather
   than ignoring the `until` clause.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
