### ISSUE TITLE
lxc_container module error ValueError: too many values to unpack

### ISSUE THREAD

**Issue by dkhabarov** [ansible/ansible#12923]
Ansible version: 1.9.2

``` shell
failed: [server] => (item={'network_ipv4_address': '10.0.3.2', 'network_ipv4_broadcast': '10.0.3.255', 'state': 'started', 'name': 'webrails2', 'network_ipv4_gateway': '10.0.3.1'}) => {"failed": true, "item": {"name": "webrails2", "network_ipv4_address": "10.0.3.2", "network_ipv4_broadcast": "10.0.3.255", "network_ipv4_gateway": "10.0.3.1", "state": "started"}, "parsed": false}
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Traceback (most recent call last):
  File "<stdin>", line 3084, in <module>
  File "<stdin>", line 1474, in main
  File "<stdin>", line 1371, in run
  File "<stdin>", line 971, in _started
  File "<stdin>", line 964, in _started
  File "<stdin>", line 622, in _config
ValueError: too many values to unpack
```

Task:

``` yaml
- name: manage containers
  lxc_container:
    name: "{{ item.name }}"
    template: "{{ ansible_distribution | lower }}"
    state: "{{ item.state | default('started') }}"
    container_config:
      - "lxc.start.auto = 1"
      - "lxc.network.ipv4 = {{ item.network_ipv4_address }}"
      - "lxc.network.ipv4.gateway = {{ item.network_ipv4_gateway }}"
      - "lxc.mount.entry = /data data/ none rw,bind,uid=33,gid=33 0 0"
    template_options: "--release {{ ansible_distribution_release }}"
  with_items: containers
  when: is_container_host is defined and item.state == 'started'
  tags: configure_lxc
```

Vars:

``` yaml
containers:
  - {name: 'webrails1', network_ipv4_gateway: 10.0.3.1, network_ipv4_address: 10.0.3.2, network_ipv4_broadcast: 10.0.3.255, state: 'started' }
```

OS: Ubuntu 14.4

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
