### ISSUE TITLE
hostvars not updated after calling add_host

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#12925]
The following change to the `_get_magic_variables` method in `lib/ansible/vars/__init__.py` resolves the issue:

``` python

                if include_hostvars:
                    hostvars_cache_entry = self._get_cache_entry(play=play)
                    # if hostvars_cache_entry in HOSTVARS_CACHE:
                    #     hostvars = HOSTVARS_CACHE[hostvars_cache_entry]
                    # else:
                    if True:
                        hostvars = HostVars(play=play, inventory=self._inventory, loader=loader, variable_manager=self)
                        HOSTVARS_CACHE[hostvars_cache_entry] = hostvars
                    variables['hostvars'] = hostvars
                    variables['vars'] = hostvars[host.get_name()]

```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jlaska** [comment]
Yay, fixed ... thank you!
