### ISSUE TITLE
git module does not update origin remote when repo url changes

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#12931]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.3
##### Ansible Configuration:

Default.
##### Environment:

Mac OS 10.10.5, applied on Ubuntu Linux 14.04
##### Summary:

Changing repo parameter in git module results in a fail
##### Steps To Reproduce:
1. Clone some repo
   
   ``` yml
   -git: repo=ssh://ro@10.10.10.10/home/git/app.git version=dev dest=/home/app/app accept_hostkey=yes force=yes
   ```
2. Change url
   
   ``` yml
   - git: repo=ssh://git@gitlab.local:44444/dev/app.git version=dev dest=/home/app/app accept_hostkey=yes force=yes
   ```
##### Expected Results:

remote url changed
##### Actual Results:

```
TASK: [role | checkout the app] *********************************************** 
failed: [host] => {"cmd": "/usr/bin/git ls-remote origin -h refs/heads/develop", "failed": true, "rc": 128}
stderr: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Cloning to a new location works. Not sure if this issue could be reproduced over ssh. Related to #8177.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by mabushey** [comment]
Any status on this bug getting fixed?
