### ISSUE TITLE
ansible-pull 2.0.0 requires an argument

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#12955]
with ansible 2.0.0-beta2 I get:

```
# ansible-pull --url myurl --key-file key
Usage: ansible-pull <host-pattern> [options]
....
ERROR! Missing target hosts
```

Man page still indicates that it should default to local.yml.  Seems something is messed up here.

**Comment by zentavr** [comment]
The problem is that no proper files are being created. Saying, when you do:

```
pip install --upgrade http://releases.ansible.com/ansible/ansible-2.0.0-0.4.beta2.tar.gz
```

and after that review the binaries - you'll see (3902 is the size of the script):

```
zentavr@zentavr-gsn-mac:~/__repos/ansible$ ls -la ./.venv/bin/ansib*
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible-doc
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible-galaxy
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible-playbook
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible-pull
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:24 ./.venv/bin/ansible-vault
```

If you do:

```
pip install --upgrade https://github.com/ansible/ansible/archive/devel.zip
```

and review the binaries - you'll see this:

```
zentavr@zentavr-gsn-mac:~/__repos/ansible$ ls -la ./.venv/bin/ansib*
-rwxr-xr-x  1 zentavr  staff  3902 29 жов 00:02 ./.venv/bin/ansible
-rwxr-xr-x  1 zentavr  staff     7 29 жов 00:02 ./.venv/bin/ansible-doc
-rwxr-xr-x  1 zentavr  staff     7 29 жов 00:02 ./.venv/bin/ansible-galaxy
-rwxr-xr-x  1 zentavr  staff     7 29 жов 00:02 ./.venv/bin/ansible-playbook
-rwxr-xr-x  1 zentavr  staff     7 29 жов 00:02 ./.venv/bin/ansible-pull
-rwxr-xr-x  1 zentavr  staff     7 29 жов 00:02 ./.venv/bin/ansible-vault
```

...saying _ansible-playbook_ has only the word /ansible/ (7 bytes) and that's it!

I have Python 2.7.10 on OS X El Capitan 10.11.1 and:
pip=7.1.2
setuptools=18.4

**Comment by zentavr** [comment]
pip install --upgrade git+https://github.com/ansible/ansible.git@develop helped for me.

**Comment by opoplawski** [comment]
Well, I'm installing from https://copr-fe.cloud.fedoraproject.org/coprs/toshio/ansible-upstream/ - no problem with the binary.  But the pull.py cli code definitely bails if there is no argument.

**Comment by sivel** [comment]
The file sizes matching or seemingly small is not the issue.  `ansible` is the only command now, and the others are symlinks in the repo.  The process of creating a python package basically duplicates them and doesn't symlink.  The zip file from github, is just a zip of the repo (which is also missing modules btw), and keeps the other files as symlinks.

The problem is probably in the `PullCLI` class.  Likely due to the following lines, which probably need removed: https://github.com/ansible/ansible/blob/7c10c16251d09fcdd99c5ee9364fb0796e3b3a25/lib/ansible/cli/pull.py#L94-L95

**Comment by zentavr** [comment]
@sivel - I saw that they are the symlinks in the repo (and in archives too). But when pip finishes - we have them as files (but not symlinks).

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
