### ISSUE TITLE
run_once not working as expected with handlers

### ISSUE THREAD

**Issue by ianunruh** [ansible/ansible#12972]
Issue Type:

Bug Report

Ansible Version:

ansible 2.0.0 (479cbfc63c8261577b359b7703d7e6168c1a74f5)

Ansible Configuration:

N/A

Environment:

OS X Yosemite / Python 2.7.10

Summary:

When using a handler with `run_once: yes`, multiple notifications trigger the handler to run multiple times. This differs from the behavior in Ansible 1.9.x, where `run_once` would only cause the handler to run once.

Steps To Reproduce:

``` yaml
- hosts: all
  tasks:
    - name: run a command
      command: ls
      notify:
        - run another command

  handlers:
    - name: run another command
      run_once: yes
      command: ls
```

``` bash
ansible-playbook test.yml
```

Expected Results:

```
PLAY ***************************************************************************

TASK [run a command] ***********************************************************
changed: [controller1]
changed: [controller2]
changed: [controller3]

RUNNING HANDLER [run another command] ******************************************
changed: [controller1]

PLAY RECAP *********************************************************************
controller1                : ok=2    changed=2    unreachable=0    failed=0
controller2                : ok=2    changed=2    unreachable=0    failed=0
controller3                : ok=2    changed=2    unreachable=0    failed=0
```

Actual Results:

```
PLAY ***************************************************************************

TASK [run a command] ***********************************************************
changed: [controller1]
changed: [controller2]
changed: [controller3]

RUNNING HANDLER [run another command] ******************************************
changed: [controller3]
changed: [controller2]
changed: [controller1]

PLAY RECAP *********************************************************************
controller1                : ok=2    changed=2    unreachable=0    failed=0
controller2                : ok=2    changed=2    unreachable=0    failed=0
controller3                : ok=2    changed=2    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ianunruh** [comment]
Thanks for the quick fix :+1:
