### ISSUE TITLE
retry files shouldn't be stored in $HOME

### ISSUE THREAD

**Issue by bmillemathias** [ansible/ansible#12996]
After an unsuccessful deployment I saw such message in the console

``` bash
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/baptistemm/apt.yaml.retry
```

I see two problems:
- programs should avoid creating random files directly at the root of the home directory of the user and rather store it under something like `~/.ansible/retry/`. 
- the retry file should be appended with the date and time of the initial execution to avoid overwrite on a further unsuccessful deployment.

**Comment by bcoca** [comment]
the location of retry files can already be set by the user (retry_files_save_path in ansible.cfg)

leaving this open to add either datestamp or configurable format to the retry file name.

**Comment by afh** [comment]
I was also confused by the `*.retry` files in `$HOME` and it took my several months to come across the `retry_files_save_path`. I would've expected the retry files to be located in `$PWD`, which wouldn't interfere with multiple setups using the same names for different playbooks, that would overwrite their retry files.

**Comment by jimi-c** [comment]
This was fixed recently, by default retry files are now stored in the same directory as the playbook unless the retry path is set in the ansible.cfg.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
