### ISSUE TITLE
Problem Starting an EC2 instance by tag type

### ISSUE THREAD

**Issue by jonkellyevanspf** [ansible/ansible#13030]
running this playbook
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    machine_name: 
    ec2_region: ap-southeast-2
  tasks:
  - local_action:
    module: ec2
    region: '{{ ec2_region }}'
    instance_tags:
      Name: '{{ machine_name }}'
    #state: absent
    state: running
    wait: True

results in an error in the ec2.py 

of 

failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false} Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1446607940.65-200286054607709/ec2", line 3216, in <module>
    main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1446607940.65-200286054607709/ec2", line 1387, in main
    (changed, instance_dict_array, new_instance_ids) = startstop_instances(module, ec2, instance_ids, state, instance_tags)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1446607940.65-200286054607709/ec2", line 1290, in startstop_instances
    if len(matched_instances) < len(instance_ids):
TypeError: object of type 'NoneType' has no len()

FATAL: all hosts have already failed -- aborting

The EC2 instance does indeed start but then the error is thrown.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
