### ISSUE TITLE
/etc/ansible/roles missing by ansible package

### ISSUE THREAD

**Issue by mechanicalduck** [ansible/ansible#13040]
Debian Jessie amd64
I installed ansible as package ansible from official Debian Jessie repository.

But when pulling an ansible role (as root user, sudo) using ansible-galaxy I get an error:

```
Error: you do not have permission to modify files in /etc/ansible/roles/[name of role]
```

I was able to fix it by creating the roles/ directory manually:

```
# mkdir -p /etc/ansible/roles
```

However, as this should work out of the box, it is probably a bug 
that the roles/ directory isn't created during installation 
and/or ansible-galaxy not creating it automatically.

With best regards

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
