### ISSUE TITLE
local variable 'task_action' referenced before assignment

### ISSUE THREAD

**Issue by tjcelaya** [ansible/ansible#13042]
Works in 9e758d3 so this is probably a small typo in 483491d. Caused by the following play (unaffected by order of `apt` and `with_items`)

```
    - name: Elixir (apt)
      when: ansible_os_family == "Debian"
      with_items:
        - elixir
        - erlang-dev
      apt:
        pkg={{item}}
        state=present
```

Sort of related, what's the recommended upgrade path? Checking out tagged versions like v1.9.4-1 gave me this error

```
Traceback (most recent call last):
  File "/home/tj/ansible/bin/ansible-playbook", line 44, in <module>
    import ansible.playbook
  File "/home/tj/ansible/lib/ansible/playbook/__init__.py", line 18, in <module>
    import ansible.inventory
  File "/home/tj/ansible/lib/ansible/inventory/__init__.py", line 26, in <module>
    from ansible.inventory.ini import InventoryParser
  File "/home/tj/ansible/lib/ansible/inventory/ini.py", line 21, in <module>
    from ansible.inventory.host import Host
  File "/home/tj/ansible/lib/ansible/inventory/host.py", line 19, in <module>
    from ansible import utils
  File "/home/tj/ansible/lib/ansible/utils/__init__.py", line 27, in <module>
    from ansible import errors
  File "/home/tj/ansible/lib/ansible/errors/__init__.py", line 29, in <module>
ImportError: cannot import name to_str
```

so I'm wondering what I should be doing if I want to stay on stable versions? The docs don't mention any specifics about upgrading other than to do `git submodule update --init --recursive` and I'm not too well versed with git submodules so I'm not sure how to proceed.

Staying on 9e758d3 for now.

**Comment by jimi-c** [comment]
@tjcelaya that traceback is most likely the result of switching between versions, but python is still finding the compiled pyc's from 2.0. I typically run `find . -name "*.pyc" -delete` to clean those up when switching between 1.9.x and devel.

**Comment by bastitx** [comment]
I have a very similar problem on 9e758d3d975f6bfa91d6b554793573d77cbb6a1e

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/lido_apps/repo/ansible-git/ansible/lib/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/lido_apps/repo/ansible-git/ansible/lib/ansible/executor/task_executor.py", line 90, in run
    item_results = self._run_loop(items)
  File "/lido_apps/repo/ansible-git/ansible/lib/ansible/executor/task_executor.py", line 201, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/lido_apps/repo/ansible-git/ansible/lib/ansible/executor/task_executor.py", line 241, in _squash_items
    if len(items) > 0 and task_action in self.SQUASH_ACTIONS:
UnboundLocalError: local variable 'task_action' referenced before assignment

fatal: [qlhansplay]: FAILED! => {"failed": true, "stdout": ""}
```

when executing this:

```
-  command: /usr/bin/crontab -l
    remote_user: "{{item}}"
    with_items:
      - user1
      - user2
      - user3
```

Even after removing all *.pyc files

**Comment by daveadams** [comment]
I get the same when running:

```
- include_vars: "{{ item }}"
  with_items:
    - users.yml
    - groups.yml
```

**Comment by abadger** [comment]
Sorry about that.  Was testing action: and localaction: last night and forgot to test regular module invocation in a with loop before committing.  That commit seems to fix it for me.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
