### ISSUE TITLE
File descriptor leak in TaskExecutor class

### ISSUE THREAD

**Issue by solomongifford** [ansible/ansible#13046]
In the 1.9 branch (including whats in the centos 6 repo) in the Runner class, it appears ansible is trying to duplicate the fileno for a new stdin, however, this introduces a file descriptor leak since the dup is never closed. 

Additionally, self._new_stdin is not used anywhere else in this class.

```
 self._new_stdin = new_stdin
            if not new_stdin and fileno is not None:
                try:
                    self._new_stdin = os.fdopen(os.dup(fileno))
                except OSError, e:
                    # couldn't dupe stdin, most likely because it's
                    # not a valid file descriptor, so we just rely on
                    # using the one that was passed in
                    pass
```

In stable-1.9/lib/ansible/runner/**init**.py#L582

This file descriptor leaks one fd for each.

It appears in the master branch as well, only its is being used by the TaskExecutor.  However, since its not being closed, it will be a file descriptor leak there as well.

**Comment by CoreyFirespotter** [comment]
Here is a patch we're using to workaround this. Probably not a good fix for everyone, but might unblock some.
[fd_leak_fix.txt](https://github.com/ansible/ansible/files/116452/fd_leak_fix.txt)

To apply, cd to the egg folder and run:
patch -p1 < fd_leak_fix.txt

**Comment by jimi-c** [comment]
Hi @solomongifford, just following up on older issues. This appears to have been fixed at some point in the past as running `watch -d "ls -1 /proc/<pid>/fd/ | wc -l"` (where <pid> is that of the main ansible-playbook process) shows a steady count of fd's.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bmsupport** [comment]
The code producing the error seems to have been removed/replaced.
