### ISSUE TITLE
feature: support ansible.cfg specify 'group_vars' and 'host_vars' paths

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#13051]
We can already set `inventory` filename, `roles_path`, and plugin
paths in `ansible.cfg`.  I would really like to be able to use
different names for `group_vars` and `host_vars` dirs too,
(or possibly additional ones to search).

I know there is already `vars_files` and `include_vars` but those
have different purposes; I'm talking about renaming the actual
path _ansible_ searches for group and host vars, so the sysadmin
can make the tree with names that are to his liking.

**Comment by Yannig** [comment]
@smemsh: I have already wrote something like this that implements group/host vars inheritance (ie additional dir to search for).

You can have a look here: https://github.com/ansible/ansible/pull/12628

**Comment by smemsh** [comment]
@Yannig if I understand your patch correctly, it only adds parent dirs that will be searched for [still hardcoded] `group_vars` and `host_vars` directories.  It will not allow me to look in, say, `/etc/ansible/gvars/` and `/etc/ansible/hvars/`.  Is my understanding correct?

**Comment by Yannig** [comment]
@smemsh you're right. It's more simple to implement this way and I think it's not a big problem.

In this case, you can rename gvars and hvars into group_vars and host_vars and pass /etc/ansible as parent path.

**Comment by smemsh** [comment]
right, well the point is, I want to name them differently :-) not even necessarily to search other ones, although I think that idea, and your patch, are good things to have also.

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We don't want this to seem confrontational, but unfortunately we're not sure if we want this feature in the program. This issue has remained open for quite a while, and it has failed to garner any interest nor have any community members picked it up to work on it. However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
