### ISSUE TITLE
feature: ControlPersist optimization for each segment of jump via ProxyCommand

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#13055]
The new `ansible_ssh_common_args` lets me add a `ProxyCommand`
argument to the `ssh` invocation for entire inventory groups, which
simplifies use of an ssh jump host.

My understanding (from reading tickets) is that this was implemented
to permit use of ProxyCommand: (1) without having to override the
whole `ssh_args`, or alternatively (2) without needing to use the
`.ssh/config` of the invoking user.

However, when using `ProxyCommand` this way, the control socket
in the filesystem is keyed off the far hop (inner tunnel) of the jump,
which means the near hop does _not_ use a persistent socket.  If
another host needs to be reached via the jump gate, an entirely
new socket will be set up, even though we could reuse it for the
inner portion (first hop) of the jump.  If reaching 1000 remote hosts
via a jump gate, we will make 1000 separate ssh invocations, each
with its own control socket, and no re-use (it only reuses if same
far-host is destination)

This could be optimized by using ControlPath to describe only the
near hop, and then use _another_ ssh with ControlPath on the far
side.  I don't know if this is a real issue or not, but thought it was
worth submitting a ticket for.  I think it would involve making a
jump-host scenario a "first class" connection property that was
implemented in code that could then be "nested" and duplicated
on the remote end (rather than just a string-append to ssh args).

If this is just totally crazy, by all means close ticket.  I think it could
help some scenarios though, it would avoid doing the first-half of the
jump circuit 999 times in the case of 1000 jump targets on the far
side.  So it would have to do only 1001 total ssh setups, rather than
2000, which could really be a big win...

**Comment by amenonsen** [comment]
> I don't know if this is a real issue or not, but thought it was worth submitting a ticket for.

…

The way you describe the problem suggests that you're thinking of `ProxyCommand` as working by doing something like `ssh jumphost ssh realhost`, but that is not actually how it works. When you run `ssh -o ProxyCommand='ssh -W %h:%p jumphost' realhost`, what actually happens is that the proxy command is executed and is then treated as though it were a connection to realhost; in particular, it's the local machine that's negotiating an SSH connection with realhost. The jumphost only provides a way to _reach_ port 22 on the real target host. It only establishes a TCP connection, either via the builtin `-W %h:%p` or by running `netcat %h %p` explicitly (as one had to do with older versions of SSH), and then forwards data between the control node and the other end of the connection.

So the simple answer is that you _can_ in fact add `-o ControlPersist=yes` and other options to your `ProxyCommand` right now. Unfortunately, ssh doesn't actually support multiplexing the proxy connection (because it's already connected to one host, and there isn't a way to tell it to use the same socket but switch to another forwarding configuration, either via `-W` or by re-executing a different `netcat` command). So it isn't possible to make it work the way you want, but that's because of ssh, not ansible. If ssh supports this behaviour in future, we can use the functionality (probably without any changes except to the value of `ansible_ssh_common_args`).

But I personally don't see ansible ever going the way of opening a connection to a jump host and then sending complete `ssh realhost somecommand` commands to it (such that the `ControlPersist` sockets end up on the jumphost). I doubt it could even be conveniently implemented as a separate connection plugin without duplicating a _lot_ of code, to say nothing of how confusing the configuration would have to be (especially for authentication). I think that situation qualifies for the "just run ansible on the better-connected host" advice that the documentation already gives for AWS.

So I think this ticket should be closed.

**Comment by smemsh** [comment]
Ok, so basically `ssh -W` is just a shorthand for netcat then.  Well, there's still two ssh sessions happening, and only one of them is using _ControlPersist_ (the second one, once _ProxyCommand_ finishes).  I see what you're saying that ssh will need to support it to combine `-o ControlPersist` with `-W` on the jumphost.

It could be done with two separate ones, as you point out, by invoking the second ssh on the jumphost (just like `ssh -tt jumphost ssh` used to be common).  I don't personally like this as much, because it requires me to put credentials on the intermediary system, or forward my local agent, neither of which I like compared to having both connections managed by my local ssh (and agent) only.  However, for the case of a management node closer in that already will have these credentials, I can see this being useful... it could be done without code duplication, and even perhaps chained to any depth of jumpgates, if the ssh connection became something that was run by ansible locally, then on the remote side using the same code object, but I don't know enough about ansible's codebase yet to comment on that part or its feasibility.

I think the right place for this is probably to teach ssh about it so it can make more than one control socket when it does a ProxyCommand (it should probably build ProxyCommand into an additional ssh connection flag instead of having to run it via system() interpretation of a ProxyCommand).  I will consider bringing this up on ssh mailing list.

I'll close as suggested and anyone finding this later can comment if they think something should be done in Ansible.  Thanks.
