### ISSUE TITLE
Template does not work with absent destinations

### ISSUE THREAD

**Issue by phy1729** [ansible/ansible#13069]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (detached HEAD cc27fc368a) last updated 2015/11/06 16:14:18 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 750aa16a06) last updated 2015/11/06 16:14:48 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 62f52d702a) last updated 2015/11/06 16:14:48 (GMT -500)
  config file = /Users/phy1729/ansible/ansible.cfg
  configured module search path = /Users/phy1729/ansible-bin/library
##### Environment:

OS X 10.11
##### Summary:

template module no longer copies to absent destinations
##### Steps To Reproduce:

Checkout a version on or after  768f2fe6d465271f6410865ac138eb62889ee40 .

```
ansible -sm template -a'src=/etc/hosts dest=/nonexistant' <some host>
```
##### Expected Results:

For /nonexistant to mirror my /etc/hosts.
##### Actual Results:

```
<some host> | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "file (/nonexistant) is absent, cannot continue",
    "path": "/nonexistant",
    "state": "absent"
}
```

**Comment by jimi-c** [comment]
Hi @phy1729, this has been corrected as of 9a25e16140407dd99b382e336ecdf9c3157ea0da.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
