### ISSUE TITLE
FAILED => Missing sudo password when NO SUDO PASSWORD is needed

### ISSUE THREAD

**Issue by armstrj** [ansible/ansible#13077]
I have SUDO configured to work without passwords.
This command works just fine:
  ansible quee -a "/usr/bin/sudo /usr/bin/apt-get update"

This command fails with "FAILED => Missing sudo password "
    ansible quee -a "/usr/bin/apt-get update" --sudo

It works if I add --ask-sudo-pass and enter a sudo password.

I am using Ansible 1.7.2 on Debian Jessie (current stable)

I want to use Ansible playbooks and expect that I will need --sudo to work properly without passwords.
Have I missed something obvious?

Any help much appreciated.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by armstrj** [comment]
User Issue - Really? then a hint would have been appreciated. It looks like a BUG to me.

**Normal sudo works fine with no password** - see the example

**Ansible sudo FAILS with the no-password-error** - see the example.

**Comment by armstrj** [comment]
And I have found the problem... Ansible uses SUDO to wrap the entire call to execute the remote temporary script. 

If you have only enabled specific known commands to run as root then Ansible sudo will not work for you.

Shame really - you would have thought that the temporary scripts would be generated **containing** the relevant SUDO on each remote command, rather than just going for SUDO the-whole-script.

Whatever you do - **DONT** accept the Ansible teams recommendation to just open up execution of any script as root.

**Comment by agouaux** [comment]
I know this is closed, but just seems to be a massive oversight!

**Comment by bcoca** [comment]
It is not an oversight, it is by design, the incorrect assumption above is that Ansible always uses 'shell commands', this is not true, in many cases it is just using system calls or other code libraries and there is no 'shelling' to a specific command. So the entire 'module' needs to run under sudo, as well as other commands that create tempdirs, copy needed files, chown, chmod, etc and cleanup everything, as they need to deal with permissions. All this won't work with a restricted set of sudo commands.

Another reason is that 'sudo' is not the only privilege escalation method, so we need to be able to handle it in a generic enough way to allow for other systems to wrap our execution.
