### ISSUE TITLE
synchronize module fails on 1.9.4

### ISSUE THREAD

**Issue by hickscorp** [ansible/ansible#13089]
Hello,

I'm using Ansible 1.9.4 (Vanilla from Ubuntu 15.10).
In one of the playbooks, i have a task as follows:

```
# Copy certificates.
- name:             copies certificates for the registry to use
  synchronize:      src=certs dest={{registry_dir}}
```

A few months ago, it was successful. Now, it fails:

```
TASK: [docker.docker_registry | copies certificates for the registry to use] *** 
failed: [127.0.0.1 -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"certs\" \"/home/vagrant/registry\"", "failed": true, "rc": 23}
msg: rsync: link_stat "/home/vagrant/certs" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

I also had to change all my playbooks... I don't know if it is related to the sync issue. For instance, I had an Ansible set of playbooks. The folder structure was containing a top-level "files" folder, itself populated with everything that would eventually be copied remotely. Until a few months ago, my playbooks were running just fine using the copy module, and omitting the "files/" prefix in my paths. Now, I had to add the prefix to all my copy operations, because Ansible was unable to find the files, as the logs showed that Ansible was only looking inside each "roles/xxx/files" folders.

Are there any regression tests done on Ansible? We are considering Ansible + Tower on many of my company projects, but given the various discrepancies we had over time, we are still uncomfortable doing so. Do you recommend freezing the minor Ansible version? Months ago, when the playbooks were working, I was also using the 1.9 branch, and such differences between the same major version are a bit scary.

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by corpix** [comment]
Hit same bug with Ansible 2.0. The error is same, `No such file or directory`. My `src` directory is a relative path. Does this bug has some known workaround?

**Comment by tima** [comment]
The synchronize module, action plugin and core engine was re-written for 2.0 and required some changes to restore backwards compatibility. In other cases the handling in 1.9 was broken and was fixed. 

If you are still experiencing this error with the latest stable version of Ansible, please resubmit with updated information using the standard issue guidelines. 

Thanks.

wontfix
