### ISSUE TITLE
[v2]win_stat does not support hidden directory，like".svn"?

### ISSUE THREAD

**Issue by BenMo158** [ansible/ansible#13084]
I have a "d:\iisroot\tiger\.svn" directory, execution
ansible iis01 -m win_stat -a "path=D:\iisroot\tiger\.svn"
iis01 | SUCCESS => {
    "changed": false, 
    "stat": {
        "exists": false
    }
}
"win_stat" module not support this?

**Comment by cchurch** [comment]
Since this is an issue about a module, could you file it under the modules repo at http://github.com/ansible/ansible-modules-core instead?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
