### ISSUE TITLE
[Feature Request] include roles without executing its tasks/main.yml

### ISSUE THREAD

**Issue by basz** [ansible/ansible#13091]
in advance : I can't create a PR (no python skills), so apologies. More apologies if this is already possible...

I would like to see an option on roles that disable the execution of the main.yml task from such a role.

Why?
For third party roles that provide sub tasks that might need defaults/vars/handlers/etc and do a lot in the main.yml. For my own roles I already use a special property in combination with an mostly empty tasks/main.yml that runs on a conditional (when property)

Suppose a role has split tasks into various tasks files so these can be easily reused. For example a role that enable's or creates a vhost.

You would want to use that role then by including the role in your playbook so any role defaults (etc) are available within the provided sub task.

```
roles:
 - { role: thirdparty.role }

tasks:
 - include: "{{ playbook_dir }}/roles/thirdparty.role/tasks/additional_task.yml"
```

However this will also run the `thirdparty.role/tasks/main.yml`which might not be a problem, but more often that not is. (I do not need to setup apache over and over again. just so I can enable a vhost)...

So what I like to emerge is an role property  that make ansible NOT run the main.yml task from the role, for example;

```
 - { role: thirdparty.role, run_default_task: false }
```

please shoot this down if it doesn't make sense.

**Comment by jimi-c** [comment]
@basz not sure this makes sense. You can still do the `- include` as you show in your example without including the role, and you could include any vars files the same way (using include_vars). Yes, this would not work well with default variables, however I believe it would make more sense to tweak any roles you're finding problematic rather than introduce this feature.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by basz** [comment]
fair enough, thank you @jimi-c
