### ISSUE TITLE
“The variable 'environment' appears to be used already”

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#13105]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0
##### Ansible Configuration:

[ssh_connection]

ssh_args = ''
##### Environment:

Ubuntu 12.04 / Ubuntu 15.04 Server
##### Summary:

After upgrading to the latest development version `ansible-playbook` displays the warning:

```
[WARNING]: The variable 'environment' appears to be used already, which is also used internally for environment variables set on the task/block/play. You should use a different variable name to avoid conflicts with this internal variable
```
##### Steps To Reproduce:

`playbook.json`:

``` json
[
    {
        "hosts": "all",
        "tasks": []
    }
]
```
##### Expected Results:

Execution without warnings.
##### Actual Results:

Execution with warning.

**Comment by sivel** [comment]
Are you using any specific inventory along with this?

**Comment by mcalhoun** [comment]
+1 on this issue...I'm having it on Mac OSX. I've tried with an inventory file with a single host and a playbook with no tasks and I still get the warning message.

**Comment by mcalhoun** [comment]
Looks like https://github.com/ansible/ansible/commit/ccbcfcddfccf5a75e0c39c508160385d97d1477d is the culprit...

**Comment by jimi-c** [comment]
Doh...

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
