### ISSUE TITLE
sudo pip install ansible --upgrade failing

### ISSUE THREAD

**Issue by garyrutland** [ansible/ansible#13116]
Hey,

I'm trying to upgrade on my Mac (OSX El Capitan 10.11.1) from version 1.9.4 to 2+ so I can utilise ec2_ami_find but running into problems when running the above command.

This is the output I get:

```
Requirement already up-to-date: ansible in /Library/Python/2.7/site-packages
Requirement already up-to-date: paramiko in /Library/Python/2.7/site-packages (from ansible)
Requirement already up-to-date: jinja2 in /Library/Python/2.7/site-packages/Jinja2-2.8-py2.7.egg (from ansible)
Requirement already up-to-date: PyYAML in /Library/Python/2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.11-intel.egg (from ansible)
Collecting setuptools (from ansible)
  Using cached setuptools-18.5-py2.py3-none-any.whl
Requirement already up-to-date: pycrypto>=2.6 in /Library/Python/2.7/site-packages/pycrypto-2.6.1-py2.7-macosx-10.11-intel.egg (from ansible)
Requirement already up-to-date: ecdsa>=0.11 in /Library/Python/2.7/site-packages/ecdsa-0.13-py2.7.egg (from paramiko->ansible)
Requirement already up-to-date: MarkupSafe in /Library/Python/2.7/site-packages/MarkupSafe-0.23-py2.7-macosx-10.11-intel.egg (from jinja2->ansible)
Installing collected packages: setuptools
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-3JkjEu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]
```

Is there anything else I need to run/install/update before I can upgrade my version?

Thanks,
Gary

**Comment by sivel** [comment]
OSX El Capitan introduced a "feature" called "System Integrity Protection" which adds protections on the `/System` directory.  It appears that some of your libraries that are being upgraded are installed in `/System`.

As such, OS X is denying even root level access to update those files.  There are several articles on disabling "System Integrity Protection" that can be found via google searches.

Since this is not an ansible related bug, I'm going to go ahead and close this issue.  Please feel free to stop by the mailing list or Mac OS related forums for further assistance.

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by tgrzemski** [comment]
Hi, 
I had the same problem. Turning off "System Integrity Protection" is quite risky.

You can try to do this:
sudo pip install --ignore-installed --upgrade ansible

**Comment by gnat42** [comment]
@tgrzemski Thanks your suggestion worked perfectly...

**Comment by nerobianchi** [comment]
@tgrzemski works like a charm

**Comment by kenny-evitt** [comment]
I ran into a similar error, also due to SIP, trying to _install_ Ansible from source initially. I followed the suggestion of [this answer](http://apple.stackexchange.com/a/209583/23450) to the following question on the "Ask Different" (Apple) Stack Exchange site:
- [osx - How to use pip after the OS X El Capitan upgrade? - Ask Different](http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade)

It suggested installing Python via Homebrew:

```
brew install python
```

After doing so I was able to install the Python modules Ansible requires without any errors:

```
pip install paramiko PyYAML Jinja2 httplib2 six
```

**Comment by tameek** [comment]
closed issue but wanted to reiterate that @tgrzemski suggestion worked for me!

**Comment by jaegerbane** [comment]
It's worth pointing out that ignoring the installed setuptools 1.1.6 does not solve the problem, it merely postpones it - ansible 2.1 installs, but attempting to deploy playbooks results in a new error:

`ERROR! Unexpected Exception: 'EntryPoint' object has no attribute 'resolve'`

I've tracked this issue down to trying to use an outdated version of setuptools http://cebuserver.com/ww2/resolving-ansible-vault-error/

So, unfortunately, the problem hasn't been fixed and this ticket should really be reopened, as the setuptools issue itself is stemming from a security feature put into place (with good reason) on OSX. Ultimately, if ansible is supposed to be be supported on OSX then this really needs looking at.

EDIT: nevermind, a colleague came up with a really good idea of installing using the `--user` flag so that the updates are installed in $HOME and don't touch anything connected to SIP.

For reference, it's just `pip install ansible --upgrade --user`

Might still be worth adding this to the documentation.

**Comment by anguspaterson** [comment]
This saved my life a few weeks back. Thanks so much @tgrzemski

**Comment by bretlinne** [comment]
I needed to upgrade from 1.9.4 ansible and successfully used:
`pip install ansible --upgrade`
