### ISSUE TITLE
Bug Report: --limit no longer working

### ISSUE THREAD

**Issue by j3ffrw** [ansible/ansible#13111]
Hi, --limit option is no longer working after commit c753ae6
# Ansible Version:

ansible-playbook 2.0.0 (devel d8fb5efa90) last updated 2015/11/10 17:07:26 (GMT +800)
  lib/ansible/modules/core: (detached HEAD fde6ee15d6) last updated 2015/11/10 17:11:10 (GMT +800)
  lib/ansible/modules/extras: (detached HEAD 6cc43bbd56) last updated 2015/11/10 17:16:15 (GMT +800)
  config file = 
  configured module search path = Default w/o overrides
# Ansible Configuration: Clean version from github
# Environment: Linux Mint 17.2 Rafaela, Python 2.7.6
# Steps To Reproduce:

 <p>Create the inventory file and play.yml</p>
- inventory

<pre><code>host1 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22
host2 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22
host3 ansible_ssh_host=127.0.0.1 ansible_ssh_port=22

[myhostgroup]
host1
host2
host3
</code></pre>
- play.yml

<pre><code>
- hosts: all
  connection: local
  tasks:
    - debug: var="{{hostvars[inventory_hostname]}}"
  </code></pre>

  <p> Run playbook w/ --list-host option to see affected hosts. It will disregard the -l option and show all hosts. </p>

<pre><code>
$ ansible-playbook -i inventory -l "host1" --list-hosts play.yml

playbook: play.yml

  PLAY: #1
    pattern: [u'all']
    hosts (3):
      host3
      host2
      host1
</code></pre>

<p> checkout previous commit before c753ae6 </p>

<pre><code>
$ git checkout e8f83dcba34ce7ea22d63b0e5f0b57b9dd49e853
</code></pre>

  <p> Re run playbook. Result will only show host specified in -l option.  </p>

<pre><code>
$ ansible-playbook -i inventory -l "host1" --list-hosts play.yml
 [WARNING]: The variable 'environment' appears to be used already, which is also used internally for environment
variables set on the task/block/play. You should use a different variable name to avoid conflicts with this internal
variable

playbook: play.yml

  PLAY: #1
    pattern: [u'all']
    hosts (1):
      host1
</code></pre>

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
