### ISSUE TITLE
Asynchronous failed retries logs as Red

### ISSUE THREAD

**Issue by philltomlinson** [ansible/ansible#13130]
I just wanted to clarify if the following line is correct for the task_executor.py:

```
self._display.display("FAILED - RETRYING: %s (%d retries left). Result was: %s" % (self._task, retries-attempt, result), color="red")
```

The line will be logged in red, however in cases I use it in I would not consider it an error if it fails to do a retry as I have some long running tasks that may poll many times to get the result. I have changed this to yellow on my local install. Is the colour red planned to be used in the 2.0 release? I would find it odd as it can be confusing as nothing has really gone wrong.

**Comment by jimi-c** [comment]
I've gone ahead and changed this to dark gray, as I went back and checked to find out we didn't actually show these interim failures at all in the v1 code.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
