### ISSUE TITLE
shell module doesn't allow awk variable usage

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13150]
Summary: running awk inside of ansible shell module cause incorrect expansion of awk variable

Steps to reproduce:
1. bin/ansible all -i inventory/test3.ini -m shell -a "ps aux | grep java | grep -v grep | awk '{print $2}' "

Expected Result:
pid of the running java programs (or any other program )

Actual Result:
The full line like $2 is removed 

Further diagnosis:
escaping $ will get the things done:
bin/ansible all -i inventory/test3.ini -m shell -a "ps aux | grep java | grep -v grep | awk '{print \$2}' "
But this is should not be necessary.

**Comment by messiahUA** [comment]
It's standard shell parameter expansion, ansible is not responsible for this, if you don't want to escape $, then use something like "ps -o pid -C java | grep -v PID"

**Comment by jimi-c** [comment]
I believe if you're doing this via ansible-playbook, you don't need to escape things, otherwise it is as @messiahUA says above.

As this is a general use question, we're going to go ahead and close this now. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ywhere** [comment]
Use the following method：   grep -v grep|/bin/awk '{print \$2}'|xargs kill
