### ISSUE TITLE
Bug Report: Synchronize module asks password

### ISSUE THREAD

**Issue by BR0kEN-** [ansible/ansible#13153]
This is duplicate of [#5934](https://github.com/ansible/ansible/issues/5934)!
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

Original.
##### Environment:

OS X Yosemite 10.10.5 (14F1021)
##### Summary:

inventory

``` ini
[vagrant]
192.168.56.132 ansible_ssh_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key
```

provision.yml

``` yml
- hosts: all
  gather_facts: yes
  sudo: yes

tasks:
  - synchronize:
      src: ./
      dest: "/var/lib/jenkins"
      archive: no
      recursive: yes
    sudo: yes
```
##### Steps To Reproduce:

``` shell
ansible-playbook -vvvv provision.yml -i inventory --limit=vagrant
```
##### Expected Results:

`synchronize` should not ask for a password, as other tasks do.
##### Actual Results:

```
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035 && echo $HOME/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035']
<127.0.0.1> PUT /var/folders/72/r_f79s2974q5b59cq0f7c1wh0000gn/T/tmpTRff6u TO /Users/BR0kEN/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035/synchronize
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/BR0kEN/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035/synchronize; rm -rf /Users/BR0kEN/.ansible/tmp/ansible-tmp-1447416965.06-222404616716035/ >/dev/null 2>&1']
vagrant@192.168.56.132's password:
```
##### Debugging steps:

I've go to `ansible/modules/core/files/synchronize.py` and put `print(cmdstr)` before `(rc, out, err) = module.run_command(cmd)`. Module generated the next command:

``` shell
rsync --delay-updates -F --compress --recursive --rsh 'ssh -i .vagrant/machines/default/virtualbox/private_key -S none -o StrictHostKeyChecking=no' --rsync-path="sudo rsync" --out-format='<<CHANGED>>%i %n%L' "/Users/BR0kEN/cibox/aae/provisioning/roles/cibox-jenkins/files/" "vagrant@192.168.56.132:/var/lib/jenkins"
```

**And even more:**

Open the `ansible/runner/__init__.py` and put `print(cmd)` before `res = self._low_level_exec_command(conn, cmd, tmp, become=self.become, sudoable=sudoable, in_data=in_data)`. Module generated something like:

``` shell
LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/BR0kEN/.ansible/tmp/ansible-tmp-1447418694.04-11945943198607/synchronize; rm -rf /Users/BR0kEN/.ansible/tmp/ansible-tmp-1447418694.04-11945943198607/ >/dev/null 2>&1
```

When I execute one of these raw commands, then everything fine.

**Comment by BR0kEN-** [comment]
Future debugging said that problem exists with VirtualBox (Vagrant). When installing on a remote - everything is fine, but not on mounted (NFS) file system.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
