### ISSUE TITLE
connection: local NOT using local connection on latest devel

### ISSUE THREAD

**Issue by senorsmile** [ansible/ansible#13162]
running with -vvvv clearly shows it using the user of the remote host and attempting to ssh.  This issue doesn't exist on the latest tag: v2.0.0-0.4.beta2, at  commit de54f26376968ebc6362137f34b5ecb584bc90eb .

**Comment by jimi-c** [comment]
@senorsmile I'm not seeing this at all:

<pre>
# ansible -m ping -c local -vvv localhost
Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1447598211.87-30455961661008`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1447598211.87-30455961661008`")
127.0.0.1 PUT /tmp/tmpkl_z8Y TO /root/.ansible/tmp/ansible-tmp-1447598211.87-30455961661008/ping
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1447598211.87-30455961661008/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1447598211.87-30455961661008/" > /dev/null 2>&1
localhost | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {}, 
        "module_name": "ping"
    }, 
    "ping": "pong"
}
</pre>

Can you please share details on your setup?

**Comment by amenonsen** [comment]
For what it's worth, it uses a local connection for me too, even when it's not "localhost" I try, but some other host with `-c local`. There were some problems in devel at one point where it _didn't_ use a local connection, but that was fixed some weeks ago and I haven't noticed it happen again since.

**Comment by jimi-c** [comment]
As there has been no follow up on this in 3 weeks, we're going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
