### ISSUE TITLE
easy_install unsupported parameter for module: state

### ISSUE THREAD

**Issue by philribeiro** [ansible/ansible#13197]
I have the following `easy_install` task:

``` ansible
 32 - hosts: all
 33   user: root
 34   tasks:
 35       - easy_install: name=pip state=latest
```

When I run my ansible playbook, I get:

```
TASK: [easy_install name=pip state=latest] ************************************ 
failed: [127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: state

FATAL: all hosts have already failed -- aborting
```

The ansible documentation confirms that: http://docs.ansible.com/ansible/easy_install_module.html. Could someone verify that's a bug or a documentation issue with ansible?

**Comment by phuqm** [comment]
I have the same issue: (the state parameter is not valid till version 2.0), 
I'm not using it just for pip but because pip is failing me.

You though, can just work around by installing pip without the state parameter and then update pip to latest in the next section of your playbook with a pip task (name=pip state=latest works for that).

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
