### ISSUE TITLE
mount module with the state=unmounted not removing entries from /etc/fstab

### ISSUE THREAD

**Issue by sivakom** [ansible/ansible#13211]
**Issue Type:**
    Bug Report

**Ansible Version:**
Running ansible 1.9.2-bbg (detached HEAD 951fac4181). I did try it on the latest version but the issue still persists.

**Ansible Configuration:**
Haven't modified the `ansible.cfg` file or any configuration regarding ansible.

**Environment:**
Running it on Ubuntu 14.04.3 LTS.

**Summary:**
I'm trying to unmount a device in an ordinary linux machine with the ansible mount module. Let's assume that the following is an example of a device that I am trying to unmount (lsblk output): 
`sdc1   8:33   0   3.7T  0 part /tmp/sdc1`

When I run this appropriate ansible command:
`- mount: name=/tmp/sdc1 src=/dev/sdc1 fstype=xfs state=unmounted`

This does unmount the device but doesn't remove the entry from the `/etc/fstab` file. According to the docs, "if mounted or unmounted, the device will be actively mounted or unmounted as needed and _appropriately configured in fstab_", the fstab entry should be removed, but is clearly not being so. However, if I set the state to `absent`, the entry is indeed deleted but this necessitates using another task just to ensure this behavior.

**Steps To Reproduce:**
Firstly, there needs to be a linux device with a mountpoint which also has an associated entry in the `/etc/fstab` file. Then you can run the following task:
`- mount: name=<mountpoint> src=<device> fstype=<device's file system type> state=unmounted`

The device should then be unmounted afterwards, a simple run of `lsblk`should do. But if you look into the contents of `/etc/fstab`, the device's fstab entry should still be there.

**Expected Results:**
As stated before, when running the mount module with a `state=unmounted`, the device should be unmounted and have it's entry removed from the `/etc/fstab` file.

**Actual Results:**
Device is unmounted but the entry remains in `/etc/fstab`.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
