### ISSUE TITLE
cloudformation fail error, but AWS shows success

### ISSUE THREAD

**Issue by zbuckholz** [ansible/ansible#13210]
Obviously this was an error on my part for not following the proper regular expression for the stack name.

```
  stack_name="IdAM-{{EnvType}}_ansible-cloudformation" state=present
```

Ansible reported failure as shown below, but the VPC successfully deployed to AWS as IdAM-dev

CHAAZML-1GAFFT0:amazon ubuckza$ ./ansible/bin/ansible-playbook -i /Users/ubuckza/Documents/work/ansible/contrib/inventory/ec2.py launch_ansible_cloudformation_template.yaml --extra-vars "EnvType=dev Region=us-west-2 KeyName=IdAM-External-Prod-uswest2"

PLAY ***************************************************************************

TASK [launch ansible cloudformation template] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "1 validation error detected: Value 'IdAM-dev_ansible-cloudformation' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
