### ISSUE TITLE
"dark gray" text is impossible to see on a dark terminal background

### ISSUE THREAD

**Issue by bikramwp** [ansible/ansible#13224]
On a dark terminal background, the use of `dark gray` text makes it invisible:

![dark-gray-not-visible-in-terminal](https://cloud.githubusercontent.com/assets/1194355/11293006/46f14f2a-8f0a-11e5-8822-aab5e35e0632.png)

I was running ansible with `-vvvv`, and happened to select the text in the terminal when I noticed that there was text that was invisible unless I selected it - that text is colored `dark gray`

This commit is the cause: https://github.com/ansible/ansible/commit/dac3684fd1c871b31d17d2b47e82bb9708467e37

Since `purple` is used for informational messages/warnings already, may I suggest that the use of `dark gray` be eliminated completely and `purple`/other color used instead?

PS. This is on the default OSX Pro terminal profile

**Comment by jimi-c** [comment]
Hi @bikramwp this is debugging output only, and we currently use purple for deprecation messages. As such, we don't have any current plans to change this, other than to perhaps light gray, and we'll close this now.

If you would like to discuss this any further, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bikramwp** [comment]
Thanks for the reply.

Debugging output is the reason one needs to be able to see the output - otherwise it (partially) defeats the purpose of debugging.

Changing to light gray sounds fine.
