### ISSUE TITLE
yum groupinstall not working

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible#13222]
From the docs example:

```
- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
```

This has stopped working for me, using 2.0.0 (devel c97c101bd3)

I see this as a result:

```
TASK [install the development tools] *******************************************
ok: [machine]
```

But when I go to the machine and 

```
yum groupinstall "Development tools"
```

They are definitely not installed by ansible.

**Comment by abadger** [comment]
In order to make yum work when multiple packages are specified and some of those packages have dependencies on one another, the module attempts to install or remove all specified packages in a single transaction.  This means that we use "yum install [PACkAGENAME] [GROUPNAME]" instead of a separate "yum groupinstall [GROUPNAME]" step.  The yum install syntax differentiates between yum "package groups" (which are specified in the package's spec file) and yum "environmental groups" (which are specified in xml files when the yum repository is created).  "development tools" is an environmental group and therefore needs to be specified like this:
"@^Development tools".  (We documented this strange behaviour here: http://docs.ansible.com/ansible/yum_module.html#notes )

**Comment by davivcgarcia** [comment]
I'm experiencing same behaviour when trying to install 'JBoss EAP 7' (that looks like an 'package group') on a RHEL 7.2. When running the task, looks like nothing is done by Ansible:

```
TASK [webserver : Install JBoss EAP 7] *****************************************
task path: /home/dvercill/Projects/ansible-example/roles/webserver/tasks/main.yml:5
ok: [sandbox-01.dvercill-lab.local] => {"changed": false, "msg": "", "rc": 0, "results": [""]}
```

I'm using Ansible version 2.1.1.0 on Fedora 24 as controlling node. Tried different configs on my playbook, and this task is specified like below (but already tried using "@^JBoss EAP 7"):

```
- name: Install JBoss EAP 7
  yum:  name="@JBoss EAP 7" state=latest
```

**Comment by gadelkareem** [comment]
Same here Ansible 2.2.0 both
```
- name: install Development Tools
  yum: name="@^Development Tools" state=latest update_cache=yes
```

and

```
- name: install Development Tools
  yum: name="@Development Tools" state=latest update_cache=yes
```

not working

**Comment by zigarn** [comment]
With Ansible 2.2.1.0, using `state: latest` doesn't work:

```yaml
- name: Install build tools
  yum:
    name: "@Development tools"
    state: latest
  become: yes
```

Results in:

```
TASK [Install build tools] ********************************************
ok: [test]
```

But, using `state: present` works:

```yaml
- name: Install build tools
  yum:
    name: "@Development tools"
    state: present
  become: yes
```

Results in:

```
TASK [Install build tools] ********************************************
changed: [test]
```
