### ISSUE TITLE
Option --diff does not show changes when template module used with with_items loop.

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#13232]
**Issue Type:**
Bug Report

**Ansible Version:**
    ansible 2.0.0 (devel d75e707af5) last updated 2015/11/20 15:57:21 (GMT +200)
      lib/ansible/modules/core: (detached HEAD 88e0bfd75d) last updated 2015/11/20 15:57:24 (GMT +200)
      lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/20 15:57:27 (GMT +200)
      config file =
      configured module search path = Default w/o overrides

**Ansible Configuration:**
None/Default

**Environment:**
Debian GNU/Linux 8.2 Jessie 

**Summary:**
Option `--diff` does not show changes when template module used with loops.
Tested w/ and w/o `--check` option and with `with_items` and `with_first_found` loops.

**Steps To Reproduce:**
test.yml playbook:

```
- hosts: localhost
  tasks:
  - template: src={{ item }}.j2 dest=/tmp/test
    with_items:
      - test
```

test.j2 template:

```
Hello
```

**Expected Results:**

```
$ ansible-playbook test.yml --check --diff
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [template dest=/tmp/test src={{ item }}.j2] *******************************
changed: [localhost] => (item=test)
--- before
+++ after: dynamically generated
@@ -0,0 +1 @@
+Hello

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Actual Results:**

```
$ ansible-playbook test.yml --check --diff
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [template dest=/tmp/test src={{ item }}.j2] *******************************
changed: [localhost] => (item=test)

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Hi @ahes, this was corrected by 6694e97a31f7a2eebf5da57f8cec267451861a95, which was merged yesterday.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
