### ISSUE TITLE
run_once with delegate_to and register doesn't work for multiple hosts

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#13267]
Issue Type: Bug Report

Ansible Version:

ansible 2.0.0 (stable-2.0 90021104d5) last updated 2015/11/23 15:20:43 (GMT -600)
  lib/ansible/modules/core: (detached HEAD 191a672891) last updated 2015/05/29 17:54:15 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/05/29 17:51:40 (GMT -600)
  config file = /home/kevin/.ansible.cfg
  configured module search path = /usr/share/ansible

Ansible Configuration: pretty standard.

Environment: rhel7 x86_64 and Fedora rawhide

Summary:

If you have a task that has run_once set and register, that variable only works for the first host to hit the task. Other hosts get undefined variable. 

Steps To Reproduce:

Use this playbook with 2 valid hosts:
- name: test playbook for bug
  hosts: td:falcar
  gather_facts: False
  
  tasks:
  - name: Run a test command
    command: uptime
    register: host_uptime
    run_once: True
    delegate_to: localhost
  - name: use the output
    debug: var=host_uptime.stdout_lines

Expected Results:

All hosts will be able to use the registered variable

Actual Results:

The first host gets the variable ok but further hosts have it undefined. 

PLAY [test playbook for bug] ***************************************************

TASK [Run a test command] ******************************************************
changed: [td]

TASK [use the output] **********************************************************
ok: [falcar] => {
    "changed": false, 
    "host_uptime.stdout_lines": "VARIABLE IS NOT DEFINED!"
}
ok: [td] => {
    "changed": false, 
    "host_uptime.stdout_lines": [
        " 15:47:03 up 26 days,  5:26,  1 user,  load average: 0.00, 0.01, 0.05"
    ]
}

PLAY RECAP *********************************************************************
falcar                     : ok=1    changed=0    unreachable=0    failed=0  
td                         : ok=2    changed=1    unreachable=0    failed=0

**Comment by stevenscg** [comment]
I believe I just observed the issue you described with both of these versions...

```
ansible 2.0.0 (devel 478c6c756a) last updated 2015/11/23 09:16:30 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 572771d0b1) last updated 2015/11/17 12:21:34 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD e5362cc76a) last updated 2015/11/17 12:21:39 (GMT -500)

ansible 2.0.0 (devel 96fcfe45d0) last updated 2015/11/23 19:54:54 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 572771d0b1) last updated 2015/11/17 12:21:34 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD e5362cc76a) last updated 2015/11/17 12:21:39 (GMT -500)
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
