### ISSUE TITLE
ssh port from inventory gets used on delegated hosts too

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#13265]
Issue Type: Bug Report

Ansible Version: 

ansible 2.0.0 (stable-2.0 1ab60564ae) last updated 2015/11/23 21:28:22 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 572771d0b1) last updated 2015/11/16 16:30:29 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD e5362cc76a) last updated 2015/11/16 16:30:32 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /srv/web/infra/ansible/library:/usr/share/ansible

Ansible Configuration: pretty standard.

Environment: rhel7 x86_64

Summary:

When you specify a ssh port to use in inventory the port is used in playbooks for that host even to try and contact delegate_to hosts as well. 

Steps To Reproduce:
1. create an inventory with "somehost:222" 
2. Make sure ssh is listening on port 222 on somehost. 
3. Run a playbook with: 
- name: test playbook for bug
  hosts: td
  gather_facts: False
  
  tasks:
  - name: task on host with non standard port
    command: uptime
  - name: task delegated to another host that has standard port
    delegate_to: falcar
    command: uptime

Expected Results: Both tasks finish correctly

Actual Results: First task finishes fine, second task fails trying to contact the second host on port 222 instead of 22

**Comment by pujan14** [comment]
Could be related to #13323 ?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
