### ISSUE TITLE
playbook_on_stats callback is called at the end of every play

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#13271]
Issue Type: Bug Report (2.0 regression)
Ansible Version: 2.0.0 (rc1)
Ansible Configuration: default
Environment: NA
Summary: For 1.9 callback plugins, playbook_on_stats was only called once at the end of the playbook run, regardless of number of plays. This made it effectively useful as an "on playbook finish" callback. In 2.0, playbook_on_stats is called at the end of every play, which breaks accumulator-style callbacks.

Steps To Reproduce:
Grab sample callback plugin from https://gist.github.com/nitzmahone/90a2510226f42c7f6e49, drop into callback_plugins. Run test_play.yml from same gist.

Expected Results:

ON STATS! should show up only once at the end of the playbook run (as it does in 1.9).

Actual Results:

ON STATS! shows up at the end of each play.

Filed on behalf of Callfire

**Comment by cchurch** [comment]
@nitzmahone Good catch; this would definitely cause issues in Tower.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
