### ISSUE TITLE
git module does not properly update bare repository

### ISSUE THREAD

**Issue by chuckyz** [ansible/ansible#13272]
The git module does not appear to properly update a bare repository...

Also, please excuse my poor understanding; but it appears that the fetch function never actually runs any commands, as there is no run_command() in the entire function.  Could that be the issue?

If I let Ansible manage my bare repo it _sometimes_ updates it, but randomly does not.  It also appears to only happen when looking at non-master branches (e.g.: origin/foo instead of origin/master).

The following task is what handles the updates, with variables included:

```
    repo_uri:       git@github.com:our/repo.git
    repo_path:      "{{ deploy_path }}/repositories/repo.git"

    - name: update the local repository
      git:
        repo: "{{ repo_uri }}"
        dest: "{{ repo_path }}"
        bare: yes
        clone: yes
        update: yes
        force: yes
        accept_hostkey: True
```

Simply running what I expect, e.g.: `git fetch origin 'refs/heads/*:refs/heads/*'` and then re-running the playbook allows everything to run smoothly.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by meshy** [comment]
(Issue was moved to https://github.com/ansible/ansible-modules-core/issues/2540)
