### ISSUE TITLE
wantlist missing from lookup in 2.0

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#13285]
`wantlist` was introduced in 1.9, and seems to have been omitted accidentally from 2.0.

You can see the functionality at:

https://github.com/ansible/ansible/blob/57389d55b1722ec4358172fb4c58a61c513148f8/lib/ansible/utils/template.py#L94
https://github.com/ansible/ansible/blob/57389d55b1722ec4358172fb4c58a61c513148f8/lib/ansible/utils/template.py#L105-L106

I don't fully understand the impact of using `UnsafeProxy`, so I figured it would be safest to just report it currently.

I'm not sure the method that should be used on `ran` to return it as is, instead of joining it.

Some thoughts:

```
diff --git a/lib/ansible/template/__init__.py b/lib/ansible/template/__init__.py
index bed1c83..af22497 100644
--- a/lib/ansible/template/__init__.py
+++ b/lib/ansible/template/__init__.py
@@ -390,6 +390,8 @@ class Templar:
     def _lookup(self, name, *args, **kwargs):
         instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)

+        wantlist = kwargs.pop('wantlist', False)
+
         if instance is not None:
             from ansible.utils.listify import listify_lookup_plugin_terms
             loop_terms = listify_lookup_plugin_terms(terms=args, templar=self, loader=self._loader, fail_on_undefined=True, convert_bare=False)
@@ -405,7 +407,10 @@ class Templar:

             if ran:
                 from ansible.vars.unsafe_proxy import UnsafeProxy
-                ran = UnsafeProxy(",".join(ran))
+                if wantlist:
+                    ran = UnsafeProxy(ran)
+                else:
+                    ran = UnsafeProxy(",".join(ran))

             return ran
         else:
```

Or if we need to do each element:

```
diff --git a/lib/ansible/template/__init__.py b/lib/ansible/template/__init__.py
index bed1c83..83e15f0 100644
--- a/lib/ansible/template/__init__.py
+++ b/lib/ansible/template/__init__.py
@@ -390,6 +390,8 @@ class Templar:
     def _lookup(self, name, *args, **kwargs):
         instance = self._lookup_loader.get(name.lower(), loader=self._loader, templar=self)

+        wantlist = kwargs.pop('wantlist', False)
+
         if instance is not None:
             from ansible.utils.listify import listify_lookup_plugin_terms
             loop_terms = listify_lookup_plugin_terms(terms=args, templar=self, loader=self._loader, fail_on_undefined=True, convert_bare=False)
@@ -405,7 +407,10 @@ class Templar:

             if ran:
                 from ansible.vars.unsafe_proxy import UnsafeProxy
-                ran = UnsafeProxy(",".join(ran))
+                if wantlist:
+                    ran = [UnsafeProxy(r) for r in ran]
+                else:
+                    ran = UnsafeProxy(",".join(ran))

             return ran
         else:
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
