### ISSUE TITLE
implement normpath and win_normpath filter

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible#13298]
Since its a pain for windows users to escape windows paths it would be cool that a filter is implemented converting C:/test/test2 to C:\test\test2 and vice versa. this could be handled with the normpath method of the os.path and ntpath imports

**Comment by nitzmahone** [comment]
@h0nIg - have you tried in 2.0 yet? Most cases where you'd need to escape no longer require backslash escaping (raw yaml values work without doubling, as do single-quoted values), and most things also just work with either forward or backslashes (some modules don't yet, it's inconsistent at the moment)...

**Comment by jhawkesworth** [comment]
This is a nice idea, but need to leave the door open for being specific.  Powershell itself is happy with c:/foo/bar/ or c:\foo\bar\ but if you are calling a native windows exe and passing it a path... they often aren't.

I think ending a line in a playbook with a windows style path with a trailing \ is likely to be trouble as a \ on the end of a line has a special meaning in yaml.

**Comment by nitzmahone** [comment]
The other problem here is that we're still going to be subject to YAML/KV escaping issues since templating happens early (and we won't know which we're doing while the filter is executing)- I'm going to close as a "probably not" and hope that we can continue to gain ground (eg, maybe fixing the playbook and cmdline KV parsers to behave sanely).
