### ISSUE TITLE
Ansible Docker Module - Not working with my particular configuration

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13309]
I am running into an issue when trying to run the following ansible docker task.
## Version Info:

ansible 1.9.4
docker 1.9.1 API version:  1.21
## Ansible Task:

```
- name: consul container
  docker:
    name: consul
    image: progrium/consul
    state: reloaded
    pull: always
    net: bridge
    ports:
    - "192.168.33.10:8300:8300"
    - "192.168.33.10:8301:8301"
    - "192.168.33.10:8301:8301/udp"
    - "192.168.33.10:8302:8302"
    - "192.168.33.10:8302:8302/udp"
    - "192.168.33.10:8400:8400"
    - "192.168.33.10:8500:8500"
    - "172.17.0.1:153:53/udp"
    volumes:
    - /mnt:/data
    command:
     - "-server -advertise 192.168.33.10 -bootstrap-expect 1 -ui-dir /ui"
```
## Ansible task error message:

```
TASK: [consulserver | consul container] *************************************** 
failed: [node1] => {"failed": true, "parsed": false}

BECOME-SUCCESS-uwdnfeyqupcdtngwerroooqaujvhwjlw
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1448489567.48-276009549745537/docker", line 3185, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1448489567.48-276009549745537/docker", line 1542, in main
    reloaded(manager, containers, count, name)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1448489567.48-276009549745537/docker", line 1417, in reloaded
    containers.refresh()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1448489567.48-276009549745537/docker", line 1352, in refresh
    self.deployed = self.manager.get_deployed_containers()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1448489567.48-276009549745537/docker", line 1169, in get_deployed_containers
    command = command.strip()
AttributeError: 'list' object has no attribute 'strip'
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.

FATAL: all hosts have already failed -- aborting
```

**Comment by ghost** [comment]
I have determined that the issue is being caused by my command:

```
command:
- "-server -advertise 192.168.33.10 -bootstrap-expect 1 -ui-dir /ui"
```

is this the correct way to pass arguments to the docker command being run?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
