### ISSUE TITLE
template function failed on control node though the libselinux-python is installed already

### ISSUE THREAD

**Issue by oopslink** [ansible/ansible#13313]
situation on control node:
- selinux is enable
- libselinux-python is installed

when using template function, action success except control node, it still throw exception like this:

_"Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"_

Here is the track:

```
...
fatal: [lark001]: FAILED! => {"changed": true, "failed": true, "invocation": {"module_args": {"dest": "/etc/selinux/config", "group": "root", "mode": "0644", "owner": "root", "src": "disable_selinux/config.j2"}, "module_name": "template"}, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

PLAY RECAP *********************************************************************
lark001                    : ok=4    changed=2    unreachable=0    failed=1   
lark002                    : ok=5    changed=2    unreachable=0    failed=0   

[root@lark001 playbook]# /usr/sbin/selinuxenabled; if [ $? -ne 0 ]; then echo "DISABLED"; else echo "ENABLED"; fi
ENABLED
[root@lark001 playbook]# yum install libselinux-python
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
Package libselinux-python-2.0.94-5.8.el6.x86_64 already installed and latest version
Nothing to do
```

I dig in a bit, find:

```
   def selinux_enabled(self):
        if not HAVE_SELINUX:
            seenabled = self.get_bin_path('selinuxenabled')
            if seenabled is not None:
                (rc,out,err) = self.run_command(seenabled)
                if rc == 0:
                    self.fail_json(msg="Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!")
            return False
        if selinux.is_selinux_enabled() == 1:
            return True
        else:
            return False
```

It seems using the return code of selinuxenabled to judge whether libselinux-python is installed, is this really work? and why?

**Comment by shrutivsampat** [comment]
It is possible that the libselinux-python package has not installed the modules
in any of the standard paths where Python can find it. That could be the reason
it complains that the package is not installed. Can you try starting the Python
interpreter and import the selinux module using `import selinux'?
Or see where it has installed using`rpm -ql libselinux-python'.

And to answer your question about the function:

> It seems using the return code of selinuxenabled to judge whether
>   libselinux-python is installed, is this really work? and why?

The return code is checked if selinux is enabled, but whether libselinux-python
is installed is determined above by trying to import selinux and the variable
HAVE_SELINUX is set. And it is deduced that selinux is enabled but we can't make
any selinux library calls since the module is absent.

However, I agree that it is a bit confusing, and maybe the developer can throw
some light on it.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, the `libselinux-python` package is not required on the Ansible machine, but on the target, in the PYTHONPATH of the python interpreter used to execute the module, which you should be able to determine using `-vvvv` when running `ansible-playbook`.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
