### ISSUE TITLE
apt action with deb parameter doesn't work with more than 1 item in with_items loop

### ISSUE THREAD

**Issue by zshamrock** [ansible/ansible#13346]
##### Issue Type:
- Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.9.4
  configured module search path = None
##### Ansible Configuration:

No changes
##### Environment:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie
##### Summary:

It looks like `apt` action with `deb` parameter doesn't work with `with_items` used together, see steps below.
##### Steps To Reproduce:

https://gist.github.com/zshamrock/1e4fae122427f107f710
A few things to mention, if I limit `with_items` in the gist above to 1 item, it works fine. Also using `shell: dpkg -i /tmp/{{ item }}.deb` works fine with arbitrary number of items in `with_items`, so problem is not in the archive downloaded.
##### Expected Results:

All the items from `with_items` to be installed.
##### Actual Results:

TASK: [local | install downloaded deb packages] ******************************\* 
failed: [127.0.0.1] => (item=viber,slack) => {"failed": true, "item": "viber,slack"}
msg: Unable to install package: E:Could not open file /tmp/viber - open (2: No such file or directory), E:Unable to determine file size for fd -1 - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/alex/site.retry

127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by jimi-c** [comment]
Hi @zshamrock, this is a common problem when using apt/yum and with_items. The .deb portion needs to be moved down to each item, so the param remains simply `name={{item}}`, otherwise the way things are joined would result in `item1,item2.deb` (which obviously doesn't work).

There have been many issues in the past discussing this, so we'll go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
