### ISSUE TITLE
installing pip install --user ansible on OS X and it will fail to find the core modules

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#13417]
On OS X 10.11 and probably earlier, where you already have Python installed via `brew`, if you install ansible via `pip install --user ansible` it will install without any errors, but when you will run it it will fail to find the core modules, including ping, data,...

For your information ansible is deployed into `~/Library/Python/2.7/lib/python/site-packages` in this case.

If you install ansible without `--user` it will end-up into `/usr/local/lib/python2.7/site-packages` and still it will be unable to find its modules.

```
ansible --version
ansible 1.9.4
  configured module search path = None
```

That's quite strange because it used to work well until I tried to install version 2.0 and after realising that there are too many changes and having to remove it and reinstalling the current release, it stopped working by failing to find the modules.

I mention that there are no ansible config files into /etc or user home directory. This makes me think that the installation of ansible 2.0 may have introduced a change that was not removed.

Here what I did to wipe ansible from the machine:

```
rm -rf /usr/local/lib/python2.7/site-packages/ansible*
rm -rf /Users/${HOME}/Library/Python/2.7/lib/python/site-packages/ansible*
rm -rf /usr/local/bin/ansible*
rm -rf /usr/local/opt/ansible*
rm -rf /usr/local/Cellar/ansible*
```

**Comment by abadger** [comment]
This looks like a problem with the setup on your machine rather than in ansible's code.  Probably best to ask this question on the mailing list.  I'll paste the list information below.

It does seem like your thought on ansible-2.0 not being completely removed is the problem.  Probably giving more information about where and how you installed ansible2.0 when you post to the mailing list will help to diagnose this.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
