### ISSUE TITLE
ansible-playbook: doesn't like "-i 'inventory.py -L foo'" for dynamic inventory

### ISSUE THREAD

**Issue by cjeanneret** [ansible/ansible#13452]
Hello there,

I'm using latest released ansible (1.9.4) for an application deploy on ec2 instances.

In order to get a smaller inventory, I've coded one that takes just the needed arguments and provides a properly formated JSON — it's working fine.

The following command does work:

``` Bash
ansible-playbook -i inventory.py playbook.yml
```

No issue with that.

But if I want my dynamic inventory to returns only a subset of the hosts, as shown in ansible documentation[1]:

``` Bash
ansible-playbook -i 'inventory.py -L staging'
```

It returns the following error:

``` Bash
ERROR: Unable to find an inventory file, specify one with -i ?
```

I also tested with some previous ansible version, I have the same issue. Is this option even working properly? Shall I put the inventory.py in /etc/ansible, even if using "./inventory" ?

Thank you for your help/hints/corrections.

Cheers,

C.

[1] "You can then run ec2.py --profile prod to get the inventory for the prod account, or run playbooks with: 
`ansible-playbook -i 'ec2.py --profile prod' myplaybook.yml`." [source](https://docs.ansible.com/ansible/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script)

**Comment by cjeanneret** [comment]
(small note: same issue with "ansible" executable, but this is kind of logic)

**Comment by jimi-c** [comment]
HI @cjeanneret, inventory scripts do not take params as you've specified them. Instead, you must either use the config file provided with the inventory script, or you must set environment variables.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by justinmacleod** [comment]
Interesting, I ran into this same issue while trying to follow the Example EC2 Dynamic Inventory Script. As mentioned by @cjeanneret, the page here http://docs.ansible.com/ansible/intro_dynamic_inventory.html contains an example where params are past to the ec2.py file. It was added in pull request #12548. Good to know it's not possible and I wasn't losing my mind.

**Comment by jimi-c** [comment]
Hrm that's interesting, I'd never noticed that before, and as long as I've worked on Ansible we've always had users specify things via env vars or config files.

**Comment by bcoca** [comment]
some inventory scripts have extra options, but these are not available through ansible and only through direct execution or through environment variables/config files.

Sadly those docs are incorrect, there was a request to add these options to ansible-playbook but it was denied, the docs seemed to have creeped in though. Fixed via dcedfbe26c2aacc901fe5ef84b51103feb92990f

**Comment by jimi-c** [comment]
@bcoca thanks!

**Comment by justinmacleod** [comment]
Ah, that makes sense. thanks @bcoca

**Comment by cjeanneret** [comment]
Thank you! For once I read the doc, and it's was wrong, a pitty ;).

Thanks for the quick clarification and doc correction. I've modified my script so that it knows about ENV var, and it's now working just fine.
