### ISSUE TITLE
ansible-pull fails on Python 3

### ISSUE THREAD

**Issue by skorokithakis** [ansible/ansible#13456]
`ansible-pull` won't run on Python 3 because of print statements lacking parentheses.

**Comment by sivel** [comment]
I believe this should be resolved in 2.0, with the introduction of using `print_function` from `__future__`.

However, you are likely to still be unable to use `ansible-pull` with python3, as the shared module code does not support python3 at this time, which would prevent you from using any built in module, including the ability to clone the repo to use with `ansible-pull`.

**Comment by jimi-c** [comment]
@skorokithakis this falls under the general Python 3 work, as noted here: https://github.com/ansible/ansible/blob/devel/docsite/rst/roadmap/ROADMAP_2_2.rst (see the `Python 3 (Toshio)` section for details). As ansible-pull operates from the target side, it will most likely only have full support in Ansible 2.4, however a large number of modules should work with it as of Ansible 2.3.

If you have any further questions about this work, please do not hesitate to ping us in our IRC channels (#ansible-devel or #ansible-meeting), or via the devel mailing list:
- https://groups.google.com/forum/#!forum/ansible-devel

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
