### ISSUE TITLE
[Proposal] Add feature for support http request

### ISSUE THREAD

**Issue by hacpai** [ansible/ansible#13483]
I think most company can't direct access intranet server with ssh.

In my company, I access intranet server with Gateway Server, look like this:

```
localhost ----ssh---> Gateway Server-----ssh---> Someone Intranet Server
```

So I can't operator intranet server  with ansible.

When one door shuts,another opens. In my company, the other way to operator intranet server is calling http api, like this:

``` shell
curl -k -d "$some_parameter" -d cmd="$cmd" $url
```

I think ansible can support this way,  is it a good idea?

**Comment by hloeffler** [comment]
just modify your ssh config to jump with gateway server => ansible works via ssh

**Comment by hacpai** [comment]
I think it's good idea. but in fact, my company login gateway server with dynamic password and I can only enter IP address to login someone intrant server.

发自我的 iPad

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We don't want this to seem confrontational, but unfortunately we're not sure if we want this feature in the program. As @hloeffler mentioned above, the common use-case is to have an intermediate system which you either connect to or tunnel through, and we have no plans to add an HTTP-based transport at this time.

Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
