### ISSUE TITLE
Doc for GCE module refer to outdated auth strategy

### ISSUE THREAD

**Issue by rorygibson** [ansible/ansible#13515]
The docs recommend using GCE credentials in P12 format (and converting to PEM).

However, running the module, libcloud informs you that this is deprecated and you should download & use credentials in JSON format instead.
(Upon trying this, it does work!)

**Comment by bcoca** [comment]
cc @erjohnso

**Comment by erjohnso** [comment]
Thanks for flagging that @rorygibson and bringing it to my attention @bcoca.

Were you planning on sending a pull-request to improve them, or just wanted to file the issue? If you weren't planning on doing the work yourself, I may have a colleague that's interested in cleaning up the docs and making them current. Otherwise, I'll get to it in a few weeks.

**Comment by viglesiasce** [comment]
Thanks for bringing this up @rorygibson! I noticed this as well last week and will take a pass at bringing these docs up to date.

**Comment by rorygibson** [comment]
Thanks guys.
I'm very much an Ansible newbie. Enjoying the experience so far and the
docs have generally been excellent.
