### ISSUE TITLE
Deprecation of conditionals (when) on includes?

### ISSUE THREAD

**Issue by slmingol** [ansible/ansible#13548]
I recently noticed this message while using ansible 2.1.0 (devel 58072c92fb).

```
TASK [common-rtim : include tags=ntp] ******************************************
[DEPRECATION WARNING]: You should not specify tags in the include parameters. 
All tags should be specified using the task-level option. This feature will be removed 
in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
```

Am I correct in understanding that we should no longer be using conditionals on includes? If not then is our only option to push these conditionals down to tasks within the included file? This seems counterproductive?

**Comment by sivel** [comment]
That message, as indicated, is referencing the use of `tags` on an include, not `when` statements.

I believe currently you may have something that looks like the following:

```
- include: foo.yml tags=bar
```

That format is deprecated and should be updated to something such as:

```
- include: foo.yml
  tags: bar
```

**Comment by sivel** [comment]
Since I can see that you have specified `tags=ntp` in the task as identified by `TASK [common-rtim : include tags=ntp]`, I am going to close this issue out.

Please feel free to stop by either IRC or the mailing list for further questions:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by slmingol** [comment]
Ah. Completely missed the messaging and what it was "acutally" telling me vs. what  I "thought" it was telling me 8-) ... thanks!
