### ISSUE TITLE
ec2_elb_lb is not idempotent when stickiness is defined / bug report

### ISSUE THREAD

**Issue by abrugnon** [ansible/ansible#13562]
## Ansible  version

```
ansible 2.1.0 (devel d203438a2c) last updated 2015/12/15 17:02:49 (GMT +200)
  lib/ansible/modules/core: (detached HEAD b1c0249045) last updated 2015/11/18 16:55:01 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/18 16:55:01 (GMT +200)
```
## Environment:

ubuntu 14.04
## Summary:

When an ELB is created with stickiness, it runs well at the first time, but it fails on all subsequent calls.
## Steps to reproduce

Here is a playbook that fails on second run

```
- hosts: 127.0.0.1
  connection: local

  tasks :
    - name : Nginx load balancer
      local_action:
        module : ec2_elb_lb
        name : elb-test-sticky
        state: present
        region : "{{adin_ec2_region}}"
        scheme : "internet-facing"
        security_group_names:
          - sg_adin_front
        subnets : "{{adin_vpc_front_subnet}}"
        purge_subnets: yes
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        stickiness:
          enabled : yes
          type: application
          cookie : JSESSIONID
```
## Actual result :

Result on 1st run : OK

Result on 2nd Run

```
 <Error>
    <Type>Sender</Type>
    <Code>LoadBalancerNotFound</Code>
    <Message>Cannot find Load Balancer e</Message>
  </Error>
```
## Expected Result

No changes nor error

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
