### ISSUE TITLE
add_host does not see complete inventory.

### ISSUE THREAD

**Issue by flajann2** [ansible/ansible#13582]
Branch: 2.0-stable

Playbook demonstrating the problem:
https://gist.github.com/flajann2/20debb7659a94ca87a99

Behavior:
We have an inventory of 25 instances on ec2. Of this, add_host only sees one of them. I have been scratching my head over this one, because it's as though add_host only wants to execute once, not every time the playbook does a new item in the inventory.

This is a critical bug for us, and not sure what a workaround would be.
I can be reached on skype as "flajann" if you wish to correspond with me directly.

The output is included in the gist.

**Comment by flajann2** [comment]
This appears to be a dup of https://github.com/ansible/ansible/issues/6912#issuecomment-39957335
which would mean I did not understand how add_host is supposed to really work. After checking the documentation for add_host, there, I did not find an adequate description there either.

Please consider updating the documentation. Thank you.

**Comment by jimi-c** [comment]
Hi @flajann2, this behavior is documented in the `Notes:` section of http://docs.ansible.com/ansible/add_host_module.html. Per the above, we'll close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
