### ISSUE TITLE
Docker API fail

### ISSUE THREAD

**Issue by patrickvanharen** [ansible/ansible#13597]
I installed python 2.7 and the newest docker-py. This is my role:
- name: nginx docker
  docker:
  name: nginx
  image: nginx/latest

Below the output of the ansible-playbook. Whats going wrong?

failed: [docker02.meisters.io] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-tmp-1450433454.29-214084830665893/docker", line 2130, in <module>
main()
File "/root/.ansible/tmp/ansible-tmp-1450433454.29-214084830665893/docker", line 723, in main
containers = manager.create_containers(1)
File "/root/.ansible/tmp/ansible-tmp-1450433454.29-214084830665893/docker", line 596, in create_containers
containers = do_create(count, params)
File "/root/.ansible/tmp/ansible-tmp-1450433454.29-214084830665893/docker", line 584, in do_create
result = self.client.create_container(*_params)
File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 115, in create_container
volume_driver
File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 120, in create_container_config
return utils.create_container_config(self._version, *args, *_kwargs)
File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 736, in create_container_config
'mem_limit has been moved to host_config in API version 1.19'
docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19

FATAL: all hosts have already failed -- aborting

**Comment by abadger** [comment]
Hi, the docker module lives in a separate repository so you'll probably want to submit bug reports there instead:  https://github.com/ansible/ansible-modules-core/

However, this looks like a bug that's already been fixed there.  You could try downloading the latest version of the module: https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/cloud/docker/docker.py and seeing if the problem has been fixed in a later version.  If so, you can use the downloaded copy until ansible-2.0 is released with the module in the tarball.

**Comment by abadger** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by patrickvanharen** [comment]
Thank you! But what do I need to do? Do I need to replace this docker.py file? There isn't currently an existing docker.py. Can you please describe what to do?

**Comment by reisubx** [comment]
I've got the same error.
as a work around, I commented this lines in the /usr/local/lib/python2.7/dist-packages/docker/utils/utils.py file

```
    #if mem_limit is not None:
    #    raise errors.InvalidVersion(
    #        'mem_limit has been moved to host_config in API version 1.19'
    #    )
```

**Comment by patrickvanharen** [comment]
Yes this works!! Thank you :)
