### ISSUE TITLE
python version requirement

### ISSUE THREAD

**Issue by yogo1212** [ansible/ansible#13600]
This matter is related to ansible's dependancy to python2 and the ![FAQ](http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine).

How is requiring people to have python point to python2 in /usr/bin/ any better than just requiring python2 in the shebang? Especially, if it's already established that ansible DOES NOT work with python3 which is a preferred candidate for the symlink.

Explicitly discouraging users to fix shebangs is even worse (encouraging bad design imho).

At some point in the future ansible-scripts will be ported from python2
to python3 - that's also the right time to change the shebang from
python2 to python3 and the dependency for ansible in general.
Then, other maintainers will also have to change their shebangs and port their
modules to python3 in order to support the new version of ansible.

**Comment by bcoca** [comment]
This is because not all distros ship with a python2 executable, even when they do it might not be the 'right one' as many allow for multiple python2 versions installed. We 'fix' the shebangs through the `ansible_python_interpreter` variable.

Ansible already supports modules in python3 (as it does perl, ruby, shell, etc), they are just not compatible with the shared code in module_utils and have to implement many functions themselves.

We are committed to allow Ansible to run on both python2 and python3, this is non trivial and an ongoing effort. But let me be clear, achieving python3 support WILL NOT imply removing python2 support, our current aim is to be able to support both for 'controller' and targets with the shipped modules.

Also, this is not the correct forum for this, please use IRC or the ansible-devel mailing list:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by ssbarnea** [comment]
The so called "fixing" of the wrongly assumed hardcoded location of python interpreter doesn't really work and here is why: Imagine that we do have an ansible playbook that has its purpose to configure the current machine (localhost). You cannot really know if the current machine is going to be an OS X one, or another one which means that you cannot really define a custom `ansible_python_interpreter` that will work.

**Comment by bcoca** [comment]
@ssbarnea in the case of 'localhost' we use sys.executable which should have been set on install of Ansible on that platform in the bin/ansible script (by setuptools or the package manager).
