### ISSUE TITLE
ansible stable-1.9 mysql_db module login_host arguments not affect

### ISSUE THREAD

**Issue by meanstrong** [ansible/ansible#13631]
I run a task of MySQL_db，get result:

```
TASK: [mysql_db login_host=10.169.123.172 state=dump name={{ dump.db_name }} target=/tmp/.ansible/mysql/{{ dump.db_name }}.sql login_user=root login_password=abc$#@!8008CBA login_unix_socket={{ dump.socket }} login_port={{ dump.port }}] *** 
<10.169.123.172> ESTABLISH CONNECTION FOR USER: work
<10.169.123.172> REMOTE_MODULE mysql_db login_host=10.169.123.172 state=dump name=dev_grouplus target=/tmp/.ansible/mysql/dev_grouplus.sql login_user=root login_password=VALUE_HIDDEN login_unix_socket=/data/env/mysql/3306.sock login_port=3306
<10.169.123.172> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/work/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 10.169.123.172 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404 && echo $HOME/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404'
<10.169.123.172> PUT /tmp/tmpgoOneI TO /home/work/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404/mysql_db
<10.169.123.172> EXEC sshpass -d12 ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/work/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o ConnectTimeout=10 10.169.123.172 /bin/sh -c 'LANG=en_US.UTF-8 PATH=/home/work/env/mysql/default/bin LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/work/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404/mysql_db; rm -rf /home/work/.ansible/tmp/ansible-tmp-1450778852.97-95155618668404/ >/dev/null 2>&1'
failed: [TEST01] => {"failed": true}
msg: Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect


FATAL: all hosts have already failed -- aborting
```

I assigned any value login_user(localhost, 127.0.0.1, 10.169.123.172), the error message is localhost always.
For some reason, MySQL will refuse localhost but will accept 127.0.0.1 and 10.169.123.172.
such as I run in shell:

```
work@TEST01:/data/mysql$ mysqldump -u rocky -h localhost --socket=/data/env/mysql/3306.sock -p'abc$#@!8008CBA' dev_grouplus > 1.sql
Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'rocky'@'localhost' (using password: YES) when trying to connect
work@TEST01:/data/mysql$ mysqldump -u root -h 10.169.123.172 --socket=/data/env/mysql/3306.sock -p'XXXXXXXXX' dev > 1.sql
Warning: Using a password on the command line interface can be insecure.

work@TEST01:/data/mysql$ mysqldump -u root -h localhost --socket=/data/env/mysql/3306.sock -p'XXXXXXXXX' dev > 1.sql
Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by tersmitten** [comment]
`localhost` will force the usage of a local socket. `127.0.0.1` and all other ip addresses will use the TCP/IP protocol to connect. So that's why you see different behavior.

**Comment by meanstrong** [comment]
Thank you for your notify
when I use  127.0.0.1  and all other ip addresses in Ansible, It seems to be the same behavior with localhost，so how can I do in Ansible?
@tersmitten
