### ISSUE TITLE
[ansible 2.0 rc3] ec2_elb_lb health_check ping_path bug

### ISSUE THREAD

**Issue by usterk** [ansible/ansible#13633]
When I'm trying to create ELB instance with: 

``` yml
  - name: Create DEV ELB instance
    local_action:
      module: ec2_elb_lb
      name: "DEV"
      state: present
      region: eu-west-1
      subnets: XXX
      security_group_names:
        - YYY
      listeners:
        - protocol: ssl
          load_balancer_port: 443
          instance_protocol: tcp
          instance_port: 9000
          ssl_certificate_id: "arn:aws:iam::foo:bar"
      health_check:
          ping_protocol: http
          ping_port: 9000
          ping_path: "/status/"
          response_timeout: 10
          interval: 11
          unhealthy_threshold: 3
          healthy_threshold: 2
      connection_draining_timeout: 300
```

I'm getting error: 

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/a/.ansible/tmp/ansible-tmp-1450778407.13-211414384422020/ec2_elb_facts", line 2351, in <module>
    main()
  File "/Users/a/.ansible/tmp/ansible-tmp-1450778407.13-211414384422020/ec2_elb_facts", line 193, in main
    list_elb(connection, module)
  File "/Users/a/.ansible/tmp/ansible-tmp-1450778407.13-211414384422020/ec2_elb_facts", line 165, in list_elb
    elb_array.append(get_elb_info(elb))
  File "/Users/a/.ansible/tmp/ansible-tmp-1450778407.13-211414384422020/ec2_elb_facts", line 144, in get_elb_info
    'health_check': get_health_check(elb.health_check),
  File "/Users/a/.ansible/tmp/ansible-tmp-1450778407.13-211414384422020/ec2_elb_facts", line 124, in get_health_check
    'ping_port': int(port),
ValueError: invalid literal for int() with base 10: '9000/status/'

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"names": ["DEV"], "region": "eu-west-1"}, "module_name": "ec2_elb_facts"}, "parsed": false}
```

The problem disappears and the instance is created when I remove last `/` from `ping_path`.

``` yml
          ping_path: "/status"
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
