### ISSUE TITLE
prevent service start after package install (apt)

### ISSUE THREAD

**Issue by jeroenjacobs79** [ansible/ansible#13641]
How can I instruct ansible to not start a service after it is installed? With a standard apt-get command I can prevent this by creating a file "/usr/sbin/rc-policy.d" which always exists with an error code.

The apt module in Ansible, seems to ignore this file completely and services always start after install. This is causing me a lot of headaches as I'm using Ansible to create a disk-image (AMI) on AWS via Packer. 

Please tell me there is a way to prevent this? I am the systems engineer, it's my decision to tell when a service should start or not. Not the decision of the package manager.

**Comment by jimi-c** [comment]
Hi @jeroenjacobs1205, this is unfortunately outside of Ansible's domain, and is controlled by the way the package was created. It is standard practice to have apt packages start the service , so the only way to do this is to use a separate command (file or copy) to create that file before the apt task is run.

Beyond that, this is more of a general use question, and we reserve github issues for bugs and/or feature requests, so we'll close this now. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by papey** [comment]
Searching a way to prevent starting service when installing pkg with apt using ansible, here is how I do it : 

```- name: Ensure nginx-full
  apt: name=nginx-full
       state=present
  register: nginx
  environment:
    # do not start at the end of install
    RUNLEVEL: 1 
```

I just add a comment here to help people looking for answers.

**Comment by jtyr** [comment]
@papey Your way didn't work for me. I had to create `/usr/sbin/rc-policy.d` file to prevent the post-installation scripts from execution on Ubuntu 16.04.

**Comment by papey** [comment]
@jtyr yeah, this solution is not working anymore (do not know why)
