### ISSUE TITLE
Ansible Vault output does not look random

### ISSUE THREAD

**Issue by ngaya-ll** [ansible/ansible#13656]
Upon visual inspection of an encrypted Ansible Vault file, one notices a preponderance of 3s and 6s, especially at the start of lines.  This suggests there may be a bug in the implementation, since one would expected encrypted data to have a random distribution.

**Example:**

```
$ curl 'http://loripsum.net/api/5/long/plaintext' >example.txt
$ echo "password" >password.txt
$ ansible-vault encrypt --vault-password-file password.txt example.txt 
Encryption successful
$ <example.txt sed 's/./&\n/g' | grep [0-9] | sort | uniq -c
    517 0
   1068 1
   1098 2
   6218 3
    997 4
   1038 5
   4246 6
    547 7
    479 8
    503 9
$ head example.txt 
$ANSIBLE_VAULT;1.1;AES256
61353366313235356538313139356631346561643036313662626633323733343432336164376461
6665666161336361333736323165376662366133643235340a633766656463336431396632313436
63633164373037666366663839343362363536333435613835376665333162643533353131653764
6565663364393165300a353363316331336634313331663263363636636165343764366434313034
64316566633236313834306164636630663264313835306262366537343230656131303636366136
36376639333630353038636662343866373238313733383164636531363938323035303130613662
38323039313031366437393162613935316234353537363938366264323231313430663361386431
61333730393330373332316336323263646236363239646165613731656462333239323736396331
61373263376633363962323165383964383839633630663635663931353761353631643166343665  
```

Notice that 3 and 6 have significantly higher frequencies than the other digits.  Repeated experiments show that 3 and 6 are _always_ the most frequent digits in the encrypted output.

**Comment by amenonsen** [comment]
It's because the ciphertext is converted to hex and the output converted to hex again. The second time, the input is only [0-9a-f], and the hex representation of those characters is always in 30…39 and 61…66, hence the "preponderance of 3s and 6s". Apart from that, it also blows up the ciphertext to 4x its original size. If you think this is a silly thing to do, you're absolutely right. I wrote a patch for it long ago, but it was rejected for 2.0.

**Comment by jimi-c** [comment]
Closing, per the above.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
