### ISSUE TITLE
[expect module] fails with stacktrace

### ISSUE THREAD

**Issue by feliksik** [ansible/ansible#13660]
Using the expect module fails; I have the following playbook:

```
- name: Test expect module
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: expect something
    expect:
        command: ls
        responses:
            "(?i)somefilename": "ip address"
```

it fails with: 

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/eric/.ansible/tmp/ansible-tmp-1450949435.59-183529276834792/expect", line 2104, in <module>
    main()
  File "/home/eric/.ansible/tmp/ansible-tmp-1450949435.59-183529276834792/expect", line 155, in main
    events=events, cwd=chdir, echo=echo)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 224, in runu
    env=env, _spawn=spawnu, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 233, in _run
    cwd=cwd, env=env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1747, in __init__
    super(spawnu, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'echo'
Exception AttributeError: "'spawnu' object has no attribute 'closed'" in <bound method spawnu.__del__ of <pexpect.spawnu object at 0x7fb5fb53cd50>> ignored

fatal: [dev-nerdrouter-1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"command": "ls", "responses": {"(?i)somefilename": "ip address"}}, "module_name": "expect"}, "parsed": false}

```

I consider this a bug, as the module should never stacktrace. 
I have not succeeded in successfully using the module at all. 

System specs:

```
ansible: 2.0.0 rc3
python-pexpect: 3.2-1
ubuntu: 15.10
```

**Comment by bcoca** [comment]
So the problem seems to be with the expect library, the module does require pexpect >= 3.3, but I'm going to cc @sivel as author to see if he knows another workaround

**Comment by kgxsz** [comment]
Hi,

Was there ever any resolution to this?
I'm also seeing this with `pexpect (4.0.1)`.

Thanks!

**Comment by sivel** [comment]
In the original report the error was due to having pexpect 3.2 installed when the dependency is >=3.3.  We might be able to catch that exception to give an error that the version of pexpect is not sufficient.

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
