### ISSUE TITLE
maven_artifact module missing from 1.9.4 release

### ISSUE THREAD

**Issue by mcquinne** [ansible/ansible#13693]
I installed ansible via homebrew and started working on a playbook to pull jars from a maven repo and deploy them. I didn't get far though, because I get:

`ERROR: maven_artifact is not a legal parameter in an Ansible task or handler`

I did some digging and discovered that the 1.9.4 release tarball from releases.ansible.com (which is what homebrew uses) doesn't contain the maven_artifact module at all. You can verify with:

`curl -s https://releases.ansible.com/ansible/ansible-1.9.4.tar.gz | tar tf - | grep maven`

Other packaging modules from extras appear to be there, e.g. bower, but not maven_artifact. Is this an intentional exclusion or something about how the release was built?

Thanks in advance!

**Comment by jimi-c** [comment]
This module was added in 2.0, as indicated in the documentation for that module.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
