### ISSUE TITLE
Document easiest way to import and use functions from Ansible core modules

### ISSUE THREAD

**Issue by garthk** [ansible/ansible#13718]
G'day!

We're trying to replace nigh-unmaintainble bash scripts with maintainable Python scripts. The main gap is needing extra modules to support the kind of behaviour we used to get from the Linux command line. Ansible and Salt have Python code with all the behaviour we need. We're already using Ansible, but it has all that behaviour locked up behind the play runner. There's a Python API, but the "hello world" example needs Ansible 2 and is [44 lines long](http://docs.ansible.com/ansible/developing_api.html). I'm going to have a lot of trouble persuading the team to jump through those hoops. What they want to do is something like:

``` python
from ansible.modules.core.files import file as file_
file_(path='/tmp/DELETEME', state='absent')
```

The import fails because of the Ansible magic:

> `{"msg": "this module requires key=value arguments (['<<INCLUDE_ANSIBLE_MODULE_ARGS>>'])", "failed": true}`

Could someone point me to the machinery I need to import `file` and call its `main`? I can take it from there.

We've already got Ansible 1.9.x deployed. I'd like to re-use our experience on that as much as possible.

**Comment by garthk** [comment]
Root cause of the error happening on import: ansible/ansible-modules-core#2754.

Note fixing this simply defers the error to when we run `main()`. `module_utils/basic.py` still checks its local `MODULE_ARGS` and dies.

**Comment by sivel** [comment]
Importing a module is not an officially supported action.  Due to how modules are built, by effectively concatenating multiple files together before shipping them to the target machine, they aren't designed to be functional on their own.

Modules with all requisite code are built using `ansible.executor.module_common.modify_module`.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by abadger** [comment]
Your best bet may be to write some code to abstract the boilerplate and give your colleagues the simpler API they desire.  I would base that on Ansible-2 as we will eventually stop bugfixing 1.9.x (although it will be supported for a longer than normal time period) and 1.9 wasn't designed with an API in mind at all. The docs do contain information on how to code for pre-2.0 as well as 2.0 should you really need it: http://docs.ansible.com/ansible/developing_api.html#python-api-pre-2-0

If you base on 2.0, some people have also coded to a slightly higher level than our official docs: (example: http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/scripts/list-vms-per-host.v2 ) which may be easier to get working.  We're not sure whether we'll make changes at the level those are coded at though -- that level is really more for implementing our specific CLIs than being a library API so it may change as the CLIs evolve.

sivel posted the list and IRC information.  Those are probably the best places to go to for further information.

**Comment by garthk** [comment]
@sivel and @abadger: yeah, I started with `#ansible`. I'll check out `ansible.executor.module_common.modify_module`. Thanks.
