### ISSUE TITLE
win_copy module is slow

### ISSUE THREAD

**Issue by eoyslebo** [ansible/ansible#13747]
Copying a folder containing 60 files totaling 75 files took about 12 minutes on the first run, and 10 minutes on the second run (when the files were already there). 

This is OK for copying small text/config files, but magnitues slower then other methods.

**Comment by jhawkesworth** [comment]
Which ansible version are you using?
This is a known limitation in 1.9.x but it is much quicker in ansible 2.0
Please note part of the speed up is due to using pywinrm 0.1.1, so please upgrade that and retry.

**Comment by eoyslebo** [comment]
ansible 2.1.0 (devel 095790ac5c) last updated 2016/01/05 20:46:01 (GMT +200), pulled from github
/usr/local/lib/python2.7/dist-packages/pywinrm-0.1.1.dist-info, installed via pip

Ansible running on ubuntu 14.04, controlling latest Windows 10 Pro

**Comment by jhawkesworth** [comment]
Ok, well that ought to be good to go (although I haven't tried Win 10 Pro myself)
How big are the files you are transferring?
Is the traffic passing through a proxy?
What is the cpu and memory usage like on the ansible controller and win 10 pro machine during the transfer?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
