### ISSUE TITLE
[win_firewall_rule] Exception while executing: property 'failed' not found

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13741]
When trying to add a rule to the Windows Firewall via action 'win_firewall_rule', I get the following exception:

```
The property \u0027failed\u0027 cannot be found on this object
```

Detailed log:

```
<23.97.144.43> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\myuser\AppData\Local\Temp\ansible-tmp-1452107348.26-82312799693260\win_firewall_rule.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\myuser\AppData\Local\Temp\ansible-tmp-1452107348.26-82312799693260" -Force -Recurse -ErrorAction SilentlyContinue }
<23.97.144.43> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'<SOMEHEXCOMMAND_WHICH_I_SKIP_HERE>']
<23.97.144.43> WINRM RESULT u'<Response code 1, out "{"exception":"At C:\\", err "">'
<23.97.144.43> WINRM STDOUT {"exception":"At C:\\Users\\myuser\\AppData\\Local\\Temp\\ansible-tmp-1452107348.26-82312799693260\\win_firewall_rule.ps1:503 char:5\r\n+ if ($capture.failed -eq $true) {\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~","msg":"The property \u0027failed\u0027 cannot be found on this object. Verify that the property exists.","failed":true}
```

I have the following declaration in my playbook:

```
- name: Firewall rule to allow smtp on TCP port 25
  win_firewall_rule:
      direction: in
      name: smtp
      enable: yes
      state: present
      localport: 25
      action: allow
      protocol: TCP
```

I tried various ways of using the win_firewall_rule in the playbook: 
- see above
- action: win_firewall_rule with args on next line
- also the args on one line, with = instead of colon.
  But all ways lead to the same error.

Tried with both ansible 2.0 (stable-2.0 branch) and ansible 2.1 (devel branch).

**Comment by dreamcat4** [comment]
OK perhaps it is worth it to try to reproduce the exact same command line flags on the target machine, and catch the returned error message. Because it sounds like `netsh ...` cmd is failing for some reason.

I have done this approach myself to debug `win_firewall_rule` module. Because there is no other simple way to see the stdout / stderr being returned.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
