### ISSUE TITLE
ansible 2.0.0 run command mysql have diffrent behavior with in shell

### ISSUE THREAD

**Issue by meanstrong** [ansible/ansible#13760]
My ansible version:

```
ansible 2.0.0 (detached HEAD a2a786ed0c) last updated 2016/01/08 10:40:22 (GMT +800)
  lib/ansible/modules/core: (detached HEAD a18306fb04) last updated 2016/01/08 10:40:40 (GMT +800)
  lib/ansible/modules/extras: (detached HEAD 9264339cbb) last updated 2016/01/08 10:40:40 (GMT +800)
  config file = /data/GRP/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

When I run a shell module with MySQL command,I get follow error:

```
fatal: [TEST01]: FAILED! => {"changed": true, 
"cmd": "mysql -h 127.0.0.1 -uroot -pabc$#@!8008CBA -P 3306 -S /data/env/mysql/3306.sock rocky < /tmp/.ansible/mysql/rocky.sql",
 "delta": "0:00:00.014157", "end": "2016-01-08 11:13:11.997750", "failed": true, "rc": 1, 
"start": "2016-01-08 11:13:11.983593",
 "stderr": "Warning: Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)", "stdout": "", "stdout_lines": [], "warnings": []}
```

But when I copy the cmd string and run it Manually，It is OK.

```
work@TEST01:~$ mysql -h 127.0.0.1 -uroot -p -P 3306 -S /data/env/mysql/3306.sock rocky < /tmp/.ansible/mysql/rocky.sql
Enter password: 
work@TEST01:~$ 
```

I do not know why? Somebody can help me?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
