### ISSUE TITLE
Ansible-playbook: Trouble with sudo parametrized

### ISSUE THREAD

**Issue by Wodric** [ansible/ansible#13768]
# Environnement

Ansible 1.9.4 on Debian 7.7
Hosts are on Debian 7.7 too.
# Case

I'm creating a playbook to automate client delivery. 
During my test, I'm focus on how to manage the environnement which need "sudo" authorization to manage my tomcats. 
So, on plays which need to be execute in sudo, I try to add "sudo" parameter and parametrize it in that way:
On group_vars/all I add:

> sudo_needed : yes 

I also test with "True" and "true" values with same behaviour.

My testing playbook is : 

```
- name: Shutdown all liferay instance
  hosts: LR_all
  sudo: "{{ sudo_needed }}"
  remote_user: pentila
  vars:
     command: stop
     command_timeout: 75
  roles:
  - liferayCommand
```

I also test with "sudo: "{{ sudo_needed | bool }}" and "{{ sudo_needed }} | bool" values with same behaviour.

In all case the sudo was considered at false (it's default value I think) with the following command :

> ansible-playbook -i hosts main2.yml -K

But if, I try to remove the variable "sudo_needed" from group_vars/all and add it on my command line:

> ansible-playbook -i hosts main2.yml -K --extra-vars "sudo_needed"=true

My play is launch as sudo and succeed
# Sources

My role liferayCommand:

```
- name : Execute command to liferay instance
  command: "./{{ tomcat_service_script }} {{ command }}"
  async: "{{ command_timeout }}"
  poll: 5
  when : command == "start" or command == "restart" or command == "stop"

- name :  Verify liferay are start
  wait_for: port="{{ liferay_tomcat_http_port }}" timeout=60 state=started
  when : command == "start" or command == "restart"

- name :  Verify liferay are stop
  wait_for: port="{{ liferay_tomcat_http_port }}" timeout=60 state=stopped
  when : command == "stop"
```
# Question

Why this case works with variable in my command line and not with global varaible define on group_vars/all?

**Comment by jimi-c** [comment]
Hi @Wodric, the problem here is that you're setting the sudo option on the entire play based on the value which is host-specific. Move the `sudo: "{{ sudo_needed }}"` to each task where you may need sudo and this should work as you expect.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
