### ISSUE TITLE
bug for "ansible docs search is broken" should be reoppened

### ISSUE THREAD

**Issue by ian-kelling** [ansible/ansible#13783]
Since it's not fixed, and people have been commenting saying so but we don't have the ability to reoppen the bug.

**Comment by jimi-c** [comment]
We are aware of the issue, and are in the process of migrating to a different site search. We'll hold this open until it is corrected.

cc @docschick

**Comment by arthur-c** [comment]
Hi,

The new search system is not usable: indexes are in the left column but the search button is at the bottom right, and we have a tiny result window. I know the old search system is broken but it was really (really) good and practical, the new one makes me to go on duckduckgo to search the doc.

We have a quick result when we know the module name, but when we don't it's a real pain to find something. Example:
"site:http://docs.ansible.com/ ec2 ebs" on duckduckgo or google -> expected answers and ec2_vol in top results.
"ec2 ebs" on "search this site button": very few interesting answers and ec2_vol in the third page, it should be in top results.

And by the way the duckduckgo ansible bang is broken (https://duckduckgo.com/bang?q=ansible).

The doc is awesome, it's sad to not be able to use it properly !

**Comment by docschick** [comment]
@arthur-c -- I'm sorry you aren't having much luck with the new search site. Luckily, we have the ability to customize it a bit as well as work on how search results are ranked. I can work on the "ec2 ebs" terms, as an example, to ensure ec2_vol hits higher as a priority. Thanks for that example. 

We know we have work to do to get the new search fully customized, but I feel confident it also offers the tools we need to do so. When our old site search broke, we couldn't seem to fix it and it was based on a change that happened long before it actually broke. Nothing we did seemed to help.

As for the search button at the bottom right, this change was made so that the search stays in the window for you at all times, so that you don't have to go back to the top of the document to find the search box. It took me a little while to get used to it, but having it always available on the page, no matter how deep you are in a section, has been helpful.  We can look at making the results window larger though. I'll make a note to do that, too.  (And honestly, if the community really doesn't take to the new location of the search button/box and wants it back at the top left in the index, we'll make that happen. For now, I think it is a change worth trying out and waiting for more feedback.) 

Thanks for the feedback. Having proper search results is a must have and we'll continue improving upon them. 

Cheers!

**Comment by ian-kelling** [comment]
Privacy badger blocks the new swiftype search engine. :(

**Comment by jimi-c** [comment]
@ian-kelling and it didn't block the old one from Google?

**Comment by ian-kelling** [comment]
@jimi-c, dunno. Didn't use the old one before it was broken. But I doubt it: I've had privacy badger on for months and this is the first time I've noticed something broken.

**Comment by bcoca** [comment]
privacy badger does not block the google one (been using it for a long time, even when google one was working). In any case you can whitelist (even if just temporarily) the switftype site in privacy badger (does not seem to block it for me, so I don't think its the default).

**Comment by ian-kelling** [comment]
Privacy backer does block it by default, because I'm using a default install, and I updated to the latest to verify. privacy badger learns what tracks you then blocks it, and does most of it by seeing things track you across multiple sites, so nothing will be blocked on the 1st site you visit with privacy bagder on. Once it learns about swiftype, it blocks it. 

Yes, the blocking can be disabled, but the bigger issue, which I thought went without saying, is why exactly is it blocked by privacy badger? Is swiftype tracking me and invading my privacy? I haven't investigated exactly how privacy badger works, but afaik it does. Is that an appropriate thing for ansible to do to it's users? I don't think so. Oh ya, feel free to close this as search is working. We can open more specific bugs related to search.

**Comment by jimi-c** [comment]
Ok yes going to close this now as we have search reimplemented. Any further issues can be discussed on the mailing list:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
