### ISSUE TITLE
Confusing error message, error caused by non existing container name provided in volumes_from is not handled correctly

### ISSUE THREAD

**Issue by akwasnie** [ansible/ansible#13807]
Issue Type:
Bug report

Ansible Version:
ansible 1.9.4

Ansible Configuration:
not modified

Environment:
Kernel Version: 3.19.0-33-generic
Operating System: Ubuntu 14.04.3 LTS

Summary:
Error caused by non existing container name provided in volumes_from is not handled correctly.

Steps To Reproduce:
Run ansible-playbook with the following role (provide non-existing container name in volumes_from param):
- name: Run container  
  docker:  
        name: ubuntu-test  
        image: "ubuntu:latest"  
        state: started  
        volumes_from:  
          - "non_existing_container_name"  
  run_once: "True"  

Expected Results:
Failed with msg: no such name: non_existing_container_name

Actual Results:
< TASK: run | Run container >
failed: [localhost] => {"changed": false, "failed": true}
msg: Docker API Error: Conflict. The name "ubuntu-test" is already in use by container ce5897eb83ab. You have to delete (or rename) that container to be able to reuse that name.

FATAL: all hosts have already failed -- aborting

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
