### ISSUE TITLE
Python not found on ubuntu 15.04 (client server)

### ISSUE THREAD

**Issue by AlmogBaku** [ansible/ansible#13829]
```
/bin/sh: 1: /usr/bin/python: not found
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
```

I expect ansible to install python in cases such as this

**Comment by modprobe** [comment]
You install ansible, _ignore_ its dependencies and then expect it to fix that _by itself?_

<img src="https://cloud.githubusercontent.com/assets/4273389/12288238/a3f93b40-b9d2-11e5-8691-1d98e02c5c10.jpg" width="333">

On a more serious note: If you install ansible via your package manager then its dependencies will also be installed. But you will most probably not get the latest version (on Ubuntu 15.04 you will get 1.7.2)

**Comment by AlmogBaku** [comment]
I'm talking about the CLIENT SERVER.
When you try to deploy a new server, i expect it will fix the server's dependencies, and install there python.

**Comment by amenonsen** [comment]
Your expectation is incorrect. Ansible will not do that. (But you can use the raw module to run "apt-get install -y python" or similar yourself.)

**Comment by bcoca** [comment]
Ansible requires python to be installed on the targets http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

You CAN use the `raw` module to install missing python if needed, but this is not automatic nor do we think it should be.

**Comment by AlmogBaku** [comment]
@bcoca the thing is, you cant actually do anything before the "getting facts" is done, and it requires the python.

Also, it's not minor issue since a ubuntu 10.04 is pretty common

**Comment by bcoca** [comment]
set`gather_facts: no` or use the ad-hoc command shown in the docs.

**Comment by abadger** [comment]
(Note: s/10.04/15.04/ in your last comment I believe)

Fedora switched to not having /usr/bin/python installed by default last year and went through the same issue.  This Fedora Magazine article should help you get up and running: https://fedoramagazine.org/getting-ansible-working-fedora-23/  Just substitute apt-get instead of dnf and the package names you need instead of the fedora-specific names for python2 and the python2 bindings for their package manager.

We'd also be happy to either point to or add documentation to our FAQ with that sort of information tailored to Ubuntu/other distros if someone would like to contribute a PR.
