### ISSUE TITLE
--start-at-task failures

### ISSUE THREAD

**Issue by jacobweber** [ansible/ansible#13864]
I'm seeing some bugs when I run `ansible-playbook test.yml --start-at-task` using Ansible 2.0.0.1. I'm only seeing them on playbooks with multiple hosts (in this example, host1 and host2). The gist is that it seems to only obey the --start task on the first host. It starts from the beginning on the second host, and also mis-labels the first task as "setup".
### Source code

test.yml:

```
- hosts: my_hosts # this is a group containing two hosts
  become: yes 
  roles:
    - foo
    - bar
```

roles/foo/tasks/main.yml:

```
- name: one
  debug: msg="one"
- name: two
  debug: msg="two"
```

roles/bar/tasks/main.yml:

```
- name: three
  debug: msg="three"
- name: four
  debug: msg="four"
```
### Example 1

When I run `ansible-playbook test.yml --start-at-task 'two'`, it still runs the first task ("one") on one of the hosts, but mis-labels it "setup":

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [host2]

TASK [setup] *******************************************************************
ok: [host2] => {
    "msg": "one"
}
ok: [host1]

TASK [foo : two] ***************************************************************
ok: [host1] => {
    "msg": "two"
}
ok: [host2] => {
    "msg": "two"
}

TASK [bar : three] *************************************************************
ok: [host1] => {
    "msg": "three"
}
ok: [host2] => {
    "msg": "three"
}

TASK [bar : four] **************************************************************
ok: [host1] => {
    "msg": "four"
}
ok: [host2] => {
    "msg": "four"
}
```
### Example 2

When I run `ansible-playbook test.yml --start-at-task 'three'`, it still runs the first two tasks ("one" and "two") on one of the hosts, and mis-labels the first task "setup":

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [host2]

TASK [setup] *******************************************************************
ok: [host2] => {
    "msg": "one"
}
ok: [host1]

TASK [foo : two] ***************************************************************
ok: [host2] => {
    "msg": "two"
}

TASK [bar : three] *************************************************************
ok: [host1] => {
    "msg": "three"
}
ok: [host2] => {
    "msg": "three"
}

TASK [bar : four] **************************************************************
ok: [host1] => {
    "msg": "four"
}
ok: [host2] => {
    "msg": "four"
}
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
