### ISSUE TITLE
"with_items" doesn't work as expected with "delegate_to" in haproxy module

### ISSUE THREAD

**Issue by mike-grayhat** [ansible/ansible#13880]
Issue Type:
Bug Report

Ansible Version:
ansible==2.0.0.0

Summary:
Delegation happens only on first host in with_items

Steps to reproduce:

```
- hosts: webservers
  serial: 1
  become: yes

  tasks:
    - name: Take out of load balancer
      haproxy:
        state=disabled
        host={{ inventory_hostname }}
        socket={{ ha_stats_socket }}
        backend=web_backend
      delegate_to: "{{ item }}"
      with_items: groups.webservers
```

Also results seems strange (presence of None)

PLAY ***************************************************************************

TASK [Take out of load balancer] ***********************************************
changed: [ha1 -> None] => (item=ha1)
ok: [ha1 -> None] => (item=ha2)

PLAY ***************************************************************************

TASK [Take out of load balancer] ***********************************************
changed: [ha2 -> None] => (item=ha1)
ok: [ha2 -> None] => (item=ha2)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by FlorinAndrei** [comment]
This still happens with 2.0.1.0

**Comment by mike-grayhat** [comment]
Can't reproduce the bug with 2.0.1.0, everything is working fine.
