### ISSUE TITLE
Failed host starts executing when include after failure

### ISSUE THREAD

**Issue by renekalff** [ansible/ansible#13893]
**Issue Type: Bug Report**

**Ansible Version:**
ansible 2.0.0.1
  config file = /Users/rkalff/Projects/TestProjects/ansible_bug_report_1/ansible.cfg
  configured module search path = Default w/o overrides

**Ansible Configuration:**

```
[defaults]
hostfile = hosts
remote_user = vagrant
private_key_file = ~/.vagrant.d/insecure_private_key
host_key_checking = False
```

**Environment:**
OS X El Capitan (10.11.1)

**Summary:**
This issue wasn't resolved by #13699.

When the failure occurs in an included task file and there is another included task file after the failure the failure is not respected and different tasks run in parallel on different hosts. In other words, the failed host starts executing from failure point later in the playbook. See test5.yml.

All tests run as expected on 1.9.3

**Steps To Reproduce:**
See https://github.com/renekalff/ansible_bug_report_1
Run: ansible-playbook -i hosts test5.yml

**Expected Results:**
That no tasks are executed for a host after it's being marked as failed.

**Actual Results:**
See: https://github.com/renekalff/ansible_bug_report_1/blob/master/play_results/test5

**Comment by jimi-c** [comment]
Looks like the `stable-2.0` branch was missing 210cf06d9ac8e62b15d6f34e9c63c1b98986a1d5 and 6ec4d98764b14cffeb7f8b43c01e015b67237753, so I've cherry-picked those over now, which has resolved the problem there. We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by renekalff** [comment]
Sorry for not having checked that. I can confirm that it works as expected with 210cf06 and 6ec4d98.

**Comment by jimi-c** [comment]
No problem, sorry for having missed including them in 2.0.0.0.

**Comment by renekalff** [comment]
Just wondering, why didn't this go in 2.0.0.2 last night. I can work from the stable-2.0 branch but I do think it can mess-up playbook execution quite a bit.

**Comment by jimi-c** [comment]
2.0.0.2 was (mostly) a packaging fix. We're looking at cutting 2.0.1 rc1 early next week, which will include this.

**Comment by renekalff** [comment]
A perfect, was just wondering how the ansible release cycle works.
