### ISSUE TITLE
Bug report: lineinfile keep on adding line=

### ISSUE THREAD

**Issue by erkules** [ansible/ansible#13909]
$ ansible --version
ansible 1.9.2

Ubuntu 15.04 

lineinfile is supposed not to add a line if a regex does not match. As a fact it does keep on adding lines.
i.e. 

lineinfile: "dest=/etc/network/interfaces  state=present regexp='^iface eth1 inet dhcp' line='iface eth1 inet static'"

Before first run:
iface eth1 inet dhcp
1. run
iface eth1 inet static
2. run
iface eth1 inet static
iface eth1 inet static
3. run
iface eth1 inet static
iface eth1 inet static
iface eth1 inet static

and so on

**Comment by bborysenko** [comment]
@erkules it's not a bug, take a look on #4531 for details 

[Default behavior is](http://stackoverflow.com/a/21934455/1319082):

```
find
 if found
   replace line found
 else
   add line
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
