### ISSUE TITLE
dnf.exceptions.DepsolveError

### ISSUE THREAD

**Issue by leocrawford** [ansible/ansible#13930]
I've just upgraded to ansible 2.0.0.1, from the latest version (1.9.?) and 

```
- name: remove packages
  package: name={{item}} state=absent
  with_items:
   - libreoffice-core
```

now produces:

> failed: [default] => (item=[u'libreoffice-core']) => {"failed": true, "item": ["libreoffice-core"], "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 2284, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 345, in main\r\n    ensure(module, base, params['state'], params['name'])\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 296, in ensure\r\n    if not base.resolve():\r\n  File \"/usr/lib/python2.7/site-packages/dnf/base.py\", line 547, in resolve\r\n    raise exc\r\ndnf.exceptions.DepsolveError: package libreoffice-xsltfilter-1:5.0.0.5-2.fc23.x86_64 requires libreoffice-core = 1:5.0.0.5-2.fc23, but none of the providers can be installed\r\n", "msg": "MODULE FAILURE", "parsed": false}

If I do 

```
sudo dnf remove libreoffice-core
```

from the command line then it works fine.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
