### ISSUE TITLE
os_router breaks idempotent

### ISSUE THREAD

**Issue by roylez** [ansible/ansible#13943]
The following code runs okay when the router is not yet created, afterwards it throws an error.

```
- name: add a router
  os_router:
    cloud: stack-user
    name: router0
    state: present
    network: ext
    interfaces:
      - int_sub
```

```
TASK [openstack-user : add a router] *******************************************
task path: /home/ubuntu/ansible/roles/openstack-user/tasks/main.yml:12
ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523 )" )
localhost PUT /tmp/tmpDk_OhR TO /home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/os_router
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/env python /home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/os_router; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/os_router", line 2398, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/os_router", line 323, in main
    if _needs_update(cloud, module, router, net, internal_ids):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1453083841.07-188624998584523/os_router", line 202, in _needs_update
    for port in cloud.list_router_interfaces(router, 'internal'):
  File "/home/ubuntu/.env/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 1724, in list_router_interfaces
    if router['external_gateway_info']
KeyError: 'external_fixed_ips'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "os_router"}, "parsed": false}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
