### ISSUE TITLE
Task fails when variable in with_items is undefined, even when task should be skipped

### ISSUE THREAD

**Issue by mstrzele** [ansible/ansible#13950]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

Ubuntu 12.04
##### Summary:

When the variable is used inside `with_items` loop and it's undefined, task fails, even if it's skipped by using `when` statement.
##### Steps To Reproduce:

``` yaml
- hosts: localhost
  vars:
    foobar: false
  tasks:
    - debug: var={{ foo }} 
      when: "{{ foobar }}"
    - debug: var={{ item }}
      with_items:
        - "{{ foo }}"
        - "{{ bar }}"
      when: "{{ foobar }}"
```
##### Expected Results:

Task should be skipped and variable shouldn't be even parsed.

Below is the output from playbook execution using Ansible 1.9.4:

```
 [WARNING]: It is unnecessary to use '{{' in conditionals, leave variables in
loop expressions bare.


PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var={{ foo }}] *************************************************** 
skipping: [localhost]

TASK: [debug var={{ item }}] ************************************************** 
skipping: [localhost] => (item={# foo #})
skipping: [localhost] => (item={# bar #})

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

Task fails, because variable is undefined:

```
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'foo' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
`when` is evaluated AFTER `with_items`, as to allow conditions per item loop iteration, so it cannot stop `with_items` with an undefined value. Use the `foo|default([])` filter to return an empty list to skip this task.

**Comment by boscowitch** [comment]
This  WHEN beeing evaluated after leads to a lot of headaches in another use case... 
took me a while to find it since i wanted to skip a whole role / include with a condition which normally works.... 
unfortunately i had to read later that it does not stop the include but adds a when condition to all sub taks... which lead to similar with_items/when contruct to fail the role even though it should be skipped all together when a variable is undefined....

```
- name: only run if webapps is defined
  include: all.yml
  when: webapps is defined
```



and in all.yml
```
- name: create webapps directories
  file: path="/var/www/{{ webapps[item].url  }}/public" state=directory mode=0755
  with_items: "{{ webapps }}"
  when: webapps is defined
```

bcoca solution here is therefore more a workaround for that situation since working manually through all roles maybe even third party roles to fix, is a heavy task just for skiping whole rolses/includes ... 

The best fix would be for me atm to enable include and roles to be really skipped entirely on a condition.
or add another when that is definitly evaluated before a any task also with item tasks are evaluated...
