### ISSUE TITLE
Ansible 2.0 docker with state: restarted stops and removes running container. 

### ISSUE THREAD

**Issue by makelly** [ansible/ansible#13953]
Ansible version 2.0.0.2
Docker engine version 1.9.1, API version 1.21

Previous working playbook now giving error.
- name: Deploy Nagios
  hosts: all
  become: True
  vars:
    ...
  vars_files:
    ... 
  tasks:
    ...
  - name: Install Nagios
    docker:
      name: ciao-nagios
      image: cpuguy83/nagios
      state: restarted
      restart_policy: always
      ports:
    - "8081:80"
      volumes:
    - "{{ nagios_config_directory }}:/opt/nagios/etc"
- name: Deploy Nagios host and service configurations for monitoring
  hosts: all
  become: True
  vars_files:
    ...
  tasks:
    ...
  - name: Restart Nagios
    docker:
      name: ciao-nagios
      image: cpuguy83/nagios
      state: restarted

At this point playbook fails with:

fatal: [chico]: FAILED! => {"changed": true, "failed": true, "msg": "Docker API Error: no such id: 6aa867ef00ed5a58e931aa0a94a3783d2039c306fce272120e6be7054a0ed748"}

The docker container is not running (docker ps) nor is there a container defined any more (docker ps -a). The docker image is still there (docker images). By omitting the restart task the playbook completes successfully and the docker container is up and running.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by jesuscript** [comment]
+1. seeing the same behaviour with a mongodb container
