### ISSUE TITLE
default epel-6 ansible.cfg file

### ISSUE THREAD

**Issue by laroche** [ansible/ansible#1397]
The default epel-6 ansible.cfg config file should maybe not include
the "-o ControlPersist=60s" option as it is not supported with the shipped openssh.

One less little point to just use ansible without any change.

best regards,

Florian La Roche

**Comment by mpdehaan** [comment]
Yeah, the thing is Ansible's connection performance without ControlPersist pretty much means you want to use paramiko on EL-6.   By leaving it in, we allow ansible to warn the user about this information and then take it out, or to consider using paramiko.   This signalling is very important for folks to have a good experience with ansible, as they now know that if they want to use openssh at maximum speed, they might wish to run it from a newer client.

This way, they end up using paramiko and are reasonably happy.

In the end, it works out pretty well for most users and we don't get a lot of questions about it, or complaints about speed, because folks will either hop to a newer client (like a Fedora) or use paramiko.   Those that still want to use it can just edit their setting.

I like having the configuration file the same for all distributions insofar as much as we don't need to start accounting for major distribution variance that we can't detect at runtime.   That time hasn't come yet.

Anyway, thanks very much for the suggestion! -- just wanted to give you the reasons for why it is the way it is

--Michael
