### ISSUE TITLE
mysql_user module: invalid privileges string

### ISSUE THREAD

**Issue by milky-milk** [ansible/ansible#13983]
Hello.
##### Ansible Version:

```
ansible --version

ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default, excluding `private_key_file` option
##### Environment

Debian GNU/Linux 8
##### Summary

I'm not sure, is it documentation bug, or module bug.
Maybe it is not working with privileges with spaces, or documentation is wrong.
https://docs.ansible.com/ansible/mysql_user_module.html

```
- mysql_user: name=replication password=12345 priv=*.*:"REPLICATION CLIENT" state=present
```

Trows an error 

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "invalid privileges string: Invalid privileges specified: frozenset(['\"REPLICATION SLAVE\"'])"}
```

But construction like 

```
- mysql_user: name=replication password=12345 priv="*.*:REPLICATION SLAVE" state=present
```

works fine.
##### Steps To Reproduce:

Create a playbook that uses the mysql_user module like this:

```
- mysql_user: name=replication password=12345 priv=*.*:"REPLICATION CLIENT" state=present
```

And you can see an error, shows the privileges string is wrong.
##### Expected Results:

Creating a mysql user 'replication'@'localhost' with password '12345' and 'REPLICATION CLIENT' privileges.
##### Actual Results:

Error, shows the privileges srting is wrong

```
FAILED! => {"changed": false, "failed": true, "msg": "invalid privileges string: Invalid privileges specified: frozenset(['\"REPLICATION SLAVE\"'])"}
```

If it is an error in documentation - can I submit a PR? 
Thanks.

**Comment by metajungle** [comment]
I've also come across this on Ansible version 2.0.0.2, and applied the same fix (moved the quotes) and it seemed to work... at any rate, the current examples in the documentation do not work.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by jimi-c** [comment]
Just as a quick follow-up, you can simply open a PR on the correct repo, rather than an issue followed by a PR.

Thanks!
