### ISSUE TITLE
Cannot access group variable when using dynamic includes

### ISSUE THREAD

**Issue by nextrevision** [ansible/ansible#14003]
Given the following:

```
# /inventory/hosts
control01
[control]
control01

# /playbooks/site.yml
- include: precheck.yml
  when: "'bootstrap' not in groups"

- hosts: bootstrap
  tasks:
    - debug: var=bootstrap

# /playbooks/precheck.yml
- hosts: control
  tasks:
    - name: create bootstrap group
      add_host: >
        hostname={{ groups['control'] | sort | first }}
        groups=bootstrap
```

When running with 2.0.0.2, I get the following:

```
ERROR! The conditional check ''bootstrap' not in groups' failed. The error was: ERROR! error while evaluating conditional ('bootstrap' not in groups): ERROR! ERROR! Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.

The error appears to have been in '/playbooks/site.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include: precheck.yml
  ^ here
```

I've removed the logic that makes this actually useful, but is this no longer supported as of 2.x? This has been working well in 1.9.4, but moving to 2.x it seems that access to the group variable is no longer available when dynamically including other files. I currently use this pattern of prechecks in other playbooks, and don't want to add the `when` logic to each task in the precheck playbook. If this is just a result of the way includes have been refactored, I can try to find a way around it, but didn't know if this was to be expected or not.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
