### ISSUE TITLE
Cannot run setup

### ISSUE THREAD

**Issue by bananabr** [ansible/ansible#14035]
I have just started with ansible and have a couple of freeBSD machines that I would like to manage. As I was following the documentation, it presents the setup module, which I understood is critical for ansible to work properly.
When I try to run this on any of my bsd boxes, this is what I have in return:

hostname | FAILED! => {
"changed": false,
"failed": true,
"module_stderr": "",
"module_stdout": "Traceback (most recent call last):\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 5197, in <module>\r\n main()\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 140, in main\r\n data = run_setup(module)\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 84, in run_setup\r\n facts = ansible_facts(module)\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 5132, in ansible_facts\r\n facts.update(Facts().populate())\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 2284, in **init**\r\n self.get_service_mgr_facts()\r\n File \"/home/PMPA/danielb.santos/.ansible/tmp/ansible-tmp-1453322134.0-207565130016853/setup\", line 2684, in get_service_mgr_facts\r\n proc_1 = os.path.basename(get_file_content('/proc/1/comm'))\r\n File \"/usr/local/lib/python2.7/posixpath.py\", line 114, in basename\r\n i = p.rfind('/') + 1\r\nAttributeError: 'NoneType' object has no attribute 'rfind'\r\n",
"msg": "MODULE FAILURE",
"parsed": false
}

Anything I have to have installed in the managed host besides python 2.7 ?

**Comment by bcoca** [comment]
no, that was a temporary bug in devel that is already fixed in the latest HEAD.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
