### ISSUE TITLE
Argument 'priv' from 'mysql_user' won't apply grant ALL privileges

### ISSUE THREAD

**Issue by jonatasbaldin** [ansible/ansible#14062]
Hi,

It seems that the priv argument from mysql_user is not working. Here's the code:

```
- name: Grant privileges to MySQL DB                                                                               
  mysql_user: name={{ zabbix3server_db_user }} password={{ zabbix3server_db_user_password }} priv:{{ zabbix3server_db_dbname }}.*:ALL state=present                                                                                   
```

In the MySQL, it returns:

```
mysql> show grants for 'zabbix'@'localhost';
+---------------------------------------------------------------------------------------------------------------+
| Grants for zabbix@localhost                                                                                   |
+---------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'zabbix'@'localhost' IDENTIFIED BY PASSWORD '*8C36F49E0B5A6D03AC2F7734354CA4C39C39EE7B' |
+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

I'm using Ansible 2.0.0.2.

```
ansbile --version
2.0.0.2
```

Thanks.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
