### ISSUE TITLE
Ansible 2 ignored host-vars from inventory file: variables priority was changed or it is a bug?

### ISSUE THREAD

**Issue by KIVagant** [ansible/ansible#14067]
I created [a gist](https://gist.github.com/KIVagant/4d8c5a41e6107864ed75) with the problem explanation.

Briefly, when I upgraded ansible from 1.9.4 to 2.0.0.2, I got a strange behaviour and after investigation I found that variables priority now changed. It is really critical changes, especially for production environments.

Ansible 2 now get variables from a group_vars/\* folders instead of `[group:vars]` section from the inventory file.
It's a new normal behaviour?

**Comment by bcoca** [comment]
Ansible always got group_vars from both locations, with the directory having priority over the inline file definitions.  Leaving this open to check if the priority with the 'all' group handling has changed.

**Comment by KIVagant** [comment]
Thank you, @bcoca. I will wait for more information.

**Comment by matlockx** [comment]
any news on this?

**Comment by bcoca** [comment]
yes, still trying to figure out the correct fix, when we defined variable priority we did by source, but this used to work in a mixed mode. 

Groups were loaded from all sources each one was overwritten, then after all sources they were merged by group. 

Currently we merge by source immediately so the 'all' group on a source with higher priority now overwrites other groups from lower priority.

**Comment by KIVagant** [comment]
Sorry for my bad English.
I don't thinking that my mind is really correct, but for me the previous behaviour was more usable and more understandable. Because the "ini"-inventory-file seems like more high level that the groups *.yml configuration. Especially more high level that the global configuration.
I'll try to explain it like this:
- the groups yml-configuration have much more variables than the connected inventory file.
- so, it's conveniently to use the inventory file for placing most-important and most often changed variables.
- and I don't need to create special group folder with the yml-file inside for overriding just one variable from all/something.yml config.

**Comment by gujo** [comment]
+1 on this issue. Seems like 2.0 handles variable precedence as the documentation states, however this behaviour breaks backwards compat with 1.9.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by KIVagant** [comment]
Thank you, @jimi-c .
I'll test the fix after release.

**Comment by aperigault** [comment]
Good news !

Before ansible 2.0 inventory group vars are also load after script group vars.
Can we move line 249 after 256 ? For people that use ansible tower to manage inventory is a big problem.
Thank you
