### ISSUE TITLE
Mount module on OSX

### ISSUE THREAD

**Issue by kpaleniu** [ansible/ansible#14076]
As far as I can tell, mount module works the same way on every POSIX-compatible OS. This means it writes entries to `/etc/fstab` and runs `mount` when appropriate. However, OSX seems to be a major pain in the ass if you try to mount stuff as you would normally. I keep running into corner-cases when trying to mount smb shares that require authentication. For example, this works.

```
- mount:
    state: mounted
    fstype: smbfs
    opts: soft
    src: //some.user:pass@foo/bar
    name: /mnt/bar
```

It fails if `some.user` was `some-user` instead by giving `No route to host` error. I suspect this triggers some weird bug in `mount_smbfs`. Also, if you leave out `opts`, this defaults to `-o defaults` which for whatever reason does not exist as an option for `mount_smbfs`. Also, I am pretty sure that due to the way OSX handles mounts `/etc/fstab`, all opts are ignored anyway because of `automount`.

The less broken way seems to be to use `automount`. The simplified explanation how it works is that `automount` reads its configuration from `/etc/auto_master`. To add mounts, you create a mapping file, e.g `/etc/auto_ansible` that looks roughly like this.

```
bar        -fstype=smbfs,soft    smb://some-user:pass@foo/bar
```

Then you add this to `/etc/auto_master` by adding the following line.

```
/mnt      auto_ansible
```

This entry maps that all mappings in `auto_ansible` are mounted under `/mnt`. Finally you invoke the following to do the equivalent of `mount -a`.

```
$ sudo automount -c
```

Now my question finally is, could this be implemented at some point?

**Comment by kpaleniu** [comment]
Forgot to mention one more OSX oddity. If you bypass `/etc/fstab` altogether and just run from command line, this works.

```
$ sudo mount -t smbfs //some-user:pass/foo/bar /mnt/bar
```

And before anybody ineviteably asks, I am using OSX El Capitan.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
