### ISSUE TITLE
rsync deprecation should not emitted when both paths are on inventory host

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#14092]
I don't see a way to use `synchronize` to rsync between two paths on the remote host, so there's no real alternative to using rsync inside `shell`, but the deprecation will be emitted every time I run my playbooks...

I think Ansible should either:
1. Detect this usage of rsync and not emit a deprecation for it
2. Add a mode for `synchronize` allowing synchronization of two remote paths...

**Comment by abadger** [comment]
There are a lot of problems with the "use this module instead of shell
mechanism" however, for the use case specified here it actually is possible
to use synchronize on this manner.

```
- hosts: remote1
  tasks:
  - synchronize:
      src: /etc
      dest: /backup/
    delegate_to: "{{inventory_hostname}}"
```

By using the same host in both the hosts and delegate_to field instruct
synchronize to execute the copy on the delegate_to host and copy it to that
same host.

This treatment of delegate_to is specific to synchronize.  It may or may
not have been a bug when delegate support was originally coded into the
module but it has long ago become a feature of the module.

The module documentation should explain this in the notes section but if it
isn't clear, feel free to propose updates top that documentation.

**Comment by abadger** [comment]
I'm going to close this as there is a way to do a remote => remote copy with the synchronize module.

**Comment by vmalloc** [comment]
@abadger The 'workaround' does not seem to actually work - getting `unsupported parameter for module: delegate_to` (with latest ansible).

Please reopen as this is not a valid workaround to eliminate the warning...

**Comment by vmalloc** [comment]
@abadger opened a new issue for the delgate_to capability on `synchronize`
