### ISSUE TITLE
Longer AWS EC2 instance IDs not used

### ISSUE THREAD

**Issue by gavD** [ansible/ansible#14128]
Hello,

Recently, AWS announced they would [change to a longer EC2 instance ID format](https://aws.amazon.com/blogs/aws/heads-up-longer-ec2-ebs-resource-ids-coming-in-2016/). I opted in for all regions and any nodes I create manually through the AWS console have the new, longer format.

The nodes I create through the Ansible EC2 module, however, still have the old, short format.

Is this an issue with the AWS API, with Ansible, or something I need to configure?

Thanks,
- Gavin

**Comment by jimi-c** [comment]
Hi @gavD, this is more of a general use question, and I'd recommend you ask on one of the mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
