### ISSUE TITLE
ansible 2.0 Regression IOError exceptions in filters hang playbook execution

### ISSUE THREAD

**Issue by marwano** [ansible/ansible#14120]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides

The playbook runs as expected on 1.9.0.1 the issue started with 2.0 
##### Ansible Configuration:

Regression is evident with clean config.
##### Environment:

Ubuntu 14.04. 
But I don't expect the issue is OS related.
##### Summary:

During playbook execution when a filter raises an exception the playbook should fail. With ansible 2.0 when an IOError is raised execution hangs at the point of the exception.
##### Steps To Reproduce:

Playbook:

```
- hosts: all
  gather_facts: False  
  tasks:
    - debug: msg="{{'hello'|myfilter}}"
```

filter (filter_plugins/myfilter.py):

```
def myfilter(data):
    raise IOError                       # Ex1: playbook hangs
    return open('no_such_file').read()  # Ex2: playbook hangs
    return 'hello there'                # Ex3: playbook ok as expected
    this_will_raise_a_NameError         # Ex4: playbook fail as expected

class FilterModule(object):
    def filters(self):
        return dict(myfilter=myfilter)
```

command to run:

```
ansible-playbook -i localhost, playbook.yml
```

There are four examples provided in the filter above. Comment out the other lines to try each example. 
##### Expected Results:

During playbook execution when a filter raises an exception the playbook should fail. 
.
##### Actual Results:

In examples 1 and 2 on ansible 2.0 execution hangs at the point the exception is raised. in 1.9 execution fails as expected. Examples 3 and 4 behave as expected on both 1.9 and 2.0

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
