### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by taozhi8833998** [ansible/ansible#14124]
ansible version is ansible 1.9.4
and my os is centos
this issue has trouble me two hours and search google for this get nothing valuable
run command `ansible daily -m ping  -vvvv` get the below errows

```
<ip> ESTABLISH CONNECTION FOR USER: root
<ip> REMOTE_MODULE ping
<ip> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ip /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719 && echo $HOME/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719'
/root/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719/ping

/root/.ansible/tmp/ansible-tmp-1453798516.81-77689240652843/ping:

/root/.ansible/tmp/ansible-tmp-1453798516.81-77689240652843/ping: No such file or directory
```

the correct output may be 

```
<ip> ESTABLISH CONNECTION FOR USER: root
<ip> REMOTE_MODULE ping
<ip> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 ip /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719 && echo $HOME/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719'
PUT /tmp/tmp**** TO /root/.ansible/tmp/ansible-tmp-1453798444.73-246072748837719/ping
```

Why I miss the PUT command????

**Comment by jimi-c** [comment]
It's apparently having issues uploading the file. Can you verify the filesystem is not full and you have write permissions to the home directory there? It could be a permissions issue of some kind.

**Comment by taozhi8833998** [comment]
I hava the full permission on this folder, and if I set the `pipelining = True` in ansible.cfg ,it works. Could you mind explaining it to me why it works, If it's convenient for you。

**Comment by jimi-c** [comment]
@taozhi8833998 pipelining works because no file is actually uploaded to the host - the python code to be executed is sent over stdin to /usr/bin/python. This further indicates there is some kind of problem uploading the file to that system.

Are you using the ssh connection transport? If so, you may want to try the paramiko transport, or set the ssh option to use scp instead of sftp for file uploads (http://docs.ansible.com/ansible/intro_configuration.html#scp-if-ssh).

**Comment by taozhi8833998** [comment]
@jimi-c in my ansible.cfg the `scp_if_ssh = True` , as you said, I just ping successfully for this moment, and later I need upload file to the sever would meet this issue again??  Thanks for ur patience， if I solved this issue, I would post it here

**Comment by jimi-c** [comment]
@taozhi8833998 if you keep that config setting, you will not have problems. It appears that SFTP is disabled in your sshd_config, so you could also look to re-enable that.

As this issue is resolved, I will go ahead and close this now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
