### ISSUE TITLE
issue after upgrading to stable-2.0.0.1

### ISSUE THREAD

**Issue by tetlika** [ansible/ansible#14126]
after upgrading to stable-2.0.0.1 I'm not able to run shell: tasks or local_action, the error is smth like that:

line 1284, in _check_arguments\r\n    for (k,v) in self.params.items():\r\nAttributeError: 'tuple' object has no attribute 'items'\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by jimi-c** [comment]
This should be resolved, and you should use the stable-2.0 branch (stable-2.0.0.1 was only created for the 2.0.0.x release updates).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
