### ISSUE TITLE
mount module can't handle nested mountpoints

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14139]
Bug Report

Ansible Version: ansible 1.9.1

Ansible Configuration:  No changes

Environment: RHEL 6.7 x86_64  (both Ansible master AND target host)

Summary: The mount module does not properly order nested filesystems in /etc/fstab even if with_dict dictionary variable has them in the proper order.

Steps to Reproduce:
1.) Create variable YAML file:
lvols:
  pgdata:
    lv_name: pgdata
    vg: pgdatavg
    lv_size: 100%FREE
    fs_type: ext4
    mount_point: /var/lib/pgsql/9.4/data
    owner: postgres
    group: dba
    mode: 700
  pgwal:
    lv_name: pgwal
    vg: pgwalvg
    lv_size: 100%FREE
    fs_type: ext4
    mount_point: /var/lib/pgsql/9.4/data/data/pg_xlog
    owner: postgres
    group: dba
    mode: 700

2.) Run Playbook:
    - hosts: newservers
      user: ansible
      sudo: True
      tasks:
        - name: mount the new filesystem and add to fstab
          mount: name='{{ item.value.mount_point }}' src=/dev/'{{ item.value.vg }}'/'{{ item.value.lv_name }}' fstype='{{ item.value.fs_type }}' dump=1 passno=2 state=mounted
          with_dict: '{{ lvols }}'

Expected Results:
Filesystem mounted in proper order (this order):
/var/lib/pgsql/9.4/data
/var/lib/pgsql/9.4/data/data/pg_xlog
(and properly defined in that order in /etc/fstab)

Actual Results:
Filesystem not mounted in proper order.  /var/lib/pgsql/9.4/data/data/pg_xlog was mounted first, THEN /var/lib/pgsql/9.4/data was mounted which covered up the first mountpoint.

Output from Playbook (hostname changed in output):
changed: [mybox.mydomain.com] => (item={'key': 'pgwal', 'value': {'mount_point': '/var/lib/pgsql/9.4/data/data/pg_xlog', 'group': 'dba', 'lv_name': 'pgwal', 'vg': 'pgwalvg', 'fs_type': 'ext4', 'mode': 700, 'owner': 'postgres', 'lv_size': '100%FREE'}}) => {"changed": true, "dump": "1", "fstab": "/etc/fstab", "fstype": "ext4", "item": {"key": "pgwal", "value": {"fs_type": "ext4", "group": "dba", "lv_name": "pgwal", "lv_size": "100%FREE", "mode": 700, "mount_point": "/var/lib/pgsql/9.4/data/data/pg_xlog", "owner": "postgres", "vg": "pgwalvg"}}, "name": "/var/lib/pgsql/9.4/data/data/pg_xlog", "passno": "2", "src": "/dev/pgwalvg/pgwal"}
changed: [mybox.mydomain.com] => (item={'key': 'pgdata', 'value': {'mount_point': '/var/lib/pgsql/9.4/data', 'group': 'dba', 'lv_name': 'pgdata', 'vg': 'pgdatavg', 'fs_type': 'ext4', 'mode': 700, 'owner': 'postgres', 'lv_size': '100%FREE'}}) => {"changed": true, "dump": "1", "fstab": "/etc/fstab", "fstype": "ext4", "item": {"key": "pgdata", "value": {"fs_type": "ext4", "group": "dba", "lv_name": "pgdata", "lv_size": "100%FREE", "mode": 700, "mount_point": "/var/lib/pgsql/9.4/data", "owner": "postgres", "vg": "pgdatavg"}}, "name": "/var/lib/pgsql/9.4/data", "passno": "2", "src": "/dev/pgdatavg/pgdata"}

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
