### ISSUE TITLE
FreeBSD Jail PKGNG Misleading Error

### ISSUE THREAD

**Issue by archonik** [ansible/ansible#14149]
##### Issue Type:

Bug Report
##### Ansible Configuration:

Clean
##### Environment:

```
FreeBSD vagrant 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

2.0.0.2 directly from ports installed via make install clean
```
##### Summary:

This issue occurs when:

Fresh BSD jail is created via 

```
ezjail-admin create database 'em0|10.0.0.2'
```

Steps To Reproduce:

Run this simple task

```
database        ansible_connection=jail ansible_python_interpreter=/usr/local/bin/python2
```

Inventory file

```
- hosts: database
  roles:
    - vagrant-basic
```

Role Code

```
- name: Install required packages
  pkgng: name="{{ item }}" state=present
  with_items: 
    - git
    - curl
    - wget 
    - ezjail
```

Resolution is easy, you need to bootstrap pkg first 

```
jexec database env ASSUME_ALWAYS_YES=yes pkg install random_package
```
##### Expected Results:

```
TASK: [vagrant-basic | Install required packages] *****************************
changed: [database] => (item=git,curl,wget,ezjail)
```
##### Actual Results:

```
TASK: [vagrant-basic | Install required packages] *****************************
failed: [database] => (item=git,curl,wget,ezjail) => {"failed": true, "item": "git,curl,wget,ezjail", "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1453884730.59-171138241710595/pkgng", line 1915, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1453884730.59-171138241710595/pkgng", line 282, in main
    _changed, _msg = install_packages(module, pkgng_path, pkgs, p["cached"], p["pkgsite"])
  File "/root/.ansible/tmp/ansible-tmp-1453884730.59-171138241710595/pkgng", line 145, in install_packages
    old_pkgng = pkgng_older_than(module, pkgng_path, [1, 1, 4])
  File "/root/.ansible/tmp/ansible-tmp-1453884730.59-171138241710595/pkgng", line 101, in pkgng_older_than
    version = map(lambda x: int(x), re.split(r'[\._]', out))
  File "/root/.ansible/tmp/ansible-tmp-1453884730.59-171138241710595/pkgng", line 101, in <lambda>
    version = map(lambda x: int(x), re.split(r'[\._]', out))
ValueError: invalid literal for int() with base 10: ''


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
