### ISSUE TITLE
"win_get_url" module with parameter "force: no" fails

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14158]
Hello I have the below task and fails with "You cannot call a method on a null-valued expression." only when parameter "force" is specified. The "KIT" directory is already created. 
 Ansible version is 2.0.0.2 on CentOS 6.7. The target operating system is Windows Server 2012 R2.

name: Download kit
       win_get_url:
         force: no
         url: 'http://some_random_url/some_random_program.exe'
         dest: 'C:\KIT\some_random_program.exe'

Thanks!

**Comment by jhawkesworth** [comment]
This has already been raised under https://github.com/ansible/ansible-modules-core/issues/2146
and some more information on this issue here: https://github.com/ansible/ansible-modules-core/pull/2644

There is a messy but working implementation in one of the comments on https://github.com/ansible/ansible-modules-core/issues/2146

**Comment by jimi-c** [comment]
As this is a duplicate, I'll go ahead and close this now.

Thanks!
