### ISSUE TITLE
Providing integer variables from command line (via --extra-vars) recognized as string

### ISSUE THREAD

**Issue by ulucaydin** [ansible/ansible#14179]
This is for Ansible 2.X: 
When I run a playbook via CLI and providing a such extra variable, node_number as integer:

`ansible-playbook my_playbook.yml --extra-vars "node_number=10"
`
I have a array slice operation within a role of my to take a portion of the playbook:

```
- debug: msg="{{ item }}"
  with_items: `groups.mygroup[:node_number]`
```

Here is the error I receive:

```
ok: [localhost]
ERROR! an unexpected type error occurred. Error was slice indices must be integers or None or have an __index__ method

```

Interestingly, when I remove the variable from CLI and provide the same variable from `group_vars/all/common.yml`, it works:

```

---
node_number:10
```

**Comment by bcoca** [comment]
the key/val parser there does not try to do typing, YAML itself does do typing, if you pass as a json string it would also preserve type as the JSON parser also does typing, but to avoid any input problems you could just do this:
`with_items: "{{groups.mygroup[:node_number|int]}}"`

**Comment by jimi-c** [comment]
As @bcoca indicated above, if you want to pass in specific types as extra vars, you should use the ability to pass in JSON or YAML via extra args: http://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
