### ISSUE TITLE
ansible_become_user take priority over become:

### ISSUE THREAD

**Issue by hxw** [ansible/ansible#14199]
http://docs.ansible.com/ansible/become.html says that `ansible_become_user`  can be used in host/group vars to provide a different default.  I would have expected that this default  could overridden by an explicit `become_user:`  in a play.  However it appears that  `ansible_become_user`  always takes priority.

Is that the expected behaviour?  If so, could the document be clarified?

**Comment by bcoca** [comment]
Actually, to quote "equivalent to ansible_sudo_user or ansible_su_user, allows to set the user you become through privilege escalation", there is no mention of 'default'

Not in that page but in variable precedence docs we specify that the connection vars take priority over the directives. http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by hxw** [comment]
Just a concrete example to clarify:

```
- name: setup npm for user 1
  npm: path=~user1 state=present
  become: true
  become_user: user1
- name: setup npm for user 2
  npm: path=~user2 state=present
  become: true
  become_user: user2
```

Normally this works and npm files are owned by user1/2 appropriately
But I had placed in group_vars for a particular host

```
ansible_become_user: root
```

Now both of the above plays are owned by root.

This means I should treat the `become_user:` as effectively a "role variable" right?

**Comment by bcoca** [comment]
become_user is a directive, not a variable, ansible_become_user is a variable, which takes precedence over the directive. 

Both plays are not 'owned by root' but anytime you use become for the hosts in that group the user will be set to root, unless you set the ansible_become_user var in a spot with higher precedence

**Comment by hxw** [comment]
Sorry for the confusion I should not have said the plays were_ "owned by root"_  I should have said:
that the plays always run as root, ignoring the `become:` directive when ansible_become_user is set in group_vars".

That was my problem, I removed all ansible_become_user settings from all group_vars files and now everything is working again.  Thanks for your help.

**Comment by ssbarnea** [comment]
The current precedence logic doesn't make much sense to me, seems quite broken. I spent half a day debugging why almost randomly my tasks were executed as root user even if it was very clear that they specified a different user. 

This is even worse because the `ansible_become_user` was defined inside a role that was a dependency of the current one, which means that anything that uses `ansible_become_user` will break code outside its scope. 

If ansible dev team is so sure that's the expected behaviour it should clearly raise a warning when it does find `become_user` on tasks/blocks and is ignoring them.

```
---
  - command: "whoami"
    register: result
    become: yes
    become_user: "{{ services_user }}"

  - name: check if {{ services_user }} == {{ result.stdout }}
    fail: msg="WTF is happening!?"
    when: services_user != result.stdout
```

To break the code below, include a role that has  `ansible_become_user: root`.

**Comment by richard-uk1** [comment]
How would you achieve a default `become_user` var?

I'm testing my playbook in vagrant (where I need `become` to get to root) and my scripts delegate to helper users for some tasks for security (using `become_user: <username>`).

**Comment by bcoca** [comment]
@derekdreery, not related to this ticket, it is normally better to ask on IRC or the mailing list, in any case become_user takes the default from ansible.cfg, which is root if not specified

closing this issue via 03c33053aa4a9952bd80985ff2e1754b3e6b0dbf which updated the docs on become.html to be explicit

**Comment by timend** [comment]
I don't see how 03c3305 clarifies on this. It only says that `become_user` in a play does not imply become = true. My solution was to stop using `ansible_become_user` completely and adding the directive `become_user` on playbook-level (default value) as well as on task level (for overriding). E.g. like so:

```
# playbook.yml
---
- hosts: "all"
  become_user: "root"
  roles:
  - "some_role"
```

```
# roles/some_role/tasks/main.yml
---
- name:  become somebody else 
  become: true
  become_user: "non_root_user"
# Fail to show which user runs the shell
  shell: 'whoami; exit 1'
```

**Comment by cadavre** [comment]
For me this is also considered as **bug**.
For my host I set:
```
ansible_become = True
ansible_become_user = deploy_dir_owner
```
So I want MOST of my tasks to be run as directory owner, because they happen inside of this dir.

Problem starts when I want to make some sudoish actions to configure deployed project in global scope, ie. add HTTP server configuration file (which requires root).
I cannot then simply add:
```
- name: Add configuration files
  ...
  become_user: root
```

Any ideas how can I achieve it other way without defining `become` in playbook? @bcoca ?
