### ISSUE TITLE
'ansible-playbook --check' changes user UID on FreeBSD remote host

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#14211]
##### Issue Type:

Bug report
##### Ansible Version:

2.0.0.2-1ppa~trusty
##### Ansible Configuration:

[defaults]
gathering = smart
hash_behaviour = merge 
[privilege_escalation]
become=True
become_method=sudo 
become_user=root 
become_ask_pass=True 
##### Environment:

Ubuntu Trusty server, remote host on FreeBSD
##### Summary:

'ansible-playbook --check'  actually makes changes on FreeBSD host
Specifically, it changes user's UID when uid: parameter for user is changed in play
##### Steps To Reproduce:

change user's UID in play, run 'ansible-playbook --check' 
##### Expected Results:

Dry run with would-be changes.
##### Actual Results:

Change is actually applied in system.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
