### ISSUE TITLE
bool filter fails to lower case environment variables

### ISSUE THREAD

**Issue by abridgett** [ansible/ansible#14240]
It seems to restrict the type match for conversion to lowercase.

```
$ export VAGRANT_RUN=True
$ ansible local -m debug -a "msg={{lookup('env','VAGRANT_RUN') |bool}}" -vvv
localhost | SUCCESS => {
    "msg": false
}
```

Changing the string test in the bool filter from:

```
    if type(a) in types.StringTypes:
```

to:

```
    if isinstance(a, basestring):
```

Makes this work as expect, but I'm not submitting a direct PR as I'm not sure if this is the correct change.

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by abridgett** [comment]
##### Issue Type:
- Bug Report

##### Ansible Version:

ansible 2.0.0.2

##### Ansible Configuration:

none

##### Environment:

Linux Ubuntu 14.04

##### Summary:

bool filter seems to be too picky when deciding what to consider a string (e.g. environment variables do not work)

##### Steps To Reproduce:

```
export VAGRANT_RUN=True
$ ansible local -m debug -a "msg={{lookup('env','VAGRANT_RUN') |bool}}" -vvv
```

##### Expected Results:

```
localhost | SUCCESS => {
    "msg": true
}
```

##### Actual Results:

```
localhost | SUCCESS => {
    "msg": false
}
```

**Comment by sivel** [comment]
It would be great to know what the value of `VAGRANT_RUN` is to begin with.

**Comment by bcoca** [comment]
```
bcoca@erebos:~/work/ansible(devel) $  ansible localhost -m debug -a "msg={{lookup('env','VAGRANT_RUN')}}" 
localhost | SUCCESS => {
    "msg": ""
}
bcoca@erebos:~/work/ansible(devel) $ export VAGRANT_RUN=True
bcoca@erebos:~/work/ansible(devel) $  ansible localhost -m debug -a "msg={{lookup('env','VAGRANT_RUN')}}" 
localhost | SUCCESS => {
    "msg": true
}

bcoca@erebos:~/work/ansible(devel) $  ansible localhost -m debug -a "msg={{lookup('env','VAGRANT_RUN')|bool}}" 
localhost | SUCCESS => {
    "msg": false
}
```

tested and corroborated

**Comment by sivel** [comment]
Ok, so it also seems that the type of variable you get from reading from env via lookup is `ansible.vars.unsafe_proxy.AnsibleUnsafeText` which could be the reason the type checking doesn't work the way it is implemented.

**Comment by bcoca** [comment]
hmm, thinking this might also be the same issue with `ansible_user/port/etc` and the `default` filter not getting along....

**Comment by sivel** [comment]
I think with default, it expects the variable to be undefined.  Those values are now defined, although empty/null, which requires you use the `boolean` argument to the default filter.  Although it could be somehow related to the proxy.

**Comment by bcoca** [comment]
well, something is happening on the template/filter lavel, cause I can detect the variable is undefined:

```
  - debug: var=idontexist
```

outputs:

```
    "idontexist": "VARIABLE IS NOT DEFINED!"    
```

**Comment by bcoca** [comment]
while:

```
var:
  nullvar: !!null
tasks:
  - debug: var=nullvar
```

outputs:

```
ok: [localhost] => {
    "nullvar": null                                                                                                                                                                                                  
}   
```

**Comment by sivel** [comment]
Just as an FYI, at least for the bool filter, the following should be all that is required.

```
diff --git a/lib/ansible/plugins/filter/core.py b/lib/ansible/plugins/filter/core.py
index fed5097..51638d0 100644
--- a/lib/ansible/plugins/filter/core.py
+++ b/lib/ansible/plugins/filter/core.py
@@ -41,7 +41,7 @@ import uuid
 import yaml
 from jinja2.filters import environmentfilter
 from distutils.version import LooseVersion, StrictVersion
-from ansible.compat.six import iteritems
+from ansible.compat.six import iteritems, string_types

 from ansible import errors
 from ansible.parsing.yaml.dumper import AnsibleDumper
@@ -110,7 +110,7 @@ def bool(a):
     ''' return a bool for the arg '''
     if a is None or type(a) == bool:
         return a
-    if type(a) in types.StringTypes:
+    if isinstance(a, string_types):
         a = a.lower()
     if a in ['yes', 'on', '1', 'true', 1]:
         return True
```

We should in general always be using `isinstance` anyway.

**Comment by bcoca** [comment]
@sivel agreed, submit patch

with default it is harder as it is built into jinja2

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
