### ISSUE TITLE
Retry files aren't generated when failure occurs

### ISSUE THREAD

**Issue by Erouan50** [ansible/ansible#14265]
**Issue Type**: Bug Report

**Ansible Version**:

```
ansible-playbook 2.1.0 (devel e3a6accc1d) last updated 2016/01/20 10:51:42 (GMT +000)
  lib/ansible/modules/core: (detached HEAD ffea58ee86) last updated 2016/01/20 10:51:51 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD e9450df878) last updated 2016/01/20 10:51:59 (GMT +000)
  config file = /workspace/ansible.cfg
  configured module search path = Default w/o overrides
```

**Ansible Configuration**:

```
[defaults]
host_key_checking = False
retry_files_enabled = True
retry_files_save_path = "~/"
```

**Environment**: Fedora 23

**Summary**:

Since the Ansible 2.0 version when a fail occur on a task no retry file is generated to limit the hosts who fail.

**Steps To Reproduce**:

Just play the follow playbook which reboot a server to simulate a network failure:

```
- hosts: all
  tasks:
    - name: Reboot a server
      shell: reboot
      when: inventory_hostname == 'test-web1'
      ignore_errors: yes

    - name: Test
      command: echo "test"`
```

Normally a retry file should be generated.

**Expected Results**:

Here is the result when I run this playbook under Ansible 1.9.4:

```
PLAY [test] *********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test-web2]
ok: [test-web1]

TASK: [Reboot a server] ******************************************************* 
skipping: [test-web2]
fatal: [test-web1] => SSH Error: Shared connection to xx.xx.xx.xx closed.
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [Test] **************************************************************** 
changed: [test-web2]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @"~/"/test.retry

test-web1          : ok=1    changed=0    unreachable=1    failed=0   
test-web2          : ok=2    changed=1    unreachable=0    failed=0
```

**Actual Results:**

Here is the output in Ansible 2.1:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test-web2]
ok: [test-web1]

TASK [Reboot a server] *********************************************************
skipping: [test-web2]
fatal: [test-web1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
...ignoring

TASK [Test] ******************************************************************
fatal: [test-web1]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
changed: [test-web2]

PLAY RECAP *********************************************************************
test-web1          : ok=2    changed=0    unreachable=1    failed=0   
test-web2          : ok=2    changed=1    unreachable=0    failed=0 
```

No retry file is generated, but it may be the expected result.

Thanks,

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits such as https://github.com/ansible/ansible/commit/78d499140c943b6bc806c222799060892bca8ae7 (which was commited on 2016-01-26) should resolve this question or problem for you.  Your version output shows that you have not updated in several days and have missed these changes.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by Erouan50** [comment]
Indeed it works, thanks !
