### ISSUE TITLE
[2.x] set_fact + run_once breaks register variables

### ISSUE THREAD

**Issue by lystor** [ansible/ansible#14279]
Hi

ansible-2.0.1.0-0.1.rc1
centos 7.2.1511 x86_64

```
=======================================
   BUG
=======================================
- name: BUG
  hosts:            all
  remote_user:      root


  tasks:
    - set_fact: xxx=5555
      run_once: true


    - command: hostname
      register: result


    - debug: var=result.stdout


-----------------------

ok: [com1-lystor] => {
    "result.stdout": "mas1-lystor"
}
ok: [log1-lystor] => {
    "result.stdout": "mas1-lystor"
}
ok: [mas1-lystor] => {
    "result.stdout": "mas1-lystor"
}
ok: [ded1-lystor] => {
    "result.stdout": "mas1-lystor"
}


=======================================
   OK
=======================================

- name: BUG
  hosts:            all
  remote_user:      root


  tasks:
    - set_fact: xxx=5555
###      run_once:  true


    - command: hostname
      register: result


    - debug: var=result.stdout


-----------------------

ok: [com1-lystor] => {
    "result.stdout": "com1-lystor"
}
ok: [ded1-lystor] => {
    "result.stdout": "ded1-lystor"
}
ok: [log1-lystor] => {
    "result.stdout": "log1-lystor"
}
ok: [mas1-lystor] => {
    "result.stdout": "mas1-lystor"
}
```

Please fix this bug.
Thank you.
## 

With best regards,
Mykola Ulianytskyi

**Comment by omgjlk** [comment]
So I ran into this today. Interestingly enough, it appears to happen when the first task of a play is a set_fact with run_once. But if the first task does not do run_once, and the second one does, it appears to work fine. This was a very bizarre and difficult to track down bug.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
