### ISSUE TITLE
Destination files get prepended with ANSI escape sequence

### ISSUE THREAD

**Issue by neowulf** [ansible/ansible#14282]
#### Issue

```
$ ansible aa.bbb.ccc.ddd -m ping -vvvv
Using /tmp/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<aa.bbb.ccc.ddd> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<aa.bbb.ccc.ddd> SSH: EXEC ssh -C -vvv -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ConnectTimeout=20 -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/Users/user/.ssh/pemfile.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -tt aa.bbb.ccc.ddd '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970 )" )'
/home/ec2-user/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970/ping
<aa.bbb.ccc.ddd> SSH: EXEC scp -C -vvv -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ConnectTimeout=20 -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/Users/user/.ssh/pemfile.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 /var/folders/home/ec2-user/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970/ping'"'"''
aa.bbb.ccc.ddd | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to \u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/ec2-user/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970/ping:\n\nExecuting: program /usr/bin/ssh host aa.bbb.ccc.ddd, user (unspecified), command scp -v -t '\u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/ec2-user/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970/ping'\nOpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/user/.ssh/config\r\ndebug1: /Users/user/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 45525\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 3\r\nSending file modes: C0600 74360 tmpBI32FT\nSink: C0600 74360 tmpBI32FT\nscp: \u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/ec2-user/.ansible/tmp/ansible-tmp-1454464297.74-145920452708970/ping: No such file or directory\n"
}
```
#### Environment

The host machine is Mac OS X.

The remote machine is an [Amazon Linux AMI](https://aws.amazon.com/amazon-linux-ami/2015.09-release-notes/).

```
$ pip list     
ansible (2.0.0.2)
ansible-playbook-debugger (0.2.3)
ecdsa (0.13)
Jinja2 (2.8)
MarkupSafe (0.23)
paramiko (1.16.0)
pip (8.0.2)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (18.0.1)
wheel (0.24.0)
```
#### Possibly related to:
- #5798
- #12068

**Comment by sivel** [comment]
It sounds like you have a shell profile or similar that is setting shell colors for a prompt, and it is doing so even for non-interactive sessions.

**Comment by neowulf** [comment]
I get the same issue after resetting my PS1

```
(venv)1818.02 neowulf33@machine:ansible [master] $ PS1="$ "
$ 
$ ansible aa.bbb.ccc.ddd -m ping -vvvv
...
    "msg": "ERROR! failed to transfer file to \u001b[?25h\u001b[0G\u001b[K\u001b[?25h\u001b[0G\u001b[K/home/ec2-user/.ansible/tmp/ansible-tmp-1454465898.53-132988371259615/ping:\n\nE
...
```

**Comment by sivel** [comment]
The problem would not be with the master.  The problem would be with the remote target machine.

**Comment by neowulf** [comment]
So, I had the following lines in the remote machine's `~/.bashrc`:

```
export NVM_DIR="/home/ec2-user/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads Node Version Manager
```

which when commented out. The ping worked! I was actually wondering why my bash login was taking it's sweet time to login.

However, shouldn't I be able to disable loading `~/.bashrc` when using Ansible? What is the recommended practice? Is there a ssh flag? I wouldn't want to manage login profiles for every machine.

**Comment by dagwieers** [comment]
Still I wouldn't be expecting this to corrupt hostnames though. I think we need to revise how we communicate back those pathnames to avoid any corruption.

@neowulf33 Can you send me exactly what's in your bash profile(s) so I can mimic this behaviour while looking for an elegant fix ?

**Comment by neowulf** [comment]
Thanks @sivel @dagwieers for helping me resolve this issue.

Here is the offending snippet within `~/.bashrc` on the remote host:

```
export NVM_DIR="/home/ec2-user/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

I am also attaching `nvm.sh` - [nvm.sh.txt](https://github.com/ansible/ansible/files/116847/nvm.sh.txt)

You may find it easier to install nvm by following the installation steps found on the [NVM project page](https://github.com/creationix/nvm) which will essentially update `~/.bashrc`.

**Comment by jimi-c** [comment]
Ansible needs a remote shell when running, I'm not sure if we'd be able to get around an error like this.

**Comment by dagwieers** [comment]
Ok, the solution for NVM is to move this snippet to `.bash_profile` rather than `.bashrc` so that it is only used for login shells.

@neowulf33, we have to open a ticket with the NVM project so they can fix their code.

But that doesn't solve the fundamental problem that Ansible is not resilient enough in such cases.

I am wondering whether it would make sense to implement some markers to ensure that any scrambled output does not corrupt our communication. A simple implementation could be to send something like: ansible_path="/path/foo/bar" and let the receiving end filter out the ansible path.

BTW Pipelining avoids this situation, but not all tasks can make use of pipelining.
BTW2 SCP is doing something similar to avoid corruption, because SCP is using the SSH shell for transferring files etc. They would be susceptible for the same kind of issue. We may want to investigate what their solution is and make it similar.

**Comment by dagwieers** [comment]
BTW The problem with ansible obviously is that we do have an interactive shell, because we force pty's. Which IMO is a very big design choice, but this was done so that sudo would work out-of-the-box (rather than having to modify the configuration to disable the requirement for a tty).

So that's a very ugly workaround with a lot of consequences (installers asking for input, because they are told the shell is interactive, etc...).

**Comment by dagwieers** [comment]
Ticket at NVM opened: creationix/nvm#1006

**Comment by jimi-c** [comment]
Thanks @dagwieers, based on the above I'm going to go ahead and close this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
