### ISSUE TITLE
Ansible does not parse condition for dependencies on initial scan.

### ISSUE THREAD

**Issue by evetion** [ansible/ansible#14289]
**Issue Type:**
Bug Report

**Ansible Version:**
ansible 2.0.0.2

**Environment:**
N/A

**Summary:**
When creating dependencies between two roles, depending on a global condition, ansible will fail  with " A recursion loop was detected".

**Steps To Reproduce:**

Create a role A and a role B (ansible-galaxy will suffice) with the following dependencies:

_roles/a/meta/main.yml_

```

---
dependencies:
  - { role: b, when: not install }
```

_roles/b/meta/main.yml_

```

---
dependencies:
  - { role: a, when: install }
```

**Expected Results:**

Normal playbook run. In this way an installation (install: true) of role B will also call A. An uninstall (install: false) of role A will also call B.

**Actual Results:**

```
ERROR! A recursion loop was detected with the roles specified. 
Make sure child roles do not have dependencies on parent roles [...]

dependencies:
  - { role: b, when: install }
    ^ here
```

**Comment by jimi-c** [comment]
Hi @evetion, this is a misunderstanding of how roles work. Roles are brought in as pre-processor statements essentially, and any conditionals applied to them are inherited by their tasks. Conditionals do not stop roles from being parsed, which is why you're seeing this error. You should restructure your roles so that there is no dependency loop.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
