### ISSUE TITLE
Problem when using multiple inventory sources

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#14312]
We have to support multiple inventory sources for a client, one is dynamic (ec2) and the other one is static for some hosts in a different data center. But our playbooks should run across all hosts at once, so we were happy to come across that section http://docs.ansible.com/ansible/intro_dynamic_inventory.html#using-multiple-inventory-sources

So we call ansible with -i pointing to the directory that contains the dynamic and static inventory files and that is working as long as that directory doesn't contain any other files nor any subdirectories with other files in them. It seem that ansible is not only reading the files in the given directory but recursivle in all subdirectories as well.

Moving the inventories into a different subdirectory of its own such that there is nothing else in it, won't work either, because we do need the group_vars and host_vars as subdirectories at least - but also other stuff.

So, this seems to be a bug - or there should be another option to explicitly define the {{inventory_dir}} which is used to find the variables and other stuff.

Any suggestions?

**Comment by jimi-c** [comment]
Hi @jurgenhaas, this is definitely a feature and we do try to filter out invalid inventory sources (both by extension, and if they're non-executable). I thought we improved this in 2.0 such that if an invalid file was attempted to be used it would ignore it if there were parsing/execution issues.

**Comment by jurgenhaas** [comment]
Here is a list of files and error messages that I'm getting (note: subsequent messages only show up when the previous file got removed first):

```
README.md:5: Expected key=value host variable assignment, got: https://gitlab.paragon-es.de/ansible-playbooks/general
deploy.yml:8: Expected key=value host variable assignment, got: name:
files/drush/dummy.make:2: Expected key=value host variable assignment, got: 7.x
```

None of the files is executable. The first one is a markdown file, the second one is a playbook and the third one is an application specific file that should be used by one of the playbooks to be copied to a host.

I stopped there because it appears that just any file gets included and I haven't seen anyone that got ignored.

This is on Ansible 2.0.0.2

**Comment by jurgenhaas** [comment]
I've got it working now with the following setting in my ansible.cfg file:

`inventory_ignore_extensions = ~, .orig, .bak, .ini, .cfg, .retry, .pyc, .pyo, .yml, .md, files, templates, wiki`

This is probably only applicable to my Ansible suite but it's maybe helpful for others as well, who are coming along.

**Comment by jimi-c** [comment]
Ahh good @jurgenhaas, I actually forgot about that config setting (I never use it), so glad you found it.

I'll go ahead and close this now, if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
