### ISSUE TITLE
[2.x] connection vars are None/null

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#14310]
##### Issue Type:
- Bug Report (regression)
##### Ansible Version:

2.x
##### Summary:

since 2.x all connection vars are defaulted to `None/null`, as in <=1.9.x they were undefined. This should be either documented in porting guide or "fixed" so None is handled as undefined.
##### Steps To Reproduce:

In 1.9 this is `22`, in 2.0 it is `""`

```
- debug msg={{ ansible_ssh_hosts | default(22) }}
```

Alternatively, to get the same result, the porting guide can be extended with:

```
- debug msg={{ ansible_ssh_hosts or 22 }}
```

**Comment by sivel** [comment]
I have a proof of concept fix for potentially handling this at https://github.com/ansible/ansible/pull/14315

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
