### ISSUE TITLE
Oracle Linux 5.11 Issue with yum module ansible 2.0.0.2

### ISSUE THREAD

**Issue by aromarom64** [ansible/ansible#14327]
I am getting the following error

`failed: [testora51.containers.arom.lan] => (item=[u'binutils']) => {"failed": true, "invocation": {"module_name": "yum"}, "item": ["binutils"], "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /home/arom/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 10185\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to testora51.containers.arom.lan closed.\r\n", "module_stdout": "{\"msg\": \"\", \"invocation\": {\"module_args\": {\"name\": [\"binutils\"], \"list\": null, \"install_repoquery\": true, \"conf_file\": null, \"disable_gpg_check\": false, \"state\": \"installed\", \"disablerepo\": null, \"update_cache\": false, \"enablerepo\": null, \"exclude\": null, \"_ansible_check_mode\": true}}, \"changed\": false, \"results\": [\"binutils-2.17.50.0.6-26.el5.x86_64 providing binutils is already installed\"], \"rc\": 0}\r\nException exceptions.AttributeError: \"'NoneType' object has no attribute 'unshare_data'\" in <bound method YumBase.__del__ of <yum.YumBase object at 0x1331f10>> ignored\r\n", "msg": "MODULE FAILURE", "parsed": false}
`

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
