### ISSUE TITLE
no filter named 'extract'

### ISSUE THREAD

**Issue by let4be** [ansible/ansible#14326]
I was trying to use map extract filter, as described in http://docs.ansible.com/ansible/playbooks_filters.html#extracting-values-from-containers

```
"{{groups['tag_Name_coop']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|list}}"
```

but it fails

```
fatal: [*.*.*.*]: FAILED! => {"changed": false, "failed": true, "msg": "TemplateRuntimeError: no filter named 'extract'"}
```

```
ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by let4be** [comment]
Ok I'm confused
docs state that

> Extracting values from containers
> New in version 2.1.

buuuut last release of ansible is 2.0.*
What am I missing? Is it available only on the master branch?

**Comment by let4be** [comment]
Hm... just cloned master from the git, same error message
Any ideas what's going on?

**Comment by jimi-c** [comment]
Hi @let4be, 2.1 = the devel branch, so this is currently available when running ansible straight from the devel git checkout right now. You can build packages/install from pip using the git URL if you wish, however I usually recommend simply sourcing the `hacking/env-setup` script we include in the git repository.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
