### ISSUE TITLE
validate elements of ansible_all_ipv4_addresses against an IP address regex

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible#14350]
Hi,

one can create its own validation for  ansible_all_ipv4_addresses elements but since this is probably sane to do in general (for everyone by default), how about adding such a regex check to ansible itself by default?

related discussion:
https://groups.google.com/forum/#!msg/ansible-project/DDpmjSJHy5c/lR7vwaR5BwAJ

**Comment by jimi-c** [comment]
Hi @nusenu, we already have a jinja2 filter which can validate IP addresses: http://docs.ansible.com/ansible/playbooks_filters.html#ip-address-filter. Doing so for the above fact would simply require a with_items loop.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by nusenu** [comment]
just for the record: 
a loop is not required according to the documentation
https://docs.ansible.com/ansible/playbooks_filters_ipaddr.html

I'm using that filter as suggested, but why not do that by default and keep more people safe?
https://github.com/nusenu/ansible-relayor/commit/d2c2108a8850241369aa8867faf4ac53246171d5
