### ISSUE TITLE
docker_image module: "Either path or fileobj needs to be provided"

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#14366]
##### Environment

OSX: 10.11.2
Ansible Host: 2.0.0.2
Python: 2.7.10
docker-py: 1.7.0
requests: 2.9.1
Ansible Remote Client: Amazon Linux
##### Problem

I was just want to use [docker_image](http://docs.ansible.com/ansible/docker_image_module.html) module to pull an image.  

``` yaml
- docker_image: name='vikas027/docker-redis:latest' state=present
```
##### Error

Documentation says that `path` is not mandatory, but I got the below error. Am I missing something ?

``` bash
failed: [myserver] => (item=vikas027/docker-redis:latest) => {"failed": true, "item": "vikas027/docker-redis:latest", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1454933036.64-112508914115589/docker_image\", line 2391, in <module>\r\n    main()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1454933036.64-112508914115589/docker_image\", line 401, in main\r\n    image_id = manager.build()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1454933036.64-112508914115589/docker_image\", line 293, in build\r\n    stream = self.client.build(self.path, dockerfile=self.dockerfile, tag=':'.join([self.name, self.tag]), nocache=self.nocache, rm=True, stream=True)\r\n  File \"/usr/local/lib/python2.7/site-packages/docker/api/build.py\", line 24, in build\r\n    raise TypeError(\"Either path or fileobj needs to be provided.\")\r\nTypeError: Either path or fileobj needs to be provided.\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
