### ISSUE TITLE
Bug Report: Unable to pass variables to 'hosts:' except via --extra-vars

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14388]
**Ansible version**:  2.0.0.2
**Ansible configuraton**: Fresh config
**Environment**: Ubuntu 14.04

**Summary**: It isn't possible to set `hosts:` dynamically using variables except for when using `--extra-vars`.
Setting `this_host` in `./group_vars/all/all.yml` also fails.
The play runs successfully when running: `ansible-playbook -e "this_host=localhost" test.yml`.

**Steps to reproduce**:

```
test.yml:

---

- hosts: localhost
  connection: local
  tasks:
    - set_fact: this_host=localhost
    - debug: var=this_host


- hosts: "{{ this_host }}"
  connection: local
  tasks:
    - debug: var=this_host
```

`# ansible-playbook test.yml`

**Expected results**:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "this_host": "localhost"
}

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "this_host": "localhost"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

**Actual results**:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "this_host": "localhost"
}
ERROR! 'this_host' is undefined
```

**Comment by jimi-c** [comment]
Hi @brianlycett, the `hosts` field (and any Play fields) are templated at YAML parsing time, and as such there is no inventory available at that time. Therefore, any variables used for these fields must be present via vars/vars_files or extra_vars passed from the CLI.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
