### ISSUE TITLE
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#14408]
**Ansible version**

ansible-playbook 2.1.0 (devel 5a88478ccc) last updated 2016/02/10 12:21:18 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 9fc4ed0458) last updated 2016/02/10 12:21:20 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6aeb2ab6cf) last updated 2016/02/10 12:21:20 (GMT +300)

**Summary**

Every now and then I get this error after a run:

```
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'terminate'
to see the full traceback, use -vvv
```

It sounds like the traditional problem of a Python thread running code during interpreter shutdown: all the globals are set to None.

It's hard to reproduce (which means either I run with `-vvv` all the time, or I'll never see the traceback),  so I've no clue nor what code.

**Comment by jimi-c** [comment]
There was a race-condition in the cleanup code, but @bcoca had committed some fixes for that yesterday (late in the day). Are you still seeing this today with a fresh pull from devel?

**Comment by mgedmin** [comment]
I was seeing this with commit 5a88478, which was a fresh pull at the time I was testing.

**Comment by bcoca** [comment]
removed that commit, previous ones should have fixed the issue, this one 'slipped in' but it is just me trying out alternatives. closing via d9dcb2a427f4041f121950668c4ae40b0042c0d6

**Comment by mgedmin** [comment]
Just saw this with commit 9286143b53661c96d91b9ca836af287fbd1cc7e4:

```
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'terminate'
to see the full traceback, use -vvv
```

**Comment by mattclay** [comment]
I encountered the same issue, but as of commit cd076db it is working for me.

**Comment by vfguy** [comment]
I'm getting this consistently.  Not sure if it's something that I'm doing incorrectly, but this was the only place I found this issue discussed online.

using Ansible 2.0.0.2 installed via pip on babun under windows.  I realize it's not a supported solution, but am providing the error msg in case it helps figure out the issue.

No config file found; using defaults
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo'
(default). This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
1 plays in playbook.yml
      0 [main] python2.7 4380 child_info_fork::abort: address space needed by '_speedups.dll' (0x6F0000) is already occupied
Unexpected Exception: 'NoneType' object has no attribute 'terminate'
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 190, in run
    self._cleanup()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 199, in _cleanup
    return self._tqm.cleanup()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 245, in cleanup
    self._cleanup_processes()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in _cleanup_processes
    self._result_prc.terminate()
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 89, in terminate
    super(ResultProcess, self).terminate()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

**Comment by janjango** [comment]
I'm getting the same issue as @vfguy .
I'm also on windows using ansible 2.1.0 via babun.

**Comment by selfsx** [comment]
@JacquesDufour same for me on babun for windows

**Comment by steve-gregory** [comment]
Am still getting this issue after installing `stable-2.1`, notably when running the ansible python library via. celery:

```
File "/opt/env/atmo/local/lib/python2.7/site-packages/subspace/runner.py", line 325, in run
  self.pbex.run()
File "/opt/env/atmo/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 196, in run
  self._tqm.cleanup()
File "/opt/env/atmo/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 254, in cleanup
  self._cleanup_processes()
File "/opt/env/atmo/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 258, in _cleanup_processes
  self._result_prc.terminate()
File "/opt/env/atmo/local/lib/python2.7/site-packages/ansible/executor/process/result.py", line 94, in terminate
  super(ResultProcess, self).terminate()
File "/usr/lib/python2.7/multiprocessing/process.py", line 137, in terminate
  self._popen.terminate()
```

I did end up finding a "solution" to this problem: switching my concurrency_pool to `gevent`.

**Comment by tanyewei** [comment]
@steve-gregory 

If  switching my concurrency_pool to gevent

celery always display "worker: Warm shutdown (MainProcess)"

**Comment by lyncir** [comment]
I'm get same error as @steve-gregory.
Env: ansible==2.2.0, celery==3.1.17

How to fixed it?

**Comment by steve-gregory** [comment]
@lyncir @tanyewei I was able to get around the error by running:

```
os.environ["PYTHONOPTIMIZE"] = "1"
```

in my settings file, and reverting back to the original concurrency pool (prefork/multiprocessing). YMMV.

**Comment by keithyau** [comment]
Same here

  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 94, in terminate
    super(ResultProcess, self).terminate()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

os.environ["PYTHONOPTIMIZE"] = "1"

not working ...

**Comment by keithyau** [comment]
working by export PYTHONOPTIMIZE = 1

https://github.com/celery/celery/issues/1709

**Comment by codenamesubho** [comment]
@steve-gregory  the above solution didn't help. any other solution for this yet?

**Comment by codenamesubho** [comment]
Changing concurrency pool to eventlet fixed my issue. Thanks.

**Comment by tanyewei** [comment]
@Ghost-script for example?

**Comment by pankajackson** [comment]
I am also getting same error when I run PlaybookExecutor from Celery, but it is working fine if I run it as a normal function(without using celery), I have installed
Ansible: 2.1.0.0
Celery: 3.1.23
Python: 2.7.11
Django: 1.9.7

and here's my log

```
[2016-06-30 17:21:27,009: ERROR/MainProcess] Task firetask[c8289a25-055c-444d-9ee4-7bb71550b92c] raised unexpected: AttributeError("'NoneType' object has no attribute 'terminate'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/media/IMPORTANT/MyDisk/DjangoWorkSpace/sat_django/executor/tasks.py", line 90, in firetask
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 201, in run
    self._tqm.cleanup()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 269, in cleanup
    self._cleanup_processes()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 273, in _cleanup_processes
    self._result_prc.terminate()
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 94, in terminate
    super(ResultProcess, self).terminate()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 137, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

please help Thanks

**Comment by codenamesubho** [comment]
@tanyewei @pankajackson  `celery -A cyclops.celeryapp worker -P eventlet --loglevel=DEBUG`   this is how i am running celery and its working fine. 
Ansible: 2.1.0.0
Celery: 3.1.23
Python: 2.7.11
Django: 1.9.6

my celery backend is redis.

**Comment by lvh** [comment]
Still seeing this issue, also getting `worker: Warm shutdown (MainProcess)` with gevent, eventlet doesn't resolve the issue.

@bcoca The commits you linked introduced some behavior that was later removed in https://github.com/ansible/ansible/commit/b63238ff2ca5ed4155ac3637fd4426725228f001. Is that removal intentional? It seems like that behavior was added to resolve the issue (that's what closed this). Either way, it seems like this should be reopened since it's ostensibly still a problem?

**Comment by lvh** [comment]
@steve-gregory I don't know if you did any digging into this, but setting `PYTHONOPTIMIZE` might not really fix the problem. It will disable the assertion in multiprocessing that makes it so that daemonized processes can't create child processes (since they'd be unable to reap them). Have you noticed any problems with using this? If you're using ansible against a larger number of hosts, it would seem like a _lot_ of processes would get created.

**Comment by targetoyes** [comment]
@lvh I also have that problem today.Has that been solved?

**Comment by lvh** [comment]
@targetoyes My last comment and the issue I linked in celery should give you full relevant information.

**Comment by serkansahin** [comment]
@lvh Hi ! I'm also getting the issue with the "worker: Warm shutdown (MainProcess)", am using celery==3.1.24 and billiard==3.5.0.1 :/ what is your advise ?

**Comment by lvh** [comment]
@serkansahin The linked issue in celery/celery details the problem and a fix in celery.

**Comment by serkansahin** [comment]
@lvh I did it :) Now it's half working....I still have the same worker warm shutdown message..but does the job and if I recall the ansible playbookexecutor function it restarts the celery worker.... :/ Still trying to fix it, will give a feedback later..

**Comment by serkansahin** [comment]
@lvh I have exactly this issue : https://github.com/celery/billiard/issues/189 see ramonz comment

**Comment by lvh** [comment]
That looks like a very different error message to me. We don't have the same issue, so I have no advice for how to fix it.

**Comment by aturetta** [comment]
in my case the error was the result of an absent dependencies key in my role's metadata/main.yml
fixed by adding
`dependencies: []`
