### ISSUE TITLE
Can't disable become and sudo together.

### ISSUE THREAD

**Issue by saltos** [ansible/ansible#14410]
Code:

```
- name: "Some action'"
  become: no
  sudo:   no
  local_action: shell echo "Some action"
```

Error:

```
ERROR! The become params (\"become\", \"become_user\") and sudo params (\"sudo\", \"sudo_user\") cannot be used together
```

But I wont to disable become and sudo. I do not use them together.

**Comment by jimi-c** [comment]
Hi @saltos, this is a misunderstanding of the two options. The `become` option has replaced `sudo`, so `sudo` should not be used.

If  you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by saltos** [comment]
Actually I don't know how my scenario will be used - with become or with sudo.
But I want protect it from the both escalation methods.

**Comment by bcoca** [comment]
`become: no` will prevent both sudo and su

**Comment by saltos** [comment]
Ok, thank you!
