### ISSUE TITLE
lineinfile

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible#14419]
Hi

I have a file with the below content. I need to update the ip address dynamically.

  "Bamboo": {
    "Endpoint": "http://xx.xxx.xx.xx:8000",

I tried the below in my playbook
- name: Ensure Bamboo endpoint is updated
  lineinfile: dest=/var/bamboo/production.json state=present regex='^Bamboo ' insertafter='^Bamboo ' line=""Endpoint": "http://{{ansible_default_ipv4.address}}:8000","

But see the error as below

The offending line appears to be:
- name: Ensure Bamboo endpoint is updated
  lineinfile: dest=/var/bamboo/production.json state=present regex='^Bamboo ' insertafter='^Bamboo ' line=""Endpoint": "http://{{ansible_default_ipv4.address}}:8000","
                                                                                                                     ^ here
  We could be wrong, but this one looks like it might be an issue with
  missing quotes.  Always quote template expression brackets when they start a value.

Can you please suggest?

Thanks,
Govind

**Comment by abadger** [comment]
There's a few things about your task that will cause it not to work.  The main thing, and the cause of error message you're seeing is that you are trying to embed double quotes (") inside of a double quoted string without escaping them.  Here's a version of your task with that and other problems that I noticed cleaned up:

```
---
- hosts: roan.lan
  tasks:
  - name: Ensure Bamboo endpoint is updated
    lineinfile:
      dest: /var/tmp/production.json
      state: present
      regexp: '^ *"Endpoint"'
      insertafter: '^Bamboo'
      line: '    "Endpoint": "http://{{ansible_default_ipv4.address}}:8000",'
```

Things changed:
- passing parameters via key=value works but sometimes in 1.x (hopefully not nearly as much in 2.x) it can mess up with complicated quoting and escaping.  Using yaml dict format is easier for ansible to parse correctly and is also easier for a human to read.
- Changed the regex parameter to regexp.
- Used regexp to define a line to replace. It seemed that what you wanted is to replace whatever the current Endpoint line was in the file, not the "Bamboo:"  line.
- And quoting -- instead of trying to embed double quotes inside of the string and having to escape the quotes, putting them inside of a single quoted string seemed clearer and easier to read.

If you have other questions which are more usage related rather than bugs, it's better to use the mailing list and IRC to get answers:

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
