### ISSUE TITLE
lineinfile: regexp="...\b..." no longer matches in v2

### ISSUE THREAD

**Issue by nichivo** [ansible/ansible#14449]
Given this line in /etc/ssh/sshd_config:

```
#AddressFamily any
```

this task in Ansible v1.9.4:

```
lineinfile: dest=/etc/ssh/sshd_config regexp='^[ \t#]*AddressFamily\b.*' line='AddressFamily inet'
```

would replace the line as expected with:

```
AddressFamily inet
```

In v2.0.0.2, the regex doesn't match and the line is instead added to the bottom of the file. However, escaping the \b and using \b in the regex works! Backslashes for other character classes like \w don't need to be escaped - this regex matches:

```
'^[ \t#]*AddressFamily \w+'
```

Is it a "bug" or a "feature" that only \b now needs to be \b in Ansible v2?

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
