### ISSUE TITLE
ec2_vpc_route_table not updating?

### ISSUE THREAD

**Issue by mattgrahamdevops** [ansible/ansible#14459]
Issue: Not sure if Im doing something wrong, but I can add the routes using ec2_vpc_route_table module but if I terminate the NAT instances that are in the routes (instance_id), you see the "black hole" in AWS GUI but for some reason when I go to run my playbook again, it creates new NAT's, gets the instance id's and then attempts to apply them to the route table but fails. If I manually go in and delete the "black hole" routes and run the playbook, its fine. 

Version: ansible 2.0.0.2

playbook code:
- name: App Private Route Table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_id }}"
      region: "{{ aws_region }}"
      subnets: "{{ item.subnet }}"
      tags:
        Name: "{{ env | default('test') }}_app_private_{{ item.az }}"
      routes:
        - dest: 0.0.0.0/0
          instance_id: "{{ item.instance }}"
    with_items:
      - { Name: app_a, subnet: "{{ cidr }}.5.0/24", instance: "{{ nat_servers.results[0].tagged_instances[0].id }}", az: a }
      - { Name: app_b, subnet: "{{ cidr }}.6.0/24", instance: "{{ nat_servers.results[1].tagged_instances[0].id }}", az: b }

Error: 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'NoneType' is not iterable
failed: [localhost] => (item={u'subnet': u'10.40.5.0/24', u'az': u'a', u'Name': u'app_a', u'instance': u'i-fddcfa22'}) => {"failed": true, "item": {"Name": "app_a", "az": "a", "instance": "i-fddcfa22", "subnet": "10.40.5.0/24"}, "parsed": false}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'NoneType' is not iterable
failed: [localhost] => (item={u'subnet': u'10.40.6.0/24', u'az': u'b', u'Name': u'app_b', u'instance': u'i-d6b1b908'}) => {"failed": true, "item": {"Name": "app_b", "az": "b", "instance": "i-d6b1b908", "subnet": "10.40.6.0/24"}, "parsed": false}

Curren route table looks like:

0.0.0.0/0 eni-af3902c8 / i-3a0b2de5 Black Hole No

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by mattgrahamdevops** [comment]
Cheers and thanks for the info. :-)
