### ISSUE TITLE
win_webpicmd_module doc error

### ISSUE THREAD

**Issue by taraslayshchuk** [ansible/ansible#14452]
There is proposal at win_webpicmd_module [description](http://docs.ansible.com/ansible/win_webpicmd_module.html#notes) to use win_reboot module, but I cannot find it in ansible [win modules list](http://docs.ansible.com/ansible/list_of_windows_modules.html)
By the way most of modules contains information about features which were added in 2.1, but 2.1 has not been released yet.

**Comment by jhawkesworth** [comment]
I think that is a reference to module which has not been merged.
There's a win_reboot role on ansible galaxy which might meet your needs.
I believe Ansible policy in the past has been to document development version.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
