### ISSUE TITLE
seport does not reassign port already used in system policy

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#14466]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

I hope irrelevant
##### Environment:

Fedora 23 on my machine, CentOs 7 it is managed.
##### Summary:

seport module does not reassign port if it already assigned elsewhere. It report OK, but do nothing. Even no error.
##### Steps To Reproduce:

```
- seport: ports=8020 proto=tcp setype=http_port_t state=present
```

```
ok: [unidata.perf.client] => {"changed": false, "ports": ["8020"], "proto": "tcp", "setype": "http_port_t", "state": "present"}
```
##### Expected Results:

SELinux port 8020 assigned to http_port_t type.
##### Actual Results:

It does not happened:

```
# semanage port -l | ag '^http_port_t|8020'
hadoop_namenode_port_t         tcp      8020
http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443, 9000
```

I think next is a reason:

```
# semanage port -a -t http_port_t -p tcp 8020
ValueError: Port tcp/8020 already defined
```

But modify work:

```
# semanage port -m -t http_port_t -p tcp 8020
# semanage port -l | ag '^http_port_t|8020'
hadoop_namenode_port_t         tcp      8020
http_port_t                    tcp      8020, 80, 81, 443, 488, 8008, 8009, 8443, 9000
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
