### ISSUE TITLE
Add validate_certs option to vsphere_guest module

### ISSUE THREAD

**Issue by matts-mpg** [ansible/ansible#14463]
I am writing a playbook using the vpshere_guest module, and trying to test in a lab. However, I get the output:

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [do the vm] ***************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "parsed": false}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1

I noticed that in the uri module there is an option to set validate_certs to no, which I believe is what would solve this issue for me without having to go get a valid cert for testing this in a lab.

Thanks

**Comment by matts-mpg** [comment]
Sorry, running Ansible 2.0.0.2 and python 2.7.10 in case that helps.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
