### ISSUE TITLE
Variables in role dependencies not correctly scoped so defaults are overriden by different role invocations in Ansible 2.0.0.2

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible#14472]
If I have a role that I use multiple times in the same playbook with different variables each time, a variable declared in one invocation of the role will override defaults in other invocations of the same role. 

I've committed a playbook with roles that illustrates the problem: https://github.com/dwcramer/ansible-bug

Notice that the role example2 depends on the role example more than one time but passes different variables each time. The effect would also exist if I have several different roles depending on the same role with different variables passed in. For example, say I'm using a role that sets up upstart jobs for different services I lay down. 

Notice that in Ansible 2.x, a value assigned to a variable in one invocation of the role (`some_variable: [1,2]`  overrides the default in all invocations of the role, not just the one to which it applies.

A workaround is to explicitly assign a value to the role each time you invoke it, but that's not how it should work.

The actual output of this playbook is:

```
davcrame@DAVCRAME-M-G095 ~/dsx/ansible-bug
$ ansible-playbook -i inventory playbook.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [example : Print example variable] ****************************************
ok: [localhost] => {
    "some_variable": [
        1,
        2
    ]
}

TASK [example : Print example variable] ****************************************
ok: [localhost] => {
    "some_variable": [
        1,
        2
    ]
}

TASK [example : Print example variable] ****************************************
ok: [localhost] => {
    "some_variable": [
        1,
        2
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

The expected output and the output from Ansible 1.9.x is:

```
davcrame@DAVCRAME-M-G095 ~/dsx/ansible-bug (master)
$ ansible-playbook -i inventory playbook.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [example | Print example variable] **************************************
ok: [localhost] => {
    "var": {
        "some_variable": "False"
    }
}

TASK: [example | Print example variable] **************************************
ok: [localhost] => {
    "var": {
        "some_variable": [
            1,
            2
        ]
    }
}

TASK: [example | Print example variable] **************************************
ok: [localhost] => {
    "var": {
        "some_variable": "False"
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

**Comment by krtek4** [comment]
I am encountering a variation of this issue, when I have a role with a dependency, say something along the lines of : 

```
- { role: supervisor, service_name: "solr", user: "solr", command: "{{ solr_command }}", root_directory: "{{ solr_install_dir }}" }
```

All subsequent reference to `root_directory` in the following roles will now have the value of `solr_install_dir` instead of the "original" value.

This happened to work as I expect in latest Ansible versions.

**Comment by faern** [comment]
I'm having the same problem in 2.0.1.0.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
