### ISSUE TITLE
Allow setting SSH options on a per-host basis

### ISSUE THREAD

**Issue by haasn** [ansible/ansible#14470]
Some SSH-related options like timeout, ssh_args and host_key_checking can only be set globally, but not on a per-host basis.

As a result, I have to resort to ugly hacks like manually running ansible as:

```
ANSIBLE_TIMEOUT=30 ANSIBLE_SSH_ARGS="-o UserKnownHostsFile=/dev/null" ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook site.yml --limit some-specific-host
```

...when I would really prefer to set this as a host-specific variable.

**Comment by jimi-c** [comment]
@haasn you can already do this, via the `ansible_ssh_common_args` and `ansible_ssh_extra_args` set on inventory hosts/groups. 

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
