### ISSUE TITLE
Dependency variable resolution error

### ISSUE THREAD

**Issue by mliudev** [ansible/ansible#14475]
Issue Type: Bug Report
Ansible version: 2.0.0.0
OS: OS X El Capitan 10.11.3

I'm experiencing a problem with Ansible variable resolution when running roles that are also dependencies for other roles. Consider a scenario with two roles, a sub-role, and a main-role. The sub-role requires a parameter `sub_role_foo` or else will fail. This var is set in sub-role's defaults. We call this role first in our playbook. The second role we call is main-role. `main-role` has a meta dependency on sub-role. However, we override `sub_role_foo` with `top_level_foo`. `top_level_foo` is passed as a parameter to main-role when we call it.

I have a github repository demonstrating this issue: https://github.com/mliudev/ansible-var-bug.

We expect this playbook to run the first role using it's default variable, however this is not the case. Instead the following error occurs:

```
TASK [sub-role : fail] *********************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'sub_role_foo is not defined' failed. The error was: ERROR! error while evaluating conditional (sub_role_foo is not defined): ERROR! ERROR! 'top_level_foo' is undefined\n\nThe error appears to have been in '/Users/manwe/git/ansible-sandbox/roles/sub-role/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- fail: msg=\"sub_role_foo is required\"\n  ^ here\n"}
```

It appears that the first call to sub-role is expecting a variable to be defined that it should not know about.

**Comment by mliudev** [comment]
I believe this is similar to https://github.com/ansible/ansible/issues/14472.

**Comment by davidbirdsong** [comment]
probably related #13792

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
