### ISSUE TITLE
Breaking change in relative path logic between 1.9.4 and 2

### ISSUE THREAD

**Issue by ghostwords** [ansible/ansible#14489]
##### Issue Type:

This is a bug report.
##### Ansible Version:

1.9.4 and 2.0.0.2
##### Environment:

Ubuntu 14.04
##### Summary:

Ansible 1.x: Relative paths are resolved relative to the playbook's directory.
Ansible 2.x: Relative paths are resolved relative to current working directory.
##### Steps To Reproduce:

Say you have the following project structure under `/home/user/Projects/`:

```
|-project/
    |-ansible/
        |-playbook.yaml
    |-project/
```

And the following tasks in `playbook.yaml`:

```
- local_action: command chdir=../project pwd
  register: result
  become: False
- debug: var=result.stdout
```
##### Expected Results:

1.9.4 produces:

```
TASK: [deploy | debug var=result.stdout] ************************************** 
ok: [example.com] => {
    "var": {
        "result.stdout": "/home/user/Projects/project/project"
    }
}
```
##### Actual Results:

2.0.0.2 produces:

```
TASK [deploy : debug] **********************************************************
ok: [example.com] => {
    "result.stdout": "/home/user/Projects/project"
}
```

**Comment by bcoca** [comment]
relative paths were 'from execution directory' which in most cases was the home of the login user. But in the case of local connections, it should be cwd.

**Comment by ghostwords** [comment]
Is this an expected backwards-incompatible change in Ansible 2? If so, is it documented?

**Comment by bcoca** [comment]
not expected change, as I would call the behavior you describe, a bug. Leaving this open to confirm

**Comment by ghostwords** [comment]
#14341 seems related.

**Comment by spiette** [comment]
I tend to disagree that this is a bug. To me, Ansible 2.x brought some sanity to the path lookups. You don't need to bury your host_vars and groups_vars in your playbooks directory anymore.

**Comment by gotgenes** [comment]
Is there any documentation to the expected behavior of relative paths as sources e.g., under what roots Ansible searches for relative paths, in what precedence/order it searches those, etc.? The documentation of the [copy module](http://docs.ansible.com/ansible/copy_module.html) and [template module](http://docs.ansible.com/ansible/template_module.html) documentation say nothing of the expected behavior for relative paths. The [documentation on roles](http://docs.ansible.com/ansible/playbooks_roles.html#roles) says:

> Any copy, script, template or include tasks (in the role) can reference files in roles/x/{files,templates,tasks}/ (dir depends on task) without having to path them relatively or absolutely).

I find the phrase "without having to path them relatively or absolutely" befuddling given that it has to be relative to _somewhere_ Ansible is looking.

**Comment by ghostwords** [comment]
That quote just tries to explain a benefit of structuring your resources in a role in a standard way. If you follow the Ansible convention, you don't need to specify paths for those resources when referencing them in modules (`src=template.j2` will work because `template.j2` is where Ansible knows templates are to be found).

**Comment by bcoca** [comment]
So this has been a historically nebulous thing in Ansible and coded different ways, in 2.2 (current devel) I have narrowed down the behavior to be what was most common and tried to make it consistent everywhere by pointing at common functions, which we had begun doing in 2.0 (if i missed a spot, it is a bug).

I'm writing up docs on expected paths for action plugins (copy, template) and lookups, the gist is:

- relative paths get attempted first with a 'files|templates|vars' in path (if not already present) depending on action being taken, 'files' is the default. (i.e include_vars will use vars/).
- paths will be searched from most specific to most general (i.e role before play).
- dependent roles WILL be traversed (i.e task is in role2, role2 is a dependency of role1, role2 will be looked at first, then role1, then play).
- role search path is rolename/{files|vars|templates}/, rolename/tasks/.
- play search path is playdir/{files|vars|templates}/, playdir/.
- the current working directory (cwd) is not searched. If you see it, it just happens to coincide with one of the paths above.
- include of a task file from a role will NOT trigger role behavior, this only happens when running as a role.
- new ansible_search_path var will have the search path used, in order.
- 5 vs (-vvvvv) should show the detail of the search as it happens.
- this does NOT affect absolute paths

Does this clarify things? does it make sense?

**Comment by ghostwords** [comment]
@bcoca Does your answer cover my original bug report? If I pass a relative path to the `chdir` param of the command module, what is/should the path be relative to?

**Comment by bcoca** [comment]
sorry, i 'followed the hijack', I'll delete and move to more appropriate spot.

The 'module execution' is relative to the 'connection login path', which has nothing to do with playbooks or roles. So most commonly with ssh this was the login user's home directory, with local it is the cwd, which did change in 2.0. As 1.x did change the ansible cwd to follow the play execution, but 2.0 does not do this as it converts most things to full paths using the 'current basedir' (based on playbook/task location).

This has created a 'less predictable' path for `local: command`, I'm still not sure this is a bug or if we need to make special considerations for shell/command/raw when using local connections.

**Comment by bcoca** [comment]
So I found this in the code for local connection plugin:
`# FIXME: cwd= needs to be set to the basedir of the playbook`
and since no one else has strong opinions on this being a bug or not ... I'm going to try to fix this.

**Comment by bcoca** [comment]
@ghostwords please confirm that the above PR fixes the issue for you also.

**Comment by ghostwords** [comment]
Ansible from master (version 2.2.0) seems to have my original issue addressed. Thank you!
