### ISSUE TITLE
vars in role playbook script will refer to the vars definition of other role directory when current role do not have the var definition.

### ISSUE THREAD

**Issue by zabrahair** [ansible/ansible#14495]
When Used Roles in playbook together,
  roles:
- {name: "ubuntu", tags: ["ubuntu"]}
- {name: "centos", tags: "centos"}
- {name: "windows", tags: "windows"}

and every role have same main.yml in their tasks folder:
- name: Task Debug OS Role Vars
  debug: msg=“{{os_version}}”
- debug: msg=os_alias={{os_alias}}
- name: OS Role Default Vars
  debug: msg=os_type={{os_type}}
- debug: msg=os_dist={{os_dist}}
- debug: msg=os_bit={{os_bit}}  

but if one role do not have var response to his var definition file, for example os_type is not define in centos/vars/main.yml
And another role have the var, for example windows have the var os_type=windows,
then run the playbook, the centos playbook will refer the var "os_type" which is not existed in his role sub-directory to windows role directory.

I think that is a very serious bug, as if playbook writer forget to set a var but used it. and another role have the same name var.  

Then the play ook will use the un-expected var to its tasks

**Comment by jimi-c** [comment]
Hi @zabrahair, this is expected behavior. You should always have some default in the defaults/main.yml or define the var where you need it, because otherwise the variable will be available in the global scope from elsewhere.

In 2.0 we did introduced a configuration option (`private_role_vars` in the `defaults` section of the cfg) to keep vars from being seen outside its own role, however this does not apply to default variables.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
