### ISSUE TITLE
stat hangs on large files

### ISSUE THREAD

**Issue by rokka-n** [ansible/ansible#14516]
##### Ansible Configuration:

```
cat ansible.cfg
[defaults]
host_key_checking = False
```
##### Environment:

Amazon Linux, both server and remote host
##### Summary:

Ansible hangs on stat.

```
- name: Check if file was already downloaded from s3
  stat: path=/db-restore/{{ filename_gz }}
  register: s3_target_file
```
##### Steps To Reproduce:

Create a file 10-100G and check its stat
##### Expected Results:

Step should pass without delay
##### Actual Results:

Step hangs forever

**Comment by sivel** [comment]
The default for the stat module is to calculate the sha1 and md5 of the file.  You should supply `get_md5=false get_checksum=false` to prevent this from happening.  Otherwise it will take time to calculate those hashes.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by rokka-n** [comment]
Thanks!

**Comment by rishibamba** [comment]
Thanks sivel :)
