### ISSUE TITLE
tags specification in role dependencies ignored

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#14525]
##### Issue Type:
- Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

Irrelevant
##### Environment:

Fedora 23
##### Summary:

Tags honored when it included/excluded from command-line. But not in role dependencies (is there exclude possibility also?)!
##### Steps To Reproduce:

Playbook:

```
- hosts: localhost
  connection: local
  roles:
    - testdep
```

role `testdep`/meta/main.yml:

```
dependencies:
  - { role: test, tags: tag1 }
  - { role: test, tags: [ 'tag1' ] }
```

Please note I have try two variants of specify it.

role `test`/tasks/main.yml:

```
- name: Task with tag1
  raw: echo Run task with tag1
  tags: tag1

- name: Task with tag2
  raw: echo Run task with tag2
  tags: tag2
```
##### Expected Results:

From role `test` executed only task "Task with tag1" as it only have `tag1`.
##### Actual Results:

PLAY ***************************************************************************

```
TASK [test : Task with tag1] ***************************************************
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Run task with tag1\n", "stdout_lines": ["Run task with tag1"]}

TASK [test : Task with tag2] ***************************************************
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Run task with tag2\n", "stdout_lines": ["Run task with tag2"]}

TASK [test : Task with tag1] ***************************************************
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Run task with tag1\n", "stdout_lines": ["Run task with tag1"]}

TASK [test : Task with tag2] ***************************************************
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Run task with tag2\n", "stdout_lines": ["Run task with tag2"]}
```

I think it may be related to old https://github.com/ansible/ansible/issues/4524 . But there tags spec just ignored, did not any errors or warning happened.

**Comment by bcoca** [comment]
I would actually expect BOTH tasks to run, as when you add the tag1 to the role, it gets added to ALL the tasks in the role.

so the 2nd task ends up having tag1 AND tag2.

**Comment by jimi-c** [comment]
@bcoca is correct. The tags are not overwritten, but are instead merged. I would only expect the single task from the role to be run if you specified `--tags=tag2`.

**Comment by Hubbitus** [comment]
You want say what

```
dependencies:
  - { role: test, tags: tag1 }
```

**assign** `tag1` that tag to all `role`'s tasks instead of filter they?

Is there then way to setup dependency to part of the role, tagged by some tags only?

**Comment by jimi-c** [comment]
So looking back through old issues, I believe this is a misunderstanding of how the `tags` keyword works on roles. When used as you did, the tags are applied to every task in that role. This is NOT a filtering mechanism. We have older feature requests to implement a filtering mechanism, however currently none are implemented.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
