### ISSUE TITLE
ansible-playbook optional json output

### ISSUE THREAD

**Issue by pixelrebel** [ansible/ansible#14544]
##### Issue Type:
- Feature Idea
##### Ansible Version:
- 2.0.0.2 
##### Summary:

Would be nice to have an option to return the stdout as a json string.  
##### Steps To Reproduce:

`ansible-playbook -j myplay.yml`
##### Expected Results:

Instead of the verbose output, you would get back an organized object:

```
{ 
  "play": "The name of this play",
  "tasks": [
    {"name": "Task 1", 
     "hosts": [ {"hostname": "myhost1", "result":"ok","registered_vars": {"mystrvar":"my variable"}}]
    }, 
    {"name": "Task 2", 
     "hosts": [ {"hostname": "myhost1", "result":"ok","registered_vars": {"myjsonvar":{"key":"value"}}}] 
    },
  ],
  "recap": {'myhost1': {'unreachable': 0, 'skipped': 0, 'ok': 2, 'changed': 0, 'failures': 0}
}
```

**Comment by sivel** [comment]
I have actually had this sitting around from when I needed something similar.  Take a look at https://github.com/ansible/ansible/compare/devel...sivel:json-stdout-callback

ansible.cfg:

```
[defaults]
stdout_callback = json
```

If it looks good to you, I'll submit as a PR.

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits from #14569 should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
