### ISSUE TITLE
vsphere_guest cannot modify nic mac address

### ISSUE THREAD

**Issue by HalisCz** [ansible/ansible#14561]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Gentoo
##### Summary:

I would like to use vsphere_guest module to clone new VM from template, and customize VM's MAC address before powering on the VM.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
