### ISSUE TITLE
iam_policy used in a role should allow policy_document to come from the roles files directory

### ISSUE THREAD

**Issue by ashak** [ansible/ansible#14584]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 2.1.0 (devel 875ea74621) last updated 2016/02/16 19:55:32 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/14 21:23:29 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/14 21:23:30 (GMT +100)
  config file = /home/blah/code/cairn-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

$ cat ansible.cfg 
[defaults]
host_key_checking = False
inventory=${ANSIBLE_HOME}/contrib/inventory/ec2.py
##### Environment:

Running ansible on Debian Stretch
Managing Debian Jessie ec2 instances
##### Summary:

Some modules (copy is an example), when used in a role allow you to specify a file in the roles files directory for the src parameter. The iam_policy module, I expected its policy_document parameter to do the same thing. But it doesn't seem to do that, I simply get a 'No such file or directory'
##### Steps To Reproduce:

```
create files:
roles/test/tasks/main.yml
- local_action:
    module: iam_policy
    iam_type: group
    iam_name: AGroupNameThatExists
    policy_name: MyPolicy
    policy_document: my_policy.json
    state: present

roles/test/files/my_policy.json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject"
      ],
      "Resource": "arn:aws:s3:::some_test_bucket_name_that_exists/*"
    }
  ]
}

And use the role in your play.

If I change the policy_document parameter:
policy_document: roles/test/files/my_policy.json
```
##### Expected Results:

I expect policy_document: my_policy.json to find the file in my role files directory
##### Actual Results:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/blah/.ansible/tmp/ansible-tmp-1455903467.88-238145639200188/iam_policy", line 2632, in <module>
    main()
  File "/home/blah/.ansible/tmp/ansible-tmp-1455903467.88-238145639200188/iam_policy", line 300, in main
    with open(module.params.get('policy_document'), 'r') as json_data:
IOError: [Errno 2] No such file or directory: 'my_policy.json'

fatal: [52.19.237.203 -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "iam_policy"}, "parsed": false}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
