### ISSUE TITLE
_mysql_exceptions.NotSupportedError is thrown without SSL

### ISSUE THREAD

**Issue by giorgio-v** [ansible/ansible#14594]
##### Issue Type:

Bug Report
##### Ansible Version:

```
> ansible --version
ansible 2.0.0.2
  config file = /Users/giorgio/.ansible.cfg
  configured module search path = /Users/giorgio/Documents/PROJECTS/ansible-module
```
##### Ansible Configuration:

Here’s my `.ansible.cfg`

```
[defaults]
ansible_managed   = DO NOT EDIT MANUALLY: managed with Ansible
forks             = 10
hostfile          = ~/.ansible/hosts
roles_path        = ~/Documents/PROJECTS/ansible-roles
jinja2_extensions =  jinja2.ext.loopcontrols

[ssh_connection]
control_path      = %(directory)s/%%h-%%r
```
##### Environment:

Control machine:

```
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
```

Target machine: SmartOS, but I don’t think it is platform-specific.
Please mention the OS you are running Ansible from, and the OS you are
managing, or say “N/A” for anything that isn't platform-specific.
##### Summary:

Please explain the problem briefly.
##### Steps To Reproduce:

Create a playbook applying the following step.

```
- name: set root password
  mysql_user:
    name: root
    password: '{{ mysql_passwords.root }}'
```
##### Expected Results:

The application of the step.
##### Actual Results:

What actually happened?

The SSL is initialized to an _empty_ map, but this causes an exception. This is the same problem triggered in Python shell:

```
>>> db=MySQLdb.connect(host='localhost', db='mysql', port=3306, ssl={})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.NotSupportedError: client library does not have SSL support
>>> db=MySQLdb.connect(host='localhost', db='mysql', port=3306, ssl=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.NotSupportedError: client library does not have SSL support
```

This map is initialized here: https://github.com/ansible/ansible/blob/34e88e48a567d52e3ed0c3ecb6a5aa578e53dd19/lib/ansible/module_utils/mysql.py#L35

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by giorgio-v** [comment]
Sorry for being so late (you know, life), but it is unclear to me why this issue was closed.

The bug report and the proposed fix in the PR involve a file in this repo, even though it is used for MySQL:
https://github.com/ansible/ansible/blob/34e88e48a567d52e3ed0c3ecb6a5aa578e53dd19/lib/ansible/module_utils/mysql.py#L35

Let me know if this issue can be reopened, thank you.
