### ISSUE TITLE
module authorized_key and symbolic link

### ISSUE THREAD

**Issue by le9i0nx** [ansible/ansible#14590]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

```
[defaults]
filter_plugins = /etc/ansible/filter_plugins:/usr/share/ansible/plugins/filter
lookup_plugins = /etc/ansible/lookup_plugins:/usr/share/ansible/plugins/lookup

hostfile       = /etc/ansible/hosts
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root
transport      = smart
remote_port    = 22
module_lang    = C

gathering = implicit
sudo_exe = sudo
timeout = 10
ansible_managed = Ansible managed: modified on %Y-%m-%d %H:%M:%S

[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
```
##### Environment:

debina 8 
##### Summary:

If you change the key replaces the symbolic link.
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

```
- hosts: remote
  remote_user: root
  tasks:

  - name: Configure ~/.ssh/authorized_keys for users
    authorized_key:
      key: "ssh-key ... root@local"
      state: 'present'
      user: 'root'
```
##### Expected Results:

A symbolic link should be a symbolic link.

```
root@pve32:~/.ssh# ls -la
total 20
drwx------  2 root root 4096 Feb 20 11:58 .
drwx------ 10 root root 4096 Feb 20 11:57 ..
lrwxrwxrwx  1 root root   29 Feb 20 11:58 authorized_keys -> /etc/pve/priv/authorized_keys
-rw-r-----  1 root root   96 Feb 19 13:51 config
-rw-------  1 root root 1679 Feb 19 13:51 id_rsa
-rw-r--r--  1 root root  410 Feb 19 13:51 id_rsa.pub
```
##### Actual Results:

Link to file is replaced if the key is added.

```
root@pve32:~/.ssh# ls -la
total 24
drwx------  2 root root     4096 Feb 20 12:27 .
drwx------ 10 root root     4096 Feb 20 12:26 ..
-rw-------  1 root www-data 1553 Feb 20 12:27 authorized_keys
-rw-r-----  1 root root       96 Feb 19 13:51 config
-rw-------  1 root root     1679 Feb 19 13:51 id_rsa
-rw-r--r--  1 root root      410 Feb 19 13:51 id_rsa.pub
```

**Comment by bcoca** [comment]
This is expected behavior, it is rare  for this to be a symlink, normally you use ssh settings to switch the location.

I'm switching this to a feature request that we add a `follow=no|yes` option so user can control following symlinks or not before doing the substitution.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by bcoca** [comment]
sorry, responded here before realizing this is in the wrong repo, please open a feature request in the proper repo as we point to at above.
