### ISSUE TITLE
S3 module doesn't use AWS Signature Version 4

### ISSUE THREAD

**Issue by Du-St** [ansible/ansible#14602]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

NONE
##### Environment:
- CentOS 7 
- Ubuntu 14.04
##### Summary:

Using Ansible's S3 module I am not able to copy server-side encrypted files (Server Side Encryption with AWS KMS managed keys) from bucket to local directory although all needed settings are set and AWSCLI works well.

EC2 instance has IAM role with permissions to use the appropriate KMS key and access the bucket. I don't set variables access_key and access_secret_key explicitly. I am able to get non-encrypted files from the same bucket using Ansible's S3 module.
##### Steps To Reproduce:

CentOS7:
- yum install epel-release
- yum install python-pip
- yum install --enablerepo epel-testing ansible
- pip install --upgrade awscli
- aws configure set s3.signature_version s3v4
- ansible -vvv localhost -c local -m s3 -a 'region=eu-west-1 mode=get bucket=my-bucket object=/id_rsa dest=/root/.ssh/id_rsa'

But this works as expected:
- aws s3 cp 's3://my-bucket/id_rsa' /root/.ssh/id_rsa --region eu-west-1
##### Expected Results:

File id_rsa occurs in the /root/.ssh/ directory.
##### Actual Results:

Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705 )" )
127.0.0.1 PUT /tmp/tmppZN1Re TO /root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/s3
127.0.0.1 EXEC LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/s3; rm -rf "/root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/s3", line 2823, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/s3", line 496, in main
    download_s3file(module, s3, bucket, obj, dest, retries, version=version)
  File "/root/.ansible/tmp/ansible-tmp-1456127493.26-47301518663705/s3", line 323, in download_s3file
    key.get_contents_to_filename(dest)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 1665, in get_contents_to_filename
    response_headers=response_headers)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 1603, in get_contents_to_file
    response_headers=response_headers)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 1435, in get_file
    query_args=None)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 1467, in _get_file_internal
    override_num_retries=override_num_retries)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 325, in open
    override_num_retries=override_num_retries)
  File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 273, in open_read
    self.resp.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>null</ArgumentValue><RequestId>...</RequestId><HostId>...</HostId></Error>

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "s3"
    }, 
    "parsed": false
}

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
