### ISSUE TITLE
ALL_IN_SCHEMA negation filters

### ISSUE THREAD

**Issue by ciphernaut** [ansible/ansible#14607]
##### Issue Type:
- Feature Idea
##### Ansible Version:

1.9.4
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Using postgresql_privs to set or remove access to one or all tables is very handy.  Sometimes there are 1 or 2 tables that should not be granted but all others are ok.

To implement this currently one would have to grant select to ALL_IN_SCHEMA then revoke it from the desired tables.  This would have the consequence of triggering changed_when twice when the net change of the 2 combined is 0 on most subsequent runs.
##### Expected Results:

single invocation of 
- name: PostgreSQL | Update the users object privileges
  postgresql_privs:
    role: "{{item.name}}"
    db: "{{item.db}}"
    priv: "SELECT"
    state: present
    schema: "{{item.schema|default('public')}}"
    objs: "ALL_IN_SCHEMA,-password,-sessions"
    type: "table"
    login_host: "{{item.host | default('localhost')}}"
  with_items: postgresql_user_object_privileges
  when: postgresql_user_object_privileges|length > 0

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
