### ISSUE TITLE
Add support for RadosGW in S3 module.

### ISSUE THREAD

**Issue by thereallukl** [ansible/ansible#14603]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /home/lleszczu/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### Summary:

Currently only 3 modes are supported fakes3, walrus_s3 and amazon.com. Rados has s3 [http://docs.ceph.com/docs/master/radosgw/s3/](http://docs.ceph.com/docs/master/radosgw/s3/) implementation that should be supported as well
##### Steps To Reproduce:

Add s3_url with radosgw endpoint.
##### Expected Results:

Object being saved in ceph cluster.
##### Actual Results:

S3 module is returning error about non existing bucket.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
