### ISSUE TITLE
Assemble module error with `remote_src=no`

### ISSUE THREAD

**Issue by dochang** [ansible/ansible#14617]
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /home/doc/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
retry_files_save_path = ~/.ansible/retry
roles_path = ~/.ansible/roles

[ssh_connection]
pipelining = True
```
##### Environment:

Local machine: Debian sid
Remote server: Debian jessie
##### Summary:

The assemble module with `remote_src=no` doesn't generate the target file.
##### Steps To Reproduce:

I've created a github [repo](https://github.com/dochang/ansible-assemble-test-1456221291).

Clone this repo, run the playbook with `smart` connection:

```
ansible-playbook -i your.remote.server, -c smart test.yml
```

Or with `local` connection:

```
ansible-playbook -i localhost, -c local test.yml
```
##### Expected Results:

`/tmp/assemble-test` is generated with the correct content.
##### Actual Results:

With _smart_ connection, assemble module fails with the message `attempted to take checksum of directory: src`, and generates a file `~/src/tmpXXXXXX` on the remote server with the assembled content.

With _local_ connection, assemble module works if ansible needs to update the target file.  But if the target file has been already updated, ansible will put the assembled content into a file called `src` in the current directory on the local machine.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
