### ISSUE TITLE
New feature Needed in os_server module

### ISSUE THREAD

**Issue by ksingh7** [ansible/ansible#14658]
##### Issue Type:

os_server module does not provide any parameter to specify openstack instance system-group information. This is very much needed to setting affinity to newly launched instance.

The equivalent argument provided by nova boot as well as openstack server create command is `--hint group=b75981a0-b5f2-4365-bcb0-b9d1dfc24111`

It nice to have a parameter in ansible os_server module like 
group: "{{ system_group_name_or_ID }}"

We need this feature in os_server module

https://raymii.org/s/articles/Openstack_Affinity_Groups-make-sure-instances-are-on-the-same-or-a-different-hypervisor-host.html  
##### Ansible Version:

```
ansible 2.0.1.0
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
