### ISSUE TITLE
fstab parameter of mount module won't work

### ISSUE THREAD

**Issue by 64er** [ansible/ansible#14653]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
##### Environment:

Ubuntu 14.04 64Bit
##### Summary:

set fstab=**/tmp/fstab** in mount module result in 'can't find mount point in **/etc/fstab**'
##### Steps To Reproduce:

./test-module -m ../lib/ansible/modules/core/system/mount.py -a "src=/dev/sda9 name=/tmp/mnt fstype=ext3 state=mounted **fstab=/tmp/fstab**"
##### Expected Results:

changed: ok

and a line in /tmp/fstab and 'mount -a' should show the mounted device
##### Actual Results:

---

PARSED OUTPUT
{
    "failed": true, 
    "invocation": {
        "module_args": {
            "dump": null, 
            "fstab": **"/tmp/fstab"**, 
            "fstype": "ext3", 
            "name": "/tmp/mnt", 
            "opts": null, 
            "passno": null, 
            "src": "/dev/sda9", 
            "state": "mounted"
        }
    }, 
    "msg": "Error mounting /tmp/mnt: mount: /tmp/mnt konnte nicht in **/etc/fstab oder /etc/mtab** gefunden werden\n"
}

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
