### ISSUE TITLE
ec2_eip docs do not explain ip and public_ip parameters correctly

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#14673]
##### Issue Type:
- Documentation Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

control: MacOSX El Capitan
target: RHEL7 on AWS
##### Summary:

Documentation for ec2_eip here:
http://docs.ansible.com/ansible/ec2_eip_module.html

Examples use the parameter "ip" which is not listed in the parameter table. 
Parameter table shows "public_ip" but its use is unclear.

**Comment by slimandslam** [comment]
Also, the reuse_existing_ip_allowed parameter is not described correctly (or maybe just for EC2 Classic). For EC2 VPC, it will REASSIGN the EIP to another instance if you tell it to.  And the in_vpc parameter is not described correctly. If it's default is "no" and I'm running EC2 VPC, how does anything work at all? PLEASE FIX THIS DOCUMENTATION AND PROVIDE EXAMPLES.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
