### ISSUE TITLE
wait_for: Python exception "socket.error" thrown with search_regex

### ISSUE THREAD

**Issue by lpancescu** [ansible/ansible#14675]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No changes from defaults
##### Environment:

OS X 10.11.3 "El Capitan" host, CentOS 7 as a VirtualBox guest (through Vagrant 1.8.4), Ansible 2.0.0.2.1_0 from MacPorts
##### Summary:

I'm triggering a reboot and wait for the reboot to complete (until SSH is available again) using a solution based on https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back and issue #14413. This worked in Ansible 1.9.4, but triggers a Python exception on Ansible 2.0
##### Steps To Reproduce:

```
# roles/common/handlers/main.yml

---
- name: reboot system
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for boot to complete
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=30 search_regex=OpenSSH
  become: no
```
##### Expected Results:

Ansible should wait until SSH is available, after the reboot, without throwing any errors (the boot is successful, I checked for SSH availability afterwards).

Vagrant generates the following inventory file:

```
# Generated by Vagrant

default ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/Users/laur/devel/wordpress/.vagrant/machines/default/virtualbox/private_key'
```

This uses the deprecated variables `ansible_ssh_host` and `ansible_ssh_port`. If I replace the variables with the new names, `ansible_host` and `ansible_port` in the `wait_for` arguments above, there is no exception thrown, but Ansible finishes successfully only after the full default timeout, not as soon as the SSH server becomes available, and reports success. However, a debug: var statement placed right before the action triggering the notification handlers shows both pairs of variables, deprecated and new, as being identical, so I don't understand why it behaves differently.
##### Actual Results:

The following Python exception is thrown:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/laur/.ansible/tmp/ansible-tmp-1456479480.41-232291563686559/wait_for", line 2450, in <module>
    main()
  File "/Users/laur/.ansible/tmp/ansible-tmp-1456479480.41-232291563686559/wait_for", line 468, in main
    s.shutdown(socket.SHUT_RDWR)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 57] Socket is not connected

fatal: [default -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "wait_for"}, "parsed": false}
```

This only happens when I specify a `search_regex` argument. Without it, Ansible finishes the execution of wait_for successfully, but it seems to return before the OpenSSH server is really available.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
