### ISSUE TITLE
ec2_eip module returns true even when EIP is already assigned

### ISSUE THREAD

**Issue by slimandslam** [ansible/ansible#14683]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

Control machine: macosx el capitan
Target machine: AWS RHEL7 instance - t2.large
##### Summary:

An instance is already running with the EIP address. I then
try to assign the same EIP to a new instance, and the assignment appears
to succeed (though the instance comes up with no public ip address at all).
##### Steps To Reproduce:
1. Start an instance on AWS with an assigned EIP
2. Then start another instance on AWS and use the ec2_eip module and
   attempt to assign THE SAME EIP to it. 
3. It should fail, but doesn't.

```
 - name: associate an elastic IP with an instance
      ec2_eip: device_id={{ dev_id }} public_ip=52.36.100.30 region=us-west-2
      register: instance
```
##### Expected Results:

It should fail. If I'm wrong and this is the expected result, then the documentation should
be altered to make this VERY CLEAR. 
##### Actual Results:

```
TASK [associate an elastic IP with an instance] ********************************
task path: /Users/fred/myscript.yml:90
ESTABLISH LOCAL CONNECTION FOR USER: fred
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456512356.09-272760837751779 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456512356.09-272760837751779 `" )'
127.0.0.1 PUT /var/folders/lg/c_x9gpnj3kx6ssg58nkdd2m00000gn/T/tmpQalVtR TO /Users/fred/.ansible/tmp/ansible-tmp-1456512356.09-272760837751779/ec2_eip
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.US-ASCII LC_ALL=en_US.US-ASCII LC_MESSAGES=en_US.US-ASCII /usr/bin/python /Users/fred/.ansible/tmp/ansible-tmp-1456512356.09-272760837751779/ec2_eip'
changed: [localhost] => {"changed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "device_id": "i-42bef698", "ec2_url": null, "in_vpc": false, "profile": null, "public_ip": "52.36.100.30", "region": "us-west-2", "release_on_disassociation": false, "reuse_existing_ip_allowed": false, "security_token": null, "state": "present", "validate_certs": true, "wait_timeout": 300}, "module_name": "ec2_eip"}, "public_ip": "52.36.100.30"}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
