### ISSUE TITLE
Ansible precedence between role variable and set_fact is incorrect

### ISSUE THREAD

**Issue by mscherer** [ansible/ansible#14702]
##### Issue Type:
- Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0.2
  config file = /home/misc/.ansible.cfg
  configured module search path = Default w/o overrides

It also happen with latest devel snapshot
##### Ansible Configuration:

Nothing special
##### Environment:

N/A
##### Summary:

I just found out (because this cause me a lots of trouble) that variable are being kept from one role to another. I use set_fact to store temporary variables, and didn't realize that. So I started to clean (ie, set to False ) the temp variables. 

Now, i found that set_fact variables override the one set in a role, but even on subsequent role invocation on the same host.
##### Steps To Reproduce:

```
$ cat main.yml                             

---
- hosts: all
  connection: local
  roles:
  - role: test
    var: foo
  - role: test
    var: bar
```

```
$ cat roles/test/tasks/main.yml 

---
- debug: var=var
- set_fact: var=plop
```
##### Expected Results:

```
$ ansible-playbook -i '127.0.0.1,' main.yml                  

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [test : debug] ************************************************************
ok: [127.0.0.1] => {
    "var": "foo"
}

TASK [test : set_fact] *********************************************************
ok: [127.0.0.1]

TASK [test : debug] ************************************************************
ok: [127.0.0.1] => {
    "var": "bar"
}

TASK [test : set_fact] *********************************************************
ok: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0  
```
##### Actual Results:

Instead of having var having a value of "bar" in the 2nd role invocation, it keep the value "plop" from set_fact, which is surprising, since the doc say that role vars have precedence on set_fact.

```
$ ansible-playbook -i '127.0.0.1,' main.yml                  

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [test : debug] ************************************************************
ok: [127.0.0.1] => {
    "var": "foo"
}

TASK [test : set_fact] *********************************************************
ok: [127.0.0.1]

TASK [test : debug] ************************************************************
ok: [127.0.0.1] => {
    "var": "plop"
}

TASK [test : set_fact] *********************************************************
ok: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0  
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

What you are seeing is expected behavior, `set_fact` will update a variable associated with a host for the rest of the play, not just for the 'current role'. It is also supposed to override role default vars in precedence. 

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mscherer** [comment]
Then this doc must be clarified on what "role default" is vs "role and include vars". My understanding is that "role default" is variable defined in defaults/main.yml and that role vars would be the variable set on the role declaration level. 

This is also a direct contraction with the note in the doc https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_variables.rst#924 :
"There are some protections in place to avoid the need to namespace variables. In the above, variables defined in common_settings are most definitely available to 'something' and 'something_else' tasks, but if "something's" guaranteed to have foo set at 12, even if somewhere deep in common settings it set foo to 20."

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
