### ISSUE TITLE
FAILED: unsupported parameter for module: get_checksum

### ISSUE THREAD

**Issue by ahilali** [ansible/ansible#14722]
##### Issue Type:

- Bug Report
##### Ansible Version:
- ansible 2.0
##### Environment:
- Ubuntu 14.04
##### Steps To Reproduce:
- Install Ansible from the devel branch of the repository.
- Update hosts file with content in summary.
- Create a playbook using the synchronize module.
- Run it.
##### Expected Results:

It does synchronize files.
##### Actual Results:

fatal: [192.168.8.123]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/home/test_report/.ssh/keys/gitlab.ahilali.net): unsupported parameter for module: get_checksum"}

**Comment by bcoca** [comment]
this issues was true for a short time in devel as the submodules were updated, the change involved getting newer version of the stat module, please make sure you update to the latest version and this should be gone.

**Comment by dmikurube** [comment]
Let me report that this is happening with "copy" in 2.0.2.0, the latest in pypi. Downgrading to 2.0.1.0 worked around against this.

**Comment by dmikurube** [comment]
Ah, sorry, this was caused by another Ansible installation out of pip,but by apt.

**Comment by zarnovican** [comment]
@dmikurube Same here.

> this was caused by another Ansible installation out of pip,but by apt.

I have Ansible 2.0.2.0 inside virtualenv and Ansible 1.7 installed via system package. The problem is that virtualenv's ansible will still default to reading `/etc/ansible/ansible.cfg` where it is pointed to `library = /usr/share/ansible` (which are modules from much older Ansible). This is IMHO problem of Ansible defaults as well as my own setup.
