### ISSUE TITLE
dnf groupinstall failing with package not found

### ISSUE THREAD

**Issue by jpoet** [ansible/ansible#14734]
##### Environment:

from:  OSX Mavericks Darwin Kernel Version 14.5.0
managing: Fedora 23 4.2.3-300.fc23.x86_64
##### Summary:

In general ansible is working correctly, however `dnf groupinstall "Web Server"` is not working.  Issuing `dnf groupinstall "Web Server"` directing on the target machine works but the equivalent with ansible fails with:

failed: [topaz](item=[u'@Web Server']) => {"failed": true, "item": ["@Web Server"], "msg": "No group Web Server available."}
##### Steps To Reproduce:

test.yaml:

```

---
- name: Install web server
  hosts: fedora
  remote_user: john
  sudo: True
  tasks:
  - name: install web server
    dnf: pkg={{ item }} state=present
    with_items:
       - "@Web Server"
```

$ ansible-playbook --verbose -l topaz test.yaml

```
TASK [install web server] ******************************************************
failed: [topaz] (item=[u'@Web Server']) => {"failed": true, "item": ["@Web Server"], "msg": "No group Web Server available."}
```

I have tried changing "@Web Server" to:
 "@^Web Server"
 "@^Web-Server"
 "@Web-Server"

But they all fail with a similar message.
##### Expected Results:

The equivalent of:
dnf groupinstall "Web Server"
##### Actual Results:

```
TASK [install web server] ******************************************************
task path: /Users/john/Ansible/Playbooks/test.yaml:7
<10.0.5.52> ESTABLISH SSH CONNECTION FOR USER: john
<10.0.5.52> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/john/.ssh/id_rsa-topaz"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=john -o ConnectTimeout=10 -o ControlPath=/Users/john/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.5.52 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456865545.82-232926842360917 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456865545.82-232926842360917 `" )'"'"''
<10.0.5.52> PUT /var/folders/5q/qkwh8wh57sqg5t0sgl08mbfh0000gn/T/tmpKTneoW TO /home/john/.ansible/tmp/ansible-tmp-1456865545.82-232926842360917/dnf
<10.0.5.52> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/john/.ssh/id_rsa-topaz"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=john -o ConnectTimeout=10 -o ControlPath=/Users/john/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.5.52]'
<10.0.5.52> ESTABLISH SSH CONNECTION FOR USER: john
<10.0.5.52> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/john/.ssh/id_rsa-topaz"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=john -o ConnectTimeout=10 -o ControlPath=/Users/john/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.5.52 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=uppdbiismovvheemehvyztfjvrqoltyn] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-uppdbiismovvheemehvyztfjvrqoltyn; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/john/.ansible/tmp/ansible-tmp-1456865545.82-232926842360917/dnf; rm -rf "/home/john/.ansible/tmp/ansible-tmp-1456865545.82-232926842360917/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
failed: [topaz] (item=[u'@Web Server']) => {"failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": [], "enablerepo": [], "list": null, "name": ["@Web Server"], "state": "present"}, "module_name": "dnf"}, "item": ["@Web Server"], "msg": "No group Web Server available."}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
