### ISSUE TITLE
Checking if filesystem exists on imagefile

### ISSUE THREAD

**Issue by straight-shoota** [ansible/ansible#14746]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

nothing special
##### Environment:

n/a
##### Summary:

I am trying to create a filesystem on a virtual imagefile using filesystem module. First run it worked and the filesystem was created. But in subsequent runs the play fails with `ValueError: invalid literal for int() with base 10: ''`. This issue might be caused by the filesystem module expecting a real block device instead of a imagefile.
##### Steps To Reproduce:

Run the following playbook twice:

```
- hosts: 127.0.0.1
  connection: local
  vars:
    imagefile: /tmp/image.img
    imagesize: 16M

  tasks:
    - name: Create dd image
      command: dd if=/dev/zero of={{ imagefile }} bs=1 seek={{ imagesize }} count=1
    - name: Create filesystem
      filesystem: "dev={{ imagefile }} resizefs=yes fstype=ext4"
```
##### Expected Results:

On the first run, I expect an imagefile with filesystem to be created. This is fine.
On subsequent runs, I expect the play to recognize the existing filesystem (and resize it, if `imagesize` has changed). The task should result in `ok` (or `changed`) but instead it fails.
##### Actual Results:

From the second run onwards (when filesystem is in place), the task fails with the error message:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 2207, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 199, in main
    devsize_in_bytes = _get_dev_size(dev, module)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 71, in _get_dev_size
    return int(devsize_in_bytes)
ValueError: invalid literal for int() with base 10: ''

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "filesystem"}, "parsed": false}
```

It should be possible to find a workaround and only apply the filesystem task if the filesystem does not exists (test if mounting fails) but I'd prefer a proper solution.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
