### ISSUE TITLE
ec2_lc doesn't accept null for spot_price

### ISSUE THREAD

**Issue by morganchristiansson** [ansible/ansible#14750]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2 (detached HEAD 7de237c5a1) last updated 2016/02/03 11:56:50 (GMT +000)
  lib/ansible/modules/core: (detached HEAD ce6619bf5d) last updated 2016/02/03 12:47:51 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 29af26884e) last updated 2016/02/03 12:47:56 (GMT +000)
  config file = /home/ubuntu/infrastructure-devops/ansible/ansible.cfg
  configured module search path = modules
```
##### Ansible Configuration:

n/a
##### Environment:

Ubuntu 14.04.3 LTS
##### Summary:

I want to enable/disable spot_price via variable but there's no way to disable it while keeping the variable.
##### Steps To Reproduce:

Setting config_spot_price to a float works correctly and creates a spot instance.

But there's no way to create standard instances by setting config_spot_price to null as is suggested by documentation.

```
  - name: create launch config
    local_action:
      module: ec2_lc
      spot_price: "{{ config_spot_price }}"
      ...
```
##### Expected Results:

A normal instance is created without errors
##### Actual Results:

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "argument spot_price is of type <type 'NoneType'> and we were unable to convert to float"}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
