### ISSUE TITLE
get_url incorrectly returning a 302 error

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible#14782]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 4cfd042839) last updated 2016/03/03 11:14:21 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/03/01 11:10:24 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/03/01 11:10:24 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

running from OS X El Capitan
controlling CentOS
##### Summary:

Getting a 302 error trying to download rpm. The rpm is there.
##### Steps To Reproduce:

```
vars/rmpforge.yml:

---
rpmforge_version: 0.5.3-1.el6.rf.x86_64

install_rpmforge.yml:

---
- include_vars: vars/rpmforge.yml

- name: get rpmforge
  get_url:
    url: 'http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-{{ rpmforge_version }}.rpm'
    dest: /usr/src
    force: no


```
##### Expected Results:

If the file exists locally, I expect it to not do much at all
If the file doesn't exist locally, I expect it to get it
##### Actual Results:

Get a 302 error in either case

```
TASK [get rpmforge] ************************************************************
fatal: [trac]: FAILED! => {"changed": false, "dest": "/usr/src", "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 302: Found", "secontext": "system_u:object_r:usr_t:s0", "size": 4096, "state": "directory", "status_code": 302, "uid": 0, "url": "http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"}
    to retry, use: --limit @install_utilities.retry

```

**Comment by jgrigonis** [comment]
It seems to be a redirect from http to https causing the problem.

**Comment by mtnbikenc** [comment]
I hit this same bug.  Using `git bisect` I tracked down the problematic commit, which is prior to the version indicated by @jgrigonis. 

```
6ff0b079b4688df943af2da71c7533a0bf9ba0cb is the first bad commit
commit 6ff0b079b4688df943af2da71c7533a0bf9ba0cb
Author: Matt Martz <matt@sivel.net>
Date:   Wed Mar 2 16:30:16 2016 -0600

    Support SSL validation with redirect control for python versions without ssl context

:040000 040000 d595c903efd6b41b105836c3cd65e4bb8fae0492 800093d3266c5adb3620c8ada479240149c43539 M  lib
```

FYI @sivel

**Comment by sivel** [comment]
Thanks for the report.  I'll look into this soon.

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
