### ISSUE TITLE
ansible reading group_files files it shouldn't

### ISSUE THREAD

**Issue by phips** [ansible/ansible#14786]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

```
[defaults]
hostfile = inventory/box
host_key_checking = False
forks = 20
remote_user = vagrant
private_key_file = ~/.ssh/vagrant
system_warnings = False
roles_path = roles
nocows = 1
ansible_managed = Ansible managed: modified on %d-%b-%Y %H:%M by {uid} on {host}
retry_files_enabled = False
[ssh_connection]
pipelining=True
control_path = /tmp/%%h-%%r
```
##### Environment:

OS X 10.10.5
Ansible in virtualenv
##### Summary:

Running a play gave the 'ERROR! Decryption failed' message - however, the **only** Vault'd file I have is for a group not present in the inventory in question.
##### Steps To Reproduce:

Have a Vault'd file that has a problem (no idea _what_ problem, but, well) named after a group **not** in the inventory being used.

```
(pip)www3:cm$ ansible-playbook plays/set_deploy.yml --list-hosts
ERROR! Decryption failed
(pip)www3:cm$  ansible-playbook -h | grep -E 'inventory.+default'
specify inventory host path (default=inventory/box) or
(pip)www3:group_vars$ file App.yml 
App.yml: ASCII text
(pip)www3:group_vars$ cat !$
cat App.yml
$ANSIBLE_VAULT;1.1;AES256
...
(pip)www3:cm$ grep App inventory/box 
[nothing]
```
##### Expected Results:

Even if the Vault file did have a problem I wouldn't expect it to be included in this play - it did not feature in the inventory.
##### Actual Results:

```
(pip)www3:cm$ ansible-playbook plays/set_deploy.yml --list-hosts
ERROR! Decryption failed
```

**Comment by leafblowersama** [comment]
+1

**Comment by RebelCodeBase** [comment]
I have the same problem: Ansible (2.1.1.0) is trying to read/decrypt a vaulted config file from a group_vars subdirectory although the server is not a member of that group.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

All inventory files get read independent of `hosts:` clause, otherwise `hostsvars['otherhost']` would not work for hosts not defined in play, also it would make inventory dependent on `hosts:` when it is the opposite.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
FYI, even though inventory is not conditional, you CAN use `include_vars` to conditionally load vault files.
