### ISSUE TITLE
iam_cert doesn't return the ARN value after creating a certificate

### ISSUE THREAD

**Issue by elnur** [ansible/ansible#14787]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

Ubuntu 14.04.4 LTS
##### Summary:

I'm using the `iam_cert` module to create a certificate to use with ELB. I've registered a variable with the results of running that module and dumped it. There's no ARN field that I need to feed to the `ec2_elb_el` module.
##### Steps To Reproduce:

```
- name: Upload SSL certificate
  iam_cert:
    name: ssl
    state: present
    cert: cert.pem
    key: cert.key
  register: ssl_certificate

- debug: var=ssl_certificate
```
##### Expected Results:

I expect the ARN field in the returned result.

AWS CLI gives that information:

```
$ aws iam list-server-certificates
{
    "ServerCertificateMetadataList": [
        {
            "ServerCertificateId": "AS...SU", 
            "ServerCertificateName": "ssl", 
            "Expiration": "2025-11-16T12:52:40Z", 
            "Path": "/", 
            "Arn": "arn:aws:iam::4...9:server-certificate/ssl", 
            "UploadDate": "2016-03-03T21:46:09Z"
        }
    ]
}
```

So the info is there, but Ansible doesn't use it.
##### Actual Results:

```
ok: [localhost] => {
    "ssl_certificate": {
        "cert_body": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----", 
        "cert_path": "/", 
        "changed": false, 
        "expiration_date": "2025-11-16T12:52:40Z", 
        "msg": "No new path or name specified. No changes made", 
        "name": "ssl", 
        "upload_date": "2016-03-03T21:46:09Z"
    }
}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
