### ISSUE TITLE
with_subelements causes [WARNING]: Failure when attempting to use callback plugin

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#14800]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.1.0 (devel afa5b3743c) last updated 2016/03/04 14:03:33 (GMT +200)
##### Ansible Configuration:

Default
##### Environment:

Mac OS X, GNU/Linux
##### Summary:

with_subelements loop causes warning:

```
 [WARNING]: Failure when attempting to use callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x104a9fbd0>): not
all arguments converted during string formatting
```
##### Steps To Reproduce:

playbook:

```

---
- hosts: localhost
  vars:
    list:
      - { name: test, group: ['a','b','c'] }
  tasks:
    - debug:
        msg: "{{ item[0].name }} {{ item[1] }}"
      with_subelements:
        - "{{ list }}"
        - "group"
```
##### Expected Results:

Normal debug output.
##### Actual Results:

```
TASK [debug] *******************************************************************
 [WARNING]: Failure when attempting to use callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x1085c0310>): not
all arguments converted during string formatting
```

**Comment by if-kyle** [comment]
I get the same issue when I try using the stock example from the docs:

http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-subelements

```
ansible --version
ansible 2.1.0 (devel 9318727021) last updated 2016/03/09 14:55:08 (GMT -700)
  lib/ansible/modules/core: (detached HEAD c86a0ef84a) last updated 2016/03/09 14:55:16 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 33a557cc59) last updated 2016/03/09 14:55:16 (GMT -700)
  config file = /home/centos/create-client/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by rcarrillocruz** [comment]
Hitting the same in devel.

The resources being executed with 'with_subelements' get created, but instead of getting the changed output noting the state change just the warning message is displayed.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
