### ISSUE TITLE
You can't register a RHEL System to the RHN portal in < 2.0

### ISSUE THREAD

**Issue by jduncan-rva** [ansible/ansible#14803]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

default install on Fedora 23
##### Environment:

running on Fedora 23, managing RHEL 7.x systems
##### Summary:

When you use the redhat_subscription module you often want to use an activation key. When you register against RHN (not a Satellite or SAM server) you must specify an orginization ID when you use an activation key.

the --org_id parameter wasn't included until ansible 2.x

Can we backport that to 1.9?
##### Steps To Reproduce:

- use the redhat_subscription module with it pointing to RHN (the default)
- use an activation key
- get a subscription-manager error about --org needing to be specified

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
