### ISSUE TITLE
cron job does not escape `%` characters

### ISSUE THREAD

**Issue by devmage** [ansible/ansible#14853]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.1
  config file = /home/admin/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
inventory=~/bin/our-project-inventory
```
##### Environment:

`Linux ip-10-254-0-230 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux`
##### Summary:

Cron tasks as configured by the `cron` module do not escape `%` symbols. Documentation around the `cron` module does not specify that `%` symbols must be escaped. This causes early termination of cron tasks, as [unescaped `%` characters are interpreted as newlines](https://en.wikipedia.org/wiki/Cron#Format). This can cause unintended behavior in cron tasks.

This could reasonably be explained as a #wontfix and/or a feature of cron. However, it would be helpful then to at least document this behavior, and to document that Ansible does not attempt to escape cron syntax in `cron` entries.
##### Steps To Reproduce:

Create a `cron` task in a playbook, and run that playbook: 

```
- cron: name="a job for reboot" job="/bin/bash -c '/bin/sleep $(/usr/bin/expr $RANDOM % 60)m && script.sh"
```

This expression allows for a random sleep of 0-59 minutes before running `script.sh`. You will now have an entry in that machine's `/etc/cron.d/` as expected.

##### Expected Results:

The cron job sleeps for a random period, then `script.sh` runs without error.
##### Actual Results:

Per cron syntax, the `%` character above is interpreted as a newline, the expression fails, and `script.sh` is never executed.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by devmage** [comment]
Thanks for the information! Will reopen on `ansible-modules-core` as you instruct.

As an aside, your instructions block reads:

> Otherwise, submit your module

I believe you mean "submit your ticket". :)

You may also want to adjust the formatting in the line beginning "This appears", as there appears to be a line break after "modules", seen as:

> ... the modules
> in ansible ...
