### ISSUE TITLE
weird interaction between include, nested loops and {{ }} interpolation

### ISSUE THREAD

**Issue by pzr** [ansible/ansible#14883]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 210cf06d9a) last updated 2016/01/04 11:36:02 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 002028748f) last updated 2015/12/30 14:34:00 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD f6a7b6dd1f) last updated 2015/12/30 14:34:04 (GMT -500)
  config file = [censored]/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
$ cat ansible.cfg
# ansible.cfg

[defaults]
display_skipped_hosts=False
inventory=./production
nocolor=1
remote_tmp=/tmp
```
##### Environment:

Control machine is Linux.
##### Summary:

include + vars + with_nested does not evaluate {{ }} in vars correctly, if the included file uses with_items
##### Steps To Reproduce:

File playbook.yml contains:

```

---

- hosts: 127.0.0.1

  tasks:

    - include: ./tasks.yml
      vars:
        this_x: "{{ item[0] }}"
        this_y: "{{ item[1] }}"
      with_nested:
        - [ 'x1', 'x2' ]
        - [ 'y1', 'y2' ]

...
```

File tasks.yml contains:

```

---

#- set_fact:
#    this_x: "{{ item[0] }}"
#    this_y: "{{ item[1] }}"

- set_fact:
    all_z:
      - { z1: "this_x is {{ this_x }}", z2: "this_y is {{ this_y }}" }

- debug: msg="all_z == {{ all_z }}"

- debug: msg="item == {{ item }}"
  with_items: "{{ all_z }}"

...
```
##### Expected Results:

Should see four "item == xxx" messages, for (x1,y1), (x1,y2), (x2,y1), (x2,y2).
##### Actual Results:

```
$ ansible-playbook ./playbook.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [include] *****************************************************************
included: [censored]/tasks.yml for 127.0.0.1
included: [censored]/tasks.yml for 127.0.0.1
included: [censored]/tasks.yml for 127.0.0.1
included: [censored]/tasks.yml for 127.0.0.1

TASK [set_fact] ****************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "msg": "all_z == [{u'z1': u'this_x is x1', u'z2': u'this_y is y1'}]"
}

TASK [debug] *******************************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! dict object has no element 1"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=7    changed=0    unreachable=0    failed=1
```

If I comment out the var section in playbook.yml, and un-comment the set_fact in tasks.yml, the correct output is produced.

If I comment out the second debug task in tasks.yml (i.e., the one that has with_items), no error occurs.

It's unclear how the "item[1]" reference in playbook.yml can appear in the second debug task in tasks.yml without also appearing in the first, since both tasks reference the same all_z fact.

**Comment by jimi-c** [comment]
Hi @pzr, I believe you're running into this caveat: http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes

**Comment by pzr** [comment]
I think something slightly weirder than
http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes
is going on.

Consider playbook_2.yml:

```
---

- hosts: 127.0.0.1

  tasks:

    - include: ./tasks_2.yml
      vars:
        this_x: "{{ item }}"
      with_items:
        - "x1"
        - "x2"

...
```

and tasks_2.yml:

```
---

- set_fact:
    all_z:
      - { z1: "this_x is {{ this_x }}" }

- debug: msg="all_z == {{ all_z }}"

- debug: msg="item == {{ item }}"
  with_items: "{{ all_z }}"

...
```

These produce the expected output:

```
$ ansible-playbook ./playbook_2.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [include] *****************************************************************
included: [censored]/tasks_2.yml for 127.0.0.1
included: [censored]/tasks_2.yml for 127.0.0.1

TASK [set_fact] ****************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "msg": "all_z == [{u'z1': u'this_x is x1'}]"
}

TASK [debug] *******************************************************************
ok: [127.0.0.1] => (item={u'z1': u'this_x is x1'}) => {
    "item": {
        "z1": "this_x is x1"
    }, 
    "msg": "item == {u'z1': u'this_x is x1'}"
}

TASK [set_fact] ****************************************************************
ok: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "msg": "all_z == [{u'z1': u'this_x is x2'}]"
}

TASK [debug] *******************************************************************
ok: [127.0.0.1] => (item={u'z1': u'this_x is x2'}) => {
    "item": {
        "z1": "this_x is x2"
    }, 
    "msg": "item == {u'z1': u'this_x is x2'}"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=9    changed=0    unreachable=0    failed=0   
```

The reference to {{ item }} in playbook_2.yml is evaluated _before_ the with_items in tasks_2.yml, so the latter sees the correct value.

But in playbook.yml / tasks.yml (i.e., from the original report), evaluation of the {{ }} in the vars section of the include task is deferred somehow, because of the with_nested section. The references to item[0] / item[1] persist until the with_items in tasks.yml tries to evaluate them - but by then, item is no longer the one set by with_nested.

This is, admittedly, a really weird edge case with a fairly obvious workaround, so I'll understand if you resolve it as Won't-Fix. Perhaps clarifying in the documentation when / how {{ }} are evaluated would suffice?

**Comment by jimi-c** [comment]
Hi @pzr, just tested your original example above on the current devel as a follow-up, and it appears to have been resolved:

<pre>
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml
PLAY [127.0.0.1] ***************************************************************
TASK [setup] *******************************************************************
ok: [127.0.0.1]
TASK [include] *****************************************************************
task path: /root/testing/14883/test.yml:7
included: /root/testing/14883/tasks.yml for 127.0.0.1
included: /root/testing/14883/tasks.yml for 127.0.0.1
included: /root/testing/14883/tasks.yml for 127.0.0.1
included: /root/testing/14883/tasks.yml for 127.0.0.1
TASK [set_fact] ****************************************************************
task path: /root/testing/14883/tasks.yml:7
ok: [127.0.0.1] => {"ansible_facts": {"all_z": [{"z1": "this_x is x1", "z2": "this_y is y1"}]}, "changed": false}
TASK [debug] *******************************************************************
task path: /root/testing/14883/tasks.yml:13
ok: [127.0.0.1] => (item={u'z1': u'this_x is x1', u'z2': u'this_y is y1'}) => {
    "item": {
        "z1": "this_x is x1", 
        "z2": "this_y is y1"
    }, 
    "msg": "item == {u'z1': u'this_x is x1', u'z2': u'this_y is y1'}"
}
TASK [set_fact] ****************************************************************
task path: /root/testing/14883/tasks.yml:7
ok: [127.0.0.1] => {"ansible_facts": {"all_z": [{"z1": "this_x is x1", "z2": "this_y is y2"}]}, "changed": false}
TASK [debug] *******************************************************************
task path: /root/testing/14883/tasks.yml:13
ok: [127.0.0.1] => (item={u'z1': u'this_x is x1', u'z2': u'this_y is y2'}) => {
    "item": {
        "z1": "this_x is x1", 
        "z2": "this_y is y2"
    }, 
    "msg": "item == {u'z1': u'this_x is x1', u'z2': u'this_y is y2'}"
}
TASK [set_fact] ****************************************************************
task path: /root/testing/14883/tasks.yml:7
ok: [127.0.0.1] => {"ansible_facts": {"all_z": [{"z1": "this_x is x2", "z2": "this_y is y1"}]}, "changed": false}
TASK [debug] *******************************************************************
task path: /root/testing/14883/tasks.yml:13
ok: [127.0.0.1] => (item={u'z1': u'this_x is x2', u'z2': u'this_y is y1'}) => {
    "item": {
        "z1": "this_x is x2", 
        "z2": "this_y is y1"
    }, 
    "msg": "item == {u'z1': u'this_x is x2', u'z2': u'this_y is y1'}"
}
TASK [set_fact] ****************************************************************
task path: /root/testing/14883/tasks.yml:7
ok: [127.0.0.1] => {"ansible_facts": {"all_z": [{"z1": "this_x is x2", "z2": "this_y is y2"}]}, "changed": false}
TASK [debug] *******************************************************************
task path: /root/testing/14883/tasks.yml:13
ok: [127.0.0.1] => (item={u'z1': u'this_x is x2', u'z2': u'this_y is y2'}) => {
    "item": {
        "z1": "this_x is x2", 
        "z2": "this_y is y2"
    }, 
    "msg": "item == {u'z1': u'this_x is x2', u'z2': u'this_y is y2'}"
}
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=13   changed=0    unreachable=0    failed=0   
</pre>

I did remove the one debug to reduce noise.

Based on the above, I'm going to go ahead and close this now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
