### ISSUE TITLE
user module should allow setting of primary group id

### ISSUE THREAD

**Issue by mcv21** [ansible/ansible#14922]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

Most relevant to Unix targets.
##### Summary:

A common pattern (e.g. it's the default behaviour in Debian) is to create user and group with the same name and id - e.g. user mcv21 group mcv21 have the same UID. The user module is unable to do this - you can specify user id and primary group, but not the id of the primary group
##### Steps To Reproduce:

An example usage:

```
 - name: create a user
   user: name=foo uid=1021 group=foo gid=1021
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by dingens** [comment]
the issue has been recreated here: https://github.com/ansible/ansible-modules-core/issues/3291 - however it has been closed again a little later stating that issues are to be reported on this repo (ansible/ansible). I didn't find another issue for this issue. Please reopen!

**Comment by mcv21** [comment]
re-opened as #36718
