### ISSUE TITLE
wrong virtualization type detection (kvm instead of NA)

### ISSUE THREAD

**Issue by progfou** [ansible/ansible#14938]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.4
```
##### Ansible Configuration:

```
[defaults]
inventory = ./hosts

[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
```

(none of that should be specific to this bug)
##### Environment:

OS I'm running Ansible from: Ubuntu 14.04

OS I'm managing: Debian 8 (jessie), with kvm module loaded but unused (not a virtualization host)
##### Summary:

Some OS preload the 'kvm' module even if it's not actually used. When Ansible collects facts about virtualization, it deduce the OS is a kvm host where it isn't, just because it finds the kvm module loaded.

Skipping unused modules allows to avoid this kind of false positive. For this, we can use the fact that the third column in /proc/modules contains the module usage count.
##### Steps To Reproduce:
- load the kvm module on a host:  ssh the-host "sudo modprobe kvm"
- run ansible setup module to get its facts

```
ansible -m setup the-host | grep virtualization
```
##### Expected Results:

ansible_virtualization_type == 'NA'
ansible_virtualization_role == 'NA'
##### Actual Results:

ansible_virtualization_type == 'kvm'
ansible_virtualization_role == 'host'

**Comment by bcoca** [comment]
I would argue that the host is a 'kvm' host even if not using it currently.

**Comment by jimi-c** [comment]
@progfou I agree with @bcoca on this. The host is a KVM by virtue of having its module loaded. Disabling this fact in this manner may break the use-case where people are provisioning new KVM hosts but which have no vms running yet. As such, we're going to go ahead and close this PR.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by progfou** [comment]
Well, I can understand your point. But, speaking of virtualisation in such a generic way, all modern Linux servers should also be considered as LXC hosts! This certainly is a mater of view point, so I won't argue more and leave this bug closed. On my side, I'll simply continue to apply my mini-patch on my personal Ansible instance. Best regards.
