### ISSUE TITLE
Windows Support documentation recommendations

### ISSUE THREAD

**Issue by watsonb** [ansible/ansible#14957]
##### Issue Type:
- Documentation Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

Default
##### Environment:

Running Ansible on RedHat 6.x managing Windows Server 2012R2
##### Summary:
1. In the section entitled "Inventory", it is not clear if group_vars/windows.yml should be defined globally (e.g. /etc/ansible/group_vars/windows.yml) or at the playbook scope.  My assumption is that this must be defined globally (e.g. under /etc) as this is the configuration that worked for me.  The documentation should state which configuration(s) are supported and any precedence rules that may be in play.
2. I understand that in the transition to Ansible 2.0, the variables ansible_ssh_\* will be changing to ansible_*, however the current documentation set leads the reader to believe that for pre-2.0 users, the password credential would be specified as: ansible_ssh_password, when in fact it must be specified as: ansible_ssh_pass.  The former will lead to 401 Authorization errors on connecting to Windows whereas the later works in my setup.
##### Steps To Reproduce:

In /etc/ansible/group_vars/windows.yml

Specify Windows user password as:

ansible_ssh_password
##### Expected Results:

Expected Ansible to connect to Windows host using given credentials
##### Actual Results:

Receive reply from Windows host including 401 Authorization error

**Comment by jimi-c** [comment]
Hi @watsonb, the documentation here (http://docs.ansible.com/ansible/intro_inventory.html) mentions where group_vars files should live:

<pre>
Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.
</pre>

As this is more of a general use question than a bug, we're going to go ahead and close this now. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
