### ISSUE TITLE
ec2 module fails when instances are stopped

### ISSUE THREAD

**Issue by colin-byrne-1** [ansible/ansible#14986]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 6a62ad6c4b) last updated 2016/02/01 13:04:11 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/02/01 13:04:24 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/02/01 13:04:31 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

the ec2 module fails to recognize existing subnet instances that are STOPPED, in AWS, and instead throws the output:
`failed: [localhost] => (item=({u'cluster': u'preprod'}, {u'type': u'app', u'name': u'j-agency-2', u'private_ip': u'10.1.2.107'})) => {"failed": true, "item": [{"cluster": "preprod"}, {"name": "j-agency-2", "private_ip": "10.1.2.107", "type": "app"}], "msg": "Instance creation failed => InvalidIPAddress.InUse: Address 10.1.2.107 is in use."}`
##### Steps To Reproduce:
1. Create an ec2 instance in a private VPC
2. Stop that instance
3. Run the identical play creating that instance again.
##### Expected Results:

According to the [ec2 documentation](http://docs.ansible.com/ansible/ec2_module.html), state 'present' should be the default and it should recognize that an instance is present, but not 'running'
##### Actual Results:

Clearly ansible is trying to create another instance, because it has not recognized the existing instance. 

```
failed: [localhost] => (item=({u'cluster': u'preprod'}, {u'type': u'app', u'name': u'j-agency-2', u'private_ip': u'10.1.2.107'})) => {"failed": true, "item": [{"cluster": "preprod"}, {"name": "j-agency-2", "private_ip": "10.1.2.107", "type": "app"}], "msg": "Instance creation failed => InvalidIPAddress.InUse: Address 10.1.2.107 is in use."}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
