### ISSUE TITLE
Git module calculates the versions to compare before doing a fetch in a wrong way

### ISSUE THREAD

**Issue by mpessas** [ansible/ansible#14990]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

The important ones are:

```
forks=20
```
##### Environment:

N/A
##### Summary:

Under certain conditions, the git module will not run the fetch command before a checkout operation.
##### Steps To Reproduce:

In the git module, at [line 763](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L763) the code uses the version of the **existing branch** for the `before` variable. At [line 773](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L773), though, it uses the version of the `version` variable.

As a result, the check at [line 774](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L774) is true for the equivalent of the following scenario:

```
git push origin branchB
# Run from ansible
git: repo={{ project_repo }} dest=~/work_dir/
     force=yes update=yes accept_hostkey=yes
     version=branchB

git push origin branchA
# Run from ansible
git: repo={{ project_repo }} dest=~/work_dir/
     force=yes update=yes accept_hostkey=yes
     version=branchA

git checkout branchB
git merge branchA
git push origin branchB
# Run from ansible
git: repo={{ project_repo }} dest=~/work_dir/
     force=yes update=yes accept_hostkey=yes
     version=branchB
```

As a result, the line [785](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L785) is run; thus, the `fetch` operation at line [789](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L789) will never run.

Then, the code will execute line [795](https://github.com/ansible/ansible-modules-core/blob/a98cd86f8853c1e1a1441d0b61a71204bdd67702/source_control/git.py#L795), which checks out `branchB` but without a fetch operation, i.e. the repo will not have the updated version of `branchB`.

From a quick look a fix would be to always run the `switch_version` function before calculating the value of the `before` variable. I could take a look at implementing a fix, if needed.
##### Expected Results:

The code should use the newest commit of `branchB`.
##### Actual Results:

The code uses the commit of `branchB` before the merge operation.

Thanks!

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
