### ISSUE TITLE
yum module fails when a rpm file is already installed

### ISSUE THREAD

**Issue by bcourtine** [ansible/ansible#14997]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No configuration tunning.
##### Environment:

Running Ansible compiled from source on Linux Mint, targetting a CentOS host.
##### Summary:

With Ansible 1.9.4, using yum module to install a remote rpm works.
When running the playbook several times, the tasks appears as "changed" every time, but it doesn't fail.

With Ansible 2.0.0.2, it is broken.
At the first run, the rpm is installed.
When I run the playbook again, the tasks fails.
##### Steps To Reproduce:

Here is a minimal playbook that reproduce the problem (the problem can probably be reproduced with other remote rpm files):

```

---
- hosts: test_host
  tasks:
    - name: Postgresql repository installation
      yum:
        name: "http://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
        state: present
```
##### Expected Results:

Output for this playbook with Ansible 1.9.4:

```
PLAY [test_host] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test_host]

TASK: [Postgresql repository installation] ************************************ 
ok: [test_host]

PLAY RECAP ******************************************************************** 
test_host                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

Same playbook with Ansible 2.0.0.2:

```
PLAY [test_host] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test_host]

TASK: [Postgresql repository installation] ************************************
fatal: [test_host]: FAILED! => {"changed": true, "failed": true, "msg": "Erreur : Rien à faire\n", "rc": 1, "results": ["Modules complémentaires chargés : fastestmirror, security\nConfiguration du processus d'installation\nExamen de /var/tmp/yum-root-PAp4J1/pgdg-centos95-9.5-2.noarch.rpm : pgdg-centos95-9.5-2.noarch\n/var/tmp/yum-root-PAp4J1/pgdg-centos95-9.5-2.noarch.rpm : ne met pas à jour le paquet installé.\n"]}

PLAY RECAP ******************************************************************** 
test_host                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
