### ISSUE TITLE
Synchronize module do not expand ansible_ssh_private_key_file variable

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#15015]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/david/gitbi/lifemall/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

(nothing)
##### Environment:

Ubuntu 15.10
##### Summary:

I am using variable in ansible_ssh_private_key_file variable and the module do not "render" it in order to have a constant string. E.g. "{{ playbook_dir }}/some/path" is not rendered to "/playbook/path/some/path"
##### Steps To Reproduce:

Set ansible_ssh_private_key_file to some content with variables
Use synchronize module ... It fail.

Then hack:

```
- name: Make synchronize works
  set_fact:
    ansible_ssh_private_key_file: '{{ ansible_ssh_private_key_file }}'

- name: Go!
  synchronize: ...
```
##### Expected Results:

It works!
##### Actual Results:

```
fatal: [server]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh '/usr/bin/ssh -i {{ environment_directory }}/ssh/keys/local_rsa -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/home/david/project/\" \"vagrant@192.168.56.4:/var/www/project/test/source/\"", "failed": true, "msg": "Warning: Identity file {{ not accessible: No such file or directory.\nssh: Could not resolve hostname environment_directory: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
