### ISSUE TITLE
pear/pecl: is not interactive

### ISSUE THREAD

**Issue by TheHett** [ansible/ansible#15016]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.0.2
```
##### Environment:

Ubuntu
##### Summary:

Ansible can not perform the task, infinity work
##### Steps To Reproduce:

run playbook

```
-  pear: name=pecl/mongo-1.6.8 state=present
```
##### Expected Results:

pecl driver can be installed
##### Actual Results:

Ansible freezes
I think problem in pecl ask:

```
pecl install mongo-1.6.8
WARNING: "pecl/mongo" is deprecated in favor of "channel:///mongodb"
downloading mongo-1.6.8.tgz ...
Starting to download mongo-1.6.8.tgz (207,879 bytes)
.....................done: 207,879 bytes
118 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
Build with Cyrus SASL (MongoDB Enterprise Authentication) support? [no] :
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
