### ISSUE TITLE
allow omitted spaces for nested loop dictionaries

### ISSUE THREAD

**Issue by shammellee** [ansible/ansible#15056]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

Ubuntu 14.04
##### Summary:

**Works:**

```
pip: name={{item.name}} version={{item.version}} state=present
with_items:
    - { name: 'django', version: '1.8.3' }    # with spacing
    - { name: 'pillow', version: '2.9.0' }    # with spacing
```

---

**Doesn't Work:**

```
pip: name={{item.name}} version={{item.version}} state=present
with_items:
    - {name:'django',version:'1.8.3'}    # without spacing
    - {name:'pillow',version:'2.9.0'}    # without spacing
```

**Comment by jimi-c** [comment]
Hi @shammellee, this is actually part of the YAML spec (http://yaml.org/spec/1.2/spec.html#id2790832):

<pre>
Normally, YAML insists the “:” mapping value indicator be separated from the value by white space. A benefit of this restriction is that the “:” character can be used inside plain scalars, as long as it is not followed by white space. This allows for unquoted URLs and timestamps. It is also a potential source for confusion as “a:1” is a plain scalar and not a key: value pair.
</pre>

So there are more condensed versions you can do, however it is required that you include white space after the `:`.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by shammellee** [comment]
@jimi-c Makes sense. Thank you.
