### ISSUE TITLE
synchronize module hangs indefinitely when synchronizing between 2 remote hosts

### ISSUE THREAD

**Issue by Yannik** [ansible/ansible#15070]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/yannik/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

default
##### Environment:

fedora
##### Summary:

The synchronize module hangs indefinitely if used to synchronize a file between two remote hosts with the delegate_to option.
##### Steps To Reproduce:

This is the task I am using:

```
- synchronize: 
    src: /test
    dest: /test
  delegate_to: HOST
```

Doing this, I want to copy from `HOST:/test` to `/test` of the inventory host currently running the playbook as described in the [documentation](https://docs.ansible.com/ansible/synchronize_module.html)
##### Expected Results:

The file should be copied.
##### Actual Results:

The command hangs indefinitely:

```
TASK [rsnapshot-remote-host : Copy ssh key of backup pulling host] *************
task path: /home/yannik/ansible/roles/rsnapshot-remote-host/tasks/rsnapshot.yml:9
<INVENTORY_HOST> ESTABLISH SSH CONNECTION FOR USER: root
<INVENTORY_HOST> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/yannik/.ansible/cp/ansible-ssh-%h-%p-%r -tt INVENTORY_HOST '/bin/sh -c '"'"'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1458571444.47-273656313378136 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1458571444.47-273656313378136 `"'"'"''
<INVENTORY_HOST> PUT /tmp/tmpv0BDhp TO /root/.ansible/tmp/ansible-tmp-1458571444.47-273656313378136/synchronize
<INVENTORY_HOST> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/yannik/.ansible/cp/ansible-ssh-%h-%p-%r '[INVENTORY_HOST]'
<INVENTORY_HOST> ESTABLISH SSH CONNECTION FOR USER: root
<INVENTORY_HOST> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/yannik/.ansible/cp/ansible-ssh-%h-%p-%r -tt INVENTORY_HOST '/bin/sh -c '"'"'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1458571444.47-273656313378136/synchronize; rm -rf "/root/.ansible/tmp/ansible-tmp-1458571444.47-273656313378136/" > /dev/null 2>&1'"'"''
^C [ERROR]: User interrupted execution
```

**Comment by abadger** [comment]
This works for me using ssh-agent forwarding:

```
$ ansible-playbook -i 'fedora22,' synchronize.yml                *[master]  (10:13:27)

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [fedora22]

TASK [synchronize] *************************************************************
changed: [fedora22 -> 192.168.122.189]

PLAY RECAP *********************************************************************
fedora22                   : ok=2    changed=1    unreachable=0    failed=0   

[pts/5@roan /var/tmp/windmill]$ cat synchronize.yml                                            *[master]  (10:13:42)
---
- hosts: fedora22
  tasks:
    - synchronize:
        src: /etc/passwd
        dest: /var/tmp/passwd
      delegate_to: 192.168.122.189
[pts/4@roan /var/tmp/windmill]$ ssh fedora22 md5sum /var/tmp/passwd                            *[master]  (09:50:34)
f3202095ad11629ec58548d9fab181ba  /var/tmp/passwd
[pts/4@roan /var/tmp/windmill]$ ssh 192.168.122.189 md5sum /etc/passwd                         *[master]  (10:13:59)
X11 forwarding request failed on channel 1
f3202095ad11629ec58548d9fab181ba  /etc/passwd
```

How are you managing the ssh authentication between your two remote hosts? Because we're running rsync and _rsync_ is then running its own ssh, the authentication there can be a problem.

If it is authentication that's the problem then this is a duplicate of:
https://github.com/ansible/ansible/issues/13099

**Comment by Yannik** [comment]
@abadger 
I tried this with agent forwarding, and it works, but that is a security issue I am not willing to risk.
(see https://www.reddit.com/r/netsec/comments/2m2zpb/the_perils_of_using_an_sshagent/, https://heipei.github.io/2015/02/26/SSH-Agent-Forwarding-considered-harmful/, https://www.commandprompt.com/blogs/ildefonso_camargo/2013/11/security_considerations_while_using_ssh-agent/ and other publications on this topic).

Doing this with agent forwarding only requires a single infected host to overtake all other hosts you are deploying with ansible. Didn't this work without agent forwarding earlier? This is necessary for systems which require atleast a minimal level of security. At the moment, it is pretty useless like this. Additionally, using `ssh-add -c` is not practical with ansible either.

**Comment by abadger** [comment]
@Yannik Understood.  Agent forwarding does have drawbacks.  (Although, IIRC, the problem is even worse if you are using password authentication from a compromised box.  If you have one-time-passwords at your site you can miigate that, however.)

This never worked without agent forwarding.  However bugs in the code could have allowed playbooks to work but transfer files between the wrong hosts.  If someone wasn't checking that the files were actually coming from the correct hosts they could have mistaken that for things working.

If you're not willing to accept the risks of ssh-agent forwarding, then the eventual improvements to allow sshpass authentication probably won't be suitable for you either (again, unless you're using one time passwords... you may be able to make that more secure at the expense of not being able to completely automate things as you'll have to be there to type in your otp).  Rolling your own thing using ansible's command module with rsync may be the best route for you to take.
