### ISSUE TITLE
[2.0.1.0] Potential issue?

### ISSUE THREAD

**Issue by hrstoyanov** [ansible/ansible#15181]
Upgrading from 1.9.x to 2.0.1.0 and bumped into this, which used to work: 

```
    - name: Schedule letsencrypt certs update via cron
      cron: name = "letsencrypt xxx.com certs update" 
               special_time= "weekly" 
               job=" "{{ letsencrypt_cmd }}" > /dev/null"
      notify: restart apache2
      when: ssl_method == "letsencrypt"
      tags: [deploy,proxy]
```

greets me with:

```
ERROR! this task 'cron' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/projects/devops/deploy-s4g.yml': line 121, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Schedule letsencrypt certs update via cron
      ^ here

```

Removing the cron task helps for now, but I do need it eventually. Any workaround would be appreciated...

**Comment by jimi-c** [comment]
Hi @hrstoyanov the problem is here: `job=" "{{ letsencrypt_cmd }}" > /dev/null"`. You're using the same quote marks there, so the parser is spliting that as it expects common quotes to group things. You should change it to be `job=' "{{ letsencrypt_cmd }}" > /dev/null'` instead, or use the full YAML dictionary syntax:

<pre>
    - name: Schedule letsencrypt certs update via cron
      cron: 
        name: "letsencrypt xxx.com certs update" 
        special_time: "weekly" 
        job: ' "{{ letsencrypt_cmd }}" > /dev/null'
      notify: restart apache2
      when: ssl_method == "letsencrypt"
      tags: [deploy,proxy]
</pre>

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by hrstoyanov** [comment]
Jimi-c,
Unfortunately, your proposed fix: `job=' "{{ letsencrypt_cmd }}" > /dev/null'` still gives the same error. Did you try the code yourself? 

Not only that, but It appears that the quotes are not the issue at all, as the next  examples fails with the same error:

```
    - name: Schedule letsencrypt certs update via cron
      cron: name = "letsencrypt xxx.com certs update" 
            special_time= "weekly"  
       #     job=' "{{ letsencrypt_cmd }}" > /dev/null'
      notify: restart apache2
      when: ssl_method == "letsencrypt"
      tags: [deploy,proxy]
```

Can you please re-open the issue until it is actually fixed? I think it might be related to #13630 and #12331

**Comment by dagwieers** [comment]
@hrstoyanov To me it seems there are 2 problems in your example, one was related to quoting, the other to syntax. Can you try to use the full YAML syntax (instead of the old parameter-syntax) ?

I noticed you are using the old parameter-syntax on multiple lines, and you have blanks between key and "="-sign.

Did you try:

``` yaml
- name: Schedule letsencrypt certs update via cron
  cron:
    name: "letsencrypt xxx.com certs update" 
    special_time: "weekly"  
    job: ' "{{ letsencrypt_cmd }}" > /dev/null'
  notify: restart apache2
  when: ssl_method == "letsencrypt"
  tags: [deploy,proxy]
```

That's what @jimi-c actually did in his example.

**Comment by jimi-c** [comment]
And yes, I did test it myself.
