### ISSUE TITLE
ansible-playbook api leak file  descriptor

### ISSUE THREAD

**Issue by liuzhenan** [ansible/ansible#15182]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```
ansible 1.9.1
```
##### env

CentOS release 6.4 (Final)
##### SUMMARY

 I use the API to perform some of the playbook I want to carry out the playbook, but after when I perform, I found that the release of program that can not correctly file descriptors.This will lead to abnormal "too many files open", I think is caused by requiretty, but when I commented out suduers, problems still exist.
##### Code

import os
import sys
def Start():
    pid=os.fork()
    if pid != 0:
        sys.exit(0)
    os.setsid()
    os.umask(0)
    pid=os.fork()
    if pid != 0:
        sys.exit(0)
    pid=os.getpid()
    os.umask(18)
    null=open("/dev/null",'a')
    os.dup2(null.fileno(),0)
    os.dup2(null.fileno(),sys.stdout.fileno())
    os.dup2(null.fileno(),sys.stderr.fileno())
    ahandle.close()
    return pid
###### 

```
    pb = PlayBook(
    playbook=playbook,
    forks=forks,
    host_list=hosts.name,     
    remote_user='root',
    callbacks=playbook_cb,
    runner_callbacks=runner_cb,
    stats=stats,
    #check=True 
    )
    results = pb.run()
```

when i execute this playbook，my fd will open file descriptor like this : 
 `lr-x------ 1 root root 64 Mar 28 14:30 38 -> /dev/ptmx`
When the playbook has finished executing，The file  descriptor  will become /dev/null 
`lr-x------ 1 root root 64 Mar 28 14:31 38 -> /dev/null`

```
```

**Comment by liuzhenan** [comment]
`#coding=utf8
__version__= 1.0
__author__="lucky_kris"
import os
import sys

def Start():
	pid=os.fork()
	if pid != 0:
		sys.exit(0)
	os.setsid()
	os.umask(0)
	pid=os.fork()
	if pid != 0:
		sys.exit(0)
	pid=os.getpid()
	os.umask(18)
	null=open("/dev/null",'a')
	#os.dup2(null.fileno(),0)
	# os.dup2(null.fileno(),sys.stdout.fileno())
	# os.dup2(null.fileno(),sys.stderr.fileno())
	# console_log="/data/nick/platform-deploy/console.log"
	# ahandle=open(console_log,"a")
	os.dup2(null.fileno(),sys.stdout.fileno())
	os.dup2(null.fileno(),sys.stderr.fileno())
	ahandle.close()
	return pid
	

`

**Comment by jimi-c** [comment]
@liuzhenan, the 1.9.x branch is only receiving fixes for critical/security bugs, so unless this bug also affects devel/stable-2.0 we will most likely not fix this going forward.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
