### ISSUE TITLE
Unable to reach the destination after root password change

### ISSUE THREAD

**Issue by MacloudTP** [ansible/ansible#15227]
Bug Report

ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
Mac OS X 10.11

Ansible is unable to reach the destination after relevant changes like root password change or setting up the firewall before configuring it (so :22 is closed).

```
- name: change root password
  user: name=root password="{{ NEW_ROOT_PASS }}"
```

next task (no matter what) will fail:

```
fatal: [hostname]: UNREACHABLE! => {"changed": false, "msg": "Authentication failed.", "unreachable": true}
```

Verbose example:

```
<hostname> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO hostname
<hostname> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459373109.85-126909552324086 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459373109.85-126909552324086 `"'
<hostname> PUT /var/folders/3x/x7239yh54mqf7_wrmql4hxnm0000gn/T/tmpOpJeWR TO /root/.ansible/tmp/ansible-tmp-1459373109.85-126909552324086/user
<hostname> EXEC /bin/sh -c 'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1459373109.85-126909552324086/user; rm -rf "/root/.ansible/tmp/ansible-tmp-1459373109.85-126909552324086/" > /dev/null 2>&1'
changed: [hostname] => {"append": false, "changed": true, "comment": "root", "group": 0, "home": "/root", "invocation": {"module_args": {"append": false, "comment": null, "createhome": true, "expires": null, "force": false, "generate_ssh_key": null, "group": null, "groups": null, "home": null, "login_class": null, "move_home": false, "name": "root", "non_unique": false, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "remove": false, "shell": null, "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on rescue", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": false, "uid": null, "update_password": "always"}, "module_name": "user"}, "move_home": false, "name": "root", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/bash", "state": "present", "uid": 0}
 ___________________________________________ 
< TASK [install : uploading autosetup file] >
 ------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/user/ansible/roles/install/tasks/main.yml:22
<hostname> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO hostname
fatal: [hostname]: UNREACHABLE! => {"changed": false, "msg": "Authentication failed.", "unreachable": true}
    to retry, use: --limit @install.retry
```

The same would work with my public key stored before changing the password so it still can logon, but this shouldn't be the solution.

After hours of configuration changes I tried exactly the same thing on Ubuntu 14.04 - works perfectly as expected.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

If you are resetting the password ansible authenticates with, ansible needs to have it's inventory/hostvars updated before calling another remote task.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
