### ISSUE TITLE
copy to symlinks breaks when src and dest files are the same

### ISSUE THREAD

**Issue by sfs42** [ansible/ansible#15238]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.3
  configured module search path = None

```
##### CONFIGURATION

pipelining = True
##### OS / ENVIRONMENT

Control host: OpenSuSE 13.1
Managed host: Scientific Linux 7.2
##### SUMMARY

If the destination of the copy module is a symlink to a file whose content is identical to the source file, then ansible produces an error, or worse, sometimes replaces the symlink with a link to itself. 
##### STEPS TO REPRODUCE

On the control host:

echo 'test' > foo

On the managed host:

cd /tmp/
echo test > bar
ln -s bar spam

```
<!--- Paste example playbooks or commands between quotes -->
```

ansible <remote host>  -u root -m copy -a "src='foo' dest='/tmp/spam'"

##### EXPECTED RESULTS

I would expect that the link 'spam' on the remote host gets replaced with a copy of foo containing 'test'.
##### ACTUAL RESULTS

```
<remote host> ESTABLISH CONNECTION FOR USER: root
<remote host> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/<my home>/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 <remote host> /bin/sh -c 'rc=flag; [ -r /tmp/spam ] || rc=2; [ -f /tmp/spam ] || rc=1; [ -d /tmp/spam ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc} "/tmp/spam && exit 0; (python -c '"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1(); afile = open("'"'"'/tmp/spam'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"' 2>/dev/null) || (python -c '"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'"'"'/tmp/spam'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"' 2>/dev/null) || (echo '"'"'0 '"'"'/tmp/spam)'
<remote host> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/<my home>/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 <remote host> /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
<remote host> | FAILED >> {
    "checksum": "4e1243bd22c66e76c2ba9eddc1f91394e57f9f83",
    "failed": true,
    "gid": 0,
    "group": "root",
    "mode": "0777",
    "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /tmp/foo",
    "owner": "root",
    "path": "/tmp/spam",
    "size": 3,
    "src": "foo",
    "state": "link",
    "uid": 0
}

```

**Comment by sfs42** [comment]
If the source file is named the same as the link on the destination host, then the link is replaced with a link to itself.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
