### ISSUE TITLE
False positive Syntax Error triggered in parser

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible#15260]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No special configuration.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Parser throws a Syntax Error which is actually a false positive.
##### STEPS TO REPRODUCE

Run the following playbook. If you remove the : after Test everything will work without a Syntax Error.

```

---

- name: Test case
  hosts: all
  become: no

  tasks:
    - debug: msg="Test: {{ somevar }}"
```
##### EXPECTED RESULTS

Print out of "Test: ..." with ... being whatever the variable is defined as.
##### ACTUAL RESULTS

```
% ansible-playbook -vvvv test.yaml
No config file found; using defaults
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/asmodai/testcase2/test.yaml': line 8, column 23, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - debug: msg="Test: {{ somevar }}"
                      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

You must quote the entire msg parameter in this case.

For example:

```
- debug: 'msg="Test: {{ somevar }}"'
```

Another alternative is to create the full string prior to debug ...

```
    - set_fact:
        newstring: "Test: {{ somevar }}"
    - debug: msg="{{ newstring }}"
```

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
