### ISSUE TITLE
lvol does not work with size suffix 'b' or 'B'

### ISSUE THREAD

**Issue by sfs42** [ansible/ansible#15263]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.3
  configured module search path = None
```
##### CONFIGURATION

pipelining=True
##### OS / ENVIRONMENT

Control host: openSuSE 13.1
Managed host: Scientific Linux 7.2
##### SUMMARY

lvol produces an internal parse error when trying to create a volume with a size given in bytes.
##### STEPS TO REPRODUCE

```
ansible <remote host> -i hosts -u root -m lvol -a "lv='scratch' vg='vg_system' size='10000000B'"
```

##### EXPECTED RESULTS

That the lv is created.
##### ACTUAL RESULTS

```
node520 | FAILED >> {
    "failed": true,
    "msg": "OpenSSH_6.2p2, OpenSSL 1.0.1k 8 Jan 2015\ndebug1: Reading configuration data /homes/mathphys/sfs/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 18: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 47: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: mux_client_request_session: master session id: 2\r\nX11 forwarding request failed\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 1852, in <module>\n  File \"<stdin>\", line 167, in main\n  File \"<stdin>\", line 93, in parse_lvs\nValueError: invalid literal for int() with base 10: '209715200B'\n",
    "parsed": false
}

```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
