### ISSUE TITLE
Random failures of service module caused by a systemd bug

### ISSUE THREAD

**Issue by zxwing** [ansible/ansible#15295]
This is not a bug report but a caveat, so I didn't follow the template and you are free to close it once you get the idea or you already know it.

We observed some random failures when managing CentOS7.2 systems. The service module complains about: 

> {"msg": "cannot detect command to enable service NetworkManager, typo or init system potentially unknown", "failed": true} 

The service name could be any others. After investigation, we found the code was stuck in 

> rc, out, err = self.execute_command("%s list-unit-files" % (location['systemctl']))

and finally led to a timeout. We root caused the issue was entailed by a systemd bug https://github.com/systemd/systemd/issues/1961 and the solution is to setup a crontab to clean up systemd session files periodically:

> rm -f /run/systemd/system/*.scope

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
