### ISSUE TITLE
Failed to execute subprocess.Popen

### ISSUE THREAD

**Issue by yanivrefael** [ansible/ansible#15300]
python script:

import subprocess
subprocess.Popen(['emulator', '-avd', 'autotest', '-no-skin', '-no-audio', '-no-window'])

fatal: [192.168.0.185]: FAILED! => {"changed": true, "cmd": ["sudo", "python", "Mobile_SDK.py"], "delta": "0:00:00.021230", "end": "2016-04-06 12:26:06.861386", "failed": true, "invocation": {"module_args": {"_ansible_check_mode": false, "_ansible_debug": false, "_ansible_diff": false, "_ansible_no_log": false, "_ansible_verbosity": 3, "_raw_params": "sudo python Mobile_SDK.py", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-04-06 12:26:06.840156", "stderr": "Traceback (most recent call last):\n  File \"Mobile_SDK.py\", line 2, in <module>\n    subprocess.Popen(['emulator', '-avd', 'autotest', '-no-skin', '-no-audio', '-no-window'])\n  File \"/usr/lib/python2.7/subprocess.py\", line 710, in __init__\n    errread, errwrite)\n  File \"/usr/lib/python2.7/subprocess.py\", line 1327, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory", "stdout": "", "stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}

The same script works on Ubuntu but if I run it with ansible (on the same machine) it failed

**Comment by sivel** [comment]
The error is indicating python can not find the `emulator` file.  You should either give it the full path or consider using `get_bin_path` and `run_command` provides by Ansible instead of using your own subprocess calls.

**Comment by sivel** [comment]
The comments around `get_bin_path` was under the assumption that you were trying to write an Ansible module.  However it may be that you are calling this via shell or command.  In which case the full path comment still applies, however if you don't want to hard code the full path, you may need to use `environment` on the task to specify a `PATH` that includes the directory where `emulator` exists.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

Per sivel's comment, this looks like a problem with PATH for the sudo'ed user on your remote system and not a problem with ansible. A test you could run is to call ['which', 'emulator'] in your script to validate the command is in the PATH for the user.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
