### ISSUE TITLE
Setup Module for remote Cisco Nexus switch returns local host facts 

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#15339]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION

```
fact_caching = redis
fact_caching_timeout = 86400
ANSIBLE_HOSTS=./hosts
```
##### OS / ENVIRONMENT
- host: Linux samsung-ubuntu 4.2.0-35 x86_64 GNU/Linux
- remote: NX-OS 7.3(0)D1(1)
##### SUMMARY

Calling the setup module for a remote nexus switch returns the facts of the local host which has made the call, instead of some facts about the remote device. 
##### STEPS TO REPRODUCE

```
ansible -m setup NX-OSv-Spine-11
NX-OSv-Spine-11 | SUCCESS => {
    "ansible_facts": {
...
        "ansible_hostname": "samsung-ubuntu", 
...
        "ansible_distribution": "Ubuntu", 
        "ansible_distribution_major_version": "15", 
        "ansible_distribution_release": "wily", 
        "ansible_distribution_version": "15.10", 
 ...
```

Whereas calling nxos_get_facts (from jedelman8/nxos-ansible https://github.com/jedelman8/nxos-ansible) with the same NX-OSv-Spine-11 gives:

```
TASK [common : Print nxos facts] ***********************************************
task path: /media/actionmystique/SAMSUNG-Ext4-1/Labs/GNS3/CCNP-Cloud/CLDAUT/Distributed-Clouds/Ansible/roles/common/tasks/main.yml:93
ok: [NX-OSv-Spine-11] => {
...
        "hostname": "NX-OSv-Spine-11", 
...
        "kickstart": "7.3(0)D1(1)", 
...
        "platform": "NX-OSv Chassis", 
```

```
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We have some questions we'd like to know about before we can get this request queued up.   If you can help answer them, we'd greatly appreciate it:
- What connection mode is defined for the inventory host?
- What is the -vvvv output from the command?

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively
we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time!  
We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgotten about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by privateip** [comment]
You cannot use the internal Ansible fact gathering module with network devices today.  If you want to collect facts, you need to include a task in your playbook that implements [nxos_facts](https://github.com/ansible/ansible-modules-core/blob/devel/network/nxos/nxos_facts.py)

**Comment by jean-christophe-manciot** [comment]
Is this on Ansible's agenda?

**Comment by privateip** [comment]
There is an nxos-facts module that will collect facts from nxos devices that can be included in your playbook.  Over time we will expand the details the facts module is collecting.

**Comment by jean-christophe-manciot** [comment]
I tried "ansible -m setup" on a local KVM Ubuntu VM, and the results are the same: the facts correspond to the host, not to the VM.
So is this command supposed to gather only local host facts, or is it possible to gather facts of a remote host?

**Comment by privateip** [comment]
I think there is a slight misunderstanding of how facts work here.  When using connection: local (which is required for nxos), the `-m setup` properly collects facts only from the localhost where Ansible is running (or the delegate_to host if used).   You want to collect nxos facts.  To do that you need to include the nxos_facts module in a playbook:

```
---
- hosts: nxos_hosts
  connection: local

  tasks:
    - name: collect nxos facts
      nxos_facts:
        host: "{{ inventory_hostname }}"
       username: <your nxos user>
       password: <your nxos password>
       transport: cli
```

You can also use the command cli executable the same way:

```
ansible -m nxos_facts -a "host=nxos01 username=admin password=admin transport=cli" --connection local nxos01
```

HTH

**Comment by jean-christophe-manciot** [comment]
Thanks for your input. I am fully aware of the nx-os original & current network module as explained in my first post.
The confusion comes from the choice of the word"local" for the ansible_connection variable: obviously it is not local since we can communicate with remote devices. What it really means is quite obscure. 
If I understand correctly, that variable is supposed to describe the type of "transport" expected for the connection between the local host and the managed devices. So we have the following choices:
- local: ? 
- chroot
- SSH 
- smart where ansible chooses the right connection between SSH & paramiko, depending on the capabilities of the devices involved in the communication.
- LXC
- LXD
- Docker
-  ...

HTTP/HTTPs do not appear in the list although they can be used when the devices offer an API such as NXAPI here.
What is even more confusing is that "local" (for whatever that means) is required for Cisco NX-OS switches, whereas they support SSH & Python (and HTTP/HTTPs which can be used by NX-OS module).
I hope someone will be able to clarify Ansible's view of a connection or transport, especially the "local" part.

**Comment by privateip** [comment]
Specifying connection=local is exactly what it implies, the task (module) is run from the local Ansible control host instead of first connecting to a remote host and executing the module code there.  This is how, for instance, cloud modules are able to consume APIs where its not possible to SSH to a remote device.  The module is executing in a local shell environment and then an API connection is made to the remote system.   

In the same way, this is how network modules work.  When specifying connection=local, the module is run on the local Ansible control host and connects to the remote device over an alternative transport (in some cases, API (eapi, nxapi, netconf, etc) or CLI over SSH.   That is why the connection parameters must be specified on a per-task basis.

The thing to remember about remote execution of Ansible modules is that they require both a connection and an execution environment.  While network devices provide the connection capabilities, they do not provide an environment that allows running arbitrary executables in.  That is why the network modules build and manage their own SSH shell connection.  A rudimentary way to think about it is we use the CLI as a form of an API transport instead of a raw SSH connection.

**What about devices that support shell environments?**
There are some network devices that do indeed support shell environments that can handle a direct SSH connection along with providing an execution environment and where they exist, we definitely take advantage of them.  Cumulus and OpenSwitch are two good examples of this.   However, for other devices that provide a shell environment, there still needs to be a mechanism, by way of binary or api or something, that will allow the module to configure the device.  There in lies the problem with many network devices that support a shell.  Once you get into the shell, there still doesn't exist a way to actually configure the device without spawning the CLI (or passing a string of arguments into a CLI interpreter in which case we can just bypass that all together and go straight to the CLI)

**What about devices that support Python?**
The same problems noted with the shell environment above exist with many of the Python shell environments available on the device.  In addition, there doesn't exist a way in many network device implementations to do much more that basic scripting with provided libraries.  To add to the complexity, invoking the Python shell usually requires connecting to the device CLI to begin with.  So once again, the common denominator here ends up being the CLI so we just short circuit the process.

**Why not just do everything over API?**
Its a fair enough question to ask and, over time, I believe the modules will evolve to this pattern.  In the short term though there is enough discrepancy between capabilities available in the CLI and in the API that in order to support full functionality we needed to provide both transports.  Compound that by considering there are still some platforms that do not support an API at all (IOS for instance).  In addition, networking devices do not come with APIs enabled and many organizations have standing policies that prohibit their ability to enable APIs on network devices.

**Looking ahead**
Certainly as network devices provide more of an open based architecture, the network integration within  Ansible will evolve to take advantage of those capabilities.   However, until there is a more wide spread adoption by networking vendors to fully embrace the Linux environment in its purest sense with all that it has to offer, we are a bit handcuffed with supporting these more closed implementations.

HTH

**Comment by jean-christophe-manciot** [comment]
Thanks for the detailed answer.
So, as I explained earlier and as you show in your last post, Ansible mixes "Computing" with "Networking"  & with the type of controlled device, which confuses people who are not familiar with the intricate details of your implementation. For instance:
- **connection=local** implies that the **execution** of the modules is local to the control host, but does not say anything about the type of **communication** taking place between that host & the remote one, which can be SSH, HTTP(s), Netconf, ..
- **connection=ssh** implies that the execution of the modules is done on the controlled remote host with an SSH type of communication.

My proposal is to separate the concepts for clarity's sake:
- **ansible_compute**: local, remote
- **ansible_protocol**: ssh, http, https, netconf, ...
- **ansible_target**: linux, lxc, lxd, docker, cisco, cumulus, ...

If there are multiple APIs per device, it could be useful to add an **ansible_api**.

**Comment by jean-christophe-manciot** [comment]
Back to the [post](https://github.com/ansible/ansible/issues/15339#issuecomment-220055738) about failing to gather facts about a local KVM VM.
When:
- **ansible_connection is local** with a **KVM VM** defined in the hosts file, all modules are actually played against the **local host** instead of the VM, which is shown by the facts gathered & all return values from all modules. After a quick search on the Internet, it seems I'm the only one writing about that kind of setup: Ansible running against local KVM VMs.
- **ansible_connection is ssh** with a **KVM VM** defined in the hosts file: all modules are really played against the **local VM**. However, in order to work, the playbook has to be run from the root account with the remote username as root. 
- **ansible_connection is ssh** with a **KVM VM** defined in the hosts file: **Ansible hangs up** during the initial setup task when it is played from the root or non-root account with a remote non-root user. Of course, the ansible_ssh_private_key_file has been updated accordingly in the meantime. I am able to ssh into that VM from the CLI with the same private key file and remote username.
