### ISSUE TITLE
synchronize doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by madkiss** [ansible/ansible#15376]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.0.2
  config file = /root/underlay/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

[defaults]

ansible_managed = Ansible managed - local changes will be lost
inventory = hosts
remote_user = root
retry_files_enabled = False
transport = ssh

system_warnings = True
deprecation_warnings = True
command_warnings = True

[ssh_connection]
pipelining = True
##### OS / ENVIRONMENT

Ubuntu 16.04 Beta
##### SUMMARY

The synchronize function will fail on Ubuntu 16.04 because of broken quotation (username has " prepended when logging in using rsync).
##### STEPS TO REPRODUCE

We have this directive in our configuration:
- synchronize:
  src: /var/lib/rabbitmq/.erlang.cookie
  dest: /var/lib/rabbitmq/.erlang.cookie
  delegate_to: "{{ rabbitmq_primary_node }}"

Running the ansible playbook results in:

fatal: [mgl-ansible-4 -> mgl-ansible-3]: FAILED! => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/var/lib/rabbitmq/.erlang.cookie\" \"root@mgl-ansible-4:/var/lib/rabbitmq/.erlang.cookie\"", "failed": true, "msg": "Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}

In the other machine's logfile, I see

Apr 12 07:03:00 mgl-ansible-4 sshd[19827]: Invalid user "root from 10.42.0.14
##### EXPECTED RESULTS

The file is copied from the source host to the target host using rsync.
##### ACTUAL RESULTS

The file is not copied as rsync is unable to create a connection.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
