### ISSUE TITLE
Broken juniper modules

### ISSUE THREAD

**Issue by kamsz** [ansible/ansible#15401]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

Built from 12.04.2016 devel branch
##### OS / ENVIRONMENT

Ansible OS: Fedora 23
##### SUMMARY

While trying to use junos modules, they're failing with:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named netcfg
fatal: [10.91.96.37]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_47BNfA/ansible/module_exec/junos_command/__main__.py\", line 270, in <module>\n  File \"/tmp/ansible_47BNfA/ansible/module_utils/junos.py\", line 22, in <module>\nImportError: No module named netcfg\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

Use any junos module
##### EXPECTED RESULTS

Junos module should execute properly
##### ACTUAL RESULTS

Junos modules fail

**Comment by Qalthos** [comment]
This should be fixed when #15344 gets merged

**Comment by kamsz** [comment]
Yup, fixed!

**Comment by kamsz** [comment]
Or not

**Comment by kamsz** [comment]
Or not.

```
fatal: [10.91.96.37]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"commands": ["show version", "show ip route"], "host": "10.91.96.37", "interval": 1, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": 22, "provider": null, "retries": 10, "ssh_keyfile": null, "username": "root", "waitfor": null}, "module_name": "junos_command"}, "msg": "failed to connecto to 10.91.96.37:22 - "}
```

I saw the same issue at mailing list, I've netconf enabled.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
