### ISSUE TITLE
lineinfile Module Failure - Ansible 2.0.2.0RC4

### ISSUE THREAD

**Issue by Techcadia** [ansible/ansible#15411]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

ANSIBLE_SCP_IF_SSH=y
##### OS / ENVIRONMENT

Ansible is running on RHEL 6.7
Managing RHEL 6.7
##### SUMMARY

lineinfile fails to work correctly
##### STEPS TO REPRODUCE

Try to run lineinfile

```
\etc\krb5.conf snippet
[libdefaults]
  dns_lookup_realm = false  
  dns_lookup_kdc = true  
  rdns = false  
  ticket_lifetime = 24h  
  forwardable = yes  
  udp_preference_limit = 0

playbook.yml

---
- name: Modify krb5.conf parameters  lineinfile:
    dest: /etc/krb5.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '\s+dns_lookup_kdc',        line: '  dns_lookup_kdc = true' }
```
##### EXPECTED RESULTS

lines in file modified or did not modifiy the files if they have already been modified.
##### ACTUAL RESULTS

```
ASK [krb5 : Modify krb5.conf parameters] 
**************************************
failed: [stg-tst-app02] (item={  
   u'regexp':u'\\s+dns_lookup_kdc',
   u'line':u'  dns_lookup_kdc = true'
}) =>{  
   "failed":true,
   "item":{  
      "line":"  dns_lookup_kdc = true",
      "regexp":"\\s+dns_lookup_kdc"
   },
   "module_stderr":"",
   "module_stdout":"
        Traceback (most 
        recent call last):
          File \"/home/myuser/.ansible/tmp/ansible-tmp-1460582668.29-248909495086912/lineinfile\", line 2598, in <module>
            main()
          File \"/home/myuser/.ansible/tmp/ansible-tmp-1460582668.29-248909495086912/lineinfile\", line 405, in mai
            ins_aft, ins_bef, create, backup, backrefs)
          File \"/home/myuser/.ansible/tmp/ansible-tmp-1460582668.29-248909495086912/lineinfile\", line 294, in present
            msg, changed = check_file_attrs(module, changed, msg, attr_diff)
          File \"/home/myuser/.ansible/tmp/ansible-tmp-1460582668.29-248909495086912/lineinfile\", line 174, in check_file_attrs
            if module.set_fs_attributes_if_different(file_args, False, diff=diff):
        TypeError: set_fs_attributes_if_different() got an unexpected keyword argument 'diff'
    ",
   "msg":"MODULE FAILURE",
   "parsed":false
}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
