### ISSUE TITLE
Getting "Syntax Error while loading YAML" when performing regex_replace

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#15426]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/vrodrigues/Code/ansible.cfg
  configured module search path = ./ansible/library
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I'm doing the following

```
- name: git pull from apps repo
  command: git pull --depth=1
  args:
    chdir: "{{ apps_path }}/{{ item }}"
  with_items:
    "{{ apps }}"
  register: pull_result

- debug: msg="{{ item.stdout | regex_replace('^(.*)"stdout": (.*).$', '\\1 \\2') }}"
  with_items:
    "{{ pull_result.results }}"
```

I get a "Syntax Error while loading YAML" error.
##### STEPS TO REPRODUCE

Run above Ansible command.
##### EXPECTED RESULTS

Expect the script to execute successfully.
##### ACTUAL RESULTS

```
fatal: [10.80.80.150]: FAILED! => {"failed": true, "reason": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in '/Users/vrodrigues/Code/cochlear/deploy/ansible/roles/applications/splunk_server_update/tasks/update_apps.yml': line 51, column 59, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug: msg={{ item.stdout | regex_replace('^(.*)\"stdout\": (.*).$', '\\\\1 \\\\2') }}\n                                                          ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case the issue is because you did not quote the  line with : followed by space, this is a YAML requirement.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ghost** [comment]
Thanks @bcoca, was convinced it was a bug. Thanks for the reference to IRC channel. Will use that next time.
