### ISSUE TITLE
npm module silently fails to install packages

### ISSUE THREAD

**Issue by mrgnr** [ansible/ansible#15433]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Running from: Ubuntu 15.10
Remote machine: Ubuntu 15.10
##### SUMMARY

With Ansible 2.0.1, the npm task appears to succeed, but packages are not actually installed on the remote machine. If the task is run multiple times, Ansible's output reports that the machine state was _changed_ on each run. I ran the same npm task on the same machines using Ansible 1.9.1 and the packages _were_ installed on the remote machine, so this seems to be a new issue with 2.0.
##### STEPS TO REPRODUCE

Run the following playbook:

```
- hosts: all
  remote_user: root
  tasks:
    - name: Test npm
      npm: name=bower global=yes state=latest
```
##### EXPECTED RESULTS

Bower should be installed on the remote machine. `which bower` should return something like `/usr/bin/bower`.
##### ACTUAL RESULTS

Bower is not installed on the remote machine. `which bower` returns nothing.

Running the task multiple times returns _changed_ output each time:

```
changed: [104.154.x.x] => {"changed": true, "invocation": {"module_args": {"executable": null, "global": true, "ignore_scripts": false, "name": "bower", "path": null, "production": false, "registry": null, "state": "latest", "version": null}, "module_name": "npm"}}
```

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
