### ISSUE TITLE
mysql_user support REQUIRE NONE to remove a REQUIRE SSL "GRANT"

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#15440]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.4
  configured module search path = /usr/share/ansible
```
##### SUMMARY

There is no way to remove the "REQUIRE SSL" mysql privilege ... other than rewriting the whole set of permission which is not practicable (especially when depending upon `append_privs=yes`)

```
-  mysql_user: name=muser priv="*.*:REQUIRESSL" append_privs=yes
```

There is no way to revert such a directive. Normally this is done using `REQUIRE NONE`
But this is not implemented by the Ansible role.
##### STEPS TO REPRODUCE

```
-  mysql_user: name=muser priv="*.*:REQUIRENONE" append_privs=yes
```
##### EXPECTED RESULTS

The REQUIRE SSL is droped for "muser"
##### ACTUAL RESULTS

This is unsupported

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
