### ISSUE TITLE
ansible_default_ipv6.address fact sometimes "wrong"

### ISSUE THREAD

**Issue by JasperWallace** [ansible/ansible#15487]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```
##### OS / ENVIRONMENT

Running from Debian Jessie (amd64) to Debian jessie and wheezy, some ubuntu things, and Raspbian jessie
##### SUMMARY

We are using {{ ansible_default_ipv6.address  }} to pick the ipv6 address from hosts to build AAAA records for our dns zone file.

After upgrading from 1.8.? some hosts are reporting their temporary address rather than the permanent one, which will make them unreachable over dns.

e.g.

on one host (raspbian jessie, kernel 4.1.19+):

```
 # ip -6 addr       
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2001:8b0:856:1:23b4:9928:507f:6f9d/64 scope global noprefixroute dynamic 
       valid_lft 86379sec preferred_lft 14379sec
    inet6 2001:8b0:856:1::43/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::ba27:ebff:fefe:71a4/64 scope link 
       valid_lft forever preferred_lft forever
# ip -6 route                         
2001:8b0:856:1::/64 dev eth0  proto kernel  metric 202 
fe80::/64 dev eth0  proto kernel  metric 256 
default via fe80::210:f3ff:fe1a:eedc dev eth0  metric 202 
default via 2001:8b0:856:1::1 dev eth0  metric 1024 
default via fe80::210:f3ff:fe1a:eedc dev eth0  proto ra  metric 1024  expires 1775sec hoplimit 64

# ip -6 route get 2404:6800:400a:800::1012                                                              
2404:6800:400a:800::1012 via fe80::210:f3ff:fe1a:eedc dev eth0  src 2001:8b0:856:1:23b4:9928:507f:6f9d  metric 0 
    cache 
```

and ansible_default_ipv6.address is 2001:8b0:856:1:23b4:9928:507f:6f9d when it should be 2001:8b0:856:1::43

on another (debian jessie, amd64, kernel 3.16.0-4-amd64):

```
# ip -6 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2001:8b0:856:1::36/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 2001:8b0:856:1:5054:ff:feac:3c21/64 scope global mngtmpaddr dynamic 
       valid_lft 82154sec preferred_lft 10154sec
    inet6 fe80::5054:ff:feac:3c21/64 scope link 
       valid_lft forever preferred_lft forever
# ip -6 route
2001:8b0:856:1::/64 dev eth0  proto kernel  metric 256  expires 86297sec
fe80::/64 dev eth0  proto kernel  metric 256 
default via fe80::210:f3ff:fe1a:eedc dev eth0  proto ra  metric 1024  expires 1697sec hoplimit 64
# ip -6 route get 2404:6800:400a:800::1012
2404:6800:400a:800::1012 from :: via fe80::210:f3ff:fe1a:eedc dev eth0  src 2001:8b0:856:1::36  metric 0 
    cache  hoplimit 64
```

and this one has the right address: 2001:8b0:856:1::36
##### STEPS TO REPRODUCE

```
ansible -m setup -a "filter=ansible_default_ipv6" "hostname"
```
##### EXPECTED RESULTS

the ipv6 address in ansible_default_ipv6.address should be a permanent one.
##### ACTUAL RESULTS

On some machines the address is not a permanent one

Looking at https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L1985 I think a better way of discovering addresses would be to try:

```
ip -6 addr show permanent scope global
```

If that produces a single address, use it.

If not fall back to the current method.

That may subtle alter the semantics of ansible_default_ipv6.address tho :worried:

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
