### ISSUE TITLE
Proxmox module failing with 501 Not Implemented

### ISSUE THREAD

**Issue by jmgilman** [ansible/ansible#15527]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Arch Linux x64 
##### SUMMARY

Attempting to create a new LXC container with the Proxmox module is resulting in the following error:

```
fatal: [192.168.1.12]: FAILED! => {"changed": false, "failed": true, "msg": "creation of VM 110 failed with exception: 501 Not Implemented"}
```

Looks to be as if the module is attempting to call a part of the API that no longer exists. Here is the line that is logged in pveproxy that shows the 501 coming in:

```
192.168.1.1 - api@pve [21/Apr/2016:09:23:16 -0700] "POST /api2/json/nodes/proxmox/openvz HTTP/1.1" 501 13
```

OpenVZ was deprecated awhile ago, and looking at the wiki page for the Proxmox module it says that it can auto detect whether to use OpenVZ or LXC. Why is it trying to use OpenVZ when I'm running PVE > 4.x ?

Here is the details of the Proxmox version:

```
proxmox-ve: 4.1-39 (running kernel: 4.2.8-1-pve)
pve-manager: 4.1-22 (running version: 4.1-22/aca130cf)
pve-kernel-4.2.6-1-pve: 4.2.6-36
pve-kernel-4.2.8-1-pve: 4.2.8-39
lvm2: 2.02.116-pve2
corosync-pve: 2.3.5-2
libqb0: 1.0-1
pve-cluster: 4.0-36
qemu-server: 4.0-64
pve-firmware: 1.1-7
libpve-common-perl: 4.0-54
libpve-access-control: 4.0-13
libpve-storage-perl: 4.0-45
pve-libspice-server1: 0.12.5-2
vncterm: 1.2-1
pve-qemu-kvm: 2.5-9
pve-container: 1.0-52
pve-firewall: 2.0-22
pve-ha-manager: 1.0-25
ksm-control-daemon: 1.2-1
glusterfs-client: 3.5.2-2+deb8u1
lxc-pve: 1.1.5-7
lxcfs: 2.0.0-pve2
cgmanager: 0.39-pve1
criu: 1.6.0-1
zfsutils: 0.6.5-pve7~jessie
```
##### STEPS TO REPRODUCE

This is the playbook being using:

```

---
- hosts: dev
  tasks:
  - name: Create new arch linux container
    proxmox: >
      vmid=110
      node='proxmox'
      api_user='api@pve'
      api_password=''
      api_host='myhost'
      password='1234567'
      hostname='test'
      ostemplate='local:vztmpl/archlinux-base_2015-24-29-1_x86_64.tar.gz'
```

##### EXPECTED RESULTS

Expected the creation of a LXC container with a VM ID of 110.
##### ACTUAL RESULTS

The command failed with 501 Not Implemented.

```
[josh@Ansible machines]$ ansible-playbook new_container.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.12]

TASK [Create new arch linux container] *****************************************
fatal: [192.168.1.12]: FAILED! => {"changed": false, "failed": true, "msg": "creation of VM 110 failed with exception: 501 Not Implemented"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @new_container.retry

PLAY RECAP *********************************************************************
192.168.1.12               : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by jmgilman** [comment]
I interactively ran lines 332-334 in _ansible-modules-extras/cloud/misc/proxmox.py_ substituting the correct credentials and the following was returned for the Proxmox version (line 334):

```
u'4.1'
```

This caused **VZ_TYPE** to be set to **lxc** so I'm not sure what beyond that point is causing proxmoxer to request _/openvz_ which is no longer implemented.

**Comment by jmgilman** [comment]
This issue is being caused by my ansible installation not having the most up to date version of the extra_modules repository. I'm guessing I will have to be on the development version, but this seems odd for the wiki to talk about a feature that's not included in the main version.

Perhaps the wiki needs to be more specific?

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
