### ISSUE TITLE
The include_vars module variables can't be overridden with task level variable definitions.

### ISSUE THREAD

**Issue by chriskarel** [ansible/ansible#15548]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
# ansible-playbook --version
ansible-playbook 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default install via EPEL repos.
##### OS / ENVIRONMENT

Oracle Enterprise Linux 7 (RHEL7 equivalent)
##### SUMMARY

include_vars module results in variables that cannot be overridden by task level definitions.  Or at least have too high a precedence.
##### STEPS TO REPRODUCE

Import variables with include_vars, then override it with a task specific variable that should have a higher priority.

```
# cat test.yaml

---
- name: Test variable precedence
  hosts: localhost
  tasks:
     - name: Should be "foo"
       debug: msg="Variable is _{{dummyvar}}_"
       vars:
         dummyvar: 'foo'
     - include_vars: vars.yaml
     - name: Should be "bar"
       debug: msg="Variable is _{{dummyvar}}_"
       vars:
         dummyvar: 'bar'
```

```
# cat vars.yaml
dummyvar: WRONG
```
##### EXPECTED RESULTS

I would have expected the variable to be set to 'foo' and 'bar' respectively
eg:

```
# ansible-playbook test.yaml 
PLAY [Test variable precedence] ************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Should be "foo"] *********************************************************
ok: [localhost] => {
    "msg": "Variable is _foo_"
}

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [Should be "bar"] *********************************************************
ok: [localhost] => {
    "msg": "Variable is _bar_"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

Instead, the 'bar' variable setting is overridden by the previous include_vars, resulting in the value being "wrong".  This seems contrary to the [documented precedence order](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable).

```
 # ansible-playbook test.yaml 
PLAY [Test variable precedence] ************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Should be "foo"] *********************************************************
ok: [localhost] => {
    "msg": "Variable is _foo_"
}

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [Should be "bar"] *********************************************************
ok: [localhost] => {
    "msg": "Variable is _WRONG_"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```
##### Related issue

I see someone opened [a similar issue for v1.9](https://github.com/ansible/ansible/issues/15483), but seemed to believe it was fixed in 2.x.  This is definitely still occurring in v2.x.

**Comment by jimi-c** [comment]
Hi @chriskarel, after reviewing this I believe this is working as expected. Variables set via set_fact or include_vars have one of the highest levels of precedence, and as such override those set in a static manner (vars or vars_files, for instance). As such, we're going to go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
