### ISSUE TITLE
uri module: non-200 application/json responses are missing the `json` attribute.

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible#15555]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

``` shell
$ ansible --version
ansible 2.0.2.0
```
##### SUMMARY

If the uri module returns with a non-200 application/json response, the `json` attribute is missing.
##### STEPS TO REPRODUCE

I whipped up a quick Docker container for this. Create this file locally:

`nginx.conf`:

```
server {
    listen       80;

    location / {
        default_type application/json;
        return 400 '{"msg": "Heyo."}';
    }
}
```

Start the container:

```
$ docker run -v ~/path/to/nginx.conf:/etc/nginx/conf.d/default.conf -P -d nginx
```

Other findings:

As I was looking through `urls.py`, I noticed that all http errors are rescued here: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L899-L900. It looks like the exception text is added to the `info` dictionary, but not the actual http response body.
##### EXPECTED RESULTS

Under `2.0.1`:

```
$ ansible -m uri -c local -a "url=http://dockerhost:CONTAINER_PORT/" localhost
localhost | FAILED! => {
    "changed": false,
    "connection": "keep-alive",
    "content": "{\"test\": \"Heyo.\"}",
    "content_length": "17",
    "content_type": "application/json",
    "date": "Fri, 22 Apr 2016 20:13:09 GMT",
    "failed": true,
    "json": {
        "test": "Heyo."
    },
    "msg": "Status code was not [200]",
    "redirected": false,
    "server": "nginx/1.9.14",
    "status": 400
}
```

Under `2.0.2`:
##### ACTUAL RESULTS

```
$ ansible -m uri -c local -a "url=http://dockerhost:CONTAINER_PORT/" localhost

localhost | FAILED! => {
    "changed": false,
    "connection": "close",
    "content": "",
    "content_length": "17",
    "content_type": "application/json",
    "date": "Fri, 22 Apr 2016 20:14:03 GMT",
    "failed": true,
    "msg": "Status code was not [200]: HTTP Error 400: Bad Request",
    "redirected": false,
    "server": "nginx/1.9.14",
    "status": 400,
    "url": "http://192.168.99.100:32791/"
}
```

**Comment by bcoca** [comment]
Module Repo Information
=======================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:

   * https://github.com/ansible/ansible-modules-extras

If this is about an existing module:

   * Find the module at http://docs.ansible.com/list_of_all_modules.html
   * Open the documentation page for that module
   * If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
   * Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by sivel** [comment]
I realize this is closed, but just in case I am not around and/or forget to do so when the replacement is opened, I just wanted to link this to https://github.com/ansible/ansible/pull/14915

Without the above PR, we can't get access to the body when an `HTTPError` is raised.

**Comment by jctanner** [comment]
The issue has been narrowed down to urls.py, so re-opening.

**Comment by sivel** [comment]
Even with that PR linked above, a change will still need to be made to the `uri` module, to look at the `['body']` attribute also.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
