### ISSUE TITLE
Fatal: invalid key specified: <!DOCTYPE html>

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible#15604]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
#ansible --version
ansible 2.0.0.2
```
##### SUMMARY

```
    - name: Add SSH Keys for user from github
    authorized_key: user=username key=https://github.com/username.keys
    tags: add_admin_user
```

Error: 
fatal: [067cea8f-3725-40ff-aa02-675c54d988da]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"exclusive": false, "key": "https://github.com/username.keys", "key_options": null, "keyfile": "/home/username/.ssh/authorized_keys", "manage_dir": true, "path": null, "state": "present", "unique": false, "user": "username"}, "module_name": "authorized_key"}, "msg": "invalid key specified: <!DOCTYPE html>"}

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
