### ISSUE TITLE
always in block isn't triggered after failure of task from include

### ISSUE THREAD

**Issue by rudimeyer** [ansible/ansible#15623]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION
- ansible 2.0.2.0
- ansible 2.1.0.0 (detached HEAD 5954a82dd6)
- ansible 2.2.0 (devel 6b0710dde3)
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When task in included task-file in role fails, 'always' part of block is not run.
##### STEPS TO REPRODUCE

```
roles/test_role/tasks/main.yml:

---
- block:
    - name: This task succeeds
      command: /bin/true
    - include: "include_file.yml"
  always:
    - name: This should always execute
      debug: msg="This should always execute"

include_file.yml:

---
- name: "This task fails"
  command: /bin/false

playbook:

---
- hosts: all
  roles:
    - test_role
```
##### EXPECTED RESULTS

After failed task in included file, 'always' part of the block should be run before play is terminated
##### ACTUAL RESULTS

When task in included file fails the play is stopped without going through the 'always' part of the block.

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [host]

TASK [test_role : This task succeeds] ******************************************
changed: [host]

TASK [test_role : This task fails] *********************************************
fatal: [host]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.008951", "end": "2016-04-27 12:44:34.913664", "failed": true, "rc": 1, "start": "2016-04-27 12:44:34.904713", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
host          : ok=2    changed=1    unreachable=0    failed=1 
```

**Comment by jimi-c** [comment]
@rudimeyer the above patch resolves the issue for me (as well as fixing at least one other issue I found during testing). If you could also do some testing with any real-world playbooks you might have I'd appreciate it.

**Comment by jimi-c** [comment]
@rudimeyer (or anyone else): have you had any chance to confirm whether this patch/feature branch works for you?

**Comment by jimi-c** [comment]
As there has been no feedback, I've gone ahead and merged this in, as it fixes the reported issue. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
