### ISSUE TITLE
tar unarchive overwrite symlinks

### ISSUE THREAD

**Issue by akam-it** [ansible/ansible#15645]
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

there is /var/run/something folder in arch and on remote host /var/run is symlink to /run
after play /var/run from arch overwrites symlink /var/run 

```
unarchive: src=arch.tar.gz dest=/
```
##### EXPECTED RESULTS

I expect files form /var/run in arch.tar.gz will added to /var/run on remote host
like --dereference option in tar
##### ACTUAL RESULTS

symlink /var/run is overwriten by new folder from arch

**Comment by nitzmahone** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
