### ISSUE TITLE
use command run s3fs  mount failed

### ISSUE THREAD

**Issue by henryon** [ansible/ansible#15640]
##### ISSUE TYPE

- Bug Report 
##### ANSIBLE VERSION

ansible 1.9.1

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```
##### OS / ENVIRONMENT

centos 6.5
##### STEPS TO REPRODUCE

ansible-playbook  s3fs.yml

```
<!--- Paste example playbooks or commands between quotes -->
```

---
- name: Install requirement rpm package
  yum: name={{item}} state=latest
  with_items:
  - gcc
  - libstdc++-devel
  - gcc-c++
  - curl-devel
  - libxml2-devel
  - openssl-devel
  - mailcap
- name: Get libfuse s3fs  packages
  get_url: url={{item }} dest=/opt/test/  validate_certs=no timeout=1000
  with_items:
  - 'https://github.com/libfuse/libfuse/releases/download/fuse_2_9_5/fuse-2.9.5.tar.gz'
  - 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/s3fs/s3fs-1.74.tar.gz'
- name: Extract libfuse Package
  command:  tar -xvf {{ item }}
  with_items:
  - fuse-2.9.5.tar.gz
  - s3fs-1.74.tar.gz
    args:
    chdir: /opt/test
- name: Install libfuse
  shell:  './configure --prefix=/usr/local ; make ; make install '
  args:
    chdir: /opt/test/{{item}}
  with_items:
  - fuse-2.9.5
- name: Update CONFIG-PKG
  shell: 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig;ldconfig;modprobe fuse'
- name: Install s3fs
  shell:  'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig;ldconfig;modprobe fuse;./configure --prefix=/usr/local ; make ; make install '
  args:
    chdir: /opt/test/{{item}}
  with_items:
  - s3fs-1.74
- name: Push AWS CRENDENTIAL TO server
  copy: content="{{readonly}}" dest=/root/.passwd-s3fs
- file: path=/root/.passwd-s3fs owner=root group=root mode=0600 state=file
- file: path={{item}} owner=root group=root state=directory mode=0777
  with_items:
  - /s3mnt
  - /tmp/cache
- command:  s3fs  {{item.s3bucket}} {{item.dest}}  -o use_rrs -o allow_other -o use_cache={{item.cache}}
  with_items:
  - { cache: /tmp/cache, s3bucket: test-backup, dest: /s3mnt }
    tags:
  - s3mount

##### EXPECTED RESULTS

[10.2.1.2] => ok
##### ACTUAL RESULTS

```failed: [10.2.1.2] => (item={'s3bucket': 'test-backup', 'dest': '/s3mnt', 'cache': '/tmp/cache'}) => {"cmd": "s3fs -o use_cache=/tmp/cache test-backup /s3mnt -o use_rrs -o allow_other", "failed": true, "item": {"cache": "/tmp/cache", "dest": "/s3mnt", "s3bucket": "test-backup"}, "rc": 2}

<!--- Paste verbatim command output between quotes -->

```
```

**Comment by nitzmahone** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

s3fs appears to be run correctly by Ansible, it's just returning a nonzero exit code. Perhaps you should ask s3fs folks what that means, but it doesn't look like Ansible's the problem here.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
