### ISSUE TITLE
(possible data loss) git does reset --hard even with force: no

### ISSUE THREAD

**Issue by KarlAmort** [ansible/ansible#15658]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### CONFIGURATION

```
executable = /bin/bash
command_warnings = true
```
##### OS / ENVIRONMENT

Host: OS X El Capitan
Remote: Ubuntu 16.04 (This task, however, runs with connection: local)
##### SUMMARY

I am running the task below, which leads to three problems:
- it runs a `git reset --hard`, even when I explicitly set `force: false`
- I did not expect the repository to be reset. I now understand the reasoning (describing a predictable state), but I believe a hard reset deserves some protection even against confused newbies like me.
- This is a dataloss bug: The user loses all local modifications to the repository that have not been commited.
- The command actually fails, because it apparently mixes up `remote` and `version` (although this could be my mistake)
##### STEPS TO REPRODUCE

Run the following task

```

- name: pull updates from git repository
  git:
    repo: "{{ git_repository }}"
    update: yes
    force: no
    dest: "{{ path_local }}"
    clone: no
    remote: "{{ git_remote }}"
    version: "{{ git_version }}"
```

##### EXPECTED RESULTS

I expected a `git pull {{ remote }}` to be run, but I would now suggest to check for local modifications and fail (which I already had as a previous task)
##### ACTUAL RESULTS

Note: The major problem is the command it's trying to run, not that it failed.

```
TASK [je: pull updates from git repository repo={{ git_repository }},
 version={{ git_version }},
 force=False,
 dest={{ path_local }},
 remote={{ git_remote }},
 clone=False,
 update=True] ***
task path: <path>/git/tasks/synchronize.yml:12
<host> ESTABLISH LOCAL CONNECTION FOR USER: ma
<host> EXEC /bin/bash -c 'LANG=en_EN LC_ALL=en_EN LC_MESSAGES=en_EN /usr/bin/python'
    fatal: [<host>]: FAILED! => {"changed": false,
         "cmd": "/usr/local/bin/git reset --hard origin",
         "failed": true,
         "invocation": {"module_args": {"accept_hostkey": false,
         "bare": false,
         "clone": false,
         "depth": null,
         "dest": "/path/projects/<host>",
         "executable": null,
         "force": false,
         "key_file": null,
         "recursive": true,
         "reference": null,
         "refspec": null,
         "remote": "origin",
         "repo": "<url>",
         "ssh_opts": null,
         "track_submodules": false,
         "update": true,
         "verify_commit": false,
         "version": "HEAD"},
         "module_name": "git"},
         "msg": "Failed to checkout branch master",
         "rc": 128,
         "stderr": "fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions,
         like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stdout": "",
         "stdout_lines": []}
<!--- Paste verbatim command output between quotes -->
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
