### ISSUE TITLE
Already executed dependency will hold execution forever

### ISSUE THREAD

**Issue by ogmueller** [ansible/ansible#15681]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

package from ubuntu 16.04:

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

don't know of any changes right now
##### OS / ENVIRONMENT

ubuntu 16.04
##### SUMMARY

if a playbook executed a role, which is a dependency of another role, the execution will be hold forever and never ends.
##### STEPS TO REPRODUCE

just take 2 roles (e.g. iptables and fail2ban). this is a simplified example of course.
we need two important files. a playbook with 2 roles and a dependency of fail2ban to one role, which is in the playbook already. i know, that in this simplified example, the problem could be solved by not mentioning the iptables in the playbook, but in very complex playbook this is not easy nor wanted. 

PLAYBOOK:

```

---
- hosts: all
  strategy: free
  roles:
    - iptables
    - fail2ban
```

META OF FAIL2BAN

```

---
allow_duplicates: no
dependencies:
  - role: iptables
```

if you execute this playbook now, it will never end. it will execute the iptables role, but will never start with fail2ban and the playbook never ends.
##### EXPECTED RESULTS

ansible should "know" that iptables has already been executed and should just continue with fail2ban, because the dependencies has already be executed anyway.
##### ACTUAL RESULTS

there is no real result to show here. ansible will show the last command of role iptables and then hangs. it just doesn't continue nor is there any output at the end.

**Comment by bcoca** [comment]
do you have allow_duplicates set?

**Comment by ogmueller** [comment]
allow_duplicates is set to "no" in all cases.

**Comment by m-wynn** [comment]
I've also encountered this issue.  I have also created a [testcase](https://github.com/m-wynn/ansible-test-case) which demonstrates this.

**Comment by jimi-c** [comment]
Looking into this now.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
