### ISSUE TITLE
yum module failing  (on AWS RHEL 7 instance) due to rhui-lb

### ISSUE THREAD

**Issue by max-allan-surevine** [ansible/ansible#15690]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/maxa/threatvine/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Running from OSX Yosemite (don't think it's relevant though)
Controlling an AWS RHEL7 instance (ami-8b8c57f8). 
##### SUMMARY

Create an instance and get ansible's yum module to "yum update" causes a failure message.
##### STEPS TO REPRODUCE

Build an AWS instance (ami-8b8c57f8) and try to yum update (or do any yum commands) like :

```
  - yum:
      name: "*"
      state: latest
```
##### EXPECTED RESULTS

 I expected yum to update everything to the latest version.
##### ACTUAL RESULTS

It will return a message like :

```
{
  "changed": false,
  "failed": true,
  "msg": "Repo rhui-REGION-client-config-server-7 forced skip_if_unavailable=True due to: \/etc\/pki\/rhui\/cdn.redhat.com-chain.crt\n.......\n\n\nCould not contact any CDS load balancers: rhui2-cds01.eu-west-1.aws.ce.redhat.com, rhui2-cds02.eu-west-1.aws.ce.redhat.com.\n",
  "rc": 1,
  "results": [

  ]
}
```

(I removed some of the repeated listing of various repos in the middle of the output and ..... instead)
I tracked it down to the load balancer config which is enabled by default. Disable that and the yum module works, (I shouldn't need to disable load balancing though). Running a simple "yum update" command from the command line works fine with load balancing enabled.
A line like :

```
  - lineinfile: name=/etc/yum/pluginconf.d/rhui-lb.conf regexp=enabled= line="enabled=0"
```

provides a workaround.
This may not be strictly the yum module's fault, but the difference in behaviour from the command line default behaviour is not helpful. Unfortunately running with vvvvvv doesn't actually show me what the yum command looks like.

**Comment by abadger** [comment]
I believe this is the command we're invoking that's leading to that error message:

```
yum -d 2 -y check-update
```

It's odd that this command would fail while the main yum command won't.  OTOH, rhui-lb is a yum plugin so perhaps it was only tested with yum install, update, remove and something about it doesn't play well with check-update....

If you test check-update and that works from the yum commandline as well, we'll need to do some more debugging to see what is going on.  That should happen in the ansible-modules-core repository as that's where the yum module lives.  I'll paste information about that repository below.

# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by antigremlin** [comment]
@max-allan-surevine, have you tried this under become=true or the manual command under sudo? I had a similar error message mistakenly running yum without sudo. As I understand, the can be caused by the certificate files in /etc/pki/rhui not being world readable...

**Comment by snyamars** [comment]
I am getting exactly the same error while installing enterprise version of OpenShift 3.2 using the ansible script. Could you pls suggest the workaround for this issue? 
RHEL instance 7.2.

**Comment by antigremlin** [comment]
@snyamars, are you using become=true in your Ansible script? Can you run a simple yum command (like yum search python) from the server console and confirm it is working for you?

**Comment by snyamars** [comment]
@antigremlin, I running the ansible scripts with sudo. Have tried with become=true as well but the same error. I am able to run yum command from server console and it is working perfectly. Have also tried setting sslverify=0 in rhel.repo file but no success.
Ansible version is 2.2

**Comment by jarovo** [comment]
This is caused by a problem with rhui2-cds01.us-east-1.aws.ce.redhat.com. It is trying to get the list of the load-ballancer by contacting  https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/mirror/?members
Which results in HTTP 500. The other load-ballancer though works fine:

```
#curl -k https://rhui2-cds02.us-east-1.aws.ce.redhat.com/pulp/mirror/?members``
rhui2-cds01.us-east-1.aws.ce.redhat.com
rhui2-cds02.us-east-1.aws.ce.redhat.com
```

This all causes the `rh-amazon-rhui-client` to write to stdout which it probably shouldn't. I am now trying to contact the developers of this package to resolve that issue.

The workaround can be to uninstall this package, or change the order of the LB servers in the `/etc/yum.repos.d/rhui-load-balancers.conf`:

```
cat > /etc/yum.repos.d/rhui-load-balancers.conf <<EOF
rhui2-cds02.us-east-1.aws.ce.redhat.com
rhui2-cds01.us-east-1.aws.ce.redhat.com
EOF
```

**Comment by jarovo** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1387682

**Comment by praveensiddu** [comment]
This error "Could not contact any CDS load balancers" happens when you run without a sudo


$ ansible-playbook testapache.yaml

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] **************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
ok: [localhost]

TASK [install httpd] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Repo rhui-REGION-client-config-server-7 forced skip_if_unavailable=True due to: /etc/pki/rhui/cdn.redhat.com-chain.crt\nRepo rhui-REGION-client-config-server-7 forced skip_if_unavailable=True due to: /etc/pki/rhui/product/rhui-client-config-server-7.crt\nRepo rhui-REGION-client-config-server-7 forced skip_if_unavailable=True due to: /etc/pki/rhui/rhui-client-config-server-7.key\nRepo rhui-REGION-rhel-server-releases forced skip_if_unavailable=True due to: /etc/pki/rhui/cdn.redhat.com-chain.crt\nRepo rhui-REGION-rhel-server-releases forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content-rhel7.crt\nRepo rhui-REGION-rhel-server-releases forced skip_if_unavailable=True due to: /etc/pki/rhui/content-rhel7.key\nRepo rhui-REGION-rhel-server-rh-common forced skip_if_unavailable=True due to: /etc/pki/rhui/cdn.redhat.com-chain.crt\nRepo rhui-REGION-rhel-server-rh-common forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content-rhel7.crt\nRepo rhui-REGION-rhel-server-rh-common forced skip_if_unavailable=True due to: /etc/pki/rhui/content-rhel7.key\n\n\nCould not contact any CDS load balancers: rhui2-cds02.us-east-1.aws.ce.redhat.com, rhui2-cds01.us-east-1.aws.ce.redhat.com.\n", "rc": 1, "results": []}
        to retry, use: --limit @/home/ec2-user/testapache.retry

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1


[ec2-user@ip-172-31-27-49 ~]$ sudo ansible-playbook testapache.yaml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] **************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
ok: [localhost]

TASK [install httpd] **********************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
`

**Comment by ghost** [comment]
Is the Issues Fixed , Still i could see issues on AWS instance 7.4
