### ISSUE TITLE
Return variables on task includes not working anymore

### ISSUE THREAD

**Issue by dcodix** [ansible/ansible#15700]
I use to be able to do things like:

included_general_task.yml

```
- name: Get list dir
  shell: ls {{ path_dir }}
  register: {{ list }}
```

main.yml

```
- include: "included_general_task.yml path_dir=/ list=root_list"

- include: "included_general_task.yml path_dir=/tmp list=tmp_list"
```

From here on, I could access to the contents of {{ root_list }} and {{ tmp_list }} without problems.
It was working ok with ansible version 2.0.1.0, but with ansible version 2.0.2.0 when I try to acces those variables I am getting:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'root_list' is undefined"}
```

Is this a bug? or it is something that is changed and will be like this from now on?

I just tested it with the last devel version and the result is the same.

Thanks!

**Comment by rawbertp** [comment]
Same here. It works with "static" variable names but doesn't with a variable that holds the register variable name.

Works:

`register: dummyresult`

Doesn't work:

`register: "{{varname|default('dummyresult')}}"`

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi @dcodix, I've reverted 7ba790bbaf5059fb5a858227b7b1e5f852a1a288 (which was the cause of this) and also cherry-picked that to stable-2.1 so this will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
