### ISSUE TITLE
Ignore ec2.py when no credentials are present

### ISSUE THREAD

**Issue by Sodki** [ansible/ansible#15728]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /ansible/ansible.cfg
  configured module search path = ./library
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

ec2.py inventory file fails by default if there are no credentials to connect to AWS instead of ignoring them.
##### STEPS TO REPRODUCE

I use the same Ansible roles on multiple AWS accounts and local virtual machines. Before running Ansible playbooks, I automatically provision the right credentials to be used by ec2.py. This works well, for AWS machines, but for local virtual machines it fails because it tries to execute ec2.py without any credentials.
##### EXPECTED RESULTS

If no credentials exist, ec2.py should exit cleanly, with no inventory.
##### ACTUAL RESULTS

ec2.py exits with an error, which prevents execution of the playbook.

**Comment by nitzmahone** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

You're wanting to turn something that (IMHO) the vast majority of people would consider a fairly major error condition into a silent failure. Since inventory scripts aren't run directly from Ansible, you can always modify yours to behave this way, or make it non-executable and add an executable shell wrapper that detects the missing credentials and silently skips execution of the inventory script (and returning empty inv).

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
