### ISSUE TITLE
Role search paths not reset after playbook include

### ISSUE THREAD

**Issue by aibor** [ansible/ansible#15726]
##### ISSUE TYPE

Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat ansible.cfg
[defaults]

nocows = 1
```
##### OS / ENVIRONMENT

Ansible Host: Debian GNU/Linux 8
Target Host: N/A
##### SUMMARY

In a playbook when another playbook is included from a subdirectory the role search paths are not reset after the include is parsed. This results in roles in relative paths to the playbook not being found, if
such an include happens before the role is called.

We suspect that this issue is related to the basedir not being reset. A dirty quick fix was to copy.copy() the loader object instead of passing it as is in the [include module on line 74](https://github.com/ansible/ansible/blob/v2.0.2.0-1/lib/ansible/playbook/playbook_include.py#L74).
##### STEPS TO REPRODUCE

```
$ pwd
/tmp/ansible

$ ls -gG
-rw-r--r-- 1   23 Mai  4 15:36 ansible.cfg
-rw-r--r-- 1   30 Mai  4 15:33 hosts
drwxr-xr-x 4 4096 Mai  4 15:25 testbook

$ ls -gG testbook
drwxr-xr-x 2 4096 Mai  4 15:31 includes
drwxr-xr-x 3 4096 Mai  4 15:29 roles
-rw-r--r-- 1   69 Mai  4 15:37 test.yml

$ cat testbook/test.yml

---
- include: includes/pb.yml

- hosts: all
  roles:
    - testrole

$ cat testbook/includes/pb.yml

---
- hosts: all
  tasks:
    - debug:
        msg: include called

$ cat testbook/roles/testrole/tasks/main.yml

---
- debug:
    msg: testrole called

$ ansible-playbook -i hosts testbook/test.yml
```
##### EXPECTED RESULTS

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [debug] *******************************************************************
ok: [test] => {
    "msg": "include called"
}

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [testrole : debug] ********************************************************
ok: [test] => {
    "msg": "testrole called"
}

PLAY RECAP *********************************************************************
test                       : ok=4    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
ERROR! the role 'testrole' was not found in /tmp/ansible/testbook/includes/roles:/tmp/ansible/testbook/includes:/etc/ansible/roles

The error appears to have been in '/tmp/ansible/testbook/test.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - testrole
      ^ here
```

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
