### ISSUE TITLE
promox: Cannot create nodes when assigning parameter ip_address

### ISSUE THREAD

**Issue by bmillemathias** [ansible/ansible#15749]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.2.0
  config file = /home/baptistemm/Code/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

I've updated the proxmox modules to 2.1
##### OS / ENVIRONMENT

```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 24 (Twenty Four)
Release:    24
Codename:   TwentyFour
```
##### SUMMARY

I cannot create an node (lxc) when setting the `ip_address` parameter, If I remove this parameter the node can be created successfully.
##### STEPS TO REPRODUCE

This playbook works

```
proxmox: vmid=106 hostname='wallabag2' node='cactus' api_host='foo.bar.fr' api_user='root@pam' ostemplate='local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz' state=present password='xxxxxxx' onboot=true ip_address='10.1.1.106'
```

This playbook doesn't work

```
proxmox: vmid=106 hostname='wallabag2' node='cactus' api_host='foo.bar.fr' api_user='root@pam' ostemplate='local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz' state=present password='xxxxxxx' onboot=true ip_address='10.1.1.106'
```

I alos tried to specify `ip_address='10.1.1.106/24'` as done it the proxmox interface but it doesn't work neither
##### EXPECTED RESULTS

node to be created and perhaps clarify how to specify the parameter `ip_address` in the documentation (I can take care of that part).
##### ACTUAL RESULTS

node is not created

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"api_host": "foo.bar.fr", "api_password": null, "api_user": "root@pam", "cpus": 1, "cpuunits": 1000, "disk": "3", "force": false, "hostname": "wallabag", "ip_address": "10.1.1.106", "memory": 512, "nameserver": null, "netif": null, "node": "cactus", "onboot": false, "ostemplate": "local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "searchdomain": null, "state": "present", "storage": "local", "swap": 0, "timeout": 30, "validate_certs": false, "vmid": "106"}, "module_name": "proxmox"}, "msg": "creation of lxc VM 106 failed with exception: 400 Bad Request"}

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by zealot128** [comment]
Seems to be related to the Proxmox 4 API - than, ip_address can't be used, but the whole netif string:

```
- proxmox:
     netif: '{"net0":"name=eth0,ip=10.0.0.2/24,type=veth,bridge=vmbr0,gw=10.0.0.1"}'
```

That worked for me!
