### ISSUE TITLE
unarchive module fails with "No such file or directory" on OS X - El Capitan nodes

### ISSUE THREAD

**Issue by mtlynch** [ansible/ansible#15754]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 56ba10365c) last updated 2016/05/04 16:27:09 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 11:06:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1846de2809) last updated 2016/05/02 11:06:58 (GMT -400)
  config file = /home/mtlynch/e2e/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
hostfile = hosts
host_key_checking = False
```
##### OS / ENVIRONMENT

Control: Ubuntu 14.04
Node: Mac OS X El Capitan
##### SUMMARY

Unarchive fails with "No such file or directory" when the target node is an OS X - El Capitan machine. I can run the same command against an Ubuntu 14.04 node and it works fine. If I reimplement the module via shell commands, it works as expected, but the unarchive module does not seem to work.
##### STEPS TO REPRODUCE

``` bash
$ echo "foo" > test.txt && zip test.zip test.txt && ansible mac-capitan -m unarchive -a "src=test.zip dest=/tmp/"
```
##### EXPECTED RESULTS

`test.txt` gets unzipped to `/tmp` on `mac-capitan` node
##### ACTUAL RESULTS

```
mac-capitan | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": ".", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "test.zip", 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/Users/user/.ansible/tmp/ansible-tmp-1462551399.13-228141622532747/source"
        }
    }, 
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: './test.txt'"
}
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by mtlynch** [comment]
Re-filed under https://github.com/ansible/ansible-modules-core/issues/3631
