### ISSUE TITLE
Security problems using short and long IDs in apt_key module

### ISSUE THREAD

**Issue by aef** [ansible/ansible#15788]
To request OpenPGP certificates through short or long key IDs from keyservers is highly insecure and should at least be a cause for a warning, better yet, it should be disallowed. If a certificate is requested, the full fingerprint should be provided, anything less is easily spoofable because of neglectable effort to find collisions.

See the following for more information:
- https://www.godobject.net/articles/9
- https://debian-administration.org/users/dkg/weblog/105

For a live (and DANGEROUS) example try this:

```
ansible [HOSTNAME] -b -m apt_key -a 'id=10000001 keyserver=hkp://pool.sks-keyservers.net'
```

This will install two certificates which have been created as a demonstration of a collision attack.

ATTENTION: Please be sure to remove BOTH keys that have been imported into the target system APT keyring by executing the following TWICE (one call won't remove both copies, which is arguably a bug in Ansible):

```
ansible [HOSTNAME] -b -m apt_key -a 'id=10000001 keyserver=hkp://pool.sks-keyservers.net state=absent'
```

**Comment by abadger** [comment]
apt_key is a module and so this issue needs to be reopened on the ansible-modules-core repository here: https://github.com/ansible/ansible-modules-core

@bcoca and I started discussing this yesterday.  At the moment we're thinking that this is something that needs to be fixed in the apt_key command line tool (which does the actual work for this module).  If it goes into that upstream tool we would consider patching the ansible module to do the same checking in the module when older versions of the command line tool are used.

I also see the following commit to the module: d441cb176c1dc624525fa870a0389ba6df366e79 which addresses: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1481871 That's probably something that should be changed more quickly.  Someone with apt will need to test the permutations, though (ie: it appears from the bug report that fingerprints will work if 0x is prepended to the string.  Will longids  and shortids also work if 0x is prepended?  If not, perhaps only truncating the fingerprint/longid when apt_key is asked to delete the key is an okay workaround).

The module's documentation could also be updated to warn that using shortids risks collisions (or, what seems to be upstream's recommendation, to not trust public key servers for this.  Instead to use a set of predownloaded keys as the source of these keys.)
