### ISSUE TITLE
user module should delete by UID not name

### ISSUE THREAD

**Issue by doanerock** [ansible/ansible#15785]
##### ISSUE TYPE
- Feature Idea
  user module should delete by UID not name, or at least make it possible to key off the UID instead of just he name
##### ANSIBLE VERSION

ansible 1.9.4
##### OS / ENVIRONMENT

CentOS release 6.7 (Final)
##### SUMMARY

I am trying to clean up a username issue, that is a mess.  Currently there are two names, but ansibile is not able to delete any of them because it is trying to delete by name not UID which is unique.  
##### STEPS TO REPRODUCE

failed: [server] => {"failed": true, "name": "username", "rc": 1}
msg: Multiple entries named 'username' in /etc/passwd. Please fix this with pwck or grpck.
userdel: cannot remove entry 'username' from /etc/passwd
##### EXPECTED RESULTS

I deleted username with UID ...

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
