### ISSUE TITLE
Allow keyserver options in apt_key module (especially for custom TLS X.509 trust anchors)

### ISSUE THREAD

**Issue by aef** [ansible/ansible#15789]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

2.x
##### CONFIGURATION

Nothing special
##### OS / ENVIRONMENT

Debian 8 "Jessie", but not relevant
##### SUMMARY

There is no option to set a trusted X.509 trust anchor (certificate authority) for keyserver requests in the apt_key module.

To request a certificate from the (probably biggest) decentral keyserver network SKS (hkps://hkps.pool.sks-keyservers.net) through TLS, requires the ability to set the SKS certificate authority as trust anchor (see https://sks-keyservers.net/overview-of-pools.php).

In GnuPG, I would provide the option `keyserver-options ca-cert-file=/etc/ssl/certs/sks-keyservers.netCA.pem`.

Being able to set any kinds of keyserver-options would be a plus, for example: `keyserver-options http-proxy=socks5-hostname://127.0.0.1:9050` and `keyserver-options no-try-dns-srv` to safely tunnel the request through Tor.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by kladiv** [comment]
+1 about "keyserver-options" of apt_key module
