### ISSUE TITLE
systemd '--user' option

### ISSUE THREAD

**Issue by souenzzo** [ansible/ansible#15805]
##### ISSUE TYPE
- Feature Idea
##### OS / ENVIRONMENT

Linux/Systemd (not sure if others init has equivalent)
##### SUMMARY

Systemd has a userland option "systemd --user [enable|stop] service".
Add it on "service" module
##### EXPECTED RESULTS

Example command:

``` bash
systemctl --user enable ssh-agent
```

Example yml

``` yml
- service name=ssh-agent user=yes enabled=yes
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by AquaL1te** [comment]
So in other words, this still hasn't been implemented? The feature request is pretty detailed and this functionality is missing: https://docs.ansible.com/ansible/systemd_module.html

**Comment by C0rn3j** [comment]
For people running across this through google, this is handled by the systemd module's scope option nowadays.

https://docs.ansible.com/ansible/latest/modules/systemd_module.html
