### ISSUE TITLE
gce_img module support snapshot disk as source

### ISSUE THREAD

**Issue by vladpanainte** [ansible/ansible#15819]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “2.0.1” between quotes -->
"2.0.1" or higher
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

gce_img source to support snapshot disk
##### STEPS TO REPRODUCE

```
<!--- Paste example playbooks or commands between quotes -->
```

##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by vladpanainte** [comment]
Thanks and sorry for confusing the repos. I've submitted an issue to the
indicated repo.

---

Vlad Panainte
