### ISSUE TITLE
cannot connect to S3 from RHEL-5 

### ISSUE THREAD

**Issue by imvitaliy** [ansible/ansible#15818]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.0.2.0
##### OS / ENVIRONMENT

RHEL-5
##### SUMMARY

can't run "module_name": "s3", only in Rhel-5 
##### STEPS TO REPRODUCE

```
- name: Get package from s3
  s3: bucket=name object={{pkg }} dest=/tmp/{{ pkg }} aws_access_key={{ aws_access_key_id }} aws_secret_key={{ aws_secret_access_key_id }} mode=get

```
##### EXPECTED RESULTS

should download package from S3
##### ACTUAL RESULTS

```
fatal: [52.39.32.137]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "s3"}, "module_stderr": "", "module_stdout": "  File \"/root/.ansible/tmp/ansible-tmp-1462959054.23-157331921236549/s3\", line 326\r\n    except SSLError as e:\r\n                     ^\r\nSyntaxError: invalid syntax\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
