### ISSUE TITLE
lineinfile module : insertbefore should insert before first match of specified regular expression

### ISSUE THREAD

**Issue by dmcnaught** [ansible/ansible#15824]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

insertbefore : If specified, the line will be inserted before the last match of specified regular expression
insertafter : If specified, the line will be inserted after the last match of specified regular expression

It seems to me that insertbefore should insert before the first match of the specified regexp. This would be consistent with the way that insertafter works (the reverse).

In our example we are adding lines to sshd_config that need to go before any ^Match blocks. If there are multiple match blocks then insertbefore won't create a valid sshd_config 
##### STEPS TO REPRODUCE

``````
lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitUserEnvironment" line="PermitUserEnvironment no" insertbefore="^Match" state=present```

##### EXPECTED RESULTS
If more than one Match block is in /etc/ssh/sshd_config, the line should be inserted before the first.
##### ACTUAL RESULTS
ssh throws an error:
/etc/ssh/sshd_config line 94: Directive 'PermitUserEnvironment' is not allowed within a Match block
``````

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by dmcnaught** [comment]
https://github.com/ansible/ansible-modules-core/issues/3648
