### ISSUE TITLE
Issue creating Security Groups using Ansible for AWS

### ISSUE THREAD

**Issue by vasyl-slobodyan** [ansible/ansible#15827]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0 (detached HEAD 24d9e5e0b4) last updated 2016/05/12 10:13:21 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 9db1233521) last updated 2016/05/05 11:31:55 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 675d778b50) last updated 2016/05/05 11:32:04 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```

Also found in devel branch.
##### OS / ENVIRONMENT

Linux 4.4.8-20.46.amzn1.x86_64 #1 SMP Wed Apr 27 19:28:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

Issue creating Security Group with outbound rules specified as empty string.
##### STEPS TO REPRODUCE

Create a playbook with security group creation and few variables pointing to rules (empty string of rules for rules).

```
- hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: no
  vars:
    - elb_ingress: ""
    - elb_egress: ""

  tasks:
  - name: Create load balancer security group for nodes
    local_action:
       module: ec2_group
       region: "your-region"
       vpc_id: "your-vpc-id"
       name: "just-remove-me-laterG"
       description: "Load Balancer-LB/SG"
       rules: "{{ elb_ingress }}"
       rules_egress: "{{ elb_egress }}"
    register: aws_elb_sg
```

##### EXPECTED RESULTS

Security group created 
##### ACTUAL RESULTS

Error message comes up

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1463050953.26-165238132175252/ec2_group", line 2678, in <module>
    main()
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1463050953.26-165238132175252/ec2_group", line 348, in main
    if rule['proto'] in ('all', '-1', -1):
TypeError: string indices must be integers, not str

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_group"}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1463050953.26-165238132175252/ec2_group\", line 2678, in <module>\n    main()\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1463050953.26-165238132175252/ec2_group\", line 348, in main\n    if rule['proto'] in ('all', '-1', -1):\nTypeError: string indices must be integers, not str\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by vasyl-slobodyan** [comment]
Update, works for 

```
ansible-playbook 1.9.6 (detached HEAD 7644312b20) last updated 2016/05/12 11:52:34 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 6972d0a291) last updated 2016/05/12 12:05:27 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1220e47f07) last updated 2016/05/12 12:05:27 (GMT +000)
  configured module search path = None
```

**Comment by vasyl-slobodyan** [comment]
Update after some digging this seems to be the commit that broke the code.
https://github.com/ansible/ansible-modules-core/commit/97f5174c09a82d63b0684f2b7390bfd19e5e530b

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
