### ISSUE TITLE
$LOOKUP()-weirdness. Uncached? Unexpanded?

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1586]
I've run into something which I find completely unintuitive. `ansible 0.9` latest devel (by the way, the version is exactly that -- it used to show git commit sha1)

When I define a var containing `$LOOKUP()`, I'd expect that to be expanded where I define it. Instead, I sometimes obtain a literal `$LOOKUP(...)` instead of the expanded content. As this is going to cause pain with, say, database lookups (higher overhead, etc.) I feel it should be addressed. Unless I'm misunderstanding what they ought to do ...

For example:

Playbook:

``` yaml

---
- hosts: a1.*
  connection: paramiko
  vars:
  - mylines: $LOOKUP(lines,/bin/ls -1 /usr/share/dict)
  tasks:
    - local_action: template src=demovar.j2 dest=/tmp/tt
```

Template

``` jinja2

{{ mylines }}

LINES begin:
{% for l in mylines %}
--> {{ l }}
{% endfor %}
LINES end:
```

Output:

```

README,connectives,propernames,web2,web2a,words

LINES begin:
--> $
--> L
--> O
--> O
--> K
--> U
--> P
--> (
--> l
--> i
--> n
--> e
--> s
--> ,
--> /
--> b
--> i
--> n
--> /
--> l
--> s
-->  
--> -
--> 1
-->  
--> /
--> u
--> s
--> r
--> /
--> s
--> h
--> a
--> r
--> e
--> /
--> d
--> i
--> c
--> t
--> )
LINES end:
```

Note how `{{ mylines }}` contains the LOOKUP expansion, whereas the second use of `mylines` contains the literal content `$LOOKUP...`.

**Comment by jpmens** [comment]
To clarify. In, say, a shell, if I do

``` sh
list=`ls -l`

echo $list
echo $list
```

the expansion occurs once at assignment time and not every time I use the value of `$list`. I feel Ansible should do this similarly.

**Comment by mpdehaan** [comment]
Please show me the playbook, possibly regex issue?

-- Michael

**Comment by jpmens** [comment]
Doubtful.
Playbook is above.

**Comment by mpdehaan** [comment]
Yep.   LOOKUP templating it seems, needs to be run at a different level,
earlier or later or in between, where it's not being run.

Good luck!

**Comment by mpdehaan** [comment]
@daniel_hozac is pretty good with the recent changes to the templating
code, I'd suggest getting up with him.

**Comment by jpmens** [comment]
@dhozac Can you help here, please? :-)

**Comment by dhozac** [comment]
It's not unexpected. We replace things as late as possible, this is how you can have $LOOKUP(module, stufftosendtoit) in your jinja2 templates and have it work. I think in order to use lookup plugins from inside jinja2, we should add a function to access them.

I previously looked at making some kind of variable lookup replacer for jinja2, where we would invoke our replacer on everything jinja2 accessed, but I couldn't figure out a way to do so. That would be the nicest solution for sure, as that would just make your case work. But until someone more familiar with jinja2 can figure that out, I think we're stuck with something like

```
{% for i in lookup('plugin', 'terms...') %}
...
{% endfor %}
```

**Comment by mpdehaan** [comment]
I would disagree that we need some special syntax.   Rather, it should work
in the way people are going to try to use it, and we can make that happen.

In the above, the problem is that there are some variables un-evaluated
prior to sending them into Jinja2 land, and we need to process any of those.

It should be sufficient to walk over the dictionary and process any values
who had scalar keys that contained dollar signs.

This needs to happen immediately before Jinja2 is invoked.

**Comment by mpdehaan** [comment]
This is not to say we don't _also_ need to have a lookup() function in
Jinja2, I'm just saying it needs to be the case that
vars/vars_files/group_vars/host_vars/etc should be able to get set
with lookups in them, as in JP's example.

**Comment by jpmens** [comment]
This looks a lot better, thank you @dhozac 
However, variables are still expanded twice when used as follows:

``` yaml
---
- hosts: a1.*
  connection: paramiko
  vars:
  - myname: $LOOKUP(redis_kv,redis://localhost:6379,myname)
  tasks:
    - debug: msg="${myname}"
    - local_action: template src=demovar.j2 dest=/tmp/tt
```

Using `$myname` in the debug causes the first external lookup to be performed, and the second is in the template (where I use `{{ myname }}`. 

Using `{{ myname }}` more than once in the template works fine: just a single external lookup is performed.

**Comment by dhozac** [comment]
That is to be expected. We lazily perform all lookups and variable replacements at time of need, we don't walk the entire variable tree to do it. We also don't cache the results, as they may change during the course of the playbook.

**Comment by mpdehaan** [comment]
Daniel, it's important to not dismiss things as "this is the way it works",
and expected behavior is what the user expects (least surprise), rather
than what the code is implemented to do.   This is quite _unexpected_,
though I would definitely agree it's not serious, it is highly weird.  This
really should be evaluated only once.

It is probably true that lookup computations should be done as early as
possible at the point where they completely resolve, though we've created a
heinous monster with the idea that we can do things like recurse/nest
variables at infinite depth.

We don't cache the results because simply, we don't cache the results.
However, a super easy fix here would be to cache the results, and there's
nothing wrong with that, provided that was cleared between plays (which
seems to be a reasonable level of permanence).

I do worry, extremely much so, that the template code is getting way too
complicated for it's own good, and we need to clean it up the best we can
for this release, and then look at making it MUCH cleaner for the next.

**Comment by dhozac** [comment]
I was merely explaining how it works and why it works that way.

**Comment by mpdehaan** [comment]
Ok, wasn't clear.
