### ISSUE TITLE
bug: included nested block with conditions results in unexpeced tasks execution

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#15926]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.2
2.1 rc3
```
##### SUMMARY

if `include` is used to include a tasks list with a nested block, a condition is not evaluated correctly.
##### STEPS TO REPRODUCE

given a simple role which has an include in `main.yml` for `inc.yml` and in `inc.yml` there is a nested block.
However since the `when` condition of the outer block is false, no task should be exectued, but the nested `block 2.1` is executed.

``` yaml
# file: common/vars/main.yml 

---
condition: ok
```

``` yaml
# file: common/tasks/main.yml 

---
- include: inc.yml
```

``` yaml
# file: common/tasks/inc.yml 

---
- block:
  - name: block 2
    fail: msg="this should not run"
  - block:
    - name: block 2.1
      fail: msg="this should not run" 
  when: condition == 'nok'
```

The bug does not show up without `include`.
##### EXPECTED RESULTS

```
 $ ansible-playbook common.yml  -i hosts

PLAY [localhost] ***************************************************************

TASK [common : include] ********************************************************
included: /home/resmo/tmp/test-block/common/tasks/inc.yml for localhost

TASK [common : block 2] *************************************************
skipping: [localhost]

TASK [common : block 2.1] ******************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```
##### ACTUAL RESULTS

```
 $ ansible-playbook common.yml  -i hosts

PLAY [localhost] ***************************************************************

TASK [common : include] ********************************************************
included: /home/resmo/tmp/test-block/common/tasks/inc.yml for localhost

TASK [common : block 2] *************************************************
skipping: [localhost]

TASK [common : block 2.1] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "this should not run"}
    to retry, use: --limit @common.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
