### ISSUE TITLE
lineinfile module should not need permissions in parent directory

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#15941]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.0.2.0
```
##### STEPS TO REPRODUCE

As an example you could make `/etc/hosts` writable for a <user> and execute following under the permissions of <user>:

```
lineinfile:
  dest: /etc/hosts
  line: "anything relevant"
```
##### EXPECTED RESULTS

The lineinfile_module should work as expected.
##### ACTUAL RESULTS

The lineinfile_module needs write permissions for <user> in the parent /etc directory, as it creates a temporary file for atomic copy. This file should be created somewhere else, as the parent /etc directory should not be writable to <user>

**Comment by bcoca** [comment]
to make changes atomically we need to replace the file, this requires write access to the directory, otherwise the change is not atomic and can lead to data corruption.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
