### ISSUE TITLE
Rolling Update Batch Size

### ISSUE THREAD

**Issue by Nagendra86** [ansible/ansible#15954]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible 2.0.1.0” between quotes -->
```
##### OS / ENVIRONMENT

CentOS Linux release 7.1.1503
##### SUMMARY

 If One uses : Serial clause in playbook ,it should move to other hosts if it fails for one host ,which i didn't find true.It get failed if my task get failed and doesn't move down to next host 
##### STEPS TO REPRODUCE

pasted below the playbook,which will run on two hosts

```
<!--- Paste example playbooks or commands between quotes

- name: serial execution on my two hosts db,web
  hosts: webserver
  serial: 1

  tasks:
    - name: This is to execute on single host
      action: copy src=inventory dest=/tmp

 -->
...
```

##### EXPECTED RESULTS

when i ran above playbook,which should run on another host as well ,as per the documentation 

http://docs.ansible.com/ansible/playbooks_delegation.html  
# Rolling Update Batch Size

but it fails and exit out ,if it gets failed for first host
##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by WolverineFan** [comment]
We have seen the same issue in Ansible 2.1.0.0 with batch size of 15. If one host in a batch fails, the playbook will exit after that batch rather than the old behavior of continuing until all batches are complete.

**Comment by WolverineFan** [comment]
This is still broken in 2.1.1.0

**Comment by jimi-c** [comment]
@Nagendra86 this is an incorrect assumption about the docs. With `serial: 1` but no max_fail_percentage set, the failure of a single host will cause the play to stop executing.

@WolverineFan I am looking into your comments, as I do see the batches ending incorrectly right now.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
