### ISSUE TITLE
Variable assginment works on one host and fails on another host

### ISSUE THREAD

**Issue by bequiet88** [ansible/ansible#15978]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.0.2
  config file = /home/jhuelss/Dokumente/git/projects/looneytunes_qa/ansible.cfg
  configured module search path = ../../delivery/modules

(Same happens for me in the 2.1 RC4 from yesterday)
##### CONFIGURATION

hash_behaviour = merge
executable = /bin/sh
gathering = explicit
##### OS / ENVIRONMENT

Running from: Ubuntu 16.04
Managing: Centos 7.2
##### SUMMARY

I'm facing an unexpected and indeterministic variable assignment behaviour while using filter plugins.
##### STEPS TO REPRODUCE

I've got the following inventory situation:

```
[zookeeper]
granny
[storm]
gossamer storm_tags=ui,supervisor,nimbus,logviewer,drpc
granny storm_tags=supervisor,logviewer
```

In my storm playbook, I use a Jinja2 template with the following Jinja2 expression to write a list of zookeeper instances into the storm.yaml file:

```
### zookeeper.*
storm.zookeeper.servers:
{% for host in zookeeper_hosts.split(',') %}
    - "{{host}}"
{% endfor %}
```

The zookeeper_hosts variable is defined as follows:
`zookeeper_hosts: "{{ groups['zookeeper'] | to_fqdn('.local') | join(',') }}"`

where to_fqdn() is a filter plugin

```
from pprint import pprint

def to_fqdn(l, domain):
    print 'input host: %s' % l
    print 'input domain: %s' % domain
    if not isinstance(l, list):
        raise TypeError('Input to the \'grep\' filter should be a list')
    if not isinstance(domain, str):
        raise TypeError('1st argument should be a string')
    result = []
    for item in l:
         result.append(item + domain)
         print 'result: %s' % result
    return result

class FilterModule(object):
    def filters(self):
        return {
            'to_fqdn': to_fqdn,
        } 
```

If I run the following command, the task below will be executed and causing and error which is described in the actual behaviour section below.
`ansible-playbook -i inv.ini -t storm_all install.yml`

```
- name: configuration is updated
  become_user: "{{ storm_user }}"
  template:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner={{ storm_user }}
    group={{ storm_group }}
    mode={{ item.mode|default('0644') }}
  with_items:
  - { src: storm.yaml.j2, dest: "{{ storm_home_dir }}/conf/storm.yaml" }
```
##### EXPECTED RESULTS

The expected results works quite well for the host _gossamer_ (i.e. not the Zookeeper host).
Debug information for _groups['zookeeper']_

```
ok: [gossamer] => {
    "groups['zookeeper']": [
        "granny"
    ]
}
```

Debug information for _zookeeper_hosts_

```
ok: [gossamer] => {
    "zookeeper_hosts": "granny.local"
}
```

Execution of storm.yaml config task (see above) results with the following:

```
input host: [u'granny']
input domain: .local
result: [u'granny.local']
changed: [gossamer] => (item={u'dest': u'/opt/gin3/software/apache-storm-1.0.1/conf/storm.yaml', u'src': u'storm.yaml.j2'})
```

where the first three lines are the print statements from the custom python plugin above.

=> the to_fqdn() filter works as expected and adds ".local" to the zookeeper hostname.
I expect that the same happens for the host _granny_.
##### ACTUAL RESULTS

The actual results differ from the expected results outlined above for the host _granny_.

Debug information for _groups['zookeeper']_ **(still the same as above)**

```
ok: [granny] => {
    "groups['zookeeper']": [
        "granny"
    ]
}
```

Debug information for _zookeeper_hosts_ **(Note: zookeeper_hosts is a list now and not the expected concatenated string)**

```
ok: [granny] => {
    "zookeeper_hosts": [
        "granny"
    ]
}
```

Subsequently, the execution of the storm.yaml config task (see above) results with the following error message:

```
failed: [granny] => (item={u'dest': u'/opt/gin3/software/apache-storm-1.0.1/conf/storm.yaml', u'src': u'storm.yaml.j2'}) => {"failed": true, "item": {"dest": "/opt/gin3/software/apache-storm-1.0.1/conf/storm.yaml", "src": "storm.yaml.j2"}, "msg": "AnsibleUndefinedVariable: ERROR! 'list object' has no attribute 'split'"}
```

-vvvv does not add extra information to this error message.
Note:
- The error message is thrown during the templating process
- No print statements from the custom to_fqdn() plugin where written during the assignment of zookeeper_hosts => I assume that the to_fqdn() filter is not even called.

Am I missing out something substantial or is it indeed a strange and buggy behaviour?

**Comment by bequiet88** [comment]
One update: One a different cluster, the setup of installing zookeeper and storm on the same node works as lined out in the "Expected Results" section. No idea why the settings mentioned above fails.

**Comment by abadger** [comment]
I can't reproduce this using 2.0.0.2 or a checkout of the devel branch.  Since you're not able to reproduce it on a separate cluster either, I think it's likely this is a problem in the way ansible is setup and configured on the first cluster rather than a problem in ansible's code.  Questions like that are better asked on the mailing list or irc where multiple users who may have had similar issues can try to figure out what's different between your two controller hosts.  I'll paste the mailing list information below.

To start you off, the symptoms you're describing sound a lot like ansible is finding the to_fqdn() filter in another file than the one you are expecting.  You could try moving the file you've been modifying outside of paths ansible is looking for filter plugins.  If nothing changes then you'll know that there's another to_fqdn filter defined somewhere.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
