### ISSUE TITLE
"service: enabled=yes" do not enable systemd service

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#15997]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

```
[defaults]
timeout = 40
hash_behaviour = merge
gathering = smart
jinja2_extensions = jinja2.ext.do,jinja2.ext.loopcontrols
retry_files_enabled = False

[ssh_connection]
pipelining = True

[privilege_escalation]
become = True
become_ask_pass = True
```
##### OS / ENVIRONMENT

OS X 10.11.5
##### SUMMARY

"service: enabled=yes" do not enable systemd service
##### STEPS TO REPRODUCE

Task:

```
- service: name=zabbix-server enabled=yes
```
##### EXPECTED RESULTS

Make service zabbix-server enabled - service should start on boot:

```
# systemctl status zabbix-server.service
● zabbix-server.service - Zabbix Server (MySQL/MariaDB)
   Loaded: loaded (/lib/systemd/system/zabbix-server.service; enabled; vendor preset: enabled)
```
##### ACTUAL RESULTS

Ansible task do not enable service. Task finished with `changed: false` status:

```
TASK [zabbix-server : service] *************************************************
task path: /Users/rob/ansible/sysops/roles/zabbix-server/tasks/main.yml:47
<z01> ESTABLISH SSH CONNECTION FOR USER: None
<z01> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=40 -o ControlPath=/Users/rob/.ansible/cp/ansible-ssh-%h-%p-%r z01 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=hhyazmleyrvcyzepgzvnakvfhcoazewd] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-hhyazmleyrvcyzepgzvnakvfhcoazewd; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"''"'"''
ok: [z01] => {"changed": false, "enabled": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "zabbix-server", "pattern": null, "runlevel": "default", "sleep": null, "state": null}, "module_name": "service"}, "name": "zabbix-server"}
```

```
# systemctl status zabbix-server.service
● zabbix-server.service - Zabbix Server (MySQL/MariaDB)
   Loaded: loaded (/lib/systemd/system/zabbix-server.service; disabled; vendor preset: enabled)
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
