### ISSUE TITLE
Lineinfile fails if file does not exists even with create=yes

### ISSUE THREAD

**Issue by Heliosmaster** [ansible/ansible#16002]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OSX 10.10 El Capitan
##### SUMMARY

`Lineinfile` module with `create=yes` fails if the file is not existing
##### STEPS TO REPRODUCE

This task:

```
  - name: Write down that we deployed this version at this time
    lineinfile: create=yes dest=file.log line="Something here"
```

fails if there is not file.log at the destination folder.
##### EXPECTED RESULTS

That the file is created, according to [the documentation](http://docs.ansible.com/ansible/lineinfile_module.html)
##### ACTUAL RESULTS

```
fatal: [myserver.example.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "lineinfile"}, "module_stderr": "OpenSSH_6.9p1, LibreSSL 2.1.8\r\ndebug1: Reading configuration data /Users/davide/.ssh/config\r\ndebug1: /Users/davide/.ssh/config line 263: Applying options for *.example.com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 49408\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to myserver.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/my-user/.ansible/tmp/ansible-tmp-1464249636.48-154091230314073/lineinfile\", line 2564, in <module>\r\n    main()\r\n  File \"/home/my-user/.ansible/tmp/ansible-tmp-1464249636.48-154091230314073/lineinfile\", line 371, in main\r\n    ins_aft, ins_bef, create, backup, backrefs)\r\n  File \"/home/my-user/.ansible/tmp/ansible-tmp-1464249636.48-154091230314073/lineinfile\", line 192, in present\r\n    os.makedirs(destpath)\r\n  File \"/usr/lib/python2.7/os.py\", line 157, in makedirs\r\n    mkdir(name, mode)\r\nOSError: [Errno 2] No such file or directory: ''\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by KamilLelonek** [comment]
Same bug here..

**Comment by Heliosmaster** [comment]
@KamilLelonek look here: ansible/ansible-modules-core#3838

**Comment by KamilLelonek** [comment]
Thanks!
