### ISSUE TITLE
custom ansible module written in jython fails with "PyCF_ONLY_AST SyntaxError: invalid syntax" on ansible 2.1

### ISSUE THREAD

**Issue by bertramn** [ansible/ansible#16019]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = //home/fred/workspaces/play/ansible.cfg
  configured module search path = ['/usr/share/ansible', './library']
```
##### CONFIGURATION

added `library = /usr/share/ansible:./library` to ansible.cfg
##### OS / ENVIRONMENT

“N/A”
##### SUMMARY

The new ansible 2.1 version applies some custom module validation rules to modules written in python. This new validation fails to recognise that this python script has specified an alternative (`jython`) interpreter. Script validation fails on plain python (on which this script will not run obviously) but script is perfectly executable on `jython`.
##### STEPS TO REPRODUCE
1. clone example [test case](https://github.com/bertramn/ansible-custom-jython-module)

``` sh
git clone https://github.com/bertramn/ansible-custom-jython-module
cd ansible-custom-jython-module
```
1. run test example

``` sh
ansible-playbook -vvvv local.yml
```

The steps to reproduce actually do not require the installation of jython as ansible will fail before the module script is actually executed.
##### EXPECTED RESULTS

Expect the custom module is executed on localhost (or remote if targeted). Also expect the line `from ansible.module_utils.basic import *` to be expanded with the ansible module boilerplate prior to the file being transferred to the target host for execution.

```
TASK [wildfly] *****************************************************************
task path: /home/bertramn/workspaces/jython-module/local.yml:4
ok: [localhost] => {"changed": false, "invocation": {"module_args": {"wildfly_home": "/opt/wildfly-10.0.0.Final"}, "module_name": "wildfly"}, "msg": "connected to wildfly cli"}
```
##### ACTUAL RESULTS

What appears to be happening is that ansible "validates" the module script if it is a python module. Ansible fails to recognise that this script is in fact executed with a python interpreter other than plain python and applies validation that albeit invalid in python are perfectly valid and executable by the jython interpreter.

```
TASK [wildfly] *****************************************************************
task path: /home/bertramn/workspaces/jython-module/local.yml:4
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 446, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 583, in _execute_module
    (module_style, shebang, module_data) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 149, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 718, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 576, in _find_snippet_imports
    recursive_finder(module_name, module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python2.7/site-packages/ansible/executor/module_common.py", line 397, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 48
    from org.jboss.as.cli.scriptsupport import CLI
                    ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by abadger** [comment]
There's no validation happening here.  ast.parse is being used to find the modue_utils imports within a new-style python module so that we can include them in the library that we send to the remote machine.  So it's an integral part of the new module assembling code.  I don't think we should stop using ast to parse the modules -- using regexes or other pattern matching is very fragile compared with using python's builtin facilities.

If jython is not parsable as regular python then that's a difficulty.  I think our options range from reimplementing and maintaining module replacer just for the few custom third party modules that are like this (probably not a good return on investment) on the one hand to treating jython modules that fail to parse with ast.parse as either old-style or non-native wants json modules on the other (that would require porting this jython module to process its parameters differently and adding some code that is presently taken care of by the default boilerplate).  I'm not sure if there's any options in between those two.....

**Comment by bertramn** [comment]
I am not a python expert but I can't see why you would want to restrict your plugin architecture to whatever python interpreter you have chosen. The script I provided runs perfectly fine in jython and ansible 2.0 and the declaration at the top explictelty states the script is to be interpreted by jython. The offending line is `from org.jboss.as.cli.scriptsupport import CLI` which cannot be changed as package name is valid java abd jython. Why does ansible has to parse a script with python when its clearly not meant to be executed by the regular python interpretor?

**Comment by bertramn** [comment]
I can also see that `sys.exetuable` yields `/usr/bin/python` when the module is executed on the target. This indicates that the module is not executed correctly and the shebang `#!/usr/bin/env jython` is completely ignored.

**Comment by abadger** [comment]
@bertramn, regarding restricting the plugin to a specific interpreter, that's not the case.  If you want to use the boilerplate that we provide for new-style python ansible modules, then you'd have to write python that works within that framework.  If you want to write your code to an interpreter that isn't compatible with that, it's perfectly fine but you can't expect to use the boilerplate then.  Instead it can be written as a non-native-wants-json module.  You can look at the ruby examples here (https://github.com/ansible/ansible-for-rubyists ) for what that looks like (the main difference with new-style python modules is that they read args in a different way and that they are responsible for formatting their output as json.

For your question about the shebang line being ignored.  In general the shebang lines are not expected to be used verbatim.  Ansible uses the shebang to determine what interpreter is being used and then checks the inventory to see if a non-standard interpreter path is specified when running that module on a specific host.  So the module should use #!/usr/bin/jython in the moduel's shebang line and then if you want to find it via env, use the environment variable for this host to specify that ansible_jython_interpreter="/usr/bin/env jython".

However, that probably isn't working quite like that in this case... what's currently happening is that the module is determined to be a new-style python module because of the import of ansible.module_utils.basic.  Python is the operative word there.  Because of that the module is looking for ansible_python_interpreter and substituting in the default for that.

Since the libraries available to jython will be very different from the libraries available to python I think we do not want this to happen.  The question is how to achieve that.  Jython modules probably should not be importing ansible.module_utils.  If this module didn't do that, that would solve this problem.  Another possibility could be to try checking the shebang line in addition to searching for the imports from module_utils.  I'm not sure if that's a good idea, though.  It would fix this case but it might break other cases where people don't understand the shebang line and specify env or pypy there....

**Comment by bertramn** [comment]
@abadger yes looking at the functionality of custom modules in 2.1 I can see that just executing it with jython shebang is not going to work anymore.I could write a "python" module to bootstrap the jython process on the target host, the only part I can't quite work out is how I can ask ansible on the control machine to include the jython module file into the `ansible_modlib.zip` archive that is transfered to the target host? It appears ansible is only zipping up resources that are referenced in the "import" section of the python module. Could you offer any hints on how to ship resource files to the target host as part of a normal custom python module execution?

**Comment by abadger** [comment]
Ansible is only bundling up python code that comes from ansible/module_utils/ on the controller that is used by the new-style python module.  It won't use any other files.

If you're talking about writing a python module to bootstrap the jython module it's probably much easier to just convert this into a non-native-wants-json module.  I can't test the wildfly code so I'm not sure if this is correct but porting to non-native-wants-json should look something like this:  https://toshio.fedorapeople.org/ansible/wildfly2.py

**Comment by abadger** [comment]
The differences from the original are basically:
- Remove the "from ansible.module_utils.basic import *" as that's what's triggering Ansible to think this is a new-style python module.
- Add the comment "# WANT_JSON" so that ansible passes the arguments as a json string in a file rather than key=value pairs.
- Implement argument parsing, returning json, and logging (I punted on that but you can implement the stub function _log() to do that) inside of the module to replace the boilerplate from AnsibleModule.

**Comment by abadger** [comment]
@bertramn See if my ported code can be the basis of your module going forward.  If so, I'll go ahead and close this issue.

**Comment by bertramn** [comment]
Yes that should work, what I was hoping to be able to do (and which worked in ansible <  2.1) was to leave the parsing and error handling up to the ansible plugin boilerplate code. It worked like a charm, so now its back to having to write all of it from scratch. Is there a possibility to add functinoality to the ansible module code on the control machine to enable shipping of module resources from the library  folder to the target host? Afterall a module should be a self contained unit but sometimes requires other items it needs to execute remotely (just like your ansible python module packages up all the util classes and ships it to the temp folder on the remote machine).

**Comment by abadger** [comment]
@bertramn I don't believe that's something we'll be doing in the near future... If you'd like to write up a specification and then work on implementing it we could consider it.  I'm not sure how feasible it is, though.  Each language probably needs some custom code in the controller code to differentiate it from other languages that the module could be written in.  The place for specifications to be written and discussed is here:  https://github.com/ansible/proposals
