### ISSUE TITLE
Ansible 2.1 on Python 3.5 fails with "NameError: name 'urllib2' is not defined"

### ISSUE THREAD

**Issue by eyecat** [ansible/ansible#16013]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

(Default)
##### OS / ENVIRONMENT

(Mac OSX)
##### SUMMARY

Traceback (most recent call last):
  File "/Users/yuhuhuan/.virtualenvs/dev35/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/executor/playbook_executor.py", line 80, in run
    self._tqm.load_callbacks()
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py", line 164, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/plugins/__init__.py", line 368, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/Users/yuhuhuan/.pyenv/versions/3.5.1/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/plugins/callback/hipchat.py", line 32, in <module>
    from ansible.module_utils.urls import open_url
  File "/Users/yuhuhuan/.virtualenvs/dev35/lib/python3.5/site-packages/ansible/module_utils/urls.py", line 330, in <module>
    if hasattr(httplib, 'HTTPSConnection') and hasattr(urllib2, 'HTTPSHandler'):
NameError: name 'urllib2' is not defined
##### STEPS TO REPRODUCE

(Just execute ansible-playbook)

**Comment by eyecat** [comment]
The issue is caused by this line:
https://github.com/ansible/ansible/blob/stable-2.1/lib/ansible/module_utils/urls.py#L330

At the beginning of this file, there is logic to conditionally import urllib2 (no longer in Python 3). However this line did not check whether urllib2 is available.

**Comment by bcoca** [comment]
there are several dozen lines in that file that are not python3 compliant .

**Comment by bcoca** [comment]
FYI, Ansible is not yet python3 compatible, but it is a goal to get there

**Comment by eyecat** [comment]
Thanks.

While it may not be officially supported on Python 3, (The core functionality) of Ansible 2.0 worked just fine on Python 3.5 (especially for the managing host with limited set of local actions). This new change renders the whole Ansible unusable on Python 3.

**Comment by bcoca** [comment]
url.py has never worked with py3, i actually had PR to change this that was abandoned for several reasons.

**Comment by eyecat** [comment]
AH either url.py has a new behavior from 2.0=>2.1, or it is being pulled in as part of `ansible/plugins/callback/hipchat.py line 32`
`from ansible.module_utils.urls import open_url`
which exposed this problem in 2.1

**Comment by bcoca** [comment]
that used to be a \* import, in any case ansible-playbook still imported it and failed under python3

**Comment by tobiasmcnulty** [comment]
As announced by Guido at PyCon 2016, Python 2 itself will be _unsupported_ as of 2020 (4 short years away). The ansible docs about Python 3 are misleading: I don't think it's fair to say that Python 3 is completely different and "most" Python programs haven't migrated yet. Most Python programs that I use (especially development-focused ones) advocate first for Python 3 usage and only offer Python 2.7 as a fall-back.

When do you plan to support Python 3? To be quite honest, lack of any kind of Python 3 roadmap (i.e., something more than "it is a goal to get there") makes me question whether it makes sense to adopt Ansible in a world that every day looks more and more like Python 3 is the way of the future.

**Comment by tobiasmcnulty** [comment]
Maybe I spoke too soon.. I do see Travis is building successfully with 3.5 now. Maybe we just need some doc updates and/or a formal announcement that Python 3 will be supported?

**Comment by abadger** [comment]
@tobiasmcnulty Wanted to give a little history of what we've been doing to support Python3.  

Python 3 on the controller side is something that we've been preparing for in parallell with developing 2.x.  However, we had so many other pieces of refactoring as part of that effort that we knew it wouldn't be done in time for 2.0 or likely (and as it turned out, in fact) for 2.1.  We did put in some important building blocks, though:
- During the 2.x refactoring we strove to convert strings from bytes to text at the borders instead of having a mix of bytes and text that we had to convert all over the code base.
- Starting with the sprints at Pycon Montreal, 2015, we merged and, on occassion, wrote ourselves, patches to fix Ansible to work with python3.

I'm leaving the Pycon 2016 Sprints in Portland today and we've pushed this forward a little bit:
- `ansible localhost -m ping` now works.   ansible-playbook and ssh connection don't work yet so this is more a proof-of-concept than good for actual work but this is a start :-)
- Many modules were updated so that their syntax is compatible with python3.   This doesn't mean that they will work but it is a step forward which we can check... which takes us to:

We still have a lot of work to do.  As mentioned above, we need to do more work before ansible-playbook and the connection plugins other than local work with python3.  Our test coverage for modules is all integration tests.  Those do okay for checking for regressions in the common paths that people are frequently using but it isn't the best for checking that every piece of code has remained compatible with both python2 and python3.  We also could use more unittests for controller code.  We're hovering around 55% unittest coverage right now.  Unittests aren't incredibly hard to add here and would be quite useful for keeping out regressions.

So getting us to a point where we can claim "support" for python3 is going to take multiple releases.  The current plan (Will be on the 2.2 roadmap when it is out) is that 2.2 will contain a controller that can run on python3 (/usr/bin/ansible, ansible-playbook, and the other scripts that you run on the host which manages your other machines will run under python3).  There will be a few modules ported as well.  These will be more a proof of how much work it is to port other modules, I don't think we'll have a complete enough subset to be usable for a real site.

2.3 I hope to approach a usable set of modules for common tasks.  I don't think that a site that has fully committed to running ansible will be able to manage hosts solely with python3 installed but they should find it is possible or almost possible to use ansible on python3 for specific tasks (like deploying a web application or running package updates on their servers).

2.4 is a little too far out for me to project what a good goal will be -- if porting of modules turns out to be really time consuming then we'll continue to chip away -- probably with modules that people tell us they need to run on python3.  If it turns out to be easy for the majority of cases, we may try to finish porting all of the low hanging fruit so that we just have a small list of modules that are known to not work with python3 when 2.4 is released.

Around the 2.4 time frame porting to python3 may become easier as well.  We're hoping that as RHEL5 goes EOL in 2017 we may finally be able to stop supporting python-2.4 in that timeframe.  Concurrent support of python3 and python-2.4 is extra work that most projects do not have to deal with.  If we can drop support that should make it easier for us.  However, there are many customers that still run RHEL5 today so we're not sure if that's going to be doable or not yet.

**Comment by tobiasmcnulty** [comment]
@abadger Many thanks for the detailed reply and I'm sorry I didn't stop by the Ansible table at the sprints! I think it is much farther along than I and probably others understand and I'm super grateful for all of your + others' work!

I guess what I am saying is it would be nice to see Ansible/RedHat as **_organizations**_ standing behind Python 3 support, rather than relying on the team member efforts at sprints to work this stuff out ad-hoc.

I hope my message did not come across as too "complainy" as that was certainly not my intent. I do think this issue is more a business one than a technical one, though. As you allude to there is a complicated relationship between RHEL5 and Ansible which makes me wonder how long it will really be, regardless of when the technical issues might be resolved. I wonder if RHEL5 users could be pinned to an "LTS" release of Ansible as they are with Python, allowing the product to advance unhindered in the meantime? Maybe that's happening already and I just don't know it?

Thanks again and safe travels!

**Comment by bcoca** [comment]
@tobiasmcnulty also please note that Ansible is a tool to automate existing systems, which currently overwhelmingly have Python 2 pre-installed, not Python 3. New distro releases are all starting to shift to Python 3 and we need to support that also, which is what the current effort is aiming at.

Migrating Ansible to Python 3 is relatively easy, supporting BOTH python 2.4 and Python 3  .... is 'fun'. This is required by having significant part of our user base still using distro versions that had either Python 2.4 pre-installed or as only available 'standard' option.

**Comment by tobegit3hub** [comment]
Same issue with Python 3.4.

**Comment by thebroz** [comment]
Python 3 was released December 3, 2008. that's a long time ago. I've not written any Python in version 2 for more than 6 years, and neither has my team. 
I just started looking at Ansible, and getting started isn't going well. Is there a Python 3 development branch I can check out and work with?

**Comment by sivel** [comment]
Python3 support is outlined in the roadmap at https://github.com/ansible/ansible/blob/devel/docsite/rst/roadmap/ROADMAP_2_2.rst

**Comment by thebroz** [comment]
Thanks for the link, Sivel! It looks like Python 3 support is coming soon!!

**Comment by akofink** [comment]
This is working for me on OS X 11.5 with ansible 2.2.0 and python 3.5.2

**Comment by mtreu** [comment]
Is there any way to avoid this while using Python 3.5.1 and Ansible 2.0.0.2?
Or do I have to go back to calling Ansible via subprocess?

**Comment by bcoca** [comment]
So I'm going to close and lock this ticket. All questions have been answered above or the provided links to the roadmaps. Progress on 3.x compatibility will be added to each release's notes, not to this ticket.
