### ISSUE TITLE
Server port in command line get less priority

### ISSUE THREAD

**Issue by mdnasr** [ansible/ansible#16042]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.10
##### SUMMARY

My playbook look like this:

```
# play.yml

---
- hosts: all
  vars:
    - ansible_ssh_port: 2222
  tasks:
    - command: touch /tmp/abcdef
    # There is another task that changes port to 2222
```

The first access to server is done using port 22 so i call the playbook using these arguments

```
ansible-playbook -i "194.1.3.4:22," play.yml
```

In older version of ansible (2.0) it worked like a charm and ansible access server using port **22** but in new version (2.1.0.0) it tries to connect using port specified in playbook so it fails to connect.

```
<194.1.3.4> ESTABLISH SSH CONNECTION FOR USER: root
<194.1.3.4> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 194.1.3.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464524251.34-43103475774375 `" && echo ansible-tmp-1464524251.34-43103475774375="` echo $HOME/.ansible/tmp/ansible-tmp-1464524251.34-43103475774375 `" ) && sleep 0'"'"''
fatal: [194.1.3.4]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
```

When i remove ansible_ssh_port from vars in play.yml i can access server using port 22

```
# play.yml modified

---
- hosts: all
  tasks:
    - command: touch /tmp/abcdef
    # There is another task that changes port to 2222
```

**So why ssh port defined in playbook take higher priority then defined in command line? Is this known change in new version or bug?**

**Comment by bcoca** [comment]
This behavior is correct, -i is 'inventory' so the defined :22 there gets put into `ansible_ssh_port` behind the scenes, this is a var and subject to normal variable precedence, which means that defining that var in play overrides the one defined in inventory. 

If on the other hand you use the `port` directive, it should still override from inventory as 'connection variables' override directives.

2.0  had several bugs in which the precedence was not applied correctly, we have since then fixed that, sorry for the confusion.
