### ISSUE TITLE
ansible 2.0.1.0 run show version with Cisco ASA-55x0

### ISSUE THREAD

**Issue by zhanght1** [ansible/ansible#16047]
I could login the cisco device with SSH and run the show version successfully.

```
[root@peklnelh03 ansible]# ssh xxxxxxx@10.106.65.xxx
xxxx@10.106.65.xxx's password: 
**********************************************************************
This is a private property facility to be accessed and used for Lenovo
internal systems. Unauthorized Access Prohibited!
**********************************************************************
***********************************************************************
*  Warning Notice:                                                    *
*    ip verify reverse-path interface is not supported      *
Type help or '?' for a list of available commands.
CNSHPFW5510-01> show version

Cisco Adaptive Security Appliance Software Version 8.2(5)51 
Device Manager Version 5.2(4)
..............
```

However, I run the ios_command with ansible, I got this error:

```
TASK [ios_command] *************************************************************
fatal: [10.106.65.xxx]: FAILED! => {"changed": false, "commands": "terminal length 0", "failed": true, "msg": "terminal length 0\r\n                 ^\r\nERROR: % Invalid input detected at '^' marker.\r\n\r> "}
```

```
- hosts: ios
  gather_facts: no
  connection: local

  tasks:
  - name: LOGIN
    include_vars: secrets.yaml

  - name: PROVIDER
    set_fact:
      provider:
        host: "{10.106.65.xxx}"
        username: "{xxx}"
        password: "{6785493@bcdD}"
        auth_pass: "{cisco}"
  - ios_command:
      host: "10.106.65.xxxxx"
      username: "xxxxxx"
      password: "6785493@bcdD"
      port: "22"
      commands:
        - show version
    register: version
  - debug: var=version.stdout_lines
```

Could someone give me some advice to fix this issue?
BR
Felix

**Comment by zhanght1** [comment]
---
- hosts: ios
  gather_facts: no
  connection: local

  tasks:
  - name: LOGIN
    include_vars: secrets.yaml

  - name: PROVIDER
    set_fact:
      provider:
        host: "{10.106.65.250}"
        username: "{wenzy1}"
        password: "{6785493@bcdD}"
        auth_pass: "{cisco}"
#  - name: VERSION
  - ios_command:
#      provider: "{provider}"
      host: "10.106.65.250"
      username: "wenzy1"
      password: "6785493@bcdD"
      commands:
        - enable
    register: version
  - debug: var=version.stdout_lines

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
