### ISSUE TITLE
Support updating tags in Cloudformation task

### ISSUE THREAD

**Issue by ash2k** [ansible/ansible#16061]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

2.1.0.0
##### CONFIGURATION

A playbook with cloudformation task.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Current docs say it is not possible to update tags https://docs.ansible.com/ansible/cloudformation_module.html
But it is possible since recently. https://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Stack.update
Implement the update for tags?
##### STEPS TO REPRODUCE

Run a playbook with cloudformation task with modified tags.
##### EXPECTED RESULTS

Tags on the stack are updated.
##### ACTUAL RESULTS

Tags on the stack are not updated.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by ash2k** [comment]
In fact there is a PR open already https://github.com/ansible/ansible-modules-core/pull/3638

Cheers!
