### ISSUE TITLE
become: yes affects ansible_user_id differently depending on where it's used

### ISSUE THREAD

**Issue by cjw296** [ansible/ansible#16072]
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

when `become=yes` is used in ansible.cfg, the behaviour of `{{ansible_user_id}}` is different than when `become: yes` is used on a task.
##### STEPS TO REPRODUCE

So, take `ansible.cfg` as follows:

```
[privilege_escalation]
become=$A
```

And the following task:

```
- shell: "echo {{ansible_user_id}} `whoami`"
  become: $B
```

So, assuming a connection user of `chris` and a privileged user of `root`...
##### EXPECTED RESULTS

```
A=yes B=yes echo="chris root"
A=no B=yes echo="chris root"
A=yes B=no echo="chris chris"
A=no B=no echo="chris chris"
```
##### ACTUAL RESULTS

```
A=yes B=yes echo="root root"
A=no B=yes echo="chris root"
A=yes B=no echo="root chris"
A=no B=no echo="chris chris"
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

`ansible_user_id` gets set by fact gathering, which is a task, in your examples you are in one case running the whole playbook as the become user (including fact gathering) in the other you are running a task as the become user, but not the fact gathering one, hence the difference.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by cjw296** [comment]
Hmm, kinda disappointed to see this just flat closed having talked this through with you guys at the booth.

Something is not right here.

**Comment by cjw296** [comment]
@jimi-c - is the above something you're really okay with just writing off as "works as expected"?
I found it massively confusing, I suspect I'm not the only one...

**Comment by bcoca** [comment]
booth non-withstanding, the issue is not a bug, its a misconception.

`A=yes B=no echo="chris chris"`<= is an incorrect expectation, 

it will always be 'root X' when A is yes
it will always be 'X root' when B is yes

the reason is because ansible_user_id gets set by gather_facts/setup and depends on the user that Ansible IS at the time of gathering. When A=yes that user is root, hence the results you get.

**Comment by cjw296** [comment]
Yes, the results do suggest that fact gathering in the case of become=yes appearing in ansible.cfg happens at the wrong time.

**Comment by bcoca** [comment]
no, it happens at the correct time, you are just expecting a result that does not match with what is happening.

**Comment by omerlin** [comment]
I have been exactly in the same case on ansible 2.1.
The problem is clear for me and related to fact gathering.

When i activate fact caching in /etc/ansible.cfg :
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible

=> ansible_user_id = user before sudo
when i deactivate fact caching,
=> ansible_user_id=root

It's easily reproducible.
So i'm quite sure cjw296 is right.
