### ISSUE TITLE
Unarchive fails when a zip file contains too many files

### ISSUE THREAD

**Issue by ntrrgc** [ansible/ansible#16083]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /hdd/home/ntrrgc/Documentos/Dropbox/hepdata-explore/deployment/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

My `ansible.cfg`:

```
[defaults]
pipelining = True
remote_tmp = /tmp/ansible-tmp
nocows = True
callback_plugins = callback_plugins
```

Inside `callback_plugins` the only element is `human_log.py` from here: https://github.com/n0ts/ansible-human_log
##### OS / ENVIRONMENT

Host: Arch Linux (rolling), x86_64
Managed: Ubuntu 16.04, x86_64
##### SUMMARY

When I use the `unarchive` module with an archive having too many files (89500 files in my case), it fails with a `Too many arguments` error. It seems to be adding each one of the files as an argument of a shell command (though I didn't get to see what command since the argument list was longer than my terminal buffer).
##### STEPS TO REPRODUCE

Create a zip file with lots of files and tell ansible to unarchive it, e.g:

```
- name: Upload data set
  unarchive: dest=/hepdata/ src=data.zip creates=/hepdata/data.zip
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
