### ISSUE TITLE
xml module should become part of ansible core modules

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#16147]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /media/psf/Home/bmll/devops/ansible.cfg
  configured module search path = ['/usr/share/ansible', 'roles.galaxy/cmprescott.xml/library']
```

Ansible should have the XML module as part of the ansible core. Current it is available from https://github.com/cmprescott/ansible-xml

**Comment by alikins** [comment]
This appears to be a submission about a module.

We would appreciate if you can submit this there (https://github.com/ansible/ansible-modules-core)
instead. (If we move it, the owner of the issue resets to ansible instead of you).

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by tbielawa** [comment]
*nudge*
