### ISSUE TITLE
YUM module doesn't install package

### ISSUE THREAD

**Issue by conserva-dev** [ansible/ansible#16165]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Master host - Ubuntu 14.04
Managed host - Centos 6.7
##### SUMMARY

I'm trying to install (upgrade) iproute2 on my centos vm to enable usage of network namespaces on it. So, I'm using yum module to install rpm from my storage, but ansible says that there's no need to install it.
The problem appeared after 2.0.1 -> 2.1.0 upgrade.
##### STEPS TO REPRODUCE

- Install ansible 2.1 on master host
- run play to install package

```
 $ ansible all -i '10.1.1.2,' -m yum -a "name=http://storage.local/iproute-2.6.32-130.el6ost.netns.2.x86_64.rpm state=present" -u root -k
```

##### EXPECTED RESULTS

On managed host:
[root@test ~]# yum list installed | grep iproute
iproute.x86_64                  2.6.32-130.el6ost.netns.2 @/iproute-2.6.32-130.el6ost.netns.2.x86_64
[root@test ~]# 
##### ACTUAL RESULTS

10.1.1.2 | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "http://storage.local/iproute-2.6.32-130.el6ost.netns.2.x86_64.rpm"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }, 
        "module_name": "yum"
    }, 
    "msg": "", 
    "rc": 0, 
    "results": []
}

On managed host:
[root@test ~]# yum list installed | grep iproute
iproute.x86_64                  2.6.32-54.el6             @centos-base  
[root@test ~]# 

```
cons@cons-ws: ansible $ ansible all -i '10.1.1.2,' -m yum -a "name=http://storage.local/iproute-2.6.32-130.el6ost.netns.2.x86_64.rpm state=present" -u root -k
SSH password: 
10.1.1.2 | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "http://storage.local/iproute-2.6.32-130.el6ost.netns.2.x86_64.rpm"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }, 
        "module_name": "yum"
    }, 
    "msg": "", 
    "rc": 0, 
    "results": []
}
```

Also, yum works pretty nice with other packages from the same storage.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
