### ISSUE TITLE
Add image update support to docker_service

### ISSUE THREAD

**Issue by derkork** [ansible/ansible#16167]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Currently it is not easily possible to update images used by docker_service. When an image does not exist, docker_service will pull it, but it won't update it once it is already there. The only way around this is to use `state:absent` and `remove_images:all` to kill the container and delete all images. This is suboptimal because you have to re-download the whole image even if just a tiny part changed and you have to  invoke two instances of the docker_service command to update an existing service. 
##### STEPS TO REPRODUCE

I suggest adding a flag to `docker_service` which is controlling the update policy of the image in question, e.g.

`update_image: yes` will perform a `docker-compose pull` before actually starting the service. If the pull yields a new image version, then this qualifies as a change of configuration and `docker_service` will then restart/recreate the container (according to the value of `recreate`).

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
