### ISSUE TITLE
path to playbook is added twice using with_fileglob with a relative path

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#1618]
looks like there is a bug when using with_fileglob with relative paths

  failed: [emil-oe-1-mgt] => (item=projects/emil/data/acm.properties) => {"failed": true, "item": "projects/emil/data/acm.properties"}
  msg: could not find src=projects/emil/projects/emil/data/acm.properties 

snippet from the playbook:

  copy: src=$item dest=/opt/tomcat/data/ owner=tomcat group=tomcat
    with_fileglob: data/*

projects/emil is the path to the playbook
the fileglob in question is data/\* which is relative to the playbook

looks like that relative path is added twice somehow

tested with ansible from latest devel

**Comment by dhozac** [comment]
Yeah, this is tricky. For non-copy, non-template cases, fileglob needs to be dwimmed to have a correct path. For copy and template though, they already do their own dwimming. Maybe dwimming should add a ./ to the result, and skip ones that have that? (Dwim as a verb is great.)

**Comment by mpdehaan** [comment]
Well you want to be able to let "./" be legal and still dwim.

rather, dwim should always result in an absolute path after dwimming, so if
something starts with "/" it does not dwim, and the dwim function always
returns the absolute path.

**Comment by dhozac** [comment]
Turns out to not be so tricky after all. The problem is that fileglob dwims the path in order for it to expand correctly. It, however, does not remove the dwim prefix when returning the list of items, exposing things like playbook structure to the actions (consider running as an included playbook from a top-level and from its real location). So, #1643 removes the dwim prefix before returning the items, and letting whatever uses the item dwim again, if required.

**Comment by srgvg** [comment]
Just tested it on my code, problem is fixed.
Thanks!
