### ISSUE TITLE
Add state=query option for OS Packaging Modules

### ISSUE THREAD

**Issue by font** [ansible/ansible#16218]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

I would like to query for the installation status of a particular package without actually changing the state of the package on the machine. This would allow one to register a variable to act upon in some other way.

It seems the way this is generally done is to run the shell module and execute commands to determine whether a package is installed. For example:

```
shell: rpm -q <package>
register: pkg_query
changed_when: false
```

Instead, I would like to use the OS Packaging Modules to query for the installation status of a particular package. This would be like adding a `state: query` option to some of the OS Packaging Modules which would then allow one to register a variable to capture the result. This would also help cleanup repetitive tasks just to handle different package managers: `apt`, `yum` and `dnf` are the ones that come to mind where this would be useful.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by jctanner** [comment]
Related Issues:
https://github.com/ansible/ansible-modules-core/issues/3917
https://github.com/ansible/ansible/issues/19086
