### ISSUE TITLE
Trying to gather facts from F5

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#16220]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

RHEL7
##### STEPS TO REPRODUCE

```

---
   - hosts: F5
     gather_facts: no
     tasks:
     - name: F5 Gather Facts
       bigip_facts:
        server: 10.1.1.1
        user: XYZ
        password: 1234
        include: pool
        validate_certs: no
       delegate_to: localhost
     - debug: var=bigip

```

##### EXPECTED RESULTS

A complete list of facts from the debug? 
##### ACTUAL RESULTS

 ansible-playbook slf_F5_Gather_Facts.yml

PLAY [F5] **********************************************************************

TASK [F5 Gather Facts] *********************************************************
ok: [10.1.1.1 -> localhost]

TASK [debug] *******************************************************************
ok: [10.1.1.1.] => {
    "bigip": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
10.1.1.1.          : ok=2    changed=0    unreachable=0    failed=0

```
Thanks
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
