### ISSUE TITLE
setlocale: LC_MESSAGES: cannot change locale (en_US.utf8): No such file or directory

### ISSUE THREAD

**Issue by vladimirmartsul** [ansible/ansible#16227]
Hi! I'm trying to set up Gentoo from the current install-amd64-minimal-20160602.iso with Ansible and get error about locale.

From my master host:

```
# ansible -m setup some_remote_host -vvv
Using /etc/ansible/ansible.cfg as config file
<some_remote_host> ESTABLISH SSH CONNECTION FOR USER: None
<some_remote_host> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=6000 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r some_remote_host '/bin/sh -c '"'"'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python && sleep 0'"'"''
some_remote_host | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "setup"
    },
    "module_stderr": "/bin/sh: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.utf8): No such file or directory\nTraceback (most recent call last):\n  File \"/tmp/ansible_r9lbo4fc/ansible_module_setup.py\", line 127, in <module>\n    main()\n  File \"/tmp/ansible_r9lbo4fc/ansible_module_setup.py\", line 117, in main\n    supports_check_mode = True,\n  File \"/tmp/ansible_r9lbo4fc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 679, in __init__\n  File \"/tmp/ansible_r9lbo4fc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1615, in _log_invocation\n  File \"/tmp/ansible_r9lbo4fc/ansible_modlib.zip/ansible/module_utils/basic.py\", line 475, in heuristic_log_sanitize\nTypeError: 'str' does not support the buffer interface\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

```
# grep module_lang /etc/ansible/ansible.cfg
module_lang = C
```

```
# locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

```
# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
# python -V
Python 2.7.11
```

At the remote host side:

```
# python -V
Python 3.4.3
```

```
# locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

This issue is similar to the https://github.com/ansible/ansible/issues/12286 and I think is related to the python version too. Am I right?
Gentoo was switched to the python-3 as default in the install iso about year ago and I used oldest available ISO with python-2 as possible but now I have nothing older than month.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- You need to install python2 on the remote host for ansible to be able to manage it. You will also need to define ansible_python_interpreter for the host if py2 is not the default python.

http://stackoverflow.com/questions/22769568/system-specific-variables-in-ansible

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by vladimirmartsul** [comment]
Thanks for ansible_python_interpreter: "/usr/bin/python2" idea, it's working!
