### ISSUE TITLE
Playbook defined variables are lost within roles

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#16237]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

roles_path    = /etc/ansible/roles:/home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
fact_caching = redis
fact_caching_timeout = 86400
ANSIBLE_HOSTS=./hosts
##### OS / ENVIRONMENT

Ubuntu 16.04 4.4.0-24
##### SUMMARY

A few variables are imported inside a playbook which then calls the role."ios_pull_config".
All those variables appear when I print them through another role 'print_variables' included as a dependency inside the first role.
But their value vanishes into thin air as soon as the role "ios_pull_config" starts once the dependency is done.
##### STEPS TO REPRODUCE

**inventory file**:

```
[iosv]
vIOS-[1:3]
```

**DNS mappings in group_vars/all/dns.yml**

```
vIOS-1: 192.168.137.254
vIOS-2: 10.0.113.2
vIOS-3: 10.0.2.3
```

**Another variable from host_vars/{{ inventory_hostname }}/os_family.yml**

```
connections.os_family: iosv
```

**role: roles/ios_pull_config/tasks/main.yml**

```
- name: Print some external variables
  debug: var={{ item }}
  with_items:
        - connections.os_family
        - vIOS-1
```

**role dependency which prints all variables: roles/ios_pull_config/meta/main.yml**

```
dependencies: 
  - print_variables
```

**playbook "pull_configs" outside of role path**:

```
- name: Pull IOS/IOSv/IOSv-L2 startup and running configs
  hosts: iosv
  gather_facts: no
  roles:
    - { role: ios_pull_config, config: startup-config }
    - { role: ios_pull_config, config: running-config }
```
##### EXPECTED RESULTS

**The external variables "connections.os_family" and the 'vIOS-1/2/3" should be still defined within the role.**
##### ACTUAL RESULTS

**Those variables lose their value as soon as the role begins after the role dependency has finished running**.

```
PLAYBOOK: pull_configs.yml *****************************************************
1 plays in pull_configs.yml

PLAY [Pull IOS/IOSv/IOSv-L2 startup and running configs] ***********************

TASK [print_variables : Print all variables for each remote device] ************
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles/print_variables/tasks/main.yml:27
ok: [vIOS-1] => {
    "hostvars[inventory_hostname]": {
        "ansible_check_mode": false, 
        "ansible_version": {
            "full": "2.1.0.0", 
            "major": 2, 
            "minor": 1, 
            "revision": 0, 
            "string": "2.1.0.0"
        }, 
        "connections.os_family": "iosv", 
        "group_names": [
            "iosv"
        ], 
...
        "vIOS-1": "192.168.137.254", 
        "vIOS-2": "10.0.113.2", 
        "vIOS-3": "10.0.2.3"
    }
}
ok: [vIOS-2] => {
_same values as the ones with vIOS-1_
ok: [vIOS-3] => {
_same values as the ones with vIOS-1_
TASK [ios_pull_config : Print some variables] **********************************
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles/ios_pull_config/tasks/main.yml:38
ok: [vIOS-1] => (item=connections.os_family) => {
    "connections.os_family": "VARIABLE IS NOT DEFINED!", 
    "invocation": {
        "module_args": {
            "var": "connections.os_family"
        }, 
        "module_name": "debug"
    }, 
    "item": "connections.os_family"
}
ok: [vIOS-2] => (item=connections.os_family) => {
_same values as the ones with vIOS-1_
ok: [vIOS-1] => (item=vIOS-1) => {
    "invocation": {
        "module_args": {
            "var": "vIOS-1"
        }, 
        "module_name": "debug"
    }, 
    "item": "vIOS-1", 
    "vIOS-1": "VARIABLE IS NOT DEFINED!"
}

```

**Comment by jimi-c** [comment]
Hi @jean-christophe-manciot, sorry to take so long to get back to this. This is actually not a bug, but is instead a problem in the way you're declaring variables.

First, with jinja2 templating, a period is used to indicate a key value in a dictionary. So for `connections.os_family` it expects the variable to be declared in the following way:

<pre>
connections:
  os_family: iosv
</pre>

Either that, or do not use periods in the variable name.

Second, variable names must conform to acceptable python syntax. In the case of your inventory names, they have a dash (`-`) in them, which is invalid. If you change the dash to an underscore, your example works as expected.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jean-christophe-manciot** [comment]
@jimi-c : You are right; I have corrected my issues several months ago, sorry for not closing this thread earlier.

**Comment by jimi-c** [comment]
No worries, it's equally our fault for not catching it sooner and having it just sit here :)
