### ISSUE TITLE
Complete list over Windows-compatible modules

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#16255]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

2.2.0
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Windows
##### SUMMARY

The documentation states that in addition to the win_-modules, "Most of the Ansible modules in core Ansible are written...".
We need a definitive and complete list of modules that are expected to work on Windows, in addition to the win_-modules.

**Comment by jhawkesworth** [comment]
There was some chat about this on ansible-devel irc channel last week.As well as things that work on windows, there are controller side modules like pause. I would like to have a way of tagging modules so the docs can show, perhaps using icons which targets they run against. So far I haven't looked into what it would take to start adding to the docs though.

**Comment by trondhindenes** [comment]
I'd like to bump this. We need to show users clearly which modules work on the Windows platform.

**Comment by trondhindenes** [comment]
While we wait for a way of tagging I think we just have to double down and list out the modules that work on windows so that there's a definite list somewhere.

**Comment by trondhindenes** [comment]
@nitzmahone do you happen to have a list? I really want us to get this in the docs, I'd be happy to PR it but I need help figuring out which modules (outside of win*) actually work on windows.

**Comment by nitzmahone** [comment]
Somebody had the clever idea of symlinking the docstubs for the relevant ones (since all the cross-platform ones are actions) under the WIndows module dir so they'd show up there when we build docs, but I'm slightly nervous about unanticipated downstream effects (esp. CI-ish things) before we have real module/doc metadata to drive those processes from.

The action/module pairs that should work when targeting Windows hosts are:
- assemble (haven't tested, but _should_ work)
- fetch
- raw
- script
- slurp
- template

Additionally, the following control-side-only actions work when targeting Windows hosts:
- add_host
- assert
- debug
- fail
- group_by
- include_vars
- meta
- pause
- set_fact

**Comment by trondhindenes** [comment]
Thanks matt. Created pr #17201 to get this into docs.

**Comment by dagwieers** [comment]
@trondhindenes I would like to close this issue, but your changes haven't hit the online documentation yet. And that's been merged three months ago !

@gundalow Can you please ensure that the docs are current. A few weeks back I noticed incomplete docs and started to improve them, only to notice that the existing docs were already perfect, but the online docs were stale.

**Comment by gundalow** [comment]
I did a production docs run yesterday so everything *should* be live now.

**Comment by jhawkesworth** [comment]
It looks like the list is live to me so I'm going to close this, hope noone minds.  Assemble doesn't seem to work but I suggested on issue raised above delegating to localhost as a workaround.

**Comment by jhawkesworth** [comment]
closing

**Comment by dagwieers** [comment]
Wondering why we have win_template when template works as well ?

**Comment by jhawkesworth** [comment]
win_template is largely historic.  Long ago it was actually a separate (action plugin) but it was about 90% copy and paste from template so it got abstracted as part of the ansible 2.0 re-write if I recall.  There's still some windows-specific documentation though  (jinja2 header trick for generating windows line endings).

**Comment by dagwieers** [comment]
@jhawkesworth So I don't understand, should users be using **template** or **win_template** ?
The documentation is not clear about it, the notes in **win_template** are missing from **template**, so is it not affected by those ? I think we should definitely add notes.

Also for all the non-windows modules that have a Windows variant. I will make a PR for those.

**Comment by jhawkesworth** [comment]
@dagwieers Right now it probably doesn't matter which is used.  Before 2.0 I think you had to use win_template because template couldn't handle windows-style paths.
That said, I would support a change where **win_template** gives you windows style line endings by default, and **template** doesn't.  Would still need to respect the jinja2 directive in the template though in order to avoid breaking existing playbooks.   If anyone ever implemented that then the docs would need to be different, otherwise no harm in making the documentation consistent.
I don't think removing win_template is an option as it would break backward compatibility.

**Comment by dagwieers** [comment]
No, removing was not an option for me either. But it's important that people understand what's used for what. Especially if we (actively) promote both for Windows. Thanks for clearing this up. I will look into making it more clear from the docs.
