### ISSUE TITLE
win_copy module fails to copy the files on Windows 2008 R2 system

### ISSUE THREAD

**Issue by sbasapure** [ansible/ansible#16266]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
2.1
```
##### OS / ENVIRONMENT

-->Ansible 2.1 on Ubuntu 14.4 and endpoint OS is Windows 2008 R2
The winrm and PS details on Windows 2008 R2 system are as follows

Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

PS C:\Users\SOE-Load> $PSVersiontable

Name                           Value

---

WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0}
SerializationVersion           1.1.0.1
BuildVersion                   6.2.9200.16398
PSVersion                      3.0
CLRVersion                     4.0.30319.1
PSRemotingProtocolVersion      2.2
##### SUMMARY

I am using the win_copy ansible module to transfer a software package sources files from an ansible role - files folderbut ansible failed to copy the files , in fact it only copies part of the files , either it failed to copy due to timeout or size limitation and throws with the following timeout errors.

The problem in on Windows 2008 R2 but there is no problem on Windows 2012 R2
Fatal: [10.20.73.193]: FAILED! => {"failed": true, "msg": "winrm send_input failed"}

PLAY RECAP *********************************************************************
10.20.73.193 : ok=1 changed=1 unreachable=0 failed=1 

stderr> [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call
last): File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 205, in _winrm_exec
self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
eof=is_last) File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 186, in _winrm_send_input
rs = protocol.send_message(xmltodict.unparse(rq)) File
"/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in
send_message return self.transport.send_message(message) File
"/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 173, in
send_message response = self.session.send(prepared_request,
timeout=self.read_timeout_sec) File "/usr/local/lib/python2.7/dist-
packages/requests/sessions.py", line 585, in send r = adapter.send(request,
**kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py",
line 479, in send raise ReadTimeout(e, request=request) ReadTimeout:
HTTPSConnectionPool(host='10.20.73.193', port=5986): Read timed out. (read
timeout=30)

Based on the above error I have tried changing the below parameters value  in protocol.py file but  did not fix the problem.

DEFAULT_READ_TIMEOUT_SEC 
DEFAULT_OPERATION_TIMEOUT_SEC
DEFAULT_MAX_ENV_SIZE

and it throws different error as below

stderr> [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call
last): File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 205, in _winrm_exec
self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
eof=is_last) File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 186, in _winrm_send_input
rs = protocol.send_message(xmltodict.unparse(rq)) File
"/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in
send_message return self.transport.send_message(message) File
"/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 173, in
send_message response = self.session.send(prepared_request,
timeout=self.read_timeout_sec) File "/usr/local/lib/python2.7/dist-
packages/requests/sessions.py", line 585, in send r = adapter.send(request,
**kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py",
line 453, in send raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by
peer'))

Much appreciated if anyone could help on this.
##### STEPS TO REPRODUCE

```
win_copy: src=files/snb dest=c:/depot/snb
```

##### EXPECTED RESULTS

The files should be copied to the destination folder on Windows 2008 R2.
The same works on Windows 2012 R2 without any problem.
##### ACTUAL RESULTS

stderr> [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call
last): File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 205, in _winrm_exec
self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
eof=is_last) File "/usr/lib/python2.7/dist-
packages/ansible/plugins/connection/winrm.py", line 186, in _winrm_send_input
rs = protocol.send_message(xmltodict.unparse(rq)) File
"/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in
send_message return self.transport.send_message(message) File
"/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 173, in
send_message response = self.session.send(prepared_request,
timeout=self.read_timeout_sec) File "/usr/local/lib/python2.7/dist-
packages/requests/sessions.py", line 585, in send r = adapter.send(request,
**kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py",
line 479, in send raise ReadTimeout(e, request=request) ReadTimeout:
HTTPSConnectionPool(host='10.20.73.193', port=5986): Read timed out. (read
timeout=30)

```

```

**Comment by jhawkesworth** [comment]
Is the Server 2008 R2 machine fully patched up with windows updates? - there was a bug in the version of Windows Management Framework version 3.0 that comes with S2008R2 that breaks winrm in unpredictable ways - see the blue box in the documentation here: http://docs.ansible.com/ansible/intro_windows.html#windows-system-prep

Personally I'd recommend getting any machines you are managing up to Windows Management Framework version 4.0.

Since this is working for you against other hosts, I suspect the problem is with the windows VM rather than ansible.

Please advise if the kb mentioned in the documentation above has been applied.

**Comment by sbasapure** [comment]
I installed the mentioned KB but still problem persists.
After that I installed Windows Management Framework 4.0 but did not fix the problem.

**Comment by jhawkesworth** [comment]
Ok well other things you can check are

See if your winrm configuration matches your S2012 machine.
You can display the configuration using the following command in a powershell window (running as Administrator)

```
winrm g winrm/config
```

also check the event logs 

also please try installing latest pywinrm (version 0.2.0) from pip.

Also I've noticed that you are connecting via an ip address, please can you try using a hostname (this is preferred for https generally)?

Since it appears from the message it is timing out while waiting to read from the remote machine might be worth checking any firewall configuration (including on the S2008r2 machine itself) to ensure winrm can communicate properly (this is not likely to be worth doing if other modules, such as setup work ok against the S2008r2 machine though).

Hope something from the above helps you to isolate this problem.

**Comment by sbasapure** [comment]
all configuration are exactly the same on all systems and pywinrm 2.0 was already installed. Also verified about firewall configuration and there is no issue as well.

I have also installed Windows management Framework 5.0 on windows 2008 R2 but no use.

Also, tried a fresh build system Windows 2008 R2 with WMF 4.0 / 5.0 and still the problem did not fix.

Only I see difference is winrm id result on Windows 2008 R2 and Windows 2012 R2

**On Windows 2008 R2**

PS C:\Users\SOE-Load.ANSISHANW2K8> winrm id
IdentifyResponse
    ProtocolVersion = http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
    ProductVendor = Microsoft Corporation
    **ProductVersion = OS: 6.1.7601 SP: 1.0 Stack: 3.0**
    SecurityProfiles
        SecurityProfileName = http://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/http/basic, http://schemas.dmtf.org/
wbem/wsman/1/wsman/secprofile/https/basic, http://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/http/spnego-kerberos, h
ttp://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/https/spnego-kerberos

**On Windows 2012 R2**

PS C:\Users\SOE-Load> winrm id
IdentifyResponse
    ProtocolVersion = http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
    ProductVendor = Microsoft Corporation
    **ProductVersion = OS: 6.3.9600 SP: 0.0 Stack: 3.0**
    SecurityProfiles
        SecurityProfileName = http://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/http/basic, http://schemas.dmtf.org/
wbem/wsman/1/wsman/secprofile/https/basic, http://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/http/spnego-kerberos, h
ttp://schemas.dmtf.org/wbem/wsman/1/wsman/secprofile/https/spnego-kerberos

**Comment by sbasapure** [comment]
Also tried with Python 2.7.11 on ansible server but the problem is not fixed.

**Comment by jhawkesworth** [comment]
Can you run any other win_ modules successfully against the affected host?

**Comment by sbasapure** [comment]
Yes absolutly ! 
Actually with win_copy module it copies part of files less than 100 mb files and fails with timeout error as specified in the error.

**Comment by jhawkesworth** [comment]
I'm a bit out of ideas what could be causing this.  

Does it make a difference if you try a different destination on the remote machine?

Might be worth trying older 0.1.1 pywinrm, just because this is a bit more known than pywinrm 0.2.0 which has only just come out.

I wondered if you were hitting a winrm quota limit (see https://msdn.microsoft.com/en-us/library/ee309367(v=vs.85).aspx) but that doesn't make any sense if you have the same config on your 2012 machine.

Personally I don't use win_copy for big files, partly because it wasn't available when I first needed it, and then the first version of win_copy was limited by the capabilities of the winrm connection plugin (which have since been fixed).  I also don't use S2008R2 except for testing modules.  My workaround is to set up a web server for files and then use win_get_url to fetch them.

**Comment by sbasapure** [comment]
jhawkesworth,

Can you please assist me over web conference later today ?
I am willing to setup a call with you and will provide my bridge details to look into the issue closely .

**Comment by jhawkesworth** [comment]
Sorry, just seen this.  I don't really know what help I could be on con call, other than the suggestions I've made above.

Since it is working ok on 2012 machine, I still think it is likely to be an issue on the S2008R2 machine, rather than in ansible.

I suggest you asking on the ansible-project google group, or on the #ansible irc channel in case anyone else has hit this and found a solution - many more people monitor the group and channel than the github issues.

**Comment by sbasapure** [comment]
jhawkesworth,

I have tried on multiple systems of 2008 R2 but the problem is persisting. Would you please test/recreate  it in your environment on Windows 2008 R2 system ?

Also searched on the  groups you suggested but no one has encountered such problem.

**Comment by sbasapure** [comment]
another point - it copies only roughly 100 MB files size on windows 2008 R2  and it fails to copy remaining files. If I re-run the win_copy it copies the remaining files again till 100 mb size of files.

**Comment by jhawkesworth** [comment]
I ran the integration tests for win_copy module yesterday against S2008R2 without a problem, but they won't test a large (100Mb) file.
Since it is working for smaller files, and other modules are working ok, I think some kind of limit is most likely cause.

Searching around I can see others have hit limits with the winrm quotas:
https://sites.google.com/site/softwaretechforge/Downhome/Programminglanguage/issueswithmaxmemorypershellmbinpowershell20and30

You could try the solution posted in the link above 

```
Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 5000
Set-Item WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB 5000
Restart-Service winrm
```

If you need a workaround - I don't actually use win_copy to transfer large files myself - I added a web server to my ansible controllers and then use win_get_url to fetch the files i need onto the windows machines.  I have yet to test whether there is any speed advantage or disadvantage to doing this now that pywinrm 0.2.0 is available, but it was faster before pywinrm 0.2.0 came out.

**Comment by sbasapure** [comment]
Thanks Jhawkesworth for replying to the issue.

Right, I am having the same of more than 100 Mb size of files does not work with Windows 2008 R2 but it works on Windows 2012 R2. This is someohow not getting into me that why it is not supporting on Windows 2008 R2.

I will try the setting you provided on Windows system and let you know shortly.

Regarding win_get_url works only for single file to copy but I have multiple files. How can we fetch multiple files with single task of win_get_url ?

**Comment by sbasapure** [comment]
I tried with the settings as you suggested but failed with the same error.

Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 5000
Set-Item WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB 5000
Restart-Service winrm

**Comment by jhawkesworth** [comment]
Perhaps it is a limitation in the network stack which which has been increased or removed in S2012 R2.  Are you sure there is nothing in the event logs from the time of the failure?

You can use 'with_items' to collect multiple files, something like this (not tested):

```
- name: get multiple files 
  win_get_url: url="{{ download_server }}{{ item }}" dest="{{staging_dir}}{{ item }}" force=no
  with_items:
     - big_file1.zip
     - big_file2.zip
     - big_file3.zip
```

**Comment by sbasapure** [comment]
There is nothing in the System event logs. Do you want me to look into any others logs ?

CSC - This is a PRIVATE message - If you are not the intended recipient, please delete without copying and kindly advise us by e-mail of the mistake in delivery. NOTE: Regardless of content, this e-mail shall not operate to bind the Company to any order or other contract unless pursuant to explicit written agreement or government initiative expressly permitting the use of e-mail for such purpose.

**Comment by jhawkesworth** [comment]
I tend to clear out all the event logs for all types, reproduce the problem then check all the event logs for all types again when dealing with unknowns like this.

**Comment by nitzmahone** [comment]
Hrm, I'm seeing similar behavior on 2008R2 with both pywinrm 0.1.1 and 0.2.0 and with WMF4 and 5. The failure varies between a connection reset or read timeout. It is _much_ flakier with pywinrm 0.1.1 than with the new 0.2.0- the older one fails in random places after just a few megs, where the new one fails pretty reliably at around 113Mib. Interestingly, the problem seems to go away if we switch to HTTP, which makes me think it's a down-deep resource leak or something with a particular SSL/TLS cipher or version that's getting used by requests/urllib3/pyopenssl. I'll tweak around with that and see if I can make it work with a different cipher.

**Comment by nitzmahone** [comment]
Yep, this is definitely an HTTPS cipher/protocol issue- _probably_ server-side, but no way to be sure (sorry, I'm not debugging the OpenSSL + SChannel protocol stacks today). 

I was able to get this working by dorking around with the default protocols on the server. It's difficult to nail down _exactly_ which cipher/protocol is being used (what's surfaced back to Python from native OpenSSL isn't always enough to figure it out). I also had to rebuild python 2.7.11 against a newer OpenSSL.

The negotiated protocol (that breaks at ~113Mib) used from my Mac's Python 2.7.10 + OpenSSL 0.9.8zg and the default Server 2008R2 protocol/cipher suite was DHE-RSA-AES256-SHA on TLSv1/SSLv3 256bit. The same client against an all-defaults Server 2012R2 negotiates to AES256-SHA (same proto/bit length), and that works fine. 

I then used IISCrypto and let it set the "Best Practices" defaults on everything. At that point, the client connects using the same cipher as the default 2012R2, but it still fails the same way (though slightly further in at ~114Mib). Once I built Python 2.7.11 against a newer OpenSSL (1.0.2g), those settings worked fine (and negotiated ECDHE-RSA-AES256-SHA as the cipher). 

So at least for me, it's a combo of the right OpenSSL client, and the right server config... The default stuff seems to blow up regardless for 2008R2.

**Comment by nitzmahone** [comment]
I'm going to close this for now, as there's not really anything we can do up at the Ansible layer to definitively fix a failure at the protocol level.

**Comment by sbasapure** [comment]
Thanks nitzmahone for looking into the issue.

With the above your details, I am still not clear whether you have succeeded to transfer the large files on windows 2008 R2 system using win_copy. 

 I compiled Python 2.7.11 against openssl 1.0.2g and tested win_copy for large files but again it failed with the same error .

Also could you please provide the steps for validating cipher handshake on windows 2008 R2.

**Comment by lgabo** [comment]
Maybe useful for others what I found out:

My Environment:
Windows 7 Professional, Powershell 4.0
Oracle Linux Server release 7.1, ansible-2.1.0.0-0.git201605271344.2452bd2.stable21.el7.centos.noarch, python-2.7.5-34.0.1.el7.x86_64

I wanted to win_copy a file about 140MB to windows machine, the win_copy made always 445 PUTs x 250000 bytes then stucked which ended after DEFAULT_READ_TIMEOUT_SEC. So I tried to play with the buffer_size 250000, but then I came to that if I increase the buffer_size then the MaxEnvelopeSizekb of winrm has to be increased too. So after some tries I was able win_copy the file form linux to windows with this change:
I increased the winrm MaxEnvelopeSizekb to 1024 in windows:
winrm set winrm/config @{MaxEnvelopeSizekb="1024"}
then I replaced the buffer_size=250000 param of _put_file_stdin_iterator method in /usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py to buffer_size=320000

**Comment by jhawkesworth** [comment]
Thanks @lgabo for your analysis.
I'm going to re-open this as I'm not sure if @nitzmahone would see this issue in closed state, just for info.
It might be that the remoting setup script could be tweaked (optionally) to increase max envelope size and likewise the buffer size in winrm.py changed.  However I've not dug into this nearly as much as @nitzmahone so not sure of the implications of upping these values.

**Comment by nitzmahone** [comment]
IIRC from my own messings around with this, adjusting the envelope size + buffer size just kinda moves the problem around (changes the failure mode)- it's ultimately an issue down at the SSL protocol level. We've got it happening on OSX, Ubuntu and RHEL-flavored control systems. I'd be curious to try it with a Python built against LIbreSSL instead of OpenSSL (since OpenSSL is still the common denominator across all those systems).

**Comment by jhawkesworth** [comment]
Fair enough, since its protocol level and there are a couple of workarounds (tweak envelope/buffer or win_get_url instead of win_copy) it seems like there's not much point  in having this as an open bug.

**Comment by nitzmahone** [comment]
If we can definitively show it's the Windows side that's getting wedged (eg, if we can get it to fail the same way with LibreSSL too), we can file a bug on it with Microsoft, though it may not help much for most of the world...

**Comment by nitzmahone** [comment]
Closing this, as there's not really anything we can do about it directly.

**Comment by sayalip17** [comment]
Hi, I am facing a problem in win_copy module. though the playbook status says OK, the files are not getting copied.

-vvv says :
<ec2-54-226-198-121.compute-1.amazonaws.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO ec2-54-226-198-121.compute-1.amazonaws.com
<ec2-54-226-198-121.compute-1.amazonaws.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1489753490.4-160983667761863").FullName | Write-Host -Separator '';
<ec2-54-226-198-121.compute-1.amazonaws.com> EXEC Set-StrictMode -Version Latest
Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1489753490.4-160983667761863" -Force -Recurse;
ok: [ec2-54-226-198-121.compute-1.amazonaws.com] => {
    "changed": false,
    "dest": "'C:\\Java'",
    "invocation": {
        "module_args": {
            "dest": "C:\\Java",
            "force": "yes",
            "src": "/root/bin/wntx64/JDK/jdk1.7.0_45",
            "state": "created"
        },
        "module_name": "win_copy"
    },
    "src": "/root/bin/wntx64/JDK/jdk1.7.0_45"
}

**Comment by jctanner** [comment]
@sayalip17 please open a new issue.

**Comment by mabrarov** [comment]
We use:

```
$ ansible --version
ansible 2.4.2.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
```

and 

```
$ ansible-playbook --version
ansible-playbook 2.4.2.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
```

and

```
$ openssl version
OpenSSL 1.0.2n  7 Dec 2017
```

We faced the same issue on Windows Server 2008 R2 SP1 configured according to "[Windows System Prep](http://docs.ansible.com/ansible/latest/intro_windows.html#windows-system-prep)" document.

Recently we applied "best practices" provided by [IIS Crypto](https://www.nartac.com/Products/IISCrypto/Download) utility on target host (Windows Server 2008 R2 SP1) and **that solved our issue with copying of (~large) files** like:

```
$ ls -l ../media
-rw-r--r--. 1 root root 268027845 Dec 22 14:13 jboss-eap-dist-7.0.3.zip
-rwxrwx---. 1 user user  72209721 Dec 20 21:01 payment-gateway-ear-jboss-config-8.7.0.0.zip
```

**Comment by chenwenwen1988** [comment]
I met the same problem and fund a  solution in this web, https://support.huaweicloud.com/usermanual-deployman/deployman_hlp_00027.html, execute the step 8 and step 9.
