### ISSUE TITLE
Ansible pear extras module does not allow responding to prompts interactively or via playbook options

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#16309]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /home/jstewart/local/ansible-deploy-scooby/ansible.cfg
  configured module search path = /usr/share/ansible:./library
```
##### CONFIGURATION

[defaults]

hostfile       = $HOME/local/ansible-deploy-scooby/hosts
library        = /usr/share/ansible:./library
remote_tmp     = $HOME/local/ansible-deploy-scooby/tmp
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root
transport      = smart
module_lang    = C
gathering = implicit
roles_path    = $HOME/local/ansible-deploy-scooby/roles
retry_files_save_path = $HOME/local/ansible-deploy-scooby/retry
host_key_checking = True
sudo_exe = sudo
timeout = 10
log_path = $HOME/local/ansible-deploy-scooby/log/ansible.log
executable = /bin/sh
ansible_shell_type = sh
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
deprecation_warnings = False
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins

[paramiko_connection]

[ssh_connection]

scp_if_ssh=True

[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 30
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.8 (Santiago)
Linux XXX 2.6.32-642.1.1.el6.x86_64 #1 SMP Fri May 6 14:54:05 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

pear: name=pecl/oci8-2.0.11 state=present hangs indefinitely waiting for the prompts it normally gets when you shell out to "pecl install oci8-2.0.11", yet doesn't give you any options to answer prompts.
##### STEPS TO REPRODUCE

pear: name=pecl/oci8-2.0.11 state=present

```
pear: name=pecl/oci8-2.0.11 state=present
```

##### EXPECTED RESULTS

I expected it to either give me a way to auto-answer prompts, or present me with the prompts so I can respond to them.
##### ACTUAL RESULTS

It hung forever.

```
No output, because the task never completed, and sat forever.
```

**Comment by nitzmahone** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
