### ISSUE TITLE
register assigned even when skipping task

### ISSUE THREAD

**Issue by cowst** [ansible/ansible#16324]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Source and destination CentOS 7.1
##### SUMMARY

When registering a variable conditionally, it is registered even when skipping the task.
##### STEPS TO REPRODUCE

```
- name: check if data directory exists
  stat: path=/var/lib/pgsql9/data
  register: data_dir
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'

- name: check if data directory exists
  stat: path=/var/lib/pgsql/9.2/data
  register: data_dir
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- name: print data_dir
  debug: msg="{{ data_dir }}"
```
##### EXPECTED RESULTS

data_dir should contain the first path
##### ACTUAL RESULTS

the skipping message of second check is printed:

```
"msg": {
  "changed": false, 
  "skip_reason": "Conditional check failed", 
  "skipped": true
}
```

**Comment by sivel** [comment]
This is the expected behavior. Registering even when skipping allows a user to use that registered var later to determine if the previous task had been skipped.

You should not try to register the same car twice, but instead register 2 different vars.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
