### ISSUE TITLE
mount module does not act as documented

### ISSUE THREAD

**Issue by sza-1** [ansible/ansible#16323]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default configuration.
##### OS / ENVIRONMENT

Arch Linux
##### SUMMARY

Documentation (http://docs.ansible.com/ansible/mount_module.html) for mount module says that fstype and src options are required when state=present or state=mounted. So I do not need to specify fstype and src when I just wish to unmount device.

But when I try task `mount: name=/mnt state=unmounted` ansible says `fatal: [192.168.122.88]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"fstab": "/etc/fstab", "name": "/mnt", "state": "unmounted"}, "module_name": "mount"}, "msg": "missing required arguments: src,fstype"}`

Workaround: pass empty fstype and src. E.g.: `mount fstype='' name=/mnt src='' state=unmounted`.
##### STEPS TO REPRODUCE

Write a simple playbook and task:

```

---

- hosts: all
  tasks:
    - name: x
      mount: name=/mnt state=unmounted
```
##### EXPECTED RESULTS

mount should unmount /mnt w/o errors
##### ACTUAL RESULTS

mount module failed because I missed fstype and src.

```

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [192.168.122.88]

TASK [x] ***********************************************************************
fatal: [192.168.122.88]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: src,fstype"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @untitled.retry

PLAY RECAP *********************************************************************
192.168.122.88             : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
