### ISSUE TITLE
unarchive inexplicit error message when unarchive fails

### ISSUE THREAD

**Issue by mlogic** [ansible/ansible#16337]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f4724e55d3) last updated 2016/06/16 16:02:26 (GMT -700)
```
##### CONFIGURATION

No change.
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

I have a host that doesn't have bzip2 installed, so when unarchive tries to unarchive a tar.bz2 package it fails. But the problem is ansible's output doesn't point to the real problem, but instead it is:

```
{"msg": "path /tmp/boost/boost_1_61_0 does not exist", "path": "/tmp/boost/boost_1_61_0", "state": "absent", "failed": true, "invocation": {"module_args": {"directory_mode": null, "force": null, "remote_src": null, "exclude": [], "owner": null, "follow": false, "group": null, "keep_newer": false, "serole": null, "content": null, "setype": null, "extra_opts": [], "dest": "/tmp/boost", "selevel": null, "original_basename": "boost_1_61_0.tar.bz2", "regexp": null, "copy": false, "src": "/tmp/boost/boost_1_61_0.tar.bz2", "validate_certs": true, "list_files": false, "seuser": null, "creates": null, "delimiter": null, "mode": null, "backup": null}}}
```

The msg above was produced by:

```
  File "/home/sophie/.ansible/tmp/ansible-tmp-1466134264.4-238242862932694/debug_dir/ansible_module_unarchive.py", line 801, in <module>
    main()
  File "/home/sophie/.ansible/tmp/ansible-tmp-1466134264.4-238242862932694/debug_dir/ansible_module_unarchive.py", line 787, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/home/sophie/.ansible/tmp/ansible-tmp-1466134264.4-238242862932694/debug_dir/ansible/module_utils/basic.py", line 1131, in set_fs_attributes_if_different
    file_args['path'], file_args['secontext'], changed, diff
  File "/home/sophie/.ansible/tmp/ansible-tmp-1466134264.4-238242862932694/debug_dir/ansible/module_utils/basic.py", line 860, in set_context_if_different
    cur_context = self.selinux_context(path)
  File "/home/sophie/.ansible/tmp/ansible-tmp-1466134264.4-238242862932694/debug_dir/ansible/module_utils/basic.py", line 803, in selinux_context
    traceback.print_stack()
```
##### STEPS TO REPRODUCE

Temporarily move away the bzip2 package or binary from a Linux system, then try to unarchive a .tar.bz2 package.
##### EXPECTED RESULTS

unarchive should explicitly complaints about the failure of unarchiving.
##### ACTUAL RESULTS

A mysterious msg is shown. It took my a whole afternoon to figure out the root cause.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
