### ISSUE TITLE
Unable to login using sudo account

### ISSUE THREAD

**Issue by prakashgula** [ansible/ansible#16334]
##### Issue Type:
- Bug Report

I am trying to SSH to server then sudo to particular account where i need to run few simple shell commands.
##### Ansible Version:

$ ansible --version
ansible 2.0.1.0
##### Ansible Configuration:

```
$ cat ansible.cfg 
[default]
hostfile = ansible_hosts
remote_user = sshaccount
host_key_checking = True
```

```
$ cat playbook.yml
- name: Sample playbook
  hosts: myhosts
  remote_user: sudoaccount
  become: yes
  become_user: sudoaccount
  become_method: 'sudo'
  tasks:
    - name: List of files/directories
      shell: ls -lt
      register: dirlist
    - debug: var=dirlist.stdout
    - debug: var=dirlist.stderr
```
##### Environment:

Running from OSX 10.11.2, ansible installed via home-brew
Target OS : RHEL
##### STEPS TO REPRODUCE

I am trying to SSH to particular host then do sudo to another account. While running ansible i am seeing prompt for both SSH as well as SUDO passwords but unfortunately shell commands are executing on SSH account rather than on sudo account.

```
$ ansible-playbook playbook.yml -i ansible_hosts --ask-pass --ask-become-pass
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [Sample playbook] *********************************************************

TASK [setup] *******************************************************************
ok: [xx.xx.xx.xx]

TASK [List of files/directories] ***********************************************
changed: [xx.xx.xx.xx]
```
##### EXPECTED RESULTS

Shell commands should run on sudo account.
##### ACTUAL RESULTS

shell commands are executing in SSH account.

Anything i am missing to add here which is required for sudo account to be used.

**Comment by sivel** [comment]
Your example does not align with your description.  You state you are trying to ssh as one user and then sudo to another, however your example shows logging in as `sudoaccount` and trying to sudo to `sudoaccount`:

```
  remote_user: sudoaccount
  become: yes
  become_user: sudoaccount
  become_method: 'sudo'
```

Logging into and sudoing to the same account will do nothing, other than run the command as the user you log in with.  Do you mean to sudo to the root user?  If so use `become_user: root`, or omit that, since `root` is the default.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by prakashgula** [comment]
My bad, its typo. Sorry for the confusion. I am trying to do SSH to one account then SUDO to another account. 
  remote_user: sshaccount
  become: yes
  become_user: sudoaccount
  become_method: 'sudo'

I tried using the following also for sudo account details in ansible.cfg but that didn't help.
[default]
hostfile = ansible_hosts
remote_user = sshaccount
host_key_checking = True
become_user: sudoaccount

Any other thoughts ?
