### ISSUE TITLE
How to get the result from ansible python api

### ISSUE THREAD

**Issue by you-n-g** [ansible/ansible#16341]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

ubuntu 14.04
##### SUMMARY

I don't know how to get the  result from ansible python api.
##### STEPS TO REPRODUCE

I'm following this page http://docs.ansible.com/ansible/developing_api.html 
I replace the tasks with this.

```
tasks = [{"action": "setup", "register": "setup_res"},{u'debug': u'var=setup_res'}]
```

I can get the result in stdout.

```
ok: [test-win1] => {
    "setup_res": {
        "ansible_facts": {
            "ansible_architecture": "64 位",
            "ansible_date_time": {
                "date": "2016/6/17",
……
            "ansible_os_family": "Windows",
            "ansible_os_name": "Microsoft Windows 10 Pro",
            "ansible_powershell_version": 5,
            "ansible_system": "Win32NT",
            "ansible_totalmem": 8534650880,
            "ansible_uptime_seconds": 49261,
            "ansible_winrm_certificate_expires": "2017-05-11 23:37:18"
        },
        "changed": false
    }
}
```

But I don't know how to get the data with python api.
##### EXPECTED RESULTS

I read the code and found the result returned here (https://github.com/ansible/ansible/blob/stable-2.1/lib/ansible/executor/task_executor.py#L552)  is exactly what I want !!!
##### ACTUAL RESULTS

I can't figure out  how to get the result.

Thanks in advance. I don't know how to use the apis.

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by you-n-g** [comment]
Thanks !
I'll follow https://github.com/sivel/ansible/commit/eab10b2402da4adb038cf88ebac089e6e2183839 and try it  :)
