### ISSUE TITLE
until loop never fails when retries set to 1

### ISSUE THREAD

**Issue by ansafonov** [ansible/ansible#16408]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### SUMMARY

until loop never fails when retries set to 1
##### STEPS TO REPRODUCE

```
cat playbooks/1
- name: test until
  hosts: localhost
  tasks:
    - name: checking output
      debug: msg='testing'
      until: false
      retries: 1

cat playbooks/2
- name: test until
  hosts: localhost
  tasks:
    - name: checking output
      debug: msg='testing'
      until: false
      retries: 2

ansible-playbook playbooks/1
ansible-playbook playbooks/2
```
##### EXPECTED RESULTS

ansible runs command once and fails with an error
##### ACTUAL RESULTS

ansible succeeds silently 

```
ansible-playbook playbooks/1

PLAY [test until] **************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [checking output] *********************************************************
ok: [localhost] => {
    "msg": "testing"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

ansible-playbook playbooks/2

PLAY [test until] **************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [checking output] *********************************************************
FAILED - RETRYING: TASK: checking output (1 retries left).Result was: {
    "attempts": 1,
    "msg": "testing",
    "retries": 2
}
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "testing"
}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @playbooks/2.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by abadger** [comment]
Verified that this is working in stable-2.1 so it's a change introduced during devel.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release (2.1.1).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ansafonov** [comment]
Thanks

**Comment by Gourds** [comment]
NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @playbooks/ssy/dbservers/dbservers.retry

PLAY RECAP *********************************************************************
ssy-db1                    : ok=5    changed=1    unreachable=0    failed=1  
ssy-db2                    : ok=5    changed=1    unreachable=0    failed=1   

[root@ssy-thrift1 ops-repo]# ansible --version
ansible 2.1.1.0
  config file = /data/ps/ops-repo/ansible.cfg
  configured module search path = Default w/o overrides

---

This is V2.1.1.0 always have the problem
