### ISSUE TITLE
Fact caching also caches ansible_date_time

### ISSUE THREAD

**Issue by alform** [ansible/ansible#16412]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel afc82f6beb) last updated 2016/03/25 09:49:26 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 7efc09ef08) last updated 2016/03/25 09:50:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7f9cdc0350) last updated 2016/03/25 09:52:02 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

# activate fact caching

gathering = smart
fact_caching = jsonfile
fact_caching_connection = /etc/ansible/fact_cache
fact_caching_timeout = 86400
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When fact caching is active,   ansible_date_time is also cached. This leads to issues for modules and playbooks using this timestamp as marker for backups (i.e. in file extensions).
##### STEPS TO REPRODUCE

Activate fact checking, run the commands below.
Also, check the ansible_date_time value used is the same as cached in the fact cache. (NB: my timezone is two hours ahead of GMT (so the hour is correct), but note the minutes)

```
[root@monitor ansible]# ansible localhost -a 'touch /tmp/test.{{ ansible_date_time.iso8601 }}'
localhost | SUCCESS | rc=0 >>
[root@monitor ansible]# ls /tmp/test.*
/tmp/test.2016-06-23T11:43:45Z
[root@monitor ansible]# date
Thu Jun 23 13:58:08 CEST 2016
[root@monitor ansible]# 

```

##### EXPECTED RESULTS

The correct time on remote host should be used. All the time/date dependent variables should also get their correct current value (rather then the cached one). 
##### ACTUAL RESULTS

The time of the last caching was used

```

```

**Comment by abadger** [comment]
ansible_date_time is a fact gathered from the remote host so fact caching means that it won't be updated.  Having ansible_date_time refresh would require the date and time to be gathered separately from other facts and then additionally marking ansible_date_time as a fact that must always be gathered.

Note that ansible_date_time will never be the current time on the remote system.  Even without fact cahing on, it is still the time that the playbook executed fact gathering (usually the very first implicit task in a playbook run) rather than the time that the specific task is executed.

With all that in mind, it's probably best for you to take your specific use case to the mailing list or IRC instead of this bug report.  It's likely that either other people are operating under similar constraints as you and have worked out some best practices for achieving what you want or that talking about how your use case differs will lead to a feature request can be implemented without redesigning the basic architecture of fact gathering to solve your problem.  I'll go ahead and close this and paste information on contacting the mailing list and IRC channel below.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by dagwieers** [comment]
We actually use the cached ansible_date_time to find out how old the cached facts are (as a means to know what we are working with). We use this as part of collecting system facts and reporting facts-changes (in a log) and keeping an inventory (CSV) of all important system facts. So changing this behaviour would have an impact.
