### ISSUE TITLE
ini_file module don't understand tab character as delimiter

### ISSUE THREAD

**Issue by kazh000** [ansible/ansible#16417]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

Debian GNU/Linux 8 (jessie)
##### SUMMARY

If INI file contains TAB chars than the ini_file module decides that TAB chars is part of option name.
##### STEPS TO REPRODUCE

MariaDB config file /etc/mysql/my.cnf contains TAB chars:
$> grep bind-address /etc/mysql/my.cnf
`bind-address           = 127.0.0.1`
Line contains: "bind-address\t\t= 127.0.0.1"
source file "**ini_file.py**" uses "_re.match('%s *=' % option, line)_" for searching option name and use only space as delimiter char. But Mysql/MariaDB (probably other too) config file uses TAB also.

```
# don't work
ini_file: dest=/etc/mysql/my.cnf section='mysqld' option='bind-address' state=absent
# but it works (option contains two TABs)
ini_file: dest=/etc/mysql/my.cnf section='mysqld' option='bind-address                ' state=absent
```

##### ACTUAL RESULTS

```

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
