### ISSUE TITLE
osx_defaults does not allow reading values

### ISSUE THREAD

**Issue by wizonesolutions** [ansible/ansible#16455]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/kevin/wizardbox/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat ansible.cfg
[defaults]
roles_path = ./data/ansible/roles
```
##### OS / ENVIRONMENT

OS X, locally
##### SUMMARY

http://docs.ansible.com/ansible/osx_defaults_module.html says that the module can be used to read from defaults, but it can't. It can only write and update. There are no read examples, and `value` is required when `state=present`.
##### STEPS TO REPRODUCE

N/A

```
- name: check if spelling correction is enabled
  osx_defaults: key={{ item }}
  with_items:
    - NSAutomaticSpellingCorrectionEnabled
    - WebAutomaticSpellingCorrectionEnabled
  register: spelling_status
```
##### EXPECTED RESULTS

The defaults to be registered into a variable.
##### ACTUAL RESULTS

```
TASK [check if spelling correction is enabled] *********************************
failed: [localhost] (item=NSAutomaticSpellingCorrectionEnabled) => {"failed": true, "item": "NSAutomaticSpellingCorrectionEnabled", "msg": "Missing value parameter"}
failed: [localhost] (item=WebAutomaticSpellingCorrectionEnabled) => {"failed": true, "item": "WebAutomaticSpellingCorrectionEnabled", "msg": "Missing value parameter"}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
