### ISSUE TITLE
Error when creates port on bridge use `openvswitch_port` module

### ISSUE THREAD

**Issue by kinhvan017** [ansible/ansible#16450]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /data/playbooks/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Error when creates port on bridge
##### STEPS TO REPRODUCE

```
- name: Add vmnet-if to br-prv
  openvswitch_port: bridge=br-prv port=p1p2 state=present
```

##### EXPECTED RESULTS

```

```
##### ACTUAL RESULTS

```
fatal: [nova-compute]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"bridge": "br-prv", "external_ids": "{}", "port": "p1p2", "set": null, "state": "present", "timeout": 5}, "module_name": "openvswitch_port"}, "msg": "'str' object has no attribute 'items'"}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
