### ISSUE TITLE
Expect module silently kills tasks after timeout is exceeded even if all questions were answered

### ISSUE THREAD

**Issue by ergo** [ansible/ansible#16461]
- Bug Report

```
2.1.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

It turns out that tasks fail after default (30s) timeout is reached even if all the questions 
were already handled by "expect" module.
##### STEPS TO REPRODUCE
1. run a task that requires "answers"
2. the task should run longer than default timeout
3. task if marked as failed without any apparent reason

this fails for me after a while:

```
- name: install App
  become_user: foo
  expect:
    command: foo bar baz
    responses:
      (?i)license: y
```

this works properly till the end:

```
- name: install App
  become_user: foo
  expect:
    command: foo bar baz
    responses:
      (?i)license: y
    timeout: 600
```

Example error

```
fatal: [172.16.115.209]: FAILED! => {"changed": true, "cmd": "/home/rcdev/.rccontrol-profile/bin/rccontrol install VCSServer host:127.0.0.1 port:10001", "delta": "0:00:30.589820", "end": "2016-06-27 15:33:23.161709", "failed": true, "invocation": {"module_args": {"chdir": null, "command": "/home/rcdev/.rccontrol-profile/bin/rccontrol install VCSServer host:127.0.0.1 port:10001", "creates": null, "echo": false, "removes": null, "responses": {"(?i)license": "y"}, "timeout": 30}, "module_name": "expect"}, "rc": null, "start": "2016-06-27 15:32:52.571889", "stdout": "Do you accept the REDACTED \r\nDownloading ....tar.bz2 ...", "stdout_lines": ["Do you accept ..."]}
```

**Comment by sivel** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
