### ISSUE TITLE
Inconsistent handler execution in multiple Ansible versions

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#16469]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
Ansible devel, Ansible stable-2.1, Ansible stable-2.0
```
##### CONFIGURATION

No modification in configuration
##### OS / ENVIRONMENT

Debian Jessie
##### SUMMARY

Handler behaviour has changed between Ansible stable-2.0 and current devel to the point where their behaviour differs depending on if the role is called directly from a playbook or through role dependency. On the current devel, handlers from dependent roles are not executed at all.
##### STEPS TO REPRODUCE

I've created [an example playbook with roles](https://github.com/drybjed/ansible-depend-handler-test) which can be used to test the issue. The README file contains output of different Ansible versions.

##### EXPECTED RESULTS

The execution of handlers is consistent no matter how the roles that use them are called. All handlers notified in current play are executed in order they were written in the playbook.
##### ACTUAL RESULTS

See the README file mentioned above.

**Comment by jctanner** [comment]
git bisect blames this commit: https://github.com/ansible/ansible/commit/ca6ee4c78980707a6ff83176d0e019a9b0ef052f

**Comment by jctanner** [comment]
@jimi-c can you take a look at this?

**Comment by jimi-c** [comment]
930d0905074ccf6537d0ecf14259a7da6a9559fb should address at least some of this, though I still need to test against the example repo provided.

**Comment by jimi-c** [comment]
# Closing This Ticket

After testing with the example playbook given (both on devel and stable-2.1), I believe this issue has been resolved by the above commit.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
