### ISSUE TITLE
htpasswd logs users password in log

### ISSUE THREAD

**Issue by jmcollin78** [ansible/ansible#16473]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 1.7.2

```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

$ uname -a
Linux xxxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
##### SUMMARY

When using the htpasswd feature, the password are displayed in output logs.
##### STEPS TO REPRODUCE

My configuration is the following:

```
- name: Install Basic Auth authentication file
  htpasswd: path=/etc/nginx/conf.d/htpasswd create=yes name={{item.login}} password={{item.password}} state=present
  with_items: pio_basic_auth.users
  when: pio_basic_auth is defined
  notify: reload nginx
```

I try to add `no_log: true` but without success.
The output is the following:

```
TASK: [etg-pio-deploy | Install Basic Auth authentication file] *************** 
ok: [etg-pio-tmp] => (item={'login': 'user1', 'password': 'user1Pwd'}) => {"changed": false, "item": {"login": "user1", "password": "user1Pwd"}, "msg": "user1 already present"}
idem for all users.
```
##### EXPECTED RESULTS

The password (ie. user1Pwd in example) is not displayed in output log

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by jmcollin78** [comment]
OK -> https://github.com/ansible/ansible-modules-core/issues/4058
