### ISSUE TITLE
any_errors_fatal: True ignored when some hosts are unreachable

### ISSUE THREAD

**Issue by vbichov** [ansible/ansible#16475]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

ansible 2.0.2.0
  config file = /**/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

[defaults]
host_key_checking=false
remote_tmp = /tmp
log_path=./ansible.log
forks=20
timeout = 30
hash_behaviour=merge

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=180s -o ServerAliveInterval=30
##### OS / ENVIRONMENT

python --version
Python 2.7.11

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.3 (Santiago)
##### SUMMARY

any_errors_fatal: True in playbooks is ignored when some hosts are unreachable.
The same works when all host are reachable
##### STEPS TO REPRODUCE

reproducer.yaml:

```

---

- hosts: all
  tasks:
   - action: ping


- hosts: all
  any_errors_fatal: True
  tasks:
   - fail: msg="failing now!!"


- hosts: all
  tasks:
   - debug: msg="should not reach here"
```

inventory:

```
[all]
unreachable_host
localhost
```

run the following command:

```
ansible-playbook reporoducer.yaml -i some_inventory
```
##### EXPECTED RESULTS

the playbook shouldn't reach the debug message
##### ACTUAL RESULTS

```

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [unreachable_host]: UNREACHABLE! => {"changed": false, "msg": "[Errno -2] Name or service not known", "unreachable": true}
ok: [localhost]

TASK [ping] ********************************************************************
ok: [localhost]

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failing now!!"}

NO MORE HOSTS LEFT *************************************************************

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "should not reach here"
}
        to retry, use: --limit @reporoducer.retry

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1
unreachable_host           : ok=0    changed=0    unreachable=1    failed=0


```

**Comment by jctanner** [comment]
Hi!

We believe recent commits (v2.1.1.0-0.1.rc1) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
