### ISSUE TITLE
docker_container module fails when used with check mode

### ISSUE THREAD

**Issue by WishCow** [ansible/ansible#16543]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

docker-py (1.8.1)
```
##### OS / ENVIRONMENT

Arch linux, both control and target
##### SUMMARY

Using the docker_container module with check mode results in an error coming from docker-py. Leaving out the check mode flag, everything works fine.
##### STEPS TO REPRODUCE

```
ansible localhost  -c local -m docker_container -C -a "name=ansible-test image=alpine command=id"
```

##### EXPECTED RESULTS

Ansible should report if the container is running with the given configuration
##### ACTUAL RESULTS

```
  [WARNING]: Host file not found: /etc/ansible/hosts

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get'
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1641, in <module>\n    main()\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1634, in main\n    cm = ContainerManager(client)\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1345, in __init__\n    self.present(state)\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1371, in present\n    container = self.update_limits(container)\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1450, in update_limits\n    limits_differ, different_limits = container.has_different_resource_limits()\n  File \"/tmp/ansible_EWLrLk/ansible_module_docker_container.py\", line 1113, in has_different_resource_limits\n    if not self.container.get('HostConfig'):\nAttributeError: 'NoneType' object has no attribute 'get'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

Better formatted traceback:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1641, in <module>
    main()
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1634, in main
    cm = ContainerManager(client)
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1345, in __init__
    self.present(state)
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1371, in present
    container = self.update_limits(container)
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1450, in update_limits
    limits_differ, different_limits = container.has_different_resource_limits()
  File "/tmp/ansible_YdX_s3/ansible_module_docker_container.py", line 1113, in has_different_resource_limits
    if not self.container.get('HostConfig'):
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
