### ISSUE TITLE
delegate_to: 127.0.0.1 fails on random hosts as UNREACHABLE

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#16568]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (stable-2.1 05536b3be5) last updated 2016/06/21 10:16:57 (GMT +200)
```
##### CONFIGURATION

Nothing special
##### OS / ENVIRONMENT

CentOS 6
##### SUMMARY

On `stable-2.1` branch tasks which use `delegate_to: 127.0.0.1` fail on random hosts with:

```
fatal: [host-85]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

**Note:** `delegate_to: localhost` works without a problem and on 1.9 both work without a problem.

I would also like to mention that our inventory doesn't have `localhost` nor `127.0.0.1` defined in it, so that shouldn't be the case.
##### STEPS TO REPRODUCE

Run the following playbook with at least 10 hosts in it, but the more hosts you have, it will fail easier on more of them:

```

---
- hosts: group_of_at_least_10_hosts
  gather_facts: no
  tasks:
    - stat: path=/etc/passwd
      delegate_to: 127.0.0.1
```
##### EXPECTED RESULTS

It should finish without a problem.
##### ACTUAL RESULTS

It fails on random hosts with:

```
fatal: [host-11]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

```

A different hosts fails almost every time.

**Comment by abadger** [comment]
The need for 10 connections is likely because of MaxSessions in /etc/ssh/sshd_config.  But that's kind of a tangent to this bug in Ansible.  If we run on a host where localhost can't ssh to itself, I think we'll find that it occurs with just a single host.  Running ansible-playbook -vvv we can see that in the initial release of 2.1.0 we used the local connection type to connect to 127.0.0.1 when we delegate_to it.  In the current HEAD of stable-2.1 we're making an ssh connection to it instead.  That's the root of the problem....

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
