### ISSUE TITLE
In extra vars  in json format List of string are casted as List for Lists

### ISSUE THREAD

**Issue by jbelafa** [ansible/ansible#16583]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
 2.1.0.0
```
##### STEPS TO REPRODUCE

```
In the beginning of the playbook 
- hosts: '{{ targets }}'

in the command line I have 
ansible-playbook -i dyna-inventory.py  -e '{"foo": "bar", "targets": ["ec2-XXXXXXX.eu-west-1.compute.amazonaws.com"]}' myplaybook.yml 

To mention that this is working since 1.9.X and the only modification is a ansible upgrade

```

##### EXPECTED RESULTS

nothing but my playbook running 
##### ACTUAL RESULTS

It's like there is a modification on the way  variables are casted when doing 
host = '{{ targets }}'
while my json definition specifies a string list  in targets 

```
ERROR! the field 'hosts' should be a list of (<type 'basestring'>,), but the item '[u'ec2-xxxxxxx-eu-west-1.compute.amazonaws.com']' is a <type 'list'>
```

**Comment by nitzmahone** [comment]
I've verified that this works without Jinja2 in the mix,  eg:

```
- hosts:
  - host1
  - host2
```

I see where the underlying problem is between early validation, templating, and post-validation, and I see a way to fix it, but it'll require a fundamental change to our attribute processor/validator that we'd probably want to beat the crap out of in testing. The problem is that we're already typing the pre-templated hosts variable as a list of string (containing a single value `{{ targets }}`), then we're expanding targets in place, leading to the list-of-lists behavior (which causes the later validation error).

We'd probably want to add an opt-in "flatten" behavior to our FieldAttribute stuff that would detect this and do the right thing on attributes we _know_ aren't hierarchical like `hosts` (rather than doing it blindly to everything). 

As a workaround for this, you can pass a colon-separated list of hosts and it should work, eg:

```
ansible-playbook -i dyna-inventory.py  -e '{"foo": "bar", "targets": "ec2-XXXXXXX.eu-west-1.compute.amazonaws.com:someotherhost"}' myplaybook.yml 
```

**Comment by abadger** [comment]
Fix has been pushed to devel and should be in the 2.2.0 release (We're getting ready for the first release candidate for 2.2 now).
