### ISSUE TITLE
wait_for fails on apt-get / aptitude lock-file in /var/lib/dpkg/lock

### ISSUE THREAD

**Issue by jhit** [ansible/ansible#16593]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

bento/ubuntu16.04 Virtualbox
##### SUMMARY

My rule:

```
- name: Wait for automatic system updates
  become: yes
  wait_for: path=/var/lib/dpkg/lock state=absent
```

will wait until ist timeouts with a error. the lockfile is never removed but only emptied.
on shell this works for me:

```
while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
    sleep 1;
done
```

unfortunatele ansibles wait_for fails here.
##### STEPS TO REPRODUCE

boot up a bento/ubuntu16.04 virtualbox image and insert as first task/rule the code below.
ubuntu 1604 runs a system update in background on (first) boot, that will lock /var/lib/dpkg/lock for some seconds up to a minute.  

```
- name: Wait for automatic system updates
  become: yes
  wait_for: path=/var/lib/dpkg/lock state=absent
```

##### EXPECTED RESULTS

I would expect wait_for can handle the lock file of apt.
##### ACTUAL RESULTS

```
TASK [common : Wait for automatic system updates] ******************************
==> default: fatal: [33.33.33.20]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for /var/lib/dpkg/lock to be absent."}
==> default:
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by lvh** [comment]
It doesn't look like this new ticket was ever filed. Perhaps instead of closing the issue, we should be filing the issue elsewhere and then closing the issue?

**Comment by jhit** [comment]
I indeed did a follow up in ansible-modules-core:
https://github.com/ansible/ansible-modules-core/issues/4241
Closing is ok. This problem already is taken care of.
See:
https://github.com/ansible/ansible-modules-core/pull/4842

**Comment by lvh** [comment]
Awesome, thanks!

**Comment by nyetwurk** [comment]
I had to do something like this, since sometimes `lock-frontend` is held but `lock` isn't
```
- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
  with_items:
    - lock
    - lock-frontend
```
Note that this workaround is still race prone, since if another apt starts between this and the upcoming ansible apt, the ansible apt one will still fail.
