### ISSUE TITLE
lineinfile duplicates lines with regexp containing quantifiers

### ISSUE THREAD

**Issue by skoval00** [ansible/ansible#16596]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/remedy/scenter-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
ask_vault_pass=False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

lineinfile module creates duplicate lines on the second and subsequent runs if its regexp arg contains quantifiers (+, \* etc.)
##### STEPS TO REPRODUCE

On the first run this task replaces `SELINUX=  #` with `SELINUX=enforcing`

```
- lineinfile: dest=/etc/selinux/config regexp='^SELINUX=\s+#' line=SELINUX=enforcing
```

On the subsequent runs this task creates duplicate lines `SELINUX=enforcing`
##### EXPECTED RESULTS

```
SELINUX=enforcing
```
##### ACTUAL RESULTS

```
SELINUX=enforcing
SELINUX=enforcing
...
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by skoval00** [comment]
This bug was already reported https://github.com/ansible/ansible-modules-core/issues/3975
