### ISSUE TITLE
Timezone documentation buggy

### ISSUE THREAD

**Issue by minac** [ansible/ansible#16624]
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

n/a
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

Page https://docs.ansible.com/ansible/timezone_module.html is unformatted and a bit confusing.
##### STEPS TO REPRODUCE

Go here: https://docs.ansible.com/ansible/timezone_module.html and look at the right hand side of the table where the footer seems to be.
##### EXPECTED RESULTS

Usual documentation.
##### ACTUAL RESULTS

Misconfigured documentation

**Comment by nateprewitt** [comment]
It looks like this is being caused by the | character in the description documentation. I've opened a PR to remove it which should fix the issue.

**Comment by minac** [comment]
Awesome.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
