### ISSUE TITLE
Ansible ec2 module can not launch instance  at AWS ap-south-1 region

### ISSUE THREAD

**Issue by shencan** [ansible/ansible#16671]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION

now AWS ap-south-1 region is available， but can not use ec2 module launch instance, other region is normal
##### OS / ENVIRONMENT

Centos 6.5 
##### SUMMARY

AWS other region  launch instance normal
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```
TASK [launch a instances on mu(ap-south-1)] *****************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Instance creation failed => Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations."}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
