### ISSUE TITLE
Can't use < (less than) or ranges, when specifying version number in pip module

### ISSUE THREAD

**Issue by danrough** [ansible/ansible#16716]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Running ansible on Debian 8, and targetting machines that are using Debian 8 too.
##### SUMMARY

I attempted to install a version of a package using the pip module by specifying the version number using `version=<4` and discovered that the pip module is written in such a way which prevents the use of anything other than an explicit version number (or none). See here: https://github.com/ansible/ansible-modules-core/blob/devel/packaging/language/pip.py#L204
##### STEPS TO REPRODUCE

```
- name: Install version less than 4
  pip: name=foo version=<4
```
##### EXPECTED RESULTS

Latest version prior to the specified version number is installed.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
