### ISSUE TITLE
pip module broken under Windows?

### ISSUE THREAD

**Issue by techn0mad** [ansible/ansible#16725]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Ansible host: Darwin laptop.foobar.com 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
Ansible target: Windows Server 2012 R2 Datacenter; 64-bit Operating System, x64-based processor
##### SUMMARY

Attempts to install Python (platform-independent) packages using the (platform-independent) PIP package manger fail under Windows. Considering Python, PIP and a majority of Python packages are somewhat platform independent, it seems reasonable to expect that the pip module would be similarly platform independent.
##### STEPS TO REPRODUCE

```
- name: Install Python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.constraint|default('') }}{{ item.ver|default('') }}"
  with_items:
    - name: gitpython
    - name: artifactory
      constraint: ">="
      ver: 0.1.11
    - name: requests
      constraint: ">="
      ver: 2.7.0
  tags: foobar-doc
```
##### EXPECTED RESULTS

The Python packages gitpython, artifactory>=0.1.11, requests>=2.7.0 are installed.
##### ACTUAL RESULTS

The pip module throws an exception that indicates /usr/bin/python cannot be found; this is to be expected, as we are running on Windows. Also tried adding the option "executable: pip.exe" but it did not seem to make any difference as Python seems to be the missing link here.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~
failed: [win-39ceoco57ao.foobar.com] (item={u'name': u'gitpython'}) => {"failed": true, "item": {"name": "gitpython"}, "msg": "The term '/usr/bin/python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~
failed: [win-39ceoco57ao.foobar.com] (item={u'ver': u'0.1.11', u'name': u'artifactory', u'constraint': u'>='}) => {"failed": true, "item": {"constraint": ">=", "name": "artifactory", "ver": "0.1.11"}, "msg": "The term '/usr/bin/python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: + ~~~~~~~~~~~~~~~
failed: [win-39ceoco57ao.foobar.com] (item={u'ver': u'2.7.0', u'name': u'requests', u'constraint': u'>='}) => {"failed": true, "item": {"constraint": ">=", "name": "requests", "ver": "2.7.0"}, "msg": "The term '/usr/bin/python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
```

**Comment by jhawkesworth** [comment]
I imagine the pip module wasn't really written with windows in mind.  
What happens if you install a python (2.x) version first?  

For windows hosts the scripting language that Ansible uses is Powershell, rather than python, simply because its already available (as is python in almost every linux distro).

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by liberforce** [comment]
@jhawkesworth: This issue should be reopen, but somehow I can't find any button in the UI for that. The bug was valid and closed for bug migration, but bugs were migrated back here again.

**Comment by jaxzin** [comment]
@jctanner Can you reopen this issue? It's valid.

**Comment by jborean93** [comment]
@jaxzin, normal Python modules do not work on Windows, you need to run a win_* module which is written in PowerShell. Please open one issue as a feature request if you want to see a win_pip module instead.

**Comment by jaxzin** [comment]
Thanks @jborean93. I created #43566 as requested.
