### ISSUE TITLE
Error specifying `dns_servers` in `docker_container`

### ISSUE THREAD

**Issue by george-angel** [ansible/ansible#16730]
Getting the following error: 

```
fatal: [10.66.10.188]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 'dns' parameter has no effect on create_container(). It has been moved to host_config"}
```

I have a `docker_container` resource and specifying:

```
    dns_servers:
      - "{{ host_ip.stdout }}" # This evaluates to an ipv4 address
```

Versions:

```
ansible==2.1.0.0
docker-py==1.8.1
```

Docker version:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by george-angel** [comment]
Thanks, linking for reference: https://github.com/ansible/ansible-modules-extras/issues/2581
