### ISSUE TITLE
New-Alias in powershell.ps1 is trying to use an existing alias

### ISSUE THREAD

**Issue by deekayen** [ansible/ansible#16734]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### POWERSHELL VERSION

```
Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1      
```
##### OS / ENVIRONMENT

Windows 2008
##### SUMMARY

When I do debugging of scripts on the Windows side in PowerShell ISE, I've been getting this warning on the console:

```
New-Alias : The alias is not allowed, because an alias with the name 'Get-attr' already exists.
At C:\Users\svc_development\AppData\Local\Temp\ansible-tmp-1468602691.61-22452776890923\win_iis_webapppool.ps1:181 char:1
+ New-Alias -Name Get-attr -Value Get-AnsibleParam
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Get-attr:String) [New-Alias], SessionStateException
    + FullyQualifiedErrorId : AliasAlreadyExists,Microsoft.PowerShell.Commands.NewAliasCommand
```

It wasn't in the base win_iis_webapppool.ps1 file. It appears to be being inserted by `lib/ansible/module_utils/powershell.ps1`:

```
New-Alias -Name Get-attr -Value Get-AnsibleParam
```
##### STEPS TO REPRODUCE

Locate a cached win_iis_winapppool.ps1 file on the remote Windows host in c:\Users\xxx\AppData\Local\Temp, open it in Windows PowerShell ISE, and run it. The console shows the warning in red.

When I removed the `New-Alias` line from `powershell.ps1` and renamed the only other `Get-Attr` in that file, re-ran my playbook, it still worked. This isn't a pull request because I know there are other uses of `Get-Attr` in other ps1 files and I don't know why.

**Comment by jhawkesworth** [comment]
So, the alias is there because I asked for it as I thought Get-Attr was a bit generic and didn't really reflect that it was there to handle ansible module parameters.
In normal use the problem described doesn't occur because the module code is created, sent to the target machine executed exactly once and deleted.

When I am debugging modules I either do the same as you and just delete that line from the generated module code, or add 
`-EA SilentlyContinue`
to the end of the 
`New-Alias -Name Get-attr -Value Get-AnsibleParam`

Its not been a priority to fix it as the intention was to refactor the module api although I'm not aware of anyone making any headway regarding that at the moment.

**Comment by jhawkesworth** [comment]
Probably best fixed by calling get-alias and only adding the alias if it doesn't exist.

**Comment by trondhindenes** [comment]
Yep. It's vanity thing, but I wouldn't mind getting rid of this error while debugging. @jhawkesworth you on it, your should I PR it in?

**Comment by jhawkesworth** [comment]
Thanks @trondhindenes Please PR it, I want to try and get the win_package tests in before the code freeze.

**Comment by nitzmahone** [comment]
fixed by https://github.com/ansible/ansible/pull/17816 for 2.2.0RC1
