### ISSUE TITLE
Specify configuration file for supervisorctl

### ISSUE THREAD

**Issue by JensRantil** [ansible/ansible#1674]
This is a feature request and partially workaround for a bug in Supervisord that concerns the "supervisorctl" module.

Currently, there is a [case when `supervisorctl` cannot be started without arguments](https://github.com/Supervisor/supervisor/pull/62). A [patch is on its way](https://github.com/Supervisor/supervisor/pull/95), but has not been merged for a long time. I propose a `conf=/etc/supervisor.conf` argument to the supervisoctl module. This will both work around the bug, as well as add another feature to the plugin.

**Comment by mpdehaan** [comment]
We don't really do feature requests.

**Comment by mpdehaan** [comment]
To clarify, patches are welcome, but this is something I don't use, and most of our core folks don't use.   Asking here won't get it done, unfortunately.    Local modules shouldn't take conf files -- long standing design decision -- though if that's specifying a conf file supervisorctl already uses, perhaps?  Though I can't say I really have enough information to know what the nature of this bug is since this is a component I don't use.

I'm generally thinking supervisorctl is probably a bit too niche to be included in core, and we should drop it and let it be maintained outside.

**Comment by cbrinker** [comment]
supervisor(d|ctl) is currently pretty heavily used in AWS ElasticBeanstalk environments. They use the -c option to specify their own config file (not the system wide config file) @ -c /opt/python/etc/supervisord.conf. It would be helpful if I could tell the supervisor module that is the location of the config file.

**Comment by mpdehaan** [comment]
http://www.ansibleworks.com/docs/modules.html#supervisorctl

**Comment by mpdehaan** [comment]
How about sending in a pull request to add this?

**Comment by cbrinker** [comment]
Yea, working on one right now, was just checking to see if such a pull request existed for it yet when I found this issue.

**Comment by bcoca** [comment]
I don't know supervisord, but if you can give it an environment variable to
specify config file (many apps allow this) you can use environment:
directive

On Wed, Jul 3, 2013 at 5:51 PM, cbrinker notifications@github.com wrote:

> a, working on one right now, was just checking to see if such a pull
> request existed for it yet when I found this issue.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by cbrinker** [comment]
Looks like they don't really work with env variables.  https://github.com/Supervisor/supervisor/blob/master/supervisor/options.py#L102
