### ISSUE TITLE
Unexpected instance termination when try to launch new instance from aws

### ISSUE THREAD

**Issue by dogukansonmez** [ansible/ansible#16742]
When you try to launch new aws instance through ec2 module with exact_count=1 and count_tag={} it terminates all vms in connected vpc.

In ec2 module documentation it doesn't mention it might remove all instances when default state is present .

In ansible-module-core cloud/amazon/ec2.py if exact count is present it calls enforce_count function and enforce_count function does not take in consideration that exact count should be only for aws instance I want to create not total instance count in vpc. In ec2 module documentation for cout_tag parameter it says "The specified tag must already exist or be passed in as the 'instance_tags' option" but enforce_count doesn't take instance_tags values if count_tag is empty even though instance_tags has values.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
