### ISSUE TITLE
module (yum) is missing interpreter line

### ISSUE THREAD

**Issue by lazukars** [ansible/ansible#16743]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 134d70e7b9) last updated 2016/07/16 23:51:28 (GMT -400)
```
##### CONFIGURATION

no changes in the default ansible.cfg file
##### OS / ENVIRONMENT

Running Ansible on Ubuntu 14.04
Configuring on EC2 Centos 7.0
##### SUMMARY

When running the yum module on an ec2 Centos 7.0 machine, ansible errors out.

This error _only_ happens on ec2. When running the exact same task locally on a vagrant Centos 7.0 machine, the error does not occur. All other tasks on the ec2 machine work fine, just the yum task causes errors.
##### STEPS TO REPRODUCE

Run the task below on an ec2 Centos 7.0 machine

```
      - name: install firewalld
         yum: name=firewalld state=latest update_cache=yes
```
##### EXPECTED RESULTS

Ansible tries to install firewalld or any other listed package on the ec2 machine
##### ACTUAL RESULTS

```
 FAILED! => {"failed": true, "msg": "module (yum) is missing interpreter line"}
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
