### ISSUE TITLE
apt: only_upgrade=xxx ...Boolean xxx not in either boolean list

### ISSUE THREAD

**Issue by richardweiu** [ansible/ansible#16754]
Hello,

Having either apt: only_upgrade=docker-engine in my playbook or running it on the command line as ansible all --sudo -m apt -a 'only_upgrade=docker-engine' fails with

```
xx.xxx.xx.xxx | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Boolean docker-engine not in either boolean list"
}
```

In the document

only_upgrade(added in 2.1)  
Only install/upgrade a package if it is already installed.

my local ansible version is

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

Thanks!

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by biroeng** [comment]
Question , why synchronize module can't preserve the user where an operation is done
     - name: Synchronize a folder
         synchronize:
           become_user: test
           #mode: pull
           src: ../files/webUtility.war
           dest: /home/forgerock/Downloads
