### ISSUE TITLE
"ansible-galaxy info" errors with "AttributeError: Values instance has no attribute 'offline'"

### ISSUE THREAD

**Issue by builtbybrayne** [ansible/ansible#16760]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/al/Studio/Projects/smc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

/../projectdir/ansible.cfg:

```
[defaults]
roles_path=./roles
host_key_checking = False
ssh_args= -t -t
allow_world_readable_tmpfiles = True
```

~/.ansible.cfg

```
[defaults]
host_key_checking = False
ssh_args= -t -t
```
##### OS / ENVIRONMENT

OSX El Capitan 10.11.5
##### SUMMARY

`ansible-galaxy info` command seems to have a fatal bug that prevents it running at all.
##### STEPS TO REPRODUCE

Run the following command

```
ansible-galaxy -vvvvv info r_rudi.cowsay
```

Feel free to try different modules. I got the same errors regardless of the module I tried. The above is just an example.

##### EXPECTED RESULTS

I don't actually know what the `info` command _should_ produce, but I'm pretty sure it shouldn't produce this error.
##### ACTUAL RESULTS

```
Using /Users/al/Studio/Projects/smc/ansible/ansible.cfg as config file
Opened /Users/al/.ansible_galaxy
Validate TLS certificates: True
Validate TLS certificates: True
ERROR! Unexpected Exception: Values instance has no attribute 'offline'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 153, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 100, in execute
    fn()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 314, in execute_info
    if not self.options.offline:
AttributeError: Values instance has no attribute 'offline'
```

**Comment by jctanner** [comment]
@s-hertel can you take a look into this please?

**Comment by s-hertel** [comment]
Hi!

I believe this issue has been resolved for the next release. Lines 111-113 of galaxy.py in this commit fix the issue:
https://github.com/ansible/ansible/commit/ff9641a6a160f436e030a588e423ea9fa0b345c1

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
