### ISSUE TITLE
GCE credentials are needed everywhere

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#16770]
Hi,
I am using Google Cloud Engine and I have an "issue" with credentials.
The basic information like email, path to json configuration file and project id are specified in the gce.ini file. But that is insufficient. For some reason each GCE module task requires **service_account_email, 
pem_file, project_id** variables to be defined.

I have added them into _all_ group but I also have to provide this variables to each GCE module task anyway:

```
service_account_email: "{{ service_account_email }}"
pem_file: "{{ pem_file }}"
project_id: "{{ project_id }}"
```

which basically forces me to define info on two places(gce.ini + all group) + for each task that uses any of the GCE modules anyway and it is total nonsense. The gce.ini should be used primarily and only if it is not available it should proceed to check environment or specific task variables.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
