### ISSUE TITLE
ERROR! 'debug' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by saltos** [ansible/ansible#16778]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
$ cat ~/.ansible.cfg 
[defaults]
host_key_checking=False
retry_files_enabled=False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Error "'debug' is not a valid attribute for a Play" for the sample from the documentation.
##### STEPS TO REPRODUCE

Create sample playbook like in the http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-the-inventory:

```
- debug: msg={{ item }}
  with_items: "{{ groups['all'] }}"
```

Run it.

```
$ ansible-playbook -v -i ./hosts/inventory sample.yml
```
##### EXPECTED RESULTS

Message output.
##### ACTUAL RESULTS

```
ERROR! 'debug' is not a valid attribute for a Play

The error appears to have been in '/home/lexus/src/ps/stash/sso/sso_install_7.6/sso_install/sso_apps_status.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- debug: msg={{ item }}
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by jctanner** [comment]
@saltos the example referenced is just a task. It is not a valid playbook because it is missings a hosts declaration and the module call is not under a tasks section. The error is indicating that you've used the "debug" keyword as an attribute of the play (not a task). 

Please reference http://docs.ansible.com/ansible/playbooks_intro.html for writing playbooks.
