### ISSUE TITLE
azure_rm_resourcegroup "module_stderr": "/bin/sh: /usr/bin/sudo: Permission denied\n

### ISSUE THREAD

**Issue by mpender** [ansible/ansible#16828]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Tower 3.0 and Azure Resource Manager Credentials being used
##### OS / ENVIRONMENT

RHEL 7.2 (self contained ansible tower install, no HA)
##### SUMMARY

Creating a Resource Group works as expected however deleting the same resource group is not possible even with the 'force' option
Azure API token has full admin permissions over the subscription
##### STEPS TO REPRODUCE

```

---
- name: Deleting "{{ resource_group }}"
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    state: absent
    force: yes
#Vars are passed directly via Tower Surveys using the same var name as above
```

##### EXPECTED RESULTS

Resource group and all resources deleted
##### ACTUAL RESULTS

```
Identity added: /tmp/ansible_tower_mlvocL/credential (/tmp/ansible_tower_mlvocL/credential)
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: Azure_Delete_RG.yml **************************************************
1 plays in Azure_Delete_RG.yml

PLAY [all] *********************************************************************

TASK [azure-delete : Deleting "Ansible-Tower-Resource-Group"] ******************
task path: /var/lib/awx/projects/myprojects/roles/azure-delete/tasks/main.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1469530170.24-47980261611538 `" && echo ansible-tmp-1469530170.24-47980261611538="` echo $HOME/.ansible/tmp/ansible-tmp-1469530170.24-47980261611538 `" ) && sleep 0'
<localhost> PUT /tmp/tmpY5KeEO TO /var/lib/awx/.ansible/tmp/ansible-tmp-1469530170.24-47980261611538/azure_rm_resourcegroup
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-lasdalnhygfasqcsgsvdsouljnbhhywxi; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1469521170.24-4798022152123538/azure_rm_resourcegroup; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1469124170.24-4798012512511538/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "azure_rm_resourcegroup"}, "module_stderr": "/bin/sh: /usr/bin/sudo: Permission denied\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @Azure_Delete_RG.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
