### ISSUE TITLE
New ansible v2.1.0 is not compatible with Eucalyptus 4.2.1 and 4.3

### ISSUE THREAD

**Issue by klebae** [ansible/ansible#16835]
##### ISSUE TYPE

- Bug Report
  We found that the new features added in the /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon/ec2_ami_find.py  mentioned in  the description line : "Starting at version 2.1, additional sort choices of architecture, block_device_mapping, creationDate, hypervisor, is_public, location, owner_id, platform    , root_device_name, root_device_type, state, and virtualization_type are supported."  are not yet supported by the Eucalyptus v4.2.1 nor 4.3.   We have HP Technical support verified and confirmed this finding and they have filed EUCA-12607 (https://eucalyptus.atlassian.net/browse/EUCA-12607) for this issue.
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

`ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides`

```

##### CONFIGURATION
<!---
Mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_* environment variables).
-->

##### OS / ENVIRONMENT
<!---
RHEL 7 and RHEL 6 -->

##### SUMMARY
<!--- Explain the problem briefly -->

##### STEPS TO REPRODUCE
<!---
For bugs, show exactly how to reproduce the problem.
For new features, show how the feature would be used.
-->

<!--- Paste example playbooks or commands between quotes below -->
```

```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes below -->
```

```
```

**Comment by klebae** [comment]
Please see the link to the Eucalyptus bug EUCA-12607 mentioned above for explanation how the added CreationDate image attribute in Ansible v2.1 causes the playbook that uses the ec2_ami module to create an image from an instance to fail.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
