### ISSUE TITLE
Exceptions must be old-style classes or derived from BaseException, not type

### ISSUE THREAD

**Issue by pcastellazzi** [ansible/ansible#16836]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /dev/null
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
export ANSIBLE_CONFIG=/dev/null
```
##### OS / ENVIRONMENT

OS X 10.11.6
python 2.7.12 (homebrew)
##### SUMMARY

When accessing `hostvars.values()` i got the message:
`Exceptions must be old-style classes or derived from BaseException, not type`. I was expecting a list containing dictionaries with the vars from all hosts similar to what `dict.values()` do on python.
##### STEPS TO REPRODUCE

```
ansible-playbook -i test.ini test.yml

# test.ini
127.0.0.1 ansible_connection=local

# test.yml
- hosts: localhost
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ hostvars.values() }}"
```

##### EXPECTED RESULTS

It should print a list of dictionaries, each dictionary being the vars from a host.
##### ACTUAL RESULTS

```
Using /dev/null as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
task path: /Users/pcastellazzi/Downloads/test.yml:5
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ hostvars.values() }}): exceptions must be old-style classes or derived from BaseException, not type"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1
```

I traced the error to [ansible/vars/hostvars.py:74](https://github.com/ansible/ansible/blob/devel/lib/ansible/vars/hostvars.py#L74).

There you are raising `j2undefined` instead of `KeyError`. May be your intention was to return `j2undefined` instead?

In any case that's where the exception comes from, but not the why. It looks to me there are two sources of truth on the class HostVars, one for `__iter__` and one for `__getitem__`.

**Comment by jimi-c** [comment]
Closing This Ticket
===================

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
