### ISSUE TITLE
Select ip for interface on os_router module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#16830]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

If the first ip of a subnet is alredy assigned, router is created but interfaces are not.
##### STEPS TO REPRODUCE
- name: Connect subnets using a router
  os_router:
    cloud: "{{ connection }}"
    state: present
    name: router_internal
    interfaces:
        - security_subnet
          ip: <<fixed ip address or next free ip if not selected>>
        - private_subnet

```
TASK [ansible-OpenstackSecurityNetwork : Connect subnets using a router] ***
fatal: [127.0.0.1 -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Error attaching interface to router 47ce1f62-19c4-4c02-8d88-51afce38a6a9: Unable to complete operation for network c8b362f5-fad4-4b15-9f1d-165f8e20c3bf. The IP address 22.0.0.1 is in use.\nNeutron server returns request_ids: ['req-5f955b8c-ce00-4dd6-8619-e1b21e71cfb7']"}
```

##### EXPECTED RESULTS

If no IP is selected, ansible should use the first free IP on the newtork.
If IP is selected, ansible should use it to create the interface, and fail if IP address is already in use.
##### ACTUAL RESULTS

Actually, only first IP of the network can be used to create the interface, if IP is in use, ansible module fails to create the interface

```

```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
