### ISSUE TITLE
set_fact inside a role fails in ansible 2.2.0

### ISSUE THREAD

**Issue by SahajaKoorapati** [ansible/ansible#16846]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel aece03312f) last updated 2016/07/27 13:05:06 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/07/27 13:05:13 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/07/27 13:05:17 (GMT -700)
```
##### OS / ENVIRONMENT

OS X EI Capitan Version 10.11.5
##### SUMMARY

Ansible group_vars variable does not seem to identify the variable set from "set_fact" inside one of the role. It works in ansible 2.1.0.0 version
##### STEPS TO REPRODUCE

group_vars/all/vars.yml

```

---
foo: "{{ foo }}"
```

Inside one of the role, i am doing a set_fact like this

```
- name: Setting foo value
  set_fact:
    foo: 'bar'
```
##### EXPECTED RESULTS

ansible-playbook should run and pick up the foo value i set in the role.
##### ACTUAL RESULTS

```
ansible-playbook playbooks/setup.yml -vvvv
Using XX/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0
Loaded callback profile_tasks of type aggregate, v2.0

PLAYBOOK: setup.yml ************************************************************
4 plays in playbooks/setup.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "{{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: {{ foo }}: recursive loop detected in template string: {{ foo }}"
}
```

**Comment by jctanner** [comment]
EDIT: I think I understand the issue now. I need to include the role in my test playbook.

Here's my testcase ...

```
[jtanner@fedmac AP-16846]$ cat group_vars/all/vars.yml
foo: "{{ foo }}"
[jtanner@fedmac AP-16846]$ cat site.yml
- hosts: el6host
  connection: local
  roles:
    - testrole
  tasks:
    - debug: var=foo
[jtanner@fedmac AP-16846]$ cat roles/testrole/tasks/main.yml
- name: Setting foo value
  set_fact:
    foo: 'bar'
```

**Comment by jctanner** [comment]
Am I overlooking something from your description?

**Comment by jctanner** [comment]
Results ...

```
[jtanner@fedmac AP-16846]$ tail -n 25 returncodes.txt
v2.0.0-0.7.rc2 ; 0
v2.0.0-0.8.rc3 ; 0
v2.0.0-0.9.rc4 ; 0
v2.0.0.0-1 ; 0
v2.0.0.1-1 ; 0
v2.0.0.2-1 ; 0
v2.0.1.0-0.1.rc1 ; 0
v2.0.1.0-0.2.rc2 ; 0
v2.0.1.0-1 ; 0
v2.0.2.0-0.1.rc1 ; 0
v2.0.2.0-0.2.rc2 ; 0
v2.0.2.0-0.3.rc3 ; 0
v2.0.2.0-0.4.rc4 ; 0
v2.0.2.0-1 ; 0
v2.1.0.0-0.1.rc1 ; 0
v2.1.0.0-0.2.rc2 ; 0
v2.1.0.0-0.3.rc3 ; 0
v2.1.0.0-0.4.rc4 ; 0
v2.1.0.0-1 ; 0
v2.1.1.0-0.1.rc1 ; 1
v2.1.1.0-0.2.rc2 ; 1
v2.1.1.0-0.3.rc3 ; 1
v2.1.1.0-0.4.rc4 ; 1
v2.1.1.0-0.5.rc5 ; 1
v2.1.1.0-1 ; 1
```

So it looks like this behavior has regressed with 2.1.1.

**Comment by SahajaKoorapati** [comment]
I have a setup.yml which includes a list of roles something like this...

```
- include: roleA.yml
- include: roleB.yml
- include: roleC.yml
- include: roleD.yml
```

I am doing set_fact in roleB... and using it in roleC and roleD....

I have group_vars/all/vars.yml as below

```
---
foo: "{{ foo }}"
```

Each role is defined as this 

```
---
- hosts: localhost
  connection: local
  roles:
    - roleA
```

```
---
- hosts: localhost
  connection: local
  roles:
    - roleB
```

```
---
- hosts: localhost
  connection: local
  roles:
    - roleC
```

```
---
- hosts: localhost
  connection: local
  roles:
    - roleD
```

What is the best and suggested place where i can include roleB here?

**Comment by jimi-c** [comment]
So the issue here is not set_fact. The problem is with the recursive variable. This problem was hidden in earlier 2.0.x and 2.1.x versions due to the fact that you were not using hostvars. As of commit 6b286ee0c88f3252a27ff94f39d794566c3f7d6f, hostvars are referenced during the creation of the connection plugin, which causes the error to manifest in a more obvious way now. If instead you simply had a task like this:

<pre>
  tasks:
  - debug: var=hostvars['localhost']
</pre>

the same error shows up:

<pre>
TASK: [debug var=hostvars['localhost']] *************************************** 
fatal: [localhost] => Failed to template {{hostvars['localhost']}}: Failed to template {{ foo }}: ...
</pre>

This same error occurs in all versions of Ansible that I've tested, so really the answer is to not try to do a recursive variable in this manner.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
