### ISSUE TITLE
group_vars ignored with inventory script in ansible 2.1.1.0

### ISSUE THREAD

**Issue by andrenarchy** [ansible/ansible#16878]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

group_vars are ignored if the inventory is the output of a script that is stored in a subdirectory. This includes the popular ec2 inventory script. This bug was introduced in 2.1.1.0 (2.1.0.0 works fine).
###### `inventory/script.sh`

```
#!/bin/sh

echo '{"webservers": ["paperberry"]}'
```
###### `group_vars/all.yml`:

```

---
frontend_path: /var/www/html
```
###### `playbooks/webservers.yml`:

```

---
- hosts: all
  connection: local
  tasks:
  - debug: var=frontend_path
```

Run the following code:

```
ansible-playbook -i inventory/script.sh playbooks/webservers.yml 
```
##### EXPECTED RESULTS

ansible 2.1.0.0 shows

```
ok: [paperberry] => {
    "frontend_path": "/var/www/html"
}
```
##### ACTUAL RESULTS

ansible 2.1.1.0 shows

```
ok: [paperberry] => {
    "frontend_path": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

It has always been that group_vars are adjacent to inventory or play, not to the directory that contains them.

What you might have run into was a bug in 2.1 in which group_vars were also loaded from the 'current working directory', which was fixed in 2.1.1.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by andrenarchy** [comment]
Thanks for pointing this out. The docs are also clear about this.

**Comment by haad** [comment]
Would it be possible to bring this behavior back, maybe disabled by default?

**Comment by RRAlex** [comment]
Strange, this has always worked for me (tm), even before 2.1.0 and all the way to 1.9.x.
Am I missing something or is it now quite hard to organize playbooks without doing a bunch of "ln -s" to the group_vars / host_vars from within all the playbooks folders?

**Comment by emanuelis** [comment]
Come on guys, this is not a bug fix, this is a braking change in a minor-minor version! You have just effectively broken thousands of infrastructures!

**Comment by kerneldemon** [comment]
I have to agree with @emanuelis on this one.
Including this backwards incompatible "bugfix" in the next patch version is an exceptionally bad decision.

**Comment by caDevOps** [comment]
wtf? my playbooks are broken due to this "upgrade"!

**Comment by ricardclau** [comment]
Unbeliveable that this is treated as a bug fix when it is effectively breaking thousands of infrastructures. Totally agree with @emanuelis

**Comment by nmarley** [comment]
This is ridiculous guys. You introduced a bug which broke so many people and are calling it a "fix". Incredible.

**Comment by cj-dimaggio** [comment]
Also generally breaks Ad-Hoc commands for a lot of setups, essentially forcing you to move all group-vars alongside inventory file as opposed to playbooks if you wish to use adhoc as you can no longer use your working directory to define them

**Comment by Modusmundi** [comment]
This breaks your best-practices documentation as well, which is incredibly frustrating for a new user to Ansible:

https://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout

**Comment by viper233** [comment]
This is an difficult issue to face when it comes to using multiple inventories. Most people seem to all fall into the case where there are certain group_vars, and even host_vars that all environments need to be aware of. 

We need to better define how groups_vars are to be used with multiple environments and document best practices for how they should be used. We all want the playbooks and roles to be as flexible as possible and work over all environments with _no_ duplication of variable declaration to the same value. 

The [documentation on variables](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) mentions _playbook group_vars_.

I don't see playbook group_vars mentioned anywhere else on the site?

https://github.com/ansible/ansible/commit/6dd07de10b7ec7f2aa865deb23f2f19e1656c217 gives the multi inventory directory layout out with it's down fails.

https://github.com/ansible/ansible/pull/17354

**Comment by kustodian** [comment]
`group_vars/host_vars` being picked up from the current working directory was is a bug which was introduced in 2.1 by mistake. It was never supposed to be there. `group_vars/host_vars` should only be read the directory of the inventory file and the directory of the playbook. The reason for this is security, since if you would to run ansible-playbook from a directory which has some malicious `group_vars/host_vars` in it you could break your managed hosts.

@Vivicus it doesn't break the best practices documentation, since in the best practices documentation `group_vars/host_vars` are in the same directory where the inventory files are (as well as where the playbooks are), so everything works.

**Comment by haad** [comment]
Sorry this doesn't make a lot of sense at all. To actually work ansible needs more than _group_var/host_vars_ so potential attacker would have to create those, too. And if he is able to create them then he could easily create entries in per inventory _group_vars/host_vars_. So to me any potential attack is very unlike to happen. 

I understand that any feature/behavior like this should be communicated properly. But to call this a security measure is false.

**Comment by kustodian** [comment]
@haad I'm not a core Ansible developer, but I've been using Ansible for a long time and whether you like it or not, this was a bug, this functionality was never documented anywhere and it's not coming back. Also if you need to define variables in CWD for your Ansible playbooks to work, then you are probably not doing something correctly, so feel free to ask the community of your use case in the forum or IRC, I and the whole Ansible community would be more than happy to help you out, to give you a solution to your problem.

Regarding this not being a security concern, let me give you an example how it is a security concern. If you have a playbook which runs a task which sets the root user SSH public key, e.g.:

```
- authorized_key:
    user: root
    key: '{{ root_public_key }}'
    exclusive: yes
```

So let's say your organization uses a bastion host through which all users connect to other hosts. Some local (malicious) user who knows about this playbook and the variable name, could do this:

```
mkdir /tmp/group_vars
echo 'root_public_key: "ssh-rsa AAKfslfs....."' >/tmp/group_vars/all
```

Now an admin user which wants to run a playbook with the task above could run `ansible-playbook` from `/tmp`, e.g.:

```
admin@bastion:/tmp$ ansible-playbook -i /path/to/inventory /path/to/playbook/set_root_key.yml
```

That would overwrite what the admin user configured in his inventory/playbook `group_vars/all` with what is in /tmp and the malicious user could take control of those hosts. Also think of the continues delivery tools running playbooks from some random directories, which could have some badly set variables in them as well.

**Comment by juliedavila** [comment]
I'll add, I've probably seen more production implementations of Ansible in terms of both quantity and variety than probably most people in the whole industry given my tenure at Ansible. That being said, anyone using Ansible properly shouldn't/wouldn't be using arbitrary group/host vars directories in such a way to leverage the CWD-vars-pickup bug. This is not a pattern I have ever recommended while providing professional services to our clients.

I agree with @kustodian and I also think it makes for a very hard to audit and manage set of code/data when it comes to correlation activities.

**Comment by cmebert** [comment]
so, how would the best practice structure (specifically for group_vars) change when using dynamic inventory in tower?  This is where i'm struggling.  I have one group_vars folder at the top level (as defined by the best practices docs) and upon upgrading to 2.1.1 they are no longer recognized.  I don't define individual inventories inside the general directory, as tower handles that for me. 

to add, this was working correctly for all versions over the last 18 months and only broke at 2.1.1

**Comment by samdoran** [comment]
@cmebert The key thing is not where `group_vars` sits but where it is _in relation to your playbooks_. A top level `group_vars` folder will only work if all your playbooks sit next to it. These are _play_ group vars. These will work consistently between Ansible Tower and Ansible on the command line. Since Ansible Tower manages its own inventory (even dynamic) it pays no attention to _inventory_ group vars.

If your playbooks are in a subfolder, put your `group_vars` in there as well. That will give you the desired behavior.

**Comment by cmebert** [comment]
that's exactly how it's explained in the best practices structure example, and exactly what we have followed.  The ability of tower to access a top level group_vars folder next to top level playbooks breaks with 2.1.1

**Comment by bcoca** [comment]
@cmebert, no it is not, in the best practices you have BOTH inventory and plays on the top level directory.

If you look at the 'alternate' layout it becomes clear that the group_vars are set adjacent to inventory.

I do see how the main example can be confusing, the documentation about how group/host_vars works is lacking and I'll be updating it soon to hopefully clear this up.

**Comment by samdoran** [comment]
@cmebert I just made a simple project to hopefully clarify.

```
.
├── group_vars
│   └── all.yml
├── inventory
│   ├── group_vars
│   │   └── all.yml
│   └── hosts
├── playbooks
│   ├── group_vars
│   │   └── all.yml
│   └── nested-playbook.yml
└── toplevel-playbook.yml
```

When running `toplevel-playbook.yml`:

```
.
├── group_vars
│   └── all.yml         <-- These are applied, others ignored.
 ...
└── toplevel-playbook.yml
```

When running `nested-playbook.yml`:

```
.
...
├── playbooks
│   ├── group_vars
│   │   └── all.yml      <-- These are applied, others ignored. group_vars at the root of a project is the same as any arbitrary directory from the perspective of nested-playbook.yml.
│   └── nested-playbook.yml
...
```

In all cases, Tower ignores inventory `group_vars`.

I find this table immensely helpful for clarifying the relationship between variables in a repository and how they are consumed or ignored by Ansible Tower.

[![Ansible Tower Variables](http://docs.ansible.com/ansible-tower/latest/html/userguide/_images/Architecture-Tower_Variable_Precedence_Hierarchy.png)](http://docs.ansible.com/ansible-tower/3.0.1/html/userguide/job_templates.html#extra-variables)

**Comment by bcoca** [comment]
This all works as expected, tower does not use the that inventory file, so those group vars are never looked at.

**Comment by cmebert** [comment]
@samdoran  That first example is exactly how our directory structure is laid out, and prior to 2.1.1 tower would recognize and use group_vars .yml files located inside of the top level group_vars folder without issue.  This breaks upon upgrade to 2.1.1 without any other changes.  (tower 3.0.2).  

If a restructure is needed, i'm happy to do it, there just doesn't appear to be any documentation (ansible or tower) indicating any requirements changed.

**Comment by bcoca** [comment]
The requirements did not change, a bug in Ansible was fixed that incorrectly allowed your setup to work.
Tower is just the thing executing Ansible in this case.

**Comment by cmebert** [comment]
@bcoca If the requirements didn't change, but a bug was fixed, and this bug fix broke the best practices example from the documentation, can we please just get an updated set of docs.  I'm a paying tower customer that can not update the version of ansible i'm using due to this "bug fix".

**Comment by bcoca** [comment]
please read above it DID NOT break the best practices example

**Comment by matthewfischer** [comment]
@cmebert did you fix it? I have the same exact problem when trying to upgrade us to 2.2.0. Dynamic inventory only and group_vars not recognized. I only have one group_vars file and it makes no sense to copy it around to several places.

**Comment by icmp-echo** [comment]
so what is the solution to this? i did upgrade and same thing all our play books are broke i am working on automation of network devices and some of them requires a latest version to run. if we have solution I would like to understand, P.S> I am not a developer nor a programmer just a network engineer, please be thorough. Many Thanks.

**Comment by senorsmile** [comment]
As others have said before, this seems like a weird "bug fix".  We have a dynamic inventory, as well as some things defined in group_vars and host_vars at the root of our repo.  We have been doing this since 1.7ish.  Suddenly, group_vars and host_vars do not get loaded at all in 2.2 (upgrading from 2.0).  Our current workaround is to symlink the top level group_vars and host_vars into our dynamic inventories submodule, adding those folders as exceptions in .gitignore.  This is a weird workaround!!! 

As an alternative, can we specify multiple directories to look for inventories in ansible.cfg?

**Comment by ghost** [comment]
I have followed the comments and I see that the fact that the issue was open **for a dynamic inventory** script was ignored after some interactions.

For me it is an issue, because we use ec2.py script to get dynamic inventory from AWS. 

I believe that my layout is correct, since group_vars are adjacent to playbooks, very similar to
@samdoran example but using a dynamic inventory. 

Example:

```
.
├── group_vars
│   ├── all
│   │   └── all.yml <--- always loaded
│   ├── tag_env_aws_eu_west_011_production
│   │   └── only_for_this_env.yml <--- I would like to have that file loaded as 
                   it defines MyArray.MyAttribute used for an iteration
├── inventory
│   └── ec2.ini
│   └── ec2.py
├── roles
│   └── pam_limits
│   └── other_role
└── my-playbook.yml
```
Inside my-playbook.yml  I have:
```
  - hosts: tag_env_aws_eu_west_011_production
    roles:
      - { role: pam_limits, tags: [ 'pam_limits'] } 
     ...
    tags:
      - common
```
Before running the playbook set ANSIBLE_HOSTS so it uses an inventory script:
```
#Set
cd .
export EC2_INI_PATH=$(pwd)/inventory/ec2.ini
export ANSIBLE_HOSTS=$(pwd)/inventory/ec2.py

```
There is a host in the dynamic inventory created by ec2.py that is in a group named " tag_env_aws_eu_west_011_production" (tags in AWS are mapped as groups)
```

"tag_env_aws_eu_west_011_production": [
    "123.123.123.123", 
    "123.123.123.124"
]

```

With ansible <= 2.1.4.0, the group_vars/tag_env_aws_eu_west_011_production/only_for_this_env.yml is loaded and my roles can use variables defined in that file.

With ansible > 2.1.4.0, only the  group_vars/all/all.yml is loaded

```
TASK [pam_limits : a_task] ********************************************************************************************************
fatal: [123.123.123.123]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, 
which appears to include a variable that is undefined. The error was: 
'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'MyAttribute'\n\nT...}

```

**Please point me to the right direction, if I am doing something wrong let me know**. Unfortunatelly I don't use tower. Should I open a new issue?

So far I have gone back to 2.1.4.0 stable.

Thanks!

**Comment by jangrewe** [comment]
I'm hitting the same issue as  @jruizjimenez with v2.2.1.0
