### ISSUE TITLE
better default speed

### ISSUE THREAD

**Issue by hpk42** [ansible/ansible#1690]
Spent an hour looking through ansible sources to understand why the default mode of ansible is so slow.   I am currently only using it for scripting a single host with a single playbook.  IISIC, In Paramiko/ssh mode, each task runs in a separate process so the plugin's SSH_CONNECTION_CACHE only is effective on a per-task basis. (It probably could rather be an instance variable rather than a global, therefore, btw).   Fireball circumvents the issue by establishing a singleton at the remote side and connecting from all subprocesses to there, right?  I am pretty sure, the main part of the fireball speedup comes from the fact that this avoids the per-task ssh-init.

If i were to try something i'd probably go for substituting multiprocess with gevent, this would make it easy to share connections and probably have other benefits.  Not sure how intrusive this change would be.

**Comment by hpk42** [comment]
Ah, using "--connection=ssh" already helps because of the ControlMaster, i guess.  Leads to a 2-3 times speedup.  Wondering why paramiko is the default then?

**Comment by dhozac** [comment]
Because older (e.g. RHEL6) openssh doesn't support ControlPersist.

**Comment by hpk42** [comment]
A default "ssh"connection type could be degraded to paramiko if openssh isn't the correct version i guess.

**Comment by mpdehaan** [comment]
paramiko is also not slower for everyone, even on newer platforms.    It is
also easier to setup, usually, due to known hosts handling and so forth.

I'm not in favor of auto-detecting for the reason that they have
differently, and that I haven't seen that -c ssh is consistently faster.

The connection cache is not used longer than each task right now because we
don't have #1688 yet.
