### ISSUE TITLE
Custom fact not working when called by Ansible, but works localy

### ISSUE THREAD

**Issue by furiml** [ansible/ansible#16915]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

I've written a custom fact in python to retrieve UUIDs from the diskutil cs list command. Renamed it with .fact extension, moved it to /etc/ansible/facts.d/ on the remote, made it executable and tested it locally : it works, and returns json output : 

> {"MHDLogicalVolumeUUID":"433D72CF-AF5A-4194-B29A-20779C850FC2","MHDLogicalVolumeGroupUUID":"42D8699E-FB3D-4637-B9AC-CEA8CCE6AB69"}

However, when I try to gather this fact from the controlling machine, I get an error : 

> macremote | FAILED! => {
>     "changed": false,
>     "cmd": "/etc/ansible/facts.d/corestorage.fact",
>     "failed": true,
>     "msg": "[Errno 2] No such file or directory",
>     "rc": 2
> }

I just can't understand why it doesn't work remotely. You can see my python script below.
Thanks !
##### STEPS TO REPRODUCE

CORESTORAGE.PY

```
import xml.etree.ElementTree as ET
import re
import subprocess
import os

pattern = re.compile("^[A-Z0-9\-]{36}$")
MHDfound = 0
LVfound = 0
LVGfound = 0

def getBashOutput(cmd):
  bashCommand = "{}".format(cmd)
  bashProcess = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
  bashOutput = bashProcess.communicate() # generates a tuple
  return bashOutput[0][:-1] # \n removed

corestorageplist = getBashOutput("/usr/sbin/diskutil cs list -plist")
tree = ET.fromstring(corestorageplist)
for node in tree.iter():
  if node.tag == "string":
    if pattern.match(str(node.text)):
      uuidinfo = getBashOutput("diskutil cs info -plist {}".format(node.text))
      subtree = ET.fromstring(uuidinfo)
      for subnode in subtree.iter():
        if subnode.text == "Macintosh HD":
          MHDfound = 1
        if subnode.text == "LV":
          LVfound = 1
        if subnode.text == "LVG":
          LVGfound = 1
      if (MHDfound == 1 and LVfound == 1 and LVGfound == 0):
        MHDLVUUID = node.text
      elif (MHDfound == 1 and LVfound == 0 and LVGfound == 1):
        MHDLVGUUID = node.text
      LVfound = 0
      MHDfound = 0
      LVGfound = 0

print "{\"MHDLogicalVolumeUUID\":\"" + MHDLVUUID + "\",\"MHDLogicalVolumeGroupUUID\":\"" + MHDLVGUUID + "\"}"

```

##### EXPECTED RESULTS

I wanted to gather UUIDs for remote volumes management. So something like

```
macremote | SUCCESS => {
    "ansible_facts": {
        "ansible_local": {
            "corestorage": {
                "MHDLogicalVolumeUUID": "433D72CF-AF5A-4194-B29A-20779C850FC2",
                "MHDLogicalVolumeGroupUUID":"42D8699E-FB3D-4637-B9AC-CEA8CCE6AB69"
            }
        }
    }
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ]
        },
        "module_name": "setup"
    }
}
```
##### ACTUAL RESULTS

```
macremote | FAILED! => {
    "changed": false,
    "cmd": "/etc/ansible/facts.d/corestorage.fact",
    "failed": true,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ]
        },
        "module_name": "setup"
    },
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}
```

**Comment by alikins** [comment]
Is '/etc/ansible/facts.d' readable by the ansible user?

is 'diskutil' on the ansible users PATH?  (it's invoked once as '/usr/sbin/diskutil' and once as 'diskutil' in the facts script).

How are you invoking the facts collection? 'ansible' or 'ansible-playbook'?
What params?

```
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_local",
            "gather_subset": [
                "all"
            ]
        },
```

Where is the 'filter' value of 'ansible_local' coming from?

**Comment by furiml** [comment]
Hello and thank you for replying :+1: 
I'll try to answer your questions : 

> Is '/etc/ansible/facts.d' readable by the ansible user?

Yes, user is owner of the /etc/ansible directory and subdirectories (did chown -R)

> is 'diskutil' on the ansible users PATH?

Yes, I can use it without writing /usr/bin/diskutil when logged on the remote machine with the account I use. I guess I've been lazy in my fact script... Thanks for pointing that out.

> How are you invoking the facts collection?

I'm running this command : 
`ansible myhost -m setup -a "filter=ansible_local"`
as seen in the documentation. That should answer your last question too.
**Please note** that while my corestorage.fact file is sitting at /etc/ansible/facts.d/, I can't use Ansible on the remote machine ! The same error gets spitted out. Only way to get Ansible to work is to rename the fact corestorage.py (py, or anything that isn't .fact)

Thanks for helping ! I have found a workaround, but I'd like to do this the "clean" way, using facts :)

**Comment by jctanner** [comment]
@Furiml what output do you see when you ssh to the remote host and execute the fact script directly?

```
# /etc/ansible/facts.d/corestorage.fact
```

**Comment by furiml** [comment]
Hello and thank you for replying. You may have found what's wrong...
I get this output :
`-bash: ./corestorage.fact: /usr/local/bin/python^M: bad interpreter: No such file or directory`
This could be why it doesn't work, but... 

```
myhost:~ user$ which python
/usr/local/bin/python
```

Where does this 

> ^M

 come from ?
I tried to change the sha-bang with the full path to the python interpreter (/Library/Frameworks/...) but it doesn't work either, same error message.

Thanks !

**Comment by jctanner** [comment]
@Furiml did you edit the file in windows?

http://its.ucsc.edu/unix-timeshare/tutorials/clean-ctrl-m.html

**Comment by furiml** [comment]
Hi and thanks for replying.
I did edit the file in windows, with Sublime Text. However, here's some weird stuff :
- deleting ^M with sed erase the whole document
- emacs & vi can't find ^M pattern

I will try to rewrite it directly with emacs on the machine, I'll give feedback.

Feedback : Yup, that was it. Seemed that Sublime text introduced those ^M, it's weird that none of the solutions provided in your link didn't work...
Thanks for the help !

**Comment by Furiml** [comment]
I'm having slightly the same problem with a fact for Windows. I've read the notes in the documentation and got everything set up properly, but things are not working **properly** :



##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
setup module, gathering custom fact on Windows host

##### ANSIBLE VERSION

```
2.1.1.0
```

##### OS / ENVIRONMENT
Running Ansible from Debian 8 Jessie
Host is Windows 10 Pro up to date

##### SUMMARY
Setup module raise a warning saying it has junk after the JSON data. The fact _works_ because I can see what I'm expecting in the error message. It appears that the error happens when the output of my PS1 script is JSON formated. I'll develop that later.

##### STEPS TO REPRODUCE
This is my script :
```
$diskStats = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='D:'" | Select-Object Size, Freespace
$percent = [math]::Round(($diskStats.Freespace / $diskStats.Size) * 100, 2)
Write-Host "{`"free_disk`":`"$percent`"}"
```
It is a simple PS1 script that outputs the percentage of free disk space on the D disk. 
It outputs correct JSON, Here's what I tried for the name:

-  "{`"free_disk`":`"$percent`"}"
-  "{`"ansible_ps1disk`":`"$percent`"}" (ps1disk is the name of my script)
-  "{`"$percent`"}"

If I set the script to output something that **isn't** correct JSON, The setup invocation works and I get this :
`"ansible_ps1disk": null,`
(Which is why I tried the ansible_ps1disk : $percent pair)

Otherwise, if the script outputs correct JSON, I get this


```
[WARNING]: Module invocation had junk after the JSON data:
hostname | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "{\"free_disk\":\"99.98\"}\n{\"changed\":false,\"ansible_facts\":{\"ansible_ps1disk\":null,\"ansible_interfaces\": 
[... I have a huge chunk of non-formated JSON with the rest of the setup output here]
    "msg": "MODULE FAILURE",
    "parsed": false
}
```
**Look at what is right after module_stdout !**
What I see here is that Ansible saw my fact, executed it and everything was ok. I don't understand the junk thing, nor the "parsed": false... My script outputs this :
`{"free_disk":"99.98"}` which is good JSON...

I tried a different approach. Leaving everything as it is, I tried to run the script with the raw module, and it works !
This input : 
`ansible hostname -m raw -a "powershell.exe C:\Users\username\ps\ps1disk.ps1"`
Outputs this :
```
hostname | SUCCESS | rc=0 >>
{"free_disk":"99.98"}
```

##### EXPECTED RESULTS

I wanted to have a successful output, with my fact displaying as : `"ansible_ps1disk ": "99.98"`
##### ACTUAL RESULTS

I can't really paste the whole thing as it is on an office computer, but you can see a part of the output above.

The input command was this :
```
ansible hostname -m setup -a "fact_path=C:/Users/username/ps/ps1disk.ps1"
```
Verbosity output (in blue) (hostname, user and DOMAIN replaced for privacy):
```
Loaded callback minimal of type stdout, v2.0
<hostname> ESTABLISH WINRM CONNECTION FOR USER: user@DOMAIN on PORT 5986 TO hostname
<hostname> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1470907337.06-215029353989986").FullName | Write-Host -Separator '';
<hostname> PUT "/tmp/tmpHOzN5D" TO "C:\Users\username\AppData\Local\Temp\ansible-tmp-1470907337.06-215029353989986\setup.ps1"
<hostname> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\username\AppData\Local\Temp\ansible-tmp-1470907337.06-215029353989986\setup.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\username\AppData\Local\Temp\ansible-tmp-1470907337.06-215029353989986" -Force -Recurse -ErrorAction SilentlyContinue }
```
Looks like something goes wrong with the parsing...
Any idea ?
Thanks <3
