### ISSUE TITLE
ansible behaviour inventory variables not being picked up from group_vars in 2.1.1

### ISSUE THREAD

**Issue by tkinz27** [ansible/ansible#16956]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
  config file = /stuff/ansible.cfg
  configured module search path = ['./library']
```
##### SUMMARY

Just upgraded to ansible 2.1.1 and noticed I could not ssh to any of my nodes anymore. Realized the ssh command that is being used to connect is not including the `-o 'IdentityFile=` or the `-o User=` flags. We set the `ansible_user` and `ansible_ssh_private_key_file` variables in group_vars for the various environments that each group of hosts is from (typically each environment has a different private_key). 

Was able to get around this by setting the options on the command line.
##### STEPS TO REPRODUCE

Move ansible_ssh_private_key_file and ansible_user variables to a group_var for a host (mine are not in all.yml, not sure if that matters) and try to run a playbook without specifying the values on the command line. 

ansible-playbook some_play -vvvv

##### EXPECTED RESULTS

This is the result when I add `-e ansible_user=ubuntu -e ansible_ssh_private_key_file=~/.ssh/dev.pem` to the `ansible-playbook` command

```
<10.64.0.218> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=360s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/tkinz/.ssh/dev.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.64.0.218 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-cjlqfgwiukyslnxpcwrfediwgqapkuwh; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```
##### ACTUAL RESULTS

```
<10.64.0.218> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=360s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.64.0.218 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-aefstgpfveqloqbmzzweiirdnbxrrtda; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

**Comment by kustodian** [comment]
You need to give an example of an inventory and a playbook which will reproduce this issue, so that the devs can easier fix it.

**Comment by jinnko** [comment]
I reproduced this problem on the stable-2.1 branch a week ago and it's still an issue today.

I'm expecting the following to be the way things work, based on documentation and from experience prior to 2.1.

```
$ tree -d -L 2
├── group_vars/
├── host_vars/
├── hosts/
├── plays/
└── roles/
    ├── common/
    ├── debops.tinc/
    ├── lsb/
    ├── nginx/
    ├── postgresql/
    └── users/
```

Eventually figured out the following does work.

```
$ tree -d -L 2
├── hosts/
│   ├── group_vars/
│   └── host_vars/
├── plays/
└── roles/
    ├── common/
    ├── debops.tinc/
    ├── lsb/
    ├── nginx/
    ├── postgresql/
    └── users/
```

Notes about the setup:
- playbooks are in the `plays/` folder
- `hosts/` is a folder containing multiple inventory files
- the `inventory` config item is definied in ansible.cfg pointing at the absolute path to the `hosts/` folder

**Comment by bcoca** [comment]
so inventory as a directory is just a 'container to inventory files', we might need to clarify this in the docs, the group_vars needs to be adjacent to the inventory FILES, not the directory.

**Comment by jinnko** [comment]
@bcoca if I understand correctly you're saying that the behaviour has intentionally changed between 2.0 and 2.1?  If that's the case I've come across no communication of this breaking change within the 2.x major version.

**Comment by bcoca** [comment]
no, the behavior changed 'unintentionally' from 1.9 to 2.0 and we corrected it in 2.1

**Comment by eyvind** [comment]
I also have this problem, but it only seems to affect group_vars; variables defined in the host_vars directory are picked up just fine.

Should we move host_vars into the inventory directory along with group_vars, to prevent trouble in future versions of Ansible?

**Comment by dliappis** [comment]
@bcoca I am a bit confused with the dir structure we should be using from now on.

[In the doc](http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data) I read:

> Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will override variables set in the inventory directory.

Let's assume a directory structure like:

```
├── inventory
│   ├── local
│   │   └── localhost.yml
│   ├── production
│   │   └── prod-vars.yml
│   └── staging
├── playbooks
│   ├── group_vars
│   │   ├── all
│   │   ├── example-group-A
│   │   └── example-group-B
│   └── host_vars
│       └── localhost
|           └── example-localhost.yml
|   └── testplaybook.yml
└── roles
```

and the contents of the two files are:

``` yaml
$ cat playbooks/testplaybook.yml 
---

- name: test 16956
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - debug: var=a_fact_in_hostvars
```

``` yaml
$ cat playbooks/host_vars/localhost/example-localhost.yml 
---
a_fact_in_hostvars: 'should be accessible'
```

This structure seems to work on all ansible versions (inc. 2.1.1.0) for both `group_vars` (files not shown here) and `host_vars` [1] and playbooks can access the vars when I use:

`ansible-playbook -i inventory/local playbooks/testplaybook.yml`
or
`ansible-playbook -i inventory/production playbooks/someotherplaybook.yml`

You mentioned `group_vars` needs to be _adjacent_ to the inventory files; can you please clarify if the above is a safe structure to follow in the future as per the docs?

[1]: One change though in 2.1.1.0 is that `[localhost]` needs to be explicitly defined in a file e.g. in my example above under `inventory/local/localhost.yml`; this wasn't needed in ansible <2.1.1.0 e.g. in 2.1.0.0

**Comment by bcoca** [comment]
They need to be adjacent to inventory or play, I was specifying that it is the 'files' in the case of inventory, that an inventory dir does not count. 

Since we were discussing ones relative to an inventory dir I did not feel the need to mention play files in that context.

**Comment by jamesdh** [comment]
Still a bit confused by this. We just upgraded from 2.1.0.0 to 2.1.1.0 and our host/group_vars are also no longer being included. Everything was working great w/ 2.1.0.0. 

Our current layout is generalized as such:

```
├── group_vars
│   ├── group1
│   ├── group2
│   └── groupXYZ
├── host_vars
│   ├── all
│   ├── host-A
│   ├── host-B
│   └── localhost
├── roles
|   ├── common
|   │   └── tasks
|   │          └── main.yml
|   ├── database
|   │   └── tasks
|   │          └── main.yml
|   └── etc
├── inventory
└── site_playbook.yml
```

Which is how it's recommended in [Best Practices](http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout). So if that results in breakage, what's the _real_ correct way?

**Comment by meetmatt** [comment]
This is 100% certainly a BC-breaking change. Why would you need to merge it to a patch version? Just broke my deployments in several projects.

**Comment by bcoca** [comment]
@jamesdh the best practices assume 'inventory' in your case is a file, not a directory.  In my testing group_vars work for both 'inventory' and site_playbook.yml in that case

**Comment by jcassee** [comment]
@bcoca I think in @jamesdh's example, the `group_vars` and `host_vars` directories _are_ adjacent to the playbook?

**Comment by jamesdh** [comment]
@jcassee is correct, it is a file.

**Comment by bcoca** [comment]
As i said, i cannot reproduce the issue when that is the case.

**Comment by purduemike** [comment]
My structure looks like this and 2.1.1 broke it as well.
![screen shot 2016-08-15 at 5 10 39 pm](https://cloud.githubusercontent.com/assets/3812871/17683848/64b6ed64-630b-11e6-957b-773e1f3dd6a7.png)
I've reverted to 2.1 for the time being.

**Comment by jamesdh** [comment]
We also were forced to manually reinstall 2.1.0.0 in order to return to a working state. 

I'll try and find some time later to create a public repo with the necessary files to reproduce this...

**Comment by tkinz27** [comment]
Sorry it has taken me so long to get back. I finally was able to recreate a very simple test that shows the problem.

I have a directory structure like this...

```
.
├── Dockerfile.2.1.0
├── Dockerfile.2.1.1
├── ansible.cfg
├── group_vars
│   └── all.yml
├── inventories
│   └── flat
└── playbooks
    └── test.yml
```

My ansible.cfg is

```
[defaults]
forks=50
nocows=1
jinja2_extensions = jinja2.ext.loopcontrols,jinja2.ext.do,jinja2.ext.i18n

host_key_checking = False
gathering = smart

retry_files_enabled = False

inventory = inventories/flat

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=360s
scp_if_ssh=yes
pipelining=True
```

inventories/flat

```
[stuff]
10.64.5.78
```

group_vars/all.yml

```
---
test: "hey this works..."
```

playbooks/test.yml

```
---

- hosts: 10.64.5.78
  gather_facts: no
  tasks:
    - debug: var=test
```

Dockerfile.2.1.0 (probably can ignore all the extra packages)

```
FROM python:2

RUN pip install six boto awscli cryptography requests python-consul

RUN pip install ansible==2.1.0
```

Dockerfile.2.1.1

```
FROM python:2

RUN pip install six boto awscli cryptography requests python-consul

RUN pip install ansible
```

Dockerfiles were build with the following command

```
docker build -f Dockerfile.2.1.1 -t ansible-test:2.1.1 .
```

Then I ran the following commands

```
 $  docker run -ti --rm -v $(pwd):/stuff -w /stuff ansible-test:2.1 ansible-playbook playbooks/test.yml

PLAY [10.64.5.78] **************************************************************

TASK [debug] *******************************************************************
ok: [10.64.5.78] => {
    "test": "hey this works..."
}
```

```
PLAY RECAP *********************************************************************
10.64.5.78                 : ok=1    changed=0    unreachable=0    failed=0

 $  docker run -ti --rm -v $(pwd):/stuff -w /stuff ansible-test:2.1.1 ansible-playbook playbooks/test.yml

PLAY [10.64.5.78] **************************************************************

TASK [debug] *******************************************************************
ok: [10.64.5.78] => {
    "test": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
10.64.5.78                 : ok=1    changed=0    unreachable=0    failed=0
```

Both versions of ansible work if I move the playbook from the playbook directory to the current working directory. So it seems like the group_vars directory is being rendered according to the playbook location instead of the working directory that ansible-playbook is called in. 

To be fair, I have some older ansible projects that I haven't worked with in a long time (ansible 1.4 timeframe). Seems like I used to symlink the group_vars directory into my playbooks directory.

**Comment by kustodian** [comment]
`group_vars` should not be picked up from the current working directory. They should be read from the directory of the inventory file, or the playbook directory. What is happening in 2.1.1 is a bug which is now fixed in stable-2.1 branch and devel. In your example 2.1 is working correctly and the variable should be undefined.

**Comment by dacjames** [comment]
@kustodian In 2.0.x and 2.1.0 they are. Prior to 2.1.1, the following directory structure works:

``` sh
├── ansible.cfg
├── group_vars
│   ├── all.yml
│   ├── ...
├── inventories
│   ├── ec2.ini
│   ├── ec2.py
│   └── ..
├── playbooks
│   ├── adapter.yml
│   ├── ...
├── roles
│   ├── adapter
│   ├── ...
└── vars
    ├── jenkins.yml
    └── ... 

```

Aside: Ansible really could benefit from a concept of a "root" directory. Having to adjust imports when you reorganize your directories is no fun.

**Comment by kustodian** [comment]
@drybjed I updated my previous comment, but to repeat myself, 2.1.1 behavior is a bug which I reported (#16953) and it's not fixed.

I like the idea of root directory, but the reason why the devs don't want to implement it is because it is a security issue. For example if you run `ansible-playbook` from a random directory which has `group_vars` configured, that means Ansible could pic up those variables which can potentially make a lot of damage on managed hosts.

I asked for a similar thing with the `library` directory to be picked up from the current working directory, but it's the same deal. Someone could put a malicious module in the library dir with the same name as some Ansible module which could do a lot of damage.

**Comment by drybjed** [comment]
I was summoned here kinda from the left field, but oh well. :-)

Since you are talking about inventories and "root Ansible directories", want to hear my take on this? I handle this issue via a custom Python script which generates `ansible.cfg` in the current directory. This file contains all the necessary paths to roles, playbooks, library, plugins, etc. which are located in one central location in `~/.local/` (or elsewhere). The layout of this "project directory" looks something like this:

```
.
├── ansible/
│   ├── inventory/
│   │   ├── group_vars/
│   │   │   ├── all/
│   │   │   └── groupname/
│   │   ├── hosts
│   │   └── host_vars/
│   │       └── hostname/
│   ├── playbooks/
│   └── roles/
└── ansible.cfg
```

I run `ansible-playbook` (well, technically my script that handles playbook lookup and passes arguments to `ansible-playbook`) from the "root directory", where the `ansible.cfg` is located. If you don't know, the Ansible commands read the `ansible.cfg` file from the current directory if it's present. The contents of `ansible.cfg` look something like this:

```
[defaults]
filter_plugins = ~/.local/share/debops/debops-playbooks/playbooks/filter_plugins:/usr/share/ansible/filter_plugins
hostfile = ansible/inventory
roles_path = ansible/roles:~/.local/share/debops/debops-playbooks/playbooks/roles:/etc/ansible/roles
connection_plugins = ~/.local/share/debops/debops-playbooks/playbooks/connection_plugins:/usr/share/ansible/connection_plugins
library = ~/.local/share/debops/debops-playbooks/playbooks/library:/usr/share/ansible/library
vars_plugins = ~/.local/share/debops/debops-playbooks/playbooks/vars_plugins:/usr/share/ansible/vars_plugins
ansible_managed = This file is managed remotely, all changes will be lost
action_plugins = ~/.local/share/debops/debops-playbooks/playbooks/action_plugins:/usr/share/ansible/action_plugins
callback_plugins = ~/.local/share/debops/debops-playbooks/playbooks/callback_plugins:/usr/share/ansible/callback_plugins
lookup_plugins = ~/.local/share/debops/debops-playbooks/playbooks/lookup_plugins:/usr/share/ansible/lookup_plugins
```

So, in some cases Ansible looks for things in a central `~/.local/share/debops/debops-playbooks/` directory, and after that in `/usr/share/ansible/` directory. The inventory file is located in `ansible/inventory/hosts` (it's an INI file), so Ansible knows where to look for the inventory for this current "project" (say, development or production environment). If I want to switch to a different environment, I just `cd` into another directory.

Notice that the inventory directory has `group_vars/` and `host_vars/` directories in the same "level" as the `hosts` file. Even though I tell Ansible to read the inventory from a directory, it looks inside for the `hosts` INI file and when it finds one, it reads the group and host variables from the directories beside that file.

I think that the suggested directory layout presented in [Ansible Best Practices](https://docs.ansible.com/ansible/playbooks_best_practices.html) is misleading, especially that it shows having different inventory INI files for production and staging environments in the same directory, which might lead to serious issues down the road. Using separate directories for each environment you manage, along with shared roles and playbooks, worked well so far, and I suggest you try it some time. :-)

**Comment by dacjames** [comment]
> I like the idea of root directory, but the reason why the devs don't want to implement it is because it is a security issue. 

I think it would have the opposite effect. In my mind, the "root" directory would not be the working directory of the program. Instead ansible would mark the root in some way, much like git does with it's .git directory (perhaps using ansible.cfg as the marker or even a setting in ansible.cfg). Then the logic would be something like: for a given playbook walk up the tree until you find the root, and progress from there. Like Git, you probably want a maximum search depth. When running ansible by itself, searching from the current directory with an optional parameter to set the root would be ideal (again, like Git). In that setup, some random group_vars folder would be ignored entirely.

I don't like using the playbook as the root of the path because we have dozens of different playbooks and it's nice to be able to organize them logically.

**Comment by kustodian** [comment]
@drybjed I agree with you about the best practices not showing best practices. Every environment should have it's own directory which includes an inventory file and the `group_vars` and `host_vars` directories.

@dacjames why would you use the playbook directory as the root one? What I would suggest is that you have a project root from which you always run `ansible-playbook`, e.g. like this:

```
├───inventories/
│   ├───production/
│   │   ├───group_vars/
│   │   ├───host_vars/
│   │   └───hosts.ini
│   ├───staging/
│   │   ├───group_vars/
│   │   ├───host_vars/
│   │   └───hosts.ini
│   └───test/
│       ├───group_vars/
│       ├───host_vars/
│       └───hosts.ini
├───library/
├───playbooks1/
│       ├───web1.yml
│       └───web2.yml
├───playbooks2/
│       ├───db1.yml
│       └───db2.yml
├───roles/
└───ansible.cfg
```

This directory could have an `ansible.cfg` in which you can define whatever you need (e.g. we define the `roles_path = roles` and `library = library` so that no matter from which directory we run playbooks they can pickup all the roles and our custom modules.

**Comment by cmebert** [comment]
This is also directly affects Tower's ability to pull a dynamic inventory and use local authentication keys.  We have used group_vars to allow different authentication parameters to be used simultaneously (different ssh keys for example) when running plays against EC2 instances.  This worked correctly in 2.1.0 (2.1.0.0-1ppa~trusty), and broke in 2.1.1 (2.1.1.0-1ppa~trusty).    

If the required structure has changed, please update the documentation prior to releasing code to your public repo without a beta tag and voluntary opt in.

**Comment by bcoca** [comment]
So this has drifted from the original issue, which I cannot reproduce when group/host_vars are adjacent to the inventory or playbook files, only when they are a level up, which was never a feature or supported.

As such I'm closing this issue, I do think we might benefit from a 'project/base/root dir' that we can pass to Ansible to use as another place to look for things, but that belongs in proposals. http://github.com/ansible/proposals

**Comment by cmebert** [comment]
you're going to close this issue without any updated documentation or best practice info?  You may have "fixed" a bug, but you did break a lot of currently structured repositories that were created / based on the docs you guys provided.  We had to roll back to 2.1.0 to fix our environment, and i STILL do not see any updated documentation.  

Following this guide: http://docs.ansible.com/ansible/playbooks_best_practices.html   things are broken.  Again, if there's a better way to structure things please just update the docs.

**Comment by mmoleksf** [comment]
HI all!

As I see that there has been quite a few issues with vars in general. I do also have one question here regarding this if someone could please help me out. I cannot get any answer from Ansible/Red Hat. We are looking into buying license for 1000+ servers and therefore you would expect to have some more support that 3 email a week and even trhis 3 emails do not answer your questions..ok sorry for a little bit off topic. So my issue is as follows:

I want to use vault for storing ssh key pairs. All good until you come to a point that you want to  use multiple access keys in one run. So the idea is ( Cause we have Tower also ) to run one job and execute it on multiple servers that require different initial ssh credentials. 

My issue here is how to reference this credentials from vault to actual inventory file?

Example:

[servers_aws]
xx.xx.xx.xx   ansible_ssh_user=ubuntu ansible_ssh_private_key_file=_path_to_pem_file_  hostname=test-server env=test app_name=streaming platform=test private_ip=0.0.0.0

So this works as expected. But can someone tell me if its possible to replace the path for pem file with vars YAML file which contains the PEM key so it can be used as initial connection credentials?

Thx!

**Comment by jamesdh** [comment]
@mmoleksf This is not related to the discussion at hand, and is not even an "issue" per se. Please take a look at the Ansible forum for support: https://groups.google.com/forum/#!forum/ansible-project

**Comment by highbass** [comment]
just upgraded last night and it broke my structure for me... seems like much like others I must have mis-understood what best practice was trying to depict. Moved group_vars into my inventory folder and it seems to resolve the issue.

**Comment by ghost** [comment]
Ewwww... Had to downgrade from 2.1.1.0 to 2.1.0.0! 3 hours and I finally found the problem!   :-P

My playbook run with 2.1.1.0 is ignoring the default settings located under "ansible/group_vars/all"! While 2.1.0.0 works just fine.

How to upgrade to 2.1.1.0 easily? Is there any new subdir recommendation?

Does Ansoble 2.2.0.0 behaves the same way as 2.1.1.0?

Here is my Ansible subdir structure that works with 2.1.0.0 but doesn't work with 2.1.1.0:

https://github.com/sandvine-eng/svauto/tree/dev/ansible

Cheers!
Thiago

**Comment by kustodian** [comment]
@tmartinx that structure looks fine, because the `hosts` file and `group_vars` directory are in the same directory. What exactly isn't working and how do you run your playbooks?

**Comment by ghost** [comment]
@kustodian it is super easy to reproduce this problem! Let me try to exemplify for you...

EDITED:

_Note: I'm creating the hosts AND the top-level-playbook.yml files, inside of a tmp/ subdir_

I'm running the playbook like this:

```
cd ansible/
mkdir tmp
```

Create those 2 files (Inventory and Playbook)

```
ansible-playbook -i tmp/openstack-hosts tmp/top-level-playbook.yml
```

Where the "tmp/openstack-hosts" contains:

```
[svsde-servers]
10.124.1.45 ansible_user=sandvine base_os=centos7

[svpts-servers]
10.124.1.44 ansible_user=sandvine base_os=centos7

[svspb-servers]
10.124.1.46 ansible_user=sandvine base_os=centos6
```

And the "tmp/top-level-playbook.yml" contains:

```
- hosts: svspb-servers
  user: sandvine
  become: yes
  roles:
  - centos-network-setup

- hosts: svsde-servers
  user: sandvine
  become: yes
  roles:
  - centos-network-setup

- hosts: svpts-servers
  user: sandvine
  become: yes
  roles:
  - { role: centos-network-setup, setup_server: 'svpts' }
```

It fails with 2.1.1.0, while works perfectly with 2.1.0.0!

The error with 2.1.1.0 is this:

```
TASK [centos-network-setup : centos6 - copy eth2 config file] ******************
fatal: [10.124.1.46]: FAILED! => {"failed": true, "msg": "The conditional check 'setup_server == 'svpts'' failed. The error was: error while evaluating conditional (setup_server == 'svpts'): 'setup_server' is undefined\n\nThe error appears to have been in '/home/tmartins/svauto/ansible/roles/centos-network-setup/tasks/centos6.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: centos6 - copy eth2 config file\n  ^ here\n"}
```

It is complaining that the variable "setup_server" is undefined! But it IS defined, right here:

https://github.com/sandvine-eng/svauto/blob/dev/ansible/group_vars/all#L134

So, I have to downgrade to 2.1.0.0, to be able to use Ansible again... Since 2.1.1.0 is apparently, completely ignoring the file "group_vars/all".

There is an ugly workaround to make it work with 2.1.1.0, which is to re-define the "missing" variable inside of that role, like this:

```
cd ansible
mkdir roles/centos-network-setup/vars
echo "setup_server: null" > roles/centos-network-setup/vars/main.yml
```

But, then, other roles starts to complain about its "undefined" variables!

The only solution that I've found, is to downgrade 2.1.1.0, to 2.1.0.0, then, all good!

Hope it helps...

Cheers!
Thiago

**Comment by ghost** [comment]
BTW, same problem with Ansible-2.2.0.0 (from ppa:ansible/ansible), I'm running Ansible from an Ubuntu 16.04 machine, "apt upgraded" today.

Is there a new, undocumented, "Directory Layout"? After reading more comments here, I'm seeing that many people are talking about outdated documentation, is that correct?

http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout <- outdated?

**Comment by ghost** [comment]
Oh, I found a much better workaround!

```
cd ansible
cd tmp
ln -s ../group_vars
```

Looks like that Ansible +2.1.1.0 is not including the "./group_vars/all" located inside of the current directory, where I'm running `ansible-playbook` command from.

Until, with 2.1.0.0, it is good to use an "ansible/tmp", to create your "Dynamic Inventory" (like just an "auto-generated" _hosts_ file), like "./tmp/openstack-hosts-f42342" and your Top-Level Palybook as "./tmp/top-level-playbook-f42342.yml" while using the "./group_vars/all" located inside of main Ansible's subdir "ansible/".

So, a even better workaround for me, is to stop using "ansible/tmp" subdir to run my "inventory / playbooks" from, then, looks like a more proper fix in my side.

 Like this:

```
cd ansible/
mv tmp/openstack-hosts tmp/top-level-playbook.yml .
ansible-playbook -i openstack-hosts top-level-playbook.yml
```

Voialá! Ansible 2.1.1.0 or 2.2.0.0 are back to business!

**Comment by JamesUoM** [comment]
Really? This is bad joke. I'm trying to port code from 1.6.x (yes) to 2.1.2.0 

```
inventory/
        hosts
group_vars/
        all
hosts_vars/
```

worked under 1.6 and now neither that nor this works:

```
hosts
group_vars/
        all
hosts_vars/
```

-vvv has improved since 1.6 but it really needs to tell us what files it is looking for and finding.

EDIT:

OK it appears playbook files don't pick up the groups_vars eg I have site.yml which includes number of playbook yml files like:

```
---
- hosts: foo-hosts
  var_files:
       - "../../vars/{{ project_environment }}/general.yml"
```

where project_environment is define in group_vars/all, will fail

**Comment by t2d** [comment]
Why has this issue been closed?

I just updated from ansible 2.0 to 2.2.1.0 and it broke my vagrant test setup. This setup has been working since 1.something.

```
ansible.cfg
hosts
host_vars
group_vars
roles
site.yml
Vagrantfile
tests/ansible.cfg
tests/vagrant.yml
```
To make ansible 2.2 work again, I had to create a symbolic link for group_vars as suggested in  https://github.com/ansible/ansible/issues/16956#issuecomment-259184869 by @tmartinx.

Why does ansible now use the path of the yaml file for vars lookup instead of the working directory?

**Comment by kustodian** [comment]
@t2d because that behavior was a bug which was not documented anywhere in the documentation, so even if you used it in the first place, it was the wrong way to do it.

Anyway everyone, there is no point in replying to this issue any more, because this will never be reverted back to the state it was in 2.0, because it was a bug. Just modify your playbook directory structure to make it work and be done with it.

**Comment by ghost** [comment]
So what is that structure?! I think that's the crux of the complaint here, is that the docs say something that doesn't work in practice. Also, the behavior around this critical feature keeps changing from the perspective of the user. Can you at the very least document what we're supposed to do here? I've been using Ansible since 1.8, and now all my playbooks are broken yet again and I don't know why. It very much is like hitting a moving target, and it's to the point that I've stopped upgrading Ansible because no matter what it's going to break all my playbooks somehow. 

Please advise.

**Comment by fostermi** [comment]
Just ran into this using Ansible v 2.3. What IS the structure? My group_vars and hosts_vars directories ARE adjacent to my hosts file as mentioned several times but not being picked up.

./inventory/dev
./inventory/dev/group_vars/myserver
./inventory/dev/host_vars/myserver
./inventory/dev/hosts

Any ideas?

**Comment by harrocan** [comment]
2.3 - still not working, group_vars are not even considered

**Comment by kustodian** [comment]
All supported versions of Ansible work with inventories and its group_vars/host_vars as it is described in the documentation. There is no point in replying in this issue any more because you won't get an answer. If you think that it's not working as it is documented please create a new bug request, or if you want to discuss this further or ask for help please do so on the [official forums](https://groups.google.com/forum/#!forum/ansible-project), or on IRC in channel **#ansible**.

**Comment by m00dawg** [comment]
I'm not sure why Ansible is being so stubborn and unhelpful with this. I think it's very much a bug not a feature. It required significant rework at my day job (where we are, of note, a paying customer) to the point we thought about switching to something else.

I find it both disappointing and aggravating the rhetoric here is with the tone of "move along peon." There are valid questions and concerns being addressed here directly related to this issue and it's shameful. I also disagree with the avenues to discuss it being a Google Group or IRC. This is a software engineering project - what better way to discuss legitimate issues than here?

I'm dumbfounded, frankly. Such a great product that gets marred by apathy towards the community that helped it rise to what is still a very good tool but one that is marred by poor behavior.

**Comment by kustodian** [comment]
@m00dawg I'm part of the community the same as you are and this is an issue which was resolved, so there is no reason to continue discussing the decision how the issue was resolved in here. If you don't agree with how it was resolved, you should raise a new one, or discuss it as I mentioned above, that's all I'm trying to tell you. Replying in this issue won't make a difference.

**Comment by bcoca** [comment]
got pinged in irc for this one, just to reiterate, closed issues don't get seen by commiters so comments here  are mostly a waste.

IF you have reproducible bug, open a new ticket, we suggest using IRC or ML first to clarify if it is a bug or not.

The original posting for this ticket was not reproducible, which is why it is closed. Many other posts complained about 'not working' either w/o showing examples or relying on CWD, which is NOT supported and was actually removed as it was a security vulnerability.

To keep this from wasting everybody's time I'm going to lock this issue now.
