### ISSUE TITLE
Ansible reads group_vars from cwd with precedence

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#16953]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu/CentOS
##### SUMMARY

If the inventory and the playbook are not in the current working directory (cwd), and `group_vars` exists in cwd, Ansible will read variables from `cwd/group_vars` and will even give them precedence. This only happens if the same file exists in both group_vars of cwd and the inventory. The 
##### STEPS TO REPRODUCE

Here is a simple repro. Create a file structure like this:

```
├── group_vars
│   └── g1
├── inventories
│   └── test
│       ├── group_vars
│       │   └── g1
│       └── hosts
└── playbooks
    └── site.yml
```

``` yaml
# group_vars/g1

---
var1: "Set in CWD"
```

``` ini
# inventories/test/hosts
[g1]
localhost
```

``` yaml
# inventories/test/group_vars/g1

---
var1: "Set in inventory"
```

``` yaml
# playbooks/site.yml

---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - debug: var=var1
```

Run `site.yml` with this inventory:

```
ansible-playbook -i inventories/test/hosts playbooks/site.yml
```
##### EXPECTED RESULTS

It should display `var1: "Set in inventory"`.
##### ACTUAL RESULTS

It actually displays the value of the variable defined in cwd:

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "var1": "Set in CWD"
}
```

**Comment by jinnko** [comment]
I believe this is a similar issue to #16956

**Comment by kustodian** [comment]
Any news about when will this issue big fixed, since this is a security concern. Variables which Ansible reads from the current working directory can bet set that way to make the managed host(s) unusable.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by GoodHaHa** [comment]
Hill,kustodian
      I have the same problem. At present, Which version to solve this problem?

**Comment by kustodian** [comment]
@GoodHaHa 2.1.2 should fix the issue.

**Comment by GoodHaHa** [comment]
@kustodian Thinks very much.
