### ISSUE TITLE
consul module: port should be optional when registering services

### ISSUE THREAD

**Issue by builtbybrayne** [ansible/ansible#17031]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

consul
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

Consul service definitions do not require a port when creating a service definition. (see https://www.consul.io/docs/agent/services.html) 

But the consul module does. So, if the `service_port` field is not supplied the task returns an error.

Surely the consul module should mirror the official consul api.
##### STEPS TO REPRODUCE

```
- name: Register some service with consul
  consul:
    service_name: "myService"
```

##### EXPECTED RESULTS

The service should be registered without a port
##### ACTUAL RESULTS

The following error is returned

```
service_name supplied but no service_port, a port is required to configure a service. Did you configure the 'port' argument meaning 'service_port'?
```

**Comment by nitzmahone** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
