### ISSUE TITLE
Setup module could use a parameter for non-default location of ohai and facter

### ISSUE THREAD

**Issue by szaydel** [ansible/ansible#1704]
There are instances where /usr/bin is not being used for ohai and/or facter, and while a symlink should probably there anyway, perhaps it is a good option to add allow collection from non-default locations. It should be a trivial change based on what I am seeing in the setup module.

**Comment by mpdehaan** [comment]
Ansible itself does not pass any parameters to the setup module, so even if
it supported them, this does not work so well.

I'm ok with it using the path lookup functions to look in alternative
locations, though for anything non-standard it should use the symlink.

While it could be a config setting what args to pass to setup (default
None), this is not such a good idea because it is very likely to be host
specific.

This implies an inventory variable, ex, "ansible_setup_params" or some
such, at which point, I really prefer the symlink than the complexity
overhead this would entail.

**Comment by szaydel** [comment]
Yeah, I can see what you mean. I am thinking then that perhaps a separate module may be a better way to do this. It would be nice though to have a way of collecting from several fact systems into one common structure.

**Comment by mpdehaan** [comment]
It is pretty easy, if you want, to fork the fact module.   If you call it
by name, you could invoke with:

```
hosts: whatever
gather_facts: False
tasks:
   - action: site_facts
```

And that is all you need!

**Comment by szaydel** [comment]
Thank you very much for this.
