### ISSUE TITLE
unarchive module error

### ISSUE THREAD

**Issue by zhijieqing** [ansible/ansible#17146]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report

如果zip文件包含中文文件，则解压报错
If the zip file contains the Chinese document, then extract the error
##### ANSIBLE VERSION

```
1.9.4
```
##### OS / ENVIRONMENT

CeontOS 7.0
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```
[root@cloud1 ccm_install]# ansible 127.0.0.1 -m unarchive -a 'src=ccm_tomcat.zip dest=/tmp/test/'
127.0.0.1 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 1911, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/u
narchive\", line 290, in main\n    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 1097, in set_fs_attributes_if_different\n    file_args['path'], file_args['secontext'], changed\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 869, in set_context_if_different\n    cur_context = self.selinux_context(path)\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 813, in selinux_context\n    self.fail_json(path=path, msg='path %s does not exist' % path)\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 1553, in fail_json\n    self.add_path_info(kwargs)\n  File \"/root/.ansible/tmp/ansible-tmp-1471592891.55-43328379715224/unarchive\", line 1125, in add_path_info\n    if os.path.exists(path):\n  File \"/usr/lib64/python2.7/genericpath.py\", line 18, in exists\n    os.stat(path)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 35-40: ordinal not in range(128)\n",     "parsed": false
}

```

**Comment by dagwieers** [comment]
That's an old Ansible version and I don't think we are actively fixing issues in Ansible 1.9 or older.

If you have a related issue with Ansible v2.1 please let us know, and please report the issue in the correct repository: https://github.com/ansible/ansible-modules-core/issues

Thanks !

wontfix

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
