### ISSUE TITLE
Loop  control loop_var value is not always inherited inside nested includes

### ISSUE THREAD

**Issue by archf** [ansible/ansible#17148]
##### ISSUE TYPE
- Bug Report

Using `loop_var` with `loop_control` and include tasks.
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
```
##### CONFIGURATION

Vanilla.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Loop  control `loop_var value` is  not inherited inside nested includes depending on context of include. This seems a variant of #16542.
##### STEPS TO REPRODUCE

Given this:

```

---
# top.yml

- hosts: localhost

  vars:
    topvars:
      - name: foo
        gid: 1111
      - name: bar
        gid: 9111

  tasks:
    - include: middle.yml
      with_items: "{{topvars}}"
      loop_control:
        loop_var: topvar
```

```

---

# middle.yml

- debug: msg="{{topvar}} from middle"
- include: bottom.yml
```

```

---
# bottom.yml

- debug: msg="{{topvar}} from bottom"
```
##### EXPECTED RESULTS

Note that `debug: msg="{{topvar}} from middle"` is missing in that run. Actually, as long as there is **no task before** `- include: bottom.yml` inside `middle.yml` everything works fine. For instance, if you move `debug: msg="{{topvar}} from middle"` after the include, then and only then it will work as expected.

```
ansible-playbook top.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /home/archf/repos/ansible-bug/roles/test_role/tasks/middle.yml for localhost
included: /home/archf/repos/ansible-bug/roles/test_role/tasks/middle.yml for localhost

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "{u'gid': 1111, u'name': u'foo'} from bottom"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "{u'gid': 9111, u'name': u'bar'} from bottom"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

We see here that `topvar` is undefined but it should...

```
ansible-playbook -vvv top.yml                                         1
Using /home/archf/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: top.yml **************************************************************
1 plays in top.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: archf
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1471608307.84-279575813548995 `" && echo ansible-tmp-1471608307.84-279575813548995="` echo $HOME/.ansible/tmp/ansible-tmp-1471608307.84-279575813548995 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpO7eqbI TO /home/archf/.ansible/tmp/ansible-tmp-1471608307.84-279575813548995/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/python /home/archf/.ansible/tmp/ansible-tmp-1471608307.84-279575813548995/setup; rm -rf "/home/archf/.ansible/tmp/ansible-tmp-1471608307.84-279575813548995/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [include] *****************************************************************
task path: /home/archf/repos/ansible-bug/roles/test_role/tasks/top.yml:15
included: /home/archf/repos/ansible-bug/roles/test_role/tasks/middle.yml for localhost
included: /home/archf/repos/ansible-bug/roles/test_role/tasks/middle.yml for localhost

TASK [debug] *******************************************************************
task path: /home/archf/repos/ansible-bug/roles/test_role/tasks/middle.yml:4
ok: [localhost] => {
    "msg": "{u'gid': 1111, u'name': u'foo'} from middle"
}

TASK [debug] *******************************************************************
task path: /home/archf/repos/ansible-bug/roles/test_role/tasks/bottom.yml:4
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'topvar' is undefined\n\nThe error appears to have been in '/home/archf/repos/ansible-bug/roles/test_role/tasks/bottom.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug: msg=\"{{topvar}} from bottom\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'top.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1
```

**Comment by jimi-c** [comment]
Hi @archf, following up on this it appears the issue was resolved along with previous fixes for includes/inheritance/etc. I've tested against devel, stable-2.2 and stable-2.1 and the output on all three is as follows:

<pre>
$ ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml ************************************************************************************************************************************************************************************************
1 plays in test.yml
PLAY [localhost] **************************************************************************************************************************************************************************************************
TASK [include] ****************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/test.yml:11
included: /home/jamesc/testing/17148/middle.yml for localhost
included: /home/jamesc/testing/17148/middle.yml for localhost
TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/middle.yml:1
ok: [localhost] => {
    "msg": "{u'gid': 1111, u'name': u'foo'} from middle"
}
TASK [include] ****************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/middle.yml:2
included: /home/jamesc/testing/17148/bottom.yml for localhost
TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/bottom.yml:1
ok: [localhost] => {
    "msg": "{u'gid': 1111, u'name': u'foo'} from bottom"
}
TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/middle.yml:1
ok: [localhost] => {
    "msg": "{u'gid': 9111, u'name': u'bar'} from middle"
}
TASK [include] ****************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/middle.yml:2
included: /home/jamesc/testing/17148/bottom.yml for localhost
TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/17148/bottom.yml:1
ok: [localhost] => {
    "msg": "{u'gid': 9111, u'name': u'bar'} from bottom"
}
PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0   
</pre>

So I'll go ahead and close this now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
