### ISSUE TITLE
Jinja2 math filter: implement `add()` function

### ISSUE THREAD

**Issue by muxator** [ansible/ansible#17205]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Jinja2 math filter: add `increment()` function
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

independent on configuration
##### OS / ENVIRONMENT

N/A
##### SUMMARY

There are situations in which, given a variable containing a list of ints:

``` yaml
list_of_ints: [ 1, 7, 8 ]
```

Someone may want to have the same list, but incremented by a fixed quantity, let's say 100:

``` yaml
incremented_list: [ 101, 107, 108 ]
```

Imagine for example having to run different instances of the same service on different ports, and having to pass a subset of the port list as a parameter to the service. In this case you really need to keep incremented_list as a separate (but correlated) list.

My proposal is enabling this:

``` yaml
# generates [ 101, 107, 108 ]
incremented_list: "{{ list_of_ints | map('increment', 100) | list }}"
```
##### STEPS TO REPRODUCE

The proposal is adding an `add()` function in https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/mathstuff.py and write the relevant documentation in order to enable this use case.

If you see some utility in this functionality I can prepare a patch for you to review.

**Comment by nitzmahone** [comment]
Sure, why not? I'd probably just call the filter `add` (might as well do `subtract` `multiply` and `divide` for completeness sake)- go ahead and file a PR, should be nice and simple...

**Comment by muxator** [comment]
Hi, I have created PR #17251.

The implemented functions are:
- `add`
- `subtract`
- `multiply`
- `divide`
- `modulo`

I have also updated the documentation, trying to mention that these filters won't be available in older Ansible versions.

**Comment by muxator** [comment]
In the spirit of this change, I am also proposing #17267 (`string_prefix` and `string_suffix`).

That functionality can be achieved by advanced users using `regex_replace` anyway, but maybe it makes sense to use simple functions for simple use cases.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this because you can already use operators to achieve the same thing (+ , - , / ...)

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by webknjaz** [comment]
@bcoca I've found a use case for `multiply` — I want to find products of a list of pairs of numbers (disk/block device sector sizes * sectors number). I realized that I couldn't just do `| zip | map('multiply')` which would be quite useful.
