### ISSUE TITLE
Ansible on Jenkins use wrong ansible.cfg file

### ISSUE THREAD

**Issue by rezastd** [ansible/ansible#17238]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
roles_path            = ./roles
gathering             = smart
stdout_callback     = default
callback_whitelist     = profile_tasks
nocolor                = 0
pipelining            = True
host_key_checking    = False
inventory    = environment/mensa_project
allow_world_readable_tmpfiles   = True

##### OS / ENVIRONMENT

Jenkins: Ubuntu 14.04
Host: Ubuntu 14.04

##### SUMMARY

I'm trying to build and deploy my project using jenkins with ansible. I created 2 playbooks which is build.yml and deploy.yml and it stored on bitbucket repository. When i run the deployment from jenkins, it runs good on the first step with build deploy and using its ansible.cfg file, but when on the second step jenkins not using the ansible.cfg file that i created for this project. so my deployment is failure on the deploy.yml
##### STEPS TO REPRODUCE

I run this command in the jenkins job configuration

```
ansible-playbook --version
ansible-playbook playbooks/Mensa_Build.yml --extra-vars "app_version=$BRANCH" -vvv 
ansible-playbook playbooks/Mensa_Deploy.yml -vvv
```

##### EXPECTED RESULTS

```
ansible-playbook 2.1.0.0
  config file = /jenkins-data/jenkins/jobs/Mensa Development Backend Deployer/workspace/ansible.cfg
  configured module search path = Default w/o overrides
+ ansible-playbook playbooks/Mensa_Build.yml --extra-vars app_version=release/0.2.0 -vvv
Using /jenkins-data/jenkins/jobs/Mensa Development Backend Deployer/workspace/ansible.cfg as config file
```
##### ACTUAL RESULTS

```
+ ansible-playbook playbooks/Mensa_Deploy.yml -vvv

Using /etc/ansible/ansible.cfg as config file
ERROR! the playbook: playbooks/Mensa_Deploy.yml could not be found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

```

**Comment by resmo** [comment]
We didn't see such a behavior in Jenkins, using it the same way for over 1 year. Further it is unlikely that the first playbook works and the second not. 

I assume the first playbooks modifies the environment in a way that ansible is affected. Probably try to make a playbook including the other playbooks and run them in "one" run.

``` yaml
# file: site.yml
- include: Mensa_Build.yml
- include: Mensa_Deploy.yml
```

and then:

```
ansible-playbook playbooks/site.yml --extra-vars "app_version=$BRANCH" -vvv 
```

needs_info

**Comment by jhawkesworth** [comment]
Hi, I suggest you either explicitly cd to the directory where you have the ansible.cfg that you want or set the environment variable.  How ansible.cfg is resolved is documented on this page: http://docs.ansible.com/ansible/intro_configuration.html

**Comment by rezastd** [comment]
hi resmo, does my first playbook change the environment?
here is my first playbook (build.yml) [this](https://github.com/rezastd/Mbuild_and_deply/blob/master/playbooks/Mensa_Build.yml). 
jhawkesworth, i run this playbook from my jenkins web, and how can i do that? thanks

**Comment by jhawkesworth** [comment]
@rezastd it depends on how you kick off ansible from your jenkins.  I use the 'send files over ssh' plugin (my jenkins runs on Windows), which lets you run a script before transferring files. I imagine you can just do the same thing if you are on linux by using whatever plugin allows you to call a script.

Looks like you are trying to get ansible to actually run your build instead of jenkins though.  Personally I would use jenkins to run things via a web ui, and maybe kick off builds, since it has lots of plugins to do that, and use ansible to deploy things, as its really good at hitting lots of machines at once.

'How do i do x' questions are usually best asked on the ansible-project google group or #ansible irc channel as many, many more people will see them than just the developers who use the bug tracker.  As such I'm going to close this ticket but please ask on the google group or irc if the above isn't enough information.
