### ISSUE TITLE
Documentation of static for task inclusion is non-existent

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#17297]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

static includes
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1c33b5a9f0) last updated 2016/08/30 16:04:37 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 5310bab12f) last updated 2016/08/30 16:05:21 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 2ef4a34eee) last updated 2016/08/30 16:05:04 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

static/dynamic includes are basically undocumented voodoo.

There is no documentation about how includes work now - the implementation differs from the original proposal, and there is undocumented magic about which includes are static and which are dynamic.
##### STEPS TO REPRODUCE

```
git grep static docsite/rst
```
##### EXPECTED RESULTS

Some references to static includes of task includes, particularly in the playbooks docs.

Things that aren't necessarily apparent:
- that a `static` modifier exists for task includes
- `static` defaults to true, which is basically reading the entire task file and skipping all items if the `include`'s `when` condition is false
- need to use `static: no` to get reasonable skipping of items
- `static` gets set to false when the `include` has a variable in it
- `static` does not get set to false just because you have a `when` condition
##### ACTUAL RESULTS

Mostly references to static inventory and a single reference to static includes of handlers. No useful docs exist on docs.ansible.com.

**Comment by jimi-c** [comment]
This was fixed in 9c311b6b1316e14fc140027c5015525279d284b3 (and tweaked in 4ba90a3817c1de5382e5f321662736e8c409487e).

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
