### ISSUE TITLE
with_dict/item.value behaves differently than with_dict/dict[item.key] in some cases

### ISSUE THREAD

**Issue by decalek** [ansible/ansible#17358]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

plugins/lookup/dict.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/alek/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

irrelevant
##### OS / ENVIRONMENT

Fedora 23
ansible-2.1.1.0-1.fc23.noarch
##### SUMMARY

Inconsistent behavior between `with_dict` and `with_items` with e.g. `{%raw%}`escape
##### STEPS TO REPRODUCE

```
- hosts: 127.0.0.1
  connection: local

  vars:
    dict:
      key: "{% raw %}{{ XXX }}{% endraw %}"

  tasks:

  - name: OK - XXX
    with_items: "{{ dict.keys() }}"
    debug:
      var: dict[item]

  - name: OK - XXX
    with_dict: "{{ dict }}"
    debug:
      var: dict[item.key]

  - name: Inconsistent - VARIABLE IS NOT DEFINED
    with_dict: "{{ dict }}"
    debug:
      var: item.value
```
##### EXPECTED RESULTS

`"item.value": "{{ XXX }}"`
##### ACTUAL RESULTS

`"item.value": "VARIABLE IS NOT DEFINED!"`

**Comment by jctanner** [comment]
Addressing the element of a dict item via the debug var= task seems to have been broken since the initial 2.x release. I can access item.key or item.value in 1.9.6, but can not in 2.x.

**Comment by jctanner** [comment]
"debug var=item" and setting a breakpoint in the plugin confirms that the correct datastructure comes back from the plugin ...

```
[{'key': u'tkey1', 'value': u'{{ XX1 }}'}]
```

The issue seems to be somewhere higher in the stack such as the way jinja accesses the methods or properties of "item"/"value".

**Comment by sivel** [comment]
The problem here, is in how the number of times the value is templated.

Using `{% raw %}` will only affect the first templating, as on the first template, `{% raw %}` and `{% endraw %}` will be removed.  The first time it is templated is in `with_dict: "{{ dict }}"` and then the second is part of how debug displays a value with `var`.

Using `!unsafe` will instead allow this to work in current versions:

```
  vars:
    dict:
      key: !unsafe "{{ XXX }}"
```

```
TASK [Inconsistent - VARIABLE IS NOT DEFINED] ************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'key': 'key', 'value': '{{ XXX }}'}) => {
    "ansible_loop_var": "item",
    "item": {
        "key": "key",
        "value": "{{ XXX }}"
    },
    "item.value": "{{ XXX }}"
}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
