### ISSUE TITLE
Template lookup|from_yaml fails if template evaluates to '[]'

### ISSUE THREAD

**Issue by alvaroaleman** [ansible/ansible#17397]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- template lookup
- from_yaml
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

```
##### SUMMARY

When using the template lookup on a template that evaluates to `[]`  and using the `from_yaml` filter on that, a `AttributeError: 'list' object has no attribute 'read` gets thrown.
##### STEPS TO REPRODUCE

``` shell
cat > var.j2 <<EOF
[]
{# comment #}
EOF

cat > playbook.yml <<EOF

---
- hosts: localhost
  gather_facts: false
  vars:
    var: "{{ lookup('template', 'var.j2')|from_yaml}}"
  tasks:
    - debug: var=var
EOF

```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: {{ lookup('template', 'var.j2')|from_yaml}}: 'list' object has no attribute 'read'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```

**Comment by georgepsarakis** [comment]
@alvaroaleman I think your solution does not resolve this issue. You are converting the list to its string representation which may bring other issues.

I assume that the origin of the problem starts from the `template` lookup module behavior and if you notice [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/template/__init__.py#L331), lists are converted to actual list objects when rendering the template. This explains the error since `yaml.safe_load` expects either string or a file object that can read from, thus raising the reported error.

The solution is this:

```
{{ lookup('template', 'var.j2', convert_data=false) | from_yaml }}"
```

I am guessing that this should be added in the documentation.

**Comment by alvaroaleman** [comment]
What I did in my Ansibole code was ``{{ lookup('template', 'var.j2'|string|from_yaml }}', which works as well.

Still I am not sure if just adding something to the docs is sufficient, because the error is far from self-explanatory.

I agree that converting anything that comes into `from_yaml` to string is probably a bit over the top, what about doing that just for lists and dicts @georgepsarakis?

**Comment by georgepsarakis** [comment]
The only global solution that I can think of is the following:

```
def from_yaml(data):
      if not isinstance(data, basestring):
          return data
      return yaml.safe_load(data)
```

What do you think?
