### ISSUE TITLE
connection: chroot is ignored in ansible 2.1.1.0 (and in latest trunk)

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#17395]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Core
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

N/A - running rom Ubuntu
##### SUMMARY

I have this in my playbook:

```
  roles:
    - { role: common, connection: chroot, tags: [ 'minimal' ] }
```

In older version of ansible, this would run the "common" role with connection: chroot, but in 2.1.1.0 I just get: fatal: [testimage]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
##### STEPS TO REPRODUCE

Add a role with connection: chroot

```
  roles:
    - { role: common, connection: chroot, tags: [ 'minimal' ] }
```

##### EXPECTED RESULTS

It should run with connection: chroot 
##### ACTUAL RESULTS

Unfortunately connection: chroot is ignored and it tries to ssh to the host instead

**Comment by tetherit** [comment]
Ah, seems this was renamed to "ansible_connection" now, closing.

**Comment by tetherit** [comment]
Ah, ansible_connection breaks local_action so that's not a solution. Any ideas why connection: is ignored in the above on 2.1.1.0? - It wasn't ignored in the past.

**Comment by jimi-c** [comment]
Yes, disallowing a few things from regular attributes because they're commonly used as param names was something we changed in 2b02e8e2b43a7b5e10e0c12b0bbecedfb00f50c0. At some point we probably need to revisit that decision, since we've tried to move users away from specifying params in the top-level dictionary for the role.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
