### ISSUE TITLE
speed up documentation build (webdocs)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#17406]
I know this has been talked about a few times, but I couldn't find a bug.

Lets use this to record our thoughts on how to improve this.
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

n/a
##### ANSIBLE VERSION

all
##### SUMMARY

It's current taking XXX minutes to do `make webdocs`

This is an issue as
- It's annoying to contributors who want to fix things
- It's too long to add to the CI pipeline
##### STEPS TO REPRODUCE

`make webdocs`
##### EXPECTED RESULTS

Build within 15 minutes
##### ACTUAL RESULTS

Build takes over 30 minutes

**Comment by jhawkesworth** [comment]
I would love to be able to do make web docs for a single module.

I had a look a little while back and there seemed to be some limited support for parallel building in later versions of sphinx, so that might be something to explore.

May not be possible due to links between modules but I wonder if it would be possible to fork and build each of the module categories e.g. cloud, windows etc simultaneously.

**Comment by gundalow** [comment]
We should set a more sensible number for CPUs
http://stackoverflow.com/questions/2527496/how-can-i-write-a-makefile-to-auto-detect-and-parallelize-the-build-with-gnu-mak

Need to get timings from Jenkins non-production run before and after making that change as well

**Comment by sivel** [comment]
This should have already been solved in https://github.com/ansible/ansible/commit/2979488b

```
$ time CPUS=8 make webdocs
[...]
real	10m0.994s
user	59m59.467s
sys	1m6.477s
```

On a host with 32 cores, specifying `CPUS=32`, this took 2m48.73s

**Comment by abadger** [comment]
@sivel -- yeah, the problem is the default value of CPUS is 1 and we aren't setting a higher number anywhere when actually invoking it.

Here's some timings that I just did on my laptop:

* Baseline on my laptop:  34:45.21 total
* Using CPUS=8   9:22.04 total
  * However, I think this may be what's causing the problems with highlighting yaml code blocks.  I'll have to look into that.
* CPUS=8 + python3 shebang in build-site.py: 7:55.11 total

So both using python3 (3.5) and parallelizing the build speed up the docs build.

**Comment by sivel** [comment]
It appears in at least 1 case I have checked, that the YAML is invalid. In other locations, the data is not YAML at all, which I guess is ok.

> ansible/docsite/rst/dnf_module.rst:99: WARNING: Could not lex literal_block as "yaml". Highlighting skipped.

```
ScannerError: while scanning an alias
  in "<string>", line 19, column 11:
        name: *
              ^
expected alphabetic or numeric character, but found '\n'
  in "<string>", line 19, column 12:
        name: *
               ^
```

As for CPUS, I think we should calculate that if possible.  A function I have used a lot (brought over from gunicorn at some point is)

```
def cpuCount():
    if not hasattr(os, "sysconf"):
        raise RuntimeError("No sysconf detected.")
    return os.sysconf("SC_NPROCESSORS_ONLN")
```

We could put that directly in build-site.py but allow for some override.

I ran into problems with the python3 part, as it's a slightly complicated to get `make webdocs` to run in my virtualenv for ansible, which uses python2, if the shebang is python3.

I guess while we are at it, pypy speeds it up too.  On my same host where I used `CPUS=8`, using pypy, sped the process up to `3m27.072s`.

**Comment by gundalow** [comment]
This should fix all warnings & errors with doc/docsite/rst apart from no toctree references to ROADMAP* https://github.com/ansible/ansible/pull/20005

**Comment by bcoca** [comment]
I didn't realize this, but a few days back I added this to make file:
```
CPUS := $(shell nproc)
```

**Comment by alikins** [comment]
See https://github.com/ansible/ansible/pull/20237

That gets the buildtime for me down to about 1min without using '-j' and about 30s with it.

**Comment by alikins** [comment]
os.sysconf("SC_NPROCESSORS_ONLN") and/or nproc will include cpu threads/hyperthread cpus in the count, which is sometimes too many.

**Comment by abadger** [comment]
Bunch of speedups have been merged.  Is this ticket now ready to be closed?

**Comment by gundalow** [comment]
Closing as we are now a lot faster. 

We may have to do other things in the future, that that's a different issue. Thanks everyone that helped with this.
