### ISSUE TITLE
ansible-pull does not always update git repository causing orphaned machines

### ISSUE THREAD

**Issue by nzjrs** [ansible/ansible#17454]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-pull
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubunutu 14.04
##### SUMMARY

ansible-pull does not update the git repository if no hosts match. This can lead to a situation of orphaned machines if at some point they are not listed in the inventory file. As ansible-pull is usually used on machines with which one has no direct communication, this leads to them being permanently lost (unconfigurable in the future)
##### STEPS TO REPRODUCE
- configure role for MachineA
- install ansible-pull on MachineA, to be executed as a cron job every hour

```
ansible-pull --accept-host-key -d /XX --key-file /XX--url='XX' --sleep=10 --checkout=master --inventory-file /XX/production site.yml
```
- mistakenly remove MachineA from inventory
- ansible-pull runs on MachineA and updates git

Now the next time ansible-pull runs on MachineA it will abort before updating the repository because `ERROR! Specified --limit does not match any hosts`
##### EXPECTED RESULTS
- adding MachineA back to inventory will allow ansible to configure that machine
##### ACTUAL RESULTS
- MachineA is now in a permanently unconfigurable state. The git repository checkout must be deleted to allow it to be configured again. If one has no direct access to the machine it is now unrecoverable from this error. To reconfigure the machine it must be _first_ added back to the inventory, and then the git checkout must be deleted

**This means, a single misconfiguration where MachineA is dropped from the inventory file yields a permanently orphaned MachineA that will never update the git repository and is now unprovisionable / unconfigurable remotely.**

**Comment by robinro** [comment]
A workaround for your issue:
Put the reference to your inventory as `hostfile = /XX/production/site.yml` in a file called `ansible.cfg` in your playbook directory. Then run `ansible-pull` without giving it the `--inventory-file` argument.

The general issue is, that ansible needs the `--inventory` and `--limit` arguments **twice**, once for pulling the repo updates and once to run your playbook. If you pass arguments to `ansible-pull` they will be **used for both**, thus not updating the repo if your host is not in the inventory.

If you don't pass the arguments to `ansible-pull`, but put them in an **`ansible.cfg`** file inside your repository, for the git-clone the defaults will be used, which include `localhost` and thus always run, while for your playbook the information of the config file is used.

Putting settings in `ansible.cfg` instead of the command line is also good practice.

Getting the parsing of those arguments right is not trivial. If you don't like the workaround any fix should consider the previous bugs in this area. See #14251 and references therein.

**Comment by robinro** [comment]
For reference the code to discuss is around https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/pull.py#L183

**Comment by nzjrs** [comment]
Thanks for your answer.

I guess the workaround would not work for me because the same repostory is also used for push-mode configuration (via `ansible-playbook`), and thus the presence of an ansible.cfg with a `hosfile` key in the repository would break this ability?

**Comment by robinro** [comment]
For push you could use the same hostfile (we do this with a dynamical inventory in our production setup), or overwrite it using the command line.

**Comment by gundalow** [comment]
Closing, updating docs tracked in https://github.com/ansible/ansible/issues/52837
