### ISSUE TITLE
Increase Ansible's performance

### ISSUE THREAD

**Issue by DebianRoxx** [ansible/ansible#17515]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (detached HEAD 35da6ba9d1) last updated 2016/07/22 09:48:22 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 45128c8bab) last updated 2016/08/31 10:57:13 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 511752e53a) last updated 2016/08/31 10:57:13 (GMT +200)
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
stdout_callback = skippy
callback_whitelist = timer, profile_tasks
pipelining = True
```
##### OS / ENVIRONMENT

Debian GNU/Linux 8.5 (jessie)
##### SUMMARY

Performance could be better.
##### STEPS TO REPRODUCE

```

---
 - name: perfs tests
   hosts: localhost
   connection: local
   vars:
     db:
         - "db1"
         - "dbXXX" (XXX = 2 to 200)
   tasks:
     - mysql_db :
         name : "{{ item }}"
         state : present
         config_file: "/etc/mysql/root.cnf"
       with_items: "{{ db }}"

     - mysql_db :
         name : "{{ item }}"
         state : absent
         config_file: "/etc/mysql/root.cnf"
       with_items: "{{ db }}"
```
##### EXPECTED RESULTS

Shell execution of same work take 3 seconds.
So, there is much room to improve performance.
In real production with a lot of parametrized roles, tasks, dependencies, and lot of variables, execution is very slow.

```
time (for i in {1..200}; do mysql -e "CREATE DATABASE db$i" ; done ; for i in {1..200}; do mysql -e "DROP DATABASE db$i" ; done)
real    0m3.178s
user    0m1.436s
sys     0m0.444s
```
##### ACTUAL RESULTS

```
Monday 12 September 2016  08:27:36 +0200 (0:00:44.573)       0:01:31.628 ****** 
=============================================================================== 
mysql_db --------------------------------------------------------------- 46.99s
mysql_db --------------------------------------------------------------- 44.57s
Playbook run took 0 days, 0 hours, 1 minutes, 31 seconds

Note : within a lightweight parametrized role, playbook run took 0 days, 0 hours, 2 minutes, 28 seconds.
```

**Comment by robinro** [comment]
Since this issue is about the performance of the mysql module, it should be opened in the ansible-modules-core repository.
https://github.com/ansible/ansible-modules-core/issues/new

See http://docs.ansible.com/ansible/community.html#i-d-like-to-report-a-bug on which repository to report bugs against.

Maybe one quick comment regarding the issue: Since the ansible module tries to be idempotent it has to check the existance of the database before creating/dropping it. So in your comparison benchmark you should add a command like `SHOW DATABASES LIKE db$i` before both statements to run  equivalent commands. Anyhow 3 seconds vs. 1.5 minutes sounds unreasonable, so maybe there's more to it.

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by DebianRoxx** [comment]
@robinro You're right, I forgot that module try to be idempotent.
I've tested with a show databases after each create database and shell execution is always under 4 seconds, so no much differences.

I have tested against core module (shell), it's the same. I'll open new ticket for this.
Thanks.

**Comment by DebianRoxx** [comment]
New ticket is here : https://github.com/ansible/ansible/issues/17528
