### ISSUE TITLE
Will EPEL packages be kept up to date?

### ISSUE THREAD

**Issue by PatBee** [ansible/ansible#17523]
- Feature Idea

For people working in a corporate environment Ansible moves fast, really fast.  That is good and bad.  Good we get new features quickly.  Bad that we can't get latest updates easily on older systems (Read RHEL or Centos 6.x, or Ubuntu 14.X).   

Currently the latest version of ansible in https://dl.fedoraproject.org/pub/epel/6/x86_64/ is 2.1.1.  
Same appears to be true for Ubuntu 14.x versions: https://launchpad.net/~ansible/+archive/ubuntu/ansible

It would be really nice to use the native package managers on servers to update to the latest version of Ansible.  Mixing the native package management with language specific management (like pip) is a dangerous path.  

If not that, how about an ansible playbook to updating ansible in some other way to make it consistent and easy to use? 
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Core Ansible Installation
##### ANSIBLE VERSION

Version, that is the question, currently 2.1

```

``
```

**Comment by bcoca** [comment]
We do provide ways to build rpm/deb/etc from our source, but sadly we don't control what distributions choose to package.

The reason pip has the latest available is because it is one method of installation we do have control over as we publish the package, the release tarball and our Ubuntu ppa are the other 2. Outside of that, there is very little we can do.

**Comment by PatBee** [comment]
You could offer the core of a playbook that builds from source.  Gitlab offers their own repo with packages they publish for popular linux distributions, it is their preferred method of installation.  Though Docker might become their preferred method.
