### ISSUE TITLE
get_distribution() should expose all distributions, not just Linux

### ISSUE THREAD

**Issue by jbergstroem** [ansible/ansible#17587]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module_utils
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 70e63ddf6c) last updated 2016/09/15 09:17:53 (GMT -300)
  lib/ansible/modules/core: (detached HEAD 683e5e4d1a) last updated 2016/09/14 21:37:36 (GMT -300)
  lib/ansible/modules/extras: (detached HEAD 8749c40fee) last updated 2016/09/14 21:37:37 (GMT -300)
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

While trying to add SmartOS support to `hostname`, we encountered that distribution will always be set to `None` meaning flavors of SunOS (SmartOS, Illumos, OmniOS, etc) won't be recognized and available through modules.
##### STEPS TO REPRODUCE

See parent issue/PR: https://github.com/ansible/ansible-modules-core/pull/4811

Comment of discovery:
https://github.com/ansible/ansible-modules-core/pull/4811#issuecomment-247079999
##### EXPECTED RESULTS

`get_distribution()` should in this case return `SmartOS`.
##### ACTUAL RESULTS

It returns `None`.

**Comment by hnakamur** [comment]
I agree `get_distribution()` should return not `None` but a distribution for platforms other than Linux.
https://github.com/ansible/ansible/blob/0bda419f66fa761408533228c36a9d2fbccc5e8f/lib/ansible/module_utils/basic.py#L234-L235

However for compatibility, it may be safe to add another method like `get_raw_distribution()` or something.
If we are going to change `get_distribution()` behavior, we should check all places where distribution is matched to `None` and rewrite it to match to appropriate multiple distributions.

**Comment by jbergstroem** [comment]
`hostname` is the only module I could find it being used from:

``` bash
 $  ag "get_distribution\("
core/system/hostname.py
73:        distribution = get_distribution()
```

..it also affects `load_platform_subclass()`, trying to populate distribution subclass:

``` python
    if distribution is not None:
        for sc in get_all_subclasses(cls):
            if sc.distribution is not None and sc.distribution == distribution and sc.platform == this_platform:
                subclass = sc
```

Indirectly, also seems to be used from `core/utilities/logic/include_vars.py`:

``` yaml
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"
```

I think we should rewrite the logic and run the test suite. At first glance, it looks like a safe change.

**Comment by jbergstroem** [comment]
@hnakamur let me whip up a patch! I'm not super acquainted to Ansible core but are eager to learn.

**Comment by robinro** [comment]
Why does one need the `get_distribution` function and can not use the host facts?
In `lib/ansible/module_utils/facts.py` there is quite elaborate distribution name/version parsing already.

`get_distribution` should be removed, since it is only used in the `hostname` module (which you are fixing here) and the `url` module, where it is (unnecessarily) used for error output.

**Comment by hnakamur** [comment]
@robinro Ah I forgot now we can use the host facts in ansible modules. Thanks for a heads up!
So, it is better to rewrite [load_platform_subclass](https://github.com/ansible/ansible/blob/0bda419f66fa761408533228c36a9d2fbccc5e8f/lib/ansible/module_utils/basic.py#L272-L294) to use the host facts instead of `get_distribution`, right?

**Comment by robinro** [comment]
@hnakamur I would definitely say so.
But one should test this carefully since I assume that `get_distribution` and the host facts don't always agree.

**Comment by hnakamur** [comment]
@robinro Thanks for your comment.
@jbergstroem If you agree and you are willing to contribute, could you create a new issue for rewriting load_platform_subclass to use the host facts instead of `get_distribution`?

**Comment by jbergstroem** [comment]
@hnakamur I don't know ansible that well so I can't argue for `get_distribution`s removal, but I'm happy to do so in order to get things working. One side effect of this would be potentially being a major abi break? perhaps just switch to host facts in `load_platform_subclass` and deprecate `get_distribution` to quickly get things moving forward?

**Comment by hnakamur** [comment]
> One side effect of this would be potentially being a major abi break?

Maybe. I think we'd better to ask core committers for what is the best to get things working.

**Comment by jbergstroem** [comment]
Guess this stalled a bit. I'm still waiting for feedback on how to proceed wrt deprecating/removing `get_distribution`. Should I just proceed and ignore it?

**Comment by jbergstroem** [comment]
Ping.

**Comment by robinro** [comment]
@jbergstroem To discuss this I'd recommend going to #ansible-devel on IRC and ask there. This is the quickest way to reach the core developers.

Another option is to just ignore it for the moment, open a PR with the changes and then discuss it there.
Personally, I don't think this is a "major abi break", since get_distribution is severly broken, not widely documented and barely used.

**Comment by alikins** [comment]
I think making load_platform_subclasses() support the case where get_distribution() is None and only platform matches seems reasonable. Lots of details to work out there though.

Maybe get_distribution() defaults to some generic distro instead None for those cases (DistributionNotApplicable etc). And change the 
``` python
if sc.platform == this_platform and sc.distribution is None:
```

to

``` python
if sc.platform == this_platform and sc.distribution is DistributionNotApplicable:
```
(ie, a way for distro-agnostic platform subclasses to indicate they dont care about the distro)

**Comment by jbergstroem** [comment]
@alikins first of all, thanks for looking into this. What are your thoughts on dropping `get_distribution` and using host facts instead?

**Comment by jbergstroem** [comment]
ping

**Comment by samdoran** [comment]
After looking at this, I'm in favor of making `get_distribution()` return a distribution for systems other than Linux. It's not named `get_linux_distribution()` and I don't see any obvious harm in making this more useful.

The reason this function only works on Linux was this function used to use `platform.linux_distribution()`. We switched to using `distro` in Anisble 2.8 since `platform.linux_distribution()` was deprecated in Python 3.5 and removed in Python 3.8. `distro` now handles many more distributions besides Linux.

Switching to using the `Distribution` class in `facts.system.distribution` and fully deprecating `get_distribution()` is not something I'm in favor of. While the methods in `Distribution()` are robust, the interface is a bit more cumbersome in that you need an `AnsibleModule` object to instantiate an instance of `Distribution`. I prefer to make simple utility functions and make them more useful but still targeted.
