### ISSUE TITLE
Issue with the ansible - Unable to verify anisble working using Ping

### ISSUE THREAD

**Issue by muraliselva10** [ansible/ansible#17610]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

I am following the above mentioned document for setting up the Ansible.
http://docs.ansible.com/ansible/intro_getting_started.html

So that I am getting the issue with proper working of the ansible here.

First I have installed ansible in my host(controller in ansible term) using the apt-get command.

It completed without any failures.

Then edited the /etc/ansible/hosts file and added the my management node IP(machine where I need to deploy some applications).

Then done adding the public SSH key in authorized_keys on that machine(management node).

Now I have tried the following command and got the error as mentioned.

$ ansible all -m ping
127.0.0.1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}

You can see that IP itselg wrong its pinging local machine.

Then added sudo with the command then it pinging to correct IP.

$ sudo ansible all -m ping
172.27.3.182 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}

I decided to follow alternative:

Then I added entry as follows in /etc/ansible/hosts file:

172.27.3.182 ansible_ssh_pass=password ansible_ssh_user=username

Then I can be able to see that Ping  is success.

$ sudo ansible all -m ping 
172.27.3.182 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

**Comment by Shaps** [comment]
I don't think this can be considered a bug. Likely the user you are running ansible as does not have permissions to read `/etc/ansible/hosts`. 
The second error is very likely because the ssh key is not stored in a path that ssh reads, hence falls back to using user/pass auth.

**Comment by coderinsg** [comment]
may I suggest the following debugging to test certain assumptions?
- without using sudo, can you read the contents of ansible.cfg using "cat /etc/ansible/ansible.cfg" ?
  If yes, then permission shouldn't be an issue.
  If not, then you need to either change permission in /etc/ansible/ or use local ansible.cfg file that is accessible by user.
- in the ansible.cfg file, instead of implicitly assuming ssh private key file will be read, can you add the parameter "ansible_ssh_private_key_file" and specify the file explicitly?

Another way is via

`sudo ansible all --private-key=<path> -u <user> -m ping`

if the above is successful, @Shaps is correct

**Comment by alikins** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
  
  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
