### ISSUE TITLE
Ansible 2.1.0->2.1.1 regression: conditional include now evaluates each task instead of ignoring them

### ISSUE THREAD

**Issue by odyssey4me** [ansible/ansible#17687]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

strategy
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```

also confirmed with 2.1.2rc3

```
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None.
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS, although I don't think it matters.
##### SUMMARY

In Ansible 2.1.0 when a task file was conditionally included the the condition was not met, all tasks in the file were not evaluated in any way. They were completely ignored. For example:

```
TASK [include] *****************************************************************
task path: /root/02-playbook.yml:41
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

In Ansible 2.1.1 this behaviour has changed to what it was in Ansible 1.9, resulting in every single task being evaluated. For example:

```
TASK [debug] *******************************************************************
task path: /root/03-included-task.yml:2
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /root/03-included-task.yml:5
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

As a result of this change in behaviour, the time to execute playbooks and roles which make use of conditional includes increase significantly - especially in large environments.
##### STEPS TO REPRODUCE

A full transcript of how to reproduce this is available in https://gist.github.com/odyssey4me/7cdcc70a60895a1280221e454cff10b6

However, to briefly summarise:

```

---
### filename: 02-playbook.yml
- name: Test conditional include (no)
  hosts: localhost
  gather_facts: false
  tasks:
     - include: 03-included-task.yml
       when: include_me | bool
  vars:
    include_me: no
```

```

---
### filename: 03-included-task.yml
- debug:
    msg: "included-task -> include_me: {{ include_me }}"

- debug:
    msg: "included-task -> arbitrary message"
```

##### EXPECTED RESULTS

```
TASK [include] *****************************************************************
task path: /root/02-playbook.yml:41
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
task path: /root/03-included-task.yml:2
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /root/03-included-task.yml:5
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

```

**Comment by jimi-c** [comment]
Hi @odyssey4me, this is due to the fact that we fixed the code for controlling when an include is `static` vs `dynamic`. In your case, the include is now being brought in statically at playbook compile time, so this behavior is in-line with how 1.9.x and before behaved. If you wish to force the include to be dynamic (with the limitations noted here: http://docs.ansible.com/ansible/playbooks_roles.html#dynamic-versus-static-includes), you can set `static: no` on the include task and the conditional will only be triggered once.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by odyssey4me** [comment]
@jimi-c Great, thanks - I've confirmed that setting `static: no` on the include task makes it work as it did before.

**Comment by jimi-c** [comment]
@odyssey4me excellent, just be aware of the limitations of dynamic includes (tags, start-at-task, etc.) documented in that link above.

**Comment by odyssey4me** [comment]
@jimi-c Something isn't making sense to me. The default in https://github.com/ansible/ansible/blob/v2.1.2.0-0.3.rc3/lib/ansible/constants.py#L187 is 'False', which should be the same as setting `static: no` on all include tasks, right?

**Comment by jimi-c** [comment]
@odyssey4me that's probably named a little poorly, those are more like force settings. If set to true, it forces them to static, otherwise (when False) it uses the option as set on the task.
