### ISSUE TITLE
playbooks cannot contain emoji

### ISSUE THREAD

**Issue by okand** [ansible/ansible#17755]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible-playbook (I think)
##### ANSIBLE VERSION

```
~/Ansible % ansible --version                                       
ansible 2.2.0 (devel cf4d436e07) last updated 2016/09/23 10:31:05 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0f505378c3) last updated 2016/09/23 10:31:11 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 1ade801f65) last updated 2016/09/23 10:31:15 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Two different computers both running the playbook on themselves:
1. Ubuntu Gnome 16.04.1
2. Debian 8.4 (over ssh, no gui installed)
##### SUMMARY

If a playbook contains emoji anywhere it fails to run.
##### STEPS TO REPRODUCE

Run the example playbook below.

```

---
- name: Emoji Test
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Extraterrestrial Alien
      debug: msg="👽"
```

##### EXPECTED RESULTS

```
~/Ansible % ansible-playbook -i hosts testing.yml -vvvvv            
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/alexander/Ansible-dev/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: testing.yml **********************************************************
1 plays in testing.yml

PLAY [Emoji Test] **************************************************************

TASK [Extraterrestrial Alien] **************************************************
task path: /home/alexander/Ansible/testing.yml:7
ok: [localhost] => {
    "msg": "👽"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```
##### ACTUAL RESULTS

```
~/Ansible % ansible-playbook -i hosts testing.yml -vvvvv
Using /etc/ansible/ansible.cfg as config file
ERROR! Syntax Error while loading YAML.
```

If I run it ad-hoc it works.

```
~/Ansible % ansible -i hosts localhost -m debug -a "msg="👽""        
localhost | SUCCESS => {
    "msg": "👽"
}
```

**Comment by okand** [comment]
Update. On my mac at home this works. Running the playbook prints the extraterrestrial.
Running Mac OS X 10.11.6

**Comment by mightydok** [comment]
@okand what yaml package version u have on mac and linux?

**Comment by mightydok** [comment]
need_info

**Comment by okand** [comment]
According to `pip list` I have version 3.12 of PyYAML on both systems.

**Comment by jborean93** [comment]
I know this is a bit late but I've recently come across this issue where unicode surrogate pair chars like emojis work on a MacOS host but not another Linux host like Fedora. The issue lies with the underlying backend that PyYAML uses. By default it will try and link against `LibYAML` and if that fails it uses its own code which currently doesn't handle surrogate chars. What you need to do to get this working is either one of the below;

* Make sure you have `LibYAML` headers installed before install PyYAML`
On fedora this would be

```
sudo dnf install libyaml-devel
pip install PyYAML
```

* Use a unicode literal to escape the char, 
For example

```
- name: this is \U0001F4A9
  module:
```

is the same as

```
- name: this is 💩
  module:
```

The latter is arguably more cross compatible as you aren't relying on people who run the playbook to have the libyaml bindings available but you need to know the UTF-32 codepoint for it to work.
