### ISSUE TITLE
Allow group_vars and host_vars to override role variables

### ISSUE THREAD

**Issue by hachaboob** [ansible/ansible#17786]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Variable Precedence
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Change Ansible's variable precedence so that groups_vars and host_vars can override all role variables. Roles should be considered standalone or isolated modules and maintain there own variable precedence. Roles can use conditions to set OS specific variables in their vars folder. All variables defined in a role should be able to be overridden outside of the role by group_vars and host_vars. This would take care of the use case for being able to set OS specific variable defaults in a role and being able to override them.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by hoall** [comment]
I would say you need to be more specific. Role default vars for example are overwritten.

See [Variable Precendence](http://docs.ansible.com/ansible/playbooks_variables.html#variable-scopes)

**Comment by krzysztof-magosa** [comment]
You should use `defaults` for values which you want to override later.
`vars` are something like private/internal variables of role.

**Comment by bcoca** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational. Since the precedence order is something all playbooks rely on, I don't see us changing it as it would cause issues to the great majority of existing users.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible! close this ticket.
