### ISSUE TITLE
Responses from remote devices not sanitized completely

### ISSUE THREAD

**Issue by schoksey** [ansible/ansible#17825]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

shell.py library from module_utils
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Remote devices that use ssh clients to execute commands remotely e.g. on Cisco N9K, 
may return extraneous spaces in their responses.  As a result, if the response is not 
appropriately sanitized to conform to JSON format, it may result in exceptions such 
as "Command does not support JSON output" in the calling ansible modules e.g. nxos_interface.
##### STEPS TO REPRODUCE

Run the nxos_interface module with default transport as cli (ssh) as follows against a N9K
device to unconfigure a port-channel interface.
Note: this is not always reproducible on all N9K versions. 
E.g.

```
ansible localhost -m nxos_interface -a "host=<ip-of-device> \
username=<username> password=<password> interface=port-channelNN state=absent"
```
##### EXPECTED RESULTS

```
localhost | SUCCESS => {
    "changed": true,
    "end_state": {},
    "existing": {
        "admin_state": "up",
        "description": "None",
        "interface": "port-channelNN",
        "mode": "layer2",
        "type": "portchannel"
    },
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "description": null,
            "host": "<ip-of-device>",
            "interface": "<port-channelNN>",
            "mode": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": 10,
            "transport": "cli",
            "use_ssl": false,
            "username": "<username>",
            "validate_certs": true
        },
        "module_name": "nxos_interface"
    },
    "proposed": {
        "admin_state": "up"
    },
    "state": "absent",
    "updates": [
        "no interface <port-channelNN>"
    ]
}
```
##### ACTUAL RESULTS

```
EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1474313424.81-246045351765696/nxos_interface; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1474313424.81-
246045351765696/" > /dev/null 2>&1 && sleep 0'
changed: [device-name] => (item={u'vlan_ids': u'NNNN', u'channel_mode': u'trunk', u'peer_link': 
u'false', u'members': [u'eth1/N'], u'port_channel': u'N'}) => {"changed": true, "end_state": {}, "existing":
 {"admin_state": "up", "description": "None", "interface": "port-channelN", "mode": "layer2", "type": 
"portchannel"}, "invocation": {"module_args": {"admin_state": "up", "description": null, "host": "<ip-of-
device", "interface": "port-channelN", "mode": null, "password": 
"VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": null, "provider": null, "ssh_keyfile": null, 
"state": "absent", "timeout": 10, "transport": "cli", "use_ssl": false, "username": "<username>", 
"validate_certs": true}, "module_name": "nxos_interface"}, "item": {"channel_mode": "trunk", 
"members": ["eth1/N"], "peer_link": "false", "port_channel": "N", "vlan_ids": "NNNN"}, "proposed": 
{"admin_state": "up"}, "state": "absent", "updates": ["no interface port-channelN"]}
```

**Comment by schoksey** [comment]
#17829

**Comment by bcoca** [comment]
Module Repo Information
=======================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:

   * https://github.com/ansible/ansible-modules-extras

If this is about an existing module:

   * Find the module at http://docs.ansible.com/list_of_all_modules.html
   * Open the documentation page for that module
   * If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
   * Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by schoksey** [comment]
#17829 - Can someone also please review the corresponding patch.
Thank you.
