### ISSUE TITLE
Play continues with when 'any_errors_fatal' and max_fail_percentage satisfied the % of hosts failed

### ISSUE THREAD

**Issue by mukundhansuresh** [ansible/ansible#17845]
##### ISSUE TYPE

Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.8 (Santiago)
##### SUMMARY

Play continues after a failed task when any_errors_fatal is set with max_fail_percentage. Is there a patch for this issue for ansible 2.1.0.0?
##### STEPS TO REPRODUCE

Run the ansible playbook
- hosts: all
  any_errors_fatal: true
  max_fail_percentage: 19
  tasks:
  - name: test_site
    script: /etc/ansible/test.py 
    register: test_out
- hosts: webserver
  any_errors_fatal: true
  tasks:
  - name: reload_webservers
    script: /etc/ansible/reload.py 
    register: reload_out
##### EXPECTED RESULTS

I have 5 hosts where the script test.py runs against from the first play and the playbook is expected to stop after the script failed on 2 out of 5 hosts (more than 19% failed) because I have any_errors_fatal: true and max_fail_percentage: 19. I also do not have  ignore_errors: true so the playbook should abort. However the playbook continues and executes the next play reload_webservers.
##### ACTUAL RESULTS

Playbook does not abort but continue to execute the rest of the playbook

The play is continuing  to execute the task in the next play

**Comment by mukundhansuresh** [comment]
Hi Jimi-c

Can you please let know if there are any fixes for this issue?

**Comment by jimi-c** [comment]
Hi @mukundhansuresh, sorry to take a while to follow-up on this, however I am not seeing this issue in any version going back to 2.1.0.0:

<pre>
PLAYBOOK: test.yml *************************************************************
2 plays in test.yml
PLAY [all] *********************************************************************
TASK [test_site] ***************************************************************
task path: /home/jamesc/testing/17845/test.yml:6
fatal: [bar1]: FAILED! => {"changed": true, "cmd": ["echo", "bar1"], "delta": "0:00:00.002335", "end": "2016-11-12 06:52:34.583034", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-11-12 06:52:34.580699", "stderr": "", "stdout": "bar1", "stdout_lines": ["bar1"], "warnings": []}
changed: [bar4] => {"changed": true, "cmd": ["echo", "bar4"], "delta": "0:00:00.003799", "end": "2016-11-12 06:52:34.613130", "failed": false, "failed_when_result": false, "rc": 0, "start": "2016-11-12 06:52:34.609331", "stderr": "", "stdout": "bar4", "stdout_lines": ["bar4"], "warnings": []}
fatal: [bar2]: FAILED! => {"changed": true, "cmd": ["echo", "bar2"], "delta": "0:00:00.004108", "end": "2016-11-12 06:52:34.621803", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-11-12 06:52:34.617695", "stderr": "", "stdout": "bar2", "stdout_lines": ["bar2"], "warnings": []}
changed: [bar3] => {"changed": true, "cmd": ["echo", "bar3"], "delta": "0:00:00.003113", "end": "2016-11-12 06:52:34.634705", "failed": false, "failed_when_result": false, "rc": 0, "start": "2016-11-12 06:52:34.631592", "stderr": "", "stdout": "bar3", "stdout_lines": ["bar3"], "warnings": []}
changed: [bar5] => {"changed": true, "cmd": ["echo", "bar5"], "delta": "0:00:00.001832", "end": "2016-11-12 06:52:34.649262", "failed": false, "failed_when_result": false, "rc": 0, "start": "2016-11-12 06:52:34.647430", "stderr": "", "stdout": "bar5", "stdout_lines": ["bar5"], "warnings": []}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
bar1                       : ok=0    changed=0    unreachable=0    failed=1   
bar2                       : ok=0    changed=0    unreachable=0    failed=1   
bar3                       : ok=1    changed=1    unreachable=0    failed=0   
bar4                       : ok=1    changed=1    unreachable=0    failed=0   
bar5                       : ok=1    changed=1    unreachable=0    failed=0   
</pre>

So this appears to have been fixed a while back when we addressing other issues with fail pct and any_errors_fatal. As such, we'll close this now.  If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
