### ISSUE TITLE
try out ujson

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1791]
From @skvidal:

"I've not tested it yet - but this might be worth investigating to see if it will work w/o modification with ansible:

http://kushaldas.in/posts/ujson-a-fast-json-implementation.html"

basically we could do something like the following where we import json today:

```
try:
    import ujson as json
except ImportError:
    try:
         import simplejson as json
    except ImportError:
        # we are using regular python standard json
        pass
```

and should compare test runtimes (which have some variability though)

**Comment by jkleint** [comment]
I'm pretty sure JSON ser/des is not even a pimple on Ansible's CPU profile, but let's just check real quick:

```
$ echo '---
- hosts: all
  tasks:
    - action: ping
      with_items: [0,1,2,3,4,5,6,7,8,9]
' > ping.yml
```

Let's run this on my RHEL 5.8 64-bit box against my 32-node cluster using Python 2.7.3, with only 1 thread since Python's profiler doesn't do multiprocessing (this shouldn't affect the proportion of time spent on JSON, if we're doing ser/des in the worker threads):

```
$ python -m cProfile -o ping.stats ansible-playbook ping.yml -f1
...
$ python -c 'import pstats; pstats.Stats("ping.stats").print_stats("lib/python2.7/json")'
Thu Dec 20 14:48:22 2012    ping.stats

         2986033 function calls (2980709 primitive calls) in 176.910 seconds

   Random listing order was used
   List reduced from 1537 to 12 due to restriction <'lib/python2.7/json'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      352    0.001    0.000    0.015    0.000 python2.7.3/lib/python2.7/json/__init__.py:281(loads)
        1    0.000    0.000    0.000    0.000 python2.7.3/lib/python2.7/json/decoder.py:304(__init__)
        1    0.000    0.000    0.002    0.002 python2.7.3/lib/python2.7/json/encoder.py:2(<module>)
      352    0.002    0.000    0.014    0.000 python2.7.3/lib/python2.7/json/decoder.py:361(decode)
      352    0.010    0.000    0.010    0.000 python2.7.3/lib/python2.7/json/decoder.py:372(raw_decode)
        1    0.000    0.000    0.000    0.000 python2.7.3/lib/python2.7/json/encoder.py:102(__init__)
        1    0.000    0.000    0.000    0.000 python2.7.3/lib/python2.7/json/encoder.py:71(JSONEncoder)
        1    0.000    0.000    0.003    0.003 python2.7.3/lib/python2.7/json/decoder.py:2(<module>)
        1    0.000    0.000    0.000    0.000 python2.7.3/lib/python2.7/json/decoder.py:274(JSONDecoder)
        1    0.000    0.000    0.000    0.000 python2.7.3/lib/python2.7/json/decoder.py:17(_floatconstants)
        1    0.000    0.000    0.005    0.005 python2.7.3/lib/python2.7/json/__init__.py:99(<module>)
        1    0.000    0.000    0.002    0.002 python2.7.3/lib/python2.7/json/scanner.py:2(<module>)
```

A total cumulative time of at most 0.051 seconds out of 176.9, or less than 0.03%.  Even if ujson were _infintely_ fast, you would not notice.  (It doesn't seem to support Python 2.4, so you couldn't use it on the nodes.)  

The best argument though is "keep it simple."  We've already got two JSON decoders (three if you count PyYAML); one more is just complexity with little marginal benefit.  And besides, it doesn't compile on RHEL 5.  ;)

**Comment by jkleint** [comment]
For extra credit (and future optimization efforts), Ansible spends most of its time on network and file operations.  And when I say "most," I mean pretty much "all:"

```
$ python -c 'import pstats; pstats.Stats("ping.stats").sort_stats("time").print_stats(25)'
Thu Dec 20 14:48:22 2012    ping.stats

         2986033 function calls (2980709 primitive calls) in 176.910 seconds

   Ordered by: internal time
   List reduced from 1537 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    91644   94.550    0.001   94.550    0.001 {method 'acquire' of 'thread.lock' objects}
     7902   75.538    0.010   75.538    0.010 {time.sleep}
   119040    0.358    0.000    0.706    0.000 python/lib/python2.7/site-packages/Crypto/Random/Fortuna/SHAd256.py:83(update)
     7494    0.253    0.000    0.253    0.000 {method 'read' of 'file' objects}
    17088    0.235    0.000    0.235    0.000 {built-in method encrypt}
   119040    0.226    0.000    0.955    0.000 python/lib/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py:57(append)
   141824    0.218    0.000    0.218    0.000 {method 'update' of '_hashlib.HASH' objects}
    39680    0.215    0.000    1.276    0.000 python/lib/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py:137(add_random_event)
   160352    0.179    0.000    0.284    0.000 python/lib/python2.7/site-packages/Crypto/Util/wrapper.py:40(__getattr__)
     7244    0.147    0.000  170.186    0.023 python2.7.3/lib/python2.7/threading.py:234(wait)
     5696    0.140    0.000    2.485    0.000 python/lib/python2.7/site-packages/paramiko/packet.py:281(send_message)
     6048    0.136    0.000    0.136    0.000 {method 'send' of '_socket.socket' objects}
      704    0.133    0.000    0.133    0.000 {method 'connect' of '_socket.socket' objects}
     2112    0.120    0.000    0.146    0.000 python/lib/python2.7/site-packages/paramiko/util.py:65(deflate_long)
     8450    0.113    0.000    0.120    0.000 python2.7.3/lib/python2.7/threading.py:185(__init__)
   329903    0.112    0.000    0.112    0.000 {getattr}
     5696    0.094    0.000    0.414    0.000 python/lib/python2.7/site-packages/Crypto/Hash/HMAC.py:59(__init__)
     5696    0.090    0.000    0.599    0.000 python/lib/python2.7/site-packages/paramiko/packet.py:42(compute_hmac)
    39680    0.080    0.000    1.356    0.000 python/lib/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py:46(feed)
   119168    0.076    0.000    0.076    0.000 {_struct.pack}
     5696    0.075    0.000    0.824    0.000 python/lib/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py:68(collect)
        8    0.073    0.009    0.073    0.009 {built-in method poll}
     5762    0.072    0.000    0.072    0.000 {posix.stat}
    11392    0.071    0.000    0.121    0.000 python/lib/python2.7/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py:121(_generate_blocks)
345908/345761    0.071    0.000    0.071    0.000 {len}
```

That's 96% of the time in `thread.lock.acquire()` (running with 1 thread! Thanks, Paramiko!) and `time.sleep()`.  Of course some of that time is waiting for Ansible on the remote end, and most modules do more, but again, most modules are doing network and file I/O.  As they should be!  

If we actually wanted to make Ansible fast, the best thing we could do is remove the implicit barriers between tasks.  Send over everything you need for a playbook and run it all in one go; let nodes phone home when they need to, and let users add barriers when they need to.

That's perhaps a bridge too far for the current system, but I think it takes advantage of most people's needs.  Personally I don't care if web04 copies httpd.conf before web17 starts apache; there's a lot of implicit synchronization that's often superfluous.  And really most people must not care either, because if web04 dies the rest just keep on truckin', so it couldn't have been that important.  ;)  I don't even think Ansible had a way to say "If one machine dies, terminate the whole operation" until recently.  If we don't even care that a machine finishes an operation, it seems a bit silly to make everybody wait for it.  That's essentially what you're doing with local mode and `ansible-pull`.

By the way, Ansible is quite fast as of 0.9, and I really appreciate the improvements.  It's fast enough that I don't worry about it; my tasks are usually the dominant factor.  Thanks for all the hard work.

**Comment by skvidal** [comment]
Thanks for the analysis. I agree - it's not worth it. But thank you for checking.

As to your comments about making ansible faster by doing thing all in one blob. I think that would be what Michael has referred to as an 'ansiball'. Make a ball of stuff, push it over the wire, execute and be done.

I personally love the idea, but I've not had any time to sit down and work out the details on how to achieve it.

**Comment by dagwieers** [comment]
It does compile on RHEL5 though, so it could be a replacement/alternative for simplejson.

**Comment by yeukhon** [comment]
Just saw this. At work we use ultrajson for really really important speed difference. If we all go for speed ....we'd use threads over processes.
https://github.com/esnme/ultrajson

+1 not worth the trouble right now to go to another json. If ujson or other json dies for whatever reason, we are stuck.

**Comment by mpdehaan** [comment]
Thanks for supplying data that we don't care about this.

I agree!!!

**Comment by mpdehaan** [comment]
ansiball is interesting and probably worthwhile

Not sure how much refactoring is required to make my head not explode to do it...

I'd still recommend fireball mode for most folks too where it works!
