### ISSUE TITLE
Errors inside blocks don't seem to be included in the failure count

### ISSUE THREAD

**Issue by richard-hulm** [ansible/ansible#17983]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Blocks / Always
##### ANSIBLE VERSION

(Doesn't happen on 2.1.1.0)

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Reproduced on Fedora 24 & Debian Jesse
##### SUMMARY

Errors inside blocks don't seem to be included in the failure count
##### STEPS TO REPRODUCE

```

---
- hosts: all
  tasks:
    - block:
      - name: Fail when something happens
        fail:
          msg: "Test"
        when: True
      always:
        - name: Something that always happens
          debug:
            msg: Doesn't really matter what this is
...
```
##### EXPECTED RESULTS

The failure to be counted and the exit code to be one
##### ACTUAL RESULTS

The failure was not included in the summary and the program exited with exit code 0

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Fail when something happens] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Test"}

TASK [Something that always happens] *******************************************
ok: [localhost] => {
    "msg": "Doesn't really matter what this is"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0  
```

**Comment by schast** [comment]
version 2.2.0.0 is also affected.

**Comment by richard-hulm** [comment]
This is a change in behaviour from 2.0 - and will silently start causing builds that used to fail to pass.

We rely on the fail: when= to catch various preconditions before migrations etc. 

This causing it to exit with a 0 exit code meant the error was never caught

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Letting this burn in on devel for a few days, will cherry-pick to stable-2.1/stable-2.2 then.

**Comment by jimi-c** [comment]
Cherry-picked to stable-2.2, does not apply to stable-2.1, so closing now. If we do want this to be backported to 2.1 we'll have to fix it another way.
