### ISSUE TITLE
Expect module - Expected results feature

### ISSUE THREAD

**Issue by bananabr** [ansible/ansible#18071]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

expect_module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/dsantos/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Expect module should have an **expected_results** option that would have the same structure of the **responses** options ( dict of lists). Every response to a pattern would have a correspondent expected_result, like in the example below:

```
- name: "Expected results example"
  delegate_to: localhost
  register: result
  expect:
    command: "/usr/bin/telnet {{ inventory_hostname }}"
    echo: true
    expected_results:
      '#:'
        - 'command1 success message pattern'
        - 'command2 success message pattern'
        - 'command3 success message pattern'
    responses:
      'username:':
        - 'myuser'
      'password:':
        - 'mypass'
      '#':
        - 'command1'
        - 'command2'
        - 'command3'
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
