### ISSUE TITLE
[Feature] ability to set roles_path from within playbook

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#18079]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

roles_path
##### ANSIBLE VERSION

```
ansible 2.2.0.0 (stable-2.2 7ee14f466e) last updated 2016/10/17 18:01:05 (GMT +100)
  lib/ansible/modules/core: (detached HEAD ec4eebc92a) last updated 2016/10/17 08:35:00 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 2b7385d15e) last updated 2016/10/17 08:35:00 (GMT +100)
  config file = /Users/brian/tmp/ansible.cfg
  configured module search path = ['/Users/brian/git/ansible/library']
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Be able to set roles_path within a playbook
##### STEPS TO REPRODUCE

Use case: I have several directories containing playbooks and private roles, plus a directory of shared roles as a sibling directory.

```
foo/pb1.yml
foo/roles/...
bar/pb2.yml
bar/roles/...
baz/pb3.yml
baz/roles/...
shared/roles/...
```

I want the user to be able to checkout this bundle at any location in the filesystem, e.g. their home directory.

I would like to be able to reference shared roles without having to give explicit paths every time:

```
  roles:
    - role: ../shared/roles/s1
    - role: ../shared/roles/s2
```
##### EXPECTED RESULTS

I was hoping for a way to set `roles_path: ../shared/roles` in the playbook itself.  I didn't find a way to do this in [playbooks_intro](http://docs.ansible.com/ansible/playbooks_intro.html) or [playbooks_special_topics](http://docs.ansible.com/ansible/playbooks_special_topics.html)
##### ACTUAL RESULTS

I tried `vars: {ansible_roles_path: ../shared/roles}` and `vars: {roles_path: ../shared/roles}` but neither made a difference.
##### WORKAROUND

Ansible will read a file `ansible.cfg` in the current working directory, before looking in `~/.ansible.cfg` or `/etc/ansible.cfg`. So it is possible to drop ansible.cfg in the playbook directory containing

```
[defaults]
roles_path = ../shared/roles
```

However this has two problems. Firstly, the user must change directory before running the playbook:

```
# This works
cd path/to/foo
ansible-playbook pb1.yml

# This doesn't work
ansible-playbook path/to/foo/pb1.yml
```

Secondly, any settings in the global ansible.cfg or per-user ansible.cfg are no longer picked up.

**Comment by fjros** [comment]
I think you might use the `ANSIBLE_CONFIG` env var to point to the appropriate configuration file.

**Comment by candlerb** [comment]
Sure - I didn't include that option because it's way more verbose and inconvenient. But for completeness here you go:

```
# This works
ANSIBLE_CONFIG=path/to/foo/ansible.cfg ansible-playbook path/to/foo/pb1.yml
```

**Comment by candlerb** [comment]
I should also add: if you edit `/etc/ansible/ansible.cfg` or `~/.ansible.cfg` to set

```
[defaults]
roles_path = ../shared/roles
```

that doesn't work either. Although it's [undocumented](https://github.com/ansible/ansible/issues/18067), it appears with 2.2 that roles_path is relative to the directory containing ansible.cfg. So this is the same as pointing to either `/etc/shared/roles` or `/home/shared/roles` which is not what I want.

**Comment by lassizci** [comment]
Wouldn't it be convenient if the configs were merged instead of the current behavior to use only the first one found? Repos could have their own config (that would even allow placing sub-playbooks in to a subdirectory) without overriding user settings such as ssh or forks. There's something wrong if you need to call ansible-playbook with an environment variable every time. Also if everyone using the repo needs to set their own environment. If there's a fear it would break something, there could be an option to prevent using further config files.

**Comment by candlerb** [comment]
> Wouldn't it be convenient if the configs were merged instead of the current behavior to use only the first one found?

Yes that would do it - as long as ansible looked for ansible.cfg in the playbook_dir as well as the current locations.

Since you can pass multiple playbooks to a single invocation of ansible-playbook, this would mean that the ansible.cfg settings would have to be overridden at the start of one playbook and reset at the end ready for the next playbook. e.g.

```
ansible-playbook foo/pb1.yml bar/pb2.yml
```

(this also applies to my smaller request to override `roles_path` at the playbook level)

**Comment by rpinohtyp** [comment]
instead of:
```
[defaults]
roles_path = ../shared/roles
```

you could use:
```
[defaults]
roles_path = ${PWD}/shared/roles
```

then its relative to your path where you want to run ansible-playbook

**Comment by robsonpeixoto** [comment]
I try to use it, @rpinohtyp, but without success. Or is it only an idea?

**Comment by robsonpeixoto** [comment]
My bad. I wrote `[default]` instead of `[defaults]`.

**Comment by jimi-c** [comment]
Hi, based on the above discussion (and also noting that there are other environment variables to change the role/collection paths at run time), we're going to go ahead and close this issue now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
