### ISSUE TITLE
include_vars will only include *.yml, *.yaml, and *.json files but isn't documented as a breaking change

### ISSUE THREAD

**Issue by joelthompson** [ansible/ansible#18223]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Action plugins, specifically include_vars action plugin
##### ANSIBLE VERSION

I'm using 2.2 RC3

```
$ ansible --version
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

#17207 introduced a requirement that include_vars will only include files with .yaml, .yml, and .json extensions. This breaks some of our existing playbooks that have YAML-formatted vars files without a .yml or .yaml extension.

Further, this isn't documented as a breaking change.
##### STEPS TO REPRODUCE

Should be trivial to reproduce
##### EXPECTED RESULTS

Load vars files without the specific set of extensions
##### ACTUAL RESULTS

```
TASK [include_vars] ************************************************************
task path: foo.yml:8
fatal: [localhost]: FAILED! => {
    "ansible_facts": {}, 
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "my_vars_files_without_extension"
        }, 
        "module_name": "include_vars"
    }, 
    "message": "my_vars_files_without_extension does not have a valid extension: yaml, yml, json"
}
```

**Comment by thunder-spb** [comment]
Same issue with RC3-RC4

**Comment by joelthompson** [comment]
I don't think that 13261b7 copmpletely fixes the issue. At the very least, it should be mentioned as a breaking change in the CHANGELOG. But, why is this requirement even necessary in the first place?

**Comment by bcoca** [comment]
This is a bug, the restriction should only apply to the new feature that allows including directories.

**Comment by bcoca** [comment]
docs were missing for new features, merged now and backported to 2.2 https://github.com/ansible/ansible-modules-core/pull/4609, testing bugfix to revert restriction when specifying a file.

**Comment by joelthompson** [comment]
Thanks @bcoca and @abadger!

**Comment by jhriv** [comment]
What about vaulted files?

**Comment by alikins** [comment]
> What about vaulted files? 

@jhriv Not sure what you mean. Are vaulted files not working? If so, how do they fail?

**Comment by jhriv** [comment]
Vaulted files aren’t in a YAML syntax, so having a .yaml / .yml suffix is misleading at best.
On Nov 18, 2016, at 10:20, Adrian Likins <notifications@github.com<mailto:notifications@github.com>> wrote:

What about vaulted files?

@jhrivhttps://github.com/jhriv Not sure what you mean. Are vaulted files not working? If so, how do they fail?

**Comment by phraktle** [comment]
+1 that none of these extensions make sense for vaulted files...

**Comment by hExPY** [comment]
+1 we got the same problem here. would be nice to allow .vault in include vars.

**Comment by cwant** [comment]
+1 for vaulted file problem.

**Comment by ricardoxvpn** [comment]
+1 for vaulted file problem.

**Comment by jsuter** [comment]
Same issue with vaulted .py file.

**Comment by jmnavarrol** [comment]
+1
I'm also bitten by the vault problem.

In fact, I question the very decision of limiting what file extension can a yaml file have.  What's this? Microsoft Windows!?  If really needed, a YAML file gets defined by its contents, not whatever "extension" (which, by the way, it's also just a Microsoft-ish concept) the file name happens to have.  The question, while maybe harsh I think is perfectly reasonable as I don't see any rationale supporting this on #17207.

I can understand that, being the use of file extensions a common trend, you can use them as a hint for an autoloader but, mandatory? Not only doesn't seem to make sense but it breaks the minimum surprise and coherence principles.  Why auto-included host and group vars don't need a file extension but then these others do? Why can I load a file if using vars_files: but then I can't load the very same file when using include_vars:?

Even more: forcing a file extension is at odds with Ansible's own best practices as stated at http://docs.ansible.com/ansible/playbooks_best_practices.html#variables-and-vaults which makes no assumptions about vars file extensions (and, explicitly does not use them) but suggests having vault in the name.  And, please, don't just change the docs to match the implementation because, in this case, it is the doc the one with the right approach.

**Comment by syl20bnr** [comment]
I was not able to include files without any extension in a group_vars direction. This is a bit ridiculous :-)

My work around for people ending on this issue:

```
- name: "include lambda group variables"
  include_vars: "{{ env_name_long }}/group_vars/lambda/{{ item }}"
  with_items: [ "users", "vars", "vault" ]
```
