### ISSUE TITLE
Per var merging of lists (and hashes?)

### ISSUE THREAD

**Issue by ptman** [ansible/ansible#18257]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
group/host_vars

##### SUMMARY
group_vars/group1:

    foo_tags:
     - bar

group_vars/group2:

    foo_tags:
     - baz

{{foo_tags|merge}} would be ['bar','baz']

Related: https://groups.google.com/forum/#!searchin/ansible-project/merge$20lists|sort:relevance/ansible-project/LfhifDwnCo4/8BWzpmSSBQAJ

**Comment by bcoca** [comment]
The `combine` filter does this already, the limitation is you cannot use the same initial variable name. 

Templates, which includes filters, do not run when variables are loaded so by the the filter runs the vars have already been collapsed.

**Comment by ptman** [comment]
Well I'd be happy for the merging to happen somewhere earlier than jinja as well. But having to have each merged variable named differently seems pretty counterintuitive. Also combine seems to be for hashes, not lists.

**Comment by bcoca** [comment]
lists can use the `union` filter or just `list1 + list2`

**Comment by koenw** [comment]
Having per-var merging would definitely add value over `union` or `combine` in my opinion. Using `union` or `combine` would require you to know exactly what variables to merge, whereas with per-var merging you could dynamically 'append' to a list or hash without maintaining a separate 'list of lists'.

For example, let's say you have a list of nagios checks for a node. Each group or role could just define a list with checks for their respective domain, and in the end when configuring nagios, all required checks would be in the list. If you would add the node to a new group (let's say, *wordpress*), all the wordpress specific checks would automatically be added to the list of checks for that node.

**Comment by jmnavarrol** [comment]
...another example (from my daily job): we have redhat servers handled by a variety of groups (say security, database, networking...).  It'd be great to have a single var, say, redhat_repos, that could be populated by merging items from different groups (but we don't know in advance which groups).

Say, aserver belongs to [mysql], [common] and [middleware], and on each group_vars file you find something like this:
[all]
redhat_repos: []
[common]
redhat_repos: "{{ redhat_repos }} + ['rhel', 'rhel-optional']"
[mysql]
redhat_repos: "{{ redhat_repos }} + ['custom-mysql-repo']"
[middleware]
redhat_repos: "{{ redhat_repos }} + ['custom-tomcat-repo']"

...so, in the end, redhat_repos becomes:
- rhel
- rhel-optional
- custom-mysql-repo
- custom-tomcat-repo

Note how this way it's not needed in advance who exactly is going to add contents to this list (or dictionary).

I know it exists an ansible.cfg option for an all-or-nothing list merging, but the current default is basically sounded... but for exceptions like this (which, with a syntax like the above, makes the intent obviously clear).

**Comment by jmnavarrol** [comment]
...don't know how this can be done, or if even makes sense (don't know how labels are processed either) but this issue is tagged as 'affects_2.3'.  AFAIK, it also affects each and every version up to current (2.7).  Shouldn't it be tagged for all these versions or, at least, for the most recent one?

**Comment by jimi-c** [comment]
Per the above discussion, the best option is to use the `combine` filter. As such, we're going to go ahead and close this issue now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jmnavarrol** [comment]
> Per the above discussion, the best option is to use the `combine` filter. As such, we're going to go ahead and close this issue now.

No, it isn't.  It's not an option *at all*.

Neither *combine* nor *union* cover the requested use-case which is being able to *"overload"* a list (or, eventually a dict) at *group_vars* level, see my example above (as well as the original one).
