### ISSUE TITLE
"No such file or directory" error on wildcards.

### ISSUE THREAD

**Issue by Pietia10** [ansible/ansible#18301]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

6.8 redhat to 6.8 redhat

##### SUMMARY
ansible host2 -a "cat /etc/*release"
host2 | FAILED | rc=1 >>
cat: /etc/*release: No such file or directory

##### STEPS TO REPRODUCE

ansible host2 -a "cat /etc/*release"

##### EXPECTED RESULTS
Red Hat Enterprise Linux Server release 6.8 (Santiago)
Red Hat Enterprise Linux Server release 6.8 (Santiago)

##### ACTUAL RESULTS
Wildcards aren't working in normal commands using -a and in playbooks.
This command works fine with -m raw .
The thing is the same command works fine for my friend.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is a 'local shell' issue, you need to use single quotes when calling Ansible with shell globing otherwise your local shell will try to interpret it.

`ansible host2 -a 'cat /etc/*release'`

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
