### ISSUE TITLE
Block issue on evaluating undefined variable

### ISSUE THREAD

**Issue by Bedotech** [ansible/ansible#18337]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
it appears on `block` feature.

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No custom config

##### OS / ENVIRONMENT
Ubuntu 16.04, x86_64, Python 2.7.12

##### SUMMARY
There is no way to execute a block of task if in the subtask use a loop over a undeclared variable.

##### STEPS TO REPRODUCE
```
- block:
    - name: Print some test in dict
      debug: msg="Is defined {{ item }}"
      with_dict:
        a: "{{ not_exists.a }}"
        b: "{{ not_exists.b }}"
        c: "{{ not_exists.c }}"

  when: not_exists is defined
```

##### EXPECTED RESULTS
I don't know if is bug or a known behavior, but for me it's better if a block doesn't meet a condition don't process at all the tasks inside, this can fast the execution to.

##### ACTUAL RESULTS

```
$ ansible-playbook -i "localhost," -c local  provisioning/test_playbook.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "Is defined 'test'"
}

TASK [debug] *******************************************************************
skipping: [localhost]

TASK [Print some test in dict] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'not_exists' is undefined"}
	to retry, use: --limit @/home/bedotech/Development/production-hosting/provisioning/test_playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

```

**Comment by rubal033** [comment]
The same thing also happening with other loops.

with_items: 
     - zabbix_agent_packages

above is not working , but rewriting it as below working.

with_items: "{{zabbix_agent_packages}}"

Due to this previous written playbooks/roles using loops need to be modified and can't be use at is.

**Comment by TheSameCH** [comment]
This is not only a block issue. We had to fall back to ansible 2.1.x because we use "is defined" conditions in a lot of tasks and they all fail in 2.2 instead of beeing skipped like in 2.1.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The block does NOT evaluate conditionals, they are there to be inherited by the tasks inside the block, since `when` executes inside the loop defined by `with`, it cannot short circuit definition errors.
As documented http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

@TheSameCH that behaviour was marked for deprecation in 2.0 and should be issuing deprecation warnings in 2.1 also. This was an error in 1.9 (but ignored), we stopped ignoring it in 2.0 but too many people relied on it so we deprecated it instead, if you don't change your plays you will not be able to use versions above 2.1.

**Comment by TheSameCH** [comment]
@bcoca thanks for the fast answer. That's ture, I remember such a warning... Could you please update your documentation on Loops where this is still listed as an example? Thansk! [http://docs.ansible.com/ansible/playbooks_conditionals.html](url)
Is there still a way to skip tasks when a variable is not defined?

**Comment by bcoca** [comment]
If you look at the example, that is NOT used with a loop, and if you look
at the page I linked you have the correct example for dealing with loops
and undefined variables.

---

Brian Coca

**Comment by Bedotech** [comment]
@bcoca thank for your reply, i think the `when` on a block is really an easy way for misunderstanding `block` feature, i will write in the mailing list, thank you.
