### ISSUE TITLE
postgresql_user does not work with user=PUBLIC

### ISSUE THREAD

**Issue by legrostdg** [ansible/ansible#1833]
```
postgresql_user: db=template_postgis user=PUBLIC priv=geometry_colums:ALL
```

fails because it tries to create a new user...

http://pastebin.com/PpSea9Ji

**Comment by mpdehaan** [comment]
something you would like to add a patch for?

Since pastebin is emphermal, contents of your post for posterity:

TASK: [postgresql_user db=template_postgis user=PUBLIC priv=geometry_colums:ALL] *********************
<192.168.122.216> ESTABLISH CONNECTION FOR USER: virt on PORT 22 TO 192.168.122.216
<192.168.122.216> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1357558845.99-121565026293290 && chmod a+rx /tmp/ansible-1357558845.99-121565026293290 && echo /tmp/ansible-1357558845.99-121565026293290'
<192.168.122.216> REMOTE_MODULE postgresql_user db=template_postgis user=PUBLIC priv=geometry_colums:ALL
<192.168.122.216> PUT /tmp/tmpOYuXT_ TO /tmp/ansible-1357558845.99-121565026293290/postgresql_user
<192.168.122.216> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-1357558845.99-121565026293290/postgresql_user'
<192.168.122.216> EXEC /bin/sh -c 'sudo -k && sudo -p "[sudo via ansible, key=qkntfqljjfzhgaxkcxnkpfgomcdqepdu] password: " -u postgres /bin/sh -c '"'"'/usr/bin/python /tmp/ansible-1357558845.99-121565026293290/postgresql_user; rm -rf /tmp/ansible-1357558845.99-121565026293290/ >/dev/null 2>&1'"'"''
failed: [192.168.122.216] => {"failed": true}
msg: password parameter required when adding a user

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
I also am not a user of the postgres module, I would suggest bringing up on the mailing list if this is not something you want to attempt to fix.  Seems like it needs to detect if the user already exists.

Thanks!

**Comment by mpdehaan** [comment]
Seems it just wanted a password

Knowing we have had lots of other users of this module and not any other reports, please bring this up on the list if you still feel it is a problem.

**Comment by legrostdg** [comment]
No, that's not the problem. "PUBLIC" is a generic user on postgresql (which already exists), it shouldn't try to add a user named "PUBLIC" ( and ask a password). It is probably an issue with double-quotes (I guess PUBLIC shouldn't be double-quoted). Please reopen this bug.

**Comment by mpdehaan** [comment]
@lorin perhaps you are the wrong person to ask, but as I think the original author of the PostgreSQL module, any thoughts on this?

**Comment by lorin** [comment]
I looked into this. I believe the issue is that "PUBLIC" is not actually a user in postgres. Instead, it's a special username  that can be used to grant privileges to all users in the system. 

In particular, if you ask postgres to list the users, it will not list PUBLIC, e.g.:

```
postgres=# \du
                             List of roles
 Role name |                   Attributes                   | Member of 
-----------+------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication | {}

postgres=# select rolname from pg_roles;
 rolname  
----------
 postgres
(1 row)
```

The postgresql_user module doesn't currently support PUBLIC. Let me give it a shot and see how difficult it is to add support for the special PUBLIC user.

**Comment by lorin** [comment]
This pull request could use a review by somebody more knowledgeable than I about postgres, but the changes are fairly modest.
