### ISSUE TITLE
vpnc dies immediately with command ansible 

### ISSUE THREAD

**Issue by sgreco2002** [ansible/ansible#18361]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

command

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Linux version 2.6.32-431.el6.x86_64

##### SUMMARY

i'm launching "vpnc" binaries in a playbook with "command" module.
But the vpnc immediately dies with this log message (taken from /var/log/messages file): 
```
"Nov  4 15:22:43 hostname vpnc[16521]: terminated by signal: 1 "
```
even if ansible stdout gives a:
```
ok: [localhost] => {
    "msg": "Enter username for IPADDRESS: Enter password for USERNAME@IPADDRESS: \r\nVPNC started in background (pid: 17214)..."
```
indeed, the 2nd step of playbbok tryes to close the vpnc , but i receive:
```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["vpnc-disconnect"], "delta": "0:00:00.003921", "end": "2016-11-04 14:40:06.297629", "failed": true, "invocation": {"module_args": {"_raw_params": "vpnc-disconnect", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-11-04 14:40:06.293708", "stderr": "", "stdout": "no vpnc found running", "stdout_lines": ["no vpnc found running"], "warnings": []}
```
##### STEPS TO REPRODUCE

1. install via yum vpnc
2. create a roles, with a below tasks:

```
- name: Opening VPNC Connection
  expect:
    command: vpnc avs_tunnel
    responses:
      (?i)username: <username>
      (?i)password: <password>
  register: vpnc

- debug: msg="{{ vpnc.stdout }}"

- name: Closing VPN
  command:  vpnc-disconnect
```

##### EXPECTED RESULTS

vpnc should be up and running 

##### ACTUAL RESULTS

vpnc dies immediately with system message:

```
`Nov  4 15:22:43 VA1CCQDNTP02 vpnc[16521]: terminated by signal: 1`
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The expect/command/shell modules are not designed to run backgrounded apps, you should setup a service, otherwise you'll hit race conditions like this one in which the service has not detached from the tty by the time Ansible closes it, causing it to fail.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
