### ISSUE TITLE
to_nice_json does not respect template identation

### ISSUE THREAD

**Issue by sermilrod** [ansible/ansible#18398]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
to_nice_json filter does not respect template identation, and consequently you cannot use the filter to template a variable and convert it to a json document within subkeys.

##### STEPS TO REPRODUCE
Lets assume we have have the following configuration block somewhere in our group_vars:
```
my_service:
    pipeline:
      key1: 50000
      key2: 1000
      key3: 40000
      key4:
        key5: 0.1
        key6: 0.2
        key7: 5000
```
And that our template looks like this:

```
{
  "something" : {
    "something_else": {
        "whatever": 1
    }
  },
  "pipeline" : {{ my_service.pipeline | to_nice_json }},
  "morestuff" : {
    "more" : "stuff"
  }
}
```

##### EXPECTED RESULTS

```
{
  "something" : {
    "something_else": {
        "whatever": 1
    }
  },
  "pipeline" :  {
    "key1": 10, 
    "key2": 1000, 
    "key3": 40000, 
    "key4": 50000, 
    "key5": {
        "key6": 0.2, 
        "key7": 5000, 
        "key8": 0.1
    }
  },
  "morestuff" : {
    "more" : "stuff"
  }
}
```

##### ACTUAL RESULTS

Just running ansible-playbook to generate that template I get this:

```
{
  "something" : {
    "something_else": {
        "whatever": 1
    }
  },
  "pipeline" :  {
    "key1": 10, 
    "key2": 1000, 
    "key3": 40000, 
    "key4": 50000, 
    "key5": {
        "key6": 0.2, 
        "key7": 5000, 
        "key8": 0.1
    }
},
  "morestuff" : {
    "more" : "stuff"
  }
}
```
As you can see the closing curly brace for "pipeline" is not aligned with its key.
If your config looks instead this way:

```
 "pipeline" : 
  {{ my_service.pipeline | to_nice_json }},
```

The result is as follows:

```
{
  "something" : {
    "something_else": {
        "whatever": 1
    }
  },
  "pipeline" :  
  {
    "key1": 10, 
    "key2": 1000, 
    "key3": 40000, 
    "key4": 50000, 
    "key5": {
        "key6": 0.2, 
        "key7": 5000, 
        "key8": 0.1
    }
},
  "morestuff" : {
    "more" : "stuff"
  }
}
```

In this last example, the starting curly brace gets properly indented as it is the position in which I want my variable contents to be placed in the template but the closing curly brace is still not properly tabulated.

**Comment by sivel** [comment]
This is not a but, but a misunderstanding in how jinja2 templating works.

`to_nice_json` has no concept of how or where it is called to know what indentation it should use.  Instead I would recommend 1 of a few things:
1. Combine use of `to_nice_json` with the `indent` (http://jinja.pocoo.org/docs/dev/templates/#indent) filter, to indent all lines after the first to a specific indentation level
2. Use a real data structures instead of inserting a partial into a larger JSON string, and then `to_nice_json` the entire data structure to get proper indentation.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sermilrod** [comment]
Thanks for the help @sivel that way I get what I need.
