### ISSUE TITLE
Distribute Ansible as a binary

### ISSUE THREAD

**Issue by bborysenko** [ansible/ansible#18502]
##### ISSUE TYPE: Feature Idea

It might be great to distribute Ansible as a binary with [pyinstaller](http://www.pyinstaller.org/) like docker-compose do. In this way it would be possible to for example bootsrap local server without even python environment installed.

What I have tried is:

```
$ virtualenv -p /usr/local/bin/python venv
$ venv/bin/pip install pyinstaller==3.1.1
$ venv/bin/pyinstaller --onefile bin/ansible-playbook
...
10720 INFO: Appending archive to EXE ./dist/ansible-playbook
10734 INFO: Fixing EXE for code signing ./dist/ansible-playbook
$ ./dist/ansible-playbook --version
Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "/private/var/folders/7s/t6j_vsgd46vgn9t97dd6r3y80000gn/T/pip-build-JOThXi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/ansible/constants.py", line 26, in <module>
  File "/private/var/folders/7s/t6j_vsgd46vgn9t97dd6r3y80000gn/T/pip-build-JOThXi/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/ansible/compat/six/__init__.py", line 54, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/7s/t6j_vsgd46vgn9t97dd6r3y80000gn/T/_MEIuYCPwz/six.py'
ansible returned -1

**Comment by abadger** [comment]
This is probably something that needs to be an Ansible Proposal if it is going to go anywhere.  I'll post a link to that process below.

There are some problems with this, though, so I'll tell you a few of those so you can judge whether you want to go through the proposal process or not:
- ansible depends on pycrypto and pyyaml, both of which have a compiled component to them.  So any binary installer will run into portability problems.
- Some binary installers attempt to work around portability problems by bundling more things.  Since some of the compiled portions of Ansible are cryptographic libraries the bundling would put us on the hook for supplying security fixes for projects for which we are not upstream and for which we may be ill-equiped to work on (for instance, if pyinstaller ends up bundling libssl because it's a dep of pycrypto)
- pip is the de facto standard for distributing python packages cross platform, not pyinstaller.  Adding pyinstaller support would be extra work for probably a limited audience.
- Someone from the community would need to step forward to show it was possible and take charge of maintaining it until/unless its popularity picked up relative to pip and system packages (our current release mechanisms).
- There's potentially architectural changes needed to make ansible work in an environment where there's no system wide python installed or the python that it runs with is different than the one that is on the system (for instance, running a task delegated_to localhost).
- Without solving the architectural problems, trying to use this for bootstrapping still means we'd only be using the pyinstaller packaged ansible to install a more complete python runtime to run the "real" install of ansible.  I'm not sure using pyinstaller is the best means of achieving that versus a more targeted install script of some sort.

# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
