### ISSUE TITLE
Module mercurial review

### ISSUE THREAD

**Issue by yeukhon** [ansible/ansible#1860]
This is my hg module. I looked at git just now and it is beautifully written.

Any case, I am used to writting my doc in numpy.doc style. So please don't mind the verboseness.

I am currently using this to deploy my test vms in my lab. I also setup dummy vagrant vms to test my this module. The existing contrib hg module was not usable to me.

Please judge.  Thank you for your time! 
https://github.com/yeukhon/ansible-mercurial

ps: I want to get feedback before putting in a pull request. Obviously this is just a module. Pull request = adding a single file.

**Comment by mpdehaan** [comment]
Yep.   When it goes into core I will expect the module docs to be consolidated because we don't use numpy.

From quickly skimming the code this looks pretty sharp and I don't think it has any code changes to make behavior wise.

As a minor code standardization thing, don't put spaces immediately after parenthis like dict( foo )

I'd suggest posting this to the mailing list if you haven't already to see if someone can help test.

**Comment by yeukhon** [comment]
Hi Michael,
Thank you for the quick review! :)
I will be posting this on the mailing list. I will close this meanwhile I guess.
