### ISSUE TITLE
should be able to use only jinja2 with "template" (without "ansible's templating")

### ISSUE THREAD

**Issue by legrostdg** [ansible/ansible#1868]
Actually, someone has to use escape "$" if he wants to actually print a "$" (else it may be replaced by ansible's templating).

At the very least, the doc for the "template" module should talk about "ansible's templating".

**Comment by akerl** [comment]
It seems like the cleanest solution would be for template to default to either Ansible's templating or Jinja2's templating, with an option "format" that accepted either a string or comma-separated list. This seems to piggyback with #1615, and would streamline the potential that somebody could implement other templating methods. The format parameter would set either the single format to use, or the sequential list of formats, so that "format='jinja,ansible'" would replicate how things work now.

**Comment by mpdehaan** [comment]
I would agree and would accept patches to enable "strict_jinja2_templates_only" or equivalent as a config file setting.

Something you would like to work on?

Yes, let's track this discussion on the other ticket.
