### ISSUE TITLE
Syntax Error with custom module

### ISSUE THREAD

**Issue by agaillar** [ansible/ansible#18747]
##### ISSUE TYPE
 - needs_info

##### COMPONENT NAME
- Custom module
- module_common.py

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /usr/users/idpihm/apps/ansible/cfg/ansible.cfg
  configured module search path =
```
##### OS / ENVIRONMENT
CentOS Linux release 7.1.1503

##### SUMMARY
Syntax Error when running a custom module with Ansible >= 2.1.0.0

I test my playbook with the new version ansible 2.2.0.0 but i have the error : 

```
fatal: [prod-cloud-ngx-1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "  File \"<stdin>\", line 99\n    from ansible_module_[name_module] import main\n                             ^\nSyntaxError: invalid syntax\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Same error with Ansible  2.1.3.0.
The custom module is OK with Ansible 1.8.4, 1.9.6 or 2.0.1.0.

Are there any specific changes to apply with Ansible >= 2.1 ?

**Comment by agaillar** [comment]
I copied the ```lineinfile.py``` module in my playbook: ```./library/test-lineinfile.py```
And I reproduce the same error ...

`fatal: [prod-cloud-ngx-1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "  File \"<stdin>\", line 99\n    from ansible_module_test-lineinfile import main\n                             ^\nSyntaxError: invalid syntax\n", "module_stdout": "", "msg": "MODULE FAILURE"}`

**Comment by sivel** [comment]
The 1st and 2nd problems are actually different, although with a similar error message.

In your first issue, the problem is likely that you do not have a function in your module named `main()`.  Ansible 2.1 introduced new functionality in how it builds the file to be executed, in that it creates a zip file.  As part of this, it attempts to import the `main` function for execution.  Without the code of your custom module I cannot tell you exactly what you need to change, but you will need to either rename your function that is called when the module runs to `main`, or create a `main` function that calls that function.

In your second instance, it is because you have a hyphen in the name of your `.py` file, and as such causes a syntax error in the shared code that tries to import based on the name.  Renaming the module `test_lineinfile.py` would likely work.

**Comment by agaillar** [comment]
Thank you very much Sivel !!!

I have a function main() in my module but all my modules are named [xxx]-[yyy].py !!! 
It's OK, now !
