### ISSUE TITLE
tmp dir to use on target should be configurable

### ISSUE THREAD

**Issue by benwtr** [ansible/ansible#188]
I often use the noexec flag when mounting /tmp, which prevents ansible from running anything on the target host.

Using /tmp is hard coded here, https://github.com/ansible/ansible/blob/master/lib/ansible/runner.py#L695

Can the tmp dir used become a configurable option? Perhaps with a command line flag, eg --tmp-dir=/var/tmp

**Comment by mpdehaan** [comment]
Sure, we can do something here... thinking about how to best expose it...

**Comment by mpdehaan** [comment]
proposal, rather than making this configurable, which burdens the user to fix this and they'd have to figure it out, how about...

if remote_user is root, always use /var/tmp

if user is not root, use ~/.ansible/tmp

these files are removed at the end of execution runs anyway and this would keep them isolated

**Comment by benwtr** [comment]
That solution will absolutely work for me and other people who can't use /tmp for whatever reason.

That's much better than adding another command line flag to work around the problem.

Thanks

**Comment by mpdehaan** [comment]
This is now done on the integration branch, will be also be available in the 0.3 release Monday.
