### ISSUE TITLE
ansible-playbook does not work when user is not root.

### ISSUE THREAD

**Issue by hackers-terabit** [ansible/ansible#18814]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
$ ansible --version
Traceback (most recent call last):
  File "/usr/bin/ansible", line 43, in <module>
    import ansible.constants as C
ImportError: No module named 'ansible.constants'

```
I hope the following substitues for this section, I posted 'verbatim' per instructions above. 

# pip show ansible
---
Metadata-Version: 1.1
Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /usr/lib64/python3.4/site-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto

---
##### CONFIGURATION
I have not configured a single thing. 

##### OS / ENVIRONMENT
I am running on gentoo hardened with pax disabled and rbac not configured or enabled (just so to rule those out)
I installed ansible via pip too to avoid any distro imposed bugs. 

##### SUMMARY
ansible-playbook is unable to find ansible.constants for some reason when starting.
This only happens when the user is *not* root for some reason.

##### STEPS TO REPRODUCE
$ pip install ansible 
$ ansible-playbook -kK -i hosts -vvv main.yml 
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 43, in <module>
    from ansible import constants as C
ImportError: cannot import name 'constants'

##### EXPECTED RESULTS
It will work as normal for non-root users.

##### ACTUAL RESULTS
 $ ansible-playbook -kK -i hosts -vvv main.yml 
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 43, in <module>
    from ansible import constants as C
ImportError: cannot import name 'constants'

**Comment by dinoocch** [comment]
Check your permissions on your `site-packages` folder for python.  Sounds like something got botched by pip... This seems to happen to me a lot on certain centos boxes as well... 🎱 Not sure if it's your issue, but certainly a good place to start

**Comment by abadger** [comment]
This is a problem with the installation of ansible on your box rather than a problem with ansible itself.  Since you say it's working for the root account and failing normal users I suspect that you have an older version of ansible installed somewhere.  The root account is not configured with the path that contains the old ansible python module and thus you don't get this error there.  Try looking at the directories in PYTHONPATH to see if they contain an ansible that you don't expect.  If that doesn't find anything, try opening a python shell and performing the imports to figure out the bad path:

(simulated)
```
$ /usr/bin/python
>>> from ansible import constants as C
ImportError: cannot import name 'constants'
>>> import ansible
>>>> ansible.__file__
/path/to/site-packages/ansible
```
The /path/to/site-packages/ansible is likely the culprit.

I'm going to close this as it's not a code problem with ansible.  If you need further help you probably should use the mailing list or the IRC channel.  I'll paste the information for both of those below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
