### ISSUE TITLE
compat/six/__init__.py execs six.py

### ISSUE THREAD

**Issue by unclejack** [ansible/ansible#19315]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
compat/six

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`ansible/lib/ansible/compat/six/__init__.py` tries to open six.py with a path relative to itself and then run it with exec.

Perhaps this should be a sub-package or something else instead? Would you accept a PR to make such a change?

**Comment by abadger** [comment]
Is this causing a problem?

six does some non-standard import magic itself and that was the only thing that ended up working correctly.  I blogged about all the things I tried here:

https://anonbadger.wordpress.com/2015/10/15/dear-lazyweb-how-would-you-nicely-bundle-python-code/

There was one reply about a different strategy using imp.load_module() that might be worth looking into if you want to take a look at doing it that way.  the requirements that I can remember us having:

* Transparently use the system package or the bundled package so that imports do not have to change
* The import shouldn't break in unexpected ways (in the blog post, it's where I mentioned all the stuff about: ```from ansible.compat.six.moves import urllib```)
* System packagers need an easy way to disable bundling.  For us, that means use six from the system package if it is available and high enough version.  Otherwise use our bundled version.

I don't believe that a subpackage would have any effect on this.

If you want to discuss this with me before launching into work (or while working), contact me on IRC.  I'm abadger1999 on irc.freenode.net #ansible-devel channel.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a developer question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by abadger** [comment]
This isn't really a user question but it is somewhat clunky to try to discuss it in a github issue.

@unclejack if you want to discuss it, probably best to find me on irc (My user should be logged in nearly always.  If I don't reply immediately, I will still read what you say later.)  If you just want to try out some code (probably based around imp.load_module) feel free to open a pull request and then draw my attention to it via IRC.  Thanks!
