### ISSUE TITLE
docker_image does not rebuild Docker image after Dockerfile is changed

### ISSUE THREAD

**Issue by kuromt** [ansible/ansible#19379]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

docker-py==1.10.6
Docker version 1.12.3, build 6b644ec(Docker for Mac)

##### SUMMARY

MacOS 10.12.1

##### STEPS TO REPRODUCE

After docker_image module build my own docker image once, I change my Dockerfile and execute my playbook again.
But build task succeeded with 'OK', not 'changed'.

 

```yaml
- name: build my docker images.
  docker_image:
    path: "{{ dockerfile_dir }}"
    name: mydocker_image
    state: present
```
This is part of my ansible role to install Docker and build Docker image.

##### EXPECTED RESULTS

I expect docker_image module recognize Dockerfile is changed and rebuild the image.

##### ACTUAL RESULTS

```
$ ansible-playbook play-book.yml
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install-docker : build my docker images.] ****************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0  

```

**Comment by mkwardakov** [comment]
Reproduced in the same environment. Seems reasonable to check Dockerfile mtime vs image creation time.

**Comment by tumbl3w33d** [comment]
See the force parameter.

**Comment by kuromt** [comment]
Sorry, I missed the parameter.

But it is not intuitive that the default  behavior of ansible_image module is different from Docker command's behavior.
"docker build" command looks the mtime of Dockerfile and related files and build the image if they are changed.

What do you  think about that?

**Comment by tumbl3w33d** [comment]
I thought so too, at first. However, from an ansible perspective it seems reasonable to me. If you execute the play twice, you would expect the image not to change, because the play itself didn't change (the change is external, in the Dockerfile) and you defined _state: present_, not _state: latest_ (which does not exist).

Unfortunately, _force_ is ambiguous as well. While you get your image newly built, it kind of implies to me that it's really built from scratch. That's not the case, though, since there is the _nocache_ flag for this.

So, yeah, the combination of the missing _state: latest_, _force_ and _nocache_ do not exactly add to this module's usability.

They probably argue that, what you ask for, should be part of a different playbook, a (re-)deployment playbook, not the "initial setup" kind of playbook as it essentially changes the system. It's less likely with your own low-level Dockerfile (e.g., a debian-base), but don't forget the case where you just use some higher level public images (e.g., anapsix/alpine-java). In this case a _force_ causes the latest remote version to be pulled (because _pull_ is true by default) which can result in your setup/application failing.

**Comment by kuromt** [comment]
Thanks, I very agree your comment.
I close this issue.

**Comment by cinemast** [comment]
I would still argue that a "latest" state would be very useful.
