### ISSUE TITLE
install simplejson

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#1943]
I have some servers not connected to a repo, where python-simplejson is not installed.
Now the "getting started" guide says this:
"
Ansible’s “raw” module (for executing commands in a quick and dirty way) and the copy module – some of the most basic features in ansible – don’t even need that. So technically, you can use Ansible to install python-simplejson using the raw module, which then allows you to use everything else. (That’s jumping ahead though.)
"
I already confirmed that the raw module indeed works as described, but the copy module does require simplejson (contrary to the doc), so how can I copy over the needed rpm files for installation using ansbile?

**Comment by mpdehaan** [comment]
Personally I would probably wget the EPEL release RPM with raw, install the EPEL release RPM with raw, and get simplejson out of yum

We definitely need to update the doc and may want to also update the copy module so that if json support isn't yet available the last part (executing the file module and so on) can remain operational.  It actually used to work more or less that way though there were compelling advantages to have the file support built in there.  I think we can definitely streamline this though.

**Comment by liedekef** [comment]
They don't have access to the internet and I'm not going to mirror the epel just for those (old redhat 4).
In the past, the copy module didn't need simplejson. I tried to create a new module based on that older code, but it doesn't work ...
So ansible needs simplejson to just emulate a scp to a bunch of servers for now.
I know the simplejson install is a one-time deal, but in an older version of ansible this probably would've worked ...

**Comment by liedekef** [comment]
Ok, it just got worse ... I've put the simplejson package on an internal webserver as workaround, so I could do a wget and install, but the python on those servers is 2.3, and ansible requires 2.4 I guess.
I can accept the webserver wget as workaround, but this requirement leaves a whole lot of servers unmanageable for now, so I need to rethink the whole thing ...

**Comment by mpdehaan** [comment]
We do require python 2.4.

You could perhaps bootstrap 2.4 via primative parallel ssh or in your
kickstarts, and then set ansible_python_interpreter to path to it.
