### ISSUE TITLE
Run ansible-lint on integration tests

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#19736]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
integration tests

##### ANSIBLE VERSION
devel

##### SUMMARY
The integration tests in this repo should follow current best practices. I'd recommend to run `ansible-lint` on them to ensure this.
Since the integration tests don't follow the standard playbook/role layout one has to think about how to best run those.

**Comment by robinro** [comment]
cc @willthames

**Comment by bcoca** [comment]
I'm not sure tests should follow best practices, sometimes they need to make sure the 'non best' also works.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this PR for now, we have plans for ansible-lint in the future but they probably will be related to galaxy and collections and not the core repo.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implanting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
