### ISSUE TITLE
FreeBSD target: service: name=postgresql state=* hangs the whole playbook

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#19763]
Issue Type:
Bug Report

Component Name:
service module

Ansible Version:
ansible 1.9.4

Ansible Configuration:
retry_files_enabled = False

Environment:
Running from Mac OS X 10.10.5, python 2.7.10
to FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015
with PostgreSQL 9.4.5

Summary:

Attempting to use the 'service' module to control PostgreSQL hangs every time. I strongly suspect that this is the same issue as ansible/ansible#5923

Steps To Reproduce:

```
1) Install postgres94-client and postgres94-server packages on FreeBSD 10.1
2) set up inventory so that the dbserver is in group fll2-dev-dbservers in inventory file development.ini
[fll2-dev-dbservers]
fll2gdbs01dev

3) ansible -vvvv -i development.ini fll2-dev-dbservers -m service -a "name=postgresql state=stopped"
```

Expected Results:

pg_ctl is called to stop the server, returns when finished, ansible reports success/failure and server state

Actual Results:

```
<fll2gdbs01dev> ESTABLISH CONNECTION FOR USER: rmartin
<fll2gdbs01dev> REMOTE_MODULE service name=postgresql state=restarted
<fll2gdbs01dev> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/rmartin/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 fll2gdbs01dev /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931 && echo $HOME/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931'
<fll2gdbs01dev> PUT /var/folders/j_/gh1x7cn138b04zb7w6q41ffw59y07m/T/tmpHfd5G9 TO /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/service
<fll2gdbs01dev> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/rmartin/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 fll2gdbs01dev /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python2.7 /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/service; rm -rf /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/ >/dev/null 2>&1'
```

ps auxww excerpt on the server during the hang:

```
rmartin 1258   0.0  0.1 17068  2484  0  Is+   3:14PM  0:00.01 /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python2.7 /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/service; rm -rf /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/ >/dev/null 2>&1
rmartin 1259   0.0  0.3 81724 13236  0  S+    3:14PM  0:00.16 /usr/local/bin/python2.7 /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/service
rmartin 1261   0.0  0.1 17068  2852  0  I+    3:14PM  0:00.03 /bin/sh /usr/local/etc/rc.d/postgresql onestatus
root    1268   0.0  0.1 49768  2652  0  I<+   3:14PM  0:00.00 su -l pgsql -c exec /usr/local/bin/pg_ctl -D /usr/local/pgsql/data -l /dev/null -w -s -m fast status
```

I have tried both with and without the fix suggested in the old ticket #5923:

```
postgresql_flags="-l /dev/null -w -s -m fast"
```

It has not made a difference.

Note that copying the ansible command

```
LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python2.7 /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/service; rm -rf /home/rmartin/.ansible/tmp/ansible-tmp-1447359262.53-79308781944931/ >/dev/null 2>&1
from the hung SSH command above, and pasting it into a bash prompt running on that server over interactive SSH works fine.
```

Any ideas why this is misbehaving, or how to work around it?

**Comment by geerlingguy** [comment]
Copying this over from old issue https://github.com/ansible/ansible-modules-core/issues/2459 — following up here, as I've had this issue when running certain playbooks inside Docker containers (e.g. MySQL in Ubuntu 14.04).

See my my progression of comments here:

  - https://github.com/ansible/ansible-modules-core/issues/2459#issuecomment-246868528
  - https://github.com/ansible/ansible-modules-core/issues/2459#issuecomment-246870463
  - https://github.com/ansible/ansible-modules-core/issues/2459#issuecomment-246880847

**Comment by yabhinav** [comment]
# Summary
facing similar issue with docker image centos:6 on  docker  and ansible releases
Issue replicable on older versions of docker and ansible too!!!
first run of the service module is ok
second and further runs will cause this issue.
with cento6 specifically because of using /sbin/init instead of /systemd in centos7 and fedora25


## Docker Version
MacBook-Pro:$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true


## Ansible Version
MacBook-Pro:ansible-role-ipaserver abhinav$ docker exec "$(cat ${container_id})" bash -c " source ~/.bashrc &&  workon ansible_latest && ansible-playbook --version && exit"
/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
ansible-playbook 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override


## Workaround

Diable --tty with `docker run --detach` and `docker exec`
Also docker should be upgraded to latest 1.13 as 1.12 still has this bug.

Add the following to your travis before_install (travis runs on ubuntu 12.04)
```
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git docker-engine
```

Need a permanent fix from module to handle `/sbin/init` properly  as we would like to enable --tty with docker builds

**Comment by geerlingguy** [comment]
Noting that I've been hitting something similar(ish?) when using the `service` module with CentOS 7 (which swaps the params over to the `systemd` module. This isn't necessarily the same issue, but I wanted to mention it just because it's a weird case where I'm having trouble even finding where the problem lies.

The command works with the same Docker container when it's run with just the one role in Travis tests; but it seems to fail when it runs as part of my Drupal VM playbook: https://travis-ci.org/geerlingguy/drupal-vm/jobs/209125708#L455

(Edit: It seems to hang whether I run `docker exec` or run it within the container using `docker exec -it bash`)

(Edit 2: Even stranger... I just noticed that my Firewall role adds both an init script and a systemd unit file. This seems to work in some instances, but not in others—for some reason `systemctl start|stop|status` was hanging, and that probably translated into Ansible hanging.)

(Edit 3: Apparently installing something within the `@development` package set on CentOS 7 causes this strange hang to occur (regardless of whether I'm using the init script, the service unit file, or both).)

**Comment by geerlingguy** [comment]
Just wanted to post an update, since I completely forgot to do so when I _actually_ fixed the problem: in my case, `systemd` was outdated in the Docker container, and as part of the `@development` installation via the `yum` module, the `systemd` packages were updated.

Once that happened, systemd started going insane inside the container, and the only fix was to restart (stop and start) the container. The _ultimate_ fix was to rebuild the Docker image so it had the latest version of systemd already installed. Once I rebuilt the image things worked great again.

**Comment by geerlingguy** [comment]
Does this actually have a PR? I don't even recall the scope of the issue, but I haven't been having any issues with my tests _lately_... so it might've just been related to systemd issues and not an Ansible bug.

**Comment by electrofelix** [comment]
@geerlingguy I've been meaning to follow up on this for a few years. I recall debugging a couple of problems, that may be less important now. One is a race condition around where the checking if the process is still running is done after checking for output returned. The problem being that output might be returned in between. The second is that additional process file descriptors may exist and be left open by the call to subprocess which can cause issues with sysv init scripts resulting in the service executable getting terminated as the connection closes.

It's been a while since I originally put together some fixes so even though I've just pushed up the changes at https://github.com/ansible/ansible/compare/devel...electrofelix:fix-service-module?expand=1 I'm a little rusty on the impact, but it might be worth testing these out to confirm that they are still useful. Not sure how to write tests for them at the moment.

**Comment by bcoca** [comment]
closing as per above, this seems an issue unrelated to the ansible service module itself.

In any case the new `timeout` keyword can also be used to mitigate the issue if it arises again.
