### ISSUE TITLE
List of options that don't feel conforming

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#20160]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_chocolatey win_get_url win_package win_reboot

##### ANSIBLE VERSION

v2.3

##### SUMMARY

I noticed, compared to the standard (Unix) Ansible modules, that some of the Windows modules have (needlessly) long or different option names, and I wonder if this was a deliberate decision.

**win_chocolatey** --> #21533
- ~`upgrade: yes` --> `state: latest`~

**win_get_url** --> #26464 + #26612
- ~`skip_certificate_validation` instead of `validate_certs` (reverse boolean)~
- ~`username` --> `url_username`~
- ~`password` --> `url_password`~

**win_package** --> #25398 + #27470
- ~`user_name` --> `username`~
- ~`user_password` --> `password`~

**win_reboot** --> #26466
- ~`connect_timeout_sec` --> `connect_timeout`~
- ~`pre_reboot_delay_sec` --> `pre_reboot_delay`~
- ~`reboot_timeout_sec` --> `reboot_timeout`~
- ~`shutdown_timeout_sec` --> `shutdown_timeout`~

**Comment by nitzmahone** [comment]
A lot of this stuff was *not* deliberate- it came from a time when nobody was "minding the store" on the Windows side, just merging whatever worked and not considering UI stuff like that. 

I did consciously do things like adding "_sec" to win_reboot because I personally find it obnoxious when I don't know what units are in use for stuff like that (sec/min/hour/ticks/fortnights/etc). 

I wouldn't be opposed to shorter/more "conforming" aliases for some of those, but I'd like to leave the default documentation pointing at the longer versions (in the `_sec` cases).

**Comment by bcoca** [comment]
we should follow the normal pattern, put the units in the description, if you have the same option that uses different units, this might make sense, i would just redo it to  use the lowest unit possible and user filters/math to allow setting via larger units.

**Comment by dagwieers** [comment]
All set, we can close this one now.
