### ISSUE TITLE
Allow ansible-galaxy to use a vaulted requirements.yml

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible#20168]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible-galaxy
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

ansible-galaxy should prompt for a vault-password if requirements.yml is encrypted. My requirements.yml contains private github repo's with o-auth tokens in the https URL's. I rather commit requuirements.yml as an ansible-vault file.  
##### STEPS TO REPRODUCE

ansible-galaxy install -r requirements.yml
Vault-password:

```yaml

```

##### EXPECTED RESULTS

decrypted on the fly
##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
Anyone using the vault password for galaxy can just as easily use it to edit the vile via ansible-vault and see the credentials. 

I would suggest having each user have his/her own auth credentials to the repo vs using a shared account.

**Comment by bbaassssiiee** [comment]
For automation, like with 'ansible-container build', we would like a non-personal o-auth token. But in git we don't want to store that in plain text.

**Comment by dhajoshi** [comment]
Is the something there yet ? can i use token as variable and inside requirements.yaml call it with {{ token }} ?

**Comment by keilr** [comment]
I think just being able to use variables would be sufficent. See #36395.

**Comment by jimi-c** [comment]
Hi, based on the fact that there is a preferred method of using variables for this (see @keilr's comment above), and there has been no other traction on this issue, we're going to go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
   * IRC: #ansible or #ansible-devel on irc.freenode.net

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
