### ISSUE TITLE
Script module does not work asynchronously

### ISSUE THREAD

**Issue by piercer** [ansible/ansible#20232]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Async and Script modules

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /*****/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Cygwin

##### SUMMARY
The title says it all.

We have a long running shell script as part of our deployment and very aggressive load balancers culling sessions that seem to be doing nothing.

I thought that 'async' would be the cure for this, but for some inexplicable reason I get the message

'async mode is not supported with the script module'

which I would have thought would be one of the main users of async mode.

This can't be right, surely?

Please advise as to how to proceed.

##### STEPS TO REPRODUCE
```
- name: Execute script
  script: execute_something_long.sh
  async: 7200
  poll: 60
```

##### EXPECTED RESULTS
I expected the script to run asynchronously for a maximum of 2 hours with Ansible polling every minute to check if the script has finished

##### ACTUAL RESULTS
```
fatal: [*****]: FAILED! => {
    "failed": true,
    "msg": "async mode is not supported with the script module"
}
```

**Comment by sivel** [comment]
Due to script not requiring python on the remote side, it has no support for async, since the async functionality runs more like a module.

I would recommend using `copy` to copy the script up, and then `command` to execute the script with `async`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
