### ISSUE TITLE
In ec2 module, allow security to be specified by ID as well as name

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2029]
Just got this error:

TASK: [Launch new EC2 instance] ********************\* 
fatal: [127.0.0.1] => failed to parse: ....
{"msg": "InvalidGroup.NotFound: The security group 'sg-4508022d' does not exist", "failed": true}

It would be great if either ID or the security group could be used here in the playbook YAML.

**Comment by mpdehaan** [comment]
Think we already had a bug about this one.

(Remember details guys?  Already fixed upstream maybe?)

cc @lwade 
cc @tgerla

Thanks!

**Comment by lwade** [comment]
Hi Rob,

I might be misunderstanding your request here but are you positive that you are running this with the correct set of the credentials?  Even the older euca2ools-based ec2 module supported a groupname such as the one your output suggests.

When you say "allow security to be specified by ID", what do you mean? Currently with the module we use boto run_instances and this takes the names of security group(s) as arguments.

Can you provide the arguements to the module that you are using?

Thanks :)

**Comment by tgerla** [comment]
The EC2 API appears to take both a security group name and a group ID (ie, sg-0342866a), but I indeed reproduced Rob's problem. The EC2 API spec says RunInstances should take both, but I can't tell if maybe this is a problem with Boto. I'm looking into it...more to come.

**Comment by lwade** [comment]
Thanks tgerla, understood. So I can validate that this doesn't work.  It looks like we'd need to use a new method of launching an instance with python boto to get security group ID's working, although this is only from a very brief flick through the documentation.

**Comment by lwade** [comment]
Looks like we might need to use this parameter with the run_instances call: security_group_ids

I'll test this on monday but adding this as a separate parameter seems quite trivial.

**Comment by lwade** [comment]
Brief update, security_group_ids works just fine.

**Comment by robparrott** [comment]
Hi All,

Trying to follow this thread, it looks like (a) you've confirmed that using
the SG id (and not it's name) does not work, and are aware of the cause.
Anything more needed from me?

I would suggest that the simplest, easiest approach for the end user would
be to try the provided string as if an id (i.e. "sg-123...")  and then on
failure try as if a more general string. Given the EC2 name conventions
already in place, the likelihood of a collision is small.

Rob

**Comment by tgerla** [comment]
I'm OK with this fix but I'd like to run it by Lester and Michael--what do you guys think? We have two options:
1. follow boto convention and add another option to the module, security_group_id
2. add some intelligence and check for sg- and send it in as a group id instead of a group name

For what it's worth we should also support passing _lists_ of security groups and group ids, but that's a separate issue.

Opinions?

**Comment by lwade** [comment]
I'm with (1).  I think at the moment its better if we stick close to it.  Tracking the way boto does it could make things simpler for us in the future and if this module gets quite large.  We also need to think about botocore (the next version of boto afaik) and how that could impact us.

I've already made a commit which adds an additional parameter, which at least gives the user the option.

Re: lists.  Completely agree, this is a new issue for both the SG-related parameters and needs to be addressed.

**Comment by skvidal** [comment]
is there a case where someone would want to specify a group  name and a groupid and where the groupid won't start with sg- but the groupname might?

sorry - but it feels like a bad decision in boto that there isn't much reason in duplicating.

**Comment by lwade** [comment]
Nope.  So the AWS API docs for RunInstances can be found here: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-RunInstances.html.  It's down to whoever is wielding boto but I can understand why it was implemented this way, since the two parameters are separate in AWS.  The GroupID was introduced later into the API spec by the looks of it, since it's required for VPC (so arrived about the same time as this service).  Both are conditional but this bit probably sums it up:

Condition: For EC2, you must specify either a group ID or a group name

... but within Boto you cannot pass the groupID via the group name parameter.

What if someone names their group name the same as their group ID?  We'd analyse the formatting and assume its an ID and so pass it as security_group_ids to the run_instances action. Since SecurityGroupId is optional for EC2, how does boto handle this? I'd imagine that it would place the instance into the default group (since no group specified = default) AND the group ID specified.  This isn't very explicit based on what the user wanted to achieve. I've not tested extensively but I think I'm still for splitting them.  Particularly as AWS indicated that ID's are (or were developed specifically) for VPC and names are for EC2.

**Comment by lwade** [comment]
p.s I should put a disclaimer to say that I'm probably the person least qualified to comment with authority in these discussions ;)

**Comment by robparrott** [comment]
Hi Lester,

I have to say that if someone named their security-group the same as their
group ID, or anything that starts with "sg-*," they probably shouldn't be
allowed near computers in the future :-)

Rob

**Comment by lwade** [comment]
LOL :D That may be true but its perhaps still a risk to consider, although quite minimal.

**Comment by mpdehaan** [comment]
any update on fixing this one (or what the desired result is?)

**Comment by tgerla** [comment]
Lester, you said you had a commit that enabled group_id to be passed through? Is that in a PR somewhere? I can't find it. I think this is the best solution--I think adding logic to detect strings beginning with "sg-" is probably not a good idea--I'd rather stick as close to the upstream API as possible. Rob, is that OK? Would that get you unstuck, at least?

-Tim

**Comment by lwade** [comment]
Hey guys.  Yeah I've got a minor addition for this which adds a group_id parameter.  I just need to test it one last time and re-submit (my earlier pull request was for an older unworking version). I'll fire this over tomorrow morning.

**Comment by lwade** [comment]
So, I thought I'd fixed this but actually I hadn't (lack of testing).  It appears that the security_group_ids parameter to the run_instance method is only for VPC security group ID's, not EC2 and VPC group ID's.  Then, the security_groups parameter is ONLY for names, not for ID's.  So, to sum that up, this works for VPC security group ID's but not EC2 ones. Having trawled through the boto EC2 API reference, I don't see any way of doing this other than a lookup of the security group ID beforehand, which might work:

 get_all_security_groups(group_ids=param)

**Comment by lwade** [comment]
Yup, that works ok.  Let me tidy it up a little later today and put in the pull request.
