### ISSUE TITLE
2.2.1.0 fails while decoding vault key to UTF-8

### ISSUE THREAD

**Issue by nblock** [ansible/ansible#20398]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /path/to/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
- pyenv on Debian 9
- Python 2.7.13

##### SUMMARY
Ansible tries to decode the content of the vault key as UTF-8:
```
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
```

The first few bytes of the vault key are:
```
39 e6 cb
```

##### EXPECTED RESULTS
This worked without issues in 2.2.0.0 (same OS, same Python)

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
the full traceback was:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/ansible/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/cli/playbook.py", line 110, in run
    vault_pass = CLI.read_vault_password_file(self.options.vault_password_file, loader=loader)
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/cli/__init__.py", line 589, in read_vault_password_file
    return to_text(vault_pass, errors='surrogate_or_strict')
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/module_utils/_text.py", line 177, in to_text
    return obj.decode(encoding, errors)
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
```

**Comment by nitzmahone** [comment]
cc @abadger

**Comment by abadger** [comment]
I think this is expected behaviour in general as passwords (when typed from a keyboard) would need to be treated as text.  All text in ansible is treated as coming from or going to utf8.

That said, it isn't good to change this in the middle of a stable release.  It probably snuck in along with a python3 fix.  I'll see if I can revert (or fix in a different way) for stable-2.2 (would be 2.2.2) but you'd want to rekey with a utf8 password before upgrading to 2.3.  I'll have to figure out if it's only the passwords being retrieved from files that were passing raw bytes through or if it's also the passwords being entered from the keyboard.

**Comment by abadger** [comment]
Here's the PR that introduced the change: https://github.com/ansible/ansible/pull/18699
And the issue that was being fixed: https://github.com/ansible/ansible/issues/18684

Going to have to tread lightly here as this was an intentional change to fix a bug.  Don't want to regress that while making this work for 2.2.2.

**Comment by nblock** [comment]
`… but you'd want to rekey with a utf8 password before upgrading to 2.3.`
Sounds reasonable.

**Comment by urajio** [comment]
My vault password is just a random bytes in the file. Now any ansible command ends with error.
How I can rekey to new password?

**Comment by nblock** [comment]
@urajio See https://docs.ansible.com/ansible/playbooks_vault.html#rekeying-encrypted-files

**Comment by urajio** [comment]
**ANY** ansible command ends with error now. ansible-vault too.

**Comment by nblock** [comment]
@urajio You need to downgrade to a version < 2.2.1.0, perform the vault re-keying and upgrade afterwards.

**Comment by abadger** [comment]
Just a followup here: The code fixing this was added to the stable-2.2 branch via #21491 and should be in the next release of 2.2.x (currently making  release candidates).   We've re-evaluated how we want to do this in devel and decided that for 2.3 we'll pass bytes through verbatim as well (so no need to convert to a utf8 password).  For 2.4 onwards we may add a commandline argument to optionally allow converting the password from the locale's encoding to a specific encoding (still debating whether that's needed or if people can just modify their locale settings if they need this functionality).
