### ISSUE TITLE
include_role doesn't work from handlers

### ISSUE THREAD

**Issue by sparunakian** [ansible/ansible#20493]
Hi,

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/stephane/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Nothing special

##### OS / ENVIRONMENT

Ansible running from ArchLinux, managing an OpenBSD machine, but the problem is with any managed machine.

##### SUMMARY

When the include_role module is used within an handler, the calling role fails, before knowing if the handler will be called.

##### STEPS TO REPRODUCE

Create the simple following role:

calling-role/tasks/main.yml
```yaml
---
- name: task with notify
  debug: msg="test"
```

calling-role/handlers/main.yml
```yaml
---
- name: handler
  include_role: name=called-role
```
called-role can be any role, with at least on task.

I run this role with this playbook:
```yaml
---
- hosts:
    - all
  roles:
    - calling-role
```

##### EXPECTED RESULTS

I expect the playbook to run.

##### ACTUAL RESULTS

The playbook doesn't run, it fails immediately.

```
Using /home/stephane/.ansible.cfg as config file

PLAYBOOK: main.yml *************************************************************
1 plays in main.yml

PLAY [all] *********************************************************************
ERROR! Unexpected Exception: 'Task' object has no attribute 'listen'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 248, in run
    self._initialize_notified_handlers(new_play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 143, in _initialize_notified_handlers
    if handler.listen:
AttributeError: 'Task' object has no attribute 'listen'
zsh: exit 250   ansible-playbook main.yml -vvv
```

The problem still exists with the devel branch (216e2c8).

Let me know if I can be of any help concerning this issue!

Stéphane

**Comment by jctanner** [comment]
cc @bcoca

**Comment by bcoca** [comment]
I'm not sure this 'should' work

**Comment by sparunakian** [comment]
Why is that ? Shouldn't all modules work in handlers ?

**Comment by oryband** [comment]
Confirming this issue. Behavior is confusing.

**Comment by thelmstedt** [comment]
I was also confused by this. My use case is deployment vs application restarts: both need to take the server out of the load balancer, perform the action and put it back in. Ideally my 'restart appserver' handler could use the same LB logic as my deployment playbook. `include_role` seemed to be the only way to achieve this

**Comment by ingvagabund** [comment]
If `include_role` should not be supported in handlers, what other way is there to share handlers among roles and at the same time to avoid relative includes of files reaching out of a role? Code duplication is not a solution.

**Comment by sandinak** [comment]
+1 on this .. need this functionality.

**Comment by cognifloyd** [comment]
`import_role` has this issue as well

**Comment by decentral1se** [comment]
Oh darn. Ran into this now via `ERROR! 'listen' is not a valid attribute for a IncludeRole` on:

```yaml
# handlers/main.yml
- name: Create the SSH user accounts.
  listen: "Run Linode bootstrap."
  import_role:
    name: ssh-user-mgmt
  when:
    - linode_details is defined
    - linode_details.changed
    - with_ssh_user_mgmt
  delegate_to: freshly-created-linode
```

I wouldn't probably be putting tasks like this in the handlers file but `ansible-lint` has a rule to push you to use handlers for tasks that rely on changed results. This may be a source of bugs in Ansible core going forward.

**Comment by lm1427934400** [comment]
with the same problem

**Comment by renatomassaro** [comment]
Any workaround?

**Comment by renatomassaro** [comment]
Ok, found a workaround:

```
- name: reboot server
  include: ../../util/tasks/reboot.yml
  static: no
```

It's ugly but well, it's a workaround. The `static` was added due to another bug, the handler may work without it.

**Comment by Illydth** [comment]
The workaround above requires your code base to "call out" to a different bit of ansible code outside the module which is, generally speaking, bad practice.  What you have above is a hard coded reference to including a specific yaml file, not using Ansible's role structure to allow ansible to call out to a role.  If that yaml file moves locations or gets checked out into a different location the unrelated self contained role you're calling that from will fail...and God help you if someone goes on Disk and adds random code to reboot.yml to fix an edge case.  

(Imagine for me a moment where on one server for one run someone decides that they need to delete the /opt or /var/<something> directory upon reboot to get a package install to work so they decide to just modify that "randomly laying around on disk" reboot.yml to do that quickly...)

In programming nuance, what you've done is "goto line 200" instead of "call my_function()"

I'm going to +1 this as well.  For something as simple as "reboot the server" it's annoying to have to write and re-write this code 100 times across 100 different roles in 100 different "handler" directories.  I should be able to develop a process for something and then when that "thing" needs to be triggered by a change call the role.

**Comment by Kassec** [comment]
+1, need this. I just wrote a role that does some sanity checks on systemd reloads (some apps do not report errors but still don't restart properly) and I'll have to duplicate the same code over several places to circumvent this limitation.

Any status update from core team ?

**Comment by suharshan** [comment]
+1 need this badly. 

```
- name: "Configure {{ service_name }} ({{ service_type }})"
  import_role:
    name: myrole
  notify: "{{ service_type }}-restart-after-configuration {{ service_name}}-restart-after-configuration"
```
results in `ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'listen'`

**Comment by lynyrds** [comment]
+1
Would be great to know if a fix is somewhere in sight.

**Comment by Asgoret** [comment]
Problem is here) 
```
ansible 2.8.6
  config file = /home/worker/Documents/Bitucket/dev-04/ansible.cfg
  configured module search path = ['/home/{user}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/{user}/.local/lib/python3.6/site-packages/ansible
  executable location = /home/worker/.local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

**Comment by Sheridan** [comment]
+1 need this too

**Comment by Sheridan** [comment]
> sparunakian opened this issue on 20 Jan 2017

Oh, it seems to me that there will be no happiness :(

**Comment by EpiqSty** [comment]
Yes it's still broken at ansible 2.8.6:
```
ERROR! Unexpected Exception, this is probably a bug: 'IncludeRole' object has no attribute 'notified_hosts'
```

**Comment by packetfairy** [comment]
Here's a workaround for this _three year old bug_ that I finally found after two solid days of aggravation. It can probably use some cleanup... and I _might_ have screwed things up while I sanitized it for this post, but hopefully it will at least be a good starting place for someone.

Important details which make this work:
- a dependent role's handlers can be triggered by the enclosing role
- handler tasks are executed in the order in which they are defined in the handler file
- `listen` is your friend -- tho a sort of jerky friend, since you can only define one listener per handler, rather than a list (cuz, really, why?)

What this means is that you can stick your shared handlers into the handlers file for a shared role, and then load that shared role as a dependency in order to make them available to other roles.

Here's how I was able to make this work. First, the handler role:

roles/myhandlers/defaults/main.yml:
`---
# file: roles/myhandler/defaults/main.yml
#
# this is the hacky way I define a service I want to act upon, and/or a
# command I want to run, and/or set the host up to be rebooted.
# 
# the main drawback here is that, at least as I've written it so far, I 
# can only do a maximum of one each of these three tasks in a single 
# ansible run... which makes it a bit inflexible, still... I suppose I 
# could handle this more gracefully with a list or a dictionary, but,
# after two days, I'm just happy to have it working, so it's fine for a
# first draft.
#
myhandler_reboot: False
myhandler_service_act: False
myhandler_service: False
myhandler_service_state: False
myhandler_command_run: False
myhandler_command: False
`

roles/myhandlers/handlers/main.yml:
`---
# file: roles/myhandlers/handlers/main.yml
#
# these are two handlers that would otherwise be called by
# an enclosing role. I include them here for the purpose of
# sequence precedence. if I leave them in the handlers file
# of the enclosing roles, I cannot be certain the facts
# will be set before they are called upon.
#
- name: restart ipsec (set_fact)
  set_fact:
    myhandler_reboot: False
    myhandler_service_act: True
    myhandler_service: 'ipsec'
    myhandler_service_state: 'restarted'

- name: reload iptables (set_fact)
  set_fact:
    myhandler_reboot: False
    myhandler_command_run: True
    myhandler_command: '/etc/network/if-up.d/restore_iptables'

#
# what follows through to the end is the set of tasks I want
# to call; this has largely been stolen wholesale from
# https://docs.ansible.com/ansible/latest/modules/elb_target_info_module.html
#
- name: get EC2 metadata (ec2_metadata_facts)
  action: ec2_metadata_facts
  when: myhandler_reboot or myhandler_service_act or myhandler_command_run
  listen: 'myhandler'

- name: get initial list of target groups (elb_target_info)
  delegate_to: localhost
  become: false
  elb_target_info:
    instance_id: '{{ ansible_ec2_instance_id }}'
    region: '{{ ansible_ec2_placement_region }}'
  register: target_info
  when: myhandler_reboot or myhandler_service_act or myhandler_command_run
  listen: 'myhandler'

- name: save fact for later (set_fact)
  set_fact:
    original_tgs: '{{ target_info.instance_target_groups }}'
  when: myhandler_reboot or myhandler_service_act or myhandler_command_run
  listen: 'myhandler'

- name: deregister instance from all target groups (elb_target)
  delegate_to: localhost
  become: false
  elb_target:
    target_group_arn: '{{ item.0.target_group_arn }}'
    target_port: '{{ item.1.target_port }}'
    target_az: '{{ item.1.target_az }}'
    target_id: '{{ item.1.target_id }}'
    state: absent
    target_status: 'draining'
    region: '{{ ansible_ec2_placement_region }}'
  with_subelements:
    - '{{ original_tgs }}'
    - 'targets'
  when: not ansible_check_mode and ( myhandler_reboot or myhandler_service_act or myhandler_command_run )
  listen: 'myhandler'

- name: wait for all targets to deregister (elb_target_info)
  delegate_to: localhost
  become: false
  elb_target_info:
    get_unused_target_groups: false
    instance_id: '{{ ansible_ec2_instance_id }}'
    region: '{{ ansible_ec2_placement_region }}'
  register: target_info
  until: (target_info.instance_target_groups | length) == 0
  retries: 60
  delay: 10
  when: not ansible_check_mode and ( myhandler_reboot or myhandler_service_act or myhandler_command_run )
  listen: 'myhandler'

- name: reboot instance (reboot)
  reboot:
    reboot_timeout: 600
  when: myhandler_reboot
  listen: 'myhandler'

- name: handle a service (service)
  service:
    name: '{{ myhandler_service }}'
    state: '{{ myhandler_service_state }}'
  when: myhandler_service_act
  listen: 'myhandler'

- name: run a command (command)
  command: '{{ myhandler_command }}'
  when: myhandler_command_run
  listen: 'myhandler'

- name: reregister instance into all target groups (elb_target)
  delegate_to: localhost
  become: false
  elb_target:
    region: '{{ ansible_ec2_placement_region }}'
    target_group_arn: '{{ item.0.target_group_arn }}'
    target_port: '{{ item.1.target_port }}'
    target_az: '{{ item.1.target_az }}'
    target_id: '{{ item.1.target_id }}'
    state: present
    target_status: 'initial'
  with_subelements:
    - '{{ original_tgs }}'
    - 'targets'
  when: not ansible_check_mode and ( myhandler_reboot or myhandler_service_act or myhandler_command_run )
  listen: 'myhandler'

- name: wait for registration (elb_target_info)
  delegate_to: localhost
  become: false
  elb_target_info:
    get_unused_target_groups: false
    instance_id: '{{ ansible_ec2_instance_id }}'
    region: '{{ ansible_ec2_placement_region }}'
  register: target_info
  until: (target_info.instance_target_groups |
          map(attribute='targets') |
          flatten |
          map(attribute='target_health') |
          rejectattr('state', 'equalto', 'healthy') |
          rejectattr('state', 'equalto', 'unused') |
          list |
          length) == 0
  retries: 61
  delay: 10
  when: myhandler_reboot or myhandler_service_act or myhandler_command_run
  listen: 'myhandler'
`

And here is how I use it:

roles/ipsec/meta/main.yml
`---
# file: roles/ipsec/meta/main.yml
dependencies:
  - { role: myhandler }
`

roles/ipsec/tasks/main.yml:
`---
# roles/ipsec/tasks/main.yml
- name: install ipsec default config file
  copy:
    src: 'ipsec.conf'
    dest: '/etc/ipsec.conf'
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart ipsec
    - myhandler

- name: install ipsec config files
  template:
    src: 'ipsec.conf.j2'
    dest: '/etc/ipsec.conf.d/{{ item }}.conf'
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart ipsec
    - myhandler
  with_items: '{{ list_gathered_from_other_task }}'

- name: install ipsec secrets file
  template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: 0600
    backup: yes
  diff: false
  notify:
    - restart ipsec
    - myhandler

- name: install iptables rules file
  template:
    src: 'iptables.j2'
    dest: '/etc/iptables_restore'
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload iptables
    - myhandler
`

roles/upgradepackages/meta/main.yml
`---
# file: roles/upgradepackages/meta/main.yml
dependencies:
  - { role: myhandler }
`

roles/upgradepackages/tasks/main.yml:
`---
# file: roles/upgradepackages/tasks/main.yml
- name: update installed packages (apt)
  apt:
    update_cache: yes
    cache_valid_time: 30
    autoremove: yes
    upgrade: 'safe'

- name: check if /var/run/reboot-required exists
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: notify myhandler if reboot is required
  set_fact:
    alb_handler_reboot: True
  notify: myhandler
  when: reboot_required.stat.exists == True
`

It's not totally graceful, and it can't handle much complexity yet. But it solves the problem of not duplicating handler code all over your repo. So.. there. Enjoy!

**Comment by olivov** [comment]
@packetfairy - for your purpose, would you be able to use a handler section in your playbook that called import_tasks to load in common handlers which are nested in the root of your ansible project?

for example:

upgrade_prod.yml:
```
---
# file: upgrade_prod.yml
- module_defaults:
    apt:
      force_apt_get: true
  hosts: prod_hosts
  serial: 1
  roles:
    - { role: 'upgradepackages' }
handlers:
  - import_tasks: handlers/myhandlers.yml
```
where your common handlers are in the file handlers/myhandlers.yml - from my experience, this method seems to make those handlers available to all roles called by a particular play and prevents you from needing to mint an empty role just for handling handlers. i may be missing your point though, apologies if that's the case.

**Comment by TinLe** [comment]
I have this `include_role` working.  I am using Ansible v2.10.5.

**Comment by jay13jay** [comment]
Just ran into this bug, Feb 2022. 

WHY IS THIS NOT FIXED. 

I am one of the biggest proponents of ansible, but holy f****** s*** this is a huge issue. If you follow ansible mantra and build your modules the way you're told to, you WILL run into this issue, it's a huge deviation from how you're instructed by almost everyone to create your ansible code, and what actually occurs.

Are there just issues with allowing it to work this way? and if so, can someone who looked into it maybe comment your damn findings so someone else with some free time can try to look into it without starting from scratch? I don't understand how an issue this core has been completely untouched for over 4 years and has literally had ZERO progress outside of heinously inadvisable workarounds

**Comment by bcoca** [comment]
First, I'm not sure this is a bug as roles were never intended to act as handlers and have a specific feature that provides handlers, this is border line 'feature request/enhancement' in my mind.

Second, let me clarify the nature of import_role and include_role, neither are 'modules', import_role is not even a 'task action' as it works more like a preprocessing macro that runs BEFORE any tasks in the play run. We have several explanations in the docs about the differences between these type of actions and normal actions, in 2.12 we added 'attributes' to the per plugin docs with specific keyword support info to avoid having people surf the whole doc site to know the practical consequences of these.

Adding a role at the handler stage has many implications and creates a lot of scenarios and corner cases that we are not sure how they should resolve, a short list, but not a complete one:

  - Roles can import handlers, including the possibility of overriding existing handlers in the list already scheduled for execution and/or executing (specially in include_role's case), not mentioning that the tasks you import can also do the same thing and it is not clear which should 'win' in that scenario. 'task named X or handler named X in same role?
 
  - They can set PLAY level variables (here import vs include also creates a major difference) that can affect all tasks in the play even if the role is never called to be executed (import case) or make play level variables change between hosts/execution of a handler (something that currently is not dealt with).
 
  - They can also add other plugins that override already 'in use' plugins. For example roleA adds it's own 'copy' module, doing this in the handler stage creates issues of possibly using a different 'copy' depending on where a task is (pre_tasks/roles:/tasks/post_task) and when/if the handler gets invoked. This is lessened by using namespaces (since 2.9), but not all uses of plugins are that easy to spot, `with_ansible.builtin.items` as an example.

'this is not fixed' because a) we are not sure this is something we SHOULD fix, b) even if we deem this to be something to implement, there are many behaviors to consider and consequences that you might not like/want of executing roles as handlers.

Roles are not 'self contained' and using them in a play does 'pollute' other systems. We have a few proposals to modify and/or create a new versions of roles that would not have these issues, but I have not seen any that would be backwards compatible as they would work in drastically different ways.

If  any of you want to further this case, I encourage you to bring this topic up in the 'core public IRC meetings' (after all I'm just one dev), which is where we make many of the decisions on going forward or not with a feature (or even classifying this as a feature or bug).

https://github.com/ansible/community/issues?q=is%3Aissue+is%3Aopen++label%3Ameeting_agenda+label%3Acore
https://raw.githubusercontent.com/ansible/community/main/meetings/ical/core-team.ics

**Comment by bcoca** [comment]
ANY unhanded exception is considered a bug, that does not mean that the behavior that issued the error is a bug. Tthe fix might be 'handling the exception and returning a user friendly error'.

**Comment by johnburbridge** [comment]
I realize this is a rather gargantuan feature suggestion for a future major revision, but as food for thought:

I'm a huge fan of how Gradle handles task dependencies and ordering (dependsOn, onlyIf, mustRunAfter, finalizedBy, etc): https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:adding_dependencies_to_tasks

Gradle users have the ability to pull arbitrary tasks from a collection and modify their constraints if needed, or just accept the natural order if that's fine with them. The tasks are added to a directed acyclic graph prior to execution which raises errors if someone were to shoot themselves in the proverbial foot (ie, broke the acyclic-ness).

I think having the same type of capabilities would obviate the need for handlers altogether. A task is a task, it has a lifecycle with pre/post execution hooks and has an order. It's implied that if a user is bold / clever / silly enough to muck with that, then they are taking on the responsibility for when it doesn't behave as expected.

**Comment by bluikko** [comment]
This totally breaks any attempts at "modular" code and it is quite astonishing.

Just to update current status, 2.11.9 crashes randomly / in some cases with
```console
ERROR! Unexpected Exception, this is probably a bug: 'IncludeRole' object has no attribute 'cached_name'
```
Probably due to this one.

**Comment by bviktor** [comment]
I wanna test my code with molecule, but some of my handlers are about restarting services, which involves systemd. That's all well, except for the fact that in Docker you don't have systemd, so all you get is:

```
RUNNING HANDLER [update : Restart cron service] ********************************
fatal: [ubuntu2204]: FAILED! => {"changed": false, "cmd": "/usr/bin/systemctl", "msg": "System has not been booted with systemd as init system (PID 1). Can't operate.\nFailed to connect to bus: Host is down", "rc": 1, "stderr": "System has not been booted with systemd as init system (PID 1). Can't operate.\nFailed to connect to bus: Host is down\n", "stderr_lines": ["System has not been booted with systemd as init system (PID 1). Can't operate.", "Failed to connect to bus: Host is down"], "stdout": "", "stdout_lines": []}
```

So the obvious solution is to create a wrapper role around the systemd module which first checks for the availability of systemd, or maybe the `/.dockerenv` file, but... no, according to this bug, you can't have include_role in handlers.

So now the other options is to check for `/.dockerenv` in each and every role first (copy-paste FTW), and then also add

```
when: (dockerenv.stat is defined) and (dockerenv.stat.exists)
```

to each and every systemd-related handler.

If you know any better solution, let me know...

**Comment by bviktor** [comment]
@zigarn thanks, that's good to know.

Still, that's a workaround. It doesn't actually detect the presence of systemd as it should, it just plugs host systemd into the container to make it not fail.

Not to mention the fact that for me that's still not gonna work, since I'm on WSL, which doesn't have systemd :)

(Yes, they announced systemd support in the very latest insider builds a couple of days ago, but my points about this being a workaround still stand).

In any case, my systemd example is just what it is, an example - there are many cases where handlers need a lot of copy-paste due to the lack of ability to include stuff from a shared location. Which is a coding anti-pattern, so I'm not sure why it's even up for debate to decide whether we want to eliminate redundancy and modularization or not. Of course we do!

**Comment by o0-o** [comment]
@bviktor

`systemd` presence is in gathered facts.

`when: ansible_service_mgr == 'systemd'`

Or am I missing something?

**Comment by bviktor** [comment]
Thanks, that's a somewhat better _workaround_.

The point is that this still won't eliminate the copy-paste. Yes, now I "only" need to copy-paste this clause under every task/handler that involves systemd :) In this one example. But there are other examples. But I'm still unable to implement a role *once* that deals with such exceptions, and then I can just call that role.

Yes, I could push my roles to Galaxy, or something. That's often unwanted complexity and maintenance overhead.

It still doesn't really explain why it's _preferable_ to force people to copy-paste in handlers. But to be frank, I'm not expecting a positive outcome after the interactions I've had with the Ansible community.

**Comment by bviktor** [comment]
Actually, I take it back, it wont work anyway:

```
# ansible -m setup localhost | grep service
        "ansible_service_mgr": "systemd",
```

Even though it's a Docker environment without any systemd presence :)

**Comment by o0-o** [comment]
That seems not great.

**Comment by bluikko** [comment]
> But to be frank, I'm not expecting a positive outcome after the interactions I've had with the Ansible community.

This is a very unfortunate view but even more unfortunately it is also accurate.

The most ridiculous common response to these matters is "Ansible is not coding". Sadly these issues are not widely known and newcomers get sucke(re)d into using Ansible. Only after things are moving to more advanced usage of Ansible do all these "designed" limitations come apparent and at that time it is often not feasible to start again with a more capable configuration management system.

I believe that the best thing any of us can do is to educate prospective and new users of Ansible about these limitations and steer them away before it is too late.

**Comment by o0-o** [comment]
> Sadly these issues are not widely known and newcomers get sucke(re)d into using Ansible. Only after things are moving to more advanced usage of Ansible do all these "designed" limitations come apparent and at that time it is often not feasible to start again with a more capable configuration management system.

@bluikko for someone who comes across this issue while shopping for management systems, which alternative do you believe has the capabilities that Ansible lacks here?

A concrete example may also be helpful in persuading the Ansible team to design a solution around roles in handlers.

**Comment by sivel** [comment]
We've specifically decided that this should be disallowed functionality, and have made this situation a proper error as part of https://github.com/ansible/ansible/commit/e9af6efee6eb51b4caf89bf9a53ab80b38615e5d

```
ERROR! Using 'include_role' as a handler is not supported.
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by bluikko** [comment]
> We've specifically decided that this should be disallowed functionality, and have made this situation a proper error as part of [e9af6ef](https://github.com/ansible/ansible/commit/e9af6efee6eb51b4caf89bf9a53ab80b38615e5d)

Would it be possible to hear the official reason why this decision was made?  
And even more importantly, what does the team suggest to do instead, keeping in mind this is a major problem trying to do code reuse and modularity?
