### ISSUE TITLE
Setup Facts to write to host

### ISSUE THREAD

**Issue by buggsdummy** [ansible/ansible#20704]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

setup - Gathers facts about remote hosts

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules/']
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I am able to gather facts for any host, but it'd be nice to have an out location where I can write the facts that were gathered to the host itself. There is no way to do that currently unless you have ansible installed on the host itself. This would be great for gathering troubleshooting data. 

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
You can use a cache plugin to save the facts to a database, you can use a template and dump the facts to files on disk ... many ways to keep this data.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * "You can use a cache plugin to save the facts to a database, you can use a template and dump the facts to files on disk"

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
