### ISSUE TITLE
Ansible ignores the 'transport' option in ansible.cfg

### ISSUE THREAD

**Issue by sanitar4eg** [ansible/ansible#20746]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
```
[ssh_connection]
transport = paramiko

[paramiko_connection]
host_key_checking = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible 2.2.0.0 ignores the 'transport' option in `ansible.cfg`

##### STEPS TO REPRODUCE

```
$ ansible -i hosts -m ping all -vvvv
```

##### EXPECTED RESULTS
Result should be identical with command:
```
$ ansible -i hosts -m ping all -vvvv -c paramiko
```
And output like:
```
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
<host> ESTABLISH CONNECTION FOR USER: user on PORT 22 TO host
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
<host> ESTABLISH CONNECTION FOR USER: user on PORT 22 TO host
<host> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485508569.79-195473457325950 `" && echo ansible-tmp-1485508569.79-195473457325950="` echo $HOME/.ansible/tmp/ansible-tmp-1485508569.79-195473457325950 `" ) && sleep 0'
```

##### ACTUAL RESULTS
But now Ansible tries connecting via ssh
```
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
<host> ESTABLISH SSH CONNECTION FOR USER: ****
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
<host> ESTABLISH SSH CONNECTION FOR USER: ****
<host> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=**** -o ConnectTimeout=10 -o 
etc....
```

**Comment by Shaps** [comment]
Hi @sanitar4eg. The `transport` option has to be specified in the `[defaults]` section of `ansible.cfg` it's not an SSH specific option See [docs](https://docs.ansible.com/ansible/intro_configuration.html#transport)

**Comment by gundalow** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * As @Shaps mentioned above that option belongs in `[defaults]`, see https://docs.ansible.com/ansible/intro_configuration.html#transport for more information

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
