### ISSUE TITLE
Allow $LOOKUP variables to be cached

### ISSUE THREAD

**Issue by oinopion** [ansible/ansible#2108]
Currently $LOOKUP(pipe) variables are evaluated on every use. 
I'm trying to write time based deployment and this evaluation leads to unexpected behaviour, show here:
https://gist.github.com/oinopion/4971667

**Comment by mpdehaan** [comment]
BTW, lookup pipe can also be written:

$PIPE(command goes here)

I think what I am suggesting is...

$PIPE_ONCE(command goes here)

which would effectively also allow

with_pipe_once:
- command

So that any time the command was called with the same arguments, it would
not re-evaluate.

This is easy to do.   Will take a look.

On Sun, Feb 17, 2013 at 9:25 AM, Tomasz Paczkowski <notifications@github.com

**Comment by mpdehaan** [comment]
Implemented as $PIPE_ONCE as above in latest devel.

We may wish to make this possible to cache arbitrary things later, in which case maybe everything can be ended in a _once.   Though this will solve things for now.

See the mailing list thread for a test playbook that shows this in use.

**Comment by oinopion** [comment]
Reopening: this behaviour is not followed when tasks have names. Not sure why.
Here are test playbooks with good and bad behaviour: https://gist.github.com/oinopion/4972703

**Comment by mpdehaan** [comment]
Amusing bug, and confirmed :)

I'll look into it.

On Sun, Feb 17, 2013 at 1:39 PM, Tomasz Paczkowski <notifications@github.com

**Comment by oinopion** [comment]
For a minute there I had doubts in my sanity :-)

**Comment by mpdehaan** [comment]
I suspect this is because it's not being evaluated prior to the
multiprocessing loop in this case.   Might be a little subtle.

On Sun, Feb 17, 2013 at 1:45 PM, Tomasz Paczkowski <notifications@github.com
