### ISSUE TITLE
Windows: Moving everything over to WMF 5.1

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#21184]
##### ISSUE TYPE

 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

upgrade_to_ps5.ps1

##### ANSIBLE VERSION

v2.3

##### SUMMARY

During cfgmgmtcamp 2017 in Ghent, the idea resurfaced to make it easy for Ansible users to move to Powershell 5.1 (WMF 5.1) and allow modules to make advantage of Powershell 5 capabilities (without requiring backward compatibility code).

Since all supported operating systems seem to be supported by WMF 5.1 there should not be a reason for keeping compatibility in modules to Powershell 3 and we could reasonably expect people to upgrade to Powershell 5+.

For this to happen we need an **upgrade_to_powershell51.ps1** script.

And we also need a mechanism for a module to indicate what version is the minimum version supported. Also see #20768

**Comment by jhawkesworth** [comment]
Nice idea.  It does leave behind those still using S2008 (not R2) though, I think:
https://msdn.microsoft.com/en-us/powershell/scripting/setup/windows-powershell-system-requirements

For reference adding the downloads link here https://www.microsoft.com/en-us/download/details.aspx?id=54616

I am wondering idly if the way to go with this is to create an example role for it?  Using a role would let us make use of existing modules rather than a custom powershell script.  A role might be useful for CI purposes too (since in the short term this effectively introduces extra 'platforms' i.e. versions of windows with/without WMF 5.1)

**Comment by jhawkesworth** [comment]
Just noticed that WMF 5.1 sort-of-requires .net 4.5.2
https://msdn.microsoft.com/en-us/powershell/wmf/5.1/release-notes?f=255&MSPPError=-2147217396

Probably not an issue in practice, but could be for those who aren't yet able to move up to .net 4.5.2

**Comment by dagwieers** [comment]
@jhawkesworth I am not intimately familiar with Windows Server so cannot estimate the impact of .net 4.5.2, but how about WMF 5.0 instead ? Maybe there is some middleground. Raising the bar to PS4 would already be a win ? I'll let others decide ;-) My audience was more knowledgeable than me in that area too...

**Comment by nitzmahone** [comment]
We still get people begging us to go back and support Powershell 2.0 (mostly for Server 2003 support, but not always)... I have yet to hear any compelling reason to bump the *minimum* up. Guaranteed, there would be a lot of hollering from existing users if we did so. Since Server 2012 shipped with 3.0, it's going to be supported through 2023, so I don't think it's reasonable to just pull the rug out arbitrarily.

That said, I have no issue with:
- a 5.x+ specific upgrade script
- individual (new) modules that require higher PS levels (so long as they're clearly documented/runtime-checked as such)
- new module_utils stuff that targets newer PS versions (same caveats apply)

As soon as the new exec wrapper is merged, we'll have the ability to do much more granular module_utils files for PS modules, so having newer ones that only support higher versions of PS (eg, DSC stuff) is no big deal. I just want to make sure that the underlying exec wrapper, core modules, and basic module API stuff continue to support back to PS3.

**Comment by dagwieers** [comment]
What is the impact of upgrading Powershell ? Why would someone not upgrade to PS5 ?
Isn't it supposed to be backward compatible but also supports the newer stuff ?

**Comment by nitzmahone** [comment]
Sure, but we try to maximize what we can do with the stuff that's "in the box" for the OSs we support- this flies directly counter to that. WMF5.1 *supposedly* reduces the upgrade hassle a bit, but it's still not something that's easy to do en masse...

**Comment by nitzmahone** [comment]
What specifically is it that you want to do that having support for PS3 is holding you back from (especially given the stipulations above)? There are a few minor syntactical things, but IME the underlying OS imposes many more restrictions than Powershell < 5.

**Comment by bcoca** [comment]
@dagwieers i know many people that want to upgrade, but cannot. Not all Ansible users are in full control of their environment (I keep recommending new job ...).

**Comment by dagwieers** [comment]
Well some modules implement the same functionality 2 times, even ConfigureRemotingForAnsible.ps1 did that for the self-signed certificate (until we removed the newer cmdlet and only kept the backward compatible implementation).

**Comment by dagwieers** [comment]
Someone in the audience asked me, and to me that sounded reasonable since PS5 was supported for all supported platforms. I guess maybe if you don't have Admin rights you're stuck with what you have, but then you'll probably won't be able to use WinRM either.

**Comment by jhawkesworth** [comment]
I would love to push things forward and allowing modules to be PS4 / PS5 only would be a big help for that. If you don't use all the extra functionality win_unzip could be very simple if you are only hitting PS4 boxes for example.
