### ISSUE TITLE
Failing to execute the Basic Ansible Playbook

### ISSUE THREAD

**Issue by krishnachaitanya511** [ansible/ansible#21295]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Ansible Playbook

##### ANSIBLE VERSION

```
2.2.X
```

##### SUMMARY

I tried writing a new playbook which never gets executed by the Ansible. I am new to this ansible. Here is the below lines I tried to write in Ansible-Playbook. In fact, I copied some lines from Ansible Documentation and tried it shows the same error.

##### STEPS TO REPRODUCE

```
- find:
    paths: "/tmp"
    age: "4w"
    size: "1m"
    recurse: yes
```

##### EXPECTED RESULTS

The playbook should search for the file.

##### ACTUAL RESULTS

rchimaku@RCHIMAKU-T440:/etc/ansible$ ansible-playbook -vvvv script.yml
Using /etc/ansible/ansible.cfg as config file
ERROR! 'find' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/script.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- find:
  ^ here

I always ended up with the same error. What is the reason?
![image](https://cloud.githubusercontent.com/assets/25428479/22857062/f25e1584-f0c3-11e6-9761-357ba5d5eaf9.png)

```
![image](https://cloud.githubusercontent.com/assets/25428479/22857057/db8fa156-f0c3-11e6-93cf-53f596e90639.png)

```

**Comment by dagwieers** [comment]
It seems the task was wrongly-indented.
Are you sure this task is part of the `tasks:` list ?
http://docs.ansible.com/ansible/playbooks_intro.html#tasks-list

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, @krishnachaitanya511 what you are posting is only PART of a play, the minimal unit you can execute in Ansible. A play requires at least a host and a task:
```yaml
- hosts: myhost
  tasks:
   - debug: msg='this is a play'
```

You are getting an error because you are trying to execute a single task as a play, please follow the tutorial @dagwieers posted above.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
