### ISSUE TITLE
ssh_args documentation does not accurately describe behavior

### ISSUE THREAD

**Issue by thoraxe** [ansible/ansible#21501]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ansible.cfg and ssh connection plugin

##### ANSIBLE VERSION
N/A

##### SUMMARY

Took a quick spin through the open issues and while https://github.com/ansible/ansible/issues/20714 is similar it's not the same.

The docs state:
```
ssh_args
If set, this will pass a specific set of options to Ansible rather than Ansible’s usual defaults:
```

However, this does not appear to be the case. For example, if I set:

```
ssh_args = xxx
```

I get:

```
SSH: EXEC ssh xxx -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=60 ...
```

So it is not completely replacing the defaults. If I set:

```
ssh_args = -o PreferredAuthentications=publickey
```

I get:

```
EXEC ssh -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=60
```

So it's not even correctly replacing the ones it's already using as defaults. Additionally, there is no direct setting for the authentication methods. 

I am not sure if this is explicitly a docs issue (eg: this behavior is intended) or if this is a bug (eg: this behavior is abnormal and not intended).

**Comment by jctanner** [comment]
@thoraxe please use the issue template in the future.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * ssh_args is primarily used to set the control persist args and other arguments not controlled via other config options
   * hostkey checking is controlled by a separate option http://docs.ansible.com/ansible/intro_configuration.html#host-key-checking
   * please read through http://docs.ansible.com/ansible/intro_configuration.html#openssh-specific-settings for other examples

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
