### ISSUE TITLE
Add a category to the module docs

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2194]
It would be nice if the module doc YAML has a "category" field, and we build the modules index page just listing the categories, with each module in the category on a subpage.

We might or might not include the full toc on each page.

This way the list becomes manageable and it's easier to skim to find what you want.

Categories might include "web" and "database" and "os".

**Comment by mpdehaan** [comment]
@yeukon has expressed interest in working on this in the next week or so.

@jpmens just FYI since you are the documentation generator guy and might have an interest, not expecting you to work on it :)

**Comment by jmandel** [comment]
Please do keep an all-in-one-page list that include all modules, their options, and examples.

Big help for offline browsing (and of course, might use sections in side-nav like http://twitter.github.com/bootstrap/components.html)

**Comment by yeukhon** [comment]
Yeah. That sounds like a great way to approach to re-theme. 
But let's work on the new tag and add to the current doc. Then we can look at the best presentation style. In general, it would be really nice if we had some cool shortcuts for browsing like github does :)

I will manage to find some time tomorrow reading relevant code.

**Comment by mpdehaan** [comment]
I'd suggest we could make the selector at the top something we generate
with 'ref' keywords rather than just the TOC.

If someone wants to attack re-theming it, that would be _fantastic_, but
it's not as important I think.

**Comment by yeukhon** [comment]
Okay. Will starting looking at this this this Saturday. 
By the way, awesome _ansibleworks_

**Comment by mpdehaan** [comment]
:)

**Comment by yeukhon** [comment]
Ah. Sorry Michael. Too busy with school and lab work. Finally finished new VM last week. 
Anyhow. I finally got a few hours free time tonight.

https://github.com/yeukhon/ansible/commit/123770ba07fb670e20a3d9524071ee4fab66222c

That's my progress. 
Basically we have three categories: **web**, **database**, and **os**

We will keep **_list.rst** as @jmandel requested earlier. So the old **modules.rst** will remain.
We are going to generate **_web.rst** for example for the web category in modules/  (that's where we keep **_list.rst** by the way)

There are two to-do list as stated in the commit:
1. have to write a category.rst so that it displays the three categories.
2. have to see if `ref` will work.

Let me know what you think. Thanks!

**Comment by mavimo** [comment]
I think we can define a multiple category (like tags) to module docs, eg:

```
tags:
  - database
  - user
```

that can be usefull, this can make possible have module filtering feature (will be better have a list of available tags to limit the growing of tags).

**Comment by mpdehaan** [comment]
This is now done.

The modules are stored in different directories and the main HTML listing now has subcategories.  This may wish to turn into subpages at some point in the near future to keep each page short.
