### ISSUE TITLE
service module won't start init script on systemd system

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#22171]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
RHEL7
##### STEPS TO REPRODUCE
1. isntall a init-script based service on RHEL7
2. try and start it with ansible

##### EXPECTED RESULTS
the service starts

##### ACTUAL RESULTS
Systemd error saying it can't start service.

Ansible should use the "service" command not "systemctl", as it support init style startup scripts while still being compatible with new systemd scripts.

**Comment by dflock** [comment]
This bug makes it impossible to use the `service` module to stop or restart the `auditd` service on RHEL systems.

The reason is a combination of two things:

1. If Ansible's service module detects that it's being run on a linux system which uses systemd for init, then it will use `systemctl` for everything, regardless.
2. The `auditd.service` refuses manual stops via systemd, using this setting in its unit file: `RefuseManualStop=yes`, so you need to use `service auditd restart` to restart it.

There's a discussion on the Red Hat Bugzilla that talks about this: https://bugzilla.redhat.com/show_bug.cgi?id=1026648

> "service auditd restart" works only because the audit package ships a script to tell `service` about a special way to do it: using the legacy scripts here: `/usr/libexec/initscripts/legacy-actions/auditd/restart`.

> The reason for this weird handling of restart requests is that auditd is treated specially by the kernel: the credentials of a process that sends a killing signal to auditd are saved to the audit log. The audit developers do not want to see the credentials of PID 1 logged there. They want to see the loginuid of the user who initiated the action.

On RHEL, the `service` command is a wrapper script, that will use a legacy script to control a package if one exists in `/usr/libexec/initscripts/legacy-actions/<service>/<action>` - and fallback to using `systemctl` if not.

So, Ansible should either be using the `service` command on RHEL7.? systems, not using `systemctl` directly - or doing the "check for legacy scripts/falling back to systemctl" thing itself.

This used to work, in Ansible 1.9.1, but I think this changed, maybe with this item in the 2.2 changelog:

> The service module has been changed to use system specific modules if they exist and fall back to the old service module if they cannot be found or detected.

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

**Comment by dflock** [comment]
FYI: This is the contents of `/usr/libexec/initscripts/legacy-actions/auditd/restart` from a RHEL7.3 system:

```console
$ sudo cat /usr/libexec/initscripts/legacy-actions/auditd/restart
```

```bash
#!/bin/sh
# Helper script to provide legacy auditd service options not
# directly supported by systemd.

test -f /etc/audit/auditd.conf  || exit 6

/usr/libexec/initscripts/legacy-actions/auditd/stop
sleep 1
echo "Redirecting start to /bin/systemctl start auditd.service"
/bin/systemctl start auditd.service
RETVAL="$?"

exit $RETVAL
```

and this is the contents of `/usr/libexec/initscripts/legacy-actions/auditd/stop`:

```console
$ sudo cat /usr/libexec/initscripts/legacy-actions/auditd/stop
```
```bash
#!/bin/sh
# Helper script to provide legacy auditd service options not 
# directly supported by systemd

# Check that we are root ... so non-root users stop here
test $EUID = 0  ||  exit 4

PATH=/sbin:/bin:/usr/bin:/usr/sbin
prog="auditd"
source /etc/init.d/functions

echo -n $"Stopping logging: "
killproc $prog -TERM
RETVAL=$?
echo
exit $RETVAL
```

**Comment by dflock** [comment]
And this is the contents of the `service` command script from the same RHEL7.3 system:

```bash
#!/bin/sh

. /etc/init.d/functions

VERSION="$(basename $0) ver. 1.1"
USAGE="Usage: $(basename $0) < option > | --status-all | \
[ service_name [ command | --full-restart ] ]"
SERVICEDIR="/etc/init.d"
ACTIONDIR="/usr/libexec/initscripts/legacy-actions"
SERVICE=
ACTION=
OPTIONS=

if [ $# -eq 0 ]; then
   echo "${USAGE}" >&2
   exit 1
fi

cd /
while [ $# -gt 0 ]; do
  case "${1}" in
    --help | -h | --h* )
       echo "${USAGE}" >&2
       exit 0
       ;;
    --version | -V )
       echo "${VERSION}" >&2
       exit 0
       ;;
    --ignore-dependencies)
       export SYSTEMCTL_IGNORE_DEPENDENCIES=1
       shift
       ;;
    --skip-redirect)
       export SYSTEMCTL_SKIP_REDIRECT=1
       shift
       ;;
    *)
       if [ -z "${SERVICE}" -a $# -eq 1 -a "${1}" = "--status-all" ]; then
          cd ${SERVICEDIR}
          for SERVICE in * ; do
            case "${SERVICE}" in
              functions | halt | killall | single| linuxconf| kudzu)
                  ;;
              *)
                if ! is_ignored_file "${SERVICE}" \
                    && [ -x "${SERVICEDIR}/${SERVICE}" ]; then
                  env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" status
                fi
                ;;
            esac
          done
          exit 0
       elif [ $# -eq 2 -a "${2}" = "--full-restart" ]; then
       SERVICE="${1}"
       if [ -x "${SERVICEDIR}/${SERVICE}" ]; then
         env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" stop
         env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" start
         exit $?
       fi
    elif [ -z "${SERVICE}" ]; then
      SERVICE="${1}"
    elif [ -z "${ACTION}" ]; then
      ACTION="${1}"
    else
      OPTIONS="${OPTIONS} ${1}"
    fi
    shift
    ;;
esac
done

if [ -f "${SERVICEDIR}/${SERVICE}" ]; then
  # LSB daemons that dies abnormally in systemd looks alive in systemd's eyes due to RemainAfterExit=yes
  # lets reap them before next start
  if [ "${ACTION}" = "start" ] && \
  systemctl show -p ActiveState ${SERVICE}.service | grep -q '=active$' && \
  systemctl show -p SubState ${SERVICE}.service | grep -q '=exited$' ; then
      /bin/systemctl stop ${SERVICE}.service
  fi
  env -i PATH="$PATH" TERM="$TERM" SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} "${SERVICEDIR}/${SERVICE}" ${ACTION} ${OPTIONS}
elif [ -x "${ACTIONDIR}/${SERVICE}/${ACTION}" -a -n "${ACTION}" ]; then
  env -i PATH="$PATH" TERM="$TERM" SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} "${ACTIONDIR}/${SERVICE}/${ACTION}" ${OPTIONS}
elif `echo $ACTION | egrep -qw "start|stop|restart|try-restart|reload|force-reload|status|condrestart"` ; then
   echo $"Redirecting to /bin/systemctl ${ACTION} ${OPTIONS} ${SERVICE}.service" >&2
   SERVICE_MANGLED=$(/usr/bin/systemd-escape --mangle ${SERVICE})
   exec /bin/systemctl ${ACTION} ${OPTIONS} ${SERVICE_MANGLED}
else
   echo $"The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl." >&2
   exit 2
fi
```

**Comment by abadger** [comment]
After reading through the red hat bugzilla for this, it looks like this is a problem in the OS packaging of auditd.  The bugzilla reports that the auditd unit file is setting RefuseManualStop=yes to explicitly tell systemd not to stop or restart the auditd service.  The systemd module should obey those settings.  Since systemd is the init system on the remote host, the service module should also respect that decision for this box.

We can offer a workaround (similar to the one that is offered in the bugzilla report): explicitly use the service script to restart auditd instead of systemd:
```
- command: /sbin/service auditd restart
```

Closing this bug as it's really something that would need to be addressed in OS packaging (and we can offer a workaround here).

**Comment by shezaan** [comment]
This issue is a generic issue and should not be just related to auditd. I am having the same problem even with the sumologic collector which won't start since it is a SysV init script.

```
TASK [sumo-collector : Enable collector service] ******************************************************************************************************
task path: /Users/shezaan/code/ansible-role-sumo-collector/tasks/main.yml:86
 [WARNING]: The service (collector) is actually an init script but the system is managed by systemd

fatal: [psvlxmdmint01]: FAILED! => {"changed": false, "msg": "Unable to start service collector: Failed to start collector.service: Unit collector.service failed to load: No such file or directory.\n"}
fatal: [psvlxmdmint02]: FAILED! => {"changed": false, "msg": "Unable to start service collector: Failed to start collector.service: Unit collector.service failed to load: No such file or directory.\n"}
```

**Comment by lxndrv** [comment]
Have same issue mysql service on ubuntu 16.04 with ansible 2.4.2.0
Using 'shell: service mysql start' as workaround

**Comment by timblaktu** [comment]
Same issue with distcc 3.1-6.2+b1 on Debian Stretch, with ansible 2.4.3.0.

**Comment by awr** [comment]
Having the same issue with dse opscenter on ansible 2.4.3 running against CentOS 7.4

**Comment by surdu** [comment]
Having the same issue (I think) with supervisor:

```
TASK [supervisor : Enable Supervisor at boot] **********************************************************************************
 [WARNING]: The service (supervisord) is actually an init script but the system is managed by systemd

fatal: [104.248.47.96]: FAILED! => {"changed": false, "msg": "Unable to enable service supervisord: supervisord.service is not a
 native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable supervisord\nupdate-r
c.d: error: supervisord Default-Start contains no runlevels, aborting.\n"}
```

```
$ ansible --version
ansible 2.6.3
```

**Comment by vchokshi** [comment]
+1 for cassandra service on RHEL.

src: 
- ansible 2.6.2 configured module search path = [u'/Users/vchokshi/.ansible/plugins/modules',u'/usr/share/ansible/plugins/modules']
- ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
- executable location = /usr/local/bin/ansible
- python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

dest:
- Linux cas-1 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abadger** [comment]
I see that people have been adding onto this closed bug.  Couple things:

We don't watch closed bugs so no one has seen your issues.  You should be opening up new bug reports instead of adding to a closed one of you want someone to read them and try to diagnose.

In the auditd case, it wasn't a problem with the service module but with the auditd package on that platform.  Other services may be problems with the init scripts or may be problems with the ansible module's code but we won't know without more information specific to each case.  Opening new bug reports for different services which fail in some way and then providing complete information about them is what will help in this case (for instance, does the service do the right thing when using the underlying command for your platform (systemctl in the case of systemd using platforms).  I'm going to lock this issue as there doesn't appear to be anything further on the auditd case to encourage future reporters to open new issues to look at.
