### ISSUE TITLE
Bug: host vars not picking up for some reason

### ISSUE THREAD

**Issue by javadan** [ansible/ansible#22683]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Host Vars

##### ANSIBLE VERSION
ansible 2.2.1.0

##### OS / ENVIRONMENT
Centos 7

##### SUMMARY
In my playbook, I'm using 
`hosts: dockers_all_not_2`

In the hosts file, I added
```
[dockers_all_not_2]
{hosts}
[dockers_all_not_2:vars]
{vars}
[dockers_test]
{other hosts}
[dockers_test:vars]
**{other vars}**
[dockers_prod]
{other hosts}
[dockers_prod:vars]
{other vars}
[test]
{other hosts}
[test:vars]
**{other vars}**
```
at the top of the file.

It used the correct {hosts} but the {vars} for this host group was not used, when I ran my playbook.  Instead a different vars section, matching either my `dockers_test` section, or my `test` section was used instead.   (They have the same vars, just different machines)

Sorry I can't test this further, or paste my code at the moment.  I'm guessing it is probably a regex sort of bug, when looking for the vars.  Hope that's sufficient for now.

**Comment by jctanner** [comment]
@javadan Please indicate what the expected versus actual results are.

needs_info

**Comment by javadan** [comment]
I left it out because I thought that was clear from the summary. Seems a bit tautological to repeat it.


Expected results

I expected the vars used by ansible to be those in the dockers_all_not_2:vars , since the host selected in the play book was dockers_all_not_2

Actual results

Vars from another host were used by the playbook. In this case, either dockers_test, or test was the source.

It sounds like a regex or string comparison type of bug to me, in the code that works out what vars to use

**Comment by dagwieers** [comment]
@javadan A minimal reproducer is always best. So that someone (anyone) can simply take your playbook/examples and test it with the exact content as you were testing. From time to time the devil is in the details (it might be a typo, it might be a misconstructed inventory) and those details get lost if you describe your setup rather than copy&paste a (non)working example.

(Also when creating that minimal reproducer, you may actually stumble on the culprit and this issue ticket becomes moot)

**Comment by sivel** [comment]
I'm going to close this issue out.  Due to lack of response or a valid reproducer we have not been able to make progress.

If you are still having problems with recent versions of Ansible (2.5+), feel free to open a new issue with a full reproducer that we are capable of executing without modification.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
