### ISSUE TITLE
Variable within Variable not getting templated

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#22859]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME
templating+jinja

##### ANSIBLE VERSION
ansible 2.1.0.0

##### SUMMARY
Need to save a variable in a file (ex: /tmp/test.txt) having a sub-variable. Variable expansion is not happening.

"{{vars['A'+num+'TXN'] }}" 

temp_file: /tmp/test.txt

/roles/vars/main.yml

A1TXN: 12345
A2TXN: 54321

/roles/tasks/main.yml

- name: Getting values from text file
   with_items: cat /tmp/data.txt
   register: number

- name: Calling variable within variable
   lineinfile: dest={{ temp_file }} line="{{vars['A'+num+'TXN'] }}" state=present 
   with_items: number 
   loop_control:
       loop_var: num

##### EXPECTED RESULTS

/tmp/test.txt  file should contain:

 12345
 54321

##### ACTUAL RESULTS
/tmp/test.txt File contents came:

A1TXN
A2TXN

**Comment by abadger** [comment]
Are you able to test this with a newer version of ansible?  (2.2 from pypi or the 2.3 release candidate from http://releases.ansible.com/ansible/ )?  2.1.0 is rather old and unlikely to see fixes for something like this.  Many things have changed in 2.2.x and the pending 2.3.x so it would be good to see if it has been fixed already before starting to diagnose this.

Assigning jimi-c to look into it once you've had a chance to test with a newer version.

needs_info

**Comment by regexcracker** [comment]
Thanks @abadger . I'll update the ansible version and test the scenario. Meanwhile I found an alternative approach. Although, the approach is not good but it works. 

Looking for good solution

Approach Used:
___________________________________________________________________________________________
**Earlier:**
name: Calling variable within variable
lineinfile: dest={{ temp_file }} line="{{vars['A'+num+'TXN'] }}" state=present
with_items: number
loop_control:
loop_var: num

**Alternative:**
  - name: Calling variable within variable
    include: another.yml print_outer_loop={{print_loop}}
    with_lines: cat /tmp/data.txt
    loop_control:
         loop_var: print_loop
another.yml:

 - set_fact: printline="{{ print_outer_loop }}"
 - name: Getting Number from file line by line
   shell: "echo {{ printline }}  | cut -d ',' -f 2"
   register: num

 - name: final variables cought
    shell: echo "{{vars['A'+num+'TXN'] }}"

**Comment by jimi-c** [comment]
@regexcracker yes, the proper way to do this is via set_fact. We don't allow the composition of variables inline as you did in your original example. As such, we'll close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
