### ISSUE TITLE
include_role does not work ad-hoc, ie "ansible -m include_role ..."

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#22983]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```
##### SUMMARY

`include_role` does not work like other modules, that is, callable as ad-hoc command.  other modules appear to work fine with identical syntax.  this is preventing use of `include_role` to run roles dynamically from the command line with ansible's ad-hoc mode invocation.

##### STEPS TO REPRODUCE

works:
```
$ ansible localhost -c local -i localhost, -m command -a true
localhost | SUCCESS | rc=0 >>
```

fails:
```
$ ansible localhost -c local -i localhost, -m include_role -a name=myrole >/dev/null
ERROR! 'include_role' is not a valid action for ad-hoc commands
```

##### EXPECTED RESULTS

include_role should behave like other modules

##### ACTUAL RESULTS

include_role does not allow operation from ad-hoc mode

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

There are several task actions that don't make sense and cannot work with adhoc, this is due to design, not a bug.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
