### ISSUE TITLE
Include additional Fortinet (fortios_*) networking modules

### ISSUE THREAD

**Issue by abenokraitis** [ansible/ansible#23247]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
fortios_*

##### SUMMARY
This tracker issue is to track the requests for the need for Fortinet Ansible modules. 

If you have any requirements for extra modules please feel free to add them to this list.

We are looking to the community to assist with building these modules.

**Comment by ryansb** [comment]
Can you please add an assignee if there's someone responsible for this?

**Comment by gundalow** [comment]
needs_contributor We are looking to the community to assist with this. 

We already have a few `fortios` modules http://docs.ansible.com/ansible/list_of_network_modules.html#fortios

**Comment by gundalow** [comment]
@jmcgill298 @bjolivot As two users of the existing `fortios_*` modules you may be interested in subscribing to this issues.

If you have an existing ideas of what else needs adding feel free to use this issue to track it.

**Comment by bjolivot** [comment]
I have some modules in dev, for the moment address, address_group,  services, times, interfaces...etc

**Comment by ikelos** [comment]
If you're after additional ideas for improving the fortios modules, the following would be useful.  At the moment, the fortios module in 2.3 requires a filename for a pre-existing static file.  This means that in order to make use of ansible's templating capabilities, a temporary file must be created on the local system.  It would be very handy to support templated files.

I used a custom module converted from the cisco modules to manage a fortios device, and had to ensure that the firewall policies are in the correct order (so that certain denies appear before certain allow statements).  In order to achieve that, I sent individual commands (for instance to enable and disable certain firewall policies, and delete lists of firewall policies), which would be a very useful feature as well.

**Comment by bjolivot** [comment]
@ikelos I could use more detailled infos or a sample.
I have template & var file based fortios module but don't really found use case.

**Comment by ikelos** [comment]
@bjolivot, so as I mentioned, I have a custom module (unfortunately named the same as the one that's now in 2.3) that was basically copied from the cisco module, but with pyFG functionality used instead of raw SSH.  I use it to build up a dynamic number of VLANs based on our office configuration, add specific sets of firewall addresses and address groups (custom to each device) and define the interface IPs, all based on a single set of ansible yaml.  I appreciate your having written the fortios_config ansible module, since I'd much rather use a module that comes with ansible than my own custom code.  However, if I have to use it to interact with fortios devices using this module, then I'll be endlessly having to construct each file for each device by redirecting a template task to localhost, which is clearly a workaround and one that seems unnecessary.  Given that a flat file can be pushed through as a template, but a template cannot be pushed through as a flat file, there's no loss of functionality in allowing templating, only loss of functionality in not having templating as a possibility.  I was honestly surprised that the `src` parameter didn't accept a template file when I first tried it and had to check the source code to believe that it didn't operate in the same way that `ios_config`'s `src` parameter does.

I'd also like individual commands in order to make use of ansible variables derived from the layout of our network (all defined in the yaml var files) to be able to make specific changes (such as setting passwords that are stored in an encrypted database that ansible can read but which we don't want recorded in flat files, and disabling certain firewall policies at will).  I don't mind how that's achieved, but commands seemed like the simplest way.  Overwriting the firewall policies seems like the trickiest part, since if the new rules are shorter than the old rules, some might get left behind (which would be a security concern) and if the policy changes aren't atomic, it would be quite possible to overwrite the rule that allows SSH to the device before being writing in the new rule that allows it again, and so lock out a device (potentially in a remote location).

My current solution has been to leave a disabled rule at the top of the policy list to allow management access.  I then issue a command (using my custom ansible module) to enable it, then issue a command to determine all the policy numbers currently in the config, then issue a command to delete all those policies in one go (to save the SSH round trip) and then use an ansible template to repopulate the policies, after which I issue one last command to disable the first rule again.  With the new module, I don't have that level of flexibility.  The fortios_ipv4_policy is of limited use if the ordering of the rules can't be specified (because if you can't guarantee that certain denies will occur before certain accepts, then you can't trust the security of the end policy), and so far the `id` parameter refers to the policy id, not the rule order.

I'm afraid I can't give you sample files detailing the layout of our network, but it isn't clear that they'd help anyway.  I honestly believe that templating will vastly improve the usefulness of this module versus its current capabilities.  I also suspect it only requires the addition of a file in action_plugins to enable the templating of a parameter and the line of code that currently opens the file at `src` but could instead pass `src` as a post-processed template.  I'd be happy to submit a pull request changing the `src` parameter from a static file to a template if that would help?  It would be a break in the API, but the module was marked as a preview module so it might be acceptable to make a change like this...

**Comment by bjolivot** [comment]
@ikelos feel free to send PR for improvements

**Comment by ikelos** [comment]
@bjolivot It turns out that since pyFG batches its changes, I no longer need to make individual modifications to the configuration to ensure the firewall stays up during modifications, so this pull request should be enough to sort 99% of the difficulties I was facing with the version in 2.3.  5:)

**Comment by aoprea1982** [comment]
@ikelos please share your custom fortios module to manage fortigates.

Don't want to reinvent the wheel.

**Comment by ikelos** [comment]
@aoprea1982, the custom modules were badly hacked together versions of the existing Cisco module.  I will not be sharing them.  Instead, use the fortios modules that exist in ansible-2.3 with or without the patches I have contributed in pull request #24026, that allow you to use templating.  They're far better, and I've converted all my code over to using these, vastly reducing the number of lines, and execution time,  required to achieve the same goal.

**Comment by aoprea1982** [comment]
@ikelos 

Used ansible 2.3 modules with template but got the following error :

/* fatal: [192.168.10.100]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to commit, check your args, the error was [(u'-8', u'set ip {{j.ip}} 255.255.255.0')]"} */

Investigated it but still no answer.


/* main.yml*/

- name: fortinet config
  fortios_config:
    host: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    src: templates/FORTI.j2

/* vars/main.yml */
ports: port1: { ip: 12.12.12.9 }

/* templates/FORTI.j2 */
{% for i,j in ports %} config system interface edit {{i}} set ip {{j.ip}} 255.255.255.0 end {% endfor %}

**Comment by ikelos** [comment]
@aoprea1982 I think that's because the 2.3 modules don't (yet) support templating.  If you want templating, you'll need to apply the patches from pull request #24026.

**Comment by aoprea1982** [comment]
@ikelos


Thanks for the reply.
I got not error after  applying(changing code inside fortios_config then pycompile it) #24026
 But
ansible it's not applying the template variables to the fortigate device; maybe something on my side .
If possible could you please share your ansible structure, config (vars, template,tasks)?

Thank you.

**Comment by ikelos** [comment]
@aoprea1982, there are two files in the patch, did you copy the second file to  lib/ansible/plugins/action/fortios_config.py, as well as editing lib/ansible/modules/network/fortios/fortios_config.py.  Also, this is a feature request, not a support forum.  If you have difficulty making use of the supplied pull request, please seek help in the [ansible project forum](https://groups.google.com/forum/#!forum/ansible-project) or another appropriate location.

**Comment by aoprea1982** [comment]
@ikelos 
Didn't copy the second file. 
You're right , it's not a support forum.Got a bit lazy. :p

Thanks for the info. Very useful.

**Comment by willwagner602** [comment]
@bjolivot I'm interested in making contributions to those modules, although my manager is most interested in using the FortiOS REST API rather than CLI via pyFG. Would love to chat with you if you're still working/interested in this over the next couple months.

**Comment by bjolivot** [comment]
@willwagner602  I don't have access to REST API doc so at this moment I can only use pyFG

**Comment by willwagner602** [comment]
Thanks @bjolivot, I'll power through on my own then.

**Comment by calfonso** [comment]
Since this issue has turned into a conversation and nothing really actionable, I'm going to close this issue. Any issues with the code should be opened as GH issues with the bug template filled out or feature ideas should be opened as a GH issue and the feature details filled out in the template.
