### ISSUE TITLE
Document Python3 incompatibility

### ISSUE THREAD

**Issue by chrono** [ansible/ansible#2344]
I tried to run my playbook against some hosts that only have python3 and was greeted with interesting syntax errors.

Please document that ansible requires python < 3 on the managed hosts to be available.

**Comment by mpdehaan** [comment]
python 3 is essentially not the same language as python 2, but yes, we'll do something here.

What OS are you using, BTW?

**Comment by chrono** [comment]
The affected boxes all run gentoo. I'm not the primary sysadmin but I think there is no specific reason for us to run python3, it appears to be the default choice by the distribution. A quick `grep -r python /etc` doesn't show any specific flags that would suggest it was a manual choice.

It appears it was just pulled in by portage

```
dev-lang/python-3.2.3 pulled in by:
  app-admin/python-updater-0.10
  sys-apps/portage-2.1.10.62
```

python updater seems to be a circular dependency, itself being required by python.

```
app-admin/python-updater-0.10 pulled in by:
  dev-lang/python-3.2.3
```

**Comment by mpdehaan** [comment]
Ok, so you just need to set ansible_python_interpreter as an inventory or
group_vars/all variable to your python2.6 (or other) path, and you'll be
fine.

Search for ansible_python_interpreter in the docs/mailling list.

**Comment by bcoca** [comment]
Hi,

gentoo python version can be chosen (normally a 2. and a 3. installed
because of package dependencies). Check with the eselect tool, you might
still be able to point to the 2. version by using
ansible_python_interpreter variable.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
