### ISSUE TITLE
different behavior when setting sticky bit when using ansible / ansible-playbook

### ISSUE THREAD

**Issue by stromvirvel** [ansible/ansible#23491]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/rewe/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False
remote_user = root
roles_path = ~/.ansible/roles/
vault_password_file = ~/.ansible/vault_password_file
```

##### OS / ENVIRONMENT
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

##### SUMMARY
If I set a directory to mode 1777 (rwxrwxrwt / with sticky bit), using file module, there is different behavior, depending on using a playbook or an ad-hoc command.

##### STEPS TO REPRODUCE (PLAYBOOK)
Give 777 permissions and set sticky bit, using a playbook
```
$ ansible-playbook -i production build-agent.yml

PLAY [build-agent] *************************************************************

TASK [setup] *******************************************************************
ok: [mima-bambooagent-06]

TASK [fix permissions for /tmp/] ***********************************************
changed: [mima-bambooagent-06]

PLAY RECAP *********************************************************************
mima-bambooagent-06        : ok=2    changed=1    unreachable=0    failed=0   
```

##### ACTUAL RESULTS (PLAYBOOK)
```
[root@mima-bambooagent-06 bambooagent]# ls -l / | grep tmp
d-wxrwS--t   15 root root 4096 11. Apr 15:03 tmp
```

##### STEPS TO REPRODUCE (AD-HOC)
Give 777 permissions and set sticky bit, using the ad-hoc command:
```
$ ansible -i production build-agent -m file -a "name=/tmp/ mode=1777"
mima-bambooagent-06 | SUCCESS => {
    "changed": true, 
    "gid": 0, 
    "group": "root", 
    "mode": "01777", 
    "owner": "root", 
    "path": "/tmp/", 
    "size": 4096, 
    "state": "directory", 
    "uid": 0
}
```

##### ACTUAL RESULTS (AD-HOC)
```
[root@mima-bambooagent-06 bambooagent]# ls -l / | grep tmp
drwxrwxrwt   15 root root 4096 11. Apr 15:04 tmp
```

##### playbook "build-agent.yml":
```yaml
---
- hosts: build-agent
  roles:
#    - common
#    - bamboo-agent
  tasks:
  - name: fix permissions for /tmp/
    file:
      name: /tmp/
      mode: 1777
```

##### EXPECTED RESULTS
```
drwxrwsrwt   15 root root 4096 11. Apr 15:03 tmp
```

**Comment by snowsky** [comment]
Reproduced.

**Comment by snowsky** [comment]
ansible-playbook used "mode": "03361" for the directory.

**Comment by snowsky** [comment]
I may be a bug for set_mode_if_different. Will take another look.

**Comment by sivel** [comment]
The problem here is that you have supplied an integer/decimal mode.  Octal modes require prefixing the value with a 0.

I believe the confusion is coming from the way that python and yaml (pyyaml) work with each other in regards to octal values.

When you specify `mode: 2750` you are indicating that you are giving it a decimal value, and not octal.  When the value is a string, the logic in python interprets it as octal.  Such a representation would look like `mode: "2750"`.  The octal equivalent of `2750` (decimal) is `05276`, which is effectively what you speciefied.  Python 2.x denotes octal values using a preceding `0`.

Your options would be something such as:

As a string:

```
mode: "2750"
```

Using proper python 2.x octal notation:

```
mode: 02750
```

Using a decimal representation of octal mode 02750:

```
mode: 1512
```

The reason that `mode=2750` produces the same results as `mode: "2750"` is due to the fact sure that `key=value` ansible parses the values, and not assuming what the user wanted, effectively casts all values to strings.


If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by snowsky** [comment]
Actually it is not caused by octal/decimal number, it is caused by this code [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1072-L1082).
I traced the codes for both ansible and ansible-playbook commands, and it is found the difference is that the mode is integer for ansible-playbook command but it is a string for ansible command.

Then go back to the code, you will find that the logic causing this issue.

**Comment by sivel** [comment]
The difference is caused by how the value is being passed.  As noted above in my explanation, you get a string value when using `key=value` format, when using YAML, it gets treated as an integer.  If you quoted the `1777`, such as `mode: "1777"` then it too would be treated as a string.

**Comment by snowsky** [comment]
I see what you mean now.

**Comment by snowsky** [comment]
Oh, it may be a feature request or documentation to make it clean. Because I will also make the same mistake to use decimal in mode.

**Comment by stromvirvel** [comment]
Thank you guys, works with a quoted value in the playbook. @snowsky that would be nice.

**Comment by ksk641** [comment]
Hi i'm new to ansible, can anyone help to write a yml code to apply stickybit on multiple servers , multiple directories.

**Comment by mprinc** [comment]
In my opinion, the safest way is to use acronym form:

```json
"mode": "ug=rwx,o=rx,g+s"
`
so you do not need to worry if all intermediaries will recognize leading 0 as indication of an octal number
