### ISSUE TITLE
 Inventory file execution issue 

### ISSUE THREAD

**Issue by MrBiT01** [ansible/ansible#23512]
ISSUE TYPE: Bug report
COMPONENT NAME: ansible, roles_path

ANSIBLE VERSION:
ansible 2.2.2.0
config file = /etc/ansible/ansible.cfg

CONFIGURATION:
defined values under [default]
hosts_path = /etc/ansible/hosts

OS:  Darwin Kernel Version 16.4.0 (root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64)

ISSUE SUMMARY: Ansible executes commands only on last host from inventory file,  witch contains identical IP and different PORT.

STEPS TO REPRODUCE:
1)My hosts file contains:
```
[servers]
#Every port forvarded to docker instance
#Inst1
188.166.42.186 ansible_user=root ansible_port=443
#Inst2
188.166.42.186 ansible_user=root ansible_port=32776
#Inst3
188.166.42.186 ansible_user=root ansible_port=32775
```

2)execute ansible "servers -m ping -c3 8.8.8.8"

RESULT:
Command executed only on last instance.
Reply from last instance displayed only.

EXPECTED:
Command executed only on every instance.
Replies from every instance are displayed.

**Comment by sivel** [comment]
This is the expected behavior.

In an "ini" formatted inventory file, the first column for a host is considered the "inventory_hostname".

The inventory_hostname is a unique key, and since you have listed `188.166.42.186` 3 times, the last one wins.

Instead what you want to do is use `ansible_host` and create aliases, like:

```
[servers]
#Every port forvarded to docker instance
inst1 ansible_host=188.166.42.186 ansible_user=root ansible_port=443
inst2 ansible_host=188.166.42.186 ansible_user=root ansible_port=32776
inst3 ansible_host=188.166.42.186 ansible_user=root ansible_port=32775
``` 

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
