### ISSUE TITLE
file module converts supplied 4 digit mode to octal

### ISSUE THREAD

**Issue by jake2184** [ansible/ansible#23521]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- 'file' module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/jr/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Run from and managing:
Linux CentOS EL7

##### SUMMARY
Noticed when changing a task using the 'file' module from legacy syntax to full YAML syntax, as per the Ansible best practices. The usersv_instance var is a list of strings.

It seems that the supplied value for mode is treated as decimal and is converted into octal - despite the supplied value being valid.

A workaround is placing a 0 in front of the mode, so '02775'.

##### STEPS TO REPRODUCE
The below task has a bug:
    - name: usersv sub-directories
      file:
        path: "/srv/{{ item[0] }}/{{ item[1] }}"
        state: directory
        owner: root
        group: "{{ item[1] }}"
        mode: 2775
      with_nested: 
        - [ 'usersv', 'useretc', 'userlogs', 'userdata' ]
        - "{{ usersv_instance | default ([])}}"

The below task works successfully as expected:
    - name: userlogs sub-directories
     file: path="/srv/userlogs/{{ item }}" state=directory owner=root group="{{ item }}" mode=2775 
     with_items: "{{ usersv_instance }}"
     when: "usersv_instance is defined"

##### EXPECTED RESULTS
Mode of the file should be (un)changed to 2775

##### ACTUAL RESULTS
Mode of the file was changed to 5327

```
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": "02775", 
+    "mode": "05327", 
     "path": "/srv/usersv/ceqclusters"
 }
```

**Comment by gtirloni** [comment]
#5409 #9196 #11385 #13115 #18952 #23491

**Comment by sivel** [comment]
I believe the confusion is coming from the way that python and yaml (pyyaml) work with each other in regards to octal values.

When you specify `mode: 2750` you are indicating that you are giving it a decimal value, and not octal.  When the value is a string, the logic in python interprets it as octal.  Such a representation would look like `mode: "2750"`.  The octal equivalent of `2750` (decimal) is `05276`, which is effectively what you speciefied.  Python 2.x denotes octal values using a preceding `0`.

Your options would be something such as:

As a string:

```
mode: "2750"
```

Using proper python 2.x octal notation:

```
mode: 02750
```

Using a decimal representation of octal mode 02750:

```
mode: 1512
```

The reason that `mode=2750` produces the same results as `mode: "2750"` is due to the fact sure that `key=value` ansible parses the values, and not assuming what the user wanted, effectively casts all values to strings.


If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jake2184** [comment]
Thanks for the feedback - I also noticed you linked some very similar tickets, my apologies. I did search the issues beforehand but was unable to find these.

Is it perhaps worth updating the docs to be clear that you still need a 0 prefix even for a 4 digit octal mode?

**Comment by jtyr** [comment]
The rule here is that you either start the mode with `0` OR you must make sure value is read like string which means to quote it. The following sets mode to `-rw-------` resp. `-rwsrwxrwx`:

```
# -rw-------
mode: 0600
```

```
# -rw-------
mode: "600"
```

```
# -rwsrwxrwx
mode: 04777
```

```
# -rwsrwxrwx
mode: "4777"
```

**Comment by 264nm** [comment]
Just wanted to add a comment here re: behaviour I noticed rather than submitting a report that will be closed with 'just quote it'

Came across this situation using the template module, but when passing a var to be templated:

## Defined var
`rsyslog_file_create_mode: 0755`

## Template file
```
    missingok
    sharedscripts
    create {{ rsyslog_file_create_mode }}
    dateext
```

## Templated Output
```
    missingok
    sharedscripts
    create 493
    dateext
```
