### ISSUE TITLE
YAML tag for python object string is broken in ansible 2.1.5, 2.2.2, 2.3

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#23560]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

ansible 2.2.2.0
  config file = /vagrant/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/modules']

ansible 2.1.5.0
  config file = /vagrant/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/modules']
```

##### CONFIGURATION

[defaults]
retry_files_enabled = False
roles_path = ./roles
host_key_checking = False
allow_world_readable_tmpfiles = True

\# callback_plugins configuration is required for the ARA callback
callback_plugins = ~/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/callbacks

\# action_plugins and library configuration is required for the ara_record and ara_read modules
action_plugins = ~/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/actions
library = ~/.ansible_venv/local/lib/python2.7/site-packages/ara/plugins/modules

##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

##### SUMMARY

YAML tag for python object string is broken in ansible versions past 2.1.4. 
##### STEPS TO REPRODUCE

1. Install ansible 2.1.4 via pip
2. Create var.yml file as below
```yaml
%TAG !string! tag:yaml.org,2002:python/object/apply:string.
---
var1: &var1 "hello"
var2: &var2 "world"
var3: !string!join [[*var1, *var2], ' ']
```
3. Create playbook.yml file as below
```yaml
- hosts: all
  tasks:
    - debug: var=var3
```
4. Run ansible-playbook:
```
ansible-playbook -c local -i localhost, playbook.yml -e @var.yml
```
5. Install ansible 2.1.5, 2.2.2, 2.3. Run ansible-playbook command again. It should fail.

##### EXPECTED RESULTS
For ansible 2.1.4:
```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "var3": "hello world"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
For ansible past 2.1.4 (2.1.5, 2.2.2, 2.3)

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/vagrant/var.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

var2: &var2 "world"
var3: !string!join [[*var1, *var2], ' ']
      ^ here
```

**Comment by nitzmahone** [comment]
@jimi-c I assume this is related to the CVE fix, and might be a case of "don't do that"?

**Comment by jimi-c** [comment]
Yes, this is caused by the fact that we're properly using the "safe" loader as the basis for our custom loader now, so built-in Python types are not allowed. This would need to be done via regular jinja2 filters later rather than via YAML references.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
