### ISSUE TITLE
ansible/parsing/dataloader.py tries to use formatting with bytes string (uncompatible with py3)

### ISSUE THREAD

**Issue by mangelajo** [ansible/ansible#23680]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
when using "copy", programming error in ansible/parsing/dataloader.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/centos/os-data-miner-jupyter-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.4.5 (default, Nov  9 2016, 16:24:59) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
when using "copy", there's a programming error in ansible/parsing/dataloader.py

##### STEPS TO REPRODUCE
$ python3
>>> for suffix in (b'.yml', b'.yaml', b''):
...     b_main = b'main%s' % (suffix)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

##### EXPECTED RESULTS
Code running fine

##### ACTUAL RESULTS

Exception

```
task path: /home/centos/os-data-miner-jupyter-ansible/jupyterhub-install.yaml:31
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib/python3.4/site-packages/ansible/executor/task_executor.py", line 521, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.4/site-packages/ansible/plugins/action/copy.py", line 97, in run
    source = self._find_needle('files', source)
  File "/usr/lib/python3.4/site-packages/ansible/plugins/action/__init__.py", line 986, in _find_needle
    result = self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
  File "/usr/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 330, in path_dwim_relative_stack
    if is_role or self._is_role(path):
  File "/usr/lib/python3.4/site-packages/ansible/parsing/dataloader.py", line 237, in _is_role
    b_main = b'main%s' % (suffix)
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

fatal: [up-premium]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by abadger** [comment]
Ansible's minimum Python-3 version is 3.5.  In 3.5, percent formatting of byte strings is supported.  Please update to Python-3.5 and the code should work.  Thank you!

**Comment by mangelajo** [comment]
Ok, understood,

@abadger, It wouldn't be a bad thing if we keep the unit-test part of the patch, what do you think?

**Comment by wbond** [comment]
@abadger You should definitely mention this on https://docs.ansible.com/ansible/python_3_support.html and probably print a warning or bail if run on < 3.5.

**Comment by mangelajo** [comment]
@wbond @abadger on centos7 / rhel7 there's no py3.5 yet, only py3.4, or is there a way to have supported py3.5 ?

**Comment by wbond** [comment]
@mangelajo Unfortunately I don't use those distros. Perhaps one of the third-party RPM repos may have it?

**Comment by eoli3n** [comment]
Is that serious ? Debian 8.9 has only Python 3.4.2 too
temp fixed by 
```
pip3 install ansible==2.3.2
```

**Comment by abadger** [comment]
Debian 8.9 has Python-2.7.9.  We chose Python-3.5 because it was available in all distributions which no longer supported Python-2.6+ by default.

If you have further questions, please take it to the mailing list as it's a user question rather than a bug report.  I'll paste the mailing list information below.

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
