### ISSUE TITLE
File Module Fails in Check Mode

### ISSUE THREAD

**Issue by marmur76** [ansible/ansible#23981]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
File module

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /home/xxxxx/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

CentOS release 6.5
##### SUMMARY
While running in check mode, the file module encounters a fatal error:

"refusing to convert between directory and link"

While it is true, and I've read and understand the reasons for not converting while NOT in check mode, I would think this should not cause a fatal error in check mode.

##### STEPS TO REPRODUCE

On the remote machine, run this:

mkdir /tmp/blah

```yaml
- name: Symlink Blah
  file:
    state: link
    src: "/var/log"
    dest: "/tmp/blah"
```

##### EXPECTED RESULTS

Check mode run to show that the link is not present (i.e. changed).

##### ACTUAL RESULTS

"msg": "refusing to convert between directory and link for /tmp/blah"
****

```

```

**Comment by abadger** [comment]
check mode's purpose is to show you what would happen if you ran the playbook "for real" without actually making any changes.  Since this is an error when run outside of check-mode, it's supposed to be an error inside of check-mode.  If you have any further questions about this, please feel free to bring it up on irc or the mailing list.  I'll paste information about that below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
