### ISSUE TITLE
Support vault encryption in copy module

### ISSUE THREAD

**Issue by fredrik-rambris** [ansible/ansible#24006]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- copy
- ansible-vault

##### SUMMARY
I would like the ability to copy vault encrypted files instead of having the file contents in a variable and using content: "{{ my_vault_var | b64decode }}" on the copy module.

Say I want to distribute a certificate key file but would rather have it encrypted in my repo. I would like to be able to do

```ansible-vault encrypt --output roles/dist_certs/files/cert.key /tmp/cert.key```

And in playbook
```- copy:
  src: cert.key
  dest: /etc/pki/tls/private/cert.key
  decrypt: yes
```

The file would then be decrypted in transit with the vault password on command line.

**Comment by sivel** [comment]
Ansible has supported copying the decrypted contents of vault files since v2.1

Simply specify the vaulted file in `src` and ansible will decrypt it, and then copy the decrypted file to the target.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
