### ISSUE TITLE
Ansible v2.3 centos7 error: TypeError: _execute_module() got an unexpected keyword argument 'wrap_async'

### ISSUE THREAD

**Issue by Kecksdose** [ansible/ansible#24059]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Simple yum installations

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
See below.

##### OS / ENVIRONMENT
CentOS ansible docker image: https://hub.docker.com/r/geerlingguy/docker-centos7-ansible/

##### SUMMARY
I use docker / [this test script from geerlingguy](https://gist.github.com/geerlingguy/73ef1e5ee45d8694570f334be385e181) to test my roles. Two days ago, everything ran fine. Today I receive the errors you find below.

```
TASK [ldap : install sssd client] **********************************************
task path: /etc/ansible/roles/role_under_test/roles/ldap/tasks/main.yml:3
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    display.debug("_execute() done")
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 502, in _execute
    retries = 1
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
TypeError: _execute_module() got an unexpected keyword argument 'wrap_async'

fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
Here is the task I run:

```
#install sssd client
- name: install sssd client
  yum: name=sssd state=latest
```

##### STEPS TO REPRODUCE
I created a repo for this bug. Simply clone it and follow the instructions in the README:https://github.com/Kecksdose/ansible-centos7-bug 

```yaml
---
- name: Update yum packages
  yum: name=* state=latest

- name: install sssd client
  yum: name=sssd state=latest
```

##### EXPECTED RESULTS
No errors.

##### ACTUAL RESULTS
```
TASK [test : install sssd client] **********************************************
task path: /etc/ansible/roles/role_under_test/roles/test/tasks/main.yml:5
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    display.debug("_execute() done")
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 502, in _execute
    retries = 1
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
TypeError: _execute_module() got an unexpected keyword argument 'wrap_async'

fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
	to retry, use: --limit @/etc/ansible/roles/role_under_test/run_test.retry

PLAY RECAP *********************************************************************
```

**Comment by abadger** [comment]
@Kecksdose @geerlingguy  At first I was only able to reproduce this using the provided test script, not by running the playbook on a centos7 virtual machine or a centos7 container.  Taking a look into the differences betweeen my vm and the docker container I think I know what the problem is.  Unfortunately, this is not really a problem that ansible can solve.

What appears to me to be happening is that the docker image is being used as both a controller and a managed machine.  When ansible-playbook starts, it starts running ansible 2.2.1 which is what's installed in the container image.  In the playbook, ansible-playbook does a yum update of all packages which updates ansible to ansible-2.3.0.  ansible-playbook continues on to the next task and fails because some of the code has already been loaded into memory and is ansible-2.2.1 but it is loading additional code which is coming from ansible-2.3.0.  The 2.3.0 code attempts to call _execute_module() with an argument that the 2.2.1 code doesn't recognize.

If you update the container image to have the latest version of ansible or update ansible inside the container prior to executing ansible-playbook I think this will start working.

needs_info

**Comment by geerlingguy** [comment]
@abadger - that makes sense. I'll trigger a new build of the Docker image so it grabs the latest Ansible version.

I wish I could tell Docker hub to trigger builds for multiple upstream projects. Maybe I could build a web hook somewhere to trigger the builds when new Ansible versions are released...

**Comment by geerlingguy** [comment]
@Kecksdose - Can you please try again, pulling the latest image version? I just ran the build again and it looks like it has 2.3.0:

```
Resolving Dependencies

--> Running transaction check
---> Package ansible.noarch 0:2.3.0.0-3.el7 will be installed
```

(Fingers crossed that doesn't cause any build failures elsewhere... I've had to modify a few of my roles to account for minor differences in 2.3).

**Comment by Kecksdose** [comment]
@abadger @geerlingguy Thanks for the quick response and help!

The error disappeared with the new docker image you provided, so I will close this issue.

**Comment by ReSearchITEng** [comment]
This is a very common situation.
Suggestion: Could you please add a hint on this in the documentation of the yum module?
https://docs.ansible.com/ansible/yum_module.html

E.g. in the exclude suggest exclude=ansible,  as well as in the example where there is '*', add an exclude=ansible.
