### ISSUE TITLE
YAML folded scalars do not work properly in command module

### ISSUE THREAD

**Issue by Techwolfy** [ansible/ansible#24077]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Command Module

##### ANSIBLE VERSION
```
ansible 2.2.1.0 (stable-2.2 04b2e1fbc0) last updated 2017/01/29 03:02:33 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 59c9a6d3c2) last updated 2017/01/29 03:04:46 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD c501e006ea) last updated 2017/01/29 03:08:22 (GMT -700)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If a YAML folded scalar is used after the "creates" argument for the command module, it is treated as part of the command. The "creates" argument is evaluated normally. This likely occurs for other arguments as well.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
    - command: creates=/tmp/nonexistent_file >
        echo
        "success"
```

##### EXPECTED RESULTS
```success```

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "'>' echo success",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "> echo \"success\"",
            "_uses_shell": false,
            "chdir": null,
            "creates": "/tmp/nonexistent_file",
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}
```

**Comment by s-hertel** [comment]
A work around for this:
```
---
- hosts: localhost
  tasks:
    - name: using a folded scalar
      command:
        creates: /tmp/nonexistent_file
        _raw_params: >
          echo
          "success"
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The problem here is that you are doing the folding in the middle of the value, this is not suported by YAML, from spec only comment or other special indicators are allowed before folding. `creates=` is NOT part of YAML, Ansible process it AFTER the `command:` string is processed by YAML.
In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above. You can use the workaround above or just put `>` at the beginning of the value instead of in the middle.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
