### ISSUE TITLE
ansible-vault does not work with piped input anymore

### ISSUE THREAD

**Issue by vlow** [ansible/ansible#24102]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
Fedora 25, latest patch level as of 2017/04/28

##### SUMMARY
Piping the output of echo into ansible-vault (as suggested in the man page) fails with the output:

```
ERROR! [Errno 2] No such file or directory: '/working-directory/-'
```
"working-directory" is the directory from where the command is executed (=$(pwd)).

##### STEPS TO REPRODUCE
1. Open a terminal on the host
2. Execute: 
```
echo "foo" | ansible-vault encrypt --output '/tmp/foobar'
```
##### EXPECTED RESULTS
An encrypted file named 'foobar' containing "foo" is created in /tmp/.

##### ACTUAL RESULTS
```
New Vault password: 
Confirm New Vault password: 
ERROR! [Errno 2] No such file or directory: '/working-directory/-'
```

**Comment by rcuza** [comment]
Looking through the existing tests, I found in the [v2.3.0.0-1 test/integration/targets/vault/runme.sh](https://github.com/ansible/ansible/blob/v2.3.0.0-1/test/integration/targets/vault/runme.sh) file a test for `STDIN`:

This test works:
```
ansible-vault encrypt_string "$@" --vault-password-file "${NEW_VAULT_PASSWORD}" < "${TEST_FILE}"
```

and this works
```
ansible-vault encrypt_string "$@" --vault-password-file "${NEW_VAULT_PASSWORD}" --stdin-name "the_var_from_stdin" < "${TEST_FILE}"
```

But these both produce the reported error:
```
ansible-vault encrypt --vault-password-file "${NEW_VAULT_PASSWORD}" --stdin-name "the_var_from_stdin" < "${TEST_FILE}"

ansible-vault encrypt - --vault-password-file "${NEW_VAULT_PASSWORD}" --stdin-name "the_var_from_stdin" < "${TEST_FILE}"
```
(The second command explicitly set `-` as the INFILE.)

So either the documentation ([web](http://docs.ansible.com/ansible/playbooks_vault.html), [man page](https://github.com/ansible/ansible/blob/v2.3.0.0-1/docs/man/man1/ansible-vault.1.asciidoc.in)) needs to be updated or `ansible-vault encrypt` has a bug for `STDIN` input. 

I am going to assume this is a bug, because `STDIN` is just good UI. In this case, there are missing tests for `STDIN`:
* `ansible-vault encrypt -`
* `ansible-vault decrypt -`
* `ansible-vault view -`

**Comment by rcuza** [comment]
Looks like it was the following commit that added the encrypt_string:

```
commit 7b6c992c46ad5761ad9a946846c2c8ac18028537
Author: Adrian Likins <alikins@redhat.com>
Date:   Fri Feb 17 10:12:14 2017 -0500

    Vault encrypt string cli (#21024)

    * Add a vault 'encrypt_string' command.

    The command will encrypt the string on the command
    line and print out the yaml block that can be included
    in a playbook.
...
```

@alikins made a great commit message, but does not seem to have updated the man page or website documentation.

**Comment by rcuza** [comment]
This issue might be related to #23567.

**Comment by alikins** [comment]
@rcuza Yup, this is the same as #23567 (fixed in https://github.com/ansible/ansible/commit/ae3d7fb29ed3aac413aea05384dd60eacc5f738c) and cherry-picked into stable-2.3

duplicate_of #23567
