### ISSUE TITLE
'shared' inventory folder alongside 'group_vars'/'host_vars'

### ISSUE THREAD

**Issue by ElijahLynn** [ansible/ansible#24388]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
'shared' subdir support

##### ANSIBLE VERSION
```
Ansible 2.3.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Add support for a 'shared' inventory folder that lives alongside 'group_vars' and 'host_vars'. This helps the use case of dev, stage, prod infrastructure all sharing a common set of group_vars. The shared folder would be a symlink up one level to a 'shared' inventory that contained group_vars. 

Docs would need to be updated here - http://docs.ansible.com/ansible/intro_dynamic_inventory.html#using-inventory-directories-and-multiple-inventory-sources

And from the looks of it, it wouldn't be much work to implement in `__init__.py` and maybe host.py for the get function. 

Also `@see http://stackoverflow.com/questions/40606890/how-to-share-group-vars-between-different-inventories-in-ansible`

Just gauging feedback before I do any work on it. Maintainers, feel free to close this if you really don't want this. My feelings won't be hurt ;). 

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by dagwieers** [comment]
Hmm, that seems very specific and over-complicated.
You can do wonderful things using dynamic inventories (inventory scripts) that does exactly what you need.

**Comment by bcoca** [comment]
wouldn't it be much simper to just
```
- inventory/
    production.ini
    staging.ini
    group_vars/
    host_vars/
```
now you can use `-i inventory/` to target all hosts or -i `inventory/staging.ini` for specific ones

**Comment by ElijahLynn** [comment]
That seems reasonable. I'll make a shared.py script we can pop in and share it here for the .1% of others who may have this use case.

**Comment by jchristi** [comment]
@dagwieers Wanting to use a shared static inventory (ie multiple inventory dirs) isn't _that_ specific a use-case. As @ElijahLynn linked, there are people on SO asking about it. While the issue was phrased in specific terms, I think what is being asked is the ability to use more than one static inventory implicitly. This can be accomplished via dynamic inventory scripts but seems trivial to implement as part of the built-in static inventory and would support the "batteries included" philosophy Ansible subscribes to.

**Comment by dagwieers** [comment]
@jchristi: As @bcoca correctly added, the `-i` flag is used exactly for specifying which static inventory you'd like to use. The group_vars/ and host_vars/ directories are shared implicitly.

**Comment by jchristi** [comment]
@dagwieers that solution assumes that _all_ group and host vars are common, which they definitely are not. Also, it does not allow for the mixed use of static + dynamic inventory.

**Comment by dagwieers** [comment]
@jchristi So all of your requirements pretty much prove you're best of with an inventory script. That's what the JSON interface is there for.

**Comment by bcoca** [comment]
The `inventory/` directory can also contain a dynamic script, those are not either/or propositions.

The not wanting to share 'all' is a different issue, i would use symlinks then.

**Comment by jchristi** [comment]
@bcoca using symlinks is not a solution beyond a couple files. It doesn't scale.

This is the solution we ended up implementing: https://gist.github.com/jchristi/c814d066d57a5d0cae5df5f110e85042
...pretty sure this could have been done with a couple of lines in core, rather than a hundred or so separately :slightly_frowning_face:

**Comment by bcoca** [comment]
In 2.4 you can now use either inventory plugins or vars plugins to do same, so I'm going to close this as it is too fringe to be part of core and easy to implement as an inventory script (seen above) or the plugins I just mentioned.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by ElijahLynn** [comment]
This issue has been solved/mitigated now by the fact we can specify multiple inventories in 2.4. We have a "shared" folder that we specify as the first inventory and then we specify a second inventory that gets loaded. Working nicely.

**Comment by ElijahLynn** [comment]
Crosslinking to https://github.com/ansible/ansible/issues/5316#issuecomment-345051733

**Comment by trompx** [comment]
Hey @ElijahLynn,

I have the same need. I have multiple projects that can have one or multiple environments, so I was planning to have the following structure:
```
├── environments
│   ├── project_1
│   │   ├── dev
│   │   │   ├── inventory
│   │   │   ├── group_vars
│   │   │   │   ├── all.yml
│   │   │   │   └── vault.yml
│   │   │   └── host_vars
│   │   │       └── all.yml
│   │   ├── staging
│   │   │   └── ...
│   │   ├── prod
│   │   │   └── ...
│   │   └── shared
│   │       ├── inventory       # empty inventory or common machines accross all env
│   │       └── group_vars
│   │           ├── all.yml     # shared vars accross all env
│   │           └── vault.yml   # shared secrets accross all env
│   ├── project_2
│   └── project_3
```
When I run ansible, I have a function that then check if there is a shared directory and if there is it adds it as first inventory. Is that the way you proceed ?

**Comment by ElijahLynn** [comment]
> Hey @ElijahLynn,
> 
> I have the same need. I have multiple projects that can have one or multiple environments, so I was planning to have the following structure:
> 
> ```
> ├── environments
> │   ├── project_1
> │   │   ├── dev
> │   │   │   ├── inventory
> │   │   │   ├── group_vars
> │   │   │   │   ├── all.yml
> │   │   │   │   └── vault.yml
> │   │   │   └── host_vars
> │   │   │       └── all.yml
> │   │   ├── staging
> │   │   │   └── ...
> │   │   ├── prod
> │   │   │   └── ...
> │   │   └── shared
> │   │       ├── inventory       # empty inventory or common machines accross all env
> │   │       └── group_vars
> │   │           ├── all.yml     # shared vars accross all env
> │   │           └── vault.yml   # shared secrets accross all env
> │   ├── project_2
> │   └── project_3
> ```
> When I run ansible, I have a function that then check if there is a shared directory and if there is it adds it as first inventory. Is that the way you proceed ?

Core Ansible has this now, you can use a 'shared' inventory (or whatever you want to call it) natively in Ansible either with CLI or with ansible.cfg. See https://github.com/ansible/ansible/issues/5316#issuecomment-345051733.

**Comment by zharalim** [comment]
Also documentation on multiple inventories was added in #47586.

**Comment by trompx** [comment]
Hey I had already read the doc about multiple inventories but don't see how I can automatically indicate in ansible.cfg to always check if a shared folder exists on the same level as the env I am targeting.
Besides in the #5316 issue inventory names are hardcoded so I don't see how I could have shared+prod sometimes and shared+staging another time. Plus I don't always have a shared folder as some infras have just a single environment.
For now the solution I use is working so if this is not bad practice I guess I'll keep this setup.
Thanks anyway for the additional info.

**Comment by jchristi** [comment]
Even with the multiple inventories supported in core, I've switched back to simply using symlinks to accomplish what I need in combination with using YAML for all inventory (combined hosts and variables). If you need something more complex than that then I suggest writing a custom inventory plugin. Writing custom plugins in Ansible is really not that hard.
