### ISSUE TITLE
Template module doesn't replace differing file on server

### ISSUE THREAD

**Issue by Tinche** [ansible/ansible#2441]
This is in 1.1, git clone from a few days ago. My rendered template and the file currently on the server are different, yet Ansible leaves the old one on the server.

Sniffing around in the code, ansible/runner/action_plugins/template.py knows the files are different, and invokes the copy module with

```
src=../reports/standalone.xml dest=/opt/jboss-as/standalone/configuration/standalone.xml owner=jboss-as group=jboss-as mode=600 src=/root/.ansible/tmp/ansible-1363605069.48-95610182331776/source dest=/opt/jboss-as/standalone/configuration/standalone.xml
```

which does nothing and returns ok for that step. If I add force=yes to that, it works properly (replaces it the first time, ok the second). Did the copy force default value change in 1.1?

**Comment by bcoca** [comment]
I had this problem, it was caused by a change in the force parameter, it
was fixed that same day. Rebase and check again to make sure it is not the
same issue.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Yep, you should be good.

Let me know if that doesn't fix you up

Thanks!

**Comment by Tinche** [comment]
It works now, thanks.
