### ISSUE TITLE
ansible use shell module cant restart openstack service （i will teach you chinese  if you help me thanks）

### ISSUE THREAD

**Issue by libp** [ansible/ansible#24436]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

shell模块
##### ANSIBLE VERSION

```

```
那些因为看不懂，我先删了。如果你能帮我解决这个问题，我会万分感激并原因无偿教你学习中文。

hi，你们好，我在使用ansible时遇到个小问题，当我用ansible的shell模块执行脚本任务时，脚本的内容是重启openstack服务，但是重启失败。进一步排查原因我发现，ansible连接被执行任务节点时，加了个-tt参数。当我们把-tt参数删除后，重启成功。一般我们用xshell连接linux服务器时，我们也没加-tt参数，我想知道为什么ansible官方要在ssh连接时加个-tt参数。

如果你能帮我解决这个问题，我会万分感激并原因无偿教你学习中文。

**Comment by gundalow** [comment]
@libp Can you please provide 

1) a sample playbook
2) `ansible --version`
3) Where are you seeing `-tt` being set?
4) Output when running with `ansible-playbook -vvvv`

**Comment by wangxuan9237** [comment]
ansible all -m shell -a "service openstack-nova-compute restart"But the openstack-nova-compute stoped not start.we tried add -vvvv find the ssh args -tt cause this problem,if we remove ssh -tt the openstack-nova-compute can restart.

**Comment by rcarrillocruz** [comment]
Is there any reason for not using the Ansible **service** module ?

http://docs.ansible.com/ansible/service_module.html

**Comment by wangxuan9237** [comment]
yes we have....we use ansible in our team.But some gays dont know how to chose right nodule.They just want to use shell or script module for everything...

**Comment by wangxuan9237** [comment]
Yes,we have...our team use ansible as our operation tools.But some guys don't know how to chose right module.They just want to use script or shell module do everything.

**Comment by gundalow** [comment]
I'd strongly suggest using the builtin modules, like `service` they have been designed to be used for this.

**Comment by liuzm7188** [comment]
ansible test -m script -a "/tmp/test.sh"
the content of /tmp/test.sh as follows：
#! /bin/sh
service openstack-nov-compute restart
**** other contents ******

result:   it only stop , but not start.

the same issue is https://github.com/ansible/ansible/issues/23383

**Comment by libp** [comment]
@gundalow the same issue is #23383  ,thank you  very much!

**Comment by libp** [comment]
@gundalow we are a team  and using ansible .

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, issues with command/shell module and services are normally due to lack of backgrounding, you need to use things like `nohup` and `&` to make sure the service is detached and backgrounded by the time the module ends and closes the tty.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by wangxuan9237** [comment]
Thank you for your reply.It means that it's not a ansible bug.The shell/script module designed not for service operation?




发自网易邮箱大师
On 05/12/2017 09:48, Brian Coca wrote:
List Information

Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, issues with command/shell module and services are normally due to lack of backgrounding, you need to use things like nohup and & to make sure the service is detached and backgrounded by the time the module ends and closes the tty.

If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by libp** [comment]
@bcoca @gundalow 
hi  thankyou very much for detail answer;
but we team using ansibe do great thing: 

we justw want use shell module like peopel use xshell to control linux.  
you konw,use cloud plant to operation linux that is a so cool think.

  thank you

**Comment by bcoca** [comment]
The issue with shell and services is that it might end the connection before the service detaches and backgrounds, to avoid this you need to use things like nohup and &, but I still recommend you use the `service` module instead.

**Comment by libp** [comment]
@bcoca 
thankyou  for you answer,but i want please you forgive me iwant say again.
shell module is for what?  not for shell ?  not for script?
we user  use shell module  write a script ,can i use the shell module?
if we can use shell module to write a script .
why we can not use shell module to write a script include a restart service cmd?
that means shell module not support script!  that is a big bug!
i please ansible team can  face the bug and solve it

thank you again ,and thank you ansible team.
@gundalow @bcoca 
i am  not mean  to trouble you. i just want  you know .shell module why can,t support restart service script?
i just want get the trues.
thank you again!
