### ISSUE TITLE
Playbook-level 'become: yes' leads to inconsistent variable expansion

### ISSUE THREAD

**Issue by srenfo** [ansible/ansible#24774]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Playbooks

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
```

##### OS / ENVIRONMENT

Both Ubuntu 16.04 LTS x64 (fairly irrelevant)

##### SUMMARY

Facts gathering runs as root if `become: yes` is set at the playbook level. This leads to inconsistent behavior. For example, `ansible_env.HOME` sometimes expands to `ansible_user`'s HOME and sometimes to `root`'s HOME.

##### STEPS TO REPRODUCE

Run the following playbooks on any arbitrary Linux host.

```yaml
---
- hosts: all
  become: yes

  tasks:
  - debug: msg="{{ ansible_env.HOME }}"
```

```yaml
---
- hosts: all

  tasks:
  - debug: msg="{{ ansible_env.HOME }}"
    become: yes
```

##### EXPECTED RESULTS
The behavior of the two playbooks should be the same. `ansible_env.HOME` should always expand to `ansible_user`'s HOME.

##### ACTUAL RESULTS

```
TASK [debug] ***************************************************************************************************************
ok: [nuc] => {
    "changed": false, 
    "msg": "/root"
}
```
vs.
```
TASK [debug] ***************************************************************************************************************
ok: [nuc] => {
    "changed": false, 
    "msg": "/home/main"
}
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the first playbook you are asking Ansible to gather facts AS root, in the 2nd you are asking it to gather facts as a different user. Facts will reflect which user was used to gather them, it is not feasible for Ansible to gather facts as all possible users on the remote system. 

Also note that become settings are irrelevant for tasks like `debug` which require no connection, user nor privilege escalation as it is a task that is purely informational and ALWAYS executes on the controller due to it's nature.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by srenfo** [comment]
@bcoca I believe you have misunderstood the issue. `debug` is merely used for exposition purposes. The issue at hand applies to any and all modules and is **not** limited to `debug`.

The issue is that there is a subtle change in variable expansion caused by a subtle change in playbook code. From my POV as a non-insider this violates the Ansible design principles of being the easiest IT automation system to use, ever, and of having a minimal learning curve. You might even argue it violates the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

The playbooks are almost identical and IMO look like they work the same. Unless I know very precisely how Ansible works internally, I have no indication that they behave differently.

There is no explicit fact gathering going on in the playbooks. It happens implicitly. The [documentation that introduces `become` at playbook level](http://docs.ansible.com/ansible/playbooks_intro.html) does not indicate that there is a change in behavior, either.

To further underline that this is an issue, [here's a blog post written about this very gotcha](https://hagbarddenstore.se/posts/2015-11-11/ansible-gotcha-playbook-sudo-vs-task-sudo/).
