### ISSUE TITLE
Playbook simulation

### ISSUE THREAD

**Issue by samuelet** [ansible/ansible#248]
I think it would be useful to have a sort of --dry-run in order to test playbooks.

**Comment by mpdehaan** [comment]
Yes, it would, but dry run is also a bit of a lie, because the right change handlers wouldn't always fire and some things have various side effects.   It is nice to know what files have different md5sums and what services are not running, but it doesn't really prove an app will go out correctly, even in Puppet.  It also doesn't make sure your RPM is going to install successfully.  I think testing in a stage environment is generally a better thing to do.   Let's discuss on the mailing list.

**Comment by mpdehaan** [comment]
closing this so we can discuss on list
