### ISSUE TITLE
! is not working on redhat7

### ISSUE THREAD

**Issue by fadyberty** [ansible/ansible#25101]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

ansible "mysqlservers:!ubuntu" -m ping
bash: !ubuntu": event not found

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes below -->
```

```

**Comment by sivel** [comment]
The "problem" is that bash also treats `!` as a special command.  As such, to prevent shell interpretation, you need to use single quotes instead of double:

```
'mysqlservers:!ubuntu'
```

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
