### ISSUE TITLE
tempfile module should remove temporary files/directories after playbook completion

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#25145]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tempfile module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/djasa/my-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT
Linux

##### SUMMARY
tmpfile module should remove all the temporary files and directories it created

##### STEPS TO REPRODUCE

1. create tmp file using tempfile module, print its path
1. after playbook finishes, look if the temporary files/directories are still present

##### EXPECTED RESULTS

Temporary files and directories are gone

##### ACTUAL RESULTS

Temporary files and directories are left "leaked" in /tmp

```

```

**Comment by robinro** [comment]
@djasa I believe this is intended behavior.

Sometimes temporary directories/files should be created that exist after the playbook run and are deleted on a different occasion.
In general the point in time where a tempfile should be deleted depends on the usecase.

You can create a handler that cleans up the file at the end of your play.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As @robinro points out this is intended behaviour, also modules execute in isolation they cannot come back at the end of play to do work, this is what handlers are for.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by granddesigntech** [comment]
Hmmm, the name tmpfile is a bit misleading then.
As ansible does have a local tmp file and attendant cleanup code for end of execution it would be good if the tmpfile module could register any path it creates with ansible which would add it to a list of paths to cleanup at execution end.

One fo two key tentpole value statements for ansible for me is the ability to do complicated things with simple, declarative statements alleviating the need for complex logic (though I appreciate the capability when all else fails).

It seems from the outside like that must be a foundational concept for ansible's creators and if so it seems logical that things that EVERY user is going to need to do (eg putting a handler or block always clause etc in to clean up temp dirs) should be worked into the inherent behaviour fo the product over time.

**Comment by boweeb** [comment]
I think what's expected depends on the user's background.  I would assert that this behavior is _exactly_ what a Linux systems engineer (or anyone "ops" side) would expect (especially if coming from a world of bash scripting).  `tempfile` as implied by the module description is a wrapper around `mktemp` which "generates a unique temporary filename", returns it, touches the file (in most cases), and stops.  It does not do any cleanup on its own -- that would be presumptuous and break the "do one thing well" unix philosophy.  A sys engineer what naturally make the connection between `tempfile` and `mktemp` and it's implications.

As @robinro pointed out there are different use-cases for temporary files.  Thus I strongly disagree with @granddesigntech 's assertion of what constitutes what "EVERY user is going to need to do".  Not every temp file needs to be immediately cleaned.  In fact every major distribution of Linux has facilities enabled by default to clean them automatically (on differing schedules or triggers).

https://linux.die.net/man/3/mktemp

**Comment by granddesigntech** [comment]
On Wed, 17 Apr 2019 at 23:34, Jesse Butcher <notifications@github.com>
wrote:

> I think what's expected depends on the user's background. I would assert
> that this behavior is *exactly* what a Linux systems engineer (or anyone
> "ops" side) would expect (especially if coming from a world of bash
> scripting). tempfile as implied by the module description is a wrapper
> around mktemp which "generates a unique temporary filename", returns it,
> touches the file (in most cases), and stops. It does not do any cleanup on
> its own -- that would be presumptuous and break the "do one thing well"
> unix philosophy. A sys engineer what naturally make the connection between
> tempfile and mktemp and it's implications.
>
I would suggest that both generating the unique file name AND touching the
file breaks the “do one thing well” Unix philosophy already. Since I
suspect the touching of the file was simply a nicety to save having to
generate a unique name AND use it to create the file I would double-down on
that assessment.

Aside from this the doco for the module states:
    “The tempfile module creates temporary files and directories.”
No it doesn’t.
It creates permanent files and directories unless manual intervention is
applied at some point post-creation.
The word temp is short for “temporary”. Not “uniquely named.
A certain demographic’s familiarity with another tool also being badly
named is no excuse for badly naming the wrapper. If anything it is a chance
to correct the misnaming of the wrapped app.

As @robinro <https://github.com/robinro> pointed out there are different
> use-cases for temporary files. Thus I strongly disagree with
> @granddesigntech <https://github.com/granddesigntech> 's assertion of
> what constitutes what "EVERY user is going to need to do". Not every temp
> file needs to be immediately cleaned.
>
thats why exception flags like “dont_clean” are common when there is a
significant opposing usecase.
Not only not adhering the English meaning of the words you use in the name
for default behaviour and thus relying on a certain background to assume
the correct interpretation of the modules behaviour but also not providing
an option for such adherent behaviour is, I believe, more than enough to
justify an opinion that the module could do with some work.

In fact every major distribution of Linux has facilities enabled by default
> to clean them automatically (on differing schedules or triggers).
>
but not the context to necessarily know WHEN it is safe to clean them.
The safest assumption is “when the process that created it exits”.
Otherwise building a unique name generation flag on the File module would
be a much more intuitive and language-accurate implementation at the
Ansible level.

If you really don’t want to break the “do one thing well” principle a
filter to generate a unique file name would be best.

File:
  Path: “/blah/{{ unique-filename(‘someprefixetc’) }}” type of thing.

https://linux.die.net/man/3/mktemp

**Comment by granddesigntech** [comment]
I see from your link that mktemp’s doco is far more accurate in its
description of the behaviour than the tempfile module:

    “mktemp - make a unique temporary *filename”*

**Comment by boweeb** [comment]
Unix philosophy is not a hill I'm willing to die on.

>Not only not adhering the English meaning of the words you use in the name
for default behaviour and thus relying on a certain background to assume
the correct interpretation of the modules behaviour but also not providing
an option for such adherent behaviour is, I believe, more than enough to
justify an opinion that the module could do with some work.

If I may, I'll take this paragraph as the core of your argument.  I agree that the plain-English usage of "temporary" is unfortunate.  I also think that expanding the functionality of the module would be very welcome -- perhaps in the manor of something you stated before: "add it to a list of paths to cleanup at execution end".  However, I don't think that would be trivial since it reaches beyond the scope of modules in general (IDK for sure, I'm not a contributor).  I just think the historical context had an impact on these things early.  I'm pretty sure Ansible was created by people close to the system and this is an example of their assumptions.  I would be stoked to have the proposed changes -- but it makes sense to me why it is the way it is and also why there could be some resistance to changing it.

A general, clarifying note on `mktemp`.  I should have made clear that that section 3 page is for the _C_ function.  The CLI `mktemp` tool (section 1) uses that function and then does the actual creation.

https://linux.die.net/man/1/mktemp
https://linux.die.net/man/3/mktemp

**Comment by bcoca** [comment]
@boweeb, you are asking the module to inject an extra task into the core engine at a 'later' execution point, there is no way to do this currently ... and frankly i would shy away from creating one.

Instead setup a  handler that removes the file on 'change' of the temp file module, it would run after all the tasks in the section.
