### ISSUE TITLE
Inconsistency in docs?

### ISSUE THREAD

**Issue by vcastellm** [ansible/ansible#2525]
I detected that in http://ansible.cc/docs/bestpractices.html#content-organization the file layout is a bit different than in https://github.com/ansible/ansible-examples/tree/master/lamp_simple for example.

I find it better organized in the examples repo. Should best practices reflect this directory structure instead?

I could help with that.

**Comment by tgerla** [comment]
Good find, Victor. If you are able to help fix this that would be great. Happy to review your pull request. Thanks!

**Comment by mpdehaan** [comment]
The long and short of it is while doing ansible-examples we decided that in
many cases, having the notion of inventory and playbooks all siting at top
level was confusing to us.

If you keep inventory in another place (our examples were meant to be
reasonably self contained) some of the organization is not quite as needed.

But yes, I think that, aside from really wanting a variable to eliminate
the need for "../" (and I'll add that), the roles organization is a great
way to go -- because it stresses that the goal of a playbook _is_ to map
the groups to the roles, and a group may fulfill multiple roles.

Plus, I needed a word for what "roles/" were :)
