### ISSUE TITLE
Playbook `hosts` ignored for inventory of the same IP (but different port)

### ISSUE THREAD

**Issue by matejkramny** [ansible/ansible#25311]
##### ISSUE TYPE
[x] - Bug Report

##### COMPONENT NAME
Playbook & Inventory

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Inventory:
```
[slave]
10.0.0.1:1222

[master]
10.0.0.1:9322
```

Playbook:

```yaml
- hosts: master
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
```

Ansible connects to port `1222` instead of `9322` as expected.

##### EXPECTED RESULTS
Ansible to connect to port `9322` as per the host group

##### ACTUAL RESULTS
```
$ ansible-playbook -vvvv -i inventory playbook.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yml ****************************************************************************************************************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [master] ******************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************
Using module file /usr/local/Cellar/ansible/2.3.0.0_2/libexec/lib/python2.7/site-packages/ansible/modules/system/setup.py
<10.0.0.1> ESTABLISH CONNECTION FOR USER: root on PORT 1222 TO 10.0.0.1
<10.0.0.1> CONNECTION: pid 83121 waiting for lock on 8
<10.0.0.1> CONNECTION: pid 83121 acquired lock on 8
```

**Comment by jctanner** [comment]
@matejkramny I think this may be due to the host "10.0.0.1" being set as the key within the internal inventory structure.

If you refactor your inventory to look like this, does it behave as you expect?

```
slave ansible_ssh_host=10.0.0.1 ansible_ssh_port=1222
master ansible_ssh_host=10.0.0.1 ansible_ssh_port=9322
```

needs_info

**Comment by matejkramny** [comment]
Rewriting the inventory like that does work - thanks!

Is this intended or a bug?

**Comment by dagwieers** [comment]
@matejkramny It is not intended, nor a bug. It's the consequence of using the IP address (or hostname) as the key in the hosts dictionary (cfr. the key in a DB table). For dictionaries it means that for duplicate keys usually the last key wins.

In this case you could wonder if the port is not an intrinsic part of that key, but changing this would impact how users have to address systems. So I bet that's not going to happen. Let's say that when the INI inventory format was "designed", this use-case was never considered.

PS If you would be using a YAML or JSON inventory, this is much clearer (and a colon in the key might as well work there). I am a real proponent of YAML inventories for static files over the INI format.

PS2 The irony here is that the INI file format was chosen as the default format because of its simplicity and because it's a known/common format, but in reality the hosts file is not even the real INI format (it does not parse), nor is it today simple to manage hosts, groups and variables in the INI format unless for very very simple situations, which people very quickly outgrow.

**Comment by matejkramny** [comment]
Thanks for explaining this @dagwieers. I was thinking it was saved under the group and it didn't make sense when it behaved like this.

Isn't the YAML format deprecated?

**Comment by dagwieers** [comment]
A long long time ago it was deprecated in favor of the crooked INI format, but it has been reinstated natively and now JSON is possible as well (but JSON is harder to get right IMO), besides JSON is a subset of YAML so...

We often use it for prototyping, or test-driving specific playbooks for lab environments.

**Comment by sivel** [comment]
Closing per above.
