### ISSUE TITLE
Serial play stops immediately after one host fails

### ISSUE THREAD

**Issue by domibarton** [ansible/ansible#25317]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core / playbook

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/dbarton/Documents/business/git/infrastructure/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

ansible.cfg:

```
[defaults]

inventory           = hosts
roles_path          = roles
retry_files_enabled = False

[privilege_escalation]
become = True

[ssh_connection]
ssh_args     = -o ControlMaster=auto -o ControlPersist=60s
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r

```

##### OS / ENVIRONMENT

Running from Mac OS X 10.12.5

##### SUMMARY

I'm not 100% sure, but I think there's something odd with the `serial` play feature (or I didn't get the docs right).

When I read the [docs](http://docs.ansible.com/ansible/playbooks_delegation.html#maximum-failure-percentage), there's written:

> By default, Ansible will continue executing actions as long as there are hosts in the group that have not yet failed. 

In my case, the play will stop immediately after the first host fails. Is this a feature or a bug? Only `serial` is set, no `max_fail_percentage`.

##### STEPS TO REPRODUCE

- Setup fresh ansible v2.3.0.0 installation
- Configure static inventory with 3 hosts
- Ensure 2 of the hosts can be pinged (i.e. `ansible -m ping all`) and 1 can't 
- Run the following playbook:

```yaml
---
- hosts:
    - all

  tasks:
    - ping:

  serial: 1
  gather_facts: False
```
##### EXPECTED RESULTS

The play should ping host-by-host. If one host fails, it should continue with the rest of it as mentioned in the [docs](http://docs.ansible.com/ansible/playbooks_delegation.html#maximum-failure-percentage).

##### ACTUAL RESULTS

Ansible will stop the play immediately after one host fails.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

As docs state, that is the default behaviour, the issue is that serial is NOT default. With serial if ALL hosts in a serial batch fail, the play fails.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
