### ISSUE TITLE
Document process for relicensing to GPLv3

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25332]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

documentation

##### ANSIBLE VERSION

v2.4

##### SUMMARY

Since I am doing such relicensing for the xml module (from strict GPLv2 to GPLv2+ including GPLv3), I wondered if there were any guidelines we can collect for future relicensing needs.

You can see what we did for the xml module at: cmprescott/ansible-xml#113

So the basic idea is to:
- Contact every individual that made a contribution to the file(s), even if the contribution may not really be copyrightable (e.g. cosmetic in nature, or low value, or maybe even already replaced by someone else's code). Github makes it very easy to trace everyone, hopefully everyone is well and active.
    - Even when it may not be strictly needed according to copyright law, splitting hairs may cause you more trouble (and is a lot more work) than asking everyone.
    - In case you cannot get everyone's agreement, you can still assess the missing people's contributions for relevance
- Ask for a written statement through Github where they clearly, non-amibuously confirm they grant permission, not just from GPLv2 to GPLv2+, but specifically mention GPLv3 to make it very explicit
    - Statement:
      > I hereby grant permission to license my contributions to the ansible-xml module under the GNU General Public License, version 2 or later, including GPLv3.
    - We opted to specifically state GPLv2+ too, because it does give contributors the same rights they had before with GPLv2.
- Do this directly in the ansible/ansible repository
    - I regret doing this in the original repository, as in this case maybe that repository will be deleted once everything is upstreamed and we will loose the agreements
- Keep track of the contributions, and grants of each individual so it is clear where you stand
- *What to do if you are unable to contact an important contributor ?*
- *What is the legal importance of explicit Copyright notices in files vs. drive-by contributions ?*
- *How well do Github comments hold in court ?*
    - In my opinion this is about due diligence, and ensuring everyone is in agreement, for most drive--by contributions I doubt anyone really would oppose. (individual value vs. commons)
    - That said, legal counsel could help improving the process

**Comment by sivel** [comment]
IANAL

> What to do if you are unable to contact an important contributor?

I'd say you are mostly out of luck here.  If you can't contact the contributor to get permission, the code can't be relicensed, and trying to perform a new implementation after having seen the previous code will always be dubious.

> What is the legal importance of explicit Copyright notices in files vs. drive-by contributions?

Based on https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html it would seem that it is not *required* to add additional Copyright holders to the file, although for anyone contributing a nontrivial amount of code, more than 10 lines, they would qualify to add themselves as an explicit copyright holder in the file.

> How well do Github comments hold in court?

As far as Github comments, from what I understand, email is the preferred method, but since Github will send an email, I believe it qualifies.

**Comment by dagwieers** [comment]
IANAL too.

Well, in our case we have a person mentioned in the file for copyright, but in Github there's no mention of him in the history. I added him to the list of people to contact...

Also not every contribution might be illegible for copyright IMO. Cosmetic changes, cleanup, small fixes, etc. And some contributions have been removed subsequently (because the one-liner was incorrect, or because something was refactored). These are two cases I would like to understand how it plays out.

**Comment by alikins** [comment]
I added lots of assignees here, @gregdek and @robynbergeron since this is a community related item, @abadger since you have lead parts of re-licensing before, @dharmabumstead and @docschick for docs

**Comment by gregdek** [comment]
I'm a little leery of documenting how relicensing *ought* to work from the Ansible side. That seems like a more general "how do you relicense code" question that's beyond our scope.

When a module is upstreamed, the committer is essentially acknowledging that he/she has rights to submit the module. That's all we should be interested in, by design. It's up to the committer to secure those rights. In this case, the relicensing should happen in the cmprescott end, and then when you're satisfied you've done that, submit the module. 

That said, @dagwieers the process you've proposed seems reasonable -- but with 21 contributors to the repo in question, it seems like a daunting task. :/

**Comment by dagwieers** [comment]
Only 6 more to go, but I am not sure if legally all 21 need to sign off on this. (Cannot find good legal practices on this). So that was one reason for me to open this ticket. The other reason is that someone on IRC (#ansible-devel) told me we should document this. If we don't, I don't mind closing this ticket though.
