### ISSUE TITLE
Powershell over SSH

### ISSUE THREAD

**Issue by bhcleek** [ansible/ansible#25344]
##### COMPONENT NAME
powershell over ssh connection

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 17 2017, 20:39:27) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
Running Ansible from macOS Sierra managing a Windows machine over SSH.

##### SUMMARY
Packer has an ansible module that works well to provision machines, but Ansible 2.3.0 broke the [connection plugin](https://www.packer.io/docs/provisioners/ansible.html#winrm-communicator) that was required by Packer to provision Windows machines.

http://docs.ansible.com/ansible/dev_guide/developing_plugins.html#connection-plugins implies that the Ansible connection is decoupled from the shell type. The fact that a custom connection plugin was required, though, makes it clear that there was at least some coupling. The Windows exec wrapper seems to have more tightly coupled the winrm connection: https://github.com/ansible/ansible/commit/8527013fbe539487e6998e806ec4e063eaeb299a#diff-ee294f79d8f01457aa343d67cf321d0a.

@trondhindenes indicated in https://github.com/hashicorp/packer/issues/4904 that @nitzmahone may be able to provide guidance to fix the underlying issue.

##### STEPS TO REPRODUCE
Packer's tests (https://github.com/hashicorp/packer/tree/master/test/fixtures/provisioner-ansible) exercise provisioning a Windows machine on Google Cloud Platform using
* https://github.com/hashicorp/packer/blob/master/test/fixtures/provisioner-ansible/connection_plugins/packer.py
* https://github.com/hashicorp/packer/blob/master/test/fixtures/provisioner-ansible/win-playbook.yml

The example playbook below is a more focused version to demonstrate the problem:

```yaml
---
- hosts: default:packer-test
  gather_facts: no
  tasks:
    - name: win_copy test
      win_copy: src=dir/file.txt dest=file.txt
```

##### EXPECTED RESULTS
The file to be copied successfully.

##### ACTUAL RESULTS
Ansible fails to get information about the file being copied, complaining about an unexpected token in the expression:

```
FAILED! => {"failed": true, "msg": "Failed to get information on remote file ('file.txt'): At C:\\Users\\packer\\AppData\\Local\\Temp\\ansible-tmp-1496625106.29-209327339463692\\win_stat.ps1:1 char:8\r\n+ {\"exec\": \"CkZ1bmN0aW9uIFJ1bigkcGF5bG9hZCkgewogICAgJGVudHJ5cG9pbnQgPSA ...\r\n+        ~\nUnexpected token ':' in expression or statement.\r\n\r\nAt C:\\Users\\packer\\AppData\\Local\\Temp\\ansible-tmp-1496625106.29-209327339463692\\win_stat.ps1:1 char:3045\r\n+ ... ec\"], \"environment\": {}, \"powershell_modules\": {\"powershell\": \"IyBUaG ...\r\n+                                                                 ~\nUnexpected token ':' in expression or statement.\r\n\r\nAt C:\\Users\\packer\\AppData\\Local\\Temp\\ansible-tmp-1496625106.29-209327339463692\\win_stat.ps1:1 char:28010\r\n+ ... XQtSnNvbiAkcmVzdWx0Cg==\", \"module_args\": {\"_ansible_version\": \"2.3.0. ...\r\n+                                                                 ~\nUnexpected token ':' in expression or statement."}
```

**Comment by dagwieers** [comment]
This is an item on our TODO list, but with low priority I'm afraid.
- https://public.etherpad-mozilla.org/p/Ansible_Windows_Community_Plan
- https://github.com/ansible/community/issues/153#issuecomment-286751848

**Comment by nitzmahone** [comment]
Hrm, given that the CP says it supports pipelining and didn't set `shell_type`, I have no idea how it worked even under 2.x (accidentally, I guess). https://github.com/ansible/ansible/pull/25012 should fix most of the issues for non-pipelined mode (if the CP correctly advertises it), but there are still a couple of issues to work through before that fix gets merged. Windows over non-WinRM CPs isn't something we have automated tests for yet, so there will certainly be issues as we make changes (plus the fact that the connection plugin API is still somewhat fluid). I'm willing to make some effort to keep things like this working (the aforementioned PR is about fixing Rackspace's AWSRun Connection Plugin for Windows), but it seems like the long-term solution here is just to get PS-over-SSH (using our native SSH/Paramiko CPs) working or have Packer configure the native management transport (WinRM) properly instead of using SSH at all.

**Comment by bhcleek** [comment]
@nitzmahone, `shell_type` was being set to `powershell` on the command line. I'd tried setting it in the communicator, but if I remember correctly, I couldn't find a variable to set it in the communicator at the time.

I agree with you on the long term fix, but if #25012 will fix this particular problem, then perhaps we can make the `packer` CP work again?

It's difficult for Packer to configure the native management transport as you suggest. Packer exposes a simple interface to its provisioners, but not the underlying transport. In order to get Ansible to work, the Packer's ansible provisioner runs an SSH server and then uses the communicator that Packer provides to the provisioner to communicate with the node. 

Configuring "native management transport" would similarly require running a WinRM server *in* the provisioner. I've considered that before, but haven't been able to find much in the way of documentation of WinRM or a server implementation. I could reverse engineer the server protocol from the various client implementations that are around, but I've been trying to avoid going that route as I'm sure you can imagine...

I'm happy to help however I can; testing, development, etc.

**Comment by nitzmahone** [comment]
@bhcleek I suspect I know the answer, but here goes: does packer have a CI env that could test this given a proposed fix? Or would the testing be manual?

**Comment by nitzmahone** [comment]
I'm just used to using techniques like https://github.com/mwrock/packer-templates to build my Vagrant boxes, using native WinRM IIRC. I'm actually pretty certain (unless we've broken something else recently) that explicitly setting the shell type + #25012 will fix 95% of the issues with making this work on our SSH/Paramiko connection plugin. We've been trying to figure out an abstraction to reliably set the shell type automatically, but setting it manually solves a lot of problems.

**Comment by bhcleek** [comment]
To the best of my knowledge, packer does not have a CI environment that could test this fix. @mwhooker or @rickard-von-essen can you confirm?

However, the tests in https://github.com/hashicorp/packer/tree/master/test/fixtures/provisioner-ansible would test it if run manually. I run `(cd test/fixtures/provisioner-ansible && PACKER_LOG=1 $GOPATH/src/github.com/mitchellh/packer/bin/packer build -var "project_id=$GCP_PROJECT_ID" -var "account_file=$GCP_ACCOUNT_FILE" ./winrm.json)` to test.

I'll take a pass at setting the shell type + #25012 and will report back in the next 48 hours.

**Comment by nitzmahone** [comment]
You may want to set pipelining to False as well (try with it on first, but I can think of a couple potential issues there)

**Comment by mwhooker** [comment]
@bhcleek we do windows CI with [appveyor](https://ci.appveyor.com/project/hashicorp/packer)

Is that what you mean?

edit: looks like it got broken when we moved to the hashicorp organization. Will fix now, but it should test PRs

**Comment by bhcleek** [comment]
@mwhooker, that just tests running Packer *on* Windows, right? What I'm looking for is something that runs the tests in https://github.com/hashicorp/packer/tree/master/test.

**Comment by mwhooker** [comment]
ahh, I misunderstood, sorry. I don't believe we have ci set up for the functional tests, at least publicly. Something we're working on, but probably not in the near future

**Comment by bhcleek** [comment]
#25012  resolves this for us. Once it's released, I'll update the packer connection plugin to take advantage to take advantage of the _shell_type property and other changes that were made in Ansible 2.3.0.

Thank you for your help!

**Comment by dagwieers** [comment]
@bhcleek Would you then care to make a PR with updates to the documentation ? It would be nice to have a section explaining this.

**Comment by bhcleek** [comment]
@dawgwieers I'm happy to make a PR, but I'm not sure which documentation you'd want updated. Can you point me in the right direction?

**Comment by dagwieers** [comment]
@bhcleek There is no documentation about Powershell over SSH, so anything you can add to the existing Windows documentation (to make it work, caveats, etc...) is well-received.

So for the time being, it can be added to the file below, maybe as a separate entry, we plan to reorganize this doc in the near future. https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/intro_windows.rst

I am especially interested, because the same solution could be useful for using Ansible with Powershell to Linux.

**Comment by jhawkesworth** [comment]
For info @bhcleek #25012 has been merged, so will be in ansible 2.4

**Comment by jborean93** [comment]
For some background info, as part of the 2.5 we are planning on looking at what it will take to get PowerShell over SSH working. Some initial work has been done but an fundamental issue with the Win32-OpenSSH implementation has been found.

The issue https://github.com/PowerShell/Win32-OpenSSH/issues/908 causes SSH to randomly drop data from the stdin pipe which is used by a lot of operations for Windows. Once this issue has been merged and released more work can continue with this.

**Comment by mattrucker** [comment]
@jborean93 It appears that the pipeline issue has been resolved in [PowerShell/openssh-portable#235](https://github.com/PowerShell/openssh-portable/pull/235). Any comment on the commitment level of getting PowerShell over SSH working in Ansible? We find WinRM to be workable, but painful, especially having to maintain a PKI relationship to sign certificates.

Thanks for all your hard work!

**Comment by jborean93** [comment]
@mattrucker there is a test branch https://github.com/ansible/ansible/pull/33074 that get's the very basics going but there would be a lot more work to be done to get it working with the existing `ssh` connection plugin. There are also other issues around become and async no longer working that we would need to fix up.

In the end I've seen some minor speed improvements on task execution but really the main benefit I see so far is the copy speed improvement. SSH won't be the the be all to end all for Windows though as it still have similar limitations to WinRM.

**Comment by cdobbyn** [comment]
@jborean93 - The only benefit I can see would be reliability at scale.

**Comment by Justin-DynamicD** [comment]
Looking and stumbled across this.

Just want to add a voice of support, as it does have a few benefits beyond the obvious "Microsoft has clearly started transition" reasons:

1.  Key support.  This alone is pretty big, as dropping a public key into a windows image is way more secure than the current model of setting a password.  In packer I just need to drop in a user_init script first to configure SSH and add a key, then I'm good to go.  

2.  Standardizes connections.  connecting to anything via ssh user@ip streamlines a lot of things beyond the immediate instance such as security policies.  anytime I can cut variables down ... the better.

It just seems like a very good idea to me.

**Comment by petemounce** [comment]
I'd also like to register a desire for ansible to work against Windows over ssh:
* productionised WinRM is a cast-iron pain, because
  * SSL cert knowledge required
  * slow file transfers (workaroundable via cloud push/pull)
* different from all my other infrastructure, so requires training and debugging that rot quicker

My use-case is mostly building golden images with packer, and occasionally remote-executing things like patch updates ahead of a new golden image. I work inside GCE, but also AWS.

I was able to get to a working win32-openssh (`7.7.1.0p1-Beta`) inside GCE on Win2016 DataCenter with:

```shell
gcloud beta compute \
  --project=not-telling-123456 \
  instances create "winssh1" \
  --zone=europe-west1-b \
  --machine-type=n1-standard-2 \
  --subnet=mynet \
  --network-tier=PREMIUM \
  --maintenance-policy=MIGRATE \
  --service-account=123456-compute@developer.gserviceaccount.com \
  --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
  --tags=mynet \
  --image=windows-server-2016-dc-v20180710 \
  --image-project=windows-cloud \
  --boot-disk-size=250GB \
  --boot-disk-type=pd-ssd \
  --boot-disk-device-name="winssh1"
```

wait for it to boot, then

```shell
gcloud beta compute \
  --project "not-telling-123456" \
  reset-windows-password "winssh1" \
  --zone "europe-west1-b"
```

admin powershell (with the aim of this becoming an instance metadata script to run on first boot):

```powershell
$ErrorActionPreference = 'Stop'; # stop on all errors

$installer_script = 'https://raw.githubusercontent.com/DarwinJS/ChocoPackages/master/openssh/InstallChoco_and_win32-openssh_with_server.ps1'
iex ((new-object net.webclient).DownloadString($installer_script))
```

This got me to the point where I could manually add my public key to `c:/users/me/.ssh/authorized_keys` and then `ssh -i mykey me@ip` worked.

I was then going to adapt @jen20's fine work over at https://operator-error.com/2018/04/16/windows-amis-with-even/:

```shell
# sshKeys is what packer's google compute builder uses
gcloud compute instances add-metadata winssh1 --zone europe-west1-b --metadata sshKeys={packer public ssh key}
```

... and then, in the instance bootstrap script:

```powershell
$ssh_public_key = Get-GceMetadata -path "instance/attributes/sshKeys"
mkdir c:\users\packer\.ssh
set-content -Path "c:\users\packer\.ssh\authorized_keys" -Value $ssh_public_key

# and... some stuff to register a scheduled task to do the same on first boot, since this instance is destined to become a set of many instances later, but here maybe instead into the c:/users/default/.ssh directory - not sure, didn't get that far
```

At this point, I set up an inventory file:

```txt
[winssh1]
{ip} ansible_user={me}
```

and tried out `ansible -m win_ping -i inventory.txt -vvv yolo`:

```
$ ansible -i inventory.txt -m win_ping -u myuser -vvv winssh1
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/mylocaluser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
No config file found; using defaults
Parsed /Users/mylocaluser/src/ip/platform/packer/improbable.io/buildkite/ansible/inventory.txt inventory source with ini plugin
META: ran handlers
<{machine-ip}> ESTABLISH SSH CONNECTION FOR USER: myuser
<{machine-ip}> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=myuser -o ConnectTimeout=10 -o ControlPath=/Users/mylocaluser/.ansible/cp/d01f763203 {machine-ip} '/bin/sh -c '"'"'echo ~myuser && sleep 0'"'"''
<{machine-ip}> (1, '', 'The system cannot find the path specified.\r\n')
<{machine-ip}> ESTABLISH SSH CONNECTION FOR USER: myuser
<{machine-ip}> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=myuser -o ConnectTimeout=10 -o ControlPath=/Users/mylocaluser/.ansible/cp/d01f763203 {machine-ip} '/bin/sh -c '"'"'echo "`pwd`" && sleep 0'"'"''
<{machine-ip}> (1, '', 'The system cannot find the path specified.\r\n')
<{machine-ip}> ESTABLISH SSH CONNECTION FOR USER: myuser
<{machine-ip}> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=myuser -o ConnectTimeout=10 -o ControlPath=/Users/mylocaluser/.ansible/cp/d01f763203 {machine-ip} '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1532819691.84-86914650742270 `" && echo ansible-tmp-1532819691.84-86914650742270="` echo ~/.ansible/tmp/ansible-tmp-1532819691.84-86914650742270 `" ) && sleep 0'"'"''
<{machine-ip}> (1, '', 'The system cannot find the path specified.\r\n')
{machine-ip} | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1532819691.84-86914650742270 `\" && echo ansible-tmp-1532819691.84-86914650742270=\"` echo ~/.ansible/tmp/ansible-tmp-1532819691.84-86914650742270 `\" ), exited with result 1",
    "unreachable": true
}
```

This sounds promising - like, it's connecting, but my local ansible needs some configuration tweak or override to understand a different temp path on windows maybe...?

cc @dagwieers & @bhcleek because https://github.com/ansible/ansible/issues/25344#issuecomment-306929698 sounds like it might go easier for the above information.

**Comment by jborean93** [comment]
copied from @trondhindenes https://github.com/ansible/ansible/issues/47706

##### SUMMARY
Add support to allow using ssh (as opposed to http/winrm) as a communication protocol when targeting Windows targets

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
winrm

##### ADDITIONAL INFORMATION
Given that the target node has Powershell 6 installed, ssh is now an alternative communication channel to the existing http/winrm. This is documented here: https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6

It would be awesome to see support for this in Ansible. I'm not sure if the native ssh connection could be used, or if a new "psremoting_ssh" connection plugin is needed, I don't know enough about the core workings of Ansible connections to be able to supply more info. 

I would assume that this support would potentially drastically speed up configuration of windows nodes, since winrm is currently http/xml-based and very slow.

**Comment by trondhindenes** [comment]
I find it really interesting that under testing the ssh option didn't provide any speed benefits over winrm (except for file copies, which makes total sense). 
From that result I would assume that they way testing was done also led to spinning up a new process/runspace on each task  -> This may suggest that what needs to be fixed _first_ for Ansible to get acceptable speends when configuring windows nodes is some sort of connection pooling or long-living process to execute inside of, and that the protocol (winrm/ssh) is of secondary importance (as far as speedup goes). --> https://github.com/ansible/ansible/issues/47707

Fun fact: Ansible drives up to 50% cpu utilization when we configure t3.micro instances, most of which can be attributed to process spinup/spindown

**Comment by jborean93** [comment]
Anyone who is following along, I've just recently revisited my POC PR and have created a new one that shared the ssh connection plugin instead of using a new one. This will need review from the core team but it is closer to what I've envisaged this would look like. If you wish to test it out, just checkout the PR locally and add the variable `ansible_shell_type=powershell` to your inventory.

PR https://github.com/ansible/ansible/pull/47732.

**Comment by ghost** [comment]
Windows Server 2019 has better support for OpenSSH:

https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

It also supports public key authentication:

https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement

Even though there are still some bugs, I did manage to log into my Windows Server 2019 test environment from my laptop using SSH with keys without too much trouble.

It would be really convenient to use this instead of winrm for consistency between Linux and Windows hosts.
