### ISSUE TITLE
Incorrect user picked if the same host is present in the hosts file

### ISSUE THREAD

**Issue by prashantabkari** [ansible/ansible#25443]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- HOST configuration 

##### ANSIBLE VERSION

ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

##### CONFIGURATION
- mentioned above 

##### SUMMARY
<!- 
This is a bit of a trivial issue so not sure if it is reported already. 
I have two entries in the same hosts file but with different ansible_user configured. 
for example 
[docker_host]
10.143.219.12 ansible_user=root
[webservers]
10.143.219.12  ansible_user=abkari

When i run ansible-playbook on a script that takes only the docker_host using the following 
ansible-playbook docker_bring_up.yml  --ask-become-pass

it still picks the one corresponding to the host configured for webservers. This is confirmed when it asks me to enter the sudo password. When i enter the password for root, it says invalid. WHen i enter the password for abkari, it goes through but flashes an error saying abkari user is not in sudoers file 

On changing the hosts file with just one single entry . It worked
-->

##### STEPS TO REPRODUCE

```---
- hosts: docker_host
  gather_facts: no
  tasks:
  - name: check if the container is up
    become: yes
    service: name=docker state=started
```

##### ACTUAL RESULTS

```
fatal: [10.143.219.12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.143.219.12 closed.\r\n", "module_stdout": "\r\nabkari is not in the sudoers file.  This incident will be reported.\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by sivel** [comment]
The `inventory_hostname` or the first column of a host definition in an inventory is a unique key.

Effectively you are adding the host 2 times, but with a different `ansible_user` attribute.  The last one defined wins.  The groups specified in a playbook or via other limit means, plays no role in how inventory is constructed.

Instead you should use host aliases instead of groups, similar to:

```
docker_host ansible_host=10.143.219.12 ansible_user=root
webservers ansible_host=10.143.219.12 ansible_user=abkari
```

Then the keys are the aliased names, still referring to the same host, with different `ansible_user` attributes.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
