### ISSUE TITLE
Can't use variables in async and poll values

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#255]
```

---
- hosts: mybox
  vars: 
    timeout: 10
  tasks:
  - name: Test
    action: command sleep $timeout
    async: $timeout
```

```
$ ansible-playbook test.yml -T30
```

```
Traceback (most recent call last):
  File "/home/jkleint/progs/ansible/bin/ansible-playbook", line 100, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/jkleint/progs/ansible/bin/ansible-playbook", line 81, in main
    pb.run()
  File "/home/jkleint/progs/ansible/lib/ansible/playbook.py", line 239, in run
    self._run_play(pattern)
  File "/home/jkleint/progs/ansible/lib/ansible/playbook.py", line 581, in _run_play
    port=port
  File "/home/jkleint/progs/ansible/lib/ansible/playbook.py", line 375, in _run_task
    async_seconds = int(task.get('async', 0))  # not async by default
ValueError: invalid literal for int() with base 10: '$timeout'
```

I spent a while trying to figure out where and how things get parsed and substituted, but it's just complicated enough that I got scared off from fixing it.

**Comment by mpdehaan** [comment]
it's probaby something that just needs to be wrapped with a utils.template call

**Comment by mpdehaan** [comment]
Hmm, yep, it's a bit intertwingled.   Agreed.

In order to template out the variables, we need host context, though the wait code is actually not per host, it's per group.   I can easily template out the timeout value, but the poll limit is harder.  If we just wanted to template things out using the variables per play, that's quite easy, though I imagine someone is going to try to use a variable from the inventory file at some point.

I'd rather it be maximally not working than part way working in confusing to explain ways -- one is easy to figure out that variables don't work there, another is confusing to figure out why it works SOMETIMES.

A better route may be to just be able to set the default up in the task variables.   That's where all the "pg.get" stuff is in playbook.py   However that doesn't make sense because it would mean every op was async.   Not good either.

I think the best thing we can do is not do this, unfortunately :)
