### ISSUE TITLE
ERROR! 'order' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by hamza-tumturk** [ansible/ansible#25531]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

ansible-playbook
##### ANSIBLE VERSION

```
2.3.1.0
```

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  order: sorted
  gather_facts: False
  tasks:
    - debug: var=inventory_hostname
```

##### EXPECTED RESULTS

It should run the task in order on the hosts. As described in the documentation: [Intro to Playbooks: Hosts and Users](http://docs.ansible.com/ansible/playbooks_intro.html#hosts-and-users)
See at the bottom of section "Hosts and Users".
##### ACTUAL RESULTS

Ansible does not know the attribute "order'.

```
ERROR! 'order' is not a valid attribute for a Play

The error appears to have been in '/Users/hamza.tumturk/git/ansible-etcd/test.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: all
  ^ here
```

**Comment by jctanner** [comment]
@hamza-tumturk unfortunately this is due to our documentation always reflecting current development code instead of the stable release. "order" hasn't made it's way into a release banch yet and only exists in devel.

We are steadily making progress on versioning the docs so that people won't hit these sort of issues in the future. Sorry about the confusion.

**Comment by bcoca** [comment]
there was a "version added" tag, but i mistyped so it is not showing in docs, pushed fix
