### ISSUE TITLE
ansible_facts function is missing after 2.4 facts refactoring

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#25686]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/facts.py

##### ANSIBLE VERSION

```
2.4
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
2.3 and below had a function called "ansible_facts" in module_utils/facts.py. After the recent facts refactor that function is gone. Openshift was using that function in a custom module and would probably like for it to remain.

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L28
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L1924

##### STEPS TO REPRODUCE
python -c 'from ansible.module_utils.facts import ansible_facts'

##### EXPECTED RESULTS
no import failure

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name ansible_facts
```

**Comment by alikins** [comment]
Is the module intentionally re-collecting system facts?  The old ansible_facts() method was more or less equivalent to running the setup module or a regular 'gather_facts: True'.

Is openshift_facts used in lieu of setup.py for fact collection?  Or does it (re)-collect system facts so it can reference them locally? (Like the code in https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L2020-L2026 for example)

Most of ansible_facts() impl was moved into the setup.py module since it is specific to gathering the default facts setup.py is responsible for. I can potentially move it back into ansible.module_utils.facts for compat. I need to figure out which old version of ansible.module_utils.facts I should target for compatibility since the 2.0 and 2.2 apis arent compatible to each other.

**Comment by sdodson** [comment]
@abutcher would know best

**Comment by abutcher** [comment]
> Is the module intentionally re-collecting system facts? The old ansible_facts() method was more or less equivalent to running the setup module or a regular 'gather_facts: True'.

> Is openshift_facts used in lieu of setup.py for fact collection? Or does it (re)-collect system facts so it can reference them locally? (Like the code in https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L2020-L2026 for example)

They're recollected so that we can reference facts like `ansible_default_ipv4`, `ansible_product_name`, `ansible_product_version`, `ansible_pkg_mgr`, `ansible_fqdn`, `ansible_nodename`, `ansible_virtualization_type` and `ansible_virtualization_role` when making configuration decisions within our facts module.

We currently try to call `ansible_facts` and then fallback to `get_all_facts(module)['ansible_facts']` which will also be gone in 2.4.
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L1931.

I think it makes sense to provide a mechanism to collect these facts but we could probably pass in system facts (collected by setup) when we call our facts module?

**Comment by sdodson** [comment]
CC: @mtnbikenc

**Comment by alikins** [comment]
@abutcher: could you test your modules against the changes in https://github.com/ansible/ansible/pull/27294 ?

#27294 is a firstpass at a 2.0/2.2 module_utils.facts compat API (though just ansible_facts() and get_all_facts() at the moment).

**Comment by mtnbikenc** [comment]
I tested #27294 against openshift-ansible and got the same errors as the PR automated tests on `constants` import.

**Comment by mtnbikenc** [comment]
I'll add that this error happens prior to the original error on `ansible_facts`.

**Comment by alikins** [comment]
import error should be fixed now (forgot there is no ansible.constants in the modules runtime path...)
