### ISSUE TITLE
Feature Idea: Lock pip dependencies to a specific version

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#25724]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible install

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun  9 2017, 12:31:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

##### SUMMARY

Hit this issue https://github.com/pyca/pynacl/issues/298 when installing ansible on a machine without `make`. Basically some ansible pip dependency now depends on pynacl which requires `make` to build. Ansible pulled this in during pip install and broke all our builds. pynacl has since uploaded binaries so `make` is no longer required, but I think locking versions will help people have repeatable and consistent ansible installs.

##### STEPS TO REPRODUCE

`pip install ansible==2.3.0.0`

```yaml

```

##### EXPECTED RESULTS

pip install ansible install the same versions of dependencies everytime

##### ACTUAL RESULTS

package dependency changed, which prevented ansible to be installed in certain environments

```

```

**Comment by nitzmahone** [comment]
IMO, this would probably create more issues than it'd solve- the biggest is that if there's a security update or bugfix in a dependency, we'd have to do a new release for people to get it (without manually installing/upgrading the updated components).

**Comment by bcoca** [comment]
I agree with @nitzmahone  -1 to this feature

**Comment by nitzmahone** [comment]
Thankfully most of our dependency projects are pretty good about addressing issues like this quickly when they do arise. Our CI system usually starts bombing loudly if there's a problem with any of the numerous distros we test on, so sometimes we'll be the first to raise the "it's busted" flag.

**Comment by sivel** [comment]
I am also a -1

Additionally, since we support such a wide variety of OSes and versions, and not all people are using pip directly to install, we effectively support just about all versions of the dependencies.

In this case pynacl is a dep of paramiko.  paramiko added it as a dep 20 days ago, to allow support for ED25519 keys.  Had we pinned at an older version, we would be limiting users to a version without this support, and users may need this functionality going forward.

To avoid dep issues, you should consider installing via an OS package manager that ensures you have all the deps you need.  If you decide to use pip, you will need to understand that there are deps that cannot be resolved outside of pip, in the case of needing to compile C extensions.  

Also, pynacl does ship wheel packages, which should largely negate the need for compiling it, assuming you are using a version of pip (>=8) which supports installing wheel packages.

**Comment by jamesongithub** [comment]
We're using pip to install since that seems to be the recommended ansible way. Pyancl only added the wheel package only after they realized people were hitting this issue.

Locking versions will always be a tradeoff between getting the latest and having consistent installs. RE: the security thing, in my experience people just pip install once and never again after that so they probably won't be receiving patches either.

For our internal stuff and for 3rd party dependencies we always lock versions to prevent things like this. Been burned too many times by npm. We release and upgrade our dependencies often tho, so our release diffs are small -- it's less of an issue for us. I don't know about ansible's release process.

Maybe consider just locking major and minor versions?

**Comment by sivel** [comment]
I don't think we are going to consider this.  I might suggest implementing your own `constraints.txt` file that constrains the package versions selected during a pip install.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
