### ISSUE TITLE
Allow to list magic variables with ansible-doc

### ISSUE THREAD

**Issue by bregman-arie** [ansible/ansible#25923]
- Feature Idea

##### COMPONENT NAME
feature

##### ANSIBLE VERSION
all

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Today, there is no option to list the magic variables by using ansible-doc.
There should be some flag for ansible-doc to display a list of the magic variables with a description for each variable.

**Comment by s-hertel** [comment]
cc @dharmabumstead

**Comment by jimi-c** [comment]
Hi, this feature request has been open for well over a year but has not received any attention. We would be open to accepting this feature, but for now, we're going to close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
