### ISSUE TITLE
Make Ansible run <role>/vars/main.yml file if execution attribute is set.

### ISSUE THREAD

**Issue by Kiarashz** [ansible/ansible#26137]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

main.yml inside vars folder of roles
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
default configuration

##### OS / ENVIRONMENT
Linux/Mac OS X

##### SUMMARY

It would be great if Ansible ran the main.yml file inside role_name/vars folder if execution attribute of the file was set. The filename may not be suitable for an executable file but this can help users to implement desired logic in the file such as loading variables from other files inside the vars folder or even from external resources.

**Comment by nitzmahone** [comment]
cc @bcoca - I suspect one of the new plugins would be a better way to handle this

**Comment by bcoca** [comment]
no, the plugins are not related to roles ... in any case -1 to this, use lookups to do get data from external dynamic sources.

**Comment by sivel** [comment]
Question About This One
=======================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by Kiarashz** [comment]
No worries!
Thanks for the update.
