### ISSUE TITLE
RFE: Allow ssh key based authentication for F5 modules 

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#26231]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

F5 modules

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

Allow ssh key based authentication for F5 modules. F5 allows ssh key based authentication outside Ansible but there is no way to use it with any of the F5 modules.

**Comment by gundalow** [comment]
@caphrim007 FYI

**Comment by caphrim007** [comment]
@gundalow thanks for the mention.

@jainnikhil30 we'll take this RFE offline and track it over at the F5 Ansible module tracker here

https://github.com/F5Networks/f5-ansible/issues/261

Some background on this.

This feature is a non-trivial implementation due to roles that customers use. If we were only dealing with root, then this wouldnt be an issue. However several customers use non-root accounts and we also have the problem of Appliance Mode in BIG-IP.

TMSH provides no structured output, so we can't use TMSH directly. So we would like to use curl calls, or something, to localhost to get the same JSON output. This is a problem for non-root accounts though because they do not have the ability to curl.

One final issue is that SSH connections are notorious, on BIG-IP, for aborting or closing unexpectedly due to resource utilization on BIG-IP. So it's basically not trusty at all. Also, Ansible's persistence framework, per my discussions with maintainers on the devel channel is still a bit too "in flux" to start writing F5 stuff against. Once this irons itself out though, it would be easier.

In any event, I'm open to this option, but we'll follow up at the F5-Ansible link above.

@gundalow can you close this issue on account of the side-band issue?

**Comment by gundalow** [comment]
Closing as tracked in F5Networks/f5-ansible#261
