### ISSUE TITLE
Optimization - Reduce Remote Operations

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#263]
Reduce number of remote operations performed for each task.
- Locally tar module & argsfile
- upload tar
- untar && chmod +x && execute in single step && cleanup in single step

**Comment by mgwilliams** [comment]
After spending some time implementing this, I discovered that the tar/untar takes as long as uploading the extra file, and requires a fair bit of reworking of the code. I was able to accomplish the same speedup by grouping the chmod, execute, and cleanup into a single exec. Further optimization could be accomplished by using a single tmp directory throughout a play, per host, and then cleaning it out at the end.

Two other possible optimizations are to keep ssh and sftp connections open throughout the play, if the fork level is not too high.

**Comment by mpdehaan** [comment]
Good data... I think the cleanup stuff is reasonable with respect to the temp dir but the tarball stuff may be unneccessary.  I do not want to keep the SSH operations open due to the way runner is used by playbooks on a large number of hosts.   They are currently open per task.   It is true that playbooks could complete a full host before moving on to finish all hosts, though this means the multiprocessing.py stuff happens in playbooks and passes forks=1 to Runner.   I'm thinking that way be overcomplicated and it may (or may not?) be better to have all hosts in more or less the same stage of upgrade versus some partially completed and some not.  There are tradeoffs.

I think this is safe to close given #158.
