### ISSUE TITLE
Block/Rescue/Always Exit Code 

### ISSUE THREAD

**Issue by joaogbcravo** [ansible/ansible#26595]
##### ISSUE TYPE
 - Feature Idea (probably bug report too or documentation report)

##### COMPONENT NAME
Block - http://docs.ansible.com/ansible/playbooks_blocks.html

##### ANSIBLE VERSION
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Block/Rescue/Always exit code bug or missing documentation.
When I use Block that has a task that fails, and then I rescue it, what should be the ansible exit code? On the documentation, there is no information about it.  

I have a scenario where I would like to use rescue with the "rollback" tasks, and then would like Ansible to return an exit code != 0, but with the "rescue block", I got always 0.

To let everyone happy I would suggest adding a variable to the Block, something like "exit_behauvior" where you can decide that block will fail at the end with the following alternatives:
- any_failure: if there any failure in any part of the block (block/rescue/always) it will make the block fail.  
- rescued (default one? is this what is in place right now?): if there is a rescue part, any failure on block part will not affect the exit of block
- not_rescued: even if there is a rescue part, if a failure on the block part, the block will fail
- others ?
 
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: False

  tasks:
    - block:
        - fail: msg="fail"
      rescue:
        - debug: msg="rescue"
      always:
        - debug: msg="always"
```

Run the playbook (ansible-playbook block_rescue_problem.yml) and then "echo $?" to get the return code.

##### EXPECTED RESULTS

PLAY RECAP **********************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

I'm not sure what to expected (because documentation don't say anything about it)

I would like to expect an exit code of 2. 

##### ACTUAL RESULTS
PLAY RECAP **********************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

I got an exit code of 0.

**Comment by alikins** [comment]
Would adding a 'fail' task to the end of the rescue block work?

**Comment by joaogbcravo** [comment]
In kind of logic, it works yes. However "pollutes" the play recap. 

Instead of just one really failed task, we have more failed tasks "manually" forced.

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, since the rescue succeeds this is not considered a failed playbook, the exit code reflects the the status of the playbook, not of individual tasks.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
