### ISSUE TITLE
service enabled + state error on ubuntu

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#2661]
https://gist.github.com/base10/945a68dfa7c8d1629393

current work around is to make it into 2 actions.

**Comment by bitmensch** [comment]
I would suggest to use either state or enabled (exclusive-or).
IMHO it seems uncommon to use both in a single task, and that's also something that's not reflected in the module's examples yet.

If this is accepted solution I could provide a PR.

**Comment by mpdehaan** [comment]
That is not neccessary @benjixx 

@bcoca, you were looking into upstart things, any progress?   I would like to get this resolved and need to this myself if not :)

**Comment by mpdehaan** [comment]
working on this now

**Comment by mpdehaan** [comment]
Ok, so the underlying problem is that at least in this case, upstart is coming back with bad status for MySQL, saying it is missing start-stop links, which means we can't really tell if it is running or not.  (Not sure why splitting the two makes it better, exactly).

What I did is detect the 'already is running' message and allow this to /not/ be an error condition, because it isn't.

Fix for this pushed so it will no longer error out.

I need to go back here and disable the 'changed' bit in this case as well.

Got to love upstart :)

**Comment by mpdehaan** [comment]
Actually, yeah, as I recall there are some limitations in the upstart pathway that don't allow us to check easily if something is enabled or not, so the changed bit, well, it may always return true if fiddling with the enablement.  In any event, the error is gone now, so I am closing this ticket.

The service module is due for some refactoring later, as it plays some fun games to figure out the types of services when all three of upstart, systemd, and sysV can be present on the same type of distribution.
