### ISSUE TITLE
include_role: handlers issue

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#26698]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

Handlers are not found in `include_role`.

##### STEPS TO REPRODUCE

```
roles/test/
├── included
│   └── handlers
│       └── main.yml
└── main
    └── tasks
        └── main.yml
```

roles/test/main/tasks/main.yml
```yml
- debug: msg="ping"
  changed_when: yes
  notify: pong

- include_role:
    name: test/included

```

roles/test/included/handlers/main.yml
```yml
- name: pong
  debug: msg="pong"
```

playbook
```yml
- hosts: all
  roles:
    - role: test/main
      tags: ttt
```

##### ACTUAL RESULTS

```
PLAY [all] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [setup] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [all]

TASK [test/main : debug] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ERROR! The requested handler 'pong' was not found in either the main handlers list nor in the listening handlers list

```

**Comment by calfonso** [comment]
It would appear you're not using include_role.  Where are you using include_role and where is the role being included?

needs_info

**Comment by abadger** [comment]
Looking at this, the handler is never being included in the play so it won't be found.  This is a user question rather than a bug in the ansible code.  I'll paste the mailing list and irc information where you can post to get help on writing the playbook so that hte handler will be found below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by hryamzik** [comment]
Oops, missed that step, updated issue.
