### ISSUE TITLE
Service module use argument not implemented

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#26747]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service module

##### ANSIBLE VERSION
All versions, starting from 2.2 since it was documented but not implemented

```
ansible 2.3.1.0
  config file = /home/david/gitbi/hublot/devops-straps/roles-df/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Nothing particular.

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

The use argument is valid because its documented, but not backed by the code...

https://github.com/ansible/ansible/commit/d2fec9d25911e89aebcfd830a2927e0bcb3b5ce3

##### STEPS TO REPRODUCE

Read code, see params['use'] never used :rofl: 

##### EXPECTED RESULTS

Can force a particular implementation of "service module".

##### ACTUAL RESULTS

Always auto-detected.

**Comment by calfonso** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational. Let's explain what we're thinking:

We believe it's a misunderstanding, the code is in the action plugin not in the module itself. 

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists to talk about this and we might be persuaded otherwise.

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by davidfischer-ch** [comment]
Hi!

Thank you very much.

However I will not open an issue if the feature is working properly ... And today I discovered that using "use" to force systemd or systemv * do not work properly. At least not on Ubuntu 16.04.

* I do not remember which one exactly, I can take some time to write a working example.
