### ISSUE TITLE
Set extra_vars via ansible.cfg and environment variables

### ISSUE THREAD

**Issue by ioggstream** [ansible/ansible#26858]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible cli

##### SUMMARY
I wish

 - to set default `extra_vars` via `ansible.cfg`.

instead

 - it's not possible (until now ;)

##### STEPS TO REPRODUCE
```
# ansible.cfg
[defaults]
extra_vars = @file.yml
```

```yaml
ansible -m debug -a msg="I'm using variable {{ mytoken }} from file.yml" '
```

And I'll never have to type `-e@file.yml` anymore :D

```yaml
ansible -e@file.yml -m debug -a msg="I'm using variable {{ mytoken }} from file.yml" '
```

**Comment by ioggstream** [comment]
@robinro Maybe we want to shorten variable names (eg. just `extra_vars` )

**Comment by jimi-c** [comment]
Hi, this feature request has been open for well over a year but has not received any attention. We would be open to accepting this feature, but for now, we're going to close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
