### ISSUE TITLE
Have ansible-pull use python imports/functions instead of run_cmd

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#26867]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
pull

##### ANSIBLE VERSION
devel

##### SUMMARY
`run_cmd` is used in `lib/ansible/cli/pull.py` to call `ansible` and `ansible-playbook`. It would be less error prone and more performant to use python to import/call the corresponding modules instead of running shell commands.

**Comment by robinro** [comment]
I might work on this in the future but am also happy to assist other people and especially newcomers on tackling this.

**Comment by akshaygin** [comment]
@robinro I would be happy to work on this. :)

**Comment by bcoca** [comment]
https://github.com/bcoca/ansible/tree/pull_fix <= i had approached this at one time

**Comment by akshaygin** [comment]
@bcoca Thanks for informing. I will look into another issue.

**Comment by bcoca** [comment]
not what i meant, i was offering as a starting point, I'm not currently working on it

**Comment by akshaygin** [comment]
@bcoca Okay. Then I will take help of that. :)

**Comment by robinro** [comment]
@akshay196 Feel free to open a PR as "WIP" early, I'd be happy to help.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this feature reqeust because the stability gains are in our view not worth the effort to re-implement the tool from scratch, but we are open to submissions in this regard.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
