### ISSUE TITLE
Problem running playbook with path that includes spaces

### ISSUE THREAD

**Issue by mvermaes** [ansible/ansible#2752]
I'm just learning Ansible and ran into a problem when converting my initial playbook to use roles. It seems that if the path to my Ansible project directory contains any spaces, I get an error message. I've included a basic scenario below on how to reproduce.

Thanks for your work on this great program.

<pre>
$ ansible --version
ansible 1.2 (devel bd0c22868e) last updated 2013/04/23 13:28:24 (GMT +800)

$ pwd
/tmp/x x/ansible

$ find
.
./roles
./roles/common
./roles/common/tasks
./roles/common/tasks/main.yml
./site.yml
./test_hosts

$ cat site.yml 
- hosts: local
  roles:
    - common

$ cat test_hosts 
[local]
127.0.0.1

$ cat roles/common/tasks/main.yml 
  - name: dummy command
    command: /bin/ls

$ ansible-playbook -i test_hosts site.yml
Traceback (most recent call last):
  File "/home/michaelv/ansible/bin/ansible-playbook", line 219, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/michaelv/ansible/bin/ansible-playbook", line 180, in main
    pb.run()
  File "/home/michaelv/ansible/lib/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/home/michaelv/ansible/lib/ansible/playbook/play.py", line 104, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/michaelv/ansible/lib/ansible/playbook/play.py", line 270, in _load_tasks
    (k,v) = t.split("=", 1)
ValueError: need more than 1 value to unpack
</pre>

**Comment by mvermaes** [comment]
Actually it has nothing to do with roles - any 'include' statement that has spaces generates the error.

**Comment by mpdehaan** [comment]
will take a look.

We've fixed various things regarding files with spaces as destinations or module parameters, so this it should not be too difficult to correct this as well.    First time anyone has tried a space in the playbook dir, apparently :)

Thanks for the report.

**Comment by AlejandroTrev** [comment]
Any chance this will be fixed in an upcoming release? I am still able to repro in latest checkout:

```
$ ansible --version
ansible 1.3 (devel c3a8b6ff07) last updated 2013/07/18 14:47:27 (GMT -400)
```

This broke all my jenkins "one-click" deployments after I updated all playbooks to use roles. This happened because I have jobs in jenkins named like "foo app - upgrade environment - staging", and jenkins creates directories with the same name:

```
~/jenkins/workspace/foo app - upgrade environment - staging/
```

Fortunately we haven't been deploying at a crazy rate lately, so I don't mind running these deploys by hand if there's an upcoming release with a fix; I'd hate to revert my switch to roles. :(  I didn't have this problem when I used tasks & includes in my playbooks.

Overall, this had a pretty big impact for us, but at least has easy & painless workarounds. :)

Thanks!

**Comment by mpdehaan** [comment]
Yes, this is targeted for 1.3

**Comment by mpdehaan** [comment]
Should be fixed per various fixes yesterday, let me know if not.

Thanks!

**Comment by lenzenmi** [comment]
Just encountered the same problem with ansible 1.7 I tried to import a roll and recieved ERROR: file cound not find "/home/me/some file/ansible/role/common/tasks/main.yml"

I copied the directory structure of my ansible project to /home/me/nospace/ansible... and it works fine.

**Comment by milanjandric** [comment]
The same thing happens for me. Running ansible 1.7.1

ERROR: file could not read: /var/jenkins/workspace/Project - Master/provision/'/var/jenkins/workspace/Project - Master/provision/roles/symfony2/tasks/main.yml'

If I copy all code to path not containing spaces: /tmp/test everything works as expected.

**Comment by bobmaerten** [comment]
The problem seems to occur with path containing non-ascii characters too. I had to rename a directory called "Privé" to "Private" to make my playbooks find my roles.
Running ansible 1.7.2 (installed with pip)

**Comment by samluescher** [comment]
Having the same problem like @milanjandric with 1.7.2 when keeping the project in a path that contains a space:

```
ERROR: file could not read: /Users/sam/Some Folder/Workspace/myproject/deployment/'/Users/sam/Some Folder/Workspace/myproject/deployment/roles/core/tasks/main.yml'
```

Notice the apostrophe where it repeats /Users. 

This seems to be a bug introduced with newer versions: downgrade to Ansible 1.6.9 _resolved the problem_, it works despite the space character. @mpdehaan I'd reopen this.

**Comment by dm03514** [comment]
Not sure if it helps but I'm receiving same error with spaces and apostrophe in the path

``` python
ERROR: file could not read: /var/lib/jenkins/jobs/production deploly/workspace/tpg/ansible/'/var/lib/jenkins/jobs/production deploly/workspace/tpg/ansible/roles/db/tasks/main.yml'
```

**Comment by EmergentBehavior** [comment]
I am also having this issue.

**Comment by codeablehq** [comment]
Same here

**Comment by abadger** [comment]
Hmm... I just noticed this bug report by accident when cleaning out old mail.  Since this bug was closed fixed in 2013 it would be great if someone could open a brand new report.  Something has broken the code causing the saeme symptoms to reappear but to to the time period that's elapsed since the first fix was applied and this one it's likely that the code has changed a great deal since then.  If you think that there is something worth pointing out in this bug, please just link to the relevant comment from the new issue.

Thanks!
