### ISSUE TITLE
syntax for gathering facts inside roles/tasks yml file 

### ISSUE THREAD

**Issue by shashiyadav2017** [ansible/ansible#27875]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

gather facts inside roles/tasks/.yml 

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.1.0
  config file = /var/lib/awx/projects/shashi/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### OS / ENVIRONMENT

Linux

##### SUMMARY

I need to gather facts only for specific hosts where the playbook is making the changes.

Main.yml file is as below:(Here i am making gather_facts as no because i don't want it to run for all the hosts)
main.yml file 
---
- hosts: Myhostgroup
  gather_facts: no
  roles:
    - { role: conditionnotmet, when: project2 !=1 }
    - { role: conditionmet, when: project2 == 1 }

And when the roles are called , there i need to gather facts only for those specific hosts where the playbook is making the changes(.i.e. where the variable project2 value is equal to 1). 

roles/conditionmet/tasks/main.yml file 
---
    - file: path=/tmp/shashi.txt state=touch

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
When using `gather_facts: yes` all it does is runs the `setup` module, so you can can just run the `setup` module by itself and add a when conditional so it only runs on a subset of your hosts.

If by itself it would be
```
# playbook.yml
- hosts: Myhostgroup
  gather_facts: no
  tasks:
  - name: only gather facts for particular hosts
     setup:
     when: project2 != 1

```

If you are calling a role that already has when condition to filter your hosts, just run the setup module normally

```
# role.yml
- setup:

- name: continue on with other tasks
```

There are more options around `setup` if you wish to filter the results, have a look at http://docs.ansible.com/ansible/latest/setup_module.html.

Because this isn't a bug, we're going to close this ticket. However, if you still have any questions or wish to discuss this further you should stop by one of our two mailing lists to talk about it.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
