### ISSUE TITLE
Ansible seems to not support strict configuration of ssh server "Incompatible ssh server (no acceptable macs)"

### ISSUE THREAD

**Issue by bitliner** [ansible/ansible#28004]
It seems that ansible, in order to connect to ssh, does not use the ssh configuration of my host where it is launched, but uses a client ssh.

The way the ssh client works is not transparent, and might need configuration. No clear how to configure it.

I would like to tell the client ssh to use a specific ssh authentication algorithm, that seems to not be included in the ones that it uses.

##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]
```

##### CONFIGURATION

My ssh server has limitation for ssh authentication algorithms and other parameters of the ssh server. 

##### OS / ENVIRONMENT

`MacOSx 10.12.6 (16G29)`

##### SUMMARY

```
PLAY [all] ***********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
No handlers could be found for logger "paramiko.transport"
fatal: [188.165.251.68]: UNREACHABLE! => {"changed": false, "msg": "Incompatible ssh server (no acceptable macs)", "unreachable": true}
```

##### STEPS TO REPRODUCE

Set in /etc/ssh/sshd_config 

```
MACs hmac-ripemd160
```

to restrict the authentication algorithms to use.

##### EXPECTED RESULTS

It connects without throwing an error.

##### ACTUAL RESULTS

```
No handlers could be found for logger "paramiko.transport"
fatal: [188.165.251.68]: UNREACHABLE! => {"changed": false, "msg": "Incompatible ssh server (no acceptable macs)", "unreachable": true}
```

**Comment by bcoca** [comment]
This is not an Ansible question, also you are conflating sshd_config (applies to sshd on that machine) and ssh_config (applies to ssh clients on that machine).

Ansible can use (normally the default) the `ssh` command line client, Ansible itself just passes parameters to it, the config behaviour is up to the ssh client itself and not changed by Ansible in that case. You can view exact execution of `ssh` by adding `-vvv` to the Ansible commands.

Since this is not really an Ansible issue, I'm closing this ticket. Feel free to look for further help at either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bitliner** [comment]
For completeness, this issue is related to [paramiko transport](https://github.com/paramiko/paramiko/issues/803) that does not support certain hmac.
