### ISSUE TITLE
Limit strings with @filename syntax do not handle awkward filenames

### ISSUE THREAD

**Issue by heathtechnical** [ansible/ansible#28116]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 6e7cf7377b) last updated 2017/08/13 07:22:09 (GMT +000)
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Limit strings using @filename syntax do not handle awkward filenames, even when properly escaped.

##### STEPS TO REPRODUCE

```
ansible --list-hosts -i inventory -l @this\:file.lst all
ansible --list-hosts -i inventory -l @another\[file\].lst all
```

##### EXPECTED RESULTS

Filenames with awkward, but escaped, characters should be handled correctly and not result in 'No such file or directory' error.

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: u'this'
to see the full traceback, use -vvv
```

**Comment by alikins** [comment]
ping @bcoca looks like this ends up in inventory.manager.InventoryManager.subset(). 
(assuming the shell is handling the escapes and ansible args parser gets '@this:test.list')

**Comment by alikins** [comment]
@heathtechnical Could you provide an example of the contents of 'this:file.lst'?

Does the limit work if simpler filenames are used? ie (file name 'this_file.lst' and cli '-l @this_file.lst') ?

**Comment by heathtechnical** [comment]
Apologies, the examples I gave above were incorrect, the actual error I get is:

```
$ ansible --list-hosts -i inventory -l @this\:file.lst all
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: u'this'
to see the full traceback, use -vvv
```

Where inventory contains:

```
$ cat inventory
host1
host2
host3
```

And a sensibly named file correctly gives:

```
$ ansible --list-hosts -i inventory -l @this_file.lst all
  hosts (1):
    host1
```

In both cases, file contents is:

```
host1
```

**Comment by sivel** [comment]
I'm not sure that this is reasonably solvable.  The escaping only affects the shell escaping, and the value ansible receives does not include the escapes.

You would have to double escape or quote so that ansible could even receive the escaped version:

```
-l '@limit\:thing.retry'
-l @limit\\:thing.retry
```

I'm still not sure the time tradeoff for implementing the additional logic is really worth it.

We split the pattern before checking if `@` exists, so it's already split into `limit` and `thing.retry` before we look for `@`.  I certainly wouldn't want to check first, as that logic would be terrible.

I'm going to go ahead and close this as a wontfix.

Should someone decide to submit an improvement to the regex that doesn't make it overly complex, we would entertain accepting such a fix.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
