### ISSUE TITLE
Custom module hangs on exit_json for the long running background process.

### ISSUE THREAD

**Issue by senthil-t** [ansible/ansible#28264]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

AnsibleModule

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### SUMMARY

if the ansible module starts any processes, AnsibleModule.exit_json never exits until all the processes are stopped. please see below playbook and the custom module. exit_json returns the result, if the stop the process manually on the backend. this seems to be a serious issue and request to provide any workaround for this issue ASAP.

##### STEPS TO REPRODUCE

Run the below playbook.

```yaml
- hosts: perry
  tasks:
    - name: Test long running background process
      run_process:
        service_name: "mxci"
      register: result

    - debug: var=result 
```

```
#!/usr/bin/python

from ansible.module_utils.basic import *
import os
import time
def main():
    fields = {        
        "service_name": {"required": True, "type": "str"},
        "process_name": {"required": False, "type": "str"}      
    }

    module = AnsibleModule(argument_spec=fields)
    command = "run mxci &"
       
    os.system(command)
    #tried with subprocess, and the behavior is same.
#     process = subprocess.Popen(['/bin/sh', '-c',command], stdin=subprocess.PIPE, stdout=subprocess.PIPE)        
#     process.stdin.flush() 
    time.sleep(5)
    response = {"result": "success"}
    
    #this hangs until the background process stopped. if i stop manually then this call resumes immediately and prints output. 
    module.exit_json(changed=True, meta=response)


if __name__ == '__main__':  
    main()
```

##### EXPECTED RESULTS

```
root@ubuntu:~/Desktop/senthil/custom_module# ansible-playbook run_process_play.yml 

PLAY [perry] *****************************************************************************************************************************************************************************************************


TASK [Gathering Facts] *******************************************************************************************************************************************************************************************

 [WARNING]: Module invocation had junk after the JSON data:  STN39 Session terminated - application closed terminal        08/16 12:51

ok: [perry.in.rdlabs.hpecorp.net]

TASK [Test long running background process] **********************************************************************************************************************************************************************

 [WARNING]: Module invocation had junk after the JSON data:  STN39 Session terminated - application closed terminal        08/16 12:51

changed: [perry.in.rdlabs.hpecorp.net]

TASK [debug] *****************************************************************************************************************************************************************************************************

ok: [perry.in.rdlabs.hpecorp.net] => {
    "changed": false, 
    "result": {
        "changed": true, 
        "meta": {
            "result": "success"
        }
    }
}

PLAY RECAP *******************************************************************************************************************************************************************************************************

perry.in.rdlabs.hpecorp.net : ok=3    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS

hangs and it doesn't print any output. when i manually break the execution (ctrl+c) it emits below output
^CProcess WorkerProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
 [ERROR]: User interrupted execution

```

```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

* When Ansible executes a module on the server, the connection stays open until all processes are finished
* You can use [async](http://docs.ansible.com/ansible/latest/playbooks_async.html) to run processes and poll the results but it will still wait until the process that was created is finished.
* If you are running a process like a service consider using native tools which can be managed by Ansible [service](http://docs.ansible.com/ansible/latest/service_module.html) and [systemd](http://docs.ansible.com/ansible/latest/systemd_module.html)

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
