### ISSUE TITLE
implement plugin auto-discovery

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#28384]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.4.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible should be able to discover and load plugins that are installed as Python packages, avoiding the maintenance burden of patching `ansible.cfg` and adding paths to each of these plugin default installations.

##### EXPECTED RESULTS

We already have multiple Python based products that are using this auto-discovery of plugins approach quite well and we can learn from them when we implement this feature into ansible.

Once we have it, it will be very easy for users to declare their requirements.txt and specify version of ansible and of plugins they want and let pip install them.

Some plugins can be enabled by default, some of them could be enabled by the user, via configuration items or environment variables. We should let the plugin authors decide regarding default behaviour (loading or not) and avoid including this in Ansible. I have the impression that this feature is already enabled in Ansible plugin API, where the plugin can decide for itself.

Few examples of products that are already doing this:
- [tox](http://tox.readthedocs.io/en/latest/plugins.html)
- [pytest](https://docs.pytest.org/en/latest/plugins.html)
- [nose](http://nose.readthedocs.io/en/latest/plugins/writing.html)

Minimal documentation on how to write a plugin should be included into http://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html and preferably pointing to a template plugin repository that does nothing, so it can be used as an working example for plugin developers.

**Comment by bcoca** [comment]
This won't work for modules as they are not required to be python

**Comment by ssbarnea** [comment]
@bcoca They don't really have to be python, only to be wrapped as a python module. Python role here is primarily for packaging and ease of distribution, also giving isolation support via virtuaenvs. 

I am still open to other ideas as long they solve the same problem: the ability to install and to auto-detect/load extensions at runtime.

**Comment by bcoca** [comment]
python is not great at packaging other languages and their dependencies

**Comment by dmsimard** [comment]
Yeah I'm not sure Ansible would be able to do something like this easily.

While I'm not sure if doing something like this is a good idea (looks like it could open up a pandora's box of security vulnerabilities), the closest thing that would come to mind is to have a common location in which callbacks and plugins could install themselves to, add that to the default seek path and then load them.

For example, these paths would be added to the default seek paths:
``callback_plugins = usr/lib/ansible/plugins/callbacks:usr/local/lib/ansible/plugins/callbacks``
``library = usr/lib/ansible/modules:usr/local/lib/ansible/modules``

etc.

Then, plugin and module developers make sure their stuff is installed in that ``usr/local/lib/ansible/<something>`` path. This would work regardless of the language the plugins would have been written in.

However, since Ansible currently automatically load plugins and modules in the seek path, we would likely need to use whitelists just like we currently do to prevent every callback/plugin that Ansible ships with.

**Comment by bcoca** [comment]
We are already on that path, we just need to figure out something that is 'cross distro/OS friendly' for the directory structure. For certain plugins (callbacks, inventory)  we already have a white listing mechanic, others (modules, lookup, filters, tests, action, etc) only get used on demand so it is mostly ok to load them ... the issue is obscuring/overloading since plugins are found by name.

**Comment by jimi-c** [comment]
Hi, going forward collections are going to cover this functionality due to the fact that it is language agnostic and standardized for Ansible.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
