### ISSUE TITLE
ifupdown support

### ISSUE THREAD

**Issue by mhalano** [ansible/ansible#28711]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Suggestion: ifupdown

##### OS / ENVIRONMENT
Ubuntu, Debian, Red Hat, etc. uses it. Ubuntu is replacing by Netplan project, but old versions still use it.

##### SUMMARY
The idea here is have a module to manage the configuration (create and delete interfaces, create vlans,  etc.) on systems using ifupdown (Debian-like or Red Hat-like).

**Comment by alikins** [comment]
Would this overlap with 'nmcli' module? Or would this be aimed at systems not using NetworkManager?

**Comment by mhalano** [comment]
This module is for computers without NetworkManager, like servers.

**Comment by jimi-c** [comment]
Hi, this feature request has been open for well over a year but has not received any attention. We would be open to accepting this feature, but for now, we're going to close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
