### ISSUE TITLE
windows ansible winrm connection failing in 2.2/2.3 but not 2.1

### ISSUE THREAD

**Issue by thatscot** [ansible/ansible#28718]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 - winrm

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /drive/g/user/ansible/futures-deployment/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
pip installed babun to get ansible working.

ran these commands to get winrm working on ansible version 2.1: 

winrm set winrm/config/client/auth '@{Basic="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'

I have ran ConfigureRemotingForAnsible

##### OS / ENVIRONMENT
Windows 7

##### SUMMARY
When running an ansible playbook I am receiving this error 
'''
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "plaintext: auth method plaintext requires a password",
    "unreachable": true
}
'''

Going back to version 2.1 runs as expected and does not produce an error. 

##### STEPS TO REPRODUCE
command to run the playbook:
```
ansible-playbook playbooks/deploy-fuse.yml \
    -i inventories/D/hosts \
    -e application_version=11.1.1.11-SNAPSHOT \
    -e application_business_rules_version=1.1.1 \
    -e snapshot_repo=libs-snapshot-local \
    -e release_repo=libs-release-local \
    --user=fuse \
    -vvv
```

group_vars.yml
```
artifactory_base_url: ******
ansible_user: 'username'
ansible_password: 'password'
ansible_port: '5985'
ansible_connection: 'winrm'
ansible_winrm_scheme: http

```

##### EXPECTED RESULTS

Should run through the playbook. 

##### ACTUAL RESULTS
```
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "plaintext: auth method plaintext requires a password",
    "unreachable": true
```

**Comment by alikins** [comment]
ping @nitzmahone

**Comment by jhawkesworth** [comment]
@thatscot Hmm, that's odd.  My guess is it isn't picking up your group vars in the same way as 2.1 did
Is your group_vars folder in inventories/d ?

Also your group_vars doesn't seem to contain a host group, so the vars you set there will apply to all hosts in your inventory, including localhost, which you are unlikely to be able to connect to using winrm.

I'd suggest adding the connection variables to a group which all your windows hosts belong to and then checking your playbook refers only to the windows hosts you want to apply it to.  Something like the following

```
# inventories/D/group_vars
artifactory_base_url: ******
[windows]
ansible_user: username
ansible_password: password
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_scheme: http
```

```yaml
# playbooks/deploy-fuse.yml
hosts: windows
roles:
  - some_role
  - another_role
```

Can you try the above?  My feeling is that it may have been a bug that you didn't hit an error in 2.1 which has been exposed by your group_vars applying to all hosts in inventory, rather than just the windows hosts.

needs_info

**Comment by thatscot** [comment]
@jhawkesworth 
 Hello, I managed to get it working. Instead of having the username password etc in the top level group_vars folder. I put it in the group_vars folder that is in invetory/d. Also just to let you know I was connecting to a windows sevrver(localhost) froma windows machine.
