### ISSUE TITLE
Realpath filter returns linked file of Ansible server (not from managed node)

### ISSUE THREAD

**Issue by froman68** [ansible/ansible#29003]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

'Realpath' filter.

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

gathering = explicit
gather_timeout = 5
timeout = 5
pipelining = True

##### OS / ENVIRONMENT

Ansible server: Red Hat Enterprise Linux Server release 7.3 (Maipo)
Managed: Red Hat Enterprise Linux Server release 7.3 (Maipo) (but happens also in RedHat EL 5 and 6)

##### SUMMARY

Realpath filter returns path of local file, not from remote server. If file does not exist locally, returns the same string as the file, not following symlinks.

##### STEPS TO REPRODUCE

In the managed server:
- Create a "/var/tmp/testfile".
- Create a symlink "/var/tmp/testlink -> /var/tmp/testfile".
In the Ansible server:
- Create a "/var/tmp/testfile2".
- Create a symlink "/var/tmp/testlink -> /var/tmp/testfile2".

```yaml
---
# Test 'realpath' filter

- hosts: all
  tasks:
    - name: Get realpath
      debug:
        msg: "Real file of {{ item }}: {{ item | realpath }}"
      with_items:
        - /var/tmp/testfile
        - /var/tmp/testlink

```

##### EXPECTED RESULTS

Get the file linked to "/var/tmp/testlink" of managed server.

##### ACTUAL RESULTS

Got the file linked to "/var/tmp/testlink" on Ansible (local) server.

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: realpath-issue.yml ***************************************************
1 plays in realpath-issue.yml

PLAY [all] *********************************************************************
META: ran handlers

TASK [Get realpath] ************************************************************
task path: /var/ansible/pruebas/realpath-issue.yml:7
ok: [BVMNGLADMBLP01-adm.nngg.corp] => (item=/var/tmp/testfile) => {
    "item": "/var/tmp/testfile",
    "msg": "Real file of /var/tmp/testfile: /var/tmp/testfile"
}
ok: [BVMNGLADMBLP01-adm.nngg.corp] => (item=/var/tmp/testlink) => {
    "item": "/var/tmp/testlink",
    "msg": "Real file of /var/tmp/testlink: /var/tmp/testfile2"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
BVMNGLADMBLP01-adm.nngg.corp : ok=1    changed=0    unreachable=0    failed=0

```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * Ansible filters are executed on the Ansible/local server so it returning the local path is correct
   * Looking at the code `realpath` is just a wrapper around `os.path.realpath` so the logic for this is through Python and not Ansible https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L495

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by froman68** [comment]
Ok, I agree that filters are executed on the Ansible server and this is how Python works. But I thing that this should be noted on Ansible documentation. I lost a lot of time investigating what was happening, and surely more people will step on the same issue.

**Comment by bcoca** [comment]
like in the first paragraph in the page that documents filters?
 http://docs.ansible.com/ansible/latest/playbooks_templating.html
or in the filters page itself?
http://docs.ansible.com/ansible/latest/playbooks_filters.html#filters-for-formatting-data

**Comment by froman68** [comment]
Yes, you are right. My apologies, I deserve this "RTFM". I went to the definitions and bypassed that intro.
