### ISSUE TITLE
service module: iptables restart fails on Fedora 17

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2917]
On Fedora 17 (EC2 ami-fd375894), restarting the firewall fails using the service module. This is the latest devel version of ansible. The play is 

```
# this is "firewalld" for F18  
- name: restart the firewall so we can talk to the services
  action: service name=iptables state=restarted
```

while the message is:

```
TASK: [restart the firewall so we can talk to the services] ******************* 
failed: [ec2-[redacted].compute-1.amazonaws.com] => {"failed": true}
msg: Failed to issue method call: Unit name iptables is not valid.
Failed to issue method call: Unit name iptables is not valid.
```

When running on the command line on the host itself, the typical command works fine:

```
[root@ip-[redacted] tmp]# service iptables restart 
Redirecting to /bin/systemctl  restart iptables.service
```

and the changes to the iptables rules are then in place.

It seems that the "service" module's systemd support is still imperfect.

**Comment by robparrott** [comment]
Update: the module succeeds when the the unit name "iptables.service" is used. I.e.

```
# this is "firewalld" for F18  
- name: restart the firewall so we can talk to the services
  action: service name=iptables.service state=restarted
```

However, this means that the user needs to have specific information about the service software being used (i.e. systemd versus SysV scripts) which makes the abstraction les useful. A simple playbook that works with CentOS or RHEL won't work with Fedora, even thought from the same vendor (or vendor base, i.e. RedHat).

**Comment by mpdehaan** [comment]
What version of ansible are you using?

**Comment by mpdehaan** [comment]
quick follow up if you can share Ansible --version output that would be great.

Thanks!

**Comment by jimi-c** [comment]
Can't reproduce this on F17 (somewhat updated) with the current devel branch:

<pre>
$ cat ~/test_firewall_restart.yml 
---
- hosts: all
  gather_facts: false
  tasks:
  - name: restart the firewall so we can talk to the services
    service: name=iptables state=restarted
$ ansible-playbook -i "localhost," -c local ~/test_firewall_restart.yml
PLAY [all] ******************************************************************** 
TASK: [restart the firewall so we can talk to the services] ******************* 
changed: [localhost]
PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

So it appears the service command has been improved. Also, since F17 is EOL and there is a work-around noted above, I don't see any point in keeping this open.

Thanks!
