### ISSUE TITLE
Support scripts dir in roles

### ISSUE THREAD

**Issue by fdavis** [ansible/ansible#2969]
Could we extend roles to support scripts?

So 

```
- script: myscript.sh
```

Gets automagically sucked up from, roles/myrole/scripts/myscript.sh

?

**Comment by srgvg** [comment]
+1
now I have to put those files outside the role

**Comment by mpdehaan** [comment]
I think this should be possible.

Patches would be accepted.   Leaving this open.

**Comment by mcodd** [comment]
This is something I was just wishing for the other day too, great to see it! My only comment would be whether it makes more sense to search for these scripts in roles/$role/files instead of a new subdirectory called scripts?  In my case I would rather have them in files/ because then you wouldn't have to duplicate file between scripts/ and files/ if you sometimes wanted to use it with copy and sometimes with script...

**Comment by srgvg** [comment]
@mcodd having a separate scripts/ directory is conform files/ and templates/; I used to put regular files in templates/ to (before we had roles), but with roles, it makes more sense to standardize, imho.

Also, I'm not sure what your use case would be to use the same file both as a script resource, and as a files (or even templates) resource?

The same goes for e.g. tasks (or files or templates, ..) you'd use in several roles. As to not duplicate the content, I keep a master file at a certain place, and just symlink them if I have to reuse them.

**Comment by mpdehaan** [comment]
I would also be inclined to agree with mcodd here, we are copying these
over verbatim, and it keeps from having too many directories (or having to
document things extra)

It should still also fallback to looking in the current spot as I mentioned
if that file didn't exist.

**Comment by srgvg** [comment]
OK for me.
