### ISSUE TITLE
Undefined variables should fail, not be silently ignored

### ISSUE THREAD

**Issue by LaszloHont** [ansible/ansible#30479]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
jinja2 templating

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible should be better than bash in *all ways*, but the one place it is not is "set -u".
Ansible should fail if a jinja2 template contains a variable that is not explicitly set.

##### STEPS TO REPRODUCE
In bash, this will silently do the wrong thing due to a typo:
```bash
$ cat bash.sh 
#!/usr/bin/bash
SOMEVAR1=test
SOMEVAR2=test
SOMEVAR3=test
SOMEV4R4=test
SOMEVAR5=test

cat <<_HERE_;
$SOMEVAR1
$SOMEVAR2
$SOMEVAR3
$SOMEVAR4
$SOMEVAR5
_HERE_
$ ./bash.sh
test
test
test

test
```

But I can fix it with a single "set -u". Ansible should do this with its templates automatically.

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment]
This is already the case, do you have an example in which undefined variables are silently ignored?

It used to be the opposite, but it was changed back in 1.3, there is a configuration setting to enable this behaviour, but that would be intentional.
```ini
[defaults]
error_on_undefined_vars = False
```
or the environment variable `ANSIBLE_ERROR_ON_UNDEFINED_VARS`

**Comment by LaszloHont** [comment]
Within a Jinja template, if I use the ansible_domain variable, and it is empty, there will be no error.

**Comment by bcoca** [comment]
I get a proper error
```
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AnsibleUndefinedVariable: 'ansible_domain' is undefined"
}
```

**Comment by itdependsnetworks** [comment]
@bcoca 

Jinja:
```
{{ fail.get('other_value') }}
```
vars:
`fail: test`



```
failed: [locahost] (item=/github/cookbook/templates/fileglob/fail.j2) => {"failed": true, "item": "/github/cookbook/templates/fileglob/fail.j2", "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'get'"}
```

This fix seems to be in this closed PR: https://github.com/ansible/ansible/pull/21672

Do not see a reason to not implement 21672. I think you would be able to close a dozen issues or so if you added this in.

**Comment by bcoca** [comment]
@itdependsnetworks  totally unrelated issue, PR was closed cause author found issue with it's correctness.

**Comment by bcoca** [comment]
@itdependsnetworks , the failure above unrelated to undefined variables, you are trying to use a method `.get` on a string, but it is only available on dictionaries. 

You cannot get an `undefined` error because in this case for 2 reasons, 1 you are causing an error before 'other_value' gets checked, 2nd ... the `.get` method is designed to avoid undefined ... it will return `None` if the value does not exist. If you want an undefined error, don't use `get`.

**Comment by itdependsnetworks** [comment]
@bcoca I was looking for feature parity with flask, as shown here:

![image](https://user-images.githubusercontent.com/9260483/30946800-0962cba8-a3d4-11e7-8152-120f9bccbc0a.png)

**Comment by itdependsnetworks** [comment]
IMHO it should at least give you the standard python, 'str object has no attribute get', which is seems that ansible is masking.

**Comment by bcoca** [comment]
you mean like this  ```'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'get'"``` ?

**Comment by itdependsnetworks** [comment]
So you are saying since it is Unicode it's not a string, that was lost on me. Anyway to have flask like output?
