### ISSUE TITLE
Do we want AWS classic ELB rename to go in 2.4?

### ISSUE THREAD

**Issue by wimnat** [ansible/ansible#30494]
@willthames @s-hertel @ryansb @abadger 

##### COMPONENT NAME
elb_classic_lb et al.

##### ANSIBLE VERSION
2.4

Guys, there was a question i raised here https://github.com/ansible/ansible/pull/25745 regarding the rename that went unanswered.

I just wanted to raise here again before 2.4 ships because I think the rename was a bad idea on my part.

If we do rename `ec2_elb_lb` to `elb_classic_lb` then we are not able elegantly update the module to support boto3 because ec2_elb_lb was marked as a stable interface.

I would prefer to revert the PR and leave the modules named as is and then introduce new boto3 modules for elb_classic_lb, elb_classic_lb_facts and elb_instance so that we can introduce changes that are not backward compatible with the old modules.

We would also have to revert part of the PR https://github.com/ansible/ansible/pull/28855.

**Comment by ryansb** [comment]
Unfortunately, I think we passed the option for making a code change, as we're on the last RC (as of about 6 hours before this issue). Regardless, thank you for bringing it up, and I think we've come up with a solution. 

Because we're on RC5 already, what we'll do is leave it as-is in 2.4, but in 2.4.1 we'll undo the rename leaving the ec2_elb_lb and related modules as `stableinterface` and making the `elb_classic_lb` files "preview" as separate files. That way, we can still change them for 2.5 and do the boto3 refactor and any output/param changes we want to make at the same time as "preview", but without putting code changes into 2.4.0 at this late stage of the process. 

That way, we get the nice preview status, but without having to do the un-rename work under the gun and cut new RC's. To this end, we documented this plan in the changelog.

See https://github.com/ansible/ansible/commit/c3821abc95711420f7bf81c3437d10d322217c9f for full changelog wording.
