### ISSUE TITLE
.ini in inventory_ignore_extensions by default

### ISSUE THREAD

**Issue by lystor** [ansible/ansible#30682]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lib/ansible/config/base.yml

##### ANSIBLE VERSION

```
2.4.0.0
```

##### SUMMARY

Hello

Please remove .ini from inventory_ignore_extensions because:
1) INI is one of officially supported by Ansible formats of inventory;
2) IDE and other editors enable INI-format syntax highlighting and content validation only if filename has .ini extension;
3) INI is the first described in documentation format but Ansible ignores *.ini files by default in inventory directory without any warnings that confuses Ansible customers very much.

Thank you

**Comment by bcoca** [comment]
This is done due to inventory scripts, many of them had a `.ini` configuration file that had to reside in the same directory.

With the introduction of inventory plugins in 2.4 we will probably phase inventory scripts out and then will be able to change this default, until then, it is configurable.

Also this only affects when using a directory as a inventory source, if you point at a file directly, the extension does not matter to the `ini` inventory plugin.
