### ISSUE TITLE
ctags tags file in module path broke ansible

### ISSUE THREAD

**Issue by petRUShka** [ansible/ansible#31070]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
PluginLoader

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /home/user/spark/ansible.cfg
  configured module search path = [u'/home/user/spark/library/ansible-aur']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
DEFAULT_MODULE_PATH(/home/user/spark/ansible.cfg) = [u'/home/user/spark/library/ansible-aur']

##### OS / ENVIRONMENT
Arch linux

##### SUMMARY
`tags` file generated by ctags somewhere in module path brake ansible `tags`.

##### STEPS TO REPRODUCE
- add some module path to your `ansible.cfg`, e.g. `library/ansible-aur`
- create tags with ctags. e.g. `library/ansible-aur/tags`
- create any task with tags. e.g. `groups`
- catch an error, e.g.  `conflicting action statements: group, tags`

example of task code:

```yaml
- name: Create user group
  group: name=user state=present
  tags:
    - user
```

##### EXPECTED RESULTS
working without errors

##### ACTUAL RESULTS

```
ERROR! conflicting action statements: group, tags

The error appears to have been in '/home/user/spark/roles/base/tasks/main.yml': line 12, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create user group
  ^ here

...

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: conflicting action statements: group, tags

...
```

Full error log: https://www.pastiebin.com/59cb4faf9ae35

More complete details in that StackOverflow question: https://stackoverflow.com/questions/46441847/ansible-conflicting-action-statements-group-tags

**Comment by sivel** [comment]
Effectively what you have done is create a file that shadows the name of a directive, in a path where modules are searched for.  Ansible modules don't require file extensions, so it picks up the `tags` file thinking it is a module that ansible can execute.

Note here, that ansible doesn't necessarily inspect what this file is, because ansible supports binary modules, etc...

As such, it now thinks you have a module called `tags`.  And since you can't list 2 modules in a single task you get that error.

There has been some discussion to error when things shadow reserved directives.  I would call that a feature idea though, and for what you have here, I would call expected, and not necessarily a bug report.

I think regardless, you are going to end up with an error.

**Comment by petRUShka** [comment]
For me it was bug because I've spend a lot of time to debug it :)

But I agree with you in general case.

**Comment by bcoca** [comment]
not sure we can exclude 'possible modules that look like keywords' as we already have things like `user` which is both.

**Comment by sivel** [comment]
From my perspective, I think we should potentially error if we find a module that shadows a keyword, and just give some detailed information about it.  Although figuring out how we effectively enumerate all of the keywords for that shadow detection is a different matter.

**Comment by bcoca** [comment]
@sivel done https://github.com/ansible/ansible/blob/devel/docs/bin/dump_keywords.py

**Comment by sivel** [comment]
This has been resolved with a nicer error message in newer ansible versions, and will indicate which file is shadowing the name of a module.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
