### ISSUE TITLE
inventory_file doesn't contain the pathname

### ISSUE THREAD

**Issue by gyurco** [ansible/ansible#31294]
- Bug Report

##### COMPONENT NAME
Ansible core(?)

##### ANSIBLE VERSION
```
ansible 2.4.0.0
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Former versions of Ansible returned the full path for inventory_file. Now it is only the filename.

##### STEPS TO REPRODUCE
ansible -m debug -a var=inventory_file localhost

##### EXPECTED RESULTS
This is the result with Ansible < 2.4.0
````
localhost | SUCCESS => {
    "inventory_file": "/var/lib/jenkins/workspace/openstack-ci/openstack-installer/inventory/inventory.py"
}
````

##### ACTUAL RESULTS
With Ansible 2.4.0
```
localhost | SUCCESS => {
    "inventory_file": "inventory.py"
}
```

**Comment by klanghans** [comment]
I can confirm that regression bug: 

vars_files:
    - group_vars/{{ inventory_environment }}.yml
    - vault.ym

is not working any longer since

inventory_file contains the path w/o filename
inventory_file contains the filename w/o path

the 2.4.0 documentation states inventory_file contains path + filename.

So either the documentation is outdated or its a regression bug.

**Comment by bcoca** [comment]
confirmed, in the refactor i mistakenly  took inventory_dir and inventory_file as complimentary, fixing.

**Comment by klanghans** [comment]
Great thanks a lot for the fast reaction time 👍

**Comment by gyurco** [comment]
Yes, that was fast :)
