### ISSUE TITLE
documentation: what is the order of inventory/var plugins?

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#31406]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
constructed

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = /private/tmp/ansible/ansible.cfg
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
```
INVENTORY_ENABLED(/private/tmp/ansible/ansible.cfg) = ['ini', 'constructed']
```

##### OS / ENVIRONMENT
macOS

##### SUMMARY
What is the order of plugins loaded with respect to inventory?, e.g. inventory then vars?  If I use the constructed plugin, can I access group_var variables, or only ones defined inside pre-loaded inventory files?

##### STEPS TO REPRODUCE
NA

##### EXPECTED RESULTS
A section in http://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html or https://docs.ansible.com/ansible/devel/plugins.html, which details the order that related plugin sections are processed.

##### ACTUAL RESULTS
NA

What I would like is to be able to use group_var/host_var variables inside the compose section of the constructed plugin, but I don't think that's possible due to the order - looks like `vars/` are loaded after `inventory/`.

**Comment by halberom** [comment]
related to https://github.com/ansible/ansible/issues/31365 and https://github.com/ansible/ansible/issues/31405

I'm trying to use constructed to do pre-processing of programmatically created vars.

**Comment by bcoca** [comment]
Just FYI, group_vars/host_vars are not available during inventory plugin runs, they happen afterwards.

We do need to add that to our docs.

**Comment by cognifloyd** [comment]
3 thoughts:

1) A composite-vars, vars plugin might be interesting too: something that can construct vars after the rest of the vars have been loaded.

2) Maybe instead of ordering just inventory plugins, we could have an order for inventory and vars plugins. That way, we could load an inventory plugin that uses vars from the default vars plugin. I'm just wrote an inventory plugin that makes sure the yaml plugin is loaded before it, so that it can use host vars specified in some other yaml files to figure out which server to talk to when getting the dynamic list of hosts.

3) I would also like to have something that runs after a vars plugin that can add hosts to groups. As is, I'm writing the vars plugin as an inventory plugin instead so that I can construct groups, not just vars. That only solves part of the problem though: host_vars and group_vars are still not available to any of the inventory plugins.

**Comment by bcoca** [comment]
@cognifloyd 

1) every `vars:` section or yaml vars file  is a composite vars plugin
```
vars:
   newvar: "{{ var1 + vars2 }}"
```
2) inventory plugins and vars plugins are not related anymore, they BOTH use the inventory source paths, but not each other. The inventory plugin order matters for optimizaiton of loading, but not for source processing order, that is established by  1 order of sources passed in, 2 if one is dir, alpha sort of dir

3) vars plugin run at task time,  .. add_host/add_group would be your plugins

**Comment by bcoca** [comment]
cc @acozine .. i believe i did document this but cannot find it, let me know if you need text to fill in if i didn't.

**Comment by azrdev** [comment]
related: #44382

**Comment by samccann** [comment]
general variable precedence is updated at  -https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
and the inventory plugin docs have also been update - https://docs.ansible.com/ansible/devel/plugins/inventory.html

Closing this issue based on ^^. If you are still seeing problems, please open a new issue with specifics on where we may still be missing info. And thanks!
