### ISSUE TITLE
creating several directories doesn't recursively set owner and group

### ISSUE THREAD

**Issue by vcastellm** [ansible/ansible#3141]
Steps to reproduce:

Version: 1.2-devel

Given that user "deploy" and just /home/deploy exists, create a set of directories using file module:

file: path=/home/deploy/foo/bar owner=deploy group=deploy state=directory

"foo" directory gets root:root owner, "bar" gets deploy:deploy

Using recurse=yes option doesn't help either.

**Comment by mpdehaan** [comment]
You may wish to call a chmod -R here with the shell command as this parameter is only intended to set the destination directory.  Otherwise, how does it know that it should also not set things all the way to /home itself (or slash?)

**Comment by mpdehaan** [comment]
Recurse recurses down the chain and not up, so if you want to set the permissions on /home/deploy/foo/bar at level foo, what you want to do is:
- file: path=/home/deploy/foo/bar state=directory owner=deploy
- file: path=/home/deploy/foo state=directory owner=deploy recurse=true

This way it will fix "foo" whether it was already there or not.

**Comment by vcastellm** [comment]
I assumed that if the parent directories doesn't exists they will be created with the same props. Then what's the point in being able to create all the tree in one command?

**Comment by yeago** [comment]
yeah. is suck.

**Comment by chakrit** [comment]
> I assumed that if the parent directories doesn't exists they will be created with the same props. Then what's the point in being able to create all the tree in one command?

I second this.

Creating intermediate directories as root is just unintuitive. It prevents access to the subdirectory. This, of course, does not immediately fail but will instead show as weird permission errors when other programs try to access it.

I think the right behavior is to create them as the specified owner if it does not exist otherwise (if it already exists) just leave them alone and only update the owner/group on the very last directory. If the user wants to enforce the permissions all the way up, **then** he/she should specify multiple entries as in your example.

Specifying multiple entries for the values may also be impossible in some cases as well. I am currently creating a machine that deploys go programs. And go programs depends heavily on having a user-defined import paths the same way java programs have a `com/example/package/subpackage` hierarchy. Defining this in a variable is not possible since all the intermediate directories now incorrectly shows up as `root`-owned. It's also impossible to specify the whole hierarchy in advance due to the code being shared across playbooks/roles and each playbook specifying an entirely different hierarchy.

Running `chown -R` and `chgrp -R` works but that's 2 commands for what ansible should've did correctly (intuitive) by itself. Also this also enforces a user/group change on existing things as well. What if in the future you have other folders that needs different set of permissions?

**Comment by kmeehl** [comment]
I just ran into this problem, and I have to say this is counter-intuitive, at the very least. And in reality the current design is pointless, since we're forced to write a second command to set permissions and ownership on the rest of the dir tree.

I agree wholeheartedly with @chakrit on how it should work.

It's very disappointing that this issue was closed on the same day without so much as a discussion about what's best. It really points to a lack of appreciation for the perspective of your users!
