### ISSUE TITLE
playbook is getting stopped in between with "user XXXXX is not allowed to execute '/bin/sh"

### ISSUE THREAD

**Issue by ramaws** [ansible/ansible#31830]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ramachandra.g$ ansible --version
ansible 2.2.0.0
  config file = /Users/ramachandra.g/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

When we re run the playbook again its end up with following error 

TASK [setup] *******************************************************************
fatal: [some host IP]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ********************************************************************************\n                             !!!WARNING!!!\n********************************************************************************\nThis system is a restricted access system. All activity on this system is\nsubject to monitoring. Information collected that is malicious, unauthorized or\nunlawful, may be provided to the relevant authorities for further action. By\ncontinuing past this point, you expressly consent to this monitoring.\n********************************************************************************\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n", "unreachable": true}
	to retry, use: --limit @/Users/ramachandra.g/Ansible/ansible-empsys-nonprod/ats-jboss-site.retry

finally its making us to reboot the VM, if we want to login to the VM

Here we are using yubkey(https://www.yubico.com/) for LDAP authentication

**Comment by sivel** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe this issue is a configuration error on the target device, and must be resolved outside of the context of ansible.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
