### ISSUE TITLE
Bad group_vars and host files path

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#32089]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
WinRM

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /root/labo/testWin2/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
```

##### CONFIGURATION

[defaults]
host_key_checking = false
callback_plugins = callback
inventory = ./inventory/site/hosts
retry_files_enabled = False

##### OS / ENVIRONMENT

Centos 7

##### SUMMARY
Strange behaviour with inventory and variables, and Windows Support, when you use a directory as hosts

##### STEPS TO REPRODUCE

First get this configuration file

```
[defaults]
host_key_checking = false
callback_plugins = callback
inventory = ./hosts
retry_files_enabled = False
```

the hosts file is like that :

```
[windows]
192.168.204.154

[linux]
192.168.204.119
```

and there is a group_vars/windows.yml

```
ansible_ssh_user: Administrator
ansible_ssh_pass: password
ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
```

Test it : it's ok

```
 ansible -m win_ping windows
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
192.168.204.154 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

Now create a directory

`mkdir inventory/site/`

And copy past your hosts file in this directory.

Edit the ansible.cfg file to change the path to the moved host file

```
[defaults]
host_key_checking = false
callback_plugins = callback
inventory = ./inventory/site/
retry_files_enabled = False
```

And test it again : it fails !

```
ansible -m win_ping windows
192.168.204.154 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.204.154 port 22: Connection refused\r\n",
    "unreachable": true
}
```

It's very surprising.

For the fun I tried specifying manually the user and the password.

```
ansible -m win_ping windows -u Administrator -k
SSH password:
192.168.204.154 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.204.154 port 22: Connection refused\r\n",
    "unreachable": true
}
```

Same problem : Note that the user try to connect using port 22 instead of 5589 (WinRM)

##### EXPECTED RESULTS

The win_ping should be a success considering the only element which have been changed is the path to the host

##### ACTUAL RESULTS

```
ansible -m win_ping windows -vvvvv
Using /root/labo/testWin2/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1
<192.168.204.154> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.204.154> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.204.154> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<192.168.204.154> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.204.154> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.204.154> SSH: PlayContext set ssh_common_args: ()
<192.168.204.154> SSH: PlayContext set ssh_extra_args: ()
<192.168.204.154> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/a1f9f0af50)
<192.168.204.154> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a1f9f0af50 192.168.204.154 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.204.154> (255, '', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/root/.ansible/cp/a1f9f0af50" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 192.168.204.154 [192.168.204.154] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.204.154 port 22: Connection refused\r\nssh: connect to host 192.168.204.154 port 22: Connection refused\r\n')
192.168.204.154 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/a1f9f0af50\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\ndebug1: Connecting to 192.168.204.154 [192.168.204.154] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.204.154 port 22: Connection refused\r\nssh: connect to host 192.168.204.154 port 22: Connection refused\r\n",
    "unreachable": true
}
```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * When using the `ansible` exec, `group_vars` are derived from the location of the inventory file/dir that is set and not the working directory
   * In your case when setting an inventory as a dir it no longer get's the variables set in the group_vars as they are not loaded
   * `ansible-playbook` is a bit different as it also loads from the playbook directory hence why examples show to use this structure

If using `ansible-playbook` this does work as expected, for your case if you want to continue to use just the adhoc command you can either set the variables in the ini file under `[windows:vars]` or you can move the `group_vars` folder to the inventory directory folder.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
