### ISSUE TITLE
vars_files does not take a single string that is not a list

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#3216]
`vars_files` with the path on one line used to work, but now fails to import the variables.

**Fail:**

``` yaml
vars_files: vars/$ansible_distribution.yml
```

**Succeed:**

``` yaml
vars_files:
  - vars/$ansible_distribution.yml
```

**Comment by rdw** [comment]
You can work around this by using the square bracket list notation:

```
vars_files: [vars/$ansible_distribution.yml]
```

But Ansible should at least give an error when it fails to open a vars file.

**Comment by mpdehaan** [comment]
I was never aware this used to work, actually, but you did not get an error?

BTW, using 1.2, you might wish to be consistent and not use $variable:

vars_files: [ "blarg/{{ ansible_distribution }}.yml" ]

etc

Anyway, let me know on behavior.  Thanks!

**Comment by rdw** [comment]
Here's a test playbook:

``` yaml
- hosts: all
  gather_facts: false
  vars_files: vars.yml
  tasks:
    - name: test vars
      local_action: shell echo '{{test_var}}'
```

And the contents of vars.yml:

``` yaml
---
test_var: success
```

The result of running `$ ansible-playbook -i production test.yml -vvv` for me with the latest from the master branch:

```
PLAY [all] ******************************************************************** 

TASK: [test vars] ************************************************************* 
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1371359358.49-54998068554167 && chmod a+rx $HOME/.ansible/tmp/ansible-1371359358.49-54998068554167 && echo $HOME/.ansible/tmp/ansible-1371359358.49-54998068554167']
<127.0.0.1> REMOTE_MODULE command echo '{{test_var}}' #USE_SHELL
<127.0.0.1> PUT /var/folders/0f/5xrj1bgd71j318pkjnn2vhh00000gn/T/tmp7XBXe3 TO /Users/breath/.ansible/tmp/ansible-1371359358.49-54998068554167/command
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/breath/.ansible/tmp/ansible-1371359358.49-54998068554167/command; rm -rf /Users/breath/.ansible/tmp/ansible-1371359358.49-54998068554167/ >/dev/null 2>&1']
changed: [promo] => {"changed": true, "cmd": "echo '{{test_var}}' ", "delta": "0:00:00.003081", "end": "2013-06-15 22:09:18.576786", "rc": 0, "start": "2013-06-15 22:09:18.573705", "stderr": "", "stdout": "{{test_var}}"}

PLAY RECAP ******************************************************************** 
promo                      : ok=1    changed=1    unreachable=0    failed=0   
```

If the vars_files line is changed to a list instead of a string, the variable is substituted as expected.

I'm just learning Ansible myself, and I've noticed a few times that when variables in the playbooks don't get correctly filled that I don't see errors.  The missing vars file is one such case that I have noticed this happening for, but I'll look around and see if I can identify more as I continue learning.  It would be awesome if Ansible was fail-fast for variable interpolation in the playbooks.

**Comment by mpdehaan** [comment]
There's a pull request for that with respect to variables, which is in
queue for testing.

**Comment by mpdehaan** [comment]
This really should error handle and just require the list IMHO.

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/commit/8478e8264732d9abd91435c13fa03d6457cf720d
