### ISSUE TITLE
chroot over ssh

### ISSUE THREAD

**Issue by vliw** [ansible/ansible#3235]
i often do image building on remote servers via my workstation. i would be glad if i could do chroot remotely.
would it be feasible to extend ssh or paramiko to do that? file transfer shouldnt be a problem,  as it would be just prepending the chroot path. for exec i am not sure. any thoughts on that? then i will work on a patch which connection could be extended easier.

**Comment by bcoca** [comment]
It might be easier to implement the same way as sudo, prepend remote
commands with chroot.

Actually, it might already be possible if you add chroot as the last sudo
option.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bennojoy** [comment]
this should also help

http://mmoya.org/blog/2013/03/06/managing-prebuilt-os-images-with-ansible/

**Comment by mpdehaan** [comment]
I'd be interested to see what could be done here as a 'chroot' keyword to the inventory object, like so:

[some_group]
lc1.example.com ansible_ssh_host=myhost.example.com ansible_chroot=/opt/containers/lc1

Patches would be considered!

**Comment by mpdehaan** [comment]
The SSH module would need to understand chroots to do this so I am inclined to think we are not going to do this soon.

**Comment by alem0lars-svcuser** [comment]
Are there any news on chroot over ssh?

Gentoo-based installations need this.

**Comment by aucampia** [comment]
@alem0lars-svcuser 

I wanted to do ssh + chroot so that I could do a `debootstrap` install (similar in many ways to a gentoo install). I ended up adding this in `/etc/ssh/sshd_config`:

```
Port 8922
Match LocalPort 8922
	ChrootDirectory /mnt/sysimage
	X11Forwarding no
```

And then creating a `chroot.myhostname` entry in `~/.ssh/config` with Port 8922.

Doing this in another way (i.e. from inside ansible) would be rather messy IMO - especially if you want to make it work with modules like `synchronize`.
