### ISSUE TITLE
Users added to sudo group not being picked up

### ISSUE THREAD

**Issue by dcotruta** [ansible/ansible#32496]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
core, possibly user

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = SOMETHING/PRIVATE/ansible.cfg
  configured module search path = ['SOMETHING/PRIVATE/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = SOMETHING/PRIVATE/.local/lib/python3.5/site-packages/ansible
  executable location = SOMETHING/PRIVATE/.local/bin/ansible
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST( SOMETHING/PRIVATE/rabbitmq/ansible.cfg) = ['SOMETHING/PRIVATE/rabbitmq/inventory']
```

##### OS / ENVIRONMENT
Ubuntu 16.04 on both

##### SUMMARY
Users added to sudo groups on a target machine cannot elevate permissions if a playbook that uses **become: true** has already failed unless the .ansible directory is cleared from the target machine.

##### STEPS TO REPRODUCE
Create a user on a target machine, do not add it to the sudo group.
Try to run a playbook that makes use of **become: true**.
Add the user on the remote system to the sudo group using **usermod -a -G SUDO_GROUP USER_NAME**.
Try to run the playbook again.
Fail.
Clear the .ansible directory within the user's home directory on the target machine.
Try to run the playbook again.
Succeed.

##### EXPECTED RESULTS
Users added to sudo groups on target machines should allow previously failed (because of a failure with **become: true**) playbooks to run.

##### ACTUAL RESULTS
Users added to sudo groups on target machines **do not** allow previously failed (because of a failure with **become: true**) playbooks to run.

```
fatal: [SOME_HOST]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to SOME_IP closed.\r\n", "module_stdout": "\r\nansible is not in the sudoers file.  This incident will be reported.\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by nitzmahone** [comment]
cc @abadger this sure sounds like a permission issue in the shell plugin stuff at first blush...

**Comment by dcotruta** [comment]
@abadger @nitzmahone Any futher thoughts on this?

**Comment by kermitshort** [comment]
I'm getting this too, Ansible version 2.6.1.  Given the position of the carriage return and newline (I.E. inside the double quotes) it looks as though the carriage return characters are being interpreted as part of the username...this will obviously fail.  I've double checked my files to ensure they aren't Windows style line endings, and they are not.  This is extremely frustrating!!

**Comment by sivel** [comment]
The problem here is that ansible uses the `ControlMaster` functionality of openssh by default.  When a connection to the host is established it will create a muxed control socket, that when re-used will not re-authenticate to the remote host, it will instead use the already existing control socket to connect to the host.

Clearing the local directory removes the control socket path used by SSH, so it establishes a new connection.

Look into altering your `ControlPersist` value to something lower, disabling `ControlMaster`, or utilizing `- meta: reset_connection` from within the playbook.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
