### ISSUE TITLE
Host variables adjacent to master playbook are unavailable to included tasks

### ISSUE THREAD

**Issue by Azenet** [ansible/ansible#32936]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 53ade280a3) last updated 2017/11/15 16:48:34 (GMT +200)
  config file = /home/ashka/.ansible.cfg
  configured module search path = ['/home/ashka/build/ansible/library']
  ansible python module location = /home/ashka/build/ansible/lib/ansible
  executable location = /home/ashka/build/ansible/bin/ansible
  python version = 3.6.3 (default, Oct 24 2017, 14:48:20) [GCC 7.2.0]
```
Note that this happens on 2.4.1.0 as well, which is the version I first had the issue with:
```
ansible 2.4.1.0
  config file = /home/ashka/.ansible.cfg
  configured module search path = ['/home/ashka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ashka/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ashka/.local/bin/ansible
  python version = 3.6.3 (default, Oct 24 2017, 14:48:20) [GCC 7.2.0]
```

##### CONFIGURATION
DEFAULT_GATHERING(/home/ashka/.ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/ashka/.ansible.cfg) = ['/home/ashka/.ansible/hosts']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/home/ashka/build/ansible/library']

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When including tasks that are included in an included playbook, and when the included playbook is not in the same directory as the master playbook, the host vars contained in a folder named `host_vars` that is adjacent to the master playbook are not available in the tasks file. This happens using `import_tasks` as well as `include_tasks`.

##### STEPS TO REPRODUCE
- Create a `playbook.yml` with the following content:
```yaml
# playbook.yml
---
- hosts: 'localhost'
  become: false
- import_playbook: a/included.yml
```

- Create an `a` folder and the `included.yml` to include inside the `a` folder:
```yaml
# a/included.yml
---
- hosts: 'localhost'
  become: false
  tasks:
    - import_tasks: b/tasks.yml
```

- Inside the `a` folder, create a `b` folder and add a `tasks.yml` file inside:
```yaml
# a/b/tasks.yml
---
- name: debug in imported tasks in imported playbook
  debug:
    var: testing
```

- Create variables:
```yaml
# host_vars/localhost
---
testing: "Hello"
```

- Run playbook:
```
$ ansible-playbook playbook.yml
```

##### EXPECTED RESULTS
Variable is defined and its value is displayed. This used to be the case in 2.3 using `include`. As far as I have tested, the same behavior is observed when used `include`.

##### ACTUAL RESULTS
Variable is not defined.
```
TASK [debug in imported tasks in imported playbook] ***
task path: /.../a/b/tasks.yml:2
ok: [localhost] => {
    "testing": "VARIABLE IS NOT DEFINED!: 'testing' is undefined"
}
```

When moving `a/included.yml` in the same folder as `playbook.yml` and editing `playbook.yml` to include `included.yml`, then editing `included.yml` to include `a/b/tasks.yml`, the variable is defined:
```
TASK [debug in imported tasks in imported playbook] ***
task path: /.../a/b/tasks.yml:2
ok: [localhost] => {
    "testing": "Hello"
}
```

**Comment by samdoran** [comment]
We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * In Ansible < 2.4.1, we do not pick up new variables adjacent to included playbooks
   *  In Ansible < 2.4.1, Variables are included adjacent to the _initial_ playbook, not any included playbooks in subdirectories
    * In Ansible >= 2.4.1, you can set [`PLAYBOOK_VARS_ROOT`](http://docs.ansible.com/ansible/latest/config.html#playbook-vars-root) to change this behavior

If you need variables to be included adjacent to included playbooks in Ansible < 2.4.1, use `vars_files`, `include_vars`, or inventory `group/host_vars`.

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists or IRC to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
    * #ansible on irc.freenode.net

Thank you once again for this and your interest in Ansible!

**Comment by lufik** [comment]
I have the same problem with my playbooks with ansible 2.4.1. I think this is not related to tasks but to included playbooks from another directory (as group/host vars are loaded with every included/imported playbook - so the _another_directory_ is the problem).

The PLAYBOOK_VARS_ROOT config doesn't change anything (it's only task related not playbook related). Shortly >=2.4.0 breaks the backward compatibility for including playbooks (maybe the caption of this issue should be changed also).

The workaround for this (on linux) is to symlink the group_vars and host_vars directories to every directory which contains included playbook otherwise you loose all group and host variables in the included playbook. The workaround for the example is: `ln -s ../host_vars a/host_vars`

I see the point with vars_files or include_vars but it's weird to load all group and host vars via those features, isn't it?

BTW the use case could even be more simplified and a little bit more descriptive.

- Create a playbook.yml with the following content:

```
# playbook.yml
---
- hosts: 'localhost'
  become: false
  tasks:
    - name: debug testing
      debug: var=testing

- import_playbook: a/included.yml
```

- Create an a folder and the included.yml to include inside the a folder:
```
# a/included.yml
---
- hosts: 'localhost'
  become: false
  tasks:
    - name: debug testing
      debug: var=testing
```

- Create variable:
```
# host_vars/localhost
---
testing: "Hello"
```

**Comment by samdoran** [comment]
@lufik 

>I see the point with vars_files or include_vars but it's weird to load all group and host vars via those features, isn't it?

You're correct. As you pointed out, using `group_vars` makes more sense and is the way to handle this.

See [this comment](https://github.com/ansible/ansible/issues/33177#issuecomment-356976272) for further details on how variables are handled with `import_playbook`. We also recently [added documentation](https://github.com/ansible/ansible/pull/35199/files) to explain this further.
