### ISSUE TITLE
Is it possible to precise the loading order of files in `group_vars/`

### ISSUE THREAD

**Issue by flaf** [ansible/ansible#33296]
Is it possible to precise the loading order of files in `group_vars/`. The documentation is not totally accurate on this point.

##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

ansible-doc

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg
  configured module search path = [u'/home/flaf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg) = True
DEFAULT_BECOME(/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg) = [u'/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/inventories/production/hosts']
DEFAULT_MANAGED_STR(/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg) = This file is managed by Ansible, don't edit it.
DEFAULT_ROLES_PATH(/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/ansible.cfg) = [u'/home/flaf/MesDocs/informatique/docs/mes_notes/git/ansible-tice/roles']
```

##### OS / ENVIRONMENT

Debian Stretch

##### SUMMARY
I would like to know the order when files in `group_vars/` are loaded. The documentation says clearly [in this page](http://docs.ansible.com/ansible/latest/playbooks_variables.html):

```
Remember: Child groups override parent groups, and hosts always override their groups.
```

But it's not enough to know the order in the cases below.

##### STEPS TO REPRODUCE

According to my tests, with this (arrows mean the relation parent/child):

```
                             +----------+
                             | group_p2 |
                             +----o-----+
                                  |
                                  v
                                  |
  +---------+                +----o----+
  | group_a |                | group_b |
  +----o----+                +----o----+
       |                          |
       v                          v
       |                          |
       +-------+        +---------+
               |        |
               v        v
               |        |
            +--o--------o--+
            | host-srv-foo |
            +--------------+
```

The order of loading is:
1. `group_a`,
2. `group_p2`,
3. `group_b`.

But with this:

```
  +----------+               +----------+
  | group_p1 |               | group_p2 |
  +----o-----+               +----o-----+
       |                          |
       v                          v
       |                          |
  +----o----+                +----o----+
  | group_a |                | group_b |
  +----o----+                +----o----+
       |                          |
       v                          v
       |                          |
       +-------+        +---------+
               |        |
               v        v
               |        |
            +--o--------o--+
            | host-srv-foo |
            +--------------+
```

The order of loading is:
1. `group_p1`,
2. `group_p2`,
3. `group_a`.
4. `group_b`.

So what is the generic rule to know the order?
Regards.

**Comment by flaf** [comment]
PS: of course, I admit that my examples are a bit weird and should not be followed in real cases.

**Comment by alikins** [comment]
Possibly related to:
https://github.com/ansible/ansible/issues/31406
https://github.com/ansible/ansible/issues/31405
and the discussions around https://github.com/ansible/ansible/issues/31405

**Comment by alikins** [comment]
pinging @bcoca

**Comment by alikins** [comment]
@flaf are you looking to know the ordering the files are loaded in, or the resulting var precedence? If the former only: why?

**Comment by alikins** [comment]
@flaf https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/helpers.py has some of the implementation.  the 'priority' can be specified with 'ansible_group_priority'.

So default looks to be sorted by depth, priority, then name with later items having higher precedence

**Comment by flaf** [comment]
Thanks for you for your answer @alikins. Indeed, I'm looking to know the ordering the files `group_vars/*` are loaded in... to be able to predict the resulting var precedence because the documentation doesn't seem to explain this point. Am I wrong?

Furthermore, the link to [helpers.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/helpers.py) doesn't seem to math with the example 1 in my first message, no?

I hope my ASCII picture is clear but here is the code:

```sh
~$ cat inventories/flaf/hosts
[group_p2:children]
group_b

[group_a]
localhost

[group_b]
localhost


~$ cat inventories/flaf/group_vars/group_a.yml 
---
var: from-group_a


~$ cat inventories/flaf/group_vars/group_b.yml # empty
---


~$ cat inventories/flaf/group_vars/group_p2.yml 
---
var: from-group_p2


~$ cat playbooks/tests/quick-test.yml 
---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: 'value of var => {{ var }}'


~$ ansible-playbook -i inventories/flaf/hosts playbooks/tests/quick-test.yml 

PLAY [localhost] *******************************************

TASK [debug] **********************************************
ok: [localhost] => {
    "msg": "value of var => from-group_p2"
}

PLAY RECAP ***********************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

According to the link, the value should be `"from-group_a"`, no?

**Comment by Vladimir-csp** [comment]
I've stumbled upon unpredictable behavior when merging parallel group hierarchies. IMHO, `ansible_group_priority` mechanism should be tuned a bit.

For example, suppose we have a host that is a member of the following groups:

- os-Linux
  - distr-Debian
    - distr-Debian-9
- frontend-servers

So, there are: a hierarchy of distributions and a host group. From my testing it appears that any hierarchy takes precedence over any single group: a variable assigned and reassigned anywhere in the above 'os-' or 'distr-' groups will take precedence over variable in 'frontend-servers', even if `ansible_group_priority` is set to higher value in 'frontend-servers'.

I propose the following changes:
1. `ansible_group_priority` should either default to 50 or support negative values (so you could set lower priority than default).
2. groups and group hierarchies should be treated as siblings.
3. `ansible_group_priority` in a root group of the hierarchy defines priority of the whole underlying hierarchy to the outside world.

With these changes the following would be possible: Suppose we add `ansible_group_priority: -10` somewhere in 'os-Linux', the whole underlying tree would get this priority, and any single host group or other parallel heirarchy with default priority will take precedence. This would be predictable and flexible. It would be possible to compose some low-priority and hight-priority group trees.

example:

- os-Linux (`a_g_p: -10`, this whole tree has priority -10)
  - distr-Debian
    - distr-Debian-9
- frontend-servers (this var or potentially a tree has default priority 1)

In this example values set in 'distr-Debian-9' would win over 'distr-Debian' and 'os-Linux', because it is a hierarchy. But values set in 'frontend-servers' would win over 'distr-Debian-9',  'distr-Debian' and 'os-Linux', because 'frontend-servers' has higher priority than 'os-Linux' tree

**Comment by sivel** [comment]
There are 2 "forces" at play here.

1. File/dir listing order which will happen alphanumerically
1. Variable precedence

Child groups, as they are more specific, have a higher precedence than the parent.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Vladimir-csp** [comment]
`ansible_group_priority` mechanism needs some tuning, why was the bug closed?
