### ISSUE TITLE
apt module says ok when package initialy ko

### ISSUE THREAD

**Issue by n0vember** [ansible/ansible#3421]
I was installing a package using ansible on debian system. Install went wrong and package was in an intermediate state : 
 dpkg -l | grep -v ^ii
 iU  haproxy-mbs                        1.4.23-mbs1                  haproxy 1.4.23 - MBS
apt module returns failed state, which is good : 
 tst-ha01                   : ok=6    changed=2    unreachable=0    failed=1

When I reran my playbook, I got this : 
 tst-ha01                   : ok=7    changed=2    unreachable=0    failed=0  
But package is still in the same state (iU)

ansible 1.2-2 is installed on archlinux, installing packages on debian 6 (squeeze).

**Comment by mpdehaan** [comment]
Sounds like dpkg says it is installed, so nothing we can do here, given your dpkg -i result ?

**Comment by n0vember** [comment]
As said, dpkg -l shows package as iU. This is because installation was not ended by first pass. This was a normal behaviour because it requested input that was not given. Second pass didn't do best, left package in iU state, not ii, but said ok. I'm trying to reproduce and will post result.

**Comment by srgvg** [comment]
Did a couple of checks, basically the problem seems that while `dpkg -l` shows package as `iU` (marked for Install and Unpackad, but not installed), yet apt.cache.Package.is_installed returns True. 

apt.Package is quite high level and doesn't have any attributes to check the state of the package in detail; apt_pkg has some lower level stuff, but not sure if that would be easily patched here.

Either way, seems a valid bug to me.

**Comment by jimi-c** [comment]
The above patch fixes the issue in my testing, however since we're getting close to the 1.3 release I'd like some additional testing on this before merging it in to make sure nothing is broken by the new checks.

My testing:

<pre>
# half installed the haproxy .deb file, downloaded locally
$ dpkg --unpack haproxy_1.4.18-0ubuntu1.2_amd64.deb 
Selecting previously unselected package haproxy.
(Reading database ... 67650 files and directories currently installed.)
Unpacking haproxy (from haproxy_1.4.18-0ubuntu1.2_amd64.deb) ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
$ dpkg -l | grep haproxy
iU  haproxy                          1.4.18-0ubuntu1.2          fast and reliable load balancing reverse proxy
# from my ansible master:
$ ansible -m apt -a "name=haproxy install_recommends=yes force=yes" ubuntu
x.x.x.x | success >> {
    "changed": true
}
# back on the ubuntu system:
$ dpkg -l | grep haproxy
ii  haproxy                          1.4.18-0ubuntu1.2          fast and reliable load balancing reverse proxy
</pre>

**Comment by srgvg** [comment]
+1
