### ISSUE TITLE
License file should be named LICENSE instead of COPYING

### ISSUE THREAD

**Issue by triztian** [ansible/ansible#3429]
The title is self explanatory, in most python projects the license file is named LICENSE, for example [Flask](https://github.com/mitsuhiko/flask), [Django](https://github.com/django/django), [Riak Python Client](https://github.com/basho/riak-python-client) or [mashape-oauth](https://github.com/Mashape/mashape-oauth) to name a few. It took me a while to actualy find the license as I was searching for the file name **LICENSE**

**Comment by mpdehaan** [comment]
Thanks for the comment.

This is pretty common practice for GPL applications, see http://www.gnu.org/licenses/gpl-howto.html

we'll stick with what gnu.org says here I think.

**Comment by rdickert** [comment]
@mpdehaan  This was confusing to me as well, and I found this issue because I was about to post an issue myself. Many github users will not be familiar with the gnu.org convention and will expect you to follow [github's recommendation to use LICENSE](https://help.github.com/articles/open-source-licensing#where-does-the-license-live-on-my-repository). I'm not saying you need to do that, but it might be a good idea to mention the license in the README as well - that's the first place I looked when I didn't see a LICENSE file. Thanks for the excellent work on Ansible!

**Comment by bcoca** [comment]
symlink?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
