### ISSUE TITLE
Slackware packaging support

### ISSUE THREAD

**Issue by orthecreedence** [ansible/ansible#3437]
I use Slack for all my servers, would love to have official packaging options for [slackpkg](http://www.slackpkg.org/documentation.html) and [slapt-get](http://software.jaos.org/#slapt-get) package managers.

I'd add myself, but don't know Python at all (although I might take a crack at it in the next few days).

Please let me know if you need any additional info.

**Comment by mpdehaan** [comment]
That sounds great, but it's not something I'm personally going to work on, and I have a practice of not leaving these tickets open in github because github is absolutely terrible at organizing tickets in it's github tracker -- it really helps to keep the queue small to things we're actively working on.

I would suggest asking someone on the mailing list if you would like to add something, and someone may feel like adding one!

**Comment by orthecreedence** [comment]
Thanks for the response! I'll take a look this weekend and see if I can whip something up.
