### ISSUE TITLE
ssh connection and Arch: "failed to transfer file to /ping" with 1.2.1

### ISSUE THREAD

**Issue by alanorth** [ansible/ansible#3446]
I've updated to Ansible 1.2.1 and now I'm getting the following error::

```
$ ansible -vvv -m ping 192.168.5.31 
<192.168.5.31> ESTABLISH CONNECTION FOR USER: aorth
<192.168.5.31> EXEC ['ssh', '-tt', '-q', '#-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.5.31', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373025620.14-196824766271523 && chmod a+rx $HOME/.ansible/tmp/ansible-1373025620.14-196824766271523 && echo $HOME/.ansible/tmp/ansible-1373025620.14-196824766271523'"]
<192.168.5.31> REMOTE_MODULE ping 
<192.168.5.31> PUT /tmp/tmpqYmlm1 TO /ping
192.168.5.31 | FAILED => failed to transfer file to /ping:

usage: sftp [-1246Cpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
          [-D sftp_server_path] [-F ssh_config] [-i identity_file] [-l limit]
          [-o ssh_option] [-P port] [-R num_requests] [-S program]
          [-s subsystem | sftp_server] host
       sftp [user@]host[:file ...]
       sftp [user@]host[:dir[/]]
       sftp -b batchfile [user@]host
```

If I revert the package to 1.2 the same command is successful.  Also, if I force paramiko as the transport it works fine:

```
$ ansible -vvv -m ping 192.168.5.31 -c paramiko
<192.168.5.31> ESTABLISH CONNECTION FOR USER: aorth on PORT 22 TO 192.168.5.31
<192.168.5.31> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373025927.04-271368898897049 && chmod a+rx $HOME/.ansible/tmp/ansible-1373025927.04-271368898897049 && echo $HOME/.ansible/tmp/ansible-1373025927.04-271368898897049'
<192.168.5.31> REMOTE_MODULE ping 
<192.168.5.31> PUT /tmp/tmpV6eZv5 TO /home/aorth/.ansible/tmp/ansible-1373025927.04-271368898897049/ping
<192.168.5.31> EXEC /bin/sh -c '/usr/bin/python /home/aorth/.ansible/tmp/ansible-1373025927.04-271368898897049/ping; rm -rf /home/aorth/.ansible/tmp/ansible-1373025927.04-271368898897049/ >/dev/null 2>&1'
192.168.5.31 | success >> {
    "changed": false, 
    "ping": "pong"
}
```

Changing `remote_tmp` to `/tmp` does nothing.  It seems the `/ping` path is, for some reason, not relative to the `remote_tmp` when using `smart` or `ssh` transports.

Local OS: Arch Linux (ansible package from [AUR](https://aur.archlinux.org/packages/ansible/))
Remote OS: CentOS 6.4

**Comment by mpdehaan** [comment]
I am wondering if this is not so much a regression as a result of the new default connection type being 'smart' versus paramiko and you having sftp disabled.  Ansible will now pick "SSH" as a connection type if you can supprot ControlPersist, where you were using paramiko before.

This may not be an accurate theory, however :)

Take a look at ansible.cfg and add

[ssh_connection]
scp_if_ssh=True

And you should use scp instead of SFTP to transfer files.

My other comment

I have not seen the remote temp issue but it may be related to your user not having a "$HOME" environment variable in some way that can expand.

I do see the mkdir here:

 "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373025620.14-196824766271523

And am not having any problems on my systems.  (Ubuntu 12.04, CentOS 6, etc)

If you can help dig and try to figure out what is going on that would be great!

**Comment by srgvg** [comment]
I can reproduce this with this:

``` bash
. hacking/env-setup
export ANSIBLE_CONFIG=~/src/ansible/examples/ansible.cfg ; ansible -vvv -m ping all -i antares.ginsys.net,
```

**Comment by mpdehaan** [comment]
Can you help figure out why possibly?  I can't here.

**Comment by srgvg** [comment]
bad comment: https://github.com/ansible/ansible/blob/release1.2.1/examples/ansible.cfg#L105

**Comment by mpdehaan** [comment]
Ok, so I'm updating the tarball on PyPi shortly.

Fix is to remove that command in front of SSH args and instead comment out ssh_args entirely, or set it to what you want instead.  (Those shown are the defaults Ansible will try to use).

Thanks for the report @alanorth and thanks for tracking it down @sergevanginderachter !
