### ISSUE TITLE
Docs broken link

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3448]
from email

I just wanted to let you know that on the page http://www.ansibleworks.com/docs/gettingstarted.html there is a broken link pointing to http://www.ansibleworks.com/docs/gettingstarted.html/examples.html, which should be pointing to http://www.ansibleworks.com/docs/examples.html

**Comment by arnehormann** [comment]
I wanted to post the same issue.
This error pattern seems to concern all links from gettingstarted to pages in /docs/,  I didn't spot broken links on the other pages. The links in the rst files look the same, though. Maybe it's a redirect in the server config?

**Comment by tgerla** [comment]
Hi,

I don't see the broken links on gettingstarted.html now. Can you verify that this is still an issue? If you see a broken link, can you let us know exactly where in the page it is? I'm having trouble finding any.

Thanks!

**Comment by arnehormann** [comment]
Sorry - I had another look, it's not (entirely) your fault.
I don't know where I came from, but I followed a link to [/docs/gettingstarted.html/](http://www.ansibleworks.com/docs/gettingstarted.html/) instead of [/docs/gettingstarted.html](http://www.ansibleworks.com/docs/gettingstarted.html). If you follow the first link, the page is shown but relative linking is broken.

**Comment by tgerla** [comment]
Thanks! That helps.

**Comment by mpdehaan** [comment]
Closing this, we will have to wait for Google for things to pick up, but should be fixed soon
