### ISSUE TITLE
import_tasks inside include_tasks generates confusing error

### ISSUE THREAD

**Issue by freeseacher** [ansible/ansible#35048]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.4.2.0 - v2.4.3.0-0.5.rc2
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
wrong error generated if import_tasks found in include_tasks file

##### STEPS TO REPRODUCE

```yaml
- include_tasks: "os/{{ ansible_distribution }}/main.yml"
...
inside
...
- import_tasks: "firewall.yml"

```

##### EXPECTED RESULTS
import error/lint error/any error

##### ACTUAL RESULTS
```
fatal: [node1]: FAILED! => {
    "reason": "'ansible_distribution' is undefined"
}
```

**Comment by atruskie** [comment]
I just want to signal boost this because it was a frustrating few hours of my life to waste.

I had three files:

**main.yml**
```
...
include: "{{ baw_app_role_path }}/tasks/childA.yml
include: "{{ baw_app_role_path }}/tasks/childB.yml
...
```

**childA**: just a generic bunch of tasks that worked

**childB**:  more generic tasks that worked, but also a new `import_tasks` statement:
```
...
- name: IMPORT | Install the SQLite3 gem
  import_tasks: sqlite3_gem.yml
  tags: [ "sqlite3" ]
...
```

This was all working before I added a new import to _childB_. After including the new import, the role would fail with:

```
fatal: [host1]: FAILED! => {"reason": "{{ baw_app_role_path }}/tasks/childB.yml: 'baw_app_role_path' is undefined"}
fatal: [host2]: FAILED! => {"reason": "{{ baw_app_role_path }}/tasks/childB.yml: 'baw_app_role_path' is undefined"}
```

This:
- made no sense, since the import of _childA_ already worked, using that very variable
- ansible's default vars also were undefined (like `role_path`)
- Ansible's playbook debugger, which I had on, did not even activate

When I switched from `import_tasks` in _childB_ to `include` the playbook ran without a problem.

**Comment by Vladimir-csp** [comment]
I confirm this. `include_tasks` fails with `'ansible_distribution' is undefined` error

**Comment by sivel** [comment]
Closing as a duplicate of https://github.com/ansible/ansible/issues/34665
