### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by ba47-development** [ansible/ansible#35188]
Hello,

probably a very simple issue, but I don't find a helpful solution. So, hopefully you can point me in the right direction. Thanks in advance.

I've written a Python module **test_main.py** that imports another self written Python module **my_module.py**, like this:
```
#!/usr/bin/python
import json
from ansible.module_utils.basic import AnsibleModule
import my_module
[...]
```

I'm starting the playbook:
> ansible-playbook -vvvv test_main.yml

test-main.yml looks like this:
```
---
- name: Execute Python
  hosts: localhost

  tasks:
  - name: Python Test
    test_main:
      title:  Parameter
```

However, after start I the the error message, that the import can't be found:
> Traceback (most recent call last):
>   File "/tmp/ansible_GagMoc/ansible_module_test_main.py", line 4, in <module>
>     import my_module
> ImportError: No module named my_module

```
# ansible-playbook --version
ansible-playbook 2.4.2.0
  config file = /usr/share/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

All code is located in **/usr/share/ansible/**, which is the configured module path.

Any idea why my_module can't be imported?

**Comment by sivel** [comment]
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

Thank you once again for this and your interest in Ansible!

**Comment by ba47-development** [comment]
It is _unsupported_ to call to write and extend by own code? That's not following the documentation.

Extending Ansible may often be necessary to include it to existing environments. My problem is, that Python doesn't find its imports, if started from **ansible-playbook**.


The solution was to add a Python search path **PYTHONPATH**. This way the modules were found.

**Comment by bcoca** [comment]
@RealFlachmann the module is executed on the target, your other module is not there.

Ansible has a special facility to copy shared code for modules to use on the target, but that code must live in `module_utils`.
