### ISSUE TITLE
inventory string variables can get converted to lists

### ISSUE THREAD

**Issue by velotraveler** [ansible/ansible#35254]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/eravin/.ansible.cfg
  configured module search path = [u'/home/eravin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /bb/ndismdns/ansible/lib/python2.7/site-packages/ansible
  executable location = /bb/ndismdns/ansible/bin/ansible
  python version = 2.7.8 (default, Apr 29 2016, 09:18:14) [GCC 4.4.7 20120313 (Red Hat 4.4.7-9)]

```

##### CONFIGURATION
no settings changes from default

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 6.6 (Santiago)

##### SUMMARY
Host-specific variables in inventory that are specified as quoted strings can get turned into lists

##### STEPS TO REPRODUCE
$ cat inventory 
[testers]
test1 val="02,06,10,16"
test2 val="00,04,08,12"

$ cat testme.yml

```yaml
---

- hosts: testers
  gather_facts: no

  tasks:

  - debug:
      msg: "{{ val }}"

```

##### EXPECTED RESULTS
The comma-separated list of numbers in the two inventory variables should both be displayed as strings.

##### ACTUAL RESULTS
One of the string variables is interpreted as a list. I haven't been able to figure out any pattern as to when this happens, it looks it's got something to do with strings that are comma-separated lists of numbers.  Our original case had variables for host-specific cron settings, half of them were parsed as strings and the other half were parsed as lists.

$ ansible-playbook -i inventory testme.yml
```
PLAY [testers] *****************************************************************

TASK [debug] *******************************************************************
ok: [test1] => {
    "msg": [
        2, 
        6, 
        10, 
        16
    ]
}
ok: [test2] => {
    "msg": "00,04,08,12"
}

PLAY RECAP *********************************************************************
test1                      : ok=1    changed=0    unreachable=0    failed=0   
test2                      : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by velotraveler** [comment]
Workaround:

```
$ cat inventory-workaround 
[testers]
# test1 val="02,06,10,16"
test1 val="{{ ['02','06','10','16'] | join(',') }}"
test2 val="00,04,08,12"

$ ansible-playbook -i inventory-workaround  testme.yml 

PLAY [testers] *****************************************************************

TASK [debug] *******************************************************************
ok: [test1] => {
    "msg": "02,06,10,16"
}
ok: [test2] => {
    "msg": "00,04,08,12"
}

PLAY RECAP *********************************************************************
test1                      : ok=1    changed=0    unreachable=0    failed=0   
test2                      : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * All ini inventory variables are processed by the [literal_eval](https://docs.python.org/2/library/ast.html#ast.literal_eval) function which is outside of Ansible
   * It is this library that is interpreting `02,06,10,16` as a tuple/list and returning that back to Ansible
   * It seems like Python 3 is not displaying this behaviour which is not surprising considering the differences in string types between 2 and 3
   * Out docs state;

> Values passed in using the key=value syntax are interpreted as Python literal structure (strings, numbers, tuples, lists, dicts, booleans, None), alternatively as string. For example var=FALSE would create a string equal to ‘FALSE’. Do not rely on types set during definition, always make sure you specify type with a filter when needed when consuming the variable.

https://docs.ansible.com/ansible/devel/plugins/inventory/ini.html

I would recommend you use the [yaml inventory plugin](https://docs.ansible.com/ansible/devel/plugins/inventory/yaml.html), it is a bit more verbose but you have finer control over the types when defining variables, in your example, the inventory would look like you can do

```
testers:
  hosts:
    test1:
      val: "02,06,10,16"
    test2:
      val: "00,04,08,12"
```

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
