### ISSUE TITLE
Ansible connection with Window hosts machine error

### ISSUE THREAD

**Issue by ajit2678** [ansible/ansible#35899]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ajit2678** [comment]
```
[WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File "/usr/lib/python2.7/site-
packages/ansible/plugins/connection/winrm.py", line 276, in _winrm_exec     self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
eof=is_last)   File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 256, in _winrm_send_input
protocol.send_message(xmltodict.unparse(rq))   File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 256, in send_message     raise
WinRMOperationTimeoutError() WinRMOperationTimeoutError

192.168.9.145 | FAILED! => {
    "msg": "winrm send_input failed"
}
```
this error is am getting when i am ping to remote windows machine 
plz help me 

This script i have already run on windows 10 machine  for enable the winrm services
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

**Comment by alexray92** [comment]
I have the same problem when using kerberos.  I had been using ntlm, which works fine, but is less secure.  I tried updating pywinrm to the latest version and am on ansible 2.4.

**Comment by alexray92** [comment]
I tried increasing operation timeout to 120 seconds and read timeout to 150 seconds for winrm, but that didn't do anything...  Also tried manually changing remote tmp to C:\\Users\\rundeckuser\\AppData\\Local\\Temp, which I had to do for NTLM, to no effect:

```
# ansible [host] -m ping -vvvvv
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/six/__init__.py
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/ping.py
<[host]> ESTABLISH WINRM CONNECTION FOR USER: [user]@[domain] on PORT 5986 TO [host]
creating Kerberos CC at /tmp/tmpcezfeR
calling kinit for principal [user]@[domain]
kinit succeeded for principal [user]@[domain]
<[host]> WINRM CONNECT: transport=kerberos endpoint=https://[host]:5986/wsman
/usr/local/lib/python2.7/dist-packages/winrm/transport.py:299: UserWarning: Function <unbound method HTTPKerberosAuth.__init__> does not contain optional arg send_cbt, check installed version with pip list
  % (str(function), name))
<[host]> WINRM OPEN SHELL: 906A8F23-F0A9-4FCC-974D-39815C5CDB93
EXEC (via pipeline wrapper)
<[host]> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-']
 [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 276, in _winrm_exec     self._winrm_send_input(self.protocol,
self.shell_id, command_id, data, eof=is_last)   File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 256, in _winrm_send_input     protocol.send_message(xmltodict.unparse(rq))   File
"/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 256, in send_message     raise WinRMOperationTimeoutError() WinRMOperationTimeoutError

<[host]> WINRM CLOSE SHELL: 906A8F23-F0A9-4FCC-974D-39815C5CDB93
[host] | FAILED! => {
    "msg": "winrm send_input failed"
}
```

**Comment by alexray92** [comment]
I enabled additional winrm logging and got these:

```
An error was encountered while processing an operation.
Error Code: 2150858793
Error String:<f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858793" Machine="localhost"><f:Message>The WS-Management service cannot complete the operation within the time specified in OperationTimeout.  </f:Message></f:WSManFault>

An error was encountered while processing an operation.
Error Code: 1460
Error String:<f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="1460" Machine="windows-host"><f:Message><f:ProviderFault provider="Shell cmd plugin" path="%systemroot%\system32\winrscmd.dll">This operation returned because the timeout period expired. </f:ProviderFault></f:Message></f:WSManFault>
```
User [domain]\[my rundeck user] authenticated successfully using Kerberos authentication

**Comment by alexray92** [comment]
ajit2678:

Were you just doing like 

``` 
ansible windows -m ping
```

I figured it out - the 'ping' module seems to rely on python, which isn't on the Windows server, which manifests as a timeout error.  Try using "win_ping" instead, it worked for me!

**Comment by ajit2678** [comment]
ok i will try to ping with "win_ping"

**Comment by ajit2678** [comment]
thanks alexray92  its works for me

**Comment by ajit2678** [comment]
But when i am trying to connect with using CREDSSP i am getting this error

192.168.9.145 | UNREACHABLE! => {
    "changed": false, 
    "msg": "credssp: 'module' object has no attribute 'TLSv1_2_METHOD'", 
    "unreachable": true
}


plz help me for this also..

**Comment by ajit2678** [comment]
Hey if i have to ping both the clients windows & Linux , So what Ping command i should use ??

**Comment by alexray92** [comment]
I would advise to use Kerberos instead of CREDSSP unless you are really needing the double-hop functionality, because it's considered less secure.

That said, the error might be caused by your Python library for CredSSP not supporting TLS 1.2.  After making sure all your system packages are updated, maybe try updating the Python libraries (I think like "pip install pywinrm pywinrm[credssp] requests-credssp --upgrade").

As far as pinging multiple systems on linux and windows goes, I'm not sure there is one module to do that, though I'm pretty new to ansible.  If this is just a test, you could do a loop on two tasks, over the list of hosts, differentiating'when' the OS fact about the host indicate linux vs windows in order to do the ping or win_ping.

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!


The error around module object has no attribute is due to the pyOpenSSL library that requests-credssp uses is too old and is not supported (usual for the builtin system versions). There is an explicit check to use TLS 1.2 as the previous versions are considered insecure and somewhat incompatible with openssl/schannel. You need to upgrade most of these packages to get CredSSP working.

**Comment by ajit2678** [comment]
OK Thanks Maan for your suggestion

**Comment by isaacegglestone** [comment]
Man we really need to put in a feature request to have it check OS type on destination host and if your using ping vs win_ping to throw a warning. I knew this and simply forgot, didn't know it would barf so terribly on such a silly problem and racked my brain for hours over it.
