### ISSUE TITLE
Ansible should expose current verbosity level to a variable accessible from playbook

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#36170]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Currently is impossible to check current verbosity level from inside the playbook and users may want to use this in order to modify behaviour, like enabling some tasks based on its value.

If ansible would allow us to access verbosity level we could do something like:
```
    shell: echo "yeah!"
    when: "{{ verbosity > 0 }}"
```

**Comment by MonsieurCellophane** [comment]
Unless a way is also provided to mute skipped tasks (which AFAIK is still missing), this would not  make  much good - at verbosity==0 you would not see "yeah", but you'd still see the "skipped" notice.

**Comment by bcoca** [comment]
@MonsieurCellophane http://docs.ansible.com/ansible/devel/plugins/callback/skippy.html

**Comment by queria** [comment]
@MonsieurCellophane yes, while for 'yeah' use case it may not be that much good without skippy,

but imagine there is not just one word, but whole log or output of get-status-overview commands etc, 
spanning few dozen+ lines ... in which case one skip is better price to pay,

... instead of having to choose between '_always use increased verbosity_'  vs '_double printing in case of increased verbosity_'
e.g. just `- shell` or any task with verbosity driven *hidden* output  vs `- shell: register;  - debug: var:`

while with this issue addressed, second approach could be taken while eliminating double printing by having condition for more verbose run to just do skip as it was likely already printed above

**Comment by UnitedMarsupials-zz** [comment]
Seconded! I already check `ansible_check_mode` to add the `--dry-run` (or some equivalent) to various commands executed by tasks. I'd like to _also_ be able to add `-v` (or equivalent), if the entire ansible is running with increased verbosity.

For example:
```yaml
- name: Populate directories
  command: >-
    rsync
    {% if ansible_check_mode %}--dry-run{% endif %}
    {% if ansible_verbosity > 0 %}-v{% endif %}
    {% if ansible_verbosity > 1 %}-v{% endif %}
    --archive
    --delay-updates
    ...
  check_mode: ansible_check_mode
```

**Comment by swkarr** [comment]
I agree.
Other use cases include when your validation or debug code requires inspection tasks unnecessary for normal playbook execution.  For example calling a REST API to gather facts.
