### ISSUE TITLE
How can I start two or more services using systemd when I execute ansible-playbook

### ISSUE THREAD

**Issue by kevin-hao** [ansible/ansible#36361]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by webknjaz** [comment]
Hello Kevin,

Please note that GitHub Issues are used for working on ansible itself and if you need to report some bug or request a feature you're expected to fill in whole issue template, so that the bot can recognise what it's about and tag appropriate people.

The best way of asking question about using ansible is to do this on [ansible-project mailing list](http://groups.google.com/group/ansible-project) as advised in [docs](https://docs.ansible.com/ansible/latest/community.html#i-ve-got-a-question).

But since you already posted the question, here's a hint for you: you're seeking to combine [loops](https://docs.ansible.com/ansible/latest/playbooks_loops.html) and [systemd](https://docs.ansible.com/ansible/latest/systemd_module.html). All information you need may be found in docs.

Have a nice day :)
