### ISSUE TITLE
Add a flag to force coloring output

### ISSUE THREAD

**Issue by such** [ansible/ansible#3641]
Would it be possible to add a flag that forces the coloring of the output ?

**Comment by mpdehaan** [comment]
We have ANSIBLE_NOCOLOR as an environment variable for turning it off, can I ask why you need to turn it on?

I'd prefer an environment variable and not a flag, just because I like to control flag sprawl.

BTW, since this is more of a question and not a bug/feature, can you post to the mailing list instead?

Thanks!
