### ISSUE TITLE
Programmatically execute Ansible with a dynamic inventory.

### ISSUE THREAD

**Issue by unacceptable** [ansible/ansible#36594]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible.playbook

##### ANSIBLE VERSION
```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
EL 7.x

##### SUMMARY
How come we have to specify a file for an ansible inventory when executing ansible programmatically?  I believe that it should be allowed to pass in a python variable containing valid YAML, INI, or JSON.

This has been bugging me since I first noticed this:

http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html

Am I missing something obvious?

I know that I can create a `NamedTemporaryFile` from `tempfile` as a workaround but this seems like a bit of a hack.

**Comment by sivel** [comment]
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
Just create an inventory plugin that supports this
