### ISSUE TITLE
host processing order

### ISSUE THREAD

**Issue by bj28** [ansible/ansible#3708]
It would be nice if ansible processes the hosts in order:

https://groups.google.com/forum/#!topic/ansible-project/QzwTjxDsQ50

**Comment by mpdehaan** [comment]
May want this to be configurable in the INI file.

(For database or external inventory hosts the order is not so meaningful)

**Comment by bcoca** [comment]
I we as thinking a per play sort order either hosts: "group1:group2| sort"
(numeric,reverse,random)

or

  hosts: "group1:group2"

  sorted: alpha,numeric,reverse,random,origin (default and as received from
inventory)

**Comment by mpdehaan** [comment]
Something like the sorted keyword seems most Ansible-like, rather than introducing more arcane things.

Currently host order is not something we record on the object, and again, DB order would not make much sense.

I am going to close this one because you could solve it with a group that contained a headnode group and an othernodes group, and that would still work with databases.
