### ISSUE TITLE
Handler is skipped when notified from included role

### ISSUE THREAD

**Issue by XooR** [ansible/ansible#37512]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible

##### ANSIBLE VERSION

```
ansible 2.4.4 (stable-2.4 02e591746c) last updated 2018/03/16 11:19:16 (GMT +200)
```

##### CONFIGURATION

```
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/user/.vault_pass
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Ubuntu 17.10

##### SUMMARY

If I set role as dependency and skip it initially (with `when: False`) and use `include_role` afterwards handlers are skipped in included role with reason that condition is `False`.

I would expect that handler is called or that there is a way to set dependency on role so it's not executed and later on we can call `include_role`.

##### STEPS TO REPRODUCE

play.yml
```yaml
---
- hosts: localhost
  roles:
    - master
```

roles/master/tasks/main.yml
```yaml
---
- name: 'Include slave role'
  include_role:
    name: slave
```

roles/master/meta/main.yml
```yaml
---
dependencies:
    - name: slave
      when: False
```

roles/slave/tasks/main.yml
```yaml
---
- name: Changed command
  command: /bin/true
  notify: handler execute
```

roles/slave/handlers/main.yml
```yaml
---
- name: handler execute
  command: /bin/echo executed
```

##### EXPECTED RESULTS

Expected that handler would execute.

##### ACTUAL RESULTS

```
# ansible-playbook play.yml  -v

Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [slave : Changed command] **************************************************************************************************************************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [master : Include slave role] **********************************************************************************************************************************************************

TASK [slave : Changed command] **************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.001338", "end": "2018-03-16 12:13:04.733996", "failed": false, "rc": 0, "start": "2018-03-16 12:13:04.732658", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [slave : handler execute] ***************************************************************************************************************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by alikins** [comment]
@XooR Was this working previous to 2.4.4? If so, what versions?

**Comment by XooR** [comment]
Not to my knowledge. It also doesn't work in new Ansible 2.5.0.
Way it works now is not something that I would expect.

**Comment by Rylon** [comment]
I have just encountered this issue too - my particular use case is as follows:

* I have a custom role which depends on some third-party roles, which are defined in the role meta under `dependencies`.

* The custom role is in a separate Git repo so it can be shared between several Ansible projects.

* The custom role is defined in a `requirements.yml` and installed from Git using `ansible-galaxy`, which also installs the third-party roles at the same time (which is what I want).

When I include the custom role in a playbook, the third-party roles are added to the play *before* the custom role. In this case, we want to include them after our custom role has run. In order to change that behaviour, we tried adding `when: false` to the meta dependency, which stops it being added to the play until we explicitly do so with `include_role`, however we then encounter the reported issue where any notified handlers are skipped.

**Comment by chrisruffalo** [comment]
This might be documented better but I find the lines 
> You can conditionally execute a role. **This is not generally recommended** with the classic syntax, but is common when using import_role or include_role

To be pretty telling. (Emphasis mine.) Source [here](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html).

So if I read this right they don't want the meta dependencies to be used with conditionals (probably for this reason) but instead to mange conditionals with import_ or include_.

This is because of
> When roles are defined in the classic manner, they are treated as static imports and processed during playbook parsing.
From [here](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html#role-dependencies).

And

> Most keyworkds, loops and conditionals will not be applied to this action, but to the imported tasks instead. If you want the opposite behaviour, use import_role instead.

From [here](https://docs.ansible.com/ansible/2.4/import_role_module.html).

So what is happening is the classic syntax is applying to the imported items. I believe the documentation ("use import_role instead") means use "include_role instead".

Short version: the conditional is being applied to the dependency/imported items and not the entire dependency as it would be with adding include_roles if you used it from the main task.

new roles/master/main.yml:
```yaml
---
- name: 'Include slave role'
  include_role:
    name: slave
  when: False

- name: 'Include slave role'
  include_role:
    name: slave
```

output:
```bash
PLAY [localhost] ****************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [include_role : slave] *****************************************************************************************************************************************************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [include_role : slave] *****************************************************************************************************************************************************************************************

TASK [slave : Changed command] **************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.001445", "end": "2018-10-02 15:50:29.947772", "rc": 0, "start": "2018-10-02 15:50:29.946327", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [slave : handler execute] ***************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["/bin/echo", "executed"], "delta": "0:00:00.001617", "end": "2018-10-02 15:50:30.136223", "rc": 0, "start": "2018-10-02 15:50:30.134606", "stderr": "", "stderr_lines": [], "stdout": "executed", "stdout_lines": ["executed"]}

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0  
```
As a side note this bit me with tags and import_tasks vs include_tasks.

**Comment by mcg** [comment]
@chrisruffalo Your suggested changes don't fix the issue, at lease for me on `ansible 2.6.4`. The handler in the included slave role is still skipped.

```
RUNNING HANDLER [slave : handler execute] ***********************************************************************************************************************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
```

But reading your comment, I'm not sure you're going after the issue. We want to use meta dependencies but only have the dependent role available, not executed until we `include_role`. 
Using `when: false` on meta for the dependent role does this, however it causes the dependent role's handlers to be skipped.

**Comment by chrisruffalo** [comment]
To get what I did to work you have to remove the dependency in the roles/master/meta/main.yml altogether. I don't know if I mentioned that well enough. I'm using Ansible 2.6.4 as well.

I’m trying to explain why having the `when: false` on the dependency makes
it skipped no matter what. (Because it’s included statically and not
dynamically and the conditional is applied to all included items.)

I’m not sure why you need the meta dependency (with `when: false`) to do
what you’re trying to do.

**Comment by mcg** [comment]
AFAIK We want to control role run order/placement and also have dependency resolution work.

**Comment by chrisruffalo** [comment]
I’m not sure about dependency resolution but you can control run order
explicitly with import_role and include_role. The way that the role
dependency works now is an implicit import_role.

**Comment by mcg** [comment]
Correct. import/include_role does do what we need as far as run order, but without the dependency listed in meta, it will not be included and the play will fail. The only workaround I know currently, is to not use meta and list every dependency from every included role(and any role(s) included recursively) in the play's requirements.yml. This is... not great.

**Comment by chrisruffalo** [comment]
I think I need a larger example so I can see the behavior. On Ansible 2.6.4
removing the `meta/main.yml ` and using just include_role works for me. I
would expect that each role in turn would use include_role for the roles it
needs.

Maybe we could see something like that?

**Comment by mcg** [comment]
include_role works in this example because the slave role exists in `roles/`. You'll need role(s) that are requested with galaxy to see the dependency tree fail.

**Comment by chrisruffalo** [comment]
Ah! I didn’t get that from the example. I’ll look at it too. Hopefully we
generate enough noise to get someone else to pop in.

**Comment by Rylon** [comment]
Hi @chrisruffalo in this case @mcg is correct when he says:

> AFAIK We want to control role run order/placement and also have dependency resolution work.

Let me try to explain the use case in more detail.

We want to be able to install all required roles, and any dependencies those roles specify in their `meta`. But the issue is that a dependent role specified via another role's `meta` is automatically included in the play too, *before* the role that required it. In some cases, this is not desired, and we want to be able to control the order of every role the play (via `include_role`).

The issue is essentially arising from the fact that the role `meta` is serving two purposes:

1. Defining other roles that a given role requires, so that `ansible-galaxy` can install all the required roles.
2. Defining additional roles to be included into a given play, when a parent role is present.

We need to be able to separate those two responsibilities, or at least to control the include order more precisely.

Hope that helps!

**Comment by XooR** [comment]
We solved our problem that we agreed at company level to have some util roles which are included by other roles and all teams should have in their Ansible repos. For util role would be one that installs Prometheus exporter and registers to Consul to be auto-discovered. We don't have that many roles which are included by other roles 3 of them I think.
In future they should implement a way to specify requirements without executing it, you may vote on issue: https://github.com/ansible/proposals/issues/57

**Comment by mcg** [comment]
I find myself having to work around this again today. Any movement at all on this?

**Comment by mkrizek** [comment]
The example in the description should be fixed in https://github.com/ansible/ansible/pull/49249. See also https://github.com/ansible/ansible/pull/49322 and discussion in https://github.com/ansible/ansible/pull/41968.

**Comment by mkrizek** [comment]
Closing as per above.

**Comment by mcg** [comment]
The fixes talk about "handlers of the same name". Do they also fix handlers from included roles, just not firing, as this bug references?
