### ISSUE TITLE
with_subelements lookup plugin (or similar)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3752]
The question comes up how to distribute SSH keys to different users.

In this case, suppose we have:

```
users:
   - name:  xyz
     ssh_keys: [ /path/to/x, y, z ]
   - name: abc
     ssh_keys: [ xx, yy ]
```

We might want to use the authorized_key module in a with_items loop, so it would be nice to say:

```
 with_subelements:
     - users:
     - 'ssh_keys'
```

And in this invocation, it would return {{ item.0 }} as each record, and {{ item.1 }} as each subelement of the given field name, as such:

   # configure all authorized keys for all users

```
- authorized_key:  name={{ item.0.name }} key={{ lookup('file', item[1]) }}
   with_subelements:
      - users
      - 'ssh_keys'
```

Alternative proposals welcome.

Having a sufficient number of lookup plugins for the 'odd' cases.

**Comment by mivok** [comment]
Alternative proposals:

Example playbook:

```
---
- hosts: all
  connection: local
  vars:
    - users:
        mark:
          name: Real Name
          ssh_key: "ssh-rsa AAAAA...."
        foo:
          name: Foo Barrington
          ssh_key: "ssh-rsa AAAA...."

  tasks:
    - debug: msg="{{users[item]['name']}}"
      with_items: users.keys()
```

This prints out: "Real Name" and "Foo Barrington" in turn.

If you relax the with_items plugin to allow a dict instead of a list (only
required on run function check, the flatten check can stay the same), then the
with_items check can be changed to just say `with_items: users`.

I just realized this is a little different than your original layout of users,
but the layut described above looks like it shouldn't need any changes. The
following works perfectly:

```
- hosts: all
  connection: local
  vars:
    - users:
        - name: foo
          ssh_key: "ssh-rsa AAAAA...."
        - name: bar
          ssh_key: "ssh-rsa AAAA...."

  tasks:
    - debug: msg="{{item.name}} - {{item.ssh_key}}"
      with_items: users
```

**Comment by mivok** [comment]
I realized my comment didn't address the specific issue described in the issue above, namely how to do a nested loop where the inner loop is a key of a dictionary instead of a straight list.

An alternative proposal for the issue mentioned could be something like:

```
with_nested:
  - users
  - item['ssh_keys']
```

Problems I'm seeing with doing it this way:
- The nested plugin currently doesn't identify anything other than a basic variable name, so foo['bar'] wouldn't be recognized as something that should be expanded/evaluated.
- The nested plugin would need to potentially evaluate the inner loop for every invocation of the outer loop, which doesn't seem to be done currently.

Advantages:
- No new plugin, just extending the functionality of an existing one.
- You could do something more complex on the variable name, just like with the with_items plugin (e.g. jinja2 filters, applying python functions), which may cover more cases that aren't being considered right now.

**Comment by mpdehaan** [comment]
The first example you suggested might not actually do it, because what I'm suggesting is dealing with a user who has multiple SSH keys.

The second example is perhaps interesting, if we can tweak with_nested without much evils.   It's probably possible and would be worth exploring.   item.ssh_keys would also be acceptable if that were done.

**Comment by mpdehaan** [comment]
Proposal is that it should be able to do iterate over

hash of 

```
x:
     foo: splat
     keys: []
y: 
     foo: splat2
     keys: []
```

And also lists of users like my 1st post too

**Comment by srgvg** [comment]
Ouch, looks like a missed this one, was thinking of exact the same thing this week.

Question: should this support just with 1 subloop, or also going deeper? (just like nested and together can take more than two list elements and do more than one subloop)

**Comment by mpdehaan** [comment]
I am thinking one fits nearly all use cases?

Can you post an example datastructure and what that might look like in playbook syntax?

**Comment by srgvg** [comment]
I don't have a use case for that, just wanted to know what you expect.

So the proposal is: with_subelements takes a list of two items, the first being a hash/dict, or a list, the second being a string pointing to a (sub)key in that hash/dict or list.

In case it's a hash like

``` yaml
x:
     foo: splat
     keys: []
y: 
     foo: splat2
     keys: []
```

will the main keys x and y appear in the resulting list?

I'm not sure if updating with_nested would be the best way to go; with_nested can also take more than two list items. Might also confuse users.

**Comment by mpdehaan** [comment]
Yes, the proposal is about returning the element x or y as item[0] and then
iterating keys as item[1]

**Comment by srgvg** [comment]
OK, and in case of a list the iterating keys just as item.
