### ISSUE TITLE
Fact improvements

### ISSUE THREAD

**Issue by sfromm** [ansible/ansible#376]
A few things:
- Prefix all dmi facts with dmi_*.  For example, ansible_product_name becomes ansible_dmi_product_name.
- When writing playbooks, it would be nice to have a single variable, eg ansible_pkgmgr, that describes the native package manger for the host.
- selinux-related facts -- I think someone was going to tackle this, but forget who.  This would be whether enforcing, policy version, policy type, and so on.

**Comment by dagwieers** [comment]
I don't think prefixing with dmi_ is very useful. It should not matter where the information is coming from as long as it is correct and clear what it means. In that respect I think it is unfortunate that the dmi information in /sys does not use the same convention as **dmidecode** w.r.t. the naming (e.g. system-product-name and system-uuid, rather than product-name and product-uuid). So I would suggest renaming the dmi facts to make more clear what they mean rather than prefixing them to indicate where they came from.

Although keeping it like it is now is probably best for backward compatibility...

**Comment by sfromm** [comment]
While there is merit to backward compatibility, I think keeping product_name will be confusing in the long term.  I saw at least one person include it in a bug report under the impression it was ansible-specific.  Perhaps deprecate the old naming of dmi facts and remove after a release or two?

Agreed regarding the discrepancy between dmidecode and /sys/class/dmi; it is unfortunate.

**Comment by dagwieers** [comment]
I agree with a rename and deprecating them, if Michael agrees. I held off making a patch after I noticed the names were based on the _/sys_ names rather than what I was used to from **dmidecode**.

**Comment by sfromm** [comment]
I avoided dmidecode because I didn't want the overhead of parsing output.  On the down side, that meant ansible would not collect dmi information from older distros like {rhel,centos}5.  Anyway, presenting the data with meaningful names would be nice.

**Comment by mpdehaan** [comment]
no movement on this one, so closing

**Comment by sfromm** [comment]
yeah, sorry.  i've been swamped with other things.  :-(

**Comment by mpdehaan** [comment]
me too, no problem!  mostly just merging other people's requests here.
