### ISSUE TITLE
Ansible requirements no longer true for SELinux nodes

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#3786]
As a result of 98cc29f9fd, the getting started documentation that says that target nodes just require python and simplejson is no longer true.

Ansible now fails against targets that have selinux enabled but do not have python-selinux installed. 

This might be desirable behaviour (I don't know enough about why python-selinux is required to argue either way) but it does raise the barrier to entry.

**Comment by vincentvdk** [comment]
This only true if you enable/use SELinux and use the SELinux module. Same goes for the Yum module (you'll need yum-utils).

**Comment by willthames** [comment]
That doesn't appear to be true. I had this without using any selinux features at all.

selinux_enabled will fail if HAVE_SELINUX is false but selinux is enabled on the server (i.e. selinuxenabled exits with status 0). 

In most parts of the code, selinux_enabled is only called if HAVE_SELINUX is true.
e.g. https://github.com/ansible/ansible/blob/44d060/lib/ansible/module_common.py#L337

However, in atomic_move, there are a few unguarded calls to selinux_enabled
https://github.com/ansible/ansible/blob/44d060/lib/ansible/module_common.py#L862
https://github.com/ansible/ansible/blob/44d060/lib/ansible/module_common.py#L865
https://github.com/ansible/ansible/blob/44d060/lib/ansible/module_common.py#L886

It might be that the fix is just to add the same check before calling HAVE_SELINUX - but in that case, why not just have selinux_enabled return False when HAVE_SELINUX is False.

Happy to create a pull request for this, just not convinced that I know what the superior fix is.

**Comment by mpdehaan** [comment]
@willthames, your assertion about unguarded calls is incorrect because those functions referenced link to functions that require SELinux when required.   Look at the definition of selinux_enabled

I'm fine with the documentation mentioning you should install python-selinux too if you are using SELinux in the RHEL section and will take care of referencing that.

**Comment by bcoca** [comment]
@willthames, those calls do check for selinux, they are not unguarded, keep
drilling down the code.

@vincent, now the core modules file/copy/template WILL require selinux
python bindings IF selinux is installed AND enabled on the target. This was
done to avoid the many complaints that ansible would leave files in a 'bad
selinux context' otherwise.

We should update the docs to reflect this extra dependency, I'll add it to
my list.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
I've already done this, I just haven't pushed it yet.

**Comment by bcoca** [comment]
_checks DONE on todo item_

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
