### ISSUE TITLE
Using `serial: 1` causes a run to fail when one system is unreachable

### ISSUE THREAD

**Issue by itiserik** [ansible/ansible#3845]
See also #1663 but it stops executing when one system is unreachable (error 110 connection timed out). Should it try the next system?

**Comment by srgvg** [comment]
At least in the 1 use case where I use serial: 1, that's what I expect, yes.

**Comment by mpdehaan** [comment]
This is  by design.

However, if you want, you can set serial: 2 and there's a patch I haven't applied yet to alter the failure percentage from the default 100% to something above 100% if you wanted to ensure it didn't fail, though I wouldn't suggest this as stopping the update is the whole point of failure detection in the rolling update.

**Comment by itiserik** [comment]
Well there should be a difference between a failure and an unreachable node. When I call ansible-playbook with a certain host list I assumed that ansible will try hard to apply the playbook on the nodes. An offline node is not a failure caused by the playbook so skip that one and go on with the next node.

**Comment by jimi-c** [comment]
There was actually a patch contributed yesterday that changes the return code from the ansible-playbook for failed vs. unreachable hosts. It will still be a non-zero return code, but it will give some indication of what the issue during the run was.
