### ISSUE TITLE
Add working directory variable by default

### ISSUE THREAD

**Issue by garthkerr** [ansible/ansible#38771]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
manager

##### SUMMARY
Request a built-in variable `awd` for ansible working directory. Expected result of the implementation:
```bash
ansible-playbook --extra-vars "awd=$(pwd)"
```

##### Why?
There are several use-cases where a role might need a reference to the ansible working directory or root directory structure of the [scm] repository, and in many cases, stacks of relative `../..` references can be cumbersome to manage or difficult to read. References to configuration files may not always be encapsulated in the role or playbook directory structure, depending on usage.

```yaml
- include_vars:
    file: '{{ awd }}/config/users.yml'
```

##### Why not use `playbook_dir` variable?
It's not consistent for determining the base path. There is a use-case for nesting playbooks into directory structures, based on their intent. Determining relative paths from a nested playbook directory structure can be cumbersome. Additionally, this structure can vary based on usage.

##### Why not just set with `pwd` at runtime OR as a variable?
This is what I currently do. The idea is to create a variable consistent with the working directory. One that does not change based on implementation or usage.

**Comment by bcoca** [comment]
just define a var:
```awd: "{{lookup('pipe', 'pwd')}}"```
If you want it to always be the 'current', use `vars:` or similar, as it is lazy evaluated and will always be calculated on use.

If you want the 'initial' working directory, you can use extras as you do above or use `set_fact` to force the evaluation and keep a constant value as it is evaluated when setting the fact.

I actually don't recommend using `pwd` as `playbook_dir` is a much safer alternative, as you can always:

``` cd /var/tmp; ansible-playbook /home/secure/safe/play.yml``` and you really want things relative to the playbook not to your current working directory.

**Comment by nkakouros** [comment]
BTW, there is also the `"{{ ansible_facts.env['PWD'] }}` variable that you can use.

**Comment by bcoca** [comment]
@tterranigma that reflects the 'remote target', not the local controller, it is also dependent on the connection info used to gather the facts.

**Comment by jpork** [comment]
The project root dir or ansible working dir is exactly what I'm looking for. All automation tool I know - `gradle, ant, maven, sbt` -  from java world have it. Referring to files relatively to the projects root dir appears to me a distinguished feature. After googling this issue it appears to me that lots of other people have the same problem too.

The pwd lookup with env or pipe - "{{lookup('env', 'pwd')}}" - cannot provide this feature because it delivers the path where the particular playbook is located which in complicated projects is often not the project home/root dir.

The problem is one never knows in which particular playbook context a role is running. And if multiple roles share a set of files I usually place them in a subdir of the project. But I can't refer to these files in a well defined way because the projects root dir is unknown as long as I don't pass it in from outside which is error prone.

**Comment by garthkerr** [comment]
I added an inventory python script i.e. `inventory/vars` that references `all` hosts and serves as a hack for how I want to reference the root directory structure.

```python
#!/usr/bin/env python
# must return valid json, consumed by ansible

import sys, json, os

# swap this with git if that fits your use-case
# awd = "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"

awd = os.getcwd()
vars = { 'awd': awd }

# redacted auto-loaded vars here

out = { 'all': { 'vars': vars } }

json.dump(out, sys.stdout)
```

**Comment by samdoran** [comment]
Closing per above suggestion to use `"{{lookup('pipe', 'pwd')}}"`

**Comment by jfilak** [comment]
BTW, I tried the suggested construction and it contains directory of the executed playbook and not current working directory of the process at the time it was started.

My set up:
```
/opt/my/stuff/theplaybook.yml
...
include_vars:
    file: "{{lookup('pipe', 'pwd')}}/config/include.yml"
...
/opt/something/else/config/include.yml
```

if I run `ansible-playbook /opt/my/stuff/theplaybook.yml` from `/opt/something/else`, the process crashes with the error about missing file `/opt/my/stuff/config/include.yml`.
