### ISSUE TITLE
Fireball connections never timeout if host is down

### ISSUE THREAD

**Issue by acranox** [ansible/ansible#3906]
I have a few hundred nodes to manage with ansible.  I'd like to use fireball mode over SSH.  It does appear to be faster.  Ideally, I'd leave the fireball daemon running for hours or days.
If I run a playbook that starts fireball over SSH, and then runs the later tasks over the fireball connection, things work well.  Nodes that are down (there are always a few) fail the SSH stage, and nothing else happens.  But once the fireball daemon is running, if I try to perform additional tasks directly over fireball, they work for the nodes that are running, but stall indefinitely for nodes that are down, the playbook never exits.

Looking at netstat I just see "SYN_SENT" connections that just sit there, for at least 10 minutes, before I've just given up and hit ctrl-c.

Can there be a mechanism where if a connection can't be made successfully over 0mq, that ansible will fail  skip that host?

Thanks.
Peter

**Comment by jimi-c** [comment]
I'm currently working on an improved version of fireball that will use raw sockets rather than 0mq, and will handle this kind of situation much better (while removing a dependency on the target nodes PLUS not requiring special bootstrapping). We're targeting this for the 1.3 release.

Once that's out, we'll be deprecating the current fireball mechanism, so I don't think we're going to be fixing issues like this unless they're critical.
