### ISSUE TITLE
Ansible control windows server return data Chinese garbled

### ISSUE THREAD

**Issue by babyshen** [ansible/ansible#39410]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
python 3.5.2 + centos 7
ansible 2.5.2
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```
[root@test-01 ~]# ansible win_test -m win_shell -a 'python d:\test\stat.py ' 
172.16.18.20 | SUCCESS | rc=0 >>
�ڴ�ʹ����(%): 13.2
CPU ʹ����(%): 0.0
��ǰ��¼�û�: {'Administrator': None}
# 中文出现乱码，win_test 系统为 windows server 2012，简体中文
```

**Comment by mkrizek** [comment]
cc @abadger @jborean93

**Comment by jborean93** [comment]
Can you share the contents of stat.py, hard to tell what is happening if we don't know the script that is being called. Also what is the expected output of the script/the output when you run it locally?

needs_info

**Comment by babyshen** [comment]
@jborean93 
#### contents of stat.py
```
import psutil

def mem_stat():  # 内存使用率
    mem_use = psutil.virtual_memory().percent
    return mem_use

def cpu_stat():  # cpu 使用率
    cpu_use = psutil.cpu_percent(0)
    return cpu_use

def user_login(): # 当前登录用户
    all_user = psutil.users()
    login_user = {u.name: u.host for u in all_user}
    return login_user

def main():
    print("内存使用率(%):", mem_stat())
    print("CPU 使用率(%):", cpu_stat())
    print("当前登录用户:", user_login())

if __name__ == '__main__':
    main()
```
#### output of the script：(windows)
```
内存使用率(%): 87.8
CPU 使用率(%): 0.0
当前登录用户: {'administrator': '0.0.0.0'}
```

**Comment by jborean93** [comment]
@babyshen this might be a difficult one to solve but I'm going to put what I've found out so far in this comment to hopefully narrow down a fix in the future.

Looking at this very briefly there seems to be an issue in the Windows UTF-8 codepage that is failing to process a 2 and 3 byte UTF-8 char. You can probably test this yourself by opening up a cmd process on your Windows box and typing in `chcp 65001` before running your Python script. That this does is temporarily changes the console code page to the UTF-8 variant  for that cmd process and show you what happens when Ansible runs it.

For some background info on what I've tried and looked into, I started with a very basic PowerShell script that outputs 4 different types of unicode chars which in order takes 1, 2, 3, and 4 bytes to represent in utf-8

```
# http://www.fileformat.info/info/unicode/char/0072/index.htm
# UTF-8: \x72
Write-Host "r"

# http://www.fileformat.info/info/unicode/char/0172/index.htm
# UTF-8: \xc5\xb2
Write-Host "Ų"

# http://www.fileformat.info/info/unicode/char/5185/index.htm
# UTF-8: \xe5\x86\x85
Write-Host "内"

# https://www.fileformat.info/info/unicode/char/1d11e/index.htm
# UTF-8: \xf0\x9d\x84\x9e
Write-Host $([Char]::ConvertFromUtf32(0x1D11E))
```

What this tests is to see how pywinrm/WinRM returns the byte representation of each different encoding of UTF-8 chars and to see where this is falling apart. At first I ran this as a raw task in Ansible to try and rule out the exec wrappers we found, in the end the output was

```
changed: [SERVER2016.domain.local] => {
    "changed": true,
    "rc": 0,
    "stderr": "",
    "stdout": "r\nÅ²\nå†…\n𝄞\n",
    "stdout_lines": [
        "r",
        "Å²",
        "å†…",
        "𝄞"
    ]
}
```

In this example we can see that we get 4 lines returned from the script where each of them are one of the chars we sent through. We can see the single and 4 byte UTF-8 chars worked but the 2 and 3 ones are giving up something completely different. In actual fact, we are getting 2 and 3 chars for the 2 and 3 byte utf-8 expectation which tells up something isn't right.

Next I tried to run pure pywinrm to rule out Ansible causing the issue, here is the script I ran

```
import binascii
from winrm.protocol import Protocol

p = Protocol(
    endpoint='https://server2016.domain.local:5986/wsman',
    transport='ntlm',
    username=r'user',
    password='pass',
    server_cert_validation='ignore')

shell_id = p.open_shell(codepage=65001)
command_id = p.run_command(shell_id, 'powershell.exe', ['-File', 'C:\\temp\\test.ps1'])
std_out, std_err, status_code = p.get_command_output(shell_id, command_id)
p.cleanup_command(shell_id, command_id)
p.close_shell(shell_id)

stdout_bytes = std_out[:-1].split(b"\n")
stdout_hex = [binascii.hexlify(b).decode() for b in stdout_bytes]
stdout_text = [b.decode('utf-8') for b in stdout_bytes]
print(stdout_hex)
print(stdout_text)
```

and here is the output for that script in both Python 2 and 3

```
# py2
[u'72', u'c385c2b2', u'c3a5e280a0e280a6', u'f09d849e']
[u'r', u'\xc5\xb2', u'\xe5\u2020\u2026', u'\U0001d11e']

# py3
['72', 'c385c2b2', 'c3a5e280a0e280a6', 'f09d849e']
['r', 'Å²', 'å†…', '𝄞']
```

Just looking at the byte representation we can see that the 1 and 4 byte example are correct but the 2 and 3 byte one are not showing what we expect. These values are actually larger than what they should be.

Pywinrm isn't doing anything fancy here, it receives a base64 string which it decodes like normal and just returns the byte string which is what we are working with on the Python script I posted and can only mean that Windows is not interpreting the characters correctly.

Finally I ran this manually from a Windows box to see what happens in WinRM natively and I get the following output

```
C:\Windows\system32>chcp 65001
Active code page: 65001

C:\Windows\system32>winrs -r:http://server2016.domain.local:5985/wsman powershell.exe C:\temp\test.ps1
r
Å²
å†…
𝄞
```
Once again we get the same output that WinRM receives, when running the script directly outside of a cmd shell I get the same output.

Ultimately this tells me that the Windows UTF-8 codepage (65001) that Ansible sets is unable to process UTF-8 chars that require 2 and 3 bytes to represent. While it is possible to set another codepage this would probably result in unexpected output that Ansible will be unable to parse in the future and so probably won't be a supported configuration.

~~Ultimately I still seem to be missing some info as it still works for 4 byte UTF-8 chars just not 2 and 3 byte chars so I need to do some more investigation. I know for a fact that 2 byte chars work fine when passing in as an argument from Ansible so this should work.~~

**Comment by jborean93** [comment]
Further testing:

Changing the encoding of the PowerShell test file to UTF-16 (either little or big endian) means that the correct chars are output correctly. I stupidly forgot that PowerShell sets the encoding based on the file that is being run which is why my tests were failing before. The Python script is another beast though, it seems like print() is failing in my particular codepage and will need to play around a bit more.

**Comment by babyshen** [comment]
@jborean93 
Thank you for your answer. I will continue to study this issue. Linux and windows coding inconsistent, Chinese garbled is indeed a more headache. Thanks again.

**Comment by jborean93** [comment]
@babyshen I finally found a fix for you. As you've probably sumised Windows encoding, especially in the cmd console, is quite archaic and cumbersome to deal with. As you may have seen from the tests I ran, to get these unicode chars working in PowerShell you needed to ensure the PowerShell script is encoded with UTF-8 + BOM so that PowerShell knows what encoding to use.

For Python scripts, they seem to use another method to determine what encoding to use when dealing with the std IO buffers, it seems to be determined based on the system's default CP settings and not based on the current console's settings which is why it doesn't work when running through Ansible/WinRM. What you need to do if force it to use the utf-8 encoding, this is easily done by setting the environment variable `PYTHONIOENCODING=utf-8` and Python will be able to output the correct chars.

In Ansible this can be done

```
- name: run Python script with utf-8 output
  win_command: Python.exe d:\test\stat.py
  environment:
    PYTHONIOENCODING: utf-8
```

I'm not sure on the syntax on an adhoc Ansible command/don't think you can set environment variables for this. You could potentially call it like this if you really want to run an adhoc command

```
ansible win_test -m win_shell -a 'Set-Item -Path env:PYTHONIOENCODING -Value "utf-8"; python d:\test\stat.py
```

There is a way to force the script to set the encoding but it is not recommended and you should be relying on the environment variables.

Finally because this is a Python-ism and not something with Ansible/there are workarounds you can do to get it working I am going to close this issue.

**Comment by babyshen** [comment]
ok
