### ISSUE TITLE
.ini files in inventory directories are ignored by default

### ISSUE THREAD

**Issue by colin-nolan** [ansible/ansible#39562]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

/lib/ansible/config/base.yml

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /mnt/host/hgi-systems/ansible/ansible.cfg
  configured module search path = ['/home/cn13/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.2 (default, Sep 13 2017, 14:26:54) [GCC 4.9.2]
```

##### CONFIGURATION

(default)

##### OS / ENVIRONMENT

n/a

##### SUMMARY

By default, Ansible is configured to ignore files in an inventory directory with the `.ini` extension:
https://github.com/ansible/ansible/blob/ebe7666d71e30d47bf1af6c8c601d275c1ddacaa/lib/ansible/config/base.yml#L1362
This is despite the fact that there is an ini plugin that parses ini inventory files.

If someone gives their ini inventory files the correct extension (useful, for example, to get the correct syntax highlighting by an IDE), they will (rather unexpectedly!) find that their inventory files get silently ignored.

I do not know the reasoning why `.ini` files are ignored by default but I argue that it is a bug that Ansible does not work (by default) with `ini` inventory files + `.ini` extensions.

##### STEPS TO REPRODUCE

Create an inventory directory and add an inventory file named `example.ini`. Then run Ansible with this inventory.

##### EXPECTED RESULTS

```
Parsed /production/example.ini inventory source with ini plugin
```

##### ACTUAL RESULTS

```
 [WARNING]: Unable to parse /production as an inventory source
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is on purpose, due to the legacy of inventory scripts and their reliance on `.ini` files for configuration. If you point at the file directly or change the configuration it will work, but if we change the default it will break many existing setups that rely on the `.ini` files being ignored. Also the ini plugin can parse files w/o the `.ini` extension.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by colin-nolan** [comment]
It is unclear to me why anyone would have non-inventory `.ini` files in a directory that is been used as an inventory source. Could you elaborate on what the legacy reasons for having such files may have been?

For context: in some of our inventory directories, we have tens of static ini inventories alongside dynamic script inventories (i.e. we deal with "partial" inventory files in inventory source directories). I wanted to add `.ini` extensions to the ini inventory files (seemed a sane thing to do) but now realise why they were created without extensions originally.

**Comment by bcoca** [comment]
As you can see herer https://github.com/ansible/ansible/tree/devel/contrib/inventory, many inventory scripts have corresponding `.ini` files (some use `.yaml/.yml`) and the ini parser was always able to read files w/o the extension mattering. This is mostly a restriction on 'directory parsing' that has always been a part of Ansilbe.

**Comment by colin-nolan** [comment]
@bcoca I see, thanks for the details!
