### ISSUE TITLE
How can i get the original command?

### ISSUE THREAD

**Issue by wjainiya** [ansible/ansible#40466]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
2.4.10

##### OS / ENVIRONMENT

ansible RHEL7
target  windows server 2016

##### SUMMARY

when i try to install huflt8 on windows server 2016, i follow the manual command setup.exe -s -f1"setup.iss", (there is no space between f1 and "C:/"), i write playbook like this:

```
-  debug:
      msg: 'E:/setup.exe -s  -f1"C:/setup.iss"'
-  win_command:  E:/setup.exe -s -f1"C:/setup.iss"

```
```
  TASK [debug] ***************************************************************
    ok: [172.28.87.34] => {
    "msg": "E:/setup.exe -s  -f1\"C:/setup.iss\""
  }
  TASK [win_command] ********************************************************
   changed: [172.28.87.34]
   PLAY RECAP ******************************************************************
    172.28.87.34               : ok=2    changed=1    unreachable=0    failed=0 
```
but, huflt8 doesn't install on windows.
i use powershell on windows machine , command E:/setup.exe -s  -f1\\"C:/setup.iss" ,not installed,
command E:/setup.exe -s  -f1"C:/setup.iss" ,installed successfully.
so , the problem i think is the "\\" happened between f1 and "C:/".
Is there some way to get the full command without escape character "\\" ?

**Comment by sivel** [comment]
I do not believe it will be possible to print the original command using any of the built in output methods in ansible.

The problem is that ansible tends to output things in a JSONified format, and those quotes will need to be escaped.

You might be able to switch from double quotes `"` to single quotes `'` to avoid that.

```
    - debug:
        msg: E:/setup.exe -s  -f1'C:/setup.iss'
```

```
ok: [localhost] => {
    "msg": "E:/setup.exe -s  -f1'C:/setup.iss'"
}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
