### ISSUE TITLE
Dashes in FreeBSD service names should be replaced by underscores in rc.conf

### ISSUE THREAD

**Issue by hostage-nl** [ansible/ansible#4094]
When using the service module, the service name should have its dashes replaced by underscores. For example the service /usr/local/etc/rc.d/php-fpm should be enabled by placing php_fpm_enable="YES" in /etc/rc.conf

I'm not a python guru, but this tiny patch against ansible-1.2.3 makes it work:

```

--- Downloads/ansible-1.2.3/library/system/service      2013-09-12 11:16:18.294884754 +0200
+++ /usr/share/ansible/system/service   2013-09-12 11:12:08.571536892 +0200
@@ -80,6 +80,7 @@
 import tempfile
 import shlex
 import select
+import string

 class Service(object):
     """
@@ -616,7 +617,7 @@
             if os.path.isfile(rcfile):
                 self.rcconf_file = rcfile

-        self.rcconf_key = "%s_enable" % self.name
+        self.rcconf_key = "%s_enable" % string.replace(self.name,"-","_");

         return self.service_enable_rcconf()

```

**Comment by mpdehaan** [comment]
Can you please submit this as a github pull request?

That is standard process we use to contribute to the project.

If you need info about pull requests see https://help.github.com/articles/using-pull-requests

Thanks!

**Comment by jimi-c** [comment]
It appears that this patch is no longer valid, as the rcconf_key is found by reading in the config and splitting on the '=' to get the key rather than basing it on the service name. Since 1.3 was released, which includes this new code, I'm going to go ahead and close this issue. If you believe that you are still having an problem related to this issue please feel free to open another. Thanks!

**Comment by hostage-nl** [comment]
there was nothing wrong with splitting the key and value, there's something wrong with the translation from the service name to the key: s/-/_/g

i'll have to reopen this issuer and figure out how to do a pull request...
