### ISSUE TITLE
Add state=touch or equivalent to file module

### ISSUE THREAD

**Issue by illenseer** [ansible/ansible#4097]
Currently the file module does not create files, if they do not exist.
I propose to add 'state=touch' or something equivalent to the file module to make sure a file gets created.
The motivation behind this is, that now you have to create two task, if you want to have a file present and ensure certain permissions. Right now you have to use copy to get an empty file with correct permissions, if the file is not present initially and in subsequent playbook runs, you need a file task to ensure the correct permissions. This is e.g. needed for syslogd on FreeBSD for /var/log/console.log, if you enable to log console.info.

**Comment by bcoca** [comment]
What about on_missing=fail (default)|touch ? with state=present and on_missing=touch, always makes sure the file exists, but doesn't modify it if there already. present=touch should (in my mind) always touch the file (modify mtime). 

I would also push stat as an alternative vs using file state=present to determine if file is there or not.

**Comment by jimi-c** [comment]
That's what I was getting at above, that state=touch should act like the CLI touch command in that respect, there are some uses for it (ie. notifying FastCGI to restart by touching its control file).

**Comment by mpdehaan** [comment]
I like the idea of it having less options and being a state.

**Comment by dch** [comment]
@bcoca just mentioned this on irc, +1 for `state=touch`. 

my case is I've got some logfiles that must be present, and secure. It is clumsy to have this wrapped around a check test (even if ansible will do this under the hood).

So the semantics I'm aiming for is : create_if_missing basically. I can ensure permissions anyway in a separate phase if reqd.

see https://gist.github.com/dch/5836fab3bedf53830fa5 for how it was previously.

**Comment by steverweber** [comment]
+1 for state=touch

**Comment by gregbuehler** [comment]
+1 for state=touch

**Comment by hjwp** [comment]
If I may be allowed a little moan -- `state=touch` isn't really what you want for ensuring a logfile is present and has the correct perms, because it always returns changed, even if the file already exists and has the correct perms.  What you want is a thing that creates the file if it's missing, or resets the file perms if they're wrong, but otherwise does nothing, and returns OK.

`state=present` would seem to capture it?

hope that makes sense + helps.

**Comment by bcoca** [comment]
code is already there that should not change the file unless it doesn't
exist.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by hjwp** [comment]
I know the file's not changed.  The problem is that Ansible still sees the touch event as a "changed", even when there's nothing to do -- it's yellow in the output, rather than green.  So I can't rely on it to notify handlers correctly, for example.

the docs also say that it will update the file's metadata, the last accessed and modified times, and I don't really want that.  my personal use case, but i suspect anyone else that's using it just to make sure that, say, a log file is present and has the correct perms to be written to, would have the same requirements...

**Comment by resmo** [comment]
@hjwp  This is exactly how it should work according the documentation: http://docs.ansible.com/file_module.html

**Comment by hjwp** [comment]
Right. I'm not saying it doesn't work as expected.  I'm saying the feature doesn't quite do what I want, and that I think a slightly different feature would work better -- cf my earlier post, `state=present` or something like that would be better.

If most people are using this like I am, which is as a way of ensuring that a file is present and has the correct perms, then they don't want the file to be touched each time.  You know how it is, you always think most people have the same use case as you do, it's hard to imagine what crazy things other people might be doing... but i still reckon most people might prefer a feature which just ensured the file was present, and didn't touch it if it wasn't necessary....

**Comment by illenseer** [comment]
Actually, I was originally looking for a feature `state=present` and I still would prefer it. My use case is the same like @hjwp described it.

**Comment by resmo** [comment]
so I wonder, why don't you open a new ticket "feature request" and not post to an old closed one. I just checked the code, I make a pull request to not change access times on present.

**Comment by hjwp** [comment]
well, don't do that, because if "touch" no longer updates access times, then it's misnamed, because it no longer behaves like the unix `touch` command.

I guess maybe a feature request could be a better place for the discussion.  I think my assumption was that, actually, 90% of people probably actually don't want `state=touch`, they actually wanted a `state=present`, so if i was king of the universe i would deprecate `touch` and replace it with `present`.  anyways, will open a new ticket.

**Comment by resmo** [comment]
yes sure, but IMHO it is more the "ansible" file touch should not behave like unix touch (otherwise it would not make sense to implement this feature anyway). 

we could change it in the way that it behaves like unix touch if `force` is yes, otherwise it should not touch it, or completely remove this part. In any case, docs must be updated.

```
diff --git library/files/file library/files/file
index 32588e5..4cbd3c2 100644
--- library/files/file
+++ library/files/file
@@ -261,10 +261,11 @@ def main():
                 except OSError, e:
                     module.fail_json(path=path, msg='Error, could not touch target: %s' % str(e))
             elif prev_state in ['file', 'directory']:
-                try:
-                    os.utime(path, None)
-                except OSError, e:
-                    module.fail_json(path=path, msg='Error while touching existing target: %s' % str(e))
+                if force:
+                    try
+                        os.utime(path, None)
+                    except OSError, e:
+                        module.fail_json(path=path, msg='Error while touching existing target: %s' % str(e))
             else:
                 module.fail_json(msg='Cannot touch other than files and directories')
```

@bcoca what do you think?

**Comment by hjwp** [comment]
I see, so then `state=touch` would work just like my proposed `state=present`, because by default `force` is set to no?  Either could work I guess.

**Comment by jimi-c** [comment]
Please see @mpdehaan's comment on #7490, you can accomplish `state=present` in other ways if you do not want touch to update the timestamp on the file. Users are used to Unix semantics, so we modeled touch's behavior on that. To change it now would potentially break other users playbooks.

**Comment by bcoca** [comment]
I think you want 2 tasks, first one can be a stat to check file existance
and permissions, 2nd one could conditionally create or set permissions.​
file did have a 'present' but it was more for detection (though would set
permissions if diff), but I believe it broke when prev_state handling was
added.

Default file state is 'prev_state' not 'present' as docs say, I've been
trying to figure out how to fix it.

**Comment by ktaragorn** [comment]
@hjwp Ive had this issue too, and it seems that one way is to do `command: touch <file> creates=<file>` This is skipped if the file exists.
