### ISSUE TITLE
delete security group, detach/delete ebs volume not supported 

### ISSUE THREAD

**Issue by pattu777** [ansible/ansible#4125]
I have just started learning ansible. I have written a simple playbook which will create , delete a server using ansible's ec2 module. I can also create a volume and attach it to a previously created instance.

But I would like to know, is there a way to delete a security group and detach/delete an ebs volume.

Thanks,

**Comment by jimi-c** [comment]
Hi, for general support questions please use just the mailing list or IRC. We prefer to use github only for bugs and feature requests. Thanks!

**Comment by pattu777** [comment]
I posted this issue on mailing list earlier and was told to create a issue to implement this feature for ec2_vol module on github .

IRC Link - "https://groups.google.com/forum/#!topic/ansible-project/4hFYq1zbysg"

Thanks,

**Comment by jimi-c** [comment]
Yes, that was me, however this wasn't stated as a feature request and was pretty much a repost of your question to the ML. Sorry if I was confusing on that, but please be sure to describe the feature you're requesting, ie: "Modify the ec2_vol module to allow for removal of volumes that were created". 

Also please be sure to create separate requests for different features. Since security groups and volumes are handled by two different modules, those should be two different feature requests.

Thanks!

**Comment by pattu777** [comment]
ok..sorry for my mistake.. I am new to github. So I didn't know how to proceed. Anyways I will make seperate threads for the feature requests.

Thanks,

**Comment by jimi-c** [comment]
No problem, if you have any questions just let me know.
