### ISSUE TITLE
Can I use the new-style module interface for other languages than python?

### ISSUE THREAD

**Issue by jhagg** [ansible/ansible#4144]
Is it possible to write a module that uses the new-style interface
for modules in other languages than python?

I'm trying to write a module in perl that can do 'check_mode', but looking
in `__init__.py` it seems as if this only is possible for modules
with module_style 'new', or actually that the module contains the REPLACER
tag (INCLUDE_ANSIBLE_MODULE_COMMON).
But adding this would automatically include a lot of python code and that
isn't really useful in a perl program. :-)

So, is the 'protocol' for new-style modules documented somewhere?

I found some hints in the code, like 'WANT_JSON', are there more of these tags?

**Comment by mpdehaan** [comment]
Development questions should usually go to the ansible-devel@googlegroups.com mailing address as we prefer to reserve the issue tracker for bug reports and pull requests, etc.

Short answer is no, but there's no meaning to new style modules instead of one that auto mixes in Python.

I would recommend taking a look here: https://github.com/ansible/ansible-for-rubyists

Will work exactly the same for Perl.

Hope this helps and if you have more development questions please stop by the devel list.  Thanks!
