### ISSUE TITLE
New Features - Meraki Module

### ISSUE THREAD

**Issue by mathewfer** [ansible/ansible#41573]
##### New Features
 - Feature Idea 
 Are you considering add more features based on this link below upcoming Ansible Versions?;
https://github.com/meraki/dashboard-api-python/blob/master/meraki.py

I use some these functions in Python to add, clone .. new networks to Meraki dashboard as I do not see these listed functions are supported in Meraki module in Ansible 2.5.0. 

##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

>
```
Linux
```

**Comment by mkrizek** [comment]
cc @kbreit

**Comment by kbreit** [comment]
@mkrizek If I recall correctly, I don't think there are any Meraki modules in 2.5 as they're all slated for 2.6. I maintain the Meraki Ansible module community wiki page which shows what's slated for releases.

https://github.com/ansible/community/wiki/Network:-Meraki

Are there any features in particular you're looking for? BTW, I may steal your time zone listing code because I don't do a check on that as I didn't want to manually write them :)

**Comment by mathewfer** [comment]
Hi,
Thanks for the reply. Yes, 2.5 has got very limited features. I see most of the features that I am looking for are in 2.6 under "Networks" - all 5 items listed there.

Also looking for the below 2 which are targeted for 2.7.
Devices:

- List devices in a network
- Update the attributes of a device

Does this mean 2.6, when released, all these 5 features will be available, possibly end of this month?

I see that the link I posted in very 1st post is from Cisco Meraki SE and it has got almost all the functions.
https://github.com/meraki/dashboard-api-python/blob/master/meraki.py

**Comment by kbreit** [comment]
2.6 will have all the features I’ve listed on the Wiki page for organizations, network, admin, and SNMP. Unfortunately, I wasn’t able to get the meraki_device module pulled in time for the 2.6 freeze so that will have to wait until 2.7. I’m pretty confident it will be there though. In fact, I have the code already pushed to my fork of Ansible so you can manually download it and try it out if you want to live life dangerously.

If you can say, what are you trying to do with these modules? I’m developing these and trying to get a grasp of use cases so any feedback you have would be very appreciated.

**Comment by mathewfer** [comment]
Thanks.
My tasks are same as I have described before and to use the Ansible module in bulk provisioning.

I tried to check your fork link but I could not find it. Can you please share the link? and I will try to use it and start testing it.

I think I can start using it as user added module to test it.

Please let me know the code location/link.

**Comment by kbreit** [comment]
https://github.com/kbreit/ansible

You’ll probably want the meraki/meraki_device branch. You will also need to setup a “development environment” using venv it properly path it.

If you have any bugs or anything you want to see, please submit issues

**Comment by kbreit** [comment]
I submitted meraki_device tonight as a PR. It won’t be integrated until 2.7 at the earliest but I wanted to get the process started for you. Take a look at the documentation in the file, do you think it meets your needs?

https://github.com/ansible/ansible/pull/41631

**Comment by mathewfer** [comment]
Hi,

Thanks.
I checked your link yesterday but I could not find most of those features are there. I will have look at it again soon.

If you can, please let me know the link.

**Comment by kbreit** [comment]
I'd suggest taking a look at my integration tests for the meraki_device module.

https://github.com/kbreit/ansible/blob/meraki/meraki_device/test/integration/targets/meraki_device/tasks/main.yml

**Comment by kbreit** [comment]
@mathewfer Do the current modules which are in Ansible 2.7 support the functions you need?

**Comment by kbreit** [comment]
This has moved to the collections and will be fixed these, if it hasn't been already. Please use the collection available at https://galaxy.ansible.com/cisco/meraki and submit issues at https://github.com/CiscoDevNet/ansible-meraki. Thank you.

**Comment by Akasurde** [comment]
Closing as per above comment.
