### ISSUE TITLE
wrong variables file used when using 'with_first_found' in 2 roles

### ISSUE THREAD

**Issue by ajardan** [ansible/ansible#41584]
##### SUMMARY
When I try to include_vars in 2 different roles by using something like:

```
- name: Including variables for distribution
  include_vars: 
    name: "{{ item }}"
    dir: 'vars'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
```
Just one of the files our of all the files in both roles is used, so some variables are missing.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = ~/Projects/adex/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ansible
  executable location = ~/.pyenv/versions/3.6.5/bin/ansible
  python version = 3.6.5 (default, May 12 2018, 18:05:38) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

```
DEFAULT_ASK_VAULT_PASS(~/ansible/ansible.cfg) = True
DEFAULT_BECOME(~/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(~/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(~/ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(~/ansible/ansible.cfg) = ['~/ansible/environments/production']
HOST_KEY_CHECKING(~/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Running from: Mac OS 10.13.4
Running on: CentOS 6.9

##### STEPS TO REPRODUCE

To reproduce use 2 roles that have the above include_vars snippet, but contain different variables which are not initialized from defaults, but only set in platform specific files or vars/default.yml.
##### EXPECTED RESULTS

I expected both roles to pick up their respective platform specific file and read the required variables
##### ACTUAL RESULTS

```
TASK [franklinkim.sudo : Including variables for distribution] ********************************************************************************
task path:~/ansible/roles/franklinkim.sudo/tasks/vars.yml:3
ok: [jira.int03.theadex.com] => (item=~/ansible/roles/common/vars/RedHat.yml) => {
    "ansible_facts": {
        "~/ansible/roles/common/vars/RedHat.yml": {
            "sudo_pkg_mgr_opts": "",
            "sudo_sudoers_group": "wheel"
        }
    },
    "ansible_included_var_files": [
        "~/ansible/roles/franklinkim.sudo/vars/default.yml",
        "~/ansible/roles/franklinkim.sudo/vars/openbsd.yml"
    ],
    "changed": false,
    "item": "~/ansible/roles/common/vars/RedHat.yml"
}
```

As you can see above, Ansible used ~/ansible/roles/common/vars/RedHat.yml instead of ~/ansible/roles/franklinkim.sudo/vars/default.yml

**Comment by maxamillion** [comment]
!component =lib/ansible/vars/manager.py

**Comment by terra-nova** [comment]
This bug (feature?) is still present as of in 2.7.6 (current version on RHEL/EPEL 7 as of today).
I am using the system Python (2.7.5).

I am using the same pattern as @ajardan above; many independent roles use `include_vars` in conjunction with `with_first_found` to source distribution/os/platform-specific variables. The idea is to try more specific var files first, and more generic files later (e.g. centos-7-x86_64.yml first, then centos-7.yml, then redhat-7.yml, then redhat.yml, then main.yml as a fallback... you get the idea).

Some of our roles depend on other roles, and we noticed that if a "more specific" vars file exists in the vars subdirectory of the "child" role depending on a "parent" role, then the parent role will source the variables file from the "child" role.

For example, we have a role  "icinga2-server" (child) which depends on another role "icinga2-repository" (parent), but because the child role has a more specific variable file, the parent role gets confused and pulls in that file:

```
TASK [linux.icinga2-repository : include_vars] **************************************************************************************************************************************************************************************************************************************************
ok: [xxx] => (item=/home/xxx/ansible/roles/linux.icinga2-server/vars/redhat-7.yml) => { ... }
```

Of course the role is now missing some important variables and subsequently fails to perform its tasks.

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

You are incorrectly mixing `name` and `dir`, name sets a variable with the contents of ALL files found in dir, first_found here is just creating a variable name, the variables from the files you reference are not imported (unless they are in vars, in which case all files are imported). If you want the behaviour of only one file, use:

``` 
- include_vars: ' {{looup("first_found", files=myfiles, paths="vars") }}'
 vars:
   myfiles:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
 ```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
