### ISSUE TITLE
Unable to use `when:` against a string variable

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#42352]
##### SUMMARY
Using `when: some_variable` results in an error

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /home/florian/dev/primesign/appliance-ansible/ansible.cfg
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.local/venvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible
  python version = 3.6.4 (default, Jan  5 2018, 02:13:53) [GCC 7.2.0]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
---

- name: testing when
  hosts: localhost
  vars:
    test: "string_value"

  tasks:
    - debug:
        var: test
      when: test
```

##### EXPECTED RESULTS

No Error

##### ACTUAL RESULTS
```
ansible-playbook 2.6.0
  config file = None
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.local/venvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible-playbook
  python version = 3.6.4 (default, Jan  5 2018, 02:13:53) [GCC 7.2.0]
No config file found; using defaults
setting up inventory plugins
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /home/florian/.local/venvs/ansible/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test.yml ***********************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [testing when] **********************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/florian/dev/company/test.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: florian
<127.0.0.1> EXEC /bin/sh -c 'echo ~florian && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612 `" && echo ansible-tmp-1530797442.6806855-31307538971612="` echo /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612 `" ) && sleep 0'
Using module file /home/florian/.local/venvs/ansible/lib/python3.6/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/florian/.ansible/tmp/ansible-local-236306xg63pfn/tmpzf5viyxu TO /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612/ /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/florian/.local/venvs/ansible/bin/python /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/florian/.ansible/tmp/ansible-tmp-1530797442.6806855-31307538971612/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/florian/dev/company/test.yml:9
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'test' failed. The error was: error while evaluating conditional (test): 'string_value' is undefined\n\nThe error appears to have been in '/home/florian/dev/company/test.yml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n"
}
	to retry, use: --limit @/home/florian/dev/company/test.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

/cc @agaffney

**Comment by agaffney** [comment]
This is reproducible in current `devel` and `stable-2.6`.

**Comment by samdoran** [comment]
Tested all the way back to v2.0 and this has never worked. It always gives the same error and tries to interpret the string value inside the variable as a variable name.

**Comment by samdoran** [comment]
Also, this is not specific to Python 3 as I tested with Python 2.7.14.

**Comment by agaffney** [comment]
What version of Jinja did you test with? My understanding is that those conditions are evaluated almost entirely by Jinja, so this could be something that changed in a recent version.

**Comment by samdoran** [comment]
@agaffney I tested with Jinja 2.10.

**Comment by agaffney** [comment]
I'm also seeing this with ansible `2.6.0` and Jinja `2.8`. I'm surprised that I've never seen this come up before.

**Comment by apollo13** [comment]
Yeah me to; it absolutely feels like something that should work (tm). To be honest I do not know if it ever worked; but I'd certainly love to see support for it.

**Comment by agaffney** [comment]
How would you expect it to work? Really, this is probably more a Jinja issue than an ansible one.

Edit: this does appear to be an Ansible issue, as I cannot reproduce it within a Jinja template, either with a var defined in the playbook or in the template itself.

**Comment by agaffney** [comment]
It seems that this is "intentional" behavior. If the entire condition matches the name of a var, the condition is replaced with the content of the var before being evaluated. It *looks* like this is to allow reuse of the same `when` condition without triggering the warning about curly braces in the condition (but it's much older than that warning).

https://github.com/ansible/ansible/blob/1f824bd620b60dff90233bd4b057c74ada1677a0/lib/ansible/playbook/conditional.py#L125-L133

**Comment by apollo13** [comment]
> How would you expect it to work? Really, this is probably more a Jinja issue than an ansible one. 

The same as in Jinja or how an "if varname" in Python itself would work (ie check if it is not empty)

**Comment by agaffney** [comment]
It looks like you can get your desired behavior by doing something like `when: some_var|string`. Aside from that, the behavior that you're seeing is intentional (even if this side effect is not), and there's not really anything to fix.

If you can think of a way to properly support the intended functionality and your use case at the same time, please suggest it.

**Comment by apollo13** [comment]
To be honest I do not really understand the "intented" behavior from the docstring. Is the goal to allow evaluation from string variables? Does this need to hold true for when to and not just assert? Is the behavior documented somewhere? All in all it seems rather inconsistent with regard to other variable types…

**Comment by agaffney** [comment]
It looks like that code was last touched by @jimi-c, but it's not clear if he was the original author. Even if it was mostly intended for use with `assert`, both `assert` and task-level `when` conditions use the same code to evaluate the conditional statement. It would probably be possible to only enable that behavior in some cases, but that would break backward compatibility with people actually using this with `when`.

**Comment by apollo13** [comment]
Would it actually be breaking backwards compat if it is not documented? Sure some people might rely on it; but having backwards compat on stuff which works by accident is weird. If this is wanted behavior it should probably get documented

**Comment by agaffney** [comment]
I didn't say that it worked by accident. I said that your use case being broken was a side effect.

There are multiple different ways to accomplish what you want, and this is obviously not something that people run into much, since you're probably the first person to create an issue on this since 2.0.

**Comment by sivel** [comment]
This is ultimately a duplicate of https://github.com/ansible/ansible/issues/34591

The above issue is just a special condition where the value of the string is `"false"`

**Comment by mowgli** [comment]
Funny, that someone else has found it just days before me and it was never detected before. Sorry of not finding this one. But github search for bool did not show it. (It even dont show mine. :-( )

I just found it as I seen some behavior of something that I need to be run not run. So I debugged the stuff founding this error.

The problem is that I just test that in when. The task should be done if the variable is a string that is not empty or an array that is not empty. So in fact, exactly as it would do in jinja if statement.

What I found how it could work, is to do
```
when: variable|d()
```
But this is all not intuitive and nothing that is expected.

@sivel it is not a special value of false! The empty string should be false but a non-empty string should always render to true.

@all I believe that many others have this bug and suffer of it without being aware of it. So it should be fixed as soon as possible.

**Comment by agaffney** [comment]
There's not really anything to "fix" here. This behavior is a result of explicit behavior in the code that allows storing a condition in a variable and using that variable in `when`. The reason that adding `|d()` "fixes" it is because the code that looks for a condition that consists of only a simple variable name no longer matches. You can get the same effect by using `|string` or really any other jinja filter.

**Comment by mowgli** [comment]
@agaffney no, |string will not fix the issue as I have a variable that can be string or array, depending on conditions outside of the play.

If that is an explicite behaviour, it is a bug nevertheless and needs to get fixed.

I even would say that it can be a security bug. You don't know where the content of the variable is coming from. It might hold some evil string. Just checking if it is empty or not does no harm. I expect that to be done when using in "when". But here the content gets evaluated! This does harm.

**Comment by agaffney** [comment]
I meant that `|string` could short-circuit that logic in the general case. I don't know the details of your specific case. My point was that adding any jinja filter would cause this specific feature to no longer trigger, as it only works against simple variable names. You can also just use more specific conditions rather than relying on implicit evaluation of the "truthiness" of a var.

You can call it a bug, but that implies unintended behavior. Just because it works differently than you expect does not necessarily make it a bug.

There's some truth to calling it a security bug, but that same potential problem exists in many more places in Ansible than just this particular feature. The main risk is from facts from a malicious target host, which is being addressed via the `ansible_facts` namespacing option (on by default as of 2.6) and the future deprecation/removal of top-level fact vars.

There *may* be reason to change this behavior, but the simple truth is that it is likely being relied upon in lots of places and will break people's playbooks if changed. In general, maintaining backwards compatibility is more important than reducing confusion when writing new playbooks, especially when this functionality was intended (even if the confusion is introduces was not).

**Comment by mowgli** [comment]
Well, about backward compatibility, I have some places in my playbook where I have to use:
```yaml
- name: Get the real installed ansible version
  shell: 'ansible --version | head -1 | sed -e "s/ansible //"'
  tags: [patches]
  register: ansible_remote_version
  changed_when: False
  check_mode: no
- name: do something
  …
  when:
    - ansible_remote_version.stdout|version_compare('2.6', '<')
    - ansible_remote_version.stdout|version_compare('2.4', '>=')
- name: do something
  …
  when:
    - ansible_remote_version.stdout|version_compare('2.4', '<')
    - ansible_remote_version.stdout|version_compare('2.3.0.0', '>=')
- name: do something
  …
  when:
    - ansible_remote_version.stdout|version_compare('2.3.0.0', '<')
    - ansible_remote_version.stdout|version_compare('2.2.0.0', '>')
```

I also fear about the day when static icludes will gets removed from include as not all versions of ansible support import_tasks or include_tasks. The same counts for jinja tests "… is …" instead of "…|…" that is also not supported by all ansible versions.

So instead of deprecating such behaviour, it would be more usefull to deprecate this "intendet" behaviour that is never expected.

**Comment by sivel** [comment]
Closing this as https://github.com/ansible/ansible/pull/51030 has been merged.  We will deprecate the current behavior in 2.12, but there is a config toggle to disable this behavior.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
