### ISSUE TITLE
Route53 overwrite arg problem when the record type to update is different from the existing one

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4242]
This happens to me when I try to update an existing record but with a different record type (ex: A != CNAME) , the module works when I update the value if the record type is the same ( A = A or CNAME = CNAME) .

```
  - name: update Route53 DNS record
    local_action: route53 command=create overwrite=true zone=test.example.net. record=xyz.test.example.net. type=CNAME ttl=60 value=asd.example.com
```

```
failed: [localhost] => {"failed": true}
msg: RRSet of type CNAME with DNS name xyz.test.example.net. is not permitted as it conflicts with other records with the same DNS name in zone test.example.net.
```

```
ansible --version
ansible 1.4 (devel 0252aac226) last updated 2013/09/23 10:19:38 (GMT +000)

CentOS 5
Linux 2.6.34.7-56.40.amzn1.x86_64 #1 SMP Fri Oct 22 18:48:49 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

boto version: 2.13.3
```

**Comment by jimi-c** [comment]
This is a limitation of Amazon's Route53 API. It really only has the two operations for modifying records: CREATE|DELETE, so it won't let you do a create on a record as you're trying to do above because it already exists. To get around this, you'll have to delete the record first if it exists, and then re-create it.

**Comment by nicolas-g** [comment]
thanks @jimi-c  .
