### ISSUE TITLE
Feature request: package module

### ISSUE THREAD

**Issue by aw** [ansible/ansible#4261]
Hi,

I have quite a few tasks installing packages for various operating systems. 

It would be helpful if there were a `package` module which doesn't require specifying yum or apt.

I wouldn't replace the apt/yum modules, but rather use it as a wrapper around those modules.

Example:

```
# Installs git using yum/apt based on {{ ansible_os_family }}
- name: Install GIT
  package: yum=git apt=git-core state=present
```

This would save me eleventy billion lines of almost identical code.

Note: The idea is somewhat similar to what the `service` module currently does.

**Comment by bcoca** [comment]
ansible_pkg_manager variable can do this, but  you still have the problem
with that is that now you need a mapping between you asking for a package
and how each system names the package.

**Comment by mpdehaan** [comment]
And Apache and many tools are very very different between different platforms, so you must always be aware why these are different.

We don't expose a greatest-common-denonimator implementation for this reason, and allow our package management to feel native.

This being pushed by some other tools is really a "marketing" kind of feature, as you have to make exemptions so many times, it really causes problems down the road.

**Comment by aw** [comment]
Understood. Still hard to get away from my old puppet/chef approaches to things.

Thanks!

**Comment by trinitronx** [comment]
Sorry to bring up an old thread, but I really find it surprising that this was the only discussion surrounding this.   First off, let me explain that I am coming from a background where I was working at a company with heavy Chef usage, modular, cross-platform, and re-usable cookbooks. Now I'm at a company using Ansible, so I've had to adapt and am re-learning how to do things in Ansible, but have been missing how well cross-platform cookbooks worked in Chef, and sad to see that not many roles on Ansible Galaxy support multiple platforms.  Understandably so, since Ansible is much younger than Chef, and the community is still developing. However, I'm struggling with some best-practices, cross-platform capabilities, and some TDD paradigms that I'm not finding in Ansible.

I'm surprised that Ansible doesn't have a generic `package` module that abstracts away the details of the package manager on a cross-platform basis.  Granted that sometimes package names are different, in 90% of cases where they are the same it makes it easier to use.  It also simplifies the configuration management code quite a bit and makes it unnecessary to do crazy conditional includes just in order to create a cross-platform role.  For those times that the package name is different, just set variables/attributes differently to store the different names. (Example: the apache2 Chef cookbook sets [package name depending on platform](https://github.com/onehealth-cookbooks/apache2/blob/master/attributes/default.rb#L45) and then uses the generic [package](https://github.com/onehealth-cookbooks/apache2/blob/master/recipes/default.rb#L20-L22) resource to install it)  My main point here is that when package names are different, you'll have to handle them anyway (why not do it in a vars file instead?) and when they're not, it simplifies making your config managment code cross-platform.  This is the same concept OOP uses for using a generic base class with specialized classes that inherit from it.

Overall I still think there's a place for some OOP design principles in Ansible, and I feel like they would actually simplify things for the community.
