### ISSUE TITLE
Support 'su' as an alternative to 'sudo'

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#4324]
In some configurations, `su` may be the preferred method for root level access.  Supporting running tasks via `su -c` should be a straightforward implementation.

This should also make it's way out into additional hostvars as well that could be provided via an inventory script.

Some ideas for hostvars:
- ansible_su_pass
- ansible_su_user
- ansible_root_method

**Comment by bcoca** [comment]
ansible_su_pass should always be the same as ssh/login password and always
prompted for.

**Comment by sivel** [comment]
ansible_su_pass should not be the same as an unprivileged user login, the root password should be different.  ssh as the root user is not possible as PermitRootLogin will in almost all cases be set to 'no'.  And in our specific use case it will be provided via an inventory script, and should not be prompted for.

Prompting for the su password in this manner would result in being prompted for a root password for every server, which could be thousands of servers at a time, where the root password is different for every host, and not known to the person running ansible.

**Comment by bcoca** [comment]
sorry, su passwod should be the same as login/ssh password of the 'target'
user.

**Comment by bcoca** [comment]
the prompting on on part of su, unlike sudo it has no 'nopassword' that i
know of (unless you are root and dropping privs)

**Comment by mpdehaan** [comment]
I'd agree it should be the same as the target user but with the caveat that they might have initially logged in via user key and just know the root password.

**Comment by zart** [comment]
Note that su does have 'nopassword' feature if configured so via pam, eg using "auth sufficient pam_wheel.so trust use_uid" in /etc/pam.d/su

**Comment by angstwad** [comment]
Alright, so I'm hacking at this in my branch: https://github.com/angstwad/ansible/tree/su-support
As of the last commit there, only `bin/ansible` support has been added.  

@jeromew -- Since you're the author of ssh_alt, we'll need to do a little work to ensure that `su` support is in your conn plugin.  There were quite a few changes made in the current `ssh.py`.  It looks like you've made good progress and and @mpdehaan is looking to get the ssh_alt plugin merged into the devel branch for further testing.  If ssh_alt is to replace the current `ssh.py` then su support hinges on integration with ssh_alt.

I'm not quite complete here -- more to come.

**Comment by mpdehaan** [comment]
Closing because pull request is merged, there are some details like making su/sudo not specifiable in the same task that are still being refined.

Thanks!!!
