### ISSUE TITLE
Command line option for config file

### ISSUE THREAD

**Issue by guoqiao** [ansible/ansible#43283]
##### SUMMARY

In `ansible-playbook --help` output, we need a option to choose the config file, just like the `-i` option for inventory. In a lot of cases, I need to load different config file for different playbooks.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansbile 2.6.1
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jborean93** [comment]
Not exactly what you are looking for but as per https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file you can set `ANSIBLE_CONFIG=/path/to/config` if you wish to use an explicit configuration file.

`ANSIBLE_CONFIG=/ansible/ansible.cfg ansible-playbook ....`

**Comment by guoqiao** [comment]
@jborean93 
Thank you, that's a good work around, but it's still reasonable to have the command line option equivalent to this env var.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this request as it does not really add functionality and it is just a question of preferences on typing `--configuration-file` vs `ANSIBLE_CONFIG`.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
