### ISSUE TITLE
Promote `/latest/` documentation

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#43562]
##### SUMMARY
We often see Google suggesting links to specific versions of documentation rather than `/latest/`.

Now we have versioned documentation we should tell search engines to prefer `latest` over (say) 2.4, or 2.5.

**Tell search engine which to use**
* Ensure `sitemap` has `/latest` first (and as the entry point)
* http://docs.readthedocs.io/en/latest/canonical.html
* https://www.mattcutts.com/blog/seo-advice-url-canonicalization/
* https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps
* Ensure all links are to `https` (as that's all we serve now)

**Review content and ensure link to latest**
* Maybe worth reviewing any blog posts and other documentation on the main ansible.com site to ensure they link to the `latest` version - Do we have a blog post review process?

**Informing the user**

* For documentation older than the current version we may want to add a banner

Thanks to dj, lhill and realged13 for their ideas.

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION
```
2.7
```

**Comment by gundalow** [comment]
docschick pointed out the following which is uses in Tower:

```
 <script>
  var url = window.location.href;
  if(url.indexOf("latest") == -1){
   var version = url.replace("http://docs.ansible.com/ansible-tower/","");
   version = version.substring(0,url.indexOf("/"));
   url = url.replace(version,"latest");
  }
  var canon = document.createElement('link');
  canon.rel = "canonical";
  canon.href = url;
  document.head.appendChild(canon);
```

**Comment by gundalow** [comment]
Also do we want to make it much clearer to the end user if they are looking at `/latest`?

similarly we may wish to add a warning header if people are on `/devel/`

**Comment by MrOwen** [comment]
It seems like the canonical tags are a good idea for any pages on `/latest` but I don't know how docs are built/deployed so not sure how much additional effort is required to add the tags on only the latest version of the docs.

One problem with the canonical tag is that it does not do redirection. So if I google "azure rm deployment" and the canonicalization has been setup and Google picks that up, I might be sent to the "latest" docs page but the URL in my address bar may still read "https://docs.ansible.com/ansible/2.5/modules/azure_rm_deployment_module.html" (this is my understanding of my brief reading of canonical tags)

That banner approach seems like a great first step because it alerts the user that they're not on latest but doesn't change any behavior they're already used to. In the meantime, perhaps the web server config can be altered so that any known crawler coming onto the site will receive a 301 to the `/latest` version of that page. One problem I do foresee is that if someone wants to explicitly search for a versioned page, Google may not ever return that because everything is redirected to `/latest` and I don't know at the moment how to work around that.

I'll try to do a bit of research and see if anything can be implemented so that version specific searches still can return what the user expects. Maybe something in the sitemap where we have links to the old versions with "?redirect=false" appended that way search engines know that this specific page exists and can be returned to the user without a 301 redirection?

**Comment by acozine** [comment]
Related to #45776, #37049, #41782

**Comment by acozine** [comment]
Also related (in a different way) to #42178.

**Comment by gundalow** [comment]
Lots of good ideas in here.

Maybe if we can list the various use-cases we can then agree on what behaviours we'd like to see.

**Comment by gundalow** [comment]
Canonical URL https://github.com/ansible/ansible/pull/49190 has been merged which has made a large improvement.

Will need to review Adobe Analytics logs again and see what other things need doing.

A banner for non-latest would still be good IMHO.

**Comment by jdillard** [comment]
Do the Ansible docs generate a sitemap currently? If not, there is a `sphinx-stemap` extension that could be used: https://github.com/jdillard/sphinx-sitemap

There is an open issue that I was going to try to tackle soon for creating a priority config value that might help in this situation: https://github.com/jdillard/sphinx-sitemap/issues/11

**Comment by samccann** [comment]
Thanks @jdillard for the suggestion!  Ansible does have a very old sitemap (manually created) that needs to be updated - https://github.com/ansible/docsite so might be worth investigating that extension.

**Comment by samccann** [comment]
RST and sphinx support metadata (description - useful for external search, and keywords, useful for site search). We can consider adding those to important pages.

We also have some lingering search hits for 2.4, tied to pages that have a lot of hits. For example, a search for 'Ansible network supported platforms' has this as the 2nd returned search result:
https://docs.ansible.com/ansible/2.4/intro_networking.html

**Comment by samccann** [comment]
sitemap updated to latest via -https://github.com/ansible/docsite/pull/17

**Comment by samccann** [comment]
banners added - https://github.com/ansible/ansible/pull/58526
