### ISSUE TITLE
Timer expired after 10 seconds when gather facts

### ISSUE THREAD

**Issue by cmdrrobin** [ansible/ansible#43884]
##### SUMMARY
Timer expired after 10 seconds when gather facts on some hosts.

```
fatal: [kso-nlape1vp-rano-009]: FAILED! => {"changed": false, "cmd": "/usr/bin/udevadm info --query property --name /dev/sda1", "msg": "Timer expired after 10 seconds", "rc": 257}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gather facts on Rancher node running as CentOS.

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/robin/dev/support-ansible/ansible.cfg
  configured module search path = [u'/home/robin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_ASK_VAULT_PASS(/home/robin/dev/support-ansible/ansible.cfg) = True
DIFF_ALWAYS(/home/robin/dev/support-ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Client: RHEL 7.5 (Maipo)
Remote: RancherOS v1.2.0

##### STEPS TO REPRODUCE
Run the playbook when it wants to gather facts it fails.

```yaml
---
- name: Deploy CoreDNS
  hosts: dns
  roles:
    - coredns
```

##### EXPECTED RESULTS
Finish the playbook

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_d9POp0/ansible_modlib.zip/ansible/module_utils/basic.py", line 2853, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
  File "/tmp/ansible_d9POp0/ansible_modlib.zip/ansible/module_utils/facts/timeout.py", line 37, in _handle_timeout
    raise TimeoutError(msg)
TimeoutError: Timer expired after 10 seconds

fatal: [kso-nlape1vp-rano-009]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/udevadm info --query property --name /dev/sda1",
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "*",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    },
    "msg": "Timer expired after 10 seconds",
    "rc": 257
}
```

**Comment by cmdrrobin** [comment]
For the record, I don't have any issues with Ansible version 2.5.7.

**Comment by Shookit** [comment]
I can confirm, I see this exact same issue sporadically. This only occurs on certain hosts, not the entire set.

**Comment by alikins** [comment]
Interesting traceback... Looks like the SIGALRM handler from facts.timeout is raising the TimeoutError when the `try/except TimeoutError` isn't in the stack, so the TimeoutError gets caught by module_utils.basic.AnsibleModule.run_command()'s `try/except` around the subprocess.Popen() call and that causes the fail_json() return before the `try/except` around get_mount_facts() ever sees it.

  The call to get_mount_facts() is wrapped in a try/except TimeoutError.
 (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/linux.py#L90-L94)

``` python
        mount_facts = {}
        try:
            mount_facts = self.get_mount_facts()
        except timeout.TimeoutError:
            pass
```

The info in the fail_json return makes it look like it came from run_command()'s try/except around the subprocess.Popen() at https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2883-L2885

``` python
    try:
            if self._debug:
                self.log('Executing: ' + self._clean_args(args))
            cmd = subprocess.Popen(args, **kwargs)

         < ... snipped for brevity ... >

            while True:
                rfds, wfds, efds = select.select(rpipes, [], rpipes, 1)
                stdout += self._read_from_pipes(rpipes, rfds, cmd.stdout)
                stderr += self._read_from_pipes(rpipes, rfds, cmd.stderr)
              
               < ... snipped lots of code handling fd errors and a
                       cmd.wait() and other things that could raise Exception ...>

            cmd.stdout.close()
            cmd.stderr.close()

            rc = cmd.returncode
        except (OSError, IOError) as e:
            self.log("Error Executing CMD:%s Exception:%s" % (self._clean_args(args), to_native(e)))
            self.fail_json(rc=e.errno, msg=to_native(e), cmd=self._clean_args(args))
        except Exception as e:
            self.log("Error Executing CMD:%s Exception:%s" % (self._clean_args(args), to_native(traceback.format_exc())))
            self.fail_json(rc=257, msg=to_native(e), exception=traceback.format_exc(), cmd=self._clean_args(args))
```

Not sure how to fix that... 

One possibility might be to add a clause in run_command() to ignore and re-raise timeout.TimeoutError, so it doesn't get handled by the 'except Exception' clause.

Another way... maybe passing in the calling stack for the wrapped method in the timeout.Timeout() decorator? Or possibly just moving the _handle_timeout def inside the context of the wrapper() method instead of just inside the decorator() method. Other timeout implementations seem to match the existing code though, so unlikely.

Though, it kind of looks like the Timeout() decorator may not be resetting the original signal handler when it is done. Comparing the facts.timeout code to https://github.com/pnpnpn/timeout-decorator/blob/master/timeout_decorator/timeout_decorator.py#L65-L94 for example, resetting the signal handler seems to be the main thing missing in facts.timeout. Wondering if that in combo with subprocess's _eintr_retry_call() is causing problems.

**Comment by balonik** [comment]
I am hitting this issue as well on Oracle Linux 7.5 with Ansible 2.6.2

**Comment by thrix** [comment]
Yep, seeing this also :(

**Comment by joltcan** [comment]
Same here!

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [hostname]: FAILED! => {"changed": false, "cmd": "/bin/udevadm info --query property --name nas:/homes", "msg": "Timer expired after 10 seconds", "rc": 257}
```

The host is running Debian 9, mounted homedir with NFS (nfs (rw,noatime,vers=3,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=nas,mountvers=3,mountport=30000,mountproto=udp,local_lock=none,addr=nas,_netdev), and my ansible host is MacOS 10.13.6. Same with MacOS 10.14 beta.

**Comment by Amos-85** [comment]
same issue with ansible 2.6.3 on rhel 7.5

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [hostname]: FAILED! => {"changed": false, "cmd": "/sbin/udevadm info --query property --name /dev/mapper/rootvg-varlv", "msg": "Timer expired after 10 seconds", "rc": 257}

the command is executing without issues on the target host.

**Comment by codemastroAB** [comment]
Same issue. Need a quick fix for this issue. 
Ansible-playbook executes properly on some nodes but on some nodes connection time out. Nothing has changed from configuration or playbook perspective.

The full traceback is:
```
Traceback (most recent call last):
  File "/tmp/ansible_Kh_sLm/ansible_modlib.zip/ansible/module_utils/basic.py", line 2853, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
  File "/tmp/ansible_Kh_sLm/ansible_modlib.zip/ansible/module_utils/facts/timeout.py", line 37, in _handle_timeout
    raise TimeoutError(msg)
TimeoutError: Timer expired after 10 seconds

fatal: [a1uspod2.securonix.net]: FAILED! => {
    "changed": false, 
    "cmd": "/bin/findmnt --list --noheadings --notruncate", 
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d", 
            "filter": "*", 
            "gather_subset": [
                "all"
            ], 
            "gather_timeout": 10
        }
    }, 
    "msg": "Timer expired after 10 seconds", 
    "rc": 257
}

```

CentOS Linux release 7.5.1804 (Core) 

ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by codemastroAB** [comment]
This work-around helped me.
In  /etc/ansible/ansible.cfg I set **gather_subset = !all** which basically only gathers minimum facts. I think while gathering facts something is messed up. So based on your requirement set the value to only gather those facts which is required for you.

**Comment by yajo** [comment]
You can see the failure here: https://travis-ci.org/Tecnativa/ansible-test-playground/builds/425233045#L601

Some problem with Debian 8? :thinking: 

---

Edit: it was a problem on my side: the docker image being used was too bloated, causing the CI machine to overflow.

**Comment by AnoopAlias** [comment]
```
# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

# ansible-playbook --version
ansible-playbook 2.6.4
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]



TASK [Gathering Facts] *********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [xxxx]: FAILED! => {"changed": false, "cmd": "/usr/sbin/udevadm info --query property --name /dev/vda3", "msg": "Timer expired after 10 seconds", "rc": 257}
```


The command itself work though!

```
# time /usr/sbin/udevadm info --query property --name /dev/vda3
DEVLINKS=/dev/disk/by-path/pci-0000:00:0a.0-part3 /dev/disk/by-path/virtio-pci-0000:00:0a.0-part3 /dev/disk/by-uuid/22cf702c-4a4a-479a-93c8-5b98e7d2a817
DEVNAME=/dev/vda3
DEVPATH=/devices/pci0000:00/0000:00:0a.0/virtio1/block/vda/vda3
DEVTYPE=partition
ID_FS_TYPE=ext4
ID_FS_USAGE=filesystem
ID_FS_UUID=22cf702c-4a4a-479a-93c8-5b98e7d2a817
ID_FS_UUID_ENC=22cf702c-4a4a-479a-93c8-5b98e7d2a817
ID_FS_VERSION=1.0
ID_PART_ENTRY_DISK=253:0
ID_PART_ENTRY_NUMBER=3
ID_PART_ENTRY_OFFSET=944762880
ID_PART_ENTRY_SCHEME=dos
ID_PART_ENTRY_SIZE=104857600
ID_PART_ENTRY_TYPE=0x83
ID_PART_TABLE_TYPE=dos
ID_PATH=pci-0000:00:0a.0
ID_PATH_TAG=pci-0000_00_0a_0
MAJOR=253
MINOR=3
SUBSYSTEM=block
TAGS=:systemd:
USEC_INITIALIZED=10858

real    0m0.006s
user    0m0.003s
sys     0m0.003s
```

**Comment by AnoopAlias** [comment]
Setting gather_timeout=20  in ansible.cfg  https://github.com/openshift/openshift-ansible/issues/8385
seem to work for me

**Comment by masato-asahara** [comment]
I am hitting this issue as well on Oracle Linux 6.9 with Ansible 2.6.3. The [workaround](https://github.com/ansible/ansible/issues/43884#issuecomment-419650710) shared by @AnoopAlias works for us.

**Comment by wavilen** [comment]
I met the issue with kubespray... Seems to me the problem in incorrect reporting about what exact command has timeout, in my case fixing fstab helps to restore normal operation of the gather facts.
In my case receipt instruction removes lvm logical volume but I forgot remove it from /etc/fstab before...
Hope this info will help someone, otherwise I'm sorry for intervention into the topic

**Comment by c2h5oh** [comment]
I've actually run `/bin/findmnt --list --noheadings --notruncate` on a affected Ubuntu 16.04 host and it takes quite a bit longer than 10s to run because of huge number of mounts:

```
$ cat /proc/mounts | wc -l
65578
```

It looks like having a handful of nested shared mounts (`mount --make-shared`) created for a single Docker container somehow ballooned to 2^16 mounts - all of them duplicates of the handful of shared ones:

```
$ cat /proc/mounts | sort | uniq | wc -l
58
```

I'm still digging into that one and I'll be posting another update soon.

Edit:
https://github.com/moby/moby/issues/37624
https://github.com/moby/moby/issues/36179

Edit2:
If you're using nested mounts with docker odds are they are going to be duplicated on each start-stop/restart going from 1->2->4->8->.. very fast. To prevent it use `rslave` propagation for nested mounts.

**Comment by alphaDev23** [comment]
@c2h5oh Ran into th same issue on an Ubuntu 16.04 running ansible 2.7.1; however the number of mounts is quite low on the target host:
cat /proc/mounts | wc -l
321

Changing  gather_timeout=20 in ansible.cfg resolved the issue.

**Comment by BarbzYHOOL** [comment]
One of these solved it:

gather_subset = !all
gather_timeout=20

But that issue was a real headache, I couldn't use any lookup plugin. This is a high priority bug

**Comment by gfidente** [comment]
For TripleO, increasing gather_timeout to 30secs did not resolve the issue [1]; fwiw the command timing out seems to be for everybody udevinfo:

  /usr/bin/udevadm info --query property --name /dev/vda1

This call has been introduced in 2.6 ; maybe there are alternatives?

1. https://logs.rdoproject.org/60/14960/23/check/legacy-rdoinfo-tripleo-master-testing-centos-7-multinode-1ctlr-featureset016/b82d69b/logs/undercloud/home/zuul/overcloud_deploy.log.txt.gz#_2018-12-04_18_45_28

**Comment by gintautassulskus** [comment]
It seems that `gather_subset = !all` does not collect network configuration information which my roles rely on. 
My solution to the issue was to revert back to 2.5.13.

**Comment by EmilienM** [comment]
ping @samdoran - could you help us?

**Comment by gfidente** [comment]
Has anyone tried replacing the udevadm call [1] with something like:

`# blkid -o export $device`

I suspect udevadm info is gathering a lot more infos and could get stuck in the kernel while querying for some of them ... while the only thing we're trying to return here is the FS UUID, which blkid can provide

I'd like to submit a patch to do the above

1. https://github.com/ansible/ansible/blob/stable-2.6/lib/ansible/module_utils/facts/hardware/linux.py#L383

**Comment by bcoca** [comment]
this PR now lets caller deal with the timeout https://github.com/ansible/ansible/pull/49449 

I'll be adding support for ignoring it in https://github.com/ansible/ansible/pull/49398 which will make this error non fatal

**Comment by abadger** [comment]
Reading up on how python interacts with signals, I think the only way to address this is to change the timeout decorator to use threads instead of signals.  signals will cause this sort of problem for any code at all so trying to change run_command() to deal with the timeout won't help because the timeout exception can be raised in code that is not run_command().

**Comment by bcoca** [comment]
That is true, but the decorator restricts the amount of code covered and run_command is the most likely culprit of being the delay/problem. The problem is that when they currently happen inside  inside run_command we always get a fatal failure. The PR above changes that to allow the caller to deal with it, after that it depends on how we use the decorator and the exception handling.

**Comment by abadger** [comment]
I started playing around with threads and multiprocessing (because it's not good to mix threads and forks, although execve is one way that has the least issues) to see if I could get the timeout decorator to work correctly.  I haven't finished playing around with it but I'm thinking those ideas may suffer from not being able to propogate an exception from the code in question correctly.  I'll keep working on that.

But if that doesn't work out, there is a way to make this work which is just a little hacky:

New code for timeout.py
``` python
class TimeoutError(Exception):
    pass


class _InternalTimeoutSignal(BaseException):
    pass

def _handle_timeout(timeout_seconds, signum, frame):
    msg = 'Timer expired after %s seconds' % timeout_seconds
    raise _InternalTimeoutSignal(msg)

def timeout(seconds=None, error_message="Timer expired"):    
    def decorator(func):
        def wrapper(*args, **kwargs):        
            local_seconds = seconds
            if local_seconds is None:
                local_seconds = globals().get('GATHER_TIMEOUT') or DEFAULT_GATHER_TIMEOUT
            signal.signal(signal.SIGALRM, partial(_handle_timeout, local_seconds))
            signal.alarm(local_seconds)
                
            try:
                result = func(*args, **kwargs)
            except _InternalTimeoutSignal as e:
                raise TimeoutError(e.args[0])
            finally:
                signal.alarm(0)

            return result
    
        return wrapper
```

This works because it's bad for code to catch ```BaseException``` so we can treat those as being outside of any exception hierarchy.  However, it's only good style that prevents other code from catching that so it's not entirely fool-proof.  I'd feel a lot better about it if we also merged at least the module and module_util portions of: https://github.com/ansible/ansible/pull/45389 so that we knew that there wasn't more code that would inadvertantly catch the exception.

I'll play around with threading and multiprocessing more tonight to see if I can fix this in a different way that doesn't rely on convention to work and submit a PR which uses one of these methods to fix the timeout decorator.

**Comment by abadger** [comment]
Initial work seems to show that multiprocessing.Process has issues with AnsiballZ which prevent functions from being pickled there but multiprocessing.ThreadPool seems to work.  I'll open a PR with that.

**Comment by joakimberg** [comment]
I've also experienced this when target hosts (Ubuntu 18.04.2 LTS) are running Python 2.7.15rc1. Some AnsiballZ_setup.py-script is pushing 100% cpu while gathering facts, until it times out.

It works fine when changing the target host interpreter to python3, so I guess it may be some issue with running ansible on ubuntu's release of python 2.7?

I tested back and forth with ansible_python_interpreter=/usr/bin/python3 to confirm this.
