### ISSUE TITLE
keystone_user module is not changing the password for existing user

### ISSUE THREAD

**Issue by azpekt** [ansible/ansible#4415]
Following construct does not changes the password on the existing user:
- name: Creation of users...
  keystone_user: user={{ item.user }} tenant=admin password={{ item.pass }} email={{ item.mail }} login_user={{ adminuser }} login_password={{ adminpass }} endpoint={{ endpoint }} login_tenant_name={{ tenant }}
  with_items:
  ........
- { user: 'admin', pass: 'newpass', mail: 'admin@domain.com' }
  tags:
- create_user

All variables were mentioned in role variable file, and I can create new users with it. But using it against existing users with password do nothing - password stays the same :(

ansible --version
ansible 1.3.2

**Comment by sivel** [comment]
The cause for this is in how keystone_user works in combination with state=present.

Based on the code, it checks to see if the user already exists, and if it does, then it returns

`{changed: False, id=123}`

See https://github.com/ansible/ansible/blob/devel/library/cloud/keystone_user#L217

If you were to use '-v' with your ansible-playbook command, this is what you should see.

Maybe this module should be updated to work like the `user` module, so that it ensures the user configuration on each run, and potentially also including a new param for `update_password`.

**Comment by mpdehaan** [comment]
Sounds good to me.

**Comment by bennojoy** [comment]
I had a look at the keystone client api and it doesn't have a method to get the user's current password, the user object returned by the lookup also doesnt have user password field either.
We could have a update_password option, but that would force an update to the password everytime.

**Comment by jctanner** [comment]
@bennojoy any suggestions on how to fix this?

**Comment by bennojoy** [comment]
@jctanner as i mentioned in the previous comment, i dont see a way to implement this because the api currently does not return the users's current password(hashed or plain), so we cant check the given password and existing password are the same, if anybody has any ideas on how this could be achieved vi api's, let me know and i can give it a try.

**Comment by xchenum** [comment]
One way is to hash the password provided to the module and store it to a local file. When the module is executed, we would compare the new password's hash with the file stored on the remote machine...

**Comment by mpdehaan** [comment]
Sorry for the delay in response, I don't think storing the password locally seems prudent.

An update_password option here seems quite reasonable and other modules have been doing this.

If someone would like to add this, it would be welcome.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
