### ISSUE TITLE
service state=reloaded should start the service if it is not already

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#4448]
Currently when a service is set to the "reloaded" state, if it is not started, then nothing happens.

As suggested in the thread linked below, it seems a more useful behaviour if Ansible would first check if the service is running, and either start it (if it is not) or reload it (if it is). Much as one would do on the command line, if one were doing it manually.

   https://groups.google.com/forum/#!topic/ansible-project/IBERDY98xuE

**Comment by wu-lee** [comment]
Just to clarify, this _is_ about reloaded, not restarted (unless it too doesn't start the service when stopped, but I believe it does).

**Comment by PriceChild** [comment]
This ticket saddens me. I think it should be up to the init script what happens when a reload is called for.

If you want it started even if it isn't running then have a previous task with `state=started` and keep the `state=reloaded` task/handler separate for the same behaviour.

Having ansible separately start if not already running means I can't choose to reload _everything_ knowing that anything not previously set as started will not start.

**Comment by abadger** [comment]
@PriceChild  That's certainly something to think about -- Probably should take it to the mailing list since not many people read comments on long closed tickets :-)
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

**Comment by PriceChild** [comment]
@abadger I wasn't going to as it's been there intentionally for some time and would break existing playbooks? I didn't think it likely it'd be changed because of this?

I might raise it now though..

Edit: I'm now imagining a "start_if_not_started" option to `state=restarted` & `state=reloaded` defaulting to 'yes'.

**Comment by pabelanger** [comment]
I've proposed https://github.com/ansible/ansible-modules-core/pull/2693 to revert this commit.

**Comment by flatrocks** [comment]
Would be cool if this sort of thing would be described in detail in the [docs](http://docs.ansible.com/ansible/service_module.html) so years-old issues like this don't have to serve as de-facto documentation.

**Comment by PriceChild** [comment]
@flatrocks There's a proposal.
