### ISSUE TITLE
how to execute sudo privileged commands 

### ISSUE THREAD

**Issue by vpvijay87** [ansible/ansible#44658]
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
![image](https://user-images.githubusercontent.com/30482456/44602977-38de2c80-a7af-11e8-806d-0d5a37501024.png)

**Comment by samdoran** [comment]
Please fill out the form rather than submitting a screenshot. The issue cannot be properly triaged and we cannot easily use your reproducing code (without retyping it all by hand).

Ansible cannot work properly with command specific `sudo` settings because Ansible executes a temp file or a sudoed shell on the remote node. See [this discussion](https://groups.google.com/d/msg/ansible-project/TZoUZUPO5no/SeJIlfaCBQAJ) for more information.

For further help with the issue, please reach out on IRC or the mailing:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
