### ISSUE TITLE
i want use yaml in ansible-playbook of task dir 

### ISSUE THREAD

**Issue by zhangmh2** [ansible/ansible#4471]
for example:  cat task.yml

``` yaml

---
{% if ansible_hostname in {{ foo}} %}
 - name: config repos
   copy: src=/etc/yum.repos.d/centos.repo dest=/etc/yum.repos.d/centos.repo
 - name:xx
    xxx
 - name:yy
    xxx
{% endif %}
```

actually, I  want exec some tasks through host vars decided

**Comment by mpdehaan** [comment]
Yeah this isn't Ansible's approach.  

It's a poor idea because it makes the data format not a valid data format.

I suggest reading the variable chapter and then the module documentation for "group_by" which allows exactly this by slightly different means.

Note:  questions should go to the mailing list or IRC rather than the bug tracker.   Thanks!

**Comment by mpdehaan** [comment]
You should also look up the "when" statement in the conditional chapter of the docs, which is how you do if statements.

Though for what you are doing this is really the "hosts:" selector.

All you do is:
- hosts: desired_hostname
   tasks:
      -

And you are doing something on just those hosts.

Much nicer, without all the Jinja2 junk sprinkled in your configuration orders.
