### ISSUE TITLE
Relative imports broken in ANSIBLE_PLUGIN_FILTERS modules

### ISSUE THREAD

**Issue by thkala** [ansible/ansible#44917]
##### SUMMARY

[This commit](https://github.com/ansible/ansible/commit/0633f73faf962620e09774a45a65aab968f6fb6d) inadvertently changed the way plugins are loaded, causing relative imports to fail in at least the case of plugin paths being overridden via environment variables (e.g. ANSIBLE_FILTER_PLUGINS).

Changing [this line](https://github.com/ansible/ansible/commit/0633f73faf962620e09774a45a65aab968f6fb6d#diff-cb51550dcfdbd27a3f224be2de15e2e8L436) from that commit to use `basename` instead of `name`, matching the other changes in the same commit, seems to correct this regression; an Ansible build with that change also seems to pass all tests.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.0.a1.post0 (devel 9d89e15ff0) last updated 2018/08/30 20:00:25 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/a/ansible/lib/ansible
  executable location = /tmp/a/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 17:08:05) [GCC 5.4.0]
```

##### CONFIGURATION

DEFAULT_FILTER_PLUGIN_PATH(env: ANSIBLE_FILTER_PLUGINS) = [u'/tmp/a/f']

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Minimal test case:

```
$ cat req.py
print(__name__)

class FilterModule(object):
    def filters(self):
        return {}
$ cat flt.py
print(__name__)

import req

class FilterModule(object):
    def filters(self):
        return {}
$ export ANSIBLE_FILTER_PLUGINS=$PWD
$ ansible -c local -m ping localhost 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ansible.plugins.filter./tmp/a/f/flt
 [WARNING]: Skipping plugin (/tmp/a/f/flt.py) as it seems to be invalid: No module named req

ansible.plugins.filter./tmp/a/f/req
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
$
```

```yaml

```

##### EXPECTED RESULTS

```
$ ansible -c local -m ping localhost
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ansible.plugins.filter.flt
ansible.plugins.filter.flt
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

(I believe that the `req` module not being mentioned is due to the module cache)

##### ACTUAL RESULTS

```
$ ansible -c local -m ping localhost 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ansible.plugins.filter./tmp/a/f/flt
 [WARNING]: Skipping plugin (/tmp/a/f/flt.py) as it seems to be invalid: No module named req

ansible.plugins.filter./tmp/a/f/req
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

Notice the weird values of `__name__` and `import req` failing, despite the files being in the same directory.

**Comment by abadger** [comment]
So a few things here:

* I've tested on Ansible's stable-2.3 branch where this code was not applied and Ansible errors in the same situation so this isn't a regression.

* I've tested changing the code you mention and it makes the warning message on your ```ansible -c local -m ping localhost``` test case disappear.  However, it doesn't make your actual use case work.  Ansible still fails to import req as seen when I run this playbook:

```
$ cat ../stable-2.3/44917.yml                                 *[devel]  (08:18:11)
---
- hosts: localhost
  gather_facts: False
  tasks:
  - debug:
      msg: '{{ test | mytest }}'

[pts/29@peru /srv/ansible/vanilla]$ ANSIBLE_FILTER_PLUGINS=/srv/ansible/stable-2.3/filter ansible-playbook /srv/ansible/stable-2.3/44917.yml -vvv
ansible-playbook 2.7.0.a1.post0 (devel 771768966f) last updated 2018/08/31 08:14:49 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/badger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /srv/ansible/vanilla/lib/ansible
  executable location = /srv/ansible/vanilla/bin/ansible-playbook
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts.mine inventory source with ini plugin

PLAYBOOK: 44917.yml *************************************************************************************************
1 plays in /srv/ansible/stable-2.3/44917.yml
ansible.plugins.filter.flt
 [WARNING]: Skipping plugin (/srv/ansible/stable-2.3/filter/flt.py) as it seems to be invalid: No module named req

ansible.plugins.filter.req

PLAY [localhost] ****************************************************************************************************
META: ran handlers

TASK [debug] ********************************************************************************************************
task path: /srv/ansible/stable-2.3/44917.yml:5
fatal: [localhost]: FAILED! => {
    "msg": "template error while templating string: no filter named 'mytest'. String: {{ test | mytest }}"
}
        to retry, use: --limit @/srv/ansible/stable-2.3/44917.retry

PLAY RECAP **********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

So this would be a new feature, rather than a bugfix.  The core team is also split as to whether this is a feature we'd want to enable or not.  We'd probably need to see code implementing this so we could have a debate about the actual implementation.

**Comment by thkala** [comment]
I'll admit to some confusion. Why compare with 2.3, which didn't even have the same loader infrastructure? FWIW, I first noticed this issue as a regression from 2.5.2, where it works just fine, to 2.6; I tracked down the cause with git bisect.

I also believe the the commit in question did not intentionally _not_ change the argument to `_load_module_source()` when the variable was effectively renamed from `name` to `basename` everywhere else.

Also, are you sure that you tested against 2.3? Your output has version strings from 2.7...

**Comment by relrod** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * You should prefer `module_utils` and/or fully qualified imports where possible. We are fine with relative imports not working.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
