### ISSUE TITLE
Ansible lineinfile duplicates line

### ISSUE THREAD

**Issue by zupo** [ansible/ansible#4531]
I have a simple file at /etc/foo.txt. The file contains the following:

```
#bar
```

I have the following ansible playbook task to uncomment the line above:

```
- name: test lineinfile
  lineinfile: backup=yes state=present dest=/etc/foo.txt
              regexp='^#bar'
              line='bar'
```

When I first run ansible-playbook, the line gets uncommented and the /etc/foo.txt now contains the following:

```
bar
```

However, if I run ansible-playbook again, I get the following:

```
bar
bar
```

If I run it yet again, then the /etc/foo.txt file will look like this:

```
bar
bar
bar
```

I believe these duplications of lines are a bug.

Happens on ansible-playbook 1.3.3 and 1.2.2.

**Comment by mpdehaan** [comment]
The above code says "add a line who'se value is bar unless there is a line which is commented out that has a bar.

I think you mean instead:

```
  lineinfile: backup=yes state=present dest=/etc/foo.txt
              regexp='^bar'
              line='bar'
```

can you confirm what your intent is with that part?

Thanks!

**Comment by zupo** [comment]
@mpdehaan snippet produces the following output:

```
#bar 
bar
```

Which is (in a sense) even better than replacing the commented line, as you keep the original line there. In that light I'm closing the issue.

Documentation for the module could be improved though, with more careful wording about how one should "read" the command.

Tnx for the help!

**Comment by joemaller** [comment]
I answered this on [SO](http://stackoverflow.com/questions/19390600), but I thought it was worth addressing here too. It's not a bug. 

To uncomment the line the task's regex needs to match both the commented _and_ uncommented line. Since it didn't match the uncommented line, the task assumed it wasn't there and added the line. Changing the regex to `regexp='^#?bar'` matches both states, replacing when commented and passing the uncommented line as already replaced.

Lineinfile can be a confusing module at first, but it's really powerful once you get your head around it.

**Comment by zabrahair** [comment]
I can not understand why the lineinfile will add aline even if none of line in file can match the regex pattern?

**Comment by ghost** [comment]
^This. It should not add lines if regex does not match(?).

For example, if there is a string in file "weekly" and the first run changes it to "daily", the next run will add "daily" line to the bottom of the file. Example:
 lineinfile:
    dest: /etc/logrotate.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?weekly', line: 'daily' }

edit: ok so i changed it to this and it works:
lineinfile: >
    dest=/etc/logrotate.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backrefs=yes
  with_items:
    - { regexp: '^#?weekly', line: 'daily' }

**Comment by spikerobinson** [comment]
I have to say @mpdehaan this behaviour is highly counterintuitive to those of us who are learning Ansible, and really not helped by the `lineinfile `[documentation ](http://docs.ansible.com/ansible/lineinfile_module.html)which is, as best, highly ambiguous on this point. I think most of us expect that, as per the documentation, the line matching the `regexp `will be **replaced** (that's the word used in the docs) if it matches (given that we want `state=present`). The documents actually say that. And, while the documents don't literally say this, the strong implication is that if the `regexp `is **not** matched, so there is nothing to replace, no action is taken. When the document says 

` For state=present, the pattern to replace if found; only the last line found will be replaced.`

The inference most people are going to understand from that is:

1. If the pattern is matched, replace the last matched occurrence with `line`
2. If the pattern is not matched (or no longer matched), do nothing. 

The last thing people will expect is 'if the pattern is not matched, add `line `at EOF'. This behaviour is similar to `insertafter `and `insertbefore`, which seem to 'default to non-idempotent', by design: if their regex is not matched, they insert at EOF or BOF, respectively. There isn't even an option for them to fail to insert, if the regex is not matched. 

I have been banging my head against this because it seems to make it almost impossible to get `lineinfile `to behave in an idempotent way. I have seen advice out there that basically says "attempt to use `lineinfile `only if all other methods have failed". I tend to agree with that sentiment! My last attempt is going to be to add an unused `backrefs `directive, not because I am going to actually use any backrefs, but only because backrefs (as documented) changes (inverts) the behaviour to more what I and others would expect, ie if the regexp match fails, no action is taken. 

There may also be some confusion as not so many people are familiar with the python flavour of regex and some may be thinking the caret ^ is a negation operator rather than a beginning of line token. 

It also does not help that none of the examples in the `lineinfile `documentation explain what effect will be created by the code shown. We really need cause and effect to be able to follow the documentation, I'm afraid the effect of `lineinfile `is **far** from 'self-explanatory'.

**Comment by spikerobinson** [comment]
Maybe as a compromise with the historical semantics of `lineinfile`, and to preserve backward compatibility of existing code (while also preserving the sanity of future users!), add an optional flag something like
`no-action-on-no-match`
which is probably the default behaviour that would be expected by new users, as opposed to old timers. 

I see @beinbliss above successfully applied the use of a spurious `backrefs `directive to solve the problem or persuade `lineinfile `to behave idempotently and as I think most people would expect. So maybe `backrefs `is a synonym for my proposed `no-action-on-no-match` flag.  :-)

**Comment by movie0125** [comment]
`
---
- hosts: 127.0.0.1
  tasks:
    - name:
      lineinfile:
        dest: foo.txt
        regexp: "msgid aaaa\nmsgstr bbbbb\n"
        line:      "msgid aaaa\nmsgstr bbbbb\n"
`

`
 echo > foo.txt
 ansible-playbook aa.yaml
 ansible-playbook aa.yaml
 ansible-playbook aa.yaml
 cat foo.txt 
msgid aaaa
msgstr bbbbb

msgid aaaa
msgstr bbbbb

msgid aaaa
msgstr bbbbb
`

**Comment by magic2k** [comment]
@movie0125 so what? use backrefs=yes, so new lines will not be added with following runs

**Comment by BryanJeterAL** [comment]
**### `'state: present'` is a directive that means that the `line:` will be present when done.**  

If you want to only replace a string when present, use `replace:` module.  That is what it is made to do.

`regexp:` is an **option** that allows you to replace the last match with `line:`, but if `lineinfile:` with `state: present` does not find `regexp:`, it will add the line.

`state:` is required.  It does what you tell it to do.

If you want to replace idempotently, use replace: module.

OR structure the regexp to match what you expect to replace.

    - name: test lineinfile
      lineinfile: 
        backup=yes 
        state=present 
        path=/etc/foo.txt
        regexp='^#?bar'
        line='bar'

In this case regexp: '^#?bar' will match ^bar or ^#bar or ^###bar (any number of # leading before the word bar).  This will act idempotently, and it accomplishes the two tasks the OP wanted to accomplish, ensuring  removal of one line and ensuring the other is there.

If you need to remove all instances of a string and ensure that only one remains, then use something like:

      lineinfile:
        path: /etc/foo.txt
        regexp: '^#bar'
        state: absent
      lineinfile:
        path: /etc/foo.txt
        line: 'bar'
        state: present
        insertafter: '^foo'   #optionally tell it where to put the line, else it puts it before EOF

And no, this is not idempotent, it will remove the line and put it back every time your run it subsequent to the first.  Which is why `replace:` is the preferred module to replace a line of text.

**Comment by spikerobinson** [comment]
In this case, "present" means "increment the number of occurrences by one",
which is pretty useless as a construct.

Yes we aware there are some crufty, complex and counter-intuitive
workarounds to this problem. We're aware the author of the language thinks
"idempotent" is a swear word.  We're aware of backward compatibility
challenges and the philosophy of conservatism.

Nonetheless, this is broken and it needs to be fixed.
