### ISSUE TITLE
Support user-local installations (--user in pip/easy_install)

### ISSUE THREAD

**Issue by SegFaultAX** [ansible/ansible#4533]
The ansible package currently in pypi is hard-wired to install into /usr/share/ansible which doesn't work if a user is trying to do a user-local install. It's generally considered a Best Practice :tm: to not modify the system installation of Python, and thus avoid `sudo pip install ...` at all costs.

I'd like to discuss the possibility of removing the hard requirement of installing system-wide and instead allowing user-local installations. Thoughts?

**Comment by mpdehaan** [comment]
Been asked for a lot, I'd ask you to think ansible more as an application and and not just an application you happen to know is Python.

Patches would be entertained though, though if you install this way you also would want to set up an ansible.cfg.

If it installed the libraries in the right place conditionally, and set up an ansible.cfg conditionally, I'd consider this.

All being said, I'm not going to leave the ticket open or work on this, so if someone wants to implement, please implement.

Generally speaking ideas for discussion should really to ansible-devel, so others can see and take part.

Closing this ticket since it's more of a discussion, but open to pull requests if they don't break the normal way it is installed without --user
