### ISSUE TITLE
Playbook's user not being honored

### ISSUE THREAD

**Issue by mmoya** [ansible/ansible#4536]
Trivial playbook:

```

---
- hosts: somelist
  user: root

  tasks:
    - name: test echo
      command: echo {{ item }}
      with_items:
        - foo
        - bar
```

with 1.3.3 both implicit `setup` and `command` tasks are run as _root_. With devel (afa781d6 at this moment) the implicit `setup` task is run as _root_ and the `command` task is run as the current user.

**Comment by mpdehaan** [comment]
This seems quite suspicious as if true, the world would be raining fire on me right now.

Please share the arguments and command line you are using to run this playbook as well as the entire contents of your inventory variables in the INI file or host_vars and group_vars for hosts in somelist where you are experiencing the error, as well as the output of running this with -v -v -v.

Thanks!

**Comment by mmoya** [comment]
I don't have any `{host,group}_vars` neither `~/.ansible.cfg` nor `/etc/ansible.cfg`. See http://pastebin.com/p2U8eHei.

I just bisected the code, the culprit is 4cee6a54. Bisection log in http://pastebin.com/qtuGdmkb.

Agree with the fire rain :)

**Comment by mmoya** [comment]
The following patch makes the playbook pass:

```
--- a/lib/ansible/playbook/task.py
+++ b/lib/ansible/playbook/task.py
@@ -135,7 +135,7 @@ class Task(object):
         # can be hashes and lists, not just scalars
         self.args         = ds.get('args', {})

-        self.remote_user      = ds.get('remote_user', play.playbook.remote_user)
+        self.remote_user      = ds.get('remote_user', play.remote_user)

         if self.sudo:
             self.sudo_user    = ds.get('sudo_user', play.sudo_user)
```

I'm not claiming at all this is a fix because I haven't explored the semantics behind `play.playbook.remote_user` vs. `play.remote_user` but it might give you a hint about where to look.

**Comment by mpdehaan** [comment]
I'm not sure there's a problem, but this in queue to see if anyone can even reproduce this.

I'm still skeptical, again, given the world would be raining fire on me right now were this true.

**Comment by resmo** [comment]
Hitting the same bug here.
- Using ansible 8a516d14795836a6fc3638354dd6aae3725260e3 alias devel latest
- Ansible node: ubuntu 13.04
- Manged node: debian 7

Playbook:

```
---
- hosts: 10.184.2.198
  remote_user: root
  tasks:
  - name: test autoinstall apt
    action: apt pkg=bash state=installed
```

Output:

```
ansible-playbook -i hosts apt.yml --ask-pass -vvv
SSH password: 

PLAY [10.184.2.198] *********************************************************** 

GATHERING FACTS *************************************************************** 
<10.184.2.198> ESTABLISH CONNECTION FOR USER: root
<10.184.2.198> EXEC ['sshpass', '-d4', 'ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/resmo/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '10.184.2.198', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1382344723.14-153546591304955 && echo $HOME/.ansible/tmp/ansible-1382344723.14-153546591304955'"]
<10.184.2.198> REMOTE_MODULE setup 
<10.184.2.198> PUT /tmp/tmpIEd59F TO /root/.ansible/tmp/ansible-1382344723.14-153546591304955/setup
<10.184.2.198> EXEC ['sshpass', '-d4', 'ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/resmo/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '10.184.2.198', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1382344723.14-153546591304955/setup; rm -rf /root/.ansible/tmp/ansible-1382344723.14-153546591304955/ >/dev/null 2>&1'"]
ok: [10.184.2.198]

TASK: [test autoinstall apt] ************************************************** 
<10.184.2.198> ESTABLISH CONNECTION FOR USER: resmo
<10.184.2.198> EXEC ['sshpass', '-d7', 'ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/resmo/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', '10.184.2.198', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1382344723.42-138059342882428 && chmod a+rx $HOME/.ansible/tmp/ansible-1382344723.42-138059342882428 && echo $HOME/.ansible/tmp/ansible-1382344723.42-138059342882428'"]
fatal: [10.184.2.198] => Authentication failure.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/resmo/apt.retry

10.184.2.198               : ok=1    changed=0    unreachable=1    failed=0   
```

Expected:

```
GATHERING FACTS *************************************************************** 
<10.184.2.198> ESTABLISH CONNECTION FOR USER: root

TASK: [test autoinstall apt] ************************************************** 
<10.184.2.198> ESTABLISH CONNECTION FOR USER: root
```

**Comment by phillipuniverse** [comment]
I can confirm this bug on the latest from devel (as of 5 mins ago, c876ce4). My fact gathering works fine, but executing commands fails. Debugging with -vvvv I can see that the fact gathering runs correctly with remote_user but just as the bug report states each play ignores the remote_user.

**Comment by resmo** [comment]
The fix of @phillipuniverse worked for me too.

**Comment by phillipuniverse** [comment]
@resmo not my fix, that was @mmoya :)

Reporting back to confirm that @mmoya's fix works for me. Echo that I'm not sure of the ramifications of it.

**Comment by jctanner** [comment]
reproducer:

<pre>
jtanner@u1304:~/issues/4536-per-task-remote-user$ fgrep el6 inventory 
el6.lab.net #ansible_ssh_user=root
jtanner@u1304:~/issues/4536-per-task-remote-user$ cat site.yml 
- hosts: el6.lab.net
  user: root
  gather_facts: False
  tasks:
    # force the connection as root@
    - shell: uname -a 
      remote_user: root
    # use the play's defined user
    - shell: uname -a 
</pre>

The second action fails because it connects as "jtanner" instead of root.

**Comment by jctanner** [comment]
@phillipuniverse @resmo @mmoya can you guys test with this patch instead?

<pre>
jtanner@u1304:~/ansible$ git diff
diff --git a/lib/ansible/playbook/task.py b/lib/ansible/playbook/task.py
index e37b2ce..9c4b40f 100644
--- a/lib/ansible/playbook/task.py
+++ b/lib/ansible/playbook/task.py
@@ -135,7 +135,11 @@ class Task(object):
         # can be hashes and lists, not just scalars
         self.args         = ds.get('args', {})
 
-        self.remote_user      = ds.get('remote_user', play.playbook.remote_user)
+        # check task's datastore for remote_user, use play's otherwise
+        if ds.get('remote_user') is not None:
+            self.remote_user      = ds.get('remote_user')
+        else:
+            self.remote_user      = ds.get('remote_user', play.remote_user)
 
         if self.sudo:
             self.sudo_user    = ds.get('sudo_user', play.sudo_user)
</pre>

It works on my side for all the various test cases I can think of, but I want to make sure I'm not missing anything.

My test playbook:

<pre>
- hosts: el6.lab.net
  user: root
  gather_facts: False
  tasks:
    # force the connection as root@
    - name: connect as root w/ task remote_user
      shell: uname -a 
      remote_user: root
      ignore_errors: True
    # use the play's defined user
    - name: connect as root from play
      shell: uname -a 
      ignore_errors: True
- hosts: el6.lab.net
  user: jtanner
  gather_facts: False
  tasks:
    # force the connection as root@
    - name: connect as root w/ task remote_user
      shell: uname -a 
      remote_user: root
      ignore_errors: True
    # use the play's defined user
    - name: connect as jtanner w/ play user
      shell: uname -a 
      ignore_errors: True
    - name: connect as nobody w/ task remote_user
      shell: uname -a 
      remote_user: nobody
      ignore_errors: True
</pre>

**Comment by jctanner** [comment]
correction:

<pre>
jtanner@u1304:~/ansible$ git diff
diff --git a/lib/ansible/playbook/task.py b/lib/ansible/playbook/task.py
index e37b2ce..79f2372 100644
--- a/lib/ansible/playbook/task.py
+++ b/lib/ansible/playbook/task.py
@@ -135,7 +135,13 @@ class Task(object):
         # can be hashes and lists, not just scalars
         self.args         = ds.get('args', {})
 
-        self.remote_user      = ds.get('remote_user', play.playbook.remote_user)
+        # check task's datastore for remote_user, use play's otherwise
+        if ds.get('remote_user') is not None:
+            self.remote_user      = ds.get('remote_user')
+        elif ds.get('remote_user', play.remote_user) is not None:
+            self.remote_user      = ds.get('remote_user', play.remote_user)
+        else:
+            self.remote_user      = ds.get('remote_user', play.playbook.remote_user)
 
         if self.sudo:
             self.sudo_user    = ds.get('sudo_user', play.sudo_user)
</pre>

**Comment by phillipuniverse** [comment]
@jctanner threw in your second proposed fix and it I can confirm that it resolves my issue.

**Comment by jctanner** [comment]
Alright, I'm going to commit that fix. If new related bugs crop up, I will iterate.

**Comment by mmoya** [comment]
Confirming @jctanner patch fixed the issue for me.
