### ISSUE TITLE
Support passing extra variables to template module

### ISSUE THREAD

**Issue by claco** [ansible/ansible#4546]
When passing a tasks output through register to consume it inside of templates, it would be nice to be able to abstract the templates themselves from module output changes or even just really complex dict structures.

For example:

```
- name: Build a server
  local_action: rax ...
  register: myserver
```

Then in templates:

```
{{ myserver.instances[0].accessIPv4 }}
```

This isn't terrible unless the rax module output changes (it's getting refactored now), or we dive into a deeper structure.

It would be nice to be able to alias variables passed into the template like so:

```
template: extravars={ ip: myserver.instances[0].accessIPv4 }
```

Then my the template can just do:

```
{{ ip }}
```

To expand this scenario further, it may be that the temple only needs a single ip address, but that may come from different places in the output, like public vs private ips, different interfaces, or different networks in OpenStack, etc.

**Comment by mpdehaan** [comment]
There's a reason this isn't.

The main reason is that the template module passes any arguments it doesn't understand to the file module to arrange file attributes.

If reusing templates multiple times, I would highly suggest using parameterized roles, because that allows defining different variables for different invocations, and was done for this purpose.

Ansible's way is not to pass variables daisy-chain-all-the-way down through where they are used, but rather to define things, and let them be accessed.

Hope this answers how this is and why this is. 

If you have further questions, please stop by the mailing list.

Thanks!

**Comment by claco** [comment]
Well, this is record. I went from "open a PR..should be easy" in #ansible to closed in 60 minutes.

So, given that a task stuffs the output of itself (such as ec2 or rax)  into variables using register, and this is compounded if you use with_sequence, this is what is dropped into that variable:

```
{'msg': 'All items completed', 'changed': False, 'results': [{'invocation': {'module_name': 'rax', 'module_args': ''}, u'instances': [{u'status': u'ACTIVE', u'accessIPv4': u'162.209.101.64', u'id': u'5abae8ad-6723-4d2e-bfb9-b58539d1caa9', u'name': u'swift-storage-server-1'}], u'changed': False, 'item': '1'}, {'invocation': {'module_name': 'rax', 'module_args': ''}, u'instances': [{u'status': u'ACTIVE', u'accessIPv4': u'162.209.126.37', u'id': u'61712695-c7f2-408e-871f-f5796f52be54', u'name': u'swift-storage-server-2'}], u'changed': False, 'item': '2'}, {'invocation': {'module_name': 'rax', 'module_args': ''}, u'instances': [{u'status': u'ACTIVE', u'accessIPv4': u'162.209.126.135', u'id': u'9681554e-59ca-46c3-a646-b76ae3c9b415', u'name': u'swift-storage-server-3'}], u'changed': False, 'item': '3'}]}
```

Is it really reasonable to be navigating this mess in templates, just to get ip address, or a specific variable 3-4 levels deep out of the contents of a task result?

```
[[ my_task_output.results[0].instances[0].accessIPv4 }}
```

I can't say I get how parameterized roles helps me here.

**Comment by iragsdale** [comment]
Have to agree with @claco here. I'm using a template to output multiple files based on a with_dict loop, and semantically it kind of sucks to use item.key or item.value all over the template - doesn't make them very reusable.

It would be nice to define "service_name" or "hostname" variables or whatever in the playbook where it's easy to see their relationship to the variable being looped, and have the templates use {{service_name}} instead of having to put "whatever_{{item.key}}" in the templates.

It really hinders the reuse of templates, because it marries them to a particular playbook structure, and the passthrough to the file module could be preserved if you just added a template_vars argument that would make its contents available to the template.

As a new user to ansible, I'd say the lack of this is really counterintuitive. Is it possible to reconsider this decision? I think it adds a lot to the reusability & understandability of templates.

**Comment by axos88** [comment]
Hello!

Just encountered this problem too.
Due to openSSL not being able to accept extendedusagetypes from the command line, only from config files, I need to do something similar to this:

```
- template: src=openssl_config.j2 dest=/tmp/openssl.cnf 
  vars:
    usage: serverAuth
- shell: openssl req -config /tmp/openssl.cnf.....

- template: src=openssl_config.j2 dest=/tmp/openssl.cnf 
  vars:
    usage: clientAuth
- shell: openssl  req -in {{item}} -config /tmp/openssl.cnf .....
  with_items: client_certs
```

**Comment by mpdehaan** [comment]
Hi all, old comments on tickets aren't something we are likely to see, but it's always welcome to bring up development topics on ansible-devel.

Please do so and we'll entertain the discussion.  Thanks!
