### ISSUE TITLE
Fetch module dest= relative path when using roles

### ISSUE THREAD

**Issue by markabey** [ansible/ansible#4566]
When fetching a file from a remote server, and specifying dest= to be a relative path, I would expect other modules to find it with the same relative path.

When using a role with fetch, it places a relative path to the playbook, yet other modules choose a relative path to the role files/ directory when looking for it..

My use case is collecting ssh pub keys from a remote server, and then adding them to other servers with the authorized_keys module. (lookup file)

eg
- fetch: dest=pubkeys/{{ansible_hostname}}/id_rsa.pub src=/home/user/.ssh/id_rsa.pub
- authorized_keys: user=anotheruser key=key="{{ lookup('file', 'pubkeys/' + item + '/id_rsa.pub') }}"
  with_items: list_of_hosts

**Comment by mpdehaan** [comment]
Not enough information is supplied here.

Please supply your playbook and the output as you see it running, as well as the output of "ansible --version"

Thanks!

(I do not yet have enough info to tell if this should be a bug or not)

**Comment by markabey** [comment]
I'm using ansible 1.3.2.

the "fetch" module places files in the playbook directory, and the other file based modules place them in the roles/<rolename>/files directory.

I've worked around this in the example above just by using ../../..
- fetch: dest=pubkeys/{{ansible_hostname}}/id_rsa.pub src=/home/user/.ssh/id_rsa.pub
- authorized_keys: user=anotheruser key=key="{{ lookup('file', '../../../pubkeys/' + item + '/id_rsa.pub') }}"

Very minor issue, probably not worth looking at really

**Comment by sumpfralle** [comment]
I am affected by the same issue.

My use case is the following:
1. create a private vpn key (for tinc) on the managed host
2. transfer the fresh public key of this host to the local directory
3. transfer all public local tinc keys (maybe including the fresh one) to the managed host

The following ansible statements are used for this purpose:

```
- name: create private tinc key
  command: creates={{ tinc_dir }}/hosts/{{ tinc_hostname }}
           tincd -n "{{ tinc_netname }}" --generate-keys=4096

- name: fetch remote public tinc key
  fetch: src={{ tinc_dir }}/hosts/{{ tinc_hostname }}
         dest=tinc/hosts/

- name: transfer all public tinc keys
  synchronize: delete=yes
               src=tinc/hosts/
               dest={{ tinc_dir }}/hosts/
  notify: restart tinc
```

Sadly the "fetch" statement stores the key relative to the playbook directory. The other modules that I am used to (copy, template, synchronize) work relative to the role directory. Thus I am surprised that fetch behaves differently. Maybe there is some reason for this behaviour that I do not understand?

markebey's workaround (storing the file below the playbook directory) does not work for me, since I need to store the file below the role directory. Currently I need to work around this issue by stating  the path of the role directory explicitely - obviously this makes role re-use harder.

I am using ansible v1.7.2 on Debian.

Please re-open this issue.

**Comment by dbohdan** [comment]
I ran into a similar issue to @sumpfralle's today with Ansible 1.9.3. I, too, would like to see this behavior changed so that `dest` paths for `fetch` be treated as relative to the role's `files` directory as they are with `copy`.
