### ISSUE TITLE
SmartOS IP address fact

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#4578]
On SmartOS, in contrast with the other OS's, it appears that the IP address object is an actual list of IPs.  Is that to be expected?

for example, in a smartos, I have to address it like this:

```
{{ ansible_net1['ipv4'][0]['address'] }}
```

where on linux

```
{{ ansible_net1['ipv4']['address'] }}
```

will suffice.

**Comment by mpdehaan** [comment]
probably not. 

As you have a SmartOS around, would you like to help standardize them?

**Comment by jsmartin** [comment]
Heh, "a smartos".  Sigh.  It was late.  Yes, I can help fix this bug.

**Comment by giorgio-v** [comment]
Should SmartOS output conform to the Linux one or the other way around? It seems to me that the Linux example would break with multiple IPs, correct?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
