### ISSUE TITLE
[RFE] Include mitogen plugin in ansible

### ISSUE THREAD

**Issue by stuarta** [ansible/ansible#45839]
##### SUMMARY
Include the mitogen plugin in ansible

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible

##### ADDITIONAL INFORMATION
Red Hat customer testing indicates that using the mitogen plugin improves
the performance of their playbook runs. Speedups of 35% have been seen
by this specific customer

Mitogen also regularly appears on the ansible lists with demonstrable
performance improvements for numerous users.

**Comment by pilou-** [comment]
Related pull-requests:
#45554 (from #40507): needs update (see #22370)
#45568 (from #45568): needs update
#45572 (from #40234): merged
#40348: requires the two previous pull-requests

**Comment by dw** [comment]
There is a significant amount of design discussion required before upstreaming is possible, and the team have avoided every attempt at progressing one, so please understand why I'm personally no longer interested in or willing to volunteer time for this.

Related action points supplied to Ansible team on 13 June for which no response was received.

- Make 'raw' command work without Python installed on the target. Super simple solution is just add an escape hatch/special case so when user is trying to use 'raw' to install Python, the real SSH client is called directly. It would also be quite simple to make it work with connection delegation
 - The serialization is still pickle. Every piece of expert advice is "don't ever do this", but we have mitigations against code execution. Memory exhaustion DoS is still possible. For preview that might be fine, but pickle still must go.
- Judgement call w.r.t. "always forking".
  - After 12+ weeks: only had 2 major user bugs due to not forking by default, both had non-hacky generalized fixes.
  - (October 2018): forking must be removed entirely, upstream Ansible also mixes threading (via multiprocessing) with forking, which explicitly breaks the guarantees offered by the host OS, unfixable deadlocks not only possible but likely
- Custom module_utils currently requires forking, alternative would be to add new errors to when user is doing something dumb (custom basic.py, some mymodule.py in different plugin directories with differing implementations). Adding errors would mean forking could be avoided even with custom module utils, but could conceivably break a presently working setup (but the fix for users is easy - just rename the conflicting modules)  https://github.com/dw/mitogen/issues/341
- 'Always forking' lacks optimizations to avoid constant recompilation. Easy to add this, but it's currently missing. We're still saving lots of time due to lack of interpreter startup, stdlib recompilation and SSH channel setup, but recompilation of ansible.* still happens. https://github.com/dw/mitogen/issues/187
- Mechanism for starting/stopping the connection multiplexer process needs replacement
    - There is no 'on shutdown' hook in the top-level process, so mux process notices shutdown by holding a socket open to the top-level process that gets closed when it dies - huge hack. That means mux process actually shuts down after Ansible, which is very noticeable with '-vvv', as logs are spammed over shell prompt after CTRL+C.
    - External multiplexer process exists simply because top-level process forks too much, leading to threading deadlocks. - No general fix exists in Python 2.x, but 3.x got many fixes for this.
    - Same problem exists, but has not been encountered yet, for use of the standard library "subprocess" package.
    - Every connection type could be made configurable somehow, and optionally just use Ansiballz as normal. Doesn't seem to be a need for it, but could make a very useful 'chicken bit' - e.g. "connection: local" is currently single-threaded.
- ~~Minor races visible in '-vvv' output: "error: no route to target for Message(...)", typically relating to logging forwarding. Probably super easy to fix, just hasn't been done yet.~~
- Logging framework integration could do with being tidied up or replaced, including
    - Move mitogen.* loggers to -vvvv output, add some more user-friendly 'high level' logs to ansible_mitogen.* and keep them visible in -vvv output.
    - Possible to entirely remove logging package use in favour of display framework, but current system seems to work quite well, and generalizes to core library's support for forwarding logging from children - including potentially in future making it much easier to debug Ansible modules
- Solution to dynamic subclassing ActionPlugin (mixins.py) to override module executor, file transfer etc.  Brian Coca might already have a design for that
- The amount of state transferred from mixins.py (on_action_run) to connection.py is totally out of control and violates layering. Not sure what a solution should look like.
    - For "connection delegation", connection.py receives a copy of hostvars (!) in order to reconstitute the delegated connection configuration. Could simply leave that feature out to begin with, since at least the "UI" parts have many different possible designs.
    - Could simply extend the Connection plugin interface to grant access to all this stuff, but that also seems like layering soup
- "Module Replacer" modules are not supported. Shouldn't be too much work to support if desired, or simply wait for user complaints.
- Maybe vendorize the core library to begin with? It's possible user-reported bugs will need core patches, and getting those upstream and on PyPI might cause needless inefficiency/roundtrips. One alternative is granting maintenance branch commit/release privs to some Ansible folk
- ansible_mitogen/module_dep_finder.py is a rewrite of the same functionality in ansible/executor/module_common.py. These could be merged away
- Various other pieces of rewritten functionality could be merged (eventually?). runner.py/planner.py split could potentially be reworked so it could also be used by Ansiballz. In every place where this happens, it was to improve code modularity, the rewritten semantics should be (close to) identical
- Overriding the built-in 'ssh'/'local'/etc. connection plugins. This is partially fixed already, in that Mitogen's versions are actually named "mitogen_ssh" etc., with a monkey-patch to rewrite the built-in ones to the Mitogen ones when the strategy is active.
    - Could simply drop the monkey-patch, but that means users require many needless edits to their playbooks to switch on/off support. Is there another option?
- Strategy situation. It should probably just be removed. The strategy is currently responsible for:
    - Starting the connection multiplexer
    - Installing monkeypatches we can hopefully get rid of, perhaps by adding some new hooks or similar? Might be replaceable with some small extensions to the callback plugin interface.
- Module renames: moving ansible_mitogen.* stuff into sensible mainline locations. Where should the Connection base class live? Current plugin loader doesn't make subclassing so easy. Perhaps split/refactor the whole thing somehow -- might be needed anyway to fix layering violations above.
- Probably many upstream Ansible code style violations, easy to fix, already started putting "from __future__" back in python3 branch
- Connection delegation -- subclass the WinRM plugin and teach it to make proxied HTTP requests. Tunnel those requests over the connection tree. Make things 'just work', except of course the ability to further sub-delegate using such a connection.
- Connection delegation doesn't (yet) support the synchronize module as it internally relies on 'ssh'. Fixing it entails some upgrades to the 'fakessh' component, to support all actions magically running transparently without modification, by tweaking PATH before executing the action.
- Core library: moving 'internals.rst' back into docstrings, so the library is actually readable/debuggable. These were (stupidly) moved out a long time ago in an attempt to remove the source code minifier, now the code is a nightmare for newbies
- Finish/update docstrings in ansible_mitogen.* that no longer make sense
- Design documentation: at the very least, a README.txt-style thing that gives a 3-10 foot overview of the whole mechanism so others can understand how it starts up, shuts down, process model, how it's supposed to work, and how to fix it if not. I want to write a full chapter for the core library docs to explain the design choices, and use the extension as a case study in the core library user guide, but not strictly necessary to get others productive.
- Debugging docs: just a cookbook for coping with strange hangs, what to look for in the logs, etc. E.g. a simple recipe for extracting a Python-level stack trace via gdb when MITOGEN_DUMP_THREAD_STACKS doesn't work.  Exotic hangs are pretty rare nowadays, but still very possible esp. during new feature development. Worst case scenario - hang with uncooperative bug reporters. Took >60 days to catch: https://github.com/dw/mitogen/issues/179
- Get core library test environment matching upstream test environment
- Get Ansible CI running under the Mitogen plugins.

**Comment by gundalow** [comment]
Myself and @dw happened to met yesterday at the London Ansible Meetup, we both agreed we will work together to progress this. There is a load of great work in Mitogen that Ansible can benefit from.

We can use this ticket to link to the various bits of work that will be going on: 

- [ ]  Ansible Architecture Diagram - Something that we are working on internally. This should help describe how some of these changes fit together
- [X] [Speed up VariableManager by preserving Templar state](https://github.com/ansible/ansible/pull/45572) based on @dw's MERGED
- [ ] [Speed up PluginLoader.all()](https://github.com/ansible/ansible/pull/45568) This #45572 should give a 25% runtime reduction in my many variable+many host test run, based on @dw's work
- [ ] Performance Tests - We need to ensure we don't introduce any regressions by any PRs (not just these), so we will be working on some metrics.
- [ ] [Remove special-case Display construction everywhere](https://github.com/ansible/ansible/pull/45554) or [singleton meta class for Display](https://github.com/ansible/ansible/pull/22370)

We can review each of the items from https://github.com/ansible/ansible/issues/45839#issuecomment-425976347 and raise an issue to detail how these should be implemented then added to the backlog and prioritized accordingly 

Once PRs are created for the above I'll update this comment so people can see the progress

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/issues/45839#issuecomment-430243355 updated to include test details, which is where we will be initially focusing.

**Comment by dw** [comment]
I've tried to reach sivel by IRC repeatedly for 2 weeks without success, despite an otherwise active IRC client. That means we're back in a position where there's no medium for planning discussion and the only avenue is blind PRs, and therefore no sensible mechanism to contribute.

I'd love to know if there is a better place to discuss ansible-baseline, otherwise feel free to strike these items off the list.

My initial take is that baseline is not in a good position to provide comprehensive metrics with sufficient granularity, and the design constraints ("any inventory") prevent writing good tests for some of the least efficient aspects of Ansible. These may be poor interpretations, but there is apparently no avenue to improve them.

**Comment by gundalow** [comment]
Remove special-case Display construction has been done in https://github.com/ansible/ansible/pull/48935

**Comment by pilou-** [comment]
@gundalow: 
- the first step was `move ansible-baseline to gh/ansible`, any news ?
- `Perf graphing callback plugin` has been merged (2nd step done)

**Comment by kustodian** [comment]
Any updates?

**Comment by MaciejKucia** [comment]
Wouldn't "affects_2.9" label would be appropriate here?

**Comment by dwt** [comment]
Any updates on this issue? Is there seems awfully quiet for such a useful library (using it every day)

**Comment by bcoca** [comment]
After reviewing backlog this week, we've decided to close this issue. This is not a rejection of the request but a reflection that this ticket is not a good way to keep track of the work that will be part of it. 

- We cannot 'just merge' mitogen as it breaks functionality (which you might not use, but others do).
- Some of the optimizations have already been added, others have always been configurable (pipelining)
- Many of the optimizations require a core redesign to be able to merge in a way that is still backwards compatible with all features.
- We will continue to look for opportunities to either add the improvements from mitogen or use a different implementation to achieve the same.

Discussions on this tipic will continue on IRC/matrix and different meetings, just not on this ticket as it is not the best place for it.
