### ISSUE TITLE
pkgng hangs and missing error messages

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4628]
ansible 1.3.3, client OSX, server FreeBSD 9.2 in a VM.

Inventory:

```
[freebsd]
bsdtest
```

`group_vars/freebsd`:

```
ansible_python_interpreter: /usr/local/bin/python
ansible_ssh_user: root
```

ssh keys have been installed in `/root/.ssh/authorized_keys`
## Problem 1: hanging when pkgng has not been used before

```
$ ansible bsdtest -i hosts.tst -m pkgng -a 'name=sudo state=present' -vvvv
<192.168.56.9> ESTABLISH CONNECTION FOR USER: root
<192.168.56.9> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/brian/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.56.9', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1382427566.86-186258707696278 && chmod a+rx $HOME/.ansible/tmp/ansible-1382427566.86-186258707696278 && echo $HOME/.ansible/tmp/ansible-1382427566.86-186258707696278'"]
<192.168.56.9> REMOTE_MODULE pkgng name=sudo state=present
<192.168.56.9> PUT /var/folders/f8/nggm8yyx2qvbflgmqg1zq5gh0000gp/T/tmpj3GfTB TO /root/.ansible/tmp/ansible-1382427566.86-186258707696278/pkgng
<192.168.56.9> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/brian/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.56.9', "/bin/sh -c '/usr/local/bin/python /root/.ansible/tmp/ansible-1382427566.86-186258707696278/pkgng; rm -rf /root/.ansible/tmp/ansible-1382427566.86-186258707696278/ >/dev/null 2>&1'"]
<< hangs at this point >>
```

There is no indication of any problem. On the target, ps shows a hung pkg process

```
root@freebsd92:~ # ps auxwww | grep pkg
root  2282   0.0  1.0 17564  2344  1  Ss+  11:57PM   0:00.00 csh -c /bin/sh -c '/usr/local/bin/python /root/.ansible/tmp/ansible-1382427566.86-186258707696278/pkgng; rm -rf /root/.ansible/tmp/ansible-1382427566.86-186258707696278/ >/dev/null 2>&1'
root  2284   0.0  0.8 14536  1952  1  S+   11:57PM   0:00.00 /bin/sh -c /usr/local/bin/python /root/.ansible/tmp/ansible-1382427566.86-186258707696278/pkgng; rm -rf /root/.ansible/tmp/ansible-1382427566.86-186258707696278/ >/dev/null 2>&1
root  2285   0.0  4.4 60000 10604  1  S+   11:57PM   0:00.04 /usr/local/bin/python /root/.ansible/tmp/ansible-1382427566.86-186258707696278/pkgng (python2.7)
root  2286   0.0  1.5 31292  3584  1  S+   11:57PM   0:00.00 /usr/sbin/pkg update
root@freebsd92:~ #
```

However you can see the reason if you run pkg interactively:

```
root@freebsd92:~ # pkg --help
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]:
```
- It would be very helpful if ansible could capture the response messages from the target system and display then, so this sort of problem can be easily diagnosed
- For this module in particular, it would be good to be able to test for this condition and handle it

Once pkg is installed, here's the help:

```
root@freebsd92:~ # pkg list
usage: pkg [-v] [-d] [-l] [-N] [-j <jail name or id>|-c <chroot path>] [-C <configuration file>] <command> [<args>]

Global options supported:
    -d             Increment debug level
    -j             Execute pkg(1) inside a jail(8)
    -c             Execute pkg(1) inside a chroot(8)
    -C             Use the specified configuration file
    -l             List available command and exit
    -v             Display pkg(1) version
    -N             Test if pkg(1) is activated and avoid auto-activation

```

So it looks like 'pkg -N' can be used to test.

```
root@freebsd92:~ # pkg -N
pkg: 1 packages installed
root@freebsd92:~ # echo $?
0
root@freebsd92:~ # 
```
## Problem 2: blank error messages

After letting pkgng bootstrap, the error changes to this:

```
$ ansible bsdtest -i hosts.tst -m pkgng -a 'name=sudo state=present'
bsdtest | FAILED >> {
    "failed": true,
    "msg": "failed to install sudo: "
}
```

The empty message is not helpful.

Again, if you run the command interactively, you find the real error message:

```
root@freebsd92:~ # pkg install sudo
Updating repository catalogue
digests.txz                         100%  316     0.3KB/s   0.3KB/s   00:00
packagesite.txz                     100%  860     0.8KB/s   0.8KB/s   00:00
Incremental update completed, 0 packages processed:
0 packages updated, 0 removed and 0 added.
pkg: No packages matching 'sudo' has been found in the repositories
root@freebsd92:~ # 
```

It turns out that since a security incident in 2012 there are [no longer any pkgng packages](https://wiki.freebsd.org/pkgng#Availability_of_binary_pkgs_for_Download). They are supposed to be available again from FreeBSD 10.

However this is a good opportunity to fix the error message collection in the mean time :-)

**Comment by tronner** [comment]
I worked around the first issue by creating a bootstrap playbook (role) that is included for all FreeBSD systems. This playbook uses the 'raw' action to:
- create /usr/local/{sbin,etc} if not exist
- if /usr/local/sbin/pkg does not exist: fetch latest pkg.txz from repo (url in variable; I use poudriere to build my own packages), unpack pkg-static from it, install downloaded pkg.txz with extracted pkg-static
- create /usr/local/etc/pkg.conf (echo 'packagesite: {{ packagesite }}' >/usr/local/etc/pkg.conf)
- install python

Now that pkg and python are installed you can use ansible in all its glory.

**Comment by dagwieers** [comment]
By default Ansible uses pseudo-tty's, so anything you run through Ansible will assume there is an interactive session and may issue a prompt to the user and wait for input. Whereas if you run it through ssh directly, there is no pseudo-tty and it behaves differently. Very unfortunate. #1801

**Comment by jctanner** [comment]
Taking some notes:

```
[root@freebsd ~]# /usr/sbin/pkg install -U -y iamnotarealpackge
pkg: No packages matching 'iamnotarealpackge' has been found in the repositories
[root@freebsd ~]# echo $?
0
```

**Comment by jctanner** [comment]
@tronner would you consider submitting a pull request for https://github.com/ansible/ansible/issues/4628#issuecomment-27953715 ?

**Comment by matburt** [comment]
Since pkg is a little busted in some version of FreeBSD and won't allow you to bypass the check we may need to test its state before running the command.  Not sure how feasible that is but the pkg man page has a safe recommendation that should work in all cases:

``` bash
if TMPDIR=/dev/null ASSUME_ALWAYS_YES=1 \
       PACKAGESITE=file:///nonexistent \
        pkg info pkg >/dev/null 2>&1; then
              # pkgng is installed and initialized
else
         # pkgng is not initialized
fi
```

**Comment by tronner** [comment]
@jctanner I don't have a patch. I can post my bootstrap playbook somewhere if that's what you mean.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
