### ISSUE TITLE
Using {% raw %} in templates does not stop jinja2 variable substitution

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#4638]
Using {% raw %} in templates does not stop jinja2 variable substitution
- ansible 1.4 -devel 4f139673865b713ad6b5e90aa79575a19b2b237e

[playbook.yml]

```

---
- name: "test raw template output"
  hosts: localhost

  vars:
    myvar: "foo"

  tasks:
    - local_action: template src="mytemplate.j2" dest="/tmp/myoutput.txt"
```

[mytemplate.j2]

```
Test: Preserve curly braces, and NOT perform variable substitution:

First Attempt:
{% raw %}
  - { include: "{{ myvar }}" }
{% endraw %}
```

[/tmp/myoutput.txt]

```
Test: Preserve curly braces, and NOT perform variable substitution:


First Attempt:

  - { include: "foo" }
```

NOTE: template output performs variable substitution even inside the {% raw %} block.

REFERENCE: Workaround suggested by Brian Coa https://groups.google.com/forum/#!topic/ansible-project/Bn1ZFu5Pfb0

**Comment by mpdehaan** [comment]
This is both a bug and not a bug.

As long as the templates will evaluate, they will evaluate recursively to allow variable nesting.

As a result, if the template changes it will keep going.

I think we just need to document this and not suggest raw/endraw.

**Comment by ghost** [comment]
I'm having the same problem trying to generate a YAML configuration file. Is there anything we can do until the issue is solved? Any workaround, even an ugly one?

Thanks

**Comment by mpdehaan** [comment]
Sorry for the late reply as I missed the notification email.

You could change the template delimiter using the parameters to the template module.

as the first line in your file:

#jinja2:variable_start_string:'[%' , variable_end_string:'%]'

**Comment by mpdehaan** [comment]
added a note about raw to the template module notes that will appear the next time docs are pushed

**Comment by juge2** [comment]
the mechanism with 
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
seems not to work anymore with ansible 1.6.6:
- template:

```
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
subsitude var1:  [% var1 %]
but not var2: {{ var2 }}
```
- template instance with ansible 1.6.0:

```
subsitude var1:  var1_content
but not var2: {{ var2 }}
```
- template instance with ansible 1.6.6: 

```
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
subsitude var1:  [% var1 %]
but not var2: var2_content
```

any idea where this got lost or how i can make it work again?

**Comment by diefans** [comment]
in ansible 1.6.3 this was also working

**Comment by yeukhon** [comment]
1.6.5 is the last version that this trick works. So we will need to diff the changes between 1.6.5 and 1.6.6.

**Comment by yeukhon** [comment]
So this appears to the root cause:

https://github.com/ansible/ansible/commit/3761bc113295e20771544491d007f1d328f40b99#diff-b03773d25210de2cbd9ad71d9c574881L83

https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#166-and-the-cradle-will-rock---jul-01-2014

So the security issue was noticed in 1.6.4+. What is the actual untrusted code execution that led to this change?

**Comment by yeukhon** [comment]
Never mind. Sorry for the spam noise. I found the code in 1.7.1 but only some overrides are whitelisted.
https://github.com/ansible/ansible/commit/de64bbdc5fab6db3c41a1bb4d34e75d706dad63c#diff-b03773d25210de2cbd9ad71d9c574881R84

**Comment by franklinwise** [comment]
The outcome of this thread is unclear to me. How do I output {{ in a template?

**Comment by franklinwise** [comment]
I figured it out. 

```
{{ '{{' }} some_thing_here {{ '}}' }}
```

**Comment by keitwb** [comment]
Since none of the escaping mechanisms work due to recursive rendering and the jinja2 delimiter comment trick no longer works is there any way to do this on Ansible 1.9?  I have tried everything listed here and nothing works.  

I really need to use `docker inspect` with a custom format.  I'm not using the docker module because I'm using docker compose to manage the containers, so I don't have to duplicate the container config in ansible.  Thus I don't have access to the `docker_containers` variable.

**Comment by iby** [comment]
@keitwb I did find a way to make it work, it required crazy escaping skills and looked really monstrous, (un)fortunately can't remember how it was done. I went other way around this issue, because I needed to do several lookups on the host I just wrote a shell script with all that logic, which printed the results into stdout. Task would then register variables line by line and proceed as normal. This is a way cleaner solution than writing semi-binary code in task directly.

``` yml
- name: get facts
  script: "get_facts.sh"
  register: result

- name: set foo fact
  set_fact: foo="{{ result.stdout_lines[0] }}"
  when: result.stdout_lines[0]

- name: set bar fact
  set_fact: bar="{{ result.stdout_lines[1] }}"
  when: result.stdout_lines[1]
```

**Comment by keitwb** [comment]
Thanks, I ended up resorting to using grep/awk to parse the full inspect output since that didn't require escapes.  Not very pretty or robust but it worked for my small usage.  Definitely if I have to do more with docker inspect I'm going to write a docker facts module or try and use a [preexisting one](http://patg.net/ansible,docker/2014/07/10/ansible-docker-facts/).

**Comment by iby** [comment]
Cool. By the way, jq is really awesome for parsing json, when available.

**Comment by slmingol** [comment]
This method worked fine for me using this version of ansible:

```
$ ansible-playbook --version
ansible-playbook 2.0.0 (devel 974b69d236) last updated 2015/09/01 13:37:26 (GMT -400)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/01 13:37:29 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/01 13:37:29 (GMT -400)
  config file = /Users/me/projects/git_repos/devops/ansible/playbooks/proj/ansible.cfg
  configured module search path = None
```

I then constructed a templated file like this:

```
$ more roles/escape_jinja_tmpl/templates/somefile.j2
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
subsitude var1:  [% var1 %]
but not var2: {{ var2 }}
```

This resulted in this file getting copied to my remote:

```
$ more /tmp/somefile
subsitude var1:  contents-of-var1
but not var2: {{ var2 }}
```

**Comment by surabujin** [comment]
Where exactly we need recursive template evaluation?

**Comment by bdgscotland** [comment]
I can confirm that this works:
`content="{{ '{{' }} variable_name_inserted_into_dest {{ '}}' }}/mirrors/{{ variable_evaluated_for_dest }}"`

**Comment by marcjay** [comment]
I can confirm that when I tested this now with Ansible version 2.3.1.0, the following worked when added to the top of the template file:
```
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
```
Input:
```
{{range $tag, $service := service "[% service_name %]" | byTag -}}
```
Output:
```
{{range $tag, $service := service "test-service" | byTag -}}
```

**Comment by vide** [comment]
FWIW, I can confirm that 
```
#jinja2:variable_start_string:'[%' , variable_end_string:'%]'
```
still works perfectly with Ansible 2.6

**Comment by reiser** [comment]
> I can confirm that when I tested this now with Ansible version 2.3.1.0, the following worked when added to the top of the template file:
> 
> ```
> #jinja2:variable_start_string:'[%' , variable_end_string:'%]'
> ```
> Input:
> 
> ```
> {{range $tag, $service := service "[% service_name %]" | byTag -}}
> ```
> Output:
> 
> ```
> {{range $tag, $service := service "test-service" | byTag -}}
> ```

wonderfull hack thank you :-)
