### ISSUE TITLE
Callbacks should be able to fail the ansible(-playbook) execution

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible#46397]
##### SUMMARY
Callbacks receive all execution events and they are able to implement business logic based on the results it gets or external circumstances.
If a callback determines that the playbook execution should be halted based on this business logic, it should be able to do it -- similar to how a module might return an exit_json with data, status codes, etc.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
callback plugins

##### ADDITIONAL INFORMATION
As an example, a callback might be keeping checks on external monitoring (nagios, sensu, prometheus, etc.) and if it starts seeing issues with hosts the playbook is running on, it might decide that the playbook execution should be stopped.

Another example would be a callback that provides logging or auditing capabilities and it might be undesirable to continue the playbook execution if the callback is not able to log successfully.

**Comment by dmsimard** [comment]
Discussed this with @bcoca this morning after a user asked if doing something like this was possible.

**Comment by bcoca** [comment]
possible, maybe, desirable, no.

callbacks are not meant to change play flow, that is what strategy plugins are for.

I meant we could add a toggle so callback exceptions outside of stdout (which are currently a warning) could be converted into an error as in some cases you can consider 'reporting' as indispensable and want Ansible to fail if you are unable to communicate the actions taken.

**Comment by bcoca** [comment]
discussed this in backlog review, the thought it callbacks are only for display/handling event data and should not feedback into play execution. A strategy might be a better option for a plugin that handles playbook/play execution.
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We discussed this in backlog review, the thought it callbacks are only for display/handling event data and should not feedback into play execution. A strategy might be a better option for a plugin that handles playbook/play execution.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourageopen dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
