### ISSUE TITLE
Dependent roles may have variables overwritten by role that includes them

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#4641]
Roles do not use their variable definitions when actvated via the role dependency mechanism.
- ansible 1.4 -devel 214b0b052c3d54b58a531b0f7fb401ec3c0229f5
# Description
1. alpha role depends on beta role
2. Each role provides a unique value for a variable named 'port' <role>/vars/main.yml
3. When beta role is executed (aka **"active"**) via the role dependency mechanism, the role uses variable definitions from alpha role instead of its own definitions (roles/beta/vars/main.yml). 
4. It has been noted that active roles use their variable definitions [unless higher precedent variables are passed via --extra-vars, or variable definitions in the base playbook]
   - "... within a role, the variables in roles/y/vars/main.yml are guaranteed to be applied to that specific role, just as if they were parameters explicitly passed to the role." ( https://groups.google.com/d/msg/ansible-project/0JIrNlnRXuI/tx1-inKYoUQJ )
# Demonstration

https://github.com/briceburg/ansible-variable-scoping/tree/master/simple_vars

**Comment by mpdehaan** [comment]
In queue for investigation.

**Comment by briceburg** [comment]
Got it -- thanks for looking. 

Of note; issue #4642 is not a duplicate of this bug, and shows different and much stranger behavior, although perhaps the fix for this issue will address both. 

This issue deals with "vars" definitions (<role>/vars/main.yml); while #4642 deals with "default" definitions (<role>/defaults/main.yml). Defaults work as expected (meaning the dependent roles use their own definitions) -- until you include tasks. In this case the dependent role uses definitions from an upstream role (meaning scope changes for tasks that are included in tasks/main.yml).

**Comment by jctanner** [comment]
@briceburg This is expected behavior for how roles are executed. If alpha depends on beta, it will execute beta by passing in alpha's variables. If you declare beta as a top level role and allow_duplicates in it's meta, beta will execute twice ... once with it's own vars and a second time with alpha's vars.

**Comment by briceburg** [comment]
@jctanner Please review issue https://github.com/ansible/ansible/issues/4642  -- it has very strange and different behavior && was closed prematurely.

**Comment by aboyett** [comment]
The problem as I see it is that dependent role variables in this example are behaving more like defaults than vars.

from docsite/rst/playbook_variables.rst:

> Next up: learning about role variable precedence.
> ...
> 
> Ok, so if you are writing a redistributable role with reasonable defaults, put those in the 'roles/x/defaults/main.yml' file.  This means the role will bring along a default value but ANYTHING in Ansible will override it.  It's just a default.  That's why it says "defaults" :)
> See `intro_roles` for more info about this::
> 
> if you are writing a role and want to ensure the value in the role is absolutely used in that role, and is not going to be overridden by inventory, you should but it in roles/x/vars/main.yml like so

@jctanner does the above documentation also apply to dependent roles?

Given the following summary of the example:
- role alpha depends on role beta
- role alpha defines `port` to be 'alpha_port' in roles/alpha/vars/main.yml
- role beta defines `port` to be 'beta_port' in roles/beta/vars/main.yml

I would expect to see the following output:
- role alpha is run, and executes role beta, within the alpha->beta scope `port` should be 'beta_port'
- role alpha then runs itself, within the alpha scope `port` should be 'alpha_port'

Instead, when run in ansible 1.4.4: `port` is 'alpha_port' in both the alpha->beta and alpha scopes

If this is the expected behavior, the documentation needs to be updated to indicate the special case behavior of role vars when the role is called as a dependency.
