### ISSUE TITLE
Conditionals abort when using string value for truth

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4650]
ansible 1.3.3

I would expect "when" conditions to treat empty string/list values as false, and non-empty strings/lists/dicts as true, in the same way as jinja2.

However this does not work.

```
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact: foo=""
    - action: ping
      when: foo
```

Result:

```
$ ansible-playbook bug.yml -i localhost.inv

PLAY [localhost] **************************************************************

TASK: [set_fact foo=""] *******************************************************
ok: [localhost]

TASK: [ping] ******************************************************************
fatal: [localhost] => error while evaluating conditional: {% if  %} True {% else %} False {% endif %}

FATAL: all hosts have already failed -- aborting
```

Workaround for string values:

```
      when: foo != ""
```

**Comment by mpdehaan** [comment]
So I think it's evaluating the bare variable because it thinks you are passing a conditional in like:

vars:
   saved_conditional:  "x == 2"

So it would evaluate the saved conditional first, like so:
- action: ping
  when: saved_conditional

That all being said, putting this in the queue to look at, to see if it's still a thing on 1.4 devel

**Comment by mpdehaan** [comment]
Ok so yes, it's like I said, if the condtional is a variable, and bare like that, we're expecting a reusable conditional expression in foo, and there's not one.

I would think this is working like we want.

I have confirmed the above is operational using the previous example.
