### ISSUE TITLE
Keep track of roles applied across plays

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible#4656]
We have a play of plays that we run against our entire infrastructure.  Each role has an implied dependency on the common role (it was created before role dependencies existed). As part of this play of plays, we run the common play first against all hosts with as many forks as possible. The play of plays then continues with a play for each role.

If we were to link the common role dependency to each role, ansible would run the common role again in each play.  If ansible remembered that the role had been applied previously throughout this play of plays, that would solve this problem.

An alternative is to not use role dependencies, but this means that we lose the ability to keep most handlers (among other things) in the common role and call them from the child roles.

**Comment by pgehres** [comment]
@mpdehaan, @jimi-c, @tgerla - as discussed yesterday

**Comment by jimi-c** [comment]
Thanks!

**Comment by jimi-c** [comment]
@pgehres if you'd like to test the above PR, it should do what you were wanting. I've tested with multiple roles that each include a common role, and can get that to execute only once even when using tags.

**Comment by pgehres** [comment]
Awesome! Thanks.  I will try and give is a test in the next few days

**Comment by jimi-c** [comment]
I went ahead and merged it in, so just let me know if you run into any problems with your testing.

**Comment by pgehres** [comment]
That works for me. Thanks!

**Comment by jimi-c** [comment]
@pgehres I'm going to have to back this out, due to some unexpected side-effects regarding handlers (#6322). Also, as it stands subsequent plays don't account for the fact that later plays may have different inventory sets, so it may lead to some odd results for users. So I'll re-open this and we'll revisit it later if we can work out the nuances of different plays.

**Comment by pgehres** [comment]
Interesting, FWIW, the way I had imagined this (no idea is this is possible in the current architecture) was to simply keep a manifest of hosts and the roles that had already been run in this "play of plays."

**Comment by mpdehaan** [comment]
I'm not positive we want to do this architectually myself.

However there is a recent pull request that added the idea of a "register_append" construct, where it would be possible to do things like add to a host variable "applied_roles", which should provide a way to implement this.

This pull request is https://github.com/ansible/ansible/pull/6488 and I'd rather solve this problem through the existing logic rather than make the role application understand cross-cutting play concerns, which could quickly get someone into a gotcha scenario.
