### ISSUE TITLE
with_items does not work with prefixes

### ISSUE THREAD

**Issue by alinnow** [ansible/ansible#4666]
With a task like

```
- name: Ensure PHP modules are installed
  yum: pkg=php54-{{ item }} state=present
  with_items:
    - gd
    - mbstring
```

Running `ansible-playbook --check` results in an error when checking the state of the second item:

```
TASK: [Ensure PHP modules are installed] **************************************
failed: [myhost] => (item=gd,mbstring) => {"changed": false, "failed": true, "item": "gd,mbstring,mcrypt,mysqlnd,pdo,soap,xml,xmlrpc", "rc": 0, "results": ["php54-gd-5.4.20-1.ius.el6.x86_64 providing php54-gd is already installed"]}
msg: No Package matching 'mbstring' found available, installed or updated

FATAL: all hosts have already failed -- aborting
```

The package `php54-mbstring` is actually installed, so it would appear that ansible is checking the package name incorrectly.

Changing the task to

```
- name: Ensure PHP modules are installed
  yum: pkg={{ item }} state=present
  with_items:
    - php54-gd
    - php54-mbstring
```

allows the playbook to run correctly, but this isn't ideal, especially with longer lists

**Comment by jimi-c** [comment]
This is a consequence of an improvement used for the apt and yum modules, where the list is concatenated together and sent to the command in one shot rather than executing each install one by one (which would be painfully slow for long lists of packages). It may be possible to add in a check that if the name field is not simply item, to prepend whatever's there to each item as it's joined together.

**Comment by alinnow** [comment]
I thought as much. The optimisation does make a lot of sense, but yeah, it should be transparent.

**Comment by jctanner** [comment]
This should be fixed by the proposed patch in https://github.com/ansible/ansible/issues/4665#issuecomment-27106039
