### ISSUE TITLE
Trying to use apt_repository with PearOS8, which fails

### ISSUE THREAD

**Issue by josh-at-knoesis** [ansible/ansible#4670]
PearOS8 is based on Ubuntu 13.04.

I want to be able to add the PPA for things like Ansible to PearOS using apt_respository.

Here's the error I get:

```
TASK: [Add PPA repository for Ansible] **************************************** 
failed: [myhost.example.org] => {"failed": true, "item": ""}
msg: Module apt_repository supports only Debian and Ubuntu.

FATAL: all hosts have already failed -- aborting
```

Here's some the output of 'ansible -m setup <PearOS host>'

```
        "ansible_distribution": "Pearos",
        "ansible_distribution_release": "Rocha",
        "ansible_distribution_version": "8.00",
        "ansible_lsb": {
            "codename": "Rocha",
            "description": "Pear OS 8", 
            "id": "PearOS", 
            "major_release": "8",
            "release": "8.00"
        }, 
```

Thanks,
Joshua

**Comment by jimi-c** [comment]
From a python shell, could you do the following and post the results?

<pre>
>>> import aptsources.distro
>>> aptsources.distro.get_distro()
</pre>

**Comment by mscherer** [comment]
Also, see https://github.com/ansible/ansible/issues/4587 for a similar type of bug/discussion. I think the issue is the same, ie by changing the code name, this break python-apt, and the issue is on python-apt side.

**Comment by mpdehaan** [comment]
Sounds like it needs to do something like what was done for Mint to me.

**Comment by jimi-c** [comment]
Ahh, I didn't know this had come up before with Mint.

**Comment by josh-at-knoesis** [comment]
Thanks all.

```
test@test-1:~/DevOps/ansible$ python
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aptsources.distro
>>> aptsources.distro.get_distro()
<aptsources.distro.Distribution object at 0x7f296b762f90>
>>> 
```

**Comment by bcoca** [comment]
So its detecing it as a simple debian type distro (otherwise you would see
"aptsources.distro.UbuntuDistribution"). It might be worth creating our own
test for ppa support.

**Comment by mscherer** [comment]
Well, for mint, we didn't do much. Python-apt use the codename to see what it should support 
https://bazaar.launchpad.net/~mvo/python-apt/debian-sid-mirrored/view/head:/aptsources/distro.py#L472

and it hardcode Ubuntu for ppa. The only way to fix that is to accept ppa support for every distribution in ansible, no matter what python-apt say, and looking at the code, to have a huge correspondence structure to convert from pearos and mint codename to the corresponding codename of Ubuntu in order to make it work correctly on 
https://github.com/ansible/ansible/blob/devel/library/packaging/apt_repository#L298

Personally, I think this should be done in python-apt correctly rather than worked around in ansible, but this also mean people would have to wait for the fix, and that the fix may not be accepted.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
