### ISSUE TITLE
Installer does not allow to influence module path (/usr/share/ansible)

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#4831]
We have the issue that we would like to install ansible as a user. And we cannot use setup.py to install Ansible because /usr/share/ansible is hardcoded. We can influence the runtime to look elsewhere, but the installer does not allow us to influence where it **should** be installed.

```
$ python setup.py install --home=/srv/ansible/ansible-1.3.4
...
creating /usr/share/ansible
error: could not create '/usr/share/ansible': Permission denied
```

Am I doing it wrong ? Or have I missed something ?

**Comment by sivel** [comment]
I'm not sure it is the solution you are looking for, however since setup.py uses `DEFAULT_MODULE_PATH` from `ansible.constants` you can influence the location utilizing the `ANSIBLE_LIBRARY` environment variable, such as something like:

`ANSIBLE_LIBRARY=/srv/ansible/ansible-1.3.4/modules python setup.py install --home=/srv/ansible/ansible-1.3.4`

Which will of course require you to continue utilizing `ANSIBLE_LIBRARY` during runtime, or to specify it in ansible.cfg as something like:

```
[defaults]
library = /srv/ansible/ansible-1.3.4/modules
```

**Comment by mpdehaan** [comment]
Ansible isn't a python library, it's a complete systems management program -- and modules don't have to be written in just python.

What you are asking for are to move the location of some data files.

As such this seems like something you'd really want to do with _packaging_, rather than pip.

I'd be happy to entertain patches to make other flags in pip work differently, provided they do not break existing packaging.
