### ISSUE TITLE
shell module: option for interactive/login shell

### ISSUE THREAD

**Issue by brafales** [ansible/ansible#4854]
I was trying to execute a `shell` command using a specific user. I was having problem to execute that shell command with the same invocation method as when the user normally logs in (`login shell`).

The way to solve it was to specify a `-i` at the end of the `sudo_user` parameter like this:

``` yaml

---
- name: rbenv | check ruby installed
  shell: rbenv versions | grep {{ ruby_version }}
  sudo_user: rails -i
  register: ruby_installed
  ignore_errors: yes
```

It'd be nice if the `shell` module had an option to specify the shell invocation method.

**Comment by jokeyrhyme** [comment]
@benbarclay and I would also dearly love this feature.

**Comment by mpdehaan** [comment]
sudo: username or remote_user: username will allow execution as a specific user.

We generally don't like to trust the user's environment in creating a reliable execution environment.

Look to the "environment" keyword for passing certain parameters to commands.

http://www.ansibleworks.com/docs/playbooks_environment.html#

**Comment by jokeyrhyme** [comment]
For my use cases, executing the login environment is the most convenient way to have `rbenv` and `nvm` initialised and `ruby` and `node` installed with this tools available in the PATH.

**Comment by jokeyrhyme** [comment]
It also makes it possible to use the `npm` and `gem` ansible modules with `rbenv` and `nvm`.

**Comment by mpdehaan** [comment]
Going through old tickets...

While I understand the underlying issues here Ansible is intended to be a centrally managed automation system.   The login shell of the user is not to be something that is required for managing the environment.

As such, it seems possible to set the required environment variables with the environment keyword and then regardless of the user's environment things will continue to function.

That being said, I'm not entirely opposed to the idea, so I'm open to pull requests to implement something like this if people want to attempt it.

It should probably be a parameter on the task like "interactive_shell: True" and then the connections would have to know about it.

**Comment by jkeskikangas** [comment]
@jokeyrhyme As a workaround, you can just execute `sudo -iu` as a command:

```
- name: "Set default ruby version to {{ rbenv.ruby_version }}"
  command: "sudo -iu {{ rbenv.user }} rbenv global {{ rbenv.ruby_version }}"
```

@mpdehaan how do you see, could we add `sudo_options: -i`, or `sudo_login: True`? I might be interested in implementing the feature, if seen feasible.

```
       -i [command]
                   The -i (simulate initial login) option runs the shell specified in the passwd(5) entry of the target user as a login shell.  This means that login-specific
                   resource files such as .profile or .login will be read by the shell.  If a command is specified, it is passed to the shell for execution.  Otherwise, an
                   interactive shell is executed.  sudo attempts to change to that user's home directory before running the shell.  It also initializes the environment, leaving
                   DISPLAY and TERM unchanged, setting HOME, MAIL, SHELL, USER, LOGNAME, and PATH, as well as the contents of /etc/environment on Linux and AIX systems.  All other
                   environment variables are removed.
```

**Comment by science** [comment]
Just more input that Ansible not dealing with this makes it very unpleasant for users of Ruby rbenv and similar tools (I've read some python people on lists with similar issues).

The problem is that at its core rbenv and similar tools _relies_ on local environments, and it's the tools job to set up the environment correctly. So when Ansible by-passes the environment setup, you're taking us two steps backwards in terms of automation.

I totally get that for many users, if Ansible enters the environment as a login shell, it will get screwed up (because, if for no other reasons, some users don't use dedicated Ansible deployment users that are isolated from manual logins). 

Which is why sourcing the environment should not be the default. But for users who need it, we should be able to access it without some hack as described above.

And for the record, my alternative hack is to prefix "source /etc/profile" onto every command:

```
- shell: . /etc/profile && rbenv install 2.1.5
```

This works too, but I can't see the point in making me use Ansible in this way. Linux has built ways to solve this problem: a login script sequence. In cases where Ansible deployments use dedicated user accounts, it makes complete sense to rely on these sequences, in my opinion.

If you don't want option sprawl, simple let us set a default shell that accepts parameters. For example, if "executable" accepted parameters, that would work fine:

```
shell: echo Should load environment..
args:
  executable: /bin/bash -l
```

Right now, Ansible blows up when the executable is given parameters, but if you could just fix that, I think a bunch of us could get back to writing scripts that add value to our projects. Thanks..

**Comment by alakra** [comment]
:+1: @science

**Comment by barraponto** [comment]
@science would a wrapper script suffice? a shell script that actually invoked the shell with parameters?

**Comment by science** [comment]
@barraponto - from my perspective it would all depend on how the wrapper script were invoked/exposed in Ansible. My main complaint is mainly that I need to build esoteric parameterization into our scripts, when Ansible represents itself as offering the opposite.

So if you expose a wrapper script as something I have to invoke and manage, then I can't see how it's better than what I've got now. But if you make expose it in a simple Ansible-like, then it serves to clean up all my code and make it work more as Linux is supposed to work (and prevent the inevitable cargo-culting of my code that other devs will do eventually)! :)

For example if you created a new command called "login_script" or "login_shell" I'd just start using that. But I think I read above from DeHaan that he doesn't want more option/command sprawl. So I'm not clear how you would expose a shell script that invoked the shell with parameters in Ansible. Any thoughts?

Thanks for inquiring about this.

**Comment by barraponto** [comment]
@science well, you can write your own plugin and share it. we're not limited to core and extras, there are other (less used) plugins out there. Subclassing from command might work.

**Comment by itsSaad** [comment]
Any solution i could use without a hacky way?

**Comment by dmitrym0** [comment]
That was very well written @science, thank you :+1:.

I'm here looking for the `rbenv` solution as well. If I installed a custom ruby using `rbenv`, what is the recommended way of using that particular ruby with the `gem` module say? 

Right now I do 

```
- name: Install bundler
gem: name=bundler state=present executable={{ gem_installed_path }}
```

where `gem_installed_path` is hardcoded. Doesn't seem that great.

**Comment by thom-nic** [comment]
I have this same issue because I use both `rbenv` and `nvm` to install my app's dependencies under the unprivileged application user.

As a variant to @science's proposal above, this could be solved by adding a `login` option to the `shell` module.  For example: `shell: bundle install chdir={{app_dir}} login=yes`. That would be slightly more succinct than `executable: /bin/bash -l` and serves a more narrow purpose.

I currently work around the issue by wrapping all of the necessary commands in a `bash -lc` invocation.  Here's an example:

``` yaml
- name:  Install required nodejs version
  shell: bash -lc "{{ item }}"
         chdir={{ client_dir }}
  with_items:
    - nvm install
    - nvm alias default {{ nodejs_version }}
  register:     nodejs_install_result
  changed_when: nodejs_install_result.stderr.find("is already installed") < 0

- name:  Install npm global packages
  shell: bash -lc "npm i -g {{ item }}"
         chdir={{ client_dir }}
  with_items: "{{ nodejs.global_packages }}"

- name:  Run npm tasks
  shell: bash -lc "{{ item }}"
         chdir={{ client_dir }}
  with_items:
    - npm install
    - npm run build:prod
```

The above is an `include`d script that's run as 

```
- include:    client.yml
  sudo:       yes
  sudo_user:  "{{ app.user }}"
```

FWIW since someone proposed a `sudo_user: rails -i` solution: I have never got `sudo -u rails -i` to give me a proper login prompt/env, I always have to do `sudo su - rails`.  So I wonder if a `sudo_user: rails -i` solution would work.
