### ISSUE TITLE
FR for cron module: add jobs into /etc/crontab

### ISSUE THREAD

**Issue by nextus** [ansible/ansible#4881]
I'm using singular file for all my cron jobs for all users and this is /etc/crontab. I'm looking toward manage this tasks by ansible cron module but it's turned up I couldn't specify cron_file outside the /etc/cron.d/ and I can't write into /etc/crontab jobs for nonroot users.

**Comment by jctanner** [comment]
@nextus the .d structure is something a lot of daemons have moved to or are moving to because it allows less magic manipulation of file contents. Is there a reason you can't use cron.d to handle your needs?

Based on what you've described, you may have better luck using lineinfile.

**Comment by bcoca** [comment]
@jctanner, cron.d is not available everywhere, cron.{daily,weekly,monthly}
can be implemented using /etc/crontab, but cron.d needs support in the cron
executable.

**Comment by jctanner** [comment]
We can work on this as a feature request. @nextus pull requests are welcomed.

**Comment by mpdehaan** [comment]
I'm going to classify this as a bug report so this can get some addition, I would think it would be easy to let this take a path parameter to allow this.

**Comment by jjshoe** [comment]
It already takes a path parameter, just needed a little love to let you specify an absolute path.

**Comment by AnneTheAgile** [comment]
This 2013 ticket looks like it can be closed? The fix added; 
`A path begining with '/' will be treated an an absolute path.`

//AnneTheAgile

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by AnneTheAgile** [comment]
As I wrote above, I believe this ticket is ok to close. Cron is a Core module. If we wanted to continue discussion, it would go here; https://github.com/ansible/ansible-modules-core/issues?q=cron

For my cross-ref, I did add a mention of it here; 
https://github.com/ansible/ansible-modules-core/issues/47

**Comment by tpo** [comment]
@AnneTheAgile no, actually this issue is not OK to close, because the code has not been merged into the ansible repo AFAICS.

**Comment by tkaymak** [comment]
:+1: I'm still having this problem with ansible version 1.9.2

**Comment by tyleha** [comment]
Not fixed in devel branch 2.1.0, either.
