### ISSUE TITLE
win_security_policy fails although the policy is changed

### ISSUE THREAD

**Issue by satken2** [ansible/ansible#48849]
##### SUMMARY

win_security_policy reports "failed" status but security policy is successfully updated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_security_policy

##### ANSIBLE VERSION

```paste below
2.7
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Ansible server: Debian 9 (stretch)
Target server: Windows server 2012 R2

##### STEPS TO REPRODUCE

+ Confirm "Administrators" and "Backup Operators" groups exist in target server.
+ Execute the playbook below.

```yaml
- win_security_policy:
    section: Privilege Rights
    key: SeShutdownPrivilege
    value: "Administrators, Backup Operators"
```
+ Ansible reports "FAILED!" and stop running but Shutdown Privilege is successfully changed.

##### EXPECTED RESULTS

```
ok: [winsv01]
```
or
```
changed: [winsv01]
```

##### ACTUAL RESULTS

```paste below
fatal: [winsv01]: FAILED! => {
	"changed": true, 
	"import_log": "
		Completed 1 percent (0/63) 	Process Privilege Rights area        
		Completed 3 percent (1/63) 	Process Privilege Rights area        
		Completed 4 percent (2/63) 	Process Privilege Rights area        
		Completed 6 percent (3/63) 	Process Privilege Rights area        
		Completed 7 percent (4/63) 	Process Privilege Rights area        
		Completed 9 percent (5/63) 	Process Privilege Rights area        
		Completed 11 percent (6/63) 	Process Privilege Rights area        
		Completed 12 percent (7/63) 	Process Privilege Rights area        
		Completed 14 percent (8/63) 	Process Privilege Rights area        
		Completed 15 percent (9/63) 	Process Privilege Rights area        
		Completed 17 percent (10/63) 	Process Privilege Rights area        
		Completed 19 percent (11/63) 	Process Privilege Rights area        
		Completed 20 percent (12/63) 	Process Privilege Rights area        
		Completed 22 percent (13/63) 	Process Privilege Rights area        
		Completed 25 percent (15/63) 	Process Privilege Rights area        
		Completed 25 percent (15/63) 	Process Group Membership area        
		Completed 49 percent (30/63) 	Process Group Membership area        
		Completed 49 percent (30/63) 	Process Registry Keys area        
		Completed 49 percent (30/63) 	Process File Security area        
		Completed 49 percent (30/63) 	Process Services area        
		Completed 65 percent (40/63) 	Process Services area        
		Completed 73 percent (45/63) 	Process Services area        
		Completed 73 percent (45/63) 	Process Security Policy area        
		Completed 77 percent (48/63) 	Process Security Policy area        
		Completed 84 percent (52/63) 	Process Security Policy area        
		Completed 88 percent (55/63) 	Process Security Policy area        
		Completed 93 percent (58/63) 	Process Security Policy area        
		Completed 100 percent (63/63) 	Process Security Policy area    
		
		The task has completed successfully.", 
	"key": "SeShutdownPrivilege", 
	"msg": "Failed to change the value for key 'SeShutdownPrivilege' in section 'Privilege Rights', the value is still *S-1-5-32-544,*S-1-5-32-551", 
	"section": "Privilege Rights", 
	"value": "Administrators, Backup Operators"
}
```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * `win_security_policy` uses secedit.exe to manipulate these values but unfortunately that tool does not validate the results during import hence the log message being successful
   * The module then exports once again to validate that the settings were imported successfully and in this case they were not it will fail (which it did); the value for `SeShutdownPrivilege` did not change
   * The ini files must use a SID prefixed with `*` and not a human readable account name to set the privilege/right which is why they did not change successfully
   * To make this a lot easier to deal with, we created a module [win_user_right](https://docs.ansible.com/ansible/latest/modules/win_user_right_module.html) to manage privileges and rights instead

Please use `win_user_right` to achieve this task, it would look something like

```
- win_user_right:
    name: SeShutdownPrivilege
    users:
    - Administrators
    - Backup Operators
    action: add
```

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by jborean93** [comment]
I thought we had a warning for this but that isn't the case so have opened https://github.com/ansible/ansible/pull/48850 to try and help guide users to the correct module in the future.
