### ISSUE TITLE
Feature request : Being able to retrieve the file name used for backup when using files module

### ISSUE THREAD

**Issue by XavM** [ansible/ansible#4907]
The "file" modules (lineinfile, ini_file, etc...) can create a backup file that includes a timestamp 

It would be handy to make the file name used for backup accesible later in the play 

Ex: 

ini_file: dest=/etc/conf section=drinks option=fav value=lemonade backup=yes
register: some_var

debug: msg="{{some_var.backup}}"

Use case :

After a task modifies a nginx.conf, an other task runs a "service nginx configtest" that fails : You can then have a task that rollback the nginx.conf to its backup content before failing the play

**Comment by mpdehaan** [comment]
You could also implement this by using the "validate" option on the template or copy module, that way the file wouldn't have to be overwritten.  It would require being able to path the file in the validate command, however.

**Comment by XavM** [comment]
Sure, but validate does not seam to be present with lineinfile and ini_file

Am i wrong ?

**Comment by mpdehaan** [comment]
So I think what we're more likely to do here is upgrade the way the backup system works long term -- rather than doing just remote backups, maintain a tree centrally and use the fetch module to return these things.

Anyway, we haven't seen any traction on this item and are going to close this ticket out -- though I think a centralized backup method, if globally disable-able, would be a nice evolution for the core and remove the "unpredictable filenames" question.
