### ISSUE TITLE
group_vars  are override by last one in the inventory doc when a host belong to more than one group

### ISSUE THREAD

**Issue by ArvidLW** [ansible/ansible#49602]
##### SUMMARY

group_vars and host_vars are override by last one in the inventory doc when a host belong to more than one group.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```ini
[g1]
192.168.0.1
[g2]
192.168.0.1

[g1:vars]
service_install_dir=/opt/file1

[g2:vars]
service_install_dir=/opt/file2

```

##### EXPECTED RESULTS

when run g1
service_install_dir=/opt/file1
when run g2
service_install_dir=/opt/file2

##### ACTUAL RESULTS

```
"hostvars":{
    ......
    service_install_dir=/opt/file2
}
```
/opt/file1 is override

##### furthermore
when
```ini
[g1]
192.168.0.1 service_install_dir=/opt/file3
[g2]
192.168.0.1 service_install_dir=/opt/file4

[g1:vars]
service_install_dir=/opt/file1

[g2:vars]
service_install_dir=/opt/file2

```
the result is
```
"hostvars":{
   "192.168.0.1":{
            ......
            service_install_dir=/opt/file4
   }
}
```
other value is override,
only one service_install_dir variable value to one host ip, cannot  be other value when a host in different group.
exactly, the variable parsing and applying process exist some problems. when we install diverse app on same host in different group

```paste below
ansible -i bug.test -m debug -a "var=vars"
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

First, group vars never override host vars, what you are showing is group vars overriding each other. This is not a bug, this is by design and clearly documented https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#how-variables-are-merged

Also be aware that `g1`  is a group and `192.168.0.1` is a host, you seem to be confusing those concepts, host vars do override each other also and the last one declared wins.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ArvidLW** [comment]
ok, group vars overriding each other or host vars overriding each other, it is not important. if a host belong to two groups, it only can get one value of the variable we assign.  another value is loss though we can set ansible_group_priority to change merge order.
I mean that how we can choose the suitable value of a variable when the host in different group.
eg:
```
[g1]
192.168.0.1
192.168.0.2
[g2]
192.168.0.1

[g1:vars]
service_install_dir=/opt/file1

[g2:vars]
service_install_dir=/opt/file2
```
playbook:
```
- hosts: g1
   roles:
   - service
- hosts: g2
   roles:
   - service
```
run the playbook,  expect that 
when hosts is g1 the service_install_dir is /opt/file1 , 
when hosts is g2 the service_install_dir is /opt/file2.

but actual service_install can not change with the groupname.

why  not apply the group vars to the playbook hosts vars

**Comment by 4linuxfun** [comment]
Any solution there?

**Comment by getway** [comment]
I have same problem too
