### ISSUE TITLE
host variable:  Conditional expression must evaluate to True or False

### ISSUE THREAD

**Issue by YAmikep** [ansible/ansible#4980]
Hi,

Here is my host file:
[local]
10.0.0.10 nickname=local dev=1

In my playbook, I want to use the host variable "dev" but I cannot make it work, I always get this error:  "Conditional expression must evaluate to True or False: ${dev} == 1"

Here is my playbook:
- name: Mount code folder.
  mount: fstype=vboxsf opts=uid=${project_name},gid=${project_name} name=${project_root}/code/ src=/projects/ state=mounted
  only_if: "${dev} == 1"

What am I doing wrong?
Thanks

PS: I use ansible 1.3.4

**Comment by mpdehaan** [comment]
So only_if is ancient stuff, and it's not always the most friendly.  It's had replacements for a while.

Don't use that, I think you're reading some really old blog post or something -- I highly recommend the official ansibleworks.com/docs and github.com/ansible/ansible-examples for learning things.

This is as simple as:

when: dev == 1

Also, instead of ${project_root} (etc) just do {{ project_root }}

and that way you're using new style variables more consistently.
