### ISSUE TITLE
firewalld: failure enabling service in /etc/services but not firewalld conf

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5035]
The documentation for the _service_ parameter of the _firewalld_ module states:

```
"Name of a service to add/remove to/from firewalld - service must be listed in /etc/services"
```

However trying to enable service _tinc_, which does exist in /etc/services, results in an error:

```
failed: [localhost] => (item=['internal', 'tinc']) => {"failed": true, "item": ["internal", "tinc"], "parsed": false}
invalid output was: SUDO-SUCCESS-vonihhpbamfgxtdjtszljmuxvooozvqv
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-1385242766.99-128457051190667/firewalld", line 1416, in <module>
    main()
  File "/home/admin/.ansible/tmp/ansible-1385242766.99-128457051190667/firewalld", line 270, in main
    set_service_enabled_permanent(zone, service)
  File "/home/admin/.ansible/tmp/ansible-1385242766.99-128457051190667/firewalld", line 155, in set_service_enabled_permanent
    fw_zone.update(fw_settings)
  File "<string>", line 2, in update
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 121, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in update
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 48, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 297, in update
    self.fw_zone.update(tuple(settings.settings))
  File "/usr/lib/python2.7/site-packages/slip/dbus/proxies.py", line 51, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: INVALID_SERVICE: tinc
```

Using something like this:

```
- firewalld: service=tinc state=enabled zone=home permanent=True
```

$ grep tinc /etc/services

```
tinc            655/tcp                 # TINC
tinc            655/udp                 # TINC
```

firewalld comes with service->port mappings in xml files in /usr/lib/firewalld/services/*.xml files - there is no tinc.xml.

One way to fix this would be to say that if the service is in /etc/services but not in /usr/lib/firewalld/services/\* then a snippet like the following should be automatically dropped into /etc/firewalld/services/tinc.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>TINC</short>
  <description></description>
  <port protocol="tcp" port="655"/>
  <port protocol="udp" port="655"/>
</service>
```

**Comment by mscherer** [comment]
I wonder if this is not something that should be done on firewalld level, ie, automatically convert inexistant data in xml from /etc/services, rather than doing it ansible side.

**Comment by groks** [comment]
Possibly. I think there's a slight mismatch in that firewalld seems to be mostly a GUI tool for laptop users, and the GUI tools expect <short> and <description> elements; data which is missing from /etc/services.

So another option here would be to give the ansible firewalld module a method for adding missing services: you would do it explicitly, passing in short= and description=.

**Comment by bertvv** [comment]
Maybe the module documentation is wrong? I think the services you can add or remove are those listed by `firewall-cmd --get-services`. For example, to enable DNS, you should specify the service `dns` instead of the `/etc/services` entry `domain`, and to enable DHCP it's `dhcp` instead of `bootp`.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
