### ISSUE TITLE
In nova inventory plugin, allow overriding ssl verification behavior by adding an 'insecure' argument 

### ISSUE THREAD

**Issue by GooseYArd** [ansible/ansible#5061]
novaclients's default behavior is to require ssl verification, but occasionally it is helpful to disable verification. The client exposes a parameter "insecure" for this purpose, but in the nova inventory plugin (plugins/inventory/nova.py), only a subset of constructor parameters are handled. 

Apologies in advance- I'm new to github, I'm going to attempt to attach a pull request with a patch in a moment and will likely screw it up a few times before I get it right :)

**Comment by mpdehaan** [comment]
Thinking about this, but when adding a new argument please be sure to add it to the documentation section as well, including the "version_added" attribute.

**Comment by GooseYArd** [comment]
will do, thanks!

**Comment by GooseYArd** [comment]
I'm guessing you already spotted this, but it looks like Marco documented the argument, but the corresponding code to handle it was lost. I'm going to find an example of the use of version_added and will generate a new PR shortly. Also fixed the formatting.

**Comment by mpdehaan** [comment]
(Sorry fro the delay in respoding to this one as we have a large backlog)

I'm going to close this one because of the missing code to handle the argument, if you want to resubmit with changes as you had mentioned above (perhaps you have a private copy you are liking to use), we are happy to accept it.

Thanks!
