### ISSUE TITLE
extra-vars problems with YAML and JSON

### ISSUE THREAD

**Issue by eaigner** [ansible/ansible#5116]
When passing extra vars with the file option like so

```
--extra-vars "@/var/folders/g1/_g56425957qbqxmf84vzszfw0000gn/T/lb20131201-41336-feu2k2.json"
```

ansible fails with (it seems to try to parse it as yaml?)

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.4.0/libexec/bin/ansible-playbook", line 269, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.4.0/libexec/bin/ansible-playbook", line 159, in main
    diff=options.diff
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 149, in __init__
    (self.playbook, self.play_basedirs) = self._load_playbook_from_file(playbook, vars)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 159, in _load_playbook_from_file
    playbook_data  = utils.parse_yaml_from_file(path)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/__init__.py", line 483, in parse_yaml_from_file
    process_yaml_error(exc, data, path)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/__init__.py", line 461, in process_yaml_error
    msg = process_common_errors(msg, probline, mark.column)
  File "/usr/local/Cellar/ansible/1.4.0/lib/python2.7/site-packages/ansible/utils/__init__.py", line 406, in process_common_errors
    if middle[0] in [ '"', "'" ] and middle[-1] in [ '"', "'" ] and probline.count("'") > 2 or probline.count("'") > 2:
IndexError: string index out of range
```

When using a `.yml` file instead of `.json` the parser fails when a `!` is encountered, like this

```
ERROR: Syntax Error while loading YAML script, /var/folders/g1/_g56425957qbqxmf84vzszfw0000gn/T/lb20131201-41807-43kqge.yml
Note: The error may actually appear before this position: line 6, column 5

  lb:
  - !ruby/object:Machine
    ^
```

So right now I can't use `JSON` or `YAML` with `extra-vars`.

**Comment by mpdehaan** [comment]
So you do have a syntax error, this is just an error highlighting the error, we've already fixed some of these in 1.4.1 where it was trying to be overly helpful.  

I'm not positive the "@" syntax will try JSON though, we'll look in and see, IMHO it ought to but may not be coded to.  I know inline JSON to -e is fine though. 

So per instructions in contributing.md, please provide the version of Ansible you are using in the ticket.

Thanks!

**Comment by eaigner** [comment]
I thought it was obvious from the trace :)

1.4.0

**Comment by mpdehaan** [comment]
The fix here should be when we get a parse error loading a "@" file to indicate that we have an exception.

**Comment by risaacson** [comment]
@eaigner it looks like you are showing two possible issues.

The first is that you are trying to use a JSON file as an —extra-vars argument and are getting an index error due to parsing problems. Your question about YAML coming up during what you would expect to see as a JSON operation is valid. In the section of code that is processing this JSON is treated as a subset of YAML.

I believe that I was able to finally track down your issue and it seems that at the core it was an unbalanced quote issue that we are not catching and printing out nicely in 1.4. I believe that we have solved that error but in the process I have uncovered a similar more obscure issue which should be fixed in GH-6197

The second is the error that you are getting while using a YAML file and on one of your lines you start it with a '!'. I would expect that this error would come up and it makes sense once you look into the YAML spec. "Explicit typing is denoted with a tag using the exclamation point ("!") symbol. Global tags are URIs and may be specified in a tag shorthand notation using a handle. Application-specific local tags may also be used."(http://www.yaml.org/spec/1.2/spec.html) Depending on what you are trying to do I am guessing that you will want to wrap this value with quotes. The error that you are getting is the correct parsing error that you want to see.
