### ISSUE TITLE
mysql_db: db=test state=absent should also remove mysql.db records?

### ISSUE THREAD

**Issue by ruudk** [ansible/ansible#5125]
I removed the test db that MySQL created with `mysql_db: db=test state=absent` but that still leaves 2 records in the `mysql.db` table that refer to the test database.

I think the mysql_db module should remove this?

**Comment by mpdehaan** [comment]
It's executing a SQL drop database.

What would you suggest we do instead or in addition?

**Comment by ruudk** [comment]
mysql_secure_installation does this:

``` bash
remove_test_database() {
    echo " - Dropping test database..."
    do_query "DROP DATABASE test;"
    if [ $? -eq 0 ]; then
    echo " ... Success!"
    else
    echo " ... Failed!  Not critical, keep moving..."
    fi

    echo " - Removing privileges on test database..."
    do_query "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    if [ $? -eq 0 ]; then
    echo " ... Success!"
    else
    echo " ... Failed!  Not critical, keep moving..."
    fi

    return 0
}
```

**Comment by Jmainguy** [comment]
When dropping the table in mysql it leaves these things behind in mysql.db, you can add privs for a user to a table that doesn't exist, or remove the table and the user would still have the privs to it. Since Mysql does not default remove these references, I do not think ansible should automatically remove these references.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
