### ISSUE TITLE
Allow ansible to accept stdin or environmental variable for ask-pass and ask-sudo-pass

### ISSUE THREAD

**Issue by ytjohn** [ansible/ansible#5135]
One can relatively securely set their password in an environmental variable and run sudo commands remotely using that variable.  This comes in handy for performing for loops and similar.

I would like to see a similar enhancement in ansible, either
- allows password or sudo password to be entered via stdin; or
- even better: ability to specify an enviornmental variable that contains the password

```
bash-3.2$ read -p 'enter: ' -s SUDOPASSWORD; echo
enter: 
bash-3.2$ export SUDOPASSWORD
bash-3.2$ echo $SUDOPASSWORD | ssh user@example "export TERM=vt100; sudo -S -p '' su - root -c 'ls /root'"
test.txt
history | grep echo
echo $SUDOPASSWORD | ssh user@example "export TERM=vt100; sudo -S -p '' su - root -c 'ls /root'"
```

**Comment by mpdehaan** [comment]
I have some reservations about the security of such an approach.

As this is not something we're going to be working on, I'm going to close this ticket.

AWX provides some nice options for the server holding onto your password that may be useful to you from an API perspective.

**Comment by adeck** [comment]
"I have some reservations about the security of such an approach."
His idea of exporting variables is dubious at best- I'm not going to argue with that- but his idea of using stdin is not only reasonable, it's the accepted standard for passing passwords. That way they never need to hit the filesystem, or potentially hit loggers or /proc (via the "cmdline" file under /proc ).

Why on earth wouldn't you just support setting stdin?

Because, at the moment, [this](http://docs.ansible.com/faq.html#user-passwords) is the official advice, and frankly using `mkpasswd` without `--stdin` is just as inadvisable as using an environment variable, but, since it's in official documentation with no visible caveats, it's far worse.
