### ISSUE TITLE
Replacing /tmp/ in OS X with a directory creates linked file in OSX

### ISSUE THREAD

**Issue by sgargan** [ansible/ansible#5139]
I'm trying to provision an OSX Mavericks vm and am seeing this curious issue when I copy files to the target and then try and set the mode of the copied file.

Running this, everything works as expected 

``` yml
- name: copy over script
  copy: src=somefile.sh dest=/tmp 
```

if I list the contents of /tmp I see the script copied correctly. However if i set the mode of the file 

``` yml
- name: copy over script with mode 755
  copy: src=somefile.sh dest=/tmp mode=755
```

then when I list /tmp the folder is gone and i see this strange symlink instead

Mavericks:~ vagrant$ ls -al /tmp
lrwxr-xr-x  1 root  wheel  53 Dec  2 20:32 /tmp -> /tmp/ansible-1386045119.92-33873775892285/somefile.sh

I'm thinking this boils down to the use of lchmod to change the mode. In OSX the /tmp file is actually a symlink to /private/tmp and I suspect that something is breaking where when it tries to rename the copied file with lchmod;  though this is entirely speculation on my part.

I can provide you with a vm to test with if needs be.

**Comment by mpdehaan** [comment]
Hmm, interesting.

(A) So what was done was to say "copy over this shell script and save it as '/tmp'", not save it _IN_ /tmp, as then you should provide the remote name.   So small bit of user error, still behavior is interesting.

(B) the automatic conversion of a file into a directory seems reasonable here, though the symlink behavior I find a bit curious.   The temp directory ansible is using does seem like it didn't quite survive a rename in some particular OSexey way.

I'm not super concerned given (A) but if you feel like digging further, that would be welcome.

**Comment by sysadmin75** [comment]
I've replicated this issue with the latest devel version. I've also found it to be more of a problem if /tmp is a symlink then it always errors with (even with follow=yes):
msg: src file does not exist, use "force=yes" if you really want to create the link: /testfile1

To the developers:
Is this something that should have time spent on or will this be handled in v2?

**Comment by bcoca** [comment]
this is probably a problem with destination detection, it looks for a directory in case it needs to append the source basename to the path, as a workaround you can specifying the full destination path.

**Comment by mattclay** [comment]
Tested on OS X El Capitan (10.11.6) and OS X Mavericks (10.9) with devel and it's working.

I believe if this was still an issue it would also be detected by integration tests run on Shippable.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

Based on the above, we're going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
