### ISSUE TITLE
ansible async poll with shell

### ISSUE THREAD

**Issue by sankalpcool25** [ansible/ansible#51431]
##### SUMMARY
ansible async poll and shell dont work togather

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

2.4.2.0

```

##### CONFIGURATION

- name: Reboot the host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: check_reboot_status.stdout.find('reboot') != -1



```error :-1: 
TASK [Reboot servers] ***********************************************************************************************************************************************************************************************************************
task path: /opt/dap/playbooks/paas/ansible-tower-management/playbooks/patch-reboot.yml:19
ERROR! conflicting action statements: shell, async


how do I fix this issue

**Comment by sivel** [comment]
The issue here is that you have a file named `async` somewhere in the search path that ansible uses to find modules.

Ansible 2.6+ has a better error message here.  Please upgrade, to determine where that file is that is causing issues.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
