### ISSUE TITLE
lvol module: fails on repeated run

### ISSUE THREAD

**Issue by inittab** [ansible/ansible#5165]
This task:
  name: Create LVs for web2 DRBD
  lvol:
    vg=sistema
    lv=drbd_web2
    size=40G
    state=present

Will create the mentioned LV on the first run, and fail in the next runs with:
failed: [patty] => {"err": "  New size (10240 extents) matches existing size (10240 extents)\n  Run `lvreduce --help' for more information.\n", "failed": true, "item": "", "rc": 3}
msg: Unable to resize drbd_web2 to 40G

Whereas this one, will work without problems:
  name: Create LVs for web1 DRBD
  lvol:
    vg=sistema
    lv=drbd_web1
    size=7G
    state=present

Main difference being the size (and name). Anything above 13-15G will fail. I say 13-15 because I could not always reproduce the issue in that range, but always above it.
Running ansible 1.4 against Debian Wheezy.

**Comment by mscherer** [comment]
Could you edit the bug so the formatting is right ( mostly using 4 spaces to handle code correctly )

**Comment by apollo13** [comment]
@mscherer Copied from my config:

```
- name: mysql volume
  lvol: lv=mysql size=70G vg=main
```

Can confirm that it fails. Issue is resolved by changing '70G' to '70g'.

**Comment by risaacson** [comment]
I just tested this against (ansible 1.5 (devel 0a83f743c1) last updated 2014/02/24 14:32:43 (GMT -500)) and found no issues. I was testing against a recent Debian Wheezy(64-bit) instance creating a 70G LV.

I used the following playbook for testing which should have caught what you saw. Unfortunately up to three months has happened while this ticket has been open and many fixes have come through. Please feel free to retest via devel or a more recent version and reopen this issue if you can confirm that the problem is still there.

```
---
# This playbook creates and removes logical volumes.

- name: create the lvm lvol - one
  lvol: lv=one size=70g vg=main state=present

- name: remove the lvm lvol - one
  lvol: lv=one vg=main state=absent

- name: create the lvm lvol - two
  lvol: lv=two size=70G vg=main state=present

- name: remove the lvm lvol - two
  lvol: lv=two vg=main state=absent
```

**Comment by risaacson** [comment]
In my previous response I was answering a question that I don't think that you have.

The behavior that you are seeing is that when you run for a second time at the same size or larger there is a failure on an existing volume. This is because the second run is trying to resize the volume. You can use a larger(if there is disk space) or a smaller size but the same size will currently fail.

So keeping that in mind the module should check if the lvol exists under the expected vg and if it is the same size to exit out nicely stating that there was no changes.

@inittab let me know if you think that sounds wonky.

**Comment by inittab** [comment]
Hi, the issue seems to be fixed in 1.4.5. I can run this task over and over without problems (either using g or G as units). I also tried successfully with 1.5 (6fe369fca0c92c11a2cc8f1883f7e13e1aed1e8d). Closing accordingly. Thanks!

**Comment by tom--** [comment]
This is not fixed in my system.
- Control: OS X 10.9.3 Ansible 1.6.3
- Target: Ubuntu 14.04

This playbook fails with the output given below:

``` yaml
- hosts: trusty5
  remote_user: "{{ unpriv_user }}"
  sudo: yes
  tasks:
    - lvol: vg=trusty5-vg lv=test size=100G state=present
    - command: lvs --noheadings -o lv_name,size --units G --separator ';' trusty5-vg
      register: lvs
    - debug: var=lvs
    - lvol: vg=trusty5-vg lv=test size=100G state=present
```

```
TASK: [lvol vg=trusty5-vg lv=test size=100G state=present] ********************
changed: [trusty5]

TASK: [command lvs --noheadings -o lv_name,size --units G --separator ';' trusty5-vg] ***
changed: [trusty5]

TASK: [debug var=lvs] *********************************************************
ok: [trusty5] => {
    "lvs": {
        "changed": true,
        "cmd": [
            "lvs",
            "--noheadings",
            "-o",
            "lv_name,size",
            "--units",
            "G",
            "--separator",
            ";",
            "trusty5-vg"
        ],
        "delta": "0:00:00.012904",
        "end": "2014-06-23 15:37:29.609964",
        "invocation": {
            "module_args": "lvs --noheadings -o lv_name,size --units G --separator ';' trusty5-vg",
            "module_name": "command"
        },
        "rc": 0,
        "start": "2014-06-23 15:37:29.597060",
        "stderr": "",
        "stdout": "  root;100.00G\n  test;107.37G",
        "stdout_lines": [
            "  root;100.00G",
            "  test;107.37G"
        ]
    }
}

TASK: [lvol vg=trusty5-vg lv=test size=100G state=present] ********************
failed: [trusty5] => {"failed": true}
msg: Sorry, no shrinking of test without force=yes.
```

There is a discrepancy between `lvs(8)` and `lvcreate(8)`.

```
LVS(8)
       --units hHbBsSkKmMgGtTpPeE
              All  sizes  are  output  in these units: (h)uman-readable, (b)ytes, (s)ectors, (k)ilobytes, (m)egabytes, (g)igabytes,
              (t)erabytes, (p)etabytes, (e)xabytes.  Capitalise to use multiples of 1000 (S.I.) instead of 1024.  Can also  specify
              custom units e.g. --units 3M

LVCREATE(8)
       -L, --size LogicalVolumeSize[bBsSkKmMgGtTpPeE]
              Gives the size to allocate for the new logical volume.  A size suffix of K for kilobytes,  M  for  megabytes,  G  for
              gigabytes, T for terabytes, P for petabytes or E for exabytes is optional.
              Default unit is megabytes.
```

So `lvcreate -L 100G` is the same as `lvcreate -L 100g` but `lvs --units G` is different from `lvs --units g`.

The lvol module's docs say that it uses sizes as does `lvcreate`. This is not correct. It creates as does `lvcreate` but reads current size as does `lvs` so using capital multipliers will never be idempotent.

A solution would be to lowercase the variable `unit` passed to `lvol` on [line 156 here](https://github.com/ansible/ansible/blob/abb4f2fbda47709af001a91907e0389079a87670/library/system/lvol#L156).

**Comment by jmdh** [comment]
This hasn't yet been fixed: discussion on it appears to have moved to: https://github.com/ansible/ansible-modules-extras/pull/196
