### ISSUE TITLE
ansible.cfg relative paths are not expanded

### ISSUE THREAD

**Issue by techtonik** [ansible/ansible#5185]
When you create ansible.cfg with the following content:

```
[defaults]
hostfile = ./hosts
```

`hostfile` will be read from whatever directory you're now in. This makes system fragile to directory changes. I'd expect this path to be resolved relative to `ansible.cfg`.

**Comment by mpdehaan** [comment]
You requested a relative path and should specify an absolute.  This is clearly not a bug.

**Comment by techtonik** [comment]
Absolute path doesn't work for my use case. The question is how relative path should be resolved against.

**Comment by techtonik** [comment]
https://groups.google.com/forum/#!topic/ansible-project/9oZHLW_b6-w

**Comment by bostrick** [comment]
while agreed not a bug, it would be a nice enhancement... i'd like to have our team be able to check out 
a repo with a configured  etc/{ansible.cfg,hosts,custom_ssh.cfg}, and just set a single environment variable such as $ANSIBLE_BASE, and be done.   ANSIBLE_{CONFIG,LIBRARY} solve the first two.  Having a predictable $CWD for relative lookups from ansible.cfg would solve the latter (where, the current default, relative from the invoking command's $CWD seves little useful purpose).

**Comment by woutervh** [comment]
:+1: 

when relative paths are specified in the ansible.cfg, they should be relative to this file. 
This should be standard behaviour.
I  hate config-files full of absolute paths, because they are not easily re-usable across different machines and teammembers.

Eg, my current ansible.cfg is located in   /opt/miniconda/envs/ansible/etc/ansible.cfg
If teammembers installed miniconda in some other place, they then need to fork my ansible-config

in my  login-shell, the env-variable is set via
`
export ANSIBLE_CONFIG=/opt/miniconda/envs/ansible/etc/ansible.cfg
`
my inventory is located /opt/miniconda/envs/ansible/etc/ansible/hosts

therefore I strongly prefer to put in my ansible.cfg/
`
inventory = ./ansible/hosts                                                           # config is relocatable 
`
then
`
inventory = /opt/miniconda/envs/ansible/etc/ansible/hosts  # config is not relocatable
`

**Comment by ghost** [comment]
The documentation is sketchy.  Consider inventory: 

_This is the default location of the inventory file, script, or directory that Ansible will use to determine what hosts it has available to talk to:_

OK, so no paths but something called a "location" it will use to "talk".  We're already off to a bad start, but maybe  I'm being too fussy.  They obviously mean "path" but if that's true and there are no qualifications, I'm going to assume any legal path and that includes relative paths.  So maybe the "bug" is in the documentation.  

Somebody suggested just specifying the inventory.  That answer is a work-around, but definitely not in keeping with the objective of automation.  So, Alice and Bob check out our source script and each simply updates the local ansible.cfg (being careful not to check back in) with a custom path:

Alice:
/users/admin/alice/projects/flowershop/source/ansible/inventory

Bob: 
C:\workspace\flowershop\source\ansible\inventory

Most would find imposing this on a handful let alone a large number of developers, unnecessary friction and cost.

**Comment by djroze** [comment]
Hi all - I'm a new user just starting to pick up Ansible. I like the concept of the product and am excited about the prospect of being able to use it, but I immediately ran into this issue. I have to say, more than being frustrated with the issue/functionality, I am disappointed to see how abruptly this feature request was dismissed (both in this thread and in https://groups.google.com/forum/#!topic/ansible-project/9oZHLW_b6-w).

Putting relative paths in the config file seems like a perfectly reasonable use case, and simply saying "no, you need to use absolute paths" and "here's the code that's written" doesn't give me a sense that the maintainers are interested in being responsive to users' needs. There are always going to be mismatches between expected behavior / features of a product and what's actually implemented, but this seems like such a dismissive way to respond to frustrated users.

For the record, here's the use case I am trying to implement, which I figured would be perfectly reasonable given that Ansible is supposed to be very easy to pick up and start running with:
1. Code already in Git repository:
   - `ansible.cfg` --> includes a line like `inventory = hosts` or `inventory = ./hosts`
   - `hosts` file
   - whatever other stuff I'll end up adding
2. User checks out Git repository to any preferred directory (in my case, `~/src/ansible/`)
3. User sets environment variable pointing to Ansible config (e.g. in `~/.bash_profile`):
   `export ANSIBLE_CONFIG=~/src/ansible/ansible.cfg`
4. Profit

`ansible.cfg` can then be extended to include any other files/functionality as needed using relative paths, so that the entire Ansible setup is committed to source control (as recommended in the official documentation!) and the user only needs to set a single environment variable to enable usage of it. If a change to the Ansible configuration is available, any users just need to `git pull` the latest and they automagically have those changes.

Would be awesome if this feature can be re-evaluated with a more substantive discussion. Thanks for your consideration!

---

Update: I did manage to come up with the following work-around, which only works when using the specific strategy I outlined above.
Modification A): Set ANSIBLE_CONFIG to the path of the Git checkout, rather than the config file itself. In the example above, `export ANSIBLE_CONFIG=~/src/ansible`
Modification B): Inside the `ansible.cfg` file, concatenate this variable with your relative path specification. For example:
`inventory = $ANSIBLE_CONFIG/hosts`

Obviously it's pretty hacky, but it does seem to work if you're adopting the strategy I described. It's also dependent upon Ansible continuing to allow `ANSIBLE_CONFIG` to point to the directory containing the config file, rather than to the config file itself.

**Comment by techtonik** [comment]
I think that the reason why this is not implemented is that it becomes Ansible a simple tool for plain users, and without this simple change it is a tool for Linux admins. Later allow Ansible to exist as a project with compensated developers. Former not.

**Comment by chris-neely** [comment]
I'm looking at the same use case as @djroze - So far our current work around is edit it when we work on a branch and then change it back before we commit.

https://github.com/ansible/ansible/issues/5185#issuecomment-220848325

**Comment by tyleha** [comment]
I agree with @djroze and others. This is standard practice for modern config. Reusability & consistency across machines and developers should be the goal. The only way to do that is with relative paths. I can't ensure a teammate who checks out my code will check it out to the same directory I did. 

Especially considering work being done in #17115 - loading ansible.cfg not from an absolute path OR the cwd - being able to specify a relative path will be of even more importance.

I would be more than willing to work on a PR for this feature if I knew ansible core would be accepting of the branch - would work on this be accepted?

**Comment by techtonik** [comment]
@tyleha this ticket was closed 4.5 years ago, so probability that developers will pay attention to it and reread the thread is minimal. If you can open a new ticket with pros and cons summarized, it may get better traction today.

**Comment by ssbarnea** [comment]
I totally agree that this bug should be reopened and fix it one way or another, allowing us to use paths relative to ansible config file.

I don't mind if someone wants to keep the current behaviour of using paths relative to CWD as long we do have an option to specify paths relative to the config file, something like: 

    inventory = %(config)/hosts

**Comment by arocki7** [comment]
How about like this?

```
[defaults]
inventory = $PWD/inventory.ini
```
