### ISSUE TITLE
DigitalOcean module shows api_key

### ISSUE THREAD

**Issue by analytically** [ansible/ansible#5194]
The api_key is secure and should not be shown in logging output. Currently:

```
TASK: [digital_ocean name=hmaster01 client_id=35isvbiQvJfg2zqMzcbio api_key=e90be8330909096e718d9d62f23123456 size_id=62 region_id=2 image_id=961965 private_networking=yes wait_timeout=500] *** 
```

**Comment by mpdehaan** [comment]
So ansible already has a provision for not logging things named "password" in them. that prevents this from being logged in remote hosts.

In your case though, what you need to do is just name the task, and then it's not going to show up in the name up top.

```
- name: foo
  digital_ocean: name=hampster01 client_id=....
```

etc

Since the name of the task is a string, it's going to show anything you have up there.

**Comment by mpdehaan** [comment]
update:  fixed Markdown formatting above

**Comment by analytically** [comment]
When using --extra-vars "api_key_password=$DO_API_KEY" -> this value is still logged when used!
