### ISSUE TITLE
hosts coming from multiple sources are not deduped

### ISSUE THREAD

**Issue by zart** [ansible/ansible#5196]
Since 1.4 ansible does not deduplicate hosts coming from multiple sources, which causes tasks to run multiple times on the same host in a single play.

```
$ tail test/* simple.yml
==> test/hosts1 <==
[group1]
localhost

==> test/hosts2 <==
[group2]
localhost

==> simple.yml <==
- hosts: localhost
  gather_facts: no

$ (cd ~/opt/ansible ; git checkout v1.3.4)
Previous HEAD position was 2a58c2b... Update files for 1.4 release
HEAD is now at 8e3ba1f... Version bump for 1.3.4
$ ansible --version ; ansible-playbook -i test simple.yml --list-host
ansible 1.3.4

playbook: simple.yml

  play #1 (localhost): host count=1
    localhost

$ (cd ~/opt/ansible ; git checkout v1.4.0)
Previous HEAD position was 8e3ba1f... Version bump for 1.3.4
HEAD is now at 2a58c2b... Update files for 1.4 release
$ ansible --version ; ansible-playbook -i test simple.yml --list-host
ansible 1.4

playbook: simple.yml

  play #1 (localhost): host count=2
    localhost
    localhost
```

**Comment by zart** [comment]
This was probably caused by `Inventory hosts are used in the order they appear in the inventory.` feature introduced by https://github.com/ansible/ansible/commit/8fc46a3a5a286bee5e429b921ef8af9ea7ecbc31

**Comment by mpdehaan** [comment]
Ah, I see this happens if the host is defined in multiple inventory files.

Probably not too severe, since they aren't defined in the same source this wasn't really meant to be a feature, but I think we should still fix it.

The workaround is that you can still put the hosts in as many groups as you want, but should only put it in one inventory file.

(There's a seperate ticket about localhost being implicit and not being something you have to add to inventory, that makes this a little cleaner)

Thanks for the report!

**Comment by haskjold** [comment]
Hi

For us this is a severe regression that blocks us from upgrading past ansible 1.3.x since we have multiple inventory sources that we pull in through inventory scripts which can and do have the same hosts defined in different and sometimes the same groups.

**Comment by jcassee** [comment]
Could this issue be the cause of ["fatal: [...] => decryption failed"](https://groups.google.com/d/topic/ansible-project/WOh157vFHO8/discussion) errors I have been seeing lately?
