### ISSUE TITLE
add_host module: can't set variables from dynamic inventory

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#5235]
I am trying to decouple my roles from the inventory mechanism. So I don't want them to reach out for variables like ec2_tag_foo, or operate on host groups like tag_web-servers_.

So I'm trying to use add_host to create group web-servers from group tag_web-servers_, and set ansible_ssh_user from ec2_tag_ansible_ssh_user. However, when the values come from dynamic inventory instead of static inventory, the variables I set with add_host don't follow through to subsequent plays.

Here is an example of it working properly with static inventory:

`./bar`

```
[tag_web-servers_]
host1 ec2_ip_address=10.0.0.1 ec2_tag_ansible_ssh_user=fedora
host2 ec2_ip_address=10.0.0.2 ec2_tag_ansible_ssh_user=fedora
```

`./bar.yml`

```

---
-
  hosts: tag_web-servers_
  connection: local
  serial: 1
  gather_facts: no
  tasks:
    -
      name: build the web-servers group
      add_host: name={{ ec2_ip_address }} groups=web-servers ansible_ssh_user={{ ec2_tag_ansible_ssh_user }}
-
  hosts: web-servers
  tasks:
    -
      name: tell the truth
      command: /usr/bin/true
```

```
$ ansible-playbook -i bar bar.yml  -vvv | grep USER
<10.0.0.1> ESTABLISH CONNECTION FOR USER: fedora
<10.0.0.2> ESTABLISH CONNECTION FOR USER: fedora
```

So ansible_ssh_user carried forward to the play that operates on web-servers.

Now observe it failing to work with dynamic inventory.

`./foo.yml`

```
---------

---
-
  hosts: tag_web-servers_
  connection: local
  serial: 1
  gather_facts: no
  tasks:
    -
      add_host: name={{ ec2_ip_address }} groups=web-servers ansible_ssh_user={{ ec2_tag_ansible_ssh_user }}
    -
      debug: msg="USER: {{ ec2_tag_ansible_ssh_user }}"
-
  hosts: web-servers
  gather_facts: no
  tasks:
    -
      debug: msg="USER: {{ ansible_ssh_user }}"
    -
      command: /usr/bin/true
```

```
$ ansible-playbook -i ./ec2.py foo.yml  -vvv | grep USER
TASK: [debug msg="USER {{ec2_tag_ansible_ssh_user}}"] *************************
ok: [197.189.194.11] => {"msg": "USER fedora"}
TASK: [debug msg="USER {{ec2_tag_ansible_ssh_user}}"] *************************
ok: [197.189.194.10] => {"msg": "USER fedora"}
<197.189.194.10> ESTABLISH CONNECTION FOR USER: sheldonh
<197.189.194.11> ESTABLISH CONNECTION FOR USER: sheldonh
```

The debug messages prove that the ec2_tag_ansible_ssh_user variable was made available by ec2.py. But the connection lines show that ansible_ssh_user was not set correctly by add_host, or subsequently lost or something.

I really don't understand what's going on. :-(

**Comment by jctanner** [comment]
@sheldonh what is your ansible version?

**Comment by sheldonh** [comment]
Anything from ansible 1.3 through 1.5devel (git HEAD).

**Comment by ex-nerd** [comment]
I noticed something like this today with a simple shell script to return json info for my vagrant inventory (ansible 1.4.3, osx).  You can test this with a simple shell script:0

``` sh
#!/bin/sh
echo '{"vagrant":{"hosts":["vagrant ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user=vagrant"]}}'
```

Then just run `ansible -i hosts.sh --list-hosts '*'` and see that the output prints the entire host string instead of just the `vagrant` hostname alias as it would if you put that string into a static inventory file.

**Comment by omgjlk** [comment]
That json isn't right. vars should not be in the hosts list entry. Vars either go in a data block for the group 

```
{groupname: {vars: {varname: value, varname2: value2}}}
```

or they go into the _meta key space

```
{'_meta': {'hostvars': {hostname1: {varname: value, varname2: value2}, hostname2: {varname: value}}}}
```

Is your inventory plugin something you wrote or something vagrant provides?

**Comment by ex-nerd** [comment]
Adding this mostly for posterity/google since I haven't actually seen mention of the proper json format for these values (the docs really could be clearer):

``` javascript
{
    "vagrant": {
        "hosts": [
            "vagrant"
        ],
        "vars": {
            "ansible_ssh_user": "vagrant"
        }
    },
    "_meta" : {
        "hostvars" : {
            "vagrant": {
                "ansible_ssh_host": "127.0.0.1",
                "ansible_ssh_port": "2222"
            }
        }
    }
}
```

It's also worth mentioning that if you want to use a nonstandard port you can't just do "host:port" for the "hosts" array -- you have to use `_meta` and `hostvars` and either put "host:port" into `ansible_ssh_host`, or split the port out into `ansible_ssh_port` as in the example above.

It's verbose, but ansible works as expected once the JSON is formatted this way.

It also appears that this particular issue may not necessarily be related to this bug report, so I apologize for the noise.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
