### ISSUE TITLE
Add Hetzner cloud server module

### ISSUE THREAD

**Issue by decentral1se** [ansible/ansible#52813]
##### SUMMARY
https://www.hetzner.com/ is a cloud provider with a solid reputation. The only Ansible modules available for IT automation are outside core right now and written in the Go programming language over at https://github.com/thetechnick/hcloud-ansible.

I've seen other attempts but they are archived/abandoned:
  * https://github.com/betacloud/ansible-hetzner
  * https://github.com/SoInteractive/ansible-hetzner

We have https://hcloud-python.readthedocs.io/en/latest/ ready to rip for API integration.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner

##### ADDITIONAL INFORMATION
N/A

**Comment by gandhiano** [comment]
I think the work in https://github.com/thetechnick/hcloud-ansible is valuable, but it is in fact written in Go and does miss support for
[volumes](https://github.com/thetechnick/hcloud-ansible/issues/26) and
[labels](https://github.com/thetechnick/hcloud-ansible/issues/25), apparently because by then no support was available for these in the hcloud-go library. Reusing the logic from there could be a plus.

**Comment by LKaemmerling** [comment]
There are already some progress on this :)

**Comment by decentral1se** [comment]
Oh nice @LKaemmerling, any links? Will happily review stuff!

**Comment by LKaemmerling** [comment]
https://github.com/ansible/ansible/pull/53062

**Comment by LKaemmerling** [comment]
`hcloud_server` was merged 🎉 and will be released with 2.8.

We have more modules in the pipeline and hopefully we can contribute them to Ansible 2.8 too.

**Comment by decentral1se** [comment]
Solid work! I'll close this off :rocket: :rocket: :rocket:
