### ISSUE TITLE
docker module: task module does not fail for attached containers

### ISSUE THREAD

**Issue by vyrak** [ansible/ansible#5284]
The following snippet is an example illustrates an issue with passing an failing command to a docker module that creates a container in an attached mode.

```
- name: Exit unsuccessfully
  docker: image=test detach=False command="exit 1"

- name: Follow up 
  command: echo "should not run"
```

The docker module should fail and not run the follow up module.

**Comment by mpdehaan** [comment]
Please explain in more detail what the state is before running the command, what happens (show output) and what you expect to happen?

You seem to be saying that the commands executed in the container should break the ansible run, which I'm not sure that they should, because Ansible was running the command requested, and that's really a function of what's going on IN the container, which should probably be manually dealt with, i..e run with "-v" and make sure you've got something you should use for output?

It was able to pass on the command, etc.

**Comment by vyrak** [comment]
It's an Ubuntu (raring) environment with not much in it.  Below, is everything that gets installed.

```
apt-get update
apt-get install -y -q python-paramiko python-yaml python-jinja2 python-simplejson git-core python-software-properties python-pip>> /tmp/cinit
pip install --upgrade boto docker-py
```

I got a playbook with a task that installs docker and creates a docker container that houses PostgreSQL.  The contents of the task in the playbook is shown below.

```
- name: Add Docker Key
  apt_key: url=https://get.docker.io/gpg

- name: Add Docker Repository
  lineinfile: regexp='docker' line='deb http://get.docker.io/ubuntu docker main' dest='/etc/apt/sources.list'

- name: Install Docker
  apt: pkg=lxc-docker=0.7.1 update_cache=yes

- name: Create Postgres Volume
  file: path={{postgres_volume}} state=directory mode=700 owner={{volume_dir_owner}}
  register: postgres_volume_dir

- name: Init Postgres Volume
  docker:
    image=test/postgres
    detach=False
    volumes={{postgres_volume}}:/var/lib/postgresql/9.3/main
    command="/usr/lib/postgresql/9.3/bin/initdb -D /var/lib/postgresql/9.3/main"
  when: postgres_volume_dir.changed

- name: Create Postgres User
  docker:
    image=test/postgres
    detach=False
    volumes={{postgres_volume}}:/var/lib/postgresql/9.3/main
    command="/bin/sh -c \"echo \\\"CREATE USER {{postgres_user}} WITH PASSWORD '{{postgres_password}}';\\\" | /usr/lib/postgresql/9.3/bin/postgres --single --config-file=/etc/postgresql/9.3/main/postgresql.conf\""
  when: postgres_volume_dir.changed

- name: Run Postgres Container
  docker: image=test/postgres volumes={{postgres_volume}}:/var/lib/postgresql/9.3/main name=postgres
  register: postgres_container
```

In the task, there are two docker modules that run commands in an attached container.  The issue that I was having, was the Create Postgres User module was silently failing.  So when I finally tried to attach to the running Postgres container, it didn't have the user in it.

In the case of using the docker module with `detach=False`, I think it needs to be seen as a failure, instead of continuing on.

**Comment by cove** [comment]
I think your example there will actually start three separate containers, since it checks to see if the command/image pair are running already and if not, starts a new one. (That behavior may no longer be needed since they added named containers.)

What you need is a docker transporter for ansible to run commands in an already deployed container, but I don't think anyone had written that yet. 

The other option is to start ssh on it and have ansible connect normally, or maybe create a standard boot strap pgsql account in the docket image and use the pgsql ansible module to change the password.

**Comment by vyrak** [comment]
Right, the initdb & create user tasks that created those short-lived containers were part of a work around.  The sample I posted earlier is no longer used, it was just an initial stab at getting ansible to setup volume that can be used by a different container housing postgres if the original container happened to fail.

The main point I'm trying to illustrate is if a command was specified for a docker container that runs in the foreground, then I expected that it should recognize a failure and prevent any subsequent tasks from running.

**Comment by cove** [comment]
Right. I think this is a docker bug actually, the start call returns a 204 for the following:

```
 - docker: image=busybox detach=False command="exit 1" docker_url=http://192.168.1.136:8000
```

Here's a trace of the REST calls when running ansible:

```
 192.168.1.136  192.168.1.136   >   GET 192.168.1.136:8000  /v1.6/containers/json?all=0&limit=-1&trunc_cmd=1    HTTP/1.1    -   -
 192.168.1.136  192.168.1.136   <   -   -   -   HTTP/1.1    200 OK
 192.168.1.136  192.168.1.136   >   GET 192.168.1.136:8000  /v1.6/containers/json?all=0&limit=-1&trunc_cmd=1    HTTP/1.1    -   -
 192.168.1.136  192.168.1.136   <   -   -   -   HTTP/1.1    200 OK
 192.168.1.136  192.168.1.136   >   POST    192.168.1.136:8000  /v1.6/containers/create HTTP/1.1    -   -
 192.168.1.136  192.168.1.136   <   -   -   -   HTTP/1.1    201 Created
 192.168.1.136  192.168.1.136   >   POST    192.168.1.136:8000  /v1.6/containers/5aeb741bbe0c8340a45fb6f166cbcae19bf85a9714d7e229f81d67b722797307/start HTTP/1.1        -
 192.168.1.136  192.168.1.136   <   -   -   -   HTTP/1.1    204 No Content
 192.168.1.136  192.168.1.136   >   GET 192.168.1.136:8000  /v1.6/containers/json?all=0&limit=-1&trunc_cmd=1    HTTP/1.1    -   -
 192.168.1.136  192.168.1.136   <   -   -   -   HTTP/1.1    200 OK
```

**Comment by jimi-c** [comment]
# Information Request

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

We have some questions we'd like to know about before we can get this request queued up.   If you can help answer them, we'd greatly appreciate it:
- Since this is a relatively old ticket, and docker has matured quite a bit during this time span, does the reported issue still present with the latest version of Ansible and docker-py?

Just as a quick reminder of things, this is a really busy project.  We have over 800 contributors and to manage the queue effectively we assign things a priority between P1 (highest) and P5.  We'd like to thank you very much for your time! We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly.  You may also wish to join one of our two mailing lists
which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

As we have not had any updates on this issue, we are going to go ahead and close this. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
