### ISSUE TITLE
configure multiple inventory file in ansible.cfg

### ISSUE THREAD

**Issue by xdays** [ansible/ansible#5316]
Currently, hostfile option in ansible.cfg support two format: 
- a file where the hosts defined 
- a list of host:port pair

would it be mixing?

and I want to configure multiple iventory file with hostfile option.

I think hostfile should be a file or a list of files. hosts and groups shuold only be defined in inventory files

so I changed the `lib/ansible/inventory/__init__.py.`

any ideas?

**Comment by bcoca** [comment]
you can define a directory, all files in the directory will be used as
inventory, and if exectuable, executed as inventory script.

**Comment by mpdehaan** [comment]
Yep, that's the way to do it!

-i /path/to/directory

Where

directory has "inventory1" and "inventory2" in it.

I would be willing to entertain pull requests to allow "filename1:filename2" if not particularly intrusive, but since the above is there, I think that's not something we're going to actively work on.

Thanks and hope this helps!

**Comment by ElijahLynn** [comment]
Since this post comes up at the top of a search for "[multiple inventory files ansible.cfg](https://www.google.com/search?q=multiple+inventory+files+ansible.cfg)" I will say that #23001 (merged 2017.05.23), specifically 8f97aef1a3 brought the ability to specify multiple inventory on the CLI with `--inventory inventory1 --inventory inventory2`. I am currently searching for how to do this in the ansible.cfg so we can migrate from our shared inventory script here. https://gist.github.com/jchristi/c814d066d57a5d0cae5df5f110e85042

**Comment by ElijahLynn** [comment]
@sivel Helped me in IRC. :100: 

You can specify multiple inventory in ansible.cfg now with the paths separated by a comma.

`inventory = inventory1,inventory2`
