### ISSUE TITLE
Accelerate daemon keep running after playbook ends

### ISSUE THREAD

**Issue by adenot** [ansible/ansible#5326]
Hi all,
so the issue I'm having is that even after the playbook finishes executing, the python accelerate daemon still in memory, holding port 5099 open:

drupal   15140  0.0  1.9 369836 11692 ?        S    11:59   0:00 /usr/bin/python /tmp/ansible-1387331961.54-69937592280950/accelerate

I tried to change accelerate_timeout from 30 to 1, but no effect.

Is that a desired behaviour? 

The reason it is a problem for me is that at the company I work for, we have different teams calling their own ansible to the hosts to perform different set of operations. Since the port stays locked to the first ansible runner, other teams' ansibles fail to connect to the host.

I know that one solution would be to use different ports, but there is also a security concern that keeping ansible listening can be a backdoor to the host. Because of that, I would like to find a way to release the port as soon as the playbook finishes, is that possible?

Thanks.

**Comment by mpdehaan** [comment]
The accelerate daemon does stay running as another play or playbook may use it.

We have proposed that additional connections add keys to it if needed, and that's how we plan to fix this particular one, and there are some tickets regarding that behavior.

But no, it shouldn't end when the PB ends because there may be multiple sessions or playbooks using the daemon.

Different teams would need to set different ports.

I suspect the new SSH implementation currrently being tested (ssh_alt.py, aka -c ssh_alt) will eliminate much of the need for accelerate mode but that remains to be seen.

As for security concerns, Ansible isn't much of a backdoor -- you still need the key on the local host to use the accelerated connection, the daemon still terminates in 30 minutes, and it a key only has the lifetime of the 30 minutes.   

As far as killing ansible playbook as a rather basic workaround -- yes -- shell kill as root would be brutal and ugly, but would probably fly.

**Comment by mpdehaan** [comment]
merging with #5171
