### ISSUE TITLE
yum module: unexpected changed=false  with invalid url (http not package name)

### ISSUE THREAD

**Issue by mvermaes** [ansible/ansible#5327]
Hi, while working on a playbook, I noticed that I had a typo in the yum call, and this was still considered 'success'. I'm not sure if this is by design or not. Here's a simple way to recreate:

```
ansible -m yum -a 'name=http://www.doesnotexist.org state=present' host -vvvv
<host> ESTABLISH CONNECTION FOR USER: root
<host> REMOTE_MODULE yum name=http://www.doesnotexist.org state=present
<host> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/michaelv/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'host', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387353176.26-128357510629379 && chmod a+rx $HOME/.ansible/tmp/ansible-1387353176.26-128357510629379 && echo $HOME/.ansible/tmp/ansible-1387353176.26-128357510629379'"]
<host> PUT /tmp/tmpFtxizs TO /root/.ansible/tmp/ansible-1387353176.26-128357510629379/yum
<host> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/michaelv/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'host', "/bin/sh -c '/usr/bin/python -tt /root/.ansible/tmp/ansible-1387353176.26-128357510629379/yum; rm -rf /root/.ansible/tmp/ansible-1387353176.26-128357510629379/ >/dev/null 2>&1'"]
host | success >> {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "http://www.doesnotexist.org: Nothing to do"
    ]
}
```

**Comment by mpdehaan** [comment]
Sounds like "Nothing to do" was coming back from yum, so likely not something we can handle in this case.

We can check and see what return codes yum returns normally in this scenario and making sure the module conveys them.

**Comment by mvermaes** [comment]
I had a look at the yum return code behaviour for this, and while yum-3.2.29-40.el6.centos.noarch returns 1 if given an invalid url path, yum-3.2.22-40.el5.centos returns 0. So I had a go at a quick fix - #5329 - which seems to work on both versions.

**Comment by mvermaes** [comment]
#5333 might work better. Currently it changes the behaviour to fail for CentOS 5 and 6, but I think CentOS 5's yum doesn't understand http:// paths anyway so maybe that should be left unchanged.

**Comment by Jmainguy** [comment]
This fails correctly on Centos 6.

ca.soh.re | FAILED >> {
    "changed": false, 
    "failed": true, 
    "msg": "Package at http://www.doesnotexist.org could not be installed", 
    "rc": 1
}

On Centos 5

192.168.122.195 | success >> {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "http://www.doesnotexist.org: Nothing to do"
    ]
}

@mvermaes is correct that Centos5 does not understand yum install http:// it is actually looking for that package instead of following the url. As this is the way yum works on Centos 5 I can see two possibilities
1. Code ansible to fail on Centos/Rhel/Oracle Enterprise/Scientific Linux 5 when http:// is used in the yum module, provide error explaining http:// doesnt work in EL5.

Or 
1. Close this out and do nothing.

What do you guys think?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
