### ISSUE TITLE
htpasswd module: traceback with badly-formatted (invalid?) htpasswd files

### ISSUE THREAD

**Issue by alinnow** [ansible/ansible#5328]
When trying to use the `htpasswd` module with a htpasswd file formatted as below, ansible returns the message "msg: need more than 1 value to unpack". I found this confusing and it took me a long time to work out as I thought the error was with the playbook or variables. The file doesn't seem to cause any problems for nginx basic auth, which increased my confusion.

```

user:cryptpass

```

I'd be happy if ansible just said that there was some error passing the current htpasswd file.

**Comment by mpdehaan** [comment]
Can you please post the complete htpasswd file? 

It sounds as though you are saying the file format was invalid previously.

I agree the traceback is suboptimal but I want to confirm here.

Also as per contributing.md, what is the output of "ansible --version" ?

Thanks!

**Comment by alinnow** [comment]
An example htpasswd would be

```

user:us0OYDvjnlMyQ

```

It probably is invalid, but I had no idea before as it was generated in another tool and worked fine with nginx. You interpreted correctly; that's how it was before using ansible to manage it.

The version is 'ansible 1.4.1'.

**Comment by mpdehaan** [comment]
thanks!

**Comment by mscherer** [comment]
The htpasswd seems perfectly valid to me, so I wonder why it fail.
Can you paste the output of the following script: 

```
#!/usr/bin/python
import passlib
from passlib.apache import HtpasswdFile
HtpasswdFile('path/to/the/htpasswd/file')
```

**Comment by alinnow** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/passlib/apache.py", line 551, in __init__
    super(HtpasswdFile, self).__init__(path, **kwds)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/passlib/apache.py", line 166, in __init__
    self.load()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/passlib/apache.py", line 236, in load
    self._load_lines(fh)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/passlib/apache.py", line 261, in _load_lines
    key, value = parse(line, idx+1)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/passlib/apache.py", line 558, in _parse_record
    % lineno)
ValueError: malformed htpasswd file (error reading line 1)
```

Well, that error message is very clear. :)

**Comment by mscherer** [comment]
It work fine for me using the extract you gave in your 2nd comment, so I am a bit puzzled.

**Comment by alinnow** [comment]
Did you copy the empty first line as well?

**Comment by mscherer** [comment]
Nope, but it wasn't obvious this was important, that make a lot more sense now.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
