### ISSUE TITLE
Inventory file parser doesn't work with FQDN with :port notation and host pattern at the same time

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#5338]
When fixing and testing https://github.com/bob-smith/ansible/commit/4bf9f714d031d9f352dc71e23ac7522d9bf2d47f I came across the following problem which I couldn't fix

```
[servers]
host-[1:10].example.com:2222
```

Running in verbose mode

```
<host-2.example.com:2222> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/mnt/data/home/johnb/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '-6', 'host-2.example.com:2222', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387404391.33-211188223669355 && echo $HOME/.ansible/tmp/ansible-1387404391.33-211188223669355'"]
```

As Ansible then looks to connect to
host: host-4-4.example.com:2222
port: 22

I assume expand_hostname_range in lib/ansible/inventory/expand_hosts.py needs some work, but that's outside my current knowledge

I've created some more tests and will add them once this has been fixed by someone.

**Comment by mpdehaan** [comment]
Yes this is because it's using the pattern and the ":port" at the same time.

The workaround is

host-[1:10].example.com ansible_ssh_port=2222

**Comment by jimi-c** [comment]
As this issue has remained open for quite a while with no further updates, and there is a listed workaround, we're going to go ahead and close it now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
