### ISSUE TITLE
check remote md5sum before copy module execution

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#536]
The copy module should always chain into the file module, but we can spot check a remote md5 of the dest before executing it to decide to not transfer a large file.   This can be done by changing the execute_copy_module code in runner without any edits to the library/copy module.

The template path probably doesn't have to worry about this -- templates are small.

**Comment by dagwieers** [comment]
How about also implementing shortcuts (much like rsync does) by comparing sizes and timestamps.

I would not exclude templates from this because the check should be faster than a copy. (If it isn't already, it should be in the future). BTW /etc/postfix/main.cf is 27k and typically templated. Think 2000 machines and we're shipping 27MB. Now also consider multiple datacenters and leased lines, or branch offices... (have been in both cases recently)

**Comment by mpdehaan** [comment]
Well, each SSH command takes a bit, though with ControlMaster on life should be pretty good.

It may also be sufficient to just run the remote md5 if the file is larger than a MB or so, as even this optimization has a cost.

rsync is pulling back data on a lot of files, whereas we'll have to make a few more hops.

OT:  If you have multiple datacenters, it probably makes sense to have an ansible host in each and run them both from there.

**Comment by mpdehaan** [comment]
done
