### ISSUE TITLE
environment key usage is somehow broken with ansible > 2.4

### ISSUE THREAD

**Issue by kiorky** [ansible/ansible#53626]
##### SUMMARY
Consider this [test case](https://github.com/kiorky/ansible_test_cases/blob/master/environmentbug/t.yml)

- In ansible 2.7-,  this would suceed and is the behavior to be expected: an enviromnent argument on a block from playbook up to tasks should set accordingly env vars.
- In ansible 2.7, this fails silently, environment parameter/argument is ignored
- In ansible devel, this fails as "environment is not a valid argument for TaskInclude"

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
- devel
- 2.7

##### EXPECTED RESULTS
```
    "stderr_lines": [
        "+ test xbar = xbar"
    ],
```

##### ACTUAL RESULTS
devel

```
ERROR! 'environment' is not a valid attribute for a TaskInclude
```

2.7
```
    "stderr_lines": [
        "+ test x = xbar"
    ],

```

**Comment by sivel** [comment]
This is the expected behavior.  In Ansible 2.5 we made a change described in [Dynamic includes and attribute inheritance](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#dynamic-includes-and-attribute-inheritance)

This meant that only certain keywords had any effect on `include_tasks` and `include_role`.  Before 2.7 any key that would have no effect was ignored.

In 2.7 we added validation of which keys work as expected, which means that you get an error when trying to provide an invalid key on a dynamic include.

Also in 2.7 we introduced a new argument to `include_tasks` and `include_role` called `apply` that does what you want:

```
    - include_tasks: it.yml
        apply:
          environment: {foo: bar}
```

When using a dynamic include, any task keywords you provide, can only affect the including of the file, not the execution of the tasks within the include.  The `apply` argument, allows you to "apply" a set of keywords to all tasks within the include.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by kiorky** [comment]
I do not agree, prior to 2.5, the environment setting was not ignored, did you read ?

**Comment by kiorky** [comment]
But, yes, i see how to fix with apply ...

Just that it will break compat :(

**Comment by sivel** [comment]
Prior to 2.5 it was not.  With the 2.5 release we made a purposeful change that ignored it.  In 2.7 we added further clarification to error.

**Comment by kiorky** [comment]
I understand the purpose, but that's really a big/tedious breaking change, maybe can something that parse & transform old keywords (like tags or environment) to the according apply structure be done ?

Even if we all understand that a new release may not be compatible with older change, here this is hard to spot and really hard to maintain setup compatibles amongst ansible versions.

**Comment by kiorky** [comment]
To sum up, for all those falling here

To port include_tasks including keywords from 2.4 to upper release, you can either use "apply" or "block wrapping". The second form is retro compatbile

2.4
```yaml
- include_tasks: t.yml
  environment: {foo: bar}
```


2.5+
```yaml
# either
- include_tasks: t.yml
  args: {apply: environment: {foo: bar}}

# or 
- block: 
   - include_tasks: t.yml
  environment: {foo: bar}
```
