### ISSUE TITLE
Wildcard group matching shouldn't be applied to the all or ungrouped groups

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#5375]
The all or ungrouped groups should be not matched by wildcards like "a*"

It's a niche usage, but it doesn't seem like that should be a thing, since if trying to hit hostnames starting with "a" that would be confusing.

See discussion thread here:  https://groups.google.com/forum/#!topic/ansible-project/DK6FSofyZ4M

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
