### ISSUE TITLE
debug module: syntax warning not provided inside jinja template (?)

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5391]
Not sure the description is corrent nor this relates to Ansible but not to Jinja.

Suppose simple playbook

``` yaml
- hosts: localhost
  tasks:
     - debug: msg="{{lookup('password', '/tmp/foo.txt'}}"
```

When you run it you'll get the following output (but not the one you would expect):

```
$ ansible-playbook test.yml 

PLAY [localhost] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg="{{lookup('password', '/tmp/foo.txt'}}"] ********************* 
ok: [localhost] => {
    "msg": "{{lookup('password', '/tmp/foo.txt'}}"
}

PLAY RECAP ******************************************************************** 
localhost                 : ok=2    changed=0    unreachable=0    failed=0   
```

The error here is missing closing `)` for the lookup filter which is not easy to notice.

The expected behaviour would be producing error/warning about that.

**Comment by mpdehaan** [comment]
What version of Ansible are you using?

NOTE: this probably just applies to the debug module.

**Comment by timurb** [comment]
```
$ ansible --version
ansible 1.5 (devel f96f69ece3) last updated 2013/12/16 16:23:13 (GMT +400)
```

No, if I use `copy` instead of debug the bug is still there:

``` yaml
  - copy:
      dest=/tmp/out
      content="{{lookup('password', '/tmp/foo.txt'}}"
```

with the output like:

```
TASK: [copy dest=/tmp/out content="{{lookup('password', '/tmp/foo.txt'}}"] **** 
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [debug msg={{lookup('password', '/tmp/foo.txt'}}] **************************
fatal: [localhost]: FAILED! => {"msg": "ERROR! template error while templating string: unexpected '}', expected ')'", "failed": true}
NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
