### ISSUE TITLE
rax_clb_nodes module: state=present errors out on repeated run

### ISSUE THREAD

**Issue by claco** [ansible/ansible#5401]
When adding a node to a load balance with state=present, it throws an error on subsequent ansible runs with:

"Duplicate nodes detected. One or more nodes already configured on load balancer."

I would assume "present" should just be a changed=False noop if it's already in the LB.

**Comment by mpdehaan** [comment]
Something you would like to work on, perhaps?

**Comment by sivel** [comment]
It looks like if you do not specify node_id, it tries to create a node.

@claco, I am assuming you are not including node_id on future runs?

We probably need to update the code:

``` python
    if node_id:
        node = _get_node(lb, node_id)
    else:
        node = None
```

To look for more than just node_id, perhaps an address:port combination as well.  Because later the `node` var is inspected to determine if we are creating a node or not.

However, as an aside, when using the `rax` module for creating hosts, you can rely on the `action` attribute to determine if the action was `create` and the `success` attribute for looping, instead of perhaps always looping `instances`.

I'll wait to hear if you are planning on working on this before I decide to dig into adding this functionality.

**Comment by claco** [comment]
Correct, I'm not including node_id on any run, first, or future. Just a straight address/server combination. I mostly tossed this issue in here so I didn't forget to dig deeper.

**Comment by mpdehaan** [comment]
@sivel et al, I'm trying to close out some old tickets, can you take a look at this one or decide whether it can be closed?

**Comment by sivel** [comment]
@mpdehaan Let's leave it for now.  I may have a fix, but need to test it a bit more.  I'll update this ticket soonish.

**Comment by mpdehaan** [comment]
@sivel and company - let us know if you have a pull request for this.    Making a sweep through cloud tickets.

Thanks!

**Comment by sivel** [comment]
Will do. I do have a branch but need to run it by a few people first.

**Comment by sivel** [comment]
I've just opened a pull request for this issue at #6862

**Comment by jimi-c** [comment]
This has been resolved by the above merge, and will be included in the next major release. If you continue experiencing any problems related to this issue, or if you have any further questions please let us know. Thanks!
