### ISSUE TITLE
service module: would be nice to support ampersand "@"

### ISSUE THREAD

**Issue by senorsmile** [ansible/ansible#5407]
Trying to control openvpn on an arch linux server.  

Able to successfully start the service on the box with

```
systemctl start openvpn@server
```

but when I try to do the same from ansible I get:

```
failed: [laprouter] => {"failed": true, "item": ""}
msg: Failed to issue method call: Unit name openvpn@.service is not valid.

FATAL: all hosts have already failed -- aborting
```

Here is the part of the yml config:

```
- name: Ensure openvpn service enabled
  service: 
    name="openvpn@server"
    state=started
```

It appears that ansible is incorrectly parsing the service name when it has an ampersand.  Initially reported on google groups at: 
https://groups.google.com/forum/#!topic/ansible-project/jajY_-n6qps

**Comment by mpdehaan** [comment]
It knows how to send the "@" in a few cases for systemd (systemd is supported) but like you have said in the ticket with multiple kinds of copies for the service it doesn't know about that and needs to be enhanced some.

**Comment by bobobo1618** [comment]
I'm having this issue as well.

P.S. @senorsmile `@` is not an ampersand. `&` is an ampersand :)

**Comment by Jmainguy** [comment]
This is working for me with latest devel, and Centos 7. Is this still an issue? If so, is this limited to Arch or all OS's?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
