### ISSUE TITLE
Feature - include file name should support variable

### ISSUE THREAD

**Issue by liangshan** [ansible/ansible#5424]
In some scenarios, it's useful to include different yaml depend on different variables.

Example:
if user is 'Alice', then

``` yaml
- include: alice.yaml
```

if user is bob, then

``` yaml
- include: bob.yaml
```

so i want this:

``` yaml
- include: "{{user}}.yaml"
```

but ansible returns error:

```
ERROR: file not found: /path/to/ansible/provision/{{user}}.yaml
```

**Comment by liangshan** [comment]
now i resolve it like this:

```
- include: alice.yml
  when: user == 'alice'

- include: bob.yml
  when: user == 'bob'
```

but it's seems weird :(

**Comment by mpdehaan** [comment]
include is how you include task steps, and this may not use inventory variables since all includes must apply to each host.

The when statement works by applying the conditional to each included task.

This is working as designed and we're not going to make any changes here

Please stop by the mailing list if you have further questions.

Thanks!

**Comment by bluesalt** [comment]
The feature is supported now. You can achieve that by dynamic/static include.
