### ISSUE TITLE
Facts and info modules

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#54280]
##### SUMMARY
Facts and info 

## `_facts` vs `_info` modules and ansible_facts

If a module is named ``<something>_facts``, it should be because its main purpose is returning ``ansible_facts``. Do not name modules that do not do this with ``_facts``.
Modules that query/return general information (and not ``ansible_facts``) should be named ``_info``.

Docs will be updated in https://github.com/ansible/ansible/pull/54182

The place for discussion outside of https://github.com/ansible/community/issues/346

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
facts

**Comment by gundalow** [comment]
bot_skip

**Comment by gundalow** [comment]
@zikalino said

I wonder what should be our action regarding facts -> info change.
in fact we should rename all `azure_rm_..._facts` modules to `azure_rm_..._info`
so, there are several questions:

(1) we are still planning to merge a few missing azure_rm_*_facts modules before freeze. should we merge them as _facts or use new _info convention?

(2) there are several new azure_rm_..._facts modules in devel. should we just rename them before freeze, so we won't have to do that later?

(3) and finally if we decide to to (1) and (2),  should we attempt to rename / create new _info modules for existing facts modules before freeze to keep everything consistent?

In fact, i really like the idea of introducing `_info` modules, it gives us opportunity to migrate all the facts modules into new info modules and make them match all the guidelines we worked out during last year or so. currently azure facts modules are quite inconsistent. some of them return ansible_facts and some don't, also they use very different format. so this is real opportunity to clean it up.

the only question is, should we try to fully migrate before freeze, and have everything in order already in 2.8, or just to start introducing _info modules after 2.8.
I would like to either do (1), (2) and (3) at once or just release things in old way and do all the changes after 2.8.

**Comment by gundalow** [comment]
@Andersson007 said:

could you please give me a couple of examples of _info modules?
I couldn't have found any.
And is new postgresql_facts module actually _facts or _info type?
Seems it returns a lot of facts that we might use to change runtime playbook's behavior

**Comment by felixfontein** [comment]
I've recently renamed all crypto and docker `_facts` modules to `_info` (PRs #54082 and #54124). The main reason for this is (next to that I think they should not return `ansible_facts`) that most of the `docker_*_facts` modules have only been added for 2.8, so now's the best time to rename them. (Before 2.8, there were only one crypto and one docker `_facts` module.)

In my opinion, modules which return information about objects which are not unique for the host. My favorite example are (docker) containers: there are usually several running on a host, so putting information about one docker container into `ansible_facts.docker_container` doesn't seem like a good idea to me. Especially because that makes working with `register` a lot more complicated: if you register the result into `x`, you need to write `x.ansible_facts.docker_container` to access the results for this specific container, instead of simply writing `x.docker_container`.

I don't know whether there are official guidelines when `ansible_facts` should be returned or not, so I guess everyone has to decide for their own whether returning `ansible_facts` makes sense for their modules.

**Comment by zikalino** [comment]
@gundalow thanks for starting this thread.
@felixfontein thanks for posting references to your prs -- it's actually very useful to see how to do actual renaming.
I am actually wondering about a few things.
you have created symbolic links _*_facts that start with underscore. is there any special meaning for the leading underscore?
i also wonder how the ci handles the situation where _*_facts doesn't match actual module name within the file (*_info).
Final issue to solve is making old facts module obsolete. Since the documentation content is just linked from *_info module, there will be no way to have information that old *_facts module is obsolete.
I saw the comment inside **docker_image_info** module:
"This module was called C(docker_image_facts) before Ansible 2.8. The usage did not change."
Do you plan to make this module obsolete? Or both facts and info are going to stay?

**Comment by felixfontein** [comment]
@zikalino the underscore marks the module as deprecated. The documentation will only be created for the new module name, not for the old module name. The deprecation marker (shown when using the old module name) says the old module (name) will be removed in Ansible 2.12, i.e. at that point we will delete the symlink (and remove the code for the marker). That is, both names for the module can be used until Ansible 2.12 (where `_facts` always triggers a deprecation warning), and from 2.12 on only the `_info` version is still around.

I'm not sure whether for renamed modules, a stub module (like https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/_docker.py) will be created, or if simply the symlink will be removed. @gundalow can you (or someone else) comment on this?

**Comment by zikalino** [comment]
thanks for info @felixfontein !
about your docker facts / info modules, you wrote:

"My favorite example are (docker) containers: there are usually several running on a host, so putting information about one docker container into ansible_facts.docker_container doesn't seem like a good idea to me. Especially because that makes working with register a lot more complicated: if you register the result into x, you need to write x.ansible_facts.docker_container to access the results for this specific container, instead of simply writing x.docker_container."

so I guess (if you want to stick data into ansible_facts), you could either return a dict:

ansible_facts.[container_id].xxx

or a list:

ansible_facts.containers[]

with container_id inside.

It gets more complex with cloud infractructure as it's not really related to local host in any way.

**Comment by zikalino** [comment]
@gundalow 
@nitzmahone 

what would be your advice for us?

we have
- around 35 new _facts modules introduced in Ansible 2.8, so could be just renamed
- 14 _facts modules introduced before 2.8 that are actually not returning **ansible_facts** already, so they we have just to use rename / obsolete pattern with symbolic link (hopefully)
- 15 very old facts modules that return **ansible_facts** and result is not curated, meaning we will have to have 2 different versions (keep old facts and introduce new info modules that is actually different). this will be the most time consuming.

Should we try to upgrade all of these before freeze? Or just start thinking about it after the freeze?
If we wait after the freeze, we will have around 35 new facts modules that will have to be obsoloeted....

**Comment by yungezz** [comment]
What's the plan of changing all existing _facts module without returning ansible_facts to _info in general? is it going to happen in ansible 2.8? I really suggest do the azure modules change after 2.8. We don't want to do last minute change before code freeze, because the change requires lots of testing.

**Comment by felixfontein** [comment]
@zikalino `ansible_facts[container_id].xxx` would indeed be possible, but that can lead to annoying problems when suddenly a lot of stuff is available globally. (There's an option to disable having facts available as global variables, but the default is still to have them around globally.)

The docker_service/docker_compose module used to do something like that, but instead of using an ID, it used the service name (IIRC), which is usually short and human readable, and caused some complaints because users thought their variables of the same name were suddenly overwritten.

@yungezz at least in the discussion at the public Ansible project meeting, someone mentioned that it's better to do the main bulk rename for 2.9, since there will be a *lot* of renames (several hundrets I think) and there isn't that much time left, and as you said, there's need for a lot of testing.

**Comment by zikalino** [comment]
@felixfontein so perhaps that's the way to do it. if there's several hundreds modules globally it's better to keep it coordinated and do it at once... I think there should be some kind of bigger community announcement about this.

**Comment by felixfontein** [comment]
@zikalino yep, I guess the main question is what to do with new modules. Having them new with `_facts` and renaming them in the next version to `_info` sounds somewhat annoying. But I guess every team has to decide for themselves what to do, if there's no "global" advice from the core team. Both renaming new modules now (avoid renames later) and renaming all `_facts` modules at once (less confusion for users why there are `_facts` and `_info` modules) have their advantages. And 14 vs. 35 is a different situation than 1 vs. 6 modules...

**Comment by zikalino** [comment]
@felixfontein so what have triggered your decision to make it just before freeze?

**Comment by Andersson007** [comment]
@gundalow 
@felixfontein 
https://docs.ansible.com/ansible/devel/modules/postgresql_facts_module.html
shortly, is this actually _facts or _info module ? should I rename this ?

**Comment by bcoca** [comment]
@Andersson007  yes, rename would be better

**Comment by bcoca** [comment]
@gundalow 
1) yes
2) yes
3) i would like, but would not block on this

**Comment by zikalino** [comment]
@bcoca after internal discussion we have to do 1, 2 and 3 at once.
so seems like we still have to break the rule in 2.8, and rename all the facts modules in 2.9.
I think there's a lack of strong message regarding the action to rename all **facts** to **info** and when it should be done.
I think most of the developers may be still confused about the actual status of new **info** modules.

**Comment by yungezz** [comment]
@bcoca  how about renaming all _facts to _info in ansible 2.9 given code freeze very near? when will the change be officially announced to ansible users? 2.9? We'll follow the overall plan to do the azure modules renaming.

**Comment by Andersson007** [comment]
[#54389](https://github.com/ansible/ansible/pull/54389) renamed postgresql_facts -> postgresql_info

**Comment by bcoca** [comment]
@yungezz the rule about `_facts` modules returning ansible facts has been long standing (but seems to have been ignored by many), the `_info` requirement is new, but since the modules are also new in 2.8 it is preferable to avoid the problem vs adding a rename/deprecation cycle in 2.9 that would make it persist up to 2.13.

**Comment by gundalow** [comment]
For modules that are new in Ansible 2.8 it would be great to get them renamed before freeze so we don't have to add an alias in.

For modules that were released in Ansible 2.7 or earlier there is no rush. Time would be better spent reviewing and fixing bugs. 

For modules that have been previously released a clear changelog/fragment and porting_guides entry is needed.

**Comment by nitzmahone** [comment]
I greenlit the merging of new _facts modules toward the end of 2.8 as the changeover to `_facts` was  still an open question at the time, and the original freeze date would already have passed by now. Unless someone *really* wants to go back and rename them in the week before community freeze, I'm not concerned about it; whatever change we apply to the scores of `_facts` modules in 2.9 will apply to these few new ones too.

**Comment by bcoca** [comment]
@nitzmahone it was rename to _info that is new, its been long standing rule that _facts modules are those that return ansible_facts.

**Comment by zikalino** [comment]
@bcoca regarding the rule of returning or not returning facts from modules.
the oldest azure modules were indeed returning **ansible_facts** but then at some point we learned that they actually shouldn't stick return values into **ansible_facts** as **ansible_facts** are intended for host-related facts and cloud related facts are not really related to **localhost**. unfortunately at the time there was no **info** modules idea.... so we ended up with very different implementation.

now, it would be good to rename all facts to info at once, but seems like the time may be too short.
(we also have new documentation to update, etc.)

**Comment by zikalino** [comment]
our current thinking is that:
- we should just release all the modules in 2.8 as **facts**
- rename and clean-up everything in 2.9

**Comment by bcoca** [comment]
The renaming to _info, as i said above is recent, the rule on _facts name has existed for much longer, in any case accepting those modules was a failure on review, i opened #54432 that i think deals with most of the changes needed.

**Comment by yungezz** [comment]
@bcoca  totally understand the rule of _info and ansible_facts for facts now. but we just learnt the rule around 4 days ago from this issue. Current situation at azure modules is that all azure get operation are named as _facts already, this is legacy before we work on it. We already has lots of  official documentation at docs.azure.doc to teach user how to use azure modules including _facts modules. and our preview role modules are named as _facts. So renaming azure modules will include below changes:
- change ansible/ansible modules,  and figure out how to keep backward compatibility
- change documentation and publish them
- change role modules
- somewhere to let user know that old _facts modules were renamed to _info.

Given it's just less than one week before code freeze, we're not ready for this change, or do it partially. we'd like to leave them as _facts for now. and change **ALL** of them at 2.9 in one batch. So user  will not meet the confused  situation: some of resource get is _facts, some of resource get is _info. that's why the revert PR.

We're fully support the consistent in ansible modules and following all rules we're aware of. Thanks for understanding.

**Comment by zikalino** [comment]
@yungezz even if we decide to rename all the old facts modules they will still be around until Ansible 2.12, so no need to hurry with the documentation.

all we need to do is:
- rename *_facts -> *_info
- create symbolic link starting with underscore: _*_facts

in this way old _*_facts modules won't be visible in the documentation (or they will be visible as obsolete in 2.12?)

**Comment by zikalino** [comment]
maybe a stupid idea.
how about we have all then new **_info** modules as @bcoca would like us to and create aliases/links with **_facts** postfix? does it sound stupid?

**Comment by felixfontein** [comment]
Here are docs for one of the renamed modules (docker_image_facts → docker_image_info):
 - latest (2.7): https://docs.ansible.com/ansible/latest/modules/docker_image_facts_module.html
 - devel (2.8): https://docs.ansible.com/ansible/devel/modules/docker_image_info_module.html

The new docs mention "Aliases: docker_image_facts". The link https://docs.ansible.com/ansible/devel/modules/docker_image_facts_module.html unfortunately does *not* work (404). (I.e. the `latest` link will stop working once 2.8 is released.)

**Comment by felixfontein** [comment]
@zikalino I don't know if adding aliases is a good idea, but if you do so, you should add a deprecation warning (I guess for 2.13, since that will be when modules renamed for 2.9 will be removed) to the module which is printed when the module is used by the alias name.

**Comment by felixfontein** [comment]
There's an issue for the docs alias problem: #42949

**Comment by nitzmahone** [comment]
Since the `_facts` rule was agreed upon very late in the 2.8 cycle (and has only been a haphazardly-enforced/documented guideline previously), it'll be left to the module maintainer's discretion whether new `_facts` modules introduced in 2.8 that don't return `ansible_facts` should be renamed to `_info`. In 2.9, we'll figure out a path to aliasing everything and disallowing new `_facts` modules that don't return facts (which will be called `_info` modules going forward).

**Comment by bcoca** [comment]
As IRC meeting, we wont require removing misnamed `_facts` modules that are new in 2.8 and already merged into devel.

**Comment by felixfontein** [comment]
FYI: I've started renaming some `_facts` modules to `_info` (#56822, #57020, #57028, #57030, #57035, #57036, #57032). There are more `_facts` modules in cloud/amazon (44), cloud/azure (52), cloud/digital_ocean (12), cloud/google (52) and cloud/vmware (33) which do not return `ansible_facts`.

@zikalino do you already have plans for renaming the cloud/azure modules?
