### ISSUE TITLE
digital_ocean module doesn't allow secure delete of droplets

### ISSUE THREAD

**Issue by lichesser** [ansible/ansible#5462]
Apparently DO doesn't secure delete droplets by default. `scrub_data` must be set to `true` on `destroy` in order to safely destroy your data.

The python wrapper the `digital_ocean` module uses (I think https://github.com/devo-ps/dopy) supports the `scrub_data` option on the `destroy_droplet` call (it's `false` by default) but this option can't be set via the ansible module.

See
- https://developers.digitalocean.com "Destroy Droplet" documentation
- https://github.com/fog/fog/issues/2525
- https://digitalocean.com/blog

for more information

**Comment by mpdehaan** [comment]
Reading the fog ticket now, that does strike me as a remarkably poor choice in a system default and their pointing the finger at fog for something that should have been handled on the backend is also a poor decision.

However, it looks like they are fixing it despite the hand-waving.

From the Digital Ocean blog:

Direct link here:  https://digitalocean.com/blog_posts/transparency-regarding-data-security

"Our first and immediate update is to ensure that a clean system is provided during creates, regardless of what method was taken for initiating a destroy. Engineers are updating the code base right now to ensure that will be the default behavior, and we will provide another notice when that code is live."

So it sounds like the security issues are being dealt with on their end, despite their extremely poor choice of not making scrubbing always happen on delete as well.

I'm not sure why they should be so concerned with delete performance.

That being said, we should absolutely update our modules to send the scrub=True by default for those that don't know about their backend issues.    

Since you appear to be a user, would you like to contribute and test a pull request?

**Comment by mpdehaan** [comment]
Relevant pull request to dopy:  https://github.com/devo-ps/dopy/pull/7

**Comment by mpdehaan** [comment]
Note:  we've applied a change to fix this branch already, so this ticket can be closed.  I've also started a thread on the mailing list to discuss details.

The ultimate fixes are going to be with Digital Ocean's SAAS code per the blog post, and the dopy change along with the ansible change should make this extra-redundant.
