### ISSUE TITLE
service doesn't always start services?

### ISSUE THREAD

**Issue by rtirrell** [ansible/ansible#549]
I have `action: service name=postgresql state=started`, and yet the service doesn't actually start - I just get `{"changed": false}` in the output. Works fine invoked from command line with `service potsgresql start`. Am I missing something? Glancing at the code it looks like it should work fine.

**Comment by mpdehaan** [comment]
So, the bug tracker isn't the best place for debugging things and seeing what the actual cause is, but the most recent service module should be in good shape.    Provided you are already using 0.5, how about asking on the mailing list and we can file a bug if there is something to change.

(Patches are, of course, always preferred to bugs, and everyone is expected to do some of the debugging)
