### ISSUE TITLE
route53 hostname not used for host_vars lookup

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible#5495]
https://github.com/ansible/ansible/pull/4213 added support to address instances by their names in route53, but a host_vars file with the same name is not being picked up by ansible.

**Comment by mpdehaan** [comment]
So this seems related to the recent question about dynamically added groups (created using group_by) not loading their "group_vars" file, which could be solved with a related fix.

As per instructions in contributing.md, can you please share what version of Ansible that you are using?

**Comment by pgehres** [comment]
devel:HEAD (191be7b951eb8c34b73b367334e0cb4343af0779 as of now)

**Comment by mpdehaan** [comment]
Thanks!

**Comment by jctanner** [comment]
@pgehres can you show me a sample playbook for what you are trying to do here?

**Comment by jctanner** [comment]
@pgehres I'm having difficulty reproducing this.

```
[jtanner@f18 5495-route53-hostvars]$ cat site.yml
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug: msg="{{ inventory_hostname }}"

- hosts: instance1.hullabaloo.com
  connection: local
  gather_facts: False
  tasks:
    - debug: msg="{{ inventory_hostname }}"
    - debug: msg="{{ hostvars[inventory_hostname]['foo'] }}"
[jtanner@f18 5495-route53-hostvars]$ cat group_vars/instance1.hullabaloo.com.yml
foo: bar
```

Result:

```
[jtanner@f18 5495-route53-hostvars]$ ansible-playbook -i inventory site.yml

PLAY [localhost] **************************************************************

TASK: [debug msg="{{inventory_hostname}}"] ************************************
ok: [localhost] => {
    "msg": "localhost"
}

PLAY [instance1.hullabaloo.com] ***********************************************

TASK: [debug msg="{{inventory_hostname}}"] ************************************
ok: [54.213.28.32] => {
    "msg": "54.213.28.32"
}

TASK: [debug msg="{{hostvars[inventory_hostname]['foo']}}"] *******************
ok: [54.213.28.32] => {
    "msg": "bar"
}

PLAY RECAP ********************************************************************
54.213.28.32               : ok=2    changed=0    unreachable=0    failed=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

If you could provide more information about how your scenario differs from mine and an example playbook, I'll keep this open. Otherwise, I will consider this resolved.

**Comment by pgehres** [comment]
```
ansible-playbook -i ec2.py site-aws.yml -l host.subdomain.appdynamics.com --sudo

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [ec2-WW-XX-YY-ZZ.us-west-2.compute.amazonaws.com]

TASK: [gather aws facts] ******************************************************
ok: [ec2-WW-XX-YY-ZZ.us-west-2.compute.amazonaws.com]

PLAY [tag_aws_utility] ********************************************************

GATHERING FACTS ***************************************************************
ok: [ec2-WW-XX-YY-ZZ.us-west-2.compute.amazonaws.com]

TASK: [aws-utility | debug msg="{{omg_wtf_bbq}}"] *****************************
fatal: [ec2-WW-XX-YY-ZZ.us-west-2.compute.amazonaws.com] => One or more undefined variables: 'omg_wtf_bbq' is undefined

FATAL: all hosts have already failed -- aborting
```

site-aws.yml

```
- hosts: tag_aws_utility
  accelerate: true
  roles:
    - aws-utility
```

roles\aws-utility\tasks\main.yml

```
---
- debug: msg="{{ omg_wtf_bbq }}"
```

host_vars\host.subdomain.appdynamics.com

```
omg_wtf_bbq: "Hello world!"
```

**Comment by jctanner** [comment]
@pgehres can I see an example output from ec2.py ?

**Comment by jctanner** [comment]
@pgehres I took the ec2.py outputs from your email and lumped them into a fake ec2 inventory script. I was able to duplicate the behavior you described, but I think it's the expected behavior. When the playbook runs, it's going to load host var files that match keys for inventory hosts. In your case, the keys are the public dns names for your nodes (ec2-XX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com). These keys won't match the route53 hostname and therefore the host var file named "route53-something.com.yml" will not get loaded. 

However, "route53-something.com" is now a group and the node is a member of that group. That gives you the ability to move the route53-something.com.yml file from host_vars/ to group_vars/ and it will load as expected. Does that make sense and will it work for your setup?

**Comment by pgehres** [comment]
@jctanner well, the concern I have is that we use the route53 domain as a permanent "name" for the host. If we rebuilt the underlying ec2 instance, the "ec2-XX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com" would change and we would have to update the name of the host_vars file even though it is still the same instance.  The group_vars hack would work, yes, but it is a host by definition, and that is a hack.

Is there any merit to using the route53 name as the ansible_hostname when the host is discovered through that method? 

@mpdehaan thoughts?

**Comment by jctanner** [comment]
@pgehres so you want the route53 hostname to become the key in inventory rather than the public dns name that is in the node metadata?

**Comment by pgehres** [comment]
I just want it to be a key; I don't need it to replace the original key. But, yes.

**Comment by mpdehaan** [comment]
So I believe this conversation was already resolved previously over other discussions, but the ticket wasn't closed.

Basically Ansible doesn't do multiple keys for the same host.  The system just doesn't work this way.

The names coming back from ec2.py are ephmeral and should not be expected to be constant.  There are some tuning settings exposed in ec2.ini that allow the keys to be changed.

However, the ec2 plugin does support grouping by ec2's route53 names to find a host, which effectively can serve as an alias:

https://github.com/ansible/ansible/blob/devel/plugins/inventory/ec2.py#L377

Since ec2.py is only an "example" plugin however, it is possible to tweak it to operate in non-standard ways if you so desire, but changing the default to pull down extra route53 info wouldn't work because the host in Ansible can have only one name.  There's not a system of aliases.

Definitely one would not want to add the same host with two different names as that would cause extra configuration.
