### ISSUE TITLE
Feature request: role syntax check

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#5524]
syntax-check in ansible-galaxy would be nice, which checks syntax of the role including meta

**Comment by mpdehaan** [comment]
This really should be part of ansible's overall syntax check IMHO for ansible things (which it is with --syntax-check, because not only should the syntax be checked, people should test the role), and then the Galaxy website should do the check on role upload, so everybody doesn't have to do it on download.

I'll pass this along, thanks!
