### ISSUE TITLE
Ansible module documentation on one page

### ISSUE THREAD

**Issue by aw** [ansible/ansible#5529]
Hi,

I :heart: the new Ansible documentation format/site, unfortunately it abolished the "one page with all modules" :rage1:.

That page, although not ideal, was useful for performing quick searches `ctrl+f or cmd+f` throughout all modules. It was also perfect for working offline `print->PDF`.

Would it be possible to generate this "one magic page" as well using Sphinx? :panda_face: 

Thanks!

**Comment by sivel** [comment]
Due to the requests I have seen, I actually worked on this a little last week, but never sent a pull request, simply because I'm not much in need of it, and I'm not sure what the goals are for the doc site.  

Here is the branch where I did the work in, but I will wait for additional feedback before sending a pull request.  Don't want to cause extra work if this is not something that is not wanted.

https://github.com/sivel/ansible/tree/all-modules-docs-page

**Comment by mpdehaan** [comment]
So there already is a list of all modules available in the category section.

I don't really want to see them all on one page as that gets too long and most people complain about that format.

I think this goes to show that if you implement something, there will always be disagreements.

I think there should be a "sleep on it" period here and we'll see how many new users can get along with the new way it is organized, but I am very very very very very very very much not liking the near infinite scrolling.

**Comment by aw** [comment]
I'm not suggesting you REVERT the current documentation. I merely would like to keep the old feature for the reasons described above.

The use-case is having access to the same documentation offline. Perhaps it's possible to generate a PDF of the docs site using Sphinx?

**Comment by ghost** [comment]
@aw agreed.

Linking this to the related issue #4265.
