### ISSUE TITLE
acl module - recursive flag feature

### ISSUE THREAD

**Issue by albanduval** [ansible/ansible#5550]
The `setfacl` command is often used recursively, it's too bad the module cannot be used that way.

**Comment by mpdehaan** [comment]
Rather than "it's too bad", perhaps you mean "it would be nice if"?  :)

Feature pull requests to add this would be considered, though you can also just shell out to setfacl right now using the shell module.

**Comment by bcoca** [comment]
I have a PR that adds the 'default' acl to a directory (which is inherited
by all entities under it).

I did not add recursive because it was muddling the code and can be very
time consuming to properly reflect changed vs OK.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
I agree that we probably don't want to add recursive to every single module, though we can do this with 'shell' commands when needed when someone wants it.

**Comment by slavafomin** [comment]
Hmm. All ACLs in my project are recursive.
