### ISSUE TITLE
Verbose output from ansible-playbook when using list of hashed variables

### ISSUE THREAD

**Issue by greenbrian** [ansible/ansible#5564]
When a list of hashes are used as variables, ansible-playbook output is very verbose, printing out the full hash contents.  My working playbooks have longer variable files, so the terminal is constantly filled with useless information.

Also, when used with debug, the output is full item results are printed to stdout. I'd like to have very short output of tasks using 'debug: var=' for administrators to easily see output of tasks (ie process_status=running/stopped, deployed software versions).

```

---

- hosts: localhost
  vars:
    myapp:
      - name: app1
        somesetting: nope
        othersetting: yep
        dontyouhatepants: yep
      - name: app2
        somesetting: yep
        othersetting: yep
        dontyouhatepants: nope
  tasks:
  - name: just an echo
    shell: /bin/echo "{{ item.name }}"
    with_items: myapp
    register: echo
  - debug: var=item.stdout
    with_items: echo.results



$ ansible-playbook -i inv/TEST test.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [just an echo] **********************************************************
changed: [localhost] => (item={'dontyouhatepants': 'yep', 'name': 'app1', 'othersetting': 'yep', 'somesetting': 'nope'})
changed: [localhost] => (item={'dontyouhatepants': 'nope', 'name': 'app2', 'othersetting': 'yep', 'somesetting': 'yep'})

TASK: [debug var=item.stdout] *************************************************
ok: [localhost] => (item={'item': {'dontyouhatepants': 'yep', 'name': 'app1', 'othersetting': 'yep', 'somesetting': 'nope'}, u'delta': u'0:00:00.002124', u'cmd': u'/bin/echo "app1" ', u'end': u'2014-01-09 16:41:02.251091', u'stderr': u'', u'stdout': u'app1', 'invocation': {'module_name': 'shell', 'module_args': u'/bin/echo "app1"'}, u'changed': True, u'rc': 0, u'start': u'2014-01-09 16:41:02.248967'}) => {
    "item": {
        "changed": true,
        "cmd": "/bin/echo \"app1\" ",
        "delta": "0:00:00.002124",
        "end": "2014-01-09 16:41:02.251091",
        "invocation": {
            "module_args": "/bin/echo \"app1\"",
            "module_name": "shell"
        },
        "item": {
            "dontyouhatepants": "yep",
            "name": "app1",
            "othersetting": "yep",
            "somesetting": "nope"
        },
        "rc": 0,
        "start": "2014-01-09 16:41:02.248967",
        "stderr": "",
        "stdout": "app1"
    },
    "item.stdout": "app1"
}
ok: [localhost] => (item={'item': {'dontyouhatepants': 'nope', 'name': 'app2', 'othersetting': 'yep', 'somesetting': 'yep'}, u'delta': u'0:00:00.002419', u'cmd': u'/bin/echo "app2" ', u'end': u'2014-01-09 16:41:02.308687', u'stderr': u'', u'stdout': u'app2', 'invocation': {'module_name': 'shell', 'module_args': u'/bin/echo "app2"'}, u'changed': True, u'rc': 0, u'start': u'2014-01-09 16:41:02.306268'}) => {
    "item": {
        "changed": true,
        "cmd": "/bin/echo \"app2\" ",
        "delta": "0:00:00.002419",
        "end": "2014-01-09 16:41:02.308687",
        "invocation": {
            "module_args": "/bin/echo \"app2\"",
            "module_name": "shell"
        },
        "item": {
            "dontyouhatepants": "nope",
            "name": "app2",
            "othersetting": "yep",
            "somesetting": "yep"
        },
        "rc": 0,
        "start": "2014-01-09 16:41:02.306268",
        "stderr": "",
        "stdout": "app2"
    },
    "item.stdout": "app2"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by mpdehaan** [comment]
So while I agree that -v should not print double output for the debug module, I do _NOT_ agree that the debug module should condionationally pretty-print.

The debug module pretty printing is generally well recieved, and it is important that it do this when -v is not specified because someone using the debug module is explicitly debugging.

We shoudl definitely fix the duplicate output with -v in this case though, and only show the pretty-printed form.

**Comment by techtonik** [comment]
```
---
- hosts: "{{ host | default('localhost') }}"
  vars:
    - loglist:
      - /var/log/wtmp
      - /var/log/apache2/access.log
      - /var/log/apache2/error.log

  tasks:
  - name: get log size info
    stat: path={{ item }}
    with_items: loglist
    register: logsize

  - name: log sizes
    debug: var={{ item.stat.size }}
    with_items: logsize.results
```

The output of this snippet is awful. Is it possible to shorten it?

**Comment by alozovskoy** [comment]
Dirty hack for this issue (use patch):

in _ansible/lib/ansible/utils/__init__.py_

```
201,203d200
<         if key == 'item':
<             del result2[key]
<             return result2
```

in _ansible/lib/ansible/callbacks.py_

```
527c527
<                 msg = "%s: [%s] => %s" % (ok_or_changed, host, utils.jsonify(host_result2, format=verbose_always))
---
>                 msg = "%s: [%s] => (item=%s) => %s" % (ok_or_changed, host, item, utils.jsonify(host_result2, format=verbose_always))
```

It's not a correct way, but at now the output is realy awful.

**Comment by sankalp-khare** [comment]
I agree with @greenbrian... When I want to debug certain variables or produce a message using a `with_items:` statement pointing to some ec2 instance data (registered elsewhere), it dumps all the information for each loop item in addition to what I ask it to, which makes the output unnecessarily verbose.

If I wanted the entire list to be output as-is, I would debug it using a `with_items` separately!

**Comment by evantahler** [comment]
This kind of thing now produces an error: `A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").`

Opened a new issue about this: https://github.com/ansible/ansible/issues/9879

**Comment by wincent** [comment]
So there are really two issues here: verbosity of `debug` output (including double-printing) and verbosity of normal output.

If I have a task that loops over a list of hashes with many keys, the output is incredibly hard to read because I get output like:

```
ok: [host] => (item={ ... (massive multi-line item dump here) ...})
ok: [host] => (item={ ... (massive multi-line item dump here) ...})
ok: [host] => (item={ ... (massive multi-line item dump here) ...})
...
```

When really what I'd like is something like:

```
ok: [host] => (item={(human-readable label here})
ok: [host] => (item={(human-readable label here})
ok: [host] => (item={(human-readable label here})
...
```

What do you think of doing this by providing an optional key such as `__description__` (or whatever), which, if present in the item, would be used for display purposes during runs without `-v`; with `-v` you'd continue to get the full dump.

Right now the only workaround I can think of is to have my "items" actually be string indexes into some global hash that I lookup from inside the task, but that feels pretty messy. (And I haven't tried it yet, so I'm not even sure it will work.)

**Comment by droopy4096** [comment]
I was ignoring this issue until now. At this moment I have a playbook that auto-generates hash that includes usernames and passwords, so when I iterate over that hash it spews _everything_ in the output making it a security issue. Having something like:

``` yaml
  - name: task
     command: echo {{ item.name }}
     with_dict: my_hash
     print_errors_only: True
```

would go a long way towards reducing amount of noise playbooks produce as well as accidental data leaks like the one I'm facing (since output is being logged too....)

there's a possibility to loop over the keys of the hash hopefully preventing this from leaking as badly but it feels clumsy and sub-optimal...

**Comment by jhawkesworth** [comment]
@droopy4096 would no_log meet your needs? http://docs.ansible.com/faq.html#how-do-i-keep-secret-data-in-my-playbook

**Comment by droopy4096** [comment]
didn't realize that would take care of hash iteration output, but it did. great!

**Comment by evantahler** [comment]
While `no_log`  does suppress output (security++), you still get a line per item in the iteration group.  I would still prefer something like 

```
- template: src=/mytemplates/{{ item }}.j2 dest=/etc/{{ item }}.conf
  with_items:
    - service_a
    - service_b
    - service_c
    - service_d
    - service_e
```

to output 1 line, rather than 5.  It gets even more confusing when you have conditionals, and it's hard to tease out which templates actually got created and which ones didn't:

```
- template: src=/mytemplates/{{ item }}.j2 dest=/etc/{{ item }}.conf
  when: "{{ item }} in group_names"
  with_items:
    - service_a
    - service_b
    - service_c
    - service_d
    - service_e
```

**Comment by paul-manjarres** [comment]
Hi, I've been bitten by this one too.
The output without -v is really verbose when using "with" and a list of objects with lots of vars, and I'm not talking about the debug module, every task.

I agree with @wincent  with his _description_  optional key, I thought in this solution too, something like a toString for the complete object avoiding the printing of the whole set of vars.
I tried to use No_log, but it hides a lot of information, even when errors occurs, so is not a good option. 

Thanks!

**Comment by strootman** [comment]
The example here, http://docs.ansible.com/ansible/playbooks_loops.html#using-register-with-a-loop, illustrates the verbosity. 

If you expand that example to use hashes, the output gets even more ridiculous. In a large `with_items` list, it would be difficult to pick out the fail messages with all that other noise around it. Adding `no_log` to the fail task suppresses the message too.

**Comment by evantahler** [comment]
Perhaps the way to solve this is to be able to provide a logging `log_loop_item_depth`  and a `log_skipped` options for all actions.  This would solve the 2 pain points I have.  

For example ([from here](http://tech.taskrabbit.com/blog/2015/03/12/rebuilding-capistrano-with-ansible/)), say you have the following setup.  It's possible to write one action to provision all the config files for all my applications based on a nested config:

``` yaml
# group_vars/all

application_configs:
  app_1:
    other: stuff
    language: ruby
    configs:
      - config_file_a
  app_2:
    other: stuff
    language: node
    configs:
      - config_file_b
```

``` inventory
# production
[app_1]
server_1.com
server_2.com

[app_2]
server_3.com
server_4.com
```

``` yaml
# role
- name: config files
  template: 
    src: "configs/{{ item.1 }}.j2"
    dest: "/var/www/{{ item.0.name }}/config/{{ item.1 }}"
  with_subelements: 
   - application_configs
   - configs
  when: "'{{ item.0.name }}' in group_names"
```

The problem is that if I provision my whole inventory, I'll have a skipped files on every server, and every line will log the whole  `application_configs` hash, which makes this action really hard to debug.  

You end up with something like (the hash is small in this example, but you can imagine that it will often get quite large):

```
TASK: [config files] ************************************************************
ok: [server_1.com] => (item=({'other': 'stuff', 'langauge': 'ruby'}, 'config_file_a'))
ok: [server_2.com] => (item=({'other': 'stuff', 'langauge': 'ruby'}, 'config_file_a'))
skipping: [server_3.com] => (item=({'other': 'stuff', 'langauge': 'node'}, 'config_file_a'))
skipping: [server_4.com] => (item=({'other': 'stuff', 'langauge': 'node'}, 'config_file_a'))
skipping: [server_1.com] => (item=({'other': 'stuff', 'langauge': 'ruby'}, 'config_file_b'))
skipping: [server_2.com] => (item=({'other': 'stuff', 'langauge': 'ruby'}, 'config_file_b'))
ok: [server_3.com] => (item=({'other': 'stuff', 'langauge': 'node'}, 'config_file_b'))
ok: [server_4.com] => (item=({'other': 'stuff', 'langauge': 'node'}, 'config_file_b'))
```

With the suggested 2 new options, the action becomes:

``` yaml
# role
- name: config files
  template: 
    src: "configs/{{ item.1 }}.j2"
    dest: "/var/www/{{ item.0.name }}/config/{{ item.1 }}"
  with_subelements: 
   - application_configs
   - configs
  when: "'{{ item.0.name }}' in group_names"
  log_skipped: false # <- HERE
  log_loop_item_depth: item.1 # <- HERE
```

This would only log the files which are created per server, and only like the name of the config file, IE: 

```
TASK: [config files] ************************************************************
ok: [server_1.com] => (item=('config_file_a'))
ok: [server_2.com] => (item=('config_file_a'))
ok: [server_3.com] => (item=('config_file_b'))
ok: [server_4.com] => (item=('config_file_b'))
```

**Comment by m1no** [comment]
@evantahler +1 i have also a task in place which would greatly benefit from it. I deploy SSL certificates with use of ansible vault. But ansible prints the whole certificate key content which is stored in tls_key, which is for keys really an issue, when using with_items :

<pre>
- name: Upload certificates
  copy: content="{{ item.src }}" dest="{{ item.dst }}" owner=root group=root mode=0644
  with_items:
    - { src: "{{ tls_ca_cert }}", dest: "{{ tls_ca_cert_file }}" }
    - { src: "{{ tls_cert }}", dest: "{{ tls_cert_file }}" }
    - { src: "{{ tls_key }}", dest: "{{ tls_key_file }}" }
</pre>

**Comment by dsmarsh** [comment]
+1
The only time you get this output is with "with_items". If you don't iterate, the only thing shown is the output of your task not the verbose output. Should have an option to do it either way. I think doing it verbose is already in with "-v", but there is no way to turn it off with "with_items".

Even if the task is skipped on a certain host, the "skipping:" lines still show the verbose output. It was skipped, so I don't care. D:

**Comment by awasilyev** [comment]
no_log: True skipped output from debug:
is it by design or a bug? adding no_log: False to debug did not help.

```
- hosts: localhost
  connection: local
  sudo: no
  no_log: True
  tasks:
  - debug: msg="Hello!"
    no_log: False
```

**Comment by jsengla** [comment]
I like clean output, and often use with_items for the single line of output (since I unfortunately can't include jinja in the 'name:' section).
I have solved this issue for clean output and security (skipping sensitive variables) by using jinja's map filter on hashes.
The trick, especially with hashes that aren't entirely uniform (i.e., a registered variable from some skipped/failed/successful tasks) is to do something like this:

> my_file_stat.results|default([])|map(attribute='stat')|map(attribute='exists')|list

Alternatively, it works to use this, depending on what's likely to be missing:

> my_file_stat.results|map(attribute='stat.exists')|list

This can be very powerful when used with with_together, but because 'undefined' is iterated over like a unicode string in such a loop, making very ugly output and unsynchronized parallel iterations, this kind of thing helps to ensure proper parallel with_together output:

> my_file_stat.results|map(attribute='item')|map('default','')|list

Thus I would argue that this is a feature - not a bug.  Ansible will iterate over precisely the list you tell it to iterate over.  Reduce the size of the list's items if you want to reduce what it shows in the 'item=' section.

**Comment by soar** [comment]
Up! Too verbose output from `with_items`/`with_nested` loops is very annoying! `no_log: True` produces string like:

```
ok: [node1] => (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```

which isn't very useful tool. Ideal solution will be:
- show only selected `item.key` if action was success
- show verbose output if action fails

**Comment by superawesome** [comment]
I'm attempting to do something similar with ElasticSearch clusters:

1) get a list of all hosts in the cluster:
2) iterate over that list, get each node's status (this is important- asking a single node doesn't identify split-brain conditions)

a simple:

```
- debug: msg={{ item.stdout }}
  with_items: {{ es_hosts.results }}
```

prints each entire element of the results array... almost all of which is useless for what I need.

Thanks for the pointer in the right direction, jslenga.... I'm able to do this and get something pretty reasonable:

```
- debug: msg="{{ post_health_checks.results|map(attribute='stdout')|list }}"
```

and:

```
- name: fail if any nodes have bad status
  fail: msg="One or more nodes has bad health"
  when:
   - post_health_checks.results|map(attribute='rc')|join(' ') != "0 0 0"
```

**Comment by paul-manjarres** [comment]
I tried the workaround suggested by @jsengla, but it seems that in Centos 6.7, with Ansible 2.0.1 python 2.6 and jinja 2.2, the map filter is not implemented, so it cant be used.  

Do i need to update Jinja?

Its a shame that this feature is not in any roadmap.

**Comment by vmorris** [comment]
I'm hitting this issue today as well. 

2 years later, and if this is a feature as @jsengla suggests, let's point people to the documentation:
http://docs.ansible.com/ansible/playbooks_filters.html
http://jinja.pocoo.org/docs/dev/templates/#builtin-filters

I managed to work this out, but it wasn't obvious... perhaps add something to the with_items documentation?

**Comment by lqueryvg** [comment]
+1 for me too

It's counter-intuitive to see a data structure dump with a `debug: msg=` task.

Why not have an extra option on the task (e.g. "`terse: yes`") so that this can be suppressed when using a `with_` loop?

**Comment by donovan** [comment]
I hit this issue frequently when working with openstack instances. I need to use register in conjunction with with_items to capture floating ip info for use in subsequent tasks eg:

```
    - name: Assign a floating IP
      os_floating_ip:
        server: "{{ item.instance_name }}"
      register: floating_ip_info
      with_items: "{{ instances }}"

# annoyingly verbose output
    - name: Output floating IPs
      debug:
        msg: "got floating ip {{ item.floating_ip.floating_ip_address }} for {{ item.item.instance_name }}"
      with_items: "{{ floating_ip_info.results }}"
```

This can result in hundreds of lines as it includes all os_server output for all instances.

The following playbook demonstrates the issue 

```
#!/usr/bin/env ansible-playbook
---

- name: testing register output with_items
  hosts: localhost
  tasks:
    - shell: echo "foo {{ item }}"
      with_sequence: count=5
      register: capture

    - debug: msg="output = {{ item.stdout }}"
      with_items: "{{ capture.results }}"
```

The debug task yields 154 lines of output, in the majority of cases I only want the msg lines I specify (5 lines in this case).

As playbook output is designed for human consumption it would be nice if one could output relevant information to the person running a playbook without also outputting large amounts of irrelevant information. Debug output as it currently stands it is difficult for a human to parse due to the verbosity.

Personally I would prefer a print module that allows me to print arbitrary lines as a task and leave the debug module as is. Having all the information output when debugging is useful. I think the issue here is that the debug module is being overloaded due to the lack of a print module.

If a print (or terse_debug) module is not possibe then it would be great if we could get a terse option for debug.

**Comment by gmarziou** [comment]
I'm new to ansible but find this also annoying especially when I'm trying to convince my team to adopt this great tool.

Could it be possible to override the default message by specifying `ok:` like below:

```
- name: Assign a floating IP
  os_floating_ip:
    server: "{{ item.instance_name }}"
    ok: msg="IP address assigned to {{ item.instance_name }}"
  register: floating_ip_info
  with_items: "{{ instances }}"
```

**Comment by eproxus** [comment]
While waiting for a perhaps "simpler" solution to this, I can second @jsengla's solution.

@gmarziou You could do it this way:

``` yaml
- name: Assign a floating IP
  os_floating_ip: server="{{ item }}"
  register: floating_ip_info
  with_items: "{{ instances | map(attribute='instance_name') | list }}"
```

**Comment by gmarziou** [comment]
Thanks @eproxus but am I right in saying that your workaround works only if I need to iterate on a single attribute? In my real task I need to access 2 or 3 attributes.

**Comment by eproxus** [comment]
@gmarziou Yes, that's a bit more tricky. You can achieve some things with the Jinja2 filters, but in the end we found the limitations were mostly related to dictionaries. We created a filter helper called `dictmap` which you might be interested in. You can find it here: https://gist.github.com/eproxus/148a3266f26d093f8707080a1566c480

**Comment by jsengla** [comment]
@gmarziou If you want to try the same thing with just core and extras (no external stuff), you can often get by with use of with_together to align the attributes.  This, however, breaks horribly if an attribute is undefined, resulting in the need for creative use of (i.e.) the default filter and/or a select('string') clause in your map filtering.
I _love_ your idea about implementing an "ok:" override.  You should really consider making a feature request.

**Comment by jeanpaulmanjarres-payulatam** [comment]
Reasonable idea for this problem in https://github.com/ansible/ansible/issues/13710

**Comment by dgarros** [comment]
I'm facing the same issue,
It would be great to have one of the proposed solutions implemented

**Comment by jeanpaulmanjarres-payulatam** [comment]
I've managed to update Jinja2, its not difficult. So, now i can use the map(attribute='') workaround. But, this only works if you dont need more than one attribute of your json object. Map attribute only let you select one attribute of your object, so, in cases like populating a template it won't work as you need more than one var.

So, we still need a fix on this.

**Comment by xyjrshank** [comment]
It appears you can use the map(attribute='') workaround in combination with "with_together" to operate on multiple attributes from a dictionary entry concurrently. I've used this in a few playbooks and so far it seems pretty reliable and simplifies the output to just the attributes you care about.

``` yaml
- name: Act on two attributes from a dictionary
  debug: msg="Instance {{ item.0 }} is owned by {{ item.1 }}"
  with_together:
    - "{{ instances | map(attribute='instance_name') | list }}"
    - "{{ instances | map(attribute='instance_owner') | list }}"
```

**Comment by evantahler** [comment]
That's a nice work-around @xyjrshank!  That looks like it also might be able to be moved into a [jinja2 extension](http://docs.ansible.com/ansible/intro_configuration.html#jinja2-extensions) for a terser syntax: `{{ instances | map(attribute='instance_name') | list }}` => `{{ instances | extract('instance_name') }}`

**Comment by bcoca** [comment]
fixed via #17294, will be in 2.2

**Comment by jeanpaulmanjarres-payulatam** [comment]
Excellent news!, thanks.

**Comment by jjaone** [comment]
Thanks @superawesome and @jsengla and @xyjrshank , your advice made it possible to me to display and show just a right amount of verbosity in shell-commands output, I did this:

``` yaml
- name: Network/sysctl settings status
  become: yes
  shell: sysctl -a -r {{ item }}
  register: sysctl
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
    - net.ipv4.icmp_echo_ignore_broadcasts
    - net.ipv4.conf.all.accept_source_route
  changed_when: False
- debug: msg="{{ sysctl.results|map(attribute='stdout')|list }}"
```

**Comment by berney** [comment]
> fixed via #17294, will be in 2.2

This still prints the item twice (the label, plus pretty JSON), as well as the message.

I find `debug` with a loops behaviour very different to what I expected. Without a loop it is easy to print a simple message, when used with looping it prints a dump of the variable as well as the message. 

What I expected to write: -

```yaml
- name: run some command
   command: echo item {{item}}
   register: my_result
   with_items:
     - 1
     - 2
  - name: my debug
    debug:
        msg: The line was {{item.stdout}}
    with_items: "{{my_result.results}}"
```

Result I expected, something close to: -
```
TASK: [my debug] ************************************************************
ok: [host1]: The line was item 1
ok: [host1]: The line was item 2
ok: [host2]: The line was item 1
ok: [host2]: The line was item 2
```

- If I use loop control the JSON get's overridden (better) but the pretty JSON is still there (very unwanted), and finally the msg (what I want) as json (that's ok).
- If I set `verbosity: 1` or set `when` to false, then the debug message is skipped but the item is still printed (either JSON or it's label when using `loop_control`/`label`).
- Putting the task in a separate file and using and `include` with a loop, gives simple output, but one task per host per item, which is too verbose/wasteful.
- Blocks can't be used with loops.
- The solution per @jjaone above (and my thanks to @jsengla, @superawesome  and @xyjrshank, others above): `- debug: msg="{{ my_result.results|map(attribute='stdout')|list }}"` is output nicely, one line per item, grouped by host, however I can't template the string, e.g. "The output was {{item}}" or anything fancier like that. If anyone knows how to do this I'd love to know.

I understand that Ansible devs want `debug` to show verbose information for newcomers to help them, but I think it should have an option to turn off the (automatic) dumping of the item variable, so that a message is printed, rather than needing to resort to jinja to process the dict. e.g.

```yaml
  - debug:
    msg: The line was {{item.stdout}}
    with_items: "{{my_result.results}}"
    auto_dump_item: false
```

**Comment by katta101** [comment]
I'm trying to get the yum list output, but it spits tons of it. Could someone help me grab how i can debug to capture the result only from yum list output, but not all the output::

ok: [lapl000385.server.lab.net] => {
    "yum_pkgs": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "invocation": {
                    "module_args": {
                        "conf_file": null,
                        "disable_gpg_check": false,
                        "disablerepo": null,
                        "enablerepo": null,
                        "exclude": null,
                        "install_repoquery": true,
                        "list": "git",
                        "name": null,
                        "state": "installed",
                        "update_cache": false,
                        "validate_certs": true
                    },
                    "module_name": "yum"
                },
                "item": "git",
                "results": []
            },

playbook as below:
- hosts: lab1
  gather_facts: false

  tasks:
    - name: list software pkgs
      yum:
        list: "{{ item }}"
      register: yum_pkgs
      with_items:
        - git
        - htop
        - vim
        - unzip
        - curl
        - sudo

    - debug:
        var: yum_pkgs


I also tried as below, which did not work:
    - debug:
        msg: "{{ yum_pkgs.results|map(attribute='stderr')|list }}"

**Comment by berney** [comment]
I found something that gives me what I wanted (https://github.com/ansible/ansible/issues/5564#issuecomment-289778604) thanks to bmaupin's answer on StackOverflow at http://stackoverflow.com/questions/31685125/is-it-possble-to-map-multiple-attributes-using-jinja-ansible.

```yaml
- name: run some command
   command: echo item {{item}}
   register: my_result
   with_items:
     - 1
     - 2
     - 3
  - name: my debug
    debug:
      msg: "{% set output = [] %}\
        {% for x in (my_result.results | map(attribute='stdout')) %}\
          {{ output.append( 'The result was: ' ~ x ) }}\
        {% endfor %}\
        {{output}}"
```

Output is something like: -

```
ok: [host1]: => {
    "msg": [
        "the result was: item 1",
        "the result was: item 2",
        "the result was: item 3"
    ]
}
ok: [host2]: => {
    "msg": [
        "the result was: item 1",
        "the result was: item 2",
        "the result was: item 3"
    ]
}
```

I tried to make the yaml nicer by using `msg: >` and `msg: |` but neither worked. You can do it all on oneline, if you split lines you need the `\` at the end. If you do oneline you need to be sure there's no spaces between the end of of a `%}` or `}}` and the start of a `{%` or `{{` otherwise you'll get spaces in the output string and get a result like: "msg: "     [u'the result was: item 1', u'the result was: item 2'```, e.g. a string with white space followed by a list.

I still wish I could write something like: -

```yaml
 - debug:
    msg: The line was {{item.stdout}}
    with_items: "{{my_result.results}}"
    auto_dump_item: false
```

It's possible to create custom jinja2 filters or custom ansible plugins. If I figure out a more elegant solution I'll post it.

**Comment by lukasmrtvy** [comment]
@berney +1

**Comment by holmesb** [comment]
+1 for `auto_dump_item: false`.  It's the only way to avoid screen-spam if you want to print (debug) multiple attributes in a conditional loop.

**Comment by ChristianHoltfurth** [comment]
+1 for `auto_dump_item: false`

**Comment by christiang830** [comment]
+1 for auto_dump_item: false

**Comment by pgporada** [comment]
Open a new ticket for `auto_dump_item: false`. This ticket has been closed since last year.

**Comment by admintidexa** [comment]
Guys i've accomplished something useful, so, just sharing:
`- name: Print EC2
    shell: echo ''
    with_items: "{{ ec2.instances }}"
    loop_control: 
      label: "{{ item.tags['Name'] }}"`

**Comment by guipedreira** [comment]
Just found something:
```yaml
  - name: Print EC2 sta
    shell: "echo ''"
    with_items: "{{ ec2.instances }}"
    loop_control: 
      label: "{{ item.tags['Name'] }}"
```

**Comment by zx1986** [comment]
I always got `'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'stdout'` with

```
- debug: msg={{ item.stdout }}
  with_items: {{ es_hosts.results }}
```

Then, I try to use @superawesome 's `- debug: msg="{{ domains.results | map(attribute='stdout') | list }}"`, it works perfect!

Thanks man, you save my day!

**Comment by sekharvajjula** [comment]
The option suggested by @guipedreira (loop_control: label) works great for me. I wanted to screen passwords from my hash. But at the same time I also wanted to see some stuff which was relevant. no_log: True was masking everything. With (loop_control: label) I can choose the fields, I want to show using coma separated tags. Thanks @greenbrian.

**Comment by LoTx** [comment]
it's seems that there's severals good answer but I've tried @superawesome 's and it worked perfectly :)

```
    shell: /bin/bash CURL.sh 
    register: curl_result
      
  - debug:
      msg: "{{ curl_result.results | map(attribute='stdout') | list }}"
```
 
thx !

**Comment by powerpbx** [comment]
Expanding on the @berney solution. The map pipe can be removed completely.  This also gives you the ability to include other output besides stdout.
```
- name: run some command
  command: echo item {{ item }}
  register: my_result
  with_items:
    - 1
    - 2
    - 3
- name: my debug
  debug:
    msg: "{% set output = [] %}\
      {% for x in my_result.results %}\
        {{ output.append( 'The command was: ' ~ x.cmd | join(' ') ) }}\
        {{ output.append( 'The result was: ' ~ x.stdout ) }}\
      {% endfor %}\
      {{output}}"
```
Which outputs
```
ok: [host1] => {
    "msg": [
        "The command was: echo item 1",
        "The result was: item 1",
        "The command was: echo item 2",
        "The result was: item 2",
        "The command was: echo item 3",
        "The result was: item 3"
    ]
}
ok: [host2] => {
    "msg": [
        "The command was: echo item 1",
        "The result was: item 1",
        "The command was: echo item 2",
        "The result was: item 2",
        "The command was: echo item 3",
        "The result was: item 3"
    ]
}
ok: [host3] => {
    "msg": [
        "The command was: echo item 1",
        "The result was: item 1",
        "The command was: echo item 2",
        "The result was: item 2",
        "The command was: echo item 3",
        "The result was: item 3"
    ]
}

```
