### ISSUE TITLE
using --check and --diff together with the "template" module produces weird diff labels (edited)

### ISSUE THREAD

**Issue by mgarren** [ansible/ansible#5575]
Playbook:
# playbook.yml

---
- hosts: "{{ dhcp_hosts }}"
  user: ansible
  sudo: yes
  
  roles:
        - /home/ansible/Ansible/roles/dhcp
  
  tasks:
  - name: Ensure that dhclient is installed first
     yum:  name=dhclient
           state=present
     tags: deploy
  - name: Restart the network
     service:   name=network
                state=restarted
     tags:    network
## DHCP ROLE:
# Drop a network config for dhcp
# 

   #Drop the /etc/sysconfig/network-script/ifcfg-eth0 template
- name: Drop the ifcfg-eth0 script
   template:  src=/home/ansible/Ansible/templates/dhcp/ifcfg-eth0.j2
              dest=/etc/sysconfig/network-scripts/ifcfg-eth0
              owner=root
              group=root
              mode=0644
   tags:      deploy
- name: Drop the /etc/dhclient-eth0.conf file
   copy:      src=/home/ansible/Ansible/files/dhcp/dhclient-eth0.conf
              dest=/etc/dhclient-eth0.conf
              owner=root
              group=root
              mode=0644
   tags:      deploy

When the above playbook and role are run without --check (even with --diff), it functions as expected.  The appropriate template is dropped as ifcfg-eth0.  Where it gets interesting is if you run the same code with "--check --diff":

TASK: [/home/ansible/Ansible/roles/dhcp | Drop the ifcfg-eth0 script] *********
--- before: /etc/sysconfig/network-scripts/ifcfg-eth0
+++ after: /home/ansible/Ansible/templates/dhcp/ifcfg-eth0.j2
@@ -1,5 +1,8 @@
 DEVICE=eth0
-HWADDR=###REMOVED###
+BOOTPROTO=dhcp
+USERCTL=no
 ONBOOT=yes
-BOOTPROTO=dhcp
-DHCP_HOSTNAME=###REMOVED###
+check_link_down() {
- return 1;
  +}
  +DHCP_HOSTNAME=###REMOVED###

changed: [###REMOVED###]

It seems as though ansible implementation has the "src" and "dst" flags switched, only when run with a "--diff --check".  Has anyone else seen this behavior?  The --check and --diff are vital components of our testing to make sure we don't deploy incorrect configs to our production servers.

Also, I have ensured that there is not a .j2 file present on any target servers and have tested across 10 different servers.

**Comment by bcoca** [comment]
IIRC the template module generates the template on the 'master' to a
temporary file to do the diff, but uses the 'template name' as the 'diff
file'.

From my testing it shows the correct diff (+ stuff i added, - stuff I
removed).

**Comment by mgarren** [comment]
Agree with correct diff, but I was nervous to do an actual deploy without
further testing because it made me believe it was not dropping the correct
filename.

Thanks,
Matt

**Comment by mpdehaan** [comment]
The issue is, per the mailing list post where I replied, I think that the "before" and "after" labels are wrong.

These are just hints we pass in to the diff library.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
