### ISSUE TITLE
synchronize module doesn't work with ansible_connection chroot

### ISSUE THREAD

**Issue by orkaa** [ansible/ansible#5577]
A little background of what is happening:

Inventory:

```
[chroot]
/tmp/tmpZhhROE/build    ansible_connection=chroot
```

Playbook:

```
hosts: chroot
tasks:
  - name: Copy image files to destination
    synchronize: src={{ app_image }}/ dest=/
```

Error:

```
TASK: [Copy image files to destination] ***************************************
failed: [/tmp/tmpZhhROE/build] => {"cmd": "rsync --delay-updates --compress --      timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out- format='<<CHANGED>>%i %n%L' /root/stacks/test/stacker/image/  root@/tmp/tmpZhhROE/build:/", "failed": true, "item": "", "rc": 12}
msg: rsync: mkdir "/tmp/root@/tmp/tmpZhhROE/build:" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(595) [Receiver=3.0.7]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(601) [sender=3.0.7]
```

Ansible wrongly generates the rsync command. The problematic part is destination - root@/tmp/tmpZhhROE/build:/

When dealing with chroot, there's no point to prepend a hoststring, local filesystem path would be enough.

**Comment by mpdehaan** [comment]
This is largely because the synchronize module doesn't know about the connection types, and wasn't really designed for use together.

I think it would be reasonable for it to check, but there's probably a few others where it wouldn't be a remote source (lxc, jail, etc)

**Comment by jctanner** [comment]
@orkaa you might want to try setting the synchronize task to a local connection, but i think you might be better off using shell: rsync in this case.

As mpdehaan said, synchronize is not currently designed to work with anything besides local/paramiko/ssh connection types.

**Comment by tetherit** [comment]
This issue is related: https://github.com/ansible/ansible-modules-core/issues/2832

I think this and the related issue need some tender love and care :( - I frequently need to provision a new host in chroot, to create new image file (to dd to a blank sd card or hard drive).

Because the synchronize module is not aware of connection, it means I need to duplicate around 20 synchronize tasks, that are otherwise identical, to provide the chroot_path manually. Seems very much against DRY and against Ansible's philosophy?

From the tens/hundreds of other modules in Ansible I use, synchronize seems the only one not to work with connection: chroot :(
