### ISSUE TITLE
memtotal_mb fact on HP-UX produces None type error on HP-UX B.11.11 OS instances

### ISSUE THREAD

**Issue by Logos01** [ansible/ansible#5652]
The current method of gathering memtotal_mb for HP-UX is causing a None type error on multiple HP-UX systems within my environment. Upon reviewing the command used, it appears there is no output.  I have modified my local library/system/setup file to reflect the below, which is successfully averting this error (changes beginning from line 1305).

```
             try:
                 rc, out, err = module.run_command("grep Physical /var/adm/syslog/syslog.log")
                 data = re.search('.*Physical: ([0-9]*) Kbytes.*',out).groups()[0].strip()
                 self.facts['memtotal_mb'] = int(data) / 1024
             except:
                 rc, out, err = module.run_command(
                     "echo 'phys_mem_pages/D '| adb -k /stand/vmunix /dev/kmem | tail -1 | awk '{print $1}'"
                 )
                 data = out
                 self.facts['memtotal_mb'] = int(data) / 1024
```

**Comment by mpdehaan** [comment]
If you would like to supply a patch, please submit it as a pull request and be sure to catch the exception, unguarded "excepts" will not be accepted.

Thanks!

**Comment by mpdehaan** [comment]
Seems it would be better to test what was available prior to running the command too.

**Comment by Logos01** [comment]
My example code has a lot of cleanup before it's pull-worthy. But at least
I narrowed down the cause and have a solution.  I'll take a look at
cleaning it up for pull-request later.

On Thu, Jan 16, 2014 at 10:50 AM, Michael DeHaan
notifications@github.comwrote:

> Seems it would be better to test what was available prior to running the
> command too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/5652#issuecomment-32493053
> .

## 

##

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
