### ISSUE TITLE
With the same name, handler from another role is chosen first

### ISSUE THREAD

**Issue by rgarrigue** [ansible/ansible#5687]
Here is my arborescence
roles/devel/
├── handlers
│   └── main.yml
roles/icinga/
├── handlers
│   └── main.yml
└── tasks
    ├── icinga.yml
    └── main.yml

I run icinga.yml. Included is a task is a `notify: restart iptables`. There's two handlers for that respectively in devel/handlers/main.yml and icinga/handlers/main.yml.

Here is the output

```
TASK: [icinga | IPtables rule for icinga] *************************************
changed: [centos]

TASK: [icinga | Services] *****************************************************
changed: [centos] => (item=httpd)
ok: [centos] => (item=icinga2)

NOTIFIED: [devel | restart iptables] ******************************************
changed: [centos]
```

icinga notify, devel answers. No big mistery here, the lookup order is alphabetical top down I guess. I'ld expect it to be down-top instead, at least with a strong preference for the role's handler dir.

**Comment by mpdehaan** [comment]
Yes, handlers are global namespace and the last one loaded is going to win.   

In this particular case if handlers are being used for server restarts the conflict won't be an issue, if it is, it's something to be aware of, but we wouldn't want to make this a warning because it occurs most of the time in the standard case and would generate a lot of false positives.

This is a valid feature in that you have a common role that defined a bunch of handlers rather than defining them on a per role basis.
