### ISSUE TITLE
(edited description) Role dependency de-duplication should take role conditionals into account

### ISSUE THREAD

**Issue by abdulg** [ansible/ansible#5708]
See sample playbook at https://github.com/abdulg/ansible-common-roles

Using ansible 1.4.4.

When using Ansible roles I ran into a problem where common roles were being skipped. The linked repo is a demonstration of the issue. There are 2 roles, _role1_ and _role2_, each of which depend on a 3rd role, _common_.

I have three playbooks, _playbook.yml_, _role1.yml_, and _role2.yml_. The first playbook selects a role to execute based upon a variable passed via the command line. The second 2 simply execute _role1_ and _role2_ respectively.

Here is the result of running the _role1_ playbook:-

```
⚡ ansible-playbook -i inventory role1.yml

PLAY [Playbook to do role 1] **************************************************

GATHERING FACTS ***************************************************************
ok: [abdul]

TASK: [common | A common task] ************************************************
changed: [abdul]

TASK: [role1 | A role1 task] **************************************************
changed: [abdul]

PLAY RECAP ********************************************************************
abdul                      : ok=3    changed=2    unreachable=0    failed=0
```

And as expected, running _role2_ is similar:-

```
PLAY [Playbook to do role2] ***************************************************

GATHERING FACTS ***************************************************************
ok: [abdul]

TASK: [common | A common task] ************************************************
changed: [abdul]

TASK: [role2 | A role2 task] **************************************************
changed: [abdul]

PLAY RECAP ********************************************************************
abdul                      : ok=3    changed=2    unreachable=0    failed=0
```

But see what happens when I run _playbook.yml_, wherein I select the role to run via a CL variable. First select to run _role1_:-

⚡ ansible-playbook -i inventory playbook.yml -e do_role=role1

```
PLAY [Configure depending on passed in variable] ******************************

GATHERING FACTS ***************************************************************
ok: [abdul]

TASK: [common | A common task] ************************************************
changed: [abdul]

TASK: [role1 | A role1 task] **************************************************
changed: [abdul]

TASK: [role2 | A role2 task] **************************************************
skipping: [abdul]

PLAY RECAP ********************************************************************
abdul                      : ok=3    changed=2    unreachable=0    failed=0
```

The roles _common_ and _role1_ are run, and _role2_ is skipped. All ok.

Now I select _role2_ in _playbook.yml__:-

⚡ ansible-playbook -i inventory playbook.yml -e do_role=role2

```
PLAY [Configure depending on passed in variable] ******************************

GATHERING FACTS ***************************************************************
ok: [abdul]

TASK: [common | A common task] ************************************************
skipping: [abdul]

TASK: [role1 | A role1 task] **************************************************
skipping: [abdul]

TASK: [role2 | A role2 task] **************************************************
changed: [abdul]

PLAY RECAP ********************************************************************
abdul                      : ok=2    changed=1    unreachable=0    failed=0
```

The _common_ role is skipped because _role1_ is skipped, and _common_ is a dependency of _role1_. _common_ should be not be skipped because it's a dependency of _role2_ .

**Comment by mpdehaan** [comment]
Can you please show the playbooks inline?  It's difficult for me cross referencing files with your output.

Thanks!

**Comment by abdulg** [comment]
playbook.yml

```
- name: Configure depending on passed in variable
  hosts: all
  roles:
    - { role: role1, when: do_role == 'role1' }
    - { role: role2, when: do_role == 'role2' }
```

role1.yml

```
- name: Playbook to do role 1
  hosts: all
  roles:
    - role1
```

role2.yml

```
- name: Playbook to do role2
  hosts: all
  roles:
    - role2
```

roles/common/tasks/main.yml

```
- name: A common task
  command: echo common task
```

roles/role1/meta/main.yml

```
---
dependencies:
  - role: common
```

roles/role1/tasks/main.yml

```
- name: A role1 task
  command: echo role1 task
```

roles/role2/meta/main.yml

```
---
dependencies:
  - role: common
```

roles/role2/tasks/main.yml

```
- name: A role2 task
  command: echo role2 task
```

**Comment by mpdehaan** [comment]
Notes for us for later:

"I have three playbooks, playbook.yml, role1.yml, and role2.yml. The first playbook selects a role to execute based upon a variable passed via the command line. The second 2 simply execute role1 and role2 respectively."

Looking at the repo:

playbook.yml applies role1 when a variable named do_role is set to "role1", or role2 when set to "role2".
role1.yml is actually a playbook, and is set to unconditionally apply role1
role2.yml is actually a playbook, and is set to unconditionally apply role2.

"But see what happens when I run playbook.yml, wherein I select the role to run via a CL variable. First select to run role1:  ansible-playbook -i inventory playbook.yml -e do_role=role1"

You have selected role 1 of 2.  The output shows that the common role is applied and the role1 is applied.  This seems 100% correct.  The actual problem reported is at the very bottom of the description, which is this:

"⚡ ansible-playbook -i inventory playbook.yml -e do_role=role2"

To me, this looks like the ultimate problem is that the logic that prevents roles from being included more than once, (i.e. allow_duplicates) should consider the conditionals applied to the role as if they were role parameters, thus common and common should not be treated as the same in this case.

Got it.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible-playbook playbook.yml -e do_role=role2
PLAY: Configure depending on passed in variable *********************************
TASK [common : A common task] ***************************************************
skipping: [localhost]
TASK [common : debug msg=this is the second task in common] *********************
skipping: [localhost]
TASK [role1 : A role1 task] *****************************************************
skipping: [localhost]
TASK [common : A common task] ***************************************************
changed: [localhost]
TASK [common : debug msg=this is the second task in common] *********************
ok: [localhost] => {
    "msg": "this is the second task in common", 
    "changed": false
}
TASK [role2 : A role2 task] *****************************************************
changed: [localhost]
PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
[root@jimi 5708]# ansible-playbook playbook.yml -e do_role=role1
PLAY: Configure depending on passed in variable *********************************
TASK [common : A common task] ***************************************************
changed: [localhost]
TASK [common : debug msg=this is the second task in common] *********************
ok: [localhost] => {
    "msg": "this is the second task in common", 
    "changed": false
}
TASK [role1 : A role1 task] *****************************************************
changed: [localhost]
TASK [role2 : A role2 task] *****************************************************
skipping: [localhost]
PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
