### ISSUE TITLE
interpreter_python completely breaks some use cases

### ISSUE THREAD

**Issue by joelgriffiths** [ansible/ansible#57136]
##### SUMMARY

interpreter_python change breaks many use cases for Ansible. Why would you ever hard code a path to a binary?

##### ISSUE TYPE
- Bug Report

The new interpreter_python option completely breaks environments using pyenv. Ansible uses /usr/bin/python instead of the version of Python that is actually run. It generates this warning:
 [WARNING]: Platform linux on host sever18.gadgetwiz.com is using the discovered Python interpreter at /usr/bin/python, but future installation of
another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more
information.

Using ansible_python_interpreter in the hosts or groups is not an option either since pyenv is a user setting that could be different on different hosts and inventories are not always defined on a per-host basis

```
MacBook:~/PROD/alpha_red_scripts/playbooks$ which python
/Users/joelg/.pyenv/shims/python
MacBook:~/PROD/alpha_red_scripts/playbooks$ python --version
Python 2.7.16
MacBook:~/PROD/alpha_red_scripts/playbooks$ /usr/bin/python --version
Python 2.7.10
MacBook:~/PROD/alpha_red_scripts/playbooks$
```

Why a path to /use/bin/python is HARD-CODED into ansible completely boggles the mind.

##### ANSIBLE VERSION

```paste below
 [WARNING]: Platform linux on host baycflcrwl18.cernerasp.com is using the discovered Python interpreter at /usr/bin/python, but future installation of
another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more
information.
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
ANSIBLE_SSH_RETRIES(/Users/joelg/.ansible.cfg) = 3
DEFAULT_FORKS(/Users/joelg/.ansible.cfg) = 30
DISPLAY_SKIPPED_HOSTS(/Users/joelg/.ansible.cfg) = False
HOST_KEY_CHECKING(/Users/joelg/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

brew install pyenv
CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install 2.7.16
pip install ansible --upgrade

```yaml
ansible-playbook -i inventories/production/hosts --limit server* -k check-escape.yml
```

##### EXPECTED RESULTS

There needs to be a way to configure the python localtion in ansible.cfg not in inventory files. Unless I'm misunderstanding what is happening, this seems to be a poorly thought out change. Hard coding paths is one of those things that makes me want to find a wall to bang my head on.

**Comment by sivel** [comment]
The discovered interpreter in your case is the same as the previous behavior (Ansible versions before 2.8), which is to use `/usr/bin/python`.

This warning is indicating that on the target machine (not the control machine) that `/usr/bin/python` was detected, but due to the distribution you are running on the target, Ansible may start selecting a different python, such as `/usr/bin/python3` if python3 were to be installed on the target.

The warning specifically indicates that this is a discovered interpreter on the host `sever18.gadgetwiz.com` and not the local control machine which you indicate to be called `MacBook`.

As another note, the locally installed Python, has nothing to do with the Python used on the target host.

**Comment by joelgriffiths** [comment]
Never mind. I am obviously misunderstanding the behavior. I apologize.

**Comment by joelgriffiths** [comment]
Thanks for the reply. As soon as I stepped away from my disk, I realized my mistake.
