### ISSUE TITLE
using copy: content="data" with notify clause always notifies

### ISSUE THREAD

**Issue by msolo** [ansible/ansible#5715]
This shows up as "changed" every run and triggers an update every time.

```
   - name: set timezone variables
     copy: content='America/Los_Angeles'
       dest=/etc/timezone
       owner=root
       group=root
       mode=0644
     notify:
       - update-timezone
```

**Comment by bcoca** [comment]
which version?

I use the following and I don't see that issue
- name: Set Time Zone
  hosts: all
  gather_facts: False
  tasks:
  - name: Set timezone variables
    copy: |
        content='America/New_York
        '
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
    notify:
    - update timezone
      handlers:
  - name: update timezone
    command: dpkg-reconfigure --frontend noninteractive tzdata

**Comment by msolo** [comment]
> ansible --version
> ansible 1.5

**Comment by sivel** [comment]
This is probably a better discussion for the ansible-project mailing list, but the reason is due to your "content".

This file basically requires that there be a newline at the end of the timezone specified within it.

When you do it your way with just `content='America/Los_Angeles'` it doesn't place a newline at the end.  When dpkg-reconfigure runs, it notices this, and "fixes" it by adding the newline.  So, every time you run your task, it is effectively changing the file because it is removing the newline.

@bcoca's example as well as the one I gave over at https://github.com/ansible/ansible/pull/5701#issuecomment-32959679 both should insert that new line. (Note in my comment, you cannot really see the spaces, but the line under "America/Chicago" is spaced in to the indentation level of "America/Chicago".

**Comment by msolo** [comment]
I should have been clear. I tried that earlier and saw no improvement in the situation. To double check I have just inserted the newline and once again, I get the same error I saw before.

```
  - name: set timezone variables
    copy: content="America/Los_Angeles\n"
      dest=/etc/timezone
      owner=root
      group=root
      mode=0644
    notify:
      - update-timezone
```

```
TASK: [set timezone variables] ************************************************ 
changed: [pa1]

NOTIFIED: [update-timezone] *************************************************** 
changed: [pa1]
```

**Comment by sivel** [comment]
Your use of `\n` there doesn't do what you think it is doing.  It literally is inserting `America/Los_Angeles\n` into that file, but tzdata and such on debian is smart enough and strips it out, and then adds the real new line in there.

You need to use a _real_ line break in there, like the examples that I and @bcoca have provided.

**Comment by msolo** [comment]
Now I understand. I should have read the --diff output more carefully -- it was telling the truth but I didn't believe it.
