### ISSUE TITLE
Static inventories behave differently than dynamic ones

### ISSUE THREAD

**Issue by maxrothman** [ansible/ansible#5740]
Consider this static inventory:

```
[foo:children]
bar

[bar]
10.10.0.1
```

And this dynamic one:

```
#!/bin/bash
echo '{ "foo": {"children": ["bar"]}, "bar": ["10.10.0.1"] }'
```

They should be identical, right?

```
$ ansible foo -i inventory.ini --list-hosts
    10.10.0.1
$ ansible foo -i inventory.bash --list-hosts
    foo
    10.10.0.1
```

Upon further inspection (with -vvvv), it becomes clear that ansible is trying to connect to a host "foo".

```
foo | FAILED => SSH encountered an unknown error. The output was:
OpenSSH_5.9p1 Debian-5ubuntu1.1, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /home/me/.ssh/config
debug1: /home/me/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/me/.ansible/cp/ansible-ssh-hi-22-me" does not exist
debug2: ssh_connect: needpriv 0
ssh: Could not resolve hostname foo: Name or service not known
```

This is with ansible 1.4.3 on Ubuntu 12.04.

Is there a reason for this behavior? Can it be fixed?

**Comment by sivel** [comment]
The script functionality, currently does the following:

``` python
            if not isinstance(data, dict):
                data = {'hosts': data}
            elif not any(k in data for k in ('hosts','vars')):
                data = {'hosts': [group_name], 'vars': data}
```

This basically says, if a "hosts" key was not provided, set the "hosts" to the group.  So in your case "foo" becomes a host as well.

I do not have historical reference here, but I assume it is to allow creating "ungrouped" servers, since creating a "ungrouped" group overrides the magic group that is created when no such group of that name exists.

I would also think that changing this could likely break backwards compatibility with people that are utilizing this functionality.  

Your JSON, should probably look like the following instead:

``` json
{ "foo": {"hosts": [], "children": ["bar"]}, "bar": ["10.10.0.1"] }
```

All in all, my take on an inventory script, is that it is intended to be more explicit than an inventory file.

**Comment by maxrothman** [comment]
Huh. That should probably be indicated in the documentation. Thanks.
