### ISSUE TITLE
Importing a mysql database with the mysql_db module is non-idempotent

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#5743]
Currently with the mysql_db module state=import tries to import the database again, thus making it non-idempotent. This is the error i'm getting; msg: ERROR 1062 (23000) at line 30: Duplicate entry '1' for key 'PRIMARY'

With this playbook:
- name: create website database
  mysql_db: name=dbname
                  login_user={{ mysql_root_user }}
                  login_password={{ mysql_root_password }}
                  state=present
- name: copy website database
  copy: src=database.sql
           dest=/home/user/database.sql
- name: import website database
  mysql_db: name=dbname
            login_user={{ mysql_root_user }}
            login_password={{ mysql_root_password }}
            target=/home/user/database.sql
            state=import

Just a heads up for a potential improvement, currently I'm commenting the last task everytime I run the playbook again for idempotency.

**Comment by mpdehaan** [comment]
Yeah, it's a database import, so it's doing the right thing :)

It's not true that every step in an automation system has to be idempotent really.

You should probably look into using a migration system like South, that's smarter, or something else similar, or key off the application version.

Feel free to stop by the list to discuss ideas with the group.

Thanks!

**Comment by SvenBrunk** [comment]
I disagree with that an automation system does not have to be idempotent. It must not repeat every step, but the process itself must be repeatable at all time... else you are f%($ed if the connection is lost during the process for example.

**Comment by odnanref** [comment]
I used the notify: field and created a handler that imports the database . The handler only get's called if the database does not exist.

**Comment by Lambdara** [comment]
You could run an import and having nothing change, right? (running it twice for example, the second time nothing should change).
It should also be easy to check I think, by running `CHECKSUM TABLE` on all tables before and after and checking the output. If this works it should definitely be implemented imo, because saying 'changed' even though it hasn't changed is just completely wrong.

A real gain would of course be if it doesn't first run the entire thing before it concludes that it didn't have to, but I wouldn't know if that's possible.
An unsafe way to do it though would be to just check if a table exists. That will create lots of problems I suppose, but perhaps this would be a nice way to do it:

If the table is created because of `state: present`, and a `target` is specified, then import. If already present, do nothing. If no `target` specified, just do old behavior.
