### ISSUE TITLE
hostname module detect FQDN and update /etc/hosts

### ISSUE THREAD

**Issue by twouters** [ansible/ansible#5748]
The hostname module currently sets the hostname wether it's an FQDN or not.

```
# hostname
testhostname.example.tld
# hostname -f
hostname: Unknown host
```

Ideally it should set the hostname to the first part of the FQDN (until the first dot).
`/etc/hosts` should be updated to include a rule like this:

```
127.0.0.1    {{ hostname_fqdn }} {{ hostname }} localhost localhost.localdomain ....
```

Or if the provided hostname is not an FQDN:

```
127.0.0.1    {{ hostname }} localhost localhost.localdomain ...
```

Another option would be to insert a new line above all other entries using the primary IP address of the host, leaving the existing localhost lines as they are.
But this could be less trivial to do, since detecting what the primary IP is might be difficult.

```
192.168.0.2    {{ hostname_fqdn }} {{ hostname }}
```

I'm not entirely sure this is exactly how it should be done, it's just how I usually do it.
I haven't been able to think of cornercases which would make this an invalid procedure.

**Comment by kiranos** [comment]
This is how fqdn should be set if for example hostname -f should output:  server.example.com 

/etc/hosts:
192.168.5.9     server.example.com server

/etc/hostname
server

and /etc/hosts should also have 127.0.0.1 localhost etc. but the part about fqdn is as above.

```
#/etc/hosts:
127.0.0.1       localhost
192.168.5.9     server.example.com server

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

```
#/etc/hostname
server
```

Imo the hostname module should be able to set the FQDN and not just the partial hostname, maybe I should write a separate feature request for that?

**Comment by filipenf** [comment]
@kiranos What if we have 2 NICs? Just pick the first one?

**Comment by kiranos** [comment]
you should pick the one that host the ip which the domain name is pointing to

**Comment by filipenf** [comment]
It wouldn't work. The domain name will point to the public IP and in most of the cases we just have the private IP.

I think the sugestion from @twouters is easier to implement and works well.

**Comment by filipenf** [comment]
Actually I just sent a PR (#8482) to add an alias to /etc/hosts.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
