### ISSUE TITLE
Negation of evaluated False results in False

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#5779]
Based on https://groups.google.com/forum/#!topic/ansible-project/5CnhAFxSZPo

Found something strange (possible bug?)  in evaluating True/False inside vars. 
Only in one particular case - if variable is evaluated as "False" - its not converted to "True" with "not"

In my example false_eval is evaluated to "False" inside debug module but "not false_eval" is still "False". Any reason for that?
- debug: var=false_eval
  TASK: [debug var=false_eval] **************************************************
  ok: [localhost] => {
  "false_eval": "False"
  }
- debug: var={{not false_eval}}
  TASK: [debug var=False] *******************************************************
  ok: [localhost] => {
  "False": "False" 
  }

playbook.yml
- hosts: localhost
  gather_facts: no
  
  vars:
    foo: bar
    true_eval: '{{ foo == "bar" }}'
    false_eval: '{{ foo != "bar" }}' 
  
  tasks:
  - debug: var=true_eval
  - debug: var={{ not true_eval }}
  - debug: var=false_eval
  - debug: var={{not false_eval}}

Output:

PLAY [localhost] **************************************************************

TASK: [debug var=true_eval] ***************************************************
ok: [localhost] => {
    "true_eval": "True"
}

TASK: [debug var=False] *******************************************************
ok: [localhost] => {
    "False": "False"
}

TASK: [debug var=false_eval] **************************************************
ok: [localhost] => {
    "false_eval": "False"
}

TASK: [debug var=False] *******************************************************
ok: [localhost] => {
    "False": "False"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0

Ansible 1.4.4
Ansible 1.5 devel

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
