### ISSUE TITLE
lineinfile doesn't play well with files that don't end with a newline

### ISSUE THREAD

**Issue by donspaulding** [ansible/ansible#5825]
The following task...

```
-  lineinfile: dest=/etc/ssh/sshd_config regexp="^AllowGroups" line="AllowGroups root projects vagrant" state=present
```

... is intended to make sure the line exists in the default sshd configuration file.  However, apparently when lineinfile doesn't find the regexp in the file at all, it attempts to insert the line beginning at the `dest` file's EOF.  If that EOF is not a newline, as is the case in Ubuntu 13.10's default sshd_config, it results in the line value being merged with the last line in the file.  It looks like this:

```
UsePAM yesAllowGroups root projects vagrant
```

Which is a syntax error that prevents sshd from starting up.  If your goal is to automate the provisioning of a server inaccessible via ssh, perhaps this is what you want.  I just can't help but think it's not the expected behavior for most folks.

Oh, and I saw this mentioned [here](https://www.mail-archive.com/ansible-project@googlegroups.com/msg00205.html) but I don't see where an issue was ever opened.

**Comment by danielparks** [comment]
This is fixed by #7702

**Comment by glyph** [comment]
That says it was merged 24 days ago, but I notice that (A) this issue is still open, and (B) I just hit this bug with Ansible 1.6.6 which according to https://pypi.python.org/pypi/ansible dropped only 4 days ago. Should this have been in that release, and if not, any clue when it will hit PyPI?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
