### ISSUE TITLE
supervisorctl module does not detect group process restats

### ISSUE THREAD

**Issue by pySilver** [ansible/ansible#5844]
Seems that supervisorctl is not capable to correcly handle grouped process restarts,

This is my task (handler):

```
- name: restart application
  # using ":" because its a group of jobs, otherwise supervisorctrl will fail to find job name
  supervisorctl: name="{{ project.name }}-application:" state=restarted 
```

Output:

```
NOTIFIED: [application | restart application] ********************************* 
failed: [33.33.33.10] => {"failed": true, "item": ""}
msg: 'convertiser-server-application 01': stopped
'convertiser-server-application 00': stopped
'convertiser-server-application 01': started
'convertiser-server-application 00': started
```

Output seems to be correct, but ansible module detects it as failure. For time being fix might be achieved by using manual error handling:

```
register: command_result
failed_when: "'ERROR' in command_result"
```

http://docs.ansible.com/playbooks_error_handling.html

**Comment by jeremyajohnson** [comment]
I've also had to workaround this by restarting individual processes.

**Comment by stefan-feltmann** [comment]
I have had the same problem.  I managed to get it working with pySilver's workaround.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
