### ISSUE TITLE
Return useful command line feedback on missing parameters and errors

### ISSUE THREAD

**Issue by ringe** [ansible/ansible#5846]
When there's an error in an ansible playbook, there is no mention of where this error was found:

```
$ ansible-playbook site.yml 
ERROR: hosts is not a legal parameter in an Ansible task or handler
```

The problem is that in the example above, the error resides in roles/common/tasks/main.yml

The reason is that the tasks file was copied over from a separate playbook.

Knowing this, I can check for such mistakes in the future. But My point is that as a new Ansible user, I had no idea why this would fail. I was trying to do it just like in #Best Practices". See #5842 

A similar problem is found in the comments at #3881 - we could definitely use some feedback when the remote shell in hanging, waiting for input that will never be sent (missing --ask-sudo-pass).

**Comment by mpdehaan** [comment]
Yeah this is somewhat difficult to establish as this happens after all of the parsing is done.

It would be nice to have.

**Comment by ringe** [comment]
Updated ticket for broader feedback, see #3881

**Comment by mpdehaan** [comment]
Please comment only on active tickets  Thanks!

**Comment by feliksik** [comment]
I am also running into this, and this indeed applies to more failures than the tasks-errror. 

It makes it harder to debug ansible scripts, unfortunately.

**Comment by jimi-c** [comment]
Hi, this is something which has been actively improved upon in the v2 (ansible 2.0) code base. For example, you should now see an error like this:

<pre>
ERROR! 'hosts' is not a valid attribute for a Task
The error appears to have been in '/path/to/your/playbook.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  tasks:
  - debug: msg="hi"
    ^ here
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
