### ISSUE TITLE
setup hangs if hostname is unresolvable

### ISSUE THREAD

**Issue by zirpu** [ansible/ansible#5876]
I was testing setting of the hostname via the 'hostname' module and discovered
if you have it set to something like 'nonesuch', 'setup' module collection hangs while trying
to resolve it.

**Comment by mpdehaan** [comment]
Closing due to lack of updates, please feel free to reopen if you still feel this is a problem.

**Comment by Govinda-Fichtner** [comment]
I just had the same problem... 

I am creating a virtual maschine, then wait for its SSH Port to become available and finally I want to run setup to gather necessary facts for later tasks...
Setup fails because the hostname is not resolvable at this moment in time...
It also does not make sense to add the FQDN and the current ip of the VM to the local /etc/hosts of the maschine where the ansible playbook is running because the IP of the VM is going to be changed by another task later...
The first IP is the IP of VM Template that is used to clone the VM. The second IP is the IP that will be used as the final IP for the VM.

It would be great if one could provide just a IP ({{ host_ip }}) for the setup module as a parameter which is then used instead of the FQDN...
Maybe that is even possible right now and I just do not know it...?!

**Comment by Govinda-Fichtner** [comment]
OK. I found a way to work around this:

```
- name: get facts from vm as the following tasks need the information
  setup:
  delegate_to: "{{ vm_template_ip }}"
```

**Comment by jctanner** [comment]
@Govinda-Fichtner If I understand your description, I think you could also use add_host and a second play in the playbook to provision the VM. Check our ec2 example: http://docs.ansible.com/guide_aws.html#example-4

**Comment by bcoca** [comment]
I experienced similar issue, but it is not a hang, just looooong timeout
while it tries to resolve the 'unresolvable' name. Eventually setup comes
back, if you have the patience to not Ctrl+C (at least in my case)
