### ISSUE TITLE
with_items flatten list of lists

### ISSUE THREAD

**Issue by ko-zu** [ansible/ansible#5913]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A
##### Summary:

with_items flatten list of lists.
##### Steps To Reproduce:

```
    - debug: msg="{{ item.src }} , {{ item.dest }}"
      with_items:
        - { src: abc, dest: def }
    - debug: msg="{{ item.0 }} , {{ item.1 }}"
      with_items:
        - [abc, def]
```

should be identical tasks.
but later one iterates through "abc" AND "def", which prints "a , b" and  "d , e".
##### Expected Results:

both should output msg=""abc, def"

```
ok: [host] => (item=[abc, def]) => {
    "item": ["abc, "def"],
    "msg": "abc , bef"
}
```
##### Actual Results:

later one iterates through "abc" and "def", which prints "a , b" and  "d , e".

```
ok: [host] => (item=abc) => {
    "item": "abc",
    "msg": "a , b"
}
ok: [host] => (item=def) => {
    "item": "def",
    "msg": "d , e"
}
```

**Comment by kuba** [comment]
I can confirm this bug. With this playbook:

```
- hosts: all
  gather_facts: no
  tasks:
  - debug: var=item
    with_items:
    - ['abc', 'def']
    - ['ghi', 'jkl']
```

following output is produced:

```
PLAY [all] ******************************************************************** 

TASK: [debug var=item] ******************************************************** 
ok: [localhost] => (item=abc) => {
    "item": "abc"
}
ok: [localhost] => (item=def) => {
    "item": "def"
}
ok: [localhost] => (item=ghi) => {
    "item": "ghi"
}
ok: [localhost] => (item=jkl) => {
    "item": "jkl"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

This happens for both:
- 1.4.4
- and ansible 1.5 (devel ab0adaf613) last updated 2014/02/08 13:49:16 (GMT +100)

**Comment by kuba** [comment]
This is related to 43d22b0c421e72772be092c3f1ebeaa0f9613dff and #1711.

**Comment by kuba** [comment]
Haha, have a look at https://github.com/ansible/ansible/pull/1711#issuecomment-10933724 and https://github.com/ansible/ansible/pull/1711#issuecomment-10934000. As @mpdehaan stated: "I know it breaks that, but it is completely gross and deserves to be broken". What they didn't foresee at that point is that somebody may just have a list of lists on `with_items` input:

```
- hosts: all
  gather_facts: no
  vars:
    foo: [['abc', 'def'], ['ghi', 'jkl']]
  tasks:
  - debug: var=item
    with_items: foo
```

and with the same run output as I pasted above in https://github.com/ansible/ansible/issues/5913#issuecomment-34544651.

This is clearly a bug and IMHO 43d22b0c421e72772be092c3f1ebeaa0f9613dff shall be reverted, but this might be hard as it's been like that since 1.1... However, given that now we have `with_flattened` (that has slightly different behaviour) maybe this odd `flatten(terms)` bit of code could be safely removed.

**Comment by mpdehaan** [comment]
This is intended behavior.  

@kuba, Assumptions that it is "clearly a bug" are of opinion nature.

Please ask on the list if you like.
