### ISSUE TITLE
"the connection plugin '<class 'ansible.utils.sentinel.Sentinel'>' was not found"

### ISSUE THREAD

**Issue by solarzc** [ansible/ansible#59390]
did anyone meet 
"the connection plugin '<class 'ansible.utils.sentinel.Sentinel'>' was not found"
problem in python3 api

**Comment by sivel** [comment]
Internal Ansible API
====================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may
continue to make Ansible better.

The internal Python API is considered an unsupported aspect of Ansible and this
is not considered a bug unless there is an issue with an Ansible binary
(`ansible`, `ansible-playbook`, `ansible-doc`, etc) or an issue with an external
API such as are provided for the development of plugins (modules, dynamic
inventories, callbacks, strategies, etc).

Thank you once again for this and your interest in Ansible!
