### ISSUE TITLE
allow sudo variable to be set by host_vars variables

### ISSUE THREAD

**Issue by jimus2** [ansible/ansible#5942]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 36250c6b86)
##### Environment:

I was running Ansible from Mac OSX 10.9.1 and managing CentOS release 5.7 (Final)
##### Summary:

sudo variable in my playbook can not be set by host_vars files variables
##### Steps To Reproduce:

1) I have a playbook with the following:

```
tasks:
 name: test
 command: do something
 sudo: "{{item.use_sudo}}"
 with_items: somelist
```

2) I have a host_var file with the following:

```
somelist:
- {name: jim, use_sudo: yes}
- {name: jim2, use_sudo: no}
```

3) When I run my playbook which references "somelist" from the host_vars file, I get a "Permission Denied" error

Looks like it was not able to set the sudo variable properly.

However, if I use "sudo: yes" in my playbook, then everything works fine
##### Expected Results:

The expected behavior should be that I can set the sudo variable with whatever value I pass from the host_vars variables
##### Actual Results:

I get "Permission Denied" error because sudo was not set

**Comment by noriordan** [comment]
I had the same issue so I raised

https://github.com/ansible/ansible/pull/6877

Hopefully that will solve this issue.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is an example and the resulting output:

<pre>
# cat test.yml
- hosts: all
  gather_facts: no
  vars:
    somelist:
    - user_name: testing
      use_sudo: yes
      
  tasks:
  - name: test
    command: whoami
    become: "{{item.use_sudo}}"
    become_user: "{{item.user_name}}"
    with_items: somelist
# ansible-playbook -v test.yml
PLAY: ***************************************************************************
TASK [test] *********************************************************************
{u'changed': True, u'end': u'2015-06-18 11:55:53.808571', u'stdout': u'testing', 'item': {u'use_sudo': True, u'user_name': u'testing'}, u'cmd': [u'whoami'], u'rc': 0, u'start': u'2015-06-18 11:55:53.806980', u'stderr': u'', u'delta': u'0:00:00.001591', 'invocation': {'module_name': u'command', 'module_args': {u'_raw_params': u'whoami'}}, 'stdout_lines': [u'testing'], u'warnings': []}
changed: [testing] => {"msg": "All items completed", "changed": true, "results": [{"changed": true, "end": "2015-06-18 11:55:53.808571", "stdout": "testing", "cmd": ["whoami"], "item": {"use_sudo": true, "user_name": "testing"}, "delta": "0:00:00.001591", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "whoami"}}, "stdout_lines": ["testing"], "start": "2015-06-18 11:55:53.806980", "warnings": []}]}
PLAY RECAP **********************************************************************
testing                   : ok=1    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
