### ISSUE TITLE
file module should error if src given without state=link

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#5947]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.5 (devel bbda98a3ee) last updated 2014/02/10 14:24:47 (GMT -500)
##### Environment:

Centos 6.5  N/A
##### Summary:

This is pretty minor, but it bit me and could safely give an error in this case.

From the docs for file module:
src         path of the file to link to (applies only to state=link). Will accept absolute, relative and nonexisting paths. Relative paths are not expanded.
##### Steps To Reproduce:

```
 - name: Test linking direction
   file: dest=doesnotexist src=doesnotexist
```
##### Expected Results:

Result:
TASK: [Test linking direction] ***********************************************\* 
fail: [localhost](red)
src is only defined for state=symlink.  Remove src or add state=symlink
##### Actual Results:

Result:
TASK: [Test linking direction] ***********************************************\* 
ok: [localhost](green)

**Comment by mpdehaan** [comment]
Thanks for the report. 

I agree you would think this should happen, but the way internal modules like template or copy call file, it can't trivally do that.

So we'd have to remove the "src" or "file" arguments to those modules prior to passing them along.

The code is simpler if we don't do this, so it's unlikely that we are going to tackle this soon because it would also break anyone's modules in the field where they have written their own action plugin and used the file module in the same way.
