### ISSUE TITLE
lineinfile behaves differently for " vs '

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#5949]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel 4688be33d4) last updated 2014/02/10 16:52:50 (GMT -500)
##### Environment:

N/A
##### Summary:

lineinfile fails with the second item below but passes when you switch the quotes " and '
##### Steps To Reproduce:

Here is an example:
Using centos6.5 exactly as below, otherwise replace path to number.py

```
#https://github.com/ansible/ansible/issues/276
  - name: Patch ansible bug related to pycrypto
   lineinfile: dest=/usr/lib64/python2.6/site-packages/Crypto/Util/number.py
               regexp="{{item.regexp}}" line="{{item.line}}"
   with_items:
     - { regexp: "HAVE_DECL_MPZ_POWM_SEC", line: "#if _fastmath is not None and not     _fastmath.HAVE_DECL_MPZ_POWM_SEC:" }
     - { regexp: "PowmInsecureWarning", line: '# _warn("Not using mpz_powm_sec. You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)' }
```
##### Expected Results:

The first item in with_items works.  I expect the second to as well.
Replacing the second with
         - { regexp: "PowmInsecureWarning", line: "# _warn('Not using mpz_powm_sec. You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.', PowmInsecureWarning)" }

Fixes it.  Just changed the outer quote to " and the inner quote to '
##### Actual Results:

```
TASK: [ansible_controller | Patch ansible bug related to pycrypto] ************ 
ok: [localhost] => (item={'regexp': 'HAVE_DECL_MPZ_POWM_SEC', 'line': '#if _fastmath is not     None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:'})
failed: [localhost] => (item={'regexp': 'PowmInsecureWarning', 'line': '# _warn("Not using    mpz_powm_sec. You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.",    PowmInsecureWarning)'}) => {"failed": true, "item": {"line": "# _warn(\"Not using mpz_powm_sec.     You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.\",    PowmInsecureWarning)", "regexp": "PowmInsecureWarning"}}
 msg: this module requires key=value arguments (['dest=/usr/lib64/python2.6/site-    packages/Crypto/Util/number.py', 'regexp=PowmInsecureWarning', 'line=# _warn(Not', 'using',     'mpz_powm_sec.', 'You', 'should', 'rebuild', 'using', 'libgmp', '>=', '5', 'to', 'avoid', 'timing', 'attack',      'vulnerability., PowmInsecureWarning)'])
```

**Comment by mpdehaan** [comment]
BTW, random :eek: at the idea of monkeypatching with lineinfile instead of using a package manager.

There's also a way to disable that warning using the warnings module in Python code.   Ok, now reading...

**Comment by mpdehaan** [comment]
Reformatting your ticket above...

**Comment by mpdehaan** [comment]
Not sure what's going on above.   May be YAML quoting issue.   In the queue to reproduce regardless.

**Comment by darKoram** [comment]
Thanks. I agree about the hacky patch, but i spent an hour or so trying yum options like --skip-broken with no luck.  So i added a #TODO and moved along.  My understanding of package manager tricks is not strong, but if you can suggest something to investigate, i would post a better method to the issue thread on the ansible site if i can make it work.

**Comment by josef-spak** [comment]
I believe #6821 could be related (and a bit clearer)

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by fcntl** [comment]
> Thanks very much for your interest in Ansible. It sincerely means a lot to us.

Tosser.
