### ISSUE TITLE
Not getting proper mtu on FreeBSD 10

### ISSUE THREAD

**Issue by smkelly** [ansible/ansible#5951]
##### Summary:

setup module not picking up proper mtu from FreeBSD ifconfig
##### Steps To Reproduce:
1. Run 'setup' module against FreeBSD 10.0-RELEASE machine
2. Look at ansible_lo0.mtu or any other interface
3. Compare to ifconfig output for the selected interface. See difference.
##### Expected Results:

ansible_vmx0.mtu should equal tue actual mtu from ifconfig
##### Actual Results:

ansible_<iface>.mtu == 0

**Comment by risaacson** [comment]
This also shows broken on devel(1.5) for both FreeBSD 9 and 10.

**Comment by bcoca** [comment]
so this currently  uses a generic function for BSDs, parses the text output from "ifconfig -a" and takes the 4rd word as mtu.

```
rc, out, err = module.run_command([ifconfig_path, '-a'])
for line in out.split('\n'):
    words = line.split()

....

 current_if['mtu'] = words[3]
```

Has this changed since FreeBSD 8? (I used to run 8 and this worked)  I don't currently have any FreeBSD so a patch or just even output from 'ifconfig -a' should be helpful for fixing this.

**Comment by kubicek** [comment]
It has changed from:

```
re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
```

to:

```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
```
