### ISSUE TITLE
service module: incorrect "unchanged" status when --check is used with "state=started enabled=yes".

### ISSUE THREAD

**Issue by Lastpixl** [ansible/ansible#5953]
##### Issue Type:

Bug Report
##### Ansible Version:

I'm using ansible v1.4.0.874.gacae162-1 (git version, just installed)
$ ansible --version
ansible 1.5
##### Environment:

openntpd is installed on my debian stable machine.
The openntpd service is enabled.
The openntpd service is not started.
##### Summary:

When "state=started enabled=yes" is passed to the service module
running with the --check option, the module incorrectly reports that no
change has to be performed if the service is enabled, but not started.
##### Steps To Reproduce:

The openntpd service is enabled on my_server.
The openntpd service is not started on my_server.

$ ansible -vvvv -i inventory my_server -m service -a "name=openntpd
state=started enabled=yes" --check

my_server | success >> {
"changed": false
}

However, when I run the same command without "--check", the service correctly gets started by ansible.
$ ansible -vvvv -i inventory my_server -m service -a "name=openntpd
state=started enabled=yes"
my_server | success >> {
"changed": true,
"enabled": true,
"name": "openntpd",
"state": "started"
}
##### Expected Results:

See above - correctly report which actions will be performed when --check is used.
##### Actual Results:

See above - Incorrect reporting of actions to be performed.

The culprit seems to be a call to self.module.exit_json in service_enable().
Thus, check_service_changed() will not be called.

**Comment by Lastpixl** [comment]
Dear ansibot, 
Could you ask your master to add a link to this template in https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md ?
That would be nice for future bug reporters.

**Comment by jctanner** [comment]
@Lastpixl yep, can do.

EDIT:

Done.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
