### ISSUE TITLE
"file" module error on Oracle Enterprise Linux

### ISSUE THREAD

**Issue by jrosengren** [ansible/ansible#5958]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.4
##### Environment:

Oracle Enterprise Linux 5.9
##### Summary:

I've encountered an error in a file module task running on OEL 5.9 that doesn't seem to have the same issue running on CentOS 5.x:
##### Steps To Reproduce:

```
- name: ensure /mnt/s3/quantumcloud exists
  file: path=/mnt/s3/quantumcloud owner=root group=root mode=0755 state=directory
  sudo: True
```
##### Expected Results:

If directory exists, a no change response
##### Actual Results:

```
fatal: [hostXXX.domainXXX] => failed to parse:
SUDO-SUCCESS-szammrqwhpjmcnhwvqnlnvdrpggamxsj
Traceback (most recent call last):
  File "/home/jrosengren/.ansible/tmp/ansible-1392144575.3-31016918420544/file", line 1378, in ?
    main()
  File "/home/jrosengren/.ansible/tmp/ansible-1392144575.3-31016918420544/file", line 269, in main
    changed = module.set_directory_attributes_if_different(file_args, changed)
  File "/home/jrosengren/.ansible/tmp/ansible-1392144575.3-31016918420544/file", line 833, in set_directory_attributes_if_different
    changed = self.set_mode_if_different(
  File "/home/jrosengren/.ansible/tmp/ansible-1392144575.3-31016918420544/file", line 796, in set_mode_if_different
    raise e
OSError: [Errno 5] Input/output error: '/mnt/s3/quantumcloud'
```

**Comment by risaacson** [comment]
@jrosengren Just to confirm that uner OEL 5.9 you are trying to confirm that a directory exists. You have tested with this file existing and you are getting this the error above. When you duplicate the test on a CentOS5 box you are not seeing the same error with the directory also existing. Correct?

I should be able to test after oracle lets me pull the ISO.

**Comment by bcoca** [comment]
is this an NFS mount? if so check for 'squash root' which would explain
this error under sudo.

**Comment by jrosengren** [comment]
@risaacson Your summary is spot on.

@bcoca It's not an NFS mount, it's actually a fuse mount (with allow_other as one of the mount options.  But again, this doesn't error out on CentOS 5.x, just on OEL 5.9

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
