### ISSUE TITLE
Create gce instance with permissions / service account scopes

### ISSUE THREAD

**Issue by jplehmann** [ansible/ansible#6003]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4.3
##### Environment:

N/A
##### Summary:

Want to use gce module to create an instance with any permissions to access any other Google cloud resources like storage.  Apparently I need to pass in the [service_account_scopes flag](https://developers.google.com/compute/docs/instances)  [as is seen done in the unit test](https://github.com/ansible/ansible/blob/devel/test/gce_tests.py#L208) when calling `gcutil` directly.  How can I pass this flag using the module?
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

cc @erjohnso

Many thanks!

**Comment by hkeide** [comment]
Any progress on this? @erjohnso @clconway

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
