### ISSUE TITLE
Traceback in ini_file module

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#6009]
##### Issue Type:

Bug Report & Documentation Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Mac OSX Mavericks 10.9.1 using vagrant 1.4.3
##### Summary:

I'm using the ini_file module: http://docs.ansible.com/ini_file_module.html

I just want to change cgi.fix_pathinfo=1 to cgi.fix_pathinfo=0 in php.ini which is under the [PHP] section. Play:
- name: configure php.ini
  ini_file: dest=/etc/php5/fpm/php.ini
               section=[PHP]
               option=cgi.fix_pathinfo
               value=0
               mode=0600

While running this it gives me this error: http://prntscr.com/2s6bb1

I can't find the mistake looking at the example, which is not very helpful and not relevant to an actual ini file.
##### Steps To Reproduce:

Run the above play on Mavericks with Vagrant.
##### Expected Results:

Change cgi.fix_pathinfo=1 to cgi.fix_pathinfo=0 in php.ini which is under the [PHP] section in php.ini
##### Actual Results:

Error: http://prntscr.com/2s6bb1

File contains parsing errors while it's a fresh php-fpm php.ini

Thanks for looking into this, hopefully the documentation.
- Hyperfocus1337

**Comment by mpdehaan** [comment]
Can you please share the INI file you were using ?

**Comment by hyperfocus1338** [comment]
Sure Michael, here's the (unedited) php.ini: https://gist.github.com/hyperfocus1337/9031568

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
