### ISSUE TITLE
mysql_db fails connecting to create a database while connection is possible

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#6042]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

Arch -> Ubuntu 12.04
##### Summary:

mysql_db fails connecting to create a database while connection is possible
##### Steps To Reproduce:

See below.
##### Expected Results:

I expect mysql_db to create a database on the node if I have the rights to do it.
##### Actual Results:

Actual results are opposite of expected results.
##### Description

From what I understand, mysql_db assumes that a connection has to be made to a database in every case :

Here is a simplified version of the code from  https://github.com/ansible/ansible/blob/devel/library/database/mysql_db#L263 :

```
    if state in ['dump','import']:
        connect_to_db = db
    else:
        connect_to_db = 'mysql'

    MySQLdb.connect(host=module.params["login_host"], 
                    port=int(module.params["login_port"]), 
                    user=login_user, 
                    passwd=login_password, 
                    db=connect_to_db)
```

So if I want to create a database, `connect_to_db` is set to 'mysql'. However, I can have rights to create database XXX and not have the rights to connect to 'mysql' database :

```
# mysql -u wp -p -h 1.2.3.4 mysql
Enter password: 
ERROR 1044 (42000): Access denied for user 'wp'@'1.2.3.4' to database 'mysql'
# mysqladmin create -u wp -p -h 1.2.3.4 wordpress
Enter password: 
# mysqlshow -u wp -p -h 1.2.3.4 wordpress
Enter password: 
Database: wordpress
+--------+
| Tables |
+--------+
+--------+
```

I am not sure of the original intend, but I don't think defaulting `connect_to_db` to `mysql` is necessary nor desirable.

**Comment by alanwj** [comment]
This is definitely a bug.  It effectively makes the mysql_db command unusable for any user except the mysql root user.

One workaround I've found is to do do something like:

```
GRANT SELECT ON mysql.time_zone TO myuser;
```

This gives 'myuser' the ability to connect to database 'mysql' without granting any real ability to do anything.

**Comment by Jmainguy** [comment]
So to create a db using mysql_db, first you need to connect and see if it exists already, or needs to be created. So to implement the suggestions above, there needs to be a way to check if a db exists or not without connecting to a db first. Not really sure how to implement this.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
