### ISSUE TITLE
ansible service module does not detect changes to service scripts on SLES

### ISSUE THREAD

**Issue by dirtyharrycallahan** [ansible/ansible#6064]
##### Issue Type:

Bug?
##### Ansible Version:

ansible 1.4
##### Environment:

SLES 11 SP2
##### Summary:

In a playbook deploy a service script to /etc/init.d/ using copy module then enable the service using the service module. If there are subsequent changes to the service script that change the dependencies (start order) it appears that the service module does not detect these and reinstall the service.
##### Steps To Reproduce:

See summary.
##### Expected Results:

Service module should detect that the dependencies have changed.
##### Actual Results:

Start order does not change. Work-around is to add a guard, disable the service before enabling it.

**Comment by mpdehaan** [comment]
Can you show a sample playbook that reproduces this problem?

**Comment by dirtyharrycallahan** [comment]
I will mock one up later today.

**Comment by dirtyharrycallahan** [comment]
Although the service module does not do quite what I want it to do I would not necessarily call it a bug. It only came up at my site because we deploy quite a few init scripts for things like torque, apache, IBM Rational Team Concert Build Engines, ClamAV, and other services.

ansible 1.5 (7fe3db40)

playbook
- hosts: localhost
  gather_facts: no
  
  tasks:
      - name: copy service file
        copy: src=foo dest=/etc/init.d/foo owner=root group=root mode=0755
  
  ```
  - name: enable service
    service: name=foo enabled=yes
  ```

foo:

#!/bin/bash
#

# foo        Startup script for foo

#

### BEGIN INIT INFO

# Provides: foo

# Required-Start:

# Required-Stop:

# Default-Start: 2 3 4 5

# Default-Stop: 0 1 6

# Should-Start:

# Short-Description: start and stop foo server

# Description: The foo service

### END INIT INFO

<< removed data not pertinent >>

lrwxrwxrwx. 1 root root 13 Feb 20 00:30 /etc/rc.d/rc3.d/S50foo -> ../init.d/foo

#!/bin/bash
#

# foo        Startup script for foo

#

### BEGIN INIT INFO

# Provides: foo

# Required-Start: httpd

# Required-Stop: httpd

# Default-Start: 2 3 4 5

# Default-Stop: 0 1 6

# Should-Start:

# Short-Description: start and stop foo server

# Description: The foo service

### END INIT INFO

<< removed data not pertinent >>

Service already enabled no change.

lrwxrwxrwx. 1 root root 13 Feb 20 00:30 /etc/rc.d/rc3.d/S50foo -> ../init.d/foo

Desired result:

# chkconfig foo off

# chkconfig foo on

lrwxrwxrwx. 1 root root 15 Aug 14  2013 /etc/rc.d/rc3.d/S85httpd -> ../init.d/httpd

lrwxrwxrwx. 1 root root 13 Feb 20 00:33 /etc/rc.d/rc3.d/S86foo -> ../init.d/foo

Work-around:

playbook
If playbook changes the dependencies for a service first disable it so it is reinstalled with
the correct dependencies.
- hosts: localhost
  gather_facts: no
  
  tasks:
      - name: copy service file
        copy: src=foo dest=/etc/init.d/foo owner=root group=root mode=0755
  
  ```
  - name: disable service
    service: name=foo enabled=no
  
  - name: enable service
    service: name=foo enabled=yes
  ```

**Comment by bcoca** [comment]
you can convert that into handlers and notify when copy detects change.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
