### ISSUE TITLE
pip with virtualenv - ValueError: ('Expected version spec in', 'upgrade,no-use-wheel', 'at', ',no-use-wheel')

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#6068]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (vault 8bfd83d042) last updated 2014/01/13 18:12:49 (GMT -500)
##### Environment:

MacOSx mountain lion for the ansible controller, targeting a centos6.5 vm on openstack.
##### Summary:

The following lines give
ValueError: ('Expected version spec in', 'upgrade,no-use-wheel', 'at', ',no-use-wheel')
- name: Upgrade setuptools
  pip: virtualenv="{{default_virtualenv}}"
      name=setuptools extra_args=upgrade,no-use-wheel 
##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, please link one uploaded to gist.github.com. 
##### Expected Results:

Expect setuptools to upgrade as via the commandline

 However, running from commandline on the target machine works

$ workon ENV1

(ENV1)[root@prod-pivot:~] pip install setuptools --upgrade --no-use-wheel

Installing collected packages: setuptools

  Found existing installation: setuptools 2.1

```
Uninstalling setuptools:

  Successfully uninstalled setuptools
```

  Running setup.py install for setuptools

```
Installing easy_install script to /root/venvs/ENV1/bin

Installing easy_install-2.7 script to /root/venvs/ENV1/bin
```

Successfully installed setuptools

Cleaning up...
##### Actual Results:

TASK: [linux_osx_common | Upgrade setuptools] ********************************\* 

failed: [prod-pivot] => {"cmd": "ENV1/bin/pip install upgrade,no-use-wheel --use-mirrors setuptools", "failed": true, "item": ""}

msg: stdout: New python executable in ENV1/bin/python

Installing setuptools, pip...done.

--use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.

Exception:

Traceback (most recent call last):

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/basecommand.py", line 122, in main

```
status = self.run(options, args)
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/commands/install.py", line 253, in run

```
InstallRequirement.from_line(name, None))
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/req.py", line 172, in from_line

```
return cls(req, comes_from, url=url, prereleases=prereleases)
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/req.py", line 70, in **init**

```
req = pkg_resources.Requirement.parse(req)
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/_vendor/pkg_resources.py", line 2606, in parse

```
reqs = list(parse_requirements(s))
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements

```
line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
```

  File "/tmp/ENV1/lib/python2.6/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list

```
raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
```

ValueError: ('Expected version spec in', 'upgrade,no-use-wheel', 'at', ',no-use-wheel')

Storing debug log for failure in /root/.pip/pip.log

FATAL: all hosts have already failed -- aborting

---

Slightly modifying the extra_args wrapping in quotes i get a similar error
- name: Upgrade setuptools
  pip: virtualenv="{{default_virtualenv}}"
      name=setuptools extra_args="upgrade no-use-wheel"

TASK: [linux_osx_common | Upgrade setuptools] ********************************\* 
failed: [prod-pivot] => {"cmd": "ENV1/bin/pip install upgrade no-use-wheel --use-mirrors setuptools", "failed": true, "item": ""}
msg: stdout: New python executable in ENV1/bin/python
Installing setuptools, pip...done.
--use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.
Downloading/unpacking upgrade
  Could not find any downloads that satisfy the requirement upgrade
Cleaning up...
No distributions at all found for upgrade
Storing debug log for failure in /root/.pip/pip.log

FATAL: all hosts have already failed -- aborting

---

Lines leading up to the "Upgrade setuptools"
- name: Install virtualenv 
  pip: name={{item}}
  with_items: 
  - virtualenv
  - virtualenvwrapper
  - name: Template virtualenv.sh to host
    template: src=virtualenv.sh dest="{{dest_config_profile}}"
             mode=0644 owner="{{_ansible_user}}" group="{{_ansible_user}}"
  - name: Source virtualenv.sh
    shell: source "{{dest_config_profile}}/virtualenv.sh"
  - name: Create virtualenv 
    shell: creates="{{VIRTUALENV_HOME}}/{{default_virtualenv}}"
          "source {{dest_config_profile}}/virtualenv.sh && mkvirtualenv -p /usr/local/bin/python2.7 {{default_virtualenv}}"
  - name: Install common python
    pip: virtualenv="{{default_virtualenv}}"
        virtualenv_site_packages=yes
        virtualenv_command=virtualenv
        chdir="{{VIRTUALENV_HOME}}"
        name="{{item}}"
    with_items: common_python

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
