### ISSUE TITLE
`git` module cannot clone empty repo.

### ISSUE THREAD

**Issue by chakrit** [ansible/ansible#6091]
##### Issue Type:

"Bug Report" or maybe a "Feature Idea"
##### Ansible Version:

ansible 1.4.4
##### Environment:

Latest OS X
`uname -a` gives `Darwin  13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64`
##### Summary:

Sometimes the source repository has nothing pushed to it yet and other times the source repository is also on a machine managed by ansible as part of our setting everything up (so everything is created as empty initially.)

This will cause ansible `git` module to error with "cannot clone empty repository."

This is actually required in our current setup as we use ansible to setup CI servers for projects on client's infrastructure (client's EC2 account) and we need git repositories on the server that links from another repository on github (or somewhere inside the client's infrastructure)

Not a high priority but a very nice to have. It is not hard to do this ourselves with the `command` module but it is clumsy to use ansible variables in there and there are no permission settings (we have to sudo at times, and adds additional `file` task at other times), for example.
##### Steps To Reproduce:
1. Create a simple playbook
2. Add "command: git init --bare /somewhere" task
3. Adds "git: repo=/somewhere dest=/anywhere" task
4. Run it
##### Expected Results:

Everything completes successfully.
##### Actual Results:

Steps 3 errors with "cannot create empty repository". We have since worked around the issue and I've lost the exact content. Will update if I find encounter this again.

**Comment by chakrit** [comment]
Updated as per @ansibot request.

**Comment by mpdehaan** [comment]
So this error message comes from git itself, so the git command line clone command won't work either.

Is there a particular flag to git you think we should be passing?

**Comment by chakrit** [comment]
Hmm. It _does_ work. Here's the output on my machine:

``` sh
chakrit@cx24 /tmp> rm -Rf a b
chakrit@cx24 /tmp> mkdir a
chakrit@cx24 /tmp> git init a
Initialized empty Git repository in /private/tmp/a/.git/
chakrit@cx24 /tmp> git clone a b
Cloning into 'b'...
warning: You appear to have cloned an empty repository.
done.
chakrit@cx24 /tmp> ls -a b
.    ..   .git
chakrit@cx24 /tmp> 
```

Only a warning is emitted. I think maybe it is giving `git` some extra flags (to specify commit) that doesn't work with empty repositories?

**Comment by chakrit** [comment]
Oops, forgot the --bare flag. Anyway here's a similar run on an ubuntu machine which is my target:

``` sh
ubuntu@hub:~$ mkdir a
ubuntu@hub:~$ git init --bare a
Initialized empty Git repository in /home/ubuntu/a/
ubuntu@hub:~$ git clone a b
Cloning into 'b'...
done.
warning: You appear to have cloned an empty repository.
ubuntu@hub:~$ echo $?
0
ubuntu@hub:~$ git --version
git version 1.7.9.5
ubuntu@hub:~$ uname -a
Linux hub.fingi.com 3.2.0-56-virtual #86-Ubuntu SMP Wed Oct 23 09:43:22 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

Everything works. Only warnings are emitted. And the return code is 0.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
