### ISSUE TITLE
included task with a tag does not trigger notify task

### ISSUE THREAD

**Issue by stick** [ansible/ansible#6094]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A
##### Summary:

When you execute the playbook with the '--tags supercool' it runs all the tasks associated with the included playbook but does not notify the trigger task.
##### Steps To Reproduce:

Given this playbook snippet:

```
- include: tasks/subtask.yml
  tags: supercool
  notify: reload nginx
- name: reload nginx
  service: name=nginx state=reloaded
```
##### Expected Results:

I would expect nginx to reload based on the notify: reload nginx trigger.
##### Actual Results:

```
$ ansible-playbook test.yml --tags supercool 

PLAY [Main playbook overview] ************************************************* 

GATHERING FACTS *************************************************************** 
ok: [charity.foo.com]

TASK: [template out configuration for demo site "supercool"] ******** 
changed: [charity.foo.com]

TASK: [create content location dir] ******************************************* 
changed: [charity.foo.com]

TASK: [create dev content location dir] *************************************** 
changed: [charity.foo.com]

PLAY RECAP ******************************************************************** 
charity.foo.com : ok=4    changed=3    unreachable=0    failed=0 
```

The tagged task works as expected however nginx (in this example) doesn't get notified to reload.

**Comment by mpdehaan** [comment]
I would agree that we should consider not requiring tags to run handlers and this is an easy change to make that should not hurt anyone.  I'll probably start a list thread to make sure this doesn't cause too much chaos :)

**Comment by jimi-c** [comment]
@stick so the issue here is that you've put the `notify:` line on the include, which is not supported. What's happening under the hood is you're essentially defining a new variable called `notify` that's being passed into the include, similar to the way a parameterized role works. You'll have to put the notification on one of your tasks in your `subtask.yml` file for it to trigger correctly.

Additionally, and I'm not sure if it's because your example is just a snippet, but handlers must be declared in the `handlers:` section (or for roles, in `handlers/main.yml`). You can not use `notify:` for regular tasks.

Please let us know if you have any further questions regarding this issue. Thanks!
