### ISSUE TITLE
mysql_user: password parameter is required

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#6141]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.5 (devel 00ed610a34) last updated 2014/02/24 02:48:28 (GMT +200)
##### Summary:

[Documentation](http://docs.ansible.com/mysql_user_module.html) claims that password parameter is not required, while Ansible requires it in **mysql_user** module.
##### Steps To Reproduce:

N/A
##### Expected Results:

required = yes
##### Actual Results:

required = no

**Comment by mpdehaan** [comment]
I think this is actually ok.   What happens is the code will yell if it needs a password and there is no credentials file, where as the documentation in the table is about whether the password field is required every single time.   As such, I think we are going to leave this as it is (since it's not required in all cases).
