### ISSUE TITLE
Want option to download public key with "adv --recv-keys" using the apt_key module

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible#6148]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible --version
ansible 1.4.5
##### Environment:

Generic feature request
##### Summary:

I want to install rsyslog with Ansible on my Ubuntu 13.10 machine using the following tutorial: http://www.rsyslog.com/ubuntu-repository/

You need to install the public key with:

"apt-key adv --recv-keys --keyserver keyserver.ubuntu.com AEF0CF8E"

Typing "man apt-key" tells you: 

"adv Pass advanced options to gpg. With adv --recv-key you can download the public key."

As far as I can tell there is no option for advanced options yet in the apt_key module: http://docs.ansible.com/apt_key_module.html

So for now I'm relying on the command module to install the latest rsyslogd.
##### Steps To Reproduce:

No steps
##### Expected Results:

Want to be able to add advanced options to the apt_key module for above use case.
##### Actual Results:

Missing options

**Comment by mpdehaan** [comment]
We'd be happy to take pull requests to the apt_key module to support this, is this something you would like to work on?

**Comment by dmage** [comment]
Since 1.6

```
apt_key: keyserver=keyserver.ubuntu.com id=AEF0CF8E
```

should work.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
