### ISSUE TITLE
bin scripts are not extensible

### ISSUE THREAD

**Issue by dghubble** [ansible/ansible#6180]
##### Issue Type:

Design Critique
##### Ansible Version:

1.4
##### Environment:

NA
##### Summary:

There is really no reasonable way to extend the bin scripts to create effective wrappers for them if desired. The bin scripts are not part of the exported ansible package either. With so many command line options, either a default extensible parser and builder should be provided in the package or strive to simplify the API interface drastically. For example, group sudo/su related options into an object, etc.

If you provide extensible parsers, please consider using argparse. Optparse is deprecated and janky.
##### Steps To Reproduce:

NA
##### Expected Results:

NA

**Comment by mpdehaan** [comment]
Not sure what you mean by wrapper scripts, though the main goal of this project is to build ansible and ansible-playbook, not a framework for creating arbitrary wrapper scripts on top of it.

Optparse also isn't going away anytime soon, and we can deal with that when we need to.  

We are not (for compatibility reasons) going to be changing the CLI interface options at this time and common options do exist in utils/ for creating parsers.   

Yes, there are a lot of options to Runner and Playbooks, but keeping compatibility is important to us.  In either case, Playbook and Runner code serve as examples of what is possible, and we're always open to questions.

Really though, Runner's not so much meant to be an API -- it's meant to be the guts of the program, and it serves those needs.   If you're asking about Runner too, that doesn't necessarily mean you couldn't use argparse on top of Runner... but yes, it's going to have the API signature it presently has.

Ultimately, this isn't going to be something we care about too much -- in the future -- since this isn't a bug or feature request, I'd suggest starting a post on ansible-devel asking why something is the way it is, etc.

Hope this explains the direction.
