### ISSUE TITLE
pip module always recreates virtualenv

### ISSUE THREAD

**Issue by lawik** [ansible/ansible#6191]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.5
##### Environment:

N/A
##### Summary:

As far as I can tell the pip module always recreates the virtualenv when you use the virtualenv option. This has hilarious side-effects and causes issues making installation of pip packages in virtualenvs a lot less idempotent than ideal.

I'm looking at the code but not quite sure if there's a check or not: https://github.com/ansible/ansible/blob/devel/library/packaging/pip
##### Steps To Reproduce:

Provision a host with:

```
- name: set up account_service python requirements
pip: chdir=/vagrant/services/my_service requirements=requirements.txt virtualenv=env
```

Run a service or daemon of some kind using /vagrant/services/my_service/env/bin/python

Provision the host again without stopping the service.
##### Expected Results:

The pip install should just run through, see that requirements.txt has already been fulfilled and move on.
The virtualenv should be untouched except for using the binaries in it and possibly installing packages from requirements.txt.
##### Actual Results:

The pip task fails as it tries to recreate the virtualenv while it is in use, it throws the error:

```
IOError: [Errno 26] Text file busy: 'env/bin/python'
```

**Comment by lawik** [comment]
Nice bot :) And nice system. Really enjoying learning and using it.

**Comment by lawik** [comment]
I'm currently working around it by working directly with commands and the shell:

```
- name: set up user_service virtualenv
  shell: chdir=/vagrant/services/user_service if [ ! -d env ]; then virtualenv env; fi
- name: set up user_service python requirements
  command: chdir=/vagrant/services/user_service env/bin/pip install -r requirements.txt
```

**Comment by lawik** [comment]
I'm not sure about your issue. Do you get the same error as me? Unless you do I'd recommend making a separate issue to keep the discussion focused in both our cases :)

The core python libraries are available without the global system site packages in any virtualenv. I've never wanted or needed that option.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
