### ISSUE TITLE
example in filesystem module fails

### ISSUE THREAD

**Issue by oppianmatt** [ansible/ansible#6204]
##### Issue Type:

“Bug Report”, “Documentation Report"
##### Ansible Version:

ansible 1.4.4
##### Environment:

from: Mac OS X Maverick
to: Ubuntu 12.04
##### Summary:

Example in 'filesystem' module is broken
##### Steps To Reproduce:

```
- filesystem: fstype=ext4 dev=/dev/sdb1 opts="-cc"
```
##### Expected Results:

create ext4 fs with block level checking
##### Actual Results:

```
failed: [host01.example.com] => {"err": "mke2fs 1.42 (29-Nov-2011)\nmkfs.ext4: invalid blocks '/dev/sdb1' on device 'ext4'\n", "failed": true, "item": "", "rc": 1}
msg: Creating filesystem ext4 on device '/dev/sdb1' failed
```

---

Trying to use the filesystem module to create a ext4 filesystem on a newly created partition with parted. I even use the example provided on the docs since it's the same device.
- filesystem: fstype=ext4 dev=/dev/sdb1 opts="-cc"

It appears to be running the wrong mkfs command judging by the output:

TASK: [ssd | create ext4 filesystem] ******************************************
<host01.example.com> ESTABLISH CONNECTION FOR USER: matt
<host01.example.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=120s', '-o', 'ForwardAgent=yes', '-o', 'ControlPath=/Users/matt/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'host01.example.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1393515212.29-107319873632586 && chmod a+rx $HOME/.ansible/tmp/ansible-1393515212.29-107319873632586 && echo $HOME/.ansible/tmp/ansible-1393515212.29-107319873632586'"]
<host01.example.com> REMOTE_MODULE filesystem fstype=ext4 dev=/dev/sdb1 opts="-cc"
<host01.example.com> PUT /var/folders/n4/2rsmjk6s3kv07f5djbd_z7sh0000gn/T/tmpTxG8uE TO /home/matt/.ansible/tmp/ansible-1393515212.29-107319873632586/filesystem
<host01.example.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=120s', '-o', 'ForwardAgent=yes', '-o', 'ControlPath=/Users/matt/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'host01.example.com', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=tenalnghvtoayznbfsfcljzocsxdgpzg] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-tenalnghvtoayznbfsfcljzocsxdgpzg; /usr/bin/python /home/matt/.ansible/tmp/ansible-1393515212.29-107319873632586/filesystem; rm -rf /home/matt/.ansible/tmp/ansible-1393515212.29-107319873632586/ >/dev/null 2>&1\'"\'"\'\'']
failed: [host01.example.com] => {"err": "mke2fs 1.42 (29-Nov-2011)\nmkfs.ext4: invalid blocks '/dev/sdb1' on device 'ext4'\n", "failed": true, "item": "", "rc": 1}
msg: Creating filesystem ext4 on device '/dev/sdb1' failed

I did some looking under the hood at what command it actually runs and it was:

mkfs -t ext4 -cc '/dev/sdb1'

turns out that doesn't work on my ubuntu (12.04)

It gives the error message:

mke2fs 1.42 (29-Nov-2011)
mkfs.ext4: invalid blocks '/dev/sdb1' on device 'ext4'

Instead I had to modify the example to be:

filesystem: fstype=ext4 dev=/dev/sdb1 opts="-c -c"

and that works. Docs need updating.

**Comment by mpdehaan** [comment]
A traceback in Ansible should be a bug, so regardless of whether we have a docs update issue here I definitely think we need to catch the above TB and present a better failure message.

**Comment by oppianmatt** [comment]
There wasn't a TB. That was output with -vvvv

It just outputs std{err,out} with the msg from mkfs

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
