### ISSUE TITLE
--list-task does not indicate roles when listing tasks

### ISSUE THREAD

**Issue by gregbuehler** [ansible/ansible#6216]
##### Issue Type:

"Bug Report"
##### Ansible Version:

ansible-playbook 1.4.5
##### Environment:

N/A 
##### Summary:

Normal ansible-playbook output indicates the role from which a task is used. This should also be indicated in --list-tasks output.
##### Steps To Reproduce:

```
ansible-playbook -i env/foo foo.yml --list-tasks
```
##### Expected Results:

```
play #4 (foo):
    [ java ] check existing java
    [ java ] Create /usr/java
    [ java ] Create /usr/framework/java
    [ java ] Create java directory
    [ java ] Copy Java to host
```
##### Actual Results:

```
play #4 (foo):
    check existing java
    Create /usr/java
    Create /usr/framework/java
    Create java directory
    Copy Java to host
```

**Comment by mpdehaan** [comment]
Since the running tasks do this, I think it would be nice if the list tasks do this as well.

Nice catch!

**Comment by jimi-c** [comment]
Hi @gregbuehler, in 2.0 --list-tasks should show the role name in the task list, so this should be resolved.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
