### ISSUE TITLE
Come up with common list of utility functions for modules, auto template code into modules that request it

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#623]
Obviously there are things like fail_json/exit_json/etc, though I also want to standardize argument parsing and also variable access and return messages.

**Comment by mpdehaan** [comment]
These will be templated into a module via Jinja2 using

{{ ansible_template_python_modules_here }}

and hacking/test_module will have to notice and respect this

calling signature of these functions will not be allowed to change

**Comment by ghost** [comment]
I think we should template a few predefined scenarios / functions
1. When the argfile is missing for some reason
2. What happens when we dont receive the correct parameters
2. What happens when an error occurs (execution error or an exception)
3. What happens on success

I would suppose it makes sense for the output to contain two aspects
1. status => failed | success
2. rc => rc returned by the module
3. module_output => "string" or "json object"

**Comment by mpdehaan** [comment]
failed=True, msg="why" is already a thing, and yeah, I intend to enforce the argument parsing and valid/invalid parameters stuff, totally.

There will probably be a whole class transferred to the remote that you have to use as a constructor specifying these things, to ensure they are always done.   Will probably start with slurp, seeing it's off the critical path too, so great idea there :)

I don't think we will enforce requiring a rc, because we aren't always executing commands, but that should be a "should" in the module documentation for when a command failure is returned.  The command module itself already does this.

**Comment by mpdehaan** [comment]
done, see list for details and discussion thread.   Once we refine the common modules code a bit (if at all, it might be ok) we'll be good to go.
