### ISSUE TITLE
htpasswd modules: fails if the first line in it is blank

### ISSUE THREAD

**Issue by xshadow** [ansible/ansible#6253]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

Debian Wheezy 
##### Summary:

If you have an existent .htpasswd file in which the first line is blank (for what reasons ever), the htpasswd module fails.

Example:
 /var/www/foo/www/.htpasswd

```

user:cryptopassword
```
##### Steps To Reproduce:

Run the htpasswd module on a .htpasswd file in which the first line is left blank and in the second line is the password.
##### Expected Results:

changed password in .htpasswd file
##### Actual Results:

msg: need more than 1 value to unpack
FATAL: all hosts have already failed -- aborting

**Comment by jctanner** [comment]
@xshadow is there a traceback if you pass -vvvv to ansible-playbook? Can you copy that to the ticket?

**Comment by xshadow** [comment]
Does not look like that:

failed: [www.org.] => (item={'host': 'smfrole.foo.li', 'user': 'smfrole', 'htpasswd_passwd2': '', 'boardname': 'neuesSMF', 'htpasswd_user2': '', 'language': 'german-utf8', 'htpasswd_passwd': 'foo123', 'htpasswd_del_user': '', 'htpasswd_user': 'foo123', 'need_install': False, 'mysql_passwd': 'foo123', 'smf_cookie': 23}) => {"failed": true, "item": {"boardname": "neuesSMF", "host": "smfrole.foo.li", "htpasswd_del_user": "", "htpasswd_passwd": "foo123", "htpasswd_passwd2": "", "htpasswd_user": "foo123", "htpasswd_user2": "", "language": "german-utf8", "mysql_passwd": "foo123", "need_install": false, "smf_cookie": 23, "user": "smfrole"}}
msg: need more than 1 value to unpack

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
