### ISSUE TITLE
Ansible facts are not accurate in cases with multiple virtual ip addresses.

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#6263]
##### Ansible Version: 1.5 (devel)

ansible 1.5 (devel bab91f9ed8) last updated 2014/02/14 11:50:02 (GMT -700)

However, I had seen this in earlier version like 1.4
##### Environment:

Centos 6 
##### Summary:

ansible_eth0.ipv4.address is not the correct IP address assigned to such as those found in /etc/sysconfig/network-scripts/ifcfg-eth0. 

This has happened to hosts that has a couple of virtual ip address like those setup in keepalived where eth0 has more than one ip addresses associated with.

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:25:90:d5:13:77 brd ff:ff:ff:ff:ff:ff
    inet 172.16.50.44/32 brd 172.16.11.255 scope global eth0
    inet 172.16.50.231/32 scope global eth0
    inet 172.16.50.230/32 scope global eth0
    inet 172.16.50.232/32 scope global eth0

In this case, ansible_eth0.ipv4.address is 172.16.50.232/32 and not 172.16.50.44/32

**Comment by PriceChild** [comment]
This looks to be identical to #7724 which has a pull request #7725 pending to fix the behaviour.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
