### ISSUE TITLE
Ansible 1.5 file lookup plugin strips double quotes

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#6294]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5
##### Environment:

N/A
##### Summary:

One of either the file lookup plugin or the authorized_key module, is removing double quotes from the file being read.
##### Steps To Reproduce:

Create a play like this:

authorized_key: user=monitoring key="{{lookup('file', 'monitoring.pub')}}"

In the monitoring.pub file, insert the content:

from="addr1,addr2,addr3",no-pty ssh-rsa AAAA....

Then run the play.
##### Expected Results:

I expect the contents of the file monitoring.pub to be inserted into the monitoring user's authorized_keys file.
##### Actual Results:

Ansible gives me the error:

msg: invalid option string: from=addr1,addr2,addr3,no-pty

**Comment by mpdehaan** [comment]
So what is happening here is the lookup plugin is evaluated at Jinja2 level and then inserted directly into the YAML.

To preserve the double quotes, you will need to escape them, because the first quote around the "{{" will match up with the quote around the ="addr1, and close off the pair.

So in your file:

```
from=\"addr1,addr2,addr3\",no-pty ssh-rsa AAAA....
```

And the inline expansion won't break things.

I also imagine you might be able to leave out the quotes.  

This isn't going to be fixable but is a consequence of how the lookup plugin is evaluating your line.

A cleaner way to get around this is also this:

authorized_key: 
    user: monitoring 
    key: "{{lookup('file', 'monitoring.pub')}}"

Notice the passing of arguments as hash members versus key=value strings.

In which case the string won't be "shlexed" and will just work, without modifying the file contents.

Hope this helps!

**Comment by aabdnn** [comment]
Hi Michael,

I understand your comments. However, in 1.4.3, my setup was working. So are you saying that the file lookup plugin in 1.4.3 was buggy, and that you have fixed it in 1.5?
