### ISSUE TITLE
(debug module) Different behavior on same command

### ISSUE THREAD

**Issue by nizsheanez** [ansible/ansible#6307]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5
##### Environment:

OS X
##### Summary:

my 2 playbooks in one gist page:
https://gist.github.com/anonymous/0c440b979000b2f57d04

if i trying to `echo "r.p("` then debug command print array as string `"[u'r.p(']"`
if i remove **any** symbol from this string then - array as array 

```
[
    "r.p"
]
```

in case 1 and in case 2 different formatting of output
##### Steps To Reproduce:

https://gist.github.com/anonymous/0c440b979000b2f57d04
##### Expected Results:

anyway must be printed formatted array
##### Actual Results:

---

**Comment by mpdehaan** [comment]
Agree this is a bit curious.   

Should appear as an array regardless, looks like the unicode detection got a bit "special" :)

**Comment by nizsheanez** [comment]
any vision what it can be?

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
TASK [command] ******************************************************************
changed: [localhost]
TASK [debug var=response.stdout_lines] ******************************************
ok: [localhost] => {
    "changed": false, 
    "response.stdout_lines": [
        "r.p("
    ]
}
TASK [command] ******************************************************************
changed: [localhost]
TASK [debug var=response.stdout_lines] ******************************************
ok: [localhost] => {
    "changed": false, 
    "response.stdout_lines": [
        "r.p"
    ]
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
