### ISSUE TITLE
docker module ports option error

### ISSUE THREAD

**Issue by lenfree** [ansible/ansible#6327]
##### Issue Type:

Bug
##### Ansible version:

1.5
##### Environment:

*BSD
##### Summary:

can't use ports option to bind an interface with multiple ports if they both tcp or udp
e.g. 
ports="10.0.2.15:80:80, 10.0.2.15:443:443" - this doesn't work
but ports="10.0.2.15:80:80, 10.0.2.15:443:443/udp" - this works
##### Steps To Reproduce:

 docker: image="name/nginx-reverse-proxy:1.0" name="nginx"     state=present hostname="nginx" l ports="10.0.2.15:80:80, 10.0.2.15:443:443"
##### Expected Result:

should be able to bind multiple ports on the same interface such as
10.0.2.15:80->80/tcp
10.0.2.15:443->443/tcp
##### Actual result:

Error

**Comment by joshuaconner** [comment]
Hmm, I'm not able to reproduce this issue. (Here's a [gist](https://gist.github.com/joshuaconner/8bbea5b0a1cc02d5fcad) of the playbook, hosts file and Dockerfile I used, as well as the output I got from running `docker ps` on the host after the playbook had run.)

Maybe the problem is the space after the comma in the port declaration?

**Comment by lenfree** [comment]
oh there shouldn't be a space after the comma to prevent error. Thanks! :)
