### ISSUE TITLE
Ansible should raise an error if you try async flags on a non-async capable module (like copy)

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#633]
Hello,

I want to copy a large file to a server and see a progress bar during the file transfr. So I'm configuring the task to be async and poll its status, but Ansible fails with an error. How can I solve this?
- name: copy JAW.war
  action: copy src=${artifacts_dir}/JAW.war dest=${transfer_home}/JAW.war
  async: 300
  poll: 5

PLAY [copy artifacts to Integration server] ********************\* 

TASK: [copy JAW.war] ********************\* 
ok: [web-c1m1d.sys.dev]
ERROR: unexpected error: unable to determine jid

**Comment by mpdehaan** [comment]
copy (as well as template, raw, and fetch) do not  work with async.   Everything else does.  The main use is long running package installs, running involved scripts, etc.

I need to make it a clear error in a playbook that this is the case.

Short term workaround is to not use async here.

Having ansible use the shell module to execute rsync from the client might work for you.

(Updating this defect to track the root cause)

**Comment by ludovicc** [comment]
Some indication of progression would have been nice on those tasks where large volumes of data are transfered, or when the connection is slow and unreliable, but I can live without it for now. I have fully automated my deployments with Ansible, and it works well. Thanks!

**Comment by mpdehaan** [comment]
going to hold off doing this until some other async rework happens

**Comment by mpdehaan** [comment]
unable to determine jid is kind of an example of a task completing too fast

looking at things now, async can't really raise an error too well from /usr/bin/ansible due to the way things are plumbed around, what happens is that if you async a copy, what happens is the copy happens, and the only remote modules (file, called by copy) get async'd.   This is still KIND OF valid, and because of the way daisy chaining operations work and such, I'm not sure if I want to fix this.

We should probably just add an note to the docs that async does not help with copy or fetch operations.
