### ISSUE TITLE
git module assumes default port for ssh when checking hsotkeys

### ISSUE THREAD

**Issue by tsh56** [ansible/ansible#6357]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

OSX 10.9.2 -> Ubuntu 12.04
##### Summary:

I have a git server running on a non standard port. I have the appropriate entry in my known hosts file, but check_hostkey method returns False. It appears that the get fqdn method totally ignores the port number. For ssh the appropriate host entry when the port is included should be [hostname]:port. Notice that the square brackets should be included.
##### Steps To Reproduce:

Attempt to perform a clone using ssh with a remote host listing on a port other than port 22. Make sure that the port 22 fingerprint is not included in the known_hosts. There should be an entry in known hosts for the listening port for the git server.
##### Expected Results:

The clone should succeed.
##### Actual Results:

The clone fails because it checks the known host file using port 22.

**Comment by juliedavila** [comment]
This is impacting us as well

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
