### ISSUE TITLE
pip module does not allow to install packages from VCS in non-editable mode

### ISSUE THREAD

**Issue by nejko** [ansible/ansible#6360]
##### Issue Type:

bug report
##### Ansible Version:

1.6
##### Environment:

Debian 7.4
##### Summary:

If the package is to be installed using pip module, the "-e" option is automatically appended to pip by the module if the package is being installed using a VCS URL. Pip documentation does not require this for all types of VCS URLs: http://www.pip-installer.org/en/latest/reference/pip_install.html

Effectively this means, packages cannot be installed in non-editable mode using the pip module. This could be avoided if "-e" would be "optional", i.e. if it would have to be explicitely listed in extra_args.
##### Steps To Reproduce:

Using the pip module, install a python package using VCS URL that does not require -e option by pip.
##### Expected Results:

The package should be installed in non-editable mode.
##### Actual Results:

The package is installed in editable mode.

**Comment by mattsch** [comment]
I've added an option to toggle the editable flag, defaults to true so it doesn't break anything already using it.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
