### ISSUE TITLE
regexp in assemble module with remote_src=false

### ISSUE THREAD

**Issue by marcoc610** [ansible/ansible#6383]
##### Issue Type:

Bug report.
##### Ansible Version:

ansible 1.5
##### Environment:

Ubuntu 12.04
##### Summary:

The `assemble` module does not take the `regexp` option when `remote_src=false`.
The option works properly if `remote_src=true`
##### Steps To Reproduce:

This playbook does not run

``` YAML

---
- hosts:
    all
  tasks:
  - assemble:
      src=fragments/prova
      dest=/tmp/prova
      regexp='({{ ansible_hostname }}|tutti)'
      mode=644
      remote_src=False
```

If I copy all files in the `fragments/prova` directory to the remote machine and I assemble them there (i.e. adjusting the paths and with the default `remote_src=True`, and so on), the `regexp` works as expected, assembling the file properly.
##### Actual Results:

```
failed: [pgli10-nm] => {"failed": true}
msg: unsupported parameter for module: regexp
```

**Comment by marcoc610** [comment]
Same behaviour also in version 1.6.1.

**Comment by hura** [comment]
Just spent an hour on this before finding this bug. :(

**Comment by jfesler** [comment]
Ug.  I've got a patch of missing hair myself over this.

**Comment by sh-vi** [comment]
I've created a pull request: #7950.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
