### ISSUE TITLE
Tags on tasks in dependent roles aren't picked up (devel branch)

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#6439]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 devel
bug introduced in commit 73c883c1220d906686f26a0e00a5e00af120fce0
##### Environment:

Ubuntu but N/A
##### Summary:

When running a play with a specific tag that contains roles with dependencies, where said tag exists on different tasks in all those roles (main and dependent roles), only the tasks of the primary role are executed, not those from the dependencies.
##### Steps To Reproduce:

Example playbook and role set

https://gist.github.com/sergevanginderachter/9507057
##### Expected Results:

```
$ ansible-playbook play.yml -t sometag

PLAY [localhost] ************************************************************** 

TASK: [a | debug ] ************************************************************ 
ok: [localhost] => {
    "item": "", 
    "msg": "Hello world!"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[A] serge@goldorak:~/tmp/9506897$ ansible-playbook play.yml -t sometag

PLAY [localhost] ************************************************************** 

TASK: [abc | debug ] ********************************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Hello world!"
}

TASK: [ab | debug ] *********************************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Hello world!"
}

TASK: [a | debug ] ************************************************************ 
ok: [localhost] => {
    "item": "", 
    "msg": "Hello world!"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

By git bisect starting on 73c883c1220d906686f26a0e00a5e00af120fce0

```
$ ansible-playbook play.yml -t sometag

PLAY [localhost] ************************************************************** 

TASK: [a | debug ] ************************************************************ 
ok: [localhost] => {
    "item": "", 
    "msg": "Hello world!"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by drybjed** [comment]
Confirming the issue, [example playbook](https://github.com/drybjed/ansible-dependency-tags-test) with lots of output showing differences between v1.5.0 and current devel branch.

**Comment by jimi-c** [comment]
Running off of devel now:

<pre>
# ansible-playbook play.yml -t sometag
PLAY [localhost] ************************************************************** 
TASK: [ab | debug ] *********************************************************** 
ok: [127.0.0.1] => {
    "item": "", 
    "msg": "Hello world!"
}
TASK: [a | debug ] ************************************************************ 
ok: [127.0.0.1] => {
    "item": "", 
    "msg": "Hello world!"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

So it appears that something has changed, possibly due to the commit regarding roles and tags I made earlier.

I'm not quite sure if this is related to https://github.com/ansible/ansible/issues/5709, though it does seem similar in the fact that it's happening after the second level of deps now.

**Comment by srgvg** [comment]
Yes, I have seen both cases where (1) first deps didn't run, and (2) deeper deps didn't run. As there were quite some bugs at the tome, I didn't manage to exactly note on which commit this difference was.

**Comment by jimi-c** [comment]
The above patch should resolve this issue, as well as the one @drybjed noted (and #5709 to boot). Please let us know if you continue having problems with this. Thanks!

**Comment by srgvg** [comment]
I now can confirm patch works, thank you.
