### ISSUE TITLE
ssh + chroot feature

### ISSUE THREAD

**Issue by renard** [ansible/ansible#6440]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (devel 0e38f5dfdc) last updated 2014/03/12 13:44:03 (GMT +000)
##### Environment:

N/A
##### Summary:

I started to implement a mix of ssh and chroot connection (see my [cnx_chroot branch](https://github.com/renard/ansible/tree/cnx_chroot)).

This adds a `chroot_dir` argument to both play and task in order to run them in a remote chroot environment.

This allows for example to configure debootstrap on a remote host.

Example:

```
  - hosts: "all"
    chroot_dir: /srv/chroot

    tasks:
    - name: copy foo
      copy: src=/tmp/foo dest=/root/foo
```

Will copy `/tmp/foo` into `/root/foo` on remote hosts in the `/srv/chroot` environment. The task is not executed on the remote host itself, but in the `/srv/chroot` environment on the remote host.

This permits to use native ansible module in a remote chroot environment.

The `chroot_dir` precedence is:
- at the play level
- at the task level

So one task can be run in an other chroot if needed.

Please note that `chroot_dir` is only compatible with the `ssh` connection. Meanwhile a `sudo` can be done.

I would like to know if you consider this useful.

**Comment by mpdehaan** [comment]
I'm interested in this, though I'm a bit worried about the extra complications on Runner logic, and the assumptions about temp having "$HOME" in it.

So there may be some things to sort through here, which, to be honest, I'm not sure we'll have time to chase in the short term.

My suggestion would probably be to be able to see if it could be developed as part of a ssh_chrootable plugin or something, without having to modify core aspects, and check for the presence of a chroot variable in inventory, thus you could set up host aliases for each chroot.

Let's continue the discussion on the development list maybe.

**Comment by yarikoptic** [comment]
Looking at https://groups.google.com/forum/#!forum/ansible-devel  I guess discussion didn't evolve yet, so I might be right in time to drop by 1c: I  liked @mpdehaan 's "ssh_chrootable plugin ... host aliases for each chroot" idea.  Theoretically, all those chroots are virtualized hosts, so it is just a matter of specifying how to get to their environment.  In some cases it might be even beneficial  to use additional helpers, suchas schroot instead of direct chroot which could be pre-configured to handle some preparation (bind mounts. initiation of named chroot sessions, etc).  So in my case I just would like to provide administration to remote hosts, some of which might be chrooted instances.  Pretty much the same could be applied to other virtualizations.

on the other hand -- as hinted above -- chrooting is a lightweight virtualization.  So some use-cases  (start/stop named "chroots") already addressed in e.g. 'docker' module.

Disclaimer: I am a total newbie to ansible -- just getting started to use it, so please pardon if my comments are useless

**Comment by AlexRiedler** [comment]
I have still seen no discussion around this; is there a plan to make a PR for this? (also nothing as per discussion on the mailing list).

**Comment by renard** [comment]
_Ansible_ has evolved since that patch has been made. Event though the patch was not stable enough at the time. It conflict with some ssh connection types. @mpdehaan  was really fond of adding an option to the tasks.

The major kick with ssh+chroot is that you have to handle a dual connection:
- ssh to the remote host (which user? `root`/`ansible`/whatever) 
- chroot to the target repository (which user? `root`/`ansible`/whatever)

In my case _ansible_ never connects as `root`, but always as `ansible`. On the other hand, where do you put task files?
- `/root/.ansible`?
- `~ansible/.ansible`?
- `/path/to/chroot/root/.ansible`?
- `/path/to/chroot/~ansible/.ansible`?

and a ssh+chroot should do:

``` sh
ssh ansible@remote sudo chroot /path/to/chroot sudo -u -H ansible sudo the_task_to_run
```

This is very complex and actually _ansible_ handles several ssh-like types:
- paraminko
- accelerated
- native ssh

With each different sudo mechanisms.

I am not that much familiar with the under-the-hood-connection part of _ansible_ to take the best choice.

**Comment by AlexRiedler** [comment]
I wonder if it would make sense to make a "chained" connection type that takes other connection types as input; but I am not sure of the implications of this with sudo... probably would have to try the implementation and see for myself.

**Comment by renard** [comment]
This would be a good design to have chained connection type thus you would be able to mix any kind of connection.

I am not sure this is simple since ansible need first to copy module files to the very target before running them.

I guess @mpdehaan would have better thoughts about it.

**Comment by dwt** [comment]
I'm interested in this, but i'm not sure it's exactly the same.

We're setting up a server from a rescue system (because we modify the root volume) and to finish that configuration (i.e. building a new kernel image) we need to chroot into something that very closely resembles the actual system.

So our use case is:
- do some stuff
- setup chroot and chroot into it
- do more stuff

Which should all be possible from one playbook.

current workaround: we just prefix the 'do more stuff' commands with chroot /path/to/chroot.

**Comment by vladimirmartsul** [comment]
+1

**Comment by andrewhoff** [comment]
I'm interested in this as well. My use case is similar to @dwt 's.

**Comment by aucampia** [comment]
I wanted to do ssh + chroot so that I could do a `debootstrap` install (similar in many ways to a gentoo install). I ended up adding this in `/etc/ssh/sshd_config`:

```
Port 8922
Match LocalPort 8922
	ChrootDirectory /mnt/sysimage
	X11Forwarding no
```

And then creating a `chroot.myhostname` entry in `~/.ssh/config` with Port 8922.

Doing this in another way (i.e. from inside ansible) would be rather messy IMO - especially if you want to make it work with modules like `synchronize`.
