### ISSUE TITLE
Add ansible-lint to ansible-test runs

### ISSUE THREAD

**Issue by rrey** [ansible/ansible#64552]
##### SUMMARY

`ansible-lint` is not part of the tools used in the `ansible-test` execution and it feels kind of weird because it is executed by Ansible Galaxy when you submit a collection.
Galaxy will then set a quality score on the collection based on the execution of `yamlint` and `ansible-lint` as [documented here](https://galaxy.ansible.com/docs/contributing/content_scoring.html).

Having `ansible-lint` added in the tests ran by `ansible-test` would allow to use a single tool (to rule them all) in our CI and have the possible issues detected on Galaxy detected earlier.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-test

##### ADDITIONAL INFORMATION
N/A

**Comment by ssbarnea** [comment]
I totally support the idea but at the same time I am wondering if we should not generalize linting as we already have multiple linters involved on our codebase (yamllint, flake8,...). Maybe that is a call to use pre-commit tool to orchestrate the linting?

**Comment by rrey** [comment]
Now that `ansible-test` is released with ansible (since 2.9) the subject goes beyond the ansible/ansible repository :)

**Comment by webknjaz** [comment]
FYI ansible-lint rules are not something that the Core team endorses as "best practices".

**Comment by rrey** [comment]
@webknjaz what about its use on Galaxy then ?

**Comment by webknjaz** [comment]
Galaxy is not the same as Core. They needed to score things somehow.

**Comment by rrey** [comment]
I understand. My request comes after the release of `ansible-test` with ansible (through `pip`).
I guess that an option provided to `ansible-test` allowing to enable or disable `ansible-lint` would allow to satisfy everybody ?

**Comment by webknjaz** [comment]
Unlikely. `ansible-test` was originally designed to test the Core repo itself. But we cannot apply this linter here.
Also, "including" something into the dist would signal that we "support" that thing which is untrue. For various reasons, we'd need to implement support of ancient Python runtimes in ansible-lint and ensure that it runs on old Pythons that isn't going to happen unless somebody does this. And there's no resources allocated (AFAIK) to (1) actively work on ansible-lint and (2) maintain its compatibility with all sorts of weird things because packaging would imply the need to produce and support RPMs meaning another bunch of implications requiring even more extra resources because of injecting it into the deps tree.

**Comment by rrey** [comment]
As a user, I find very hard to understand that Ansible Galaxy uses ansible-lint as a quality indicator and `ansible-test` the tool bundled with Ansible (which includes linters) will not include that tool.

There is an issue here. Either `ansible-lint` is : 

- accepted in the official Ansible ecosystem (which seems to be the case since Galaxy uses it)
- not accepted and it is removed from Galaxy 
- not accepte, replaced by something else in Galaxy and shipped in `ansible-test`

**Comment by ssbarnea** [comment]
We should all remember that what rules are enabled by default or skipped is not something set in stone. Is it in our power to decide what rules make sense or not but at the same time checking no-rules is clearly much worse than checking a subset of them, those that are stable and non-debatable. 

I guess that rpm-packaging-is-hard (it is!) should not be used an excuse for not doing anything about addressing this issues.

Is rpm packaging a hard-dependency? Why we cannot use pip/virtualenv to install the linter?

**Comment by jctanner** [comment]
Hi folks,

I empathize with all the points and the confusion being brought up here. However as @webknjaz has mentioned, ansible-test has a different scope from ansible-lint and both are useful to different ends. 

A collection can potentially contain plugins AND roles, therefore a combination of ansbile-test and ansible-lint is a logical combination, but they should be dependences of a larger tool like molecule rather than of eachother.

What currently exists in the galaxy importer was an MVP that started when all galaxy understood was roles. Things are evolving there and will continue to evolve, including the addition of "ansible-test sanity" we hope.

All that being said, we have no plans or desire to make ansible-lint a depedency of ansible-test.
