### ISSUE TITLE
AIX support  user permission issues in the setup module of 1.6

### ISSUE THREAD

**Issue by litvos** [ansible/ansible#6458]
##### Ansible Version: 1.6

$ ansible --version
ansible 1.6
##### Environment:

OS RHEL 6.4, managed node AIX 6.1
##### Summary:

During collecting facts (executing setup module on AIX) as a non root user, module fails with 2 errors
##### Expected Results:

module setup should be able to collect facts without need to run as root.
$ ansible host1 -m setup  -i hosts
##### Actual Results:

setup modul fails in these 2 places:

host1 | FAILED >> {
    "cmd": "/etc/route -n get 8.8.8.8", 
    "failed": true, 
    "msg": "[Errno 13] Permission denied", 
    "rc": 13
}

host1 | FAILED >> {
    "cmd": "/usr/sbin/bootinfo -p", 
    "failed": true, 
    "msg": "[Errno 13] Permission denied", 
    "rc": 13
}

**Comment by mpdehaan** [comment]
I'm not sure this particular section of the system has had any changes with respect to 1.5.X, so may have always been a think?

I would agree the facts should be omitted in this case when we can't gather them.

Is this something you would like to work on, perhaps?

Thanks!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
