### ISSUE TITLE
github_hooks exception

### ISSUE THREAD

**Issue by ava-miket** [ansible/ansible#6459]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.0
##### Environment:

client running Ubuntu 13.10, target server running Ubuntu 12.04
##### Summary:

github_hooks throws "failed to parse" error
##### Steps To Reproduce:

github_hooks: action=create hookurl=http://{{ inventory_hostname }}:88 user={{ github_user }} oauthkey={{ github_oauth }} repo=https://github.com/{{ yii_admin_repo }}

All variables were checked using debug statements to make sure they had valid values.  Task was run with sudo_user, I have not tested this without using sudo_user.
##### Expected Results:

Expected a hook to be created in the specified GitHub repo
##### Actual Results:

fatal: [54.185.9.246] => failed to parse: 
SUDO-SUCCESS-astpyzjqbrfryzxrhuotxhrfdzgldycj
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1394648274.06-177805719541157/github_hooks", line 
1241, in <module>
    main()
  File "/tmp/ansible-tmp-1394648274.06-177805719541157/github_hooks", line 
161, in main
    (rc, out) = create(hookurl, oauthkey, repo, user)
TypeError: 'NoneType' object is not iterable

FATAL: all hosts have already failed -- aborting

**Comment by mpdehaan** [comment]
Thanks for the report, is this something you might have cycles to attack by any chance?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
