### ISSUE TITLE
Allow variables to be passed in to lookup

### ISSUE THREAD

**Issue by HelloGrayson** [ansible/ansible#6463]
Currently there is no way to pass in variables when using `lookup('template', 'mytemplate.j2')`.

For example. Given the following lookup:

```
lookup('template', 'mytemplate.j2')
```

Let's say I want to pass in a var `foo` which equals `bar` so that inside the template `{{ foo }}` outputs `{{ bar }}`

My scenario is that I'm generating user-data for cloudformation... I have 3 sets of user-data to generate from the same file, where 1 variable changes in that file for each set.

**Comment by HelloGrayson** [comment]
Or, in other words.

Create 2 registered variables from 1 template where different parameters are provided to each.

**Comment by mpdehaan** [comment]
In most cases usage of lookup('template') is an anti-pattern and folks should just use the template module.   It's there because it could be done, which is not neccessarily the greatest reason to merge something.

In the case of using the cloud formation module, you could use the standard template module to generate the cloudformation template, and then a call to cloudformation to run it.

**Comment by dw** [comment]
There is a use-case for `lookup('template', '...', variable=...)` when using the `iam_policy` module to dynamically generate a JSON policy document in combination with `with_items` to loop over an array controlling the policies being created.

We are using this to generate IAM groups that restrict resource access by project and environment. There appears to be no other functionality aside from writing a custom module that would enable this to succeed. At present, in order to effect a change of a variable in the template that generates the JSON policy document, I have to write a base template, then `{% include %}` it into subsidiary templates that set that single variable (in this case, the environment type being granted access to (staging/production/test).

Thankfully I only need 4 template files to accomplish this, but it is purely by luck that my needs are not more complex.

**Comment by kallebertell** [comment]
I have the same need when defining identical s3 bucket policies. The policy must have the bucket name in it and the only way to pass the policy is by string. I want to use the same policy.json and just vary the bucket name. Now I have to duplicate the policy file for each bucket and hard code the bucket name in each.

**Comment by prabhakar-pal** [comment]
We too are looking for the same capability where multiple variables are defined from a same template file with some parameters being different

**Comment by DenverJ** [comment]
For those that stumble on this before any official documentation, you can do this now. 

https://docs.ansible.com/ansible/2.4/playbooks_lookups.html
```
     # Since 2.4, you can pass in variables during evaluation
     - debug: msg="{{ lookup('template', './some_template.j2', template_vars=dict(x=42)) }} is evaluated with x=42"
```

**Comment by bcoca** [comment]
Or this way:
```
  - debug: msg="{{ lookup('template', './some_template.j2' }}"
    vars:
        x: 32
```
