### ISSUE TITLE
ec2_lc traceback when region parameter omitted

### ISSUE THREAD

**Issue by timperrett** [ansible/ansible#6495]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 0cea4d8a32) last updated 2014/03/14 16:43:08 (GMT +100)
##### Environment:

Developing on OSX, deploying to Cent OS
##### Summary:

When using the new ec2_lc module, given:

```
- name: aws | create launch configuration
  ec2_lc:
    name: test
    image_id: "{{ ami_id }}"
    key_name: "{{ keypair }}"
    security_groups: "{{stack_name.stdout}}"
```

The runtime explodes with:

```
raceback (most recent call last):
  File "/Users/tmperrex/.ansible/tmp/ansible-tmp-1394815558.22-194508001909237/ec2_lc", line 1481, in <module>
    main()
  File "/Users/tmperrex/.ansible/tmp/ansible-tmp-1394815558.22-194508001909237/ec2_lc", line 1477, in main
    create_launch_config(connection, module)
  File "/Users/tmperrex/.ansible/tmp/ansible-tmp-1394815558.22-194508001909237/ec2_lc", line 1436, in create_launch_config
    connection.create_launch_configuration(lc)
AttributeError: 'NoneType' object has no attribute 'create_launch_configuration'
```
##### Steps To Reproduce:
1. use the aforementioned configuration for the ec2_lc.
2. try to run, and it will explode.
##### Expected Results:

Command doesnt explode, and actually creates the launch configuration.
##### Actual Results:

As above, the module explodes with the aforementioned trace.

**Comment by timperrett** [comment]
Ok i've 'fixed' it.

The documentation says that the `region` is not required, but in my haste I had not specified it. Strikes me that region should be marked as required, or the error handler should pickup on the fact that no EC2_REGION env var is defined, and error out accordingly.

Perhaps this is just a documentation bug?

**Comment by mpdehaan** [comment]
So the "required" param is actually enforceable in code by setting required=True in the argument spec.  If it is actually required, that may solve the problem.

**Comment by willthames** [comment]
Again, #6419 should resolve this by making use of the common `ec2_argument_spec()` from module_utils/ec2.py which requires region, and then using the common `connect_to_aws` method (which then relies on `get_aws_connection_info` to ensure all the usual checks are done with the region parameter)

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
