### ISSUE TITLE
ansible 2.9.0 breaks ansible-vault aliases

### ISSUE THREAD

**Issue by mestuddtc** [ansible/ansible#65012]
##### SUMMARY

I set up an alias for ansible-vault so I didn't have to specify how to get the credentials every single time:
```
alias ansible-vault='ansible-vault --vault-id id@~/.vault-password'
```
With Fedora upgrading to ansible 2.9.0, the alias is broken, giving and error:
```
[mstudd@mstudd ansible]$ ansible-vault edit inventories/test/group_vars/all/secrets.yml 
usage: ansible-vault [-h] [--version] [-v]
                     {create,decrypt,edit,view,encrypt,encrypt_string,rekey}
                     ...
ansible-vault: error: argument action: invalid choice: 'ops@~/.vault/ops' (choose from 'create', 'decrypt', 'edit', 'view', 'encrypt', 'encrypt_string', 'rekey')
```

Downgrading to ansible 2.8.5 works as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /home/mstudd/dev/git/ansible/ansible.cfg
  configured module search path = ['/home/mstudd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_CONTROL_PATH(/home/mstudd/dev/git/ansible/ansible.cfg) = .ssh-cp-%%h-%%p-%%r
DEFAULT_HOST_LIST(/home/mstudd/dev/git/ansible/ansible.cfg) = ['/home/mstudd/dev/git/ansible/inventories/dev/hosts']
DEFAULT_ROLES_PATH(/home/mstudd/dev/git/ansible/ansible.cfg) = ['/home/mstudd/dev/git/ansible/galaxy-roles', '/home/mstudd/dev/git/ansible/roles', '/home/mstudd/dev/git']
INTERPRETER_PYTHON(/home/mstudd/dev/git/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

Fedora 31

##### STEPS TO REPRODUCE

I set up an alias for ansible-vault so I didn't have to specify how to get the credentials every single time:
```
echo 'password' > ~/.vault-password
alias ansible-vault='ansible-vault --vault-id id@~/.vault-password'
ansible-vault edit vault.yml
```

##### EXPECTED RESULTS

ansible-vault decrypts and opens file for editing.

##### ACTUAL RESULTS

```
usage: ansible-vault [-h] [--version] [-v]
                     {create,decrypt,edit,view,encrypt,encrypt_string,rekey}
                     ...
ansible-vault: error: argument action: invalid choice: 'ops@~/.vault/ops' (choose from 'create', 'decrypt', 'edit', 'view', 'encrypt', 'encrypt_string', 'rekey')
```

```paste below

```

**Comment by sivel** [comment]
Ansible 2.9 switches from using python optparse to python argparse.  The switch to `argparse` means that the argument parsing is now more strict.

As such, `ansible-vault` has no argument called `--vault-id`.  `--vault-id` is only an argument for one of the sub commands.

As such, you cannot specify `--vault-id` before the sub command, it will have to be provided after.

Instead of using an alias, you should instead define the list of vaults in an ansible.cfg file: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-vault-identity-list

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
