### ISSUE TITLE
teach test-module to support python debuggers + optparse

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#658]
See comments on  https://github.com/ansible/ansible/pull/657

**Comment by bradobro** [comment]
Refactoring to make it a bit more like bin/ansible (more functions). 

No NIH comples...just seems like it's getting bigger and needed to broken into some functions. Tried to stick with original logic and vars.

**Comment by bradobro** [comment]
HEADS UP: You probably know already, but just to make sure: Guido obsoleted optparse in Python 2.7 (much to my chagrin...it feels right-sized to me). 

Only an issue if you ever plan on porting to 3.X. Take to groups if/when we need to discuss sometime. No great solution, because getopts is much lower-level, while argparse doesn't port well to conservative distros.
