### ISSUE TITLE
Subversion module is leaving remote directory in conflict state

### ISSUE THREAD

**Issue by siboulet** [ansible/ansible#6588]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

CentOS 5.8
##### Summary:

The subversion module documentation states that with force=no option set, "module will fail if it encounters modified file".

In the current version, the module does fail, however, it leaves the remote in conflict state (which include leaving review files in the remote directory, and adding conflict markers in conflicting files).

The problem is due to conflicts not being properly handled after the "svn switch":

```
local_mods = svn.has_local_mods()
svn.switch() => **Remote repository left in conflict state**
if local_mods:
    if force:
        svn.revert()
    else:
        module.fail_json(msg="ERROR: modified files exist in the repository.")
```

On a side note, I think the default should have been force=no to prevent changes from being accidently lost. Currently the default is force=yes, which means any local changes to tracked files are lost by default.
##### Steps To Reproduce:
- Create a subversion task with force=no
- Run task
- On the remote server, change a tracked file (create a conflict)
- Re-run task, it will fail, and leave the remote server in conflict state
##### Expected Results:

Without force=yes, the module should exit in error if modified file exists and leave the remote directory unchanged (conflict free).
##### Actual Results:

Remote directory is left in conflict state.

**Comment by siboulet** [comment]
I've been using this in production for the last week. Let me know if there is anything I can do to have patch #6589 accepted upstream.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
