### ISSUE TITLE
Default variable in task name breaks task name templating

### ISSUE THREAD

**Issue by ninetythirty** [ansible/ansible#6610]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 991399edf0)
##### Environment:

Ubuntu 10.04
##### Summary:

Default variable in task name breaks task name templating
##### Steps To Reproduce:

See below.
##### Expected Results:

See below.
##### Actual Results:

See below.

Here is a very simple example that illustrates the problem. Templating in the task itself is correct in all cases, as shown by the debug messages.

```
--- # role/defaults/main.yaml
common: d-pickaxe
default: d-feather

--- # role/vars/main.yaml
common: v-overridden
var: v-sail

--- # role/tasks/main.yaml
- name: default={{ default }}
  debug: msg="Default variables in task names don't template. default={{ default }}"

- name: default={{ default }} var={{ var }}
  debug: msg="In fact, the mere existence of a default var messes up all task name templating. default={{ default }} var={{ var }}"

- name: var={{ var }}
  debug: msg="But this works fine. var={{ var }}"

- name: common={{ common }}
  debug: msg="This works fine. common={{ common }}"

- name: var={{ var }} common={{ common }}
  debug: msg="And this works fine. var={{ var }} common={{ common }}"
```

Output (uninteresting lines removed):

```
PLAY [host] *******************************************************************

TASK: [role | default={{default}}] ********************************************
    "msg": ""Default variables in task names don't template. default=d-feather"

TASK: [role | default={{default}} var={{var}}] ********************************
    "msg": "In fact, the mere existence of a default var messes up all task name templating. default=d-feather var=v-sail"

TASK: [role | var=v-sail] *****************************************************
    "msg": "But this works fine. var=v-sail"

TASK: [role | common=v-overridden] ********************************************
    "msg": "This works fine. common=v-overridden"

TASK: [role | var=v-sail common=v-overridden] *********************************
    "msg": "And this works fine. var=v-sail common=v-overridden"

PLAY RECAP ********************************************************************
host               : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by mpdehaan** [comment]
This is really "undefined variable in task makes task line not template" because the default is in inventory scope, the rest of the line can't be interpolated.

We should not expect to see the default loaded in here at all, but it may be reasonable to expect the template engine to "go as far as it can".

We can investigate if this is possible to template out as many variables as it can though this may be a Jinja2 limitation.

**Comment by hans-d** [comment]
same issue is when doing a `include: '{{ default }}.yml'`
This results in a `ERROR: file could not read: [...]/{{default}}.yml`

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above (with one added task to show the output when a variable is undefined or not yet available, as is the case with inventory variables):

<pre>
PLAY: ***************************************************************************
TASK [test : test : default=d-feather] ******************************************
ok: [localhost] => {
    "msg": "Default variables in task names don't template. default=d-feather", 
    "changed": false
}
TASK [test : test : default=d-feather var=v-sail] *******************************
ok: [localhost] => {
    "msg": "In fact, the mere existence of a default var messes up all task name templating. default=d-feather var=v-sail", 
    "changed": false
}
TASK [test : test : var=v-sail] *************************************************
ok: [localhost] => {
    "msg": "But this works fine. var=v-sail", 
    "changed": false
}
TASK [test : test : common=v-overridden] ****************************************
ok: [localhost] => {
    "msg": "This works fine. common=v-overridden", 
    "changed": false
}
TASK [test : test : var=v-sail common=v-overridden] *****************************
ok: [localhost] => {
    "msg": "And this works fine. var=v-sail common=v-overridden", 
    "changed": false
}
TASK [test : test : undefined var {{ this_does_not_exist }}] ********************
ok: [localhost] => {
    "msg": "Default variables in task names don't template. default=d-feather", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
