### ISSUE TITLE
paramiko connection setting will always connect even for action plugins that run locally

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#6611]
##### Summary:

When using paramiko connection method, ansible will always cause paramiko to create an ssh connection to the host, even for tasks that are action plugins executed locally (such as debug). This is not observed when using the ssh connection plugin.

I traced this down into the connection plugins themselves.

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/paramiko_ssh.py#L163 is called and will attempt to open the connection.

But with ssh
https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/ssh.py#L54
just creates the object but doesn't attempt a connection. That'll come later when a task is executed.

The upshot here is that it makes it very confusing on a platform like CentOS where paramiko is picked by default as the plugin when tasks that should be purely local such as debug and set_fact error out trying to connect to a fake server name (or a server name that doesn't have ansible_ssh_host set yet).
##### Steps To Reproduce:

```
ansible -i derp, all -m debug -a "msg=hi" -c paramiko
```
##### Expected Results:

```
derp | success >> {
    "msg": "hi"
}
```
##### Actual Results:

```
derp | FAILED => FAILED: [Errno 8] nodename nor servname provided, or not known
```

**Comment by mpdehaan** [comment]
Basically what is happening here is the connection is established in the runner object when it is instantiated in the loop.
Nice catch.

Some action plugins actually do use the connection instance, so it's not enough to say "don't connect in action plugins".

However, it does seem reasonable to make the connection loading lazy up until the point as it is used for a basic optimization.

This should probably be done in a way that is somewhat generic for all connection plugins.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible -i derp, all -m debug -a "msg=hi" -c paramiko
derp | SUCCESS => {
    "msg": "hi", 
    "verbose_always": true, 
    "changed": false
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
