### ISSUE TITLE
Update mysql_replication MASTER_CONNECT_RETRY variable for CHANGE MASTER TO command can only accept integer value.

### ISSUE THREAD

**Issue by jgornick** [ansible/ansible#6661]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

OS X 10.9.2 -> Ubuntu 12.04.4
##### Summary:

Similar to this commit 1d731e5c3064fe29e840c6b4afa56af415419423, but for MASTER_CONNECT_RETRY.
##### Steps To Reproduce:

Try to use the changemaster mode for mysql_replication and specify a master_connect_retry as either an integer or string.
##### Expected Results:

I would of expected either an integer or string to parse properly. I would expect the code to have safe escaping of variables.
##### Actual Results:

When an integer is specified in the YAML, there's a concatenation error. When there's a string specified in the YAML, there's a SQL error.

**Comment by mpdehaan** [comment]
"Try to use the changemaster mode for mysql_replication and specify a master_connect_timeout as either an integer or string."

Can you please paste an example of the above from your playbook execution?

Thanks!

**Comment by jgornick** [comment]
Specify master_connect_retry as integer:

```
- name: Change the master in slave to start the replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ hostvars[mysql_replication_master.host]['ansible_eth0']['ipv4']['address'] }}"
    master_log_file: "{{ repl_stat.File }}"
    master_log_pos: "{{ repl_stat.Position }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.pass }}"
    master_connect_retry: 10
  when: >
    mysql_replication_master is defined
    and mysql_replication_master is not none
# Ignore errors here because MySQL 5.6 complains about sending passwords without SSL
  ignore_errors: true
  tags:
    - mysql_replication
```

Result:

```
TASK: [mysql | Change the master in slave to start the replication] *********** 
fatal: [hostname-01] => failed to parse: SUDO-SUCCESS-jrqrprlubwrphocujsqehhtynfdibwpz
Change master
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1395846736.5-207052226429428/mysql_replication", line 1460, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1395846736.5-207052226429428/mysql_replication", line 330, in main
    chm.append("MASTER_CONNECT_RETRY='" + master_connect_retry + "'")
TypeError: cannot concatenate 'str' and 'int' objects

fatal: [hostname-02] => failed to parse: SUDO-SUCCESS-wqmttkoqaejyrlwvbmswmiibbdrptnzu
Change master
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1395846736.5-225372613215446/mysql_replication", line 1460, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1395846736.5-225372613215446/mysql_replication", line 330, in main
    chm.append("MASTER_CONNECT_RETRY='" + master_connect_retry + "'")
TypeError: cannot concatenate 'str' and 'int' objects
```

---

Specify master_connect_retry as string:

```
- name: Change the master in slave to start the replication
  mysql_replication:
    mode: changemaster
    master_host: "{{ hostvars[mysql_replication_master.host]['ansible_eth0']['ipv4']['address'] }}"
    master_log_file: "{{ repl_stat.File }}"
    master_log_pos: "{{ repl_stat.Position }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.pass }}"
    master_connect_retry: "10"
  when: >
    mysql_replication_master is defined
    and mysql_replication_master is not none
# Ignore errors here because MySQL 5.6 complains about sending passwords without SSL
  ignore_errors: true
  tags:
    - mysql_replication
```

Result:

```
TASK: [mysql | Change the master in slave to start the replication] *********** 
fatal: [hostname-02] => failed to parse: SUDO-SUCCESS-zqbojkwzyiumdcozuborikoedxvbzwfn
Change master
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-274165504626767/mysql_replication", line 1460, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-274165504626767/mysql_replication", line 351, in main
    changemaster(cursor,chm)
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-274165504626767/mysql_replication", line 164, in changemaster
    cursor.execute("CHANGE MASTER TO " + SQLPARAM)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10',MASTER_LOG_FILE='mysql-bin.000002',MASTER_LOG_POS=120' at line 1")

fatal: [hostname-01] => failed to parse: SUDO-SUCCESS-mgyddgxcdmknhcckbelcqvzymtbzyeei
Change master
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-103341533283815/mysql_replication", line 1460, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-103341533283815/mysql_replication", line 351, in main
    changemaster(cursor,chm)
  File "/home/user/.ansible/tmp/ansible-tmp-1395846971.88-103341533283815/mysql_replication", line 164, in changemaster
    cursor.execute("CHANGE MASTER TO " + SQLPARAM)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10',MASTER_LOG_FILE='mysql-bin.000002',MASTER_LOG_POS=120' at line 1")
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
