### ISSUE TITLE
mysql_replication module does not recognize 'login_port=' parameter

### ISSUE THREAD

**Issue by diclophis** [ansible/ansible#6663]
##### Issue Type:

What kind of ticket is this?  `Bug Report`
##### Ansible Version:

```
ansible 1.4.5
```
##### Environment:

```
Darwin wesson.local 12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64
Linux mavenlink.vagrant 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
##### Summary:

I was attempting to establish a master/slave pair on my vagrant host and ran into a problem where the `mysql_replication:` module does not understand `login_port=` ... I was able to work around the problem by using the `login_unix_socket=` parameter.
##### Steps To Reproduce:

Create a task with the following:

```
mysql_replication: login_port=3308 mode=stopslave
```
##### Expected Results:

The module will use the provided login_port: 3308 to communicate with the database
##### Actual Results:

```
msg: unsupported parameter for module: login_port
```

**Comment by Jmainguy** [comment]
login_port was never included in this module so this is a feature request instead of a bug report. I have opened a PR which addresses adding login_port. Thank you for reporting this @diclophis

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
