### ISSUE TITLE
Permission Denied when using 'lineinfile' to create a new file

### ISSUE THREAD

**Issue by firecat53** [ansible/ansible#6669]
##### Summary:

When using lineinfile to create a non-existant file, the playbook fails with an OSError. If the file already exists, it will complete successfully.
##### Steps To Reproduce:

Simple playbook to recreate issue:

```

---
- hosts: homeserver
  sudo: yes 
  tasks:
   - name: test
     lineinfile: create=yes
                 dest=/etc/sysctl.d/docker.conf
                 line="net.ipv4.forward = 1"
                 insertbefore=BOF 
                 state=present 
```
##### Expected Results:

New file docker.conf created in /etc/sysctl.d with one line in it.
##### Actual Results:

```
ansible $ ansible-playbook test.yml 
sudo password: 

PLAY [homeserver] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [homeserver]

TASK: [test] ****************************************************************** 
failed: [homeserver] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395721648.67-120885087558134/lineinfile", line 1524, in <module>
    main()
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395721648.67-120885087558134/lineinfile", line 357, in main
    ins_aft, ins_bef, create, backup, backrefs)
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395721648.67-120885087558134/lineinfile", line 185, in present
    os.makedirs(destpath)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/ansible'


FATAL: all hosts have already failed -- aborting
```

Thanks!
Scott

**Comment by firecat53** [comment]
Another run gave a slightly different error:

```
ansible $ ansible-playbook test.yml 
sudo password: 

PLAY [homeserver] ************************************************************* 

TASK: [test] ****************************************************************** 
failed: [homeserver] => {"failed": true, "parsed": false}
invalid output was: 
SUDO-SUCCESS-dowdemssqzjpnsoqwfrxjctpergbcrpu
Traceback (most recent call last):
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395764245.43-203517594059115/lineinfile", line 1524, in <module>
    main()
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395764245.43-203517594059115/lineinfile", line 357, in main
    ins_aft, ins_bef, create, backup, backrefs)
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395764245.43-203517594059115/lineinfile", line 267, in present
    write_changes(module, lines, dest)
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395764245.43-203517594059115/lineinfile", line 162, in write_changes
    module.atomic_move(tmpfile, dest)
  File "/var/local/ansible/.ansible/tmp/ansible-tmp-1395764245.43-203517594059115/lineinfile", line 1371, in atomic_move
    os.chown(tmp_dest.name, st.st_uid, st.st_gid)
UnboundLocalError: local variable 'st' referenced before assignment
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
