### ISSUE TITLE
Unarchive module tickling md5sum bug

### ISSUE THREAD

**Issue by mattsch** [ansible/ansible#6723]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3 
ansible 1.6 (devel 95a283ccaa) last updated 2014/03/27 13:26:07 (GMT -400)
##### Environment:

From OS X 10.9.2, to Ubuntu Precise
##### Summary:

Unarchive module fails if sudo password provided for NOPASSWD account
##### Steps To Reproduce:

Mark user account as NOPASSWD in sudoers file
Create play to be run as root that uses the unarchive module
Run ansible-playbook with --ask-sudo-pass flag
Type in anything at the prompt, doesn't have to be a valid password
##### Expected Results:

Unarchive should work
##### Actual Results:

This error:

```
msg: dest '/tmp/foobar/' must be an existing dir
```

From this command:

```
message00.local> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/ME/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'message00.local', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=vwdankwbvlqyqnvjllwpnqgxymoqvadl] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-vwdankwbvlqyqnvjllwpnqgxymoqvadl; rc=0; [ -r "/tmp/foobar/" ] || rc=2; [ -f "/tmp/foobar/" ] || rc=1; [ -d "/tmp/foobar/" ] && echo 3 && exit 0; (/usr/bin/md5sum /tmp/foobar/ 2>/dev/null) || (/sbin/md5sum -q /tmp/foobar/ 2>/dev/null) || (/usr/bin/digest -a md5 /tmp/foobar/ 2>/dev/null) || (/sbin/md5 -q /tmp/foobar/ 2>/dev/null) || (/usr/bin/md5 -n /tmp/foobar/ 2>/dev/null) || (/bin/md5 -q /tmp/foobar/ 2>/dev/null) || (/usr/bin/csum -h MD5 /tmp/foobar/ 2>/dev/null) || (/bin/csum -h MD5 /tmp/foobar/ 2>/dev/null) || (echo "${rc} /tmp/foobar/")\'"\'"\'\'']
```

Reverting the patch from #5659 "fixes" this for a Linux host.  Issue #5800 looks to be related.

**Comment by mattsch** [comment]
Test playbook:

```
---
- hosts: foo
  tasks:
    - name: test unarchive
      unarchive:
        src="files/{{ item }}"
        dest="/tmp/foobar/"
      with_items:
        - "message.tgz"
        - "shared.tgz"
```

**Comment by mattsch** [comment]
Noticed this is marked as "needs_info", could you clarify what's needed?

**Comment by yuanl** [comment]
Looks interesting. could be the same problem to #6790. I'll test it on monday.

**Comment by ethervoid** [comment]
I've been studying this problem and it seems its related with the SSH pipelining (don't judge me, i'm still newbie in this things hahaha) and sudoers with **NOPASSWD** option activated.

If you activate the debug version, you receive the following error from SSH:

```
channel 2: request exec confirm 1\r\ndebug3: mux_session_confirm: sending success reply\r\n
 callback done\r\n
 channel 2: open confirm rwindow 0 rmax 32768\r\ndebug1: mux_client_request_session: master session id: 2\r\n
 channel_input_status_confirm: type 99 id 2\r\n
 PTY allocation request accepted on channel 2\r\n
 channel 2: rcvd adjust 2097152\r\n
 channel_input_status_confirm: type 99 id 2\r\n
 exec request accepted on channel 2\r\n
 channel 2: rcvd eof\r\n
 channel 2: output open -> drain\r\n
 channel 2: obuf empty\r\n
 channel 2: close_write\r\n
 channel 2: output drain -> closed\r\ndebug1: client_input_channel_req: channel 2 rtype exit-status reply 0\r\ndebug3: mux_exit_message: channel 2: exit message, evitval 0\r\ndebug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0\r\n
 channel 2: rcvd eow\r\n
 channel 2: close_read\r\n
 channel 2: input open -> closed\r\n
 channel 2: rcvd close\r\ndebug3: channel 2: will not send data after close\r\n
 channel 2: send close\r\n
 channel 2: is dead\r\n
 channel 2: gc: notify user\r\ndebug3: mux_master_session_cleanup_cb: entering for channel 2\r\n
 channel 1: rcvd close\r\n
 channel 1: output open -> drain\r\n
 channel 1: close_read\r\n
 channel 1: input open -> closed\r\n
 channel 2: gc: user detached\r\n
 channel 2: is dead\r\n
 channel 2: garbage collecting\r\ndebug1: channel 2: free: client-session, nchannels 3\r\ndebug3: channel 2: status: The following connections are open:\r\n  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)\r\n\r\n
 channel 1: obuf empty\r\n
 channel 1: close_write\r\n
 channel 1: output drain -> closed\r\n
 channel 1: is dead (local)\r\n
 channel 1: gc: notify user\r\ndebug3: mux_master_control_cleanup_cb: entering for channel 1\r\n
 channel 1: gc: user detached\r\n
 channel 1: is dead (local)\r\n
 channel 1: garbage collecting\r\ndebug1: channel 1: free: mux-control, nchannels 2\r\ndebug3: channel 1: status: The following connections are open:\r\n\r\n
 set_control_persist_exit_time: schedule exit in 60 seconds
debug3: mux_client_read_packet: read header failed: Broken pipe\r\n
 Received exit status from master 0\r\nShared connection to 127.0.0.1 closed.\r\n', 'rc': 0}
```

IMHO, the real problem is the broken pipe error **debug3: mux_client_read_packet: read header failed: Broken pipe**

I've been doing some tests, and reading about the topic trying to solve this problem. I'm on it but tomorrow i going to be out for 2 weeks. When i come back i continue with this bug if it still persists.

**Comment by redbaron** [comment]
see exactly same behavior in our setup, simple unarchive usage breaks when ssh access is configured with password, using version 1.7.1

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by yannrouillard** [comment]
I confirm that this problem is still present with ansible 1.7.2.

**Comment by ghost** [comment]
confirmed: problem present in 1.7.2.

**Comment by iandyh** [comment]
I can confirm this bug still exists in 1.9.1.

**Comment by yeroc** [comment]
I just ran into this on one of our machines.  Does anyone have a workaround?

**Comment by yeroc** [comment]
It looks like this issue is now being tracked over at https://github.com/ansible/ansible-modules-core/issues/932.

**Comment by asimayub** [comment]
hit this problem now ansible 2.2.0.0
