### ISSUE TITLE
add su support to local connection plugin

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#6726]
##### Issue Type:

Bugreport
##### Ansible Version:

ansible 1.6 (devel 2156e87e62) last updated 2014/03/20 09:29:28 (GMT -400)
##### Environment:

OSX, CentOS6
##### Summary:

If your host uses the "local" ansible_connection method and are using the "su" method to escalate privileges, modules will error stating that they do not support su.
##### Steps To Reproduce:

```
- hosts: localhost 
  connection: local
  gather_facts: no
  tasks: 
  - command: /usr/bin/ls 
    su: true 
    su_user: jmartin
```
##### Expected Results:

command is run with su privileges
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

TASK: [command /usr/bin/ls] *************************************************** 
fatal: [127.0.0.1] => Internal Error: this module does not support running commands via su

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
I think we should at least change this to say "this connection" as it's not really the module here.

**Comment by vincentvdk** [comment]
Hi, this is still the case in 1.9.1

**Comment by bcoca** [comment]
this was never implemented for local, putting it on the list

**Comment by greg0ire** [comment]
I am trying ansible for the first time today because I thought it would be the best to provision my local machine with my development tools and setup and this is kind of a show-stopper. I'm using archlinux, which does not have `sudo` by default. What workaround do you recommend ? Here is what I can think of : 
1. Install `sudo` and use that as escalation method ?
2. Install ssh server and stop using the local connection ?
3. Run ansible as `root` ?

**Comment by keltik85** [comment]
Hi, i am using:

```
[root@localhost /]# ansible --version
ansible 1.9.4
```

and this task:

```
- name: "chkconfig shinken on"
  become: true
  become_user: shinken
  become_method: su
  service: name=shinken enabled=yes state=started
```

creates the same error:

```
TASK: [chkconfig shinken on] **************************************************
<localhost> REMOTE_MODULE service name=shinken enabled=yes state=started
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1457603667.53-50662024273755 && chmod a+rx /tmp/ansible-tmp-1457603667.53-50662024273755 && ec /tmp/ansible-tmp-1457603667.53-50662024273755']
<localhost> PUT /tmp/tmphpuh6u TO /tmp/ansible-tmp-1457603667.53-50662024273755/service
<localhost> EXEC ['/bin/sh', '-c', u'chmod a+r /tmp/ansible-tmp-1457603667.53-50662024273755/service']
fatal: [localhost] => Internal Error: this module does not support running commands via su

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/install-shinken.retry

localhost                    : ok=8    changed=0    unreachable=1    failed=0
```

where `localhost` is defined inside `/etc/ansible/hosts` like this:

`localhost ansible_connection=local ansible_become_pass=mySecretPw`

**Comment by jimi-c** [comment]
This feature was added in 2.0, as shown in the following output:

<pre>
# ansible-playbook --version
ansible-playbook 2.0.2.0 (stable-2.0 0df4bfe063) last updated 2016/04/18 12:04:17 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 38a38bbd03) last updated 2016/06/18 06:21:26 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 40acb516fd) last updated 2016/06/18 06:21:27 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
# cat 6726.yml 
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - command: whoami
  - command: whoami
    become: true
    become_user: jamesc
    become_method: su
# ansible-playbook -vv 6726.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: 6726.yml *************************************************************
1 plays in 6726.yml
PLAY [localhost] ***************************************************************
TASK [command] *****************************************************************
task path: /root/testing/6726.yml:5
changed: [localhost] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003211", "end": "2016-06-18 06:21:30.302902", "rc": 0, "start": "2016-06-18 06:21:30.299691", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
TASK [command] *****************************************************************
task path: /root/testing/6726.yml:6
changed: [localhost] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003030", "end": "2016-06-18 06:21:30.408260", "rc": 0, "start": "2016-06-18 06:21:30.405230", "stderr": "", "stdout": "jamesc", "stdout_lines": ["jamesc"], "warnings": []}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
</pre>

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
