### ISSUE TITLE
Omitting protocol in firewalld produces a stack trace

### ISSUE THREAD

**Issue by tpbrown** [ansible/ansible#6727]
##### Summary:

Omitting the protocol in the port attribute of firewalld module fails (as it should), but doesn't indicate why.
##### Steps To Reproduce:

Drop the protocol of the firewalld port attribute.

```
- name: enable Go HTTPS traffic through firewalld
  firewalld: port=8154 permanent=true state=enabled
```
##### Expected Results:

A better error message "protocol not specified."?
##### Actual Results:

You just get a stack trace and "ValueError: need more than 1 value to unpack"

```
  <127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
  <127.0.0.1> REMOTE_MODULE firewalld port=8154 permanent=true state=enabled
  <127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/tpbrown/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/tpbrown/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036 && echo $HOME/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036'"]
  <127.0.0.1> PUT /var/folders/rj/3n90sgbn3md7jy45q5qf6_mr0000gn/T/tmpDN6TBo TO /home/vagrant/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036/firewalld
  <127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/tpbrown/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/tpbrown/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=zbifnpzupzfvousdoxlqyrkbmaxslhjh] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-zbifnpzupzfvousdoxlqyrkbmaxslhjh; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036/firewalld; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036/ >/dev/null 2>&1\'"\'"\'\'']
  fatal: [default] => failed to parse: SUDO-SUCCESS-zbifnpzupzfvousdoxlqyrkbmaxslhjh
  Traceback (most recent call last):
    File "/home/vagrant/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036/firewalld", line 1558, in <module>
      main()
    File "/home/vagrant/.ansible/tmp/ansible-tmp-1395940546.54-79250404223036/firewalld", line 226, in main
      port, protocol = module.params['port'].split('/')
  ValueError: need more than 1 value to unpack


  FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by mkotsbak** [comment]
Seems this issue should be reopened as bug reports/code are moved back to this repository. Prefix with "firewalld: "
