### ISSUE TITLE
gce.py breaks when changing secrets.py

### ISSUE THREAD

**Issue by 12f-techops** [ansible/ansible#6738]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel cda90e3ff6) last updated 2014/03/27 11:34:15 (GMT -700)
##### Environment:

Fedora 20, managing gce 
##### Summary:

$ansible_source/plugins/inventory/gce.py does not handle changing of credentials/project
##### Steps To Reproduce:

Setup gce parameters:
set $GCE_INI_PATH in .bashrc to point to your gce.ini

Setup gce.ini as follows:
[gce]
libcloud_secrets=/path/to/your/secrets.py

Setup your secrets file:
GCE_PARAMS = ('service-account@developer.gserviceaccount.com', '/path/to/your/converted.pem')
GCE_KEYWORD_PARAMS = {'project': 'your-project-name'}

run gce.py --list;  If you have only used one single credential at this point, if you have set it up correctly, it should work.

Now change to another project and change your credentials as needed (secrets.py); also remember to remove the secrets.pyc file so that it can be regenerated correctly.
##### Expected Results:

json formatted list from changed permissions
##### Actual Results:

```
Traceback (most recent call last):
  File "./gce.py", line 257, in <module>
    GceInventory()
  File "./gce.py", line 101, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 157, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 542, in __init__
    self.zone_list = self.ex_list_zones()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 874, in ex_list_zones
    response = self.connection.request(request, method='GET').object
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 580, in request
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 675, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 114, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 222, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
libcloud.common.google.ResourceNotFoundError: {u'domain': u'global', u'message': u"The resource 'projects/your-second-project-name' was not found", u'reason': u'notFound'}
```

**Comment by mpdehaan** [comment]
Not sure what libcloud is up to here, is this something you might like to help explore/work on?

You might have a pyo or something lurking around.

**Comment by 12f-techops** [comment]
Will investigate this with #libcloud on freenode and report back, as it is an upstream issue potentially, will leave this here as ansible is affected, but not the root cause.

**Comment by ricardinho** [comment]
The code creates a ~/.gce_libcloud_auth file which caches permissions. Delete it and you can use a second project

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
