### ISSUE TITLE
Allow for conditional role defaults

### ISSUE THREAD

**Issue by jonhattan** [ansible/ansible#6756]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible-playbook 1.6 (devel 9870784d80) last updated 2014/03/27 21:08:48 (GMT +000)
##### Environment:

N/A
##### Summary:

Roles only allow for default variables defined in `defaults/main.yml`.

It would be nice to provide a way to include defaults conditionally.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
This is not something we're likely to implement.  You can add conditionals with include_vars, however, but cannot do so for defaults.

**Comment by jonhattan** [comment]
In case it helps to change your mind, I have a use case here:
https://github.com/sbitmedia/ansible-fail2ban/tree/master/defaults

I'd like to provide defaults set upstream by the SO.

**Comment by jonhattan** [comment]
For the record, finally I managed to implement a pattern to provide default values per OS.
https://github.com/sbitmedia/ansible-fail2ban/commit/70a6b594a3d8e6789119751f675cfd593b6f2a3e

**Comment by hachaboob** [comment]
I don't think being able to set default values per OS is required if the variable precedence was changed. I see roles as being isolated as in they maintain their own variable precedence. So any OS specific defaults can be in a role's vars folder. Then if Ansible's overall variable precedence was changed so that group_vars and host_vars could override all variables in a role that would take care of this issue. I am having this issue right now trying to implement roles with OS specific "defaults" and not being able to override them in group_vars and/or host_vars which does not make any sense to me.
