### ISSUE TITLE
Can't add machine to EC2 LB

### ISSUE THREAD

**Issue by brandonhilkert** [ansible/ansible#6783]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

Ubuntu 13.10
##### Summary:

New EC2 machines cannot be added to EC2 load balancers without producing an error.
##### Steps To Reproduce:

Attempt to add a new EC2 server to an existing LB.
##### Expected Results:

The server is added to the Load balancer.
##### Actual Results:

```
failed: [ec2-54-82-200-114.compute-1.amazonaws.com] => (item=ec2-54-196-51-24.compute-1.amazonaws.com) => {"failed": true, "item": "ec2-54-196-51-24.compute-1.amazonaws.com"} 
msg: failed to find the initial state of the load balancer 
failed: [ec2-54-82-200-114.compute-1.amazonaws.com] => (item=ec2-54-82-200-114.compute-1.amazonaws.com) => {"failed": true, "item": "ec2-54-82-200-114.compute-1.amazonaws.com"} 
msg: failed to find the initial state of the load balancer
```

**Comment by mpdehaan** [comment]
Please see this comment over here about the development branch - this seems to be a duplicate.

https://github.com/ansible/ansible/issues/6543

If you can reproduce this on the development branch, please reopen this ticket.

Thanks!

**Comment by brandonhilkert** [comment]
I haven't check on master, but assume it is it, when can we expect this to be released? 

Hopefully it'll be in a future patch...

**Comment by brandonhilkert** [comment]
@mpdehaan @jctanner Can someone speak when this (https://github.com/ansible/ansible/issues/6543) might be released?

It's been since November that I was able to add any server to a load balancer. After I put work in to help sorting it out pre-1.5, I was bummed to find it broken again in 1.5. Sort of cramps devops on EC2 with that ability.

**Comment by mpdehaan** [comment]
Sorry about this.

I should say though, If it has been since November, the first report we've had about this from anyone was the report a month ago - the above - and this ticket is only 2 weeks old.   We would have benefited from an earlier report.

As a heads up, you can also easily use newer modules with the system by dropping them into a "./library" directory alongside the playbook.

Given this is already fixed, this should be an easy solution to get you into an operable state.

**Comment by brandonhilkert** [comment]
Not true, Here's the beginning: https://github.com/ansible/ansible/issues/5076
