### ISSUE TITLE
SSL certificate verification error with datadog_event service

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#6792]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Ubuntu 12.04
##### Summary:

The `datadog_event` module fails with a certificate validation error.
##### Steps To Reproduce:

Run the following playbook:

```
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Generate Datadog event
    datadog_event: title="Test" text="" api_key={{ datadog.api_key }}
```
##### Expected Results:

An event is created in Datadog,
##### Actual Results:

```
failed: [XXXXXXXX] => {"changed": false, "failed": true}
msg: Failed to validate the SSL certificate for app.datadoghq.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
```
##### Notes:

Maybe related to #6474 and #6412.

The server at `app.datadoghq.com` uses a certificate that has the AddTrust External Root certificate as its root. That certificate is in `/etc/ssl/certs` and rerunning `update-ca-certificates` made no difference.

See also the output of `gnutls-cli`:

```
$ gnutls-cli --x509cafile /etc/ssl/certs/AddTrust_External_Root.pem app.datadoghq.com
Processed 1 CA certificate(s).
Resolving 'app.datadoghq.com'...
Connecting to '23.23.101.88:443'...
- Ephemeral Diffie-Hellman parameters
 - Using prime: 1024 bits
 - Secret key: 1015 bits
 - Peer's public key: 1023 bits
- Certificate type: X.509
 - Got a certificate list of 2 certificates.
 - Certificate[0] info:
  - subject `OU=Domain Control Validated,OU=PositiveSSL,CN=app.datadoghq.com', issuer `C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=PositiveSSL CA 2', RSA key 2048 bits, signed using RSA-SHA1, activated `2013-01-02 00:00:00 UTC', expires `2015-01-17 23:59:59 UTC', SHA-1 fingerprint `0fd8d190dd724b7407a8350da90820e295ddfc72'
 - Certificate[1] info:
  - subject `C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=PositiveSSL CA 2', issuer `C=SE,O=AddTrust AB,OU=AddTrust External TTP Network,CN=AddTrust External CA Root', RSA key 2048 bits, signed using RSA-SHA1, activated `2012-02-16 00:00:00 UTC', expires `2020-05-30 10:48:38 UTC', SHA-1 fingerprint `94807b1c788dd2fcbe19c8481ce41cfab8a4c17f'
- The hostname in the certificate matches 'app.datadoghq.com'.
- Peer's certificate is trusted
- Version: TLS1.2
- Key Exchange: DHE-RSA
- Cipher: AES-128-CBC
- MAC: SHA1
- Compression: NULL
- Handshake was completed
```

Using `strace`, it does seem like the module is reading the root certificate:

```
$ strace -f ansible-playbook XXXXXXXX.yml |& grep '/etc/ssl/certs/AddTrust_External'
[pid  4180] stat("/etc/ssl/certs/AddTrust_External_Root.pem", {st_mode=S_IFREG|0644, st_size=1521, ...}) = 0
[pid  4180] open("/etc/ssl/certs/AddTrust_External_Root.pem", O_RDONLY) = 6
```

**Comment by mpdehaan** [comment]
We can look, though workaround would be to add validate_certs=no for now.

It may be that certs are more up-to-date in newer Ubuntus and you need to do the update-ca-certs command.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
