### ISSUE TITLE
publicly_accessible flag is not available when creating an RDS database

### ISSUE THREAD

**Issue by follower** [ansible/ansible#6799]
##### Issue Type:

Feature Idea / Bug Report / Documentation Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

N/A
##### Summary:

`publicly_accessible` flag should be available when creating an RDS database.
##### Steps To Reproduce:

```
publicly_accessible: no
```
##### Expected Results:

Database would be created with no public access.
##### Actual Results:

Flag not supported so database has public access.

It's not possible to set the `publicly_accessible` flag when creating an RDS database.

It seems this flag is only supported by [`boto.rds2`](http://boto.readthedocs.org/en/latest/ref/rds2.html).

Perhaps a doc comment would be handy until this functionality is supported?

Unfortunately it doesn't seem possible to change this setting "manually" after creation (at least not through the AWS console).

**Comment by willthames** [comment]
I have added a publicly_accessible parameter as part of #8834 which provides boto.rds2. 

Probably worth testing this works as expected. There may well be tweaks needed to #8834, I've definitely improved included test coverage but don't claim that it's complete

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
