### ISSUE TITLE
connection plugin paramiko_ssh should have a scp_if_ssh flag like -c ssh does (edited)

### ISSUE THREAD

**Issue by mpetrive** [ansible/ansible#6818]
##### Environment:

Ansible OS: RHEL 6
Ansible Managed OS: VMWare vCenter Appliance
##### Summary:

When connecting to a host that supports advance SSH features and the paramiko_ssh plugin is chosen (ansible.cfg: transport=smart), the paramiko_ssh plugin assumes that SFTP is available and open on the managed host.  If SFTP is administratively disabled, the play will fail when file transfer is attempted.

The paramiko_ssh plugin should be updated to check if SFTP is available and if not fail over to SCP.
##### Steps To Reproduce:

Attempt to run a play against host that has SSH installed (OpenSSH_5.3p1, OpenSSL 1.0) but SFTP disabled
##### Expected Results:

Ansible will choose the paramiko_ssh plugin and attempted to transfer files using SFTP. 
##### Actual Results:

File transfer fails because SFTP is blocked

**Comment by mpdehaan** [comment]
Yeah it's not going to check most likely (would be slower than just trying what you want), but it would be possible to add an option like scp_if_ssh for paramiko, like it already exists for the native SSH connection type ("-c ssh")

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
