### ISSUE TITLE
Please Allow User Input to Customize Variable Assignments and Filters with the VMware Inventory Plugin

### ISSUE THREAD

**Issue by JRNC** [ansible/ansible#68289]
@Akasurde 

There are obstacles preventing folks from moving to the VMware dynamic inventory plugin from the old VMware inventory script. These obstacles include the lack of customization that was provided via options like alias_pattern, host_pattern, groupby_patterns, and host_filters that were available for the old inventory script (https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.ini).

It appears as if, at minimum line 418 (https://github.com/ansible/ansible/blob/4e8b240b8b74db2453851f12ec82c7f782289187/lib/ansible/plugins/inventory/vmware_vm_inventory.py#L418) could be modified to allow an input to be passed to the script. This would let the user choose what they wanted the host's name to be. This would be especially helpful to at least allow us to choose not to append the UUID. In many environments, we self enforce no duplicate names and don't want our UUIDs as part of the ansible host's name in the inventory.

Line 426 (https://github.com/ansible/ansible/blob/4e8b240b8b74db2453851f12ec82c7f782289187/lib/ansible/plugins/inventory/vmware_vm_inventory.py#L426) could also be modified to take input from the user and let them choose if they would rather have something like the hostname's FQDN set as the ansible_host value. This is critical for those of us that manage Windows systems in addition to Linux systems via ansible. Kerberos authentication against a WinRM https listener will not work if ansible targets the IP address.

**Comment by sivel** [comment]
Please be aware there are some changes regarding the repository organization. Since March 2, 2020, the Ansible team does not accept any new changes on the VMware modules on the core https://github.com/ansible/ansible repository.
The development continues but in the new VMware collection repository: https://github.com/ansible-collections/vmware

https://github.com/ansible-collections/vmware/issues

Links:

- https://groups.google.com/forum/#!msg/ansible-devel/6UAfogEDtG8/wMTgxBGWCgAJ
- https://github.com/ansible-collections/overview/blob/master/README.rst
