### ISSUE TITLE
Invalid boolean values in ansible.cfg are treated as "false"

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#68334]
##### SUMMARY
If any ansible.cfg value that expects a boolean is set to a value other than "true" or "yes" it is interpreted as "false", which leads to difficult to debug issues. Invalid boolean values should report an error or, at the very least, a warning.

This is especially confusing when the user attempts to use an inline comment (see #10354) - the configuration file *looks* valid to anyone who doesn't know the implementation details, but doesn't do what it seemingly should. I was about to re-open #23912 because Ansible wasn't printing a diff even though I set `always = True # some comment` in ansible.cfg.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.cfg

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /media/sf_work/lops/ansible/ansible.cfg
  configured module search path = [u'/home/evgeny/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/media/sf_work/lops/ansible/ansible.cfg) = True
DEFAULT_BECOME(/media/sf_work/lops/ansible/ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/media/sf_work/lops/ansible/ansible.cfg) = [u'/media/sf_work/lops/ansible/filter_plugins']
DEFAULT_HASH_BEHAVIOUR(/media/sf_work/lops/ansible/ansible.cfg) = merge
DEFAULT_LOG_PATH(/media/sf_work/lops/ansible/ansible.cfg) = /media/sf_work/lops/ansible/ansible.log
DEFAULT_ROLES_PATH(/media/sf_work/lops/ansible/ansible.cfg) = [u'/media/sf_work/lops/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/media/sf_work/lops/ansible/ansible.cfg) = debug
DEFAULT_TRANSPORT(/media/sf_work/lops/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/media/sf_work/lops/ansible/ansible.cfg) = /home/evgeny/.ansible/password
DIFF_ALWAYS(/media/sf_work/lops/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/media/sf_work/lops/ansible/ansible.cfg) = auto_legacy_silent
RETRY_FILES_ENABLED(/media/sf_work/lops/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/media/sf_work/lops/ansible/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```ini
[privilege_escalation]
become = truee

[diff]
always = True # Always print diff
```

##### EXPECTED RESULTS

Error (or at least warning) such as "Invalid boolean value for ansible.cfg setting 'become' in section 'privilege_escalation"

##### ACTUAL RESULTS
Ansible runs with become = false and always = false, so it does not attempt to use sudo and does not print the diff at the end.

**Comment by loop-evgeny** [comment]
Before someone says "this is just how Python/configparser works" - maybe, but Ansible can still be (fairly easily) made to work better.

**Comment by sivel** [comment]
Related: https://github.com/ansible/ansible/issues/62879

The problem here, is that while we can make python3 do this, we cannot for python2.

The only comment character that python2 allows for in inline comments is `;`

So instead of:

```
always = True # some comment
```

You would use:

```
always = True ; some comment
```

Unfortunately, the related issue I mention above, means that this doesn't work on Python3 by default, because Python3 defaults to disabling inline comments.  But work has been started in that other issue to match Python2.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by loop-evgeny** [comment]
This issue is not about inline comments specifically - that's just one likely way it can be discovered. The issue is that ANY text other than "true" or "yes" is treated as false, when this is likely not what the user intended. That's similar to treating any non-integer in a setting that expects an integer as 0, which Ansible thankfully does not do! For example if I write

`remote_port = whatport`

in ansible.cfg then Ansible fails with

> AnsibleOptionsError: Invalid type for configuration option setting: DEFAULT_REMOTE_PORT : invalid literal for int() with base 10: 'whatport'

I would expect the same behaviour for booleans. That's what this issue is about.

**Comment by sivel** [comment]
I'll re-open, and we can discuss.  This is a result of not using strict booleans, which means anything other than the following list (lowercased, and stringified) are considered to be non-True:

```
'y', 'yes', 'on', '1', 'true', 't', 1, 1.0, True
```
