### ISSUE TITLE
user groups option always triggers changed

### ISSUE THREAD

**Issue by oppianmatt** [ansible/ansible#6854]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Managing Ubuntu 12.04
##### Summary:

For the user module, if the groups option is specified, it always triggers "changed" even if the group list doesn't change.
##### Steps To Reproduce:

```
- user: name={{ jenkins_user }} groups={{ group }},{{ sudo_group }}
```
##### Expected Results:

```
TASK: [jenkins | jenkins user] ************************************************
ok: [host1.example.com]
```
##### Actual Results:

```
TASK: [jenkins | jenkins user] ************************************************
changed: [host1.example.com]
```

**Comment by muffl0n** [comment]
Does "group" contain the "usergroup"? E.g. group "testuser" for user "testuser". I experienced the same some days ago. It seems like the module does not check for the existence of the groups the right way.

**Comment by tchapi** [comment]
+1, I'm seeing the same bug in the latest release (1.5.5). The list of groups is unchanged and always the same, but the `changed` is triggered everytime

Example : I want to add the `sudo` group to user `myUser`: 

```
TASK [Add user to sudo group] ***************************************** 
changed: [REDACTED] => {"append": true, "changed": true, "comment": ",,,", "group": 27, "groups": "sudo", "home": "/home/myUser", "item": "", "move_home": false, "name": "myUser", "shell": "/bin/bash", "state": "present", "uid": 1001}
```

Thanks

**Comment by jameskyle** [comment]
I see this behavior, but _only_ if the user's GID group is added to the groups list, e.g.

```
groups=wheel,docker,admin
```

Does not trigger a change on all runs, but

```
groups=jkyle,wheel,docker,admin 
```

Will. I now do this so it doesn't trigger a change until it's resolved:

```
groups=wheel,docker,admin
append=yes
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by burner1024** [comment]
this is still there with 1.8

**Comment by raffomania** [comment]
happens for me too.

**Comment by strowi** [comment]
dto. with ansible 1.8.4

**Comment by raffomania** [comment]
In an effort to get this fixed I've reopened this issue at https://github.com/ansible/ansible-modules-core/issues/1118 as I couldn't find it in that repo. I hope that helps.

**Comment by cowboy** [comment]
FWIW, I'm seeing this on 1.9.2.

**Comment by msabramo** [comment]
I'm seeing this in 1.9.4 also.

**Comment by paulmaunders** [comment]
I see this on 1.9.4 when append is set to no

**Comment by georf** [comment]
I'm seeing this bug in ansible 2.0.1.0 also

**Comment by clement-tricart** [comment]
Hi, i can confirm that this bug is still here on **ansible 2.0.1.0** thx !

**Comment by nox-404** [comment]
I got the same changed state
:+1:  pls

**Comment by Gonzih** [comment]
I see the same issue in ansible 2.1.1.0.

**Comment by fidelperez** [comment]
I'm having the same issue on 2.1.0.0

**Comment by LeeYenhsun** [comment]
I got the same issue on ansible 2.1.2.0

**Comment by martinbarlow** [comment]
I had this issue when i put the users primary group, in the groups parameter. When i moved to group parameter, issue went away.

**Comment by girgen** [comment]
It is still there, and does not matter if I have groups at all or not. :(

**Comment by ingomueller-net** [comment]
Still broken in 2.2.1.0...

**Comment by lewer** [comment]
... and still in 2.3.1.0 ...

**Comment by sambrentnall** [comment]
still broken with version 2.3.2.0

**Comment by chjohnst** [comment]
seems to still be broken in 2.4.1 as well

**Comment by Bassinator** [comment]
I found a workoround for me. User does not report changed=true if: But you Need to know the existing Primary Group of the user, which is actually the case in my context.

```
- name: add user to newGroupName group
  user:
    name: username
    group: primaryGroupName
    groups: primaryGroupName, newGroupName 
    append: yes
```

**Comment by insideClaw** [comment]
I can confirm that it only looked like a bug - adding the append option to two tasks made it so that they're not always undoing the work of the other, and fixed the permanently changed trigger. I did not need to add "group:"
