### ISSUE TITLE
mysql connection error message

### ISSUE THREAD

**Issue by hansbaer** [ansible/ansible#6860]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4.4 (but it's also in the latest version)
##### Environment:

Ubuntu 13.10
##### Summary:

When a mysql connection database fails due to a non-standard socket file path, the error message does not hint that this could be the cause.
##### Steps To Reproduce:

Happens on any MySQL server host where the socket file is not in /var/lib/mysql/
##### Expected Results:

An error message which helps to see that this is the cause.
##### Actual Results:

The error message only names username/password solutions.

**Comment by mpdehaan** [comment]
Thanks for this ticket.

Just to be clear, when you say "latest version", did you mean 1.5.4?

Also, if you would like to submit a pull request, amending the message seems like it would be easy.  Just wanted to point that out if you felt like it. 

Thanks!

**Comment by hansbaer** [comment]
Yes, I just looked up the most recent state here in the repository to check if the message has changed since the version I used.

I have just submitted a pull request. Changing one line in each of the mysql modules will do the trick.

Thanks for your reply!

**Comment by Jmainguy** [comment]
#6865 was the PR hansbaer opened to address this issue. Currently that PR is closed as it needed to be cleaned up a little.

**Comment by Jmainguy** [comment]
PR #8542  adds explicit error message if socket does not exist, or file pointed to is not actually a socket.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
