### ISSUE TITLE
Bug Report: playbook variable with VLAN-ed interfaces

### ISSUE THREAD

**Issue by leseb** [ansible/ansible#6879]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible version: ansible 1.6 (devel 51727e81ac) last updated 2014/03/31 16:52:09 (GMT +200)
##### Environment:

nvironement:
Distributor ID: Debian
Description:    Debian GNU/Linux 7.4 (wheezy)
Release:    7.4
Codename:   wheezy
Kernel: 3.10-0.bpo.2-amd64
##### Summary:

While trying to apply a variable into a playbook it didn't work. The variable is applied from a fact.
This only happens with VLAN-ed interfaces.
##### Steps To Reproduce:

Get a VLAN on top of an interface.

The fact gathers the nic properly:

```
pouet1 | success >> {
    "ansible_facts": {
        "ansible_bond1.2108": {
            "active": true,
            "device": "bond1.2108",
            "ipv4": {
                "address": "192.168.0.1",
                "netmask": "255.255.255.0",
                "network": "192.168.0.0"
            },
            "ipv6": [
                {
                    "address": "fe80::b6b5:2fff:fe63:4e69",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "b4:b5:2f:25:6e:90",
            "mtu": 1500,
            "promisc": false,
            "type": "ether"
        }
    },
    "changed": false
}
```

However while trying to use this variable inside a playbook like this:

```
- name: tell memcached what IP to listen on
  lineinfile: dest=/etc/memcached.conf regexp="^-l" line='-l {{ ansible_bond1.2108.ipv4.address }}'
  notify: restart memcached
```
##### Expected Results:

I should get

```
-l 192.168.0.1
```
##### Actual Results:

I get the following in the memcached.conf:

```
-l {{ansible_bond1.2108.ipv4.address}}
```

**Comment by mpdehaan** [comment]
Because of the dot here you will have to access the interface name through the "hostvars" datastructure, such as

{{ hostvars[inventory_hostname]["ansible_bond1.2108"].ipv4.address }}

This is because the "." is part of a variable name when it should not be.  So I'm making this ticket about replacing "." with "_" in the interface names.

**Comment by leseb** [comment]
Thanks for the quick response Michael. Your solution works like a charm.
Thanks for the fix too.

**Comment by mpdehaan** [comment]
We can leave this one open I think -- it should be possible to replace the
"." with "_" in the code for the future.

(edit: we've done this before for other similar bits, like "-" in a fact)

**Comment by leseb** [comment]
Ok sure :)

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
