### ISSUE TITLE
docker module doesn't support volume access rights

### ISSUE THREAD

**Issue by ifraixedes** [ansible/ansible#6884]
##### Issue Type:

"Feature Idea” and “Documentation Report”
##### Ansible Version:

ansible 1.6 (devel 8d3e22ccc4) last updated 2014/04/01 17:31:20 (GMT +100)
##### Environment:

Linux Ubuntu server 13.10 x64
##### Summary:

I've realised that docker module doesn't support the access rights specification.

Although without specify them works properly mapping them as rw, it is quite confusing how to map them, so I spent some time trying to figure out why the directory wasn't mapped and the problem was when I specified the volumes as e.g. volumes="/host_machine:/tmp:rw" it was running the container with the expected mapping, basically because the module skips as container-path has been specified when the string split parts is different of 2 (https://github.com/ansible/ansible/blob/devel/library/cloud/docker#L352)
##### Steps To Reproduce:

Just run any task with `docker module` and use `volumes` property providing a string as `host_port:container_port:rw|ro`
##### Expected Results:

Map the directory between host machine and docker container as expected by using [docker run](http://docs.docker.io/en/latest/reference/commandline/cli/#run)
##### Actual Results:

Not sure, but probably the result is the same than only providing a `volumes=host_port`.

**Comment by mpdehaan** [comment]
Something you'd like to work on, perhaps?

**Comment by ifraixedes** [comment]
I may try to make the change, but I am not able in the following days. Whenever I find a gap of time I will try.

**Comment by softzilla** [comment]
Pull request: #6890

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the commit merged in via PR #7561 should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
