### ISSUE TITLE
Can't install package with wildcard version via apt

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#6885]
##### Issue Type:

Bug Report
##### Ansible Version:

admin@monitoring:~/ansible$ ansible --version
ansible 1.5 (devel 27fb0576ad) last updated 2014/02/02 23:09:41 (GMT +400)

(It looks like it is not yet fixed in HEAD also: https://github.com/ansible/ansible/blob/devel/library/packaging/apt#L233-L235)
##### Environment:

N/A
##### Summary:

When using `apt` module when you specify wildcard in version the module fails.
##### Steps To Reproduce:

Use the following lines in the cookbook:

```
- name: zabbix agent package
  apt: pkg=zabbix-agent=1:1.8.* state=present
```

Another similar use case is described here: https://groups.google.com/forum/#!topic/ansible-project/uHdB2G11VHs
##### Expected Results:

I would expect to pass the both package name and version with wildcard to apt command
##### Actual Results:

I get the error message:

```
msg: pkgname wildcard and version can not be mixed
```

**Comment by juliedavila** [comment]
It's my understanding you have to use the 'shell' module anytime you want to do any command-line tricks like wildcards, piping, etc.

you could do

shell: apt-get install zabbix-agent1.8.*

**Comment by timurb** [comment]
@nousdefions It's not the wildcard processed by shell but a wildcard processed by apt.

**Comment by bryanlarsen** [comment]
This should be tagged with 'bug', not 'feature_idea'.   Versions are useless without wildcards, since apt repositories tend to delete old versions whenever a new minor or patch level update is uploaded.   So if you pin to a specific version, your playbook will break over time.

**Comment by erichmond** [comment]
+1 this is definitely a bug, not a feature_idea.

**Comment by rikmeijer** [comment]
Any other workaround than use shell instead of apt?

Ow and definitly a bug :)

**Comment by nervo** [comment]
:+1: Definitely a (troublesome) bug :)

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
