### ISSUE TITLE
Inconsistency in Template module return value

### ISSUE THREAD

**Issue by ralovely** [ansible/ansible#6887]
Hi.

I experience a bug (or at least a very annoying inconsistency) with the template module.
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.2
##### Environment:

MacOSX 10.9.2
##### Summary:

The Template module returns a 'dest' key when changed, but a 'path' key when not changed.
##### Steps To Reproduce:
1. Create a basic template task.
2. Run the task
3. Run it a second time
##### Expected Results:

The module should return consistent dictionary keys (either `dest` or `path` each time)

> And since copy returns `path`, `path` would be a preference.
##### Actual Results:

The module returns `dest` on the first run, `path` on the subsequent ones.

Raphael.

**Comment by mpdehaan** [comment]
This is because it's using the file module being called under the covers in some cases, we can't remove any existing returns for backwards compatibility reasons, really -- at least, we need to carefully consider the implications of doing so.

That being said, this is probably reasonably minor as the user does know where they are installing the file.

**Comment by ralovely** [comment]
I register the output of template and use it in other tasks.
Makes it all dry.

One solution would be to have the template module return both path and dest.
Compatible and offers at least a degree of consistency when needed.

Thanks.
Raphael.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by chrono** [comment]
This issue is still present in ansible 1.7.2 and 1.8.1

According to [the documentation](http://docs.ansible.com/template_module.html#this-is-a-core-module), `template` is a core module, the [core repository says template is a virtual module implemented on the server side](https://github.com/ansible/ansible-modules-core/blob/devel/files/template.py#L1). So I suggest reopening the issue here.

For posterity, here is the return value of a template run.

A `template` run, with change:

```
ok: [thmdev] => {
    "uwsgi_nginx_config": {
        "changed": true,
        "checksum": "6bc7abb98c0fee65f538f0b72d1f2b9adedbe94a",
        "dest": "/etc/nginx/sites-available/uwsgi",
        "gid": 0,
        "group": "root",
        "invocation": {
            "module_args": "src=uwsgi.j2 dest=/etc/nginx/sites-available/uwsgi owner=root group=root mode=0644",
            "module_name": "template"
        },
        "md5sum": "361077cabc7ce4cdfdb56007ba5df5d7",
        "mode": "0644",
        "owner": "root",
        "size": 1422,
        "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1417734711.71-96901152562562/source",
        "state": "file",
        "uid": 0
    }
}
```

Another `template` run with no change:

```
ok: [thmdev] => {
    "uwsgi_nginx_config": {
        "changed": false,
        "gid": 0,
        "group": "root",
        "invocation": {
            "module_args": "src=uwsgi.j2 dest=/etc/nginx/sites-available/uwsgi owner=root group=root mode=0644",
            "module_name": "template"
        },
        "mode": "0644",
        "owner": "root",
        "path": "/etc/nginx/sites-available/uwsgi",
        "size": 1422,
        "state": "file",
        "uid": 0
    }
}
```

There should be a consistent way to access the destination path.

**Comment by aehlke** [comment]
@mpdehaan Should this be reopened per chrono's comment? Thanks.
