### ISSUE TITLE
Winrm module not found on Ansible 2.9.5/CentOS 8/Python 3.6

### ISSUE THREAD

**Issue by nylarahotep** [ansible/ansible#69007]
##### SUMMARY

Running under CentOS8/Python 3.6, Ansible Windows modules report unable to find the python winrm module.  I have validated that the pywinrm module is installed and working with a stand-alone python script.  I have also validate that the same Ansible version running on CentOS7/Python 2.7.6 works correctly; see 'Expected Results' below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_ping

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/apps/ansible/prod/inventory/test.yml']
```

##### OS / ENVIRONMENT

The only Python interpreter installed is the standard 3.6.8.
Pip list shows the following:
Package             Version   
------------------- ----------
ansible             2.9.5     
asn1crypto          0.24.0    
Babel               2.5.1     
bcrypt              3.1.6     
certifi             2020.4.5.1
cffi                1.14.0    
chardet             3.0.4     
configobj           5.0.6     
cryptography        2.9       
cx-Oracle           7.3.0     
dbus-python         1.2.4     
decorator           4.2.1     
gpg                 1.10.0    
idna                2.9       
Jinja2              2.10.1    
jmespath            0.9.0     
MarkupSafe          0.23      
netifaces           0.10.6    
ntlm-auth           1.4.0     
paramiko            2.4.3     
pciutils            2.3.6     
perf                0.1       
pip                 20.0.2    
ply                 3.9       
pyasn1              0.3.7     
pycparser           2.20      
pygobject           3.28.3    
PyNaCl              1.3.0     
pyOpenSSL           18.0.0    
pyparsing           2.1.10    
python-dateutil     2.6.1     
python-dmidecode    3.12.2    
python-linux-procfs 0.6       
pytz                2017.2    
pyudev              0.21.0    
pywinrm             0.4.1     
PyYAML              3.12      
requests            2.23.0    
requests-ntlm       1.1.0     
rhnlib              2.8.6     
rpm                 4.14.2    
schedutils          0.6       
selinux             2.9       
sepolicy            1.1       
setools             4.2.2     
setuptools          39.2.0    
six                 1.14.0    
slip                0.6.4     
slip.dbus           0.6.4     
syspurpose          1.25.17   
urllib3             1.25.9    
wheel               0.34.2    
xmltodict           0.12.0    

##### STEPS TO REPRODUCE

Trying to do a simple win_ping command

```yaml
ansible -m win_ping -i prod.yml -vvvv windows-host

# inventory settings
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_user: myUser
ansible_password: myPassword
ansible_winrm_transport: basic

```

##### EXPECTED RESULTS

windows-host | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

##### ACTUAL RESULTS

command FAILED

```paste below
ansible 2.9.5
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /home/ansible/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /apps/ansible/prod/inventory/prod.yml as it did not pass its verify_file() method
script declined parsing /apps/ansible/prod/inventory/prod.yml as it did not pass its verify_file() method
Parsed /apps/ansible/prod/inventory/prod.yml inventory source with yaml plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
windows-host | FAILED! => {
    "msg": "winrm or requests is not installed: No module named 'winrm'"
}

```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * The EPEL package for Ansible isn't built by us so we don't have full control over how it builds the package
   * The issue here is that the shebang of the `ansible` commands created by that package contains the argument `-s` which retricts the Python packages that can be used when Ansible is running
   * That flag stops you from using any pip installed packages so Ansible is unable to find the `pywinrm` install you have
   * I've spoken with one of the maintainers of the EPEL package and they will look into removing that argument in the next EPEL release of Ansible (2.9.7)
   * Unfortunately for now you have 3 choices
       * Install Ansible with pip and not yum
       * Manually remove the `-s` arg in the shebang on `ansible-playbook` and other ansible commands you run
       * Call Ansible with an explicit Python version, i.e. `/usr/bin/python3.6 ansible-playbook ...` to have the shebang be ignored

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
