### ISSUE TITLE
Win_updates with wsus

### ISSUE THREAD

**Issue by theoneakta** [ansible/ansible#69008]
Hi

I am having issue withe the module

My wsus reports that i have downloaded updates

One of my machine has 1 update downloaded

But when i ask ansible to update he reports none

here is my playbook

#- name: Install Updates
- hosts: updates
  serial: 1
  remote_user: ansible_admin
  tasks:

       - block:
         - name: Download
           win_updates:
             state: searched
             server_selection: managed_server
             register: update_count
             debug: var=update_count
             log_path: c:\logs\ansible\win_updates.log

       - block:
         - name: Install Updates, Security and Critical
           win_updates:
             state: installed
             server_selection: managed_server
             register: update_count
             debug: var=update_count
             log_path: c:\logs\ansible\win_updates.log
             reboot: yes
         # server_selection: windows_update
         #state: installed

i can connect or ping my hosts

Please help me understand how this works

Thanks

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * The `win_updates` module just looks up the updates that are available based on the OS settings for it, the only controllable aspect is `server_selection` where you can choose the default of letting the OS decide or force it to use the public update catalogue
   * As well as this there are a list of default categories that are used to find updates. This filters the updates further
   * If you are finding updates are not installed then you need to figure out what categories they apply to and specify them in `category_names` option, only until at least 1 category is matched will the  update be installed.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by theoneakta** [comment]
Thanks I was able to figure it out

Sorry about that

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
