### ISSUE TITLE
apt: python-apt was removed from Debian bullseye/sid

### ISSUE THREAD

**Issue by edigaryev** [ansible/ansible#69053]
This is due to Python 2 end-of-life and happened 4 days ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=937579

It seems that `python3-apt` now is the way to go, but unfortunately Ansible 2.9.7 fails when using the `apt` module because it attempts to install the `python-apt` package:

```
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
fatal: [10.0.0.50]: FAILED! => {
    "changed": false,
    "cmd": "apt-get install --no-install-recommends python-apt -y -q",
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
Package python-apt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-apt-dbg python3-apt python-apt-doc python-apt-common




STDERR:

E: Package 'python-apt' has no installation candidate



MSG:

E: Package 'python-apt' has no installation candidate
```

**Comment by edigaryev** [comment]
Found a workaround: https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#using-python-3-on-the-managed-machines-with-commands-and-playbooks

So you either set `ansible_python_interpreter=/usr/bin/python3` globally or for specific hosts like those with Debian bullseye/sid.

Also, hopefully this will be help this issue to find the "right people":

>If you find a bug running under Python 3 you can submit a bug report on Ansible’s GitHub project. Be sure to mention Python3 in the bug report so that the right people look at it.

**Comment by sivel** [comment]
The `apt` module will install `python3-apt`, but will only do so when you are using python3 on the target host.  This is mostly often done by supplying `ansible_python_interpreter=/usr/bin/python3`.

The issue here is you are using the standard fallback to `/usr/bin/python` which is typically going to be python2 on the target host.  For backwards compat, we don't automatically select python3, unless that is the only python on your host, or whether the target OS is listed in `INTERPRETER_PYTHON_DISTRO_MAP` within https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml

In the end, this process is working as expected, and this is not a bug we need to address.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by edigaryev** [comment]
>https://github.com/ansible/ansible/blob/a8a61829b81b2ec5fc9230a37c56cd45ef979fe7/lib/ansible/config/base.yml#L1476

Shouldn't `testing` be added too then?
