### ISSUE TITLE
`Please install python-apt package.` when installing a package with `sudo` privilege

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#6910]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.5.4
```
##### Environment:
- Ubuntu 13.10 on the control machine
- Debian wheezy 7.4 on the remote machine (with no `python-apt` installed)
- Default terminal, default package manager, ssh agent, ... on both machines
##### Summary:

When running a playbook as a non-privileged user, installing a package with `sudo: yes` does not install `python-apt` in the first place as it should.
##### Steps To Reproduce:

```
# The command to be run.
# Note that `python-apt` is absent from the server
# Ran with:
#       ansible-playbook site.yml -i hosts -K -vvvv
- name: Ensure nginx is installed
  apt: pkg=nginx state=present
  sudo: yes
```
##### Expected Results:

I expected that [this fix](https://github.com/resmo/ansible/commit/a10e017d6e90b5a064fb4ae142f416c4f00ea21c) would first install `python-apt` with `sudo` and then install the requested package also with `sudo`.
##### Actual Results:

Error message thrown by Ansible:

```
msg: Could not import python modules: apt, apt_pkg. Please install python-apt package.
```

A more verbose output using `-vvvv` is shown [here](http://pastebin.com/Sk3vCPRM).
##### Workaround:

Meanwhile, I have a first task taking care of `python-apt`, but my guess is that the snippet above should install `python-apt` with `sudo` when the package itself is to be installed with `sudo: yes`:

```
- name: Ensure python-apt is installed
  command: >
    apt-get install python-apt -y -q
    creates=/usr/share/doc/python-apt
  sudo: yes

- name: Ensure nginx is installed
  apt: pkg=nginx state=present
  sudo: yes
```

---

Let me know if I am unclear or if you need more information on my side.

**Comment by mpdehaan** [comment]
Problem was addressed in this commit:

https://github.com/ansible/ansible/commit/0981488df74b27beaa222e7cd1b1912a920db568

So the next release will have this self-installing again.

**Comment by astorije** [comment]
You guys are too efficient :)
Thanks!

**Comment by 3cham** [comment]
Hi, 

I ran into similar problem, the background is quite interesting and just want to share some information here.

My targeted host uses Anaconda python as system python and it does not recognize that there are python-apt package installed in /usr/lib/*. 

Using `anaconda search -t conda python-apt`, I found some mirror of the packages:

Packages:
     Name                      |  Version | Package Types   | Platforms  
     --------------------- |   ------   | ---------------    | ---------------
     anaconda-cluster/python-apt |    0.8.5 | conda           | linux-64, linux-armv7l
     conda-cluster/python-apt  |    0.8.5 | conda           | linux-64  
     pdrops/python-apt         |    0.7.8 | conda           | linux-64  
                                          : Python bindings for libapt.
Found 3 packages

So I installed python-apt via anaconda-cluster channel and can `import apt` as well as `import apt_pkg` using anaconda python. But running ansible-playbook still gives me the same error. After few hours trying to catch and analyze ansible tmp python modules I found that the error log from ansible did not point out the correct problem:

```
    if not HAS_PYTHON_APT:
        if module.check_mode:
            module.fail_json(msg="python-apt must be installed to use check mode. If run normally this module can autoinstall it")
        try:
            module.run_command('apt-get update', check_rc=True)
            module.run_command('apt-get install python-apt -y -q', check_rc=True)
            global apt, apt_pkg
            import apt
            import apt.debfile
            import apt_pkg
        except ImportError:
            module.fail_json(msg="Could not import python modules: apt, apt_pkg. Please install python-apt package.")

```

Obviously "import apt.debfile" didn't work, the reason is that anaconda python could not find the "apt_inst" module. It seems that the python-apt version from anaconda is too old. 

In the end, the only "work around"-Solution for me is to include "/usr/lib/python2.7/dist-packages" into PYTHONPATH. It is not really a nice solution because there are another packages in /usr/lib which could cause conflict but I havent figured out another solution yet.

I hope these infos could help somebody out there.
