### ISSUE TITLE
ansible-doc can't find non .py modules

### ISSUE THREAD

**Issue by ikbenale** [ansible/ansible#69109]
##### SUMMARY

I have a ruby module in my modules path that loads and executes correctly in my playbooks. However, `ansible-doc -t module my_module` outputs `[WARNING]: module my_module not found in: /Users/alejandro/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/local/lib/python3.7/site-packages/ansible/modules`

##### ISSUE TYPE
- ~Bug Report~
- Documentation Report

##### COMPONENT NAME
ansible-doc

##### ANSIBLE VERSION

```paste below
  ansible 2.9.7
  config file = None
  configured module search path = ['/Users/alejandro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

 OS X 10.15.4

##### STEPS TO REPRODUCE

- Add a non-python module to your modules path
- Run `ansible-doc -t module <module name>`

```yaml

```

##### EXPECTED RESULTS

The module documentation is displayed

##### ACTUAL RESULTS

```paste below
[WARNING]: module my_module not found in: /Users/alejandro/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/local/lib/python3.7/site-packages/ansible/modules
```

**Comment by eReGeBe** [comment]
The culprit seems to be that `find_plugin` is called with `mod_type='.py'` hardcoded here: https://github.com/ansible/ansible/blob/8c044b8/lib/ansible/cli/doc.py#L317

**Comment by sivel** [comment]
Ansible documentation can only be provided from within a `.py` file. We do not support documentation residing in any other file type.  We use the python `ast` module to parse and find the documentation, which only understands python.

In our use of powershell modules, they still require a matching `.py` file that holds the documentation.

Since `ansible-doc` is a means of displaying documentation, this limitation seems expected.

**Comment by eReGeBe** [comment]
@sivel that makes sense. I think the problem is then that the documentation for adding modules locally specifies using `ansible-doc` as a way of validating that the module is available (which is what I originally was trying to do), without making it clear this only applies to .py modules https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-a-module-locally

**Comment by bcoca** [comment]
we kind of assumed you would want to document your module for users.

**Comment by sivel** [comment]
We should probably update the documentation to describe alternate ways of determining the module can be located.
