### ISSUE TITLE
Installation Tutorial Gaps

### ISSUE THREAD

**Issue by dsoprea** [ansible/ansible#6919]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.6
##### Environment:

Ubuntu 13.10, OS X Mavericks 10.9.2
##### Summary:

It seems like the installation tutorial (http://docs.ansible.com/intro_installation.html) misses a few things:
1. There doesn't appear to be a _env-setup_ script if you install via PyPI.
2. I assumed the following statement meant that /etc/ansible/hosts should exist after env-setup, but it doesn't:
   
   "Once running the env-setup script you’ll be running from checkout and the default inventory file will be /etc/ansible/hosts"
3. When I cloned from Github and installed from OS X Mavericks, I got a missing package:
   
   ```
   ansible/bin$ ./ansible all -m ping --ask-pass
   Traceback (most recent call last):
     File "./ansible", line 25, in <module>
       from ansible.runner import Runner
   ImportError: No module named ansible.runner
   ```
4. When I install via PyPI on OS X (and not using env-setup, since it was missing) as well as when I cloned from Github on Ubuntu, the test command ("ansible all -m ping --ask-pass") worked, presumably, as I got prompted for a password. However, I don't believe it should be asking me for a password and I don't understand why it is. I can connect to _localhost_ with the SSH client using PK-based authentication. This is the output:
   
   ```
   ansible/bin$ ./ansible all -m ping --ask-pass
   SSH password: 
   127.0.0.1 | FAILED => Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host.
   ```

Advice?

**Comment by jctanner** [comment]
@dsoprea 

1) env-setup is only for running ansible from a git checkout:

http://docs.ansible.com/intro_installation.html#running-from-source

2) The hosts file is your inventory and it must be created. We can not auto-generate this during install as it would be specific to your environment:

http://docs.ansible.com/intro_inventory.html#hosts-and-groups

3) You do not have ansible's lib path in your environment. This is added by running the env-setup script in the checkout.

4) --ask-pass is telling ansible to prompt you for a password. If your hosts can be reached with a passwordless sshkey or the playbook is running in local connection mode, do not add --ask-pass

**Comment by majkinetor** [comment]
I had -k parameter but it still complains about SSH until I manually log in and confirm to ssh about this host. Any way to prevent it completely ?

<pre>vagrant@dominator:/baraba/ansible$ ansible all -i hosts_prod -k -m ping
SSH password:
baraba | FAILED => Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint
 to your known_hosts file to manage this host.
vagrant@dominator:/baraba/ansible$ ssh root@10.32.34.168
The authenticity of host '10.32.34.168 (10.32.34.168)' can't be established.
RSA key fingerprint is ff:f1:c7:d1:f0:01:1e:a5:26:e8:39:b9:4b:29:32:ba.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.32.34.168' (RSA) to the list of known hosts.
root@10.32.34.168's password:
[root@baraba ~]# exit
logout
Connection to 10.32.34.168 closed.
vagrant@dominator:/baraba/ansible$ ansible all -i hosts_prod -k -m ping
SSH password:
baraba | success >> {
    "changed": false,
    "ping": "pong"
}
</pre>

**Comment by andyewing** [comment]
I agree - the installation instructions should make it clear that

1) you need to create the hosts file
2) you need to ssh to the localhost and add the key before you can run "./ansible all -m ping --ask-pass"

**Comment by sam95** [comment]
Faced the same issue. Get's resolved just by doing this
I used a vagrant machine with ip `192.16.33.20`

```
$ssh vagrant@192.168.33.20
The authenticity of host '192.168.33.20 (192.168.33.20)' can't be established.
ECDSA key fingerprint is 11:5d:55:29:8a:77:d8:08:b4:00:9b:a3:61:93:fe:e5.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.33.20' (ECDSA) to the list of known hosts.
vagrant@192.168.33.20's password: 
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Tue Mar 22 06:56:36 2016 from 10.0.2.2
vagrant@precise64:~$
```

When asked for the password type in `vagrant`
After that ansible works great
