### ISSUE TITLE
quantum_router_interface fails to get subnet by name

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#6922]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 70c52625ac) last updated 2014/03/27 14:12:57 (GMT -500)
##### Environment:

MacOS maverics as ansible_controller.
Targeting ubuntu 12.04 openstack controller.
##### Summary:

quantum_router_interface module fails to get subnet by name
##### Steps To Reproduce:

```
     - name: Remove the network interface to the router
       quantum_router_interface: state=absent
                             auth_url="{{ os_auth_url }}"
                             login_username={{ admin_tenant_user }}
                             login_password={{ admin_pass }} login_tenant_name={{ admin_tenant }}
                             tenant_name={{ tenant.name }}
                             router_name={{ tenant.router.name }}
                             subnet_name={{ tenant.subnet.name }}
```

However, the name is correct and exists.

root@node-8:~# quantum subnet-show dc_lynx_dev2_subnet
+------------------+--------------------------------------------------+
| Field            | Value                                            |
+------------------+--------------------------------------------------+
| allocation_pools | {"start": "192.x.y.2", "end": "192.x.y.254"} |
| cidr             | 192.168.6.0/24                                   |
| dns_nameservers  | 10.1.5.2                                         |
|                  | 10.1.5.3                                         |
| enable_dhcp      | True                                             |
| gateway_ip       | 192.168.6.1                                      |
| host_routes      |                                                  |
| id               | bf4e******_551f8ea             |
| ip_version       | 4                                                |
| name             | dc_lynx_dev2_subnet                              |
| network_id       | 8db4**_**_be0f3             |
| tenant_id        | 401a**_***cd2cc5                 |
+------------------+--------------------------------------------------+
##### Expected Results:

Expected the module to accept the subnet name and get the id to delete it.
##### Actual Results:

TASK: [debug subnet] *********************************************************\* 
ok: [node-8] => {
    "item": "", 
    "msg": "dc_lynx_dev2_subnet"
}

TASK: [Remove the network interface to the router] ***************************\* 
failed: [node-8] => {"failed": true, "item": ""}
msg: failed to get the subnet id, please check the subnet name

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/Users/kbroughton/tenant_play.retry

node-8                     : ok=2    changed=0    unreachable=0    failed=1

**Comment by jimi-c** [comment]
I am unable to reproduce this, however I believe I'm hitting a newer version of Openstack since I'm getting the neutron command instead of the older quantum version (my Openstack version is 1:2013.2.2-0ubuntu1~cloud0).

What version of Openstack are you targeting?

**Comment by mpdehaan** [comment]
Any updates on this?  Thanks!

**Comment by darKoram** [comment]
I am still seeing this behavior.

Some more details:

quantum_router_interface works fine when attaching an interface to a router.  Only removing it fails.

I'm running with this in the hosts file
localhost ansible_connection=local ansible_python_interpreter=/usr/local/bin/python
[openstack_controller]
node-1
The playbook is run against the node-1

localhost (mac)
from neutronclient.neutron import client
client.API_VERSIONS

> > > {'2.0': 'neutronclient.v2_0.client.Client'}

I believe we are running grizzly with neutron on the openstack controllers. 
We use "quantum" for most cli calls instead of "nova".

root@node-1:~# python
Python 2.7.3 (default, Apr 20 2012, 22:39:59) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from neutronclient.neutron import client
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named neutronclient.neutron
> > > 
> > > from quantumclient.quantum import client

So yes, this definitely could be related to the version/client being used.
I have noticed that there is a difference in quantum/nova handling of list commnads.  It seems quantum commands list resources according to the login creds rather than the tenant_name specified.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
