### ISSUE TITLE
lldp module is not able to parse values with embeded newlines

### ISSUE THREAD

**Issue by psvo** [ansible/ansible#6935]
##### Issue Type:

Bug Report.
##### Ansible Version:

ansible 1.6 (devel 5ce6c86) last updated 2014/04/09 10:28:19 (GMT +200)
##### Environment:

Debian Wheezy (but most probably general problem).
##### Summary:

Multiline values is not parsed correctly and module fails with ValueError exception.

Problematic value - key contains CRLF newlines:

```
lldp.eth0.chassis.descr=H3C Comware Platform Software, Software Version 5.20 Release 2208
H3C S5120-52C-EI
Copyright (c) 2004-2010 Hangzhou H3C Tech. Co., Ltd. All rights reserved.
```

At least these switches are affected (has multiline description):
- HP A5120
- HP H3C 5800
- Cisco ASR 9K
##### Steps To Reproduce:

```
ansible 10.20.0.225 -i 10.20.0.225, -m lldp
```
##### Expected Results:

Module runs successfuly.
##### Actual Results:

```
10.20.0.225 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"<stdin>\", line 1174, in <module>\n  File \"<stdin>\", line 73, in main\n  File \"<stdin>\", line 58, in gather_lldp\nValueError: need more than 1 value to unpack\n", 
    "parsed": false
}
```

**Comment by psvo** [comment]
I would provide patch for this but because of issue #6930 API changes is needed for this module so it will be better to fix both issues at once.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
