### ISSUE TITLE
mount module doesn't remount a mount after opts change

### ISSUE THREAD

**Issue by IronTetsubo** [ansible/ansible#7010]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

RHEL 5/6
##### Summary:

With a NFS mount that's already mounted, after changing opts the fstab is updated, but the mount is not umounted/remounted and thus the changes aren't really applied.
##### Steps To Reproduce:

With a playbook like:
- name: Add nfs mount
   mount: name=/opt/nfs src="nfsserver:/export" fstype=nfs opts="rw,bg,hard" state=mounted
  run this playbook (to ensure the mount is added to fstab and mounted).

Add an option:
- name: Add nfs mount
   mount: name=/opt/nfs src="nfsserver:/export" fstype=nfs opts="rw,bg,hard,nointr" state=mounted

run the new playbook, and fstab is updated, but the mount itself is not changed.
##### Expected Results:

The mount is remounted to reflect the new options. If the mount is in use, it should error out accordingly.
##### Actual Results:

/etc/fstab is updated, but the mount itself isn't changed.

**Comment by Xiol** [comment]
I'd just like to add my +1 to this.

I need to go through an add noatime to all the mountpoints on 600+ VMs (long story). I'm currently doing this with:

```
- name: Remounting existing filesystems with noatime
  mount: src={{item.device}} name={{item.mount}} fstype={{item.fstype}} opts={{item.options}},noatime state=present
  with_items: ansible_mounts
  when: item.mount in ['/', '/home', '/var']
```

While this does update fstab, it doesn't remount the filesystem with the extra options. I've added some extra steps in my playbook to remount the filesystems using the fstab options (e.g. `mount -o remount /`), but it would be nice if this functionality was rolled into the mount module.

**Comment by srgvg** [comment]
AFAIK and in my experience a changed fstab should indeed trigger a remount.

I however have seen situations where a `-o remount` doesn't enable certain new options, and a hard umount/mount dance is needed. Is it possible this is the case here?

**Comment by Xiol** [comment]
Not in the case of noatime -  you can toggle that on and off with a remount (for ext\* and XFS at least).

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
