### ISSUE TITLE
[1]Umlauts not handled properly in `ansible-galaxy collection init`

### ISSUE THREAD

**Issue by fbruetting** [ansible/ansible#70157]
### SUMMARY
When I create a new collection with an umlaut in the name, `ansible-galaxy` produces a wrong name string in `galaxy.yml`.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/frank/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
Fedora 31 Silverblue

##### STEPS TO REPRODUCE
```yaml
ansible-galaxy collection init abcö
```

##### EXPECTED RESULTS
`abcö/galaxy.yml`
```
…
name: "abcö"
…
```

##### ACTUAL RESULTS
`abcö/galaxy.yml`
```
…
name: "abc\xF6"
…
```

**Comment by jborean93** [comment]
This looks to be fixed on devel/2.10+ and it's only the 2.9.* branches that still have this problem. In any case it's probably not a good idea to use non-ascii chars in the namespace/collection name as it has a few issues when being used by a Python 2.7 host. I would highly recommend you avoid using them in your name.

**Comment by Akasurde** [comment]
@jborean93 Do you think we should add a recommendation in collection init documentation regarding this?

**Comment by fbruetting** [comment]
Thanks, good to know! But as far as I know, Python 2 is not even supported anymore, so I think it’s a way worse idea to use that in the first place.


> @jborean93 Do you think we should add a recommendation in collection init documentation regarding this?

It would be nice if unicode would just work, as many people apart from native english speakers would be able to use proper names instead of escaping non-ascii letters (and up to now it works flawlessly). 😊

**Comment by jborean93** [comment]
> @jborean93 Do you think we should add a recommendation in collection init documentation regarding this?

It's probably a good idea, I don't even know what Galaxy/AH does to validate the name, I believe `ansible-galaxy collection init` does a basic regex check on `[\w_]` which works with non-ascii chars on Python 3 but breaks on Python 2.

> Thanks, good to know! But as far as I know, Python 2 is not even supported anymore, so I think it’s a way worse idea to use that in the first place, isn’t it?

It's still comes by default on RHEL 7 and other distributions and we still test it in CI. Unfortunately to us we still need to support Python 2.7 which is why it isn't recommended. Collections are heavily based on the Python loader and there are a few differences between it's logic on Python 2 compared to 3. I wouldn't be surprised if this wouldn't work in some scenarios.

> In case you want to restrict that – it would really be nice if unicode would just work, as many people apart from native english speakers would be able to use proper names instead of having to escape non-ascii letters like it’s 1982 – especially if it’s just about private collections (and up to now it works flawlessly). blush

For your private usage you are more than welcome to use whatever you want but there are no guarantees that it will work, especially when it comes to older Python versions. From my brief testing Python 3 has been mostly fine but we don't have tests to cover this scenario so I don't know if it works in all situations.

**Comment by samdoran** [comment]
Seems like this is fixed we just need to document this in order to resolve it fully.

**Comment by acozine** [comment]
Update https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#creating-a-collection-skeleton to specify that collection names follow the same rules as namespaces.
