### ISSUE TITLE
One failed host aborts playbook with serial keyword

### ISSUE THREAD

**Issue by jjneely** [ansible/ansible#7019]
##### Issue Type:

Bug Report
##### Ansible Version:

Tested with 1.4.5 and 1.5.4
##### Environment:

Ubuntu: Precise and Saucy
##### Summary:

When using the serial keyword a single failed host aborts the entire playbook with the error "FATAL: all hosts have already failed -- aborting"

Removing the serial keyword and all hosts are evaluated and a single failure does not abort the playbook run.
##### Steps To Reproduce:

Create an inventory with a "test" group with three hosts, A, B, and C.  Save the following playbook.

```
- hosts: test
  sudo: false
  connection: local
  serial: 1

  tasks:

    - name: Who am I?
      debug: msg={{ inventory_hostname }}

    - name: Test action
      command: echo 'Hello World!'

    - name: Test failure
      fail: msg="Bad host that fails"
      when: inventory_hostname == "B"

    - name: Next action
      command: echo 'Goodbye World!'
```

Run playbook
##### Expected Results:

This playbook should iterate through all three hosts, executing each action in sequence before moving on to the next host.  A failure on one host should abort any further actions on that one host and move on to the next.
##### Actual Results:

The first failure that occurs aborts the entire playbook.

Run output:

```
$ ansible-playbook -i testinv testserial.yml 

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [A]
ok: [C]
ok: [B]

TASK: [Who am I?] ************************************************************* 
ok: [C] => {
    "msg": "C"
}

TASK: [Test action] *********************************************************** 
changed: [C]

TASK: [Test failure] ********************************************************** 
skipping: [C]

TASK: [Next action] *********************************************************** 
changed: [C]

TASK: [Who am I?] ************************************************************* 
ok: [B] => {
    "msg": "B"
}

TASK: [Test action] *********************************************************** 
changed: [B]

TASK: [Test failure] ********************************************************** 
failed: [B] => {"failed": true}
msg: Bad host that fails

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/slack/testserial.retry

A                          : ok=1    changed=0    unreachable=0    failed=0   
B                          : ok=3    changed=1    unreachable=0    failed=1   
C                          : ok=4    changed=2    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
This is working as intended. When using `serial: 1`, you're telling the play to only operate on 1 host at a time. The working group failure percentage is based off of the serial count (see #4407), so when there is only 1 host in the group and it fails the failure % will always be 100%. To move past this error, you should increase the serial group size or use `ignore_errors: yes` on tasks that are not fatal to the workflow of your playbook.

If you have any further questions regarding this, please let us know. Thanks!

**Comment by bootswithdefer** [comment]
ignore_errors causes the playbook to continue executing tasks for that host, if we want to stop executing tasks for a host but continue the playbook with the next host it doesn't work.

**Comment by badnetmask** [comment]
Can this issue be reopened? I agree with @bootswithdefer comments: there should be some way to keep ansible going through the list of hosts when the playbook fails for a given one. That saves a lot of time.

**Comment by oppianmatt** [comment]
could you not just set `max_fail_percentage` to 100% ?

http://docs.ansible.com/playbooks_delegation.html#maximum-failure-percentage

**Comment by jl-montes** [comment]
Still there in ver 2.1.1.0
It would be nice to perhaps have a flag to tell Anisible to ignore_errors at the global execution/setup-level as well as the task level, that would avoid this condition.

The work-around we tried was to increase the serial count to 5 since we only had 2 machines that were  having network maintenance and not reach-able thus causing some script to fail that were running in serial=1 mode

**Comment by habeebr** [comment]
Agree, the entire playbook should not fail because of one host failing. Can serial <n> just use the default behavior Ansible has - to remove the failed host from further execution and continue with rest of hosts(or this should be optional). Could we reopen this issue?

**Comment by b3zn0gim** [comment]
I think it actually SHOULD fail as it's more secure way imo. serial: 1 is all about this considering that ansible should be idempotent.

You're iterating over hosts with your playbook one by one and for some reason it can't be applied to one of your hosts, there is definitely something wrong with your playbook if it doesn't work on one of machines.

IMO, if you want it to work the way you described you should add ignore_failure and register results of failing task, then add excessive step to check if your task fails or not and decide if you want to continue execution or skip next steps.

Try to imagine what can happen if you allow ansible to execute failing playbook.
What if your playbook failure leads to machine getting offline? What if you continue to apply the same actions to the rest of you group? You will just bring all your hosts down.

**Comment by itewk** [comment]
@jimi-c can you see everyone's above comments? I just ran into this myself and its a major pain in the butt. The scenario is creating a playbook to do an operating system level package update including system reboot on a group of hosts one at a time so that the entire cluster is not down at one time. But if one host in the cluster has an issue, then the entire rolling update is aborted, but i just want to move onto the next host and note that there is one host that didn't get patched, but if we do `ignore_errors: true` then for that one failed host it will keep trying all the tasks for that failed host, which is not what is wanted, just want to stop for that host and move onto the next

**Comment by srwiser** [comment]
Why is this issue marked as closed ?
Can't it be fixed in ansible ?

**Comment by KleinSa** [comment]
Though this is kind of old i would like to add my thoughts: i think both opinions are somewhat correct but i'm in a situation like @itewk mentioned it having OS patches stopping just because one single host fails and i cant find a nice way around it ( handling every following step with some registered variables is kind of complicated i think ). i would suggest a configurable solution so you can set, maybe on the play just like max_fail_percentage, whether max_fail_percentage should be calculated on the hosts in serial batch or with all hosts in the play. btw: even if the play shall fail if the permitted amount of hosts failing is exceeded, i dont think this shall stop the complete playbook as the other steps may be completety unrelated to the hosts used in the playbook.
