### ISSUE TITLE
Traceback handling with facts.d files when no permission on the files

### ISSUE THREAD

**Issue by jjneely** [ansible/ansible#7023]
##### Issue Type:

Bug Report.
##### Ansible Version:

ansible 1.5.4
ansible 1.4.5
##### Environment:

Ubuntu: Precise, Saucy

```
jjneely@jjneelytest:~$ ls -l /etc/ansible/facts.d/
total 4
-rw------- 1 root root 1460 Apr 16 07:44 preferences.fact
```
##### Summary:

When using the facts.d/ directory Ansible will traceback and fail a host immediately (the setup module) if it cannot read the facts.d/ files.  This restricts Ansible's use to root-level only.
##### Steps To Reproduce:

Whip up a test node, and create a fact file under /etc/ansible/facts.d/ that is readable only by root.

Next, run any ansible playbook against that host that does not SSH/Sudo to root.  Example:

```
- hosts: A
  sudo: false

  tasks:

    - name: Who am I?
      debug: msg={{ inventory_hostname }}

    - name: Test action
      command: echo 'Hello World!'
```

Run it with something similar to this.  Note the use of the `user` option.

```
$ ansible-playbook -i inventory/ec2/ testfactsd.yml --user jjneely
```
##### Expected Results:

Perhaps an error should be logged.  But this should not prevent Ansible runs as a non-root or non-privileged user.  Clearly, the facts in the protected file would not be available to the unprivileged run.
##### Actual Results:

```
$ ansible-playbook -i inventory/ec2/ testfactsd.yml --user jjneely

PLAY [A] ******************************** 

GATHERING FACTS *************************************************************** 
fatal: [A] => failed to parse: Traceback (most recent call last):
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 3456, in <module>
    main()
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 2359, in main
    data = run_setup(module)
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 2300, in run_setup
    facts = ansible_facts(module)
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 2289, in ansible_facts
    facts.update(Facts().populate())
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 151, in __init__
    self.get_local_facts()
  File "/home/jjneely/.ansible/tmp/ansible-tmp-1397660243.31-271684030993521/setup", line 208, in get_local_facts
    out = open(fn).read()
IOError: [Errno 13] Permission denied: '/etc/ansible/facts.d/preferences.fact'


TASK: [Who am I?] ************************************************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/slack/testfactsd.retry

A               : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by mpdehaan** [comment]
Discussed this and we think what we want to do is catch the error so there is no traceback when they fail, but still report the error with a "fail_json" call in the system.

For permissions I don't know -- Facts.d scripts can be worked around by making them world readable but can do the right thing based on permissions of what they have access to -- on the other hand, it's a configuration issue.

We could perhaps return the hash key for the fact with a "failed: True", "msg" and "traceback" element... though this might be noisy.  In the case of the permissions error we could leave off the traceback though, and this would not be noisy -- most of the time a facts.d would not be expected to traceback.

**Comment by jjneely** [comment]
One of our goals is to not include sensitive configuration data in our Ansible repository.  (Passwords and such.)  We fetch them via a custom lookup plugin.  We also store some sensitive hashes in `/etc/ansible.facts.d/` on the client machine which allow Ansible runs on that machine to fetch specific secrets.  (Reasoning being if you are already root on the client machine, you have the secrets installed there anyway.)  So we set those facts.d files as readable only by root.

But we still wanted to run non-privileged Ansible runs on these machines.

That is our use case and what we are looking to solve or work around appropriately.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
