### ISSUE TITLE
Git submodule update only tracks branches

### ISSUE THREAD

**Issue by bibliotechy** [ansible/ansible#7030]
##### Issue Type:

“Bug Report” /  “Feature Idea”
##### Ansible Version:

ansible 1.6 (devel a5e7492c4f) last updated 2014/04/15 21:12:13 (GMT -400)
##### Environment:

Ubuntu 12.04
##### Summary:

Git submodule update is hard coded to track branches (always adds the `--remote` flag, assuming the git version is late enough to support tracking branches.

https://github.com/ansible/ansible/blob/1c9950678a8a226020c6a1a32d6a60f942495072/library/source_control/git#L423-424

I have a use case where we definitely want to track the sha1 recorded in the superproject, not a branch or tag of the submodule. I'm willing to put in a PR on this, but wonder about the best way to add in a choice on this. A submodule_remote parameter? Something else?
##### Steps To Reproduce:

In a git repo with submodules that are tracked by commit hash stored in the superproject rather than branch or tag, run 

`git: repo=reponame dest=place/to/put/it`
##### Expected Results:

I'd expect all of my submodule repos to be checkout out on the commit stored in the the superproject.
##### Actual Results:

All of my submodule repos are be checkout out to the commit at the tip of the master branch.

If the submodules also do not use the label "master" for the master branch, it throws an error

`fatal: Needed a single revision`

`Unable to find current origin/master revision in submodule path`

**Comment by mpdehaan** [comment]
Honestly, I'm not a big user of submodules, so I don't know what module flags need to be passed to git to avoid the --remote added here. 

Would it be possible to have a track=yes/no (default yes) that can just be manually set to no in such conditions, and include that if using submodules that are not by branch or tag, be sure to pass track=no ?

That may seem easiest.

I would have trouble understanding a complexity like "submodule_remote" from git parlance.

**Comment by bibliotechy** [comment]
The git command to update submodules based on the  is the superproject sha1 (the default behavior) is:

`git submodule update`

whereas to update submodules based on branch/ tag is:

`git submodule update --remote`

So I'm not totally convinced that tracking branches should be the default behavior, but since it is already out in the wild and people are using it, I understand why it should stay the default.

I'm not sure that just  "track" conveys enough to indicate it is doing something to submodules. Maybe "track_branches"? Either way, I think a simple yes / no works well.

**Comment by wizonesolutions** [comment]
What happened here in the end? I am using https://github.com/protobox/protobox downstream and running into this. The repo I'm trying to clone, https://github.com/fillpdfservice/fillpdf-service, is choking because the submodule `sites/all/modules/fillpdf`'s default branch is called `6.x-1.x`, not `master`. So we are kind of unsure how to troubleshoot.

@patrickheeney I think this is the bug

**Comment by bibliotechy** [comment]
@wizonesolutions I implemented local workaround and let this drop since then. 

But, you've spurred me into action, so I just submitted https://github.com/ansible/ansible/pull/7877

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by frodopwns** [comment]
BUMP!

I have this same problem in Ansible 1.7.2.  Has there been a fix?
