### ISSUE TITLE
When creating a directory recursively with "file:" "owner=" only honours the last directory

### ISSUE THREAD

**Issue by aruiz** [ansible/ansible#7037]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Fedora 20
##### Summary:

When creating a directory recursively with file: and the owner= argument, ownership only changes in the last item of the created directories.
##### Steps To Reproduce:

```
  - name: Populate dir
    file: path=/home/user/foo/bar/baz owner=user
```
##### Expected Results:

/home/user/foo,   /home/user/foo/bar and /home/user/foo/bar/baz  should be owned by 'user', 
##### Actual Results:

Only /home/user/foo/bar/baz is owned by 'user'

**Comment by mpdehaan** [comment]
This is actually by design, because the directory ownership of all the intermediate directories might be very very different.

You should if creating directories this way follow up with statements to make sure you have set things as you like.

Some people may want to just set the leaf and some may want to set the intermediates

You definitely wouldn't want to set the ownership of "/" and to be properly idempotent (cough, that word again) you can't rely on the starting state because then it wouldn't be consistent if you had intermediate levels existing.

Hope this explains things -- For future questions about this, stop by the mailing list.
