### ISSUE TITLE
Document how to upgrade to ansible and/or ansible-base

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#70392]
##### SUMMARY

Related to https://github.com/ansible/ansible/issues/70348

When a user updates with pip, there's a problem wherein they can end up with an unstable installation of ansible. Document the correct steps to upgrade.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by acozine** [comment]
Most common error message would be `command not found: ansible-playbook`, because the binary executable files get wiped out.

**Comment by felixfontein** [comment]
Installing ansible-base next to ansible 2.9 (or older) essentially destroys the 2.9 installation (and vice versa, if ansible-2.9 is installed afer ansible-base). After that, uninstalling one of them destroys the remaining one.

Once ansible-2.10 is released, `pip install --upgrade ansible` when ansible-2.9 (or older) is currently installed will result in a broken installation (since pip internally installs ansible-base first and then removes ansible-2.9).

**Comment by felixfontein** [comment]
What users should (not) do:
- ansible 2.9 or older should never be installed next to ansible-base (or vice versa)
- when upgrading from ansible 2.9 (or older) to ansible 2.10 (or newer), first uninstall ansible 2.9 manually, and only then install ansible 2.10

**Comment by abadger** [comment]
For someone coming from ansible-2.9 or previous, the upgrade commands should be:
```
pip uninstall ansible
pip install --upgrade  ansible
```

To fix an install if you've already upgraded ansible, the command to fix the install is:
```
pip install --upgrade ansible --force-reinstall
```

**Comment by samccann** [comment]
Fixed by https://github.com/ansible/ansible/pull/71023
