### ISSUE TITLE
yum: failed to parse: This system is not registered with RHN.

### ISSUE THREAD

**Issue by johanfforsberg** [ansible/ansible#705]
when using the "yum" module to install a package in RHEL6, I just get this error:

fatal: [jofo-mgmt1] => failed to parse: This system is not registered with RHN.

RHN support will be disabled.

{"changed": true}

These lines are always printed by yum on the machine, unless the RHN plugin is disabled with "--disableplugin=rhnplugin", or, I guess, by registering the machine with RHN. However, the latter would probably be impractical since it's actually a disposable VM in a opennebula cluster.

**Comment by mpdehaan** [comment]
looks like yum output to stderr and needs to be captured here?

**Comment by skvidal** [comment]
okay - so I'm pretty sure this is coming from when we create the yum base object in the module. Essentially, it's being emitted from the plugin directly. If we invoke yum as a command we catch it. But by creating the object in python we suffer from whatever it spits out. Do we have anyway to duplicate stderr from the module execution and push it into json in the standard module invocation?

**Comment by mpdehaan** [comment]
Basically anything the module wants to do to mess with stdin would be fair game.   Don't think it would have to be in the AnsibleModule class.

Also that means nothing already exists like that, but sys.stdin = and dup() <whatever> I think is a pattern that exists in enough other apps where we could just follow that kind of pattern.

If we just assign it to a "stderr" variable like the command module I would be cool with that, but stderr and stdout are unfortunately merged due to various parmako/sudo stuff so the module is going to have to do that, can't do it higher up.

**Comment by skvidal** [comment]
update to the above: If we don't have any way to catch all of stderr from the invoked module then I'm going to have to redo the whole 'dump out our package list' thing to use repoquery/rpm. It's not the end of the world but it will be  bit more involved.

**Comment by mpdehaan** [comment]
RHNNNNNNNNNNNN </KHAAAAAAAAAAAAAAAAAN voice>

**Comment by mpdehaan** [comment]
This should be fixed by the most recent merge of updates to the yum module.   Let us know if you are still seeing this after a git pull.   Thanks!

**Comment by skvidal** [comment]
I've sent a PR to devel that I believe fixes this issue. please test it and let me know
