### ISSUE TITLE
Synchronize module asking for a password during playbook run

### ISSUE THREAD

**Issue by IronTetsubo** [ansible/ansible#7071]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

RHEL 5 & 6
##### Summary:

When using the synchronize module, it prompts for a password, then fails to synchronize.
##### Steps To Reproduce:

https://gist.github.com/IronTetsubo/11071900 - this includes the playbook, the command used to execute, and the -vvvv output of the run.
##### Expected Results:

Synchronize/Rsync works using the password supplied when running the playbook.
##### Actual Results:

see https://gist.github.com/IronTetsubo/11071900 - rsync attempts to ask for the password via stdout, then fails when it doesn't get it.

From my cursory understanding of the synchronize code/rsync command, this seems to be because synchronize assumes you're using public key authentication, and doesn't support password auth. if this is true (and intended, for whatever reason), it'd be nice to note that in the module docs. From the rsync man page:

```
       Some  modules  on the remote daemon may require authentication. If so, you will receive a password prompt when you connect. You can avoid the password prompt by setting the environment variable RSYNC_PASSWORD to the password
       you want to use or using the --password-file option. This may be useful when scripting rsync.
```

This might be a dup of Issue #5934.

**Comment by mpdehaan** [comment]
Seems like more password related.  We could technically set RSYNC_PASSWORD but that seems to be a bad idea.   May require doc update.  In queue for some more investigation.  (We would be able to raise an error in this situation that explained this).

Thanks!!!

**Comment by leth** [comment]
How about using `sshpass` for this, in the same way that the ssh connection stuff does?

**Comment by YAmikep** [comment]
I have a similar problem. (ansible-playbook v1.6.5)
The `synchronize` module prompts for the passphrase (Enter passphrase for key) even though I already entered it at the beginning of running the playbook
I run my playbook with the following options:

```
-u myuser --ask-sudo-pass --private-key=/path/to/id_rsa
```

Here is my synchronize task:

```
- name: synchronize source files in src location
  sudo: yes
  synchronize: src={{local_src}} dest={{project_dirs.src}} archive=yes delete=yes rsync_opts=["--compress"]
  when: synchronize_src_files
```

**Comment by PriceChild** [comment]
@YAmikep Are you really specifying `--private-key=/path/to/id_rsa` or something like `--private-key=relative/path/to/id_rsa`

The former works, the latter doesn't. I'm pondering filing a bug on it...

**Comment by YAmikep** [comment]
@PriceChild  yes i use an absolute path, i know that using a relative path does not work at all.
The proof that my key and passphrase work is that the playbook is run and none of the task has an issue until it gets to the synchronize one which asks again for a passphrase.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by majkinetor** [comment]
I have the same issue, and it looks like other people have it too:

[Ansible prompts password when using synchronize](http://stackoverflow.com/questions/24504430/ansible-prompts-password-when-using-synchronize)

[Ansible synchronize prompts passphrase even if already entered at the beginning](http://stackoverflow.com/questions/24763343/ansible-synchronize-prompts-passphrase-even-if-already-entered-at-the-beginning)

[Synchronize module asks password](https://groups.google.com/forum/#!msg/Ansible-project/EJh6Q56iNqk/bduV2cnAC1IJ)

**Comment by seanburlington** [comment]
http://docs.ansible.com/synchronize_module.html

set_remote_user
put user@ for the remote paths. If you have a custom ssh config to define the remote user for a host that does not match the inventory user, you should set this parameter to "no".

I have a remote user configured in my ssh config and needed to add `set_remote_user=no` to get synchronize to work, otherwise it tried to use the wrong username and neither ssh key nor password would work.

**Comment by messiahUA** [comment]
ansible 2.0.0 (devel 061b83cd74)
I'm using ssh-agent and it still asks for password. I've tried to manually execute exact same command, which ansible outputs in failed log, and it works! All arguments seems to be correct:

 rsync --delay-updates -F --compress --archive--rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path="sudo rsync" --out-format='<<CHANGED>>%i %n%L' "/dir" "user@server:~/dir"

why it asks for password?
