### ISSUE TITLE
New changelog categories missing from documentation

### ISSUE THREAD

**Issue by samdoran** [ansible/ansible#70923]
##### SUMMARY

Two new changelog categories, `breaking_changes`, and `security_fixes`, were added in #69968 but were not added to the [changelog fragment documentation](https://github.com/ansible/ansible/blob/4cc4cebc97ab1b9c5f0c424238d5352274b5dbad/docs/docsite/rst/community/development_process.rst#creating-a-changelog-fragment).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

`changelogs/config.yaml`
##### ANSIBLE VERSION

```paste below
2.11
```

##### CONFIGURATION

```paste below
default
```

##### OS / ENVIRONMENT

macOS 10.15.6
##### ADDITIONAL INFORMATION

Do we need to backport #69968 so we can backport security fixes to those branches and have the changelog build successfully?

**Comment by samdoran** [comment]
cc @felixfontein

**Comment by mattclay** [comment]
Since security fixes will be backported to stable branches, the config change should be backported so fragments with the new categories will be accepted. The docs should also be updated for the changelog fragments and backported as well.

If there are any existing changelog fragments in devel that are being changed, and they have already been backported, then those updates should be backported too.

@acozine Since you opened the original PR to apply the changes to devel, can you take care of making sure the necessary docs updates and backports are opened?

**Comment by felixfontein** [comment]
I think we had a PR planned for also updating the changelog docs, but it apparently got lost...

**Comment by acozine** [comment]
Related to #69968.

**Comment by acozine** [comment]
Related to #71071.

**Comment by acozine** [comment]
Related to #71072.
