### ISSUE TITLE
Error in documentation - assert module example

### ISSUE THREAD

**Issue by Seethaar** [ansible/ansible#71003]
##### SUMMARY

I tried "Edit on GitHub" link, but got a 404 error returned.

https://docs.ansible.com/ansible/latest/modules/assert_module.html#examples.. 
```
- assert:
    that:
      - "'foo' in some_command_result.stdout"
```
This is incorrect.
```
- assert:
    that:
      - "'foo' in some_command_result.stdout[0]"
```
This works!

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```
    - name: Push configs to ios
      napalm_install_config:
        config_file: '/home/aramanan/real/s/config.txt'

```

##### CONFIGURATION

```
ACTION_WARNINGS(/home/aramanan/.ansible.cfg) = False
AGNOSTIC_BECOME_PROMPT(default) = True
ALLOW_WORLD_READABLE_TMPFILES(default) = False
ANSIBLE_CONNECTION_PATH(default) = None
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_COW_WHITELIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', 'hellokitty', 'kitty', 'luke-koala', 'meow', 'milk', 'moofasa
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANSIBLE_SSH_ARGS(default) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(default) = None
ANSIBLE_SSH_CONTROL_PATH_DIR(default) = ~/.ansible/cp
ANSIBLE_SSH_EXECUTABLE(default) = ssh
ANSIBLE_SSH_RETRIES(default) = 0
```

##### OS / ENVIRONMENT

$ uname -a
Linux anslab9a 4.14.186-110.268.amzn1.x86_64 #1 SMP Tue Jul 14 02:57:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
##### ADDITIONAL INFORMATION

-

**Comment by sivel** [comment]
This is not an error in the documentation, but a module caveat in how networking modules operate.

The examples are based off of the assumption of using the `shell` or `command` modules, and not `napalm_install_config`.

Networking modules can often perform multiple commands in a single invocation, and as such they store their actual stdout as a list, where each element of the list is the stdout from an individual command.

Perhaps we could add an example `command` task so that it doesn't cause as much confusion.

However, in the end, this is still going to require that you understand the data that you are validating, and not blindly following examples.

**Comment by Seethaar** [comment]
Thanks. I did not realise networking modules' specific caveat. I tried some playbooks with command and shell module and could now understand what you said.

You may wanna add a comment to https://docs.ansible.com/ansible/latest/modules/assert_module.html#notes.. but its totally up to you.

Thanks for your time.
