### ISSUE TITLE
ansible-vault erases file if you get the password wrong

### ISSUE THREAD

**Issue by calpaterson** [ansible/ansible#7101]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.5.5`
##### Environment:

Ubuntu 13.10
##### Summary:

If you get the password wrong, ansible-vault will wipe your vault file.
##### Steps To Reproduce:
- Create a file with some content
- Encrypt that file with ansible vault
- Decrypt that file, but get the password wrong
##### Expected Results:

Vault file is unchanged
##### Actual Results:

Vault file is now a zero length file

```
cal@church ~/vault-file-deletion> ansible --version
ansible 1.5.5
cal@church ~/vault-file-deletion> echo "hello world" > helloworld
cal@church ~/vault-file-deletion> ls -la
total 20
drwxr-xr-x   2 cal cal  4096 Apr 21 19:27 ./
drwxr-xr-x 127 cal cal 12288 Apr 21 19:26 ../
-rw-r--r--   1 cal cal    12 Apr 21 19:27 helloworld
cal@church ~/vault-file-deletion> ansible-vault encrypt helloworld
Vault password: 
Confirm Vault password: 
Encryption successful
cal@church ~/vault-file-deletion> ls -la
total 20
drwxr-xr-x   2 cal cal  4096 Apr 21 19:27 ./
drwxr-xr-x 127 cal cal 12288 Apr 21 19:26 ../
-rw-r--r--   1 cal cal   355 Apr 21 19:27 helloworld
cal@church ~/vault-file-deletion> ansible-vault --debug decrypt helloworld
Vault password: 

Traceback (most recent call last):
  File "/usr/local/bin/ansible-vault", line 211, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-vault", line 142, in execute_decrypt
    this_editor.decrypt_file()
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 214, in decrypt_file
    self.write_data(dec_data, self.filename)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 301, in write_data
    f.write(data)
TypeError: must be string or buffer, not None

ERROR: must be string or buffer, not None
cal@church ~/vault-file-deletion> ls -la
total 16
drwxr-xr-x   2 cal cal  4096 Apr 21 19:27 ./
drwxr-xr-x 127 cal cal 12288 Apr 21 19:26 ../
-rw-r--r--   1 cal cal     0 Apr 21 19:27 helloworld
```

**Comment by calpaterson** [comment]
Whoops, didn't see the template, have now fixed my report

**Comment by mpdehaan** [comment]
I would have expected more villagers with pitchforks here, this _may_ be down a corner-case path, it certainly wasn't when I initially validated it.

Still, completely unacceptable for our standard.   We'll investigate this ASAP.

cc @jimi-c

**Comment by jimi-c** [comment]
Odd, this only happens when using the --debug option. If you leave that off, nothing bad happens:

<pre>
# ansible-vault decrypt helloworld 
Vault password: 
ERROR: Decryption failed
</pre>

But with --debug and a bad password:

<pre>
$ ansible-vault --debug decrypt helloworld 
Vault password: 
Traceback (most recent call last):
  File "/data/devel/ansible/bin/ansible-vault", line 207, in main
    fn(args, options, parser)
  File "/data/devel/ansible/bin/ansible-vault", line 141, in execute_decrypt
    this_editor.decrypt_file()
  File "/data/devel/ansible/lib/ansible/utils/vault.py", line 214, in decrypt_file
    dec_data = this_vault.decrypt(tmpdata)
  File "/data/devel/ansible/lib/ansible/utils/vault.py", line 127, in decrypt
    raise errors.AnsibleError("Decryption failed")
AnsibleError: Decryption failed
ERROR: Decryption failed
</pre>

Even after this, the encrypted file remained, which seems to be shown in the final `ls -la` of your output above @calpaterson? 

<pre>
ERROR: Decryption failed
$ cat helloworld 
$ANSIBLE_VAULT;1.1;AES256
36356636626664623635316337663133346234396266646630343864333039373761646430653238
3731376532363239663565393331346534643839646163330a643761363562366236313561653164
36386265303030323764646665616164626561376230623731373163366261373763313836323033
6364643565623936390a353163326439636634366465333561346333633566396231633536306661
3437
$ ansible-vault --debug decrypt helloworld 
Vault password: 
Decryption successful
$ cat helloworld 
hello world
</pre>

**Comment by calpaterson** [comment]
The file still remains after giving the wrong password, but it's now empty.  That's why it's size is 0 bytes in the output of `ls -la`

This happens for me, even when I do not use `--debug`

**Comment by calpaterson** [comment]
Can't replicate this with https://github.com/ansible/ansible/commit/c115c34a1f5d570422b2560cc3ff0ce0ebe53dff

**Comment by calpaterson** [comment]
Looks like you already fixed this in https://github.com/ansible/ansible/commit/b8f627d1d543eb3acb181e0ff7c7a50bc6717402

**Comment by jimi-c** [comment]
@calpaterson ahh ok, I missed in the output that it was 0 len, but yes it appears we've fixed this in devel.

**Comment by jimi-c** [comment]
Oh, and after looking at the code, it appears that the traceback is intentional when --debug is used, I was unaware it was written that way.

**Comment by calpaterson** [comment]
Ok, I'm closing then, thanks
