### ISSUE TITLE
vault-encrypted variables file in excluded playbook forces password to be entered

### ISSUE THREAD

**Issue by toddwells** [ansible/ansible#7118]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel b0d22b76bd) last updated 2014/03/13 10:06:30 (GMT -700)
##### Environment:

OSX 10.9.2
Ubuntu 12.04
##### Summary:

vault-encrypted variables file in excluded playbook forces password to be entered
##### Steps To Reproduce:

Create a playbook with a role and in roles/xxx/vars directory create an vault encrypted main.yaml
OR
Create a playbook and using vars_files include an encrypted variable file

Include this playbook in the site.yaml file with a when condition on the include ( when: dosecret is defined ) 

run 'ansible-playbook site.yaml' without the when condition ( so the included role is not run ) 
##### Expected Results:

playbook will run
##### Actual Results:

playbook does not run.  Error is:
ERROR: A vault password must be specified to decrypt data

**Comment by felipou** [comment]
I just had a similar issue. I created a script that doesn't use the inventory at all. It uses a command-line supplied variable to specify the host to execute on.

It worked fine in version 1.6.2, but now I just tested it with version 1.7.2 and it failed with the vault password error: "ERROR: A vault password must be specified to decrypt data".

I ran it with the vault password specified (using "--ask-vault-pass") and it worked, but I didn't use any host in the inventory, so it shouldn't need to read any file in the vault.

I'm guessing my issue is somehow related to this one. I haven't had time to look at the source code to find the issue, but would be glad to help if someone showed me some directions where I could work on.

**Comment by davidfokkema** [comment]
Same problem when you have an encrypted host vars file. Even if you limit to other hosts, Ansible still asks for the vault password.

**Comment by corysmith-bydeluxe** [comment]
Same issue in 1.9.1

Steps to recreate:
1) Create an ansible-vault file at group_vars/host_group1.yml
2) Create a playbook using host_group2
3) Run the playbook on host_group2

Expected result:
Playbook runs without vault password

Actual result:
Playbook errors out on missing password for group_vars/host_group1.yml

**Comment by kadecole** [comment]
I am experiencing the same behavior in 2.0.2.0. It appears that ansible reads all files in group_vars directory regardless of which group your playbook specifies.  Maybe this should be a feature enhancement request?

**Comment by nitzmahone** [comment]
There are numerous important use cases that rely on this behavior, many of which we're unable to detect reliably to do anything different (think dynamic Jinja2 expression that digs through the hosts in a group to grab an inventory var). Not sure what we could do here to not break those use cases while still allowing for some encrypted inventory files to be ignored. If you've got any ideas, we're all ears- let's discuss on the mailing list or something (or file a proposal with our shiny new proposal process).

Meantime, I'm going to close this as "by design"...

**Comment by felipou** [comment]
What about loading the files on demand? I mean, it doesn't make sense to try and load an encrypted file if it isn't going to be used. Some would even consider this a security issue, no? Decrypting a file unnecessarily, I mean.

**Comment by bcoca** [comment]
@felipou how do we KNOW the file is not needed? until we decrypt it we don't know the variables it contains and we cannot know if the play uses them or not.

**Comment by felipou** [comment]
You're right, I had mistaken the way Ansible organizes its variables with another program.

**Comment by kadecole** [comment]
My thought would be that if you are running a play on a particular group you would only load the group_vars/group_name/ files and the group_vars/all file. That should be the only files you need to load.  If my vault encrypted file is not in these locations then you should not need to load that file and decrypt that file.

**Comment by bcoca** [comment]
@kadecole that you target 1 group does not mean you do not use vars from other groups.

**Comment by AceSlash** [comment]
What about a simple option --ignore-vault? This would solve this issue.

**Comment by ryanooi** [comment]
@kadecole ansible should give error "variable not defined" if you didn't include the files to be loaded. Why would Ansible need to decrypt/read all files that it not suppose to?

**Comment by sibradzic** [comment]
Totally agree with @ryanooi. Exactly, it is just way more natural that failing to decrypt vars should just leave those encrypted variables undefined, and perhaps just throw a warning...

**Comment by AceSlash** [comment]
@ryanooi @sibradzic : I don't agree with that, there are cases where you define a variable for a group and you want to override it in a host_vars, if you fail to decrypt the host_vars, you can screw up your system.

For me, adding a switch to ignore indecipherable vaults files is still the best way to handle this, it means that the user know what will happen. Furthermore, it doesn't change the current default behavior, which is important.

**Comment by Ulls** [comment]
So, given the situation where an encrypted file was committed to a source repository that contains variable information specific to a machine where the playbook will run... I want to add a local file to work with my machine's settings for testing purposes.  Now both files exist in the vars directory of the role I'm working on, one encrypted by my vault secret and another encrypted by a different secret.  The only way I can test the role is to completely remove the original encrypted file from the vars directory because Ansible will attempt to read it regardless if the commands in the role reference it or not.  I never plan on committing my local file to the repo, but need it to test and don't want to remove the original encrypted variable file.  If there was a --ignore-file cli parameter, this wouldn't be an issue.

**Comment by davidfokkema** [comment]
We've switched to git-crypt (https://github.com/AGWA/git-crypt). You can then .gitignore your local file. We do not need to be able to use different secrets, something you can do with vault. You can run all playbooks without knowing the secret (unless you need the crypted host vars, of course).

**Comment by promaty** [comment]
Still the same issue in 2.3.2. No way to ignore encrypted variable files for hosts that are not included?

**Comment by ntelisil** [comment]
Adding an ansible-playbook parameter to ignore vaults would be a great solution.
This way the user will be able  to run playbooks that do not require sensitive data from the vaults without the need to provide (or even knowing in the first place) the passphrase.
