### ISSUE TITLE
yum module enablerepo won't do multiple repositories

### ISSUE THREAD

**Issue by mftovey** [ansible/ansible#7137]
##### Issue Type:

"Bug Report:"
##### Ansible Version:

ansible 1.4.3, 1.5.3
##### Environment:

Oracle Enterprise Linux 6.4
##### Summary:

yum module enablerepo won't do multiple repositories
##### Steps to Reproduce:

```
ansible server1 -s -K -m yum -a "name=pkgname enablerepo=repo1,repo2 state=latest"
```

repo1 and repo2 are intentionally disabled by default in the yum.repo.d configuration files and are enabled as required when installing packages 

```
[repo1]
name=Repository 1
baseurl=http://reposerver/repository1
gpgkey=http://reposerver//RPM-GPG-KEY-repo1
gpgcheck=1
enabled=0

[repo2]
name=Repository 2
baseurl=http://reposerver/repository2
gpgkey=http://reposerver//RPM-GPG-KEY-repo2
gpgcheck=1
enabled=0
```
##### Expected Results:

The specified package and any dependencies it requires are successfully installed on the target servers.
##### Actual Results:

ansible on the Ansible server outputs that it cannot find repository data for the second specified repository (repo2).  Swapping the order of the repository names in the command line simply changes which repository data cannot be located.

```
server1 | FAILED >> {
    "failed": true,
    "msg": "Error setting/accessing repo repo2: Error getting repository data for repo2, repository not found"
```

If I run ansible with '-vvv', the following is output:

```
<server1> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO server1
<server1> REMOTE_MODULE yum name=ansible enablerepo=repo1,repo2 state=latest
<server1> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236 && echo $HOME/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236'
<server1> PUT /tmp/tmpqjd93P TO /home/ansible/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236/yum
<server1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ymortmfovnpsvcpoojkrmqfchlzqzlfm] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ymortmfovnpsvcpoojkrmqfchlzqzlfm; /usr/bin/python -tt /home/server1/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236/yum; rm -rf /home/server1/.ansible/tmp/ansible-tmp-1398273878.46-183006336271236/ >/dev/null 2>&1'"'"''

I have checked the log files on the repository server and used tcpdump to monitor traffic to and from the target server and I can see that the yum module is never reaching out to the repository server.  It appears to be stuck at reading the yum.repos.d configuration files.

I have five Ansible servers, each in different data centers, I get the same results on on all five servers.  I have tried different packages and different repositories, and it is always the same: the yum module fails on the second repository.
```

**Comment by mftovey** [comment]
I saved the tmp file on a target server and looked through it to try to see what is happening.  I was able to isolate the issue to this code snippet:

```
current_repos = my.repos.repos.keys()
for r in en_repos:
    try:
        my.repos.enableRepo(r)`
        new_repos = my.repos.repos.keys()
        for i in new_repos:
           if not i in current_repos:
                rid = my.repos.getRepo(i)
                a = rid.repoXML.repoid
        current_repos = new_repos
    except yum.Errors.YumBaseError, e:
        module.fail_json(msg="Error setting/accessing repo %s: %s" % (r, e))
```

I added some print statements to output repo information as the code is executed:

```
current_repos = my.repos.repos.keys()
print ("current_repos = %s" % (current_repos))
for r in en_repos:
    print ("checking repo %s against %s" % (r, current_repos))
    try:
        my.repos.enableRepo(r)
        new_repos = my.repos.repos.keys()
        print ("new_repos = %s" % (new_repos))
        for i in new_repos:
            print ("testing repo %s against %s" % (i, current_repos))
            if not i in current_repos:
                rid = my.repos.getRepo(i)
                a = rid.repoXML.repoid
        current_repos = new_repos
    except yum.Errors.YumBaseError, e:
        module.fail_json(msg="Error setting/accessing repo %s: %s" % (r, e))
```

That generates this output:

```
current_repos = ['ol6_latest', 'uti_EPEL', 'ol6_u4_base']
checking repo: uti_EPEL against ['ol6_latest', 'uti_EPEL', 'ol6_u4_base']
new_repos = ['uti_EPEL']
testing repo uti_EPEL against ['ol6_latest', 'uti_EPEL', 'ol6_u4_base']
checking repo: ol6_latest against ['uti_EPEL']
{"msg": "Error setting/accessing repo ol6_latest: Error getting repository data for ol6_latest, repository not found", "failed": true}
```

So, at the highlighted line, the list of repositories that the current repository is being tested against has been reduced to just the previously tested repository.
Now, I am not a Python programmer (I bought a "Learning Python" book a couple of months ago, but haven't had time to go through it yet) and it was a stretch for me to get this far.  I am not sure where to go from here, but hopefully someone more knowledgeable can look into it and carry the torch from here.
    Thanks,

```
-Mark
```

**Comment by Jmainguy** [comment]
@mftovey multiple repo's works for me on Centos 6.5 target, is this limited to Oracle Enterprise?

**Comment by Jmainguy** [comment]
Of the servers I could test myself

Centos 5 and 6, Scientific Linux 6, RHEL 5 and 6 support --enablerepo blah --enablerepo blah-blah

However Oracle Linux 6 does not support this, and only works with --enablerepo blah,blah-blah

Fortunately  Centos 5 and 6, Scientific Linux 6, RHEL 5 and 6, and Oracle Linux 6 all support the Oracle method of --enablerepo blah,blah-blah. 

So I recommend this module be changed to use the comma separated way, instead of the multiple --enablerepo way. 

That being said, the yum python module is not really documented anywhere on the internet, and this ansible module is 838 lines long, and I am still pretty new to python. I am unable to patch this module. 

If someone else can take a stab at converting from multiple --enablerepo's to a single --enablerepo with repos separated by comma, that would be great.

**Comment by MiLk** [comment]
Please test the following:

``` diff
diff --git a/library/packaging/yum b/library/packaging/yum
index 245d3b8..2278c84 100644
--- a/library/packaging/yum
+++ b/library/packaging/yum
@@ -737,13 +737,11 @@ def ensure(module, state, pkgspec, conf_file, enablerepo, disablerepo,
     if enablerepo:
         en_repos = enablerepo.split(',')

-    for repoid in dis_repos:
-        r_cmd = ['--disablerepo=%s' % repoid]
-        yum_basecmd.extend(r_cmd)
+    r_cmd = ['--disablerepo=%s' % disablerepo]
+    yum_basecmd.extend(r_cmd)

-    for repoid in en_repos:
-        r_cmd = ['--enablerepo=%s' % repoid]
-        yum_basecmd.extend(r_cmd)
+    r_cmd = ['--enablerepo=%s' % enablerepo]
+    yum_basecmd.extend(r_cmd)

     if state in ['installed', 'present', 'latest']:
         my = yum_base(conf_file)
```

If you have issues with repoquery, you may want to replace all the occurences of:

``` python
for repoid in dis_repos:
  r_cmd = ['--disablerepo', repoid]
  myrepoq.extend(r_cmd)

for repoid in en_repos:
  r_cmd = ['--enablerepo', repoid]
  myrepoq.extend(r_cmd)
```

By:

``` python
r_cmd = ['--disablerepo', ','.join(dis_repos)]
myrepoq.extend(r_cmd)

r_cmd = ['--enablerepo', ','.join(en_repos)]
myrepoq.extend(r_cmd)
```

**Comment by Jmainguy** [comment]
Thank you @MiLk, that pretty much did it. Submitted #8577 to fix this issue.

**Comment by mftovey** [comment]
Interesting thing now, I can't reproduce it anymore.  I downgraded my Ansible version back to 1.5.3 (I was up to 1.6.6) and I down graded yum to the original version delivered on the OS CDs (yum-3.2.29-40.0.1.el6, yum-utils-1.1.30-14.0.1.el6), and still everything installed properly when multiple repositories are specified.  So, I don't know what else changed between April and now, but apparently something did that fixed this.  But the work you did was still good if only to ensure better compatibility with differing operating system versions.
Thanks!
-Mark

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
