### ISSUE TITLE
Unable to login with credentials used to create mongo user

### ISSUE THREAD

**Issue by hlassiege** [ansible/ansible#7157]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

debian 7 for both master and slave
pymongo 2.7
mongo 2.6.0
##### Summary:

Hi,

I'm trying to use mongo_user to create some users. However, I'm unable to login with the credentials specified.
##### Steps To Reproduce:

I use the following commands : 

```
- name: add Mongo admin
  mongodb_user: database=admin name=bigadmin password=BigBosS roles='root' state=present
  sudo: true         
```

and then, if I try to connect, it fails : 
    mongo admin -u bigadmin -p BigBosS
=> auth failed

But if I add this user manually on mongo it works 
    db.addUser({user: "superadmin", pwd: "BigBosS", roles: [{role:"root", db:"admin"}]})

mongo admin -u superadmin-p BigBosS
=> auth successfull
##### Expected Results:

The following command should succeed
    mongo admin -u bigadmin -p BigBosS
##### Actual Results:

The login fail.

The weird thing is that the password is different in the admin db.system.users collection : 

```
>  db.system.users.find()
{ "_id" : "admin.bigadmin", "user" : "bigadmin", "db" : "admin", "credentials" : {  "MONGODB-CR" : "8757ec7d8b6d462f69e10c51d36ff9c1" }, "roles" : [ { "role" :  "root", "db" : "admin" } ] }
{ "_id" : "admin.superadmin", "user" : "superadmin", "db" : "admin", "credentials" : {  "MONGODB-CR" : "96dfab41377d3965ce104f7b1f3d8044" }, "roles" : [ { "role" :  "root", "db" : "admin" } ] }
```

I think the password shoud be identical.

Any idea about that ?

**Comment by mpdehaan** [comment]
This might be a good topic to ask the project list, given it's probably more of a mongo usage question.

As not a heavy user of Mongo, I don't have a direct answer to this one right now, but we can investigate -- just letting you know this is in queue and I'd suggest asking the list first.

Thanks!

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
