### ISSUE TITLE
python api for one or more host

### ISSUE THREAD

**Issue by cc272309126** [ansible/ansible#7202]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.2.2
##### Environment:

RHEL 5/6, Centos 5/6,
##### Summary:

it should add a opption for ansible runner to confirm the host list is a file or string
##### Steps To Reproduce:

I have noticed that the runner api can not suport the host list like 'xxx.xxx.xxx.xxx', but
can suport the host list like 'xxx.xxx.xxx.xxx,' . xxx.xxx.xxx.xxx is the ip of remote host. I read the source and I know the reseaon. it because the below code.
if isinstance(host_list, basestring):
if "," in host_list:
host_list = host_list.split(",")
host_list = [ h for h in host_list if h and h.strip() ]
I think this is a slight bug. it should add a opption for ansible runner to confirm the host list is a file or string

my runner file
import ansible.runner

runner = ansible.runner.Runner(
host_list='xxx.xxx.xxx.xxxx,',
private_key_file='xxx',
module_name='shell',
module_args='rpm -qa | grep sudo',
pattern='*',
forks=10
)
datastructure = runner.run()
print datastructure

**Comment by mpdehaan** [comment]
Ansible 1.2.2 is incredibly ancient, the current release is 1.5.4, with 1.6 on the way.

This is really a question for the development list (ansible-devel) rather than the issue tracker, as this is not a bug or feature idea, but more of a question -- that being said, raised on a very old version of Ansible.

Thanks!
