### ISSUE TITLE
Unable to list systems from cobbler using namespaced puppet management classes 

### ISSUE THREAD

**Issue by hozn** [ansible/ansible#7234]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.5
##### Environment:

RHEL 5.x, 6.x
##### Summary:

We are using Ansible in an environment that makes heavy use of Puppet for config mgmt and uses cobbler for the inventory.  We are using the cobbler.py script provided as a reference (with a few necessary tweaks for our environment).  The inventory is built up correctly, indexing things off of the management classes, but we're not able to use these due to the use of "::" to separate puppet namespaces.

E.g. here is a snippet from inventory output:

```
"infrastructure::jira": [
    "jira.example.com", 
    "jira-test.example.com"
  ], 
```

However, I cannot list these with "ansible --list":

```
[root@localhost]# ansible --list-hosts infrastructure::jira
No hosts matched
```

I trace the issue back to https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py#L159

Changing the seprator character to something else (e.g. "||") fixes the issue, but I have no idea what the correct fix is here.  Was the intent to allow people to use either semicolons or colons to separate multiple patterns on the commandline?  That (the latter, anyway) is kinda incompatible with Puppet management classes.  Maybe you guys don't care, but figured I would comment.
##### Steps To Reproduce:

Add a management class with "::" in it to system(s) in cobbler.  Attempt to list this using "ansible --list".
##### Expected Results:

Expect to see my systems.
##### Actual Results:

I see nothing (see main summary above).

**Comment by mpdehaan** [comment]
This seems like the cobbler inventory script should just replace ":" in group names that come from Cobbler with "_".

Something you may want to work on, perhaps?

**Comment by hozn** [comment]
That seems less than ideal, since classes can certainly have "_" characters
in them ...  I'm not sure offhand which char would work well but not get
munged by the pattern processing.  I've just patched ansible in our build
process to replace ";" with "||" and then split on "||".

**Comment by jctanner** [comment]
Starting in v2.0.0-0.6.rc1, the algorithm for splitting a host pattern is something like this ...

1) if semicolon in pattern, split on semicolon
2) else if comma in pattern, split on comma
3) else check if the pattern looks like an ipv6 address
4) if not an ipv6 address, use a regex to split on ( anything not whitespace or [] ) OR ([a-z])

 In the case of "infrastructure::jira", we hit the last part of the algorithm and end up splitting on ':' into [infrastructure,jira]. Those aren't valid groups, so the rest of the execution fails.

However, there is a way to make this work without modifying any ansible code ...

```
ansible --list-hosts "infrastructure::jira,"
```

Putting the comma in there causes the split to happen on that instead of getting down to the regex which would have split on the colons. I have confirmed the behavior with the following testcase ...

```
$ cat inventory.py
#!/usr/bin/env python

import json
import sys
from pprint import pprint

INV = {}
INV['_meta'] = {'hostvars': {}}

groups = ['one', 'two', 'three', 'infrastructure::jira']
hosts = ['foo', 'bar', 'baz', 'bang']

for idx, group in enumerate(groups):
    INV[group] = {}
    INV[group]['children'] = []
    INV[group]['vars'] = {}
    INV[group]['hosts'] = [hosts[idx]]

for host in hosts:
    INV['_meta']['hostvars'][host] = {}
    INV['_meta']['hostvars'][host]['ansible_connection'] = 'local'

print json.dumps(INV, indent=2)

$ ansible  -i inventory.py --list-hosts "infrastructure::jira,"
  hosts (1):
    bang
```
