### ISSUE TITLE
(Doc) Intro to Ad-Hoc Commands:  the command module *does* accept shell variables

### ISSUE THREAD

**Issue by jf** [ansible/ansible#7240]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.6 (devel 40a7a306f5)
##### Environment:

Ubuntu 12.04
##### Summary:

http://docs.ansible.com/intro_adhoc.html states:

---

Note

The command - Executes a command on a remote node module does not support shell variables and things like piping. If we want to execute a module using a shell, use the ‘shell’ module instead. Read more about the differences on the About Modules page.

---

But I've tried with various invocations of `ansible` with no problem:

`ansible <hostname> -a 'echo $SHELL'` =>  /bin/bash

`ansible <hostname> -a 'echo $HOME' --sudo -K` => /root

`ansible <hostname> -a 'touch $HOME/abc'` => file is touched

I wont submit a patch; I'll leave you guys to decide how to fix this, but that paragraph needs a bit of love...

**Comment by mpdehaan** [comment]
Unless I'm incorrect. The default -m module for /usr/bin/ansible is actually "shell", hence why this works.

I'll triple check and see about clarifying the docs.

You can use "-m" to select different modules.

**Comment by jf** [comment]
yeah... was a bit lazy typing out the examples, but they are run with '-m command' (and I did check). The docs say that the default module is actually 'command' (http://docs.ansible.com/intro_adhoc.html: 'Normally commands also take a -m for module name, but the default module name is ‘command’, so we didn’t need to specify that all of the time.'), but just in case, I've specifically run them with '-m command' with the same results.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
