### ISSUE TITLE
Overriding user and hosts with the ansible-playbook command

### ISSUE THREAD

**Issue by jonaswouters** [ansible/ansible#725]
Nowhere in the documentation there is mention that you can override the user and hosts variable in a playbook.  
Currently there does not seem to be a way to override these variables unless they are defined as a variable 

```
- hosts: $hosts
  user: $user
```

It would be nice to be able to override these variables even though they are not defined like the example above. 

Especially when including playbooks in playbooks ([documentation should be updated](http://ansible.github.com/bestpractices.html) "Having playbooks be able to include other playbooks is coming in a future release. See Issue #538." is Closed) this functionality would be welcome. This would allow us to reuse other people's playbooks without having to modify them for our own environment.

An alternative would be to mention this in the best practices documentation for people willing to write reusable playbooks.

**Comment by mpdehaan** [comment]
Not sure I agree, because different groups of hosts could be listed in each play, which is one of the multinode features of ansible.

The current method allows setting different hosts like you could say "group1=foo and group2=foo", etc.

Yes, you are going to have to edit other people's playbooks, but that's almost always going to be the case anyway.

I think we should just document how to do this better.
