### ISSUE TITLE
synchronize does not follow "delegate_to" setting

### ISSUE THREAD

**Issue by rcp** [ansible/ansible#7250]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5, initially. Also tried:
ansible 1.6 (devel 40a7a306f5) last updated 2014/05/01 11:43:40 (GMT -400)
##### Environment:

CentOS 6.5 (all hosts)
##### Summary:

The documentation for the synchronize action leads me to believe (and #ansible IRC chats confirm)  that the expected behaviour of the snippet below is that the src of the rsync will be delegate.host:some/relative/path.  My experience is that the source is instead some/relative/path on the host from whence the action is issued.

synchronize: >
    src=some/relative/path dest=/some/absolute/path
    delegate_to: delegate.host
##### Steps To Reproduce:

Follow bash commands in http://pastebin.com/SA9aHt2J They are also reproduced below.

```
# bash commands to reproduce ansible problem with 'delegate_to' in 'synchronize'
# edit 'host1' and 'host2', run on a separate host3
#
mkdir -p /tmp/tst/a
ssh host1 mkdir -p /tmp/tst/a/b
cat >/tmp/tst/sync-test.yml <<EOF

---
# Test "delegate_to:" in synchronize action (RUN ON host3!)
- name: ensure soldev in sync with master
  hosts: host2
  remote_user: root
  tasks:
  - name: syncronize /tmp/tst tree (should be from host1)
    synchronize: >
      src=/tmp/tst/ dest=/tmp/tst
      delegate_to: host1
EOF
ansible-playbook -vv /tmp/tst/sync-test.yml 
ssh host2 find /tmp/tst
# see presence of /tmp/tst/sync-test.yml, and absense of /tmp/tst/a/b
```
##### Expected Results:

```
/tmp/tst
/tmp/tst/a
/tmp/tst/a/b
```
##### Actual Results:

```
/tmp/tst
/tmp/tst/sync-test.yml
/tmp/tst/a
```

**Comment by mpdehaan** [comment]
Synchronize is a wrapper around producing local_action: shell rsync <args> commands.

It runs between the remote host and the local one, but it can't be used to bridge rsync's between two different hosts.

If you wanted this, I'd just call "shell: rsync" directly.

We can look at making the documentation more clear on this.

**Comment by edrozenberg** [comment]
I just ran into this same issue - would be great if the docs reflected the fact that it doesn't do a sync between two remote hosts. Also thought it was a bug and was about to file it as such when I found this existing issue report.

Though it certainly would be great if this functionality existed - sync between two remote hosts is a common scenario with many use-cases.

**Comment by simonft** [comment]
> It runs between the remote host and the local one, but it can't be used to bridge rsync's between two different hosts.

Is this still the case? I'm able to use delegate_to: in a synchronize task and ansible connects to the delegate host, then runs rsync locally on the deletate host to push the directory to the remote host. I had to add the following to allow the delegate to connect to the remote host:

```
rsync_opts='--rsh "ssh -i /root/.ssh/ansible"' 
```

Is it a bug that this works?

**Comment by flynfish** [comment]
I also having it working when passing in `rsync_opts: '-e "ssh -i /home/openvpnas/.ssh/id_rsa"'`

**Comment by abadger** [comment]
This is working for me in 1.9.2 and we've just merged a patch to make sure that this is working in ansible-2.0 here:  https://github.com/ansible/ansible/pull/11822

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
