### ISSUE TITLE
unarchive module doesn't check for previous upload (edited description)

### ISSUE THREAD

**Issue by alexanderjardim-zz** [ansible/ansible#7258]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel b753625dbf) last updated 2014/05/02 17:13:20 (GMT -200)
##### Environment:

Darwin Kernel Version 13.1.0: Wed Apr  2 23:52:02 PDT 2014; root:xnu-422.92.1~2/RELEASE_X86_64 x86_64
##### Summary:

When I use unarchive on a task, it takes too long to execute even if the file was already unarchived.
##### Steps To Reproduce:

Setup {{java_dir}}, {{download_dir}} properly
Using this tasks in a playbook.

```

---
- name: download Oracle JDK7 to host
  local_action: >
    command wget -N -P "{{download_dir}}" --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz
    creates="{{download_dir}}/jdk-7u51-linux-x64.tar.gz"
    sha256sum=77367c3ef36e0930bf3089fb41824f4b8cf55dcc8f43cce0868f7687a474f55c

- name: "{{java_dir}} must exist"
  file: path={{java_dir}} state=directory

- name: unpacks Jdk7
  unarchive: 
    src="{{download_dir}}/jdk-7u51-linux-x64.tar.gz"
    dest="{{java_dir}}"
    creates="{{java_dir}}/{{java_dist}}/bin/java"
    force=no

- name: setup JAVA_HOME
  lineinfile:
    dest=~/.bashrc
    line="export JAVA_HOME={{java_dir}}/jdk1.7.0_51"
    state=present
    insertafter=EOF
    create=true

- name: append JAVA_HOME to PATH
  lineinfile:
    dest=~/.bashrc
    line="export PATH=$JAVA_HOME/bin:$PATH"
    state=present
    insertafter=EOF
    create=true
```

Run the following command twice.
$ time ansible-playbook -i hostfile playbook.yml
##### Expected Results:

Task "unpack jdk7" should take less time on the second execution as it doesn't need to change the files again at the hosts.
##### Actual Results:

Even as the files don't need to change, I see ansible PUTting the "tgz"package again at the hosts.

```
TASK: [oracle-jdk | append JAVA_HOME to PATH] ********************************* 
<ommitedIP1> ESTABLISH CONNECTION FOR USER: weblogic
<ommitedIP2> ESTABLISH CONNECTION FOR USER: weblogic
<ommitedIP1> REMOTE_MODULE lineinfile dest=~/.bashrc line="export PATH=$JAVA_HOME/bin:$PATH" state=present insertafter=EOF create=true
<ommitIP2> REMOTE_MODULE lineinfile dest=~/.bashrc line="export PATH=$JAVA_HOME/bin:$PATH" state=present insertafter=EOF create=true
<ommitedIP1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/alexanderjardim/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=weblogic', '-o', 'ConnectTimeout=10', 'ommitedIP1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205 && echo $HOME/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205'"]
<ommitedIP2> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/alexanderjardim/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=weblogic', '-o', 'ConnectTimeout=10', 'ommitedIP2', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644 && echo $HOME/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644'"]
<ommitedIP1> PUT /var/folders/24/z4kdgvy113g057ghgtyfg2k80000gn/T/tmptA4OnK TO /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205/lineinfile
<ommitIP2> PUT /var/folders/24/z4kdgvy113g057ghgtyfg2k80000gn/T/tmpCXhMHG TO /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644/lineinfile
<ommitIP2> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/alexanderjardim/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=weblogic', '-o', 'ConnectTimeout=10', 'ommitIP2', "/bin/sh -c '/products/python/bin/python /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644/lineinfile; rm -rf /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-154713247024644/ >/dev/null 2>&1'"]
ok: [cat02] => {"backup": "", "changed": false, "item": "", "msg": ""}
ommitedIP1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/alexanderjardim/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=weblogic', '-o', 'ConnectTimeout=10', 'ommitedIP1', "/bin/sh -c '/products/python/bin/python /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205/lineinfile; rm -rf /home/weblogic/.ansible/tmp/ansible-tmp-1399059820.18-193242956046205/ >/dev/null 2>&1'"]
ok: [cat01] => {"backup": "", "changed": false, "item": "", "msg": ""}
```

It takes 20 minutes, even as it was not changed. Am I doing something wrong?

**Comment by jimi-c** [comment]
No, it appears that we're not checking the MD5 of the uploaded file to see if it was already uploaded and still exists. I will look into this.

**Comment by alexanderjardim-zz** [comment]
Same behavior with get_url :(. Should I open other ticket for it?

**Comment by jonhadfield** [comment]
I've submitted a pull request that should fix this the issue for the unarchive module: https://github.com/ansible/ansible/pull/7357. 
In the meantime, you could try cloning my fork and testing with the 'skip-archive' branch: https://github.com/jonhadfield/ansible/tree/skip-unarchive

**Comment by jonhadfield** [comment]
I produced the patch before seeing this issue as I experienced what I believe to be the same issue. The summary reads to me that the key issue is time and then goes on to suggest the issue is, incorrectly IMHO, the extraction time.
From looking through the code, a copy takes place first, without checking the creates value. By the time it is checked, the file has already been copied. I can't see the benefit of carrying out the copy in the first place so the change I submitted returns immediately after checking creates and before the copy would take place.
The documentation suggests this is the correct behaviour:
"creates"... 'a filename, when it already exists, this step will not be run.'
I've only carried out minimal testing but it has reduced my deployment times significantly.

**Comment by buster** [comment]
+1 for this bug. Trying to deloy on dozens on servers and it always takes ages because of this :(

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
