### ISSUE TITLE
new module locale_gen fails with "Is the package "locales" installed?"

### ISSUE THREAD

**Issue by eggnog-armed** [ansible/ansible#7289]
Can anyone see what I'm doing wrong? I'm trying to generate and set the system's locale with the following tasks against ubuntu server 14.04 and 12.04 32 bit.

```
- name: install the locales package
  apt: pkg=locales state=present

- name: ensure the locale exists
  locale_gen: name={{ locale }} state=present

- name: set the locale
  command: /usr/sbin/update-locale LANG={{ locale }} --reset
```

output

```
msg: /etc/locale.gen and /var/lib/locales/supported.d/local are missing. Is the package “locales” installed?
```

However I have confirmed that the locales package is installed on the remote host.

```
root@vps01:~# apt-get install locales
Reading package lists... Done
Building dependency tree       
Reading state information... Done
locales is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Also if I don't use the locale_gen: module everything works fine.

```
- name: install the locales package
  apt: pkg=locales state=present

- name: ensure the locale exists
  command: /usr/sbin/locale-gen {{ locale }}

- name: set the locale
  command: /usr/sbin/update-locale LANG={{ locale }} --reset
```

output

```
changed: [vps03.fqdn.com] => {"changed": true, "cmd": ["/usr/sbin/locale-gen", "en_GB.UTF-8"], "delta": "0:00:02.105356", "end": "2014-04-25 01:03:10.600058", "item": "", "rc": 0, "start": "2014-04-25 01:03:08.494702", "stderr": "", "stdout": "Generating locales...\n  en_GB.UTF-8... done\nGeneration complete."}
```

**Comment by damncabbage** [comment]
+1; confirmed in my own setup (14.04 control/nodes).

**Comment by tersmitten** [comment]
We fixed it like [this](https://github.com/Oefenweb/ansible-locales/blob/master/tasks/main.yml), but it's not pretty...

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
