### ISSUE TITLE
virt module doesnt use default libvirt uri

### ISSUE THREAD

**Issue by landryb** [ansible/ansible#7290]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel c6f3a0a) last updated 2014/05/02 09:59:57 (GMT +200)
##### Environment:

Debian/OpenBSD
##### Summary:

virt module doesnt respect default libvirt uri
##### Steps To Reproduce:

Set default_uri to lxc:/// in /etc/libvirt/libvirt.conf on the host node.
Try to use virt module to gather status of a container without specifying uri.

```
#ansible tiger -m virt -a 'name=debpkg command=status'
```

Since uri is set to default='qemu:///system' in library/cloud/virt, the default on the remote system is ignored, and one has to always provide the uri value.. dunno how that qualifies as a bug though :)
##### Expected Results:

```
tiger | success >> {
    "changed": false, 
    "status": "running"
}
```
##### Actual Results:

```
tiger | FAILED >> {
    "failed": true, 
    "msg": "virtual machine debpkg not found"
}
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
