### ISSUE TITLE
gem module fails to install new version of gem when using local a local .gem file as gem_source

### ISSUE THREAD

**Issue by utilitynerd** [ansible/ansible#7305]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

RHEL 6 host and target
##### Summary:

If a local .gem file has been installed by setting gem_source, ansible refuses to install a new version of the gem when gem_source is set to the newer .gem file. The version argument for the gem module can't be used as it is mutually exclusive with the gem_source argument. 
##### Steps To Reproduce:

```
Copy example_1.0.gem to remote host
Install example_1.0.gem using gem module and gem_source
```

--- LATER --

```
Copy example_1.1.gem to remote host
Attempt to Install example_1.1.gem using gem module and gem_source gem module thinks the gem is already installed and doesn't run {"changed": false
```

m. 
##### Expected Results:

New gem should actually be installed
##### Actual Results:

gem does not get installed

**Comment by utilitynerd** [comment]
The issue is caused by the exists function

def exists(module):
    if module.params['state'] == 'latest':
        remoteversions = get_installed_versions(module, remote=True)
        if remoteversions:
            module.params['version'] = remoteversions[0]
    installed_versions = get_installed_versions(module)
    if module.params['version']:
        if module.params['version'] in installed_versions:
            return True
    else:
        if installed_versions:
            return True
    return False

If version isn't set and any version of the gem is installed, then exists will always return True.  Version, can't be set when gem_source is set.  state=latest won't help either, since it relies on the remote repository to get the version of the latest release.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
