### ISSUE TITLE
rabbitmq_policy errors when setting priority for policy

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/ansible#7323]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 
##### Environment:

Running from: Mac OS X 10.8.3
Managing: CentOS 6
RabbitMQ Version: 3.1.5 
##### Summary:

Testing setting a policy on a RabbitMQ 3.1.5 server with the rabbitmq_policy module, the policy fails to set throwing an error saying:

```
Error: invalid command 'set_policy ha_all .* {"ha-mode": "all"} --priority 10'
```

Troubleshooting the error, it stems from --priority being appended before the priority value.
##### Steps To Reproduce:

Task configured in playbook:

```
- name: Configure HA Policy for Queues
  rabbitmq_policy: name="ha_all"
                    pattern=".*"
                    priority=10
                    tags="ha-mode=all"
                    node=rabbit@{{ cluster_disk_nodes[0] }}
  when: ansible_hostname == "{{ cluster_disk_nodes[0] }}"
```

Or executing as shell command:

```
/usr/sbin/rabbitmqctl -n rabbit@host set_policy -p / ha_all '.*' '{"ha-mode": "all"}' --priority 10
```
##### Expected Results:

Success when executing through module, or the following when executing without quiet mode on the command line:

```
Setting policy "ha_all" for pattern ".*" to "{\"ha-mode\": \"all\"}" with priority 10 ...
...done.
```
##### Actual Results:

```
failed: [host] => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit@host set_policy -p / ha_all '.*' '{\"ha-mode\": \"all\"}' --priority 10", "failed": true, "item": "", "rc": 1}
stderr: Error: invalid command 'set_policy ha_all .* {"ha-mode": "all"} --priority 10'
```

**Comment by geauxvirtual** [comment]
Also found when not setting the priority in the task, the rabbitmq_policy module tries to set the priority to 0 by default which causes the task to fail also since it appends --priority 0 to the command.

```
- name: Configure HA Policy for Queues
  rabbitmq_policy: name="ha_all"
                   pattern=".*"
                   tags="ha-mode=all"
                   node=rabbit@{{ cluster_disk_nodes[0] }}
  when: ansible_hostname == "{{ cluster_disk_nodes[0] }}"
```

results in

```
failed: [host] => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit@host set_policy -p / ha_all '.*' '{\"ha-mode\": \"all\"}' --priority 0", "failed": true, "item": "", "rc": 1}
stderr: Error: invalid command 'set_policy ha_all .* {"ha-mode": "all"} --priority 0'
```

**Comment by arpyzo** [comment]
The --priority parameter was introduced in rabbitmq 3.2.0. It's likely rabbitmq_policy will fail for any installation of rabbitmq prior to version 3.2.0.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
