### ISSUE TITLE
Support "--net" option in docker.io module

### ISSUE THREAD

**Issue by pilwon** [ansible/ansible#7324]
##### Issue Type:

Feature Idea
##### Ansible Version:

Latest
##### Environment:

N/A
##### Summary:

Docker v0.11 is released and it supports powerful `--net` option for advanced networking. Please add support of "--net" option to the `docker` module.
- Host networking (from the [announcement](http://blog.docker.io/2014/05/docker-0-11-release-candidate-for-1-0/))

For those wanting their containers to directly access the host system’s network interfaces, Docker 0.11 features a “host networking” mode. A container in host networking mode is sandboxed as usual, except for its network stack which is shared with the host system.

By default, when you start a container, it’ll only have a loopback interface `lo` and a virtual interface `eth1` connected to the docker bridge:

```
$> docker run busybox ip a
```

You can now directly use the interfaces of you host (it’s much faster as it doesn’t go through the bridge) via --net=host:

```
$> docker run --net=host busybox ip a
```
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by sivel** [comment]
This will require us to wait until docker-py has support for this.

**Comment by pilwon** [comment]
Created [docker-py Issue #219](https://github.com/dotcloud/docker-py/issues/219) for this.

**Comment by pr0xr** [comment]
+1

**Comment by a-sk** [comment]
docker-py already has this feature, dotcloud/docker-py#224

**Comment by pr0xr** [comment]
> docker-py already has this feature, dotcloud/docker-py#224

Thats great. It seems that there is no documentation on how to use it on:  http://docs.ansible.com/docker_module.html.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the commit merged in via PR #7408 should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by matejkramny** [comment]
@jimi-c how can I use it now, without waiting for 2.0?

Thanks

**Comment by pilwon** [comment]
@matejkramny You can copy this file https://raw.githubusercontent.com/ansible/ansible/b10afccb071495a676f60b15c94c9b4708ad3c8f/library/cloud/docker to `library/cloud/docker` of your project.

**Comment by matejkramny** [comment]
Many thanks @pilwon!
