### ISSUE TITLE
skip creation of .retry files when there is only one host in the inventory

### ISSUE THREAD

**Issue by jokeyrhyme** [ansible/ansible#7328]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.1
##### Environment:

OS X 10.9.3 beta
##### Summary:

Loving ansible, it definitely lessens some of the pain of system maintenance.

Unless I am misunderstanding this feature, the `--limit` option for `ansible-playbooks` allows you to skip hosts where the playbooks ran successfully. This way, you only re-run the failed playbooks on the hosts where it failed.

However, if there is only one host, then simply re-running `ansible-playbooks` with exactly the same parameters as before (no `--limit`) achieves the same result.

I propose that when there is only one host, the `playbook.retry` file should not be created, as in this case it serves no purpose.
##### Steps To Reproduce:
1. use `ansible-playbooks` to execute a playbook that will fail, with an inventory that contains only 1 host
##### Expected Results:
- see an error message
- observe that no `.retry` file has been created
##### Actual Results:
- pointless (?) `.retry` file is created, no matter how many hosts were initially involved

**Comment by Rowno** [comment]
:+1:

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

We don't want this to seem confrontational, but unfortunately we're not sure if we want this feature in the program. This issue has remained open for quite a while, and it has failed to garner any interest nor have any community members picked it up to work on it. However, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
