### ISSUE TITLE
authorized_key: manage_dir fails with bad message when home directory doesn't exist

### ISSUE THREAD

**Issue by lfrancke** [ansible/ansible#7333]
##### Issue Type:

Documentation Report, Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

RHEL 6.5
##### Summary:

The `authorized_key` module fails (even with `manage_dir` turned on) when the user's home directory does not exist.
##### Steps To Reproduce:

```
authorized_key: user=doesnotexist key="{{ lookup('file', '...foobar') }}" manage_dir=yes
```
##### Expected Results:

I agree that Ansible probably shouldn't create home directories but a better error message would be nice. Explaining why this creation fails (i.e. checking whether the home directory exists at all). When setting `manage_dir` I expected the directory to be created. Problem is that these systems are set up to create the home directory on first login so when I logged on to debug the issue it went away.
##### Actual Results:

```
Traceback (most recent call last):
  File "<stdin>", line 1516, in <module>
  File "<stdin>", line 419, in main
  File "<stdin>", line 400, in enforce_state
  File "<stdin>", line 170, in keyfile
OSError: [Errno 2] No such file or directory: '/home/doesnotexist/.ssh'
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
