### ISSUE TITLE
vsphere_guest enhancements for larger environments

### ISSUE THREAD

**Issue by nigelm** [ansible/ansible#7349]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6.1
##### Environment:

N/A
##### Summary:

The `vsphere_guest` module has a number of shortcomings, which mostly show up if you are running vSphere instances with additional features licensed (although some are more generic):-
- Datastores for new VMs must be specified directly - if you have SDRS licensed you normally allocate to a datastore_cluster or a storage class and let the system put the VM in the best place rather than second guessing it
- A VM must be allocated to a specific host.  If you have DRS licensed then you would normally allocate to a cluster and let the load balancing put it in the right place (the system will only sneak it elsewhere as soon as your back is turned causing the next run to fail)
- Documentation is lacking for putting networks on distributed switches
- There appears to be no way to (de|a)ttach an ISO or change the boot mechanism
- Documentation bugs (powered_on appears twice as an option but powered_off does not)
- There is not support for a soft (OS mediated power up/down)
- There is no support to clone an existing VM template (ie gold image)
- Documentation examples are really hard to use - they use an older syntax and do not just transport across to an ansible 1.6 installation

I'm intending to have a look at whichever of these I can as I get the opportunity.  However if other people wish to attack any of these please drop a comment onto this ticket to prevent too much clashing work.

**Comment by rhoop** [comment]
Good breakdown! I am already working on the following but feel free to improve where you can:
- There is not support for a soft (OS mediated power up/down)
- There is no support to clone an existing VM template (ie gold image)
- Documentation bugs

**Comment by fti7** [comment]
Hi rhoop,
+1 For support to clone an existing VM template
Let me know if you need a Beta Tester

**Comment by bguse** [comment]
Is there a chance to set the mac-address of the network-interfaces too?

**Comment by nathansoz** [comment]
@rhoop:  any idea where you are at on the template clone support? I'd be willing to contribute to making that happen!

**Comment by bcoca** [comment]
I've been using the template clone feature for a couple of weeks, works
nicely!​

TODO: change the vmware inventory plugin to use pysphere, its much faster
and it would be nice for people not having to install 2 diff base libraries

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
