### ISSUE TITLE
Dependency Children Skipped as Duplicates

### ISSUE THREAD

**Issue by rodnaph** [ansible/ansible#7353]
##### Issue Type:

Bug Report
##### Ansible Version:

master
##### Environment:

N/A
##### Summary:

If a role dependency is skipped, via:

``` yaml

---
dependencies:
  - { role: foo, when: false }
```

Then it's children are also skipped, even if they are required by other roles.
##### Steps To Reproduce:

```
# roles/foo/meta/main.yml

---
dependencies:
  - { role: child, when: false }
```

```
# roles/bar/meta/main.yml

---
dependencies:
  - { role: child }
```

```
# roles/parent/meta/main.yml

---
dependencies:
  - { role: foo }
  - { role: bar }
```

If the _parent_ role is used, then _child_ will never be executed.
##### Expected Results:

Roles are re-run if required by subsequent roles, and have not been run already (under no-duplicate roles policy).
##### Actual Results:

Role is skipped for the rest of the play.

**Comment by jimi-c** [comment]
Using your example, I am unable to reproduce this:

<pre>
$ ansible-playbook 7353.yml 
PLAY [localhost] ************************************************************** 
TASK: [7353_child | debug msg="here i am in the child"] *********************** 
skipping: [127.0.0.1]
TASK: [7353_child | debug msg="here i am in the child"] *********************** 
ok: [127.0.0.1] => {
    "item": "", 
    "msg": "here i am in the child"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

As you can see in the above output, the child task is skipped, however it is run the second time via the dependency from the `bar` role.

Can you create a github repository containing a sample playbook that reliably reproduces this issue on your system and share that here so I can test against what you're seeing?

**Comment by rodnaph** [comment]
Of course, here you go:

https://github.com/rodnaph/ansible-7353

**Comment by jimi-c** [comment]
Great, I do see that your roles included there do reproduce the issue. I'll look into this more today.

**Comment by stintel** [comment]
Having the same issue with one of my playbooks. Running git bisect shows 0411ea2867af48f9df4dcdb68921fe0535d4e156 as the first bad commit. After checking later commits, I found that setting "allow_duplicates: true" in roles/child/meta/main.yml seems to solve it.

**Comment by sontek** [comment]
+1 just had the exact same issue. Discussed on the mailing list and IRC but allow_duplicates really isn't an option for me. Slows the runs down a LOT

**Comment by msabramo** [comment]
I also ran into this; I work with @sontek and it was the same playbook but I ran into a different manifestation of the problem. Basically there are 2 roles that include a role called "common" and one of the tasks in that "common" role creates a new UNIX group. One of the 2 roles that depends on the "common" role gets skipped because of a condition - that causes common to not get executed in the other role that depends on it and that role fails badly because it is relying on that group to be present (it does a chown to that user group). I managed to work around this by moving the common role up a level, but I'm pretty sure this is not possible in all situations. 

I would also point out (and I can file a separate issue for this if you wish) that Ansible just says the task is skipped and gives no info about why, so it's puzzling and tricky to diagnose. If it's not feasible to have the expected behavior then please consider outputting a warning that explains why things are being skipped.

**Comment by msabramo** [comment]
I looked at the code today and I don't see an easy way to solve this. Role is not a class and the building of the dependency tree is done after loading the playbook with no regard to the `when` clauses, those are evaluated later on. Roles seem to be a different animal than what I hoped they would be and I don't see an easy way to make them aware of what actually executed and what didn't.

Bummer.

**Comment by jimi-c** [comment]
@msabramo I actually have a feature branch I've been working on turn Role into a proper class, however this problem is still quite difficult to fix even in that branch.

You can find the working branch here: https://github.com/jimi-c/ansible/tree/class_based_roles

**Comment by jimi-c** [comment]
HI @rodnaph, the above fix actually addresses a separate bug I found while testing this in devel, but this issue should now be resolved and will be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by nhooey** [comment]
@jimi-c: There appears to be a [regression](https://github.com/ansible/ansible/issues/14438) of this bug in between at least Ansible 2.0.0.2 and Ansible 2.0.2.0.

**Comment by jimi-c** [comment]
@nhooey I just tested this on devel, v2.0.1.0-1, and v2.0.2.0-1 and do not see the issue there.

**Comment by kal4l** [comment]
I am experiencing this issue on 2.1.1.0.

**Comment by jimi-c** [comment]
@kevcgrant please open a new issue for this, as it's probably not related to this old issue.
