### ISSUE TITLE
Ansible test-module corrupting executable before execution

### ISSUE THREAD

**Issue by robertoaloi** [ansible/ansible#7356]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.5
##### Environment:

“N/A”
##### Summary:

I'm working on a new Ansible module and I would like to use the Ansible test-module script to verify it works, as explained in the official ansible documentation.

The executable is standalone and it works as expected on its own, but running the Ansible test-module on it fails.

I noticed that, before invoking my executable, the Ansible test-module does the following:

It renames the executable into .ansible_module_generated (and it places it into my home dir)
It appends a newline at the end of the executable
My executable is in a compressed format and the appended newline corrupts its internal validation. Moreover, the executable requires the original executable name to be preserved, so the renaming is an issue, too.

Is the above behaviour specific to the test-module - which means that I can easily tweak the test-module script by stripping out the extra newline and by avoiding the renaming operation - or is it a general Ansible behaviour that the test-module is trying to emulate? Is there any workaround?
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
What language is the module written in, and does it work when executed normally by ansible? Or do you mean that it just works when run directly on a system?

**Comment by robertoaloi** [comment]
The module is an [Erlang escript](http://www.erlang.org/doc/man/escript.html) archive. Essentially an executable .zip file with a shebang (`#!/usr/bin/env escript\n`) as its first line. Haven't tried it in Ansible yet (since it didn't pass the test-module validation). It works when run directly on a system with Erlang installed.

**Comment by robertoaloi** [comment]
Just tried to run the module via ansible. I get a: `FAILED => failure encoding into utf-8`.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
