### ISSUE TITLE
password string exposures when it specified by an environment value

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible#73620]
##### SUMMARY

When a password string specified by an environment value, `env_fallback` cannot handle `no_log` so the password string will be shown in the playbook output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/parameters.py#L258

##### ANSIBLE VERSION

devel

##### STEPS TO REPRODUCE

Please refer to this issue:
https://github.com/infobloxopen/infoblox-ansible/issues/41

**Comment by sugitk** [comment]
The customer faced the issue on 2.9.16 but I was not able to find the code in stable-2.9.

**Comment by jborean93** [comment]
This was just fixed with https://github.com/ansible/ansible/pull/73487 and is backported all the way back to Ansible 2.8. A release is pending which will include this fix but it's not out just yet.

Just to expand on the problem, the issue only applies to `no_log` fallback options in sub options. Any root module options that have `no_log=True` and was sourced from a fallback were masked but with the PR it now also includes suboptions.

**Comment by nitzmahone** [comment]
Was fixed in https://github.com/ansible/ansible/commit/49ebd509df9de1c1fc1bcee00e79a835dd00662c - should be released in the next few days.

**Comment by sugitk** [comment]
@jborean93 @nitzmahone Thank you very much for your immediate comments.  I will wait for the next minor release and after that I will inform it to the customer.

**Comment by bcoca** [comment]
closing as per above
