### ISSUE TITLE
lineinfile failed to parse with #

### ISSUE THREAD

**Issue by jasonmader** [ansible/ansible#7386]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1 
##### Environment:

from OS X managing SLES11SP3
##### Summary:

In **lineinfile** module `line` option containing `#` cannot be parsed.

Escaping `\#` can be parsed but the inserted line will contain `\#`.
##### Steps To Reproduce:

``` yaml
- lineinfile: dest=/etc/services regexp='31010/tcp' state=present insertbefore='^autotrac-acp'
    line='lstc_proxy         31010/tcp    # LSTC License Server Proxy for Clusters'
```
##### Expected Results:

```
TASK: [cluster | lineinfile dest=/etc/services regexp='31010/tcp' state=present insertbefore='^autotrac-acp' line='lstc_proxy         31010/tcp    # LSTC License Server Proxy for Clusters'] ***
changed: [master] => {"backup": "", "changed": true, "item": "", "msg": "line added"}
```
##### Actual Results:

```
TASK: [cluster | lineinfile dest=/etc/services regexp='31010/tcp' state=present insertbefore='^autotrac-acp' line="lstc_proxy         31010/tcp] ***
fatal: [master] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1400003075.9-231049357270038/lineinfile", line 1539, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1400003075.9-231049357270038/lineinfile", line 328, in main
    supports_check_mode=True
  File "/root/.ansible/tmp/ansible-tmp-1400003075.9-231049357270038/lineinfile", line 559, in __init__
    (self.params, self.args) = self._load_params()
  File "/root/.ansible/tmp/ansible-tmp-1400003075.9-231049357270038/lineinfile", line 1110, in _load_params
    items   = shlex.split(args)
  File "/usr/lib64/python2.6/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.6/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
