### ISSUE TITLE
Module get_url should first do a HEAD call to get filename

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#7424]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7
##### Environment:

Ansible controller running on Mac OSX 10.9.3 controlling Slackware64 14.1 hosts.
##### Summary:

The module "get_url" always downloads the file if the destination is a directory. This is because the filename isn't known until the GET request is made.

This approach should be enhanced by making a HEAD call first, to get the filename, removing the need to make a GET call if the filename already exists at the destination. 

This idea came out of the following discussion:
https://groups.google.com/forum/#!topic/ansible-devel/HjY3ER0tJOw
##### Steps To Reproduce:

Assume: /tmp/myfile-4.3.2.tar.gz already exists at the destination.

```
# Attempt to download file that already exists at destination
- name: get file to a destination directory
  get_url: >
      url=http://files.com/myfile-4.3.2.tar.gz
      dest=/tmp
      mode=0644
```
##### Expected Results:

What should happen with an enhancement to "get_url" is the file is not downloaded again.
##### Actual Results:

The file is fully downloaded even though it is already present at the destination dir, and then is discarded after compare with existing file (unless overwrite is forced), wasting time and bandwidth.

The only way to prevent a full re-download is to specify the full destination file name, not just the destination directory.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
