### ISSUE TITLE
Update homebrew module to use: brew info --json

### ISSUE THREAD

**Issue by finn** [ansible/ansible#7453]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.4
##### Environment:

Mac OS X 10.9.3 (Mavericks) and Ubuntu 12.04 (precise)
##### Summary:

This is a suggestion to use the `--json` flag from the `brew info` flag in the homebrew module as it is a proper programmatic API interface rather than human readable console output.
##### Steps To Reproduce:

n/a
##### Expected Results:

n/a
##### Actual Results:

n/a

**Comment by finn** [comment]
I'm flagging this for @mpdehaan @danieljaouen and @andrew-d to note that brew now has a programmatic json interface that can be used to query its formula state:

https://github.com/Homebrew/homebrew/wiki/Querying-Brew

It is invoked when passing the --json flag to the brew info command.

If someone wanted to adapt the homebrew module to use the json output from brew it should be much more reliable than manually parsing the human-readable output from the brew info command.

**Comment by danieljaouen** [comment]
Wow, useful!  I'll look into re-implementing some of the code tonight.

**Comment by danieljaouen** [comment]
@finn @jimi-c Just a quick update here: I've submitted a patch for this update which you can find here: https://github.com/ansible/ansible/pull/7458

**Comment by jimi-c** [comment]
@danieljaouen thanks, this one is still in queue to be reviewed.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by AnneTheAgile** [comment]
I don't think this one is yet ported to the new extras project.
AnneTheAgile
