### ISSUE TITLE
stat module documentation

### ISSUE THREAD

**Issue by twekberg** [ansible/ansible#7457]
##### Issue Type:

What kind of ticket is this?  “Documentation Report”
##### Ansible Version:

1.5.4
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Ubuntu 12.04
##### Summary:

The stat module exposes many attributes available via the stat function in the Python os module, and some additional attributes. These attributes should be mentioned in the documentation of the stat module. The attributes pw_name and isdir were used in the examples. I had to go to the source for the stat module to find the other attributes.

Here is what I would like to see added to the end of ansible/library/files/stat's DOCUMENTATION string. The only ones that I'm unsure about are pw_name, isgid and isuid.

returns: a stat object with the following attributes:
  atime - last access time
  ctime - last creation time
  dev - path's device
  exists - true if the file exists
  gid - path's group id
  inode - path's inode
  isblk - true if path is a block device
  ischr - true if path is a character device
  isdir - true if path is a directory
  isfifo - true if path is a fifo (a.k.a. named pipe)
  isgid - invoking group's id matches path's group id
  islnk - true if path is a symbolic link
  isreg - true if path is a regular file
  issock - true if path is a socket (a.k.a. UNIX Domain Socket)
  isuid - invoking user's id matches path's user id
  lnk_source - where path links to
  md5 - md5 checksum for path
  mode - the mode of path in 4 octal digits
  mtime - last modification time
  nlink - number of hard links to this path
  pw_name - owner of path
  rgrp - path mode: group read
  roth - path mode: other read
  rusr - path mode: user read
  size - size of path
  uid - path's user id
  wgrp - path mode: group write
  woth - path mode: other write
  wusr - path mode: user write
  xgrp - path mode: group execute
  xoth - path mode: other execute
  xusr - path mode: user execute

[I tried to paste in the .txt file, but only PNG, GIF and JPG are allowed.]
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by twekberg** [comment]
[vent on]
I'm not sure what's going on with Ansibot. I filled out the initial version of the ticket using the template. Perhaps it always sends out this notice saying 'I see you did not fill out your issue description based on our new issue template' even when that is not the case.
[vent off]

Tom Ekberg
Senior Computer Specialist, Lab Medicine
University of Washington Medical Center
1959 NE Pacific St, MS 357110
Seattle WA 98195
work: (206) 598-8544
email: tekberg@uw.edu

**Comment by sivel** [comment]
Your "issue type" is an h4 instead of an h5, indicating a missing '#', I believe that is the cause.

**Comment by twekberg** [comment]
I see - I didn't paste in the first character. Thanks!

**Comment by frio** [comment]
+1 for this information being included in the documentation.  I'm glad I found this ticket, because I wouldn't have thought to look in the Python stat module.

**Comment by ghost** [comment]
:+1: 

Finally found what I needed (i.e. methods on stat) here. Please include this in the documentation for stat.

**Comment by ciphernaut** [comment]
Please add to main documentation.  Having this information hidden makes it less useful from the onset.

**Comment by mattfinlayson** [comment]
+1 bump

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by shabbyrobe** [comment]
In case anyone else does what I did and finds this one on Google instead of the open one on the ansible-core page, here's the link:
https://github.com/ansible/ansible-modules-core/issues/107
