### ISSUE TITLE
RHEL for Edge package module support / new ansible_pkg_mgr

### ISSUE THREAD

**Issue by briansmith0** [ansible/ansible#74661]
### Summary

When running a playbook on a RHEL for Edge system (which uses rpm-ostree) and using the "package" module to validate a package is installed, it fails:
```
FAILED! => {"msg": "The conditional check 'not item in ansible_facts.packages' failed. The error was: error while evaluating conditional (not item in ansible_facts.packages): 'dict object' has no attribute 'packages'\n\nThe error appears to be in '/usr/share/linux-system-roles/crypto_policies/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# exist.\n- name: Ensure required packages are installed\n  ^ here\n"}
```
Ansible is detecting the ansible_pkg_mgr as "dnf":
```
ansible 192.168.122.195 -m ansible.builtin.setup -i inventory/ | grep pkg_mgr
        "ansible_pkg_mgr": "dnf",
```
There is another issue, https://github.com/ansible/ansible/issues/73084 which makes the assumption that RHEL for Edge should have ansible_pkg_mgr set to "atomic_container", however RHEL for Edge is different than Atomic and from what I understand will need a new "ansible_pkg_mgr" defined for it.   

From what I understand, Red Hat is not going to support installing additional packages with "rpm-ostree install".  If additional packages need to be added to the RHEL for Edge system, they need to be added to the ostree image and the RHEL for Edge system needs to be updated to the new image.  

However, there are many existing playbooks that use the "package" module to simply validate that a package is installed, which fail on RHEL for Edge even if the package is installed.  

The request is to have:

- A new ansible_pkg_mgr defined for RHEL for Edge
- The package module should be able to detect if a RPM package is installed on the RHEL for Edge system, and return success if it is.  
- The package module should gracefully fail if the specified package is not installed on the RHEL for Edge system, preferably with a message that the package needs to be added to the ostree image, and the system needs to be updated to the new image.  

This specific issue came up when testing RHEL System Roles / Linux System Roles on RHEL for Edge.  Many of these modules check to see if the package is installed (i.e. the timesync role validates that the chrony package is installed).  Even in cases where the RHEL for Edge system has the chrony package installed, the timesync role will still fail.  

### Issue Type

Feature Idea

### Component Name

package module

### Additional Information

Example playbook from Linux System Roles:  https://github.com/linux-system-roles/timesync/blob/master/tasks/main.yml

This playbook attempts to install chrony:
```
- name: Install chrony
  package:
    name: chrony
    state: present
  when:
    - timesync_mode != 2
    - timesync_ntp_provider == 'chrony'
```
This fails on a RHEL for Edge 8.3 system, even if the chrony package is installed on the system.  

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by brian999999** [comment]
@maxamillion has been involved in this discussion.

**Comment by jborean93** [comment]
The PR https://github.com/ansible/ansible/pull/74579 will fix up the `ansible_pkg_mgr` autodetection for RHEL edge but the problem around `package` picking up an ostree module to install is not something we are looking to fix. The recommended action is to either contribute an `ostree` package module in a collection and use the `use: namespace.name.ostree` parameter in package which can be templates for compatibility with other hosts.

**Comment by brian999999** [comment]
Hi @jborean93, it looks like https://github.com/ansible/ansible/pull/74579 would have RHEL for Edge set ansible_pkg_mgr set to "atomic_container", which is not correct (RHEL for Edge and Atomic are not the same).  @maxamillion might be able to explain this better than me, but from what I understand after talking to him, we need to have a new ansible_pkg_mgr defined to support RHEL for Edge.   

Also, regarding "package", I'm just requesting that on a RHEL for Edge system it has the ability to detect if a package is already installed and return success.  I am not requesting that the package module have the ability to install a missing package (which on RHEL for Edge would require a new image deployment).  

This is because many existing playbooks validate that packages are installed with the "package" module, and this fails on RHEL for Edge even if the package is already installed / included in the image.  

Thanks,
Brian

**Comment by sivel** [comment]
`ansible_pkg_mgr` needs to have a value that points to an existing ansible module for managing packages via that package manager.  It should not be set to an arbitrary value that is not linked against a non-existent ansible module.

We do not have an `ostree` module, and the only package manager we support at current would be `atomic_container` that can address these packages.

**Comment by brian999999** [comment]
I'm going to need to defer to @maxamillion to explain this better than I can.   I'll contact him and see if he can jump in this discussion here.

**Comment by maxamillion** [comment]
After reading the comments here, something I was thinking I could do is patch the `dnf` module detect that it's a RHEL for Edge and then validate the package is either installed or not installed and handle the scenario accordingly. The idea for RHEL for Edge is that the device itself doesn't actually do package management and the workflow is for an admin to build a new [rpm-ostree](https://coreos.github.io/rpm-ostree/) commit with [osbuild](https://www.osbuild.org/) and then have the devices apply the updates. The feature request as I understand it from @brian999999 is to have the validation occur and if the validation passes then return no change but otherwise fail the task, which I was originally thinking we would need to do via a change to the `ansible_pkg_mgr` fact but since there is no on-device supported package manager to install things, we can just throw some logic into the `dnf` to do the "yup, they're here" or "nope, failed" logic.

Thoughts?

**Comment by ikke-t** [comment]
My two cents here, I run into ansible handicap with rpm-ostree with fedora-iot a while back at https://github.com/ansible/ansible/issues/69565. As a friendly reminder, there is a use case in fedora-iot to install packages. There one can actually install packages using rpm-ostree. There has been couple of rpms I needed on Fedora-IoT, and it's super that I actually can install them as I don't control the base image. It's RHEL Edge that won't allow install, but in some cases one can install rpms.

Use case here: https://github.com/ikke-t/podman-container-systemd/blob/098e87beca8343dfb2bf48b38e571ca29f8f75ff/tasks/main.yml#L234

In Fedora-IoT, it would actually be nice to also just use ansible dnf/package module to install packages as well.

**Comment by maxamillion** [comment]
I'm sitting here because I can't sleep and I got thinking about this more. On second though, I don't really like what I wrote in https://github.com/ansible/ansible/issues/74661#issuecomment-840970530 and think I'll instead write an `rpm-ostree` module and patch to the fact discovery to set `ansible_pkg_mgr` to `rpm-ostree`. In the `rpm-ostree` we can detect if it's RHEL for Edge or not and if so then handle that, but if it's Fedora IoT or Silverblue then handle the overlay and/or override installation.

Thoughts?

**Comment by nullr0ute** [comment]
I think this is a difficult one, in all cases, whether we prefer it or not, users will likely layer packages, in Fedora IoT we discourage it too but users do.

I wonder if there's a way to delineate a "check it's there" vs a "install it if it's not". A sort of "if foo, configure bar, else do nothing but continue" style of functionality?

An example would be if a service is present we'd want to ensure it's got at least a minimal secure configuration, but if the service isn't there we don't necessarily want to install it but we also don't need to attempt to configure it.

**Comment by sivel** [comment]
> I wonder if there's a way to delineate a "check it's there" vs a "install it if it's not". A sort of "if foo, configure bar, else do nothing but continue" style of functionality?

There is a `package_facts` module which if it doesn't work currently could be extended to getting info about installed packages via `rpm-ostree`.

If you don't recommend actually installing, then `package_facts` seems like the right path.

**Comment by brian999999** [comment]
If possible, we would like to avoid having to build out custom logic in playbooks just for rpm-ostree systems like RHEL for Edge.   The specific use case I'm looking at is Linux System Roles (https://linux-system-roles.github.io/).  These roles use the package module to validate/install packages related to each role.   With RHEL for Edge, most of these packages are already going to be installed, but the role fails because the package module can't check if the package is installed on rpm-ostree systems.  

If the package module could detect that a package is installed on the RHEL for Edge system, most of these Linux System Roles would work without any modification.

**Comment by maxamillion** [comment]
I haven't had a chance to test this, but I just threw this together as a draft.

https://github.com/ansible/ansible/pull/77293

**Comment by jborean93** [comment]
Support for rpm ostree was implemented in [ansible.posix in this PR](https://github.com/ansible-collections/ansible.posix/pull/393).
