### ISSUE TITLE
Jinja2 deprecates overriding Context.resolve

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#74668]
### Summary

If we're on Jinja2 >= 3.0, override `resolve_or_missing` instead. See https://github.com/pallets/jinja/issues/1380 for more details.

### Issue Type

Bug Report

### Component Name

Jinja2 plugins

### Ansible Version

```console
(all)
```

### Configuration

```console
N/A
```

### OS / Environment

(Jinja2 >= 3.0)

### Steps to Reproduce

N/A

### Expected Results

N/A

### Actual Results

```console
N/A
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Since we override both `resolve_or_missing` and `resolve`, we aren't impacted by this warning.  The warning is only generated if you override `resolve` and not `resolve_or_missing`:

https://github.com/pallets/jinja/blob/be15556dbaebc4ab45d3f5f5d34874279831103c/src/jinja2/runtime.py#L179-L183

Because we override `resolve_or_missing` it will instruct newer jinja2 versions that we are not using "legacy_resolve_mode", and on older versions our custom `resolve` will still give us the features we need.  So there is no need to conditionally define our overrides, as the logic in `jinja2.runtime.Context` addresses this for us.
