### ISSUE TITLE
Allow collections to depend on roles

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#74979]
### Summary

I finally started moving some of my traditional Galaxy Roles to Collections... and already some users are noticing that the roles I include in my Collections, when they depend on someone else's role on Galaxy that's not yet been migrated to a Collection (and may never be depending on how willing the role author is to migrate it if and when migration is even possible...), are not able to automatically install, or force the run of the dependent role.

For example, I stripped out the role meta dependency from `geerlingguy.mac.homebrew` on the galaxy role `elliotweiser.osx-command-line-tools`, as from my previous discussion and reading of the docs on Collections, that role dependency would not result in anything anymore, as the metadata is all collection-level and doesn't incorporate anything from the roles _within_ the collection.

This could be an incorrect understanding... but I wanted to open this issue to request two things:

  1. (This seems like it may not have any internal support, but we'll see) When you `ansible-galaxy install` a collection, it can have dependencies on Galaxy _roles_, and not just collections, and those roles would be installed like any other role with an `ansible-galaxy role install xyz`.
  2. I can define role dependencies (maybe still in `meta/main.yml`'s `dependencies: []` list?) and when my collection role is called in a play, the dependent roles are called prior to it.

### Issue Type

Feature Idea

### Component Name

collections

### Additional Information

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by geerlingguy** [comment]
I should note the inverse of this issue was closed as 'won't fix' earlier this year. But this particular issue is more about making it possible to support _existing_ use cases while allowing role maintainers to migrate to Collections without upsetting the entire world of role-based Ansible usage using the deep pool of good community roles already available on Ansible Galaxy (many of which will either take time or will never be migrated to Collections).

**Comment by sivel** [comment]
You are correct. This was an intentional design decision that collections can only depend on other collections, and that stand alone roles depend on stand alone roles. They can be called from each other, but are purposefully lacking any supported dependency mechanism.

**Comment by geerlingguy** [comment]
@sivel - In that case, since the installation can at least still be made workable through `requirements.yml` files, would there be any consideration for having collection roles depend on other _collection_ roles even? E.g. `geerlingguy.mac.mas` depends on `geerlingguy.somethingelse.role`? I haven't even tested it, but I can imagine others moving from roles to collections may want to rely on that functionality (if it's not already there).

For myself, I rarely use role dependencies, but this is one of the collections where that is actually a valid issue as people are upgrading their playbooks and they never had to explicitly call to the dependent role before, and now they do.

**Comment by sivel** [comment]
Dependencies have to be specified at the collection level.  So `geerlingguy.mac` can already depend on `geerlingguy.somethingelse`.

**Comment by geerlingguy** [comment]
@sivel - But what I mean is when I run the role `geerlingguy.mac.something`, that role depends on `geerlingguy.somethingelse.anotherrole` — with traditional roles, you could define that in `meta/main.yml` and you wouldn't have to explicitly call `- include_role: geerlingguy.somethingelse.anotherrole` _before_ calling `geerlingguy.mac.something` when you want to include `geerlingguy.mac.something`.

**Comment by sivel** [comment]
> But what I mean is

Yes, that works currently.  You just also need to list the collection dependencies for installation.

**Comment by Tristan971** [comment]
> This was an intentional design decision that collections can only depend on other collections, and that stand alone roles depend on stand alone roles. They can be called from each other, but are purposefully lacking any supported dependency mechanism.

Would you happen to have some place where the rationale for this is documented?
Short of repackaging/vendoring existing role, this means a choice between the "future" (collections) on one end and almost all of the ecosystem on the other, so I'm curious what reason was compelling enough to justify it

**Comment by jborean93** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.
Our reasons for this are:

   * Unfortunately while we can understand why this is something that is desired we have no plan on implementing this feature at this point
   * We do somewhat support mixed dependencies with `ansible-galaxy install -r requirements.yml` but it's limited in what options can be run with that command
   * Ultimately we want collections and roles to be separate entities and don't want to complicate the code and UX of trying to manage both at the same time with the same command

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
