### ISSUE TITLE
[async_wrapper] Make random digit generation configurable.

### ISSUE THREAD

**Issue by swatinarvekar** [ansible/ansible#75331]
### Summary

Currently, Ansible Async wrapper is using a random 12 digit number along with time interval (which is 4 digit) while performing async call back to Ansible server and logging the same. 

`async_jid = str(random.randint(0, 999999999999))`

Example:
```
/var/log/messages
Jul 19 18:29:18 <*server_name*> su: (to root) *username* on pts/2
Jul 19 18:29:18 <*server_name*> su: (to root) *username* on pts/2
Jul 19 18:29:19 <*server_name*> ansible-async_wrapper.py: Invoked with 495007868633 1800 (***12 digit random number + 4 digit Time interval***) /var/tmp/ansible-tmp-1626719354.21-34347-162955661854519/AnsiballZ_command.py _
```

### Issue Type

Feature Idea

### Component Name
```
async
```

`Issues Faced`: While scanning the logs, Splunk servers are interpreting this 12 digit number followed by 4 digit time interval as Credit card and this is becoming a compliance issue.

**Comment by Akasurde** [comment]
!component =lib/ansible/plugins/action/__init__.py

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we are going to decline this request because this looks  like spelunk bug/misconfiguration, not a bug in Ansible, EVERY number length will seem like some thing (zip code, telephone number, ssn, other ids), as such and for the sake of keeping the 'job id' simple for users we are not going to make this change.

However, we're absolutely always up for discussion.  
Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  

You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
