### ISSUE TITLE
pkgng fails when a package has a comma in the name

### ISSUE THREAD

**Issue by anm** [ansible/ansible#7582]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

This was run on an ubuntu ansible host against a FreeBSD 10 box.
##### Summary:

pkgng fails when a package has a comma in the name
##### Steps To Reproduce:

Running:
`pkgng: name=nginx-1.6.0,2 state=present`

Gives:
`stderr: pkg: No packages matching 'nginx-1.6.0' available in the repositories`

Note absence of `,2` in the package it attempted to install.

Manually running `pkg install nginx-1.6.0,2` is successful.
##### Expected Results:

Package installed.
##### Actual Results:

Package not installed.

**Comment by mpdehaan** [comment]
This is probably because of the magic "with_items" joining behavior.

Any pointers to what a comma _does_ for pkg and why they didn't just use a
dot?  :)

**Comment by anm** [comment]
It seems to be part of the version number. I don't know why.

**Comment by bcoca** [comment]
It is used in freebsd, I forget the particulars, but it is not uncommon.

Brian Coca

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
