### ISSUE TITLE
Ansible role dependency handling for collections

### ISSUE THREAD

**Issue by papanito** [ansible/ansible#76030]
### Summary

When creating an ansible role you can specify the dependencies in `meta/main.yml` as follows

```
dependencies:
- role: papanito.xxx
```

How I do this, if `papanito.xxx` was converted into a collection? Or let's phrase it otherwise: How to I tell my role, that it depends on a module/role from a collection?

If I run `ansible-playbook` which uses a role, that has a dependency to a role in a collection, get the following error:

```
ERROR! the role 'papanito.xxx' was not found in ansible.legacy:
/home/papanito/Workspaces/devenv/roles:
/home/papanito/.ansible/roles:
/usr/share/ansible/roles:
/etc/ansible/roles:
/home/papanito/Workspaces/devenv/roles:
/home/papanito/Workspaces/devenv
```

As I can see ansible checks these paths for roles, however, collections are stored under `/home/papanito/.ansible/collections/ansible_collections/`.

Using `role: the_namespace.the_collection.the_role` does not solve the problem, but I still get the same error.

Further [the documentation](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-collections-in-roles) says

> Within a role, you can control which `collections` Ansible searches for the tasks inside the role using the collections keyword in the role’s `meta/main.yml`

So I updated `meta/main.yml` to

```yaml
collections:
- papanito.xxx
dependencies:
- role: papanito.xxx.xxx
```

Which still results in the exact same error as above when I run the playbook.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/collections_using.rst

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5] 
  config file = /home/papanito/Workspaces/devenv/ansible.cfg
  configured module search path = ['/home/papanito/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/papanito/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_BECOME(/home/papanito/Workspaces/devenv/ansible.cfg) = False
DEFAULT_HOST_LIST(/home/papanito/Workspaces/devenv/ansible.cfg) = ['/home/papanito/Workspaces/devenv/inventory.yml']
DEFAULT_REMOTE_USER(/home/papanito/Workspaces/devenv/ansible.cfg) = papanito
DEFAULT_TIMEOUT(/home/papanito/Workspaces/devenv/ansible.cfg) = 10
DEFAULT_VAULT_PASSWORD_FILE(/home/papanito/Workspaces/devenv/ansible.cfg) = /home/papanito/.ssh/papanito_devenv
RETRY_FILES_SAVE_PATH(/home/papanito/Workspaces/devenv/ansible.cfg) = /home/papanito/.ansible-retry
(END)
```

### OS / Environment

Archlinux

### Additional Information

Improving the documentation should make role owner clear, how they can use dependencies to roles on collections properly

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
A stand alone role is not meant to depend on a collection, just as a collection is not meant to depend on a stand alone role.

It can be achieved technically, but users will be requires to resolve the dependencies manually.

As such, collections should only depend on collections, and stand alone roles should only depend on stand alone roles.

**Comment by papanito** [comment]
Thanks for the quick reply. That's unfortunate as my standalone role depended on another standalone role which now is a collection. So as you say I have either to
- remove the dependency `metal/main.yaml` and tell the user in the `README.md` to install the respective collection. 
- or migrate my standalone role to a collection and then update `metal/main.yaml` ro use `collections`?

What I don't understand of the current [documentation](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-collections-in-roles) is this:

>  Within a role, you can control which collections Ansible searches for the tasks inside the role using the `collections` keyword in the role’s `meta/main.yml`

As I understand this - considering the example given - I could refer to a collection within a role

**Comment by papanito** [comment]
Thanks @sivel for clarifying

**Comment by Timoses** [comment]
We do have the issue the other way around.

We migrated to collections quite a while ago. However, we use quite a bit of roles from external sources. 

Since it is not possible to depend on a role from a collection we had to ourselves create forks of these roles wherein we transform these roles into collections.
This however is a huge maintenance burden on us. For example, if a role defines plugins we have to move these up 2 layers into the collection structure.


In my opinion this is a huge misstep in the introduction of collections. They should be able to depend on roles as it is not likely that everybody makes the transit to collections at the same time.

**Comment by papanito** [comment]
Yeah I actuality would like to see that you can depend on roles in collections and vice versa.

**Comment by Timoses** [comment]
Another comment I see fitting this issue: https://github.com/geerlingguy/ansible-role-postgresql/issues/186#issuecomment-979511064

**Comment by Mtze** [comment]
We're also migrating to collections at the moment but need external role dependencies (e.g. `geerlingguy.mysql`). I think it is quite common for collections to be dependent on other roles. Especially during transitions...

**Comment by williamhanseneric** [comment]
Add me to the list of those that believe not have dependency capability between collections and roles is a bad idea...

**Comment by max06** [comment]
And another one bites the dust. Can you please add support for depending on roles _and_ collections from a role or collection?

**Comment by sivel** [comment]
I'm going to proceed with closing this issue. There are no plans to allow dependencies between collections and stand alone roles.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by max06** [comment]
@Mtze there are 2 possible solutions, as stated in https://github.com/ansible/ansible/issues/77907#issuecomment-1137254399

**Comment by max06** [comment]
It sounds harsh, but I can now understand why other projects and developers, touching ansible, gave up. 

You, the maintainers, should start reading your own code of conduct.

**Comment by Timoses** [comment]
> @Mtze there are 2 possible solutions, as stated in [#77907 (comment)](https://github.com/ansible/ansible/issues/77907#issuecomment-1137254399)

Sorry, that is no proper solution to this issue.
Please see this for reasoning: https://github.com/ansible/ansible/issues/76030#issuecomment-958732624

Are there plans to deprecate roles completely? Otherwise installing them as dependencies from collections is a **MUST** feature, since nobody would be driven towards rewriting their roles into collections, and stumbling across roles would be a common sight. Having to maintain ones own forks just in order to turn upstream roles into collections is a maintenance burden which makes using Ansible with dependencies not very convenient. If not even setting a barrier which leads people to using other solutions and look elsewhere. Which is quite sad, as that is what Ansible is all about: Sharing IaC knowledge in an automated fashion. Proper dependency resolution is ... well a dependent factor.


What I have come across lately is a role like this one: https://galaxy.ansible.com/lean_delivery/java
It seems to be installable via Ansible Collections, however the Github Repo is a role (not a collection).
I haven't yet spotted how this works. Does anybody know that pattern? And whether it is usable without having to ask maintainers of upstream role repositories to do things differently (e.g. not depending on the good-heartedness of upstream maintainers to "properly adjust their roles to the lack of Ansible's ability to **itself** properly handle dependencies")?

**Comment by max06** [comment]
@sivel Care to explain the reasons?

**Comment by s-hertel** [comment]
I can try to clarify some of the technical obstacles of implementing this in ansible-galaxy (of course, there are more important factors). This is just my perspective, so take it with a grain of salt.

Role and collection dependencies are handled entirely separately in ansible-galaxy currently because roles are less structured than collections. The role dependency builder doesn't create a full dependency tree, just considers what's currently getting installed. Roles have no versioning schema, can be renamed at install-time, support extra source types, etc, so the first step would be to reconcile those differences, including making some backward-incompatible changes to standalone roles like requiring semantic versioning. Once that's done, the role dependency resolution in ansible-galaxy could be ported to resolve the full dependency tree in the same way as collections (still entirely separate from collections, just using common code).

ansible-galaxy doesn't look at roles in collections, so the next thing would be for Galaxy/AH to inspect collection content and support querying dependency information inside collection roles (and role collection requirements). Otherwise, all-potential collection/role candidates would need to be downloaded to a temp location just to inspect the cross-type requirements inside them and find the best candidates that are compatible with everything else, before installing.

Probably most importantly, we'd need thorough documentation for runtime corner-cases, since supporting installing cross-type dependencies would encourage their use and cause its own slew of confusion.

I'm sure more issues would crop up during implementation, but it seems like it would be possible at that point to update ansible-galaxy to handle roles and collections together and allow cross-type dependencies. I think it would be a significant undertaking and require work across multiple teams.

----

> We migrated to collections quite a while ago. However, we use quite a bit of roles from external sources.

@Timoses If your issue is mostly role runtime behavior (as opposed to ansible-galaxy stuff), this example works for me:
```
.
├── collections
│   └── ansible_collections
│       └── ns
│           └── coll
│               └── roles
│                   └── collection_role
│                       ├── meta
│                       │   └── main.yml
│                       │       │ # By default the collections search list is ['ns.coll', 'ansible.builtin']
│                       │       │ # ansible.builtin does not include legacy paths like library/
│                       │       │ collections: ['ns.coll', 'ansible.builtin', 'ansible.legacy']
│                       │       │
│                       │       │ # Although technically possible, this will require adding
│                       │       │ # the standalone role to the requirements.yml used to install
│                       │       │ # this collection. For example:
│                       │       │ # collections:
│                       │       │ #   - ns.coll
│                       │       │ # roles:
│                       │       │ #   - standalone_role
│                       │       │ dependencies: ['standalone_role']
│                       └── tasks
│                           └── main.yml
│                               │ - debug: msg='running collection_role'
│                               │ - module2: 
├── roles
│   └── standalone_role
│       ├── library
│       │   ├── module1.py
│       │   └── module2.py
│       └── tasks
│           └── main.yml
│               │ - debug: msg='running standalone_role'
│               │ - module1:
└── run_role.yml
    │ - hosts: localhost
    │   gather_facts: no
    │   tasks:
    │     - include_role: name=ns.coll.collection_role
```

> This however is a huge maintenance burden on us. For example, if a role defines plugins we have to move these up 2 layers into the collection structure.

Just in case you haven't found it already - here is a tool that can help alleviate some of the burden on role authors to port their content to a collection: https://github.com/ansible-community/role2collection

**Comment by papanito** [comment]
@s-hertel thanks for the info, that is indeed helpful to better understand the technical limitations
