### ISSUE TITLE
git clone folder creation could be more closely checked (edited description)

### ISSUE THREAD

**Issue by sethwoodworth** [ansible/ansible#7607]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3 (but unchanged in HEAD)
##### Environment:

N/A
##### Summary:

[git clone](https://github.com/ansible/ansible/blob/devel/library/source_control/git#L239) silently squashes exceptions when attempting to create new directories:

```
try:
    os.makedirs(dest_dirname)
except:
    pass
```

I get that this try-except block lets the function continue if the folder has already been created, but there are other exceptions that the function can and will throw. The `os.makedirs` source contains a safer except block:

```
    ...
    if head and tail and not path.exists(head):
    try:
        makedirs(head, mode)
    except OSError, e:
        # be happy if someone already created the path
        if e.errno != errno.EEXIST:
            raise
```

I suggest ansible employs the same, catching `OSError` and check that the error raised is due to the folder already existing.
##### Steps To Reproduce:

An example that might be applicable:
1. begin a git clone operation with ansible
2. evaluate a unicode string on a filesystem that is ASCII encoded
3. except block will eat the error and try to continue
##### Expected Results:

If `os.makedirs` fails, the relevant python error message should be thrown
##### Actual Results:

Ansible will attempt to continue sans folder(s) and throw a different issue

**Comment by mpdehaan** [comment]
While i understand the disclaimer against an unguarded except, do you have an example of this creating an actual problem?  

The git checkout should fail later on the missing head regardless of the case.

This is more of an example of trying to focus ticket discussion around actual bugs versus theoretical bugs, so I prefer bug reports that mention cause and effect, and don't particularly go into code particulars with a _theoretical_ cause an effect which may still be caught later in the app, as that can be somewhat time consuming to boil down in every instance of such a question.

Hope this makes sense

**Comment by jimi-c** [comment]
Hi @sethwoodworth,

I believe this situation has been corrected in recent updates to the git module (in at least 1.8.0, if I recall correctly). Since this is actually a module issue, it should have been moved to ansible/ansible-modules-core when we split those off, so I'm going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
