### ISSUE TITLE
ansible hangs when ssh running with "-tt"

### ISSUE THREAD

**Issue by Sec42** [ansible/ansible#76086]
### Summary

Running ansible with
```
[ssh_connection] 
ssh_args = -tt
```
in ansible.cfg makes ansible hang indefinitely.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
tested with
ansible 2.9.6
and
ansible 2.9.25
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/home/sec/Projects/ansible/ansible.cfg) = -tt
```

### OS / Environment

tested on
Ubuntu 20.04.3 LTS
and
Red Hat Enterprise Linux Server release 7.9

### Steps to Reproduce

```
ansible -vvv -i /tmp/inv -m setup all
```

/tmp/inv is simply:
```
[all]
munnvmonpmac11
```

### Expected Results

I expected ansible to continue to work.

I'm relatively sure it worked at some point in the past.

### Actual Results

```console
...
<munnvmonpmac11> ESTABLISH SSH CONNECTION FOR USER: None
<munnvmonpmac11> SSH: EXEC ssh -tt -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 munnvmonpmac11 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<munnvmonpmac11> (0, b'PLATFORM\r\nLinux\r\nFOUND\r\n/usr/bin/python\r\n/usr/bin/python3.6\r\n/usr/bin/python2.7\r\n/usr/libexec/platform-python\r\n/usr/bin/python3\r\n/usr/bin/python\r\nENDFOUND\r\n', b'Shared connection to munnvmonpmac11 closed.\r\n')
<munnvmonpmac11> ESTABLISH SSH CONNECTION FOR USER: None
<munnvmonpmac11> SSH: EXEC ssh -tt -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 munnvmonpmac11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''

indefinite hang here.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * See above https://github.com/ansible/ansible/issues/76086#issuecomment-946892715

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
