### ISSUE TITLE
lookup file no longer searches root directory

### ISSUE THREAD

**Issue by phy1729** [ansible/ansible#7628]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 6bc056e012) last updated 2014/06/01 15:17:10 (GMT -500)
##### Environment:

running from OSX 10.7
remote is Debian stable
##### Summary:

The lookup file plugin no longer searches the root of the project for the file.
##### Steps To Reproduce:

Use `lookup('file','<relative path from root of project>')` in `vars/main.yml`
##### Expected Results:

For the variable to have the contents of the file.

My case:
For `nslcd_bind_user` and `nslcd_bind_passwd` to have the contents of `secret/nslcd_bind_user` and `secret/nslcd_bind_passwd` respectively.
##### Actual Results:

The variables are blank.

My case:
(All paths are relative to my github repo at https://github.com/phy1729/cv_config )

After commit e83a494 the varibles `nslcd_bind_user` and `nslcd_bind_passwd` (defined in `roles/nslcd/vars/main.yml`) would always be blank instead of having the value in the respective files. 

Now it because of commit 2fda9bc the `ssh-box.yml` playbook fails after GATHERING FACTS on TASK: [base | Set hostname] with:
    fatal: [c] => /Users/phy1729/cv_config/roles/base/files/secret/nslcd_bind_user does not exist

**Comment by jimi-c** [comment]
The change done by commit e83a494 has actually since been reverted, so I don't think that should be the problem any longer, and the later one is probably just catching the error it should. I see the file lookup uses listify_lookup_plugin_terms(), which was also causing problems with the `env` lookup plugin after e83a494 too, so it may be because of that. Could you try the following patch to see if it resolves your issue?

<pre>
diff --git a/lib/ansible/runner/lookup_plugins/file.py b/lib/ansible/runner/lookup_plugins/file.py
index d5291c2..d9bf3d8 100644
--- a/lib/ansible/runner/lookup_plugins/file.py
+++ b/lib/ansible/runner/lookup_plugins/file.py
@@ -16,6 +16,7 @@
 # along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
 
 from ansible import utils, errors
+from ansible.utils import template
 import os
 import codecs
 
@@ -26,7 +27,11 @@ class LookupModule(object):
 
     def run(self, terms, inject=None, **kwargs):
 
-        terms = utils.listify_lookup_plugin_terms(terms, self.basedir, inject)
+        try:
+            terms = template.template(self.basedir, terms, inject)
+        except:
+            pass
+
         ret = []
 
         # this can happen if the variable contains a string, strictly not desired for lookup
</pre>

UPDATE: forgot the include of the template module in the first version of this patch.

**Comment by phy1729** [comment]
With that patch I get the same error as before.

**Comment by jimi-c** [comment]
@phy1729 could you paste in a small example playbook that reproduces this error for you? Thanks!

**Comment by phy1729** [comment]
https://github.com/phy1729/ansible-issue7628-example will reproduce it with just `vagrant up`

**Comment by jimi-c** [comment]
I've merged the above patch into the devel branch to address this issue. The file lookup will now check the base directory of the lookup, and then check for the relative paths based on the "files" directory (for roles) and the current playbook directory. This works with the example you provided, but please let us know if you see any further issues regarding this. Thanks!

**Comment by phy1729** [comment]
Confirmed fixed. Thanks!
