### ISSUE TITLE
Variables passed in as paramaters to includes are not available to handlers

### ISSUE THREAD

**Issue by simonft** [ansible/ansible#7663]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Ubuntu 12.04
##### Summary:

When I pass a variable in as a parameter to an include, then try to use that variable in a handler, the variable is not there. James Cammarata [says](https://groups.google.com/forum/#!topic/ansible-project/rGEi9_5mShI) "As far as I can tell, variables passed in as params to includes have never been merged into the global list of variables (I've gone back to 1.3.0 to test your example)."
##### Steps To Reproduce:

Create the following files: 

```
# test.yml

---
- hosts: deployservers
  remote_user: root
  roles:
  - test
```

```
# roles/test/tasks/main.yml 

---
- include: test.yml test_var="this is a test"
```

```
# roles/test/tasks/test.yml

---
- debug: var=test_var

- command: /bin/true
  notify:
  - test test_var
```

```
#  roles/test/handlers/main.yml

---
- name: test test_var
  debug: var=test_var
```

Then run ansible-playbook test.yml 
##### Expected Results:

The cow for the notified debug task should look like this (the variable exists, with the correct string):

```
 _________________________________
< NOTIFIED: test | test test_var >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [ansible.example.com] => {
    "item": "", 
    "test_var": "this is a test"
}
```
##### Actual Results:

The cow for the notified debug task looks like this (the variable is not existent):

```
 ________________________________
< NOTIFIED: test | test test_var >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [ansible.example.com] => {
    "item": "", 
    "test_var": "{{ test_var }}"
}
```

**Comment by jimi-c** [comment]
Hi @Simonft, going back through old issues, and after review I believe this would be expected. Parameterized variables (for both roles and task includes) do not end up in the global pool of variables, and essentially act as variables just for the tasks which are brought in, respectively for roles and includes. Since the handler is outside of the include, it will never see the variable passed in as a parameter. In this situation, the use of a role would be better, as both the tasks and the handlers for that role would see any parameterized values.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
