### ISSUE TITLE
Vagrant guide outdated

### ISSUE THREAD

**Issue by maspwr** [ansible/ansible#7665]
##### Issue Type:

Documentation Report
##### Ansible Version:

master
##### Environment:

N/A
##### Summary:

The [Vagrant guide](https://github.com/ansible/ansible/blob/9b52ce8a427a1bfc1f7f68718c43dcc991a403a4/docsite/rst/guide_vagrant.rst) is slightly outdated.  For example, Vagrant no longer creates multiple inventory files in the same directory.

/cc @gildegoma
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Something you might like to work on helping to upgrade (the docs are in source control, so it's easy to take pull requests on them).

**Comment by maspwr** [comment]
Yep, I don't mind updating it when I get some time soon.  Just wanted to track that it was outdated in case someone gets to it before I do.

**Comment by gildegoma** [comment]
A few notes:
- It could be useful to mention which version of Vagrant is covered by the guide (currently based on Vagrant 1.4 features). 
- I've just noticed that PR #7314 addresses the "single inventory" introduced in Vagrant 1.5.
- There are also other changes since 1.5 (like `ansible.host_key_checking` which is now disabled by default). See https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md
- More generally, I'd love to coordinate the "content cooperation" between this guide and http://docs.vagrantup.com/v2/provisioning/ansible.html

**Comment by gildegoma** [comment]
@maspwr I created #9890. Could you please have a look into it? Many thanks in advance for your help :)

**Comment by maspwr** [comment]
@gildegoma Commented on the PR. Thanks!

**Comment by jimi-c** [comment]
The above PR was merged, so we're going to go ahead and close this. Sorry for the late follow-up, and thanks!
