### ISSUE TITLE
Split "ansible_shell_type" into "ansible_local_shell_type" and "ansible_remote_shell_type"

### ISSUE THREAD

**Issue by nekopep** [ansible/ansible#76773]
### Summary

I am in a particular case of a linux host trying to control a remote windows through openssh.
As documented in recent ansible version, openssh can be used to control a windows machine.
Everything work, but sadly, ansible.builtins.copy and ansible.windows.win_copy, nor ansible.posix.synchronize works.

In fact ansible.windows.win_copy use winrm protocol so is a nogo.
ansible.builtins.copy, ansible.posix.synchronize could work, but because to make openssh work on windows you must specify "ansible_shell_type" = cmd or powershell, the local commands like scp or rsync or even command run with "local_action:" can't be run because powershell is launched on the linnux host!

I propose to set up two variable:
ansible_local_shell_type and ansible_remote_shell_type, to solve such corner case when the two os have different shell.

For compatibility reason, we could keep ansible_shell_type for remote and ansible_local_shell_type when set coudl force the local shell.

### Issue Type

Feature Idea

### Component Name

builtins

### Additional Information

```yaml (paste below)
- name: basic touch not working with linux -> openssh -> windows
  local_action: ansible.builtin.command touch test
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
> Everything work, but sadly, ansible.builtins.copy and ansible.windows.win_copy, nor ansible.posix.synchronize works.

This is true with `copy` and `synchronize`, `copy` is a Python module designed for POSIX compliant hosts which Windows is not and `synchronize` most likely relies on features not available on the Windows port of OpenSSH. The `win_copy` definitely works as it offers `scp`, `sftp` and a way to pipe data which we even test in CI. In fact `copy` may even work due to how it transparently converts module calls for `copy`, `stat`, `file` to the `win_` variant if it detects that Windows is in use (the powershell or cmdl shell plugin is being used). If you are having issues with `win_copy` and `ssh` please share the errors you are getting as it should work.

The variablle `ansible_shell_type` controls what shell plugin is used for the remote host, it shouldn't be affecting what the local shell unless localhost is your target. The `sychronize` action plugin might muddy that up a bit as it does some weird and complex things but it's not something we've ever tried to get working with Windows and most likely won't be something we ever wish to get working on Windows.

**Comment by nekopep** [comment]
I just tried back win_copy ,and it worked! ... Sorry for the noise. I don't know what changed, but because you said it is normal that it works I'm happy.  You gave me really good technical explanation.
Thank you so much, I can continue my ansible travel.

**Comment by jborean93** [comment]
No worries, feel free ot reach out in IRC or the mailing list if you have further questions. SSH on Windows is fairly new but I'm not aware of any fundamental limitation of it compared to Windows over WinRM so things should just work as they did before.

**Comment by bcoca** [comment]
in any case, you can set a different `ansible_shell_type` for the remote than for 'localhost', so no real need for 2 variables, even in the case they solved your issue.
