### ISSUE TITLE
Missing attribute in AnsibleModule "safe_eval"

### ISSUE THREAD

**Issue by cloudnull** [ansible/ansible#7679]
##### Issue Type:

Missing Attribute from AnsibleModule
##### Ansible Version:

``` shell
# ansible --version
ansible 1.6.2
```
##### Environment:

``` shell
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.4 LTS"
```
##### Summary:

When the AnsibleModule has a option with the `type='dict'` the method `_check_argument_types` attempts to do a `json.loads(value)` and if the value is not valid json an exception is raised which then attempts to perform a "safe_eval" in an effort to load the dictionary. Sadly the 'safe_eval' is not a valid AnsibleModule attribute.

Line Number:
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L712-L728
##### Steps To Reproduce:

Create a simple module which uses the option `type='dict'`

``` python
def main():
    """Ansible Main module."""
    module = AnsibleModule(
        argument_spec=dict(
            options=dict(
                type='dict'
            )
        )
    )
```
##### Expected Results:

This should provide a dictionary which would then be available within `module.params.get('option')`
##### Actual Results:

raises an exception

``` shell
fatal: [HOSTNAME] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/TEMPFILE/MODULENAME", line 2311, in <module>
    main()
  File "/root/.ansible/tmp/TEMPFILE/MODULENAME", line 1094, in main
    supports_check_mode=False,
  File "/root/.ansible/tmp/TEMPFILE/MODULENAME", line 1323, in __init__
    self._check_argument_types()
  File "/root/.ansible/tmp/TEMPFILE/MODULENAME", line 1823, in _check_argument_types
    (result, exc) = self.safe_eval(value, dict(), include_exceptions=True)
AttributeError: 'AnsibleModule' object has no attribute 'safe_eval'

FATAL: all hosts have already failed -- aborting
```

**Comment by dpereira-daitan** [comment]
Any known workaround?

**Comment by dpereira-daitan** [comment]
The same error will occur if the method _check_argument_types ( https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L773-L774 ) is called - even for a valid json.

The workaround would be changing the syntax to use equal instead of a json.
Instead of: 
{"InstanceId":"{{ec2_facts.ansible_facts.ansible_ec2_instance_id}}"}
Use:
"InstanceId"="{{ec2_facts.ansible_facts.ansible_ec2_instance_id}}"

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
