### ISSUE TITLE
I removed myself from the sudo group. Does the 'user' module's documentation need an extra warning?

### ISSUE THREAD

**Issue by mascip** [ansible/ansible#7681]
Hi, I followed the example given in the user module's documentation, here: http://docs.ansible.com/user_module.html

```
# Add the user 'johnd' with a specific uid and a primary group of 'admin'
- user: name=johnd comment="John Doe" uid=1040 group=admin
```

I wanted to add myself to the 'docker' group, so I used this on myself, on localhost. Very silly.

I think we could add this word of warning for this example: 

```
# Beware: the user will be removed from any other group
```

I would also add this warning in the synopsis:

```
Beware: by using this module you risk removing yourself from the 'sudo'  group.
Read the documentation thoroughly.
```

I know, dealing with devops tools, one should always read the documentation thoroughly. I still think that others will do the same mistake I did. An extra word of warning about this module could save some from disasters.

**Comment by bcoca** [comment]
This is why you have append=yes, fyi, this problem exists when using the
usermod command itself.​ I believe this happens to every admin at least
once ;-)

the docs are part of the repo, I'm pretty sure that they will welcome a PR
to it.

**Comment by mascip** [comment]
Cheers, will send a PR soon :-)
I'm working like crazy on a deadline this week end and in the next few
days, so it will be a bit later.

-- Pierre Masci

**Comment by mscherer** [comment]
@mascip  any link to the PR ?

**Comment by bcoca** [comment]
It is already clearly stated in the docs

groups:
        required: false
        description:
            - Puts the user in this comma-delimited list of groups. When
set to
              the empty string ('groups='), the user is removed from all
groups
              except the primary group.

append:
        required: false
        default: "no"
        choices: [ "yes", "no" ]
        description:
            - If C(yes), will only add groups, not set them to just the list
              in I(groups).

On Sun, Sep 21, 2014 at 11:20 AM, mscherer notifications@github.com wrote:

> @mascip https://github.com/mascip any link to the PR ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/7681#issuecomment-56301935.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
