### ISSUE TITLE
max_fail_percentage not honoured if host not reachable

### ISSUE THREAD

**Issue by recursify** [ansible/ansible#7686]
I have 1 host that cannot be reached at the `GATHERING FACTS` stage, attempting to deploy to 3 hosts, and have `max_fail_percentage` set to 0.  The playbook continues with the remaining 2 hosts.  Is this the expected behaviour?  It was certainly a surprise to me.

If one of the tasks in the playbook fail, then the `max_fail_percentage` works as expected.

```
GATHERING FACTS ***************************************************************
fatal: [IP_REDACTED] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
ok: [IP_REDACTED]
ok: [IP_REDACTED]

TASK: [bootstrap | Install common packages via YUM] ***************************
ok: [IP_REDACTED] => (item=htop,tmux,ntp,emacs,gcc)
ok: [IP_REDACTED] => (item=htop,tmux,ntp,emacs,gcc)
```

**Comment by jimi-c** [comment]
This is more of a mailing list question, but yes - this is expected behavior. If a host is unreachable, it will be taken out of the list of hosts. Furthermore, `max_fail_percentage: 0` doesn't quite work the way you think - even set at 0 a failed task will mean no further tasks will be executed on that host.
