### ISSUE TITLE
[git] A repo checked out with depth cannot be moved to a different version

### ISSUE THREAD

**Issue by FiloSottile** [ansible/ansible#7693]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.5.5
##### Environment:

OS X manager
Ubuntu target
##### Summary:

The git module performs a checkout to change the version, but that fails in a shallow clone (`depth=1`).
##### Steps To Reproduce:

Cosider this task:

``` yaml
git: dest={{ hub }} repo={{ hub_repo }} depth=1 version={{ hub_rev }}
```

Run it once. Then run it again with a different `hub_rev`. It should just work, as it is supposed to be idempotent. Instead:

```
failed: [1.2.3.4] => {"failed": true, "item": ""}
msg: Failed to checkout origin/classes_log
```

Remove the old repository clone and it will work again.

**Comment by jimi-c** [comment]
If the hub_rev is different, I definitely would not expect this to be idempotent - you've changed something after all. Also, wouldn't this be a limitation of limiting the depth of the tree? Is the version your specifying on the same branch as the first checkout, since by default using depth also limits the checkout to a single branch (unless you also specify --no-single-branch, which I don't think the command does right now).

**Comment by FiloSottile** [comment]
I'm sure this is a limitation of the shallow clone, but I believe
Ansible should workaround it.

With that task I'm telling Ansible to put that repo at that rev in that
place. Nothing rings idempotency exception to me.

**Comment by cjunge-work** [comment]
I've also found this problem. In addition, removing the depth parameter requires deleting the clone and re-cloning it.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
