### ISSUE TITLE
lookup('password', ...) different in template and role

### ISSUE THREAD

**Issue by harris1** [ansible/ansible#7706]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 
##### Environment:

Ubuntu 12.04
##### Summary:

lookup('password') looks in different directories depending if it's used in a template or a tasks file.
##### Steps To Reproduce:

See example above.
##### Expected Results:

One password to be created and used in both places:

```
TASK: [test | Password in Role] ***********************************************
ok: [ansibletest] => {
    "msg": "G6rNO6_YEQFR6WCFFgDa"
}

$ cat /tmp/pass.conf
password = G6rNO6_YEQFR6WCFFgDa
```
##### Actual Results:

Two passwords are created, in roles/test/tasks/credentials/test-pass (JiCZ password) and credentials/test-pass (G6rN password):

```
TASK: [test | Password in Role] ***********************************************
ok: [ansibletest] => {
    "msg": "JiCZ6d4,j0o7hxg87h--"
}

$ cat /tmp/pass.conf
password = G6rNO6_YEQFR6WCFFgDa
```

**Comment by harris1** [comment]
Lost test case from "above". Happens 

play.yml

```
---
- hosts: all
  roles:
    - test
```

roles/test/tasks/main.yml

```
---
- name: Password in Role
  debug: msg={{ lookup('password', 'credentials/test-pass') }}

- name: Password in Template
  template: src=pass.conf dest="/tmp/pass.conf"
```

roles/test/templates/pass.conf

```
password = {{ lookup('password', 'credentials/test-pass') }}
```

**Comment by zxaos** [comment]
This issue has existed since 1.6.8 (at least, since I'm encountering it there), although it seems to prefer roles/files/credentials/pass.conf as the path rather than roles/tasks/credentials/pass.conf.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [test : test : Password in Role] *******************************************
ok: [localhost] => {
    "msg": "7SMTZ-wp8b7noDhxKas_", 
    "changed": false
}
TASK [test : test : Password in Template] ***************************************
changed: [localhost] => {"src": "/root/.ansible/tmp/ansible-tmp-1434952673.91-260521761279509/source", "md5sum": "860e5cc426eb40061354ef558383c944", "group": "root", "uid": 0, "dest": "/tmp/pass.conf", "checksum": "c0619f86bea720a64e3a9fdee1d0f6e3ebc8823c", "changed": true, "owner": "root", "state": "file", "gid": 0, "secontext": "unconfined_u:object_r:user_tmp_t:s0", "mode": "0644", "invocation": {"module_name": "copy", "module_args": {"dest": "/tmp/pass.conf", "src": "/root/.ansible/tmp/ansible-tmp-1434952673.91-260521761279509/source", "original_basename": "pass.conf", "follow": true}}, "diff": {"after": "password = 7SMTZ-wp8b7noDhxKas_\n", "before": ""}, "size": 32}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
# cat /tmp/pass.conf 
password = 7SMTZ-wp8b7noDhxKas_
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
