### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded on nested `all` group

### ISSUE THREAD

**Issue by cypreess** [ansible/ansible#7708]
##### Summary:

When constructing nested group with `all` hosts recursion occurs, which throws python exception.
##### Steps To Reproduce:

Construct following groups in inventory file:

```
some.host

[nesting_group:children]
all
```
##### Expected Results:

I was hoping ansible would put all "other" hosts into this group. This way I would like to add all hosts from this inventory to specific group to bind them with some specific group_vars.
##### Actual Results:

Raises python exception `RuntimeError: maximum recursion depth exceeded.`

**Comment by mpdehaan** [comment]
"This way I would like to add all hosts from this inventory to specific group to bind them with some specific group_vars."

But all your hosts in a group called foo

But that group foo under "nesting_group:children"

That'll do it.

A traceback is a bug - regardless - but what you have won't be a thing :)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
