### ISSUE TITLE
File module fails to make relative symlinks

### ISSUE THREAD

**Issue by phy1729** [ansible/ansible#7711]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 0073b34653) last updated 2014/06/10 02:55:50 (GMT -500)
##### Environment:

Running from OSX 10.7
Remote is Debian stable
##### Summary:

The file module errors on relative links.
##### Steps To Reproduce:

Make /tmp/foo/foo
Try to symlink /tmp/bar/bar to ../foo/foo
##### Expected Results:

For the link to succeed.
##### Actual Results:

```
failed: [default] => {"failed": true, "gid": 1000, "group": "vagrant", "mode": "0777", "owner": "vagrant", "path": "/tmp/bar/bar", "size": 10, "src": "../foo/foo", "state": "link", "uid": 1000}
msg: src file does not exist, use "force=yes" if you really want to create the link: /tmp/bar/foo
```

**Comment by phy1729** [comment]
Repo with minimal example and Vagrantfile: https://github.com/phy1729/ansible-issue7711-example

Forgot to mention that bisect indicates the issue arose after 062e829.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
