### ISSUE TITLE
ec2_vol errors when attaching a volume from a snapshot

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#7719]
**Issue type:**

Bug report

**Ansible Version:**

1.6.2

**Environment:**

Mac OS X 10.9.3

**Summary:**

ec2_vol module fails to create a new volume from a snapshot and attach to an image, returning an error message that doesn't make sense given the arguments.

**Steps to reproduce:**
1. Start an instance on EC2, record the instance id
2. Create a new snapshot on EC2, record the snapshot id
3. Use the ec2_vol module to attach:
   
   ```
   ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
   ```

**Expected results:**

Creates a new EBS volume from the snapshot, attaches volume to the instance.

**Actual results:**

```
$ ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
localhost | FAILED >> {
    "failed": true,
    "msg": "Cannot specify volume_size and either one of name or id"
}
```

The error makes no sense, given that neither volume_size, name, nor id are arguments.

Note that the documentation for ec2_vol has an example with this exact combination of arguments, so I assume this is legal. From the docs:

```
# Example using snapshot id
- local_action:
    module: ec2_vol
    instance: XXXXXX
    snapshot: "{{ snapshot }}"
```

**Comment by shaunbrady** [comment]
Now that is a coincidence.   I was about to issue this pull request:

```
sbrady@excalibur:~/git/ansible$ git diff
diff --git a/library/cloud/ec2_vol b/library/cloud/ec2_vol
index 59347a6..4a7dcdc 100644
--- a/library/cloud/ec2_vol
+++ b/library/cloud/ec2_vol
@@ -325,7 +325,7 @@ def main():
     if id and name:
         module.fail_json(msg="Both id and name cannot be specified")

-    if not (id or name or volume_size):
+    if volume_size and (id or name):
         module.fail_json(msg="Cannot specify volume_size and either one of name or id")

     # Here we need to get the zone info for the instance. This covers situation where
```

This logic matches the comments and does the correct thing for the use case that we both had.

True table difference:
sbrady@excalibur:~$ python /tmp/tt.py 
them    me    x  y  z
False True is True and True and True
False True is True and True and False
False True is True and False and True
False False is True and False and False
False False is False and True and True
False False is False and True and False
False False is False and False and True
True False is False and False and False
sbrady@excalibur:~$

**Comment by lorin** [comment]
@shaunbrady Nice... :thumbsup:

**Comment by shaunbrady** [comment]
https://github.com/ansible/ansible/pull/7722

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by lorin** [comment]
Created https://github.com/ansible/ansible-modules-core/issues/139
