### ISSUE TITLE
Git clone hangs at ls-remote waiting for password

### ISSUE THREAD

**Issue by makmanalp** [ansible/ansible#7720]
##### Issue Type:

 “Bug Report”
##### Ansible Version:

```
$ ansible --version
ansible 1.6.2
```
##### Environment:

OSX 10.9.2 host, ubuntu trusty 64 guest on virtualbox
##### Summary:

Ansible git module hangs on clone without telling us what happened
##### Steps To Reproduce:

Something like:

```
- name: get code
  git: repo=https://github.com/cid-harvard/observatory-economic-complexity.git
       dest=/foo/bar
       version=master
```
##### Expected Results:

Timeout after a while, maybe detect that password was needed.
##### Actual Results:

Hangs forever with no indication of what's happening. `ps -ejHf` tells me:

```
--- snip ---
root      7284  7283  7280  7280  0 00:59 pts/0    00:00:00               /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1402448111.16-232225376669841/git
root      7285  7284  7280  7280  0 00:59 pts/0    00:00:00                 /usr/bin/git ls-remote https://github.com/cid-harvard/observatory-economic-complexity.git -h ref
root      7286  7285  7280  7280  0 00:59 pts/0    00:00:00                   git-remote-https https://github.com/cid-harvard/observatory-economic-complexity.git https://gi
---snip---
```

and `git ls-remote https://github.com/cid-harvard/observatory-economic-complexity.git` just brings the user prompt: `Username for 'https://github.com':` (which is odd in itself since you'd expect a public repo to not require passwords for ls-remote)

**Comment by makmanalp** [comment]
Also should note that git clone on that same url works fine without a password.

**Comment by jimi-c** [comment]
Are you sure this is a public repo? Looking at https://github.com/cid-harvard/ I do not see that repo listed, and if I run the ls-remote command against the atlas-playbooks repo it works fine. Either that repo doesn't exist there, or it is private (which would explain why credentials are being requested).

If you do need credentials for this, I would recommend using the `git://` URL instead of https.

If you have any further questions regarding this, please let us know. Thanks!

**Comment by makmanalp** [comment]
Oops, I think it's an artifact of an old repo rename: github forwards the requests to the old repo url but I guess the credentialing behavior is slightly different.
