### ISSUE TITLE
Bundling Playbooks within a Collection

### ISSUE THREAD

**Issue by monsdar** [ansible/ansible#77285]
### Summary

I want to distribute a playbook in one of my collections. The docs are stating that this is possible:
* [Developing collections #playboos-directory](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#playbooks-directory)

However I do not find an example of how this could be done:
* Above mentioned docs only show the directory sturcture, not where the playbook-file needs to be placed nor any examples.
* When using `ansible-galaxy collection init ...` a skeleton is created but it does not contain a `playbooks` directory where I could check how this is done by default.
* I found the right command to call in [this Pull Request](https://github.com/ansible/ansible/pull/67435), but there is no further info about the structure needed in the collection.

In the end I tried just putting a `test.yml` file containing a simple playbook into `namespace/collection/playbooks/` but when using that collection Ansible states that `ERROR! the playbook: namespace.collection.test could not be found`.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/dev_guide/developing_collections_structure.rst

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=3600s
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'community.vmware.vmware_vm_inventory']
```

### OS / Environment

Ubuntu 20.04

### Additional Information

Having examples available would help to better understand how this feature is meant to work.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by monsdar** [comment]
Looks like somehow an old version of Ansible found it's way onto my machine. Problem is resolved after updating to the latest version available (>2.11). Leaving this issue open as docs could still be improved.

**Comment by samccann** [comment]
Thanks @monsdar for the Ansible docs issue.

Discussing this in the community matrix/irc channel, we came up with the following to add to the docs.

Edit https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_collections_structure.rst to:

Clarify that playbooks within a collection follow the same guidelines as any playbooks except:
  - must be in /playbooks directory
  - hosts: Consider defining a host as a variable so the users of your playbook do not mistakenly run the plays against their entire inventory (if the host is set to all)
   e.g. hosts: '{{target|default("all")}}'

then the user does: ansible-playbook --e 'targets=webservers'

or if no host set, recommend user uses --limit webservers

Either way, the collection owner should document their playbooks and how to use them in the /docs folder or README file.

PR most welcome if you feel up to making these edits. They are simple enough that you could just use the little pencil icon on the above link to make the changes and create a quick patch PR:
![image](https://user-images.githubusercontent.com/30267855/158870476-5be12ad7-e2be-4019-88c0-66603e1f19f8.png)

Otherwise we'll add this issue to the docs backlog. 
Thanks again for highlighting the difficulties here and where we need more info!

**Comment by DesmondSanctity** [comment]
I want to work on this
