### ISSUE TITLE
module_defaults cannot be set using a variable any more

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#77344]
### Summary

Before commit 3b861abce13c541c1fc41e59d631e76d2564582a, it was possible to set module_defaults using a variable. This does not work anymore.

You may argue that this was not supposed to work anyway, although it worked perfectly. But imagine having a long list of module defaults (>100 lines of yaml code) that you have to copy around all your dozens of playbooks. This becomes unmaintainable.

### Issue Type

Bug Report

### Component Name

module_defaults

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.9]
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/projects/twmn/data/deps/python/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nikos/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nikos/projects/twmn/data/deps/python/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Arch linux

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  connection: local
  module_defaults: "{{ defaults }}"
  tasks:
    - file:
        path: /tmp/dfdfdf
```

Run with:

```
ansible-playbook -e defaults="{'ansible.builtin.file':{'state':'absent'}}" playbook.yml
```

### Expected Results

I would expect ansible to use the defaults I supplied.

### Actual Results

```console
ERROR! The field 'module_defaults' is supposed to be a dictionary or list of dictionaries, the keys of which must be static action, module, or group names. Only the values may contain templates. For example: {'ping': "{{ ping_defaults }}"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
Hi!

Thanks very much for your interest in Ansible.  It means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

In the linked commit there is a breaking change entry that states https://github.com/ansible/ansible/commit/3b861abce13c541c1fc41e59d631e76d2564582a#diff-87683a122e003f78dfb047ade864420c980475779b63275e062101088522f0f9R4

> - Action, module, and group names in module_defaults must be static values. Their values can still be templates.

This was an explicit decision as trying to support variable expansion at playbook parse time won't have the full range of values that people would typically expect at that time. If there was a way to lazily expand the keys that would be another story but for now we don't wish to expose a half baked implementation and cause all sorts of undocumented behaviour.
