### ISSUE TITLE
ini_file module fails with ConfigParser.InterpolationError

### ISSUE THREAD

**Issue by xcezx** [ansible/ansible#7743]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.6.2
```
##### Environment:

N/A
##### Summary:

`ini_file` module fails with `ConfigParser.InterpolationError`.
##### Steps To Reproduce:

Try to run such task:

```
- hosts: localhost

  tasks:
    - name: deploy ini file
      copy:
        content: |
          ; ~/sample.ini
          [DEFAULT]
          foo = %(bar)s
        dest: ~/sample.ini

    - name: configure ini file
      ini_file: dest=~/sample.ini section=DEFAULT option=foo value=xxx
```
##### Expected Results:

Changed `~/sample.ini` such as:

```
; ~/sample.ini
[DEFAULT]
foo = xxx
```
##### Actual Results:

Ansible crashes with

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "(...)/ini_file", line 1397, in <module>
    main()
  File "(...)/ini_file", line 182, in main
    changed = do_ini(module, dest, section, option, value, state, backup)
  File "/(...)/ini_file", line 130, in do_ini
    oldvalue = cp.get(section, option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 669, in _interpolate
    option, section, rawval, e.args[0])
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [DEFAULT]
        option : foo
        key    : bar
        rawval : %(bar)s

```

**Comment by mpdehaan** [comment]
A traceback is always a bug, we likely need to return a smarter error here, though there are issues with config parser and sections named default.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
