### ISSUE TITLE
Copy file fails on platforms where os.path.exists returns False

### ISSUE THREAD

**Issue by svisser** [ansible/ansible#7760]
Ansible 1.6.3.

If I want to copy a file to `/home/user1/.ssh/destfile` (which does not exist yet) and `/home/user1/.ssh/` does exist then the copy action fails with the following error: `Destination directory /home/user1/.ssh/ does not exist`. Note that I was trying to do this while being `user2` (which also explains the below, on some platforms).

This error occurs because the check on line 191 thinks the directory does not exist (even though it does): https://github.com/ansible/ansible/blob/devel/library/files/copy#L191 And that happens because, as the Python documentation says, for `os.path.exists` it can be the case that:

> On some platforms, this function may return False if permission is not granted to execute os.stat() on the requested file, even if the path physically exists.

If this can't be fixed (as attempting a file copy may not be a good idea) then this should be clarified in the docs. It is also possible to give a better error message as `os.stat()` raises an `OSError` in this situation.

**Comment by mpdehaan** [comment]
This is actually fixable I believe through heinous stupid workarounds, yay Python stdlib.

Note:  we should have an "exists" function in module_utils to avoid this in the future.

**Comment by jimi-c** [comment]
I've created the above patch to correct this. In the case of insufficient privileges to the target destination, the next check after the one that is currently failing would have caught that in normal situations, however I've added an additional check using os.stat() to determine if the parent directory really doesn't exist or if it's a permission issue. I'm not sure if this would be useful in a module function, since the actual check in this case is for the parent directory, not the target destination itself, however if it comes up again we can definitely move the check to a common location.

Please let us know if you have any further questions. Thanks!

**Comment by svisser** [comment]
I think this already helps because it clarifies why the error occurs. I was able to work around it by copying the file as another user. If a fix is possible which would actually detect the existence of the directory and then allow the file copy to succeed then that would be best (I think that's what Michael was alluding to).

**Comment by jimi-c** [comment]
No, in no case will the copy be allowed if the permissions are not set right, so I think throwing an error is the best and only way to handle it properly. Really, it shows that the user should be using sudo or su to copy the file properly.
