### ISSUE TITLE
Manpages not present when installed with pip

### ISSUE THREAD

**Issue by komuta** [ansible/ansible#7790]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

When ansible is installed by pip, the manpages are not present on the system.
##### Steps To Reproduce:

Just installing ansible with pip, after having removed any other install (apt package for instance). Manpages can't be found, and pip is reporting no such installed file:

```
$ pip show -f ansible | grep 'man/'
...
```
##### Expected Results:

Since manpages are present on the repository, they should always be installed along with the software.
##### Actual Results:

```
$ man ansible
No manual entry for ansible
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by mpdehaan** [comment]
Thanks for the comment.

Manpages are installed with the OS package manager, not with the python library.

We get enough flack from virtualenv users for installing modules in OS locations, so I don't want to extend that further.

**Comment by ghost** [comment]
@mpdehaan wrote:
> We get enough flack [sic] from virtualenv users for installing modules in OS locations, so I don't want to extend that further.

I don't read this issue report as requesting that when Ansible is installed in a virtualenv, it should put anything into system directories. (Why would you do that, anyway?) Rather, I think it is asking that the man pages be installed in the virtualenv, much as the executables are. I doubt you would get any flak from anyone about that.

At the moment, such an approach would, I think, be blocked by https://github.com/pypa/virtualenv/issues/1129 , but if that is fixed, then this issue could be fixed as I described above.

Please can you re-open this issue, accordingly? Thanks.

**Comment by jborean93** [comment]
This is no longer necessary, you can run `ansible-doc module_name` to open up the man page equivalent for that module.

**Comment by ghost** [comment]
@jborean93 [wrote](https://github.com/ansible/ansible/issues/7790#issuecomment-361020952):
> This is no longer necessary, you can run `ansible-doc module_name` to open up the man page equivalent for that module.

That's better than nothing. But it is non-standard and non-obvious.

That documentation should be accessible using the `man` command; it not should not require an Ansible-specific [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern) of a command.

As such, this bug report has been closed improperly, because the reported issue has not in fact been fixed. Please can you re-open it?

**Comment by roens** [comment]
My workaround hack until `pip install ansible` "dtrt":

1. `git clone https://github.com/ansible/ansible`
1. `cd ansible`
1. `make docs`
1. `sudo cp docs/man/man1/* ${path-to-local-man}/man1/`
1. `man ansible` => standard manpages!

FWIW, I'm an oddball. I've been using macOS long enough that I use MacPorts, and fall back to `brew` "when I have to". The argument that "Manpages are installed with the OS package manager" falls short since there is no standard "package manager" in macOS, and often the best way to install a python package is with `pip`.

Perhaps an acceptable "fix" is to make the documentation install a separate `pip` package, or somehow an optional, additional install on the main `ansible` package?
