### ISSUE TITLE
mount documentation does not match code

### ISSUE THREAD

**Issue by shaunbrady** [ansible/ansible#7791]
There seems to be a mismatch with regard to the documentation/behavior of the mount modules.  
##### Issue Type:

“Bug Report”, “Documentation Report”
##### Ansible Version:

$ ansible --version
ansible 1.6.1
##### Environment:

N/A
##### Summary:

Looking from line https://github.com/ansible/ansible/blob/devel/library/system/mount#L263
we see that "absent" is suppose to "remove from fstab and unmounted", and the code appears to reflect this.  As well "unmount" is suppose to "not change fstab state, but unmount" and the code appears to reflect this. 

On the documentation page http://docs.ansible.com/mount_module.html we read:

"If mounted or unmounted, the device will be actively mounted or unmounted as well as just configured in fstab. absent and present only deal with fstab. mounted will also automatically create the mount point directory if it doesn't exist. If absent changes anything, it will remove the mount point directory."

The code and documentation for "unmount" and "absent" are in contention.  
##### Steps To Reproduce:

Review code/documentation at provided links.  
##### Expected Results:

I expect that the documentation would be the correct way for the software to behave.  It seems to be the most extensible.  Either way, consistency is more important.  
##### Actual Results:

The code and documentation for "unmount" and "absent" are in contention.  

I would be happy to provide a pull request for documentation or for code, but I wanted to see which (or both) were to be changed.

Thank you.

SB

**Comment by jimi-c** [comment]
Yes, feel free to send us a PR to bring the documentation in line with what the code is doing, as I believe that is the correct behavior. Thanks!

**Comment by shaunbrady** [comment]
https://github.com/ansible/ansible/pull/7795

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
