### ISSUE TITLE
ansible/builtin/dnf_module: Parameters document "list" but no examples given

### ISSUE THREAD

**Issue by jwalzer** [ansible/ansible#78069]
### Summary

in ansible/builtin/dnf_module in the parameter section the parameter `list` is documented with

>  "Various (non-idempotent) commands for usage with /usr/bin/ansible and not playbooks. See examples." 

but there are no examples given for the usage of this parameter

### Issue Type

Documentation Report

### Component Name

collections/ansible/builtin/dnf_module

### Ansible Version

```console
this is a documentation bug in the recent online version and its regardless of my running ansible version. 
See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#ansible-collections-ansible-builtin-dnf-module
```

### Configuration

```console
this is a documentation bug in the recent online version and its regardless of my running ansible version. 
See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#ansible-collections-ansible-builtin-dnf-module
```

### OS / Environment

this is a documentation bug in the recent online version and its regardless of my running OS Environment. 
See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#ansible-collections-ansible-builtin-dnf-module

### Additional Information

Providing Examples, on how to sensibly use the `list` parameter of the dnf module, would make it usable. Otherwise there will be an illogical reference from the parameterlist "See examples" when there are no examples explaining the usage.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment]
We should probably just deprecate that arg, it's somewhat vestigial from before package facts were around...

**Comment by samccann** [comment]
@nitzmahone Should we just point to package facts instead in the description? If so... where are they? :-)

**Comment by sivel** [comment]
@samccann specifically, the `package_facts` module.  Although technically speaking, the `list` arg here provides more functionality, but goes against our design goals, which is why we've not really documented it.  But in lieu of actually deprecating it or writing replacement functionality, the values are:

* updates
* upgrades
* installed
* available
* repos
* repositories
* [any name of an OS package]

That last one presents an issue with documentation, since it cannot be described statically, the validate-modules test would fail if we used `choices`.
