### ISSUE TITLE
[RFE] Provide facts for systemd sockets, targets, timers

### ISSUE THREAD

**Issue by myllynen** [ansible/ansible#78107]
### Summary

It would be helpful if one could gather facts (akin the package_facts) about systemd sockets, targets, timers (and possibly other units). One could then use the information in tasks to execute or skip them, e.g. when a timer is present on the system etc.

### Issue Type

Feature Idea

### Component Name

systemd

### Additional Information

This probably should be similar to `package_facts` so perhaps something like this:

```
- name: Gather systemd unit facts
  systemd_facts:
```

Or possibly this could be init system independent if the same idea applies to init managers on non-systemd platforms.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattclay** [comment]
Hi!

Thank you very much for your submission to Ansible. It means a lot to us that you've taken the time to contribute.

Since Ansible 2.10 we are no longer accepting new modules/plugins into Ansible core.  However, we recommend looking into providing this functionality through Ansible Galaxy via Ansible Collections. You can find more information about collections at:

   * https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html.

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
The mailing list and irc are great ways to ask questions, or post if you don't think this particular issue is resolved.

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Thank you once again for this and your interest in Ansible!
