### ISSUE TITLE
On  Conditionals with imports

### ISSUE THREAD

**Issue by dilyanpalauzov** [ansible/ansible#78130]
### Summary

https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#conditionals-with-imports says:

> Thus if `x` is initially undefined, the `debug` task will be skipped.

Please write there down, what will happen with the `debug` task, if `x` is initially defined.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/playbooks_conditionals.rst

### Ansible Version

```console
Not applicable.
```

### Configuration

```console
Not applicable.
```

### OS / Environment

Not applicable.

### Additional Information

Not applicable.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment]
If x is defined and the conditional on `import_tasks` is `when: x is not defined`, all imported tasks will be skipped, not just the debug task.

The `import_tasks` example skips the second task regardless of whether x is defined - I think the point of the example is that `import_tasks` would not achieve the intended result (to define and display a variable that wasn't previously defined). If you replace `import_tasks` in the example with `include_tasks`, then both tasks run only when x is initially undefined.

**Comment by dilyanpalauzov** [comment]
> Thus if `x` is initially undefined, the `debug` task will be skipped.

I think the above sentence is misleading in the context.  Correct would be:

> The `debug` task will be skipped.

or

> Irrespective of whether `x` was initially defined, the `debug` task will be skipped.

You might want to replace the example with a differnnt one, where the second imported task is conditioannly executed.

**Comment by s-hertel** [comment]
It's not as clear as it could be probably, but the subject of the example is `import_tasks` + conditional versus `include_tasks` + conditional. The exercise is: use a tasks file to define and display a previously undefined variable. This example uses `import_tasks` to show why a conditional on `import_tasks` may not do what's assumed. Your suggested text replacements don't make sense in that context (they're true statements also, but irrelevant to the point that's being made).

> You might want to replace the example with a differnnt one, where the second imported task is conditioannly executed.

This is the point of the example though, that `include_tasks` + `when` would make more sense for this example (because the conditional should not apply to the tasks for inclusion, just in the determination of whether or not to include them).
