### ISSUE TITLE
ansible-vault multiple password

### ISSUE THREAD

**Issue by JulienLanaud** [ansible/ansible#78335]
### Summary

I am using multiple password in my project. To do this, I have mulitple password file and I have added this in my cfg :
```yml
[defaults]
vault_id_match = True
vault_identity_list = common@.common_password_file, perso@.perso_password_file
```
I think it will be good to have a default directory like roles but named "pass" or "passwords" or something like this that can contains multiples files.
And each file name is interpreted as the vault-id and his content at the password for this vault id.
For example :
pass/
- perso
- common
- .gitignore
.gitignore contains "*" and perso the password for the vault-id perso.
So it would be a good idea to auto-fill the vault_identity_list with the content of this directory.

### Issue Type

Feature Idea

### Component Name

ansible-vault

### Additional Information

It would replace this in the config file
```yml
[defaults]
vault_id_match = True
vault_identity_list = common@.common_password_file, perso@.perso_password_file
```
and it would be easier to use multiple password in a project.
And it would be better if the use of ansible-vault encrypt-string auto use this directory to find password if just the argument `--encrypt-vault-id=perso` would be necessary to encrypt instead of `ansible-vault encrypt_string --vault-id perso@.perso_password_file --encrypt-vault-id=perso --stdin-name 'variable_name'`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
or 'vaults'?

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.

Currently the core team has no interest nor plans to implement this, however we are willing to examine a contribution that provides such facility but we are going to close the ticket as no one in the community has shown interest in implementing it either.

However, we're absolutely always up for discussion.
Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If you or anyone else has any further questions, please let us know by using any of the communication methods listed in the page below:

   * https://docs.ansible.com/ansible/latest/community/communication.html

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
