### ISSUE TITLE
Nested structures with Jinja templating that fail YAML parsing throw traceback

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7835]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ansible is running on Fedora 20. AWS API is the target.
##### Summary:

Using Jinja templating in complex structures seems to result in invalid YAML that throws an uncaught traceback.
##### Steps To Reproduce:

Try to create an EC2 VPC with tags using variables with something like this:

``` yaml
   - name: Create VPC for new environment
      local_action:
        module: ec2_vpc
        state: present
        cidr_block: 10.0.0.0/16
        resource_tags: { "Name": "{{ environment }}" }
        region: "{{ aws_region }}"
        dns_hostnames: true
        dns_support: true
        internet_gateway: true
        validate_certs: true
        instance_tenancy: default
        wait: true
        subnets: []
        route_tables: []
```
##### Expected Results:

If this is indeed invalid YAML then it should give an error message.
##### Actual Results:

It throws a traceback like the following:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403121708.45-114116167152383/ec2_vpc",
line 2001, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403121708.45-114116167152383/ec2_vpc",
line 599, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) =
create_vpc(module, vpc_conn)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403121708.45-114116167152383/ec2_vpc",
line 278, in create_vpc
    previous_vpc = find_vpc(module, vpc_conn, id, cidr_block)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403121708.45-114116167152383/ec2_vpc",
line 240, in find_vpc
    if resource_tags and
set(resource_tags.items()).issubset(set(vpc_tags.items())):
TypeError: unhashable type: 'dict'
```

**Comment by jimi-c** [comment]
Does the same thing happen if you specify the resource tags this way:

<pre>
    resource_tags:
      Name: "{{ environment }}-marketplace"
</pre>

**Comment by bcoca** [comment]
I would not use 'environment' as it is an ansible directive (myenv works
for me), this might not be the cause but it can cause problems.

**Comment by jimi-c** [comment]
Yes, as @mpdehaan pointed out on #7833 the environment variable is a special variable and may be the cause here. Could you please change that and see if the problem persists?

**Comment by mpdehaan** [comment]
Brian is right above, we need a warning system about such vars and have considered renaming that to ansible_environment but that's likely the issue.

That being said, we always view a traceback as a bug, regardless of cause, so we at least need a proper error message or handling behavior.

**Comment by mpeters** [comment]
Sorry for the confusion, but it seems that my initial example was flawed. In order to trigger the traceback you need to have:

```
resource_tags: { "Name": "{{ environment }}" }
```

**Comment by mpeters** [comment]
And to @jimi-c 's point above, yes it still occurs if I try this:

```
resource_tags:
     Name: "{{ environment }}"
```

And if I use a different variable name (as has been pointed out in #7833) it doesn't happen. So I'm guessing "environment" evaluates as "{}" (an empty dict in string form?) which then messes up the YAML parsing which then throws an uncaught exception.

**Comment by jimi-c** [comment]
@mpeters yep, that would be the case.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
