### ISSUE TITLE
'Notify' events that are fired should run even if play fails down the line

### ISSUE THREAD

**Issue by marktheunissen** [ansible/ansible#784]
If some actions in the playbook trigger notifications, but the play fails farther down, perhaps in some unrelated action, the host is removed and the triggered 'Notify' events are never run.

It may be a good idea to run all triggered events regardless of whether the play fails or not. Logically, if an action doesn't fail and triggers a 'Notify' event, that should be run even though other actions fail, otherwise you end up in a situation where re-running the playbook will not re-trigger the 'Notify' events, and you have to manually figure out what should have been triggered, potentially restart services manually, etc. 

Some ideas:
- --run-notifiers-even-on-failure could be a setting perhaps
- could also be a per-task variable (notify vs something like 'always_notify' (need a better name)), but that's ugly
- if you had something like a --force-notify that treats everything as IF it chained

**Comment by mpdehaan** [comment]
We can discuss this on the list in a few days.  Want to get the release out first.

**Comment by mpdehaan** [comment]
notify immediately seems wrong as it would double bounce things.   It seems we want to just decide whether to notify_always: True, which to me, seems like it is best done as a play setting, default off.

It would then run the plays regardless of failure status.  Would make for an easy patch and avoids adding too many setttings/options/other plumbing.

**Comment by mpdehaan** [comment]
thoughts?  If not, I think we'll do it that way.

**Comment by gottwald** [comment]
Is it really a good idea to do that?
When a playbook fails, something in the deployment obviously went wrong.
The whole configuration set may be inconsistent.
Do you really want to reload your daemons in such a situation?
I'm not sure about that.

On the other side when something like this happens, the quality of the running playbooks probably isn't that good and this situation is more likely to occur in your test lab than in production.

**Comment by mpdehaan** [comment]
@gottwald, I'm generally inclined to agree, I think @marktheunissen  had an interesting use case though.   I believe it was something he had stopped earlier in the play.   

I suppose if you're just trying to force the notifiers, something like notify_always is NOT the way to do it, because you'd have to run through the first parts anyway.

Thinking about it again, if your notifiers used an include, you could have a playbook that included those handler files like so:

tasks:
- blarg
  handlers:
- include: handlers/foo.yml

and a playbook run_handlers_for_whatever_reason.yml

tasks:
- include: handlers/foo.yml 

Seeing there's a way to do it, I think that should be sufficient as a way to get around the scenario.

And yes, you definitely want stage environments.

Closing for now.

**Comment by YvesChan** [comment]
I just get the same problem. 

<pre>
task:
  - modify A.conf
    notify:
      - restart A
  - modify B.conf
    notify:
      - restart B
  - modify C.conf
    notify:
      - restart C
handlers:
  - restart A
  - restart B
  - restart C
</pre>

These 3 tasks doesn't have any relativity. Suppose task A and B run succeed, but task C failed. So in the end all 3 service will not restart!  Then I fix the problem and run this playbooks again, but task A and B will never be run ( I use the template module ). Do you think that's reasonable? Or  I use notify in a wrong way ? I know it can be impleted by using "when" conditional control, so I just wonder how to use the notify in a right way...

@mpdehaan Any guidance, please?

**Comment by gottwald** [comment]
If these are independent services i would recommend separate playbooks.

So you can assure that a notify fires when a service change succeeded.

You could kind of stick them together with one playbook that includes the
three separate ones.

Am Freitag, 26. Juli 2013 schrieb Yves Chan :

**Comment by YvesChan** [comment]
@gottwald Thanks for reply.
Well, I do have a playbook with nearly 100 lines. But in my opinions, the more separate playbooks are, more time will be spent. For instance, while installing softwares like "nginx, mongodb, apache" etc, you probably use the *with_items" list to do it once. But in separate playbooks, you have to invoke apt module 3 times... Isn't it? So I think there's a trade-off.
Also, code reuse is another factors.

**Comment by gottwald** [comment]
That is true but I don't think the trade off is that big.
You probably have your database and application server on different machines anyway.
Also if you have a simple change in your nginx config, let's say a new rewrite rule, do you really want to run a huge playbook that has to go through your database service and so on, do you?
By invoking the apt module 3 times more, you only have 3 times more ssh connect time. That's not that much.
A huge playbook will take way longer than those little extra seconds.

The thing about the apt module that took the most time in my setup was the _update_cache_ procedure when invoked repeatedly in the playbooks.
That's why I wrote the _cache_valid_time_ option. Have you looked into that?

**Comment by YvesChan** [comment]
Yep, that's a helpful option.
What you say is true, I always use "tags" to solve the problem. But maybe a better structure should be figured out. :)

Thanks @gottwald
