### ISSUE TITLE
ec2_group occasionally fails with InvalidGroup.NotFound

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7850]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ansible is running on Fedora 20 against the AWS APIs.
##### Summary:

Randomly creation of a new Security Group via the ec2_group module fails with a `InvalidGroup.NotFound` error. This is similar to issue #7848.
##### Steps To Reproduce:

Using the sample task run multiple times, it will randomly fail with a `InvalidGroup.NotFound` error. From what I can tell, the details of the security group don't matter since it can fail for lots of different ones. But here is a sample task that has failed for me recently:

``` yaml
- name: Create log security group
  local_action:
    module: ec2_group
    name: 'logger'
    description: 'logger servers'
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.0.0.0/16
      - proto: tcp
        from_port: 514
        to_port: 514
        cidr_ip: 10.0.0.0/16
```
##### Expected Results:

It should be able to create the new security group each time without fail.
##### Actual Results:

It fails with an uncaught exception like this:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403202936.91-164188570092746/ec2_group", line 1785, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403202936.91-164188570092746/ec2_group", line 272, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/usr/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 204, in authorize
    dry_run=dry_run)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 3144, in authorize_security_group
    params, verb='POST')
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1196, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg-00dcbf65' does not exist</Message></Error></Errors><RequestID>8f81ff0f-ab21-4b60-b155-ca21ee6f198d</RequestID></Response>
```

**Comment by mpeters** [comment]
This solution to fix this bug isn't as easy as issue #7848 because `get_all_security_groups()` is actually being called in a loop to make sure it gets an object back before preceding. But somehow when it gets to the `group.authorize()` call it fails with this exception from boto. I'm not familiar enough with boto to know if there's a way to test an object that you get back from `get_all_security_groups()` to know if it is available enough to have `authorize()` called on it.

**Comment by crashdump** [comment]
I encounter this random issue quite often as well – I am running a fairly recent devel branch of ansible (0c3d7f1)

**Comment by altruism** [comment]
Same; I have a playbook which creates a dozen or so security groups and I haven't been able to run it all the way through without this error. Thank god for idempotency!

**Comment by jsmartin** [comment]
I get this issue only when I'm working on a VPC that is not the default.

**Comment by altruism** [comment]
@jsmartin Ah, I am also working on a non-default VPC.

**Comment by jsmartin** [comment]
Hmm, it seemed there was an issue with a leftover group of the same name.  So technically this is a non-issue for me at this point, but the error message could be cleaner.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
