### ISSUE TITLE
Global ignore_errors

### ISSUE THREAD

**Issue by ryan-lane** [ansible/ansible#7852]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.3
##### Environment:

n/a
##### Summary:

My playbooks take quite a while to run (a couple minutes for no-change runs) and if I add 10 tasks while developing and they have errors, I need to re-run the playbook over and over to fix each iterative issue, making a small change take possibly a very long time. It would be nice if I could set a configuration setting to continue on error globally so that I can have all the tasks run, fix the red ones, then vagrant destroy/up and ensure nothing is still red.
##### Steps To Reproduce:

n/a
##### Expected Results:

n/a
##### Actual Results:

n/a

**Comment by mpdehaan** [comment]
The whole point of Ansible is to make errors be fixed rather than to keep going, so I'm disinterested in this feature.  You may enjoy the '--start-at-task' or '--tags' options.

**Comment by vfguy** [comment]
wow.  nice way to dismiss a person.  Just because YOU aren't interested in this feature, doesn't mean it's not useful to others, myself included.

**Comment by HontoNoRoger** [comment]
While it's true what @mpdehaan stated, it would be a nice feature for the check mode.

Consider an example where you have a large role or playbook and want to run your check until the end, so you can fix occuring errors in one go and not iterative. Also, you could see what would fail because of previous tasks failing.

UPDATE:

Ignore what I mentioned, I just saw there's something like that already. You can specify
`ignore_errors: "{{ ansible_check_mode }}"` 
on a play globally, which meets my use case. Thanks!

**Comment by mattock** [comment]
It is rather disappointing that it is not possible to set ignore_errors on the command-line. This renders the ```--check``` feature way less useful than the equivalent feature, ```--noop``` in Puppet, for example.

As ```--check``` will not make any changes to the system, it is only natural that a task that depends on a previous task will fail. For example, you cannot add a SSH key for a user unless that user has been created. Similarly, you cannot enable a service unless a package containing that service has been installed. These are very common scenarios, and being able to do a proper dry-run and being able to guage yourself which errors really matter would be highly useful.
