### ISSUE TITLE
rax_identity stacktraces with pyrax >= 1.8.0

### ISSUE THREAD

**Issue by claco** [ansible/ansible#7860]
Starting with pyrax 1.8.0 and greater installed, the rax_identity module now dies with a stacktrace trying to serialize the output:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403232596.15-235494610913070/rax_identity", line 1438, in <module>
    main()
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403232596.15-235494610913070/rax_identity", line 110, in main
    cloud_identity(module, state, pyrax.identity)
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403232596.15-235494610913070/rax_identity", line 82, in cloud_identity
    module.exit_json(changed=changed, identity=instance)
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403232596.15-235494610913070/rax_identity", line 1051, in exit_json
    print self.jsonify(kwargs)
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403232596.15-235494610913070/rax_identity", line 1029, in jsonify
    return json.dumps(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <'load_balancer' Service object at 0x102bc23d0> is not JSON serializable
```

As a workaround, rolling back to < 1.8.0 fixes the problem.

**Comment by sivel** [comment]
I'll look into this soon.  I have a branch in the works that may already solve this issue.

**Comment by sivel** [comment]
I've applied a fix in my rax-de-dupe branch at https://github.com/sivel/ansible/tree/rax-de-dupe

I'll submit the fix for this as part of the pull request for the above mentioned branch in the next few weeks.  Testing would be welcome.

**Comment by claco** [comment]
I'll give this a whirl this evening. Thanks @sivel. You're my hero. :-)

**Comment by claco** [comment]
I'm not a heavy python dude, so this very well may be a case of I'm stupid.

I created a venv, and installed your branch and pyrax:

```
virtualenv .
source ./bin/activate
pip install git+git://github.com/sivel/ansible.git@rax-de-dupe
pip install pyrax
```

And turned loose my playbook. The stacktrace has changed to this:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403309962.42-98630130384189/rax_identity", line 1446, in <module>
    main()
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403309962.42-98630130384189/rax_identity", line 103, in main
    cloud_identity(module, state, pyrax.identity)
  File "/Users/claco/.ansible/tmp/ansible-tmp-1403309962.42-98630130384189/rax_identity", line 68, in cloud_identity
    instance.update(rax_to_dict(identity))
NameError: global name 'rax_to_dict' is not defined


FATAL: all hosts have already failed -- aborting
```

**Comment by claco** [comment]
k, wiped every single bit of ansible/pyrax from my admittedly crapped up OSX. Redid the venv, your branch, and the latest pyrax. :+1: now.

**Comment by sivel** [comment]
This is resolved in current devel with some of the dedupe refactoring that has already been merged.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
