### ISSUE TITLE
Add support for creating a network interface for EC2 instance.

### ISSUE THREAD

**Issue by haad** [ansible/ansible#7895]
##### Summary:

It would be great if it would be possible to create an instance with more than one interface in it. _Boto_ library seems to support interface creation so it's just matter of implementation inside _ansible_ [1].

I'm not sure what should be correct way to do it. There are at least two ways.

1) Make _vpc_subnet_id_ require an array where if you pass more than one vpc_subnet it would create another interface for it.

2) Add new module for interface creation where you could add new interface and later use it with instance with new parameter named 

```
network_interface_id: []
```

Do you have any suggestions ?

[1] https://github.com/boto/boto/blob/develop/tests/unit/ec2/test_networkinterface.py

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by wimnat** [comment]
I've written a module here for eni creation - https://github.com/wimnat/ansible-modules-extras/blob/feature/ec2_eni/cloud/amazon/ec2_eni.py

I'd appreciate any feedback / testing so I can submit a PR

**Comment by zyphlar** [comment]
@wimnat I could definitely use this eni module included in Ansible; I'll try to test it out.
