### ISSUE TITLE
loss of 'map' jinja2 filter after upgrade from  1.5.3 to 1.6.2-1

### ISSUE THREAD

**Issue by davidbirdsong** [ansible/ansible#7908]
In complying w/ the template, I've also simplified the example. Downgrading to 1.5.3 gives me the expected output.

The error is fully reproducible on upgrade and fixable on downgrade.
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6.2
##### Environment:

Centos6 managing Centos6
##### Summary:

jinja2 `map` filter disappears after upgrade from 1.5.3
##### Steps To Reproduce:

template:

```
foo template
{% set pairs = "%-30s"|format(server_line_pairs.items()|map('join', ' ')|join(' ')) %}
{{ pairs }}
```

playbook:

```

---
- name: "template test playbook"
  hosts: svac20
  sudo: yes
  vars:
    server_line_pairs: { "server1" : 9000, "server2" : 9002}

  tasks:
    - name: copy foo template
       template: src=templates/foo.tmpl dest=/tmp/foo.txt$                                                        
```
##### Expected Results:

cat /tmp/foo.txt

```
 foo template



server1 9000 server2 9002     
```
##### Actual Results:

```
TASK: [copy foo template] ***************************************************** 
fatal: [svac20] => {'msg': "file: /export/sda3/home/david/src/ansible-repo/templates/foo.tmpl, line number: 2, error: no filter named 'map'", 'failed': True}
fatal: [svac20] => {'msg': "file: /export/sda3/home/david/src/ansible-repo/templates/foo.tmpl, line number: 2, error: no filter named 'map'", 'failed': True}
```

**Comment by jimi-c** [comment]
I just tested this with your example above on the devel branch, and cannot reproduce this:

<pre>
$ ansible-playbook 7908.yml 
PLAY [template test playbook] ************************************************* 
GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]
TASK: [copy foo template] ***************************************************** 
changed: [127.0.0.1]
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
$ cat /tmp/foo.txt 
foo template
server1 9000 server2 9002     
</pre>

I also tested on the 1.6.2 branch and got the same results. The map filter is a jinja2 built-in, so upgrading between versions should not have affected it. Can you test against devel as well to see if your issue was resolved, or if a clean environment works with your playbook?

**Comment by davidbirdsong** [comment]
So a completely new environment only displays this error condition and downgrading doesn't help. Which I guess makes more sense, but, hell, it means my shell server is a mess if moving the needle on ansible versions somehow changes jinja2 behaviour.

....and it's jinja2 and not ansible:

``` python
>>> import jinja2
>>> f = "/home/david/ansible-repo/templates/foo.tmpl"
>>> jinja2.Template(open(f).read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 625, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 563, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 448, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateAssertionError: no filter named 'map'
>>> jinja2.__file__
'/usr/lib64/python2.6/site-packages/jinja2/__init__.pyc'
```

``` sh
[david@svab1 ansible-repo]$ rpm -qf /usr/lib64/python2.6/site-packages/jinja2/__init__.pyc 
python-jinja2-2.2.1-2.el6_5.x86_64
```

...grr, so I guess I need to go bark up jinja2's tree?

**Comment by jimi-c** [comment]
Looks that way, let us know if you need anything else. Thanks!

**Comment by KeynesYouDigIt** [comment]
Did Jinja2 mention anything about this? I have a working web app using Map that gets this error when I deploy to google app engine
