### ISSUE TITLE
hostname fails on ec2 instances with Amazon Linux

### ISSUE THREAD

**Issue by jimbydamonk** [ansible/ansible#7932]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 
##### Environment:

Linux ip-10-0-4-228 3.4.82-69.112.amzn1.x86_64 #1 SMP Mon Feb 24 16:31:21 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

When using hostname on amazon ami (Amazon Linux) I get a trace back 

The trace back 
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1403707765.25-178940409144843/hostname", line 1611, in <module>
    class RedHatServerHostname(Hostname):
  File "/root/.ansible/tmp/ansible-tmp-1403707765.25-178940409144843/hostname", line 1614, in RedHatServerHostname
    if float(get_distribution_version()) >= 7:
ValueError: could not convert string to float:

After some digging, it looks like a strange python issues:
http://bugs.python.org/issue18872
##### Steps To Reproduce:

try to set the hostname on an ec2 instance while
##### Expected Results:

Sets the hostname 
##### Actual Results:

The trace back 
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1403707765.25-178940409144843/hostname", line 1611, in <module>
    class RedHatServerHostname(Hostname):
  File "/root/.ansible/tmp/ansible-tmp-1403707765.25-178940409144843/hostname", line 1614, in RedHatServerHostname
    if float(get_distribution_version()) >= 7:
ValueError: could not convert string to float:

**Comment by neersighted** [comment]
:+1:, please pull, I'm seeing this on Debian unstable (version is returned as `jessie/sid`).

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
