### ISSUE TITLE
ansible.builtin.command cannot handle commands not creating/removing files

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#79342]
### Summary

why can this build in tool not know if it was allready run? 

### Issue Type

Bug Report

### Component Name

command?

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

ALL

### Steps to Reproduce

try to run a command only once without doing 100 needed extra steps

### Expected Results

compatibility with commands not creating any files 

### Actual Results

```console
i need to create a custom script,
run it in a extra step,
removing this custom created script
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
Hi!

Thanks very much for your interest in Ansible.  It means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
