### ISSUE TITLE
KeyError: 'ansible_job_id' when skipping play that uses poll

### ISSUE THREAD

**Issue by mschurenko** [ansible/ansible#7947]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7
##### Environment:

OSX 10.9.3 and Amazon Linux 2014.03
##### Summary:

I have a job that needs to be launched as a daemon. In order to do this I am using async and setting poll to 0 as per this document:

http://docs.ansible.com/playbooks_async.html

I want to conditionally run this play based on a passed in variable. It seems that when the play is skipped it gives a KeyError: 'ansible_job_id' error. Here is my play:

```
- name: start node gulp
  shell: ( cd /tmp/{{ project }};gulp --target {{ node_env }} &> {{ splunk_monitor }} & )
  sudo: true
  async: 60
  poll: 0
  when: node_type == "web"
```
##### Steps To Reproduce:

Run the play and set node_type to something other than "web".
##### Expected Results:

The play should be skipped and ansible should move on to the next play in the playbook.
##### Actual Results:

```
TASK: [node | start node gulp] ************************************************
skipping: [guardian-test]
Traceback (most recent call last):
  File "/Users/matts/ansible/bin/ansible-playbook", line 317, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/matts/ansible/bin/ansible-playbook", line 257, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/playbook/__init__.py", line 319, in run
    if not self._run_play(play):
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/playbook/__init__.py", line 673, in _run_play
    if not self._run_task(play, task, False):
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/playbook/__init__.py", line 449, in _run_task
    results = self._run_task_internal(task)
  File "/Library/Python/2.7/site-packages/ansible-1.7-py2.7.egg/ansible/playbook/__init__.py", line 413, in _run_task_internal
    self.runner_callbacks.on_async_ok(host, res, poller.runner.vars_cache[host]['ansible_job_id'])
KeyError: 'ansible_job_id'
```

**Comment by tom--** [comment]
`poll:` can be a string so a workaround:

```
poll: "{( 0 if node_type == "web" else 10 }}"
```

**Comment by hfinucane** [comment]
I'm just going to toot my own horn: https://github.com/ansible/ansible/pull/7621

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible-playbook -vv 7947.yml 
1 plays in 7947.yml
PLAY: ***************************************************************************
TASK [command] ******************************************************************
skipping: [localhost] => {"skipped": true, "changed": false, "skip_reason": "Conditional check failed"}
PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
# ansible-playbook -vv 7947.yml -e node_type=web
1 plays in 7947.yml
PLAY: ***************************************************************************
TASK [command] ******************************************************************
ok: [localhost] => {"started": 1, "results_file": "/root/.ansible_async/858260432550.13680", "ansible_job_id": "858260432550.13680", "changed": false}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   </pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
