### ISSUE TITLE
rds_param_group says "too many values to unpack"

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#7952]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 9b52ce8a42) last updated 2014/05/05 12:27:23 (GMT +200)
&
ansible 1.7 (devel 14cf3c4d2a) last updated 2014/06/30 11:48:15 (GMT +200)
##### Environment:

Fedora Core 19
##### Summary:

Trying to create an RDS Parameters Group with a few custom parameters value.
##### Steps To Reproduce:

```
- name: create the RDS Parameters Group
    local_action:
      module: rds_param_group
      description: param group for main-db-02
      engine: mysql5.6
      immediate: yes
      name: main-db-02
      params:
        key_buffer_size: 512M
        max_allowed_packet: 64M
        table_definition_cache: 2000
        table_open_cache: 2000
        query_cache_limit: 10M
        query_cache_size: 128M
        slow_query_log: 1
        wait_timeout: 120
        #innodb_buffer_pool_size: 11.25G {DBInstanceClassMemory*3/4}
        #innodb_log_file_size: 128M
        #innodb_log_buffer_size: 8M
        #innodb_thread_concurrency:
      region: eu-west-1
      state: present
```

I manually created a param group (main-db-01) that has the required values. Here's the comparison report against the two:
Parameters Comparison

| Parameter | main-db-01 | main-db-02 |
| --- | :-: | --: |
| interactive_timeout | 28800 |  |
| key_buffer_size | 525950976 | 536870912 |
| slow_query_log |  | 1 |
| table_definition_cache | 2000 |  |
| wait_timeout | 120 |  |
##### Expected Results:

Parameter group gets successfully created with all parameters having the set values.
##### Actual Results:

```
TASK: [create the RDS Parameters Group] *************************************** 
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/dvaida/.ansible/tmp/ansible-tmp-1403860155.54-123040854027363/rds_param_group", line 1658, in <module>
    main()
  File "/home/dvaida/.ansible/tmp/ansible-tmp-1403860155.54-123040854027363/rds_param_group", line 275, in main
    changed_params, group_params = modify_group(next_group, group_params, immediate)
  File "/home/dvaida/.ansible/tmp/ansible-tmp-1403860155.54-123040854027363/rds_param_group", line 199, in modify_group
    set_parameter(param, new_value, immediate)
  File "/home/dvaida/.ansible/tmp/ansible-tmp-1403860155.54-123040854027363/rds_param_group", line 177, in set_parameter
    param.value = converted_value
  File "/usr/lib/python2.7/site-packages/boto/rds/parametergroup.py", line 171, in set_value
    self._set_integer_value(value)
  File "/usr/lib/python2.7/site-packages/boto/rds/parametergroup.py", line 149, in _set_integer_value
    min, max = self.allowed_values.split('-')
ValueError: too many values to unpack


FATAL: all hosts have already failed -- aborting
```

Parameter group gets created but some parameters do not have the intended values.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by nergdron** [comment]
This should be re-opened, since issues have moved back into this repo I guess. In any case, still very much seeing this problem with ansible 2.2.1.0 and ansible 2.3.0. Here's a simple example on 2.3:

```yaml
- name: "Create RDS Parameter Groups"
  rds_param_group:
    name: "{{ item.key }}"
    region: "{{ region }}"
    engine: "{{ item.value.engine }}"
    params: "{{ item.value.params }}"
    description: "Managed by Ansible"
    state: present
  with_dict: "{{ rds_param_groups }}"
  register: rds_pgs
- debug: verbosity=1 var=rds_pgs
```
```yaml
rds_param_groups:
  test-postgres95:
    engine: postgres9.5
    params:
      work_mem: 20480
      log_min_duration_statement: 1000
```
```
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/tessa/.ansible/tmp/ansible-tmp-1493834509.17-77120241914615/rds_param_group.py; rm -rf "/home/tessa/.ansible/tmp/ansible-tmp-1493834509.17-77120241914615/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py", line 316, in <module>
    main()
  File "/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py", line 292, in main
    changed_params, group_params = modify_group(next_group, group_params, immediate)
  File "/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py", line 213, in modify_group
    set_parameter(param, new_value, immediate)
  File "/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py", line 182, in set_parameter
    param.value = converted_value
  File "/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py", line 171, in set_value
    self._set_integer_value(value)
  File "/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py", line 149, in _set_integer_value
    min, max = self.allowed_values.split('-')
ValueError: too many values to unpack

failed: [localhost] (item={'key': u'bench-postgres95', 'value': {u'engine': u'postgres9.5', u'params': {u'work_mem': 20480, u'log_min_duration_statement': 1000}}}) => {
    "failed": true, 
    "item": {
        "key": "test-postgres95", 
        "value": {
            "engine": "postgres9.5", 
            "params": {
                "log_min_duration_statement": 1000, 
                "work_mem": 20480
            }
        }
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py\", line 316, in <module>\n    main()\n  File \"/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py\", line 292, in main\n    changed_params, group_params = modify_group(next_group, group_params, immediate)\n  File \"/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py\", line 213, in modify_group\n    set_parameter(param, new_value, immediate)\n  File \"/tmp/ansible_4lPk6q/ansible_module_rds_param_group.py\", line 182, in set_parameter\n    param.value = converted_value\n  File \"/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py\", line 171, in set_value\n    self._set_integer_value(value)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py\", line 149, in _set_integer_value\n    min, max = self.allowed_values.split('-')\nValueError: too many values to unpack\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

note that if I remove log_min_duration_statement from the params, leaving a single param, then it works. so there's definitely a problem somewhere with parsing multiple parameters, and it's been a problem for a long time by the look of this ticket.

**Comment by conlon** [comment]
I'm getting the same error with only a single param, log_min_duration_statement...something is wrong here. I'm on Ansible 2.3.0.0 and boto 2.46.1

**Comment by conlon** [comment]
@nergdron just FYI, I opened up a new issue #24340
