### ISSUE TITLE
lookup('file') can't read AES-256 (probably binary) encrypted files

### ISSUE THREAD

**Issue by fnando** [ansible/ansible#7957]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.5
##### Environment:

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.9.3 (13D65)
      Kernel Version: Darwin 13.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

I'm trying to create a module that copies encrypted files. So I decided to do something like this:

``` yaml
encrypted_file: >
  content="{{lookup('file', item)}}" passphrase=test dest=/tmp/decrypted.txt
with_file:
  - encrypted.txt
```

The encypted.txt file has been created with the following command:

``` bash
date | openssl enc -aes-256-cbc -salt -in /dev/stdin -out files/encrypted.txt -k test
```

When I try to run the playbook, I receive an exception, because the content can't be converted to UTF-8.

```
$ ansible-playbook -i hosts playbook.yml                                               
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 536, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 614, in _executor_internal
    items = utils.plugins.lookup_loader.get(items_plugin, runner=self, basedir=basedir).run(items_terms, inject=inject)
  File "/Library/Python/2.7/site-packages/ansible/runner/lookup_plugins/file.py", line 42, in run
    ret.append(codecs.open(path, encoding="utf8").read().rstrip())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 671, in read
    return self.reader.read(size)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9a in position 8: invalid start byte
```

Notice that I don't want to use vault; I just want the raw file content.

I make an example that reproduces this bug: https://dl.dropbox.com/s/s2qdq5f1gbacda3/index.html
##### Expected Results:

lookup('file') must pass in the raw content, without raising an exception.
##### Actual Results:

An exception is raised because it tries to convert the content to UTF-8

**Comment by shabbyrobe** [comment]
I was trying to do something similar, but using vault: https://gist.github.com/shabbyrobe/d64bf796d79239476590

I get the same error. Is it the same bug, or am I just doing something wrong?

**Comment by sivel** [comment]
In short ansible attempts to encode all data in the module file shipped to the remote host as 'utf-8'.

This obviously fails to function correctly on binary data.  At the moment, you can not ship modules with binary data in them.  The data you ship would have to be encoded with something like base64, and the module would have to handle decoding in the 'last mile'.

**Comment by akurilin** [comment]
Just ran into a similar issue today where I was storing an AES key in base64 in my ansible vault and I was hoping to either copy content or template it into a file on the target host, however this won't work since Ansible only deals with utf-8.

Would be nice if there was a way to handle that without additional manual commands so I can have a copy content from the vault with {{ mykey | b64decrypt }} that doesn't blow up. The upside of this approach is that ideally it'd be able to CRC the two binaries and not replace them if they're identical, as right now I'd have to do that operation by hand.

**Comment by shabbyrobe** [comment]
@AKurilin - here's my hacked up module for dealing with this problem, it does exactly what sivel describes: https://gist.github.com/shabbyrobe/63a7cc1cc8e1b3473e64

It's just a copy/pasta/hack of the copy module. It lets you do this:

```
  tasks:
  - decode:
      content: "{{ test }}"
      dest: /tmp/test
      filter: base64
```

I'm sure there's some native way to do it that I've missed, but as we well know, you're more likely to get the right answer on the internet by posting the wrong one :D

**Comment by akurilin** [comment]
This is awesome, thanks Blake! I'll test it out and let you know. Maybe
have this be part of the official module list? _wink wink_ :)

**Comment by akurilin** [comment]
Seems to do the trick, thank you for sharing it.

**Comment by adamchainz** [comment]
Module worked for me too, thanks. Faffed around trying to do this native but couldn't find a way either.

**Comment by jimi-c** [comment]
Hi @fnando, sorry this is such a late reply on this. In your original example here, `with_file` actually returns the contents of the file in question, so doing the lookup is not necessary (you're passing the binary contents in as the file name to lookup).

Regardless, the `copy` module now has support for vaulted files, and should not have had a problem with binary files originally.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
