### ISSUE TITLE
command/shell module requirements

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#797]
In my 'enterprisey linux' environment we have some older RHEL 4 boxen running python 2.3. Unfortunately those modules require the python subprocess module (not available on those boxen).

Would you accept a patch something akin to this?

```
try:
    import subprocess
    cmd = subprocess.Popen(args, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = cmd.communicate()
except ImportError:
    # relevant legacy popenX.popenX(....) code here
```

[1] http://ansible.github.com/gettingstarted.html#requirements

**Comment by mpdehaan** [comment]
If done in a utility method in the module_common code, and made available to all of them, yes.

module.exec(args, shell=True/False) # some signature like this.

Cobbler actually bundled a copy of subprocess, it may be the best thing to do is package it and use the "raw" module (or kickstart, whatever) to see that it is present.

**Comment by mpdehaan** [comment]
if we do this, we should probably port as many modules as possible to use this as well, just to set the precedent for new modules. 

I am also a little uncomfortable with requiring only python 2.3 on nodes for modules other than command, because it would mean we couldn't do things like use "sorted()", though we could also make a utility function for that.

I don't remember many other issues with 2.3 compliance and we already require 2.4

If we do this, we would want to make sure everywhere was 2.3 complaint, not just 2.4, basically, so we could move the doc pointer to say only 2.3 on modules.

I'm ok with that but want us to be consistent.

**Comment by timlnx** [comment]
I simply don't have the resources, nor desire, to make all modules python 2.3 compliant. It's a nice idea, but I think something we'll just get over by shipping our own python 2.3 shell/command module if we need to.

If you're not interested in this (I wouldn't be) go ahead and close the ticket.

**Comment by mpdehaan** [comment]
well, ok, just make the subprocess module in core and then the command module can use it, and we can port the others as needed. 

Seems ok to do to me.

You would prob. have to look after 2.4isms creeping back in accidentally, as I might not be super vigilant, but I can see value of this being there in core for when you need to flog
ancient things with /usr/bin/ansible

**Comment by mpdehaan** [comment]
send me a pull request if you want to do this (which I'm fine with), otherwise closing to keep the list short.
