### ISSUE TITLE
ec2_metric_alarm namespace options unnecessarily limited

### ISSUE THREAD

**Issue by zol** [ansible/ansible#7970]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

The namespace option doesn't accept `System/Linux` which is required to target metrics set up by the official AWS Linux metric reporting [tool](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/mon-scripts-perl.html)

This is also an issue for users who report metrics under their own, custom, namespace.
##### Steps To Reproduce:

Create a an ec2 metric such as:

```
- name: Alarm
  ec2_metric_alarm:
    ...
    namespace: "System/Linux"
```
##### Expected Results:

Alarm is setup ok.
##### Actual Results:

Error message that complains about a namespace that's not allowed.

**Comment by mpdehaan** [comment]
Can you paste the actual error message you were experiencing?

Thanks!

**Comment by zol** [comment]
When running the playbook, I get:

```
TASK: [High memory alarm] ***************************************************** 
failed: [REDACTED] => {"failed": true}
msg: value of namespace must be one of: AWS/AutoScaling,AWS/Billing,AWS/DynamoDB,AWS/ElastiCache,AWS/EBS,AWS/EC2,AWS/ELB,AWS/ElasticMapReduce,AWS/OpsWorks,AWS/Redshift,AWS/RDS,AWS/Route53,AWS/SNS,AWS/SQS,AWS/StorageGateway, got: System/Linux
```

**Comment by bilalaslam** [comment]
:+1:  I also saw this. This prevents me from creating a disk utilization alarm.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
