### ISSUE TITLE
Docker module volumes property misinterprets readonly binding

### ISSUE THREAD

**Issue by jeffcharles** [ansible/ansible#7978]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

N/A
##### Summary:

When using the Docker module and specifying a volume with readonly bindings (e.g., `volumes=/vagrant/api:/usr/source/node:ro`), a read-write volume is created in the container without a binding to the host (as if I specified, `volumes=/vagrant/api` instead).
##### Steps To Reproduce:
1. Create a Docker image
2. Enter a value like `volume=/vagrant/foo:/foo:ro` when using the Docker module in your playbook
##### Expected Results:

The Docker container should have a readonly volume located at `/foo` which points to `/vagrant/foo` on the host (i.e., similar to if you were to use `docker run` with the `-v /vagrant/foo:/foo:ro` argument). Alternatively and less ideally, the module should output a failure message indicating that readonly bindings aren't supported.
##### Actual Results:

The Docker container has a read-write volume located at `/vagrant/foo` which is not bound to anything on the host. 
##### Other Notes:

`__init__` in the Docker module seems to think that a volume has up to two parts and assumes that anything that doesn't have two parts, has just one (including things with three  or more parts). `docker-py` looks like it supports passing a dictionary as the value of the binding which looks like `{'bind': parts[1], 'ro': True}` which should allow for readonly bindings specified through Ansible.

**Comment by mpdehaan** [comment]
Seems you have a good understanding of the module and python - Is this something you might like to work on, perhaps?

**Comment by jeffcharles** [comment]
I can put together a pull request some time later this week.

**Comment by jeffcharles** [comment]
It looks like versions of `docker-py` earlier than 0.3.2 do not support passing a dictionary as the binding format and the resulting error message is not pretty for end users. In 0.3.2, if you try to send docker-py the legacy binding format with a readonly flag appended which works prior to 0.3.2, it errors out because of part of a compatibility fix they implemented for Ansible unconditionally appends a read-only flag.

I don't know how to make a safe fix for this since the format you need to send the binding in is different depending on which version of `docker-py` you're running. I also know that you can't run docker-py 0.3.2 with Ansible 1.6.3 or earlier due to other API fixes in the Docker modules not having been incorporated in those releases.

**Comment by jeffcharles** [comment]
I just realized, the last sentence in the first paragraph should end with, unconditionally appends a _read-write_ flag.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the commit merged in via PR #7561 should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
