### ISSUE TITLE
service module in service mode does not restart auditd

### ISSUE THREAD

**Issue by juresaht2** [ansible/ansible#80142]
### Summary

The bug is kinda elaborated here: https://stackoverflow.com/a/47442135/2897386 (answer and comments)

Explanation: Due to issue https://access.redhat.com/solutions/2664811 , auditd cannot be restarted using Ansible on CentOS 7 using systemd . The recommended solution is to use `service` instead, which in Ansible can be accomplished by using the `service` module using the `use: service` argument.

However, while this completes successfully and without error it does not, in fact, restart the service.

It is notable that this behaviour is different than if you use the same Ansible context and simply run service using `command: /sbin/service auditd restart` instead. Therefore this is clearly a module bug.

### Issue Type

Bug Report

### Component Name

service module

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /home/username/dev-jsah/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep 21 2021, 00:13:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
DEFAULT_NO_LOG(/home/username/dev-jsah/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/username/dev-jsah/ansible.cfg) = ['/home/username/dev-jsah/roles', '/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/username/dev-jsah/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/username/dev-jsah/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/username/dev-jsah/ansible.cfg) = False

ssh:
___
host_key_checking(/home/username/dev-jsah/ansible.cfg) = False
```

### OS / Environment

Managed device is CentOS 7.9.2009 .

### Steps to Reproduce

```yaml (paste below)
- service: name=auditd state=restarted use=service
```

### Expected Results

Expected step to complete without error and service to be restarted.

### Actual Results

```console
Step was completed without error, but the service was not restarted.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by juresaht2** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1026648

This is the bug referenced in the Red Hat issue, if you don't have access.

**Comment by sivel** [comment]
I think there might be a slight misunderstanding about the `use` parameter, or potentially the `service` module.  The `service` module that is invoked by `use: service` does not imply use of the `service` command.

The older `service` module, was a single module to interact with all init systems, and it will still attempt to use `systemctl` in your case, since the system is managed by systemd.

There is no way to force the `service` module to use the `service` command on a systemd managed system.  The `service` module is effectively frozen at this point in time, and provided for some form of backwards compatibility.

The `sysvinit` module is only capable of interacting with the `service` command if it is an actual sysvinit script.

So the only reliable way to force calling the `service` command to interact with a systemd unit is to use the `command` module.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by bcoca** [comment]
Note that the 'service' command is not uniformly implemented, while it was created as a shortcut/convention it was never made into a standard and behavior does vary by implementation, this is why the service related modules try to use the actual init system instead.

**Comment by juresaht2** [comment]
However providing `use: service` still fails to do anything, yet yields no error, whereas not providing this argument fails.

Even if this is not currently implemented, shouldn't it still yield an error in this case?

**Comment by bcoca** [comment]
That is probably due to a bug with the service module, `systemd`  has changed over time and has always been inconsistent with what you should look at return codes for and what you should look at output for. The newer `systemd` module tries handles most of these inconsistencies, while the `service` module is a lot more naive and is probably only relying on return codes.
