### ISSUE TITLE
`hw.model` removed from `sysctl` in OS X 10.10

### ISSUE THREAD

**Issue by jcf** [ansible/ansible#8021]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible 1.7`
##### Environment:

OS X 10.10 Yosemite
Python 2.7.3
##### Summary:

I'm having some trouble running Ansible on my dev machine running OS X 10.10 (Yosemite).

It appears the issue stems from the fact Ansible relies on `hw.model` from `sysctl` when gathering facts about the target system.

The output of running `sysctl hw` on my laptop can be found in this [gist](https://gist.github.com/jcf/c66caf573dd735b36bd1).
##### Steps To Reproduce:

Attempt to gather facts
##### Expected Results:

Playbooks run
##### Actual Results:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 3748, in <module>
    main()
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 137, in main
    data = run_setup(module)
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 81, in run_setup
    facts = ansible_facts(module)
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 3687, in ansible_facts
    facts.update(Hardware().populate())
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 2727, in populate
    self.get_mac_facts()
  File "/Users/jcf/.ansible/tmp/ansible-tmp-1404336982.71-141093321131903/setup", line 2755, in get_mac_facts
    self.facts['model'] = self.sysctl['hw.model']
KeyError: 'hw.model'
```

**Comment by jcf** [comment]
`sysctl` does return the expected result when you ask for `hw.model` directly like so:

```
$ sysctl hw.model
hw.model: MacBookPro10,1
```

It appears this information is simply not included when you run `sysctl -a` or `sysctl hw`.

**Comment by jcf** [comment]
If like me you're not using facts in your plays, you can work around this issue by skipping the fact checking step by adding the following to your play.

``` yaml
gather_facts: False
```

https://groups.google.com/forum/#!msg/ansible-project/jva6aEaRp1A/17rUg7SDuPQJ

**Comment by jbenden** [comment]
I posted a fix here: https://github.com/ansible/ansible/pull/8171

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by madrobby** [comment]
@jcf thanks for the workaround (works fine for Ansible 1.6, haven't gotten around to upgrade).

**Comment by papamoose** [comment]
I would like to reopen this as I just ran into this issue in 1.9.2.

root@foobar:~/# ansible --version
ansible 1.9.2
  configured module search path = /usr/share/ansible

hostname:~ username$ sysctl hw.model
hw.model: Macmini6,2

GATHERING FACTS *************************************************************** 
failed: [hostname] => {"failed": true, "parsed": false}
BECOME-SUCCESS-owsyebakipvfvxzxqqauytgqtwjuhfay
Traceback (most recent call last):
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 3969, in <module>
    main()
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 2359, in main
    data = run_setup(module)
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 2300, in run_setup
    facts = ansible_facts(module)
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 2290, in ansible_facts
    facts.update(Hardware().populate())
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 1345, in populate
    self.get_mac_facts()
  File "/Users/username/.ansible/tmp/ansible-tmp-1433800405.06-279572644204444/setup", line 1373, in get_mac_facts
    self.facts['model'] = self.sysctl['hw.model']
KeyError: 'hw.model'
OpenSSH_5.9p1 Debian-5ubuntu1.4, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to hostname closed.
