### ISSUE TITLE
nova_compute fails when instance has no networking

### ISSUE THREAD

**Issue by ericwb** [ansible/ansible#8025]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 12.04.4
##### Summary:

The nova_compute module fails when the nova instance spawned has no networking.
##### Steps To Reproduce:

In my setup, OpenStack's neutron is incorrectly configured, so instances will not get networking.  As a result, the nova_compute module fails because it attempts to reference data in the response that is not there.
##### Expected Results:

I would expect the nova_compute module to parse the response without error, but with limited output in the result.  
##### Actual Results:

Results in a traceback failure.

```
TASK: [smoketest | create a new virtual machine instance] ********************* 
failed: [smoke01] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-clepxocrvzdsqcrekectpvenhrboyyob
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404343436.45-207837475094541/nova_compute", line 1490, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404343436.45-207837475094541/nova_compute", line 266, in main
    _create_server(module, nova)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1404343436.45-207837475094541/nova_compute", line 184, in _create_server
    private = [ x['addr'] for x in getattr(server, 'addresses').itervalues().next() if 'OS-EXT-IPS:type' in x and x['OS-EXT-IPS:type'] == 'fixed']
StopIteration
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
