### ISSUE TITLE
Ansible hangs when trying to connect to MacOS Ventura, Apple M1

### ISSUE THREAD

**Issue by jackfarzan** [ansible/ansible#80341]
### Summary

I've been using Ansible to run scripts on an M1 Mac mini, previously running Big Sur but I have just upgraded to Ventura 13.2.1. 

Ansible has been unable to connect to this machine since the upgrade. It's been working as usual with the Mac Intel machine I have that was also upgraded to Ventura. I've enabled the debug variable and it hangs after these logs:

```
<> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=60)
<> SSH: Set ssh_common_args: ()
<> SSH: Set ssh_extra_args: ()
<> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/home/jenkins/.ansible/cp/1565a75b80")
<> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="jenkins"' -o ConnectTimeout=60 -o 'ControlPath="/home/jenkins/.ansible/cp/1565a75b80"' x.x.x.x '/bin/sh -c '"'"'chmod u+x /Users/jenkins/.ansible/tmp/ansible-tmp-1680029425.1518364-88-157089100555109/ /Users/jenkins/.ansible/tmp/ansible-tmp-1680029425.1518364-88-157089100555109/AnsiballZ_setup.py && sleep 0'"'"''
```
 No error, no timeout, it just hangs. 

### Issue Type

Bug Report

### Component Name

ssh

### Ansible Version

```console
$ ansible --version 
ansible [core 2.14.3]
  config file = /var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, Nov 23 2021, 15:27:38) [GCC 9.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg) = False
HOST_KEY_CHECKING(/var/jenkins/workspace/job-testing/cai-helper-build-valet-release-macarm64-TEST/ansible.cfg) = False
```

### OS / Environment

MacOS Ventura 13.2.1

### Steps to Reproduce

Try running Ansible remotely on a MacOS M1 Ventura machine

### Expected Results

Expect Ansible to run

### Actual Results

```console
Ansible hangs with no timeout or error
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattclay** [comment]
Hi!

Thanks very much for your interest in Ansible.  It means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

This appears to be an issue with SSH, not with Ansible. You may want to try running SSHD in debug mode.

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
