### ISSUE TITLE
Update P() semantic markup example

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#80447]
### Summary

The new semantic markup examples for P() mistakenly still use the M() markup :-)

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/dev_guide/developing_modules_documenting.rst

### Ansible Version

```console
$ ansible --version
2.15
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
none
```

### OS / Environment

none

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
docs fix - change M() to P() at https://github.com/ansible/ansible/blame/devel/docs/docsite/rst/dev_guide/developing_modules_documenting.rst#L265

**Comment by Christinanik251** [comment]
Hello!
My name is Christina and I am a university student trying to familiarize myself with contributing in open-source software. I would be very interested in helping out in the documentation before trying out writing code. Since this is an easy fix issue can I go ahead and correct it? Thank you in advance!

**Comment by samccann** [comment]
Welcome @Christinanik251 ! I've assigned this issue to you and thanks for volunteering!  Add a comment here if you need help along the way.
