### ISSUE TITLE
2.14.4: Unable to run tests when packaging ansible-core for Arch Linux (modules not found)

### ISSUE THREAD

**Issue by dvzrv** [ansible/ansible#80472]
### Summary

Hi! I maintain the ansible-core package on Arch Linux.
I am looking into running (ideally only unit) tests when building the package, but it looks like this is impossible using plain `pytest`.
As bit of background: I have been trying to run tests since 2.14, but the attempt to run them goes back much further than that and we have so far not succeeded.

We create packages in pristine [systemd-nspawn](https://man.archlinux.org/man/systemd-nspawn.1) environments which (should) have all the required build/test and eventually also runtime requirements for a package. We use a PEP517 based workflow in which [build](https://github.com/pypa/build) is used to create a wheel from an sdist/source tarball and [installer](https://github.com/pypa/installer) to install the resulting wheel.

Testing usually means running `pytest` on a specific directory *just works*. Sometimes one has to massage the visibility of the thing one is packaging in by using `PYTHONPATH` (e.g. by installing the wheel to a temporary directory and then providing the `site-packages` dir in there in `PYTHONPATH`).

However, running `pytest` on ansible-core does not work: Neither plainly, e.g. by providing the `lib` dir in `PYTHONPATH` and the `bin` dir in `PATH`, nor by first installing to a temporary directory and providing `site-packages` in `PYTHONPATH` and the resulting `bin` dir in `PATH`.
Nearly 500 tests fail because they can not find ansible-core internals (see examples below).

FWIW, I have also tried running `ansible-test units` but that seems to result in even more obfuscated issues that I am unable to solve.

I would really love to be able to run tests and ensure ansible-core's functionality in the Arch Linux ecosystem (which would give me a much much higher confidence in the package actually working). Currently this is unfortunately not possible. Pointers as to what to try would be very much appreciated, as I am by now all out of ideas.

### Issue Type

Bug Report

### Component Name

installation

### Ansible Version

```console
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dave/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/dave/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Arch Linux

### Steps to Reproduce

Please have a look at the attached long check output!

```shell
python -m build --wheel --no-isolation
make docs
export PYTHONPATH="lib:$PYTHONPATH"
export PATH="bin:$PATH"
# ignoring a lot of tests because pytest errors on them during collection
pytest -vv --ignore test/integration/ --ignore test/ansible_test/
```
[ansible-core-2.14.4-3-x86_64-build.log](https://github.com/ansible/ansible/files/11199422/ansible-core-2.14.4-3-x86_64-build.log)
[ansible-core-2.14.4-3-x86_64-check.log](https://github.com/ansible/ansible/files/11199423/ansible-core-2.14.4-3-x86_64-check.log)

```shell
python -m build --wheel --no-isolation
make docs
python -m installer --destdir=test_dir dist/*.whl
export PYTHONPATH="test_dir/$site_packages:$PYTHONPATH"
export PATH="$PWD/test_dir/usr/bin:$PATH"
pytest -vv test/units/
```

[ansible-core-2.14.4-3-x86_64-build.log](https://github.com/ansible/ansible/files/11199529/ansible-core-2.14.4-3-x86_64-build.log)
[ansible-core-2.14.4-3-x86_64-check.log](https://github.com/ansible/ansible/files/11199530/ansible-core-2.14.4-3-x86_64-check.log)

```shell
python -m build --wheel --no-isolation
make docs
bin/ansible-test units
```

[ansible-core-2.14.4-3-x86_64-build.log](https://github.com/ansible/ansible/files/11199565/ansible-core-2.14.4-3-x86_64-build.log)
[ansible-core-2.14.4-3-x86_64-check.log](https://github.com/ansible/ansible/files/11199566/ansible-core-2.14.4-3-x86_64-check.log)

### Expected Results

All tests find the internals of ansible-core. Tests can be run using pytest.

### Actual Results

```console
____________________________ test_warning_no_color _____________________________

thing = <module 'ansible' from '/build/ansible-core/src/ansible-core-2.14.4/lib/ansible/__init__.py'>
comp = 'utils', import_path = 'ansible.utils'

    def _dot_lookup(thing, comp, import_path):
        try:
>           return getattr(thing, comp)
E           AttributeError: module 'ansible' has no attribute 'utils'

/usr/lib/python3.10/unittest/mock.py:1248: AttributeError

During handling of the above exception, another exception occurred:

capsys = <_pytest.capture.CaptureFixture object at 0x7f8bb2e8d2d0>
mocker = <pytest_mock.plugin.MockerFixture object at 0x7f8bb2e8f550>
warning_message = 'bad things will happen'

    def test_warning_no_color(capsys, mocker, warning_message):
        warning_message, expected_warning_message = warning_message

>       mocker.patch('ansible.utils.color.ANSIBLE_COLOR', False)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by dvzrv** [comment]
cc @svenstaro @Antiz96

**Comment by dvzrv** [comment]
As a short addendum: You can find the current PKGBUILD (build script) for ansible-core [here](https://github.com/archlinux/svntogit-community/blob/packages/ansible-core/trunk/PKGBUILD) in case you want to check up on dependencies, etc.

**Comment by sivel** [comment]
I would not advise calling `pytest` directly, as I cannot guarantee the instructions and invocation will continue to work for any given period of time. As this is not a public entry point for running tests, you would have to adjust your invocation to follow how `ansible-test` invokes it constantly.

What you should do is just use `ansible-test` directly:

```
bin/ansible-test units --requirements --python 3.11 --truncate 0
```

You can omit `--requirements` but you will be responsible for installing all of the necessary dependencies ahead of time. See the examples below for the requirements and constraints files. Note that we also constrain our python dependencies, and only test within those constraints. If you satisfy deps by another means that fall outside of our constraints, the tests may not function properly.  Instead of `--requirements`, you can also use `--venv` which will create a virtual environment for the test, and install the python deps via pip into the virtual env automatically.

Now, one thing to note about `ansible-test` is that it breaks up the `pytest` invocations across subsets of files, and if a subset were to fail, it will abort, and not continue.

To see the commands that `ansible-test` is running in full you can use the `--truncate 0` argument. The following is roughly equivalent to what `ansible-test` is running, but without chunking the invocation:

```
pip install -r ./test/lib/ansible_test/_data/requirements/ansible.txt \
    -r ./test/lib/ansible_test/_data/requirements/units.txt \
    -r ./test/units/requirements.txt \
    -c ./test/lib/ansible_test/_data/requirements/constraints.txt

PYTHONPATH=lib:$PYTHONPATH pytest --forked -r a -n auto \
    --color yes -p no:cacheprovider \
    -c ./test/lib/ansible_test/_data/pytest/config/default.ini \
    --strict-markers --rootdir . --durations=25 test/units/
```

As you can probably tell, those files are not necessarily supposed to be used publicly, and they could move, or be renamed without warning.

Another point here, is that our units are designed primarily for running inside of our `default` container image (invoked with `--docker default` instead of `--requirements` or `--venv`), and are not necessarily guaranteed to work outside of those containers.  There may be other required dependencies not solved by python packages, and not strictly documented anywhere.  In at least one of your examples, you are missing `ssh-keygen`.

While we do usually address unit test failures that happen as a result of running in some other environment, we cannot necessarily prevent them from regressing, or new tests being implemented that only pass in some environments, as a result of only running the units in CI within an expected environment defined by our container images.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible-devel or #ansible-packaging on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
