### ISSUE TITLE
Support apt-mark hold

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#8060]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4

(but current documentation suggests it's not available in latest either)
##### Environment:

Debian/Ubuntu
##### Summary:

Support apt-mark hold/unhold to mark a package as ineligible for automatic updates. Otherwise, ansible can install a particular version of a package, only to see it blown away with a more recent one later.

https://help.ubuntu.com/community/PinningHowto#Introduction%20to%20Holding%20Packages
##### Steps To Reproduce:

```
- action: apt pkg=condor=8.0.7-250355 state=present
... later
- action: apt upgrade=dist
```

ends up with an unexpected version of the package installed.
##### Expected Results:

Would like to be able to do something like this:

```
- action: apt pkg=condor=8.0.7-250355 state=present hold=yes
```

hold=yes/no would correspond to apt-mark hold/unhold.

For completeness, you could support the manual/auto flag too. So another syntax would be

```
- action: apt pkg=condor=8.0.7-250355 state=present mark=hold
... or ...
- action: apt pkg=condor=8.0.7-250355 state=present mark=hold,manual
```

Arguably, whenever you use ansible to install a _specific_ version of a package then it should be held (and implicitly unheld if you specify "state=latest").

ansible 1.4 doesn't appear to do that, but maybe it's changed in later version.
##### Actual Results:

Currently no obvious ansible way to mark a package as held.

Workaround: use shell to run "apt-mark hold <package>". But this will be run on every ansible run, and relies on apt-mark itself being idempotent.

**Comment by sidharthsurana** [comment]
+1 for the request.. specially the auto hold if a specific version was requested

**Comment by scottnonnenberg** [comment]
+1 - with apticron installed, it's important to have holds in place. And right now, I'm doing this manually.

**Comment by Janfy** [comment]
+1

**Comment by pztrick** [comment]
+1

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
