### ISSUE TITLE
play_hosts doesn't reflect correct list in handlers when when: is used

### ISSUE THREAD

**Issue by nathanhruby** [ansible/ansible#8073]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Mac OSX 10.9.3
##### Summary:

When firing a handler from a task with notify: limited to specific hosts via a when: clause, play_hosts in the handler reflects only the hosts that triggered a notify:
##### Steps To Reproduce:

runn playbook and inventory from https://drive.google.com/file/d/0B7vhBal_UqRNMGdwTkNxSzZmRTg/edit?usp=sharing

see example output below.
##### Expected Results:

play_hosts should reflect the host in the play, regardless of limit
##### Actual Results:

```
[nhruby@badhorse ../ansible-handler-play-hosts]$ ansible-playbook -i test.inv test.yml

PLAY [test handler from role] *************************************************

GATHERING FACTS ***************************************************************
ok: [test2]
ok: [test1]

TASK: [testhandler | this is a test role task for all] ************************
changed: [test1] => {
    "changed": true,
    "play_hosts": [
        "test1",
        "test2"
    ]
}
changed: [test2] => {
    "changed": true,
    "play_hosts": [
        "test1",
        "test2"
    ]
}

TASK: [testhandler | this is a test role task limited and notifies] ***********
skipping: [test2]
changed: [test1] => {
    "changed": true,
    "play_hosts": [
        "test1",
        "test2"
    ]
}

NOTIFIED: [testhandler | this is a test role handler] *************************
ok: [test1] => {
    "play_hosts": [
        "test1"
    ]
}

PLAY RECAP ********************************************************************
test1                      : ok=4    changed=2    unreachable=0    failed=0
test2                      : ok=2    changed=1    unreachable=0    failed=0

[nhruby@badhorse ../ansible-handler-play-hosts]$
```

**Comment by jimi-c** [comment]
Hi @nathanhruby, looking back at this issue, and I believe what's happening here is correct and to be expected. Handlers do not execute in the normal host loop, but instead are restricted to a unique list of only those hosts which received the notification for that given handler. I am very willing to concede that that variable is not appropriately named, as it is really the hosts active for the current task and not for the play overall. For instance, adding a third host (essentually duplicating test1 in your example) with the following task in your example role:

<pre>
  - name: fail one host
    fail:
    when: inventory_hostname == 'test3'
</pre>

results in the following `play_hosts` list for your first debug statement:

<pre>
TASK: [testhandler | fail one host] ******************************************* 
skipping: [test1]
skipping: [test2]
failed: [test3] => {"failed": true}
msg: Failed as requested from task
TASK: [testhandler | this is a test role task for all] ************************ 
changed: [test1] => {
    "changed": true,
    "var": {
        "play_hosts": [
            "test1",
            "test2"
        ]
    }
}
changed: [test2] => {
    "changed": true,
    "var": {
        "play_hosts": [
            "test1",
            "test2"
        ]
    }
}
</pre>

Given that this variable has existed for a while, I'm not sure we can change it without potentially breaking existing playbooks in the wild.

If you're satisfied with this explanation, we can close this issue, otherwise let us know if you have any further questions, comments, or concerns.

Thanks!

**Comment by nathanhruby** [comment]
Hi,

This report is so old, I don't remember the specific of the original issue I encountered.  Most probably I was trying to trigger cache refreshes across the play hosts after a build process on one specific member, and was trying to do so in a handler versus inlining with a register/conditional in my may task file.

If this is the expected behavior, that's fine, but I would request to have that expectation explicit in the documentation for play_hosts.

Thanks!

-n

**Comment by jimi-c** [comment]
No problem, we're actually going to fix this to resemble what you had expected above, as the v2 rewrite hadn't implemented this magic variable yet.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
