### ISSUE TITLE
unarchive extra_opts '-j' : path does not exist

### ISSUE THREAD

**Issue by tholeb** [ansible/ansible#81084]
### Summary

I want to extract a single file from an archive. So I ignore all the others inside and add the '-j' (junk) extra opts. Without the extra opts, the task runs well (I only have the file I want and an empty folder for some reason). But when I add the extra opts '-j', the task fails with `path b'/tmp/test/subfolder' does not exist`. 

When i do the command by hand : `unzip -j -o archive.zip -x "*.MF" "*.xml" "*.yaml" -d /tmp/test` I have no problem, it only extract the file I want without subfolders. 

The archive structure : 
```
/tmp/test
├── META-INF
│   └── MANIFEST.MF
└── rundeck-projectname
    ├── files
    │   └── etc
    │       └── project.properties # (the only file I want to keep)
    ├── jobs
    │   └── job.xml
    └── webhooks.yaml
```

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 14 2020, 14:45:30) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
# empty
```

### OS / Environment

CentOS 7 

### Steps to Reproduce

```yaml (paste below)
- name : Unzip files in /tmp/test
      unarchive:
        src: archive.zip"
        dest: "/tmp/test"
        remote_src: true
        extra_opts:
          - '-j'
        exclude:
          - '*.MF'
          - '*.xml'
          - '*.yaml'
```

### Expected Results

I expect to **only** get the file `project.properties` in `/tmp/test/`.

### Actual Results

```console
"ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/tmp/test", 
            "directory_mode": null, 
            "exclude": [
                "*.MF", 
                "*.xml", 
                "*.yaml"
            ], 
            "extra_opts": [
                "-j"
            ], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "owner": null, 
            "regexp": null, 
            "remote_src": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/path/to/archive.zip", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "item": "pulse", 
    "msg": "path b'/tmp/test/subfolder/jobs/' does not exist", 
    "path": "/tmp/test/rundeck-pulse/jobs/"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tholeb** [comment]
I've just checked the file, and it's not a zip file, but a jar file.

**Comment by bcoca** [comment]
Hi!

Thanks very much for your submission to Ansible.  It means a lot to us.

The `-j` option is incompatible with how the module works as it needs to verify paths to detect changes. Not all possible options that you can pass via  `extra_opts` are supported. 

We would suggest using `command`/`shell` actions in this case as the options supplied already make most of the features you get by using `unarchive` irrelevant.

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
The mailing list and irc are great ways to ask questions, or post if you don't think this particular issue is resolved.

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Thank you once again for this and your interest in Ansible!
