### ISSUE TITLE
vars_files silently ignores single file if undefined var is a part of filename

### ISSUE THREAD

**Issue by mkoshelev** [ansible/ansible#8109]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Fedora 20
##### Summary:

If the filename used in vars_files includes undefined variable, ansible just silently ignores this include - no error or even 'not importing' messages displayed.
This issue seems to be present in all ansible versions.
##### Steps To Reproduce:

Run the following playbook:

```
- name: demonstrate bug with var_files and undefined variable
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - "vars/vars_{{ undefined_var }}.yml"

  tasks:

  - name: report run results
    debug: msg="paybook started despite non-existing file included in vars_files, no error|warning|any message is shown"
```
##### Expected Results:

Playbook should probably fail due to undefined variable. Or fail with "ERROR: file could not read" message, just like it does in case when filename is text or based on actually defined variable - and the file doesn't exists.
##### Actual Results:

Playbook runs without any errors or messages about missing/not importing file.

```
PLAY [demonstrate bug with var_files and undefined variable] ****************** 

TASK: [report run results] **************************************************** 
ok: [localhost] => {
    "msg": "paybook started despite non-existing file included in vars_files, no error|warning|any message is shown"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
This is somewhat of a feature when the argument to vars_files is a list.   If there is only one in the list, however, I agree it should be an error condition.

**Comment by anentropic** [comment]
This would help a lot debugging

I have this:

```
  vars_files:
    - group_vars/{{ inventory_file | basename }}.yml

  tasks:
    - name: Debug - inventory
      debug: "msg=\"Inventory: {{ inventory_file | basename }}\""

    - name: Debug - group var
      debug: "msg=\"FROM_GROUP_FILE: {{ FROM_GROUP_FILE }}\""
```

the first debug message prints expected value, suggests that the `vars_files` succeeded but the second debug message raises an error because variable (which should have been loaded from vars file) is undefined

I don't know where I'm wrong, but if I knew that `vars_file` would raise an error then I could eliminate that

**Comment by anentropic** [comment]
and yes, by elimination this worked:

```
 vars_files:
    - group_vars/staging.yml
```

so it's the variable interpolation in the `vars_files` directive which doesn't work and failed silently :(

**Comment by jimi-c** [comment]
Hi @mkoshelev, sorry for the late follow-up on this.

This should no longer be the case as of 2.0, which should raise an error if the vars files list is templated at a late stage but the file name still has an unresolved variable in it. As such, I'll go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
