### ISSUE TITLE
ec2_vpc should set subnet resource_tags even if the subnet already exists.

### ISSUE THREAD

**Issue by altruism** [ansible/ansible#8147]
#6081 added support for setting tags on subnets, but it only sets those tags if it also creates the subnets. If a subnet already exists, its tags will not be changed.

I'd like the behavior of this module to be such that if I add a new resource tag to a subnet that already exists, that tag will be added or replaced when the module is run. I think this supports the main use case for tagging subnets, which is to be able to reference subnets by AZ + vpc + tag rather than by bare subnet id.
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.6
##### Environment:

N/A
##### Summary:
#6081 added support for setting tags on subnets with `resource_tags`, but it only sets those tags if it also creates the subnets. If a subnet already exists, its tags will not be changed. It would be cool if the tags would always be set to what's in my playbook instead of only being set if the subnet is created.

I'd like the behavior of this module to be such that if I add a new resource tag to a subnet that already exists, that tag will be added or replaced when the module is run. I think this supports the main use case for tagging subnets, which is to be able to reference subnets by AZ + vpc + tag rather than by bare subnet id.
##### Steps To Reproduce:

Use `ec2_vpc` to create a subnet in a VPC without specifying `resource_tags` for that subnet. The `subnets` parameter should be something like this:

```
subnets:
  - cidr: 10.0.0.0/18
    az: "us-east-1a"
```

Run that task.

Modify the playbook to add a `resource_tags` parameter:

```
subnets:
  - cidr: "10.0.0.0/18"
    az: "us-east-1a"
    resource_tags:
      Environment: Dev
```

Run the task again.
##### Expected Results:

The subnet created after the first run has a tag "Environment" with value "Dev".
##### Actual Results:

The subnet has no tags.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
