### ISSUE TITLE
Support install in $HOME with --user

### ISSUE THREAD

**Issue by IsoLinearCHiP** [ansible/ansible#8148]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.7 (devel 4b8dcb2ae4) last updated 2014/07/15 18:25:10 (GMT +200)
##### Environment:

Any supported platform of ansible?
##### Summary:

Support install in $HOME through setuptools `--user` parameter.

After quite some time of unsuccessfully trying to `pip install --user ansible` or `pip install ansible` in a `virtualenv` I finally came across the mention of running it from a git checkout, however being able to use the 'standard' install locally process would be a nice comfort feature.

The setup script keeps trying to overwrite `/usr/share/ansible`

```
....
creating /usr/share/ansible
error: could not create '/usr/share/ansible': Permission denied
```

Hopefully http://legacy.python.org/dev/peps/pep-0370/ provides the information necessary to adjust the installer to not create system wide directories when `--user` is specified

**Comment by mpdehaan** [comment]
Various duplicates of this bug, I'm not against it but would need to see some code submitted and it would have to be reasonably clean.

We are a LSB-compliant systems management application that happens to be written in Python, we do not take the view that we are pure-python application that needs to support python development tools in all forms.

We actually allow modules to be written in other languages, etc, and the core modules are only all Python by convention, and are being installed in data locations rather than hidden away in ~/.

I understand different people have contrasting views.
