### ISSUE TITLE
remove code dealing with relative symlink paths in file module

### ISSUE THREAD

**Issue by pilt** [ansible/ansible#815]
[Problematic code](https://github.com/ansible/ansible/blob/devel/library/file#L319-324):

``` python
if os.path.isabs(src):
    abs_src = src
else:
    abs_src = os.path.join(os.path.dirname(dest), src)
```

First, dest is undefined which raises an exception. It should be path. Second, I wonder if this is expected behavior? If I write `file src=a/b dest=a/c state=link`, do I want the link to point to ...a/a/b?

**Comment by mpdehaan** [comment]
Two things:

(A) src and dest both should require absolute paths.   The non-abs code path there needs to be shot, and we should check earlier that dest is an absolute path and raise an error in all cases (not just links)

(B) it's probably module.params['dest'], but it's invalid because we shouldn't be supporting relative paths.

updated the description

**Comment by mpdehaan** [comment]
I made the relative usage an error now which removes the code problem, and also the ambiguity.  Let me know if you hit any further problems.  Thanks!

**Comment by pilt** [comment]
Thanks!
