### ISSUE TITLE
ec2_vol error on Eucalyptus-based clouds (3.4 and higher)

### ISSUE THREAD

**Issue by baughj** [ansible/ansible#8151]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

N/A
##### Summary:

ec2_vol is unable to create volumes against Eucalyptus clouds (tested with 3.4, 4.0)
##### Steps To Reproduce:

Run the following against a Eucalyptus endpoint with appropriate values:

``` yml
- name: Create and attach data volume to the instance
  local_action:
    module: ec2_vol
    instance: "{{ ec2_instance_id }}"
    volume_size: "{{ data_volume_size }}"
    ec2_url: "{{ eucalyptus_url }}"
```
##### Expected Results:

Volume is created.
##### Actual Results:

`failed: [<hostname>] => {"failed": true}`
 `msg: OperationNotPermitted: Instance's platform is not Windows`

ec2_vol is using EC2's GetPasswordData to guess if an instance is Windows. However, this call against a Eucalyptus cloud results in an OperationNotPermitted error, with the message "Instance's platform is not Windows". 

This is a deviation from the behavior of EC2 so I will report it upstream to Eucalyptus. However, it would still be nice if ec2_vol handled this error. Below is one way of doing that:

``` diff
diff --git a/library/cloud/ec2_vol b/library/cloud/ec2_vol
index 59347a6..a1da816 100644
--- a/library/cloud/ec2_vol
+++ b/library/cloud/ec2_vol
@@ -278,7 +278,14 @@ def attach_volume(module, ec2, volume, instance):
     # Use password data attribute to tell whether the instance is Windows or Li
     if device_name is None and instance:
         try:
-            if not ec2.get_password_data(instance.id):
+            try:
+                instance_pwdata = ec2.get_password_data(instance.id)
+            except boto.exception.EC2ResponseError, e:
+                if e.error_code == "OperationNotPermitted":
+                    instance_pwdata = False
+                else:
+                    module.fail_json(msg = "%s: %s" % (e.error_code, e.error_message))
+            if not instance_pwdata:
                 device_name = '/dev/sdf'
                 attach = volume.attach(instance.id, device_name)
                 while volume.attachment_state() != 'attached':
```

With the patch I get what I would expect:

`ok: [<hostname>] => {"changed": false, "device": null, "volume_id": "vol-c2c056aa"}`

I am happy to submit a PR; I wasn't sure if it was overkill for something so trivial.

**Comment by mpdehaan** [comment]
A PR would be welcome, we don't really spend any time on Eucalyptus compatibility or testing, but if Eucalyptus developing or using folk would like to supply it, that would be great.

Thanks!

**Comment by baughj** [comment]
I've noticed a few other issues with Eucalyptus support in my recent work. Do I need to open issues for each one or is it acceptable for me to just submit a PR that handles all of them?

Thanks again.

-Justin

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
