### ISSUE TITLE
known_hosts file with paramiko connection could be erased during well-timed interrupt

### ISSUE THREAD

**Issue by kmarion-tx** [ansible/ansible#8169]
##### Issue Type:

Bug Report
##### Ansible Version:

/usr/bin/ansible --version
ansible 1.5.5
##### Environment:

RHEL 6
##### Summary:

The /root/.ssh/known_hosts file is being partially wiped.

Allowing the command below to complete causes no problem.

Pressing CTRL-C will wipe the massive /root/.ssh/known_hosts during 5 different tests. It would be from a different point in the file, probably related to the device in use and the location of the device in known_hosts, but from that point down, contents are removed.
##### Steps To Reproduce:

sudo /usr/bin/ansible -C --private-key /root/.ssh/my_test_key -i /home/ansible/production/devices devices_ca -m setup --tree /home/ansible/production/facts.d/
##### Expected Results:

Only updates, additions, or no modifications are expected to /root/.ssh/known_hosts
##### Actual Results:

Pressing CTRL-C will partially wipe the massive /root/.ssh/known_hosts

**Comment by mpdehaan** [comment]
Ouch.

FYI - The latest version of Ansible is 1.6.6 and you should upgrade (see the changelog, there are security updates included).  This won't fix this problem.

This should only happen to users using paramiko.  As you are running from RHEL 6, you are using paramiko and paramiko needs to record the new host in the host file and we have that implemented manually.

In this case, you probably hit control-c as the file was being rewritten, and the library doing this is paramiko itself.

A temporary solution would be to run Ansible from a more-updated host, like Ubuntu or OS X or Fedora, where there is a newer SSH and ansible can use OpenSSH and not paramiko by default - or you could turn off ansible host key checking, which is also not an option if you like that behavior.

Although what we need to do here is utilize the atomic_move methods we have for the rest of ansible to replace the known host file.

I'm filing this as a P2 bug and we'll take care of it.  We are sorry for the inconvenience.   I don't think anyone has hit Control+C with exactly that timing before, but that's not something I'd find acceptable.   

Thanks for the report.

**Comment by jimi-c** [comment]
I have pushed the above commit to resolve this issue. If you continue seeing any problems related to this, please let us know. Thanks!

**Comment by jimi-c** [comment]
Re-opening, due to an issue with the above patch.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
