### ISSUE TITLE
Remove space in env for docker module

### ISSUE THREAD

**Issue by kuon** [ansible/ansible#8199]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Running from Mac OS X 10.9.4 on Ubuntu 14.04 LTS.
##### Summary:

When writing env var on multiple line with the docker module, env vars have a space prepended.
##### Steps To Reproduce:

Use the docker module with newline to separate env vars (for readability).

Example:

```
- name: Postgresql Instance
  docker:
    image=docker.mwy.io/postgresql
    env="PG_ROLE=master,
         PG_PORT=5432,
         PG_ENABLE_ARCHIVING=1,
         PG_ENABLE_WALE=1,
         about 20 more..."
```
##### Expected Results:

Env var should not have a space prepended
##### Actual Results:

```
docker inspect
```

shows something like:

```
    "Env": [
        "PG_ROLE=master",
        " PG_ENABLE_WALE=1",
        " PG_ENABLE_ARCHIVING=1",
        " PG_RESTORE_WALE_BACKUP=LATEST",
        " PG_PORT=5432",
         /\--- extra space prefixed
```

**Comment by mpdehaan** [comment]
This module should really be used with complex (hash) vars in this case.   We would want to make sure the examples didn't show strings.

**Comment by mpdehaan** [comment]
I suggested recently on the list that this should be "type=dict" in Ansible, though this may break some existing uses. This is something we'll need to consider.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
