### ISSUE TITLE
Docker module issue with username and password

### ISSUE THREAD

**Issue by kuon** [ansible/ansible#8202]
##### Issue Type:

What kind of ticket is this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version:

ansible 1.6.6
##### Environment:

Running from OS X 10.9.4 on Linux Ubuntu 14.04 LTS
##### Summary:

When using the docker module, the username and password options are ignored. Thus, images cannot be pulled from private repositories.
##### Steps To Reproduce:

Create a simple playbook with:

```
- docker: image=someprivaterepository/imagename username=auser password=apass
```

Run the playbook.
##### Expected Results:

The image should be pulled from the private repository and the docker instance should be started.
##### Actual Results:

```
msg: unsupported parameter for module: username

FATAL: all hosts have already failed -- aborting
```

Without the username/password parameter, the error is:

```
msg: Docker API error: No such image: privatereregistry/image (tag: latest)

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
The beauty of open source submissions :)

Yes, it appears nothing is using the username parameter.   Something you might like to work on, perhaps?

**Comment by kuon** [comment]
I've been using ansible for two days, I need a little time to dive in. But if no one chimes in for the next days/weeks, I'll come with a fix when I'm able.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the commit merged from https://github.com/ansible/ansible/pull/8095 should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
