### ISSUE TITLE
Module mysql_user return traceback if privileges are no specify

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8222]
##### Issue Type:

“Bug Report” 
##### Ansible Version:

1.7
##### Environment:

Centos 6.5
##### Summary:

Running module mysql_user with missing privileges return Traceback.
##### Steps To Reproduce:

```
- name: test state=present for a user with no priveleges (expect changed=true)
  mysql_user: name={{ user_name_1 }} password={{ user_password_1 }} state=present
  register: result
```
##### Expected Results:

There should be no Traceback return when privileges are missing. A friendly message should be return such as 'privileges are missing or required'
##### Actual Results:

```
ok: [testhost] => {
    "result": {
        "failed": true, 
        "invocation": {
            "module_args": "name=db_user1 password=12345 state=present", 
            "module_name": "mysql_user"
        }, 
        "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1405960380.02-47993263932027/mysql_user\", line 1774, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1405960380.02-47993263932027/mysql_user\", line 462, in main\n    changed = user_add(cursor, user, host, password, priv)\n  File \"/root/.ansible/tmp/ansible-tmp-1405960380.02-47993263932027/mysql_user\", line 161, in user_add\n    cursor.execute(\"CREATE USER %s@%s IDENTIFIED BY %s\", (user,host,password))\n  File \"/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py\", line 173, in execute\n    self.errorhandler(self, exc, value)\n  File \"/usr/lib64/python2.6/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\n_mysql_exceptions.OperationalError: (1396, \"Operation CREATE USER failed for 'db_user1'@'localhost'\")\n", 
        "parsed": false
    }
}

```

**Comment by jimmykane** [comment]
Same issue here

**Comment by Jmainguy** [comment]
Tested on a Centos 6.5 target and I was unable to produce the tracebook using the test above. I tried on 1.7.0 and devel. mysql_user: name=jon password=jon state=present. What target OS were you guys getting this error on?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
