### ISSUE TITLE
vars_plugins are invoked twice

### ISSUE THREAD

**Issue by jpetrelliswork** [ansible/ansible#8225]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

RHEL6
##### Summary:

When using vars_plugins, the plugins are executed twice.  Our plugin pulls in a large file and parses it, so running twice kills performance.  

The inventory._vars_per_host seems to be caching that info. The problem is that it’s called from multiprocessing and so when the process finishes, the cache is lost. The second time get_variables() is called from the main process, the cache needs to be reloaded. A quick and dirty fix would be to add preload _vars_per_host before calling multiprocessing.process().
##### Steps To Reproduce:

Create a vars_plugin and put a "print" statement in run function.  Run ansible -m setup $host.
##### Expected Results:

Should only print once per host.  Indicative of one plugin execution.
##### Actual Results:

Plugin is called twice per host.

**Comment by srgvg** [comment]
This behaviour changed with a recent refactoring of Ansible.Inventory.

Given you use private custom var_plugins, I presume your plugins only provide a VarsModule.run() method. This method is the original method that returns all merged variables per host, and is still used for backwards compatibility. This method is indeed still being called from the multiprocessing instances.

With the refactoring however, two new methods are used if available: get_host_vars() and get_group_vars() which returns _only_ the specific variables from the particular host or group.
See the example https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/vars_plugins/noop.py for the exact method signatures.

That being said, I'll have a look why this changed so that caching doesn't work any more here.

**Comment by srgvg** [comment]
OK, after some digging:
- before the refactoring, vars_plugins were called for _every_ host, again and again, and that was called from (multiprocess) runner and no caching was done ever. 
- after refactoring the run() method ( and the gethost/group_vars() methods) are called at inventory init time, and all is cached there. Those methods are called only once per host or group, and are cached by that host's or group's name. But, given this happens at inventory init time, and not at the time a host is touched, (which gave a small extra time at the beginning of every play), now _all_ hosts and groups are loaded in the inventory, not only those targetted in the runner or the play. 

Yes, this yields a bigger init time, which is noticed with large inventories or many variables.

In you use case, it seems that large file is parsed for _every_ host, which is why you see thet print debug statement multiple times. It doesgets it results cached, but on a per host base, so it indeed will get called again for other hosts.

As I see it, this would have been parsed multiple times before the refactor as well, difference is, you notice it getting reparsed when you only target 1 host too.

Seems like something where you'd need to optimize your plugin.
Perhaps you can link that parsed file to a particular group, and switch to the get group vars method?

**Comment by mpdehaan** [comment]
"Yes, this yields a bigger init time, which is noticed with large inventories or many variables."

We also did a lot of recent refactoring which greatly REDUCES init time, so that may help some.

" now all hosts and groups are loaded in the inventory, not only those targetted in the runner or the play."

IMHO, we should only load the ones that need to be loaded, on demand, when they load.

I'm still going to leave this at present priority though, as right now, there are no stock vars_plugins.

**Comment by srgvg** [comment]
@mpdehaan 

'IMHO, we should only load the ones that need to be loaded, on demand, when they load.'
FYI This was something I brought up when discussing my refactoring, then the increased init time didn't bother you. So I acted forward.

Keep in mind there are different places to load variables, and the code got triggered at different places. This is now a bit better and focused in Inventory. Deferring this would also only be beneficial to part of inventory (e.g. not for InventoryScripts.)

Also that increased init time is minimal and only with large sets of host/group_vars. In the current case, I suspect there are better ways to optimize the OP's inventory.

If you'd like to elaborate on that, you know where to find me.

**Comment by jpetrelliswork** [comment]
Thanks for your responses.

Our install wasn't recent enough to have the refactor (wasn't me!).  It takes care of the issue we're seeing.  I now do the heavy lifting in my vars_plugin.**init**() and cache the output so that get_host_vars() and get_group_vars() can reference it.  

I do still see get_host_vars() being called for each host in inventory, but for how we run things that won't be a problem.

**Comment by srgvg** [comment]
@jpetrelliswork so you had the problem before this refactor? any idea what triggered the difference you noticed?

**Comment by jpetrelliswork** [comment]
It was primarily our lack of optimization.  Along with updating our Ansible to a post-refactor version, I also moved the heavy work into vars_plugin.**init** and added the caching.  After doing both of these things, I retried and the problem was solved.

To be honest I probably wouldn't have even noticed the problem if I had written the plugin correctly from the start.  Since I couldn't pinpoint the issue at first, I decided to dive into the Ansible code and see how the var_plugins stuff worked, which is when I saw the 2 calls.

**Comment by srgvg** [comment]
@jpetrelliswork Does this mean you can close this ticket?

**Comment by srgvg** [comment]
I think we can close this one /cc @jimi-c

**Comment by jpetrelliswork** [comment]
Yes, go for it. Sorry, missed the post

**Comment by jimi-c** [comment]
# Closing This Ticket

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
