### ISSUE TITLE
Handling of ansible_managed variable changes in 2.16

### ISSUE THREAD

**Issue by TheMysteriousX** [ansible/ansible#82322]
### Summary

I think this is could be intended/never fully supported, but it's not explicitly called out in the release notes.

We have _ansible_managed_ overriden in our ansible.cfg:
```
ansible_managed = Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}
```

Prior to 2.16, this worked fine - it embeds a string into the file that identifies which git release the template is taken from:
```
# Ansible managed: automatic.conf.j2@716551c3 modified 2023-04-03 07:25:13 by user@domain: Add new widget server
```

This is incredibly useful for helping someone understand the current state of the system compared to the default string. Upgrading to 2.16, this no longer works. We get the following string: `Ansible managed: {{ lookup('git_info', template_fullpath | quote) }}` I've tried the following variations
```
"Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}"
'Ansible managed: {{{{ lookup("git_info", template_fullpath | quote) }}}}'
Ansible managed: {{ lookup('git_info, template_fullpath | quote) }}
```

But they don't restore functionality. Looking at the release notes, this looks the cause: https://github.com/ansible/ansible/pull/79129
If I revert the changes to `lib/ansible/template/__init__.py`, the string is rendered as before.

It's possible to work around, but I like it when things keep working without changes.

### Issue Type

Bug Report

### Component Name

lib/ansible/template/__init__.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.0]
  config file = ./Developer/ansible/ansible.cfg
  configured module search path = ['./.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', './Developer/ansible/plugins/modules', './.ansible/collections/*/modules']
  ansible python module location = /usr/local/lib/python3.12/site-packages/ansible
  ansible collection location = ./.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.0 (main, Oct  5 2023, 15:52:37) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/usr/local/opt/python@3.12/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(./Developer/ansible/ansible.cfg) = True
CONFIG_FILE() = ./Developer/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/plugins/action', '/usr/share/ansible/plugins/action', './Developer/ansible/plugins/action>
DEFAULT_FILTER_PLUGIN_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/plugins/filter', '/usr/share/ansible/plugins/filter', './Developer/ansible/plugins/filter>
DEFAULT_FORKS(./Developer/ansible/ansible.cfg) = 9
DEFAULT_HOST_LIST(./Developer/ansible/ansible.cfg) = ['./Developer/ansible/inventory']
DEFAULT_JINJA2_NATIVE(./Developer/ansible/ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(./Developer/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(./Developer/ansible/ansible.cfg) = ./.ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup', './Developer/ansible/plugins/lookup>
DEFAULT_MANAGED_STR(./Developer/ansible/ansible.cfg) = Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}
DEFAULT_MODULE_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', './Developer/ansible/plugins/modules', '>
DEFAULT_MODULE_UTILS_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils', './.ansible/collections/>
DEFAULT_ROLES_PATH(./Developer/ansible/ansible.cfg) = ['./.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', './Developer/ansible/roles', '/Users/ad>
DEFAULT_STDOUT_CALLBACK(./Developer/ansible/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(./Developer/ansible/ansible.cfg) = ./Developer/ansible/contrib/vault/lastpass-client.py
DEPRECATION_WARNINGS(./Developer/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = nano
HOST_KEY_CHECKING(./Developer/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(./Developer/ansible/ansible.cfg) = python3
MAX_FILE_SIZE_FOR_DIFF(./Developer/ansible/ansible.cfg) = 208896
PAGER(env: PAGER) = less
PLAYBOOK_DIR(./Developer/ansible/ansible.cfg) = ./Developer/ansible/playbooks:./jobs
USE_PERSISTENT_CONNECTIONS(./Developer/ansible/ansible.cfg) = True
```

### OS / Environment

Mostly RHEL targets, MacOS 15 workstation.

### Steps to Reproduce

In ansible.cfg:
```yaml (paste below)
ansible_managed = Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}
```
In a template:
```yaml (paste below)
{{ ansible_managed }}
```

### Expected Results

Ansible managed: automatic.conf.j2@716551c3 modified 2023-04-03 07:25:13 by user@domain: Add new widget server

### Actual Results

```console
Ansible managed: {{ lookup('git_info', template_fullpath | quote) }}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
most likely the change from using `to_text` to using `to_unsafe_text`

**Comment by vaygr** [comment]
I'm also affected by this.

I have this in the config that no longer works with the new release:

```
ansible_managed = [ generated by Ansible: {{{{template_destpath}}}} ][ {{{{template_path | basename}}}} ] :: [ {{{{inventory_hostname}}}} ] :: [ by {{{{ansible_user}}}} ][ %Y-%m-%d %H:%M:%S ]
```

**Comment by tierpod** [comment]
Hello, we also affected by this issue.

> So this might not be possible to re enable w/o creating a security issue

Sorry, could you please describe more detailed what kind of security issue?

As a workaround we added another custom variable (`ansible_managed_full` or `__ansible_managed`) on inventory group_vars/all level and use this custom variable. How is this different from using modified `ansible_managed` with the same variables in it on ansible.cfg level?

**Comment by pva** [comment]
@bcoca could you please explain, what security issue you are talking about? This affects many people since poor formatting for ansible_managed is not something that can suit the needs of tracing where that file came from.  For example, we've used this for a very long time to mention the git commit that was used as a base for templating:

```
ansible_managed = Ansible managed: {{{{ template_path | basename + lookup('pipe', 'git log --format=",%%h %%ad %%ae" -1 --date=format:"%%Y/%%m/%%d %%H:%%M" ' + template_fullpath | quote) | default(",UNCOMMITED", True) }}}}$
```

And I don't see how we can make this otherwise.

**Comment by bcoca** [comment]
not sure what you want aside from an actual exploit, i showed above already how you can create an opening during templating and file system access.

**Comment by pva** [comment]
@bcoca I don't understand how provided example is a security issue. It looks like just an error and that's it. Could you elaborate on the security aspect of this issue?

**Comment by pva** [comment]
> The changes were guarding against hings like `src: "templates/completely{{ 1 % 0 }} safe template.j2"` which prevents templating on the provided variables. So this might not be possible to re enable w/o creating a security issue.

So as I read this example, we have a variable that will not be rendered due to exception and I'll get an error like:

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ZeroDivisionError: integer division or modulo by zero

How is this a security issue? @bcoca are you sure that we have a security issue here? Could you, please, explain what attack vector is here? Otherwise, there is still a workaround @tierpod suggested that could be used as well and I'm sure people will start doing that without understanding the security implications.

**Comment by Rina-Y** [comment]
I think this is the same issue I was encountering attempting to allow collections to work in the pipx install of ansible.  
The default `ansible --version` shows up as 

`ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections`

Which doesn't actually contain the location of the static ansible collections since they are located in `~/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections'` So I just loaded up an `ansible-config init --disabled` dump for my .ansible.cfg to attempt to fix the ansible collection locations.

The default output by ansible-config for the collections_path is:

`;collections_path={{ ANSIBLE_HOME ~ "/collections:/usr/share/ansible/collections" }}`

Which makes sense, all of the paths inside the config file look like this.  So I uncommented it and changed the /usr/share portion to point to the pipx location... and ansible --version now shows up with... 

`ansible collection location = /home/username/{{ ANSIBLE_HOME ~ "/collections:/home/username/.local/pipx/venvs/ansible/lib/python3.11/site-packages" }}`

I wasted so much time trying to get something to work so I could actually use ansible.  I did end up with something, but it basically was a colon separated list of absolute paths.   Something seems to have changed in ansible's config parser such that config program outputs defaults that don't work... and it's not just the `ansible-managed` variable as the OP posted... the defaults don't even work anymore.

**Comment by lotusnoir** [comment]
having the same issue here, downgrading ansible back to 2.15... :(

**Comment by bcoca** [comment]
@Rina-Y the defaults can be templated, but assigned values cannot. The generated file should not have 'templatable' entries but fully templated ones, this is a bug and a different issue than what is being discussed here.

**Comment by bcoca** [comment]
@pva that is just an example of how a specially crafted filename can force template execution, the template I use is mostly benign, but it is just as easy to create one that is not.

**Comment by andreymal** [comment]
>a specially crafted filename can force template execution

So what?

Since Ansible is a tool for executing arbitrary code, I don't really understand how having an additional way to execute something affects security (and that's why I still use 2.15)

**Comment by davidwinterstein** [comment]
Apart from me not understanding the security implications, removing parsing from `ansible_managed` also removed some functionality that has been relied upon by quite some people.  
We are also using a dynamic `ansible_managed` variable to provide clear information to anyone on a server exactly where a file is coming from and what state it is in:

```
ansible_managed =    ! managed by ansible !
    repo:     xxx
    role:     {{{{ role_name | default("no role", True) }}}}
    template: {{{{ template_path | basename }}}}
    commit:   {{{{ lookup('pipe', 'git log --format="#%%h ~ %%ae @ %%ad" -1 --date=format:"%%Y-%%m-%%d %%H:%%M" ' + template_fullpath | quote) | default("#uncommited", True) }}}}
```

Would it be possible to provide that functionality in some other way, or maybe create an optional config flag that could be enabled to have ansible parse the variable like before?
