### ISSUE TITLE
apt upgrade safe is sometimes stuck

### ISSUE THREAD

**Issue by YAmikep** [ansible/ansible#8251]
##### Issue Type:

Bug Report
##### Ansible Version:

```
vagrant@main:$ ansible --version
ansible 1.6.7
```
##### Environment:

They are all Ubuntu 14.04 (host and remote machines).
##### Summary:

I am running the playbook with two remote machines.
The task with apt is sometimes stuck forever.
It does not always appear and sometimes it is just on one machine.
The fact that it does not behave the same way every time makes the apt module not reliable. Sometimes it works, that is great and sometimes it will be stuck for no reason.

I look at the following logs  (/var/log/apt/history.log ; /var/log/apt/term.log ; /var/log/dpkg.log) and I see that the update was done so it should not hang. Even though the update is done on both machines, sometimes one still hangs.
##### Steps To Reproduce:

I cannot reproduce it every time. Sometimes both machines pass. Sometimes one hangs.
I tested from new machines every time so that it is the first update of the system.

```
- name: update APT package cache
  sudo: yes
  apt: update_cache=yes

- name: upgrade all safe packages
  sudo: yes
  apt: upgrade=safe
```
##### Expected Results:

```
TASK: [rolebooks/update | upgrade all safe packages] **************************
changed: [10.0.0.202]
changed: [10.0.0.201]
```
##### Actual Results:

```
TASK: [rolebooks/update | upgrade all safe packages] **************************
changed: [10.0.0.202]
| # stuck here whereas the apt logs shows that it is done on this machine as well!
```

**Comment by mpdehaan** [comment]
Sometimes apt does weird things.  I'm not sure this is really ansible being stuck here or a package that is going interactive despite nine-billion flags we give so it is not.   

It would require some debugging to figure out what the problematic package was.

**Comment by YAmikep** [comment]
Would the logs show that the update is done if a package goes interactive?

**Comment by mpdehaan** [comment]
Hard to say what is going on the package but it would be worth taking a look.

We do pass a large number of flags to convince packages to stay in batch mode.

**Comment by ABAJosh** [comment]
I can confirm this issue is occurring for me as well. For me, it always hangs on one machine, which is running Ubuntu 14.04 (as are all my other machines). I'm running ansible 1.7.2. 

My playbook is:

```
 - name: update cache
   apt: "update_cache=yes"

 - name: upgrade packages
   apt: upgrade=yes
```

Interestingly, I went to the host and manually ran an apt-get upgrade, so everything is up to date. When I run it manually on the host it does not go interactive, and says there are no packages to upgrade.

edit: The issue also occurs when using "upgrade=safe"

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by iambibhas** [comment]
Just tested with 1.7.2 and 1.8.2 and it's still freezing. This is the task -

```
- name: update apt cache and upgrade
  apt: update_cache=yes upgrade=safe
```

**Comment by ABAJosh** [comment]
@iambibhas - I've suggest updating this issue: https://github.com/ansible/ansible-modules-core/issues/78 - Ansible changed their project structure a while back and that's the one that was looked at actively.
