### ISSUE TITLE
Constructed Inventory does not consider group_vars/all

### ISSUE THREAD

**Issue by sscheib** [ansible/ansible#82561]
### Summary

When adding group variables for all groups in e.g. `group_vars/all.yml`, they are not being considered by the `ansible.builtin.constructed`. Adding group vars to specific groups, e.g. `group_vars/my_group.yml` or to host vars, e.g. `host_vars/my.host.example.com.yml` works as expected.

### Issue Type

Bug Report

### Component Name

constructed

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.2]
  config file = /home/steffen/sources/__constructed_test/ansible.cfg
  configured module search path = ['/home/steffen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/steffen/venvs/ansible-latest/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/steffen/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/steffen/venvs/ansible-latest/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/home/steffen/venvs/ansible-latest/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
ansible-config dump --only-changed -t all
CACHE_PLUGIN(/home/steffen/sources/__constructed_test/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/steffen/sources/__constructed_test/ansible.cfg) = /tmp/fact_cache
CONFIG_FILE() = /home/steffen/sources/__constructed_test/ansible.cfg
DEFAULT_FORKS(/home/steffen/sources/__constructed_test/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/steffen/sources/__constructed_test/ansible.cfg) = ['/home/steffen/sources/__constructed_test/inventory']
DEFAULT_REMOTE_PORT(/home/steffen/sources/__constructed_test/ansible.cfg) = 1905
DEFAULT_REMOTE_USER(/home/steffen/sources/__constructed_test/ansible.cfg) = steffen
GALAXY_SERVER_LIST(/home/steffen/sources/__constructed_test/ansible.cfg) = ['automation-hub', 'galaxy']
INTERPRETER_PYTHON(/home/steffen/sources/__constructed_test/ansible.cfg) = auto_silent

CACHE:
=====

jsonfile:
________
_uri(/home/steffen/sources/__constructed_test/ansible.cfg) = /tmp/fact_cache

CONNECTION:
==========

paramiko_ssh:
____________
port(/home/steffen/sources/__constructed_test/ansible.cfg) = 1905
remote_user(/home/steffen/sources/__constructed_test/ansible.cfg) = steffen
ssh_args(/home/steffen/sources/__constructed_test/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

ssh:
___
port(/home/steffen/sources/__constructed_test/ansible.cfg) = 1905
remote_user(/home/steffen/sources/__constructed_test/ansible.cfg) = steffen
ssh_args(/home/steffen/sources/__constructed_test/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60
```

### OS / Environment

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.9 (Ootpa)
```

### Steps to Reproduce

1. Create `inventory.yml`:

```
----
my_group:
  hosts:
    host.example.com: {}
...
```
2. Create `group_vars/all.yml`:

```
---
version: '1.0'
...
```

3. Create group vars for group `my_group` in the file `group_vars/my_group.yml`:

```
---
my_version: 'custom version'
...
```

4. Create constructed inventory `zz_constructed.yml`:

```
---
plugin: ansible.builtin.constructed
use_vars_plugins: true
keyed_groups:
  - prefix: 'grp'
    key: 'version'

  - prefix: 'grp'
    key: 'my_version'
...
```

5. Run `ansible-inventory` to list out the inventory:

```
ansible-inventory --list -i inventory.yml -i zz_constructed.yml
```

### Expected Results

A group `grp_custom_version` should be created as well as a group `grp_1_0` with `host.example.com` being in both of them.

### Actual Results

```console
# Only the group grp_custom_version is created, although the variable from group_vars/all.yml is correctly shown in the output as variable for the host host.example.com ("version": "1.0"):

{
    "_meta": {
        "hostvars": {
            "host.example.com": {
                "my_version": "custom version",
                "version": "1.0"
            }
        }
    },
    "all": {
        "children": [
            "ungrouped",
            "my_group",
            "grp_custom_version"
        ]
    },
    "grp_custom_version": {
        "hosts": [
            "host.example.com"
        ]
    },
    "my_group": {
        "hosts": [
            "host.example.com"
        ]
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
The issue is that due to the way you've structured your inventory it isn't a member of `all` yet at the point the plugin runs. Inventory [reconciliation](https://github.com/ansible/ansible/blob/3f74bc08cefccec791c9dc5315185d2396e5c5ac/lib/ansible/inventory/data.py#L103) (which ensures that all hosts are members of `all`) runs once after all sources have been loaded: https://github.com/ansible/ansible/blob/3f74bc08cefccec791c9dc5315185d2396e5c5ac/lib/ansible/inventory/manager.py#L220-L233

It would be possible to change this so that reconciliation happens after each plugin, but that could have backwards-incompatible effects on the final group structure so I'm not sure that it's a good idea.

For now you can work around it by making sure that your groups are explicitly children of `all`:
```yaml
all:
  children:
    my_group:
      hosts:
        host.example.com: {}
```

There is also a problem with the specific value of `version` in your reproducer, which is a float.
```
[WARNING]:  * Failed to parse /home/ezekielh/testing/zz_constructed.yml with
auto plugin: failed to parse /home/ezekielh/testing/zz_constructed.yml: Invalid
group name format, expected a string or a list of them or dictionary, got:
<class 'float'> . Invalid group name format, expected a string or a list of
them or dictionary, got: <class 'float'>
```

You need to either quote the value in the variable file so that the YAML parser treats it as a string, or explicitly cast it to a string in the inventory config:
```yaml
plugin: ansible.builtin.constructed
use_vars_plugins: true
keyed_groups:
  - prefix: grp
    key: my_version | string

  - prefix: grp
    key: version | string
```

**Comment by jborean93** [comment]
Hi!

Thanks very much for your interest in Ansible.  It means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

* IRC: #ansible on [irc.libera.chat](https://libera.chat/)
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

* https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

Thanks @flowerysong for the detailed response, that pretty much hits the nail on the head. We currently don't want to change the behaviour to reconcile the `all` settings as it can be a costly process and the workaround in pre-defining the all group is a good enough way to do so today.

**Comment by sscheib** [comment]
Thanks for the detailed response to both of you!
I think it would be good to document that only group_vars from explicitly defined groups are loaded, not the ones from implicit groups (`all`, `ungrouped`), unless explicitly defined. Personally, I didn't find it obvious that only group_vars for explicit groups are loaded. Even when opening this issue, I thought it must be a bug, because all other groups worked.

I am happy to do a PR on `ansible.builtin.constructed` to briefly mention it in the `use_vars_plugins` - if desired.

What do you think?

**Comment by jborean93** [comment]
Sounds like a good idea to me.

**Comment by sscheib** [comment]
Thanks Jordan, I created a PR: #82580
