### ISSUE TITLE
Using synchronise module in local mode: paths are relative to base folder but not to actual role

### ISSUE THREAD

**Issue by kafecho** [ansible/ansible#8261]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Running Ansible on CentOS 6.5 64bits. I am running the playbook in local mode.
##### Summary:

This issue is similar to https://github.com/ansible/ansible/issues/5307 but it occurs when I run a playbook in local mode. The symptoms are the same, to paraphrase the issue above: "the relative path is relative to where you are executing the playbook from." 
##### Steps To Reproduce:

I have a playbook which installs Solr on the local host using a solr role which itself uses the synchronize module to copy the solr configuration files (which are within the files folder of the role). 
The playbook uses a local mode.

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
   http_port: 8183
  roles:
  - solr
```

If I run a non local version of the playbook, it all works fine.
##### Expected Results:

I would expect the synchronize module to copy the files correctly.
##### Actual Results:

The rsync command fails to resolve the paths to the solr config file relative to the role. Instead the paths are resolved relative to where the ansible-playbook command is ran from (root/qstack-ansible-playbooks)

```
failed: [127.0.0.1] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' solr /opt/jetty", "failed": true, "item": "", "rc": 23}
msg: rsync: link_stat "/root/qstack-ansible-playbooks/solr" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
```

**Comment by mpdehaan** [comment]
This will need retesting on 1.6.8 as well as I'll need to see the synchronize line from your solr/tasks/main.yml

Can you please check on 1.6.8 and also include this line?

**Comment by kafecho** [comment]
Hi, the line is:
    - name: Copy the solr directory to /opt/jetty
      synchronize: src=solr dest=/opt/jetty rsync_path="sudo rsync"
      tags: solr-conf

I will try with version 1.6.8 and let you know.

**Comment by kafecho** [comment]
I've just tried with Ansible version 1.6.9 installed via pip on CentOS 6.5.
I get a similar error message:

```
failed: [127.0.0.1] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' solr /opt/jetty", "failed": true, "rc": 23}
msg: rsync: link_stat "/root/qstack-ansible-playbooks/solr" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
```

**Comment by awheeler** [comment]
I am having this issue as well.  I've worked around it for now by creating a pull_mode group when in pull mode that I can check for and then prefix the src path.
Is there a cleaner way to detect that I am in pull mode vs push?

**Comment by coliban** [comment]
I have the same problem.

Since this bug is now nearly a year old, does someone know, if there is a workaround (which no too complicated and tedious tampering) ?

(ansible-playbook 1.9) 

I saw that this is propably a "feature", it seems that ansible-playbook is not able to get the source from an absolute path. I wonder, if this makes sense, i can´t use this feature

**Comment by coliban** [comment]
It seems, as if ansible not able to handle absolute path, so i have created a workaround with the command "rsync" which is executed localy on the server:

```
- name: rsyn
  local_action: command rsync -auvL {{ rsync_source }}   tester@client001:{{ rsync_dest }}
  ignore_errors: True
```

**Comment by xrow** [comment]
I believe, I have hit the same problem in version 1.9.1.

**Comment by conrado** [comment]
same here for 1.9.1

**Comment by abadger** [comment]
A bunch of refactoring and i think this now works.  tested with @kafecho's playbook and a simplified solr role (just rsync's a directory with a single file in it).

Before https://github.com/ansible/ansible/commit/e7b5cb87828a49cfc8771ab3d83fda157d42972f the test case failed and after I committed that it works.  So this looks fixed in devel.

Note that the case where non-local connections were used  (which might be what would be done here: https://github.com/ansible/ansible/issues/8261#issuecomment-77359205 ) should already have worked (fixed in: https://github.com/ansible/ansible/issues/5307 ).  If things are still problematic, please open a new bug report with a new test case for us to take a look at.  Thanks and sorry it took so long to resolve this one.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
