### ISSUE TITLE
No module named fcnt1 on AIX

### ISSUE THREAD

**Issue by cmlsharp** [ansible/ansible#8266]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 75e5b6401c) last updated 2014/07/22 14:37:30 (GMT -400)
##### Environment:

Running from RHEL 6
Managing AIX
##### Summary:

Can't connect to AIX box: more details in next section
##### Steps To Reproduce:

Compile python 2.6.8 on AIX.
Run
    ansible -m ping aixservername
##### Expected Results:

The ping would not fail
##### Actual Results:

The ping command returns:  

```
aixservername   | FAILED >> {
"failed": true,
"msg": "Traceback (most recent call last):\n  File \"/home/chad/.ansible/tmp/ansible-   tmp-1406142576.36-87138506530381/ping\", line 102, in <module>\n    import   subprocess\n  File \"/opt/freeware/lib/python2.6/subprocess.py\", line 416, in <module>\n    import fcntl\nImportError: No module named fcntl\n",
"parsed": false
}
```

Any idea what causes this?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by knh1** [comment]
If you are using the AIX python RPM from perzl.org, then you will need to switch the symbolic links in /usr/bin to point at the 64-bit binaries in /opt/freeware/bin.

```
# Change to /usr/bin directory
cd /usr/bin

# Create links to 32-bit python
ls -l python* | grep -v _64 | awk '{print $(NF-2)" "$NF}' | while read LINK TARGET ; do LINK=$(echo $LINK | /opt/freeware/bin/sed 's/python\(2.6\)*/\0_32/') ; echo "$LINK --> $TARGET" ; sudo ln -s $TARGET $LINK ; echo ; done

# Replace default 32-bit links with 64-bit targets
ls -l python* | grep _64 | awk '{print $(NF-2)" "$NF}' | while read LINK TARGET ; do LINK=$(echo $LINK | sed 's/_64//') ; echo "$LINK --> $TARGET" ; sudo ln -fs $TARGET $LINK; echo ; done
```

**Comment by udesilva** [comment]
Perfect! I just changed the /usr/bin/python link to point to python2.6_64 in the same directory, though, and it was sufficient to get Ansible working correctly.

**Comment by tolimar** [comment]
I'm new to ansible, but setting the host configuration to `ansible_python_interpreter=/opt/freeware/bin/python_64` works for my first tests.
