### ISSUE TITLE
Add all AWS EC2 Tags as facts for ec2_facts module

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#8267]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

1.6.6
##### Environment:

n/a
##### Summary:

I would like to modify ec2_facts so that it also returns all tags as facts

I'd suggest:

```
"ansible_ec2_tags": {
    "key": "value",
    "key2": "value2"
    ...
}
```
##### Steps To Reproduce:

n/a 
##### Expected Results:

n/a
##### Actual Results:

n/a

**Comment by mpdehaan** [comment]
We do return each tag as group info so I would be open to this if someone would like to make the code addition.

The workaround for now is to just select groups like so:
- hosts: ec2_tag_foo

# all hosts tagged foo

and 
- hosts: ec2_tag_foo_value

# all things with value foo

This is not to say even a workaround really, but the way this is available.

Such as this you can also do conditionals like:
- when: foo in groups['ec2_tag_bar'] and inventory_hostname in groups['ec2_tag_baz']

instead of (cleaner):
- hosts: ec2_tag_foo:&ec2_tag_baz

Given queue length and the above feature we are unlikely to work on this one, but pull requests would be great.  

Thanks!
