### ISSUE TITLE
cron module failure has traceback versus error message (edited)

### ISSUE THREAD

**Issue by fninja** [ansible/ansible#8277]
##### Issue Type:

What kind of ticket is this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version:

ansible 1.6.7
##### Environment:

Ubuntu 14.04
##### Summary:

The module "cron" is failing to manage the crontab on my CentOS5.6 hosts, while it works well with my CentOS6.5 hosts.
##### Steps To Reproduce:

```
fninja~/ ansible -i hosts.staging.ini -m cron -a "name='Ansible TestJob' hour='1' job='ls -alh > /dev/null'" testhostcentos5
testhostcentos5 | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\r\n  File \"/home/fninja/.ansible/tmp/ansible-tmp-1406200677.2-173966596948178/cron\", line 1738, in ?\r\n    main()\r\n  File \"/home/fninja/.ansible/tmp/ansible-tmp-1406200677.2-173966596948178/cron\", line 436, in main\r\n    crontab = CronTab(module, user, cron_file)\r\n  File \"/home/fninja/.ansible/tmp/ansible-tmp-1406200677.2-173966596948178/cron\", line 176, in __init__\r\n    self.read()\r\n  File \"/home/fninja/.ansible/tmp/ansible-tmp-1406200677.2-173966596948178/cron\", line 197, in read\r\n    raise CronTabError(\"Unable to read crontab\")\r\n__main__.CronTabError: Unable to read crontab\r\n",
    "parsed": false
}
```
##### Expected Results:

success in green color
##### Actual Results:

"failed": true

**Comment by mpdehaan** [comment]
We definitely need to catch this error and return a non-traceback as that's not an interface we like to present at all, though it may be that your crontab is actually unreadable.   Will look.

**Comment by davidvasandani** [comment]
Similar issue. This task:

```
- name: Keep hegemon and helios up to date
  cron:
    name="Keep {{ item }} up to date"
    minute="*/15"
    job="/usr/bin/flock -n /tmp/git_{{ item }}.lock cd /opt/wp/app/hegemon && git pull --rebase"
  with_items:
    - hegemon
    - helios
  when: ansible_nodename == "m-bamboo01" or ansible_nodename == "m-warp01"
```

Successfully adds the hegemon task but fails on the helios task.

```
ok: [m-bamboo01] => (item=hegemon)
ok: [m-warp01] => (item=hegemon)
ok: [m-bamboo01] => (item=helios)
failed: [localhost] => (item=hegemon) => {"failed": true, "item": "hegemon", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1410360454.69-137934164949874/cron", line 1736, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1410360454.69-137934164949874/cron", line 436, in main
    crontab = CronTab(module, user, cron_file)
  File "/root/.ansible/tmp/ansible-tmp-1410360454.69-137934164949874/cron", line 176, in __init__
    self.read()
  File "/root/.ansible/tmp/ansible-tmp-1410360454.69-137934164949874/cron", line 197, in read
    raise CronTabError("Unable to read crontab")
__main__.CronTabError: Unable to read crontab

ok: [m-warp01] => (item=helios)
failed: [localhost] => (item=helios) => {"failed": true, "item": "helios", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1410360455.1-238209494136025/cron", line 1736, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1410360455.1-238209494136025/cron", line 436, in main
    crontab = CronTab(module, user, cron_file)
  File "/root/.ansible/tmp/ansible-tmp-1410360455.1-238209494136025/cron", line 176, in __init__
    self.read()
  File "/root/.ansible/tmp/ansible-tmp-1410360455.1-238209494136025/cron", line 197, in read
    raise CronTabError("Unable to read crontab")
__main__.CronTabError: Unable to read crontab
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
