### ISSUE TITLE
Implement case insensitive match in "--limit" option of ansible-playbook command

### ISSUE THREAD

**Issue by GiorgioBullo** [ansible/ansible#82802]
### Summary

DNS records are case insensitive, however the `--limit` option of the ansible-playbook command seems not to be. For instance, if my inventory.ini contains the following hosts:
```
HOST1
HOST2
HOST3
```

and I run `ansible-playbook -i inventory.ini` -l "host2" whatever-playbook.yml`, the command will fail saying that it was left without valid hosts. Is it possible to make it case insensitive?

### Issue Type

Feature Idea

### Component Name

ansible-playbook

### Additional Information

I have a huge dynamic inventory file and we often limit the execution of a playbook to a smaller portion of hosts. Most of the time users of my platform provide the list of host where to run. Sometimes hosts are upper case and sometimes lower case because users don't know the `ansible-playbook --limit` is case sensitive. So we need to convert the case and the run the ansible-playbook.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bcoca** [comment]
The `--limit` affects both `inventory_hostname` and `group` names, neither of these are required to match a DNS name, in many cases of the former they do, but this is up to the user.  Since both names are case sensitive in Ansible, we should not restrict the option to be case insensitive. Al so, you can already handle that specific case as @s-hertel explains above.
