### ISSUE TITLE
Invalid Configuration Requests with ec2_elb_lb and purge_subnets

### ISSUE THREAD

**Issue by elasticdog** [ansible/ansible#8312]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel fb60e767a7) last updated 2014/07/28 09:35:24 (GMT -600)
##### Environment:

N/A
##### Summary:

When using the _ec2_elb_lb_ module in conjunction with its `purge_subnets = true` parameter, actually updating your subnets will fail under a number of circumstances. The problem is that the module does not detach the existing subnets before attaching the new ones. If you try and attach a subnet for an Availability Zone that already has a subnet attached, you will get this error from boto:

``` xml
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidConfigurationRequest</Code>
    <Message>ELB cannot be attached to multiple subnets in the same AZ.</Message>
  </Error>
  <RequestId>f5875fe1-1272-11f4-a213-a1b5c6b355a1</RequestId>
</ErrorResponse>
```

The tricky bit here is that you also cannot simultaneously detach _all_ subnets from an ELB, so just switching the ordering in the module ([here](https://github.com/ansible/ansible/blob/226dacc7e6d9910060e17d87e25759ff01bddc73/library/cloud/ec2_elb_lb#L478-L481)) is not enough. If you do change that ordering and then try and swap out all of your attached subnets, you'll get this error from boto:

``` xml
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidConfigurationRequest</Code>
    <Message>Requested configuration change for LoadBalancer &quot;example-load-balancer&quot; is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.</Message>
  </Error>
  <RequestId>7327b69f-1473-11f5-ac48-3d737b1864a9</RequestId>
</ErrorResponse>
```

So a smarter method of swapping out the subnets is required. If you're managing multiple subnets, you could shuffle around the order of attach/detaches, but if you're only managing a single subnet, I'm not sure what the best solution would be (or if there is a solution).
##### Steps To Reproduce:

Lets say you have an existing ELB named "example-load-balancer" and you want to update its subnet according to:

| Status | Subnet ID | Availability Zone |
| --- | --- | --- |
| Existing | subnet-abcd1234 | us-east-1a |
| Desired | subnet-1a2b3c4d | us-east-1a |

Here's your task:

``` yaml
- local_action:
    module: ec2_elb_lb
    state: present
    name: example-load-balancer
    region: us-east-1
    subnets:
      - subnet-1a2b3c4d
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    purge_subnets: true
```
##### Expected Results:

```
TASK: [aws | ec2_elb_lb] ******************************************************
changed: [localhost -> 127.0.0.1] => {"ansible_facts": {"ec2_elb": "info"}, "changed": true, "elb": {"dns_name": "example-load-balancer-570321845.us-east-1. elb.amazonaws.com", "listeners": [[80, 80, "HTTP", "HTTP"]], "name": "exaple-load-balancer", "status": "ok", "subnets": ["subnet-1a2b3c4d"], "zones": ["us-east-1a"]}}
```
##### Actual Results:

``` xml
TASK: [aws | ec2_elb_lb] ****************************************************** 
failed: [localhost -> 127.0.0.1] => (item=subnet-1a2b3c4d) => {"failed": true, "item": "subnet-1a2b3c4d, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/elasticdog/.ansible/tmp/ansible-tmp-1406564373.52-277382391891465/ec2_elb_lb", line 2103, in <module>
    main()
  File "/home/elasticdog/.ansible/tmp/ansible-tmp-1406564373.52-277382391891465/ec2_elb_lb", line 596, in main
    elb_man.ensure_ok()
  File "/home/elasticdog/.ansible/tmp/ansible-tmp-1406564373.52-277382391891465/ec2_elb_lb", line 261, in ensure_ok
    self._set_subnets()
  File "/home/elasticdog/.ansible/tmp/ansible-tmp-1406564373.52-277382391891465/ec2_elb_lb", line 479, in _set_subnets
    self._attach_subnets(subnets_to_attach)
  File "/home/elasticdog/.ansible/tmp/ansible-tmp-1406564373.52-277382391891465/ec2_elb_lb", line 461, in _attach_subnets
    self.elb_conn.attach_lb_to_subnets(self.name, subnets)
  File "/home/elasticdog/.virtualenvs/ansible/lib/python2.7/site-packages/boto/ec2/elb/__init__.py", line 711, in attach_lb_to_subnets
    params, None)
  File "/home/elasticdog/.virtualenvs/ansible/lib/python2.7/site-packages/boto/connection.py", line 1158, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 409 Conflict
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidConfigurationRequest</Code>
    <Message>ELB cannot be attached to multiple subnets in the same AZ.</Message>
  </Error>
  <RequestId>f5875fe1-1272-11f4-a213-a1b5c6b355a1</RequestId>
</ErrorResponse>
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by radykal-com** [comment]
@elasticdog hello, I'm facing this same error. Did you find a solution?

**Comment by elasticdog** [comment]
@radykal-com unfortunately, we never did, and I have since moved on from that company and the environment. When I needed to make the ELB updates, I just tweaked things manually as changes were not very frequent.

**Comment by radykal-com** [comment]
Thanks you @elasticdog
