### ISSUE TITLE
error when trying to use with_items with apt module

### ISSUE THREAD

**Issue by gergelyimre** [ansible/ansible#8314]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 226dacc7e6) last updated 2014/07/28 21:56:28 (GMT +300)
##### Environment:

  managing host: Ubuntu 14.04 64bit
  managed host: Ubuntu 10.04 32bit (python 2.6.5 + python-apt 0.7.94)
##### Summary:

Getting an error message while using with_items with the apt module.
##### Steps To Reproduce:

According to feature request #7863 and fix #8292, with_items should be used like this:

```
    - name: install debs
      apt: deb=/tmp/{{ item }} state=installed
      with_items:
        - linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb
        - linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb
        - linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb
```
##### Expected Results:

deb packages getting installed
##### Actual Results:

error message:

```
TASK: [install debs] ********************************************************** 
failed: [host1] => (item=linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb,linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb,linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb) => {"failed": true, "item": "linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb,linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb,linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb", "parsed": false}
invalid output was: SUDO-SUCCESS-mwctpznrbdkgnukozzhwfjskdskanudn
Traceback (most recent call last):
  File "<stdin>", line 1865, in <module>
  File "<stdin>", line 523, in main
  File "<stdin>", line 302, in install_deb
  File "/usr/lib/python2.6/dist-packages/apt/debfile.py", line 285, in compare_to_version_in_cache
    if pkgname in self._cache:
TypeError: argument of type 'NoneType' is not iterable


FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Hi,

The underlying magic here is because when ansible sees a with_items on a apt or yum command it tries to install them all in one transaction.  The commands in question aren't quite as smart for when local files are being used.

The solution would be seperate tasks in the interim, since ansible will try to join them.  We could then perhaps tweak the module such that it works in a loop for when it can't specify them all on the same commandline.

**Comment by egli** [comment]
I have the same issue but I get a slightly different error (using Ansible version v1.6.0-1353-g9edf3a7):

``` shell
TASK: [install debs] ********************************************************** 
fatal: [xmlp-test] => failed to parse: 
SUDO-SUCCESS-vezxbadxecppwcnzcahcazlrvcajnbze
Traceback (most recent call last):
  File "/home/eglic/.ansible/tmp/ansible-tmp-1408095944.08-178150558729123/apt", line 1906, in <module>
    main()
  File "/home/eglic/.ansible/tmp/ansible-tmp-1408095944.08-178150558729123/apt", line 523, in main
    force=force_yes, dpkg_options=p['dpkg_options'])
  File "/home/eglic/.ansible/tmp/ansible-tmp-1408095944.08-178150558729123/apt", line 299, in install_deb
    pkg = apt.debfile.DebPackage(deb_file)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 57, in __init__
    self.open(filename)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 66, in open
    self._debfile = apt_inst.DebFile(self.filename)
SystemError: E:Could not open file tcolorbox_2.51-5_all.deb - open (2: No such file or directory), E:Unable to determine the file size - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)


FATAL: all hosts have already failed -- aborting
```

I created a minimal example to reproduce the problem. See https://github.com/sbsdev/ansible-apt-test

**Comment by srgvg** [comment]
Another workaround is to 

   `ln -s`/usr/share/ansible/packaging/apt library/apt_items`

and reference the "apt_items" module. That way the special magic won't trigger.

**Comment by davidreuss** [comment]
I'd say this is magic gone too far, and even so when the error message is anything but helpfule. This caught me by surprise, and logic really didn't explain why this was an error at all, given how one would think "with_items" is implemented (purely templating parameters).

I'd much prefer a option to the module somehow to enable this "magic".

I fully understand why the optimization is there in the first place, but i'd rather opt-in to magic, than it being default.

**Comment by fti7** [comment]
Im with @davidreuss 
Also this Feature wont allow so see the exact changes (Package Installs) were made.
There should be an parameter to disable/enable the "Intelligent Loop" Feature

**Comment by srgvg** [comment]
This is something that probably will be adressed with a refactoring of the runner code, AFAIK.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by senorsmile** [comment]
Until this is actually fixed, an easy work around is here: http://stackoverflow.com/a/19127494/1099103
