### ISSUE TITLE
playbook_dir variable returning relative path

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8317]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

OS X 10.9.4
##### Summary:

The playbook_dir variable always returns a relative path to the working directory from where I ran the playbook
##### Steps To Reproduce:

Run a simple playbook:

``` yaml

---
- hosts: all
  connection: local
  tasks:
      - debug: msg="{{playbook_dir}}"
```
##### Expected Results:

```
ok: [localhost] => {
    "msg": "/abs/path/to/playbook_dir"
}
```
##### Actual Results:

```
ok: [localhost] => {
    "msg": "."
}
```

**Comment by mpdehaan** [comment]
All path variables in the app should absolutely be absolute.   Please ignore the above comment (now removed).

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
