### ISSUE TITLE
hostname module failing in Scientific Linux 6.5

### ISSUE THREAD

**Issue by earlruby** [ansible/ansible#8339]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel b64a5ff73d) last updated 2014/07/29 09:49:48 (GMT -700)
##### Environment:

Running from: OS/X 10.9.4
Managing: Scientific Linux 6.5
##### Summary:

A recent update to the hostname module is causing it to fail for Scientific Linux 6.5 with the error:

msg: Command failed rc=127, out=, err=/bin/sh: hostnamectl: command not found

Scientific Linux 6.5 does not use hostnamectl to set the hostname.
##### Steps To Reproduce:

I used this command to set the host name on Scientific Linux 6.5. It was working until recently.
- name: Set the host name
  hostname: name={{ fqdn }}
##### Expected Results:

I expect the host name to be set on a Scientific Linux 6.5 host.
##### Actual Results:

The error:

msg: Command failed rc=127, out=, err=/bin/sh: hostnamectl: command not found

**Comment by dirtyharrycallahan** [comment]
What version of ansible?

**Comment by earlruby** [comment]
ansible 1.7 (devel b64a5ff) last updated 2014/07/29 09:49:48 (GMT -700)

**Comment by mscherer** [comment]
Can this bug be closed, since it seems fixed ?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
