### ISSUE TITLE
ec2_eip.reuse_existing_ip_allowed did not reuse ip

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible#8344]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.7
##### Environment:

OSX
##### Summary:

ec2_eip.reuse_existing_ip_allowed flag is broken
##### Steps To Reproduce:

Alexeys-MacBook-Pro:ansible alw$ aws ec2 describe-addresses
{
"Addresses": [
{
"InstanceId": "i-1c84dd30",
"PublicIp": "23.23.145.172",
"Domain": "standard"
},
{
"InstanceId": "i-3a1ef46a",
"PublicIp": "54.197.232.96",
"Domain": "standard"
},
{
"InstanceId": "i-381ef468",
"PublicIp": "54.197.232.99",
"Domain": "standard"
},
{
"InstanceId": null,
"PublicIp": "54.227.249.218",
"Domain": "standard"
},
{
"InstanceId": null,
"PublicIp": "54.235.247.229",
"Domain": "standard"
},
{
"InstanceId": "i-cfce2fe5",
"PublicIp": "54.243.47.47",
"Domain": "standard"
}
]
}

Alexeys-MacBook-Pro:ansible alw$ cat test.yml

hosts: 127.0.0.1
connection: local
tasks:

local_action:
module: ec2_eip
reuse_existing_ip_allowed: yes
region: "{{ region }}"
register: eip

debug: var=eip
Alexeys-MacBook-Pro:ansible alw$ ansible-playbook test.yml

PLAY [127.0.0.1] **************************************************************

TASK: [ec2_eip] ***************************************************************
changed: [127.0.0.1]

TASK: [debug var=eip] *********************************************************
ok: [127.0.0.1] => {
"eip": {
"changed": true,
"invocation": {
"module_args": "",
"module_name": "ec2_eip"
},
"public_ip": "54.83.8.39"
}
}

PLAY RECAP ********************************************************************
127.0.0.1 : ok=2 changed=1 unreachable=0 failed=0
##### Expected Results:

One of existing free elastic ip should be used.
##### Actual Results:

New address allocated.

**Comment by awasilyev** [comment]
https://github.com/ansible/ansible/pull/8518

**Comment by mpdehaan** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
