### ISSUE TITLE
OpenBSD and ansible_interface.ipv4.address 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8356]
##### Ansible Version:

  ansible 1.6.6 linux (centos 6.5) 
  ansible 1.6.10 OpenBSD 5.5 (on OpenBSD tested also on ansible 1.6.6. Used newer ansible release to show it still happens)
##### Environment:
- ansible is run local to the server in each instances
- host: Centos 6.5 and OpenBSD 5.5
##### Summary:

  An OpenBSD system not able to assign retrieved fact for ansible_interface.ipv4.address to variable.
#### create play (Centos 6.5)

```

---
# test.yml

- hosts: localhost
  connection: local
  remote_user: gregm
#  sudo: yes

  tasks:
  # name: address (frrebsd and openbsd replace with em0 ans nic)
  - debug: msg={{ ansible_eth0.ipv4.address }}
  - debug: msg={{ ansible_default_ipv4.address }}

# EOF
```
#### create paly (OpenBSD 5.5)

```

---
# test.yml

- hosts: localhost
  connection: local
  remote_user: gregm
#  sudo: yes

  tasks:
    # name: address
    - debug: msg={{ ansible_alc0.ipv4.address }}
    - debug: msg={{ ansible_default_ipv4.address }}
```
##### Expected Results:
- I would expect the same results on OpenBSD as the one on Centos 6.5. I tested it also with ansible 1.6.6 on OpenBSD and the same happened.
#### for reference, I include collected facts from the Centos 6.5 host:

```
    "ansible_eth0": {
        "active": true,
        "device": "eth0",
        "ipv4": {
            "address": "192.168.0.44",
            "netmask": "255.255.255.0",
            "network": "192.168.0.0"
        },
        "ipv6": [
            {
                "address": "fe80::20c:29ff:fefd:f56c",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "00:0c:29:fd:f5:6c",
        "module": "e1000",
        "mtu": 1500,
        "promisc": false,
        "type": "ether"
```
#### Centos 6.5 results:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg={{ansible_eth0.ipv4.address}}] *******************************
ok: [localhost] => {
    "msg": "192.168.0.44"
}

TASK: [debug msg={{ansible_default_ipv4.address}}] ****************************
ok: [localhost] => {
    "msg": "192.168.0.44"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
#### For referance, I included fact collected from the OpenBSD 5.5 host

```
localhost | success >> {
    "ansible_facts": {
        "ansible_alc0": {
            "device": "alc0",
            "flags": [
                "UP",
                "BROADCAST",
                "RUNNING",
                "SIMPLEX",
                "MULTICAST"
            ],
            "ipv4": [
                {
                    "address": "192.168.16.95",
                    "broadcast": "192.168.16.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.16.0"
                }
            ],
            "ipv6": [
                {
                    "address": "fe80::224:1dff:fe56:e3f4%alc0",
                    "prefix": "64",
                    "scope": "0x1"
                }
            ],
```
#### OpenBSD 5.5 results

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg={{ ansible_alc0.ipv4.address }}] *****************************
fatal: [localhost] => One or more undefined variables: 'list object' has no attribute 'address'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/gregm/test.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by mscherer** [comment]
Likely duplicate with #4578 , there is not much we can do I think. It is either breaking compatibility with older templates and playbook on Linux, or doing complicated change on solaris/openbsd.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
