### ISSUE TITLE
Paramiko connection cache is being wiped at the end of each task

### ISSUE THREAD

**Issue by mkollaro** [ansible/ansible#8359]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.7 (devel d51e10a3f4) last updated 2014/07/28 15:15:04 (GMT +200)
```
##### Environment:

   Linux Mint 16
   python-paramiko 1.10.1-1
##### Summary:

The Paramiko plugin is [supposed to use a cache](https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/paramiko_ssh.py#L109) for the SSH connections, but the Runner [closes the connection](https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L910) and therefore removes it from the cache at the end of each task, causing it to re-authenticate each time. Shouldn't the connections be closed only at the end of the playbook?
##### Steps To Reproduce:

Create a [playlist that runs any command a few times](https://gist.github.com/mkollaro/0ced9bf74171ae97c9ad#file-test-yml) and either use [strace](https://gist.github.com/mkollaro/0ced9bf74171ae97c9ad#file-strace-output) or `-vvv` to see there is a new connection request at each task. When I remove the [line that closes the connection](https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L910), the connect request [happens only once](https://gist.github.com/mkollaro/0ced9bf74171ae97c9ad#file-strace-output-without-conn-close). You can also try printing the contents of the `SSH_CONNECTION_CACHE` variable - it will be empty in the beginning of each task.
##### Expected Results:

Reuse the connection in the cache.
##### Actual Results:

New connection is created at each task.

The re-connection causes quite a slowdown for me - when I run a [simple playbook](https://gist.github.com/mkollaro/0ced9bf74171ae97c9ad#file-test-yml) with 10x the command 'uptime' on a single host, it takes ~35 seconds. When I comment out the [line where the connection is closed](https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L910), it takes approximately 22 seconds. (I'm also wondering why is it still so slow, a small script with Paramiko doing the same takes 6 seconds...)

**Comment by mpdehaan** [comment]
Sort of no, not really.  The cache was never really used.  That line is a vestige of trying to solve exactly this but it was never done.

This has never really been an operational thing but is problematic because of the way the multiprocessing module works.

The solution is to use -c ssh and ControlPersist, which particularly when used with the pipelining feature, completely rocks.

Or use accelerated mode.

As RHEL7 is now featuring a new enough SSH there isn't a lot of demand for updating the way this works, and would be extremely hard to do with the mulitprocessing architecture, but the accelerated mode features really unlock the performance if you need it with paramiko, so I'd suggest trying it out.

If you need further help please stop by IRC or the mailing list and we'd be glad to help.
