### ISSUE TITLE
would like better error message when disk is full

### ISSUE THREAD

**Issue by joaogbcravo** [ansible/ansible#8362]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

From: Centos 5/6
To: Centos 5/6
##### Summary:

When ansible tries to run a command in a machine with a full disk it returns a misleading message.
##### Steps To Reproduce:

Full a disk of target machine (using DD or any other way).  Run ansible to do something on the target machine. You will get the message.
##### Expected Results:

The error message should be something like this
mkdir: cannot create directory `$HOME/.ansible/tmp/ansible-tmp-1406727561.92-124710193092100': No space left on device
##### Actual Results:

Message:
"Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory".

Full stack trace:
13:39:20 TASK: [generic | checking for the existence of the service FOO] ***\* 
13:39:22 fatal: [host] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1406727561.92-124710193092100 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1406727561.92-124710193092100 && echo $HOME/.ansible/tmp/ansible-tmp-1406727561.92-124710193092100, exited with result 1
13:39:22

**Comment by mpdehaan** [comment]
We're not aware that's the actual result in this case right now, but we can check to see if that comes back in the string I'm guessing.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit in #8458 should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
