### ISSUE TITLE
locale_gen does not generate locales on Arch Linux

### ISSUE THREAD

**Issue by tummychow** [ansible/ansible#8387]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.10
##### Environment:

Arch Linux (both master and slave)
##### Summary:

locale_gen doesn't generate locales on Arch Linux.

The [locale_gen](https://github.com/ansible/ansible/blob/devel/library/system/locale_gen#L66) module looks for lines starting with a hash and a space, and removes the hash to enable locale generation for those lines. But Arch's locale.gen doesn't have spaces (only the hash) so no lines get uncommented. Since no locales are enabled, locale-gen does nothing.
##### Steps To Reproduce:

Create a fresh Arch Linux system and install openssh/python2 on it. Add it to your Ansible hosts.

```
$ ansible -m locale_gen -a "name=en_US.UTF-8 state=present" --extra-vars "ansible_python_interpreter=/usr/bin/python2" <your Arch Linux target here>
$ ssh <your arch linux target here> locale -a
```
##### Expected Results:

The Ansible ad-hoc command should succeed and indicate "changed"
The ssh command `locale -a` should list all the locales on the system. `en_US.UTF-8` should be on the list.
##### Actual Results:

The Ansible command does succeed, but C and POSIX are the only locales listed aftewards. `en_US.UTF-8` does not appear.

**Comment by ghost** [comment]
can you post a snippet of ArchLinux's locale.gen for comparison? I'm guessing a regex that looks for the hash and an optional space should be used. The `replace_line` is using String.replace and that would have to be replaced.

**Comment by tummychow** [comment]
Sure:

```
#en_IE@euro ISO-8859-15  
#en_IN UTF-8  
#en_NG UTF-8  
#en_NZ.UTF-8 UTF-8  
#en_NZ ISO-8859-1  
#en_PH.UTF-8 UTF-8  
#en_PH ISO-8859-1  
#en_SG.UTF-8 UTF-8  
#en_SG ISO-8859-1  
en_US.UTF-8 UTF-8  
#en_US ISO-8859-1  
#en_ZA.UTF-8 UTF-8  
#en_ZA ISO-8859-1  
#en_ZM UTF-8  
#en_ZW.UTF-8 UTF-8  
#en_ZW ISO-8859-1  
#es_AR.UTF-8 UTF-8  
```

As you noted, the fix for the issue would be to make the spaces optional.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
