### ISSUE TITLE
Shell task ignores "creates" option (?) when used in multi-line format

### ISSUE THREAD

**Issue by fesplugas** [ansible/ansible#8390]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.10 (also affects 1.6.9)
##### Environment:

OSX
##### Summary:

Shell command will always run although `creates` option is used.
##### Steps To Reproduce:

This is one of the tasks which is failing for us.

```
- name: install homebrew
  shell: >
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    creates=/usr/local/bin/brew
```
##### Expected Results:

Task should be skipped.
##### Actual Results:

Task is run ignoring the "creates" option.

**Comment by mpdehaan** [comment]
We have tests to verify the creates= option works correctly.   However, this may just be because you are using the newline there, and the parser is slightly confused.  We can add an additional test for this to be sure.

Meanwhile, try this on a single line:

 shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" creates=/usr/local/bin/brew

I should also caution you about running random content through bash as an install habit, it's rather insecure should that upstream repo get compromised.  At least it's https:// but it's still scary as all :)

**Comment by fesplugas** [comment]
Using a single line fixes this on `Ansible 1.6.10`. Thanks.

**Comment by fesplugas** [comment]
Removing `>` also fixes the error:

```
- name: install homebrew
  shell:
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    creates=/usr/local/Cellar
```

The error also happened when creating a file from a template:

```
- template: >
    src="Brewfile"
    dest="/usr/local/Brewfile"
```

And again, removing `>` fixed the error.

The interesting part is the we use `>` in a lot of our playbooks/roles an we only have the problem when running the playbooks when connection is set to local on OSX.

**Comment by fesplugas** [comment]
Removing quotes makes it work ...

```
- template: >
    src=Brewfile
    dest=/usr/local/Brewfile
```

O_o

**Comment by jimi-c** [comment]
I believe this has also been corrected on devel as well, as of last Thursday, if you can try that version?

**Comment by fesplugas** [comment]
Tried with `devel` branch and seems to work. Thanks.

**Comment by jimi-c** [comment]
Excellent, closing this now. Thanks!
