### ISSUE TITLE
Internal error with regex_replace

### ISSUE THREAD

**Issue by hehachris** [ansible/ansible#8391]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

RHEL/CentOS 6.5
##### Summary:

`item.cidr` comes from a list of hashes, while the values can be 10.1.0.0/24, 10.99.0.0/24, etc (2nd bit is different in each subnet). What I want to do is to get the first IP address from the cidr subnet. eg. 10.1.0.0/24 => 10.1.0.1, 10.99.0.0/24 => 10.99.0.1
##### Steps To Reproduce:

Regexp:

```
private_ip    : "{{ item.cidr | regex_replace('^[0-9]+\\.([0-9]+)\\.0\\.0/24$', '10.\\1.0.1') }}"
```
##### Expected Results:

No error
##### Actual Results:

error:

```
msg: Instance creation failed => InternalError: An internal error has occurred
```

**Comment by mpdehaan** [comment]
Instance creation failed seems like it's coming from an EC2 module or boto.

Can you please supply the full output as well as the task line from your playbook?

**Comment by hehachris** [comment]
Thanks for your reply. Here is the task in the playbook:

```
- name      : Lanuch NAT instance in the public subnet
  register  : ec2

  with_items: vpc.subnets
  when      : item.cidr | match("[0-9]+\.[0-9]+\.0\.0/24") # matches x.x.0.0

  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

    wait          : yes
    exact_count   : 1
    region        : "{{ vpc_region }}"
    key_name      : "{{ aws_key_name }}"
    instance_type : "{{ nat_instance_type }}"
    image         : "{{ nat_image }}"

    source_dest_check: no

    vpc_subnet_id : "{{ item.id }}"
    #private_ip    : "{{ item.cidr | regex_replace('^10\\.([0-9]+)\\.0\\.0/24', '10.\\1.0.254/24') }}"
    private_ip    : "{{ nat_ip1 }}"

    instance_tags:
      Name  : NAT 1
      class : NAT 1

    count_tag:
      class : NAT 1
```

Error output:

```
TASK: [vpc | Lanuch NAT instance in the public subnet] ****************** 
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-xxxxxxxxr-B'}, u'cidr': u'10.1.6.0/24', u'az': u'ap-northeast-1b', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-public-C'}, u'cidr': u'10.1.1.0/24', u'az': u'ap-northeast-1c', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-web-C'}, u'cidr': u'10.1.3.0/24', u'az': u'ap-northeast-1c', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-queue-C'}, u'cidr': u'10.1.9.0/24', u'az': u'ap-northeast-1c', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-db-C'}, u'cidr': u'10.1.5.0/24', u'az': u'ap-northeast-1c', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-xxxxxxxxr-C'}, u'cidr': u'10.1.7.0/24', u'az': u'ap-northeast-1c', u'id': u'subnet-xxxxxxxx'})
failed: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-public-B'}, u'cidr': u'10.1.0.0/24', u'az': u'ap-northeast-1b', u'id': u'subnet-xxxxxxxx'}) => {"failed": true, "item": {"az": "ap-northeast-1b", "cidr": "10.1.0.0/24", "id": "subnet-xxxxxxxx", "resource_tags": {"Name": "apne1-subnet-public-B"}}}
msg: Instance creation failed => InternalError: An internal error has occurred
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-db-B'}, u'cidr': u'10.1.4.0/24', u'az': u'ap-northeast-1b', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-queue-B'}, u'cidr': u'10.1.8.0/24', u'az': u'ap-northeast-1b', u'id': u'subnet-xxxxxxxx'})
skipping: [localhost] => (item={u'resource_tags': {u'Name': u'apne1-subnet-web-B'}, u'cidr': u'10.1.2.0/24', u'az': u'ap-northeast-1b', u'id': u'subnet-xxxxxxxx'})

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [debug msg={{ item | regex_replace('^10\.([0-9]+)\.0\.0/24', '10.\1.0.254/24') }}] ***
{'skip_reason': 'Conditional check failed', 'item': u'10.1.6.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.1.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.3.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.9.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.5.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.7.0/24', 'skipped': True, 'changed': False}
{'msg': u'10.\x01.0.254/24', 'verbose_always': True, 'changed': True, 'item': u'10.1.0.0/24'}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.4.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.8.0/24', 'skipped': True, 'changed': False}
{'skip_reason': 'Conditional check failed', 'item': u'10.1.2.0/24', 'skipped': True, 'changed': False}
skipping: [localhost] => {"msg": "All items completed", "changed": true, "results": [{"item": "10.1.6.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.1.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.3.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.9.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.5.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.7.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"msg": "10.\u0001.0.254/24", "verbose_always": true, "changed": true, "item": "10.1.0.0/24"}, {"item": "10.1.4.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.8.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}, {"item": "10.1.2.0/24", "skipped": true, "changed": false, "skip_reason": "Conditional check failed"}]}
PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
