### ISSUE TITLE
setup module (facts) does not list interface aliases

### ISSUE THREAD

**Issue by akhayyat** [ansible/ansible#842]
On an OpenVZ guest, the main ip is assigned to `venet0:0`. However, ansible facts list only `lo` (127.0.0.1) and `venet0` (127.0.0.2).
Therefore, one cannot get the machine's actual IP address using ansible facts.

Facter, however, does show the main IP.

Upon inspecting the source code of both tools, it turns out ansible parses `/proc/dev/net`, which does not show `venet0:0`, while facter parses the output of the `ifconfig` command, which does list both `venet0` and `venet0:0`.

As far as I can tell, there is no reference to either of the `venet0:0` alias or the main IP address anywhere in `/proc` or `/sys`

Options:
1. Parse the output of the `ifconfig` command
2. Parse the output of the `ip addr` command
3. Something else I am unaware of!

On a positive note, the current implementation parses a handful of `/proc` files as well as the output of the `ifconfig` command. Using only `ifconfig` or `ip addr` to extract all facts, the implementation can be made simpler.

**Comment by sfromm** [comment]
As discussed elsewhere, interface aliases are not enumerated in _/proc/net/dev_.  Since this problem is specific to ipv4, it seems prudent to switch to 'ip addr' in get_ipv4_facts() to enumerate all addresses associated with a real interface.

This begs the question:  do we want to behave like facter and pretend that venet0:0 is an interface (option #1) or more closely emulate how linux understands the alias (option #2).  

If option #1, then the ifalias needs to be appended to ansible_interfaces and a ansible_<ifalias> dict needs to be created for each ifalias.  I have some working code for this that I can commit.

If option #2, we treat aliases as additional addresses on an interface, similar to how ansible collects ipv6 information.  This also means there is no ansible_venet0:0 fact.  The alias would show up under ansible_venet0.  For examle:

```
"ansible_venet0": {
    "ipv4": [
        {
            "address": "127.0.0.2",
            "netmask": "255.0.0.0",
            "network": "127.0.0.0"
        },
        {
            "address": "192.168.4.5",
            "netmask": "255.255.255.0",
            "network": "192.168.4.0",
            "ifalias": "venet0:0"
         }
     ]
```

Thoughts?  In general, I like the idea of presenting the facts as near to what the underlying OS reports.  However, it won't be easy for users to discover.

**Comment by sfromm** [comment]
To reinforce the point, making ipv4 a list of dicts will not be backward compatible.  Pretty sure that will break people's playbooks.

As a sidenote, there isn't a good way to look up a specific ipv6 address.  Moving ipv4 to a list of dicts will have the same problem.

One possibility mentioned on irc ( @akhayyat ?) would be to add route-related facts.  This could be a problem if someone is running quagga on their box and have a serious route table going on.

**Comment by sfromm** [comment]
Another option to retain compatibility:

```
ansible_venet0: {
    ipv4: { ... }
    ifaliases: [
       venet0:0: { ... }
    ]
}
```

**Comment by akhayyat** [comment]
About options 1 and 2..
In the case of the OpenVZ guest, `route` lists the default interface as `venet0`, while `ip addr` shows the main IP next to `venet0:0`, which is listed under `venet0`.
Also, configuring the firewall for `venet0` works fine.
These two points favor option 2.
So, it appears that dealing with the alias as an IP alias (another IP for the same interface, not another interface) works for most purposes.

The only problem with option 2 is IP lookup. Listing multiple addresses under one interface makes it tricky to identify which is the desired IP. Then again, with option 1 you'd have two interfaces, and you'd have to pick the right interface.

What could help determining the main IP is a fact for the default route. For example, a command like:
    `ip route get 8.8.8.8`
shows the interface and the IP for outgoing connections. As @sfromm pointed out, I have no idea how that command would behave on a router system with multiple routes. Perhaps it will just pick the one that leads to the destination used in the command, which may or may not be the desired outcome.

**Comment by sfromm** [comment]
A more concrete example:

Currently:

```
    "ansible_eth0": {
        "ipv4": {
            "address": "10.10.60.21", 
            "netmask": "255.255.254.0", 
            "network": "10.10.60.0"
        }, 
```

Proposed:

```
    "ansible_eth0": {
        "ipv4": [
            {
                "address": "10.10.60.21", 
                "netmask": "255.255.254.0", 
                "network": "10.10.60.0"
            }, 
            {
                "address": "10.10.61.19", 
                "ifalias": "eth0:2", 
                "netmask": "10.10.254.0", 
                "network": "10.10.60.0"
            }, 
            {
                "address": "10.10.60.29", 
                "ifalias": "eth0:3", 
                "netmask": "255.255.254.0", 
                "network": "10.10.60.0"
            }, 
```

**Comment by akhayyat** [comment]
I just realized that the current network fact data structure allows only a single IPv4 address per interface.

This has two implications:
1. Option 2 breaks compatibility, because it replaces a dictionary with a list of dictionaries under the ipv4 key.
2. The current implementation does not allow multiple IPv4's, whether they belong to an alias interface (e.g. `eth0:0`) or they are assigned to the same interface (e.g. via `ip addr add ...`).

IMHO, disallowing multiple IPv4's per interface is a limitation that is better fixed sooner than later. I realize compatibility is important, but breaking compatibility now is easier than breaking it later.

Also, changing IPv4 from a single dictionary to a list of dictionaries introduces more consistency, as the IPv6 key already maps to a list of dictionaries.

**Comment by sbocahu** [comment]
I prefer option #2 (a list of IPv4 addresses) for the following reasons:
- from a sysadmin point of view: I do not setup aliases (I mean Linux's legacy way to handle them: ethX:Y) to get another interface name, but to add an additional IP address. I tend to use iproute2 on new systems. Legacy API is considered "deprecated".
- option #2 also makes more sense for portability with BSD. On these systems there is no such interface notation. Additionnal IP addresses are listed by ifconfig 

(example:

```
# ifconfig wm0
wm0: flags=8b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
...
        inet 192.168.69.43 netmask 0xffffff00 broadcast 192.168.69.255
        inet alias 192.168.69.44 netmask 0xffffff00 broadcast 192.168.69.255
        inet alias 192.168.69.45 netmask 0xffffff00 broadcast 192.168.69.255
```

). option #1 would then require to give a wrong interface name for these aliases.

About breaking backward compatibility: I believe it would be best sooner than later, and that it is acceptable provided it is documented. If the current model has issues, they should be fixed now :)

**Comment by sfromm** [comment]
Another crazy idea:  if the interface has one and only one address, ipv4 continues to point to a dict.  No change.  If the interface has more than one ip address, then ipv4 points to a list of dicts as described above.  

As a concrete example, a host with eth0 and only one ipv4 address:

```
"ansible_eth0": {
    "ipv4": {
        "address": "10.10.40.20", 
        "netmask": "255.255.254.0", 
        "network": "10.10.60.0"
    }, 
```

And a host with more than one ip address for a single interface:

```
"ansible_eth0": {
    "ipv4": [
        {
            "address": "10.10.60.21", 
            "netmask": "255.255.254.0", 
            "network": "10.10.60.0"
        }, 
        {
            "address": "10.10.61.19", 
            "ifalias": "eth0:2", 
            "netmask": "10.10.254.0", 
            "network": "10.10.60.0"
        }, 
    ]
```

At this point, I'm leaning towards this option.  Again, comments are welcome.

**Comment by mpdehaan** [comment]
So we simply cannot break backwards compat on playbooks -- that's a good way to lose a slew of users.   Also deeply nested datastructures with lots of exemptions in them are a PITA to iterate across, and nobody likes that.   The real question comes up is how are people actually going to USE this data, otherwise it's kind of bikeshedding.  I think those needs are mainly around knowing what the ipaddresses each machine has, and also what ipaddresses belong to each interface.  As long as I know that, life is pretty good.   If anybody is really trying to extract the broadcoast address, well, let's talk... but I kinda doubt that is happening.

So, just naming aliases like they are real interfaces seems totally fine, though zecrazytux brings up a point that his aliases don't have names.   Sure.

It seems best to me that we present aliases as interfaces, as in sfromm's "option 1".   While zecrazytux does not actually name his interfaces, I am guessing that most likely he would not be grief stricken if the keys were as such:

 "ansible_wm0": {
        "ipv4": {
            "address": blarg,
            "netmask": blarg,
            "network": blarg,
        }, 

 "ansible_wm0:1": {
        "ipv4": {
            "address": blarg,
            "netmask": blarg,
            "network": blarg,
        }, 

so basically if the alias has no name, we give it one.   Yeah, I know he didn't name his alias or whatever, but that should be alright for most applications.

Though you still might want to know the name of the device without having to parse the string key off, which also sucks in a template or doing basic JSON code.   I would supplement this by, in every interface record, having a key named device, such that:

 "ansible_wm0:1": {
        "ipv4": {
            "address": blarg,
            "netmask": blarg,
            "network": blarg,
            "device": wm0
        }, 

In which case when enumerating the list, I can assume I know what the original interface is, without parsing it, and I can realize the name in the string key "ansible_interfaces" is not _REALLY_ neccessarily any name that has any real meaning.

Ultimately though, all users are mostly just wanting to find all the ip addresses, so even if we do all of this shit, let's just keep it simple and also supply two new top level network facts:

all_ipv4_addresses: []
all_ipv6_addresses: []

and then I think there's enough data to be technically accurate enough, and still please all parties, while still making it super easy to access things.

I think it would also be nice for basic users if there were something like "ansible_ip_v4_address" that attempts to give the first non-loopback address and similarly for ipv6, because most users are just wanting to get an IP address out and that would save them the trouble of iteration too.

If you look at ohai, they have this massive IP structure that is technically correct, but it's hard to iterate across.   Puppet goes the other way and has string keys for most everything.  I think what we want, essentialy is something that is easy to iterate across when you need to, but not terribly deep (avoiding problems of Chef), and having some structure to it where it's not just a flat namespace (like Puppet).   

We also will not break compatibility.

So, yeah, let's make option #1 so... and to make it easier on people who need just the IPs and don't care about iteration, let's make some simple lists and string values so they can get IP addresses out easy enough.

People who really don't like this have freedom to write their own site_facts module as well, or just use the facts from ohai or facter by installing those tools, though this should fulfill 99% of the user needs, if not all of them.

Comments?

**Comment by mpdehaan** [comment]
On Fri, Aug 10, 2012 at 6:40 PM, Stephen Fromm notifications@github.comwrote:

> Another crazy idea: if the interface has one and only one address, ipv4
> continues to point to a dict. No change. If the interface has more than one
> ip address, then ipv4 points to a list of dicts as described above.

This makes it evil to use in a template if you don't know how many you get
back -- an object or function should always return one and only one kind of
data type.   Things that return different datastructures require special
handling in iteration.

**Comment by akhayyat** [comment]
Works for me, I guess.

The top level IP facts are a great idea: much easier to access. I particularly like the `ansible_ip_v4_address`, which I was referring to as the default interface address earlier. This is basically what I am after.

If _every_ interface gets a `device` key, be it an alias or a real interface, then I think all scenarios are accounted for. That will definitely help when trying to find the name of the interface of a given IP (e.g. the main IP available in a top level fact). Otherwise, you'd have to check the interface key for the `:` character and ... well ... it gets ugly.

The only thing I dislike about this is the inconsistency between the IPv4 and IPv6 structures, but that's arguably cosmetic, and may be considered to reflect the native capabilities of the two IP versions.

**Comment by mpdehaan** [comment]
Would you like to submit a pull request to make this so?

**Comment by akhayyat** [comment]
Sure. I will give it a go tonight.

**Comment by akhayyat** [comment]
There is a potential problem..
What if `eth0` has two IPv4 addresses, and there is also `eth0:0` with its own IPv4 address?
If we see both `eth0` addresses first, we will give them the interface names `eth0` and `eth0:0`, respectively.
When we find the real `eth0:0`, we would have to rename it, or rename the fake `eth0:0`.
In all cases, do we really want to confuse made up interface names with real ones that are really present in the underlying system?

A simple solution might be to devise our own made up names for interfaces with multiple IPv4 addresses. Something like `eth0-0`. But do we really want to make up our own interface names?
On one hand, it's non-standard. On the other hand, it is less confusing, and simplifies the code.

What do you think?

**Comment by mpdehaan** [comment]
I think most people just need the IP addresses.  I'll comment on the pull request.

**Comment by mpdehaan** [comment]
merged in, so closing this.  Thanks everyone for building a nice answer to this that is also compatible with any playbooks that are already out there.  Good stuff.
