### ISSUE TITLE
Service module error message on bad return in Fedora 20 could be improved (edited)

### ISSUE THREAD

**Issue by bozicm** [ansible/ansible#8420]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.6
##### Environment:

Ansible host: Fedora 20
Ansible target:
- CentOS 6.5
- stock MySQL 5.1.73
##### Summary:

Ansible throws error when trying to reload MySQL daemon, but it does reload the configuration. Mysqld init script throws `exit 3` on reload. Workarounds are possible but I'm wondering if Ansible should handle uncommon exit statuses more gracefully.
###### Service module example

```
ansible -m service -a 'name=mysqld state=reloaded' c6host
```
###### Shell module example

```
ansible -m shell -a '/sbin/service mysqld reload' c6host
```
##### Expected Results:

```
c6host | success >> {
    "changed": true, 
    "name": "mysqld", 
    "state": "reloaded"
}
```
##### Actual Results:

What happens:
###### Service module example

```
c6host | FAILED >> {
    "failed": true, 
    "msg": ""
}
```
###### Shell module example

```
c6host  | FAILED | rc=3 >>
```

**Comment by mpdehaan** [comment]
So this seems to be a new problem in the MySQL init script with Fedora 20, so you should definitely persue this with upstream (ideally the Fedora bug system for MySQL).

That being said, I think the "failed: True" part could include the rc code, because that would provide a little more debugging info.

It may be that the status report from MySQL is unreliable, in which case the "pattern" argument to the service module may help.

**Comment by bozicm** [comment]
Acutally, the host in question has CentOS 6.5 (Fedora is my desktop from where I run Ansible playbooks). I took another look at the MySQL init script and it's funny, `service mysqld reload` doesn't actually do anything at all, just returns `exit 3` (looks like a placeholder?).

So yeah, I'll just file my issue to CentOS upstream.
