### ISSUE TITLE
ec2_asg module: port should not be a required option

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#8444]
##### Issue Type:

Bugfix
##### Ansible Version:

ansible 1.7 (devel 4e6685d772) last updated 2014/08/04 19:06:17 (GMT -700)
##### Environment:

N/A
##### Summary:

I should not have to specify a port if I just want to return information about an ELB that was created outside of Ansible.  The core of the problem is here (line 584)

```
if state == 'present' and not listeners:
    module.fail_json(msg="At least one port is required for ELB creation")
```
##### Steps To Reproduce:

Create ELB outside of Ansible, then:

```
ansible localhost -i hosts -c local -m ec2_elb_lb -a "name=rollcage-ElasticLo-EX3JVJP8O03A state=present region=us-east-1"
```
##### Expected Results:

The task would return information about the load balancer, even though it wasn't created in ansible.

```
TASK: [ec2_asg] ***************************************************************
<127.0.0.1> REMOTE_MODULE ec2_asg name=rollcage-WebServerGroup-DTP1RQO7C6P4 state=present region=us-east-1
changed: [localhost -> 127.0.0.1] => {"availability_zones": ["us-east-1c", "us-east-1b", "us-east-1d"], "changed": true, "desired_capacity": 5, "health_check_period": 300, "health_check_type": "EC2", "instances": ["i-bb1cc597", "i-a51fc689", "i-53629c79", "i-ca8267e7", "i-905da3ba"], "launch_config_name": "rollcage-LaunchConfig-ZAZA7BCRNVAI", "load_balancers": ["rollcage-ElasticLo-EX3JVJP8O03A"], "max_size": 10, "min_size": 5, "vpc_zone_identifier": ""}
```
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true,
    "msg": "At least one port is required for ELB creation"
}
```

**Comment by mpdehaan** [comment]
clarifing description to make it clear this is about the ec2_asg module

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
