### ISSUE TITLE
postgresql_user module: Creating an user with wrong or invalid privilege will cause a Traceback

### ISSUE THREAD

**Issue by wrosario** [ansible/ansible#8456]
##### Issue Type:

“Bug Report"
##### Ansible Version:

1.7 
##### Environment:

Centos 6.5. 
##### Summary:

Creating an user with wrong or invalid privilege will cause a Traceback. 
##### Steps To Reproduce:

```
- name: test state=present for a database name (expect changed=true)
  postgresql_db: name={{ db_name }} state=present
  sudo: yes
  sudo_user: postgres
  register: result

- name: create user1 to access database 
  postgresql_user: db={{ db_name }} name=user1 password=password1 priv=*.*:ALL state=present
  sudo: yes
  sudo_user: postgres
```
##### Expected Results:

Expect to display a friendly message instead of a traceback.
##### Actual Results:

```
TASK: [test_postgresql_db | create user1 to access database] ****************** 
failed: [testhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-kjavwnxytywjrajrxodlxntyanridyba
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1406925328.38-256639295968953/postgresql_user", line 1830, in <module>
    main()
  File "/tmp/ansible-tmp-1406925328.38-256639295968953/postgresql_user", line 500, in main
    changed = grant_privileges(cursor, user, privs) or changed
  File "/tmp/ansible-tmp-1406925328.38-256639295968953/postgresql_user", line 375, in grant_privileges
    changed = grant_func(cursor, user, name, privilege)\
  File "/tmp/ansible-tmp-1406925328.38-256639295968953/postgresql_user", line 289, in grant_table_privilege
    cursor.execute(query)
psycopg2.ProgrammingError: schema "*" does not exist



FATAL: all hosts have already failed -- aborting
```

**Comment by piffey** [comment]
Seems to be a couple of different issues open right now with psycopg2 exceptions bubbling up. Right now the modules handle a few specific ones based upon pg error code. Instead of raising the exception when it doesn't match one of the conditionals, would it be better just to always wrap that up? Problem is a lot of those error messages are pretty misleading.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
