### ISSUE TITLE
docker module only spins off one container per image

### ISSUE THREAD

**Issue by yongjunj** [ansible/ansible#8461]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

OS X 10.9.4
##### Summary:

`docker` module only spins off one container per image by default
##### Steps To Reproduce:

I'm trying to use `docker` module for rolling deployment of my app containers.
To do this, my playbook first builds a docker image with `docker_image`.
It then uses `docker` module to spin off multiple (let's say N) containers from that single image.
##### Expected Results:

Ansible spins off N containers from the image.
##### Actual Results:

Ansible spun off only one container and skipped over the rest.
##### Notes:

The workaround is to explicitly assign unique names to each container (i.e. specify `name` option in `docker` module).

Perhaps I'm using `docker` module options correctly - is this a known issue/intended behavior?

**Comment by mpdehaan** [comment]
Can you share a snippet of your playbook so we can understand a bit more of seeing this in context?

Thanks!

**Comment by yongjunj** [comment]
Thanks for the quick response. The following reproduces this issue:

Playbook:
- `rolling-deploy.yml`: https://gist.github.com/yongjunj/82a36b325236a93d51cc

And the two roles:
- `docker-build`: https://gist.github.com/yongjunj/d4c2f9e8c7d8b620465b
- `docker-run`: https://gist.github.com/yongjunj/3f9db0e4c52e82a8ea9e

Required variables:
- DOCKER_URL: docker host url
- HAPROXY_URL: haproxy url
- DOCKER_BUILD_PATH: path to Docker build context
- DOCKER_IMAGE_NAME
- DOCKER_IMAGE_TAG
- DOCKER_RUN_PARAMS: list of `docker run` parameters, e.g.:

```
[
    {"port": "9010:80", "volumes": "/home/user/log/9010:/var/log", "env": "BACKEND_URL=https://back.end.com,APP_LOGLEVEL=DEBUG"},
    {"port": "9011:80", "volumes": "/home/user/log/9011:/var/log", "env": "BACKEND_URL=https://back.end.com,APP_LOGLEVEL=DEBUG"},
    {"port": "9012:80", "volumes": "/home/user/log/9012:/var/log", "env": "BACKEND_URL=https://back.end.com,APP_LOGLEVEL=DEBUG"}
]
```

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- The expected behavior of the playbook is Ansible spins off N containers from the image.

However, however what is happening is that:
- You have not specified the `count=` parameter in your playbook above. Per the docker module documentation (http://docs.ansible.com/docker_module.html), the default value for the count parameter is 1.

We would suggest:
- Specify an explicit value for the count parameter, or as you have done already assign unique names to each container.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by yongjunj** [comment]
Thanks for the response.

I was aware of `count=` parameter; however, my use case involves supplying different `env=` parameter to each of the containers, so I guess it was right to assign unique names to each container.

I will be sure to ping ansible-project Google group in the future. Thanks @jimi-c !

**Comment by jimi-c** [comment]
@yongjunj ahh yes, if you have unique settings for each container then using unique names is the correct way to go. Thanks!
