### ISSUE TITLE
ControlPersist sockets conflict with synchronize and rsync commands in playbook

### ISSUE THREAD

**Issue by acesaro** [ansible/ansible#8473]
##### Issue Type:

Bug Report/Feature Idea
##### Ansible Version:

ansible 1.6.7
##### Environment:

CentOS 6.5
##### Summary:

I've noticed that when I have `synchronize` tasks or `shell: rsync` tasks defined in a playbook and I am utilizing `transport = ssh` and `ControlPersist`, the SSH connections for Ansible to run the plays and the connections used by `rsync` conflict with each other.
##### Steps To Reproduce:
- Use `transport = ssh` in ~/.ansible.cfg file
- Create a task using the `synchronize` module
- Run the playbook with this task defined
- The task should hang for the amount of seconds that you have defined in the `ControlPersist` option of your ~/.ssh/config or ~/.ansible.cfg ssh_args parameter.
- If you `Ctrl-c` the run of the playbook, the issue no longer occurs, but you have to run the playbook twice every time to avoid this.
##### Expected Results:

The synchronize module automatically figures out that `ControlPersist` connection exists for the host that it is `rsync`'ing to and disables the use of `ControlPersist` in its own SSH connection that wraps the rsync protocol.  It could also just always add the `-e 'ssh -S none'` parameter to the `rsync` command that it executes.
##### Actual Results:

What occurs is that `rsync` hangs until the `ControlPersist` timeout expires and then is able to continue (resulting in 60s or more of waiting for synchronize tasks to complete).

As a workaround that resolves this issue, I added `rsync_opts="-e 'ssh -S none'"` to the synchronize module call and `-e 'ssh -S none'` to the `shell: rsync`, which effectively disables the use of `ControlPersist` by the `ssh` wrapper that `rsync` uses by default.  I just want to report this behavior in case anyone else runs into this and if the development team would like to consider adding a cleaner option for the synchronize module to handle this case.  I searched the web and the issues for this GitHub project, but couldn't find anything relevant before deciding to post this.  Thanks!

**Comment by mpdehaan** [comment]
Ouch!

Strange that this hasn't been reported before really, but I'm also curious about your control OS. Are you managing from CentOS 6.5?   This SSH doesn't have ControlPersist functionality, so I'm wondering a bit if you've upgraded your SSH.  If so, that's fine, otherwise I'm just a little confused how you got there :)

I'm thinking the "-S none" may be the best option if we find out control persist is a parameter, yes and that seems easy enough.

**Comment by acesaro** [comment]
Yes, I am using CentOS 6.5 as the control host, but I have a custom compiled OpenSSH client that is first in $PATH:

```
$ /usr/local/bin/ssh -V
OpenSSH_6.6p1, OpenSSL 1.0.1e-fips 11 Feb 2013
```

Thanks for your support with this and I'm also surprised that I'm the first to mention it. :)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
