### ISSUE TITLE
Suggestion for enhancing functionality of group module

### ISSUE THREAD

**Issue by kad** [ansible/ansible#8476]
##### Summary:

I'd like to suggest functionality of group module, where for sysadmin would be possible to specify explicitly list of users for that group.
##### Steps To Reproduce:

```
# set members list of  "somegroup" to those users and no one else.
- group: name=somegroup state=present users=user1,user2,user3

# add users to the group if they are not existing 
- group: name=somegroup2 append=yes users=user2,user3,user4
```
##### Expected Results:
- groups membership can be explicitly defined in playbooks.
##### Actual Results:

right now, group membership is required to be listed in each individual account. so, it is possible to limit user to belong to only specific set of groups, but impossible for site admins to declare group where only specific users allowed to be present.

**Comment by mpdehaan** [comment]
Yeah right now the pattern is more like to maintain a list of users to remove.  I think this would be a reasonable thing to do.  We could move some of the users code to a common file to make this easier.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
