### ISSUE TITLE
traceback when atomic_move can't rewrite a file:  should catch exception and give nice msg

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#8480]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.10
##### Environment:

Mac OS X 10.9.4 to CentOS 6.5
##### Summary:

Ugly return
##### Steps To Reproduce:

This section of my playbook:
- name: Set date.timezone
  lineinfile: dest=/etc/php.ini
              regexp='^;date.timezone'
              line="date.timezone = America/Los_Angeles"
##### Expected Results:

I hadn't told ansible to use sudo, this should return a friendlier message like "You have to use sudo, you dummy!"
##### Actual Results:

TASK: [roundcube | Set date.timezone] ****************************************\* 
fatal: [jedis-test] => failed to parse: Traceback (most recent call last):
  File "/home/joliver/.ansible/tmp/ansible-tmp-1407360596.56-1014960040092/lineinfile", line 1589, in <module>
    main()
  File "/home/joliver/.ansible/tmp/ansible-tmp-1407360596.56-1014960040092/lineinfile", line 361, in main
    ins_aft, ins_bef, create, backup, backrefs)
  File "/home/joliver/.ansible/tmp/ansible-tmp-1407360596.56-1014960040092/lineinfile", line 270, in present
    write_changes(module, lines, dest)
  File "/home/joliver/.ansible/tmp/ansible-tmp-1407360596.56-1014960040092/lineinfile", line 165, in write_changes
    module.atomic_move(tmpfile, dest)
  File "/home/joliver/.ansible/tmp/ansible-tmp-1407360596.56-1014960040092/lineinfile", line 1416, in atomic_move
    prefix=".ansible_tmp", dir=dest_dir, suffix=dest_file)
  File "/usr/lib64/python2.6/tempfile.py", line 444, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python2.6/tempfile.py", line 228, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/etc/.ansible_tmp8EQMXdphp.ini'

**Comment by mpdehaan** [comment]
Ansible definitely agrees that a traceback is always a bug.   We can probably at least catch this and return a nice "permission denied".

**Comment by jimi-c** [comment]
@jnojr I've created the above patch, which should resolve the issue, if you'd like to test it before I merge it in.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
