### ISSUE TITLE
Ansible 1.7 regression: "ERROR: problem running [Vault password file] ([Errno 13] Permission denied)"

### ISSUE THREAD

**Issue by amyodov** [ansible/ansible#8483]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

OS X 10.9.4, Ansible 1.7 taken from Brew
##### Summary:

If a Vault password file has the executable bit set, it is now forcibly treated as "a file that must be executed to generate the password on stdout" and never attempted as "a file that contains the password".

That may be wrong and even regressive (without any obvious workaround), if the password file is actually stored on an FS that mounts all the files with executable bit set.

In particular, I faced the following scenario. I store the Vault password files on the Truecrypt-secured volume, msdos-formatted. When mounting it on OS X, it must get be mounted with the executable bit enabled; otherwise the directories on the Truecrypt volume will become unbrowseable (and on OS X, unlike on Linux, `mount_msdos` command doesn't have any separate umask/fmask options to set different flags for a file and for a directory). Thus, I always have to mount these files as executable. Since Ansible 1.7, I cannot use them for `ansible-playbook` command with `--vault-password-file` option anymore, as they are attempted to be executed, unsuccessfully.
Also, this behavior is inconsistent, as they still can be used with `ansible-vault` command.
##### Steps To Reproduce:

Create a Vault password file, and use it for Vault-encryption of any contents. `chmod +x` your Vault password file. Now:
1. Try to use this file with `ansible-playbook`.
2. Try to use this file with `ansible-vault`, to edit your previously encrypted data.
##### Expected Results:
1. `ansible-playbook` attempts to use this file as an executable script; fails, maybe generates some warnings; then fallbacks to pre-1.7-behavior and reads this file as just a password-containing data.
2. `ansible-vault` behaves consistent with `ansible-playbook`, and finally, after a warning or two, reads this file to decrypt the data.
##### Actual Results:
1. `ansible-playbook` fails with `ERROR: problem running [here goes the path to the vault password file] ([Errno 8] Exec format error)` (or maybe `([Errno 13] Permission denied)`, depending on mount options).
2. `ansible-vault` just decrypts the contents as usual, even though `ansible-playbook` cannot do that anymore.

**Comment by mpdehaan** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- The executable bit is a way to indicate the file is not a basic file but a script to return the password
- This is referenced in the documentation
- chmod -x the file means it is no longer treated as a script
- inventory files in Ansible work the same way

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by bimusiek** [comment]
Would be nice to mention it the script possible problem. I got this `vault_password` in this form somehow from colleague and I could not figure out why it does not work for me. Then I found this post, but I think better error message would be nice to have.

**Comment by cplewnia** [comment]
Although this is an old topic I would like to add a thought, since there still is a problem today with version 2.5: Using the Windows Subsystem for Linux the windows filesystem is mounted in a way that all files have the executable bit and apparently you cannot change that with chmod. I must confess that I did not dig deeper whether this filesystem issue can be fixed.

However, although this kind of a filesystem issue, I think the design decision to rely on the filesystem is not optimal. Further - although documented - it is in my opinion preferable to have a syntax that expresses explicitely whether you are loading a password from a text file or whether you are executing a script. With the current approach it is my guess that alot of Ansible user runs into the issue once before they find this out via the documentation.
