### ISSUE TITLE
Imported module support code does not exist at /usr/lib/pymodules/python2.7/ansible/module_utils/powershell.ps1

### ISSUE THREAD

**Issue by sergeyx10** [ansible/ansible#8490]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu 14.04.1 LTS
##### Summary:

I try to use Windows supprt in Ansible. Looks like i'm doing something wrong.
##### Steps To Reproduce:
1. Install ansible
2. Setup file group_vars/windows.yml:
   ansible_ssh_user: ansible
   ansible_ssh_pass: password
   ansible_ssh_port: 5986
   ansible_connection: winrm
3. Setup file hosts:
   [windows]
   host1
   host2
4. Run
   ansible windows -m win_ping
##### Expected Results:

Some information about the windows hosts.
##### Actual Results:
1. The results:
   host1 | FAILED => imported module support code does not exist at /usr/lib/pymodules/python2.7/ansible/module_utils/powershell.ps1
   host2 | FAILED => imported module support code does not exist at /usr/lib/pymodules/python2.7/ansible/module_utils/powershell.ps1

Thanks!

**Comment by sergeyx10** [comment]
But as i understand, it can be downloaded from
https://github.com/ansible/ansible/blob/a52cbdbcedab708d38e07a0e79ae82fb001cd960/lib/ansible/module_utils/powershell.ps1

**Comment by mpdehaan** [comment]
It's possible the python packaging didn't pick this file up, and we'll verify.  

Can you share some information about how you installed Ansible?

**Comment by jimi-c** [comment]
Hi!

A change has been applied for this ticket, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
