### ISSUE TITLE
Runner.run_async fails with `UnboundLocalError: local variable 'jid' referenced before assignment`

### ISSUE THREAD

**Issue by tonsky** [ansible/ansible#8491]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

N/A
##### Summary:

When using Runner through Python API, run_async fails with UnboundLocalError
##### Steps To Reproduce:

```
ansible.runner.Runner(
    inventory   = inv,
    module_name = module,
    module_args = args
).run_async(0)
```
##### Expected Results:

It works in fire and forget mode: executes command and does not wait for output.
##### Actual Results:

```
File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 1250, in run_async
  return results, poller.AsyncPoller(results, self)
File "/usr/lib/python2.6/site-packages/ansible/runner/poller.py", line 51, in __init__
  if jid is None:
UnboundLocalError: local variable 'jid' referenced before assignment
```

Indeed, there’s a path when `skipped` may be set to `false`, but `jid` kept uninitialized. Here’s the place: https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/poller.py#L51

**Comment by jimi-c** [comment]
Hi! I see you're running 1.6.6, which is several revisions old at this point (we just released 1.7 yesterday). I believe this issue has been resolved, so I would recommend testing against at least 1.6.10 to see if you still see the issue there.

**Comment by tonsky** [comment]
Confirmed for ansible 1.7:

```
import ansible.runner
import ansible.inventory

print ansible.runner.Runner(
    remote_user = user,
    inventory   = ansible.inventory.Inventory([host]),
    module_name = 'command',
    module_args = 'echo "Hello world"'
).run_async(0)
```

---

```
Traceback (most recent call last):
  File "./ans.py", line 11, in <module>
    ).run_async(0)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 1291, in run_async
    return results, poller.AsyncPoller(results, self)
  File "/Library/Python/2.7/site-packages/ansible/runner/poller.py", line 51, in __init__
    if jid is None:
UnboundLocalError: local variable 'jid' referenced before assignment
```

Regression was intoduced in 1.6.0, by this commit: https://github.com/ansible/ansible/commit/e09313120c96c00980aef12c3105647bdc3857ca (the line with `jid=None` removed)

**Comment by jimi-c** [comment]
Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
