### ISSUE TITLE
pip module installing a specific git commit should not be editable

### ISSUE THREAD

**Issue by klynch** [ansible/ansible#8493]
##### Issue Type:

Feature Idea / Limitation
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

When installing an egg from a specific git commit (e.g. `git+https://github.com/klynch/something-python@dece755dde8b9395f66a2eba85bae2f6cc3002d1#egg=something`), pip does not force editable mode.

However, the ansible pip module blindly forces editable. Ansible should follow pip's lead, or an optional flag should be provided.
##### Steps To Reproduce:

```
- name: install python package
  pip:
    name: "git+https://github.com/klynch/something-python@dece755dde8b9395f66a2eba85bae2f6cc3002d1#egg=something"
```
##### Expected Results:

Ability to install a pip package from a git commit without having the code be installed in "editable" mode.
##### Actual Results:

The pip package is installed in editable mode. Installing directly via pip does not install the package in editable mode.

**Comment by jimi-c** [comment]
Hi! Thanks very much for your submission to Ansible. It sincerely means a lot to us.

Just as a quick reminder of things, this is a really busy project. We have over 800 contributors and to manage the queue effectively we assign things a priority between P1 (highest) and P5.

We may also ask some questions and it may be a while before we can get to this. We'll work things in priority order, so just wanted you to be aware of the queue and know we haven't forgot about you!

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly. You may also wish to join one of our two mailing lists which is very active:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Comment by dominik-lekse** [comment]
Currently, I am on a project in which Ansible is used for application deployment and relatively new to the concepts of Anisble. However, so far, I experienced a steep learning curve.

To get to this issue, I also struggled with this behavior while using the pip module to install from a git repository. Since, I was migrating a plain shell script to pretty Ansible code, the difference in the module behavior from the pip cli was not obvious. I would at least expect a parameter to explicitly disable an install editable mode. As a workaround, there was no other way for me to use the shell module.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
