### ISSUE TITLE
math operation on variables results in string

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#8498]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8 (devel 769a5738e3) last updated 2014/08/07 10:24:07 (GMT -700)
##### Environment:

N/A
##### Summary:

Perform math operation on variable results in string.  
##### Steps To Reproduce:

```
- hosts: localhost
  connection: local
  vars:
    w: 1
    x: 2
    y: "{{ w + x }}"
    z: 3
  tasks:
  - debug: msg="{{ y }}" == "{{ z }}"
    when: y == z
```

If I use:

```
  - debug: msg="{{ y | int }}" == "{{ z }}"
    when: y == z
```

then it is successful.
##### Expected Results:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="3" == "3"] **************************************************
ok: [localhost] => {
    "msg": "3"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="3" == "3"] **************************************************
skipping: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us.

We're not sure this is a bug, since the jinja2 print block (`{{ var }}`) always results in a string, meaning the cast to an int is required if that result is stored in another variable.

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists to talk about this and we might be persuaded otherwise.

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
