### ISSUE TITLE
Enhancement - please load plugins from /myproject/plugins/*_plugins

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#8504]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8
##### Environment:

Mac OSX controlling Slackware Linux
##### Summary:

Suggestion - please load custom plugins from /myproject/plugins/*_plugins
(for example /myproject/plugins/filter_plugins)

This is cleaner than having to litter the top project directory with for example
/myproject/filter_plugins
/myproject/callback_plugins
etc.

Even cleaner would be allowing for the following structure:

/myproject/plugins/action
/myproject/plugins/connection
/myproject/plugins/filter
...etc...
##### Steps To Reproduce:

Place a new custom plugin for example:

/myproject/plugins/filter_plugins/customfilters.py
##### Expected Results:

Filters should be loaded
##### Actual Results:

Filters are not loaded because it doesn't look inside the project's "plugins" folder currently. It only looks for a top-level "filter_plugins" folder.

**Comment by mpdehaan** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

```
* (A) We don't want to change existing behavior and break things
* (B) It's possible we could have it look in both places
* (C) We're not finding that the change is quite neccessary to work on this at the expense of managing other items in the queue
* (D) many folks keep their plugins in directories outside their projects when dealing with multiple projects, and configure those paths in ansible.cfg instead
```

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always neccessary.

Thank you once again for this and your interest in Ansible!
