### ISSUE TITLE
yum module problem in version 1.6.6 working on centos 5.8 with Python 2.7

### ISSUE THREAD

**Issue by yekeqiang** [ansible/ansible#8507]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Centos 5.8 
Python2.7
##### Summary:

yum module is throw a ImportError
##### Steps To Reproduce:

ansible test1 -m yum -u root -a "name=httpd state=installed" -k
SSH password: 
host1 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1407467645.48-218673787363246/yum\", line 27, in <module>\n    import yum\nImportError: No module named yum\n", 
    "parsed": false
}

host2 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1407467645.71-72622898567899/yum\", line 27, in <module>\n    import yum\nImportError: No module named yum\n", 
    "parsed": false
}
##### Expected Results:

i hope can install httpd in the remote machine
##### Actual Results:

host1 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1407467645.48-218673787363246/yum\", line 27, in <module>\n    import yum\nImportError: No module named yum\n", 
    "parsed": false
}

host2 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1407467645.71-72622898567899/yum\", line 27, in <module>\n    import yum\nImportError: No module named yum\n", 
    "parsed": false
}

**Comment by dirtyharrycallahan** [comment]
Have you installed yum on the CentOS system?

**Comment by yekeqiang** [comment]
i have installed yum on my system。i can use yum install software with CLI
example:
yum -y install httpd 
the result is success

**Comment by yekeqiang** [comment]
the reson may be is python2.7 that it does not have the yum module？how can i fix it?

**Comment by mpdehaan** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- I see you are trying to manage a CentOS 5 system with an extra python
- you probably have set ansible_python_interpreter for this host
- yum is installed for the system python, not your python (don't correct this)
- you will need to NOT set ansible_python_interpreter for this host
- ansible should work fine with the system python as modules are meant to usually be 2.4 compatible

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
