### ISSUE TITLE
lineinfile generates invalid data

### ISSUE THREAD

**Issue by fesplugas** [ansible/ansible#8535]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.0
##### Environment:

Ubuntu 14.04
##### Summary:

When using lineinfile sometimes in some cases generated line is scaped.
##### Steps To Reproduce:

```
- name: "add dotenv to node-app"
  lineinfile: >
    dest=/u/{{ node_app_name }}/app.js
    line="{{ item }}"
    insertbefore=BOF
  with_items:
    - "dotenv.load();"
    - "var dotenv = require('dotenv');"
```
##### Expected Results:

```
$ cat app.js 
var dotenv = require('dotenv');
dotenv.load();
```
##### Actual Results:

```
$ cat app.js
var dotenv = require('dotenv');
'dotenv.load();'
```

**Comment by fesplugas** [comment]
In `1.6.8` works as expected.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
