### ISSUE TITLE
problems with yaml parsing after > character in ansible-playbook 1.6.10

### ISSUE THREAD

**Issue by bentrombley** [ansible/ansible#8537]
This line command is working in Ansible 1.6.3 
- name: Monitor for full disk
  template: >
    src=filesystem.j2
    dest=/etc/monit/conf.d/filesystem
    backup=no
  sudo: yes

However in the latest version I see three errors (fixing one reveals the next one):
1) the variable `dest` includes the newline character, so on the target filesystem it creates a file named `filesystem?`
2) changing to dest="/etc/monit/conf.d/filesystem" works in 1.6.3, but now fails because the " is included in the path
3) backup=no is rejected as not a valid boolean option, I believe for the same reason

So far I've only seen this in template module, so it may be specific to that.

**Comment by mpdehaan** [comment]
Can you please reformat the above?   GitHub allows four space indent to preserve formatting.

I would like to see the full output of "ansible --version" and the output of your playbook run as well, as well as a paste of the file in both the working and non-working case.

Thank you!

**Comment by mpdehaan** [comment]
The first one should actually already be resolved in a recent commit on the devel branch if we're talking about newline preservation.

I'll leave it up to @jimi-c to provide the SHA and explore the other 2.

**Comment by mpdehaan** [comment]
Hi, i see this was reported on 1.6.10, can you also please check all of the above on 1.7, which was recently released with various parser fixes?  

Newlines aren't exactly 100% perfect on this branch, but this will give us a better baseline for the report.

Thanks!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe recent commits on the devel branch should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
