### ISSUE TITLE
Cannot install ansible 1.7

### ISSUE THREAD

**Issue by zupo** [ansible/ansible#8545]
Hi,

I'm trying to install Ansible via easy_install and via zc.buildout, but both fail. I get the following error:

error: Setup script exited with error: SandboxViolation: mkdir('/home/foo/dev/project/share', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
An error occurred when trying to install ansible 1.7. Look above this message for any errors that were output by easy_install.

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Additionally, it seems you might be following a step outside our normal install process (which may be installing with easy_install instead of pip).  See http://docs.ansible.com/intro_installation.html

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by zupo** [comment]
I've read the install docs, but due to infrastructure constraints and politics I cannot use pip for a particular project. The entire infrastructure is built with Buildout and we cannot switch to Pip because it's lacking features.

Basically, with pip-only install, you are cutting away the entire Plone community and a part of the Django community that relies on buildout for setting up their development/production environments.

I've found issues on GitHub about support for buildout that were closed due to opinions that no-one uses easy_install or buildout anymore. Maybe it's time to revisit those?

**Comment by chbrown** [comment]
+1. I too prefer `easy_install` over `pip`, because:
1. `setuptools` is practically part of the standard library; for example, current Mac OS X comes with Python 2.7.5 and `easy_install`, but not `pip`
2. `pip` often fails to install relatively complicated packages successfully, despite reporting success (zeromq), or outright fails (numpy)

Python packaging is purgatory, sure, but pip is not a standard.

**Comment by domenkozar** [comment]
Ansible `devel` branch (future 1.8 release) installs fine via easy_install.

**Comment by chbrown** [comment]
@iElectric awesome, glad to hear that!

**Comment by zupo** [comment]
:clap:
