### ISSUE TITLE
`postgres_user` module doesn't work with AWS RDS databases

### ISSUE THREAD

**Issue by dan-mcdonald** [ansible/ansible#8547]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7.0
##### Environment:

OSX Mavericks 10.9.4
##### Summary:

When running against an AWS RDS Postgresql instance, the postgres_user module can't set up new users.
##### Steps To Reproduce:

Run this task:

```
- name: Ensure user has access to the database
  postgresql_user: login_host={{ db_host }}
                   port={{ db_port }}
                   login_user={{ db_admin_user }}
                   login_password={{ db_admin_password }}
                   db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present 
```
##### Expected Results:

```
ok: [...] => {"changed": true, "db": "database"}
```
##### Actual Results:

```
failed: [...] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-qwpjepgvenunnlewzwjddpnrbfjyptxo
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 1869, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 497, in main
    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 201, in user_alter
    cursor.execute(select, {"user": user})
psycopg2.ProgrammingError: permission denied for relation pg_authid
```

Apparently the `pg_authid` relation [is not available in RDS](https://forums.aws.amazon.com/thread.jspa?threadID=151248).

Possible workaround: if access denied for `pg_authid`, then always set the password.

**Comment by Tatsh** [comment]
Also having this issue. Easiest workaround is to create a database first, save that with `register:` and based on the `changed` key create the new user.

``` yaml
- name: Create db
  postgresql_db: login_user={{pg_user}} ...
  register: create_db

- name: Create user for said db
  postgresql_user: ...
  when: create_db.changed
```

**Comment by lamp** [comment]
The workaround above worked for me

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by memelet** [comment]
This work around did not work for me on 1.9.x. Was this ever fixed or just closed?

**Comment by arusahni** [comment]
@memelet looks like it was just closed. Am on 2.x and it's still broken.

**Comment by billputer** [comment]
@memelet @arusahni It's closed as a duplicate of [ansible/ansible-modules-core#297](https://github.com/ansible/ansible-modules-core/issues/297).

**Comment by tedder** [comment]
In 2.x you must use `no_password_changes=true`.

**Comment by cpcundill** [comment]
Worked for me @tedder , cheers

**Comment by kwach** [comment]
FYI since 2.0 there is `no_password_changes` option that is designed to workaround RDS issue.
Effective when pg_authid is not accessible (such as AWS RDS). Works like a charm.
