### ISSUE TITLE
digital_ocean module: Add support for v2 API

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8563]
##### Issue Type:

Feature idea
##### Ansible Version:

Next
##### Environment:

All
##### Summary:

The digital ocean API was recently updated to v2 and includes a set of new features that make working with Digital Ocean much simpler, including referring to images and regions by string names rather than IDs.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Yep, it's been discussed that some people want this - apparently at least to be able to use names.

Something you might like to work on, perhaps?

**Comment by ghost** [comment]
Yes I've been digging in to the code to see about adding support for names. I don't have a lick of Python experience, though looking at the module code this doesn't look bad at all--might be a good spot to dip my toe in. :)

**Comment by ghost** [comment]
Been making some good progress on this. Something to think about if the V2 API will go in core... how should it fit with the current V1 implementation? There are a few options:
1. Deprecate the V1 API in favor of V2
2. Operate as two entirely separate modules for a while (digital_ocean2 perhaps?)
3. Patch V2 in to the current V1 module and add an "api_version" option

I may spin this module off in to an independent project rather than an ansible fork, and you all can bring it in to core whenever and however seems appropriate.

**Comment by vladcosorg** [comment]
any progress on that?

**Comment by ghost** [comment]
Yeah. I'm working in a fork over at https://github.com/rvangundy/ansible/tree/module-digital_ocean_v2_api

This is a work in progress. It's very similar to the V1 implementation. Currently it only supports working with the Droplet API. I'm now moving on to ssh_keys, domains, etc.

The V2 API requires the latest version of https://github.com/Shrugs/skiff.

You can play with it by calling up the digital_ocean_droplet module.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by gawbul** [comment]
@rvangundy Have you made any progress in moving this over to the new module system at all please? I see the new issue has been logged in ansible-modules-core (https://github.com/ansible/ansible-modules-core/issues/209), but couldn't find whether any code had been migrated over/worked on?

**Comment by leucos** [comment]
@gawbul FYI as of now devel works fine with DO API v2 now and supports slugs at least for regions and sizes and DO_API_TOKEN (tested this morning).
