### ISSUE TITLE
keystone_user modules can't create a role without associating it with user/tenant.

### ISSUE THREAD

**Issue by tomgoto** [ansible/ansible#8565]
##### Issue Type:

“Bug Report”
##### Ansible Version:

Ansible 1.6.6-1.el6
##### Environment:

CentOS 6.5
##### Summary:

`keystone_user` modules can't create a role without associating it with user/tenant.
When you want to create a keystone role, you need to attach it to tenant and user, even if all you want to do is to create only a role.

There is a situation where you want to create empty role named `heat_stack_user` for [OpenStack heat installation](http://docs.openstack.org/icehouse/install-guide/install/zypper/content/heat-install.html).
This role will be used for automatically created user by openstack heat.
##### Steps To Reproduce:

1) playbook

``` python
- name: create heat_stack_user role
  keystone_user: 
    endpoint: http://localhost:35357/v2.0
    token: KEYSTONEADMINTOKEN
    role: heat_stack_user
```
##### Expected Results:

Above task should create a role named `heat_stack_user` only, and you don't have to associate it with user/tenant.
##### Actual Results:

``` javascript
TASK: [create heat_stack_user role] *******************************************
failed: [testsrv06] => {"failed": true}
msg: Code should never reach here

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
