### ISSUE TITLE
request for nova_compute module to be able to add files via the config drive

### ISSUE THREAD

**Issue by paolo-de-rosa** [ansible/ansible#8568]
##### Issue Type:

Feature Request
##### Ansible Version:

ansible 1.8
##### Environment:

Debian Wheezy
##### Summary:

Could be possible to have option to add files in nova boot params for example to pass /etc/network/interface in openstack static ip environment.
##### Expected Results:

adding files in config_drive openstack option something like this: 

```
 files:
     description:
        - A list of file to include in config drive
     required: false
     default: None

....

def _create_server(module, nova):
    image_id = _get_image_id(module, nova)
    flavor_id = _get_flavor_id(module, nova)
    try:
        for dest_path, source_path in module.params['files'].items():
            try:
                source_file = open(source_path)
                module.params['files'][dest_path] = source_file.read()
            except IOError as e:
                raise e
    except IOError as e:
        raise e

    bootargs = [module.params['name'], image_id, flavor_id]
    bootkwargs = {
                'nics' : module.params['nics'],
                'files' : module.params['files'],
```
##### Actual Results:

option not present

**Comment by mpdehaan** [comment]
Hi,

This seems more to be a feature request than a new module pull request, so I'm going to edit the descriptions above.

If you are intending to submit code, please do submit a pull request as opposed to code in the comment description.

The ansible-devel mailing list would be a good place to discuss possible code additions.

Thanks!

**Comment by paolo-de-rosa** [comment]
Ok thanks.
I'm sorry for the confusion did

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
