### ISSUE TITLE
empty with_items and authorized_key module should be skipped (edit: should raise error on empty string)

### ISSUE THREAD

**Issue by jensdepuydt** [ansible/ansible#8593]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.6.6
##### Environment:

$ cat /etc/*release
CentOS release 6.5 (Final)
$ uname -r
2.6.32-431.23.3.el6.x86_64
##### Summary:

Having an empty list in combination with the authorized_key module and with_items still executes the action.
##### Steps To Reproduce:

The following causes an error-message:

variable definition in inventory (host_vars):
dmz_user_allowed:
- jendep
- test1

dmz_user_disabled:

playbook role-contents:
- debug: var=dmz_user_disabled
- name: remove public-keys from authorized_keys for disabled users
  action:  authorized_key user={{ item }}
           key="{{ lookup('file', 'pubkey/' + item) }}"
           manage_dir=yes
           state=absent
  with_items: dmz_user_disabled

output:
TASK: [dmz-auth | debug var=dmz_user_disabled] ********************************
ok: [testvm102] => {
    "dmz_user_disabled": ""
}

TASK: [dmz-auth | remove public-keys from authorized_keys for disabled users] ***
failed: [testvm102] => {"failed": true, "item": ""}
msg: Failed to lookup user : 'getpwnam(): name not found: '

The execution of the authorized_key statement should be completely skipped because the list of items is empty
##### Expected Results:

Skip the task
##### Actual Results:

The taks is executed with an empty string
##### Temporary workaround:
- name: remove public-keys from authorized_keys for disabled users
  action:  authorized_key user={{ item }}
           key="{{ lookup('file', 'pubkey/' + item) }}"
           manage_dir=yes
           state=absent
  with_items: dmz_user_disabled
  when: not item == ""

**Comment by mpdehaan** [comment]
Ok so the value here is an empty string, IMHO, iterating against an empty string should produce an error message as well, and not an empty list.

I would, in the interim, define your value like:

dmz_users_disabled: []

And then it will be iterating over the empty list.

Thanks!

**Comment by jensdepuydt** [comment]
Thanks for the information (and the fantastic product). 
Specifiyng dmz_users_disabled: [] indeed does the trick.

I can also add as extra information that this behaviour has nothing to do with the authorized_key module since I can simulate the "issue" with a simple debug as well.

The following playbook-entry:
- name: test loop
  action: debug var={{ item }}
  with_items: dmz_user_disabled

with variable:
dmz_users_disabled:

causes:
TASK: [dmz-auth | test loop] **************************************************
ok: [testvm102] => {
    "": "()",
    "item": ""
}

with variable:
dmz_users_disabled: []

causes:
TASK: [dmz-auth | test loop] **************************************************
skipping: [testvm102]

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# cat 8593.yml 
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    foo: ""
  tasks:
  - debug: var=item
    with_items: "{{foo}}"
  - debug: var=item
    with_items: ""
  - debug: var=item
    with_items:
# ansible-playbook -vv 8593.yml 
ERROR! you must specify a value when using with_items
The error appears to have been in '/root/testing/8593.yml': line 13, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  - debug: var=item
    ^ here
# after commenting out the last debug task
TASK [debug var=item] ***********************************************************
{'verbose_always': True, u'item': u''}
ok: [localhost] => {"msg": "All items completed", "changed": false, "results": [{"verbose_always": true, "item": ""}]}
TASK [debug var=item] ***********************************************************
{'verbose_always': True, u'item': u''}
ok: [localhost] => {"msg": "All items completed", "changed": false, "results": [{"verbose_always": true, "item": ""}]}
</pre>

As you can see, an empty value there is no longer valid. Unfortunately the way the templating engine works, None's are converted to empty strings before the lookup plugins see them, so preventing an empty variable from being used is not possible (as shown in the second output, after removing the last debug statement).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jhawkesworth** [comment]
Just curious, what if the with items was an empty list?  I sometimes use
empty lists when I know items are going to be needed in a list at a later
date.
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    my_empty_list: []
  tasks:
  - debug: var=item
    with_items: my_empty_list

**Comment by jimi-c** [comment]
With an empty list, it should not execute any items.
