### ISSUE TITLE
Git submodule does not show the error message

### ISSUE THREAD

**Issue by abrahammartin** [ansible/ansible#8596]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

I had a wrong permission in one of the files inside my .git folder but the git submodule didn't show the error message, only a very generic "msg: Failed to download remote objects and refs". I believe that the git submodule should show the error message that git is showing, so you do not have to log in and execute the command by yourself to check the error and see what happened.
##### Steps To Reproduce:

Just change the permissions of some files inside the .git to some that the ansible user cannot read/write
##### Expected Results:

The actual error
##### Actual Results:

"msg: Failed to download remote objects and refs"

**Comment by mpdehaan** [comment]
Can you please show the line you are using from the playbook task entry?

Thanks!

**Comment by abrahammartin** [comment]
Sure, line 80 in https://git.csx.cam.ac.uk/x/ucs/u/mcv21/isg_ansible.git/blob/HEAD:/roles/mwsserver/tasks/main.yml

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
