### ISSUE TITLE
GovCloud not supported in ec2_ami module

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#8604]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

Ubuntu 14.04
##### Summary:

ec2_ami does not work in AWS GovCloud
##### Steps To Reproduce:

Attempt to use ec2_ami within in GovCloud to register or deregister an ami.

Sample:

```
     - name: Register New AMI
       ec2_ami: instance_id={{ ansible_ec2_instance_id }} no_reboot=yes description="Latest {{ ansible_distribution }} {{ ansible_distribution_version }} built on {{ ansible_date_time.date }}" wait=yes region=us-gov-west-1 name="{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_date_time.date }}"
       register: newAMI
```
##### Expected Results:

```
TASK: [Register New AMI] ******************************************************
changed: [<ip_address>] => {"changed": true}
```
##### Actual Results:

```
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: us-gov-west-1
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
