### ISSUE TITLE
Blank line printed in j2 template even though test should prevent it

### ISSUE THREAD

**Issue by seeafish** [ansible/ansible#8611]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Running from: Mac OS X 10.9
Deploying to: Centos 6/7 (and other Linux distros, but my testing is limited to Centos at the moment)
##### Summary:

Ansible seems to write out an empty line on a j2 template, if there's anything in it at all, including j2 code and Ansible variables only.
##### Steps To Reproduce:

Create vars file with an empty hash:

```
hash:
#  - { key: value }
```

(note the commented out of entry, which may or may not be in the hash, depending on use)

Create a j2 template with a test to see if it's iterable:

```
{% if hash is iterable %}
{% for item in hash %}
{{ item.key }}
{% endfor %}
{% endif %}
```
##### Expected Results:

Since hash isn't iterable, I would expect an **empty file** to be created on the target system.
##### Actual Results:

A file with a **single blank line** is created, which affects how some programs read that file.
##### Additional information

Unless I am misunderstanding something, if the hash is empty, the test 'is iterable' should return false, and my template should have no lines in it whatsoever.
Conversely, if I just have a completely empty j2 file (with no j2 code in it) that deploys an empty file, as expected.

**Comment by seeafish** [comment]
Apologies, closed this by mistake. Reopening!

**Comment by mpdehaan** [comment]
Can you perhaps upload a github repo that reproduces this problem?

**Comment by seeafish** [comment]
Sure, here's a mock repo that you can clone and run to see the output:
https://github.com/seeafish/ansible_issue_8611

On the remote site, when the vars thehash has commented out values, I see this when I cat the file:

``` bash
cat config.conf
<blank line>
file config.conf
config.conf: very short file (no magic)
```

If the j2 template has no j2 code in it whatsoever, that same cat looks like this

``` bash
cat config.conf
file config.conf
config.conf: empty
```

So there's clearly a difference between the two.

Thanks.

**Comment by shirou** [comment]
I think you have a line break at the end of config.conf.j2.
Deleting it makes the file empty on my environment (ansible 1.7.1)

**Comment by seeafish** [comment]
@shirou I have upgraded my ansible to version 1.7.1 and checked the file in vim to ensure no whitespace is at the end of the file; the issue persists.
Can you by any chance run it and do the cat and file commands and post output?
Thanks.

**Comment by shirou** [comment]
```
% cat roles/ansible_issue_8611/templates/config.conf.j2
{% if thehash is iterable %}
{% for k in thehash %}
{{ k.somekey }}
{% endfor %}
{% endif %}%
```

% is my prompt, so the last % seems no line break at end of config.conf.j2.

```
% cat /tmp/config.conf
% file /tmp/config.conf
/tmp/config.conf: empty
```

Here is git diff

```
diff --git a/templates/config.conf.j2 b/templates/config.conf.j2
index 6ffd295..977f170 100644
--- a/templates/config.conf.j2
+++ b/templates/config.conf.j2
@@ -2,4 +2,4 @@
 {% for k in thehash %}
 {{ k.somekey }}
 {% endfor %}
-{% endif %}
+{% endif %}
\ No newline at end of file
```

I use Emacs and with my small vim skill, I could not delete the last line in vim. perhaps, use perl or sed? see  http://stackoverflow.com/questions/1654021/how-can-i-delete-a-newline-if-it-is-the-last-character-in-a-file
 and `perl -pi -e 's/\n$//g if(eof)' config.conf.j2` works for me.

**Comment by eljrax** [comment]
Hi,

I'm seeing this behaviour as well. I end up with a newline. 

```
==> $ cat roles/ansible_issue_8611/templates/config.conf.j2 
{% if thehash is iterable %}
{% for k in thehash %}
{{ k.somekey }}
{% endfor %}
{% endif %}
==> $ wc -l roles/ansible_issue_8611/templates/config.conf.j2 
5 roles/ansible_issue_8611/templates/config.conf.j2
==> $ 
```

When ran, this is the resulting file:

```
==> $ cat /tmp/config.conf 

==> $ wc -l /tmp/config.conf 
1 /tmp/config.conf
==> $ 
```

I would have expected a completely empty file though.

**Comment by shirou** [comment]
```
% wc -l roles/ansible_issue_8611/templates/config.conf.j2
       4 roles/ansible_issue_8611/templates/config.conf.j2
```

Because there are only 4 line breaks.

Note: the last line is not a "Line" in POSIX (see http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap03.html#tag_03_205) since not terminating `<newline>`.

**Comment by seeafish** [comment]
Thanks for the comments @shirou however, I am observing this to be an issue with many editors. Wouldn't that warrant a fix in ansible rather than applying workarounds using sed or perl every time a j2 file is edited?
Using your perl one-liner, I also see 4 lines (although it shows 5 without running that) and then, yes, it deploys an empty file; I get your point, just not sure the fix lies with the end-user, as popular editors (vim, atom, sublime, etc) supposedly terminate every line so that they are POSIX lines. For that reason, I believe ansible should handle this gracefully, since it should work without additional tweaks before a playbook is run.
Thanks.

**Comment by shirou** [comment]
Emacs can :sunglasses:

It seems automatically deciding remove newline or not is so hard. If you really want to get an empty file, how about using file module state=touch with `when` ?

**Comment by seeafish** [comment]
I will try that and report back.

**Comment by seeafish** [comment]
I put in a place a workaround to check for the iterable state in the task using `when`, and moving my conditionals around a little bit.
I would like to reiterate (no pun intended!) that this is a workaround. It would be nice if these phantom newlines that are seemingly generated by most popular editors were handled.
Or perhaps mine is an edge case, as I'm deploying lsyncd, which reads an empty line as an item, where most binaries would probably just ignore the,

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
