### ISSUE TITLE
host/group patterns match substrings instead of start of hosts 1.7

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#8614]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

RHEL6 host
##### Summary:

host patterns seem to match more than they should. A pattern of 'foo*' matches foobar and also thisisfoobar, where it would have only matched foobar before
##### Steps To Reproduce:

Given an inventory with: 

foobar
barfoobar

ansible -i inventory --list-hosts foo*

you get both hosts. 
##### Expected Results:

Should only match the one host that starts with the pattern, not simply contains it. 
##### Actual Results:

All hosts with a substring of the pattern are matched.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
