### ISSUE TITLE
 Inconsistent booleanification of string "false"

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#8629]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel b4476c238f) last updated 2014/08/14 17:52:06 (GMT +000)
##### Environment:

AWS Linux and CentOS 6.5
##### Summary:

If you have the a variable `foo` with the string value of "false" in a variable using `when: foo` and `when: not foo` always evaluate to the same thing, false.
##### Steps To Reproduce:

Create a playbook `test.yml` that looks like this:

``` yml

---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - set_fact: foo=false

  - command: ls /
    when: foo

  - command: ls /
    when: not foo
```

And run it like `ansible-playbook -i '127.0.0.1,' test.yml`
##### Expected Results:

I understand that `set_fact: foo=false` will set foo to the string "false" which isn't the same as a boolean `false`. But only one of those 2 command tasks should be skipped. If the string "false" evaluates to boolean `true` then it should be just the 2nd one that is skipped.
##### Actual Results:

Both of those command tasks are skipped:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [set_fact foo=false] **************************************************** 
ok: [127.0.0.1]

TASK: [command ls /] ********************************************************** 
skipping: [127.0.0.1]

TASK: [command ls /] ********************************************************** 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0 
```

**Comment by mpdehaan** [comment]
Thanks!!!

**Comment by jimi-c** [comment]
As a work-around, using `foo|bool` make this work as expected.

**Comment by mpdehaan** [comment]
Part of the problem above is set_fact is used in string form.

Switching this to:

```
set_fact:
    foo: False
```

Will set it to a proper boolean.

Though the real question is why both values are true.

The first one is a non-empty string, which is True

The second one is the same as:

not "false"

Since "false" is a true value, this later one should be expected to be true.

**Comment by mpeters** [comment]
I think you mean "this later one should _not_ be expected to be true."

**Comment by sivel** [comment]
The problem seems to be coming from:

https://github.com/ansible/ansible/blob/268e72318f5aac74c07b6be24afeb2684568aacd/lib/ansible/utils/__init__.py#L252-L253

It early replaces "foo" with "false" so that the statement looks like:

```
{% if false %} True {% else %} False {% endif %}
```

`false` unquoted, no matter the case, in jinja2 evaluates as False.

Commenting out those 2 lines, gives us more of what we expect.  I have not been able to successfully track down the origin of those 2 lines as of yet.

**Comment by sivel** [comment]
It looks like that `conditional = inject[conditional]` line was added in 62b39d3de535370ae7e98a3fbdcd1799819523ee

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
