### ISSUE TITLE
GIT module should not checkout the repository when update=no

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#8630]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

Hello!

Currently the GIT module will perform a checkout if update=no.
This is unexpected, and there is no way to just get information about the repository.

I'd like to make a deploy process similar to chef's deploy_revision, which creates a new directory for each checked out revision, and symlinks the current one.

In order to do this, I would need to fetch the current HEAD's sha, to create that directory, and clone the repo in there, checking out the correct commit sha.

I tried doing this so, but the /current will contain a cloned repository after the first checkout:

```

---
# Input Variables:
# deploy_dir: Directory to deploy to
# deploy_revision: Revision (branch) to deploy
# deploy_repository: Repository link (usually git://.... )

- debug: var={{item}}
  with_items:
    - deploy_dir
    - deploy_revision
    - deploy_repository


- name: get current HEAD sha
  git: repo={{deploy_repository}}
       key_file=~/.ssh/insecure-key
       accept_hostkey=yes
       update=no
       dest={{deploy_dir}}/current
       version={{deploy_revision}}
  register: repo_state
- name: create deploy directory
  file: name={{ deploy_dir | mandatory }}/{{repo_state.after}} state=directory
  register: deploy_directory_presence
- name: checkout git repository
  git: repo={{ deploy_repository }}
       key_file=~/.ssh/insecure-key
       dest={{ deploy_dir }}/{{repo_state.after}}
       version={{repo_state.after}}
       force=yes
  when: repo_state | changed
  register: git_checkout
```
##### Steps To Reproduce:

Create a playbook with a git checkout set update=no, and the dest to a non-existing directory
##### Expected Results:

The directory is not created, and before=null, after=current HEAD sha
##### Actual Results:

A clone is performed

**Comment by mpdehaan** [comment]
We can investigate this one, though I should point out there
are some good galaxy roles that do things like this you may wish to investigate such as:

https://galaxy.ansible.com/list#/roles/732

We're also looking at making something like this into a core module.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by abadger** [comment]
After people started using ansible with this change, it turned out that getting a clone but not updating further is desired by a great number of people.  I'm going to be working on something that reverts the behaviour of update=no not doing an initial clone so reopening this ticket.  (See https://github.com/ansible/ansible-modules-core/issues/426 for more information)

Not sure how to enable this use case yet -- maybe a new parameter to the git module that tells it only to gather information from a remote?

**Comment by cliffano** [comment]
+1 on new parameter.

I think it's better to support backward compatibility because lots of Ansible roles out there already use update=no with the intention to clone once.

**Comment by abadger** [comment]
Okay, in ansible-modules-core devel this has been changed so that a new clone parameter controls this: https://github.com/ansible/ansible-modules-core/commit/b650ad1671a0f0cd5f2f139407bc793b6f1fd6a3

Setting clone=no should do what was requested in this ticket.  clone=no and update=no together may cover cornercases as well (depending on what your actual use case is here). @axos88 feel free to test to make sure this satisfies your needs.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by geerlingguy** [comment]
FYI this is like the 4th time someone has asked me about why their playbooks aren't working in Ansible 1.8.2 when they've worked with 1.5.x, 1.6.x, and 1.7.x without issue... Can we please get a 1.8.3 release to fix this regression (as suggested in https://github.com/ansible/ansible-modules-core/issues/426).
