### ISSUE TITLE
playbook fails to find a library-only role

### ISSUE THREAD

**Issue by yaegashi** [ansible/ansible#8633]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu 14.04

```
Linux ansible 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
##### Summary:

In a playbook, invocation of a role with only library modules causes an error saying "cannot find."
##### Steps To Reproduce:

Create the following files as shown in https://gist.github.com/yaegashi/345c96c913409e21e319:
- hosts
- site.yml
- roles/modules/library/module

Then run:

```
$ ansible-playbook -i hosts site.yml
```
##### Expected Results:

```

PLAY [all] ******************************************************************** 

TASK: [module ] *************************************************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```
##### Actual Results:

```
ERROR: found role at /home/yaegashi/ansible/roles/modules, but cannot find /home/yaegashi/ansible/roles/modules/tasks/main or /home/yaegashi/ansible/roles/modules/handlers/main or /home/yaegashi/ansible/roles/modules/vars/main or /home/yaegashi/ansible/roles/modules/defaults/main or /home/yaegashi/ansible/roles/modules/meta/main or /home/yaegashi/ansible/roles/modules/library
```

**Comment by mpdehaan** [comment]
Hi @yaegashi,

Pretty sure we did this the other day but can double check.

The module only role should be looking for the modules in /home/yaegashi/ansible/roles/modules/library which is one of the paths listed in the error message.

Can we see your playbook yml that you used to test this one and perhaps the permissions on the library directory?

**Comment by yaegashi** [comment]
Sure I have no problem in my playbook.  I think the problem is that ansible-playbook actually checks `roles/modules/library/` _is_ a regular file and not a directory.  A trivial fix would be like this:

``` diff
diff --git a/lib/ansible/playbook/play.py b/lib/ansible/playbook/play.py
index 38aab2d..bcaab49 100644
--- a/lib/ansible/playbook/play.py
+++ b/lib/ansible/playbook/play.py
@@ -401,7 +401,8 @@ class Play(object):
             library   = utils.path_dwim(self.basedir, os.path.join(role_path, 'library'))

             missing = lambda f: not os.path.isfile(f)
-            if missing(task) and missing(handler) and missing(vars_file) and missing(defaults_file) and missing(meta_file) and missing(library):
+            missing_dir = lambda f: not os.path.isdir(f)
+            if missing(task) and missing(handler) and missing(vars_file) and missing(defaults_file) and missing(meta_file) and missing_dir(library):
                 raise errors.AnsibleError("found role at %s, but cannot find %s or %s or %s or %s or %s or %s" % (role_path, task, handler, vars_file, defaults_file, meta_file, library))

             if isinstance(role, dict):
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
