### ISSUE TITLE
`pip install ansible` attempts to create /usr/share/ansible

### ISSUE THREAD

**Issue by mistydemeo** [ansible/ansible#8634]
##### Issue Type:

Bug report
##### Ansible Version:

1.7.1
##### Environment:

I'm running Mac OS X 10.9.4, with Python 2.7.8 as installed by Homebrew. I was installing ansible 1.7.1 using pip 1.5.6 and setuptools 5.3 and 5.6.

I had previously successfully installed ansible 1.6 using pip, but ansible 1.7 fails the same way.

I have also had reports of this occurring for some users installing ansible under Homebrew (which does a setup.py install, but only from users whose Homebrew prefixes are not /usr/local.
##### Summary:

When attempting to install ansible 1.7.1 via `pip`, ansible attempts to create the directory `/usr/share/ansible` and the install fails when it doesn't have permissions to do so:

```
running install_data

creating /usr/share/ansible

error: could not create '/usr/share/ansible': Permission denied
```

The Python I'm installing it with doesn't exist in `/usr` and is not owned/operated by a root account or an account that has permissions to create any directories within `/usr`.

This happens regardless of whether I'm upgrading ansible from a previous version.
##### Steps To Reproduce:

`pip install ansible`
##### Expected Results:

Ansible installation is within the prefix that Python itself was installed, and does not require elevated privileges when `pip install` does not normally.
##### Actual Results:

Ansible cannot install if it can't install some contents into `/usr`.

**Comment by thomasvnoort** [comment]
I've noticed the same behaviour and solved it for now by doing:

```
export ANSIBLE_LIBRARY=/usr/local/share/ansible; pip install ansible
```

**Comment by mpdehaan** [comment]
Hi!

Homebrew contains a patch it shouldn't contain since it differs from upstream packaging, but that's beside the point.   It shouldn't do that, i.e. we want upstream to match all the distributions.  (We'd definitely consider a pull request for it).

A few options for you that will get you going:
- install with sudo even though you aren't going to use it with sudo.
- from a checkout, run hacking/env-setup and run from source, no install is required if the development parameters are set.
- install with "pip install -e" in an editable environment using the development branch (see https://github.com/ansible/ansible/pull/8367).  The same thing happens as with hacking/env-setup more or less.

Hope this helps!   If you still have problems you can stop by ansible-devel to suggest possible changes or ansible-project if you're stuck with the env-setup process.

Thanks!
