### ISSUE TITLE
copy module will change permissions of destination files even though check_mode is set

### ISSUE THREAD

**Issue by jfchevrette** [ansible/ansible#8639]
##### Issue Type:

Bug report
##### Ansible Version:

1.7.1
##### Environment:

OSX client, CentOS/RHEL server
##### Summary:

The copy module will change destination files permissions even though --check (check_mode) is set
##### Steps To Reproduce:

https://gist.github.com/jfchevrette/d8e18c104dc4dff0b138
- Run once to copy files to destination
- Change destination files permissions to something other than 0644
- Re-run with --check
- Observe that the playbook reports "changed" and the permissions have been changed on the target
##### Expected Results:

Should only report changed but NOT actually change permissions
##### Actual Results:

File permissions are set even though --check is used

**Comment by akuznecov** [comment]
tried with Ansible 1.2.1, 1.4.0, 1.6.0, 1.6.10, 1.7.0, 1.7.1
Same behavior with --check with all of them

**Comment by jfchevrette** [comment]
The code will always get to this point which will set permissions. This part of the code doesn't support check_mode and module.set_fs_attributes_if_different will always run if state = file and prev_state = file

https://github.com/ansible/ansible/blob/devel/library/files/file#L204

**Comment by jfchevrette** [comment]
Ran with ANSIBLE_KEEP_REMOTE_FILES and noticed the resulting file module on the host has

MODULE_ARGS = 'dest=/tmp/testfile1 mode=0644 original_basename=testfile src=testfile'

It's missing CHECKMODE=True. Could it be that the copy module isn't passing the info along to the file module?

Then there seems to be no way to actually check if permissions are different. That would need to be implemented in module_utils/basic.py IMO

Thoughts?

**Comment by jimi-c** [comment]
@jfchevrette yes, I believe that would be the issue. Each of the set_*_if_different() calls tests against self.check_mode, so the above line you pointed out isn't the issue. It would be an issue though, if checkmode isn't enabled. I'll look into this now.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
