### ISSUE TITLE
TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by stefanvangastel** [ansible/ansible#8644]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04 LTS 
Vagrant 1.6.3
Python 2.7.6
##### Summary:

Error is generated using Ansible 1.7 and the vars_prompt feature. 

I did not have the issue using Ansible 1.3 but upgraded tot the latest version because I needed the debconf feature.

After a nice google-quest I found this temp solution that fixed the error: 

```
export PYTHONIOENCODING='utf-8'
```

The sys.stdout.encoding variable seemd to be a None value in /usr/lib/pymodules/python2.7/ansible/callbacks.py
##### Steps To Reproduce:

Create a playbook using vars_prompt like this:

```

---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  sudo: yes

  vars_prompt:
  - name: "cakephp_version"
    prompt: "\n\nWhat version of CakePHP do you want to deploy? (2 or 3)?"
    default: "2"
    private: no

  roles:
    - system
```
##### Expected Results:

```
What version of CakePHP do you want to deploy? (2 or 3)? [2]: 
```
##### Actual Results:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 305, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 65, in __init__
    self.vars             = self._get_vars()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/play.py", line 672, in _get_vars
    vname, private, prompt, encrypt, confirm, salt_size, salt, default
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 665, in on_vars_prompt
    result = prompt(msg, private)
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 651, in prompt
    msg = prompt.encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
