### ISSUE TITLE
Potential for hosts to be configured out of order when using "serial: 1"

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#8646]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.10, 1.7.1, and Devel
##### Environment:

N/A
##### Summary:

See https://groups.google.com/forum/#!searchin/ansible-project/serial$20order/ansible-project/CFagwWg7GxA/Z_f0Mu_AM68J  ... hosts in a playbook are running out of order when set with "serial: 1"
##### Steps To Reproduce:

Use INI inventory and set serial: 1 in a simple play
##### Expected Results:

facts and tasks happen in inventory 
order
##### Actual Results:

facts gather in order, tasks happen in reverse order.   I tested this with "-f 1" and this only applies to serial execution.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
