### ISSUE TITLE
Password lookup should write file with owner-only permissions

### ISSUE THREAD

**Issue by ToBeReplaced** [ansible/ansible#8652]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

`lookup('password', '/some/file/path')` writes a file with default permissions (`0664 -rw-rw-r--` on my machine). A password file should be have permissions `0600 -rw------`. This is a security concern.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
We agree this should be set.

In the meantime, you can set the default ACLs for the directory:

setfacl -d -m group:rwx /path/to/your/dir

My general thought is we should deprecate and undocument the password lookup anyway (it's a bit of a hck), though the umask here does need to be adjusted.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
