### ISSUE TITLE
Can't create amazon elasticache with vpc security groups ids

### ISSUE THREAD

**Issue by orkaplan** [ansible/ansible#8655]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

ansible 1.6.6
##### Environment:

N/A
##### Summary:

On amazon elastic cache module (library/cloud/elasticache) in order to use a security group id of vpc it is required to add a support to cache_subnet_group_name argument (boto throws error 'Cache subnet group name must be specified along with security group IDs.')
##### Steps To Reproduce:

create a simple playbook that tries to create an elasticache like the next one:

<pre>
- name: Create an elastic cache cluster
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    num_nodes: 1
  tasks:
    - name: launch elasticache cluster
      local_action:
        module: elasticache
        name: "redis-test"
        state: present
        engine: redis
        cache_engine_version: 2.8.6
        node_type: cache.m3.large
        num_nodes: "{{num_nodes}}"
        cache_port: 6379
        security_group_ids:
          - {{vpc_security_group_id e.g. sg-12345678}}
        cache_subnet_group_name: vpc-name
        cache_security_groups: [] # must be empty otherwise boto throws error
        region: "us-east-1"
        zone: "us-east-1b"
</pre>
##### Expected Results:

a new redis elasticache should be created with success
##### Actual Results:

boto throws error - Cache subnet group name must be specified along with security group IDs.
See the following output:

PLAY [Create an elastic cache cluster] ****************************************

TASK: [launch elasticache cluster] ********************************************
failed: [localhost] => {"failed": true}
msg: Cache subnet group name must be specified along with security group IDs.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/ork/launchelasticache.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1

The connected pullrequest is #8654

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us, however we are going to close this ticket for the following reasons:
- The PR you reference above has not been merged in yet, so any issues related to it should be brought up there before it is merged.
- I tested the above playbook, and was unable to replicate the issue while using the referenced PR. I created a new cache subnet group via the AWS management interface, and using that subnet name was able to create the elasticache instance with no issues. I believe the issue you had above may be caused by specifying the VPC subnet name, rather than the cache name.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by orkaplan** [comment]
Hi!
Nice to hear from you :+1: 
I know that this is misordered, but the pull request you are reffering is actually the fix to the issue (which I made), I reported the issue and the pull request on different items, should I join them?

**Comment by jimi-c** [comment]
@orkaplan ahh, in that case don't worry about it. Since we have the PR in queue and I've already closed this, we'll just keep track of it in that PR. Thanks!
