### ISSUE TITLE
Docker module does not support private docker image repositories with a non-standard http port

### ISSUE THREAD

**Issue by kormoc** [ansible/ansible#8658]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

Private docker image repositories are often run with non-standard http ports ( 5000 is often used and is the default for https://github.com/docker/docker-registry ). When pushing, this creates images named `hostname:port/name`. When attempting to use this, Ansible splits on the `:` and uses `hostname` as the repository image name and `port/name` as the tag.

Using `hostname:port/name:tag` does not help, as Ansible splits on the first `:`.
##### Steps To Reproduce:

Attempt to use an image tagged with a : in the name
##### Expected Results:

Correctly find the image file
##### Actual Results:

Throws

```
docker.errors.InvalidRepository: Invalid repository name (hostname)
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
