### ISSUE TITLE
Using ec2_vpc without specifying the (optional) route parameter leads to deleting the vpc routes !

### ISSUE THREAD

**Issue by crashdump** [ansible/ansible#8666]
##### Issue Type:

Bug Report
##### Ansible Version:

It use to work well on 1.6. This appeared with a fairly recent develop commit (600a465).
##### Environment:

MacOS 10.10
##### Summary:

I created a VPC (see the configuration below, I didn't specify any routes) then added a route manually in the Aws console, re-ran my playbook and I received a : "The routeTable 'rtb-aaaaaaa' has dependencies and cannot be deleted."

Is that a normal behavior ? 

```
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: Unable to delete old route table rtb-e2e11b87, error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>DependencyViolation</Code><Message>The routeTable 'rtb-e2e11b87' has dependencies and cannot be deleted.</Message></Error></Errors><RequestID>f16f96d6-7103-4da6-a9c0-d378e3d70cd0</RequestID></Response>

FATAL: all hosts have already failed -- aborting
```

```
  - name: Create the VPC
    local_action:
      module: ec2_vpc
      state: present
      cidr_block: "10.10.0.0/16"
      internet_gateway: true
      subnets:
        - cidr: "10.10.10.0/24"
          az: "eu-west-1c"
        - cidr: "10.10.20.0/24"
          az: "eu-west-1c"
      wait: yes
    register: vpc
```
##### Steps To Reproduce:

See summary
##### Expected Results:

It use to return the vpc object
##### Actual Results:

It tries to delete my routes !

**Comment by mpdehaan** [comment]
The above commit should have no bearing on the VPC module, though we can and definitely will investigate.

**Comment by jimi-c** [comment]
Hi @crashdump, I have created the above commit, which I believe should resolve this issue. This patch changes the behavior of the module to not modify the subnets or route tables if those params are left out. If this patch resolves the issue for you, I'll get it merged in ASAP.

Thanks!

**Comment by jimi-c** [comment]
Just noticed another small bug as I was testing this more myself, which was that any changes to the route_tables were not correctly reflected by setting `changed = True`. That is corrected now in this commit as well.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
