### ISSUE TITLE
service module: Reports no errors even when enable has failed (systemctl)

### ISSUE THREAD

**Issue by lukejahnke** [ansible/ansible#8667]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
Also read devel branch source.
##### Environment:

Fedora release 20 (Heisenbug)
##### Summary:

The "enable" option can fail for the service module without any errors being reported to the user.

The example I encountered is that Fedora 20 has moved from mysqld to mariadb, and as a result of this move (potentially a bug on Fedora's end) the enable command only works for mariadb and not mysqld (start/stop/etc still work fine for mysqld).

```
# systemctl enable mysqld.service
Failed to issue method call: No such file or directory
# echo $?
1
```

I believe this issue is either a result of the call to "service_enable" method not checking what was returned (https://github.com/ansible/ansible/blob/3bead39c752fdea8922814a93df5bb66c0a852dd/library/system/service#L1182) or "service_enable" itself not validating what was returned by execute_command (https://github.com/ansible/ansible/blob/3bead39c752fdea8922814a93df5bb66c0a852dd/library/system/service#L717).

I'm not sure which is the suitable fix, thus no pull request. Also, if you see the systemctl command output above, we do have a status code to distinguish the error.
##### Steps To Reproduce:

Running a playbook against a Fedora 20 machine with the "mysql-server" package (really MariaDB) installed with the following lines inside:
      - name: mysql - enable and start
        service: name=mysqld enabled=yes state=started
##### Expected Results:

Ansible to return an error to the user.
##### Actual Results:

Ansible returns "Ok" and service not enabled.

**Comment by abadger** [comment]
This should be fixed in 6943ec11a5b7a3fc684cea944a430c6aaa7d13aa

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
