### ISSUE TITLE
allow_duplicates: yes does not appear to work with dependent role handlers

### ISSUE THREAD

**Issue by asmartin** [ansible/ansible#8684]
##### Summary: allow_duplicates: yes does not appear to work with handlers

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

I have 3 roles:

roles/apache2/meta/main.yml:

```
allow_duplicates: yes
```

roles/apache2-php/meta/main.yml:

```
allow_duplicates: yes
dependencies:
  - { role: apache2 }
```

roles/apache2-ssl/meta/main.yml:

```
allow_duplicates: yes 
dependencies:
  - { role: apache2-php, when: include_php == True }
  - { role: apache2, when: include_php == False }
```

I would like to be able to use the apache2-ssl role in a playbook and have it call the apache2-php and apache2 dependent roles. This works for the most part, except with handlers in the base apache2 role. Even with allow_duplicates: yes everywhere, when I call the apache2-ssl role with include_php == False, the "reload apache" handler still gets skipped:

excerpt from roles/apache2/tasks/main.yml:

```
 - name: copy apache configuration (12.04)
   template: src=000-default.j2 dest=/etc/apache2/sites-enabled/000-default
   when: ansible_distribution_version == "12.04"
   notify: reload apache2
```

excerpt from roles/apache2/handlers/main.yml:

```
  - name: reload apache2
    service: name=apache2 state=reloaded enabled=true
```

The handler is NOTIFIED, but skipped:

```
NOTIFIED: [apache2 | reload apache2] ******************************************
skipping: [apachetest]
```

I think this occurs because the first dependent role, apache2-php, is skipped because include_php is False. It then marks all tasks and handlers in apache2-php and apache2 as skipped, and then when it goes to apache2 a second time (when it hits the second dependent role), it is already marked as skipped and so the handler doesn't execute. Any ideas on what is going on here, and how to fix it?
##### Expected Results:

I would expect that the "reload apache2" handler is both NOTIFIED and changed, rather than NOTIFIED and skipped.
##### Actual Results:

The handler is NOTIFIED, but skipped:

```
NOTIFIED: [apache2 | reload apache2] ******************************************
skipping: [apachetest]
```

This seems to be caused by the first dependent role in roles/apache2-ssl/meta/main.yml, which calls the apache2 role and marks the "reload apache2" handler as skipped. Then, when the second dependent role in roles/apache2-ssl/meta/main.yml is called (and not skipped), the handler is not re-evaluated for running so it is skipped instead of being run as expected.

**Comment by mpdehaan** [comment]
What is a recursive handler?

**Comment by asmartin** [comment]
You're right, this isn't actually recursion (since the apache2 role is called as two separate roles). I changed the title and the text of the issue to remove this confusion

**Comment by asmartin** [comment]
Are there any updates on the status of this bug? As a workaround, I added a no-op task to apache2-ssl which calls a copy of the `reload apache2` handler that I placed in `apache2-ssl/handlers/main.yml`. This forces the apache2 config to be reloaded every time the playbook is run - definitely not ideal but is the only solution I can think of until this bug is fixed.

Thanks!

**Comment by jamesdmorgan** [comment]
+1 this is causing me issues as well

**Comment by usernamenumber** [comment]
Ditto. +1

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [apache2 : apache2 : debug msg=in apache2 tasks] ***************************
ok: [localhost] => {
    "msg": "in apache2 tasks", 
    "changed": false
}
TASK [apache2-php : apache2-php : debug msg=in apache2-php tasks] ***************
skipping: [localhost] => {"skipped": true, "changed": false, "skip_reason": "Conditional check failed"}
TASK [apache2 : apache2 : debug msg=in apache2 tasks] ***************************
ok: [localhost] => {
    "msg": "in apache2 tasks", 
    "changed": false
}
TASK [apache2-ssl : apache2-ssl : debug msg=in apache2-ssl tasks] ***************
ok: [localhost] => {
    "msg": "in apache2-ssl tasks", 
    "changed": false
}
RUNNING HANDLER [apache2 : reload apache2] **************************************
ok: [localhost] => {
    "msg": "apache reloaded", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by tamsky** [comment]
My ansiblle: 1.9.6

I encountered at least a similar bug where the second play in a playbook could no notify the handlers that had already run in a previous play for the same role (`hosts:` differed).

At the playbook level I found two workarounds:
1. use different `tags:` on the roles with handlers -- this allows each run to have "different" handlers.
2. include a `handler: - include: my_role/handlers/main.yml` at the play level, which explicitly re-loads the handlers into the play.
