### ISSUE TITLE
Allow passing variables to inventory (executable file) file

### ISSUE THREAD

**Issue by sulochan** [ansible/ansible#8699]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5
##### Environment:

Debian 6
##### Summary:

inventory file can be executable, however, there is no means to pass an argument to an executable inventory generation file. It would be very handy if we could allow passing args to this like so:

$ ansible-playbook -i gen_inventory.py myplaybook.yaml --inv-args "arg1=bla arg2=bla"

such that those arguments can be passed to Inventory object and in turn passed to InventoryScript to allow calling the gen_inventory.py file for example with the given arguments, just like extra-vars to playbooks.

This helps using such inventory generation file through ansible python api, rather than sticking with cli, making automation around ansible using the python api much easier.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, for the following reason:
- Our long-standing policy for inventory scripts is that they either use an INI file for configuration, or that they use environment variables for parameters. The reason we enforce this more generic interface is due to the wide range of parameters that any given inventory script may take. A very good example of this is the ec2.py inventory script, which has served as the template for several other inventory scripts we also include in the examples/ directory of the repository.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always neccessary.

Thank you once again for this and your interest in Ansible!
