### ISSUE TITLE
More than one action statement of the same type gets ignored

### ISSUE THREAD

**Issue by ggeldenhuis** [ansible/ansible#87]
- name: Stop 389 services
  action: service name=dirsrv-admin state=stopped
  action: service name=dirsrv state=stopped

This does not work as expected to get it to work you have to:
- name: Stop 389 services
  action: service name=dirsrv-admin state=stopped
- name: Stop 389 services2
  action: service name=dirsrv state=stopped

**Comment by mpdehaan** [comment]
per mailing list discussion 

```
- name: foo
  action: bar
- action: bar
```

is ok

you can't do:

```
 - action:
   action:
```

because that's just overriding the same hash key.

If that doesn't describe the problem and there is still an issue let me know.

TIP:  github thinks everything is markdown so indent four spaces on thigns you don't want to reformat.  (Yeah, it's annoying)

Thanks!
