### ISSUE TITLE
Variables passed in role dependencies are not fully templated

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#8717]
##### Ansible Version:

  ansible 1.8 (devel 8e0af04c3b) last updated 2014/08/22 11:00:57 (GMT +200)
  ansible 1.7.1
##### Summary:

When passing variables through role dependencies they are not templated correctly.
##### Steps To Reproduce:

The whole code of a failing example:

```
### ./inv
hostA ansible_connection=local

[some_group]
hostA
hostB


### ./playbook.yml
- hosts: hostA
  gather_facts: no
  vars:
    members: '{{ groups.some_group }}'
  roles:
    - roleA


### ./roles/roleB/tasks/main.yml
- debug: var=members
- debug: var=complex_variable
- set_fact: { members: '{{ members }}' }
- debug: var=members
- debug: var=complex_variable


### ./roles/roleA/meta/main.yml
dependencies:
  - role: roleB
    complex_variable:
      blah: '{% for m in members %}{{ m }} {% endfor %}'
```
##### Expected Results:

complex_variable should have value {"blah": "hostA hostB " }
##### Actual Results:

```
PLAY [hostA] ****************************************************************** 

TASK: [roleB | debug var=members] ********************************************* 
ok: [hostA] => {
    "members": [
        "hostA", 
        "hostB"
    ]
}

TASK: [roleB | debug var=complex_variable] ************************************ 
ok: [hostA] => {
    "complex_variable": {
        "blah": "{ {   g r o u p s . s o m e _ g r o u p   } } "
    }
}

TASK: [roleB | set_fact ] ***************************************************** 
ok: [hostA]

TASK: [roleB | debug var=members] ********************************************* 
ok: [hostA] => {
    "members": [
        "hostA", 
        "hostB"
    ]
}

TASK: [roleB | debug var=complex_variable] ************************************ 
ok: [hostA] => {
    "complex_variable": {
        "blah": "{ {   g r o u p s . s o m e _ g r o u p   } } "
    }
}

PLAY RECAP ******************************************************************** 
hostA                      : ok=5    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
Thanks for the report.

I'll admit this one is confusing to read to understand what you are trying to do.

groups is not going to be available at that point in time, though it does look like the software should realize groups is not available and decline to template it, to make it bind later.

I'm not sure the issue has anything to do with role deps just that the detection on things to not template may need to be improved.

What you have is definitely a bit over-complicated for the norm in Ansible though, so I'd probably be interested in seeing if you could step back and eliminate the weird for loop in Jinja2.

It might make sense exploring a more direct real-world use case, as that might make it easier to give organization suggestions.

**Comment by ktosiek** [comment]
Hmm, aren't variables resolved lazily in the rest of Ansible? Why would things passed to roles behave differently?

About the specific use case:
I have a separate role for installing and configuring pacemaker (tool for managing services in HA environment), and I want to have a role for PostgreSQL on pacemaker. So I made a role setting up PostgreSQL, and added the pacemaker role as a dependency with specification of managed resources.
One of the resources needs to be passed a list of nodes that host PostgreSQL instances, which I can generate from group.postgresql by taking first part of inventory name of those hosts, and joining the results with spaces.

This brings us to the loop I used in dependency - I can't push that down into pacemaker role, as that role knows nothing about that particular resource (and IMHO shouldn't).
I hoped the resources list will only be rendered when I use that value, but it seems to be rendered earlier. Is there any good workaround for this?

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [roleB : roleB : debug var=member_groups] **********************************
ok: [hostA] => {
    "member_groups": [
        "hostA", 
        "hostB"
    ], 
    "changed": false
}
TASK [roleB : roleB : debug var=complex_variable] *******************************
ok: [hostA] => {
    "complex_variable": {
        "blah": "hostA hostB "
    }, 
    "changed": false
}
TASK [roleB : roleB : set_fact members=['hostA', 'hostB']] **********************
ok: [hostA] => {"changed": false, "ansible_facts": {"members": ["hostA", "hostB"]}}
TASK [roleB : roleB : debug var=members] ****************************************
ok: [hostA] => {
    "changed": false, 
    "members": [
        "hostA", 
        "hostB"
    ]
}
TASK [roleB : roleB : debug var=complex_variable] *******************************
ok: [hostA] => {
    "complex_variable": {
        "blah": "hostA hostB "
    }, 
    "changed": false
}
PLAY RECAP **********************************************************************
hostA                      : ok=5    changed=0    unreachable=0    failed=0   
</pre>

One caveat here was that the `members` variable had to be renamed due to its use in your `set_fact` call (otherwise a recursive template error is raised, which may be a separate issue in the v2/devel code).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
