### ISSUE TITLE
win_feature: not properly setting 'message' in results

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#8723]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

CentOS 7 (ansible), Windows Server 2012 R2 (managed machine)
##### Summary:

win_feature module does not properly set the 'message' field in its results.

The win_feature module returns a 'feature_result' list.
Each entry in the list contains:

```
display_name (descriptive name)
id (integer)
restart_needed (boolean)
skip_reason
success (boolean)
message
```

The message field returned appears to always be "Microsoft.Windows.ServerManager.Commands.FeatureMessage[]", instead of an actual message string.
##### Steps To Reproduce:

Run the windows/enable-iis.yml playbook from ansible-examples.
##### Expected Results:

```
changed: [ip.address.goes.here] => {"changed": true, "feature_exitcode": "SuccessRestartRequired", "feature_restart_needed": "Yes", "feature_result": [{"display_name": "Application Development", "id": "147", "message": "some actual descriptive message", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"}, {"display_name": "Application Initialization", "id": "445", "message": "some actual descriptive message", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"}, {"display_name": "ASP", "id": "150", "message": "some actual descriptive message", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"},
```
##### Actual Results:

```
changed: [ip.address.goes.here] => {"changed": true, "feature_exitcode": "SuccessRestartRequired", "feature_restart_needed": "Yes", "feature_result": [{"display_name": "Application Development", "id": "147", "message": "Microsoft.Windows.ServerManager.Commands.FeatureMessage[]", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"}, {"display_name": "Application Initialization", "id": "445", "message": "Microsoft.Windows.ServerManager.Commands.FeatureMessage[]", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"}, {"display_name": "ASP", "id": "150", "message": "Microsoft.Windows.ServerManager.Commands.FeatureMessage[]", "restart_needed": "True", "skip_reason": "NotSkipped", "success": "True"},
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
