### ISSUE TITLE
Error in docker: AttributeError: 'int' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible#8731]
##### Steps To Reproduce: Example playbook:

``` yml

---
- hosts: myhost
  tasks:
    - name: fail
      docker:
        image: base
        expose:
          - 1864
```
##### Actual Results: AttributeError: 'int' object has no attribute 'endswith'

```
TASK: [fail] ******************************************************************
failed: [myhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1408811153.49-174422831359320/docker", line 2130, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1408811153.49-174422831359320/docker", line 700, in main
    manager = DockerManager(module)
  File "/root/.ansible/tmp/ansible-tmp-1408811153.49-174422831359320/docker", line 382, in __init__
    self.exposed_ports = self.get_exposed_ports(self.module.params.get('expose'))
  File "/root/.ansible/tmp/ansible-tmp-1408811153.49-174422831359320/docker", line 424, in get_exposed_ports
    if port.endswith('/tcp') or port.endswith('/udp'):
AttributeError: 'int' object has no attribute 'endswith'
```

Not sure what's the best way to deal with types in python, but this could be easily fixed with:

``` diff
diff --git a/library/cloud/docker b/library/cloud/docker
index eb379c2..05822b3 100644
--- a/library/cloud/docker
+++ b/library/cloud/docker
@@ -450,7 +450,7 @@ class DockerManager:
         if expose_list:
             exposed = []
             for port in expose_list:
-                if port.endswith('/tcp') or port.endswith('/udp'):
+                if isinstance(port, str) and (port.endswith('/tcp') or port.endswith('/udp')):
                     port_with_proto = tuple(port.split('/'))
                 else:
                     # assume tcp protocol if not specified
```

**Comment by mpdehaan** [comment]
Looks like different API versions of docker need some casting now.    Can you share the version of the docker libraries you have installed?

**Comment by bobrik** [comment]
@mpdehaan error happens in `library/cloud/docker.py`, how docker libs can affect this?

```
# pip show docker-py
---
Name: docker-py
Version: 0.4.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests, six, websocket-client, mock, coverage
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
