### ISSUE TITLE
ansible_os_family = "NA" on Archlinux host (1.8-git)

### ISSUE THREAD

**Issue by firecat53** [ansible/ansible#8732]
##### Issue Type:

Bug report
##### Ansible Version:

$ ansible --version
ansible 1.8
##### Environment:

Archlinux host
##### Summary:

ansible_os_family no longer returns "Archlinux" for my Arch machines. It now returns "NA"
##### Steps To Reproduce:

ansible -m setup <any configured Arch hostname>|grep ansible_os_family
##### Expected Results:

```
    "ansible_os_family": "Archlinux", 
```
##### Actual Results:

```
    "ansible_os_family": "NA", 
```

**Comment by 3onyc** [comment]
Observing the same behaviour here in Ansible 1.7.1.

```
~$ ansible -m setup arch-box | grep ansible_os_family
        "ansible_os_family": "NA",  
```

**Comment by dcbishop** [comment]
Same here with 1.7.1. Also NA for the the ansible_distribution values:

```
    "ansible_os_family": "NA", 
    "ansible_distribution": "NA", 
    "ansible_distribution_major_version": "NA", 
    "ansible_distribution_release": "NA", 
    "ansible_distribution_version": "NA", 
```

**Comment by gunzy83** [comment]
Confirming the observations of @dcbishop using 1.7.1 on Arch Linux. All distribution and the os_family values are NA.

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two seperate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by firecat53** [comment]
Resubmitted: https://github.com/ansible/ansible-modules-core/issues/34`
