### ISSUE TITLE
win_feature.ps1 : A parameter cannot be found that matches parameter name 'IncludeManagementTools'

### ISSUE THREAD

**Issue by johnyzed** [ansible/ansible#8739]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7.1
##### Environment:

Windows Server 2008 R2
##### Summary:

Each time I am using the windows module called win_feature i am receiving the error message:

```
msg: A parameter cannot be found that matches parameter name 'IncludeManagementTools'.
```

From my investigation, it seems like on Powershell in Windows 2008, the command Add-WindowsFeature (the command used in the module) doesn't have a flag called  IncludeManagementTools.
##### Steps To Reproduce:

Run the following playbook , on a windows client running Windows 2008 R2:
https://github.com/ansible/ansible-examples/blob/master/windows/enable-iis.yml 
##### Expected Results:

```
PLAY [Install IIS] ************************************************************ 

TASK: [Install IIS] *********************************************************** 
changed: [windows2008]

PLAY RECAP ******************************************************************** 
windows2008                    : ok=1    changed=1    unreachable=0    failed=0  
```
##### Actual Results:

```
PLAY [Install IIS] ************************************************************ 

TASK: [Install IIS] *********************************************************** 
failed: [windows2008]

msg: A parameter cannot be found that matches parameter name 'IncludeManagementTools'.

PLAY RECAP ******************************************************************** 
windows2008                    : ok=0    changed=0    unreachable=0    failed=1  
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
