### ISSUE TITLE
ansible-vault decrypt is broken (fix included)

### ISSUE THREAD

**Issue by oddjobz** [ansible/ansible#8752]
##### Steps To Reproduce:

ansible-vault decrypt --vault-password-file=~/.password_file <filename>
##### Expected Results:

"File Decrypted"
##### Actual Results:

"ERROR: Values instance has no attribute 'vault_password_file'"

**Comment by oddjobz** [comment]
Line 118 in bin/ansible-vault , replace "vault_password_file" with "password_file"

**Comment by mpdehaan** [comment]
Thanks for the report, in the future, please submit code changes via github pull requests so they are easy to apply and merge.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dstynchula** [comment]
this fixed my problem in ansible 1.7.1 on mac. :+1:
