### ISSUE TITLE
Ansible should ask for vault password when there is a file that's password encrypted

### ISSUE THREAD

**Issue by shuhaowu** [ansible/ansible#8771]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu, OS X
##### Summary:

`--ask-vault-pass` is somewhat annoying to type when there is a large mixture of roles that sometimes need a password and sometimes not need one.
##### Steps To Reproduce:

Use ansible with vault
##### Expected Results:

When encountering a variable file that's encrypted or when playing a playbook with an encrypted variable file, password is asked as opposed to requiring a param (preferably the latter).
##### Actual Results:

playbook operation fails. Required to rerun with --ask-vault-pass

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a problem, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- This is not a good option for us as it does not stipulate up front that a playbook may go interactive.  As such, the argument is there to allow the system to immediately prompt to avoid surprises later.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
