### ISSUE TITLE
apt_repository performance issue

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#8779]
##### Issue Type:

Performance Issue
##### Ansible Version:

```
$ ansible --version
ansible 1.7.1
```
##### Environment:

```
$ uname -a
Darwin 0x6D6763726561 14.0.0 Darwin Kernel Version 14.0.0: Sat Aug  9 00:14:02 PDT 2014; root:xnu-2782.1.80~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```
##### Summary:

My playbooks are blazing fast (with an apt_cacher_ng proxy), but they keep hanging ~10sec on every `apt_repository` command. Is there a reason it's taking so long? Would it be possible to improve the performance of this command?
##### Steps To Reproduce:

```
- name: MongoDB | Install ppa
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
- name: NodeJS | Install ppa
  apt_repository: repo=ppa:chris-lea/node.js state=present
```
##### Expected Results:

500ms wait
##### Actual Results:

10sec wait

**Comment by mpdehaan** [comment]
It's probably downloading the signing keys again when it may not need to, and the server you are talking to is slow.  I'll leave this marked as a bug, but it doesn't seem like it's hanging, but rather it should be faster.

**Comment by mgcrea** [comment]
@mpdehaan my playbook contains around a dozen `apt_repository` commands and they all seem to be slow, wether they are direct deb packages or ppa, (eg [NodeJS install](https://github.com/mgcrea/ansible-web-playbooks/blob/master/roles/web/nodejs/tasks/install-ubuntu.yml)), maybe using the `ppa:chromium-daily/stable` as a benchmark could be useful (not sure if it qualifies as a speedy mirror).

**Comment by gdevenyi** [comment]
I have also observed that my 10 item ppa add is much slower than I would expect.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
