### ISSUE TITLE
Parsing traceback in 1.6.10 (needs retesting with newer ansible)

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#8786]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.10
##### Environment:

OS X 10.9.4
##### Summary:

Ugly error output
##### Steps To Reproduce:
- name: Configure Roundcube to use macsecurity plugin
  lineinfile: dest=/var/www/html/roundcube/config/config.inc.php
              regexp='^\$config[\'plugins\']\ =\ .*'
              line="$config['plugins'] = array('macsecurity');"
##### Expected Results:

No errors :-)  But even if I've made a boo-boo with quotes or something YAML is parsing, we should beta  friendlier error than:
##### Actual Results:

fatal: [jedis-test] => failed to parse: SUDO-SUCCESS-bmqjrumylttuzzfdgnjmbdmbgcdrokao
Traceback (most recent call last):
  File "/home/joliver/.ansible/tmp/ansible-tmp-1409175269.9-123275515097320/lineinfile", line 1589, in <module>
    main()
  File "/home/joliver/.ansible/tmp/ansible-tmp-1409175269.9-123275515097320/lineinfile", line 330, in main
    supports_check_mode=True
  File "/home/joliver/.ansible/tmp/ansible-tmp-1409175269.9-123275515097320/lineinfile", line 566, in **init**
    (self.params, self.args) = self._load_params()
  File "/home/joliver/.ansible/tmp/ansible-tmp-1409175269.9-123275515097320/lineinfile", line 1135, in _load_params
    items   = shlex.split(args)
  File "/usr/lib64/python2.6/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.6/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by mpdehaan** [comment]
Ansible 1.7.1 is the current version of Ansible, can you reproduce this there?

Also: this is actually a traceback, so I'm going to update your ticket description.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
