### ISSUE TITLE
Docker Module: Add support for --restart policies

### ISSUE THREAD

**Issue by matthewcmorgan** [ansible/ansible#8787]
##### Issue Type:

Feature idea
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu 14.04
##### Summary:

Feature Request: Add support for --restart policies in the docker module.
##### Steps To Reproduce:

``` yaml
docker: 
    image: "{{container}}:{{tag}}"
    name: "{{name_of_container}}"
    volumes_from: "{{name_of_data_container}}"
    ports: "{{container_ports}}"
    env: "{{env_vars}}"
    command: "{{command}}"
    restart: "--restart=on-failure:10"
```
##### Expected Results:

``` bash
TASK: [services/auth | Auth | Run Auth Container] ***************************** 
changed: [10.0.3.44]
```
##### Actual Results:

``` bash
TASK: [services/auth | Auth | Run Container] ***************************** 
<10.0.3.44> ESTABLISH CONNECTION FOR USER: ubuntu
fatal: [10.0.3.44] => Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.

FATAL: all hosts have already failed -- aborting
```

**Comment by justinmayer** [comment]
In case it's not clear, support for restart policies was [introduced in Docker 1.2](https://blog.docker.com/2014/08/announcing-docker-1-2-0/). Like Matthew, I'm looking forward to seeing similar support implemented in Ansible's [Docker module](http://docs.ansible.com/docker_module.html).

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We have received a PR for this already (#8815), so we will close this and track this there. If you would like to test that PR, it is always helpful for us to receive +1's to speed up our testing.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
