### ISSUE TITLE
wrong processor_count fact on linux intel

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#8797]
##### Issue Type:

Bug
##### Ansible Version:

ansible devel
##### Environment:

Linux intel
##### Summary:

Info for bug fixes:
- issue added with b9613665
- Intel systems have both 'model name' and 'vendor_id' (generating doubled counts)

Sadly I'm not able to check  any bug fixes on linux / system z
##### Steps To Reproduce:

```
- hosts: all
  tasks:
    - debug: msg="count={{ansible_processor_count}}"
```
##### Expected Results:

```
TASK: [debug msg="count={{ansible_processor_count}}"] *************************
ok: [dualprocessor.inter.nos] => {
    "msg": "count=2"
}
ok: [singleprocessor.inter.nos] => {
    "msg": "count=1"
}
```
##### Actual Results:

```
TASK: [debug msg="count={{ansible_processor_count}}"] *************************
ok: [dualprocessor.inter.nos] => {
    "msg": "count=4"
}
ok: [singleprocessor.inter.nos] => {
    "msg": "count=2"
}
```

**Comment by mpdehaan** [comment]
What OS are you finding this on (for the remote machine?)

**Comment by lberruti** [comment]
It seems that only (vSphere) virtual machines are affected.

Wrong:
- VM Debian GNU/Linux 5, kernel 2.6.32-5-amd64
- VM Debian GNU/Linux 6, kernel 2.6.26-2-686
- VM Debian GNU/Linux 7, kernel 3.2.0-4-686-pae
- VM SUSE Linux Enterprise Server 11 (x86_64), kernel 3.0.101-0.7.19-default
  Right:
- Debian GNU/Linux 5, kernel 2.6.29-bpo.2-amd64 on bare metal
- Debian GNU/Linux 5, kernel 2.6.26-2-686 on bare metal

**Comment by ntrepid8** [comment]
I'm also seeing this.  It looks like the `get_cpu_facts` in the `LinuxHardware` Class is counting some CPUs twice.  Here is an example expert from `/proc/cpuinfo` that will generate the issue:

```
processor   : 7
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
stepping    : 7
microcode   : 0x710
cpu MHz     : 2600.086
cache size  : 20480 KB
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm
bogomips    : 5216.79
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

It's counting `vendor_id` and `model name` both, resulting in the double counting.  The source file is here:

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
