### ISSUE TITLE
win_feature on non-server windows

### ISSUE THREAD

**Issue by ptman** [ansible/ansible#8798]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.7.1
##### Environment:

Managing Windows 7 Pro 64bit from Mac OS X and Linux.
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

```
win_feature: name=SNMP state=present
```
##### Expected Results:

SNMP feature installed
##### Actual Results:

```
msg: The term 'Add-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I realise managing features on client windows may not be a very common thing to do. Add-WindowsFeature is a Windows Server cmdlet. I have however been able to manage those features on client/desktop windows products before, using dism (through the puppetlabs-dism puppet module).

win_feature could switch or fallback to using dism when Add/Remove-WindowsFeature isn't available.

**Comment by trondhindenes** [comment]
Yep, that shouldn't be too hard to implement.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
