### ISSUE TITLE
keystone_user, msg: unsupported parameter for module: user

### ISSUE THREAD

**Issue by ramelito** [ansible/ansible#8800]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.8 (devel 984d551257) 
##### Environment:

Linux ansible 3.13.0-34-generic #60-Ubuntu
##### Summary:

So, using keystone_user module to create user but get this error.
##### Steps To Reproduce:
- name: create an administrative user
  keystone_user: user=admin password={{ admin_pass }} email="root@localhost" role=admin tenant=admin tenant_description="Admin Tenant" token={{ keystone_token.stdout }}
  sudo: yes

**Comment by ramelito** [comment]
Looking through the code of keystone_user module i have found it misses user and tenant variables

def main():

```
argument_spec = openstack_argument_spec()
argument_spec.update(dict(
        tenant_description=dict(required=False),
        email=dict(required=False),
        role=dict(required=False),
        state=dict(default='present', choices=['present', 'absent']),
        endpoint=dict(required=False,
                      default="http://127.0.0.1:35357/v2.0"),
        token=dict(required=False),
        login_user=dict(required=False),
        login_password=dict(required=False),
        login_tenant_name=dict(required=False)
))
```

so documentation should be updated or module should be removed until repair

**Comment by ramelito** [comment]
I found commit https://github.com/ansible/ansible/commit/4012272fa2ae0a6caafad0e0783c8d8fcc3e852a#diff-c729a497d74eab45995637611ba650d7
this commit broke keystone_user and i suppose the author of commit did not make q&a tests.
this commit should be rolled back.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
