### ISSUE TITLE
can't set/override default arguments to modules

### ISSUE THREAD

**Issue by ergonlogic** [ansible/ansible#8810]
##### Issue Type:

Bug Report, Documentation Report
##### Ansible Version:

1.7.1
##### Environment:

N/A
##### Summary:

There appears to be a regression in the ability to set and override default arguments to modules requiring complex arguments.

According to https://github.com/ansible/ansible-examples/blob/master/language_features/complex_args.yml, we should be able to pass default parameters to modules. In fact, it shows an example of overriding the default fact locally, which no longer works either. Even in 1.7.0, adding an override (e.g. "ec2: region=us-west-1") results in the following error:

```
 msg: duplicate parameter: region (value=us-west-1)
```
##### Steps To Reproduce:

The following works in 1.7.0, but not in 1.7.1, as shown by the output below:

```
# in file: test.yml
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    default:
      region: us-east-1
      instance_type: m3.medium
      image: ami-d2ff23ba
  tasks:
    - name: Provision hosts
      ec2:
      args: default
```
##### Expected Results:

```
$ sudo pip install ansible==1.7.0
$ ansible-playbook test.yml

PLAY [localhost] **************************************************************

TASK: [Provision hosts] *******************************************************
changed: [127.0.0.1]

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
$ sudo pip install ansible==1.7.1
[...]
$ ap test.yml 

PLAY [localhost] ************************************************************** 

TASK: [Provision hosts] ******************************************************* 
ERROR: args must be a dictionary, received default (<type 'str'>
```

Possibly related to #6244; see https://github.com/ansible/ansible/issues/6244#issuecomment-53008716

**Comment by jimi-c** [comment]
@ergonlogic this change was related to a security fix. It should work if you add the variable brackets around it, ie:

<pre>
  tasks:
    - name: Provision hosts
      ec2:
      args: "{{default}}"
</pre>

**Comment by ergonlogic** [comment]
@jimi-c Unfortunately, that doesn't work either. It returns essentially the same error:

```
ERROR: args must be a dictionary, received {{ default }} (<type 'str'>)
```

**Comment by mpdehaan** [comment]
Yeah that should not be forcing to strings there, we'll investigate.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
