### ISSUE TITLE
Question about running the Oracle installer

### ISSUE THREAD

**Issue by pschirch** [ansible/ansible#8814]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Host: Ubuntu 14.04 LTS
Guest: openSUSE 13.1
##### Summary:

I wrote a task to perform a silent oracle client setup. With ansible **1.6.10 it works**, but ansible 1.7.1 skips executing the shell process. I also tried the module **command** and **raw**, same issue here.
##### Steps To Reproduce:

**Task definition**

``` yaml
# install oracle client
- name: Install orale client
  shell: /bin/sh /home/oracle/Downloads/client/runInstaller -silent -noconfig -responseFile /home/oracle/Downloads/client.rsp
  sudo_user: oracle
```
##### Expected Results:

Executing the oracle client setup after **"Please wait ..."**

``` bash
TASK: [oracle-client | Install orale client] ********************************** 
changed: [default] => {"changed": true, "cmd": "/bin/sh /home/oracle/Downloads/client/runInstaller -silent -noconfig -responseFile /home/oracle/Downloads/client.rsp", "delta": "0:00:54.090876", "end": "2014-08-29 10:03:30.492918", "rc": 0, "start": "2014-08-29 10:02:36.402042", "stderr": "", "stdout": "Starting Oracle Universal Installer...\n\nChecking Temp space: must be greater than 120 MB.   Actual 26345 MB    Passed\nChecking swap space: must be greater than 150 MB.   Actual 519 MB    Passed\nPreparing to launch Oracle Universal Installer from /tmp/OraInstall2014-08-29_10-02-36AM. Please wait ...[WARNING] [INS-13014] Target environment do not meet some optional requirements.\n   CAUSE: Some of the optional prerequisites are not met. See logs for details. /tmp/OraInstall2014-08-29_10-02-36AM/installActions2014-08-29_10-02-36AM.log\n   ACTION: Identify the list of failed prerequisite checks from the log: /tmp/OraInstall2014-08-29_10-02-36AM/installActions2014-08-29_10-02-36AM.log. Then either from the log file or from installation manual find the appropriate configuration to meet the prerequisites and fix it manually.\nYou can find the log of this install session at:\n /opt/oracle/oraInventory/logs/installActions2014-08-29_10-02-36AM.log\nThe installation of Oracle Client 11g was successful.\nPlease check '/opt/oracle/oraInventory/logs/silentInstall2014-08-29_10-02-36AM.log' for more details.\n\nAs a root user, execute the following script(s):\n\t1. /opt/oracle/oraInventory/orainstRoot.sh\n\n\nAs install user, execute the following script to complete the configuration.\n\t1. /opt/oracle/oraHome/product/11.2.0/client_1/cfgtoollogs/configToolAllCommands RESPONSE_FILE=<response_file>\n\n \tNote:\n\t1. This script must be run on the same host from where installer was run. \n\t2. This script needs a small password properties file for configuration assistants that require passwords (refer to install guide documentation).\n\n\nSuccessfully Setup Software."}

```
##### Actual Results:

**Task Output**

``` bash
TASK: [oracle-client | Install orale client] ********************************** 
changed: [default] => {"changed": true, "cmd": "/bin/sh /home/oracle/Downloads/client/runInstaller -silent -noconfig -responseFile /home/oracle/Downloads/client.rsp", "delta": "0:00:01.021228", "end": "2014-08-29 09:39:21.995088", "rc": 0, "start": "2014-08-29 09:39:20.973860", "stderr": "", "stdout": "Starting Oracle Universal Installer...\n\nChecking Temp space: must be greater than 120 MB.   Actual 26473 MB    Passed\nChecking swap space: must be greater than 150 MB.   Actual 519 MB    Passed\nPreparing to launch Oracle Universal Installer from /tmp/OraInstall2014-08-29_09-39-20AM. Please wait ..."}
```

Skipping shell executing after **"Please wait ..."**

**Comment by mpdehaan** [comment]
Ansible will execute any program you want here, rather than prepending a specific shell, so I'm curious what you mean about this one and why you think it's skipping invocation of the shell.

Did you mean certain environment variables are not being loaded, etc?

**Comment by mpdehaan** [comment]
Also, if this is about environment variables, I'd recommend reading this chapter - 

http://docs.ansible.com/playbooks_environment.html

**Comment by pschirch** [comment]
Ansible 1.7.1 skips:

``` bash
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2014-08-29_10-02-36AM
```

I'm currently checking if any env vars are not available ...

**Comment by pschirch** [comment]
Unfortunately I can't figure out what is wrong here. The oracle client installer stops without any warnings or errors after `Please wait ...`.  If I connect to the server and run the shell script manually all works fine (so all depending ansible tasks runs sucessfully but oracle client setup). Checkout ansible 1.6.10 and the install task finish sucessfully. The break comes with ansible 1.7. Configuring ansible verbose mode to `vvvv` shows non additionally information.

**Comment by pschirch** [comment]
I think, I should prepare an environment so that you can test it. It is okay to prepare an Ansible + Vagrant + VirtualBox environment in that my oracle client setup playbook can be provisioned?

**Comment by mpdehaan** [comment]
Yeah we do not do testing of user-supplied VMs, would it be possible to replicate this with a tiny hello world style shell script?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
