### ISSUE TITLE
Docker module should allow specifying restart policy

### ISSUE THREAD

**Issue by iragsdale** [ansible/ansible#8820]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.8
##### Environment:

N/A
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!
##### Expected Results:

Docker 1.2 now lets you specify a restart policy (see here: https://blog.docker.com/2014/08/announcing-docker-1-2-0/). It should be configurable using the docker module in 1.8.
##### Actual Results:

Cannot configure the restart policy using ansible.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We have received a PR for this already (#8815), so we will close this as a duplicate. If you would like to test that PR, it is always helpful for us to receive +1's to speed up our testing.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
