### ISSUE TITLE
ansible-galaxy exits with status 0 when a role is not found

### ISSUE THREAD

**Issue by benbridts** [ansible/ansible#8823]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Ubuntu 14.04
##### Summary:

When ansible galaxy can't install a role, because it's not found, I expect the exit status to be non-zero, but it isn't
##### Steps To Reproduce

```
ansible-galaxy install foobar.does_not_exists
echo $?
```
##### Expected Results:

```
ansible-galaxy install test.foobar
    downloading role 'foobar', owned by test
    Sorry, test.foobar was not found on galaxy.ansible.com.
echo $?
    1 (or anything other than 0)
```
##### Actual Results:

```
ansible-galaxy install test.foobar
    downloading role 'foobar', owned by test
    Sorry, test.foobar was not found on galaxy.ansible.com.
echo $?
    0 
```

**Comment by srgvg** [comment]
different output but same issue on devel

```
$ ansible-playbook --version; ansible-galaxy install foobar.does_not_exists; echo $?
ansible-playbook 1.8 (devel 0179c13e04) last updated 2014/09/09 21:40:40 (GMT +200)
- downloading role 'does_not_exists', owned by foobar
- sorry, foobar.does_not_exists was not found on galaxy.ansible.com.
0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
