### ISSUE TITLE
when: evaluation doesn't like variables containing "-" (dashes)

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#8849]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 9edf3a749a) last updated 2014/08/13 09:45:46 (GMT +200)
##### Environment:

Host is FC19 and Target is Wheezy 7.5
##### Summary:

In a task, upon using the 'when' functionality, the evaluation of the condition doesn't work if a variable contains the dash char in its name.
##### Steps To Reproduce:

```
- name: do something
  lineinfile:  bla bla bla
  when: (phpfe is defined) or (php-be is defined) or (nginx is defined) 
```
##### Expected Results:

Task gets applied on host that has the variable php-be defined.
##### Actual Results:

This only works for hosts phpfe and nginx.
When I change php-be to php_be, it works like a charm.

**Comment by danfaizer** [comment]
Hi,
Ansible playbooks are written in YAML format. As far as I know, dash '-' is a reserved character in YAML specification[1]. Therefore, I believe there is no other solution than renaming those variables and avoid using reserved characters.

[1] http://yaml.org/spec/current.html#id2439001

**Comment by danvaida** [comment]
Right ;) 10x.

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible. We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The problem you are experiencing is due to the fact that variable names cannot include dashes. Please see http://docs.ansible.com/playbooks_variables.html#what-makes-a-valid-variable-name for details on variable naming.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
