### ISSUE TITLE
APT fails when {{item}} in the middle of a deb argument

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#8852]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

There is a problem when invoking apt with variables.
When the variables are inside an argument, it gives an error:

```
- name: Install chromium browser
  apt: deb=/root/{{item}}.deb
  when: ansible_architecture in ['armv7l']
  with_items:
    - chromium-inspector
    - chromium-browser
```

Fails:

```
TASK: [gui | Install chromium browser] ****************************************
fatal: [7c669d537a3e] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1409662082.8-144889871942361/apt", line 1907, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1409662082.8-144889871942361/apt", line 523, in main
    force=force_yes, dpkg_options=p['dpkg_options'])
  File "/root/.ansible/tmp/ansible-tmp-1409662082.8-144889871942361/apt", line 299, in install_deb
    pkg = apt.debfile.DebPackage(deb_file)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 57, in __init__
    self.open(filename)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 66, in open
    self._debfile = apt_inst.DebFile(self.filename)
SystemError: E:Could not open file /root/chromium-inspector - open (2: No such file or directory), E:Unable to determine the file size - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)


FATAL: all hosts have already failed -- aborting
```

(note the missing .deb at the end of the filename)

Whereas:

```
- name: Install chromium browser
  apt: deb=/root/{{item}}
  when: ansible_architecture in ['armv7l']
  with_items:
    - chromium-inspector.deb
    - chromium-browser.deb
```

(note moving the .deb filenames inside the array rather than after the variable on the deb argument)

Succeeds.
There should NOT be any difference between the runs.
When trying to find out if it is caused by whitespace I did:

```
- name: Install chromium browser
  shell: echo deb=/root/{{item}}.deb
  when: ansible_architecture in ['armv7l']
  with_items:
    - chromium-inspector
    - chromium-browser
```

Which resulted in:

```
changed: [7c669d537a3e] => (item=chromium-inspector) => {"changed": true, "cmd": "echo deb=/root/chromium-inspector.deb", "delta": "0:00:00.035228", "end": "2014-09-02 12:48:54.123722", "item": "chromium-inspector", "rc": 0, "start": "2014-09-02 12:48:54.088494", "stderr": "", "stdout": "deb=/root/chromium-inspector.deb"}
changed: [7c669d537a3e] => (item=chromium-browser) => {"changed": true, "cmd": "echo deb=/root/chromium-browser.deb", "delta": "0:00:00.017942", "end": "2014-09-02 12:48:56.467385", "item": "chromium-browser", "rc": 0, "start": "2014-09-02 12:48:56.449443", "stderr": "", "stdout": "deb=/root/chromium-browser.deb"}
```
##### Steps To Reproduce:

See above.
##### Expected Results:

No difference between the runs
##### Actual Results:

Fails when .deb is in the argument line, Succeeds when inside the array.

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

What is happening is that:
- Multiple issues in the past have covered this, where {{item}} cannot be used in the middle of a string as you're doing. There is at least one other open issue regarding this, so we will be closing this as a duplicate.

In order to work around this for the time being, we would suggest:
- Move the full string down to the list of items, so that {{item}} is used by itself in the module parameter.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by axos88** [comment]
Which issue is that?

**Comment by jimi-c** [comment]
This is essentially the same issue: https://github.com/ansible/ansible/issues/8314
