### ISSUE TITLE
ec2 with exact_count & count_tag doesn't restrict to zone

### ISSUE THREAD

**Issue by mike-d-d** [ansible/ansible#8863]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 893f15b30b) last updated 2014/09/02 18:45:31 (GMT -700)
##### Environment:

OS X 10.9
##### Summary:

I'm using the ec2 module with exact_count & count_tag.  I assumed that if I e.g. specified exact_count=1, I'd be sure to end up with an instance running in the specified zone, but the search done by `find_running_instances_by_count_tag()` doesn't include a zone filter, so it's happy as long as there's an instance running in _any_ zone.

Is this the intended behavior?  It seems wrong.  I can work around it by adding an additional "zone" tag to all my instances, but that seems like a hack.
##### Steps To Reproduce:

```
  - ec2:
      count_tag: { Name: "{{ name }}" }
      exact_count: 1
        ...
```

where there are no instances running with the given name in the specified zone, but there are instances with that name in other zones in the region.
##### Expected Results:

I expected to end up with one instance in each zone.
##### Actual Results:

I only end up with a single instance in the region, in whichever zone ran that task first.

**Comment by jimi-c** [comment]
@mike-d-d I've created the above patch, if you'd like to give it a test.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
