### ISSUE TITLE
GPL license implies that my plugins are also GPL (MPD's note:  it does not)

### ISSUE THREAD

**Issue by nedbat** [ansible/ansible#8864]
We've copied plugins/inventory/ec2.py and made modifications to it for our own project.  A strict reading of the GPL would be that that means the file in our project must also be GPL, and that my project must be GPL.  Is this your interpretation as well?
I wouldn't think you'd intend that any project using Ansible must necessarily be GPL.  Can you clarify the situation, perhaps by explicitly putting the plugins directory under a permissive license?

**Comment by mpdehaan** [comment]
Hi @nedbat,

Generally speaking, questions should go to the project list (ansible-project) rather than GitHub, but I'll answer here.

This is not our interpretation.

Inventory plugins in ansible have a contract where they emit JSON -- they are executed by ansible, and not linked.   

If you have based something on ec2.py (say ec2_mycompany.py), that work is also GPL.  The "work" in that case is your copy of ec2.py, not your whole project, and whatever that may link to by means of import (web/network services don't count).   

That would only apply if you wished to distribute it as well, if you don't distribute it, you have no concern.

If you've wrote your own inventory plugin, especially from scratch, it can also be any license you want - see http://docs.ansible.com/developing_inventory.html

Most folks do not release their changes to the inventory script they make because they are not distributing them to others (such as customers) but made them internally.

Ansible modules, for instance, are GPL by convention, but the shared code that gets mixed into modules you write is explicitly BSD, to enable folks to write proprietary modules and not feel they need to distribute them.

For further questions on this, feel free to drop us a line at info@ansible.com.   We'd also be happy to address any concerns with your legal department, should they wish to have a statement from us saying such.   You may also point them at this github response.

Thanks!

--Michael

**Comment by mpdehaan** [comment]
I'm going to mark this ticket as resolved and close the comments on it, for further questions about license items, if anyone has them, email the info@ address.

Thanks!
