### ISSUE TITLE
Ansible fails to install correctly into a virtualenv when built as a wheel

### ISSUE THREAD

**Issue by evansd** [ansible/ansible#8875]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04
##### Summary:

When built as a Python wheel and then installed from that wheel into a virtualenv, ansible fails to populate the `share/ansible` directory, and so breaks.

Note that other that this issue, ansible and its dependencies install fine from wheels.
##### Steps To Reproduce:

``` bash
virtualenv wheel-test
source wheel-test/bin/activate
pip install wheel
pip wheel ansible==1.7.1
pip install --use-wheel --find-links wheelhouse ansible==1.7.1
ls wheel-test/share/ansible
```
##### Expected Results:

```
cloud     internal    net_infrastructure  source_control      windows
commands  inventory   network             system
database  messaging   notification        utilities
files     monitoring  packaging           web_infrastructure
```
##### Actual Results:

```
ls: cannot access wheel-test/share/ansible: No such file or directory
```

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- that ansible tries to install into LSB specific locations is a bug

However, however what is happening is that:
- ansible is installing into LSB applications because various contents are not python modules and it's a systems management application, not just a basic python library.  There are other options though...

We would suggest:
- you refer to instructions in http://docs.ansible.com/intro_installation.html -- you could use pip in editable mode, or simply do a checkout and run things with "source ./hacking/env-setup" - no installation is required.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by evansd** [comment]
I completely understand that this isn't a priority for you (and I'll try to track down the issue and submit a patch myself) but I don't think I've misunderstood the issue here.

Just to clarify, installing in a virtualenv without building a wheel first works perfectly:

```
virtualenv wheel-test
source wheel-test/bin/activate
pip install ansible==1.7.1
ls wheel-test/share/ansible
# displays correct directories
```

Installation should work identically whether using the package or the wheel. I think that's true regardless of whether it's a "basic python library" or not.

Again, I'm only submitting this as a bug so there's a public record of it. I'm not expecting anyone other than me to invest time and effort in fixing it!

**Comment by msabramo** [comment]
I just ran into this as well and it wasted a fair amount of time for me, because I was upgrading from one version of Ansible to another and the error messages I was getting convinced me that I had something in my playbook that was non-standard or deprecated and I went down the rabbit trail of looking for that before I realized that Ansible wasn't finding any modules. It then took a bit longer to realize that it was because I was installing from a wheel.

I also think that this is a bug because the installation should work the same regardless of whether a wheel was used or not and I don't think "basic python library" vs. "systems management application" is a useful distinction in regards to this issue. No matter how powerful Ansible is or what its scope is or if it includes bits that are not Python, I'd say it's a python package if it's installable with pip.

I'm guessing that it's probably possible to fix this, but I'd have to dig a bit deeper into it. Ansible doesn't seem to use the `pkg_resources` module -- that's the typical way that packages find their files -- it could be related to that. I guess it does something else.

In the meantime, I sent a PR to add a note to the documentation about this issue, as it's a tricky little problem and it would be nice if there were a warning about it:

https://github.com/ansible/ansible/pull/8999

**Comment by msabramo** [comment]
The change in this PR fixed the issue for me -- https://github.com/ansible/ansible/pull/9043; @evansd: Do you want to give it a try?

**Comment by aabdnn** [comment]
I have just encountered this same problem. I found that if I build a wheel, and install that wheel into a virtualenv, then instead of the modules going into <virtualenv>/usr/share/ansible, they go into <virtualenv>/lib/python/site-packages/usr/share/ansible.

Obviously, ansible cannot then find these modules. However, I don't know enough about the insides of setup.py and ansible's constants.py to know what the correct fix is.

**Comment by philipn** [comment]
Unfortunately, I can confirm that ansible is still broken when installed via a wheel.  I'm not sure where the breakage was happening before, but I see errors such as:

```
Traceback (most recent call last):
  File "gevent-1.0.2-cp27-none-linux_x86_64.whl/gevent/greenlet.py", line 327, in run
  File "app-0.1.0-py2-none-any.whl/app/server/webapp/deploy.py", line 115, in __call__
  File "ansible-1.9.1-py2-none-any.whl/ansible/playbook/__init__.py", line 310, in run
  File "ansible-1.9.1-py2-none-any.whl/ansible/playbook/play.py", line 194, in __init__
  File "ansible-1.9.1-py2-none-any.whl/ansible/playbook/play.py", line 681, in _load_tasks
  File "ansible-1.9.1-py2-none-any.whl/ansible/playbook/task.py", line 115, in __init__
AnsibleError: fail is not a legal parameter in an Ansible task or handler
```

When attempting to use ansible after installing via a wheel.  Installing via a downloaded tarball + `setup.py install` or via `pip` works fine.
