### ISSUE TITLE
Git module does not switch branches when they have the same head SHA

### ISSUE THREAD

**Issue by cwstrommer** [ansible/ansible#8877]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 12.04
##### Summary:

The git module fails to switch branches when both branches have the same HEAD checksum
##### Steps To Reproduce:

Create two branches on a git repository that are identical but by the branch name.  Use the git module to check out branch1, then to check out branch2.  
##### Expected Results:

The local repository that the git module checked out should be on branch2.  Git module should return with changed=True
##### Actual Results:

The git module compares the SHA sums of the two repositories, and returns with changed=False, leaving the local repository on branch1

**Comment by mpdehaan** [comment]
usually this module is used to deploy software, so if they have the same SHA, you'd be deploying the same software.

Though it seems like it should, so thanks for filing the report.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
