### ISSUE TITLE
with_first_found in template module doesn't search relative to .../templates

### ISSUE THREAD

**Issue by irilyth** [ansible/ansible#8879]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6 (czen-1.6.6 004f90b4aa) last updated 2014/09/02 16:02:41 (GMT -400)

(Can't easily test on a newer version.)
##### Environment:

RHEL 5
##### Summary:

In a role that uses the the template module, using with_first_found and "src={{ item }}", Ansible reports "unable to read .../roles/<role-name>/templates", even though that directory (and the files within it) exist.
##### Steps To Reproduce:

Our playbook has a task like this:

```
- name: template TrustedHosts
  template: dest=/etc/opendkim/TrustedHosts src={{ item }} backup=yes
  with_first_found:
    - TrustedHosts.{{ stack }}
    - TrustedHosts.default
```

The directory for this role looks like this:

```
+$ tree
.
|-- files
|   `-- sysconfig-opendkim
|-- tasks
|   `-- main.yml
`-- templates
    |-- KeyTable
    |-- SigningTable
    |-- TrustedHosts.default
    |-- TrustedHosts.prod
    `-- opendkim.conf
```

Let me know if you need us to create a more complete set of files to reproduce this, or if that's enough to go on.
##### Expected Results:

Either TrustedHosts.prod or TrustedHosts.default would be found and used, depending on the value of {{ stack }}.
##### Actual Results:

This error:

```
TASK: [../../shared/roles/opendkim | template TrustedHosts] *******************
fatal: [host3] => {'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}
fatal: [host2] => {'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}
fatal: [host3] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}]}
fatal: [host2] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}]}
fatal: [hos1] => {'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}
fatal: [host1] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': 'unable to read /home/jsmift/ansible/shared/roles/opendkim/templates', 'failed': True}]}
```

Note that the error goes away (and the task works as expected) if we change the task to

```
- name: template TrustedHosts
  template: dest=/etc/opendkim/TrustedHosts src={{ item }} backup=yes
  with_first_found:
    - ../templates/TrustedHosts.{{ stack }}
    - ../templates/TrustedHosts.default
```

instead.

**Comment by mpdehaan** [comment]
This is probably looking in "files", which would make sense as this is what most lookup plugins do, though the paths here are not clear and probably should be.

The real problem here is the template dir itself is missing, and since roles aren't being used in the "can't find" message I would expect it to report on all the locations searched.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
