### ISSUE TITLE
vars_files: expanding list of files via a single variable results in error

### ISSUE THREAD

**Issue by dixhuit** [ansible/ansible#8881]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Mac OS 10.9.4
##### Summary:

See issue title and this user group post: https://groups.google.com/forum/#!topic/ansible-project/34s04iBgzXQ
##### Steps To Reproduce:

Create a variable containing multiple file paths (I created my var in `group_vars/all`):

```
settings_files: '"../settings.yml", "../example.settings.yml"'
```

Try to expand that variable when calling vars_files in a playbook:

```
vars_files:
  - [ "{{ settings_files }}" ]
```
##### Expected Results:

The same as if I'd just added this to my playbooks:

```
vars_files:
  - [ "../settings.yml", "../example.settings.yml" ]
```

Ansible should then load the first file it finds that does exist.
##### Actual Results:

Failed play and this fatal error:

```
vlad: not importing file: /Volumes/Data/Projects/vlad/vlad/vlad/playbooks/"../settings.yml", "../example.settings.yml"
ERROR: vlad: FATAL, no files matched for vars_files import sequence: [u'/Volumes/Data/Projects/vlad/vlad/vlad/playbooks/"../settings.yml", "../example.settings.yml"']
```

It appears as if Ansible is prefixing an absolute path (the path to the playbook making the call: /Volumes/Data/Projects/vlad/vlad/vlad/playbooks/) to my expanded variable, irrespective of what my variable contains. This in turn is making the expanded variable a bit garbled, hence the error.

**Comment by mpdehaan** [comment]
Might be worth trying this:

vars_files: "{{ settings_files }}"

And see if that helps.

Though the following is still a curious expansion that should not happen :)

Thanks for the report!

**Comment by dixhuit** [comment]
Thanks for the suggestion but I already tried that. It results in a different error:

```
ERROR: file could not read: /Volumes/Data/Projects/vlad/vlad/vlad/playbooks/"../settings.yml", "../example.settings.yml"
```

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated. In particular, we believe you have said:
- Ansible should then load the first file it finds that does exist.

However, however what is happening is that:
- You are passing the entire string to vars files, which (even if this worked as-is), means all of the files would be loaded, not just the first one found. This will not work at all, however, since the variable is a string instead of a list.

There are several ways to address this:

If you really wished for only the first file found to be loaded, you should use the following:

<pre>
vars_files_var: ['../path/to/file1', '../path/to/file2', ...]
- include_vars: {{item}}
  with_first_found: vars_files_var
</pre>

The above will properly load only the first file found, and is more flexible than trying to do this via the `vars_files` language keyword. Also note that the variable is initialized with a list, not a string. If you did want to continue using a string, you would need to write a new filter plugin to allow the string to be split on the comma, so that the value you would become a list.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
