### ISSUE TITLE
ansible_ssh_port is not taken into account when there is the same host in an inventory file

### ISSUE THREAD

**Issue by MichaelBitard** [ansible/ansible#8883]
We have found what seems to be an issue on ansible (tested on 1.6.2 and 1.7.1)

In our hosts file, we have two hosts with the same ip, but a different ssh port (this machine is a gateway to our production)

```
[ANYNAME]
172.17.11.200 ansible_ssh_port=61222 ansible_ssh_user=user ansible_ssh_pass=pass ansible_sudo_pass=pass user=user

[ANOTHER_ONE]
172.17.11.200 ansible_ssh_port=59222 ansible_ssh_user=user ansible_ssh_pass=pass ansible_sudo_pass=pass user=user
```

If you use a very simple .yml: 

```
- hosts: "{{ host_to_reach }}"
  tasks:    
  - command: echo "toto"
```

and call it with 

```
ansible-playbook test.yml -vvvv -i hosts --extra-vars "host_to_reach=ANOTHER_ONE"
```

or 

```
ansible-playbook test.yml -vvvv -i hosts --extra-vars "host_to_reach=ANYNAME"
```

it will ALWAYS reach the same port (the second one declared in the hosts file)
If we use IP:PORT syntax in the hosts file, the problem is reversed (the first one is always used)

I created a repo that reproduce the bug : 
https://github.com/MichaelBitard/ansible_ssh_port_bug

This is a major problem for us, because everything goes through this gateway, and it's dangerous because we deliver our software on the wrong machines.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- ansible is ignoring a variable

However, however what is happening is that:
- host entries can only occur once in an inventory, what you have done is put the host into two groups and set different variables against it

We would suggest:
- setting an alias for each and using "ansible_ssh_host" as indicated in the documentation so that you can have the same host twice with different ports.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by MichaelBitard** [comment]
Sorry, I really misunderstood the inventory file.

Works better now, thanks and sorry, next time i'll post on the google group.
