### ISSUE TITLE
zypper_repository: absent state for a repository without name

### ISSUE THREAD

**Issue by alxgu** [ansible/ansible#8886]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 5a7cbdda7e) last updated 2014/09/04 08:50:17 (GMT +200)
##### Environment:

CentOS 6
Dest: SLES 11
##### Summary:

Running against an error when you run state=absent with just a repo url.
##### Steps To Reproduce:

The playbook got follwoing line:
zypper_repository: state=absent repo='ftp://download.nvidia.com/opensuse/12.2
##### Expected Results:

It should remove the repository!
##### Actual Results:

I get following error message:

failed: [$servername] => (item={'repo': 'ftp://download.nvidia.com/opensuse/12.2', 'name': 'Nvidia'}) => {"failed": true, "item": {"name": "Nvidia", "repo": "ftp://download.nvidia.com/opensuse/12.2"}}
msg: Name required when adding non-repo files:

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
