### ISSUE TITLE
Request for raw command to not invoke a shell (was: Talk to devices via ssh without a shell)

### ISSUE THREAD

**Issue by FritsHoogland** [ansible/ansible#8887]
##### Summary:

Request for raw command to not invoke a shell
##### Expected Results:

Ability to execute commands on devices without a shell, but do provide access with ssh. Examples of these devices are lights-out adapters, networking devices, etc.
##### Actual Results:

Currently, when for example trying to execute commands via ssh to an Oracle iLOM, this message is returned:
shell: Invalid credentials\n\n\n
###### actual request, and verbose description:

When doing advanced orchestration of change implementations, there is a fair chance you might want to talk to devices via ssh, which do not have shell, but merely expose their embedded interpreter via ssh. Think about lights-out adapters like HP iLO, Oracle iLOM, Del DRAC, but also devices like Cisco router/switch/firewalls and other networking devices.

The module which seems most appropriate is 'raw', however a separate mode needs to be implemented which does not require a shell on the remote side, but just sends the user defined commands, and reads the output.

I tried this with an Oracle iLOM adapter with the raw module, which returned:
shell: Invalid credentials\n\n\n
Despite the ssh connection been set up prior to executing the commands via the raw module.

Thanks!

Reference: google groups (subject: 'Talk to lights-out adapters')
(Michael DeHaan:)
We'll likely have to incorporate it into the action plugin source for raw, which I don't think will be especially difficult, though I will say it may be some time before this happens due to other things in the queue.

If others would like to attempt this, I'm suggesting something like:

raw: /usr/bin/foo asdf bar shell=false

And the code would have to parse off the free-form argument "shell=" if present, before sending the command.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
