### ISSUE TITLE
Allow to re-run failed tasks

### ISSUE THREAD

**Issue by kpx-dev** [ansible/ansible#8896]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.7.1
##### Environment:

N/A
##### Summary:

I would like to re-run failed tasks only. Ex: I have 10 tasks, task number 9 failed the first time I run, the 2nd time I run it, only task number 9 should be executed
##### Steps To Reproduce:

1.) Run a playbook
2.) A task fail
3.) Run it again, only execute the failed tasks
##### Expected Results:

Only failed task run
##### Actual Results:

All tasks are ran

**Comment by jimi-c** [comment]
# Question About This One

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute. Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:
- Ansible already provides support for retrying failed tasks by using the `until` and `retries` options for tasks (see http://docs.ansible.com/playbooks_loops.html#do-until-loops for more details). 

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always neccessary.

Thank you once again for this and your interest in Ansible!
