### ISSUE TITLE
mongodb_user works incorrectly with old pymongo

### ISSUE THREAD

**Issue by senz** [ansible/ansible#8899]
##### Environment:

OSX 10.7 -> Ubuntu precise
##### Summary:

mongodb_user works incorrectly with old pymongo (~2.1). 
Tested with 2.7.2, work correctly.
##### Steps To Reproduce:
- Fresh mongo instance with auth enabled, no users
- ansible host  -m mongodb_user -a "database=admin user=test roles=root password=test state=present"
##### Expected Results:

Creates new user
##### Actual Results:

Changed = false

This code block supposed to fail on non-existant user:

```
        try:
           client[db_name].authenticate(user, password)
           if state == 'present':
              module.exit_json(changed=False, user=user)
        except OperationFailure:
           if state == 'absent':
              module.exit_json(changed=False, user=user)
```

But it is exiting correctly and continue.

**Comment by mpdehaan** [comment]
From the above, do you mean it does not create the user and returns success?

I'm not sure why it should fail on a non-existant user when the command above is saying to create one, so perhaps I'm just misunderstanding your report.

**Comment by senz** [comment]
@mpdehaan correct, it cannot create user, but successfully returns with changed: false.
Also, changed: false is always returning in my case, with new or old version of pymongo, but new version actually creates user. Not proficient in python to investigate further in source code.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
