### ISSUE TITLE
apt_repository should allow the repo filename to be specified

### ISSUE THREAD

**Issue by gdevenyi** [ansible/ansible#8904]
##### Summary:

I request a feature to allow me to specify what filename the apt_repository creates

apt_repository: repo='deb http://archive.canonical.com/ubuntu hardy partner' state=present filename=hardy-partner.list
##### Steps To Reproduce:

When I add a repo such as:
deb http://dl.google.com/linux/talkplugin/deb/ stable main

A file is created named:
dl_google_com_linux_chrome_deb.list

When I install the package google-chrome-stable, which comes from this repo, it creates:
google-chrome.list

With the same repo content, so apt-get complains about duplicate entries 
##### Expected Results:

Clean repository
##### Actual Results:

Duplicated repo entries

**Comment by mscherer** [comment]
Can you try https://github.com/mscherer/ansible/tree/fix_8904 ? The patch is not polished ( no doc yet ) and I do not have a Debian server near me to test for now.

**Comment by gdevenyi** [comment]
How can I try out this fix?

**Comment by gdevenyi** [comment]
Traceback (most recent call last):
  File "/home/localadmin/.ansible/tmp/ansible-tmp-1410207370.38-227831542925412/apt_repository", line 2208, in <module>
    main()
  File "/home/localadmin/.ansible/tmp/ansible-tmp-1410207370.38-227831542925412/apt_repository", line 417, in main
    sourceslist.add_source(repo, file=filename)
NameError: global name 'filename' is not defined

**Comment by gdevenyi** [comment]
I think I haven't specified any filenames yet, I think there's an issue with that

**Comment by mscherer** [comment]
Ok, likely sloppy coding. let me find some debian hosts and correct my python

**Comment by mscherer** [comment]
So, I spun off a VM, tested on a Debian 6.0 and this work, the filename is taken in account. Just need to add some doc now

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
