### ISSUE TITLE
Docker module does not recognize when an image tag has changed

### ISSUE THREAD

**Issue by iragsdale** [ansible/ansible#8905]
##### Issue Type:

Bug Report
##### Ansible Version:

Current develop branch
##### Environment:

Ubuntu 12.04
##### Summary:

If you pull the latest version of a given named image, the docker image that name references will change, but any existing containers launched using that name are still using the old image. If you do a "docker inspect" on those containers, they still list the image name in Config->Image, but the top level Image property correctly references the original Image ID.

The existing code compares the name given in the Ansible configuration to the Config->Image property. So, if that image is updated, the Docker module will fail to relaunch the instance with the newly updated image, because the name has not changed. If it were to instead look up the ID that image name refers to and compare it to the top-level Image property, it would correctly recreate the container.

I think that behavior is likely to be very confusing - you'll have a newly downloaded image, but no running containers will have restarted to use it. This will happen whether the image is updated via the module or updated manually. I think this COULD be considered a Docker bug, but I think they would likely call that intended behavior.

I believe the correct thing to do would be to look up the current ID for a given image name and compare that to the top-level Image property for the container when deciding whether to recreate the container.
##### Steps To Reproduce:

Use the docker module to create & run a container based on a tagged image. Now create a new image with the same tag. Run the same task and note that the container does not change. Now delete that container and recreate it with the task and note that it uses the new image.
##### Expected Results:

I would expect the docker container to be recreated with the new image.
##### Actual Results:

The docker container is unchanged.

**Comment by mpdehaan** [comment]
I'm wondering if this should need a new parameter to force updates?

**Comment by iragsdale** [comment]
I would say yes.

**Comment by bfleming-ciena** [comment]
I think I have encountered this problem as well. Can someone confirm it is the same issue?

I started with a playbook like this, install a redis db and a tiny fake web server. And it worked FANTASTIC the first time. Ansible deployed my two containers.  Side Note: I'm running this all on  a local host. I don't need to deploy remotely. I just need a tool to server as a docker container installer/upgrader.

So here it is:
- hosts:  localhost 
  sudo: yes
  tasks:
  - name: ensure redis container is running
    docker: image=dockerfile/redis name=redis command=" bash -c 'redis-server  /etc/redis/redis.conf'"
  - name: ensure web container is running
    docker: image=snazzy/cyweb ports=5000:5000 links=redis:redis name=cyweb

Notice, my webapp is snazzy/cyweb.

OK, now I go and create a new image for snazzy/cyweb.  This is the latest right? So I'm pushing a new latest version.

When I re-run the playbook nothing happens.  The old version of the image is still running and no change is made. I expect ansible to see "Oh there is a new image for cyweb, shut down the old one, start up this new one".  That's how this is suppose to work, correct?

Thanks

**Comment by abadger** [comment]
What does docker itself do in these circumstances?  I know that I've found several places where I've updated an image or a dependency of a docker build and docker chooses to keep using the old thing instead of the new one.  I'm not sure if this is one of those cases, though.

Also, @iragsdale, is your ansible playbook like @stonefury's ?  I think that @stonefury's is actually doing the correct thing.  In this case, it looks like a long running process is being started in the cyweb container.  I would not expect ansible to restart that container by rerunning a task that simply defines that the container needs to be running.  If were specifying that the container needed to be restarted I think there might be a case to be made.  But again, I'd be hesitant to introduce different semantics than what docker itself would do with a similar command line.

**Comment by bfleming-ciena** [comment]
Hey @abadger.  If I were doing this manually, I would have to do:

1) destroy the current container
2) pull/run the new one

docker rm -f cyweb  (destroy the running container)

If I'm local, running snazzy/cyweb will run the latest version. We don't need to pull because we already have the latest locally.

If I am remote and my docker image is stored on a server, I will need to first run pull; We can do a pull even if is already local.  It will just be a no-op.
docker pull snazzy/cyweb
docker run snazzy/cyweb

Also note, I am naming the container "cyweb".  This is because I only want one cyweb container running at a time. By giving it a name docker will not allow two of these to run at once due to a name conflict.  If you omit the name, then docker will let you run multiple instances of the same container (assuming you let docker choose your public port. I explicitly define it as 5000:5000 in my example).

Let me know if I need to clarify.

Side Note:

I think a work-around for now is to add a task (assuming they are synchronous) that does a state=absent which tells ansible to destroy the container.  Then the next task is just the pull/run.  Then it will work, but I am doing the destroying of the container which should be ansible's job, I think. (I'm new to ansible).

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
