### ISSUE TITLE
Galaxy metadata broken for "Ansibles" account (no affiliation with Ansible) (was: Role-Alias does not work on 1.7.1)

### ISSUE THREAD

**Issue by robertkowalski** [ansible/ansible#8908]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

OSX
##### Summary:

Ansible seems to support something like aliases which don't work for me. Installing a package with dependencies works, but the downloaded dependencies get another name and are not found. The workaround for me is to rename the downloaded dependencies.
##### Steps To Reproduce:

```
ansible-galaxy install guillaumededrie.couchdb --roles-path=./provisioning/roles
```

Will install `guillaumededrie.couchdb` and `pjan.vandaele.build-essential` and `pjan.vandaele.erlang`, but the roles defines `Ansibles.erlang` and `Ansibles.build-essential` as dependencies: https://github.com/guillaumededrie/ansible-role-couchdb/blob/master/meta/main.yml#L19-L20
##### Expected Results:

Provisioning should work and role should not be missing.
##### Actual Results:

```
ERROR: cannot find role in /Users/robert/project/provisioning/roles/Ansibles.erlang
```

**Comment by mpdehaan** [comment]
This is because the user in question renamed their github account and needs to do a rebuild.

We're going to be taking care of the cleanup as a result of this soon.

cc @jimi-c

**Comment by jimi-c** [comment]
This should be resolved as of the Galaxy update today.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
