### ISSUE TITLE
Traceback in ansible-galaxy CLI

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#8909]
##### Summary:

Installing guillaumededrie.couchdb makes galaxy fail
##### Steps To Reproduce:

```
$ ansible-galaxy --roles-path=./roles install guillaumededrie.couchdb
- downloading role 'couchdb', owned by guillaumededrie
Traceback (most recent call last):
  File "/home/tomek/ansible/ansible/bin/ansible-galaxy", line 900, in <module>
    main()
  File "/home/tomek/ansible/ansible/bin/ansible-galaxy", line 894, in main
    fn(args, options, parser)
  File "/home/tomek/ansible/ansible/bin/ansible-galaxy", line 770, in execute_install
    print "- the specified version (%s) was not found in the list of available versions." % role.version
AttributeError: 'dict' object has no attribute 'version'
```

for the record, meta/main.yml from that role is:

```

---
# file: meta/main.yml

galaxy_info:
  author: Guillaume Dedrie
  description: "Install CouchDB"
  min_ansible_version: 1.4
  license: GPL3
  platforms:
    - name: Debian
      versions:
        - wheezy
  categories:
    - database
    - database:nosql
    - web

dependencies:
  - { role: Ansibles.erlang, erlang-version: "{{ erlang_version }}"  }
  - { role: Ansibles.build-essential }
```
##### Expected Results:

The role being installed
##### Actual Results:

See "Steps to reproduce"

**Comment by mscherer** [comment]
Here is a PR for fix that backtrace.

**Comment by jimi-c** [comment]
@mscherer I actually ran into this before I saw this ticket, and fixed it myself (there was a second issue as well, which was also corrected). So I will close this and your PR now as it is fixed.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
