### ISSUE TITLE
Ansible vault code, when no password is supplied, should indicate which file it needed a password for

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#8926]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8/devel
##### Environment:

N/A
##### Summary:

When running ansible against a repo that has a vault encrypted file buried somewhere within it, it will raise an error such as:

A vault password must be specified to decrypt data

This is painful as I then have to identify which file that was vault encrypted.
##### Steps To Reproduce:
1.  vault encrypt something
2.  run playbook
3.  see message
##### Expected Results:

A vault password must be specified to decrypt data, filename: ____
##### Actual Results:

A vault password must be specified to decrypt data

**Comment by mpdehaan** [comment]
note that vault doesn't always require filename usage at low API levels, so this should only be true when working on files, but should handle all usage of VaultLib.decrypt on a file.

**Comment by michalgasek** [comment]
That would be indeed great to have!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
