### ISSUE TITLE
Openstack Identity v3 not supported in nova cloud plugin

### ISSUE THREAD

**Issue by stenstad** [ansible/ansible#8934]
##### Issue Type:

Feature Idea
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

Auth has also moved from nova/cinder/etc-client into keystoneclient. Openstackclient uses this.
##### Steps To Reproduce:

Try to connect to an Openstack cloud using Identity v3.
##### Expected Results:

Auth successfully.
##### Actual Results:

No auth for you.

**Comment by jimi-c** [comment]
Thanks, I saw your comment on https://github.com/ansible/ansible/pull/8924 and agree that PR would probably be a good place to make this change.

**Comment by emonty** [comment]
Agree. We may need to start porting to openstacksdk to get it to work though, since cinderclient doesn't support using keystoneclient yet. /me stabs self.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
