### ISSUE TITLE
Registered variables can clear out hostvars

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#8968]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 239b6e79c3) last updated 2014/09/10 21:18:25 (GMT +000)
##### Environment:

CentOS 6.5
##### Summary:

After commit 10afaee108f9fd04ad45155b7977144304d77a1d when you register a variable from a task it can remove other hostvars.
##### Steps To Reproduce:

Run `ansible-playbook` with a play like this:

```
- hosts: all[0]
  gather_facts: true
  remote_user: sg
  tasks:
  - debug: var=hostvars[groups.all[0]].ansible_default_ipv4.address
  - command: ls /tmp
    register: foo
  - debug: var=hostvars[groups.all[0]].ansible_default_ipv4.address
```

It tries to debug the same variable (just the default ip address) both before and after running a simple `ls /tmp` command and registering the results.
##### Expected Results:

It should print the same output for both debug tasks.
##### Actual Results:

You get results like this:

```
PLAY [all[0]] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ec2-54-167-185-191.compute-1.amazonaws.com]

TASK: [debug var=hostvars[groups.all[0]].ansible_default_ipv4.address] ******** 
ok: [ec2-54-167-185-191.compute-1.amazonaws.com] => {
    "hostvars[groups.all[0]].ansible_default_ipv4.address": "10.101.201.36"
}

TASK: [command ls /tmp] ******************************************************* 
changed: [ec2-54-167-185-191.compute-1.amazonaws.com]

TASK: [debug var=hostvars[groups.all[0]].ansible_default_ipv4.address] ******** 
ok: [ec2-54-167-185-191.compute-1.amazonaws.com] => {
    "hostvars[groups.all[0]].ansible_default_ipv4.address": "{{ hostvars[groups.all[0]].ansible_default_ipv4.address }}"
}

PLAY RECAP ******************************************************************** 
ec2-54-167-185-191.compute-1.amazonaws.com : ok=4    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
