### ISSUE TITLE
feature request: Allow search for supervisor process names by regex

### ISSUE THREAD

**Issue by hahnicity** [ansible/ansible#8970]
##### Issue Type:

Feature request
##### Ansible Version:

1.7.1
##### Environment:

Any
##### Summary:

I've been trying to restart all of my supervisor processes for a specific app but because my playbook is meant to be used over mulitple different apps I do not know my exact supervisor process names so I am forced to search for them through a command.

```
- name: Get all supervisor tasks for {{ app_name }}
  shell: supervisorctl status | grep {{ app_name }} | awk '{print $1}'
  register: supervisor_tasks

- name: "Restart {{ app_name }} supervisorctl processes"
  supervisorctl: name="{{ item }}" state=restarted
  with_items: supervisor_tasks.stdout|split('\n')
```

It would be nice if I could just enter some kind of regex search into the name component and ansible would handle the gory details for me

```
- name: Restart {{ app_name }} supervisorctl processes
  supervisorctl: name="{{ app_name }}_*" state=restarted with_regex=yes
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
