### ISSUE TITLE
ec2_eip module creates new ip on repeated run

### ISSUE THREAD

**Issue by arnuschky** [ansible/ansible#8972]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04.1
##### Summary:

If an EC2 instance already has an EIP associated to it, I would expect the ec2_eip module to do nothing/reuse the existing IP. Instead, it creates a new IP and associates this.

Note that I am not asking for the functionality provided by `reuse_existing_ip_allowed`.
##### Steps To Reproduce:
1. Associate an EIP to any instance using the ec2_eip module, for example `- ec2_eip: instance_id=i-1212f003`
2. repeat
##### Expected Results:

An instance without an EIP gets a new one allocated.
An instance with an EIP gets the same one allocated (idempotent),
##### Actual Results:

An instance with an EIP gets the another new EIP allocated (no idempotent, every new run creates and allocated a new EIP)

**Comment by mpdehaan** [comment]
Can you please share the full invocation of the ec2_eip module as you have it in your playbook as well as the output of that module in verbose mode?

**Comment by arnuschky** [comment]
Sorry for late answer. Here's the playbook that creates an instance and associates an EIP.
(vpc and security group exist already)

```
- name: EIP module bug
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - include_vars: "aws/eip-bug/vpc_info"
    - name: Creating instance
      local_action:
        module: ec2
        key_name: "keyname"
        region: us-east-1
        group_id:
          - "{{ sg_default.group_id }}"
        instance_type: t2.micro
        image: "ami-0619bf6e"
        wait: yes
        vpc_subnet_id: "{{ subnet_test_id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Environment: "eip-bug"
          Class: eip-bug
        instance_tags:
          Environment: "eip-bug"
          Class: eip-bug
          Name: eip-bug
      register: instance
    - name: Allocating elastic IP to instance
      ec2_eip:
        in_vpc: yes
        reuse_existing_ip_allowed: yes
        state: present
        region: us-east-1
        instance_id: "{{ instance.tagged_instances[0].id }}"
      register: instance_eip
    - debug: var=instance_eip.public_ip
```

The instance task is idempotent thanks to exact_count/count_tag. The EIP task creates and associates a new EIP on every invocation. Accordingly, the number of EIPs increases; after 4 invocations the task fails due to Amazon's restriction to 3 unallocated EIPs.

EIP module output with -vvv:

```
TASK: [Allocating elastic IP to instance] ************************************* 
<127.0.0.1> REMOTE_MODULE ec2_eip region=us-east-1 state=present instance_id=i-xxx
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211 && echo $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211']
<127.0.0.1> PUT /tmp/tmpvxur9q TO /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ec2_eip
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/user/.pvenvs/ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ec2_eip; rm -rf /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ >/dev/null 2>&1']
changed: [127.0.0.1] => {"changed": true, "public_ip": "xx.xx.xx.xx"}
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by barraponto** [comment]
This issue is being worked on ansible/ansible-modules-core#300

**Comment by davidmweber** [comment]
This is still an active bug
```yaml
    - name: Allocate elastic IPs
      ec2_eip:
        region: "{{ region }}"
        reuse_existing_ip_allowed: yes
        state: present
```
creates a new address each time it runs. FYI, the issue https://github.com/ansible/ansible-modules-core/pull/300 indicates that a fix was implemented and then overwritten by a subsequent patch. It ends with referring us back to ansible. It is now 2017 and there is still no fix.

**Comment by andriipopryhin** [comment]
Yep, confirm - bug is still present. 
```
- name: Associating new instance with Elastic IP
  ec2_eip:
    reuse_existing_ip_allowed: yes
    region: "{{region}}"
    device_id: "{{ item }}"
  with_items: "{{ aws.instance_ids }}"
  tags:
    - aws_instance
  register: gerrit_eip

ansible 2.3.0.0
  config file = /home/username/Documents//project/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

**Comment by keras** [comment]
@andriipopryhin 

I had similar problem: I copypasted the task from the ec2_eip documentation. I got it to work by using `ec2`-modules `tagged_instances` property instead of `instance_ids`:

```
- name: Associate new elastic IPs with the instance
  ec2_eip:
    device_id: "{{ item.id }}"
    region: "{{ aws_region }}"
    in_vpc: true
  with_items: "{{ ec2.tagged_instances }}"
```
