### ISSUE TITLE
Ansible Galaxy: Add install option for cloning roles bare repository (.git) too

### ISSUE THREAD

**Issue by pschirch** [ansible/ansible#8992]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8 (devel 1c8f999e51) last updated 2014/09/12 13:21:50 (GMT +200)
##### Environment:

Ubuntu 14.04
##### Summary:

The `ansible-galaxy install` command clones the role repository without its bare repository.  For quick development it would be a pleasure when the roles bare repository could checked out too (like [Composer](https://getcomposer.org/) in PHP).

There should be an install option for that e.g. `-b, --bare clone roles with its bare repository`:

``` bash
ansible-galaxy install -help
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

Options:
  -b, --bare            clone role with its bare repository
  -h, --help            show this help message and exit
  -i, --ignore-errors   Ignore errors and continue with the next specified
                        role.
  -n, --no-deps         Don't download roles listed as dependencies
  -r ROLE_FILE, --role-file=ROLE_FILE
                        A file containing a list of roles to be imported
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfg file (/etc/ansible/roles if not
                        configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -f, --force           Force overwriting an existing role
```
##### Steps To Reproduce:

``` bash
ansible-galaxy install example-vendor.example-role -p roles
```
##### Expected Results:

``` bash
cd roles/example-vendor.example-role/
```

There should be the bare repository directory `.git` for quick development.
##### Actual Results:

Bare repository folder is missing.

**Comment by fago** [comment]
I'm missing this feature as well. Composer uses the --prefer-source option, so maybe it would be best to stick to the name as well. A bare git repository is something else; a checkout without  working copy - what is not what we want.

**Comment by jonpugh** [comment]
Drush make uses `--working-copy` as the name of it's option...

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
