### ISSUE TITLE
lineinfile should have an option to remove duplicate lines matched by regexp

### ISSUE THREAD

**Issue by ekini** [ansible/ansible#9006]
##### Issue Type:

Feature Pull Request
##### Ansible Version:

All versions.
##### Environment:

Ubuntu 14.04, and all other.
##### Summary:

The module "lineinfile" should have an option to remove duplicate lines matched by regexp.
Currently it changes only the last line. 
##### Steps To Reproduce:

Let's say that we have the following lines in sshd_config (don't ask me how I got this):

```
PasswordAuthentication yes
# some stuff
PasswordAuthentication yes
```

We run ansible as:

```
$ansible -c local -m lineinfile -a 'dest=./sshd_config  regexp="^[#\s]*PasswordAuthentication.*" line="PasswordAuthentication no"' localhost
```
##### Expected Results:

With an option like "remove_dups=yes" we would have:

```
# some stuff
PasswordAuthentication no
```
##### Actual Results:

```
PasswordAuthentication yes
# some stuff
PasswordAuthentication no
```

**Comment by piffey** [comment]
I could see this being potentially bad. For instance, if I have an sshd_config file and at the end have a bunch of match objects like:

```
Match User root
    PasswordAuthentication no

Match User user
    PasswordAuthentication no
```

I would end up losing one of those lines. There are a lot of config files with things like that and I think it'd be hard to make something that'd differentiate between necessary duplicates and unnecessary duplicates.

**Comment by ekini** [comment]
Fair enough. However, my patch adds "remove_dups" option, which is "no" by default, so it won't delete duplicates and won't break anything.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
