### ISSUE TITLE
Bug: LineInFile -- TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by superscott** [ansible/ansible#9033]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.4 (inside Vagrant VM)
##### Summary:

When passing in an integer to the lineinfile module, the following error is returned: 
`TypeError: object of type 'int' has no len()`

The [lineinfile module](https://github.com/ansible/ansible/blob/dc9482d54868f7abb1b453f77845a7ab927def00/library/files/lineinfile#L370) references the 'is_quoted' method being called from [/module_utils/splitter.py](https://github.com/ansible/ansible/blob/317ab06bc6bdecd8a3b9c254702d6d7ea7e334d9/lib/ansible/module_utils/splitter.py#L190)

The method tries to get the length of a integer, and fails as demonstrated below.

```
>>> len("hello")
5
>>> len("1")
1
>>> len(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'int' has no len()
```
##### Steps To Reproduce:

[Sample code to reproduce the error.](https://gist.github.com/superscott/55c65dc7aafd8c0f61c6)
I initially thought it was due to me incorrectly passing in the variable, but turned out removing the variable and putting in '2' still caused the same error.
##### Expected Results:

Be able to pass in an integer to the lineinfile module. 
##### Actual Results:

TypeError: object of type 'int' has no len()

**Comment by piffey** [comment]
Was curious about this one since I have some similar set ups. Went ahead and tried to reproduce with every combination of variable quoting, then turned to maybe it being a Trusty-specific bug so set up a VM there. I just can't get it to reproduce in the latest devel. Same problem if you use latest devel vs. 1.7.1 tag?

**Comment by superscott** [comment]
Yeah I can't reproduce on devel.

But after it worked on devel, i switched back to the version in apt, and the same error continues to happen. I also went back and pulled from git and switched to the 1.7.1 branch, and same thing is happening again, (just wanted to make sure it wasnt the version in apt that was causing issues). And for completeness, switched down to 1.7.0 branch, and same error occurred. 

I can provide the vagrant file, and setup script if there is a desire to use the exact same setup? 

More details: [updated my gist with more system info](https://gist.github.com/superscott/55c65dc7aafd8c0f61c6)
Python 2.7.6
Vagrant 1.6.3

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by papile** [comment]
If anyone else comes to this page, this is working for me in Ansible 1.7.2 now.  It was previously broken in 1.7.0.  So upgrade.
