### ISSUE TITLE
synchronize (rsync error) in ansible 1.7.*

### ISSUE THREAD

**Issue by aminjam** [ansible/ansible#9039]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

ubuntu 14.04
##### Summary:

I went through a lot of debugging to figure out that version 1.7.1 has errors with synchronize method. I was successful from my local machine which was running version 1.6.10. I was just trying to sync from a ubuntu to another ubuntu both running the same version of `rsync version 3.1.0  protocol version 31`. I ended up downgrading the server to ansbile version 1.6.10, and everything worked. This is the error I was seeing when running version 1.7.1
##### Steps To Reproduce:

Install ansible 1.7.1
 synchronize: src="/path/to/src" dest="/path/to/dest" delete=yes recursive=yes
##### Expected Results:

synchronize should've succeeded. 
##### Actual Results:

```
msg: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]
```

**Comment by ethervoid** [comment]
I wasn't able to reproduce yesterday using this playbook with version 1.7.1 and version 1.8-dev and rsync 3.1.1 in MacOSX

```
- name: test rsync
  synchronize: src="/tmp/foobar" dest="/home/ubuntu/foobar" delete=yes recursive=yes
```

**Comment by aminjam** [comment]
Here is a sample playbook that I am running. The problem I am facing is that I am running this playbook in `jenkins`, so my `aws.pem` file has `Permission 400` where the user is `jenkins`, so when I run my playbook using `-u ubuntu`, I believe the error is happening because the `ubuntu` user can't read the key from the disk (even though `-u` is referring t the remote user not the current running user), but since I am running that command as `sudo`, it shouldn't matter at all. Below is the playbook I created for testing, and the error I keep receiving. This error doesn't happen when I roll back my ansible to `version 1.6.10`. 

```
---
- name: test rsync
  hosts: "*"
  tasks:
    - name: rsync it
      sudo: yes
      synchronize: src="/home/ubuntu/foobar" dest="/foobar" delete=yes recursive=yes
```

Error:

```
msg: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
