### ISSUE TITLE
copy fails with unclear result when there is no space on device

### ISSUE THREAD

**Issue by kamilchm** [ansible/ansible#9054]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

Ansible copy module should show correct error message when there is no space left on device.
##### Steps To Reproduce:

```
- name: don't show no space error
  copy: dest=/small_file_system/ src=big_file
```
##### Expected Results:

```
/small_file_system/big_file: No space left on device
```
##### Actual Results:

```
failed: [user@server] => {"failed": true, "md5sum": "92d069893bc29fbde3d6405836e885a2", "parsed": false}
```

**Comment by jimi-c** [comment]
Hi @kamilchm, this was recently addressed in the devel branch. Using your example, the output is now:

<pre>
TASK: [don't show no space error] ********************************************* 
failed: [127.0.0.1] => {"failed": true, "md5sum": "efeebdda98ec1d7fb2ad83d23f0713bf"}
msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1411065376.98-106208610232862/source to mnt/test.file: [Errno 28] No space left on device
FATAL: all hosts have already failed -- aborting
</pre>

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
