### ISSUE TITLE
Service module incorrectly assumes service is restarted successfully

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#9056]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 6b1ae82acc) last updated 2014/09/18 09:30:54 (GMT +200)
##### Environment:

N/A
##### Summary:

The following block of code from the service module does not correctly check if a service has been restarted successfully:

```
    if rc != 0:
        if err and "is already" in err:
            # upstart got confused, one such possibility is MySQL on Ubuntu 12.04
            # where status may report it has no start/stop links and we could
            # not get accurate status
            pass
        else:
            if err:
                module.fail_json(msg=err)
            else:
                module.fail_json(msg=out)
```

The problem being, if `err` contains the word "is already" the service module assumes that the service has been successfully restarted.  This is particularly problematic if `err` contains "is already" and the service fails to start.  For example, in an apache configuration file, it's possible to define an apache module multiple times.  The init script will print to stderr:

`module proxy_ajp_module is already loaded, skipping`

At the same time, there may be other syntactical errors that would prevent Apache from starting altogether, but the service module believes the service is started.
##### Steps To Reproduce:

Easiest way to reproduce this is with Apache, but of course, any init script that contained "is already" in its std err when returning an rc !=0 would run into this problem.

on an EL6 machine, edit /etc/httpd/conf/httpd.conf

```
cat <<EOF >> /etc/httpd/conf/httpd.conf
LoadModule auth_basic_module modules/mod_auth_basic.so
BLARG
EOF
```
##### Expected Results:

Ansible should fail to start the Apache service because BLARG is invalid syntax, just like the service command does:

```
service httpd restart
Stopping httpd:                                            [FAILED]
Starting httpd: [Thu Sep 18 12:38:14 2014] [warn] module auth_basic_module is already loaded, skipping
Syntax error on line 1011 of /etc/httpd/conf/httpd.conf:
Invalid command 'BLARG', perhaps misspelled or defined by a module not included in the server configuration
                                                           [FAILED]
```
##### Actual Results:

Module claims that the service is started:

```
ansible -i inventory/hosts 10.42.0.6 -u vagrant -v -m service -a "name=httpd state=restarted" -s -v
<10.42.0.6> REMOTE_MODULE service name=httpd state=restarted
10.42.0.6 | success >> {
    "changed": true,
    "name": "httpd",
    "state": "started"
}
```

**Comment by kustodian** [comment]
`service` module for me always reports state changed for both `started` and `stopped` on the 1.8 devel branch.

**Comment by abadger** [comment]
I took a look at the upstart source code.  Looks like we could key off of "Job is already running" which would cut down on the likelihood of false positives.

**Comment by abadger** [comment]
@jsmartin Committed cc80b058c1d5e8a41c888e8daae036bda5865934 which checks for the longer string to cut down on this problem.  Let me know if it doesn't help.

@kustodian, that might be a different error than this.  If it continues even with this fix could you open a new bug report with information on what type of hosts you are managing, what your playbooks/commands are, and what ansible is reporting?

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
