### ISSUE TITLE
Role name variable available for tasks

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#9057]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.8
##### Environment:

Any
##### Summary:

I think it would be really nice to have some `role_name` available as variable in the tasks in same way as done for `role_path` https://github.com/ansible/ansible/commit/7051cdeb57d947a213803ca28a4e1a6a2f905d26 recently

For now we have few options to let tasks know about current role name
1) set variable on role definition (playbook level)
example

``` yaml
  roles:
    - { role: webserver, role_name: "webserver" }
```

2) extract role folder name from `role_path` with `regex_replace` filter (task level)
example

``` yaml
- hipchat: msg='{{ role_path | regex_replace('^.*/(.*)$', '\\1') }} | tasks finished'
           token="{{ hipchat_token }}"
           room="{{ hipchat_room }}"
           color="{{ hipchat_color }}"
```

Please let me know if  we already have way to get role name in tasks

Thanks in advance

**Comment by akuznecov** [comment]
Just found https://github.com/ansible/ansible/issues/4392 and related PR
Looks like my ticket is duplicate, in same time `role_names` is list of roles, but how we should get current role from it?

**Comment by aragnon** [comment]
I also would like to see this feature.

**Comment by bcoca** [comment]
or you can just use `{{role_path|basename}}`

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
