### ISSUE TITLE
Adding notifications for ec2_asg module

### ISSUE THREAD

**Issue by mschurenko** [ansible/ansible#9066]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.8
##### Environment:

N/A
##### Summary:

AWS autoscale groups support notifications when changes occur (instance is terminated, instance is launched, etc) as per http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/ASGettingNotifications.html
. Are their plans to add this functionality to the ec2_asg module? If not I can add it and submit a pull request. If this is already being done then I will leave it be. I tried searching pull requests and issues and couldn't find anything concerning this.

The way I would want it to work is as follows:

if state is present and notifications is true then apply notifications. 

if state is absent and notifications is false then disable notifications prior to actually deleting the asg. This way one will not get spammed with alerts. This would work well for me as ec2_asg is being used as part of our deploy process and I would want alerts to be silenced during deploys.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mschurenko** [comment]
I've started adding this and am now wondering if this should be added to ec2_asg or if it should be a separate module altogether? When one creates the asg there is no parameter to enable notifications, this must be done after the fact, the same when deleting. (This is going by boto docs).

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
