### ISSUE TITLE
[service module] state=restarted shuts down the proftpd service.

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#9069]
##### Issue Type:

 Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Debian GNU/Linux 7 64bit
##### Summary:

service module doesnt restart the proftpd service when pushing state=restarted, it shuts it down.
##### Steps To Reproduce:

REMOTE SERVER:

```
test:~# service proftpd status
ProFTPD is started in standalone mode, currently running.
test:~# test:~# netstat -lnp |grep proftpd
tcp6       0      0 :::21                   :::*                    LISTEN      21097/proftpd: (acc
```

ANSIBLE (restart ProFTPd)

```
ansible managed -i hosts.yml -m service -a "name=proftpd state=restarted" -u root -k -vv
SSH password: 
<192.168.6.6> REMOTE_MODULE service name=proftpd state=restarted
192.168.6.6 | success >> {
    "changed": true, 
    "name": "proftpd", 
    "state": "started"
}
```

REMOTE SERVER after the above command:

```
test:~# netstat -lnp |grep proftpd
test:~# 
test:~# service proftpd status
ProFTPD is started in standalone mode, currently not running.

last line in syslog:
Sep 19 08:41:35 localhost ansible-service: Invoked with name=proftpd pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default
```

Now when the service is down, if I run the same command again:

```
ansible managed -i hosts.yml -m service -a "name=proftpd state=restarted" -u root -k -vv
SSH password: 
<192.168.6.6> REMOTE_MODULE service name=proftpd state=restarted
192.168.6.6 | success >> {
    "changed": true, 
    "name": "proftpd", 
    "state": "started"
}
```

the service will start. so if the initial state is down the command end as expected with the proftpd service started.

REMOTE SERVER

```
test:~# service proftpd status
ProFTPD is started in standalone mode, currently running.
```

Also this is the manual restart output of ProFTPd when running it locally on Debian 7.

```
test:~# service proftpd status
ProFTPD is started in standalone mode, currently running.
test:~# service proftpd restart
[ ok ] Stopping ftp server: proftpd.
[....] Starting ftp server: proftpdtest proftpd[21287]: mod_tls_memcache/0.1: notice: unable to register 'memcache' SSL session cache: Memcache support not enabled
. ok 
test:~# service proftpd status
ProFTPD is started in standalone mode, currently running.
```

the "unable to register" notice is a debian bug.
##### Expected Results:

That the ProFTPd service should be up and running again when the command is compete
##### Actual Results:

ProFTPd shuts down from the service command above.

**Comment by mscherer** [comment]
I can reproduce on HEAD

**Comment by mscherer** [comment]
A work around is to use sleep=5 as a parameter.

```
root@test-debian:~/ansible# ansible -i '127.0.0.1,' -c local -m service -a "name=proftpd
state=restarted sleep=5" all
127.0.0.1 | success >> {
    "changed": true, 
    "name": "proftpd", 
    "state": "started"
}

root@test-debian:~/ansible# service proftpd status 
ProFTPD is started in standalone mode, currently running.
```

**Comment by mscherer** [comment]
So since I didn't explained, the problem come from the init script. it return before proftpd is shutted down, so ansible try to start right away and fail. One solution would be to try restart, and try start/stop if it fail.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
