### ISSUE TITLE
Access to inventory groups hierarchy

### ISSUE THREAD

**Issue by vespian** [ansible/ansible#9070]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

It would be nice to have a way of recreating inventory group hierarchy inside i.e. Jinja2 template.
##### Steps To Reproduce:

Our use case is auto-generating Icinga hostgroups. We wanted to recreate host/hostgroup hierarchy basing directly on our Ansible's inventory and thus manage host memberships directly from Ansible.

It would be nice if by some chance you found some time to implement a dictionary, i.e. group_children, with each key being a group and it's value being the list of its child-groups.

**Comment by srgvg** [comment]
The group hierarchy is something that is - since 1.7 - correct in the ansible inventory objects (It wasn't fully coherent before.)

Given I myself has some use cases to be able to use this kind of information, it would probably be best to discuss this on the mailing list, to see what is acceptable and how it should be implemented.

Could you perhaps start a discussion there?

**Comment by vespian** [comment]
@sergevanginderachter Sorry for the late reply. Sure, I will send an email, and we will see what others think about it.

Thanks.

**Comment by vespian** [comment]
ansible-devel post:

https://groups.google.com/forum/#!topic/ansible-devel/TAJZBF5OdRE

**Comment by mpdehaan** [comment]
I find it unlikely that we are going to do this, so I'm going to close this ticket.

The inventory API is available if you wanted to create a private facts module.

Will continue discussion on the devel list.
