### ISSUE TITLE
ec2_elb_lb always reports a changed state when specifying a https listener with certificate

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9073]
##### Issue Type:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made.
##### Ansible Version:

1.7.1
##### Environment:

Management Machine: Mac OS X 10.9.4, ansible 1.7.1 installed via homebrew
Target Machine: EC2 ELB
##### Summary:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made.  If I remove the HTTPS listener and only specify HTTP, the status is reported correctly.
##### Steps To Reproduce:
1. Create an ELB with the ec2_elb_lb module with a HTTP and HTTPS (with SSL certificate) listener.  The ELB will be provisioned.
2. Rerun the same task.  The status will report as changed even though no changes were made.
##### Expected Results:

Status should be ok on subsequent runs of the same task
##### Actual Results:

Status always shows as changed.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by teamdoug** [comment]
Oops, I timed my pull request creation poorly. I'll make a copy of this issue in the correct repo.
