### ISSUE TITLE
Control the location of retry files

### ISSUE THREAD

**Issue by Lekensteyn** [ansible/ansible#9093]
##### Issue Type:

Feature Idea.
##### Ansible Version:

ansible 1.7.1
##### Environment:

Arch Linux as client, Ubuntu as remote or client.
##### Summary:

Ansible always creates a `$HOME/HOST.retry` if a play fails and there is no way to prevent this. Over time, `$HOME` gets accumulated with useless ansible retry files. It would be nice if the creation of retry files can be controlled. E.g.:

```
# Use a different directory to store retry files.
ansible-playbook -i some.inventory --retries-dir=$HOME/.ansible/retries/
# Disable creation of retry files
ansible-playbook -i some.inventory --retries-dir=
```
##### Steps To Reproduce:
1. Run a playbook that fails
##### Expected Results:

No retry file should be created in `$HOME`. If it does, it should create stuff under `$HOME/.ansible/`.
##### Actual Results:

A retry file is created for the inventory.

**Comment by CleanCut** [comment]
Looks like this has been implemented, but not merged:

https://github.com/ansible/ansible/pull/9404

**Comment by svenstaro** [comment]
Can't this be closed?

**Comment by abadger** [comment]
#9404 has been merged so yes, thank you for pointing that out!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
