### ISSUE TITLE
umask command throwing directory not found

### ISSUE THREAD

**Issue by bputt** [ansible/ansible#9101]
##### Steps To Reproduce:

I am trying to run the following:

```
#this file is inside roles/configuration/tasks/main.yml
- name: Configure umask to 027
  command: umask 027
```

The playbook is:

```
- name: Hardening server
  hosts: security-update
  sudo: true
  sudo_user: root
  roles:
    - configuration
```
##### Actual Results:

```
failed: [host] => {"cmd": "umask 027", "failed": true, "rc":2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting
```

**Comment by mscherer** [comment]
Umask is a internal bash builtin command, not a external one, so this cannot be started by command module. You could do that with shell, but even that, since it only apply to the current process and descendents, this would have no effect at all if run by ansible, since it will disappear as soon as the task is finished

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated. As @mscherer notes above, the umask command is a bash shell command.

We would suggest:
- Use the `shell` module instead of `command`, and use a semi-colon to separate the commands as follows: `shell: umask 027; /path/to/cmd --options...`

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
