### ISSUE TITLE
docker module does not ensure image present

### ISSUE THREAD

**Issue by constfun** [ansible/ansible#9104]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

Controlling os: OS X
Target os: Ubuntu 14.04 LTS
##### Summary:

The docker module always reports OK, even if the image is not present.
##### Steps To Reproduce:

```

---
- name: Pull the docker image.
  docker: image="sylvainlasnier/memcached" state=present
```
##### Expected Results:

I would expect the image to be downloaded and the play to report "changed."
##### Actual Results:

```
==> mta.vagrant: Running provisioner: ansible...

PLAY [-redacted-] ********************************* 

GATHERING FACTS *************************************************************** 
ok: [mta.vagrant]

TASK: [docker | add apt key for docker repository] **************************** 
ok: [mta.vagrant]

TASK: [docker | add apt sources for docker repository] ************************ 
ok: [mta.vagrant]

TASK: [docker | install docker] *********************************************** 
ok: [mta.vagrant]

TASK: [docker | install pip] ************************************************** 
ok: [mta.vagrant]

TASK: [docker | install docker python client] ********************************* 
ok: [mta.vagrant]

TASK: [docker_container | Pull the docker image.] ***************************** 
ok: [mta.vagrant]

PLAY RECAP ******************************************************************** 
mta.vagrant                : ok=7    changed=0    unreachable=0    failed=0   

```

```
% vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
