### ISSUE TITLE
Variables no longer useable unless all templated members resolveable.

### ISSUE THREAD

**Issue by rektide** [ansible/ansible#9132]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.8 (devel 86edd0381c)
##### Environment:

Debian Testing
##### Summary:

It has become impossible to make any use whatsoever of a variable which has a member whose value is an expression that is not yet resolvable.
##### Steps To Reproduce:

Sample playbook which used to work:

```
- hosts: all
  vars:
    pointer: "foo"
    foo: "one"
    bar: "{{tbd}}"
  tasks:
  # this first line will fail, saying: fatal: [127.0.0.1] => One or more undefined variables: 'tbd' is undefined
  - debug: msg="{{vars[pointer]|default('nope')}}"
```

https://gist.github.com/rektide/164b80c9b120361759b2
##### Expected Results:

Historically, one would have gotten:

```
TASK: [debug msg="{{vars[pointer]|default('nope')}}"] ************************* 
ok: [127.0.0.1] => {
    "msg": "one"
}
```
##### Actual Results:

```
TASK: [debug msg="{{vars[pointer]|default('nope')}}"] ************************* 
fatal: [127.0.0.1] => One or more undefined variables: 'tbd' is undefined
```
##### Horrible Workaround:

Turn `{{tbd}}` into `{{tbd|default()}}`.

**Comment by mpdehaan** [comment]
Urg, we'll look at this ASAP.

FWIW, the value of  vars['pointer'] in the above is foo, there's not a variable indirection in your above example, but that shouldn't affect the error.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rektide** [comment]
Yup! Tested last night, works. Thanks thanks thanks!
