### ISSUE TITLE
unarchive module extracts archives even when using ansible-playbook --check

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#9140]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.8 (devel 86edd0381c) last updated 2014/09/25 10:27:37 (GMT -400)
##### Environment:

N/A
##### Summary:

unarchive module extracts data even when using ansible-playbook --check.
##### Steps To Reproduce:

playbook

```
- hosts: localhost
  connection: local
  tasks:
  - name: extract archive
    unarchive: src=/tmp/test.tar.gz dest=/tmp copy=no
```

invocation:

```
ansible-playbook -v test.yml -i hosts --check
```
##### Expected Results:

A dry run of the playbook would occur
##### Actual Results:

make sure file is not there:

```
rm -rf /tmp/test
```

run the playbook in check mode:

```
ansible-playbook -v test.yml -i hosts --check

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [extract archive] *******************************************************
changed: [localhost] => {"changed": true, "check_results": {"cmd": "/usr/bin/tar -v -C \"/tmp\" --diff -zf \"/tmp/test.tar.gz\"", "err": "tar: Option --diff is not supported\nUsage:\n  List:    tar -tf <archive-filename>\n  Extract: tar -xf <archive-filename>\n  Create:  tar -cf <archive-filename> [filenames...]\n  Help:    tar --help\n", "out": "", "rc": 1, "unarchived": false}, "dest": "/tmp", "extract_results": {"cmd": "/usr/bin/tar -xzf \"/tmp/test.tar.gz\"", "err": "", "out": "", "rc": 0}, "gid": 0, "group": "wheel", "handler": "TgzFile", "mode": "0755", "owner": "root", "size": 11, "src": "/tmp/test.tar.gz", "state": "link", "uid": 0}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

check if file is there:

```
ls -l /tmp/test
total 0
-rw-r--r--  1 jmartin  wheel  0 Sep 25 10:11 foo
```

**Comment by jsmartin** [comment]
other modules possibly affected:

synchronize

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
