### ISSUE TITLE
how to do make ansible document with pdf format

### ISSUE THREAD

**Issue by canshen-yottaa** [ansible/ansible#9159]
##### Issue Type:

Feature Idea
##### Ansible Version:

devel branch
##### Environment:

mac os 
##### Summary:

I has enter to the ansible docsite directory， I can not found pdf parameter in Makefile.
If I wanto make pdf format document , how to do ?
##### Expected Results:

can not run
##### Actual Results:

 I can not found pdf parameter in Makefile

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi @canshen-yottaa, thanks for your request!

Unfortunately, we have in the past declined to have the documentation output in PDF format for a variety of reasons (you can search here and on the ML for previous examples), so we're going to go ahead and close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ghost** [comment]
This is still a problem. The main thread for this issue is #4265.
