### ISSUE TITLE
lineinfile module does not insert line in some situations

### ISSUE THREAD

**Issue by 0x44** [ansible/ansible#9166]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8 (devel 6af5455edc) last updated 2014/09/26 15:16:29 (GMT +800)
```
##### Environment:

Mac OS X Mavericks (10.9.5) manages Debian GNU/Linux 7.6 (wheezy)
##### Summary:

When there's a line same as the one to be inserted exists elsewhere, lineinfile module does not do the insertion.
##### Steps To Reproduce:

```
@managed$ cat test.txt
1
3
4
2

@managing$ cat test.yml

---
- hosts: managed
  tasks:
    - lineinfile:
        dest=~/test.txt
        insertafter=^1$
        line=2
```
##### Expected Results:

```
@managed$ cat test.txt
1
2
3
4
2
```
##### Actual Results:

```
@managed$ cat test.txt
1
3
4
2
```

(Nothing changed.)

**Comment by jimi-c** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated. In particular, we believe you have said:
- The lineinfile module is not working as expected.

However, however what is happening is that:
- The module will only insert the line if it is not already found in the file. Because the line "2" in your example exists, the module is not inserting it again.

We would suggest:
- If you are trying to relocate a line, use the module to first remove the existing line prior to inserting it in the correct location.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
