### ISSUE TITLE
As of 1.7.2 lineinfile not inserting double single quotes

### ISSUE THREAD

**Issue by PriceChild** [ansible/ansible#9171]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Debian Sid
##### Summary:

Using the gist at https://gist.github.com/anonymous/dc1de03995dc9ae147af in ansible 1.7.1 correctly forces a line with `synchronous_standby_names=''` in it.

With 1.7.2, it enforces a line with `synchronous_standby_names=`.

I have confirmed it is definitely a difference between 1.7.1 & 1.7.2 by swapping between:
sudo dpkg -i /var/cache/apt/archives/ansible_1.7.1+dfsg-1_all.deb
sudo dpkg -i /var/cache/apt/archives/ansible_1.7.2+dfsg-1_all.deb

Looking at the patches debian applies, that shouldn't be related. Time for a git bisect!
##### Steps To Reproduce:

Use the task in the linked gist.
##### Expected Results:

A line with `synchronous_standby_names=''` should appear in the file.
##### Actual Results:

`synchronous_standby_names=` appears in the file.

**Comment by PriceChild** [comment]
Checked out master and found the issue has already been resolved!

Ran a git bisect and found the fixing commit was 085ba4ffd828f0ee24fca84f9200084ff8c3580d so it turns out this issue is a duplicate of #8806

Edit: I must be using git bisect incorrectly... that commit was included in v1.7.2? I'll see if I can figure out what's up and report back. It'd be nice to have this fixed for 1.7 rather than 1.8?

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
