### ISSUE TITLE
role vars overridden by vars of a dependent role

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9178]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Linux CentOS 6.5
##### Summary:

role variables values are being overridden by values of variables with the same name from a second role that depends on the first one.
###### playbook

<pre>
- hosts: all
  roles:
    - role-hadoop
</pre>

###### role-hadoop

roles/role-hadoop/tasks/main.yml:

<pre>
- name: print install_dir variable
  debug: msg="install dir is {{ install_dir }}"
</pre>

roles/role-hadoop/vars/main.yml:

<pre>
install_dir: /opt/hadoop
</pre>

roles/role-hadoop/meta/main.yml:

<pre>
dependencies:
  - { role: role-java }
</pre>

###### role-java

roles/role-java/tasks/main.yml:

<pre>
- name: print install_dir variable
  debug: msg="install dir is {{ install_dir }}"
</pre>

roles/role-java/vars/main.yml:

<pre>
install_dir: /opt/java
</pre>

##### Expected Results:

<pre>
TASK: [role-java | print install_dir variable] ********************************** 
ok: [192.168.50.100] => {
    "msg": "install dir is /opt/java"
}

TASK: [role-hadoop | print install_dir variable] ********************************** 
ok: [192.168.50.100] => {
    "msg": "install dir is /opt/hadoop"
}
</pre>

##### Actual Results:

<pre>
TASK: [role-java | print install_dir variable] ********************************** 
ok: [192.168.50.100] => {
    "msg": "install dir is /opt/hadoop"
}

TASK: [role-hadoop | print install_dir variable] ********************************** 
ok: [192.168.50.100] => {
    "msg": "install dir is /opt/hadoop"
}
</pre>

**Comment by mpdehaan** [comment]
Thanks for the report.

Roles should definitely be able to access variables from other roles, but they should be guaranteed that the role variables they use are defined if that role if the same names are used - this is the "no clobbering" protection that exists between roles in ansible, and should exist for role deps as well.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
