### ISSUE TITLE
setup module fails with "/bin/sh: 1: powershell: not found\r\n"

### ISSUE THREAD

**Issue by fxlv** [ansible/ansible#9184]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible 1.8 (devel ffee9a8fe0) last updated 2014/09/27 22:27:21 (GMT +300)`
##### Environment:

Tested on Debian Wheezy 7.6 and OSX 10.9.5
##### Summary:

Running any module or playbook that collects facts (runs setup module) fails.
##### Steps To Reproduce:

`ansible -m setup localhost`
##### Expected Results:

Expected it not to fail.
##### Actual Results:

running `ansible -m setup localhost`
returns

```
localhost | FAILED >> {
    "failed": true,
    "msg": "/bin/sh: 1: powershell: not found\r\n",
    "parsed": false
}
```

All problems, including #9183 start with commit e5116d2f9bd851949ae50e0c9c112750e7cec761
Module path broken?

**Comment by philm** [comment]
Confirmed at my end too, same commit, on Ubuntu 14.04.

Also found this [recent post](http://tech.barwick.de/development/ansible-error-powershell-not-found.html) confirming the same thing with some additional details.

**Comment by philm** [comment]
Dug around some more. When https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L1216 is being called for the "setup" module, it's returning setup.ps1. This is because https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/plugins.py#L164 doesn't have a value for suffixes and self.class_name.

**Comment by philm** [comment]
...when self.class_name is None and https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/plugins.py#L175 is called, the first path that is checked ends with ".ps1", for example:

../ansible-modules-core/windows/setup.ps1

which represents a valid file path, thus the function exits, and returns "/setup.ps1" up the stack, and then gets interpreted as a Powershell call. 

I don't know enough about the internals here to muck around with a  PR but a temporary hack if you don't need to deal with any Windows machines is to modify https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/plugins.py#L168 to

```
suffixes = ['', '.py']
```

**Comment by mpdehaan** [comment]
I'm looking into this right now, thanks.

**Comment by mpdehaan** [comment]
Hi!

A change has been applied for this ticket on the development branch, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
