### ISSUE TITLE
Wrong ansible_distribution_version for Mageia

### ISSUE THREAD

**Issue by htgoebel** [ansible/ansible#9217]
Issue Type: Bug Report
Ansible Version: 1.7.2
Environment: N/A
Summary: Wrong distribution_version for Mageia
Steps To Reproduce:

run `ansible -m setup mageia-host | grep -iE (Mageia|ansible_distribution)'`

Expected Results (shortened):

```
"ansible_distribution_major_version": "4",
"ansible_distribution_version": "4",
```

Actual Results (shortened):

```
"ansible_distribution_major_version": "4",   <------- this one is correct
"ansible_distribution_version": "release",    <------- should be "4", too
```

**Comment by mpdehaan** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module (the setup module), and aside from action_plugins, if you know what those are, the modules in ansible are now moved two seperate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by htgoebel** [comment]
No, this is not a bug in the setup module, as this has barely any logic.

The bug is in lib/ansible/module_utils/facts.py `Fact.get_distribution_facts()`. There _every_ existing file listed in `OSDIST_DICT` is tested. This order of the tests is undetermined, as they are stored in a dict. Thus for a Linux distribution having several compatible release-files (as Mageia has), the result is unpredictable.
