### ISSUE TITLE
role variables in vars_files overriding each other

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9219]
This has come and gone over the previous releases, and is currently present on the devel branch.

To reproduce:

roles/test1/vars/main.yml:

```
myvar: test1
```

roles/test2/vars/main.yml:

```
myvar: test2
```

both roles' task file is:

```
- debug: var=myvar
```

and the playbook:

```
- hosts: localhost
  roles:
    - test1
    - test2
```

The results should be:

```
TASK: [test1 | debug var=myvar] *********************************************** 
ok: [localhost] => {
    "myvar": "test1"
}

TASK: [test2 | debug var=myvar] *********************************************** 
ok: [localhost] => {
    "myvar": "test2"
}
```

But are actually:

```
TASK: [test1 | debug var=myvar] *********************************************** 
ok: [localhost] => {
    "myvar": "test2"
}

TASK: [test2 | debug var=myvar] *********************************************** 
ok: [localhost] => {
    "myvar": "test2"
}
```

`git bisect` points to 8a1fbed5d6a61583950024df60ac74d5c98d6cca

**Comment by jimi-c** [comment]
Hi @hkariti, I do have a feature branch for refactoring roles code quite a bit which resolves this, if you'd like to give it a try:

https://github.com/jimi-c/ansible/compare/class_based_roles

I've tested it against your small sample above, which produces the correct output. Previous to the commit you reference in your bisect, the vars were winning in a slightly different (and weirder way) - that patch attempted to make the winning order more sane but it did expose the problem you're seeing.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Also for follow-up, we have not merged in the above referenced feature branch, the above commit resolved the issue by taking some portions of that code and porting it to the existing devel branch.

**Comment by hkariti** [comment]
Thanks a lot! 
Also, cool branch. Looks like a good refactoring :)
