### ISSUE TITLE
Variables are not preserved between plays

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#9231]
##### Issue Type:

Bug Report
##### Ansible Version:

From Ansible v1.6.2+ to current Ansible devel
##### Environment:

Debian, Ubuntu
##### Summary:

Variables defined in a play are not preserved in the next play (undefined). Bug has been bisected to https://github.com/ansible/ansible/commit/8851ceaa9e9ad6e5052ba8186094fe4fc605f9a2 commit. This bug also affects some other types of variables, for example variables defined in a role defaults when role is used as a dependency of other roles, and not included in a play directly.
##### Steps To Reproduce:

```

---

- hosts: all
  vars:
    static_var: 'Some string'

  tasks:
    - debug: var=static_var

- hosts: all

  tasks:
    - debug: var=static_var
```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [helios]

TASK: [debug var=static_var] ************************************************** 
ok: [helios] => {
    "static_var": "Some string"
}

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [helios]

TASK: [debug var=static_var] ************************************************** 
ok: [helios] => {
    "static_var": "Some string"
}

PLAY RECAP ******************************************************************** 
helios                     : ok=4    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [helios]

TASK: [debug var=static_var] ************************************************** 
ok: [helios] => {
    "static_var": "Some string"
}

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [helios]

TASK: [debug var=static_var] ************************************************** 
ok: [helios] => {
    "static_var": "{{ static_var }}"
}

PLAY RECAP ******************************************************************** 
helios                     : ok=4    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
hostvars are preserved, play vars should not be preserved, they are 'play
scoped'.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by jimi-c** [comment]
I believe @bcoca is correct here - any var set via something like `register:` or `set_fact` will be available across plays, however things defined specifically within a play's `vars:` or `vars_files:` should not be. It is curious that this worked prior to the version you noted, however I would consider this a fixed bug rather than a new bug.

If you'd like to discuss this further, please stop by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
