### ISSUE TITLE
extra_vars don't override variables in vars_files

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9242]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 43eb821d3f) last updated 2014/10/02 08:44:04 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 617a52b20d) last updated 2014/09/28 12:24:37 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2014/09/28 12:24:41 (GMT +000)
  configured module search path = None
##### Environment:

Ubuntu 12.10
##### Summary:

Overriding variables with `-e` doesn't work on variables in vars_files.

Bisecting points to 8a1fbed5d6a61583950024df60ac74d5c98d6cca (again, sorry James :\ )
##### Steps to reproduce:

var_file:

```
var: 1
```

playbook:

```

---
- hosts: localhost
  gather_facts: no
  vars_files:
    - var_file
  tasks:
    - debug: var=var
```

command:

```
ansible-playbook playbook.yml -e var=2
```
##### Expected Results:

```
TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "2"
}
```
##### Actual Results:

```
TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "1"
}
```

**Comment by jimi-c** [comment]
Hi @hkariti, I just tried this against devel and it appears fixed:

<pre>
TASK: [debug var=var] ********************************************************* 
ok: [127.0.0.1] => {
    "var": "2"
}
</pre>

I even backed up to a commit on Oct. 1st and it still worked, so I'm not quite sure what your issue might be.

**Comment by hkariti** [comment]
Ok, this is working correctly for me too now. But I still think I'm not crazy. I managed to reproduce it again with the latest dev, but with inventory vars + regular vars and not vars_file:

inventory:

```
localhost ansible_connection=local
[all:vars]
var=1
```

playbook:

```
---
- hosts: localhost
  gather_facts: no
  vars:
    var2: "{{var}}"
  tasks:
    - debug: var=var2
    - debug: var=var
```

command:

```
ansible-playbook -i inventory playbook.yml -e var=2
```

output:

```

TASK: [debug var=var2] ******************************************************** 
ok: [localhost] => {
    "var2": "1"
}

TASK: [debug var=var] ********************************************************* 
ok: [localhost] => {
    "var": "2"
}
```

**Comment by jimi-c** [comment]
Yeah that's an odd one, but should be easy to fix. Looking into this now.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by hkariti** [comment]
Thanks!
