### ISSUE TITLE
Bug fix: atfork import warning displayed even when system_warnings = False

### ISSUE THREAD

**Issue by bpennypacker** [ansible/ansible#9247]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

 1.8 (latest)
##### Environment:

Amazon Linux AMI release 2013.03 (RHEL 5 compatible)
##### Summary:

Ansible 1.6 added the system_warnings = False option to disable system warnings.  This pull request updates how atfork is imported so that it calls system_warning if an PowmInsecureWarning exception is raised.  It is now functionally similar to how keyczar is imported in lib/ansible/utils/**init**.py.
##### Steps To Reproduce:

Set system_warnings = False when an older version of gmp is in use.  Ansible will still display a warning message along the lines of:

/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
##### Expected Results:

When system_warnings = False this warning should not be displayed
##### Actual Results:

When system_warnings = False this warning is still displayed.  This patch fixes this issue.
##### Pull Request:

https://github.com/ansible/ansible/pull/9248

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
