### ISSUE TITLE
Module embedding in roles is broken

### ISSUE THREAD

**Issue by sampierson** [ansible/ansible#9263]
Since the submodule refactor, embedded modules do not work, unless they are used in the first play in a playbook.   I just spent half a day narrowing this down, and I have created a simple example that demonstrates this behavior at https://github.com/omadahealth/example-playbook.git

The only difference between broken.yml and works.yml is the order of the plays:

```
 $ ansible --version
 ansible 1.8 (devel 402d0c37b8) last updated 2014/10/03 10:21:02 (GMT -700)
   lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/03 10:21:08 (GMT -700)
   lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/03 10:21:13 (GMT -700)
   configured module search path = None

 $ ansible-playbook -i inventory broken.yml 
 ERROR: embedded_module is not a legal parameter in an Ansible task or handler

 $ ansible-playbook -i inventory works.yml 

 PLAY [Demonstrate embeded modules stopped working] **************************** 
 TASK: [role-with-embedded-module | Invoke embedded module] ******************** 
 changed: [localhost]
 PLAY [Play the First] ********************************************************* 
 TASK: [another_role | What time is it?] *************************************** 
 changed: [localhost]
 PLAY RECAP ******************************************************************** 
 localhost                  : ok=2    changed=2    unreachable=0    failed=0   
```

It works file with ansible 1.7.1.  Both play books run to completion.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
