### ISSUE TITLE
Ansible Galaxy does not support README.rst in roles

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#9269]
##### Issue Type:

Bug Report
##### Ansible Version:

N/A
##### Environment:

N/A
##### Summary:

After converting README files of my roles to reStructuredText fornat, I cannot re-import them in Ansible Galaxy web interface.
##### Steps To Reproduce:

Create a role with `README.rst` file and without `README.md`.
##### Expected Results:

Roles are updated and imported correctly.
##### Actual Results:

FAILED:
Failed to find a README.md. All role repositories must include a README.md. Please refer to the 'Getting Started' documentation regarding role requirements. Once the issue has been corrected in the repsotitory, you can retry the import.

**Comment by mpdehaan** [comment]
We keep our galaxy tickets in another tracker, so this is just a note to indicate we have noted and recorded this idea.

Thanks!

**Comment by GR360RY** [comment]
In case ansible-galaxy has a public issue tracker, is it possible to subscribe to this "moved" issue ?

**Comment by dfarrell07** [comment]
> In case ansible-galaxy has a public issue tracker, is it possible to subscribe to this "moved" issue ?

+1, is there a public issue we can use to tack this?

**Comment by ypid** [comment]
I am also curious if there is a public issue tracker for this because I am getting the same error message but for an unknown reason.

What I did: I tried to re-import some of my roles yesterday but I got the message:

> FAILED:
> Failed to find a README.md. All role repositories must include a README.md. Please refer to the 'Getting Started' documentation regarding role requirements. Once the issue has been corrected in the repsotitory, you can retry the import.

(Note the typo: repsotitory)

So I tried to re-import all other of my roles to see if there is some hint. Unfortunately I could not find any correlation.

Roles that can be re-imported:
- https://galaxy.ansible.com/list#/roles/2807
- https://galaxy.ansible.com/list#/roles/2980
- https://galaxy.ansible.com/list#/roles/3015
- https://galaxy.ansible.com/list#/roles/3042
- https://galaxy.ansible.com/list#/roles/3314
- https://galaxy.ansible.com/list#/roles/3315
- https://galaxy.ansible.com/list#/roles/3778
- https://galaxy.ansible.com/list#/roles/3980
- https://galaxy.ansible.com/list#/roles/4109
- https://galaxy.ansible.com/list#/roles/4557
- https://galaxy.ansible.com/list#/roles/4559
- https://galaxy.ansible.com/list#/roles/4633
- https://galaxy.ansible.com/list#/roles/4649
- https://galaxy.ansible.com/list#/roles/4668
- https://galaxy.ansible.com/list#/roles/4752

Roles that can not be re-imported (due to the noted error):
- https://galaxy.ansible.com/list#/roles/2758
- https://galaxy.ansible.com/list#/roles/4054
- https://galaxy.ansible.com/list#/roles/4058
- https://galaxy.ansible.com/list#/roles/4113
- https://galaxy.ansible.com/list#/roles/4114
- https://galaxy.ansible.com/list#/roles/4558
- https://galaxy.ansible.com/list#/roles/4749

BTW: All the roles do include a `README.md` and some of the roles which can not be re-imported have not been changed for a while …

**Comment by cchurch** [comment]
@GR360RY @dfarrell07 @ypid - https://github.com/ansible/galaxy-issues has been setup for issues like these.

**Comment by ypid** [comment]
Thanks.
