### ISSUE TITLE
group_vars are not applied for inlined inventory when using ad-hoc command

### ISSUE THREAD

**Issue by danielsiwiec** [ansible/ansible#9278]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

OSX 10.9.4
##### Summary:

The group_vars/all are not applied, when using ansible ad-hoc command and inlined inventory. I submitted this in a comment to issue https://github.com/ansible/ansible/issues/6563 but it looks like it's a separate problem.
##### Steps To Reproduce:

I'm running the debug module with the inventory passed either through a file or inlined. In the latter option, the variable is not picked up.

```
[dsiwiec@NAdsiwiec /tmp]$ ansible --version
ansible 1.7.2

[dsiwiec@NAdsiwiec /tmp]$ more inv
192.169.0.10

[dsiwiec@NAdsiwiec /tmp]$ more group_vars/all.yml
my_var: Hello, I'm group var

[dsiwiec@NAdsiwiec /tmp]$ ansible all -m debug -a var=my_var -i inv
192.169.0.10 | success >> {
    "my_var": "Hello, I'm group var"
}

[dsiwiec@NAdsiwiec /tmp]$ ansible all -m debug -a var=my_var -i "192.169.0.10,"
192.169.0.10 | success >> {
    "my_var": "{{ my_var }}"
}
```

My understanding is that the inlined hosts are assigned the **all** group, like it is with the inventory file in case you don't enclose the host with a group tag (_vide_ my first invocation of ansible). This is also how the inlined inventory works for the **ansible-playbook** command, where the host is clearly matched with the **all** group:

```
[dsiwiec@NAdsiwiec /tmp]$ more playbook.yml
- hosts: all
  gather_facts: false
  tasks:
    - debug: var=my_var

[dsiwiec@NAdsiwiec /tmp]$ ansible-playbook playbook.yml -i "192.169.0.10,"

PLAY [all] ********************************************************************

TASK: [debug var=my_var] ******************************************************
ok: [192.169.0.10] => {
    "my_var": "Hello, I'm group var"
}

PLAY RECAP ********************************************************************
192.169.0.10    : ok=1    changed=0    unreachable=0    failed=0
```
##### Expected Results:

```
[dsiwiec@NAdsiwiec /tmp]$ ansible all -m debug -a var=my_var -i "192.169.0.10,"
192.169.0.10 | success >> {
    "my_var": "Hello, I'm group var"
}
```
##### Actual Results:

```
[dsiwiec@NAdsiwiec /tmp]$ ansible all -m debug -a var=my_var -i "192.169.0.10,"
192.169.0.10 | success >> {
    "my_var": "{{ my_var }}"
}
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible all -m debug -a var=my_var -i inv
foo | SUCCESS => {
    "verbose_always": true, 
    "my_var": "Hello, I'm group var", 
    "changed": false
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
