### ISSUE TITLE
Debian build of Ansible fails with 'cannot import name vvv'

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#928]
Hello,

It looks like the Debian installer has made a mess with ansible.callbacks: it cannot import vvv from ansible.callbacks, and looking at PyDoc, it seems that callback.py is not recognized, while callbacks package can be seen. Other projects use the singular form for modules, for example Cheetah has a template module and templates package.

ansible-playbook myplaybook.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 24, in <module>
    import ansible.playbook
  File "/usr/lib/pymodules/python2.7/ansible/playbook/**init**.py", line 19, in <module>
    import ansible.runner
  File "/usr/lib/pymodules/python2.7/ansible/runner/**init**.py", line 36, in <module>
    import connection
  File "/usr/lib/pymodules/python2.7/ansible/runner/connection.py", line 26, in <module>
    modules = utils.import_plugins(os.path.join(dirname, 'connections'))
  File "/usr/lib/pymodules/python2.7/ansible/utils.py", line 463, in import_plugins
    modules[name] = imp.load_source(name, path)
  File "/usr/lib/pymodules/python2.7/ansible/runner/connections/local.py", line 23, in <module>
    from ansible.callbacks import vvv
ImportError: cannot import name vvv

**Comment by mpdehaan** [comment]
doesn't happen for me.   Interesting.   

I suspect we can rename "callbacks.py to "callback.py" though that's particularly heinous in that it could break existing users.

Moving the callbacks directory is another option, which only messes with people trying out 0.7.   Still, it seems cleaner to just do the first thing.

Are you sure you don't have some stuff still around from a "make install" or otherwise maybe are running somethings out of PYTHONPATH?

**Comment by ludovicc** [comment]
I don't know. It would be good to try out of a fresh system, but my colleague is on holidays, so no spare computer with Ubuntu here. I have prepared a patch renaming callbacks.py to callback.py, it works for me but I'm not a confident Python developer, so please review it.

**Comment by mpdehaan** [comment]
thanks, I am probably just going to rename the other directory.   It seems Debian may be putting an "**init**.py" in the callbacks/ dir and making it become a package when it wasn't before.

I am hesitant to just rename callbacks.py to callback.py because anyone with existing scripts using the Runner/Playbook API would be broken by that  -- if they were passing in callbacks explicitly

It's an easy change though and only a minor inconvience for folks.

**Comment by mpdehaan** [comment]
directories are renamed instead, should be good to go

**Comment by ludovicc** [comment]
Yes, **init**.py is added to all folders containing Python code. So that's why the callbacks directory was treated as a Python package and conflicted with the callbacks.py module.
