### ISSUE TITLE
Can't run ec2_metric_alarm

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#9284]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Running on and managing Ubuntu/AWS
##### Summary:

Looking for assistance in fixing this error
##### Steps To Reproduce:

https://github.com/smiller171/Ansible-CloudWatch/blob/feature/create-alarm/roles/alarm/tasks/add-alarm.yaml
##### Expected Results:

Expected to have a new CloudWatch alarm created
##### Actual Results:

I'm getting the following error when I try to create an alarm for an EC2 instance with Ansible:

```
failed: [localhost -> localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/ansible/tmp/ansible-tmp-1412699627.25-238544724030680/ec2_metric_alarm", line 1818, in <module>
    main()
  File "/tmp/ansible/tmp/ansible-tmp-1412699627.25-238544724030680/ec2_metric_alarm", line 1814, in main
    create_metric_alarm(connection, module)
  File "/tmp/ansible/tmp/ansible-tmp-1412699627.25-238544724030680/ec2_metric_alarm", line 1683, in create_metric_alarm
    alarms = connection.describe_alarms(alarm_names=[name])
AttributeError: 'NoneType' object has no attribute 'describe_alarms'
```

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
