### ISSUE TITLE
Mac OS  space in path not working

### ISSUE THREAD

**Issue by Sonique** [ansible/ansible#9316]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2 (installed via `brew`)
##### Environment:

Mac OS X Maverics  10.9.5
##### Summary:

Problem with space in `$HOME` path `/Volumes/Data HD/`.
##### Steps To Reproduce:

Put ssh and other configs in folder with spaces and run
##### Expected Results:

`ansible -m ping vps` >> ping servers
##### Actual Results:

After installing ansible via `brew` I tried create simple config and run ping as suggested in docs. After running `ansible -m ping vps` I get following errors:

```
→ ansible -m ping vps -vvvv
<host1> ESTABLISH CONNECTION FOR USER: sshuser
<host2> ESTABLISH CONNECTION FOR USER: sshuser
<host1> REMOTE_MODULE ping
<host2> REMOTE_MODULE ping
<host1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Volumes/Data HD/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=sshuser', '-o', 'ConnectTimeout=10', 'host1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1413105855.8-234833560625031 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1413105855.8-234833560625031 && echo $HOME/.ansible/tmp/ansible-tmp-1413105855.8-234833560625031'"]
<host2> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Volumes/Data HD/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=sshuser', '-o', 'ConnectTimeout=10', 'host2', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1413105855.8-90546096038337 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1413105855.8-90546096038337 && echo $HOME/.ansible/tmp/ansible-tmp-1413105855.8-90546096038337'"]
host2 | FAILED => SSH encountered an unknown error. The output was:
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
command-line line 0: garbage at end of line; "HD/.ansible/cp/ansible-ssh-%h-%p-%r".

host1 | FAILED => SSH encountered an unknown error. The output was:
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
command-line line 0: garbage at end of line; "HD/.ansible/cp/ansible-ssh-%h-%p-%r".
```

**Comment by abadger** [comment]
Reproduced by doing

``` shell
$ export HOME=$(pwd)/'Data HD'
$ mkdir -p "$HOME"
$ ansible -m ping localhost -vvvv
```

Looking into this now.

**Comment by abadger** [comment]
I think that should fix your issue!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
