### ISSUE TITLE
Do not lose handler notifications on failure

### ISSUE THREAD

**Issue by josef-spak** [ansible/ansible#9323]
##### Feature request

I was looking for a way to print notified handlers that can't be run because a task failed. So I found this in the mailing list at https://groups.google.com/forum/#!topic/ansible-project/2T7VEHvgmag

Michael DeHaan:

> But I am open to a new retry file that lists handlers that didn't succeed.
> 
> We need to attack other things int he queue before researching this though.

As I understand it the idea was:
- to record in the retry file a list of handlers that were notified but didn't succeed (not run at all or failed).
- use this to enhance playbook retries

Personally I'd welcome an option to:
- print out the unsuccessful handlers after a failure

As quoted above, probably low priority but posting it here so someone (or me) gets to it eventually.

**Comment by mpdehaan** [comment]
So right now this generates the list of retry hosts, not the list of specific handlers.

Using "--force-handlers" will rerun the existing handlers

We're also exploring some ideas around try/except blocks.

Anyway, discussion on ansible-devel is welcome, though I'm not seeing this feature change in this way specifically for the above reasons.

**Comment by rbu** [comment]
> Using "--force-handlers" will rerun the existing handlers

From what I see, "--force-handlers" will neither continue running notified handlers on one host after a task failed on that host nor will it run the handlers in the next run (rerun with --limit, for example) if that handler is not notified again -- which it may not be if it was notified by a changed file, for example.

**Comment by dwt** [comment]
http://docs.ansible.com/playbooks_intro.html also mentions `- meta: flush_handlers` which allows to at least localize this problem a little bit more.

Unfortunately this still allows the problem to happen if the error happens between the notify and the `- meta: flush_handlers` call.

**Comment by dwt** [comment]
I have to say that I'm quite uneasy about these lost handlers, as currently (ansible 1.7) `--force-handlers` doesn't allow us to force execution of handlers on failed machines, rerunning doesn't run them reliably and `meta: flush_handlers` is not a reliable workaround, while still adding quite some cruft to otherwise lean and mean task files.

Therefore I propose to reopen this bug.

**Comment by sistemasdistal** [comment]
Also, `--force-handlers` will run handlers IFF they're notified by a task. This is not always the case when re-running a playbook.

For instance, I had a handler fail because of a oom-killer hicup. When running the playbook again the handler won't run because the task that notified it had already completed on the first run.
