### ISSUE TITLE
Ansible should trap SIGINT (^C) to trigger callbacks before exiting

### ISSUE THREAD

**Issue by rafecolton** [ansible/ansible#9337]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.7.2`
##### Environment:

Running on Mac OS X against Ubuntu 14.04
##### Summary:

For example, if I use the hipchat callback, I would like to get a playbook failure notification if I `^C` the playbook run

**Comment by wevanscfi** [comment]
Would just like to add to this, it would be nice if ansible is capturing SIGINT within a block to exit to the rescue and always sections. This will allow manually interrupting a play, and still having error handling run.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
