### ISSUE TITLE
Ansible fails to parse yml file when string contains a colon and a \n

### ISSUE THREAD

**Issue by simonft** [ansible/ansible#9359]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

Debian sid
##### Summary:

When attemping to use both a colon and a \n in a string, ansible fails to parse the line. It works with just a :, and it works with just a \n, but not with both. 
##### Steps To Reproduce:

Create a file test.yml with the following:

```
- hosts: all
  task:
  - name: test
    debug: msg='test : \n'
```

Run 

```
ansible-playbook test.yml
```
##### Expected Results:

```
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 _________________
< GATHERING FACTS >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [localhost]
 ____________
< TASK: test >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [localhost] => {
    "msg": "test : \n"
}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost              : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
ERROR: Syntax Error while loading YAML script, /path/to/updates.yml
Note: The error may actually appear before this position: line 10, column 22

  - name: test
    debug: msg='test : \n'
                     ^
This one looks easy to fix.  There seems to be an extra unquoted colon in the line
and this is confusing the parser. It was only expecting to find one free
colon. The solution is just add some quotes around the colon, or quote the
entire line after the first colon.

For instance, if the original line was:

    copy: src=file.txt dest=/path/filename:with_colon.txt

It can be written as:

    copy: src=file.txt dest='/path/filename:with_colon.txt'

Or:

    copy: 'src=file.txt dest=/path/filename:with_colon.txt'


```

**Comment by jimi-c** [comment]
Hi @Simonft, this is a limitation of the YAML format. Since the colon is significant to the parser, when one appears on the line in this manner you must quote the entire line, like so:

<pre>
- hosts: localhost
  gather_facts: no
  tasks:
  - name: test
    debug: "msg='test : \n'"
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
