### ISSUE TITLE
Cryptic message if testing 'when' fails

### ISSUE THREAD

**Issue by alexintel** [ansible/ansible#9374]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

amazon-linux-ami: ami-b66ed3de
##### Summary:

Cryptic message if testing 'when' fails
##### Steps To Reproduce:

Use case scenario in the role task:
- name: perform some check
  command: "test -x /etc/some_exec_file"
  register: executable_present          <- this is expected to fail, proper behavior
  ignore_errors: true
- name: perform copy template
  sudo: yes
  template: src=existing_template
  dest=/etc/profile.d/some_setting_here.sh
  owner=root group=root mode=0600
  when: exectuable_present              <- note typo 'exectuable_present' instead of 'executable_present'
##### Expected Results:

Ansible should fail with a descriptive message. Something like 'variable exectuable_present is not defined' or 'evaluation of exectuable_present failed'
##### Actual Results:

Ansible fails with a cryptic message "failed expects a dictionary".

Thank you,
Alex.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [foo] **********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UndefinedError: 'exectuable_present' is undefined
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}
NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
