### ISSUE TITLE
Ansible Jira module can not use 

### ISSUE THREAD

**Issue by canshen-yottaa** [ansible/ansible#9398]
##### Issue Type:

"Bug Report"
##### Ansible Version:

ansible 1.6.2
##### Environment:

Centos 6.4
##### Summary:

Jira module can not be used ，
 i use the  Jira module Example whit site http://docs.ansible.com/jira_module.html#id4  
when run the flowing playbook ，found  the “HTTP Error 400: Bad Request”
##### Steps To Reproduce:

the playbook files

ansible  localhost -m jira -a "uri='https://xxxxx.jira.com' username=‘xxxx’ password=‘xxxxx’ project=Opeartions operation=create  summary='Example Issue' description='Created using Ansible' issuetype=Task"  -c local

I has also check use the Example playbook ，also can not run normal。
##### Actual Results:

when I run the commands , found the error information

localhost  | FAILED >> {
    "failed": true, 
    "msg": "HTTP Error 400: Bad Request"
}

I  has read the jira document found  the 400 http code  maybe the jira module missing  some  parameters or attributes。

the follow information is from  the Jira   document 
website https://developer.atlassian.com/static/rest/stash/2.7.2/stash-jira-integration-rest.html

HTTP Code 400 (Bad Request) Description information：

One or more of the required parameters or attributes:
    were missing from the request;
    incorrectly formatted; or
    inappropriate in the given context.

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
