### ISSUE TITLE
Add 'eu-central-1' to AWS_REGIONS in ec2 module

### ISSUE THREAD

**Issue by adonig** [ansible/ansible#9414]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7.2
##### Environment:

“N/A”
##### Summary:

Ansible misses support for the new AWS Frankfurt region. You can fix it by adding 'eu-central-1' to AWS_REGIONS in lib/ansible/module_utils/ec2.py
##### Steps To Reproduce:

Try to create a stack in region 'eu-central-1' with the cloudformation module.
##### Expected Results:

It should create the stack.
##### Actual Results:

It fails with the following error message:

```
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: eu-central-1
```

**Comment by cchurch** [comment]
This will only work if you've also upgraded to boto 2.34.0.  Just my $0.02, but it may make more sense to use `boto.regioninfo.get_regions("service_name")` instead of maintaining a separate list of regions?

**Comment by mpdehaan** [comment]
Module tickets should be filed on the modules repo.  Can you please open this here:

https://github.com/ansible/ansible-modules-core

**Comment by willthames** [comment]
@mpdehaan - you might think this is a modules issue but the code for this is almost entirely in ansible core, as the report suggests (the fix is in `lib/ansible/module_utils/ec2.py`)
@cchurch - wow, it's incredible that boto needs updating too (I guess not too incredible otherwise ansible wouldn't need a fix either). I wonder how best to expose that to the user who wishes to use eu-central-1 but boto fails. It's not very handy that `connect_to_region` silently fails and returns `None` rather than throwing an exception
