### ISSUE TITLE
Bad error message when a variable is undefined for port:

### ISSUE THREAD

**Issue by MichaelBitard** [ansible/ansible#9424]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Ubuntu 14.04.01
##### Summary:

I get a confusing error message when a variable is undefind for the entry port:
##### Steps To Reproduce:

Launch this playbook with `error_on_undefined_vars=True`

```

---
- hosts: local
  port: "{{ unknown_var }}"
```
##### Expected Results:

`{'msg': u'FAILED: var "{{ unknown_var }}" is undefined', 'failed': True}`
##### Actual Results:

`{'msg': u'FAILED: Configured port "{{ unknown_var }}" is not a valid port, expected integer', 'failed': True}`

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible-playbook -vv 9424.yml 
1 plays in 9424.yml
ERROR! the field 'port' has an invalid value, which appears to include a variable that is undefined. The error was: 'unknown_var' is undefined
The error appears to have been in '/root/testing/9424.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
---
- hosts: localhost
  ^ here
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
