### ISSUE TITLE
`fatal error while evaluating conditional: yes` passing option from inventory file

### ISSUE THREAD

**Issue by techtonik** [ansible/ansible#9426]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Debian 7.6
##### Summary:

Ansible fails with `fatal error while evaluating conditional: yes` when variable is set in inventory file (which is not yaml)
##### Steps To Reproduce:

Create this inventory file:

```
[network]
node001

[network:vars]
optimized_config=yes
```

Create task:

```
- shell: echo xxx
  when: optimized_config
```
##### Actual Results:

```
TASK: [node001 | use config optimized for testing] ******************************
fatal: [node001] => error while evaluating conditional: yes

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
We should probably convert yes/no to booleans here, I'm guessing.

**Comment by techtonik** [comment]
Yes. That will help. Looks like yes/no to bool conversion should be here https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/ini.py#L53 right?

**Comment by jimi-c** [comment]
Hi, looking back at older issues, and I'm not sure this is the correct way to handle this. I don't think we should automatically assume these strings are booleans, as that could introduce other problems. Really, the conditional should use `|bool` to make sure it is converted properly.

Due to this fact, I'm going to go ahead and close the ticket.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
