### ISSUE TITLE
ansible >=1.7 fails unnecessarily by trying to open irrelevant vaults

### ISSUE THREAD

**Issue by c-nichols** [ansible/ansible#9457]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7-1.7.2
##### Environment:

debian 7, ubuntu 12.04
##### Summary:

I'm having a problem upgrading my project to ansible>=1.7.  I'm finding that ansible MUST open any vault files put into group_vars/ before anything else can happen, regardless of what I ask ansible to do.  
##### Steps To Reproduce:

I've created a small test case that "works" on older than 1.7 (the playbook errors out, but it's a normal run and a descriptive error) and strangely blows up on 1.7 or higher: 
https://www.dropbox.com/s/gu2t7mymyeio838/ansible-testcase.tar.gz?dl=0

See the readme file for more info.  Oh and the password to the vault is password if you need it.
##### Expected Results:

it should gather facts, etc. then spit out an error.  In other words it should run the playbook like normal
##### Actual Results:

ERROR line about not being able to open an irrelevant vault file is the first and only output.

Thanks and let me know if I can be of any further assistance!
Colin

**Comment by mpdehaan** [comment]
Hi...

Ansible will load anything that is in inventory because it may be referred to by other hosts, even for hosts not in the play.

(As a matter of course, I don't download tarballs, but uploading a gist would be welcome)

In any case, I think this is just a misunderstand about why it is loading the files - it may need them in various playbooks - and as such I think you'll just need to specify --ask-vault-pass.

In any case, if you disagree with this one, feel free to stop by ansible-project and we can discuss.

Thanks!

**Comment by c-nichols** [comment]
I'll head over to the google groups -- I'm not sure where I'm going wrong; my example project seems aligned perfectly with the documentation, and I had no trouble up to 1.6.10.  Seems like it might be a regression, I'd love to get some more eyes on it.  I'm also in #ansible on freenode (xkillac4), feel free to hit me up.

Here's the gist: https://gist.github.com/c-nichols/aca08301235ddd5b4014
