### ISSUE TITLE
[bug report] Possible issue with ignore_errors and variables

### ISSUE THREAD

**Issue by zachsnow** [ansible/ansible#9464]
### Summary:

Difference in ability to use variables with `ignore_errors` from version 1.5.5 vs. successive versions (including 1.7.2) on OSX.
### Expected:

In Ansible 1.5.5 one could use variable names in `ignore_errors`, which we used to dynamically allow ignoring or not ignoring errors.  For example:

```
# inventory.hosts
localhost ansible_connection=local

# group_vars/all.yml
test_variable: no

# playbook.yml
- name: Issue (playbook)
  hosts: all
  tasks:
    - name: Show variable
      debug:
        var: test_variable
    - name: Use variable in 'when'
      debug:
        msg: Testing...
      when: test_variable
    - name: Use variable in 'ignore_errors'
      fail:
        msg: Failing...
      ignore_errors: test_variable

```

Behavior in 1.5.5 is as expected: the first task shows the variable's value, the second is skipped, and the third ignores errors and so succeeds despite the use of `fail`.

(Note that in my actual scenario I have a "real" inventory; this simple inventory is solely for purposes of illustrating the issue).
### Actual:

In versions later than 1.5.5 (I believe I tested them all, and certainly including 1.7.2) this results in an error:

`ERROR: error while evaluating conditional: test_variable`.

However, the first task correctly displays the contents of `test_variable`, and the second is correctly skipped:

```
TASK: [Show variable] *********************************************************
ok: [localhost] => {
    "test_variable": "False"
}

TASK: [Use variable in 'when'] ************************************************
skipping: [localhost]
```

I tried various different syntaxes and concluded there's something amiss; `{{ test_variable|bool }}` yields `jinja2.exceptions.UndefinedError: 'test_variable' is undefined` which is seemingly false. Finally I dropped `import ipdb; ipdb.set_trace()` [around here](https://github.com/ansible/ansible/blob/release1.7.2/lib/ansible/playbook/__init__.py#L467) and found that the variable isn't available in the set of those being used when evaluating the conditional after all, and that we are using different logic to process `when` as compared to `ignore_errors` entirely.

**Comment by mpdehaan** [comment]
First off, an undefined variable is undefined, not false.

However, since you have it defined in "all", it's most likely defined, and inventory variables aren't being pulled in here, which does make this a bug, most likely.

Thanks for the report!

**Comment by zachsnow** [comment]
"Seemingly false" means "apparently not the case". Note the lack of backticks.

**Comment by phillipholmes** [comment]
Confirming this is indeed a reproducible bug in OSX

I just came across this issue on OSX (Yosemite) with ansible 1.8.2 (installed via Brew).  I use a default variable for an include script (var is detailed in a common role used by all playbooks) and override it for a notification system that is occasionally busy when I really need the notify task to fail if it fails (usually I don't care if it fails) because I need to see the message (or investigate if it fails)

sample common role: /roles/common/vars/main.yml

```
---
notifyignoredefault: True
```

sample include file: /include-notify.yaml

```
---
- name: notify with message
  ignore_errors: "{{ notifyignoredefault }}"
  notifymodule:
    message: "{{ themessage }}"
  register: actionresult
- debug: var=actionresult
```

sample playbook: /playbook-test.yaml

```
---
- hosts: localhost
  roles:
    - common
  tasks:
    - debug: var=notifyignoredefault
    - include: include-notify.yaml
      vars:
        - message: "This is a test message"
      register: actionresult
    - debug: var=actionresult
```

command used:

```
ansible-playbook playbook-test.yaml
```

On Linux, the above works as expected (notifymodule sends the message and if fails, scripts continue) using Ansible 1.7.2. I have another more serious bug identified with 1.8.x so still cannot switch to it yet (its in the issue tracker already).

Feel free to replace notifymodule with a notification module of your choice (and give it any configuration variables - those at least still pass through as expected).

On OSX, the above fails with this message:

```
< truncated exception error>
jinja2.exceptions.UndefinedError: 'notifyignoredefault' is undefined
```

If I change the include script to directly access the variable as a conditional I get this error message instead:

```
ERROR: error while evaluating conditional: notifyignoredefault
```

In this specific instance only ignore_errors is having an issue with variables being passed to it, and only when using OSX.

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible-playbook -vv test.yml -i inv 
1 plays in test.yml
PLAY: Issue (playbook) **********************************************************
TASK [Show variable] ************************************************************
ok: [localhost] => {
    "changed": false, 
    "test_variable": false
}
TASK [Use variable in 'when'] ***************************************************
skipping: [localhost] => {"skipped": true, "changed": false, "skip_reason": "Conditional check failed"}
TASK [Use variable in 'ignore_errors'] ******************************************
fatal: [localhost]: FAILED! => {"msg": "Failing...", "failed": true, "changed": false}
NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 </pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
