### ISSUE TITLE
For 1.8, change the "smart" connection handling for Darwin

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#9470]
Because of the askpass kernel panic issue (hi Darwin) we use "-c paramiko" for smart connections on Darwin.

We should use "-c paramiko" for "smart" only if it's not going to be needed to run ssh-askpass -- key based auth should use the better mechanism (-c ssh, which can leverage ControlPersist).

**Comment by jfchevrette** [comment]
+1

#5007 changed the behavior and this had a side effect of causing an issue because I use a SSH private key cipher that is not supported by paramiko.

Here's the error :

```
fatal: [server] => {'msg': 'FAILED: Unknown private key cipher "AES-256-CBC"', 'failed': True}
```

I will file an issue with paramiko and in the meantime will force transport to ssh but I would rather leave it at 'smart' because we use a common ansible.cfg deployed on our clients (OS X, Linux..).

I'm not sure how we can check if key based auth is being used? It is my understanding that ansible is not aware of the type of auth that either paramiko or ssh will request later on?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
