### ISSUE TITLE
zypper module TypeError: package_present() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#9473]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.8 (devel 7cd5b13e34) last updated 2014/11/03 09:44:40 (GMT -500)
  lib/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:03 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:06 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 14:28:11 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 14:28:15 (GMT -500)
  configured module search path = None
##### Environment:

What OS are you running Ansible from OSX 10.9.5 and Python 2.7.5 
Managing openSUSE 12.3 and Python 2.7.3
##### Summary:

Attempting to update all packages installed with zypper using this play:
- name: Update all out of date packages (zypper)
  zypper: name=\* state=latest

Results in 

TypeError: package_present() takes exactly 5 arguments (4 given)
##### Steps To Reproduce:
- name: Update all out of date packages (zypper)
  zypper: name=\* state=latest
  sudo: yes
  always_run: yes
##### Expected Results:

I expect all packages to be updated.
##### Actual Results:

failed: [opensuse-test.domain.com] => {"failed": true, "parsed": false}

SUDO-SUCCESS-yxkdipekxgngrypiigdxchymoygrjfts
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1415045092.82-179041386412668/zypper", line 1785, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1415045092.82-179041386412668/zypper", line 246, in main
    (rc, stdout, stderr, changed) = package_latest(module, name, installed_state, disable_gpg_check, disable_recommends)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1415045092.82-179041386412668/zypper", line 167, in package_latest
    (rc, stdout, stderr, changed) = package_present(m, name, installed_state, disable_gpg_check)
TypeError: package_present() takes exactly 5 arguments (4 given)

FATAL: all hosts have already failed -- aborting

**Comment by basictheprogram** [comment]
Don't know git very well, but I think this is the patch you need to fix this problem.

diff --git a/packaging/zypper.py b/packaging/zypper.py
index 73b1569..df6d5a7 100644
--- a/packaging/zypper.py
+++ b/packaging/zypper.py
@@ -164,7 +164,7 @@ def package_present(m, name, installed_state, disable_gpg_check, disable_recomme
 def package_latest(m, name, installed_state, disable_gpg_check, disable_recommends):

```
 # first of all, make sure all the packages are installed
```
-    (rc, stdout, stderr, changed) = package_present(m, name, installed_state, disable_gpg_check)
-    (rc, stdout, stderr, changed) = package_present(m, name, installed_state, disable_gpg_check, disable_recommends)
  
   # if we've already made a change, we don't have to check whether a version changed
   if not changed:

**Comment by jimi-c** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
