### ISSUE TITLE
Ansible retriving package results in 404

### ISSUE THREAD

**Issue by ZhijieWang** [ansible/ansible#9486]
Hi,

I am installing EdX on Ubuntu 12.04. The VPS is hosted on Digital Ocean.
When the EsX provisional script is trying to install python-pycurl, it causes an error. Based on the log it is trying to retrieve the package information at this location.
http://mirrors.digitalocean.com/ubuntu/dists/precise/main/binary-amd64/Packages

However, the correct location is here.
http://mirrors.digitalocean.com/ubuntu/dists/precise/main/binary-amd64/Pacakges.gz
or 
http://mirrors.digitalocean.com/ubuntu/dists/precise/main/binary-amd64/Pacakges.bz2

The Linode has a similar hosting pattern, that there is no /Pacakges but Pacakges.**

If ansible team can fix this small glitch or point me to the correct place that I can configure it.

Thank you very much,

**Comment by bcoca** [comment]
how is ansible 'trying to retrieve' this package? what version of ansible?

**Comment by jimi-c** [comment]
Seeing as there has been no follow up on this issue, I'm going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
