### ISSUE TITLE
include_vars in previous role overrides paramaterized variable in later role

### ISSUE THREAD

**Issue by dstillman** [ansible/ansible#9497]
##### Issue Type:

Bug Report
##### Ansible Version:

cbad867f24fd56c9a98c4cf85cc4447ccfa74066 and 1.7.2 and many versions before that
##### Environment:

Amazon Linux AMI release 2014.09
##### Summary:

In [Variable Precendence](http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable), it gives this example:

```
roles:
   - { role: common_settings }
   - { role: something, foo: 12 }
   - { role: something_else }
```

and says this:

> There are some protections in place to avoid the need to namespace variables. In the above, variables defined in common_settings are most definitely available to ‘something’ and ‘something_else’ tasks, but if “something’s” guaranteed to have foo set at 12, even if somewhere deep in common settings it set foo to 20.

There's a typo in there (the "if" after "but"), but my understanding of that is that `foo` should always be set to 12 in 'something', even if it was set to something else in 'common_settings'.

However, this doesn't seem to be the case if `foo` was set via `include_vars` in 'common_settings'.
##### Steps To Reproduce:

Create these five files:

main.yml:

```
- hosts: 127.0.0.1
  roles:
    - { role: a }
    - { role: b, foo: GOOD }
```

roles/a/vars/main.yml:

```
foo: BAD
```

roles/a/vars/foo.yml:

```
foo: BAD
```

roles/a/tasks/main.yml:

```
- include_vars: foo.yml
```

roles/b/tasks/main.yml:

```
- assert: { that: "foo == 'GOOD'" }
```
##### Expected Results:

`foo` should be equal to 'GOOD' in role b, since it was passed as a parameter.
##### Actual Results:

`foo` is set to 'BAD', due to the `foo: BAD` declaration in roles/a/vars/foo.yml. The `foo: BAD` in roles/a/vars/main.yml isn't actually necessary to reproduce the problem, but it's there to demonstrate that this doesn't occur if roles/a/vars/foo.yml is commented out, even though there's the same `foo: BAD` declaration in roles/a/vars/main.yml. So the problem is limited to variables set via `include_vars`.

As far as I can tell, this makes it necessary to namespace variables within roles, since there's no way to know that a totally unrelated variable with the same name wasn't set via `include_vars` in an earlier role.

**Comment by dstillman** [comment]
Actually, this appears to have been fixed on Sept. 30 by 313f26f866cec92e4dbe0e1d713a0ab0da647c98. I wasn't sourcing hacking/env-setup, so I wasn't getting all the latest code. Sorry for the noise.

**Comment by dstillman** [comment]
This is happening again after 9a0f8f0, which fixed #9498. The above steps to reproduce are still valid.

**Comment by farridav** [comment]
Hi, i think im having the same issue (inline role vars bleeding into and overriding that of other roles), are you aware of a fix for this? intermediary or otherwise?

My use case is as follows:

# playbook.yml
    ...
    - {role: My.role, vars_file: "/path/to/varsA.yml"}
    - {role: My.role, vars_file: "/path/to/varsB.yml"}

# My.role/tasks/main.yml

```
- name: Load in project specific vars
  include_vars: "{{ vars_file }}"
  when: vars_file is defined
```

A more elaborate example can be taken from [this question](http://stackoverflow.com/questions/26734719/how-do-i-include-a-lot-of-vars-into-ansible-roles) I posted on Stack Overflow

Thanks in advance for any pointers you can give

**Comment by jimi-c** [comment]
Hi @farridav, I'm actually looking into this issue now and have a preliminary patch to address it.I just tested your use-case (with a simple debug message in the role task instead of include_vars), and got the following output:

<pre>
PLAY [localhost] ************************************************************** 
TASK: [farridav | debug msg="the var specified is /root/testing/9497/farridavA.yml"] *** 
ok: [127.0.0.1] => {
    "msg": "the var specified is /root/testing/9497/farridavA.yml"
}
TASK: [farridav | debug msg="the var specified is /root/testing/9497/farridavB.yml"] *** 
ok: [127.0.0.1] => {
    "msg": "the var specified is /root/testing/9497/farridavB.yml"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

So it would appear my patch also fixes this. I will be pushing this up as soon as my internal testing passes and I ensure the other two related issues (#9411 and #9498) remain fixed.

**Comment by farridav** [comment]
@jimi-c Great! thanks for your prompt reply, Once I get hold of the patch ill try it in my play and confirm the results, subject to all going well is this likely to make it into the next release? and do you have any idea on when that is due?

Thanks again

**Comment by jimi-c** [comment]
Yes it will be in the next release, which will be coming out this month.

**Comment by jimi-c** [comment]
@dstillman / @farridav the patch is above, if you'd like to test it before I merge it in.

**Comment by dstillman** [comment]
Yes, with the above patch, all three of my tests for these various issues pass.

**Comment by jimi-c** [comment]
@dstillman excellent, I'll go ahead and merge this in.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dstillman** [comment]
Thanks for the fix, but the patch doesn't appear to include any tests, including the simple one I provided. Is this covered by any existing tests? In case it's not clear, these variable-related issues made Ansible dangerous to use — it could silently configure machines in a totally different state from what was expected. Thankfully I noticed them while still trying Ansible out on test instances, but I'm not really comfortable committing to Ansible in production use if these sorts of bugs could resurface at any time. I believe this ticket should stay open until there are tests in place.

**Comment by jimi-c** [comment]
@dstillman sorry I missed that. If you want to send that in as PR I can merge it, otherwise I can add it myself. We already have a variable precedence test, so I would say this is not being covered properly.

**Comment by dstillman** [comment]
OK, great, thanks. I'll submit a PR for this later.

**Comment by dstillman** [comment]
Actually, @jimi-c, I'm going to let you handle the test for this. I'm seeing test_var_precedence already failing without a test for this (since 8a1fbed5d6a61583950024df60ac74d5c98d6cca), so I think the variable precendence tests may need some more work in general.

**Comment by dstillman** [comment]
This is broken again on devel, [not that anyone cares](https://groups.google.com/d/msg/ansible-project/4OIuDxRSv0M/RgW8HkuIKQAJ).
