### ISSUE TITLE
get_url fails when you try to download large file to separate mount

### ISSUE THREAD

**Issue by bentrombley** [ansible/ansible#9512]
I tried to download a 16gb db snapshot to a separate drive (/data), but it failed because the file was buffered on a different drive, I believe in /tmp.  This seems like a design flaw when curl has no problem (see below).

This fails:
get_url:
  url: "{{snapshot_url}}"
  dest: /data/latest-snapshot.tar.gz

But this works:
command: curl -o  /data/latest-snapshot.tar.gz {{snapshot_url}}

**Comment by nathancahill** [comment]
You can set one of the environment variables `TMPDIR`, `TEMP` or `TMP` to choose where the file is written to on the server as a workaround: https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
