### ISSUE TITLE
Setting python-interpreter for modules when using ansible-pull

### ISSUE THREAD

**Issue by nmeum** [ansible/ansible#9515]
I wanna use ansible-pull on a server running OpenBSD. The problem is that OpenBSD (just like many other unix-like operating system) stores local packages in `/usr/local` thus my python2 interpreter is located at `/usr/local/bin/python2.7`. If I would be using `ansible-playbook` I would simply set the `ansible_python_interpreter` inventory variable as suggest by the FAQ. However, this doesn't seem to work with `ansible-pull`.

I tried setting `ansible_python_interpreter` in `/etc/ansible/group_vars/all` and in `/etc/ansible/hosts` using:

```
[all:vars]
ansible_python_interpreter=/usr/local/bin/python2.7
```

I also tried

```
localhost ansible_python_interpreter=/usr/local/bin/python2.7
```

But somehow none of these workarounds seem to work. Thus I decided to file a bug report. If there is another way to tell `ansible-pull` which python interpreter it should use then please let me know.

For the record: This is the erorr message I get when invoking `ansible-pull`:

```
Starting ansible-pull at 2014-11-08 14:19:15
localhost | FAILED >> {
    "failed": true, 
    "msg": "/bin/sh: /usr/bin/python: not found\n", 
    "parsed": false
}
```

And by the way: Why don't you use "/usr/bin/env python" as the shebang for the modules and as the default `ansible_python_interpreter` value?

**Comment by ienliven** [comment]
+1

**Comment by bcoca** [comment]
ansible_python_interpreter is only for modules, not for the
ansible/ansible-playbook/ansible-pull scripts.

These scripts should be pointed to the correct python during the install
(setup tools takes care of this). Ansible cannot use env as the python
returned in many cases is the 'incorrect ones' specially since many systems
install v2 and v3 alongside each other.

I would check the install for ansible on the target machine and why it did
not point to the correct python.

## 

Brian Coca

**Comment by nmeum** [comment]
> ansible_python_interpreter is only for modules

well…ansible-pull actually uses the git module according to the man page. See the `-M` option.

That's infact also the reason why I get the error message mentioned above. If I wouldn't be able to invoke `ansible-pull` at all I would get a totally different error message.

> Ansible cannot use env as the python returned in many cases is the 'incorrect ones' 

It returns a more correct one then `#!/usr/bin/python`. Further more, many operating system which use python3 as `env python` simply patch the shebang of packages…

**Comment by bcoca** [comment]
so the error is with the git module and not ansible-pull? Can you post the

## error output?

Brian Coca

**Comment by nmeum** [comment]
> so the error is with the git module and not ansible-pull?

Actually that's just a wild guess. BUT I can invoke ansible-pull itself
and can view the help with "ansible-pull -h" etc. The error (that I
already posted above) only appears when I try to clone a repo for
instance. And infact this theory makes a lot of sense because if
you look at the git module the shebang is "#!/usr/bin/pytho".

**Comment by sivel** [comment]
I imagine the issue is related to how repositories are cloned with `ansible-pull`.  See: https://github.com/ansible/ansible/blob/v1.7.2/bin/ansible-pull#L172-L174

`ansible-pull` invokes `ansible` and at least for `-e/--extra-vars` this doesn't get passed to `ansible` as the `ansible` command doesn't support those options. See #9063

It is also possible that `group_vars`, `host_vars` or the inventory file wouldn't be used if the repo hasn't already been cloned.

Since `localhost` may be explicitly declared, this would not allow implicit localhost to work, and you would get the `ansible_python_interpreter` set by ansible for the implicit localhost.

When you are running `ansible-pull` are you explicitly specifying `-i /etc/ansible/hosts`?  `ansible-pull` requires that this be explicitly provided.  `ansible` and `ansible-playbook` provide a default for `-i` that isn't provided to `ansible-pull`, so by default `-i` is empty, resulting in ansible using `localhost,` as the inventory when no file is specified.

**Comment by nmeum** [comment]
> When you are running ansible-pull are you explicitly specifying -i /etc/ansible/hosts? 

No, I am not doing this, since the inventory file that I wanna use isn't `/etc/ansible/hosts`. I wanna use a file called `hosts` (which is a part of my ansible git repo) as the inventory file, thus I use `-i hosts`.

If ansible would just use `#!/usr/bin/env python` then we would have fewer problems here…

**Comment by sivel** [comment]
There are reasons why the shebang won't be changed to that in the modules at this point.

If your inventory file doesn't exist (which is the case with a never before cloned repo), then `ansible-pull` uses `localhost,` which won't allow you to set `ansible_python_interpreter`.

You could clone the repo first, before running `ansible-pull`, and have `ansible_python_interpreter` set in you actual inventory file.

Or you could potentially run it using a local inventory file the first time, and have your playbooks then reconfigure `ansible-pull` to use the hosts file that is part of your repo for subsequent runs.

As far as the comment about `/etc/ansible/hosts`, I had assumed from your initial comment that was the inventory file you were using.

Another fix would be that we get `-e/--extra-vars` support into the `ansible` command, and get `ansible-pull` to pass on `-e`.  Then you could pass `-e "ansible_python_interpreter=/usr/local/bin/python2.7"` to `ansible-pull` This work is in #9063.

**Comment by nmeum** [comment]
> There are reasons why the shebang won't be changed to that in the modules at this point.

What are the reasons for not changing this? The files in `bin/` already use `#!/usr/bin/env python` as the shebang.

> You could clone the repo first, before running ansible-pull, and have ansible_python_interpreter set in you actual inventory file.

That doesn't work. I guess that the git module is invoked before the inventory file is read, but I am not 100% sure.

> Or you could potentially run it using a local inventory file the first time, and have your playbooks then reconfigure ansible-pull to use the hosts file that is part of your repo for subsequent runs.

Doesn't work either (see above).

The workaround I currently use is creating a symlink for `/usr/bin/python` but I would prefer a proper fix for this problem…

**Comment by bcoca** [comment]
so this should work now via #9063, by being able to pass -e "ansible_python_interpreter=.." with ansible-pull
