### ISSUE TITLE
ignore failed errors when running in checked mode

### ISSUE THREAD

**Issue by bputt** [ansible/ansible#9536]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.7.2
##### Environment:

Centos 6.5
##### Summary:

While running my scripts in check mode, I often get errors that make the script fail that would otherwise work in "actual" mode. 

For example: I touch a file and then I add configuration information to the file. In check mode, it fails to add the config info because the file doesn't exist.
##### Steps To Reproduce:

```
- name: Ensure file exists
  file: state=touch path=/etc/somefile.cfg
- name: Ensure config line exists
  lineinfile: dest=/etc/somefile.cfg regexp="^\s*someprop.prop=.*" line="someprop.prop=xyz"
```
##### Expected Results:

I'd imagine this would be tough to add a status message against, and this logic below may not suit all cases...

If file exists and changed:
    changed
else if file exists and not changed:
    ok
else if file does not exist
    changed (should always occur since file was just created, unless it was created by a template)
end if

```
TASK: [play name | task name]
changed: [server]

TASK: [play name | task name]
?? : [server]
```
##### Actual Results:

```
TASK: [play name | task name]
skipping: [server]
TASK: [play name | task name]
failed: [server]...
msg: Destination /etc/somefile.cfg does not exist !
```

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by jimi-c** [comment]
FYI, the `always_run` option was added to address this a while back.
