### ISSUE TITLE
screen program broken in 1.7.2

### ISSUE THREAD

**Issue by joebalt** [ansible/ansible#9539]
Working pre 1.7.2.
I have a shell task that runs a .bin installer as follows:

```
- name: exec one-click installer

  shell: screen -t 'test' -L -d -m bash -c '/tmp/cloudera-manager-installer.bin --i-agree-to-all-licenses --noprompt --noreadme --nooptions'

  tags: execoneclick
```

ansible 1.7.2 reports rc=0, but the program never executes. screenlog.0 is zero bytes, so no help there. I am left with a Dead screen session on the target machine. screen -rd reports it as Dead.

I can use ssh to execute the same line successfully and the .bin program does indeed run.

You can get the .bin file I am using from:

```
wget http://archive.cloudera.com/cm5/installer/latest/cloudera-manager-installer.bin -O /tmp/cloudera-manager-installer.bin
```

**Comment by sysadmin75** [comment]
Is this still an issue with the latest version? I am unable to reproduce. 
I used your example but replaced it with ping and it worked.
- name: Ping test
  shell: screen -t 'test' -L -d -m bash -c 'ping -c 25 192.168.1.1'

**Comment by jimi-c** [comment]
Hi, this situation does not appear to be present in the devel branch (which will be ansible 2.0)

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
