### ISSUE TITLE
Apt provider unable to purge package once removed

### ISSUE THREAD

**Issue by gertjanol** [ansible/ansible#9582]
Ansible Version: 1.7.2 (from pip, also tested and confirmed with 1.6)
Environment: Ubuntu 12.04
Summary: The apt provider does not purge packages that are removed but not yet purged (state: rc)
Steps To Reproduce:

Install and remove (without purging) a random package

```
# ansible all -i 127.0.0.1, --connection=local -m apt -a "pkg=libgd2-noxpm state=present"
# ansible all -i 127.0.0.1, --connection=local -m apt -a "pkg=libgd2-noxpm state=absent"
# dpkg -l libgd2-noxpm
[..]
rc  libgd2-noxpm                2.0.36~rc1~dfsg-6ubuntu2
```

Now try to purge the package:

```
# ansible all -i 127.0.0.1, --connection=local -m apt -a "pkg=libgd2-noxpm state=absent purge=yes"
```

Expected Results:

```
# dpkg -l libgd2-noxpm
No packages found matching libgd2-noxpm.

# dpkg-query -W -f '${Status}' libgd2-noxpm
unknown ok not-installed
```

Actual Results:

```
# dpkg -l libgd2-noxpm
[..]
rc  libgd2-noxpm                2.0.36~rc1~dfsg-6ubuntu2

# dpkg-query -W -f '${Status}' libgd2-noxpm
deinstall ok config-files
```

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
