### ISSUE TITLE
Suggestion: additional options for ansible-vault

### ISSUE THREAD

**Issue by jacobweber** [ansible/ansible#9610]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8
##### Environment:

N/A
##### Summary:

I'd like to suggest adding two options to the ansible-vault command:

--ask-vault-pass: just like with ansible-playbook. This would be useful if you have a default vault_password_file in your Ansible config, but want to override it.

--mode: when you edit a file, ansible-vault changes the file's mode to 0600, even if you don't make any changes. In some cases you may need this to be different (e.g. if you run ansible-playbook as a different user), so it would be nice to be able to set the mode yourself.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!
