### ISSUE TITLE
docker port mappings not working 

### ISSUE THREAD

**Issue by tcurdt** [ansible/ansible#9648]
```
- name: running docker-registry container
  docker:
    image: tcurdt/docker-registry
    name: docker-registry
    state: running
    net: host
    volumes: "{{volumes}}"
    ports: "127.0.0.1:5000:5000"
```

should be the equivalent of running `docker run --name registry -p 127.0.0.1:5000:5000 -v /srv/docker-registry:/srv/docker-registry -d tcurdt/docker-registry` - but it's not. It seems to ignore the port mapping.

Plus the documentation is horrible. No clue  how multiple port mappings are supposed to work. I assume I have to use the same hack I use for volumes.

This is on Docker version 1.3.2, build 39fa2fa, Ansible 1.7.2

**Comment by olvesh** [comment]
On a side-note what is your "volumes hack"? I am struggling with getting volumes mapped via ansible, and find no good documentation about it.

**Comment by tcurdt** [comment]
I meant using the "{{var}}" thing. But turns out you don't need that. But this works, too:

```
volumes: [
  "/var/www:/var/www:ro",
  "/srv/nginx/log:/srv/nginx/log:rw"
  ]
ports: [
  "80:80",
  "443:443"
  ]
```

**Comment by joestubbs** [comment]
I encountered some subtle behavior with port mappings that is perhaps related. If the underlying base image does not expose a port, you must pass the "expose" parameter in the Ansible playbook; for instance:

```
- name: docker port test
  docker:
    image: ubuntu
    command: nc -l 80
    ports: 
      - "80:80"
```

appears to map the ports correctly:

```
$ docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                NAMES
596b94bc89a2        ubuntu:latest       "nc -l 80"          4 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp   adoring_brown
```

but I can't actually reach port 80 on the loopback interface, I can only get to it using the IP on docker0:

```
$ nc localhost 80 
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                NAMES
596b94bc89a2        ubuntu:latest       "nc -l 80"          4 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp   adoring_brown
# wtf? container still there
$ nc 172.17.0.26 80
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

(Note the container was removed the second time). 

However, passing the 'expose' parameter in the Ansible playbook makes things work:

```
- name: docker port test
  docker:
    image: ubuntu
    command: nc -l 80
    expose: 80
    ports: 
      - "80:80"
```

Now hitting port 80 on lo stops the container:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                NAMES
e24d097995f5        ubuntu:latest       "nc -l 80"          3 seconds ago       Up 2 seconds        0.0.0.0:80->80/tcp   desperate_ritchie
$ nc localhost 80
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Passing "expose" like that isn't necessary if the underlying image exposes port 80 (to test, repeat with an image created from a dockerfile that simply descends from ubuntu and exposes 80). This threw me off for a bit since the docker CLI does not care whether the underlying image exposed any ports (i.e., `docker run -p 80:80 <image> nc -l 80` works as expected regardless of the image). 

It appears that Ansible's DockerManager.create_containers method uses the ports in the expose parameter in the call to docker.client.create_container. I'm not sure if that is technically necessary for some reason or if it could work differently (namely, pass all the ports in the "ports" stanza).

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
