### ISSUE TITLE
Ansible git with recursive ignores accept_hostkey

### ISSUE THREAD

**Issue by stemail23** [ansible/ansible#9655]
When executing the `git` command, with `recursive: yes`, the `accept_hostkey: yes` directive is ignored for submodules. If the submodule remote is a different server to the main git repo, the Ansible script hangs waiting for manual authentication of the remote.

**Comment by juliedavila** [comment]
So this is related to something I brought up here https://groups.google.com/forum/#!topic/ansible-devel/hp5636_AAcw

Sounds like the way to go according to @mpdehaan is to use lineinfile to ensure the hostkey(s) are present in known_hosts.

**Comment by stemail23** [comment]
So thanks for the suggested workaround, but this still feels like a "bug" to me. At the very least, a note in the help docs describing the limitation might save people some frustration.

**Comment by abadger** [comment]
Because this is host key related, I assume that this only occurs when the submodule is configurd to pull the remote module over ssh?

**Comment by stemail23** [comment]
Presumably!

**Comment by abadger** [comment]
Trying to juggle a few different changes to this module at the same time so forgive me not having this in a branch yet.  Building on top of this cleanup:

https://github.com/ansible/ansible-modules-core/pull/472

I think this patch will fix this issue:
https://gist.github.com/anonymous/de19d3abc0b0c10f4fbb

I'll try to get both of those merged into devel tomorrow or hte next day.

**Comment by juliedavila** [comment]
Toshio, I think the only problem there is when the repo has not been cloned
previously. If the base repo (no subs) has been cloned, then it would work
since the .gitsubmodule dir is already there, but if it is a new clone with
recursion, it won't work. The playbook would almost need two git tasks, one
to clone normally, and the next with recursion enabled.

**Comment by abadger** [comment]
@nousdefions After the cleanup in #472 that I just merged, I think that the code internally does just that.  In the initial checkout it first does a clone without the --recursive flag.  Then, if recursive=yes, it processes the .gitmodules file and updates the submodules.

This patch on top of those changes will make the second step also add the hostkeys for any submodule repositories.

I haven't found any git documentation that says that removing --recursive in the initial clone and doing the submodules as a separate step afterwards will have any side effects but I often miss something important in git documentation :-)  If you can see a problem with this strategy, please let me know so I can fix it!

**Comment by juliedavila** [comment]
AFAIK that should be good to go then, that was the fix I had in my brain as well.

**Comment by abadger** [comment]
Okay, should be fixed in: https://github.com/ansible/ansible-modules-core/commit/2493dda4e519b3845f5a4926a4368d65829413c2

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by rasheey97-alt** [comment]
this will help me a lot
