### ISSUE TITLE
Ansible can't use the lookup with included lookup in 'hosts' key

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#9656]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.7.2 (release1.7.2 d3c28fee87) last updated 2014/10/04 20:52:50 (GMT +400)
```

Also in 1.9 (develop).
##### Environment:

RHEL 5.5
##### Summary:

When i use the lookup with 'pipe' or 'file' with included another "lookup" for get "hosts" variable (i need that it be various in some tasks) i've got empty results. If use just one lookup (without included) it's worked well, also lookup with including lookup worked well in (for example) debug module.
##### Steps To Reproduce:

```
$ cat test_playbook

---
- hosts: localhost
  tasks:
  - shell: echo localhost > {{ lookup('env', 'PLAY_TMPDIR')}}/hostnames
  - debug: msg="{{ lookup('file', lookup('env', 'PLAY_TMPDIR') + '/hostnames') }}"
- hosts: "{{ lookup('file', lookup('env', 'PLAY_TMPDIR') + '/hostnames') }}"
  tasks:
  - debug: msg="{{inventory_hostname}}" 
```

```
$ export PLAY_TMPDIR=~/tmpdir && ansible-playbook test_playbook
```
##### Expected Results:

```
$ export PLAY_TMPDIR=~/tmpdir && ansible-playbook test_playbook
PLAY [localhost] ************************************************************** 

TASK: [shell echo localhost > /home/ansible/tmpdir/hostnames] *** 
changed: [127.0.0.1]

TASK: [debug msg="localhost"] ************************************************* 
ok: [127.0.0.1] => {
    "msg": "localhost"
}

PLAY [localhost] *********************************************************************** 

TASK: [debug msg="{{inventory_hostname}}"] ************************************ 
ok: [127.0.0.1] => {
    "msg": "127.0.0.1"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0 
```
##### Actual Results:

```
$ export PLAY_TMPDIR=~/tmpdir && ansible-playbook test_playbook
PLAY [localhost] ************************************************************** 

TASK: [shell echo localhost > /home/ansible/tmpdir/hostnames] *** 
changed: [127.0.0.1]

TASK: [debug msg="localhost"] ************************************************* 
ok: [127.0.0.1] => {
    "msg": "localhost"
}

PLAY [] *********************************************************************** 

TASK: [debug msg="{{inventory_hostname}}"] ************************************ 
ok: [host1] => {
    "msg": "host1"
}
ok: [host2] => {
    "msg": "host2"
}
<... and so on - Ansible uses a group "all", not localhost, because "hosts" variable is empty>
```

**Comment by alozovskoy** [comment]
Now i used 'add_host' module for this case, and i think that this issue not actually for me, but maybe you can solved it.

**Comment by resmo** [comment]
Does not really solve the issue with non-working nested lookups. but I this is IMHO a solution:

```
---
- hosts: localhost
  vars:
    play_tmpdir: "{{ lookup('env', 'PLAY_TMPDIR' )}"
  tasks:
  - shell: echo localhost > {{ play_tmpdir }}/hostnames
  - debug: msg="{{ lookup('file', play_tmpdir + '/hostnames') }}"
- hosts: "{{ lookup('file',  play_tmpdir + '/hostnames') }}"
  tasks:
  - debug: msg="{{inventory_hostname}}" 
```

**Comment by alozovskoy** [comment]
@resmo, variables is binded to hostnames, it's does not worked when hosts is undefined.

```
PLAY [localhost] ************************************************************** 

TASK: [shell echo localhost > /home/ansible/tmpdir/hostnames] *** 
changed: [127.0.0.1]

TASK: [debug msg="localhost"] ************************************************* 
ok: [127.0.0.1] => {
    "msg": "localhost"
}

PLAY [{{ lookup('file',  play_tmpdir + '/hostnames') }}] ********************** 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   

```

**Comment by MatthewHannigan** [comment]
I couldn't reproduce this problem with 1.8.4.  I came across it while looking for issues similar to my #10376

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example above:

<pre>
TASK [setup] ********************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435548148.35-249503562125668 && echo $HOME/.ansible/tmp/ansible-tmp-1435548148.35-249503562125668
127.0.0.1 PUT /tmp/tmpqjFo9f TO /root/.ansible/tmp/ansible-tmp-1435548148.35-249503562125668/setup
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1435548148.35-249503562125668/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1435548148.35-249503562125668/ >/dev/null 2>&1
ok: [localhost]
TASK [command] ******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1435548152.19-67123037948692 && echo $HOME/.ansible/tmp/ansible-tmp-1435548152.19-67123037948692
127.0.0.1 PUT /tmp/tmpoaeNTw TO /root/.ansible/tmp/ansible-tmp-1435548152.19-67123037948692/command
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /bin/python /root/.ansible/tmp/ansible-tmp-1435548152.19-67123037948692/command; rm -rf /root/.ansible/tmp/ansible-tmp-1435548152.19-67123037948692/ >/dev/null 2>&1
changed: [localhost] => {"changed": true, "end": "2015-06-28 23:22:32.250080", "stdout": "", "cmd": "echo localhost > /tmp//hostnames", "start": "2015-06-28 23:22:32.246777", "delta": "0:00:00.003303", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo localhost > /tmp//hostnames", "_uses_shell": true}}, "stdout_lines": [], "warnings": []}
TASK [debug msg=localhost] ******************************************************
ok: [localhost] => {
    "msg": "localhost", 
    "changed": false
}
PLAY: ***************************************************************************
TASK [debug msg=localhost] ******************************************************
ok: [localhost] => {
    "msg": "localhost", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
