### ISSUE TITLE
Module 'template' wrong resolves user home dir with tilde '~'

### ISSUE THREAD

**Issue by azhurbilo** [ansible/ansible#9663]
**Issue Type**: Bug report

**Ansible Version**: 1.8.1

**Environment**: Ubuntu 14.04

**Summary**: After updating from 1.7.2 to 1.8.1 module 'template' doesn't resolve tilde '~' as home of sudo_user.

**STR**:

1 - run playbook with ansible_ssh_user=vagrant in inventory file

2 - execute task:

```
 - sudo_user: 'user123'
   template: src=ssh/config dest=~/.ssh/config
```

**Expected result**: file copy to /home/user123/.ssh/config

**Actual result**: file is tried copy to /home/vagrant/.ssh/config

**Comment by bcoca** [comment]
misread and reversed this in my head.

**Comment by adamchainz** [comment]
+1 broke several of my plays

**Comment by a-chernykh** [comment]
this bugs me as well

**Comment by cjamison** [comment]
+1 This one bit me as well . . .

**Comment by drybjed** [comment]
Confirming the bug.

**Comment by abadger** [comment]
Potential fix:  https://gist.github.com/abadger/0eae73574352c7e5e633  I'm looking for a relevant place to add an integration test for this now.

**Comment by abadger** [comment]
Thanks everyone for the report and the testing!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
