### ISSUE TITLE
custom module generates SUDO-SUCCESS parse failure

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9673]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.1
##### Environment:

OS X 10.10
##### Summary:

Custom module generates SUDO-SUCCESS parse failure. On latest 1.7 branch (1.7.2) it workes as expected.
##### Steps To Reproduce:

playbook:

``` yaml
- test-module:
  sudo: True
```

module "test-module":

``` sh
#!/bin/bash

echo "rc=0 msg='success'"
exit 0
```
##### Expected Results:

It works in ansible 1.7.2 as expected:

```
PLAY [configuration] ********************************************

GATHERING FACTS ***************************************************************
ok: [host1]

TASK: [test | test-module ] ******************************************
ok: [host1] => {"msg": "success", "rc": 0}

PLAY RECAP ********************************************************************
host1                     : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [configuration] ********************************************

GATHERING FACTS ***************************************************************
ok: [host1]

TASK: [test | test-module ] ******************************************
failed: [host1] => {"failed": true, "parsed": false}

SUDO-SUCCESS-zzfmijpztyulkogyeeyprpugepovoioz
rc=0 msg='success'


FATAL: all hosts have already failed -- aborting
```

**Comment by sivel** [comment]
As of ansible 1.8 modules must return full JSON.

"Baby JSON" was removed.  See the release announcement at https://groups.google.com/forum/m/#!topic/ansible-announce/w1Uj8Jl1G3E

**Comment by ghost** [comment]
Thank you, that explains reported behaviour.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

Based on the above, we're going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
