### ISSUE TITLE
key=value parsing appears to be broken

### ISSUE THREAD

**Issue by stelcheck** [ansible/ansible#9678]
Ref: https://github.com/rhaido/ansible-modules/issues/3
##### Issue Type

Parsing related
##### Ansible Version

``` bash
> ansible --version
ansible 1.8.1 (detached HEAD 6598c83b02) last updated 2014/12/01 12:43:20 (GMT +900)
  lib/ansible/modules/core: (detached HEAD dd4095137a) last updated 2014/12/01 12:48:17 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD cf54dc46b4) last updated 2014/12/01 12:48:27 (GMT +900)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/01 12:48:42 (GMT +900)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/01 12:48:49 (GMT +900)
  configured module search path = None
```
##### Environment

OSX 10.9 against a CentOS6 Vagrant box
##### Summary

After upgrade, the aforementioned custom module stopped working. After switching the output to valid JSON instead of key=value (with the same key attributes and values), the module works again.
##### Steps To Reproduce
1. Install this module
2. Try to set it up to install something in a playbook (or use an existing playbook, and replace yum with yum2)
3. Run
##### Expected Results

Should run properly, and msg should hold the string "OK" if the package installs successfully.
##### Actual Results

When trying to install `bash-completion`

```
[18:23:27] failed: [box] => (item=bash-completion) => {"failed": true, "item": "time", "parsed": false}
[18:23:27] SUDO-SUCCESS-wodkadxzfptrfepsxznyhbmiskdwnbrm
[18:23:27] msg="OK" changed="False"
```

**Comment by jimi-c** [comment]
Hi @stelcheck, support for "Baby JSON" was removed in 1.8.0, so modules are expected to return full/valid JSON now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by stelcheck** [comment]
http://docs.ansible.com/developing_modules.html#deprecating-and-making-module-aliases

```
Modules should return JSON or key=value results all on one line. JSON is best if you can do JSON. All return types must be hashes (dictionaries) although they can be nested. Lists or simple scalar values are not supported, though they can be trivially contained inside a dictionary.
```

Then the documentation needs to be updated.

**Comment by jimi-c** [comment]
@stelcheck thanks, I've removed those references now, and the page will be updated the next time we push documentation.
