### ISSUE TITLE
Referencing host variable from another file doesn't always work anymore

### ISSUE THREAD

**Issue by jscheid** [ansible/ansible#9684]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.0, 1.8.1, current HEAD (e61e8a37f50860534610ef767315d70ba61583a2)

(bug introduced by https://github.com/ansible/ansible/commit/f1267c0b053e5975dc08c151530c802015902242#diff-af869caf5f6f46706dbf35970e39c686R1166)
##### Environment:

N/A
##### Summary:

Referencing a host variable from another file doesn't always work anymore.

This is a follow-up for #9667. It describes a related but distinct issue that isn't fixed by e61e8a37f50860534610ef767315d70ba61583a2.
##### Steps To Reproduce:

Run the playbook in https://gist.github.com/jscheid/5e688b3ba00cd9af6c83

More generally:
- Define two variable files that each use `to_json` on a variable defined in the other file, resp.
- Use the `template` action 
##### Expected Results:

Should be able to reference variable defined in other file.

Output with 716f3eb6d98af14dc896f4bd3b551c7c85febb6c:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [template src=template.j2 dest=/tmp/template] *************************** 
ok: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

And on target host:

```
$ cat /tmp/template 
"foo"
"bar"
```
##### Actual Results:

Unable to reference variable defined in other file.

Output with f1267c0b053e5975dc08c151530c802015902242 or e61e8a37f50860534610ef767315d70ba61583a2:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [template src=template.j2 dest=/tmp/template] *************************** 
fatal: [127.0.0.1] => an unexpected type error occurred. Error was Undefined is not JSON serializable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/redacted/playbook.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0   
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jscheid** [comment]
Awesome, thanks! Could you tell me if this is going to make it into 1.8.2?
