### ISSUE TITLE
Directory existance checks relying on ShellModule::checksum will fail when the python interpreter doesn't exist only 

### ISSUE THREAD

**Issue by jimktrains** [ansible/ansible#9704]
##### Issue Type:

Bug Report
##### Ansible Version:

Last working release: 1.7.2
First affected release: 1.8.0
Working in devel branch: no
Commit introduced: d4d23b1b1f6b65edb13032104da11dee1b7d639f
##### Environment:

Local System: Ubuntu 14.04
Remote System: FreeBSD 10
##### Summary:

When using a python interpreter that doesn't exist on the local machine (e.g. it's set to the location on the remote machine), ShellModule::checksum will return 4 (meaning the python interpreter doesn't exist), not 3 (meaning the file the checksum was asked for is a directory).

An example of a module that checks directory existence with ShellModule::checksum is `unarchive` with it's dest param.
##### Steps To Reproduce:

Set your python_interpreter to a path that doesn't exist on the local machine. Using a module such as unpack, attempt to do a directory existance check (e.g. unarchive src=/dev/zero dest=/tmp)
##### Expected Results:

The directory existence should be confirmed. (In the example above unzip should fail).
##### Actual Results:

The module fails with a "msg: dest 'dir' must be an existing dir" error.

**Comment by abadger** [comment]
From irc discussion, this is happening as a part of a local_action:

**Comment by abadger** [comment]
Thanks for working with me on IRC to identify and fix this!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
