### ISSUE TITLE
Github ships broken tarballs; releases.a.c ships crufty tarballs insecurely

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#9721]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

N/A
##### Summary:

Currently, the tarballs shipped by github for the 1.8.1 release don't contain any of the module code, due to it being in separate modules.  Because of this, the released tarballs on github can no longer be used.  I understand that may be unavoidable because of the splitting of repositories, but it should be noted, as tests will fail to run correctly.

The official source of the 1.8.1 tarball (releases.ansible.com) seems to be shipping .git cruft from the submodules, causing the size of the released tarball to balloon about 12x.  Furthermore, attempting to access it over HTTPS gets a cloudflare error back.

Please ensure that cruft is trimmed from the official released tarballs and ensure HTTPS access is available.

**Comment by mpdehaan** [comment]
The github tar balls are not release tar balls, just something it generates from the branch.

Official tar balls are available at releases.ansible.com

The "git cruft" stuff has been removed in 1.8.2 and we are not replacing them since home-brew keeps a SHA of that download.

As for https;//, we'll investigate.  

You may also download things from PyPi or the APT PPA, which we both maintain.

Thanks!
