### ISSUE TITLE
role parameters don't override role vars when using role as dep + using include:

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9738]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None

Also present in HEAD
##### Environment:

Ubuntu 14.04
##### Summary:

This may be considered pretty edge-case-y. 

When depending on a role and using role parameters to override a variable defined in the role's `vars` directory, the variable's value will revert to its original value (i.e. the role parameter ignored) if the role uses an 'include' task.

The dependency part is important - if the playbook uses the parameterized role directly, it works as expected.
##### Steps To Reproduce:

roles/parent/vars/main.yml:

```
var: default_value
```

roles/parent/tasks/main.yml:

```
- name: before include
  debug: var=var
- include: empty.yml
- name: after include
  debug: var=var
```

roles/parent/tasks/empty.yml:

```
# This can be empty
```

roles/child/meta/main.yml:

```
dependencies:
  - { role: parent, var: not_default }
```

play.yml:

```

---
hosts: localhost
roles:
  - child
```

working_playbook.yml:

```

---
hosts: localhost
roles:
  - { role: parent, var: not_default }
```
##### Expected Results:

```
TASK: [parent | before include] *********************************************** 
ok: [localhost] => {
    "var": "not_default"
}

TASK: [parent | after include] ************************************************ 
ok: [localhost] => {
    "var": "not_default"
}
```
##### Actual Results:

```
TASK: [parent | before include] *********************************************** 
ok: [localhost] => {
    "var": "not_default"
}

TASK: [parent | after include] ************************************************ 
ok: [localhost] => {
    "var": "default_value"
}
```

**Comment by dan-mcdonald** [comment]
This bug is definitely a regression since 1.7.2. Just tried to build an environment with 1.8.2 and started seeing this issue.

**Comment by mpdehaan** [comment]
It's not a regression because the bug didn't exist before and was then closed - however, this does seem like it may be a bug.  We'll investigate.  Thanks!

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your example above:

<pre>
PLAY: ***************************************************************************
TASK [parent : parent : before include] *****************************************
ok: [localhost] => {
    "var": "not_default", 
    "changed": false
}
TASK [parent : parent : include] ************************************************
included: empty.yml for localhost
TASK [parent : parent : debug msg=this is the included file] ********************
ok: [localhost] => {
    "msg": "this is the included file", 
    "changed": false
}
TASK [parent : parent : after include] ******************************************
ok: [localhost] => {
    "var": "not_default", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
