### ISSUE TITLE
ansible-galaxy --offline not mentioned in manpage

### ISSUE THREAD

**Issue by mavit** [ansible/ansible#9758]
##### Issue Type:

Documentation Report
##### Ansible Version:

```
ansible 1.8
  configured module search path = None
```
##### Environment:

RHEL 6.6
##### Summary:

Behind a firewall, `ansible-galaxy init` fails unless the `--offline` option is given (see also #9687).  However, the `--offline` option is not mentioned in the manpage.
##### Steps To Reproduce:

```
ansible-galaxy init foo
```
##### Expected Results:

```
- foo was created successfully
```
##### Actual Results:

```
- the API server (galaxy.ansible.com) is not responding, please try again later.
```

**Comment by abadger** [comment]
So -- #9687 is open to change init to do the equivalent of --offline all the time.  And this is just to have --offline documented.  Correct?

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by zemmali** [comment]
Use Ansible galaxy init to create a default 'common' role

ansible-galaxy init common --init-path=${PROJECT_PATH}/roles/
