### ISSUE TITLE
[OpenWrt] Can't start a service: "No such file or directory"

### ISSUE THREAD

**Issue by Malvineous** [ansible/ansible#9762]
##### Actual Results: See below

---

On the OpenWrt platform (latest version, "Barrier Breaker") a statement like this:

```
- name: Start DHCP server
  service: name=dhcpd state=started
```

Returns an error like this:

```
TASK: [dhcp-master | Start DHCP server] *************************************** 
<remote-host> ESTABLISH CONNECTION FOR USER: root
<remote-host> REMOTE_MODULE service name=dhcpd state=started
<remote-host> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 remote-host /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
failed: [remote-host] => {"failed": true, "parsed": false}
{"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": "initctl version", "rc": 2}
{"state": "started", "changed": false, "name": "dhcpd"}
OpenSSH_6.7p1, OpenSSL 1.0.1j 15 Oct 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 14221
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0


FATAL: all hosts have already failed -- aborting
```

The correct way to start this service is like so:

```
/etc/init.d/dhcpd start
```

This fails with any service, not just `dhcpd`.

**Comment by bcoca** [comment]
some fixes went into the service module in devel, can you check if this fixes it for you?

**Comment by abadger** [comment]
Broken in current devel:

```
ansible-playbook 1.9 (devel fa51e8f36d) last updated 2014/12/09 10:50:10 (GMT -700)
  lib/ansible/modules/core: (devel 375025d2e3) last updated 2014/12/09 09:02:22 (GMT -700)

$ ansible cumberland -m service -a 'name=iodined state=started'
cumberland | FAILED >> {
    "failed": true, 
    "msg": "no service or tool found for: iodined"
}
$ ssh root@cumberland ls -al  /etc/init.d/iodined
-rwxr-xr-x    1 root     root           608 Sep 23 06:43 /etc/init.d/iodined
```

**Comment by bcoca** [comment]
I traced this down, I had fixed some loopholes in service module detection that allowed start/stop to work on Openwrt but failed incoherently with enable/disable. 

OpenWRT uses their own variation for init management as enable/disabling is done through the init scripts themselves, so now you get the semi-valid message of "no service or tool found for:" which means service does not know how to enable/disable on this platform.

The solution is adding support for OpenWRT's sysV init variation.

**Comment by roberthartung** [comment]
Any update on this?

**Comment by bigHosting** [comment]
After updating to 1.9.4 from epel I cannot run any service tasks because of this error.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
