### ISSUE TITLE
Template rendering failure reports on wrong item using with_items

### ISSUE THREAD

**Issue by lorrin** [ansible/ansible#9773]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2, 1.6.6
##### Environment:

OS X 10.10.1 deploying to Ubuntu 14.04 LTS
##### Summary:

As discussed in #3907, you get a `TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'` error when your template contains hyphens in the variable names. I observe that when deploying multiple templates using `with_items` this error is reported on the preceding template. (Or perhaps on the first one? I've only got two here.)
##### Steps To Reproduce:

`templates/logging.ini` contains: `format={{env-name}}-{{node_flavor}}-{{ansible_ec2_instance_id}} {{service_name}} %(name)s[%(process)d]: %(message)s`

```
- name: Stage config
  template: src={{ item }} dest={{stage_dir}}/{{ item }}
  with_items:
    - client.cfg
    - logging.ini
```
##### Expected Results:

An error on `logging.ini`
##### Actual Results:

1.6.6:

```
TASK: [deploy_master | Stage config] **********************************
changed: [172.18.12.98] => (item=client.cfg)
fatal: [172.18.12.98] => {'msg': "unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}
fatal: [172.18.12.98] => {'msg': 'One or more items failed.', 'failed': True, 'changed': True, 'results': [{u'src': u'/home/ubuntu/.ansible/tmp/ansible-tmp-1418241796.41-129989221827551/source', u'md5sum': u'83661edf8868e50a00755b5d6843caf8', u'group': u'ubuntu', u'uid': 1000, u'dest': u'/opt/stage-dir.2014-12-10T19-56-56/client.cfg', u'changed': True, 'item': 'client.cfg', u'state': u'file', u'gid': 1000, u'mode': u'0664', 'invocation': {'module_name': 'template', 'module_args': u'src=client.cfg dest=/opt/stage-dir.2014-12-10T19-56-56/client.cfg'}, u'owner': u'ubuntu', u'size': 2556}, {'msg': "unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}]}
```

1.8.2:

```
TASK: [deploy_master | Stage config] **********************************
changed: [172.18.12.98] => (item=client.cfg)
fatal: [172.18.12.98] => {'msg': "TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}
fatal: [172.18.12.98] => {'msg': 'One or more items failed.', 'failed': True, 'changed': True, 'results': [{u'src': u'/home/ubuntu/.ansible/tmp/ansible-tmp-1418256136.07-136150186637538/source', u'md5sum': u'83661edf8868e50a00755b5d6843caf8', u'group': u'ubuntu', u'uid': 1000, u
'dest': u'/opt/stage-dir.2014-12-10T23-58-24/client.cfg', u'checksum': u'2e9bce35e3e670a7fb08b6a1da75392381b59b4c', u'changed': True, 'item': 'client.cfg', u'state': u'file', u'gid': 1000, u'mode': u'0664', 'invocation': {'module_name': u'template', 'module_args': u'src=cl
ient.cfg dest=/opt/stage-dir.2014-12-10T23-58-24/client.cfg'}, u'owner': u'ubuntu', u'size': 2556}, {'msg': "TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'", 'failed': True}]}
```

Corroborating data points:
- with original `client.cfg` and fixed `loggg.ini` template, deploy completes
- Emptying out `client.cfg` complete did not make a difference.
- Correctly rendered client.cfg was present on the box after each failure message.

**Comment by shintasmith** [comment]
I'm facing this issue. Is there a workaround on this?

I'm using ansible 1.8.2

**Comment by kkoudev** [comment]
+1

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    env-name: foo
  tasks:
  - name: Stage config
    template: src={{ item }} dest=/tmp/{{ item }}
    with_items:
    - file_1
    - file_2
    - bad_file
{"msg": "AnsibleUndefinedVariable: ERROR! Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.", "failed": true, "item": "bad_file"}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
