### ISSUE TITLE
Utils combine_variables does not update new variable (thread safety python api)

### ISSUE THREAD

**Issue by sulochan** [ansible/ansible#9797]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Debian 6
##### Summary:

We are using ansible python api with threaded workers running the same playbook with different extra_vars passed to them. When used like this ... a localhost delegated task seems to keep the variable from a previously running playbook and not the current playbook.

This is caused by : 
https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L1497

when called from: 
inject = utils.combine_vars(inject, self.setup_cache.get(host, {}))

will cause old values to be retained for the first task.
##### Steps To Reproduce:

https://gist.github.com/sulochan/c6a59fc3e0b94889639c

Both python thread using threading and playbook example is on the gist, when 2 threads are run you will see the second one will print the wrong id.
##### Expected Results:

Each thread should be able to call the same playbook with different variables.
##### Fix:

Fix looks to be simple giving priority to new value in combine vars although i have not looked at if there is any side effect to it.
ie: https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/__init__.py#L1497 
should return dict(b.items() + a.items())
rather than dict(a.items() + b.items())

**Comment by abadger** [comment]
Touching variables does have the potential to cause many many side effects.  We also don't support using threads with ansible -- we use multiprocessing in the command line tools to avoid issues with the limitations of threads under python (you may be able to as well depending on whether any of the rest of your code truly needs threads rather than separate processes).  With the API we do try to make it consistent and easy to understand so that it's easy to hack on but its main purpose is to implement the needs of the command line tools.

So between these concerns we're unlikely to fix this unless it's also causing issues for the command line tools  (at least intentionally... we are working on a rewrite of some of this code presently that aims to make the code more readable but if fixed your issue it would be as a side effect of the overall changes).

If you do think that making ansible threadsafe should be a goal, feel free to stop by the mailing list https://groups.google.com/forum/#!forum/ansible-devel and make a case for it.
-Toshio
