### ISSUE TITLE
Exception: host not found: {{ item }}

### ISSUE THREAD

**Issue by pawel7318** [ansible/ansible#9828]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2 - buggy
1.8.1 - OK
1.8 - OK
1.7 - OK
##### Environment:

Ubuntu 13.10
##### Summary:

```
  delegate_to: "{{ item }}"
  with_items:
    - foobar-host.in.my.domain
```

Throws an exception:

```
Exception: host not found: {{ item }}
```
##### Steps To Reproduce:

Exact task I have (check Summary section for example one):

```
- name: Configure secrets on clients
  template:
    dest=/etc/rsync_backup.secret
    src=rsync_backup.secret.j2
    owner=root group=root mode=0640
  delegate_to: "{{ item.hosts_allow }}"
  with_items: rsyncd.volumes
```
##### Expected Results:

```
TASK: [rsync-backup | Configure secrets on clients] *************************** 
ok: [bkp1.somedomain -> psql.somedomain] => (item={'password': 'xxxxxxx', 'hosts_allow': 'psql.somedomain', 'name': 'psql'})
```
##### Actual Results:

```
TASK: [rsync-backup | Configure secrets on clients] *************************** 
fatal: [bkp1.somedomain -> psql.somedomain] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 818, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1025, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/template.py", line 93, in run
    remote_checksum = self.runner._remote_checksum(conn, tmp, dest, inject)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1231, in _remote_checksum
    python_interp = inject['hostvars'][inject['delegate_to']].get('ansible_python_interpreter', 'python')
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 103, in __getitem__
    result = self.inventory.get_variables(host, vault_password=self.vault_password).copy()
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 442, in get_variables
    raise Exception("host not found: %s" % hostname)
Exception: host not found: {{ item.hosts_allow }}
```

**Comment by abadger** [comment]
Judging from the symptoms, I think this was fixed here: https://github.com/ansible/ansible/commit/3269a349f32a2b5c1fc079a2d174e01c541f444b

Could you take a look at that patch to lib/ansible/runner/**init**.py and see if it works for you?

**Comment by pawel7318** [comment]
Yep ! I can confirm - the patch worked for me.

**Comment by abadger** [comment]
Thanks!  I'll close this ticket then.  The fix should be in the next release of ansible.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
