### ISSUE TITLE
SSH key permisions check in ansible/lib/ansible/runner/connection.py prevents ansible from working on Windows from a Vagrant file

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/ansible#9836]
##### Issue Type:

“Feature Idea”

##### Ansible Version:

ansible 1.8.2

##### Environment:
-    Windows 7 Enterprise
-    babun 1.0.1
-    ansible 1.8.2 from pip
-    Vagrant 1.7.1

##### Summary:

I know is unsupported to run Ansible on a Windows control machine,
I just want to have it noted down that the in the following file ansible/lib/ansible/runner/connection.py
lines checking if the key is readable by group and world, in the current form is the only thing that prevents ansible being used as a provisioner for Vagrant.

Thank you!
##### Steps To Reproduce:

Environment set up like here http://www.azavea.com/blogs/labs/2014/10/running-vagrant-with-ansible-provisioning-on-windows/
##### Expected Results:

I hoped that it will run as it runs flawlessly from outside Vagrant when invoked with -k
##### Actual Results:

Commenting the check out, allows provisioning with ansible from a Vagrant definition file.

**Comment by jctanner** [comment]
@mihai-satmarean I think you've missed a key element of the blog post you linked to. The author is using cygwin to emulate a more "unixy" posix filesystem where the permission on the sshkey are actually set. Quickly looking through the babun page, it's an enhanced powershell/dos terminal and not in the same league as cygwin.

I suggest doing one of the following:
1. Use the shell provisioner in vagrant to run ansible inside the box instead of from the host
2. switch to a cygwin shell
3. Use the new linux subsystem for windows once that has matured a bit more: https://github.com/mitchellh/vagrant/issues/7731

EDIT: babun does claim to wrap around cygwin, but I still recommend trying vanilla cygwin instead.
