### ISSUE TITLE
Tasks for Panama release

### ISSUE THREAD

**Issue by timlnx** [ansible/ansible#985]
@mpdehaan this is for you buddy
- Bump specfile
- Review man pages (any new paramaters added?)
- For good measure:

```
$ touch VERSION
$ make docs
```
- Tag 0.7
- ping me to start working on the corresponding Fedora update

**Comment by mpdehaan** [comment]
I'm aware of these and have my own list.

The manpage in general is somewhat suboptimal because it doesn't elaborate much on the output of --help (the web docs are really needed for understanding and I don't want to duplicate that writing), so I'd like to see us get closer to help2man with a wrapper template in the future.
