### ISSUE TITLE
Bug report: Mixing templated variables from defaults and vars leads to odd results

### ISSUE THREAD

**Issue by xicesky** [ansible/ansible#9856]
##### Ansible Version: 1.8.2

(After upgrading, issue was present in 1.7.2 too)
##### Summary:

When doing calculations, i often use variables defined in the vars/main.yml file for a role.
If such calculations include variables (parameters) from the defaults/main.yml file this leads to very odd results.
##### Steps To Reproduce:

Minimized test case: https://sky.q1cc.net/bugreports/ansible/01/ansible_bug.tar.gz
Run

```
ansible-playbook site.yml
```

after changing the inventory appropriatly. Everything runs local though, remote machine is not actually altered.
##### Expected Results:

```
ok: [testbox.localnet] => {
    "msg": "v_cfg: 100\nv1: 100\nv2: 100\nshould_be: 100"
}
```
##### Actual Results:

```
ok: [testbox.localnet] => {
    "msg": "v_cfg: 100\nv1: 100\nv2: 0\nshould_be: 100"
}
```
#### Additional info

If one were to edit the file "roles/buggy/main.yml" to say:

```

---
v1: "{{ v_cfg }}"
v2: "{{ v1|int }}"
```

(i.e. remove the filter), everything works as expected.
#### Possible Workaround

Use set_fact to do calculations that involve both types of variables:
http://docs.ansible.com/set_fact_module.html

**Comment by xicesky** [comment]
Here is - finally - the test case:
https://sky.q1cc.net/bugreports/ansible/01/ansible_bug.tar.gz

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
< TASK [buggy : buggy : Debug memory sizes (autotuner)] >
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
ok: [testbox.localnet] => {
    "msg": "v_cfg: 100\nv1: 100\nv2: 100\nshould_be: 100", 
    "changed": false
}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
