### ISSUE TITLE
0.8 - Paramiko connections (and other connections?) should be cached

### ISSUE THREAD

**Issue by jeamland** [ansible/ansible#987]
I'm in Melbourne, Australia and I'm using ansible to set up a VM on Rackspace in their DFW location.

Ansible runs take a very, very long time mainly because paramiko sets up a new connection for every task.

I'm aware that I can switch to using "vanilla" ssh and thus gain the benefit of a ControlMaster/ControlPersist type arrangement but it seems to me that a better approach would be for ansible to cache connections in order to avoid having to wear the connection and authentication cost once per task.

I'm currently looking at refactoring the Connection classes to look more like ConnectionManager classes from which one requests a connection, thus allowing them to hand out cached connections on a (host, user) basis.

Is this an acceptable approach?

**Comment by mpdehaan** [comment]
It's really not, unless it were a perhaps configurable behavior you could turn on if you had a very small number of hosts.

At some point, you're going to have too many hosts, and it's not going to make sense to do that any more.   Keeping all connections open is, therefore, a suboptimal approach.

ControlPersist should really work a lot better.

You may also be interested in ansible-pull.

**Comment by mpdehaan** [comment]
It probably also makes sense to run your commands once logged in to a control machine at your site.

**Comment by dagwieers** [comment]
Why not keep connections open with a specific timeout (very much like what ControlPersist already does) ? Seems to be the best of both worlds. Without a ControlPersist-enabled ssh ansible is slow. Adding a newer openssh, or introducing Fedora in a corporate environment in order to manage systems is not acceptable (and doesn't fit Ansible's simple/out-of-the-box nature).

I would prefer to improve the current paramiko implementation, especially because it _is_ the default and it shouldn't be that hard. Already looked at it, but need a proper window for working on it :-/

**Comment by mpdehaan** [comment]
Basically exactly what I said earlier.

Configuring an optional LRU size to keep X connections open makes sense - especially when looking at playbooks with a configured "serial: N" value, there isn't a need for a configurable timeout, but neither will buy you anything with a large number of hosts.   Just close the hosts that fall out of the least recently used list.  We've already played with this before but I didn't accept it because it actually left all the connections open and wasn't configurable, and then the SSH connection type came along with better answers.

WRT what dag said, while I certainly agree that for some the stone-agedness of RHEL is a problem, I emphasize, but it's also the stone-agedness of RHEL that's the problem -- and folks should also contact their TAMs and get them to ship a newer openssh as well -- if we are to drive things forward, we don't want to wait for RHEL 7 everywhere.  But that's neither here nor there.

Anyway, I'm not against the configurable connection pool size -- though it should read from the config file in the [paramiko] section, not require additional parameters to the Runner() class, and be off by default.   Seems simple enough.   Send me a patch.   I'd also need some benchmarks to go along with the patch to make sure it worked.

**Comment by dagwieers** [comment]
I have been looking for the issue/pull-request/commit where one already played with something similar, but I couldn't find it. By any chance do you have a reference to those changes ?

**Comment by mpdehaan** [comment]
sorry, not sure it was ever a PR.  Anyway, it didn't close anything, ever,
so we don't want that.

**Comment by mpdehaan** [comment]
So, I'm being stupid here.  

There's a definite benefit to leaving them open even in the life of one runner call.   It should be configurable, yes, and it should have a default, but it makes sense even with one host because of the way we make multiple calls to clean up module directories and so forth.

**Comment by jkleint** [comment]
I think this would be a great improvement.  I actually looked into it a while ago, and it turned out to be a tough nut.  I'll share what I recall and maybe sharper minds can prevail.

First, ansible uses Python's multiprocessing for threads, so each connection lives in an entirely separate OS-level Python interpreter process.  You can't share them the normal multiprocessing way, because Paramiko's connection objects aren't pickle-able (The reason?  They contain thread locks.  The irony is poking me in the eyes.)  Even if you could, while it's _technically_ possible to share a socket among multiple processes, I'm not sure the low-level SSH library would be happy and Paramiko evidently isn't.

If we want to keep using processes (which we do, since otherwise Python / we can't use multiple CPUs for computation), then I'm assuming one connection must stay with a particular process.  PLEASE let me know if this assumption is incorrect.

If connections are bound to processes, then you need a specific process to do a particular task (on a particular host).  I don't see a(n efficient) way to use the standard multiprocessing Pool for this.  My idea was to have a shared task queue per connection, i.e., per `(user, host, port)`.  A manager process puts tasks on the appropriate queue, and a worker process checks all queues for which it has connections.  Alternately, you could have the manager dole out one task at a time to each process.

My takeaway from looking at the code was that it would be a good bit of work and lots of big structural changes.  Processes/connections need to persist at the play or playbook level, but currently they're launched (and terminated) per task.  You need a way of assigning connections to processes, which gets complicated if they go away, LRU-style.  And then there are lots of tuning and scheduling issues, like if one processes gets backed up with a bunch of tasks, is it worth starting up a duplicate connection in another process?

Fun stuff, and I'd be interested to hear others' thoughts.

**Comment by mpdehaan** [comment]
I think the benefit is mainly going to be inter-runner process only, and then hit or miss outside of that.   Still, it's meaningful.

I am not interested in making them shared between processes or changing the way multiprocessing works as people can and should being using -c ssh when they have the need.

Given if a host doesn't fail, it may likely be sent to the same worker every time.

Then again, it's a paramiko.  I don't care a lot.

**Comment by mnot** [comment]
I'm also in Melbourne, also using RAX DFW, so +1 on this (hey, benno).

Another motivation: I use iptables' hitcount mechanism to rate-limit SSH connections; ansible + parimiko sometimes falls foul of this. Of course, there are other ways to control SSH, and there is the ssh connection module, but still, would be nice.

**Comment by mpdehaan** [comment]
Haven't forgotten about this, but you really should log into a headnode
versus hitting multiple hosts from afar as it stands now.   The problem is
anything we do is going to be somewhat of a hit or miss optomization.

Logging into a headnode and using fireball mode especially.

I also have written to the list about how we can cut down the total number
of remote operations which will yield some pretty impressive gains.

Since each host is going to hit different forks there is a limit to what
this would achieve.

It could miss so much as to not be worth it, so I've been concentrating on
other improvements first.

**Comment by mnot** [comment]
Makes sense, -c ssh is a reasonable workaround for the time being. Thx!

**Comment by mpdehaan** [comment]
Ok, so long time defect, not much changing.  Until now.   A little bit.  Not all you want, but a bit :)

I've modified things such that SFTP connections to a given host live for the full life of the Runner operations.   In my testing, this cuts test runs down from 65 seconds to 53.

I've also previously pushed various things to cut down on remote ops in Runner which also helps with all connection types.

I will leave it to others to explore Paramiko Least-Recently-Used connection recycling.
