### ISSUE TITLE
Ansible git module does not fetch new branches when branch points to the same commit

### ISSUE THREAD

**Issue by xytis** [ansible/ansible#9876]
##### Issue Type:

Bug Report
##### Ansible Version:

 a55c6625d4771c44017fce1d487b38749b12b381 (latest dev)
##### Environment:

Target OS: Ubuntu 14.04
Target git version 1.9.1
##### Summary:

Ansible git module does not fetch new branches when branch points to the same commit
##### Steps To Reproduce:

Create a simple git repository:

```
C1 (master)
```

Run such task:

```
- git: repo=<repo_url> version=master
```

Update the repo so that a new branch would point to the same commit:

```
C1 (master)(newbranch)
```

Rerun task:

```
- git: repo=<repo_url> version=newbranch
```
##### Expected Results:

Task updates the source.
##### Actual Results:

Task fails.

**Comment by dahpgjgamgan** [comment]
Hi, it seems like git module is not running git fetch if it detects the sha1 being the same between current branch and new branch, which results in later branch checkout ending with an error:

```
fatal: Cannot update paths and switch to branch \\'newbranch\\' at the same time.
Did you intend to checkout \\'origin/newbranch\\' which can not be resolved as commit?
```

The quick and dirty fix would be to run a git fetch manually(with cmd module or whatever)

The better solution is to fix the git module - but I think that the issue and pull request should be moved to ansible-modules-core repository.

For 1.8 module the fix is near line 700 (I think): 

```
@@ -699,7 +699,8 @@ def main():
                 if version in get_tags(git_path, module, dest):
                     repo_updated = False
             else:
-                repo_updated = False
+                if version in get_branches(git_path, module, dest):
+                    repo_updated = False
         if repo_updated is None:
             if module.check_mode:
                 module.exit_json(changed=True, before=before, after=remote_head)
```

For v2 the code has changed, so I am not sure if the same fix applies, and I do not know yet (how to switch between module versions :))

EDIT: https://github.com/ansible/ansible-modules-core/pull/558

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
