### ISSUE TITLE
Precedence order change for top level and inventory level group_vars

### ISSUE THREAD

**Issue by michaelmcguinness** [ansible/ansible#9877]
**Issue Type:**
Bug Report

**Ansible Version:**
Working in 1.7
Broken in 1.8.1 and 1.8.2

**Environment:**
Suse 11SP3

**Summary:**
The inventory level group_vars (same directory as inventory) are not overriding the top level group_vars (same directory as playbooks).

**Steps To Reproduce:**
Created a stripped down environment to demonstrate the issue. 

$ find .
./group_vars
./group_vars/all.yml
./roles
./roles/test
./roles/test/tasks
./roles/test/tasks/main.yml
./test
./test/group_vars
./test/group_vars/all.yml
./test/inventory
./test.yml

---

./group_vars/all.yml contains a single entry:
testvar: top_level

./test/group_vars/all.yml contains a single entry:
testvar: env_level

The playbook invokes roles/test/tasks/main.yml which contains the single task:
- debug: var={{ testvar }}

The following steps illustrate the change in behaviour

$ sudo pip install ansible==1.7 2>&1 > /dev/null
$ ansible --version
ansible 1.7
$ ansible-playbook -i test test.yml
PLAY [myhost] *****************************************************************
TASK: [test | debug var={{ testvar }}] ***************************************\* 
ok: [mst] => {
"env_level": "{{ env_level }}"
}
PLAY RECAP *******************************************************************\* 
mst : ok=1 changed=0 unreachable=0 failed=0

$ sudo pip uninstall ansible -y 2>&1 > /dev/null
$ sudo pip install ansible==1.8.1 2>&1 > /dev/null
$ ansible --version
ansible 1.8.1
configured module search path = None
$ ansible-playbook -i test test.yml
PLAY [myhost] *****************************************************************
TASK: [test | debug var={{ testvar }}] ***************************************\* 
of: [mst] => {
"top_level": "top_level"    <<<<<<<<<<< CHANGED <<<<<<<<<<<<<<<
}
PLAY RECAP *******************************************************************\* 
mst : ok=1 changed=0 unreachable=0 failed=0 

**Expected Results:**
I was not expecting this order to change. I would expect to be able to set values in the group_vars at the playbooks level that would apply to all of my environments (test, stage, uat, production) and values in the group_vars at the inventory level for values that differ between environments (logging level, endpoint addresses, heap sizes etc) such that they override those generic values

**Actual Results:**
As illustrated above it seems that the top level group_vars overrides the inventory level group_vars. I can see similar issue reported about precedence but not exactly this one

**Comment by michaelmcguinness** [comment]
Did complete as per template I think. If someone could be specific about what is missing I will go back and update it as required.

**Comment by redbaron** [comment]
Broken on current devel too.

Simpler example without using roles or jinja templates (at playbook level):

Put following into prep.sh in empty dir and run it:

```
#!/bin/sh

mkdir -p group_vars env/group_vars

cat >env/group_vars/all <<EOF
testvar: from env
EOF

cat >env/hosts <<EOF
localhost
EOF

cat >group_vars/all <<EOF
testvar: top level
EOF

cat >test.yml <<EOF
- hosts: localhost
  connection: local
  tasks:
    - debug: var=testvar
EOF
```

Then to ansible 1.7.2 result:

```
/tmp/ans-1.7.2/bin/ansible-playbook -i env test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=testvar] ***************************************************** 
ok: [localhost] => {
    "testvar": "from env"
}
```

And ansible trunk:

```
/tmp/ans-trunk/bin/ansible-playbook -i env test.yml 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=testvar] ***************************************************** 
ok: [localhost] => {
    "var": {
        "testvar": "top level"
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by michaelmcguinness** [comment]
Yes, thanks. Even clearer.

**Comment by redbaron** [comment]
Git bisect identified this commit as source of problem: 0ab721d51e77ba4779b86b200128ca08cdcd6b7b

**Comment by abadger** [comment]
I believe this was a bugfix: http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

inventory is seen as more defaulty because it is pulled in for every playbook than what's in a playbook because playbooks are for a specific set of plays.

What you're describing sounds like you want to set site wide defaults in the "all" group.  Then override those with settings in specific groups.

**Comment by redbaron** [comment]
May I ask you to reopen the ticket, because documentation explicitly cover this case (http://docs.ansible.com/intro_inventory.html#splitting-out-host-and-group-specific-data) and we rely on this behaviour, which stops us from upgrading to 1.8: 

```
Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in either the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will be loaded second.
```

**Comment by abadger** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you were trying to use the playbook vars as a site-wide default that could be overridden by inventory group_vars.  However, when we fixed a bug in variable precedence, that stopped working.

We would suggest:
- Instead of wanting inventory to override playbooks to use the group "all"  to set site-wide defaults and then a more specific group to override the site-wide defaults.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by abadger** [comment]
Ah, missed that we aren't talking about in playbooks but rather in group_vars defined in the playbook directory.

@mpdehaan or @jimi-c Could you explain whether this is an intentional change in behaviour or not?  (We should change the documentation as well -- "loading last" has different meanings depending on whether first found is used or last found is used.)

**Comment by michaelmcguinness** [comment]
Do the labels associated with this ticket being reopened imply that the behaviour in 1.8 is correct and it is the documentation that is now in error?

**Comment by abadger** [comment]
@michaelmcguinness Working out right now whether it's a docs bug or a code bug.  Currently we're thinking that "variables in the playbook directory will be loaded second" in the quoted portion of the docs means that the group_vars in the playbook are supposed to _override_ the variables in the inventory directory.  This is how loading last is meant in other parts of the docmentation, agrees with the way the code works (all vars are loaded and the last var loaded takes precedence), and the  conceptual model of which setting is supposed to override.  Given all of that, 1.8's behaviour seems correct and the documentation needs to be clarified since "loading last/second/etc" is ambiguous if you don't know the broader context of variable loading.

However, the people who work on variable precedence most frequently are on vacation until January.  I think that the analysis of the situation is correct and the playbooks will need to be ported to the idiom mentioned earlier but I'll leave this bug open so that they can confirm that precedent was changed as a bug fix rather than the new precedence being an unintended bug.

**Comment by abadger** [comment]
Performed a bit of historical digging.  Looks like this is indeed a bug fix.  1.6.10 and earlier have the same behaviour as 1.8.x (the inventory group_var is overridden by the playbook group_var). Only the 1.7.x series has this bug where playbooks group_var is overridden by the inventory.

I'll continue to leave this open but I think the answer when jimi-c is back from vacation will be that 1.8.x behaviour is correct here.

**Comment by abadger** [comment]
@jimi-c I've pushed a clarification to the docs (but not to docs.ansible.com) in https://github.com/ansible/ansible/commit/4e9a8f87fe00649418324b79d0c474ad0ff46656  since "loading second" is definitely too ambiguous.

If you decide that inventory group_vars  are supposed to take precedence over playbook group_vars we can update which one is doing the overriding in the change.

**Comment by michaelmcguinness** [comment]
I have been thinking about this for a while and still think, despite the history, the 1.7 behaviour is more correct. I agree with the general principle that hideously complex precedence hierarchies should be avoided (I still wake up at night in a cold sweat thinking about my days wrangling Puppet configs) but in multistage environments a degree of precedence is useful. 

Ross Tuck's post (http://rosstuck.com/multistage-environments-with-ansible/) describes a set up similar to my own. That is to say a number of stages of an application stack from Integration Test, SIT, UAT, Performance, pre-Live, Live. Each stack consists of many application components across many servers with hundreds of variables being managed. The servers are grouped in the inventories (web servers, search servers, middleware servers etc) per stage and associated group_var files exist which are aligned to those groups. This stack of applications are the first of dozens of stacks of applications that we want to bring under Ansible control. So lots of groups and lots of variables.

The good news is that for any particular group nearly all of the variables have the same values regardless of whether it is my SIT servers or my Production servers (install directory, process owner, cron jobs etc). These I want to define once and so until now I have defined these at the playbook level group_vars. This seems to be the right place as it is not stage specific so they get applied to all stages. 

There is a small set of variables that I do want to change though, say in my Live environment (larger heap size, decreased logging verbosity, specific DB password etc). Those I would expect to be able to override at the stage specific, inventory level group_vars. So the playbook level group_vars is a collection of YAML files with large numbers of settings for each group and the inventory level group_vars is a collection of smaller YAML files overriding the playbook level where appropriate for that stage.

This seems to me to be a good and logical way to organise multistage environments which allows generic values to be set and then be overridden only when required for a specific stage. So much so I am surprised that this issue has not been raised earlier for the change in 1.8.

If there is another way of organising multistage environments then I am yet to figure it out which is definitely not the same as there not being another way of organising it.

**Comment by redbaron** [comment]
To some extent what you are describing can be achieved with role specific variables in role/defaults,but that practically usefull only if variable is used  only in one role.

I agree that having a "global default" level like group_vars is very usefull and in fact we rely on the behaviour of 1.7 too, but breaking documented behaviour is a thing which any serious project should aim to avoid, therefore even if it causes major inconvenience to us, I think ansible should keep current behaviour.

Where does it leave us? Given that Ansible project is notoriously slow in including new features, there are very slim chances that we'll have an 1.7 behaviour implemented in 1.8 as some additional feature (lets say as "group_default" playbook level directory). 

If I read `Inventory` class correctly (from lib/ansible/inventory/**init**.py) "global default" feature can be achieved with small vars_plugin, as in `_get_group_variables`  method it first reads vars from plugin, then updates them from inventory/group_vars and playbook group_vars, so if that plugin will load default from some custom directory, it can do what we want without touching ansible source code.

**Comment by michaelmcguinness** [comment]
@redbaron, thank you for your suggestion. Yes, role variables will solve the problem for some of the variables but as you point out this is an issue where variables apply to different roles and those roles are being applied to different servers. If you have worked with WebSphere Application Server you may be familiar with some of those scenarios. I have written some modules for WebSphere which I hope to submit soon.

I hear what you say about having a plugin and it sounds like it would work but I am keen to follow a standard Ansible model but at the same time have a simple variable hierarchy rather than go down a bespoke route. I will go down that route though if it makes logical sense..

As I mentioned before it is surprising that this was not encountered sooner as I would have thought our use case would be widely used. The two-place global/specific variable model is something I have been using for years, long before Ansible, Puppet, Chef and the others came along.

I am fortunate I suppose in that our Ansible effort is only a few months old so a redesign is feasible, If it were a year's time I would have a major task on my hands. 

I hope the argument I put here makes sense to the core Ansible team.

**Comment by bcoca** [comment]
I managed a very similar environment but I did not use play specific
group_vars, I put most configurations inventory group_vars, for those
variables that changed by environment I had them in group_vars/all and
overrode in the environment specific group_vars.

I had groups for 3 reasons: purpose, location and environment (i.e:
webservers, colo1, development) every server was at least in 3 of these
groups (+ all).  So I could have a generic tomcat vars in all, override the
memory requirements for staging and production but keep it common for
development, qa and uat.

So what you want can be achieved it just requires a bit different

## organization.

Brian Coca

**Comment by redbaron** [comment]
You are talking about having single inventory with all environments specified in groups, right? 

This way you force all vairables to be kept in `all`, rather than having a group specific variables inside group vars, that is because if you have var defined in both "web"  (purpose) and "prod" (environment) groups, then which one wins is IMHO strictly not defined (AFAIK in practice it goes in alphabetic order, not sure). That leads to an unpractically big 'all" variable files. In addition to this, it  makes it tricky to run playbooks written for particular group (like `hosts: web` ), because now you all of sudden apply changes simultaniously to all environments and you have put extra effort to mitigate it, like having artificial `<purpose>-<env>` groups which are children of `<purpose>` group and never forget to use --limit "<purpose>-<env>".

Not to mention that single inventory way goes against docummented best pracrices which most newcomers to ansible adopt blindly relying on a experience of ansible devs: http://docs.ansible.com/playbooks_best_practices.html#deployment-vs-configuration-organization

**Comment by bcoca** [comment]
It normally makes no sense to define a variable across environments AND
function, you chose one or the other depend on your needs. Data that only
changed by function would go into group_vars/webservers, data that changed
by location (ntp,dns, etc) would go into group_vars/colo1, data that
changed by environment (this could affect different functions) would go
into group_vars/development, etc. This avoids the webservers vs staging
group issue. Yes, the all file gets large, but that was not a big issue.

I also had inventory files for each environment, so no need for limit
(which i still used for other reasons), this also allowed different access
rules by using the file permissions (i.e. only devops could read/execute
the 'production' inventory). All in the same directory so you could share
group/host_vars or for the case in which you needed to access ALL servers
you could point at the directory as your inventory.

The best practices cover the most common use cases, it is not something you
should use when it does not apply well to your case. I'm not saying my
setup above works for all situations, but it served me well and your needs
seem to be very similar to what mine were.

## 

Brian Coca

**Comment by redbaron** [comment]
Problem is that most variables are function variables as ammount of location specific vars comparing to app specific vars tends to zero (we are talking about orders of magnitude here), and any of them can be overriden by env (think of "apache_workers"), so either all of them must be kept in all in case some env required to override it which make `all` file to be enormosly large or to be split into 2 sets overridable and not overridable, which is even worse as var required to be migrated to "all"  file the moment env needs to override it.

Having multiple hosts files inside single invenotory dir, all sharing same set of group/host vars and invoking ansible playbook pointing to exact file is a brilliant idea, I never thought of that and it is definitely going to affect future layout of my ansible playbooks, especially when I figure out how to do function vs env without to much maintenance overhead (like having group:children tricks etc). Very much thank you for this idea.

I agre about best practices, but in reality you first follow and by the time you understand what is your case and what do you really need it is to late change anything.

**Comment by bcoca** [comment]
btw, if that worried about all file being that large, you can do 'all dir'

group_vars/all/{file1,file2}

## 

Brian Coca

**Comment by neh** [comment]
I'll just throw in my opinion in support of the issue as filed (inventory group_vars should override global group_vars). It makes sense conceptually, to me at least, that the inventory vars should win. It also seems like the current (1.8) behaviour is inconsistent, since inventory vars override group_vars/all, but not other files in the same location.

**Comment by redbaron** [comment]
What is global group_vars?

**Comment by bcoca** [comment]
@neh there are no global group vars, only those adjacent to inventory or adjacent to the play

**Comment by neh** [comment]
Ah, fair point. I was thinking of them as global since I keep them at the root of my ansible repo. Calling them play-adjacent might change my mind about this bug.

**Comment by ldevigne** [comment]
Hi,

In our case, we have several inventories working with same hostnames and group_vars default values are a high missing feature of ansible.

is this ticket definitely closed ? Or would it be possible to add an extra-option (ansible.cfg) so that group_vars would work as real default values (i.e take precedence over inventory group_vars).

Regards

**Comment by bcoca** [comment]
So to clear this up as some of you seem to be asking for contradictory features:

These act as defaults:
 /path/to/inventory
            group_vars/
                              all
                              group1

These override the inventory ones:
/path/to/play.yml
             group_vars/
                               all
                               group1

1.7 reversed this (as a bug) but it was fixed in 1.8 and going forward.

**Comment by mitsuhiko** [comment]
So what exactly are affected users supposed to do now?  What's a supported way to load defaults?

**Comment by donjohnson** [comment]
-1. I am currently having to refactor my entire ansible repo from top-level group_vars, a few app deploy roles, and thin/dry inventory group_vars to no top-level group_vars, a ton of per-app roles differing from each other only in name and with those old top-levels in as role defaults. After this I think we'll lock on 2.0.1 and just ride it out :-/

**Comment by igcherkaev** [comment]
Was it really that hard to introduce a setting to `ansible.cfg` to swap play/inventory group_vars/host_vars precedence? It'd satisfy both camps. :-( I think many would like to have that "bug" from 1.7 available as a feature. Why resisting?

**Comment by igcherkaev** [comment]
Seriously, guys, the fix seems to be very simple. Just swap these two if some config option is set in the `ansible.cfg` file: 

https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py#L764

Current:

```
    basedirs = [_basedir, _playbook_basedir]
```

Switch to:

```
    basedirs = [_playbook_basedir, _basedir]
```

It swaps the precedence Ansible picks variables from. Nothing else should be affected by this. I'll stick with this change on my ansible host for a while to see if any issues arise.

So for everyone who's struggling with this, be my guest to try it too.

**Comment by andrew-sumner** [comment]
@igcherkaev Is your suggestion something that should work?  I tried putting 

> basedirs = [_playbook_basedir, _basedir]

 in ansible.cfg and it made no difference when using ansible version 2.3.1.0.

I can't understand how ansible continue to stick with this behavior.  

- From my research it is based on the view that plays are somehow more specific than inventories.  I don't understand that view at all as plays strike me as a global thing that operate on what inventory tells it to do :-(
- The only solutions I've seen are *very* hacky

**Comment by redbaron** [comment]
@andrew-sumner , solution @igcherkaev proposed is to swap values in code, it was `inventory/__init__.py` at the time of writing, might be something else by now
