### ISSUE TITLE
Docker Containers Keep on Shutting down when the Playbook execution is done

### ISSUE THREAD

**Issue by kgrvamsi** [ansible/ansible#9901]
##### Issue Type

Bug Report
##### Ansible version

Ansible = 1.8.2
Docker-py = 0.6.0
##### Environment

12.04.5 LTS
##### Summary

role/main.yml

```

---
- name: running docker-registry container
  docker:
    image: tcurdt/docker-registry
    name: docker-registry
    state: running
    ports: "127.0.0.1:5000:5000"   
```

Output /var/log/syslog

```
Dec 27 02:58:13 test ansible-docker: Invoked with publish_all_ports=False tty=False links=None docker_url=unix://var/run/docker.sock image=ubuntu:12.04 detach=True hostname=None lxc_conf=None state=running env=None volumes_from=None email=None memory_limit=0 dns=None expose=None stdin_open=False user=None password=NOT_LOGGING_PASSWORD memory_swap=0 count=1 name=None privileged=False command=None volumes=None debug=False ports=None 
Dec 27 02:58:13 test kernel: [20246.060154] device veth6fbb0a7 entered promiscuous mode
Dec 27 02:58:13 test kernel: [20246.060464] IPv6: ADDRCONF(NETDEV_UP): veth6fbb0a7: link is not ready
Dec 27 02:58:13 test kernel: [20246.095010] IPv6: ADDRCONF(NETDEV_CHANGE): veth6fbb0a7: link becomes ready
Dec 27 02:58:13 test kernel: [20246.095083] docker0: port 1(veth6fbb0a7) entered forwarding state
Dec 27 02:58:13 test kernel: [20246.095089] docker0: port 1(veth6fbb0a7) entered forwarding state
Dec 27 02:58:13 test kernel: [20246.119246] docker0: port 1(veth6fbb0a7) entered disabled state
Dec 27 02:58:13 test kernel: [20246.120744] device veth6fbb0a7 left promiscuous mode
Dec 27 02:58:13 test kernel: [20246.120749] docker0: port 1(veth6fbb0a7) entered disabled state
```

Output docker ps == null

The Containers are not in the Running mode instead they get shutdown.
##### Expected Result

The Containers Have to run based upon the state mentioned in the role/main.yml

**Comment by abadger** [comment]
From the output, this seems to be a misunderstanding of docker containers rather than ansible.

docker containers come in two flavours:

One flavour is mostly seen with self-contained applications.  These containers are usually configured so that when the docker container is invoked, the applications are started and then run continuously while serving requests on a certain port.  So if you started that sort of docker container using the ansible docker module it should indeed start up and keep running.

The other flavour is more generic.  They provide an environment but don't start up any program when started.  These types of docker containers are used for base images that create the basic environment that someone then runs their application within.  They are also sometimes used as the basis of "lightweight virtual machines" -- containers that are just intended to come up with a certain environment that people can then log into and do their own thing on.  These containers necessitate
specifying a command to run when the docker container starts.  The container will continue to run until that command exits (which means that running sshd, httpd, or similar will make the container run indefinitely.  OTOH, running something like `expr 3 + 4` will quickly run, calculate the value, and then exit.)

The ubuntu container that you are using is one of the latter type.  So it shutting down has nothing to do with ansible.  Starting the container using similar parameters on the command line would shut down similarly.  Depending on what you're trying to do you may want to build your own container using the ubuntu container as the parent container image or you may want to use the command parameter of the ansible docker module to set the command you expect to run inside of the container: http://docs.ansible.com/docker_module.html
