### ISSUE TITLE
git module: Not work with update option

### ISSUE THREAD

**Issue by iwai** [ansible/ansible#9907]
ansible 1.8.1

``` bash
$ python --version
Python 2.6.9
```

Not worked

``` bash
ansible localhost -vvvv -i ./hosts -c local -m git -s -a "repo=https://github.com/m4rw3r/php-libev.git \
dest=/tmp/php-libev version=56557bbb590a6415196e9e64fc12c5e0a32f7726 \
update=no accept_hostkey=yes"
```

Not failed, but not cloned.

Working

``` bash
ansible localhost -vvvv -i ./hosts -c local -m git -s -a "repo=https://github.com/m4rw3r/php-libev.git \
dest=/tmp/php-libev version=56557bbb590a6415196e9e64fc12c5e0a32f7726 \
accept_hostkey=yes"
```

have already been reported?

**Comment by abadger** [comment]
I'm not certain I understand what you're reporting broken but I have a feeling it may be this issue: https://github.com/ansible/ansible-modules-core/issues/426

If it is something different, please add some more information about what you are expecting to happen and what is happening instead.

Thanks!

**Comment by iwai** [comment]
i'm mistaken specify path to private key. specified symlink path.
it modify to direct path, its worked.

I'm afraid my expressions may be rude or hard to read, because I'm not so good at English.

**Comment by abadger** [comment]
From your original comment, I see that update=no is the difference between the working and non-working runs.  I think that this is a bug/mis-feature in the git module for ansible 1.8.0-1.8.2.  The linked bug https://github.com/ansible/ansible-modules-core/issues/426 contains a fix for that that's applied to the devel tree.  The fix restores the former behaviour of update= so that update=no will clone a repository but not update it once cloned.

As a workaround until a new release of ansible is out you could do things in two steps like this: https://github.com/ansible/ansible-modules-core/issues/426#issuecomment-70276429

or you could apply the relevant commit as a patch to the code: https://github.com/ansible/ansible-modules-core/commit/b650ad1671a0f0cd5f2f139407bc793b6f1fd6a3

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by iwai** [comment]
@abadger thank you so match!!
