### ISSUE TITLE
When including tasks, parameters are not passed or resolved correctly.

### ISSUE THREAD

**Issue by rjprins** [ansible/ansible#9919]
When using the include statement in a role to execute some task with parameters, the parameters are not passed or resolved correctly.

Example:

``` bash
$ cat playbook.yml

- hosts: sandbox
  sudo: yes
  gather_facts: true
  vars:
    foobar: 'blah'

  roles:
    - somerole


$ cat roles/somerole/tasks/main.yml

# Prints 'blah' because foobar is defined:
- debug: msg="{{ foobar|default('notblah', true) }}"

- include: ../../../tasks/sometask.yml
  foo: "{{ foobar|default('notblah', true) }}"


$ cat tasks/some.yaml
# Should print 'blah' because foo is a parameter in the include statement, 
# but prints 'notblah'!
- debug: msg="{{ foo }}"

# Prints 'blah' because foobar is implicitly passed.
- debug: msg="{{ foobar }}"


$ ansible-playbook ./playbook.yml

PLAY [sandbox] *********************************************************

GATHERING FACTS ***************************************************************
ok: [10.0.0.1]

TASK: [somerole | debug msg="notblah"] ***************************************
ok: [10.0.1.21] => {
    "msg": "blah"
}

TASK: [somerole | debug msg="notblah"] ************************************
ok: [10.0.1.21] => {
    "msg": "notblah"
}

TASK: [somerole | debug msg="{{ foobar }}"] *******************************
ok: [10.0.1.21] => {
    "msg": "blah"
}

PLAY RECAP ********************************************************************
10.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0
```

**Comment by traut** [comment]
Fully executable example - https://www.dropbox.com/s/hol5eb3ag1vjk5o/test.tbz2 - // thanks to @farrellit

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
PLAY: ***************************************************************************
TASK [somerole : somerole : debug msg=blah] *************************************
ok: [localhost] => {
    "msg": "blah", 
    "changed": false
}
TASK [somerole : somerole : include foo=blah] ***********************************
included: ../tasks/sometask.yml for localhost
TASK [somerole : somerole : debug msg=blah] *************************************
ok: [localhost] => {
    "msg": "blah", 
    "changed": false
}
TASK [somerole : somerole : debug msg=blah] *************************************
ok: [localhost] => {
    "msg": "blah", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
