### ISSUE TITLE
Bug report: multiline parsing in `local_action` results in module not found

### ISSUE THREAD

**Issue by rouge8** [ansible/ansible#9939]
##### Issue Type:

Bug Report
##### Ansible Version:

``` console
$ ansible --version
ansible 1.8.2
  configured module search path = None
```
##### Environment:

OS X 10.9.5. Tried with Ansible installed from Homebrew and in a virtualenv from pip.
##### Summary:

The changes to module argument parsing in ansible/ansible@317ab06bc6bdecd8a3b9c254702d6d7ea7e334d9 / ansible/ansible@8d0c1dd2faa21074d12832c074a4f4afa9e577e2 mean that on Ansible 1.7.2+, `local_action` (and presumably anything else that takes a module name as its first argument) no longer strips newline characters from the module name, resulting in module not found errors when Ansible looks for `module_name\n` rather than `module_name`. Originally reported as ansible/ansible-modules-core#368.

Switching from the 

``` yaml
local_action: >
  module_name
    key=val
```

syntax we had been using in our playbooks on 1.7.1 and earlier to

``` yaml
local_action:
  module: module_name
  key: val
```

fixes it, but I'm not sure if this is intentional behavior.
##### Steps To Reproduce:

Here's the shortest playbook I could come up with to reproduce the problem:

``` yaml
- hosts: all
  gather_facts: no
  tasks:
    - name: Do something
      sudo: no
      local_action: >
        command
          ansible --version
```
##### Expected Results:

With Ansible 1.7.1:

```
$ ansible-playbook -i localhost, -c local  ~/Desktop/sample-playbook.yml -vvvv

PLAY [all] ********************************************************************

TASK: [Do something] **********************************************************
<127.0.0.1> REMOTE_MODULE command ansible --version
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729 && echo $HOME/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729']
<127.0.0.1> PUT /var/folders/v5/9frdjzm50p9_60zfy7s0568000010y/T/tmp_rtiGD TO /Users/rouge8/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729/command
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/rouge8/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729/command; rm -rf /Users/rouge8/.ansible/tmp/ansible-tmp-1420472392.16-179064520397729/ >/dev/null 2>&1']
changed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": ["ansible", "--version"], "delta": "0:00:00.327966", "end": "2015-01-05 10:39:52.587168", "rc": 0, "start": "2015-01-05 10:39:52.259202", "stderr": "", "stdout": "ansible 1.7.1"}

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
$ ansible-playbook -i localhost, -c local  ~/Desktop/sample-playbook.yml -vvvv

PLAY [all] ********************************************************************

TASK: [Do something] **********************************************************
<127.0.0.1> REMOTE_MODULE command ansible --version
fatal: [localhost -> 127.0.0.1] => module command
 not found in configured module paths

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/rouge8/sample-playbook.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat 9939.yml
- hosts: localhost
  gather_facts: no
  tasks:
  - local_action: >
      shell
        echo 'hello';
        echo 'world'
# ansible-playbook -vv 9939.yml 
1 plays in 9939.yml
PLAY: ***************************************************************************
TASK [command] ******************************************************************
changed: [localhost] => {"changed": true, "end": "2015-07-01 14:05:34.886260", "stdout": "hello\nworld", "cmd": "echo 'hello'; echo 'world'", "start": "2015-07-01 14:05:34.883047", "delta": "0:00:00.003213", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "echo 'hello'; echo 'world'", "_uses_shell": true}}, "stdout_lines": ["hello", "world"], "warnings": []}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
