### ISSUE TITLE
Ansible: sshpass dependency issues

### ISSUE THREAD

**Issue by RoelVdP** [ansible/ansible#9941]
1) Why does sshpass need to be installed for ad-hoc commands, while normal ssh works just fine?
2) Why does Ansible ask for a ssh password if it is not going to subsequently use it because of a [apparetly (though seemingly incorrect) - ref question 1] missing dependency?

```
[roel@localhost percona-qa]$ echo ${ANSIBLE_HOSTS}
/home/roel/ansible/ansible_hosts
[roel@localhost percona-qa]$ cat ${ANSIBLE_HOSTS}
127.0.0.1
[roel@localhost percona-qa]$ ssh 127.0.0.1
roel@127.0.0.1's password:
Last login: Tue Jan  6 09:15:26 2015 from localhost
[roel@localhost ~]$ exit
logout
Connection to 127.0.0.1 closed.
[roel@localhost percona-qa]$ ansible all -m ping --ask-pass
SSH password:
127.0.0.1 | FAILED => to use the 'ssh' connection type with passwords, you must install the sshpass program
```

**Comment by sivel** [comment]
sshpass is needed so that Ansible can respond to the password prompt for ssh connections.  You have a few options to not require sshpass.
1. Don't use password based auth, use ssh key based auth
2. Use the `paramiko` transport instead of `ssh`

Also if you want to run tasks on localhost, you might consider setting the connection type to `local`, perhaps in your inventory file using `127.0.0.1 ansible_connection=local` or via `-c local` on the command line

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by RoelVdP** [comment]
@sivel Thanks! 
@bcoca Ack. In this case it looked like a bug.
