### ISSUE TITLE
Ansible Documentation in PDF format

### ISSUE THREAD

**Issue by StuartBudd** [ansible/ansible#9945]
Hello

I can not find any copies of the Ansible documentation in PDF format.
Please can you direct me to where it is located.

It does seem strange that PDF versions of the documentation for a software produce is not very easily accessible.
Perhaps I am just missing it but I can not find it anywhere.

Thank you

**Comment by abadger** [comment]
We do not produce documentation in pdf format at this time mainly because ansible is changing and updating all the time and we don't want to be passing obsolete documentation around to users.  The website http://docs.ansible.com and using /usr/bin/ansible-doc are the ways we promote for getting documentation.

If you need hardcopy you could write a script to print those or convert from the restructured text sources: https://github.com/ansible/ansible/tree/devel/docsite

**Comment by ghost** [comment]
This is still a problem. The main thread for this issue is #4265.

**Comment by sampablokuper** [comment]
This is still a problem. The main thread for this issue is #4265.
