### ISSUE TITLE
Wrong order of rendering of variables

### ISSUE THREAD

**Issue by cscetbon** [ansible/ansible#9946]
Issue Type: Bug Report

Ansible Version: **1.8.2**

Environment: Ubuntu Trusty

Summary:

Dynamic variables defined in  in role/test/vars/main.yml rendered after the playbook role/test/tasks/main.yml has been played

Steps To Reproduce:

Use the provided Vagrantfile to provision a vm

The whole code of a failing example can be found at https://www.dropbox.com/s/qdvsm7tirzlnav6/bug.tgz

Expected Results:

```
TASK: [test | debug var=test_version] *****************************************
ok: [master] => {
    "test_version": "1.2.13"
}

TASK: [test | debug var=test] *************************************************
ok: [master] => {
    "test": {
        "var1": "master",
        "version": "1.2.13"
    }
}

TASK: [debug var=test_version] ************************************************
ok: [master] => {
    "test_version": "1.2.13"
}

TASK: [debug var=test] ********************************************************
ok: [master] => {
    "test": {
        "var1": "master",
        "version": "1.2.13"
    }
}
```

Actual Results:

```
TASK: [test | debug var=test_version] *****************************************
ok: [master] => {
    "test_version": "1.0"
}

TASK: [test | debug var=test] *************************************************
ok: [master] => {
    "test": {
        "var1": "master",
        "version": "1.2.13"
    }
}

TASK: [debug var=test_version] ************************************************
ok: [master] => {
    "test_version": "1.2.13"
}

TASK: [debug var=test] ********************************************************
ok: [master] => {
    "test": {
        "var1": "master",
        "version": "1.2.13"
    }
}
```

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We do not consider this this is a bug, as this works as we designed it to, that is the expected variable behavior.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
