### ISSUE TITLE
Does setting "ansible_sudo=yes" in inventory-file and "sudo: yes" in playbook the same?

### ISSUE THREAD

**Issue by mathieumd** [ansible/ansible#9986]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9 (devel 8bcd2b8f9c) last updated 2015/01/12 21:33:19 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 8c8be0e48c) last updated 2015/01/12 21:34:14 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ffa8abf979) last updated 2015/01/12 21:34:14 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 27d5e5124f) last updated 2015/01/12 21:34:14 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/19 23:20:26 (GMT +200)
  configured module search path = None
```
##### Environment:

Local:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```

Remote:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```
##### Summary:

Depending on the location of sudo enabling option, sudo-password input is failing or not.
##### Steps To Reproduce:

Remote SSH user is `deploy`, which is in the `sudo` group, and sudo is working:

``` bash
id
uid=1000(deploy) gid=1000(deploy) groups=1000(deploy),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),109(lpadmin),110(sambashare)

sudo id
[sudo] password for deploy: 
uid=0(root) gid=0(root) groups=0(root)
```

Inventory file `inventory`:

``` ini
[Servers]
server1
server2

[Servers:vars]
ansible_ssh_user=deploy
ansible_sudo=yes
```

Playbook `playbook.yml`:

``` yaml
- hosts: all
  tasks:
    - file: path=/root/write_access state=touch
```

Command:

``` bash
ansible-playbook -i inventory playbook.yml --limit server1 -K
```
##### Expected Results:

The file `/root/write_access` should have been created (which only root can do).
##### Actual Results:

The play fails:

```
sudo password: 
[...]
TASK: [file path=/root/write_access state=touch] ****************************** 
fatal: [server1] => Missing sudo password
```
##### Other ways which works:

It works _if_ you enable sudo either:
- with `--sudo` on the command line; or
- with `sudo: yes` into the playbook, like this:

``` yaml
- hosts: all
  sudo: yes
  tasks:
    - file: path=/root/write_access state=touch
```

```
sudo password: 
[...]
TASK: [file path=/root/write_access state=touch] ****************************** 
changed: [server1]
```

I believe important to be able to enable or not sudo **from the inventory** (and not from the command-line or the playbook themselves), because all servers may not have sudo installed (Debian vs. Ubuntu).

**Comment by mspiegle** [comment]
Not only could sudo be installed (or not), but some cloud images (I'm thinking of EC2 in particular) have the default user set as root in which case I don't need sudo.  Other images use "centos" or "ec2-user" which would require sudo.  I'd love to be able to configure this via add_host/inventory.

**Comment by tamsky** [comment]
Similar discussion at https://groups.google.com/forum/#!topic/ansible-project/ZEnYyvLcqL0

**Comment by tamsky** [comment]
Related: #10669

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- ansible_become is a functional variable now, which is a drop in replacement for your given example.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
