### ISSUE TITLE
Tasks from include executed on false condition

### ISSUE THREAD

**Issue by OnlyLoveOleg** [ansible/ansible#9998]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9 (devel f1fdddb640) last updated 2015/01/13 14:06:26 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 8c8be0e48c) last updated 2015/01/13 14:09:53 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD ffa8abf979) last updated 2015/01/13 14:09:53 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 27d5e5124f) last updated 2015/01/13 14:09:54 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/31 10:08:32 (GMT -400)
  configured module search path = /usr/share/ansible
##### Environment:

Ansible node:
12.04.5 LTS, Precise Pangolin x64

Managed node:
12.04.5 LTS, Precise Pangolin x64
##### Summary:

Using a simple role to manage users and ssh keys on remotes the role should only make changes when the "users" variable is defined for some reason tasks that use with_subelements loop got evaluated when the yml file should not be included (i.e the users variable is undefined).
##### Steps To Reproduce:

The relevant portion of the role:
tasks/main.yml

```

---
- name: Check for supported operating system on target
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ansible_os_family not in ['Debian']

- name: include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- debug: msg=users is Defined :)
  when: users is defined

- name: Include Debian specific tasks
  include: Debian.yml
  when: users is defined and ansible_os_family == 'Debian'
```

tasks/Debian.yml

```

---
- name: Debian | Manage users
  user: >
   append={{ item.append |default(omit)}}
   comment={{ item.comment |default(omit)}}
   createhome={{ item.createhome |default(omit)}}
   force={{ item.force |default(omit)}}
   generate_ssh_key={{ item.generate_ssh_key |default(omit)}}
   group={{ item.group |default(omit)}}
   groups={{ item.groups |default(omit)}}
   home={{ item.home |default(omit)}}
   login_class={{ item.login_class |default(omit)}}
   move_home={{ item.move_home |default(omit)}}
   name={{ item.name |mandatory}}
   non_unique={{ item.non_unique |default(omit)}}
   password={{ item.password |default(omit)}}
   remove={{ item.remove |default(omit)}}
   shell={{ item.shell |default(omit)}}
   ssh_key_bits={{ item.ssh_key_bits |default("2048")}}
   ssh_key_comment={{ item.ssh_key_comment |default("ansible-generated")}}
   ssh_key_file={{ item.ssh_key_file |default(".ssh/id_rsa")}}
   ssh_key_passphrase={{ item.ssh_key_passphrase |default(omit)}}
   ssh_key_type={{ item.ssh_key_type |default("rsa")}}
   state={{ item.state |default("present")}}
   system={{ item.system |default(omit)}}
   uid={{ item.uid |default(omit)}}
   update_password={{ item.update_password |default("always")}}
  with_items: users

- name: Debian | Manage SSH authorized keys
  authorized_key: >
   key='{{ item.1.key }}'
   key_options='{{ item.1.key_options | default(omit) }}'
   manage_dir='{{ item.1.manage_dir | default("yes") }}'
   path='{{ item.1.path | default(omit) }}'
   state='{{ item.1.state | default("present") }}'
   user={{ item.0.name }}
  with_subelements:
   - users
   - authorized
```
##### Expected Results:

Expected all the tasks in Debian.yml to be skipped since the "users" variable is undefined.

tasks/main.yml

```
- name: Include Debian specific tasks
  include: Debian.yml
  when: users is defined and ansible_os_family == 'Debian'
```
##### Actual Results:

when running ansible-playbook the task "Manage SSH authorized keys" from include fails .

```
PLAY [test-nodes] ***

TASK: [Users | Check for supported operating system on target] ****************
skipping: [node01.example.org]

TASK: [Users | include os specific variables] *********************************
ok: [node01.example.org]

TASK: [Users | debug msg=users is Defined :)] *********************************
skipping: [node01.example.org]

TASK: [Users | Debian | Manage users] *****************************************
skipping: [node01.example.org] => (item=users)

TASK: [Users | Debian | Manage SSH authorized keys] ***************************
fatal: [node01.example.org] => subelements lookup expects a dictionary, got 'users'

FATAL: all hosts have already failed -- aborting
```

**Comment by juliedavila** [comment]
This is hitting me too

**Comment by ncadou** [comment]
Same here

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
PLAY: ***************************************************************************
TASK [test : test : debug var=foo] **********************************************
ok: [localhost] => {
    "foo": "VARIABLE IS NOT DEFINED!", 
    "changed": false
}
TASK [test : test : include] ****************************************************
skipping: [localhost] => {"skipped": true, "changed": false, "skip_reason": "Conditional check failed"}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

As you can see above, the included task is skipped, and in the current devel tasks inside the include are not expanded as they were previously (1.9.x and before). This prevents the error you're seeing from occurring, as those tasks are never evaluate.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by mbialozor** [comment]
Looks like this still persists on 2.4.1.0:
```
(root@hydra ansible)# ansible-playbook hydra.test.aero.yml --tags nfs

PLAY [hydra.test.aero] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************
ok: [hydra.test.aero]

TASK [nfs : Install NFS client package] ******************************************************************************************************************************************************************************************
skipping: [hydra.test.aero]

TASK [nfs : Start and enable NFS client service] *********************************************************************************************************************************************************************************
skipping: [hydra.test.aero]
ERROR! subelements lookup expects a dictionary, got 'None'
```

List is empty:
```
nfs_servers:
```

Role is defined as meta and controled via list status:
```
dependencies:
  - { role: nfs, tags: ['nfs', 'install'], when: nfs_servers is defined and nfs_servers }
```
